### ISSUE TITLE
Support bit64 columns

### ISSUE THREAD

**Issue by coloneltriq** [tidyverse/dplyr#1092]
group_by() doesn't appear to support integer64 columns.  I saw an [issue](https://github.com/hadley/dplyr/issues/337) from about a year ago that said that support for 64 bit integers wasn't available, but might be added.  Has anything changed in that regard?  This is a significant issue for me, as I'm dealing with a database whose index column is a 64-bit integer, and need to be able to group_by.  I'm getting around it for now using plyr::ddply, but native dplyr support would be preferable.  Example code is below:

```
iris2 <- iris
iris2$Grp <- as.integer(iris2$Species)
dplyr::group_by(iris2, Grp) %>% dplyr::summarise(Totcount=n()) # works

iris2$Grp2 <- as.integer64(iris2$Species) 
dplyr::group_by(iris2, Grp2) %>% dplyr::summarise(Totcount=n()) # doesn't work
dplyr::group_by(iris2, Grp) %>% dplyr::summarise(Totcount=n()) # doesn't work even though Grp2 isn't required

plyr::ddply(iris2, .(Grp2), nrow) # works with plyr
plyr::ddply(iris2, .(Grp), nrow) # works with plyr
```

**Comment by hadley** [comment]
Well there's not really such a thing as int64 columns in base R. We could support the bit64 package like data.table, but I'm a bit leery of the approach bit64 takes - it seems fragile in the sense that you could easily start doing things that don't make sense without warning.

**Comment by coloneltriq** [comment]
Yes, I'm using bit64's integer64 class.  Sorry for not clarifying.  

For my specific purpose, it would be sufficient to be able to group by an integer64 column, not to perform computations with them (e.g. mean).  And also to ignore/pass through the unsupported type if the offending column isn't actually used.

e.g. Using the example above, filter(iris2, Petal.Length < 3)  fails even though the integer64 column doesn't need to be evaluated by the filter.  

Would it be any easier a task if bit64 was to be partially supported for grouping columns and/or passing them through unchanged, but not necessarily for computing with them?

**Comment by ashiklom** [comment]
On a loosely related note (not sure if it deserves its own issue?), could you add an `escape` method (and possibly other relevant SQL-building function methods) for the `integer64` class? If I'm not mistaken, it should be exactly the same as the current `integer` methods.

**Comment by hadley** [comment]
@krlmlr how hard would it be to add hashing for bit64 columns?

**Comment by krlmlr** [comment]
Since they're basically numerics, it would probably mostly consist of accepting the integer64 class. But I haven't made any tests yet.

**Comment by russellpierce** [comment]
Alternatively consider the recent package https://cran.r-project.org/web/packages/VeryLargeIntegers/index.html in case someone in the future decides that 64 bit integers aren't big enough?

**Comment by romainfrancois** [comment]
part of #2432. We would just need to be careful about NA. The bits of NA_real_ are not the same as the bits of the int64 NA.

**Comment by krlmlr** [comment]
I have used handcrafted `INT64SXP`, `INTEGER64()` and `NA_INTEGER64` macros in *RSQLite* and friends to clarify intentions: https://github.com/r-dbi/RSQLite/blob/8a656cfe3f7d3103140dc9f79a1f7521e55c8049/src/integer64.h

**Comment by romainfrancois** [comment]
related to https://github.com/r-lib/vctrs/pull/122

**Comment by romainfrancois** [comment]
Seems to work now: 

``` r
library(dplyr, warn.conflicts = FALSE)
suppressPackageStartupMessages(
  library(bit64, warn.conflicts = FALSE)
)

iris2 <- iris
iris2$Grp <- as.integer(iris2$Species)
dplyr::group_by(iris2, Grp) %>% dplyr::summarise(Totcount=n()) # works
#> # A tibble: 3 x 2
#>     Grp Totcount
#>   <int>    <int>
#> 1     1       50
#> 2     2       50
#> 3     3       50

iris2$Grp2 <- as.integer64(iris2$Species) 
dplyr::group_by(iris2, Grp2) %>% dplyr::summarise(Totcount=n()) # doesn't work
#> # A tibble: 3 x 2
#>   Grp2    Totcount
#>   <int64>    <int>
#> 1 1             50
#> 2 2             50
#> 3 3             50
dplyr::group_by(iris2, Grp) %>% dplyr::summarise(Totcount=n())
#> # A tibble: 3 x 2
#>     Grp Totcount
#>   <int>    <int>
#> 1     1       50
#> 2     2       50
#> 3     3       50
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
