### ISSUE TITLE
sample_n() silently fails after group_by() %>% filter()

### ISSUE THREAD

**Issue by jaimyoung** [tidyverse/dplyr#1438]
## Background

Sample 3 rows from each cylinder group: works as expected

``` r
mtcars %>%
  group_by(cyl) %>%
  sample_n(size=3)
```
## Symptom

Sample 3 rows from only "cyl==6" group after group_by()
Expected: 3 row from cyl==6 group
Results: silently returns zero row

``` r
mtcars %>%
  group_by(cyl) %>%
  filter(cyl==6) %>%
  sample_n(size=3)
```
## Desired behavior

Give error ("desired sample size > actual rows for groups a, b, ...") and fail.
## Detours

Detour 1. ungroup()

``` r
mtcars %>%
  group_by(cyl) %>%
  filter(cyl==6) %>%
  ungroup() %>%
  sample_n(size=3)
```

Detour 2. don't group to begin with:

``` r
mtcars %>%
  filter(cyl==6) %>%
  sample_n(size=3)
```

**Comment by hadley** [comment]
Part of #341

**Comment by romainfrancois** [comment]
This is what I see now after #341 and the `slice` based reimplementation of `sample_n`: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data <- mtcars %>%
  group_by(cyl) %>%
  filter(cyl==6)

group_data(data)
#> # A tibble: 3 x 2
#>     cyl .rows    
#>   <dbl> <list>   
#> 1     4 <int [0]>
#> 2     6 <int [7]>
#> 3     8 <int [0]>

data %>%
  sample_n(size=3)
#> Error in slice_impl(.data, dots): Evaluation error: `size` must be less or equal than 0 (size of data), set `replace` = TRUE to use sampling with replacement.
```

So we do get an error, but a confusing one. Maybe we should move `sample_n` to internals instead of using `slice` and better control error messages. 

Created on 2018-05-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Can we make that error message better without rewriting `sample_n()` in C++?

**Comment by romainfrancois** [comment]
Sure. Moving it to c++ will potentially also help for #3561 I think. In the meantime I can special case what happens in `slice` when empty groups are involved.

**Comment by krlmlr** [comment]
I'm not sure this affects only empty groups, rather all cases where the group size is less than `size` and the default `replace = FALSE` is active. Maybe `sample_n()` can do a quick check on `group_data()` before invoking `slice()`?
