### ISSUE TITLE
parallel execution

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#145]
There are cases where we might be able to parallelise the execution. Of course that is hard because of how R is implemented, but when we have an expression that is completely hybrid (not sure the term is right). 

```
summarise( df, v = mean(x) )
```

There is no reason we can't calculate the means in parallel. 

The difficulty is identifying whether some expression can be run in parallel. Perhaps we'd have to include this information in a `virtual` method of `Result`.

**Comment by holstius** [comment]
+1. Milestone for 0.5?

**Comment by sfischme** [comment]
+1 as well. It would be good to have something like parallelGroupBy integrated, because right now it's an additional dependency for something that would be great in the core of dplyr

**Comment by romainfrancois** [comment]
It was never a plan to have parallelGroupBy as a dep, it was rather just an experiment. But I have some new ideas on how to do it and it might soon appear, at least as a branch on dplyr.

**Comment by kendonB** [comment]
+1

**Comment by xiaodaigh** [comment]
+1

**Comment by Alleno** [comment]
++1

**Comment by koaning** [comment]
+1 

I'm currently using Spark locally to get a performance boost to help with some of the tasks. It helps but I don't see SparkR giving me the level of flexibility that dplyr does anytime soon. I especially miss `do`, which might never make the cut.

**Comment by jwpestrak** [comment]
+1

**Comment by erickramer** [comment]
+1

**Comment by hadley** [comment]
FWIW I'm working on parallel support now - it's a higher-level approach than what I was original thinking, but I think it will be much much easier to implement.

**Comment by koaning** [comment]
is there a branch we can check out?

**Comment by sanmai-NL** [comment]
+1

**Comment by hadley** [comment]
See https://github.com/hadley/multidplyr
