### ISSUE TITLE
Duplicated columns in join get suffixes

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#148]
``` R
e <- data.frame(x = c(1, 1, 2, 3), z = 1:4)
f <- data.frame(x = c(1, 2, 2, 4), z = 1:4)

j <- inner_join(tbl_cpp(e), tbl_cpp(f), "x")
```

if the same name exists in both the x and y sources, then the variable names in the output get `.x` and `.y` added.

**Comment by rmatev** [comment]
I find the default suffixes `.x` `.y` rarely useful. Is it sensible to provide an argument "suffix" for all joins (defaulting to `c(".x", ".y")`) a la `merge()`? Or is there an easy way to do that with available tools?

**Comment by napeednus** [comment]
+1 to rmatev's comment.

The missing suffix change functionality from the joins sometimes makes me reluctantly use merge()

A fix would be great. Thanks for all your work.

**Comment by rickyars** [comment]
I agree. Would be nice to pick the suffix.

**Comment by sfirke** [comment]
One more who ended up here hoping for a suffix option.  Or a function like rename_each to pipe in before the join.

**Comment by holgerbrandl** [comment]
+1 to rmatev's comment: Having customizable suffices like for base::merge() would help a lot.

**Comment by holgerbrandl** [comment]
+1 to rmatev's comment.

**Comment by nigelhenry** [comment]
+1

**Comment by pmBarlev** [comment]
Upvote for the suffix option.
