### ISSUE TITLE
Joins should message when renaming duplicate vars

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#1791]
So you know what's going on

**Comment by krlmlr** [comment]
How can we silence this message?

**Comment by hadley** [comment]
I think a `quiet` argument would be the best option here.

**Comment by krlmlr** [comment]
Or we accept a list of known duplicates and check for a match. (This may be more convenient than explicitly renaming these columns beforehand.)

**Comment by hadley** [comment]
That would make it work more like `by` but is fairly heavy. I'll think about it.

**Comment by krlmlr** [comment]
Related: #3266.

**Comment by krlmlr** [comment]
Superseded by #3425.
