### ISSUE TITLE
Allow mutate() to choose the position of new columns

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2047]
These arguments would specify the position where the new columns are inserted, before or after some column given as index or name.

See also https://github.com/hadley/tibble/issues/99.

**Comment by krlmlr** [comment]
@hadley: What should the interface look like? Perhaps separate verbs?

**Comment by hadley** [comment]
I have no idea. I doesn't seem worthwhile to have a whole separate verb just for this, so maybe a `.where` argument to `mutate()`? 

We'll need to think through what happens when you insert variables with the same name as existing variables:

```
df <- tibble(x = 1:5, y = 1:5)
df %>% mutate(y = x * 2, .where = 0) # error?
df %>% mutate(y = x * 2, .where = 1) # overridden by existing y?
df %>% mutate(y = x * 2, .where = 2) # overrides existing y
```

**Comment by krlmlr** [comment]
That's why I suggested a new verb, which could also forbid mutating existing columns. If we call it poke(), I'll be gently reminded of my C64 past once in a while ;-)

**Comment by hadley** [comment]
I'd prefer to keep it as an argument. We can just say it applies to creating new variables, not replacing existing variable.

**Comment by krlmlr** [comment]
We could do nicer things with the new `rlang` syntax:

```r
tibble(x = 1, y = 2) %>% mutate("z" %after% "x" := 3)
```

@lionel-: Would that be parsed correctly w.r.t. operator precedence?

**Comment by lionel-** [comment]
yes because `:=` has a very low precedence (just between `~` and `<-`)

**Comment by hadley** [comment]
To me, that seems overly complicated. I think 90% of the time people just want variables to go in the front, instead of in the back.

**Comment by krlmlr** [comment]
```
df %>% mutate(y = x * 2, .to_front = TRUE)
```

would be a fair bit easier to implement than the generic solution.

**Comment by krlmlr** [comment]
Best after #2311, otherwise we'd need to change two places.

**Comment by krlmlr** [comment]
If we're only interested in supporting adding to the front, maybe we could use `transmute()`?

@lionel-: What would it take to make the following syntax work?

``` r
library(tidyverse)
tibble(a = 2, b = 3) %>% transmute(x = 1, everything())
#> Error in mutate_impl(.data, dots): Evaluation error: No tidyselect variables were registered.
```

> Created on 2018-03-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
I think mixing select and mutate semantics is going to be very challenging/risky.

**Comment by krlmlr** [comment]
Agreed, but `mutate()` and `transmute()` already seem to support select semantics, you can use just the name of an existing variable. Under the hood this is auto-naming and evaluation, but it feels like a selection. If we just supported `everything()` as a special case here?

Users might be tempted to do the following (I have no idea why the second occurrence of `Species` is discarded, feels like a bug):

``` r
library(tidyverse)
iris %>% transmute(Species, !!!.) %>% head()
#>   Species Sepal.Length Sepal.Width Petal.Length Petal.Width
#> 1  setosa          5.1         3.5          1.4         0.2
#> 2  setosa          4.9         3.0          1.4         0.2
#> 3  setosa          4.7         3.2          1.3         0.2
#> 4  setosa          4.6         3.1          1.5         0.2
#> 5  setosa          5.0         3.6          1.4         0.2
#> 6  setosa          5.4         3.9          1.7         0.4
```

> Created on 2018-03-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lionel-** [comment]
Just supporting `everything()` would be confusing I think.

**Comment by krlmlr** [comment]
Do we stick with `.to_front` then?

```r
df %>% mutate(y = x * 2, .to_front = TRUE)
```

**Comment by romainfrancois** [comment]
it's easy enough to write a mutate_front that just moves newly created to front and leaves mutated where they are: 

``` r
library(dplyr)

mutate_front <- function(.data, ...){
  old_names <- tbl_vars(.data)
  .data <- mutate(.data, ...)
  new_names <- setdiff(tbl_vars(.data), old_names)
  select(.data, new_names, everything())
}

iris %>% 
  mutate_front(
    Sepal = Sepal.Length * Sepal.Width, 
    Petal = Petal.Length * Petal.Width, 
    Petal.Length = round(Petal.Length)
  ) %>% 
  head()
#>   Sepal Petal Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1 17.85  0.28          5.1         3.5            1         0.2  setosa
#> 2 14.70  0.28          4.9         3.0            1         0.2  setosa
#> 3 15.04  0.26          4.7         3.2            1         0.2  setosa
#> 4 14.26  0.30          4.6         3.1            2         0.2  setosa
#> 5 18.00  0.28          5.0         3.6            1         0.2  setosa
#> 6 21.06  0.68          5.4         3.9            2         0.4  setosa
```

That does not really need to be in the 📦, because then we'd need `mutate_front_(at,if,all)`. 

Having it as an argument also potentially adds complexity to the scoped variants.

**Comment by krlmlr** [comment]
This is important when developing data transformation pipes: Especially after a `mutate()` the effect of the operation is difficult to see if the data has more than just a few columns. While you'd usually want the new column added to the end, you still want to double-check it manually.

I wonder if we could attach an attribute to the result of `mutate()` that changes how the resulting tibble is printed, so that we show the new data instead of existing columns. This attribute would vanish when the result is further transformed, e.g. with `select()` or `summarize()`.

Sketch:

``` r
library(tidyverse)
options(width = 60)
iris %>%
  as_tibble() %>%
  mutate(Sepal.Area = Sepal.Width * Sepal.Length)
#> # A tibble: 150 x 4
#>    Sepal.Length Sepal.Width Petal.Length | Sepal.Area
#>           <dbl>       <dbl>        <dbl> |      <dbl>
#>  1          5.1         3.5          1.4 |       17.8
#>  2          4.9         3            1.4 |       14.7
#>  3          4.7         3.2          1.3 |       15.0
#>  4          4.6         3.1          1.5 |       14.3
#>  5          5           3.6          1.4 |       18  
#>  6          5.4         3.9          1.7 |       21.1
#>  7          4.6         3.4          1.4 |       15.6
#>  8          5           3.4          1.5 |       17  
#>  9          4.4         2.9          1.4 |       12.8
#> 10          4.9         3.1          1.5 |       15.2
#> # ... with 140 more rows, and 2 more variables:
#> #   Petal.Width <dbl>, Species <fct>
```

> Composed on 2018-05-30 with the help of the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by see24** [comment]
I don't think creating an argument or function to add the new column to the front would be worth the effort. It would be much more useful to be able to use a `.before` or `.after` argument like `tibble::add_column`. For me the time when this is helpful is when I have columns that naturally group together. For example I might have columns describing the soil and then, several columns related to climate, and then columns describing the species that are present. If I use mutate to insert a new climate related column I want to be able to add it after the other climate variables. 
I don't know anything about how hard it would be to implement but I do think it would be very useful

**Comment by torfason** [comment]
Yes, I definitely second the suggestion to use `.before` and `.after`, in line with `tibble::add_column`. Using these variables, `.to_front=TRUE` is easily achieved with `.before=1`.

In terms of error handling, one could refer to the behavior of `add_column` - that function tends to be forgiving and just stuffs things at the beginning or end if an index is out of bounds, but that is an implementation decision.

In fact, I find myself using the following workaround a lot of the time, when creating new columns that logically should be close to some existing columns:

    d <- starwars %>%
        add_column(mass_modified=NA, .after="mass") %>%
        mutate(mass_modified=mass*3.14)

I realize that this workaround could be taken as an argument against implementing  `.before` and `.after` in `mutate`, but it seems like overly complicated (and many users will not know about `add_column`) for a very common use case that is 95% supported by `mutate` anyway. I'd really like to be able to type:

    d <- starwars %>%
        mutate(mass_modified=mass*3.14, .after=mass)

Being able to directly refer to column names would be a huge plus as opposed to requiring numbers (and not requiring quotes like `add_column` does would be pretty great as well).

**Comment by grayskripko** [comment]
why don't just suggest a more generic approach of handy reordering of columns that can be useful for all other cases? 

In case of a new function
```{r}
df %>%
  mutate(b = a * 2) %>%   # a b
  reorder(b, .before = a) %>%  # b a
  mutate(c = b + 1) %>%  # b a c
  reorder(c, .after = b)  # b c a
```
Name like "reorder" could be familiar for the users of data.table::setorder().

Using the preexisting functions, not obvious in my opinion
```{r}
tibble(a = 1, b = 2) %>% 
    mutate(c = 3) %>% 
    select(1:(one_of("b") - 1), last_col(), everything())  # a c b
```

**Comment by cderv** [comment]
@grayskripko for your last example you do simpler
``` r
library(dplyr, warn.conflicts = FALSE)
tibble(a = 1, b = 2) %>% 
  mutate(c = 3) %>%
  select(matches("[^b]"), b)
#> # A tibble: 1 x 3
#>       a     c     b
#>   <dbl> <dbl> <dbl>
#> 1     1     3     2
```

<sup>Created on 2018-12-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

`tidyselect` helpers can be powerful - all the more paired with regex matching using `matches`. However, reordering columns is something not so obvious in the tidyverse. A `reorder` verb can be interesting to wrap this.
FWIW, I often want to reorder column at the end of a pipe chain, not within a mutate directly, where end of table is fine for a new column, until reordering.

**Comment by romainfrancois** [comment]
I would definitely prefer a separate verb rather than making `mutate()` more complicated. The other benefit is that it can be incubated in a separate package, until we find the "right syntax"

**Comment by grayskripko** [comment]
@cderv 
as an option ```select(-b, everything(), b)```.
The idea of my example was to give an alternative to possible ```.after``` and ```.before``` arguments with ```tidyselect``` tools

**Comment by torfason** [comment]
I like the idea of reorder() with .before and .after as arguments. One can use select() relatively simply to pull a column to the front or back, but often the desired place is at the beginning or end of a logical grouping of columns, and that is pretty complicated as the examples above have demonstrated.

**Comment by lionel-** [comment]
I agree an adverb would be better than a verb, so that front- and back- variables can be created in the same mutate call.

For interested passerbys, here's a tidyeval implementation for a new `mutate_front()` verb:

```r
mutate_front <- function(.data, ...) {
  exprs <- enquos(..., .named = TRUE)
  .data <- mutate(.data, ...)

  new_vars <- syms(names(exprs))
  select(.data, !!!new_vars, everything())
}

starwars %>%
  mutate_front(
    height_m = height * 100,
    birth_year_fct = cut_number(birth_year, 4)
  )
#> # A tibble: 87 x 15
#>    height_m birth_year_fct name  height  mass hair_color skin_color
#>       <dbl> <fct>          <chr>  <int> <dbl> <chr>      <chr>
#>  1    17200 [8,35]         Luke…    172    77 blond      fair
#>  2    16700 (72,896]       C-3PO    167    75 NA         gold
#>  3     9600 [8,35]         R2-D2     96    32 NA         white, bl…
#>  4    20200 (35,52]        Dart…    202   136 none       white
#>  5    15000 [8,35]         Leia…    150    49 brown      light
#>  6    17800 (35,52]        Owen…    178   120 brown, gr… light
#>  7    16500 (35,52]        Beru…    165    75 brown      light
#>  8     9700 NA             R5-D4     97    32 NA         white, red
#>  9    18300 [8,35]         Bigg…    183    84 black      light
#> 10    18200 (52,72]        Obi-…    182    77 auburn, w… fair
#> # ... with 77 more rows, and 8 more variables: eye_color <chr>,
#> #   birth_year <dbl>, gender <chr>, homeworld <chr>, species <chr>,
#> #   films <list>, vehicles <list>, starships <list>
```

**Comment by grayskripko** [comment]
does ```tidyverse``` contain tools for handy flexible reordering of columns? Is it going to add in the future? If yes, there is no point in adding redundant functions in ```dplyr```. If both are "no", perhaps it's a good idea. As for me, I feel the lack of such functionality.

Also, I like this finding that main data processing functions ```select```, ```filter```, ```mutate``` ... have similar scoped versions that can be astonishing expressive. It looks elegant as the Periodic table of the Elements.

**Comment by lionel-** [comment]
@grayskripko I'm not suggesting to add `mutate_front()` in dplyr, just showing that it's easy to implement and can be copied in one's script utils.

I think it's better to have a `front()` adverb that can be used inside `mutate()`, though I'm not sure what interface and implementation it should have exactly. Should it return a subclassed tibble? A boxed vector? It feels connected to the issue of supporting expressions returning tibbles inside mutate.

**Comment by romainfrancois** [comment]
Anyway, any time I look at this (that happens sometimes as it lives on the last page of issues) I feel that making `mutate()` more complex is not the way to deal with this.

**Comment by romainfrancois** [comment]
Right ok 👍 having the explicit `sels()` would make it ok to mix selection and action in `transmute()`

**Comment by moodymudskipper** [comment]
I had made this `move` function and have been happily using it since then. People on SO liked it and I think its interface is close to dplyr standards. 

```
#' Move column or selection of columns
    #'
    #' Column(s) described by \code{cols} are moved before (default) or after the reference column described by \code{ref}
    #'
    #' @param data A \code{data.frame}
    #' @param cols unquoted column name or numeric or selection of columns using a select helper
    #' @param ref unquoted column name
    #' @param side \code{"before"} or \code{"after"}
    #'
    #' @return A data.frame with reordered columns
    #' @export
    #'
    #' @examples
    #' iris2 <- head(iris,2)
    #' move(iris2, Species, Sepal.Width)
    #' move(iris2, Species, Sepal.Width, "after")
    #' move(iris2, 5, 2)
    #' move(iris2, 4:5, 2)
    #' move(iris2, one_of("Sepal.Width","Species"), Sepal.Width)
    #' move(iris2, starts_with("Petal"), Sepal.Width)
    move <- function(data, cols, ref, side = c("before","after")){
      if(! requireNamespace("dplyr")) stop("Make sure package 'dplyr' is installed to use function 'move'")
      side <- match.arg(side)
      cols <- rlang::enquo(cols)
      ref  <- rlang::enquo(ref)
      if(side == "before") dplyr::select(data,1:!!ref,-!!ref,-!!cols,!!cols,dplyr::everything()) else
        dplyr::select(data,1:!!ref,-!!cols,!!cols,dplyr::everything())
    }
    

examples:
  

    iris2 %>% move(Species, Sepal.Width)
    #   Sepal.Length Species Sepal.Width Petal.Length Petal.Width
    # 1          5.1  setosa         3.5          1.4         0.2
    # 2          4.9  setosa         3.0          1.4         0.2

    iris2 %>% move(Species, Sepal.Width, "after")
    #   Sepal.Length Sepal.Width Species Petal.Length Petal.Width
    # 1          5.1         3.5  setosa          1.4         0.2
    # 2          4.9         3.0  setosa          1.4         0.2
    
    iris2 %>% move(5, 2)
    #   Sepal.Length Species Sepal.Width Petal.Length Petal.Width
    # 1          5.1  setosa         3.5          1.4         0.2
    # 2          4.9  setosa         3.0          1.4         0.2
    
    iris2 %>% move(4:5, 2)
    #   Sepal.Length Petal.Width Species Sepal.Width Petal.Length
    # 1          5.1         0.2  setosa         3.5          1.4
    # 2          4.9         0.2  setosa         3.0          1.4
    
    iris2 %>% move(one_of("Sepal.Width","Species"), Sepal.Width)
    #   Sepal.Length Sepal.Width Species Petal.Length Petal.Width
    # 1          5.1         3.5  setosa          1.4         0.2
    # 2          4.9         3.0  setosa          1.4         0.2
    
    iris2 %>% move(starts_with("Petal"), Sepal.Width)
    #   Sepal.Length Petal.Length Petal.Width Sepal.Width Species
    # 1          5.1          1.4         0.2         3.5  setosa
    # 2          4.9          1.4         0.2         3.0  setosa
```

The original SO answer:

https://stackoverflow.com/a/52096938/2270475

**Comment by hadley** [comment]
It may be worth considering that the primary reason to put variables on the left is so you can see them in the default display. It's possible that a better fix for the underlying issue would also be to show some columns on the far right (i.e. elide columns in the middle, not on the right)

**Comment by japhir** [comment]
I think it would be a very useful default to display the first and last few columns in stead of just the first few. I've had to use `options(tibble.width = Inf)` quite often recently, even though most of the time I'm only interested in the last few ones. I could use glimpse of course, but I prefer to see the actual data.

**Comment by krlmlr** [comment]
I can imagine a subclass of `"tbl_df"` that records details on the last operation:

- For `mutate()`: new columns
- For `filter()`: rows lost
- For `arrange()`: columns arranged by
- ...?

The `print()` method of that class would show details of the last operation, e.g., after `mutate()` it will try to show the new columns along with as many existing ones as possible. A `collect()` would coerce to a plain `"tbl_df".

What are the use cases where we genuinely want to control the position of the new column?

**Comment by japhir** [comment]
> What are the use cases where we genuinely want to control the position of the new column?

I think only when re-ordering data in a desired output format for export to csv or... *shudder* excel.

**Comment by see24** [comment]
For me its also when I have created a column out of some kind of
conditional on another column(s) and I want to see the result next to the
original column for comparison

**Comment by moodymudskipper** [comment]
A few more :

- One might have groups of columns that they want to be able to access with `col1:coln`, and adding a column at the end of this group is convenient
- Some functions like `base::plot` might give a special treatment to the first columns of a data.frame input.
- sort out columns of a very wide data.frame, using select helpers to group similar or numbered variables.
- Sanity checks using View
- print in markdown reports

**Comment by sibojan9** [comment]
Any update on this feature? is it implemented in the new version?

**Comment by batpigandme** [comment]
Hi @sibojan9,
We use GitHub's "magic words" to close issues, so, when it's implemented, the issue will automatically be closed by the pull request that implements it!

**Comment by sibojan9** [comment]
This means that this feature remains to be implemented?

**Comment by batpigandme** [comment]
Yes. When it's implemented, this issue will be closed.

**Comment by sibojan9** [comment]
From my end, it shows an open issue.
![image](https://user-images.githubusercontent.com/11802171/70255977-87ad9c80-173c-11ea-9676-da5990184228.png)

I tested ".before" augment on dplyr 0.7.6. It doesn't work for me.

``` r
library(tidyverse)
mpg %>% select(year,cyl,model) %>% mutate(aa=model,.before='cyl')
#> # A tibble: 234 x 5
#>     year   cyl model      aa         .before
#>    <int> <int> <chr>      <chr>      <chr>  
#>  1  1999     4 a4         a4         cyl    
#>  2  1999     4 a4         a4         cyl    
#>  3  2008     4 a4         a4         cyl    
#>  4  2008     4 a4         a4         cyl    
#>  5  1999     6 a4         a4         cyl    
#>  6  1999     6 a4         a4         cyl    
#>  7  2008     6 a4         a4         cyl    
#>  8  1999     4 a4 quattro a4 quattro cyl    
#>  9  1999     4 a4 quattro a4 quattro cyl    
#> 10  2008     4 a4 quattro a4 quattro cyl    
#> # ... with 224 more rows
```

<sup>Created on 2019-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by sibojan9** [comment]
This feature was suggested three years ago. I can hardly believe that it is still pending.

**Comment by braiam** [comment]
In MySQL we have two verbs, first and after <column>, to add a column in a table with alter. Maybe dplyr can copy that behavior?

**Comment by hadley** [comment]
I'm once again leaning towards a `.where` argument, which would use tidyselect along the lines of https://github.com/r-lib/tidyselect/issues/151.

**Comment by hadley** [comment]
Discussion of dedicated move verb at #4598

**Comment by courtiol** [comment]
This is a great feature, and perhaps it should support multiple columns relocation (the thread title is indeed _Allow mutate() to choose the position of new column**s**_):
```
iris %>%
  as_tibble() %>%
  mutate(Petal.Length.mm = Petal.Length * 10,
         Sepal.Length.mm = Sepal.Length * 10,
         .after = c(Petal.Length, Sepal.Length))
```
produces
```
# A tibble: 150 x 6
   Petal.Length Sepal.Length Petal.Length.mm Sepal.Length.mm Petal.Width Species
```
and not
```
# A tibble: 150 x 6
   Petal.Length Petal.Length.mm Sepal.Length Sepal.Length.mm Petal.Width Species
```

**Comment by lionel-** [comment]
@courtiol Your suggestion would not work with plural selections like `starts_with()` or `is.numeric`.

**Comment by courtiol** [comment]
I agree @lionel-, but it would make sense in mutate() calls without suffix (as shown above), wouldn't it?
Perhaps for `mutate_if()` and `mutate_at()` a possibility would be to consider a `.before = .x` (or `.after = .x`) to imply that each newly created column goes before (or after) its source.
