### ISSUE TITLE
take advantage of chaining

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#205]
e.g. with code like this: 

```
Batting %.%
  group_by(playerID) %.%
  summarise(total = sum(R)) %.%
  arrange(desc(total)) %.%
  head(5)
```

why would we have to create the full data with `arrange` when we extract the top 5 rows right after. perhaps we can identify that we don't need to.

**Comment by matthieugomez** [comment]
filter(id==1) %>% summarize(id)

is a good example too.
