### ISSUE TITLE
Grouping by character very slow

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2198]
for data frames. Are we hashing strings or string pointers? This might explain the vast difference (~2 orders of magnitude!)

```
lll <- sample(c(letters[1:10], "-"), 1e6, replace = TRUE) %>% paste(collapse = "") %>% gsub("--+", "-", .)
ll <- strsplit(lll, "-")[[1]]

system.time(
  tibble::enframe(ll) %>%
    dplyr::group_by(value)
)
## 0.7 seconds

system.time(sum(duplicated(ll)))
## 0.004 seconds
```

**Comment by romainfrancois** [comment]
@krlmlr IIRC we are hashing the pointers, but there might be something to deal with encodings, e.g. when two strings are supposed to be equal but don't have the same pointer because of encoding

**Comment by krlmlr** [comment]
The code appears to be calling `base::sort()` twice. Apart from removing the second call, we could use `sort(method = "radix")`, which works best if all values are UTF-8 (but sorts only in the C locale, which may or may not be desired).

```r
system.time(
  sort(ll, method = "shell")
)
## 0.25 seconds
```
