### ISSUE TITLE
Performance regressions

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2220]
From [https://github.com/krlmlr/dplyr.benchmark](https://github.com/krlmlr/dplyr.benchmark):

![perf](https://cloud.githubusercontent.com/assets/1741643/19835288/756a0342-9e81-11e6-91b2-4204ed73123d.png)
## Recent regressions:
- [x] filter() (see also https://github.com/hadley/dplyr/commit/d1c91f3c2a4f54ff31662b8e36c6a225c029d33b#commitcomment-19602027)
- [x] mutate2

## Older regressions
- [ ] mutate
- [ ] summarise_mean and summarise_mean_reg
- [ ] windowed

Looks like these were introduced here: https://github.com/hadley/dplyr/compare/36911e5aad94f0207eeea0d81875d65442a449d3...c0b28a9

**Comment by romainfrancois** [comment]
I'm going to close this now as this is very unclear what the success criteria is.
