### ISSUE TITLE
Encapsulate and fix argument matching in hybrid evaluator

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2299]
A class that allows walking through the list of arguments.

```c++
class ArgMatcher {
public:
  ArgMatcher(Language call_, const char* prototype_fun, const char* package = NULL) : ... {}

public:
  SEXP match_next_arg(const char* name);
  bool has_more_args() const;

private:
  Language call;
  Function prototype;
}
```

https://github.com/hadley/dplyr/pull/2298#discussion_r91424933

**Comment by hadley** [comment]
I think it would probably be slightly better to convert to a `map< std::pair<std:string, SEXP> >` up front.

**Comment by hadley** [comment]
This class could also (optionally) do the constant folding.

**Comment by krlmlr** [comment]
Constant folding: good idea. Not sure about the map -- none of the hybrid functions need random access, and the order is correct after `match.call()`.

**Comment by hadley** [comment]
They need an easy way to check if an argument is used, and it would decouple from the order of the function in R (although that would require changing the 2nd arg to `Environment Env` and then looking up the function def dynamically)

**Comment by krlmlr** [comment]
Why would we want to decouple from R's declaration? Do you prefer avoiding `match.call()`?

**Comment by hadley** [comment]
With this construction we need two definitions: one in R and one in this call. (I think decouple might've been the wrong word)

**Comment by romainfrancois** [comment]
This is what the `Expression` class is doing now.
