### ISSUE TITLE
Properly specify and implement hybrid evaluation for summary variables

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2312]
See e.g. #1434; hybrid evaluation usually doesn't make much sense here, we can (and should) safely fall back to regular evaluation.

**Comment by hadley** [comment]
But don't you still need it for things like `first(x) - last(x)` or `min(x) - max(x)`?

**Comment by krlmlr** [comment]
This is perhaps more about hybrid optimization (terminology?). We should perhaps distinguish internally between handlers for summarize() and handlers for mutate().

**Comment by krlmlr** [comment]
Still not fixed in #3526, a code search for `is_summary` helps finding the instances.

https://github.com/tidyverse/dplyr/pull/3799/files#r215957353

https://github.com/tidyverse/dplyr/pull/3799/files#r215955331

**Comment by krlmlr** [comment]
Hybrid handlers shouldn't be used when a summary variable is involved.

**Comment by romainfrancois** [comment]
Fair enough, this should further simplify some code too. Smaller pr in a few days.
