### ISSUE TITLE
All error messages should mention the affected column(s)

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2448]
https://github.com/hadley/dplyr/pull/2425#discussion_r102037470

**Comment by hadley** [comment]
Includes #2367 and #2438

**Comment by hadley** [comment]
And should not include the uninformative call site.

**Comment by hadley** [comment]
Also need to make sure that we're setting the call to `R_NilValue()` since it usually does not provide information that is helpful to the user.

**Comment by krlmlr** [comment]
@hadley: I identified ~60 calls to `stop()` where a column name is missing, of which ~40 have no associated test. Okay to tackle only the tested calls, and leave the others for later (perhaps after #2311 and a round of coverage improvement)?

To remove the call site for C++ calls, we can tweak `exception_to_r_condition()` in `RcppExport.cpp` (via the `END_RCPP` macro). The function itself is provided by Rcpp, but I guess we can use some preprocessor hacks in `dplyr_types.h`.

**Comment by krlmlr** [comment]
I'll double-check the linked issues, too.

**Comment by hadley** [comment]
Sounds good.

**Comment by krlmlr** [comment]
@hadley: What formatting do we use for column names, classes, and function names? Currently, the preference seems: `'column'`, `class`, `function_name`. Should we be using backticks, double quotes, and trailing parentheses instead: `` `column` ``, `"class"`, `function_name()`? Please advise.

**Comment by hadley** [comment]
I think:

* `` `column` ``
* Class can usually be bare, `` `x` is not a vector ``
* I think I usually put functions in backticks too `` `between()` needs numeric inputs ``
