### ISSUE TITLE
Foreign UTF-8 characters on non-UTF-8 locales

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2471]
https://github.com/hadley/rlang/pull/43 will provide a lossless symbol → string → symbol roundtrip by converting all `"<U+xxxx>"` sequences in symbols *and* names to UTF-8. (If a symbol or name contains such a sequence, it is always interpreted as the corresponding UTF-8 codepoint.) To be consistent with this, dplyr only needs to:

- [ ] use `rlang::names2()`, or the equivalent C entry point, when querying column names
- [ ] always return UTF-8 column names

**Comment by krlmlr** [comment]
@hadley @lionel-: We're currently nowhere near good support for alien variable names. This is in a Latin-1 locale on Windows:

``` r
library(rlang)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

x <- data.frame(a = 1:3, b = 4:6)
names(x)[[1]] <- "\u5e78"
x
#>   <U+5E78> b
#> 1        1 4
#> 2        2 5
#> 3        3 6

x %>% filter(`<U+5E78>` > 1)
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in filter_impl(.data, quo): variable '<U+5E78>' not found
x %>% filter((!!sym("\u5e78")) > 1)
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in filter_impl(.data, quo): variable '<U+5E78>' not found
x %>% filter(.data$"\u5e78" > 1)
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in filter_impl(.data, quo): variable '<U+5E78>' not found
x %>% filter(.data[["\u5e78"]] > 1)
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in filter_impl(.data, quo): variable '<U+5E78>' not found
x %>% filter((!!sym("\u798f")) > 1)
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in filter_impl(.data, quo): object '<U+798F>' not found
x %>% arrange(`<U+5E78>`)
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in arrange_impl(.data, dots): variable '<U+5E78>' not found
x %>% arrange(-!!sym("\u5e78"))
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in arrange_impl(.data, dots): variable '<U+5E78>' not found
x %>% arrange(-.data$"\u5e78")
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in arrange_impl(.data, dots): variable '<U+5E78>' not found
x %>% arrange(-.data[["\u5e78"]])
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in arrange_impl(.data, dots): variable '<U+5E78>' not found
x %>% arrange(-!!sym("\u5e78"))
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in arrange_impl(.data, dots): variable '<U+5E78>' not found
x %>% arrange(-!!sym("\u798f"))
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in arrange_impl(.data, dots): object '<U+798F>' not found
x %>% mutate(!!sym("\u798f") := -!!sym("\u5e78"))
#> Warning: Mangling the following names: <U+5E78> -> <U+5E78>. Use
#> enc2native() to avoid the warning.
#> Error in mutate_impl(.data, dots): variable '<U+5E78>' not found
```

This can also be replicated on Ubuntu (and probably OS X), though only line by line:

``` r
library(rlang)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

x <- data.frame(a = 1:3, b = 4:6)
names(x)[[1]] <- "\u5e78"
Encoding(names(x)) <- "UTF-8"
x
#>   幸 b
#> 1  1 4
#> 2  2 5
#> 3  3 6

withr::with_collate(
  "en_US.ISO8859-1",
  {
    x %>% filter(`<U+5E78>` > 1)
    x %>% filter((!!sym("\u5e78")) > 1)
  }
)
#> Error in filter_impl(.data, quo): object '<U+5E78>' not found
```

I'll try to fix it before release, but this might require changes to rlang.

**Comment by krlmlr** [comment]
@lionel-: I'll be looking into encoding issues on Windows soon, when do you plan to release rlang?

**Comment by lionel-** [comment]
I sent it yesterday. Do you need more changes?

**Comment by krlmlr** [comment]
For some reason I assumed that I could write the same code in RStudio's REPL and in an UTF-8 encoded source file. This was short-sighted: I can run code like `tibble("幸" := 1:3, "福" := letters[1:3])`, or even just `"幸"` in the REPL but not from an R script. It seems that `parse()` translates the entire input to native, and `source(encoding = "UTF-8")` seems completely broken (reprex below).

So, to make foreign UTF-8 characters accessible to users, we'd first need to use a better `source()` call in the RStudio IDE. And then we need to treat `"<U+xxxx>"` and the corresponding code point as equivalent for name lookup, in both tibble and dplyr. Is it safe to use `.Call("rlang_unescape_character", "<U+7986>", PACKAGE = "rlang")` from tibble and dplyr?

## Broken `source()`

```r
# Use one of the following:
id <- "Gl\u00fcck"
id <- "\u5e78\u798f"
id <- "\u0441\u0447\u0430\u0441\u0442\u044c\u0435"
id <- "\ud589\ubcf5"

file_contents <- paste0('"', id, '"')
Encoding(file_contents)
#> [1] "UTF-8"
raw_file_contents <- charToRaw(file_contents)

path <- tempfile(fileext = ".R")
writeBin(raw_file_contents, path)
file.size(path)
#> [1] 8
length(raw_file_contents)
#> [1] 8

source(path, encoding = "UTF-8")
#> Warning in source(path, encoding = "UTF-8"): invalid input
#> found on input connection 'C:\Users\muelleki\AppData\Local\Temp
#> \RtmpCQRp30\filebac19e7f01.R'
#> Error in source(path, encoding = "UTF-8"): C:\Users\muelleki\AppData\Local\Temp\RtmpCQRp30\filebac19e7f01.R:1:1: unexpected INCOMPLETE_STRING
#> 1: "
#>     ^
```

**Comment by hadley** [comment]
cc @yihui @kevinushey 

I guess Chinese R users on windows don't currently write their scripts in UTF-8?

**Comment by yutannihilation** [comment]
> I guess Chinese R users on windows don't currently write their scripts in UTF-8?

I don't know if this is a popular practice among CJK people, but I usually write scripts in UTF-8 since it is easier to share them with users on other OS. (I've never pushed "Source" button for UTF-8 scripts on RStudio for years, though...)

> a better `source()` call in the RStudio IDE.

This worked:

```r
source(file(path, encoding = "UTF-8"), echo = TRUE)
#> 
#> > "행복"
#> [1] "<U+D589><U+BCF5>"
```

**Comment by krlmlr** [comment]
@yutannihilation: Thanks, this is very valuable information. Which version of R are you using?

**Comment by yihui** [comment]
I don't have time to help you at the moment, but this hole on Windows is pretty darn deep. Here is one of the ugly tricks I used before in shiny: https://github.com/rstudio/shiny/blob/06c75dd65/R/utils.R#L1498-L1505 I have no idea if it still works, or anything has changed in base R. The pain is that `source(encoding = 'UTF-8')` cannot just work. It depends on whether the native system encoding supports all characters in the file, and certain (regional/language) settings in the control panel of Windows.

**Comment by yutannihilation** [comment]
@krlmlr Thanks. I'm using R 3.4.0. Should I try with another version? 

Here's my session info:
```r
devtools::session_info(pkgs = "base")
#> Session info ------------------------------------------------------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.0 (2017-04-21)
#>  system   x86_64, mingw32             
#>  ui       RStudio (1.0.143)           
#>  language (EN)                        
#>  collate  Japanese_Japan.932          
#>  tz       Asia/Tokyo                  
#>  date     2017-05-09                  
#> 
#> Packages ----------------------------------------------------------------------------------------------------------------
#>  package * version date       source
#>  base    * 3.4.0   2017-04-21 local 
```

**Comment by krlmlr** [comment]
I can confirm that the reprex works on my Latin-1 Windows system when I use the Latin-1 version of the string (`"Glück"`). This is so much unexpected that I haven't even checked, and the documentation of the `encoding` argument to `source()` doesn't mention this.

Anyway, this seems to mean that this issue is still blocked. I'll submit to R-devel.

**Comment by aakhmetz** [comment]
Sorry for disturnbing, but no update on this issue? Thank you and sorry again

**Comment by krlmlr** [comment]
@kevinushey: Is *io* going to support a better `source()` function?

**Comment by krlmlr** [comment]
Thanks for the detailed reply! Is the RStudio IDE doing "the right thing" on Windows now? Or would it need to wait for *io*? (I remember this was the reason why this issue is blocked now, but I haven't looked for some time.)

We hand-format everything for tibbles in *pillar* now, so (hopefully) no encoding issues apart from inevitable ones. The *utf8* package does some heavy lifting, too.

**Comment by kevinushey** [comment]
Unfortunately, RStudio's handling of encodings on Windows is not great -- we also inadvertently roundtrip strings through the native encoding on occasion -- but we're trying to tackle these issues as they come up + time permitting.

**Comment by hadley** [comment]
@romainfrancois can you please take a look at this one again too?

**Comment by romainfrancois** [comment]
IIUC most of the issue now lives in the `DataMask` class, when the active bindings are created: 

``` r
library(rlang)
e <- env()
bindings <- set_names(list(function() 42),  "<U+5E78>")
env_bind_active(e, !!!bindings)
names(bindings)
#> [1] "<U+5E78>"
env_names(e)
#> [1] "幸"
e[["\u5e78"]]
#> [1] 42
e[["<U+5E78>"]]
#> NULL
eval_bare(sym("\u5e78"), e)
#> [1] 42
eval_bare(sym("<U+5E78>"), e)
#> Error in eval_bare(sym("<U+5E78>"), e): object '<U+5E78>' not found
```

`<U+5E78>` is promoted to utf-8 as `幸` in the names of the bindings, but then `<U+5E78>` no longer stands for the same thing.

**Comment by krlmlr** [comment]
I think UTF-8 handling on Windows now is as good as it gets, and it no longer seems a dplyr issue (rather a vctrs/rlang one if any). These things will be a non-issue with the UCRT builds, I hope. Closing.

We still might benefit from `brio::source()` though.
