### ISSUE TITLE
Extract select_var and helpers

### ISSUE THREAD

**Issue by topepo** [tidyverse/dplyr#2539]
`is_negated`, `set_current_info`, `deparse_trunc `, and `combine_vars` are used inside of `select_vars`. To emulate that code in other packages, these would need to be exported. 

Thanks

**Comment by hadley** [comment]
Can you give me a bit more context for where you need this in recipes? I'm now thinking I'm not going to have time to carefully separate this out for the next dplyr release, so we'll need some interim patch.

**Comment by topepo** [comment]
I created a [function](https://github.com/topepo/recipes/blob/master/R/selections.R#L209) that emulates `select_vars` (I can't reuse that function since recipes search for names, role, or data types). Since the function also selects variables by name, it uses `set_current_vars` to get the current variable names, etc. 

I can create copies of these functions in recipes (they mostly aren't complicated) but that's obviously a bad idea.

**Comment by hadley** [comment]
How urgently do you need this? If it can wait a couple of weeks more, we'll pull these functions out into a separate package.

**Comment by krlmlr** [comment]
Does tidyselect solve the original request?

**Comment by topepo** [comment]
It has been resolved.
