### ISSUE TITLE
Make sure that all verbs can be used with column names with foreign encoding

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2553]
`group_by()` example:

``` r
library(dplyr, warn.conflicts = FALSE)
tibble(a = 1) %>% rename("\u5e78" := a) %>% group_by(`<U+5E78>`)
#> Error in grouped_df_impl(data, unname(vars), drop): unknown column '<U+5E78>'
```

@lionel-: Is there perhaps a way to use `!!` or `!!!` with a string constant?

**Comment by lionel-** [comment]
> Is there perhaps a way to use !! or !!! with a string constant?

I'm not sure I understand the question. Are you looking for:

```r
data_frame(a = 1) %>% rename(!! sym("\u5e78") := a) %>% group_by(`<U+5E78>`)
```

which should already work with latin1 locales?

**Comment by krlmlr** [comment]
The `rename()` works already with my syntax, I'm having trouble getting `group_by()` to work. Any ideas?

**Comment by lionel-** [comment]
> The rename() works already with my syntax

I'm not sure I understand the context of what you're doing here. You're in a non-UTF-8 locale, and you're using `:=` to avoid conversion to native encoding is that it? And the purpose is to test what would happen when the user unquotes a symbol with serialised unicode?

**Comment by krlmlr** [comment]
I'm in a non-UTF-8 locale and trying to `group_by()`.

**Comment by lionel-** [comment]
I guess that's the dilemma of handling strings in the native encoding or in UTF-8 in verbs backends.

Should we maintain the data frame names in UTF-8, then convert symbols to UTF-8 strings in the backends before any processing? Latin1 Windows users can display UTF-8 strings properly right, so it wouldn't affect their workflow to have the df names in UTF-8?

**Comment by krlmlr** [comment]
Yes, I think dplyr should be calling `unescape_sexp()` all over the place (not only for converting error messages to UTF-8). A C entry point would be very welcome.

R handles strings with proper encoding mark very well, so it shouldn't make a difference to the user if a string is in UTF-8 or in the native locale. I have found that in a UTF-8 locale strings are not always marked as UTF-8, and I wonder if we can entirely avoid different code paths for UTF-8 and non-UTF-8 locales.

**Comment by lionel-** [comment]
> A C entry point would be very welcome.

Indeed. Should it be called `chr_parse_unicode()`?

**Comment by krlmlr** [comment]
I have struggled to find a name/verb for this particular escaping mechanism. Perhaps chr_demangle_unicode()? Something that applies exclusively to the transform between "<U+xxxx>" and unicode character.

**Comment by lionel-** [comment]
I slightly prefer `parse` than `demangle` because it's a bit shorter

**Comment by pgensler** [comment]
@lionel- & @krlmlr 
Not to budge into your conversation, but I wanted to comment on some issues I've been encountering recently with encoding that I think apply to this issue:

Is there any way we get more documentation around how file encoding should work in the tidyverse/dplyr in general? Should we be force converting the encoding for a file before reading a file into dplyr and working with it? I have a txt file where before I can even make it workable for analysis, I need to force convert it to UTF-8 with iconv in bash to make it readable in R.

I've been working with some files that I've had some real issues with even simply reading in with readr, and will fail almost instantly, thus making encoding a real issue (not to downplay your issue at hand here) . I think this would be helpful to get clarification, especially for issues like this, as I have never been able to read in a file unless it is UTF-8 encoded. Once I have, I've gotten the unicode characters as hexadecimals: "<U+xxxx>" , and using stringi/textclean to convert text to proper codes, and proceed.

Below is an example file, that illustrates these encoding issues.
[cellartracker-10records.txt](https://github.com/hadley/dplyr/files/874438/cellartracker-10records.txt)

**Comment by lionel-** [comment]
> Should we be force converting the encoding for a file before reading a file into dplyr and working with it?

No, but your character data should have either:

- An UTF-8 or latin1 encoding tag (you can check with `Encoding()`, note that ASCII strings never have encoding tags).
- No encoding tag, in which case it is expected to be encoded in your locale codeset.

If the encoding tag is not correctly specified you'll get problems in R. To make sure data is correctly encoded _and_ has the correct encoding mark, you have to make sure the reading function knows the encoding of your input file. It might assume UTF-8 by default.

Note that R on Windows is buggy regarding encoding. For example data frames might not display properly while individual character vectors will. These are display bugs, so if your character vectors are properly encoded you should not suffer data loss.

Things get tricky when strings are converted to symbols because the latter only support the locale encoding, and it might not be able to handle all characters (e.g. latin1 can only represent very few characters). Unrepresentable characters are converted by R to the ASCII text `<U+xxxx>`. We are trying to solve this issue by unserialising those tags automatically during `symbol → string` conversions.

**Comment by hadley** [comment]
@pgensler that file has special characters encoded in html style, so is not a good example.  Also this is totally side tracking an important discussion so I'm deleting these comments.

**Comment by k1moradi** [comment]
All Unicode names get converted to <U+....>, which should not happen in the first place.

**Comment by romainfrancois** [comment]
Is this still an issue @krlmlr ?

**Comment by k1moradi** [comment]
Yes. in as much as I know.

**Comment by krlmlr** [comment]
Thanks. The reprex now works for me.

@k1moradi: The conversion to `<U+....>` is a feature of R on Windows, we can't do anything about it in _dplyr_, only work around.
