### ISSUE TITLE
Add rolling-window functionality

### ISSUE THREAD

**Issue by iangow** [tidyverse/dplyr#2593]
This was first discussed in #2586. As discussed [here](https://cran.r-project.org/web/packages/dplyr/vignettes/window-functions.html) *using NZ spelling at time of writing*, there are three types of windows:

- Recycled: e.g., `BETWEEN UNBOUND PRECEDING AND UNBOUND FOLLOWING`
- Cumulative: e.g., `BETWEEN UNBOUND PRECEDING AND CURRENT ROW`
- Rolling: e.g., `BETWEEN 2 PRECEDING AND 2 FOLLOWING`

`dplyr` currently supports the first two, but not the third. This request is for some support for rolling windows.

For example,

```r
df %>%
  select(gvkey, datadate, ni) %>%
  mutate(
    ni_sum = over(
      sum(ni), 
      partition = gvkey, 
      order = datadate, 
      range = c(-1, 0)
    )
  )
```

Ideally, `over()` would inherit the grouping and ordering implied by `group_by()` and `arrange()` so one could do something like:

```r
df %>%
  select(gvkey, datadate, ni, sale, cogs, sga) %>%
  group_by(gvgkey) %>%
  arrange(datadate) %>%
  mutate(
    sale_ttm = over(sum(sale), range = c(-3, 0)),
    cogs_ttm = over(sum(cogs), range = c(-3, 0)),
    sga_ttm = over(sum(sga), range = c(-3, 0))
  )
```

**Comment by hadley** [comment]
I thought this going to be trivial, but I have to somehow suppress the default window-ness of `sum()` etc, if called inside `over()`.

**Comment by hadley** [comment]
One possible definition is this:

```
  over = function(x, partition = NULL, order = NULL, frame = NULL) {
    win_over(
      x,
      partition = partition %||% win_current_group(),
      order = order %||% win_current_order(),
      frame = frame
    )
  }
```

But it only works with new aggregation functions because `mean()` etc are already wrapped in the over call. 

Another option would be to make it just override the default partition, order, and frame, but then it wouldn't work with custom aggregation functions.
