### ISSUE TITLE
Problems uploading to ubuntu

### ISSUE THREAD

**Issue by pssguy** [tidyverse/dplyr#262]
Hi
 Trying to install dplyr on an AWS instance. assertthat and BH unpack fine but with dplyr I get message that it has successfully unpacked and MD5 sums checked but then I get 
*\* libs
g++ -I/usr/share/R/include -DNEDBUG  etc.... and the system hangs

in the usr/local/lib/R/site-library there is now a file 00LOCK-dplyr

**Comment by paul4forest** [comment]
kevinushey's answer above didn't work on my VPS. Matt Lacey posted [How to compile dplyr on low memory VPS ](http://lacey.se/posts/compiling-dplyr-on-low-memory-vps/). He mannaged to install dplyr by adding a larger swap space. Unfortunately this operation is not permitted on my system:  "swapon failed: Operation not permitted". But enlarging the swap size sounds like a way to install dplyr on low memory systems.

**Comment by rafaveguim** [comment]
I couldn't install in my DigitalOcean droplet with 512MB RAM. It failed even after upgrading it to 1GB RAM. What solved the problem for me was changing temporaily the default R compiler from `g++` to `clang`. On my Fedora 24, the config file is located at `/usr/lib64/R/etc/Makeconf`. 

Comment the following lines:
```
CC = gcc -m64
CXX = g++ -m64
```

And add the following:
```
CC = clang
CXX = clang++
```
