### ISSUE TITLE
Functions in `dbplyr` not exposed by `dplyr`

### ISSUE THREAD

**Issue by iangow** [tidyverse/dplyr#2620]
To make the following code work with the current development version of `dplyr`, I need to say `dbplyr::sql` or have `library(dbplyr)`. Is this intended behaviour?

``` r
library(dplyr, warn.conflicts = FALSE)

pg <- src_postgres()

filers <- tbl(pg, sql("SELECT * FROM whalewisdom.filers"))
#> Error in inherits(x, "sql"): could not find function "sql"
```

Relatedly, if I don't have `dbplyr` installed and install `dplyr` (`devtools::install_github("hadley/dplyr", force = TRUE)`), it appears that `dplyr` assumes the presence of `dbplyr` without having it installed:

``` r
library(dplyr, warn.conflicts = FALSE)

pg <- src_postgres()
#> Error in loadNamespace(name): there is no package called 'dbplyr'

filers <- tbl(pg, sql("SELECT * FROM whalewisdom.filers"))
#> Error in tbl(pg, sql("SELECT * FROM whalewisdom.filers")): object 'pg' not found
```

**Comment by hadley** [comment]
`src_postgres()` starts with:

```R
check_dbplyr()
check_pkg("RPostgreSQL", "connect to PostgreSQL")
```

So it's definitely supposed to be checking. Are you sure you have the latest version?

**Comment by hadley** [comment]
I agree that we dplyr should re-export `sql()`

**Comment by iangow** [comment]
The first issue above definitely appears with the current issue. The second one is created by just installing `dplyr` by itself. (I just saw your latest comment after typing this.)

**Comment by hadley** [comment]
Oh oops, just noticed a stupid typo

**Comment by lionel-** [comment]
Should also reeport `src_desc`:

```
* installing *source* package 'bigrquery' ...
** package 'bigrquery' successfully unpacked and MD5 sums checked
** R
** preparing package for lazy loading
Error : object 'src_desc' is not exported by 'namespace:dplyr'
ERROR: lazy loading failed for package 'bigrquery'
```

**Comment by lionel-** [comment]
And `src_sql()`.

Also I see this NOTE in RPresto:

```
* checking dependencies in R code ... NOTE
Missing or unexported objects:
  ‘dplyr::base_agg’ ‘dplyr::base_scalar’ ‘dplyr::base_win’
  ‘dplyr::build_sql’ ‘dplyr::ident’ ‘dplyr::sql’ ‘dplyr::sql_prefix’
  ‘dplyr::sql_translator’ ‘dplyr::sql_variant’ ‘dplyr::src_sql’
  ‘dplyr::tbl_sql’
```

**Comment by hadley** [comment]
Given that there are only a handful of packages that need these functions and they clearly belong in dbplyr, I think we can just suggest to package authors that use something like:

```R
if (packageVersion("dplyr") > 0.6.0) {
  check_dbplyr()
  getExportedValue("dbplyr", "base_agg")
} else {
 getExportedValue("dplyr", "base_agg") 
}
```

And we could export something to make that friendlier, like:

```
base_agg <- dbplyr_compat("base_agg")
```

Although that would have to be executed at run-time, not build-time.

**Comment by hadley** [comment]
`sql()` is a trickier option. I think since most people will not attach dbplyr, it's ok to do

```
sql <- function(...) {
  check_dbplyr()
  dbdplyr::sql(...)
}
```

You'll get a warning about conflicts if you attach both, but it won't affect code. 

We can't re-export `sql()` because that would require dplyr to import dbplyr.
