### ISSUE TITLE
[bug] convert a character column to numeric type with tibble type dataframe

### ISSUE THREAD

**Issue by sibojan** [tidyverse/dplyr#2625]
It says **Error: (list) object cannot be coerced to type 'double'**.  It won't cause any issue with conventional data.frame instead of **data_frame.**

> aframe <- data_frame(a1= 1:5, a3=c(1,'e',3,'e','d'))
>  
>  as.numeric( aframe[,2]   )
**Error: (list) object cannot be coerced to type 'double'**
>  
>   aframe <- data.frame(a1= 1:5, a3=c(1,'e',3,'e','d'))
>  
>  as.numeric( aframe[,2]   )  
[1] 1 4 2 4 3                   **(no issues here)**

**Comment by lionel-** [comment]
that's because subsetting a tibble with `[` always yield a tibble, never a vector. Use `[[` instead: `aframe[[2]]` to get a vector.

**Comment by sibojan** [comment]
Thank you for the clarification.
