### ISSUE TITLE
`bind_cols(NULL)` crashes R

### ISSUE THREAD

**Issue by strengejacke** [tidyverse/dplyr#2630]
I found this issue when using `bind_cols()` inside an own function, which binds arguments passed by `...` to `bind_cols()`. If no arguments are specified for `...`, the dots are `NULL`, which leads to the crash when calling `bind_cols(...)`. Of course I will fix this issue in my function, but I thought it might be interesting for you as well, to throw a warning or an error when passing `NULL` to `bind_cols()`.

```r
bind_cols(NULL)
```

**Comment by lionel-** [comment]
I cannot reproduce on master. I've added an unit test for this case: https://github.com/tidyverse/dplyr/commit/0eceb997196f43642d5af977b14a4ef1882b1ee7

**Comment by strengejacke** [comment]
Just checked it on the dev-version, and indeed bind_cols now returns an empty data frame:

```
dplyr::bind_cols(NULL)
#> data frame with 0 columns and 0 rows
```
