### ISSUE TITLE
summarize-defined columns in lists

### ISSUE THREAD

**Issue by wkostelecki** [tidyverse/dplyr#2632]
Problem in dplyr 0.5.0 when using summarize-defined column in list.
Sorry, I couldn't get the github::install_github to build the latest dplyr and check if this has already been fixed.

```r
library(dplyr)
library(testthat)
df = mtcars %>%
  group_by(cyl) %>%
  summarize(x = min(cyl), y = list(x), z = x)

expect_equal(df[["y"]], list(2, 4, 8))
expect_false(identical(df[["y"]], list(8, 8, 8)))
```

**Comment by lionel-** [comment]
The list-column is properly handled but this fails: `summarise(group_by(mtcars, cyl), x = 1, z = x)`
