### ISSUE TITLE
Converting strings to columns

### ISSUE THREAD

**Issue by MrFlick** [tidyverse/dplyr#2662]
Many times you may get a list of columns as strings (for example from a shiny interface or as command parameters passed to Rscript). With pre 0.6 one might do

```
cols <- c("am","gear")
mtcars %>%
  group_by_(.dots=cols) %>%
  summarise(mean_cyl=mean(cyl))
```

If the `group_by_` function is being deprecated , what's the best way to work with columns as strings? So far this seems to work

```
cols <- c("am","gear")
grouping_vars <- rlang::parse_quosures(paste(cols, collapse=";"))
mtcars %>%
  group_by(!!!grouping_vars) %>%
  summarise(mean_cyl=mean(cyl))
```

But it seems a bit clumsy to me. Am I missing a function that can help with this?

**Comment by hadley** [comment]
`rlang::syms()`
