### ISSUE TITLE
dplyr no longer picks up verb_ methods

### ISSUE THREAD

**Issue by edzer** [tidyverse/dplyr#2664]
In the following example:
```r
library(sf)
library(dplyr)
nc = st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
nc %>% filter(AREA > .1) %>% class()
# [1] "data.frame"
```
the output used to be `"sf"  "data.frame"` rather than `"data.frame"`, because `filter` (not a generic) would call `filter_`, for which package `sf` provides a method:
```r
methods(filter_)
# [1] filter_.data.frame* filter_.sf          filter_.tbl_cube*  
# [4] filter_.tbl_df*    
# see '?methods' for accessing help and source code
```
With the new dplyr, this no longer works, indicating a backward incompatibility.

**Comment by hadley** [comment]
@lionel- can you please double check your implementation of the default methods?

**Comment by lionel-** [comment]
The `.default` method sends objects to the old underscored versions, but if the object inherits from `data.frame` that won't be the case. Should we try to handle this with some ad hoc dispatching?

**Comment by lionel-** [comment]
hmm I think I see a general way of handling this while avoiding infinite dispatch recursion, I'll try it on Monday.

By the way, should we start sending bare `data.frame` to the `tbl_df` methods? I've wished for automatic promotion to tibble ever since I started using dplyr.

**Comment by edzer** [comment]
@lionel- yes if you want to enforce tibbles on those who are happy with data.frames, no if you want to be backward compatible. I'm in favor of giving users that choice, also there will be a lot of packages that assume objects behave exactly like data.frames, rather than similar to data.frames.

**Comment by lionel-** [comment]
yeah I guess the moment tibbles started behaving a bit different than data frames, rather than just having a nicer print method, is the moment we gave up that option.

**Comment by lionel-** [comment]
Hi @edzer,

It looks like the best option is to provide a non-underscored method in the next version of your package. Otherwise we need to complicate our dispatch mechanism.

**Comment by hadley** [comment]
@edzer we'll have a vignette that explains this shortly, and you'll receive an official revdep email later today.

**Comment by edzer** [comment]
OK, thanks!

**Comment by edzer** [comment]
One more question regarding 0.5 compatibility; `sf` tries to make geometry sticky, and this used to work with `select_.sf`:
```r
> sf:::select.sf
function (.data, ..., .dots = NULL) 
{
    .dots <- c(.dots, attr(.data, "sf_column"))
    ret = NextMethod()
    structure(ret, agr = st_agr(ret))
}
```
but no longer does because the `.dots` arg has been dropped in the `select` generic. Any idea how I can make this work under the new dplyr?

**Comment by lionel-** [comment]
I think the simplest way is to dispatch manually to the next method:

```r
unclass_sf <- function(x) {
  i <- match("sf", class(x))
  class <- class(x)[-seq_len(i)]
  structure(x, class = class)
}

select.sf <- function(.data, ...) {
  .data <- unclass_sf(.data)
  sf_column <- attr(.data, "sf_column")

  ret <- select(.data, ..., !! sym(sf_column))
  structure(ret, agr = st_agr(ret))
}
```

**Comment by edzer** [comment]
Thanks, @lionel- , that did it. !! Nice.
