### ISSUE TITLE
Migration guide for deprecated functions

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2666]
I had a call to `mutate_each()` in a code I haven't touched for a long time. The warning points me to `mutate_all()`, and it took me some time to figure out that `mutate_each(funs(...), x, y)` translates to `mutate_at(vars(x, y), funs(...))`. Perhaps `?mutate_each` and/or the warning could be more helpful.

I haven't checked other deprecated functions yet.

**Comment by lionel-** [comment]
Good point, I'll adjust the warning next week.

**Comment by rtaph** [comment]
It would be great to also have more documentation on refactoring the deprecated underscore functions. 

``` r
d1 <- mutate_each_(mtcars, funs(log), c("hp", "wt"))
d2 <- mutate_at(mtcars, c("hp", "wt"), funs(log))

identical(d1, d2)
#> [1] TRUE
```

It took me a while to figure out the above, and it is not mentioned in the [Programming with dplyr](http://dplyr.tidyverse.org/articles/programming.html) vignette.

**Comment by hadley** [comment]
As well as improved warning message, we should include a section on this in the news/blog post
