### ISSUE TITLE
Change in cbind() behavior with data.frame and tibble

### ISSUE THREAD

**Issue by MilkWasABadChoice** [tidyverse/dplyr#2667]
I'm seeing a change in how cbind() behaves when given a data.frame and a nibble and couldn't find an obvious related deprecation/change in the release notes:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

a <- data.frame(node=c("A","B","C"), arc=c("D","E","F"), stringsAsFactors=FALSE)
b <- data.frame(color=c("X","Y","Z"), shape=c("P","Q","R"), stringsAsFactors=FALSE)
b <- as_tibble(b)

cbind(a,b)
#>      a           b          
#> node Character,3 Character,3
#> arc  Character,3 Character,3
```

On dplyr 0.5.0, I get the expected result:

``` r
  node arc color shape
1    A   D     X     P
2    B   E     Y     Q
3    C   F     Z     R
```

**Comment by lionel-** [comment]
I'm not sure it's a good idea to export cbind and rbind method. Cf dispatch section of `?cbind`:

```
Dispatch:

     The method dispatching is _not_ done via ‘UseMethod()’, but by
     C-internal dispatching.  Therefore there is no need for, e.g.,
     ‘rbind.default’.

     The dispatch algorithm is described in the source file
     (‘.../src/main/bind.c’) as

       1. For each argument we get the list of possible class
          memberships from the class attribute.

       2. We inspect each class in turn to see if there is an
          applicable method.

       3. If we find an applicable method we make sure that it is
          identical to any method determined for prior arguments.  If
          it is identical, we proceed, otherwise we immediately drop
          through to the default code.
```

According to point 3, finding different methods (here one for data.frame and the other for tbl_df) dispatches to the default method, which coerces to a matrix.

**Comment by krlmlr** [comment]
We have corresponding issues in the tibble repo: https://github.com/tidyverse/tibble/issues/85.

**Comment by lionel-** [comment]
Just noticed that 0.5.0 already had methods for grouped df. If we remove the tbl_df methods, we'll have an inconsistency there.

**Comment by hadley** [comment]
I'm not sure what we can do here — `cbind()` is designed in such a way that we can't make it work cleanly in all circumstance.  I suspect the best thing is to eliminate the new methods. This is still inconsistent and buggy, but at least it's consistently with the previous version of dplyr.
