### ISSUE TITLE
Segmentation fault when using summarise()

### ISSUE THREAD

**Issue by etienne-s** [tidyverse/dplyr#2673]
The following code doesn't make much sense, but it creates a segmentation fault:

```r
df <- data.frame(id = c(1, 2, 3, 3, 4),
                 color = c(NA, "blue", "red", "blue", NA),
                 stringsAsFactors = FALSE)

df%>% 
  group_by(id) %>% 
  summarise(color = color[1],
            color2 = first(color))
```
I use R 3.3.3 and dplyr 0.5.0, but I'm told that it's the same with the dev version.

Original SO question: http://stackoverflow.com/q/43421152/6656269

**Comment by lionel-** [comment]
I can reproduce the crash, thanks for reporting.
