### ISSUE TITLE
mutate() should preserve names in list-columns

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#2675]
To fix https://github.com/tidyverse/dplyr/pull/1689, we now strip names from all vectors in summarise and mutate (https://github.com/tidyverse/dplyr/pull/2512).

I think this is slightly too strong, and we should only strip names from atomic vectors. The current behaviour breaks `tidyr::unnest()` which assumes `transmute()` preserves the names (and there is a unit test that checks it). I'd prefer not to change the API for `unnest()` because it seems likely that someone will have relied on this behaviour.

@krlmlr do you think it's ok to make the stripping conditional (i.e. only for atomic vectors)? I've tried it out locally: the tests now pass in tidy, and only one test fails in dplyr.

```R
test_that("mutate strips names of list-columns, but keeps names in original data (#2523)", {
  vec <- list(a = 1, b = 2)
  data <- data_frame(x = vec)
  data <- mutate(data, x)
  expect_identical(names(vec), c("a", "b"))
  expect_null(names(data$x))
})
```

**Comment by krlmlr** [comment]
The original issue is #1689. If we need to maintain names for tidyr, I don't think there is a way around being more careful with the `names` attribute. I'll look into it.

**Comment by hadley** [comment]
Sorry - I copied and pasted the wrong issue. I've updated the original issue.

**Comment by hadley** [comment]
I think the problem is probably less severe for list-columns because I don't think they'll ever use the hybrid evaluation - most of the time they'll be called with `map()` or `lapply()`.  Restoring the previous behaviour (to not reset the names) will technically re-introduce some class of bugs, but I think they will be extremely rare, and so preserving tidyr backward compatibility is more important in the short term.

**Comment by romainfrancois** [comment]
We currently have this test: 

```r
test_that("summarise strips names (#2675)", {
  data <- tibble(a = 1:3) %>% summarise(b = setNames(nm = a[[1]]))
  expect_null(names(data$b))

  data <- tibble(a = 1:3) %>% rowwise() %>% summarise(b = setNames(nm = a))
  expect_null(names(data$b))

  data <- tibble(a = c(1, 1, 2)) %>% group_by(a) %>% summarise(b = setNames(nm = a[[1]]))
  expect_null(names(data$b))
})
```

And under the current `vec_c()` based implementation, names are kept which I think make sense now: 

``` r
library(dplyr)

tibble(a = 1:3) %>% summarise(b = setNames(nm = a[[1]])) %>% pull()
#> 1 
#> 1
tibble(a = 1:3) %>% rowwise() %>% summarise(b = setNames(nm = a)) %>% pull()
#> 1 2 3 
#> 1 2 3
tibble(a = c(1, 1, 2)) %>% group_by(a) %>% summarise(b = setNames(nm = a[[1]])) %>% pull()
#> 1 2 
#> 1 2
```

which comes from: 

```r
vctrs::vec_c(c(a = 1, b = 2), c(c = 3))
#> a b c 
#> 1 2 3
```

**Comment by krlmlr** [comment]
tibble now preserves inner names for all columns types. Name removal was introduced in tibble 1.1 by accident.
