### ISSUE TITLE
Allow pull() to use raw variable names?

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/dplyr#2677]
It is awkward to switch from raw variable names to character strings when you add pull() to a pipe, e.g.

````
library(babynames)
babynames %>% 
  group_by(year, sex) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(rank == 1) %>% 
  ungroup() %>% 
  distinct(name) %>% 
  pull("name")
````

I'm certain that you did this for sound reasons, but it'll cause students and teachers frustration. Is it possible to match syntax across single table verbs?

**Comment by hadley** [comment]
Oops, yes, I'll fix asap.
