### ISSUE TITLE
Is it obvious dplyr::distinct() should restrict columns to grouping variables?

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2678]
I wanted to ask if it is obvious that dplyr::distinct() should estrict columns to grouping variables?  I tried help(distinct) which does have some discussion around this (visa vie .keep_all).  But it doesn't seem obvious to me if the second nrow() calculation below should be 2 or 4 rows.  I guess I would ask for a bit more documentation in the help/examples.

```r
library("dplyr")
d <- data.frame(x=c(1,1,2,2), y=c(1,2,1,2))
d %>% dplyr::distinct() %>% nrow()
# [1] 4
d %>% group_by(x) %>% dplyr::distinct(.keep_all = TRUE) %>% nrow()
# [1] 2
packageVersion("dplyr")
# [1] ‘0.5.0’
```

**Comment by hadley** [comment]
This is fixed in the dev version (including more examples)
