### ISSUE TITLE
Allow formula in mutate, summarise

### ISSUE THREAD

**Issue by arbelt** [tidyverse/dplyr#2681]
Would it be possible to add `as_function` formula parsing to the `.funs` arguments of `mutate_at`, `summarise_at`, etc. without the `funs` wrapper?  I.e., allow calls like:

```r
df %>% mutate_at("var1", ~ mean(.x, na.rm = TRUE))
```

Not a huge deal, but it'd be nice to make the API more consistent with the purrr functions.  Also, less typing :)

**Comment by lionel-** [comment]
This should be feasible. About less typing, this would be the idiomatic way of doing this:

```r
df %>% mutate_at("var1", mean, na.rm = TRUE)
```

**Comment by lionel-** [comment]
Note that these lambdas will block hybrid evaluation so it's much faster to supply functions like `mean()` directly (as in the comment above).

**Comment by arbelt** [comment]
Cool — thanks so much, that was quick!  & for the hybrid evaluation tip.  On a tangent: `rlang` is really nice to work with, looking forward to 0.6!
