### ISSUE TITLE
Using filter on a data.table with attributes returns an error

### ISSUE THREAD

**Issue by HughParsonage** [tidyverse/dplyr#2683]
Following an R CMD Check error on my package which imports dplyr (thank you for the email), I reproduced the error using the latest dplyr (0.5.0.9004).

There were two problems. Firstly, `bindr` doesn't seem to be listed as a dependency:

```r
library(dplyr)
library(dtplyr)
library(data.table)
DT <- data.table(x = 1)
filter(DT, x == 2)

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘bindr’
Error in filter_impl(.data, quo) : 
  function 'bindrcpp_RcppExport_validate' not provided by package 'bindrcpp'

```

The above seemed to be solved by `install.packages('bindr')`; however, without it, my R session crashed.

Secondly, certain attributes cause problems with `filter`:

```r
library(dplyr)
library(dtplyr)
library(data.table)

DT <- data.table(x = 1, y = 2)
setattr(DT, "vars", list("x", "y"))

DT[x == 3]
# Empty data.table (0 rows) of 2 cols: x,y
filter(DT, x == 3)
# Error in filter_impl(.data, quo) : not compatible with STRSXP
```

**Comment by lionel-** [comment]
Thanks for the report. This should be fixed with the new dtplyr release that is now on CRAN. Please reopen if that is not the case.
