### ISSUE TITLE
partial_eval does not exist

### ISSUE THREAD

**Issue by emiliotorres** [tidyverse/dplyr#2684]
In the development version the partial_eval function does not exist . Is there an alternative? Thank you

```r
devtools::install_github("tidyverse/dplyr")
library(dplyr)
partial_eval # Unknown
```

**Comment by lionel-** [comment]
That function now lives in the new package `dbplyr`.

**Comment by hadley** [comment]
@emiliotorres in the future, please use `reprex::reprex()` to create your reprex, and there's no need to include session info unless specifically requested.

Why are you using `partial_eval()`? It's mostly an internal implementation detail.
