### ISSUE TITLE
Possible to combine column names with `c()` during tidyeval?

### ISSUE THREAD

**Issue by gergness** [tidyverse/dplyr#2685]
This code works in the CRAN version of dplyr, but gives error for the current development version.

``` r
library(dplyr, warn.conflicts = FALSE)
iris %>%
  dplyr::select(c(Sepal.Width, Sepal.Length))
#> Error in overscope_eval_next(overscope, f): object 'Sepal.Width' not found
```

For srvyr, I took advantage of this behavior when I wanted to use the select-style column selection as a named argument (similar to `summarize_at()`). In srvyr's case, using `vars()` is undesirable because most of the time there is only 1 column name, and so it's not intuitive why `vars()` is needed. 

Personally, I never remember to surround the variables argument in `vars()` when using `summarize_at()` and so wonder if it would be better there too.

```r
# Currently need
iris %>% 
   summarize_at(vars(starts_with("Sepal")), "mean")
# or 
iris %>% 
   summarize_at(vars(Sepal.Length, Sepal.Width), "mean")

# But could be changed to allow this
iris %>% 
   summarize_at(starts_with("Sepal"), "mean")
# and
iris %>% 
   summarize_at(c(Sepal.Length, Sepal.Width), "mean")
```

Regardless of whether you change `summarize_at()`'s behavior, would you consider adding support back into `select()`? This is why the revdep checks fail for srvyr right now.

Thank you!

**Comment by lionel-** [comment]
This is because calls supplied to `select()` are now evaluated in the calling environment. This is done so the following works:

```r
df <- tibble(var = 1:3)
var <- "v"
select(df, starts_with(var))
```

We could add an exception for `c()` like we do for `-`, but I don't like that road. I think ultimately I'd prefer simpler semantics and evaluate everything in the overscope. Especially since we now have unquoting so the above example would work that way:

```r
select(df, starts_with(!! var))
```

What do you think @hadley?

**Comment by hadley** [comment]
I think we should special case `c()` for `select()`

**Comment by gergness** [comment]
Thanks!
