### ISSUE TITLE
bind_rows() warning with columns of unknown classes

### ISSUE THREAD

**Issue by pierucci** [tidyverse/dplyr#2688]
It seems `bind_rows()` throws a warning when columns are not part of a set of know classes (listed in [this file](https://github.com/tidyverse/dplyr/blob/master/inst/include/dplyr/Collecter.h) line 28). I understand that users need to be warned that attributes may be lost, but I think that one should be able to silence those warnings when one knows what they are doing. Reprex:

``` r
tab1 <- tibble::tibble(x = lazyeval::as.lazy_dots(list(a = "1", b = "2")))
tab2 <- tibble::tibble(x = lazyeval::as.lazy_dots(list(c = "1", d = "2")))

dplyr::bind_rows(tab1, tab2)
#> Warning in bind_rows_(x, .id): Vectorizing 'lazy_dots' elements may not
#> preserve their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'lazy_dots' elements may not
#> preserve their attributes
#> # A tibble: 4 × 1
#>            x
#>       <list>
#> 1 <S3: lazy>
#> 2 <S3: lazy>
#> 3 <S3: lazy>
#> 4 <S3: lazy>
```

I'd prefer not to wrap my code in `suppressWarnings()` in case there is another reason for a warning.

I see the following solutions:

  1. *Tedious solution:* Add new classes in `known_classes`, like `lazy_dots`. That could quickly become a nightmare for `dplyr` maintainers, and would not allow this solutions to work with custom user classes.
  2. *Option solution:* Let the user add custom known classes (by the options?).
  3. *Automagic solution:* Check the column attributes. If there is no attribute beside class or if the attributes have identical values then don't throw the warning.
  4. *Simple solution:* Add an option to `bind_rows()` to inactivate that specific check.

Solutions 4 solves the problem and seems rather easy to implement. What do you think about it?

**Comment by joethorley** [comment]
This is causing me the same issue. 
3. seems like the most elegant (my class has no attributes besides class) and doesn't exclude 4.
Would you consider a pull request for 3?

**Comment by hadley** [comment]
This is going to get fixed in general in the vctrs package, which will be included in the next major release of dplyr. 

I looked into 3, and it's not simple because the class is currently dropped. 

I think using `suppressWarnings()` is a reasonable work around for now.

**Comment by michaelbarton** [comment]
I realise this issue is closed, but could you provide clarification of what this means? I am getting this warning when calling:

    tidyr::complete(nesting(...))

Does this warning mean I am doing something wrong, or that this is an underlying issue that I should need to worry about?
