### ISSUE TITLE
select() partial matches on select_vars() arguments

### ISSUE THREAD

**Issue by nachocab** [tidyverse/dplyr#2692]
Something seems to have broken between 0.5.0.9000 and 0.5.0.9004 because this no longer works:

```r
data.frame(a = 1:4) %>% select(var = a)
Error in typeof(x) : object 'a' not found
```

I think it's because `var` is already assigned to an existing function. This works perfectly:

```r
data.frame(a = 1:4) %>% select(b = a)
```

**Comment by lionel-** [comment]
this should be resolved shortly.

**Comment by lionel-** [comment]
could you post the version of rlang installed on your computer just to be sure?

**Comment by nachocab** [comment]
rlang_0.0.0.9017
