### ISSUE TITLE
Can find files - 

### ISSUE THREAD

**Issue by wallacetodd** [tidyverse/dplyr#2699]
Hi

Very new to R so please forgive me if this is in the wrong location (and tell me where it should go....)

Running Windows 7 and R 3.3.3

I am trying to load some packages but I keep getting a number of messages that I don't fully understand: see below

Message 1:

The downloaded binary packages are in
        C:\Users\a1094996\AppData\Local\Temp\RtmpaKAmcv\downloaded_packages
> install.packages("zoo")
Installing package into ‘\\uofa/users$/users6/a1094996/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://mirror.aarnet.edu.au/pub/CRAN/bin/windows/contrib/3.3/zoo_1.8-0.zip'
Content type 'application/zip' length 902449 bytes (881 KB)
downloaded 881 KB

Q: why am I getting the message (as ‘lib’ is unspecified), and how do I fix it?

Message 2: 

>   # required packages (must be downloaded and installed prior to running the model)
>   library(coda)
>   library(R2jags)
Loading required package: rjags
Error : .onLoad failed in loadNamespace() for 'rjags', details:
  call: packageVersion(pkg, lib)
  error: package ‘rjags’ not found
Error: package ‘rjags’ could not be loaded
>   library(zoo)

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Q: the packages seem to be downloaded, but presumably are not where R is looking for them. I have tried to manually move them to the library folder, but that doesn't seem to help. I was pointed to a near identical example by someone else.... https://github.com/tidyverse/dplyr/issues/2002 which suggests that the antivirus software may be causing the problem, but I am working on a networked computer and cant turn off the AV software. 

Thanks in advance

**Comment by hadley** [comment]
This doesn't seem to be related to dplyr, so I'd recommend asking a local R expert or on a mailing list.
