### ISSUE TITLE
Join fails when vectors have attributes attached

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/dplyr#2701]
This works with the current CRAN version, but surprised to see it now throws an error

```r
library(dplyr)

dat <- tibble::tibble(
  vs = structure(c(0, 1), foo = "bar"),
  info = c(3, 4)
)

dplyr::left_join(mtcars, dat)

#> Joining, by = "vs"
#> Error in left_join_impl(x, y, by$x, by$y, suffix$x, suffix$y, accept_na_match) : 
#>  attributes of different sizes
```

Perhaps it would be better to ignore the attributes and throw a warning?

**Comment by hadley** [comment]
Yeah, I think we went a bit too restrictive here, and we should downgrade back to a warning.

**Comment by strengejacke** [comment]
Especially if you work with data importet with _haven_ (SPSS-, Stata- or SAS-data), join-operations might fail quite often, confusing users. It would be a lot of work to "clean" the data from attributes first before you can do some dplyr-operations.
