### ISSUE TITLE
Filter on value of an object that has same name as a column in data frame

### ISSUE THREAD

**Issue by adibender** [tidyverse/dplyr#2703]
Not sure if this is a bug, but I expected to get first row of the data frame instead of empty data.frame

```r
library(dplyr)
df <- data.frame(y=1:2, time=c("a", "b"), time2=c(30L, 40L))
time <- 30L
df %>% filter(time2 == time)
## <0 rows> (or 0-length row.names)
```

**Comment by hadley** [comment]
Names in dplyr expressions are looked for first in the data frame.

**Comment by giko45** [comment]
it seams that 

> df %>% filter(time2 == !!time)

works.  Is that OK or just coincidental?
