### ISSUE TITLE
Loading dplyr affects ggplot2 facet output

### ISSUE THREAD

**Issue by juliasilge** [tidyverse/dplyr#2706]
The current development version of dplyr is causing me problems with certain elements in ggplot2, such as `geom_abline` only appearing in the first facet when using `facet_wrap()`.

``` r
library(ggplot2)
library(dplyr)

ggplot(iris, aes(Petal.Width, Petal.Length)) +
    geom_point() +
    geom_abline() +
    facet_wrap(~Species)
```

![no_line](https://cloud.githubusercontent.com/assets/12505835/24580424/38233492-16c5-11e7-897a-7651f7a49e76.png)

This problem does not occur if I run this example without dplyr loaded.

@dgrtwo has had a (related?) problem with `expand_limits()` only applying to the first facet, and he also has the most current dplyr installed.

This is the error I get without `geom_point()`.

``` r
library(ggplot2)
library(dplyr)

ggplot(iris, aes(Petal.Width, Petal.Length)) +
    geom_abline() +
    facet_wrap(~Species)
#> Error in order(panels$PANEL): argument 1 is not a vector
```

This issue is the same as tidyverse/ggplot2#2093.

**Comment by lionel-** [comment]
I can't reproduce with ggplot2 CRAN or master. Could you try updating all the relevant packages please (dplyr, rlang, ggplot2).

**Comment by juliasilge** [comment]
Huh, I updated to R 3.4.0 and then reinstalled dplyr, rlang, and ggplot2 from GitHub and it is now working:

``` r
library(ggplot2)
library(dplyr)

ggplot(iris, aes(Petal.Width, Petal.Length)) +
    geom_point() +
    geom_abline() +
    facet_wrap(~Species)
```

![](http://i.imgur.com/vin0Zka.png)

Mysterious... but resolved, I suppose!

**Comment by hadley** [comment]
I have a vague memory of seeing this problem myself so it's possible it was a bug in the dev version of ggplot2
