### ISSUE TITLE
Inconsistencies across systems working with factors

### ISSUE THREAD

**Issue by jojedagithub** [tidyverse/dplyr#2712]
It seems to me that there is some sort of inconsistency in the behaviour of `dplyr` under different systems.

---
Following code does work on ubuntu raising a core dump after displaying following message on the console
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
Aborted (core dumped)
```
But does on some windows:
``` r
library(dplyr) 

dd<-data.frame(x=rnorm(1000),f=factor(c("friend","foe")[1+rbinom(1000,1,.5)]))
dd$c<-with(dd,x>0&f=="friend")
summary(dd)
winLength<-50
if(FALSE) {  
  ## The original setup for the error
  ddSum <- dd %>% tbl_df %>% 
    mutate(ep=ceiling(row_number()/winLength)) %>% 
    group_by(ep) %>%
    summarize(max(x),mean(x),sd(x),sum(x),sum(f),max(c))
} else { 
  ## The error is produced by the factor sum
  ddSum <- dd %>% tbl_df %>% 
    mutate(ep=ceiling(row_number()/winLength)) %>% 
    group_by(ep) %>%
    summarize(sum(f),max(c))
}
```
The ubuntu and R system that produces where the code raises a core dump are the following:
```
Processor     : 4x Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
Memory        : 8089MB (3195MB used)
Operating System      : Ubuntu 16.04.2 LTS
R 3.4.0
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          3
minor          4.0
year           2017
month          04
day            21
svn rev        72570
language       R
version.string R version 3.4.0 (2017-04-21)
nickname       You Stupid Darkness
```
but it worked on an virtualized XP 32bits raising the expected error ('sum not meaningful for factors) while in some others just returns something (_I didn't that test by myself_). While I have solved the problem I have at hand, I think this may pose a sort of uneasy or unconfortable problem to understand. 

Thank you very much.
---

**Comment by hadley** [comment]
In most previous cases this behaviour has been caused by a compiling dplyr against one version of Rcpp and then using it with a different version. The dev version has a warning to make this easier to diagnose in the future.

**Comment by jojedagithub** [comment]
It may well be that because I update the package a day or two a go, while
the windows install is just fresh. I will be aware for if it happens again.

Thank you very much again, Jorge.
