### ISSUE TITLE
%in% operator does not work properly when working with postgres

### ISSUE THREAD

**Issue by jandraor** [tidyverse/dplyr#2714]
I'm working with a remote postgres db. When I try to use the filter function with the operator %in% I receive an error if the variable years_new has only one variable. If it has more than one value, there's no problem.

This is the message I receive:  RS-DBI driver: (could not Retrieve the result : ERROR:  error de sintaxis en o cerca de Â«2016Â»
LINE 4: WHERE ("year" IN 2016)) "wsrhvprnxc"

```r
bd                       <-    src_postgres(dbname = "db", 
                                                        host = "host", 
                                                        port = 5432, 
                                                        user = "postgres", 
                                                        password = "123456")
years_new             <- 2016
table                      <- tbl(bd, "a_31_1_detalle")
table                      <- filter(table, year %in% years_new)


```

**Comment by hadley** [comment]
Fixed in dev version
