### ISSUE TITLE
dplyr join issue: Spark1.6.2 reports "same name join" even for "by" columns

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2722]
The issue is illustrated below.  Using the current CRAN versions of dplyr and sparklyr (as of 2017-03-30') we get an error message "Use Spark2" when there are any duplicate column names: even in the "by" columns (which are often deliberately the same).  The problem is in real production systems you can choose your version of dplyr and sparklyr, but you often can not choose your version of Spark as it is part of a possibly shared cluster.

``` r
library("dplyr")
```

``` r
packageVersion("dplyr")
```

    ## [1] '0.5.0'

``` r
library("sparklyr")
packageVersion("sparklyr")
```

    ## [1] '0.5.4'

``` r
sc <- spark_connect(master = "local", 
                    version = "1.6.2")

d1 <- copy_to(sc, 
              data.frame(x=c('a','b'), y=c(1,2)),
              name= 'd1',
              overwrite = TRUE)
d2 <- copy_to(sc, 
              data.frame(x=c('b'), z=c(3)),
              name= 'd2',
              overwrite = TRUE)
```

``` r
left_join(d1, d2, by='x')
```

    ## Error in sql_join.spark_connection(con, from_x, from_y, type = query$type, : This dplyr operation requires a feature not supported in Spark 1.6.2 . Try Spark 2.0.0 instead or avoid using same-column names in joins.

``` r
left_join(d1, rename(d2, xb = x), by= c('x'='xb'))
```

    ## Source:   query [2 x 4]
    ## Database: spark connection master=local[4] app=sparklyr local=TRUE
    ## 
    ##       x     y    xb     z
    ##   <chr> <dbl> <chr> <dbl>
    ## 1     a     1  <NA>   NaN
    ## 2     b     2     b     3

**Comment by hadley** [comment]
Can you please file this in the sparklyr repo?
