### ISSUE TITLE
dplyr mutate fails to add vector of values on sparklyr

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2723]
In the example below I attempt to use `dplyr::mutate` to add a new column to a Sparklyr dataframe.  In the first attempt it errors-out and in the second attempt it adds a strange structure.

``` r
library("dplyr")
```

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

``` r
packageVersion("dplyr")
```

    ## [1] '0.5.0'

``` r
library("sparklyr")
packageVersion("sparklyr")
```

    ## [1] '0.5.4'

``` r
sc <- spark_connect(master = "local", version = "2.0.0")
d <- data.frame(y=c(1,1,1,0,0,0), x=c(1,1,0,0,0,1))
dS <- copy_to(sc, d, overwrite = TRUE)
```

``` r
d2 <- mutate(dS, RowId = seq_len(nrow(dS)))
print(d2)
```

    ## Error in UseMethod("escape"): no applicable method for 'escape' applied to an object of class "c('tbl_spark', 'tbl_sql', 'tbl_lazy', 'tbl')"

``` r
ids <-  seq_len(nrow(dS))
d3 <- mutate(dS, RowId = ids)
print(d3)
```

    ## Source:   query [6 x 3]
    ## Database: spark connection master=local[4] app=sparklyr local=TRUE
    ## 
    ##       y     x            RowId
    ##   <dbl> <dbl>           <list>
    ## 1     1     1 <S3: spark_jobj>
    ## 2     1     1 <S3: spark_jobj>
    ## 3     1     0 <S3: spark_jobj>
    ## 4     0     0 <S3: spark_jobj>
    ## 5     0     0 <S3: spark_jobj>
    ## 6     0     1 <S3: spark_jobj>

``` r
print(d3$RowId[[1]])
```

    ## NULL

**Comment by hadley** [comment]
And this one too — any bugs that are specific to spark are best filed in sparklyr because that's most likely where they need to be fixed.
