### ISSUE TITLE
Piping vs non-piping error

### ISSUE THREAD

**Issue by pierrelafortune** [tidyverse/dplyr#2726]
I expected these two expressions to have the same output. But when the data frame is piped into the select call, it fails:

```
(function(x) select(mtcars, !!enquo(x)))(disp)
                     disp
Mazda RX4           160.0
Mazda RX4 Wag       160.0
Datsun 710          108.0
Hornet 4 Drive      258.0
Hornet Sportabout   360.0
```

Compared to 
```
(function(x) mtcars %>% select(!!enquo(x)))(disp)
Error in (function (x, strict = TRUE)  : 
  the argument has already been evaluated
```

**Comment by hadley** [comment]
The pipe does weird things to evaluation order (which might might try to remedy in the future). Just do the enquosing outside the pipe:

```R
library(dplyr)

foo <- function(x) {
  x <- enquo(x)
  mtcars %>% select(!!x)
}
foo(disp)
```

**Comment by JohnMount** [comment]
I think the issue is in magrittr's freduce.R.  This function directly evaluates pipe stages using the recursive environment.  I think if instead it called eval and referenced the parent environment that might clean up everything.

**Comment by lionel-** [comment]
Then the pronoun `.` would stop working. Here is a version that uses a temporary binding.

https://gist.github.com/lionel-/10cd649b31f11512e4aea3b7a98fe381

**Comment by JohnMount** [comment]
Okay, sorry that was not enough.  I had been looking and hoped that might be helpful, but clearly it was not.
