### ISSUE TITLE
Issue in dplyr db interface with an oracle backend

### ISSUE THREAD

**Issue by GuiMarthe** [tidyverse/dplyr#2732]
### Description

Unable to "query" an oracle database with a connection created with the ROracle package using the dplyr api. However, it works perfectly with `dbGetQuery(con, "select count(*) from mytable")` .

Here are the steps I have followed:

```r
> library(dplyr)
# dplyr loading output
> library(DBI)
> library(ROracle)
> drv <- dbDriver("Oracle")
> con <- dbConnect(drv,
+                  username = "user",
+                  password = "passwd",
+                  dbname = "details/dbname")
> dd <- tbl(con, "select count(*) from mytable")
Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-00972: identifier is too long
In addition: Warning messages:
1: replacing previous import by ‘rlang::enquo’ when loading ‘dbplyr’ 
2: replacing previous import by ‘rlang::quo’ when loading ‘dbplyr’ 
3: replacing previous import by ‘rlang::quos’ when loading ‘dbplyr’ 
4: replacing previous import by ‘rlang::quo_name’ when loading ‘dbplyr’ 
```
However, when running the same with `dbGetQuery`, right after the previous code:

```r
> dd <- dbGetQuery(con, "select count(*) from mytable")
> dd
  COUNT(*)
1    10965
```
#### Comments

I am fairly sure this will be hard to provide a reproducible example from my end for two reasons. 
Firstly, the error happens when attempting to create a table with the suggested method from the documentation, ie: `tbl(con, sql("select count(*) from mytable"))`, so there isn't much i have fiddled with the code.

Secondly, I've only tried the code against a production db, so I am not sure if it persists against another environment.

### R session output

```r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C               LC_TIME=pt_BR.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ROracle_1.3-1    DBI_0.6-1        dplyr_0.5.0.9004

loaded via a namespace (and not attached):
[1] magrittr_1.5      assertthat_0.2.0  R6_2.2.0          tools_3.2.3       glue_1.0.0       
[6] tibble_1.3.0      Rcpp_0.12.10      rlang_0.0.0.9018  dbplyr_0.0.0.9001
```

**Comment by hadley** [comment]
That suggests ROracle hasn't supplied the necessary methods to make a full dplyr backend. I'd recommend discussing with the maintainers of that package.

**Comment by GuiMarthe** [comment]
I see. I will message the current maintainer of the ROracle package!

**Comment by edgararuiz** [comment]
@GuiMarthe - Can you post what this return in for your connection: `class(con)`?  

I just realized that you are actually using `odbc` to connect and extracting the driver from the `ROracle` package.  This may provide a `class` we can work with.
