### ISSUE TITLE
arrange() error with memdb sources

### ISSUE THREAD

**Issue by ianmcook** [tidyverse/dplyr#2740]
Some of the tests in dbplyr/tests/testthat/test-output.R are failing because of an error that occurs when `arrange()` is applied to a memdb source.

Reprex:
``` r
library(dplyr)
library(dbplyr)
ds <- memdb_frame(x = runif(100), y = runif(100))
ds %>% arrange(x)
#> Error: All unnamed arguments must be length 1
```

**Comment by hadley** [comment]
They look ok on travis? https://travis-ci.org/tidyverse/dbplyr/builds/228065760

**Comment by ianmcook** [comment]
Your recent dbplyr commits look good, but the recent dbplyr PRs (not just mine) have this error. https://travis-ci.org/tidyverse/dbplyr/jobs/228496221

**Comment by hadley** [comment]
Oh it's probably due to some change in dplyr error messages (although I wouldn't have thought that the changes affected these tests). I've restarted the build and I'll look into it in more detail tomorrow or Friday.

**Comment by hadley** [comment]
I can't reproduce this error though. Are you still seeing it with latest dplyr, dbplyr, rlang, and tibble?

**Comment by ianmcook** [comment]
Ah, this went away after syncing forks. Closing.
