### ISSUE TITLE
Using nested lists in dplyr filter() raises error.

### ISSUE THREAD

**Issue by bakaburg1** [tidyverse/dplyr#2747]
Hello, if I access nested elements in a list with the `$` operator with `dplyr::filter()` I get this error:

> Error: invalid subscript type 'closure'

The error is not triggered if `[]` are used to access the inner element.

Here's some dummy code:

```r
    d <- data.frame(days = seq(ymd('2017/1/1'), ymd('2017/2/1'), by = 'days'))
    
    test <- list(
        period = list(start = ymd('2017/1/10')
        )
    )
    
    d %>% filter(days > probe$period$start)
    ## Here's the error
    
    d %>% filter(days > probe$period['start'])
    ## This works!

```
I noticed that something similar was solved in previous issues, but I still see this problem.

**Comment by hadley** [comment]
Both work for me in the dev version, but I had to rename `test` to `probe`. In the future, please use the reprex package to make your reprexes.
