### ISSUE TITLE
Implement tbl_sum.tbl_sql()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2749]
Currently, dbplyr implements `print.tbl_lazy()` and `print.tbl_sql()`, but `tbl_sql` objects inherit from `tbl_lazy`. If we remove `print.tbl_sql()`, printing is handled by `print.tbl_lazy()`, which will print only the query plan but not the data.

@hadley: Okay to get rid of `print.tbl_lazy()`, and implement a different method (e.g., `render()`) to show the query plan of a lazy object?

**Comment by hadley** [comment]
Yeah, that's fine. The function to show the query plan doesn't need to be exported for now.
