### ISSUE TITLE
loading tidyverse causes R 3.3.3 and 3.4 to crash using macOS Sierra

### ISSUE THREAD

**Issue by thomasklee** [tidyverse/dplyr#2753]
I've been using tidyverse 1.1, R 3.3.3 and RStudio 1.0.143 successfully but after installing R 3.4, R crashes when I load tidyverse. 

I can successfully load read_r and dplyr separately, but broom and tidyr cause RStudio to crash. They also cause to R to crash when used outside RStudio. 

I reinstalled R 3.3.3 and have the same problems as with R 3.4. 

I use a Macbook Pro:
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

I've attached a screen shot of the error messages from RStudio. Thanks for any suggestions you might have.
![screen shot 2017-05-08 at 2 50 16 pm](https://cloud.githubusercontent.com/assets/11205359/25793554/a93fc968-33ff-11e7-914a-a7e708204d9e.png)

**Comment by lionel-** [comment]
does the problem go away if you reinstall all packages? What does `.libPaths()` return on your system? It should return a library containing 3.4 in the path. If that's the case, you probably had to reinstall all packages when you switched to 3.4 and that couldn't explain the crash.

@kevinushey A R crash shouldn't normally trigger an RStudio crash right?

**Comment by thomasklee** [comment]
Thanks for the response. I haven't tried to reinstall all my packages yet. At the moment, I have R 3.3.3 installed, so my user library and system library paths are:

> .libPaths()
[1] "/Users/thomasklee/Rlibs"                                       
[2] "/Library/Frameworks/R.framework/Versions/3.3/Resources/library"

I've also uninstalled and reinstalled tidyverse, but the problem persists.

**Comment by thomasklee** [comment]
I'm running 3.3 with the 3.3 base library as far as I can tell (see my previous post). 

I'll install 3.4 and then reinstall all the packages in my user library.

**Comment by lionel-** [comment]
oops sorry I read your post too fast! Perhaps your library now contains a mix of 3.3 and 3.4-built packages, which would explain that you keep seeing crashes after switching back to 3.3.

**Comment by hadley** [comment]
It's a really bad idea to try and mix multiple R versions using the same library. I'd recommend deleting your library and starting afresh.

**Comment by kevinushey** [comment]
Unfortunately R segfaults can (and often do) bring down RStudio as well, with this exact kind of stack trace. :/

Definitely agree that libraries need to be version-specific. Trying to use packages compiled against R 3.3.x with R 3.4.x will cause crashes on load in many cases.

**Comment by thomasklee** [comment]
Thanks for all your help. Installing the new version of R (3.4), deleting my old user library, and downloading a fresh set of packages did the trick. I really appreciate the help!
