### ISSUE TITLE
Problem with glimpse and PostgreSQLConnection

### ISSUE THREAD

**Issue by turbomanson** [tidyverse/dplyr#2762]
---
Function glimpse() now returns error when I call it on class 'PostgreSQLConnection'

```r

#the object in question
> dput(site)
structure(list(src = structure(list(con = <S4 object of class structure("PostgreSQLConnection", package = "RPostgreSQL")>, 
    info = structure(list(host = "data-warehouse.co94rwcdy34w.us-east-1.redshift.amazonaws.com", 
        port = "5439", user = "billing", dbname = "billing", 
        serverVersion = "8.0.2", protocolVersion = 3L, backendPId = 30141L, 
        rsId = list()), .Names = c("host", "port", "user", "dbname", 
    "serverVersion", "protocolVersion", "backendPId", "rsId")), 
    disco = <environment>), .Names = c("con", "info", "disco"
), class = c("src_postgres", "src_sql", "src")), ops = structure(list(
    src = structure(list(con = <S4 object of class structure("PostgreSQLConnection", package = "RPostgreSQL")>, 
        info = structure(list(host = "data-warehouse.co94rwcdy34w.us-east-1.redshift.amazonaws.com", 
            port = "5439", user = "billing", dbname = "billing", 
            serverVersion = "8.0.2", protocolVersion = 3L, backendPId = 30141L, 
            rsId = list()), .Names = c("host", "port", "user", 
        "dbname", "serverVersion", "protocolVersion", "backendPId", 
        "rsId")), disco = <environment>), .Names = c("con", "info", 
    "disco"), class = c("src_postgres", "src_sql", "src")), x = structure("site", class = c("ident", 
    "sql", "character")), vars = c("uuid", "stripe_owner", "owner_locutus_id", 
    "domain_name", "board_name", "board_fee_subscriptions", "enabled", 
    "lm_start_date", "lm_leads", "lm_users", "texting", "real_leads", 
    "facebook_managed_marketing", "plan", "home_valuation_tool", 
    "facebook_tool")), .Names = c("src", "x", "vars"), class = c("op_base_remote", 
"op_base", "op"))), .Names = c("src", "ops"), class = c("tbl_postgres", 
"tbl_sql", "tbl_lazy", "tbl"))

#attempting glimpse()

> glimpse(site)
Observations: NA
Variables: 16
Error in if (width[i] <= max_width[i]) next : 
  missing value where TRUE/FALSE needed

```

**Comment by hadley** [comment]
Can you please provide a reprex created with the reprex package?

**Comment by turbomanson** [comment]
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

my_db <- src_postgres(host = 'data-warehouse.co94rwcdy34w.us-east-1.redshift.amazonaws.com',
                      port = '5439',
                      user = "billing",
                      password = "*********")

leads <- tbl(my_db, 'leads')
glimpse(leads)
#> Observations: NA
#> Variables: 87
#> Error in if (width[i] <= max_width[i]) next: missing value where TRUE/FALSE needed

**Comment by turbomanson** [comment]
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

my_db <- src_postgres(host = 'data-warehouse.co94rwcdy34w.us-east-1.redshift.amazonaws.com',
                      port = '5439',
                      user = "billing",
                      password = "*******")

leads <- tbl(my_db, 'leads')
glimpse(leads)
#> Observations: NA
#> Variables: 87
#> Error in if (width[i] <= max_width[i]) next: missing value where TRUE/FALSE needed

**Comment by hadley** [comment]
Seems fine in the dev version.
