### ISSUE TITLE
filter(row_number() == 1)

### ISSUE THREAD

**Issue by makhomashoba** [tidyverse/dplyr#2768]
Hello,

filter(row_number() == 1)

I was having trouble using this filter code on a proprietary system that connects to dplyr.  It did work before this development version, and I suspect it might be popular. I thought it might be helpful to let you guys know.

Thank you for dplyr!
---

Brief description of the problem

```r
# insert reprex here
```

**Comment by lionel-** [comment]
could you provide a rexprex please.
