### ISSUE TITLE
Dev Version of Filter adds a vars attribute

### ISSUE THREAD

**Issue by colearendt** [tidyverse/dplyr#2772]
The new version of `filter` in dplyr (0.5.0.9004) adds a `vars` attribute that is new (does not show in dplyr 0.5.0).  This is causing some tests to fail when using `expect_identical()` because attributes have changed.

Expected behavior is to not have the `vars` attribute

In my tests, the attribute seems always to be `character(0)`, which suggests to me that it is unintentional.  I have struck out finding where it is coming from, though.

```r
## Using CRAN Version - expected and desired behavior
suppressMessages(library(dplyr))                          
packageVersion('dplyr')                                   
#> [1] '0.5.0'
data_frame(id=c(1,2,3)) %>% filter(id==1) %>% attributes()
#> $class
#> [1] "tbl_df"     "tbl"        "data.frame"
#> 
#> $row.names
#> [1] 1
#> 
#> $names
#> [1] "id"

## Using devtools::install_github('tidyverse/dplyr')
suppressMessages(library(dplyr))
packageVersion("dplyr")
#> [1] '0.5.0.9004'
data_frame(id = c(1, 2, 3)) %>% filter(id == 1) %>% attributes()
#> $class
#> [1] "tbl_df"     "tbl"        "data.frame"
#> 
#> $row.names
#> [1] 1
#> 
#> $names
#> [1] "id"
#> 
#> $vars
#> character(0)
```

**Comment by lionel-** [comment]
This attribute is set there:

https://github.com/tidyverse/dplyr/blob/6667b736c62c34457393f0187819aba0ab04b0f8/src/utils.cpp#L149

Introduced in https://github.com/tidyverse/dplyr/pull/2388

@krlmlr Could we safely remove this attribute when the symbol vector is empty?

**Comment by colearendt** [comment]
Much thanks for the quick fix and the great package!
