### ISSUE TITLE
Issue with grouped operations and attributes

### ISSUE THREAD

**Issue by Enchufa2** [tidyverse/dplyr#2773]
Consider the following custom S3 class with an attribute:

```r
x <- 1:10
class(x) <- "foo"
attr(x, "foo") <- 1:10
```

in which the length of the attribute must coincide with the vector. I define the following S3 methods:

```r
as.data.frame.foo <- as.data.frame.numeric

mean.foo <- function(x, ...) {
  foo <- mean(attr(x, "foo"))
  structure(NextMethod(), "foo" = foo, class = "foo")
}
```

where `mean` summarises the vector as well as the attribute. Then,

```r
data.frame(x=x) %>%
  summarise_all(mean) %>%
  .$x
# [1] 5.5
# attr(,"foo")
# [1] 5.5
# attr(,"class")
# [1] "foo"
```

Ok, but

```r
data.frame(x=x, y=rep(c("A", "B"), each=5)) %>%
  group_by(y) %>%
  summarise_all(mean) %>%
  .$x
# [1] 3 8
# attr(,"foo")
# [1] 5.5              # <- I'd expect: 3 8
# attr(,"class")
# [1] "foo"
```

**Comment by lionel-** [comment]
Aggregation of attributes is a really difficult issue because we don't have any information about how to do it. Some attributes are vectorised, some aren't. I'm surprised that the attributes of the original vector are preserved at all actually.

**Comment by Enchufa2** [comment]
This could work if the subsetting of grouped data were done by calling R's subsetting operator. But even if I define the operator `[.foo`, the example doesn't work, so I suppose that this is done internally, at C++ level. Any chance of having support for this?

**Comment by lionel-** [comment]
There's the issue of subsetting and there's the issue of aggregating all the data back to one vector. We need C-level genericity of vectors and we have plans regarding this, but it's not a trivial issue to solve.

**Comment by hadley** [comment]
This is on our long term to do list.
