### ISSUE TITLE
Duplicate columns not allowed in join (dev dplyr)

### ISSUE THREAD

**Issue by MZLABS** [tidyverse/dplyr#2774]
Instead of adding suffixes join fails with duplicate column message.  I think this depends on the version of dplyr used.  Seeing the failure with the dev-version of dplyr '0.5.0.9004' as of 5-14-2017.

``` r
# devtools::install_github("tidyverse/dplyr")
# devtools::install_github('tidyverse/dbplyr')
suppressPackageStartupMessages(library('dplyr'))
packageVersion("dplyr")
```

    ## [1] '0.5.0.9004'

``` r
library('sparklyr')
packageVersion("sparklyr")
```

    ## [1] '0.5.4'

``` r
if(requireNamespace("dbplyr", quietly = TRUE)) {
  packageVersion("dbplyr")
}
```

    ## [1] '0.0.0.9001'

``` r
R.Version()$version.string
```

    ## [1] "R version 3.4.0 (2017-04-21)"

``` r
sc <- sparklyr::spark_connect(version='2.0.2', 
   master = "local")
d1 <- copy_to(sc, data.frame(x=1:3, y=4:6), 'd1')
d2 <- copy_to(sc, data.frame(x=1:3, y=7:9), 'd2')

left_join(d1, d2, by='x')
```

    ## Source:     lazy query [?? x 3]
    ## Database:   spark_connection

    ## Error: Each variable must have a unique name.
    ## Problem variables: 'y'

``` r
spark_disconnect(sc)
rm(list=ls())
gc(verbose = FALSE)
```

**Comment by hadley** [comment]
Can you please file on the sparklyr repo, and I'd recommend creating the reprex with the reprex package.
