### ISSUE TITLE
Simple cast emits `SQL` not accepted by `MySQL` (filed here as instructed in dbplyr)

### ISSUE THREAD

**Issue by MZLABS** [tidyverse/dplyr#2775]
Simple cast emits `SQL` not accepted by `MySQL`.

``` r
# devtools::install_github("tidyverse/dplyr")
# devtools::install_github('tidyverse/dbplyr')
suppressPackageStartupMessages(library('dplyr'))
packageVersion("dplyr")
```

    ## [1] '0.5.0.9004'

``` r
if(requireNamespace("dbplyr", quietly = TRUE)) {
  packageVersion("dbplyr")
}
```

    ## [1] '0.0.0.9001'

``` r
R.Version()$version.string
```

    ## [1] "R version 3.4.0 (2017-04-21)"

``` r
sc <- dplyr::src_mysql('mysql', 
                       '127.0.0.1', 
                       3306, 
                       'root', 'passwd')
d1 <- copy_to(sc, data.frame(x=1:3), 'd1')

# works, Note PostgreSQL needs this form 
# or it doesn't know type of newCol
mutate(d1, newCol= 'a')
```

    ## Source:     lazy query [?? x 2]
    ## Database:   mysql 5.6.34 [root@127.0.0.1:/mysql]
    ## 
    ## # A tibble: ?? x 2
    ##       x newCol
    ##   <int>  <chr>
    ## 1     1      a
    ## 2     2      a
    ## 3     3      a

``` r
# throws
mutate(d1, newCol= as.character('a'))
```

    ## Source:     lazy query [?? x 2]
    ## Database:   mysql 5.6.34 [root@127.0.0.1:/mysql]

    ## Error in .local(conn, statement, ...): could not run statement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TEXT) AS `newCol`
    ## FROM `d1`
    ## LIMIT 10' at line 1

``` r
rm(list=ls())
gc(verbose = FALSE)
```

**Comment by hadley** [comment]
Can you please use the reprex package to create this reprex? (And please make it minimal by removing all code not directly related to the problem)

**Comment by JohnMount** [comment]
Looks like it works now.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.0'
packageVersion("dbplyr")
#> [1] '1.0.0'
sc <- dplyr::src_mysql('mysql', 
                       '127.0.0.1', 
                       3306, 
                       'root', '')
d1 <- copy_to(sc, data.frame(x=1:3), 'd1')

mutate(d1, newCol= 'a')
#> # Source:   lazy query [?? x 2]
#> # Database: mysql 5.7.18 [root@127.0.0.1:/mysql]
#>       x newCol
#>   <int>  <chr>
#> 1     1      a
#> 2     2      a
#> 3     3      a
mutate(d1, newCol= as.character('a'))
#> # Source:   lazy query [?? x 2]
#> # Database: mysql 5.7.18 [root@127.0.0.1:/mysql]
#>       x newCol
#>   <int>  <chr>
#> 1     1      a
#> 2     2      a
#> 3     3      a
```
