### ISSUE TITLE
 fatal error: plogr.h: No such file or directory  #include <plogr.h>

### ISSUE THREAD

**Issue by tarunparmar** [tidyverse/dplyr#2795]
I was trying to deploy `purrr` package using RStudio Connect and notice that it comes to a stop and throws this error:
` fatal error: plogr.h: No such file or directory #include <plogr.h>`

This causes failure in compilation on `purrr`  package.

---
From what I understand it seems system is not able to file `plogr.h` as other files have format like this : `<dplyr/config.h>`. See image below.
![image](https://cloud.githubusercontent.com/assets/17690950/26168540/6b89d5e0-3b08-11e7-8443-e00f6b536298.png)

```r
library(purrr)
```

**Comment by krlmlr** [comment]
What version of the purrr package do you have? The most recent CRAN version shouldn't exhibit this behavior.

**Comment by tarunparmar** [comment]
This seemed to be an issue with dplyr's github version. I rolled back to CRAN and it was fine.
I had 0.2.2 of purrr

**Comment by krlmlr** [comment]
You need purrr 0.2.2.2 for compatibility with dplyr > 0.5.0.
