### ISSUE TITLE
Two-table verbs crash R when join encoded column name whose value is an encoded factor level

### ISSUE THREAD

**Issue by mauriciocramos** [tidyverse/dplyr#2798]
This issue seems to be related to the closed #1513.

The only way I can reproduce this error is when two identical data frames have column whose value is an encoded factor level and any dplyr two-table verb join on these columns.

Although I'm using a locale with "latin1" encoding, I believe the following test code should work in your locale with "UTF-8" encoding.

``` r
#Environment
R.version.string
#> [1] "R version 3.4.0 (2017-04-21)"
library(dplyr)
packageVersion("dplyr")
#> [1] '0.5.0'
Sys.info()[1:5]
#>       sysname       release       version      nodename       machine 
#>     "Windows"      "10 x64" "build 14393"     "DESKTOP"      "x86-64"
Sys.getlocale("LC_CTYPE")
#> [1] "Portuguese_Brazil.1252"
getOption("encoding")
#> [1] "native.enc"

#Native and foreign encoding
(native <- ifelse(l10n_info()[[2]], "UTF-8", ifelse(l10n_info()[[3]], "latin1", "unknown")))
#> [1] "latin1"
(foreign <- switch(native, "latin1"="UTF-8", "UTF-8"="latin1"))
#> [1] "UTF-8"

#First data frame containing a native encoded factor level string relatedto the problem
df.native <- data.frame(name = "Mauricio", family = as.factor("Collaça"), stringsAsFactors = FALSE)
str(df.native)
#> 'data.frame':    1 obs. of  2 variables:
#>  $ name  : chr "Mauricio"
#>  $ family: Factor w/ 1 level "Collaça": 1
sapply(df.native, function(x) Encoding(as.character(x)))
#>      name    family 
#> "unknown" "unknown"

#Second data frame containing a foreign encoded factor level string which is also related to the problem
df.foreign <- data.frame(name = "Mauricio", family = as.factor(iconv("Collaça", to = foreign)), stringsAsFactors = FALSE)
str(df.foreign)
#> 'data.frame':    1 obs. of  2 variables:
#>  $ name  : chr "Mauricio"
#>  $ family: Factor w/ 1 level "Collaça": 1
sapply(df.foreign, function(x) Encoding(as.character(x)))
#>      name    family 
#> "unknown"   "UTF-8"

#All set, the natural join on the column "family" is avoided, R doesn't abort
inner_join(df.native, df.foreign, by = "name")
#>       name family.x family.y
#> 1 Mauricio  Collaça  Collaça
```
``` r
#Natural join and explicit join on "family" crash R without any message
inner_join(df.native, df.foreign)
inner_join(df.native, df.foreign, by = c("name", "family"))
inner_join(df.native, df.foreign, by = "family")
```

**Comment by lionel-** [comment]
Next time could you use the reprex package please, so we can easily copy paste the code.

Also your code doesn't work portably. Could you try with the dev version?

**Comment by mauriciocramos** [comment]
I tried to use reprex but it mess my latin1 characters... I'll give it another try in minutes...

**Comment by lionel-** [comment]
It doesn't need to be done with reprex, but the code should be unprefixed (no `>`) and the output should be commented with `#`.

To try with the dev version without permanently installing packages, you can use:

```r
# To install in a temporary library
devtools::dev_mode(TRUE)

devtools::install_github("tidyverse/dplyr")
```

**Comment by mauriciocramos** [comment]
@lionel- Thanks for the explanation.  I fixed the post.  I was not thinking to test with the dev version but I can try that later.  Can you please recheck this new code and tell me why it's not working portably or at least what are you watching?  I would need more time to switch to a UTF-8 platform to check that, probably just at night. Cheers.

**Comment by lionel-** [comment]
This returns `"unknown"` on my machine:

```r
(native <- Encoding(iconv(rawToChar(as.raw(1:255)))))
```

What does calling `iconv()` without argument do? Kirill has worked on encoding a lot so it's likely fixed already, it'd help if you could test the dev version on your machine.

To create portable examples, it's best to create all strings from their bytes representation and to set the encoding manually:

```r
library("dplyr")
library("rlang")

df <- tibble(
  unknown = string(bytes(0xc3, 0xa7), encoding = "unknown"),
  utf8 = string(bytes(0xc3, 0xa7), encoding = "UTF-8"),
  latin1 = string(bytes(0xe7), encoding = "latin1")
)

map(df, str_encoding)
#> $unknown
#> [1] "unknown"
#>
#> $utf8
#> [1] "UTF-8"
#>
#> $latin1
#> [1] "latin1"
```

**Comment by mauriciocramos** [comment]
Strange, in my machine this returns exactly what you see before:
```r
(native <- Encoding(iconv(rawToChar(as.raw(1:255)))))
#> [1] "latin1" 
```
I've been using this as a tricky way to discover the current native encoding.
Then I can switch it to the foreign one (when I need) with:
```r
(foreign <- switch(native, "latin1"="UTF-8", "UTF-8"="latin1"))
#> [1] "UTF-8"
```
help(iconv)
>iconv(x, from = "", to = "", sub = NA, mark = TRUE, toRaw = FALSE)
>All R platforms support "" (for the encoding of the current locale), "latin1" and "UTF-8".
As far as I understood, from="" and to="" "transforms from native to native", because as I said, I don't want to transform, just to portably know the current native enconding.  Better ideas? 
But now that you told me you got "unknown" I got confused.
I'll checkt the way you told me and also test the dev version.

**Comment by lionel-** [comment]
There are two native encodings with special markings: `latin1` and `UTF-8`. All other native encodings will be marked as `unknown`.

You can use `l10n_info()` to see which native encoding is active (if both latin1 and UTF-8 are FALSE, the native encoding is unknown).

**Comment by mauriciocramos** [comment]
Thanks to you I changed the test code in the original post, expecting to be portable now.  Kindly confirm it runs in your machine.

```r
(native <- ifelse(l10n_info()[[2]], "UTF-8", ifelse(l10n_info()[[3]], "latin1", "unknown")))
#> [1] "latin1"
(foreign <- switch(native, "latin1"="UTF-8", "UTF-8"="latin1"))
#> [1] "UTF-8"
```

As this portability detail had nothing to do with the bug I found in my fresh CRAN installation, inner_join() still crashes R.

But, great news!  In the the dev version, the bug no longer exists.  Your guidance worths!  Is there anything else I can contribute in this issue?

When such dplyr fix will be pushed to CRAN? Is it common people using dplyr dev version for production?

Cheers.

**Comment by lionel-** [comment]
>  Kindly confirm it runs in your machine.

I get "UTF-8" for the first and "latin1" for the second.

> When such dplyr fix will be pushed to CRAN? Is it common people using dplyr dev version for production?

It should be on CRAN sometime next week, so not much longer to wait :)
