### ISSUE TITLE
Why plyr disturbs dplyr?

### ISSUE THREAD

**Issue by parischan** [tidyverse/dplyr#2806]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the mailing list <https://groups.google.com/forum/#!forum/manipulatr> or http://stackoverflow.com.

Please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://github.com/jennybc/reprex#what-is-a-reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.  

Delete these instructions once you have read them.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by lionel-** [comment]
you should load plyr first then dplyr
