### ISSUE TITLE
Inconsistent behaviour of select_vars and mix of positive and negative signs

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverse/dplyr#2808]
I'm wondering what the desired behaviour should be when `select_vars` is called with a mixture of positive and negative signs.

For example:
```
select_vars(vars=names(mtcars), cyl, mpg)   # all +ve: ok
  cyl   mpg 
"cyl" "mpg" 

> select_vars(vars=names(mtcars), cyl, -mpg)   # +ve and -ve: latter is ignored
  cyl 
"cyl" 

> select_vars(vars=names(mtcars), c(cyl, -mpg))  # combined into a single arg: error
Error in combine_vars(vars, ind_list) : 
  Each argument must yield either positive or negative integers
```

Conceptually, I don't see the difference between the latter two examples. Absent any reason to think otherwise, I would assume that `select_vars(*, x1, x2)` should give the same result as `select_vars(*, c(x1, x2))`.

(My preference would be to throw an error if signs are mixed, but I'm easy.)

**Comment by hadley** [comment]
The convention we've chosen is that each argument must be all positive or negative to avoid problems like `-mpg:cyl`. I'm happy with the error for now.

**Comment by Hong-Revo** [comment]
I'm happy with the error too. But for consistency, that implies the 2nd example should give an error as well.

**Comment by hadley** [comment]
It only applies to single arguments. `select(df, x, y)` is not the same as `select(df, c(x, y))`

**Comment by Hong-Revo** [comment]
You'll have to explain that one to me. How are they not the same?

**Comment by hadley** [comment]
By definition. `select()` could have been defined in such a way that they were equivalent, but it wasn't.
