### ISSUE TITLE
Problem variables "."

### ISSUE THREAD

**Issue by kaji331** [tidyverse/dplyr#2809]
This is a simple question. When one column name of data.frame is ".", filter function will return error "Problem variables : "."" even I did not use this column name in filter function. I think this is because of the mechanism of dplyr, but some temporary operations which are very convenient would create "." column name that I won't use. 

Could you please change this feature?

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by kaji331** [comment]
This is the sample code and data.


________________________________
发件人: Hadley Wickham <notifications@github.com>
发送时间: 2017年5月22日 20:27
收件人: tidyverse/dplyr
抄送: kaji331; Author
主题: Re: [tidyverse/dplyr] Problem variables "." (#2809)


Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you<https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif>!

If you've never heard of a reprex before, start by reading "What is a reprex<https://github.com/jennybc/reprex#what-is-a-reprex>", and follow the advice further down the page.

―

**Comment by hadley** [comment]
You didn't provide any data or code

**Comment by kaji331** [comment]
[dplyr_test.zip](https://github.com/tidyverse/dplyr/files/1024173/dplyr_test.zip)
Sorry. I just replied by email attachment.

**Comment by kaji331** [comment]
I tried to give a simpler code, but I found that if I didn't follow the code in dplyr_test.zip, I got another errors (I couldn't find any column names by filter) after I named a column "." like colnames(data)[163] <- "."

I am trying to find the rules for reproducing this problem.

**Comment by lionel-** [comment]
Could you paste the code here between fences (triple backticks) please.

**Comment by kaji331** [comment]
I repeat the new errors in  #2821

**Comment by kaji331** [comment]
test.R
```r
library(pipeR)
library(dplyr)
temp <- read.table("cnvr_table.tsv",sep="\t",header=T,row.names=1)
temp <- apply(temp[,1:3],1,function(x) paste(x,collapse="_")) %>>% sapply(function(x) gsub(" +","",x),simplify=T) %>>% (cbind(temp,.))
temp <- cbind(temp,cytoBand[match(temp[,161],cytoBand[,9]),c(2,9)])
temp <- temp[!is.na(temp[,162]),]
filter(temp,V2 == "1p36.22") %>>% dim
colnames(temp)[162] <- "cyto"
filter(temp,cyto == "1p36.22") %>>% dim
```

**Comment by kaji331** [comment]
test.R
```r
load("test.rda")
library(pipeR)
library(dplyr)
temp <- read.table("cnvr_table.tsv",sep="\t",header=T,row.names=1)
temp <- apply(temp[,1:3],1,function(x) paste(x,collapse="_")) %>>% sapply(function(x) gsub(" +","",x),simplify=T) %>>% (cbind(temp,.))
temp <- cbind(temp,cytoBand[match(temp[,161],cytoBand[,9]),c(2,9)])
temp <- temp[!is.na(temp[,162]),]
filter(temp,V2 == "1p36.22") %>>% dim
colnames(temp)[162] <- "cyto"
filter(temp,cyto == "1p36.22") %>>% dim
```
