### ISSUE TITLE
Feature request: dplyr verb for setting column names

### ISSUE THREAD

**Issue by danielcnorris** [tidyverse/dplyr#2810]
Sometimes when data munging, I want to be able to reset all of the column names for a data frame. Dplyr's ```rename``` feels tedious for this purpose (though perhaps safer against bugs). Using base R's ```names``` or the like breaks the flow of my pipeline and requires creating a new, temporary variable. I'd like a variadic verb that works like the following:

```r
df %>%
  set_names(col1, col2, col3)
```

Thoughts?

Thank you.

**Comment by thomasjwood** [comment]
`magrittr::set_colnames(col1, col2..)`?

**Comment by danielcnorris** [comment]
Perfect. Thanks!

**Comment by lionel-** [comment]
you can also use `rlang::set_names()` which now takes dots and also supports implicit splicing of lists of character vectors.

**Comment by danielcnorris** [comment]
Thanks @lionel-!
