### ISSUE TITLE
Selecting variables named 'NA' doesn't work

### ISSUE THREAD

**Issue by seanchrismurphy** [tidyverse/dplyr#2815]
Perhaps this is working as intended, but this stumped me for a good long while. I'm working with affect data, and among data of that sort it's common to have variables for negative affect called 'na'. Usually not a problem as R knows the difference between character 'NA' and missing data NA. However, select_ doesn't - if NA is among a list of variable names to be selected it gives the following error:

> Error: All select() inputs must resolve to integer column positions.
> The following do not:
> *  "NA"

Regardless of whether the variable in question is in the dataset or not. 

```
test <- data.frame('id' = 1:100, 'NA' = rnorm(100))

select_(test, 'NA')
```

**Comment by lionel-** [comment]
`data.frame()` is creating a column called `NA.`. But using tibble works:

```r
test <- tibble('id' = 1:100, 'NA' = rnorm(100))
select(test, `NA`)
```

Note you have to quote `NA` with backticks otherwise R isn't looking for a symbol named NA but returns the missing value. E.g.:

```r

`NA` <- "foo"
NA
#> [1] NA

`NA`
#> [1] "foo"
```

**Comment by seanchrismurphy** [comment]
Yeah, I hadn't realised that - my actual data.frame has a column named NA. 

But if I fix my example: 

```
test <- data.frame('id' = 1:100, 'NA' = rnorm(100))
colnames(test) <- c('id', 'NA')
```

Then I can call my column from the dataframe without backticks, as below, which seems inconsistent with the select functioning:
```
test['NA']
```

Although the following does fail:

```
test$NA
```

**Comment by lionel-** [comment]
> Then I can call my column from the dataframe without backticks

Yes but you're selecting with a string rather than a symbol there. In the new version of dplyr you can select with strings as well, so `select(test, "NA")` works as well.

> Although the following does fail:

That's beause `$` takes a symbol. If you use backticks it works:

```r
test$`NA`
```
