### ISSUE TITLE
Use select helpers inside group_by()

### ISSUE THREAD

**Issue by jankislinger** [tidyverse/dplyr#2818]
It would be useful if group_by() function could take benefits from select helpers. Some `dplyr` functions (other than `select`) already work with these helpers (e.g. `mutate_at`).

```r
require(dplyr, warn.conflicts = F, quietly = T)
df <- data_frame(g1 = rep(letters[1:3], 5), g2 = rep(letters[1:3], each = 5)) %>% 
  mutate(x = seq_len(n()), y = runif(n()))
group_by(df, starts_with("g"))
#> Error in mutate_impl(.data, dots): wrong result size (0), expected 15 or 1
```

**Comment by lionel-** [comment]
That's out of scope for `group_by()` because it has mutate semantics, but we now have `group_by_at()` which allows what you want. See http://dplyr.tidyverse.org/articles/dplyr.html#patterns-of-operations for more information.

**Comment by jankislinger** [comment]
Thanks for fast response. I will check that
