### ISSUE TITLE
Feature request: dplyr generic way to get table name and data source

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2824]
Feature request: it would be very handy to have a dplyr generic way (that is commands that are part of dplyr that simultaneously work with multiple data providers such as Spark, PostgreSQL, and SQLite) to get table name and data source.  

Below I have a reprex showing example implementations of the two functions I would like ( table_name and data_source ) with ad-hoc implementations that work by looking directly into the dplyr 0.5.0 Spark data structures (obviously not the right way for external code, as this is unlikely to be stable across different data providers and dplyr versions).

The utility is: if you have handle to remote data you may want to delete the underlying data at some point as part of a clean up.  The data_source has the additional use for copy_to as is already an option in the dplyr join verbs.

``` r
suppressPackageStartupMessages(library("dplyr"))
my_db <- sparklyr::spark_connect(version='2.0.2', 
                                 master = "local")
d <- copy_to(my_db, data.frame(x=1:3), 'dsparkname')

# would like a version of this function that works
# accross multiple dplyr data sources: 
#  Spark, PostgreSQL, RSQLite, ...
# should return NULL if d is local data (data.frame/ tibble)
# should return NULL if d is not a trivial query.
table_name <- function(d) {
  as.character(d$ops$x)
}

# would like a version of this function that works
# accross multiple dplyr data sources: 
#  Spark, PostgreSQL, RSQLite, ...
# should return NULL if d is local data (data.frame/ tibble)
data_source <- function(d) {
  d$src$con
}

# The above two functions would let us write
# code such as the following:

name <- table_name(d)
dataSource <- data_source(d)

db_drop_table(dataSource, name)

sparklyr::spark_disconnect(my_db)
```

**Comment by JohnMount** [comment]
Closed https://github.com/rstudio/sparklyr/issues/711 in favor of this request.

**Comment by hadley** [comment]
I agree that a `data_source` method (possible with a more specific name, like `dbi_con`) is a good idea.

But there's no guarantee that a data source has an underlying table. What should happen in that case?

**Comment by JohnMount** [comment]
> possible with a more specific name, like dbi_con

I'll leave names to you, I doubt I can pick names that would meet all intended package conventions.

> But there's no guarantee that a data source has an underlying table. What should happen in that case?

I think that would be covered by the "hould return NULL if d is not a trivial query" idea.  If the data source doesn't have an underlying table, it likely has a non-trivial SQL query.  Finding names to no-longer needed intermediates (effects of *_join(copy=TRUE) in particular) is necessary to free intermediates in production environments (where you can't always wait for db_disconnect to tear everything down).
