### ISSUE TITLE
select_() called with string argument doesn't throw

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2827]
Current master:

``` r
f <- function(data, ...) dplyr::select_(data, .dots = lazyeval::lazy_dots(...))
f(mtcars[1,], "vs")
#>           vs
#> Mazda RX4  0
```

dplyr 0.5.0:

``` r
f <- function(data, ...) dplyr::select_(data, .dots = lazyeval::lazy_dots(...))
f(mtcars[1,], "vs")
#> Error: All select() inputs must resolve to integer column positions.
#> The following do not:
#> *  "vs"
```

Responsible for downstream failures in assertr. @lionel-: Is this intended?

**Comment by hadley** [comment]
This was deliberate to make it more compatible with `pull()`

**Comment by krlmlr** [comment]
Why does this need to affect the `select_()` compatibility layer?

**Comment by hadley** [comment]
Because it would require another special case. Why does the absence of a dplyr error cause an assertr test to fail?

**Comment by krlmlr** [comment]
This is what assertr tests, I'm not sure if their interface relies on this particular behavior, probably not. We might just close this and alert assertr maintainers once more. CC @tonyfischetti
