### ISSUE TITLE
copy_to does not recognize schemas

### ISSUE THREAD

**Issue by dkulp2** [tidyverse/dplyr#2829]
`copy_to` doesn't work well with schema (at least in Postgres). 

- Table names that include schemas are treated as non-standard table names with dots in their name, instead of creating them in the named schema. 
- Using `search_path` allows dplyr to read and create tables in the correct schemas, but `copy_to` refuses to write a table if it exists in any other schema,

```r
library(dplyr)
library(RPostgreSQL)

db <- src_postgres()

dbGetQuery(db$con, "CREATE SCHEMA t1")
df <- data.frame(A=letters)

# This (wrongly?) creates a table public."t1.df" 
copy_to(db, df, temporary=FALSE, name="t1.df")

dbGetQuery(db$con, "set search_path=t1")
copy_to(db, df, temporary=FALSE)  # successfully creates table t1.df

dbGetQuery(db$con, "set search_path=public")

# This refuses to create public.df with "Error: Table df already exists."
copy_to(db, df, temporary=FALSE)  

```

**Comment by hadley** [comment]
This is fixed in the dev version, which will be available on CRAN next week.  See `?dbplyr::dbplyr::in_schema`.
