### ISSUE TITLE
dplyr v0.6: summarise_at/mutate_at (vars) out of boundaries in SE evaluation

### ISSUE THREAD

**Issue by DasHammett** [tidyverse/dplyr#2834]
In dplyr v0.6, summarise_at and mutate_at `vars` selection goes out of boundaries if top end is set to `ncol(.)`

```r
test <- function(attribute,group) {
  att <- enquo(attribute)
  grp <- enquo(group)
  mtcars %>%
    group_by(!!grp) %>%
    summarise_at(vars(3:ncol(.)),funs(sum(.)/sum((!!att) == 4)))
}

test(cyl,am)
 Error in combine_vars(vars, ind_list) : Position must be between 0 and n 
```

However, setting `vars` to reach `(ncol(.)-1)` give expected results

```r
test <- function(attribute,group) {
  att <- enquo(attribute)
  grp <- enquo(group)
  mtcars %>%
    group_by(!!grp) %>%
    summarise_at(vars(3:(ncol(.)-1)),funs(sum(.)/sum((!!att) == 4)))
}

test(cyl,am)
# A tibble: 2 x 9
     am      disp       hp     drat        wt   qsec       vs     gear     carb
  <dbl>     <dbl>    <dbl>    <dbl>     <dbl>  <dbl>    <dbl>    <dbl>    <dbl>
1     0 1839.0667 1015.000 20.81333 23.869667 115.16 2.333333 20.33333 17.33333
2     1  233.2375  206.125  6.58125  3.917875  28.21 0.875000  7.12500  4.75000
```

**Comment by hadley** [comment]
What do you expect . to be bound to in `vars()`? Why not drop the first two columns instead?

**Comment by DasHammett** [comment]
Hi, 

I would expect . to be bound to the df I am passing to `summarise_at` in the pipes. Unfortunately I cannot drop the first columns as I need them later on for further processing.

My wild guess is that `vars()` is not correctly defining the boundaries where `funs()` needs to be applied when you supply programmatically the range of columns. It would seem that `vars(n:ncol(.))` is extending the last column position by 1, giving the error message above (given I understand correctly the error). 

For example, if the df has 8 columns, `vars(4:ncol(.))` `summarise_at` applies `funs()` to columns 4 to 9. Since there are not 9 columns in the df, we get the error message. Reason also why `vars(4:(ncol(.)-1)` would correctly set the boundaries for `funs()` to be applied.

In dplyr v0.5 the code works correctly, but I have seen this regression in v0.6rc

**Comment by hadley** [comment]
I think it's that . doesnt mean anything inside vars. Just use `vars(-(1:2))` instead

**Comment by lionel-** [comment]
You should be able to use the pronoun `.data`. You cannot currently use `ncol()` with data sources, but `length()` works:

```r
select_at(mtcars, vars(2:length(.data)))
```
