### ISSUE TITLE
dplyr v0.6rc Column position in summarise_at/mutate_at

### ISSUE THREAD

**Issue by DasHammett** [tidyverse/dplyr#2837]
In `summarise_at()`and `mutate_at()`, `vars()` column position is modified if there is a grouping variable 

It would seem that the column(s) used for `group_by()` are removed from `vars()` before passing them to `funs()`
```r
iris %>% select(Species,everything()) %>% head()

  Species Sepal.Length Sepal.Width Petal.Length Petal.Width
1  setosa          5.1         3.5          1.4         0.2
2  setosa          4.9         3.0          1.4         0.2
3  setosa          4.7         3.2          1.3         0.2
4  setosa          4.6         3.1          1.5         0.2
5  setosa          5.0         3.6          1.4         0.2
6  setosa          5.4         3.9          1.7         0.4
```
I have moved Species column to better illustrate `summarise_at()` behaviour. From `head()` we can see that columns 2 to 4 are from `Sepal.Length` to `Petal.Length`.
```r
iris %>% select(Species,everything()) %>% 
   group_by(Species) %>% 
   summarise_at(vars(2:4),funs(min))

# A tibble: 3 x 4
     Species Sepal.Width Petal.Length Petal.Width
      <fctr>       <dbl>        <dbl>       <dbl>
1     setosa         2.3          1.0         0.1
2 versicolor         2.0          3.0         1.0
3  virginica         2.2          4.5         1.4
```

`summarise_at()`seems to remove the grouping column from the intermediate internal df and starts the `funs()` at `Sepal.Width`, as column 1 is `Sepal.Length` instead of `Species`.

Is that expected behaviour in this rc? This behaviour is not found in v0.5. This new behaviour might be giving incorrect calculation without warnings to existing code.

**Comment by hadley** [comment]
This is somewhat expected. I really don't think it's a good idea to specify variables by position, so I don't plan to make any changes here.
