### ISSUE TITLE
dplyr Update Error in Rstudio: cannot update package ... "non-zero exit code"

### ISSUE THREAD

**Issue by sfd99** [tidyverse/dplyr#2846]
Using:
  - _latest version_ of Rstudio + R 340,
  - Linux Ubuntu 14.04 32 bit.

Have **tidyverse** package working fine.

Today, 
when I click on the _Rstudio [Update] PKGS button_
it offers a **dplyr** update (v 0.5.0 to 0.7.0).
I select this dplyr PKG update.

But...the **dplyr** update 
ends in a "non-zero exit code" error, (see details below).

_DETAIL of install dplyr update output_:
.........<lots of compilation code, then...>
installing to /home/me/R/i686-pc-linux-gnu-library/3.4/dplyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading

**Error in unloadNamespace(pkg_name) : 
  namespace ‘dplyr’ is imported by ‘broom’ so cannot be unloaded 
                                  (  # MY NOTE.... "broom" PKG is not even loaded in my WS !)**
* removing ‘/home/me/R/i686-pc-linux-gnu-library/3.4/dplyr’
* restoring previous ‘/home/me/R/i686-pc-linux-gnu-library/3.4/dplyr’

Warning in install.packages :
  installation of package ‘dplyr’ had **non-zero exit status**

The downloaded source packages are in
	‘/tmp/RtmpUHMcW7/downloaded_packages’

So, dplyr version 0.7.0 was not installed...HELP!

**Comment by hadley** [comment]
I'd recommend trying to install again in a clean R session.
