### ISSUE TITLE
dplyr::union_all with SQLite errors out if data is "headed"

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2858]
dplyr::union_all errors out if data is "headed", adding the commented out compute step back in fixes the issue. Also filed as [RSQLite 215](https://github.com/rstats-db/RSQLite/issues/215).

``` r
suppressPackageStartupMessages(library('dplyr'))
packageVersion('dplyr')
#> [1] '0.7.0'
packageVersion('dbplyr')
#> [1] '1.0.0'
my_db <- dplyr::src_sqlite(":memory:", create = TRUE)
dr <- dplyr::copy_to(my_db,
                     data.frame(x=c(1,2),y=c('a','b'),
                                stringsAsFactors = FALSE),
                     'dr',
                     overwrite=TRUE)
dr <- head(dr,1)
# dr <- compute(dr)
print(dr)
#> # Source:   lazy query [?? x 2]
#> # Database: sqlite 3.11.1 [:memory:]
#>       x     y
#>   <dbl> <chr>
#> 1     1     a
print(dplyr::union_all(dr,dr))
#> Error: SQLite does not support set operations on LIMITs
```

**Comment by hadley** [comment]
There's nothing we can do here - SQLite doesn't support this SQL.

**Comment by JohnMount** [comment]
I thought to report it here, as `dbplyr`'s description says: "If you find any bugs, please file in dplyr."  And I thought one of the roles of `dbplyr` was dealing with variations in `SQL` dialects.

**Comment by hadley** [comment]
Yes, dbplyr will work around minor variations. But there's nothing I can do when a database simply does not support a feature.
