### ISSUE TITLE
bug if rename with var

### ISSUE THREAD

**Issue by thomasbrand** [tidyverse/dplyr#2861]
I use dplyr 0.7.

I want to rename one column of the mtcars dataframe.

No problem if I type :
```r
df <- mtcars %>% 
  rename(variable=vs)
```
But if I type

```r
df <- mtcars %>% 
  rename(var=vs)
```
I obtain "Error: All arguments must be named".

Thank you.

**Comment by lionel-** [comment]
Thanks, this is now fixed
