### ISSUE TITLE
dplyr "mutate" gives error in Sweave file

### ISSUE THREAD

**Issue by jtrommel** [tidyverse/dplyr#2864]
---

Brief description of the problem
I have a Sweave document that includes an example from your book "R for Data Science". With the new version of dplyr execution stops with the message "argument value is missing with no default". Removing this example from the Sweave file reproduces the same error in the next calculation where I use "mutate".
When I re-install dplyr version 0.5.0 the error disappears. 
```r
# insert reprex here
<<>>=
diamonds %>% mutate(y=ifelse(y < 3 | y > 20, NA, y)) -> diamonds2
@
```

**Comment by hadley** [comment]
Please provide a reproducible example using the reprex package.
