### ISSUE TITLE
programming vignette: object named "group_by"

### ISSUE THREAD

**Issue by davharris** [tidyverse/dplyr#2865]
In the dplyr programming vignette, the following code is suggested:

```
my_summarise <- function(df, group_by) {
  group_by <- enquo(group_by)
  print(group_by)

  df %>%
    group_by(!!group_by) %>%
    summarise(a = mean(a))
}
```

If I understand correctly, this code uses `group_by` to refer to a variable to use for grouping (the argument) and also to refer to the `group_by` verb. 

If so, wouldn't it be better to name the argument `group_var`, as in the preceding examples?  The current naming approach seems more confusing than it needs to be.

Sorry if I'm misunderstanding something.

**Comment by hadley** [comment]
Yes, that would be great. Want to do a PR?

**Comment by markdly** [comment]
I've added a pull request for this in #2901 and also updated the other examples where this occurred.  I'm rather new to this so apologies if this is poor etiquette / incorrect procedure...
