### ISSUE TITLE
 std::bad_alloc with database

### ISSUE THREAD

**Issue by RobertMyles** [tidyverse/dplyr#2866]
Hi, I'm having an `Error in new_result(connection@ptr, statement) : std::bad_alloc` error  (raised in #2323 -- I've also followed the instructions there and I'm using the dev version of odbc) when I try to use dplyr/dblpyr with a Microsoft SQL Database. I've read that this may be to do with Rcpp, so I've re-installed dplyr, dblpyr and Rcpp without success. 

```r
library(DBI)
library(dplyr)
library(dbplyr)
con <- dbConnect(odbc::odbc(),
                 driver = "Microsoft SQL Server",
                 dsn = "tblEmpenhos", 
                 server = "SERVER")
```

I can connect to the base with no problems:  
```r
class(con)

[1] "Microsoft SQL Server"
attr(,"package")
[1] ".GlobalEnv"
```
And `dbListFields(con, "tblEmpenhos")` gives me all the correct column names. But using this gives the error:  
```r
tbl(con, "tblEmpenhos")
Error in new_result(connection@ptr, statement) : std::bad_alloc
```

I thought this error had to do with memory allocation, but that can't be right in this case. Is there anything else I could check?

**Comment by hadley** [comment]
Can you please file at http://github.com/rstats-db/odbc/issues? It's almost certainly a odbc issue.

And can you please use reprex to create your reproducible example?

**Comment by RobertMyles** [comment]
Sorry, I thought it was reltade to `tbl()`, my mistake. Over on `odbc`now, thanks.
