### ISSUE TITLE
Feature request: return error when errant column used in distinct()

### ISSUE THREAD

**Issue by RickPack** [tidyverse/dplyr#2867]
Can dplyr error out when one identifies a variable that does not exist in the data frame?

```r
## No error returned despite aa not appearing in the complimentary R data frame named "cars"
df <- cars %>% distinct(aa)

```

**Comment by holgerbrandl** [comment]
Still broken in dplyr_0.7.2. Was it moved to a later release?

**Comment by foo-bar-baz-qux** [comment]
@holgerbrandl yes, the change appears to be reverted and moved to v0.9 (probably)
