### ISSUE TITLE
nrow returns NA on dbplyr backed table

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2871]
nrow returns NA on dbplyr backed table.  I know counting the rows is a potentially expensive operation (which is why it is left out of the print summary), but if code is explicitly asking for it it may be worth supplying.

``` r
# set up
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.0'
packageVersion("dbplyr")
#> [1] '1.0.0'

d <- data.frame(x = 1:3)

# expected behavior
nrow(d)
#> [1] 3

# db vector behavior (throws)
dS <- dbplyr::memdb_frame(x = 1:3)
print(dS)
#> # Source:   table<ziexcrtofu> [?? x 1]
#> # Database: sqlite 3.11.1 [:memory:]
#>       x
#>   <int>
#> 1     1
#> 2     2
#> 3     3
nrow(dS)
#> [1] NA
```

**Comment by edgararuiz** [comment]
hey @JohnMount! , 

Does `dS %>% tally` work?

**Comment by JohnMount** [comment]
Yes, `tally` works.

```r
dS %>% tally
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.11.1 [:memory:]
#>       n
#>   <int>
#> 1     3
```

**Comment by edgararuiz** [comment]
@hadley  - Would masking the `base::nrow()` function be an acceptable solution this?  

I tried that in my fork and it worked:

```
> dS <- dbplyr::memdb_frame(x = 1:3)
> nrow(dS)
[1] 3
```
And I also confirmed that it works with a regular DB connection like MS SQL:

```
con
m <- tbl(con, "airports")
class(m)
nrow(m)
nrow(tbl(con, "airports"))
```

```
<OdbcConnection> rstudioadmin@EC2AMAZ-O5QKKM8
  Database: airontime
  Microsoft SQL Server Version: 12.00.4422
[1] "tbl_dbi"  "tbl_sql"  "tbl_lazy" "tbl"     
[1] 1396
[1] 1396
```

Here are the code changes,  I basically added an `UseMethod` for `nrow()`,  then created a `default` method as a 'catch-all', and then added a `tbl_sql` method:

https://github.com/tidyverse/dbplyr/compare/master...edgararuiz:master

If it's acceptable, I'll be glad to send a PR for this.

**Comment by lionel-** [comment]
You can probably solve this more cleanly by providing `dim()` methods.

**Comment by edgararuiz** [comment]
Thanks @lionel- ! you're absolutely right! I didn't notice the `dim.tbl_sql()` function until you mentioned it.  That's is the reason why `NA` is consistently returned.  I moved the dplyr row count verbs from `nrow()` to `dim()`.  Does that look better to you?: https://github.com/tidyverse/dbplyr/compare/master...edgararuiz:master

**Comment by edgararuiz** [comment]
Added one more change to ensure column count is returned as part of `dim()`
https://github.com/tidyverse/dbplyr/compare/master...edgararuiz:master

**Comment by hadley** [comment]
Not overriding `dim()` or `nrow()` in this way is a deliberate choice. Part of the API of `dim()` is that it is a cheap operation. Computing the number of rows in a query is an expensive operation so I strongly believe that it should not be computed by `dim()` (but a different function would be fine).

**Comment by michaellevy** [comment]
What would you think of a warning for `dim.tbl_sql` that points the user to `tally`?
