### ISSUE TITLE
R 3.4: Error in : 'src_sql' is not an exported object from 'namespace:dplyr'

### ISSUE THREAD

**Issue by karrtikiyer-tw** [tidyverse/dplyr#2873]
After upgrade to R 3.4
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin16.6.0 (64-bit)
I am getting below error while using src_pool
Error in : 'src_sql' is not an exported object from 'namespace:dplyr'
dplyr version is 0.7.0
pool version is 0.1.0
RMySQL version is 0.10.11

---

Brief description of the problem

```r
 SRC_POOL <- src_pool(pool)
```

**Comment by hadley** [comment]
Please wait for an updated version of pool, and in the future please use the reprex package to make a reproducible example.

**Comment by karrtikiyer-tw** [comment]
Thanks for the update. Is there any workaround for the same till a new
version of pool is out? If no, any time line by which I can expect the new
version of pool?
Regards,
Karrtik

**Comment by hadley** [comment]
We are working on it.

**Comment by karrtikiyer-tw** [comment]
Thanks, please do notify once a new version of pool is available.
