### ISSUE TITLE
Prevent including ORDER BY for Window Functions (dbplyr)

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/dplyr#2874]
We need to find the best way to prevent including `ORDER BY` in a subquery when we use `arrange()` and a window function.  It seems that is an issue for MS SQL, but not other databases: 

```
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: HY000: The ORDER BY clause is invalid in views, 
inline functions, derived tables, subqueries, and common table expressions, 
unless TOP, OFFSET or FOR XML is also specified., Statement(s) could not be 
prepared.,  
Failed to execute SQL chunk
```

A possible solution would be to use the approach @ianmcook used in his implyr package: https://github.com/ianmcook/implyr/commit/08a704a130104582c4b531817fd4016980f65114

**Comment by ianmcook** [comment]
This is an issue for Impala too. From [the Impala ORDER BY docs](https://www.cloudera.com/documentation/enterprise/latest/topics/impala_order_by.html):
> If an ORDER BY clause is applied to an early phase of query processing, such as a subquery or a view definition, Impala ignores the ORDER BY clause. To get ordered results from a subquery or view, apply an ORDER BY clause to the outermost or final SELECT level.

Impala issues a warning but does not error out. But somewhere between Impala and DBI (could be in the ODBC or JDBC drivers) the warning is lost, so it is not displayed in R.

**Comment by ianmcook** [comment]
I should also add that the new `sql_optimise()` has reduced this problem greatly by eliminating unnecessary subqueries.

**Comment by edgararuiz** [comment]
@ianmcook - You're right, I ran the same query inside HUE and even though it completes, there is a warning in the Log: 

```
Query 6c4a5deca41acb89:620e8dab72c6b390 100% Complete (1 out of 1)
Ignoring ORDER BY clause without LIMIT or OFFSET: ORDER BY mpg ASC.
An ORDER BY appearing in a view, subquery, union operand, or an insert/ctas statement has no effect on the query result unless a LIMIT and/or OFFSET is used in conjunction with the ORDER BY.
```

**Comment by hadley** [comment]
One option is to avoid using `arrange()` in favour of individual `order_by()` statements around each expression. This isn't particularly easy but at least allows you to express what you need to.

Another possible option (combining with the needs of https://github.com/tidyverse/dplyr/issues/2593) would be to provide a new `window()` function that would let you more directly set window parameters. I think there are two possible APIs:

1.  Make it work like `mutate()`, but with extra options:

    ```R
    df %>%
      group_by(gvgkey) %>%
      window(
        .order = vars(datadate),
        .frame = (-3, 0),
        
        sale_ttm = sum(sale),
        cogs_ttm = sum(cogs),
        sga_ttm = sum(sga)
      )
    ```

1.  Provide two variants for explicitly setting the order and frame:

    ```R
    df %>%
      group_by(gvgkey) %>%
      window_frame(-3, 0) %>%
      window_order(datadata) %>%
      mutate(sale_ttm = sum(sale),
        cogs_ttm = sum(cogs),
        sga_ttm = sum(sga)
      )
    ```
    
The second option seems cleaner to me, and I don't think it should be too hard to implement. It just requires the two functions (which would have `group_by()` semantics) and two new ops functions for extract the current window frame and window order (I don't think partition is necessary as group by seems adequate).

**Comment by hadley** [comment]
Adding @iangow since he might have thoughts about the API.

**Comment by iangow** [comment]
Second option seems awesome and a bit easier to understand/document than the former.

I guess what comes out of the `window_order` function in the pipeline above is a "data frame" (forgive lack of precision with term) with `group_by`, `window_frame`, and `window_order` attributes that cause `mutate` to be behave appropriately with functions like `sum`. This seems analogous to what happens already with `mutate` applied to  a "data frame" with a `group_by` (or `Groups`) attribute.

**Comment by hadley** [comment]
@iangow yes exactly!
