### ISSUE TITLE
dbplyr: Truncated error messages

### ISSUE THREAD

**Issue by vergilcw** [tidyverse/dplyr#2876]
Hi,

I'm using dbplyr from Linux with kerberos authentication to a SQL Server 2016 database. Standard dplyr verbs seem to be working fine, but a few operations seem to give errors.  However, those errors are truncated so I don't actually get the substance of the message.

I don't have a reprex as I'm unable to create a public-facing database.  I have pasted my code and the errors below:

```r
library(dplyr)
library(dbplyr)
library(DBI)

con_odbc <- dbConnect( 
  odbc::odbc(),  #don't need to load the odbc package, it's only called here
  .connection_string = paste0("driver=SQL Server Native Client 11.0;", 
                              "server=servername.junkdomain.local;", 
                              "database=AbTables;", 
                              "trusted_connection=yes;") 
)

copy_to(con_odbc, nycflights13::flights, "flights",
        temporary = FALSE,
        indexes = list(
          c("year", "month", "day"),
          "carrier",
          "tailnum",
          "dest"
        )
)
```

This gives the following error:
```
Error in eval(substitute(expr), envir, enclos) : 
  <SQL> 'CREATE INDEX "flights_year_month_day" ON "flights" ("year", "month", "day")'
  nanodbc.cpp:1587: 42000: [Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot find the o
```

As you can see it's truncated.  At first I thought it said: "Cannot find the covfefe" but that was just my imagination. :)  Note that I don't have any trouble uploading the table using the dbWriteTable() function from DBI

Any tips on how I might dig under the hood and get the full error message so I can file a more useful issue would be appreciated.

**Comment by hadley** [comment]
This is most likely due to the underlying odbc driver, so can you please file the issue at http://github.com/rstats-db/odbc/issues ?

**Comment by vergilcw** [comment]
Sure, thanks!
