### ISSUE TITLE
Simplify DSL for testing hybrid evaluation

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2880]
The `test-hybrid.R` file has test cases that verify if a particular expression is evaluated with hybrid evaluation or not. Most test cases use `check_{not_}hybrid_result()` and `expect_{not_}hybrid_error()` to test

- if an expression uses hybrid evaluation
- if the result of the evaluation matches normal R evaluation

It is a concise way of writing these test cases, the logic is implemented in `helper-hybrid.R` and `hybrid.R`.

This issue is about documenting the logic and perhaps make it more accessible through simplification

- [ ] Document entry points for the test cases
- [ ] Describe testing logic and some internals
- [x] Get rid of underscore functions (with `_` suffix)
- [ ] A better syntax, perhaps:
    ```r
    check_hybrid_summary(
      a = 1:5,
      mean(a),
      expect_identical(., 3)
    )
    check_hybrid_eval(
      a = 1:5,
      lag(a),
      expect_identical(., c(NA, 1:4))
    )
    ```

https://github.com/tidyverse/dplyr/pull/2879#discussion_r122428639

CC @hadley @lionel-.

**Comment by romainfrancois** [comment]
I don't think we still need that. #3822 has a more recent comment about what testing hybrid needs.
