### ISSUE TITLE
Summarize clears group_vars attribute

### ISSUE THREAD

**Issue by alex-gable** [tidyverse/dplyr#2882]
Summarize clears group_vars attribute, would expect it to be persisted through transformation
```r
require(tibble)
#> Loading required package: tibble
require(dplyr)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tbl1 <- tibble(x = 1:5, y = x^2)
tbl2 <- tibble(x = 1:5, y = x^3)
tbl3 <- bind_rows(tbl1, tbl2) %>%
          group_by(x) %>%
          summarize( count = n(), z = sum(y) )

tbl4 <- bind_rows(tbl1, tbl2) %>%
          group_by(x)

setequal(group_vars(tbl3), group_vars(tbl4))
```

**Comment by hadley** [comment]
`summarise()` always drops the last group. The reason should become obvious if you ponder on it a bit.

**Comment by alex-gable** [comment]
I looked through the docs and source code for summarise and the reasoning behind the following statement still doesn't make sense to me: 
> "Each summary call removes one grouping level (since that group is now just a single row)". 

This is from the summarise example. In which, the returned tbl group var `cyl` returns not a single, but multiple rows due to the additional group var `vs`. This causes granularity issues if you wanted to join on the group_var or use the group vars to validate whether or not it is a "safe" join.

In this case, I see that `vs` is removed from the attribute, but it's still present in the returned  dataset and part of the grouping which defines the level at which `n_cyl` was computed. 

Looking at the test cases it seems like this behavior is intentional, but it's unclear which problem this solves.

```r
require(dplyr)        
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
mtcars %>%            
    group_by(cyl, vs) %>% 
    summarise(cyl_n = n())
#> # A tibble: 5 x 3
#> # Groups:   cyl [?]
#>     cyl    vs cyl_n
#>   <dbl> <dbl> <int>
#> 1     4     0     1
#> 2     4     1    10
#> 3     6     0     3
#> 4     6     1     4
#> 5     8     0    14
```
