### ISSUE TITLE
Error: package or namespace load failed for ‘dplyr’

### ISSUE THREAD

**Issue by naveen093044** [tidyverse/dplyr#2892]
I'm facing issues with loading package , however there were no issues while installing.
> library(dplyr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘magrittr’
In addition: Warning message:
package ‘dplyr’ was built under R version 3.3.3 
Error: package or namespace load failed for ‘dplyr’

**Comment by hadley** [comment]
Restart R and then install magrittr.
