### ISSUE TITLE
select prints warning for duplicated col names only with helper functions?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/dplyr#2897]
---
if a dataset has duplicated colnames, `select()` throws a different error message depending on whether one quotes the variable directly or uses `starts_with`:

- `select(starts_with(col))` throws a useful and clear error message:  *found duplicated column name:*

- `select(col)` returns an error message that is not very helpful: *Data source must be a dictionary*

Is there a reason for having a different error message for the same problem? Would it make sense to have also the more informative error message for the second case?

```r
library(dplyr)
df <- data_frame(a=1, b=2) %>%
  rename(a=b) 

df %>%
  select(starts_with("a"))

df %>%
  select(a)
         
```

**Comment by lionel-** [comment]
upstream issue: https://github.com/tidyverse/rlang/issues/190
