### ISSUE TITLE
dbplyr - Difference creating WHERE query with filter() when using %in% versus ==

### ISSUE THREAD

**Issue by boshek** [tidyverse/dplyr#2898]
Is this possibly a bug? 

I've been using dplyr tools on a database but got stymied by this issue:

---

```r
## Load libraries and create database
library(dbplyr)
library(dplyr)
  
con <- DBI::dbConnect(RSQLite::SQLite(), path = ":memory:")
copy_to(con, nycflights13::flights, "flights",
        temporary = FALSE, 
        indexes = list(
          c("year", "month", "day"), 
          "carrier", 
          "tailnum",
          "dest"
        )
)
```
When just using data frames, these two approach are equivalent:
```r
identical(
  nycflights13::flights %>%
  filter(carrier %in% c("UA")),
  nycflights13::flights %>%
    filter(carrier == "UA")
)
```

When using dbplyr I am expecting this:
```r
tbl(con, "flights") %>%
  filter(carrier=="UA")
```
To produce the same output as this:
```r
tbl(con, "flights") %>%
  filter(carrier %in% c("UA"))

DBI::dbDisconnect(con)
```
However I get this error message:

> Error in rsqlite_send_query(conn@ptr, statement) : no such table: UA

I understand that these two database subsets produce different SQL queries and that that is why it is throwing an error. But I wonder if this is problematic if the goal is seamless transition between working with database connections and working with data frames. 

Amazing package nonetheless.

**Comment by hadley** [comment]
More minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

mf <- dbplyr::memdb_frame(x = letters)
mf %>% filter(x %in% "a") %>% show_query()
#> <SQL>
#> SELECT *
#> FROM `iwgthndjal`
#> WHERE (`x` IN ('a'))
mf %>% filter(x %in% c("a")) %>% show_query()
#> <SQL>
#> SELECT *
#> FROM `iwgthndjal`
#> WHERE (`x` IN 'a')
```
