### ISSUE TITLE
sql_build.op_mutate() always calls translate_sql_() with window = TRUE

### ISSUE THREAD

**Issue by ianmcook** [tidyverse/dplyr#2899]
dbplyr translates some scalar functions in mutate operations as if they are window functions. This is because `sql_build.op_mutate()` calls `translate_sql_()` without passing the `window` argument, so it always defaults to `window = TRUE`.

Here's a reprex demonstrating what happens in `translate_sql_()`:
```r
variant <- sql_variant(
  sql_translator(.parent = base_scalar, paste0 = sql_prefix("CONCAT")),
  base_agg,
  sql_translator(.parent = base_win, paste0 = win_absent("paste0"))
)
x <- quote(~paste0(foo, bar))
overscope <- dbplyr:::sql_overscope(expr = x, variant = variant, con = NULL, window = TRUE)
dbplyr::escape(rlang::overscope_eval_next(overscope, x))
```
The command `paste0(foo, bar)` should be translated as a scalar function, but it's translated as a window function, resulting in the error from `win_absent()`:
```
 Error: Window function `paste0()` is not supported by this database 
```
Setting `window = FALSE` in the call to `sql_overscope()` gives the expected output:
```
<SQL> CONCAT("foo", "bar")
```

**Comment by hadley** [comment]
Is there any other function that this is going to be a problem for? `paste()` is unusual in that it can be either a vector function or an aggregate function.

**Comment by edgararuiz** [comment]
@ianmcook - I just got home and tested that against an Impala datasource and it worked for me. What is the scalar base and translation that you are using?  My connection is using this one: https://github.com/tidyverse/dbplyr/blob/master/R/db-odbc-impala.R


```

> tbl(con, "newmtcars") %>% 
+   mutate(y = paste0(row_names, row_names))
```

```
# Source:   lazy query [?? x 13]
# Database: Impala 2.5.0-cdh5.7.0[User@Impala/IMPALA]
           row_names   mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
               <chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
 1         Mazda RX4  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
 2     Mazda RX4 Wag  21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
 3        Datsun 710  22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
 4    Hornet 4 Drive  21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
 5 Hornet Sportabout  18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
 6           Valiant  18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
 7        Duster 360  14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
 8         Merc 240D  24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
 9          Merc 230  22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
10          Merc 280  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
# ... with more rows, and 1 more variables: y <chr>
```

```
> show_query({
+   tbl(con, "newmtcars") %>% 
+     mutate(y = paste0(row_names, row_names))
+ })
```
```
<SQL>
SELECT `row_names`, `mpg`, `cyl`, `disp`, `hp`, `drat`, `wt`, `qsec`, 
`vs`, `am`, `gear`, `carb`, CONCAT(`row_names`, `row_names`) AS `y`
FROM `newmtcars`
```

**Comment by ianmcook** [comment]
@hadley `paste()` and `paste0()`. I can't think of any others.

**Comment by ianmcook** [comment]
@edgararuiz The problem only happens when you define translations for `paste()` and `paste0()` in the window functions in `sql_variant()` (which is necessary now, after https://github.com/tidyverse/dbplyr/commit/76b6801e8b6ad90735ee636c48e576e3d74d2813). Impala doesn't support `GROUP_CONCAT()` with window functions, so I set these translations to:
```r
paste = win_absent("paste"),
paste0 = win_absent("paste0"),
```

**Comment by edgararuiz** [comment]
@ianmcook / @hadley - I'm sorry, I'm not sure what I'm missing here.  How would we use `paste` and `paste0` in an aggregate? We don't have them defined as aggregate in the `base_odbc` translations, just scalar.  I have only been able to come up with one way to use them in an aggregate, which is as the grouping variable: 

```
> show_query({
+   tbl(con, "newmtcars") %>% 
+     mutate(y = paste0(row_names, row_names)) %>%
+     group_by(y)%>%
+     summarise(b = mean(mpg))
+ })
```
```
<SQL>
SELECT `y`, AVG(`mpg`) AS `b`
FROM (SELECT `row_names`, `mpg`, `cyl`, `disp`, `hp`, `drat`, `wt`, `qsec`, `vs`, `am`, `gear`, `carb`, CONCAT(`row_names`, `row_names`) AS `y`
FROM `newmtcars`) `igfwhtldyd`
GROUP BY `y`
```

**Comment by ianmcook** [comment]
@edgararuiz Here's an example of using `paste()` in `summarise()` to aggregate a column in a `tbl_df`:

```r
mtcars %>% group_by(cyl) %>% summarise(gears = paste(gear, collapse = ","))
```
This same kind of thing should work with SQL sources. It does with implyr (dev version):
```r
tbl(impala, "mtcars") %>% group_by(cyl) %>% 
  summarise(gears = paste(as.character(gear), collapse = ","))
```
The trouble is: To make that work, I had to add a translations for `paste()` and `paste0()` aggregate functions. But then because of https://github.com/tidyverse/dbplyr/commit/76b6801e8b6ad90735ee636c48e576e3d74d2813 I get a warning saying: `Translator is missing window functions: paste, paste0`. Then when I add translations for `paste()` and `paste0()` in the window functions, dbplyr calls those instead of the scalar translations when they are used in a scalar context.

**Comment by hadley** [comment]
Instead of calling `win_absent()`, the function in the window context could just call the same thing as in the vectorised context. I think that resolves all the problems.   (To do even better you'd inspect the `collapse` argument and switch between behaviours)

**Comment by ianmcook** [comment]
Ah yes, that works. Thanks!
