### ISSUE TITLE
[Design] `case_when(..., .otherwise ~  )` syntactic sugar

### ISSUE THREAD

**Issue by npjc** [tidyverse/dplyr#2900]
I think it is possible to make `case_when(...)` even more friendly to future me (and hopefully others!) by changing the way the default case is written:

### Currently 
```r
case_when(
   x %%  5 == 0 ~ "fizz",
   x %%  7 == 0 ~ "buzz",
   x %% 35 == 0 ~ "fizz buzz",
TRUE ~ as.character(x)             # this default case could be made easier to read/understand
 )
```

### pretty
```r
case_when(
   x %%  5 == 0 ~ "fizz",
   x %%  7 == 0 ~ "buzz",
   x %% 35 == 0 ~ "fizz buzz",
.otherwise ~ as.character(x)
 )
```
### or
```r
case_when(
   x %%  5 == 0 ~ "fizz",
   x %%  7 == 0 ~ "buzz",
   x %% 35 == 0 ~ "fizz buzz",
.otherwise = as.character(x)
 )
```

The `case_when()` code kinda scared me so I figured I would ask before trying to see if I could make it a thing.

**Comment by lionel-** [comment]
maybe a single-sided formula could be treated as the truth branch?

**Comment by hadley** [comment]
The choice to use `TRUE` was deliberate because it's in the same form as all the other branches, and obviously it's always true.
