### ISSUE TITLE
use %<>%

### ISSUE THREAD

**Issue by luca325** [tidyverse/dplyr#2903]
Hello, it would be helpful if `dplyr` could use `%<>%` without loading `magrittr`. So that the example below would work even if `magrittr` is not explicitly loaded. Thank you. Luca

```r
library(dplyr)
dta <- iris
dta %<>% 
  select(Sepal.Length) 
```

**Comment by hadley** [comment]
I'm fundamentally conflicted about `%<>%` so dplyr will not re-export it.
