### ISSUE TITLE
Strange and surprising behaviour of `select_(df, colname)`

### ISSUE THREAD

**Issue by huftis** [tidyverse/dplyr#2905]
I’m not sure if this is a bug or just undocumented intended behaviour, but in any case it is *strange* behaviour. If one writes `select_(df, colname)` and colname is a character vector whose *first* element is the name of a column in `df`, a subset of `df` containing this character column (but no other columns) is returned. Example:

```r
library(dplyr)
myvars = c("Sepal.Width", "Petal.Length")
iris %>% select_(myvars)
```

This returns the same thing that `iris %>% select(Sepal.Width)` would return (note that only the `Sepal.Width` column is returned, not `Sepal.Width` *and* `Petal.Length`). I’m not sure what it is *supposed* to return, but it is certainly surprising behaviour. It’s very easy to accidentally write `select_(df, myvars)` when one means to write `select_(df, .dots = myvars)` (that’s how I discovered this issue), so I think it would be better if the former issued a warning (or an error message), or that the `...` argument is removed from the `select_()` syntax.

I observe this behaviour with dplyr 0.7.1 and the latest GitHub version (as of 2017-06-24).

**Comment by lionel-** [comment]
That's because the old lazyeval takes the first string and ignores the remaining:

```r
lazyeval::as.lazy(letters)
#> <lazy>
#>   expr: a
#>   env:  <environment: base>
```

lazyeval and the SE verbs are not under development anymore.
