### ISSUE TITLE
`arrange()` gives incorrect results for data frames with S4 objects

### ISSUE THREAD

**Issue by huftis** [tidyverse/dplyr#2906]
The `arrange()` function returns incorrect results when a column is an `Interval` object from the `lubridate` package, and I expect this holds for *all* S4 objects. Example:

``` r
library(dplyr)
library(lubridate)
x = as.Date("2017-12-15")
i1 = interval(x, x+10)
i2 = interval(x-500, x-450)
d = data_frame(int = c(i1, i2), ord = 2:1)
d
#> # A tibble: 2 x 2
#>                              int   ord
#>                   <S4: Interval> <int>
#> 1 2017-12-15 UTC--2017-12-25 UTC     2
#> 2 2016-08-02 UTC--2016-09-21 UTC     1
d1 = arrange(d, ord)
d1
#> # A tibble: 2 x 2
#>                              int   ord
#>                   <S4: Interval> <int>
#> 1 2017-12-15 UTC--2018-02-03 UTC     1
#> 2 2016-08-02 UTC--2016-08-12 UTC     2
```

Note that the ‘start’ parts of the intervals seems to not have been sorted at all, while the ‘end’ parts of the intervals is completely wrong, containing dates not in the original tibble (they even contain a date with a year (2018) that wasn’t even mentioned in the original tibble).

Sorting the tibble using the good, old `order()` function works correctly:

``` r
d2 = d[order(d$ord), ]
d2
#> # A tibble: 2 x 2
#>                              int   ord
#>                   <S4: Interval> <int>
#> 1 2016-08-02 UTC--2016-09-21 UTC     1
#> 2 2017-12-15 UTC--2017-12-25 UTC     2
```

The surprising thing is that the `int` column in `d1` (incorrect output) and the `int` column in `d2` (correct output) are *apparently* identical:

```r
> d1$int == d2$int
[1] TRUE TRUE
```

The reason that they are displayed differently (and that they’re not really `identical()`), is because of one of the S4 slots, which had not been rearranged by the `arrange()` function, but which has been rearranged by the `[order(...),]` call:

```r
> d$int@start
[1] "2017-12-15 UTC" "2016-08-02 UTC"
> d1$int@start
[1] "2017-12-15 UTC" "2016-08-02 UTC"
> d2$int@start
[1] "2016-08-02 UTC" "2017-12-15 UTC"
```

So I expect this a bug which happens with *all* S4 objects (possibly related to #2568).

**Comment by krlmlr** [comment]
Thanks for reporting. https://github.com/tidyverse/dplyr/issues/2432 is the canonical issue for this problem.
