### ISSUE TITLE
(dbplyr): mutate(round) quietly clobbers non-numeric columns

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2908]
I have only tested this using RSQLite (so I don't know if it applies to other databases or not), but `dplyr`/`dbplyr` quietly applies round() to non-numeric columns.  The expected behavior (which is also safe and desirable) would be more like what happens with local `data.frame`s: the rounding errors out when it hits non-numeric columns.

reprex:

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.1.9000'
packageVersion("dbplyr")
#> [1] '1.0.0.9000'
packageVersion("RSQlite")
#> [1] '2.0'
packageVersion("magrittr")
#> [1] '1.5'
base::date()
#> [1] "Sat Jun 24 09:58:25 2017"

db <- DBI::dbConnect(RSQLite::SQLite(), 
                     ":memory:")
dL <- data.frame(x = 3.077, 
                 k = 'a', 
                 stringsAsFactors = FALSE)
dR <- dplyr::copy_to(db, dL, 'dR')

dR %>% mutate_all(funs(round(., 2)))
#> # Source:   lazy query [?? x 2]
#> # Database: sqlite 3.19.3 [:memory:]
#>       x     k
#>   <dbl> <dbl>
#> 1  3.08     0
```

Example of desired behavior (an exception warning the user):

``` r
suppressPackageStartupMessages(library("dplyr"))

dL <- data.frame(x = 3.077, 
                 k = 'a', 
                 stringsAsFactors = FALSE)

dL %>% mutate_all(funs(round(., 2)))
#> Error in mutate_impl(.data, dots): Evaluation error: non-numeric argument to mathematical function.
```

**Comment by krlmlr** [comment]
SQLite allows different data types in one column, we'd need to look deeply into the math extension. Could you please file an issue at the RSQLite repo?

**Comment by JohnMount** [comment]
Eeek- I did not know it allowed more than one type per column.  I've re-filed as [RSQLite 225](https://github.com/rstats-db/RSQLite/issues/225).  Thanks for taking the look.
