### ISSUE TITLE
summarise() on grouped tibble returns NA

### ISSUE THREAD

**Issue by tzoltak** [tidyverse/dplyr#2915]
With dplyr 0.7.1 if summarise() is called on a grouped tibble with only one row per group in a "rename-like" manner (as an alternative to calling: ```rename() %>% select()```):

```r
tib = tibble(x = LETTERS[1:3], y = 1:3) %>% group_by(x)
summarise(tib, "my variable" = y)
```

it assigns NAs to all groups but the first unless some operation is made on the variable created with summarise (e.g. ```summarise(tib, "my variable" = identity(y))``` works fine).

**Comment by JohnMount** [comment]
I see the same (even without the quotes), I am pasting it here as a "`reprex`":

``` r
suppressPackageStartupMessages(library("dplyr"))
data.frame(x= 1:2, y= 3:4) %>% group_by(x) %>% summarize(z = y)
#> # A tibble: 2 x 2
#>       x     z
#>   <int> <int>
#> 1     1     3
#> 2     2    NA
```

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = LETTERS[1:3], y = 1:3) %>% 
  group_by(x) %>%
  summarise(z = y)
#> # A tibble: 3 x 2
#>       x     z
#>   <chr> <int>
#> 1     A     1
#> 2     B    NA
#> 3     C    NA
```

@krlmlr can you take a quick look at this please? It's a fairly special case as it only arises when the all groups have a single row, so don't spend too much time on it right now.
