### ISSUE TITLE
Document how to supply list of formulas to case_when()

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#2929]
e.g. https://stackoverflow.com/questions/44822256/use-dplyrcase-when-with-arguments-programmatically/44823159

Formulas should be created with `exprs()` (so they are unevaluated) if they refer to data columns or `.data` / `.env` pronouns.

Mention that supplying formulas directly to `case_when()` within a `mutate()` works precisely because they are captured unevaluated by `mutate()`.

**Comment by hadley** [comment]
Related to #3133 ?
