### ISSUE TITLE
Temporary tables in MSSQL

### ISSUE THREAD

**Issue by donaldmusgrove** [tidyverse/dplyr#2931]
I receive the below error when attempting to create a temporary table on a MSSQL database by copying a column from an existing table into the new temporary table. Below, the error shows the underlying SQL code which does not appear correct for MSSQL (I'm no SQL pro but I use either CREATE TABLE #TempName or INTO).  I can successfully copy local dataframes into temporary tables via the ```copy_to``` function, though this feature isn't very useful for my current situation.

``` r
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
library(DBI)

con <- DBI::dbConnect(odbc::odbc(), "MyDB")

d1 <- tbl(con, "Device") %>%  select(Key) %>% compute(name="#keys")
#> Error: <SQL> 'CREATE TEMPORARY TABLE "#keys" AS SELECT "Key" AS "Key"
#> FROM (SELECT "Key" AS "Key"
#> FROM "Device") "tjfnbkcubs"'
#>   nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Unknown object type 'TEMPORARY' used in a CREATE, DROP, or ALTER statement.
```

**Comment by Hong-Revo** [comment]
Until the fix in dbplyr goes live, you can use the workaround here:

https://stackoverflow.com/a/46267726/474349

This has also been added to the dbplyr PR, although there's some questions remaining about the interface.

**Comment by kerry-ja** [comment]
I get an error when trying to use local temporary tables in a SQL Server database.
```
library(odbc)
library(DBI)
con <- DBI::dbConnect(odbc::odbc(), 
                      Driver = "SQL Server", 
                      Server = ServerName, 
                      Database = DatabaseName, 
                      Trusted_Connection = "True")

# Create 3 tables in SQL Server database; a local temporary, a global temporary and a non-temporary
dbExecute(con, "CREATE TABLE #LocalTemp (TableType varchar(255));
CREATE TABLE ##GlobalTemp (TableType varchar(255));
CREATE TABLE NonTemp (TableType varchar(255));
INSERT INTO #LocalTemp VALUES ('Local Temporary Table');
INSERT INTO ##GlobalTemp VALUES ('Global Temporary Table');
INSERT INTO NonTemp VALUES ('Non Temporary Table');
")

# Query the tables, and see what the response is
dbReadTable(con, "#LocalTemp")
dbReadTable(con, "##GlobalTemp")
dbReadTable(con, "NonTemp")

# Drop the tables
dbRemoveTable(con,"#LocalTemp")
dbRemoveTable(con,"##GlobalTemp")
dbRemoveTable(con,"NonTemp")

# Disconnect
dbDisconnect(con)
```
When I run the code, it works correctly for the  non temporary table and the global temporary table, but not for the local temporary table.  Please note that there are differences between a local temporary table and a global temporary table, and to minimize the risk of different users interfering with each other local temporary tables would be preferred.
[Difference between local and global temporary tables](https://technet.microsoft.com/en-us/library/ms186986(v=sql.105).aspx)
```
> # Query the tables, and see what the response is
> dbReadTable(con, "#LocalTemp")
Error: <SQL> 'SELECT * FROM "#LocalTemp"'
  nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#LocalTemp'. 
> dbReadTable(con, "##GlobalTemp")
               TableType
1 Global Temporary Table
> dbReadTable(con, "NonTemp")
            TableType
1 Non Temporary Table
> 
> # Drop the tables
> dbRemoveTable(con,"#LocalTemp")
Error: <SQL> 'DROP TABLE  "#LocalTemp"'
  nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot drop the table '#LocalTemp', because it does not exist or you do not have permission. 
> dbRemoveTable(con,"##GlobalTemp")
> dbRemoveTable(con,"NonTemp")
```

The same SQL works without issue using the RODBC package

**Comment by kerry-ja** [comment]
Sorry, I know this issue is marked as closed, but I still get the same errors as previously when trying to query a local temporary table in a SQL server database where the local temporary table (starts with a single #) was created in the session.  I did update the packages
```
devtools::install_github("tidyverse/dbplyr")
devtools::install_github("rstats-db/odbc")
devtools::install_github("rstats-db/DBI")
```

**Comment by hadley** [comment]
@kerry-ja commenting on closed issues is generally not a good strategy. Please create a reprex (with the reprex package) and file a new issue.
