### ISSUE TITLE
bind_rows deletes columns with duplicate names: intended?

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverse/dplyr#2933]
``` r
df <- data.frame(a=1:4, a=5:8, check.names=FALSE)
bind_rows(df)

#  a
#1 5
#2 6
#3 7
#4 8

```
This is actually rather convenient for me (saves a bunch of verification code), but I'd just like to confirm that it's intended behaviour.

**Comment by krlmlr** [comment]
I'd advise against relying on this feature, we shouldn't be supporting "broken" data frames at all and just throw an error when we see one.

**Comment by Hong-Revo** [comment]
Thanks, I've fixed up my code.
