### ISSUE TITLE
RSQlite reads force convert missing values in numeric fields to 0

### ISSUE THREAD

**Issue by lhunsicker** [tidyverse/dplyr#2935]
Brief description of the problem:  Because of the design of SQLite, which does not have strict typing requirements, null data (e.g., ",," in a *.csv file, get read into an SQLite numeric column as 0 length "text" type fields rather than as NULLs.  When an RSQLite query pulls these values into R, the 0 length text field is force converted to a 0, rather than to an NA.  Clearly, reading missing numeric values as 0s is an error.  I realize that this problem is mostly due to SQLite's handling of missing values.  But I suggest that RSQLite might check the SQLite column affinity, and when fed a 0 length "text" value in a numeric affinity column, render it as NA rather than 0.   

newdb.csv file contents:
```
"Integer", "Real", "Text", "Blob", "Null"
1,1,1,1,1
2,2,2,2,2
3,3,3,3,3
4, 4, 4 ,"4",4
,,,,
```

R-code and results:

```r
library(RSQLite)
testdb <- dbConnect(SQLite(), "test.db")
newdb1 <- read_csv("C:/Larry/R-Spaces/tidyverse/newdb.csv")
# A tibble: 5 x 6
#        Integer  Real  Text    None    Blob  Null
#         <int>  <int> <int>   <chr>   <int> <int>
#   1       1      1       1       1     1     1
#   2       2      2       2       2     2     2
#   3       3      3       3       3     3     3
#   4       4      4       4    "\"4\""  4     4
#   5      NA     NA      NA      NA    NA    NA
dbSendQuery(testdb, "Create table test1 (
   testa INTEGER,
   testb REAL,
   testc TEXT,
   testd BLOB,
   teste NULL,
   testf NONE
);")
dbWriteTable(testdb, 'test1', 'newdb1.csv', append = T)
dbGetQuery(testdb, 'select typeof(testa),typeof(testb),typeof(testc),
           typeof(testd),typeof(teste),typeof(testf) from test1;')
#   typeof(testa)  typeof(testb) typeof(testc) typeof(testd) typeof(teste) typeof(testf)
# 1       integer          real          text          text          text       integer
# 2       integer          real          text          text          text       integer
# 3       integer          real          text          text          text       integer
# 4       integer          real          text          text          text       integer
# 5            text           text          text          text          text          text
test1 <- dbGetQuery(testdb, 'Select * from test1;')
test1
#   testa testb testc   testd teste testf
# 1     1     1     1       1     1     1
# 2     2     2     2       2     2     2
# 3     3     3     3       3     3     3
# 4     4     4     4   """4"""   4     4
# 5     0     0                             0
```

Note that when newdb.csv is read directly into R, all columns except column 4 (with an explicit text entry) are "correctly" typed by R as int columns.  Row 5 is correctly read in each column as NA.  However, when newdb.csv is read into an SQLite table, the blanks in row 5 are all read as 0 length "text" fields.  When these data are pulled back into R, the numeric affinity fields convert these 0 length "text" fields to 0.  (The text affinity fields are coerced less egregiously inappropriately as blank text fields.

Thanks for considering the above.
Larry Hunsicker

**Comment by krlmlr** [comment]
Thanks, this looks like a problem with RSQLite. Could you please resubmit there?
