### ISSUE TITLE
Dplyr with SQL - Fetch Size Issue when working Amazon Athena

### ISSUE THREAD

**Issue by emadretina** [tidyverse/dplyr#2939]
Sorry if this problem has come up before. After a couple of hours of Googling around I couldn't find the right answer. 

Problem: When connecting to Amazon Athena using JDBC and Dplyr. I run into the issue of FetchSize which Amazon defaults to 999 rows. If you were using rJDBC only you can get around it by fetching in block sizes and small chunks. Would be cool if collect() function allowed that as well. 

RECREATE PROBLEM WITH:

```r
some_data <- tbl(conn, dplyr::sql('select * from long_table'))
some_data %>% collect()
```
Error in .jcall(rp, "I", "fetch", stride, block) : 
  java.sql.SQLException: The requested fetchSize is more than the allowed value in Athena. Please reduce the fetchSize and try again. Refer to the Athena documentation for valid fetchSize values.

CURRENT WORK AROUND:

```r
query <- 'select * from long_table'
r <- dbSendQuery(conn, query)
data_batch <- fetch(r, n=-1, block=500)
```

WOULD LIKE:
```r
some_data <- tbl(conn, dplyr::sql('select * from long_table'))
some_data %>% collect(n=Inf, block=500)
```

**Comment by edgararuiz** [comment]
Hi @emadretina , 

Maybe a better solution is to get a `dplyr` SQL translation for Athena working, that way you can push the data manipulation to the database and then to collect a much smaller dataset that contains the results

If interested in this, can you send me what you receive when passing the following command: `conn@jc`?

**Comment by emadretina** [comment]
Yes, certainly that's what I am doing. The SQL translation for Dplyr actually works really well. The problem is that Athena's FetchSize limit is literally 999 rows which I am sure you agree for even small data sets is really small. 

Anyway, this is what I get when I type in `conn@jc`

`Java-Object{com.amazonaws.athena.jdbc.AthenaConnection@45a37759}`

**Comment by edgararuiz** [comment]
That's great to hear! 

A possible solution would be to create a custom `collect()` method for Athena that passes the right argument to the `dbFecth()`  function

**Comment by edgararuiz** [comment]
Yeah, you can use `show_query()`

**Comment by emadretina** [comment]
Amazing! I like it. Thanks, this is a better work around.
