### ISSUE TITLE
dbplyr - MS SQL - filter for is.na not working

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/dplyr#2940]
The translation for `is.na()` is not working when used in `filter()` for the MS SQL translation.  The reason is because we're using the same translation used in `mutate()`.  

```
show_query({
  flights %>%
    filter(!is.na(dep_time))
})
```
Results in:

```
<SQL>
SELECT *
FROM "flights"
WHERE (NOT(CASE WHEN "dep_time" IS NULL THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END))
```

`filter()` should translate `is.null()` to `x IS NULL`  and `!is.null()` to `x IS NOT NULL`

So the correct translation of the code above should be:

```
<SQL>
Select * from flights where dep_time is not null
```

**Comment by krlmlr** [comment]
Thanks. How does `filter(is.na(...))` translate?

**Comment by edgararuiz** [comment]
Hi @krlmlr , it translates to:

```
<SQL>
SELECT *
FROM "flights"
WHERE (NOT(CASE WHEN "dep_time" IS NULL THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END))
```
I plan to work on this issue when I get back from vacation, I think I know what I need to update.  I'll be ok with this issue be assigned to me if you like.

Thanks

**Comment by krlmlr** [comment]
Isn't this the translation of `filter(!is.na(...))`? I asked about `filter(is.na(...))`.

We'll be happy to review a pull request.

**Comment by jschelbert** [comment]
Bump... Here is the output you requested for
```{r}
show_query({
    flights %>%
        filter(is.na(dep_time))
})
```

```
<SQL>
SELECT *
FROM "flights"
WHERE (CASE WHEN "dep_time" IS NULL THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END)
```

**Comment by juliangkr** [comment]
Hello,

was this issue fixed? I connected to a oracle database using DBI and ROracle. Everything works fine, but when I want to filter by _!is.na_ I receive the following error:

```
Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-00920: invalid relational operator
```
My query is:

```r
tbl.obj = dplyr::tbl(con, table_name)
    tbl.obj %>% dplyr::filter(!is.na(col))
```

I tested it with an installation from CRAN and from github

**Comment by edgararuiz** [comment]
Hi @juliangkr , this fix was meant for MS SQL so your issue may be separate.  Would you mind sharing with me the code you used to connect, including the code used to get ROracle working with `dplyr`.  Also, would you mind posting the result of: `tbl.obj %>% dplyr::filter(!is.na(col)) %>% show_query()`?  This may required a new Issue to be opened, but please allow me to take a look at what I requested to make a determination.  Thanks.

**Comment by juliangkr** [comment]
The complete code is:

```r
connection_str = paste0('(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=', host, ')(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=', service_name, ')))')

 drv = dbDriver("Oracle") 
 con = DBI::dbConnect(drv, 
                      user=username,
                      password=password,
                      dbname=connection_str)

tab = dplyr::tbl(con, "Samples") %>%
    dplyr::filter(!is.na(name))
```
class(con) returns:

```r
class(con)
[1] "OraConnection"
attr(,"package")
[1] "ROracle"
```

**Comment by juliangkr** [comment]
Hello @edgararuiz, I still was not able to fix this issue. Could you please have a second look on my problem? Additionally, I sometimes get an error, that my query is not a correct SQL statement. I think my queries can be quiet long, but with dplyr in combination with dplyrOracle there was no problem with the long queries.

**Comment by edgararuiz** [comment]
Hi @juliangkr , is the issue still there after using the version of `dbplyr` in the PR? `devtools::install_github("tidyverse/dbplyr", ref = devtools::github_pull(34))`

For your second problem,  I wonder if you're experiencing the same problem I'm having that prevents the `sql_optimiser` from running when a `print` action happens: https://github.com/tidyverse/dplyr/issues/3084 .  Can you try a `collect()` in the code and see if it fails as well?

**Comment by juliangkr** [comment]
Hi @edgararuiz, thank you for your quick answer! With the PR version it works perfectly, thank you!

The second issue seems to be the same as in #3084, if i execute a command without `collect()` I get the error message `ORA-00933: SQL command not properly ended` otherwise not.

**Comment by edgararuiz** [comment]
That's great to hear! 

Also, thank you for testing and letting me know that the issues are related.  I think I know where the fix needs to be done, but I haven't put together a PR yet,  I'll follow up with you when I have something for that.

**Comment by Prometheus77** [comment]
This issue doesn't appear to be fixed in the CRAN version as of yet, as I'm experiencing the same problem. Any update on when we can expect this to be included?

**Comment by Prometheus77** [comment]
I just installed the utf8 package and that fixed the issue for me. The underlying query is still using the NOT(("X") IS NULL) syntax instead of "X" IS NOT NULL, but it appears to be working properly now.

Here's a snippet:
```
library(tidyverse)
library(DBI)
library(dbplyr)

con <- dbConnect(odbc::odbc(), .connection_string = paste0("driver={SQL Server Native Client 11.0};server=MYSERVER;database=MYDB;trusted_connection=yes"))

con %>% tbl(ident_q("MYDB.dbo.mytable")) %>%
  filter(!is.na(mycolumn))
```
