### ISSUE TITLE
Please add JDBC support for Oracle

### ISSUE THREAD

**Issue by fpmcardoso** [tidyverse/dplyr#2941]
I'm using `dplyr` and `dbplyr` with an Oracle database as a source and a JDBC connection object created with RJDBC.

To translate the dplyr verbs to Oracle SQL correctly, I must run the following steps before:

```
# the jdbc connection object has "JDBCConnection" as its class
sql_translate_env.JDBCConnection <- dbplyr:::sql_translate_env.Oracle
sql_select.JDBCConnection <- dbplyr:::sql_select.Oracle
sql_subquery.JDBCConnection <- dbplyr:::sql_subquery.Oracle
```
as  commented by Edgar Ruiz here (http://disq.us/p/1k1smn8).

That's is needed because the package gets the database vendor from the odbc connection object when using an odbc connection,  but there's no support for jdbc connections. 

Is it possible to add support for this case? 

Many thanks in advance!

**Comment by edgararuiz** [comment]
Hi @fpmcardoso !

I have a branch ready for you, can you try installing this and let me know if it works for you?

```
devtools::install_github("edgararuiz/dbplyr", ref = "translation-jdbc ")
```

**Comment by fpmcardoso** [comment]
Hi @edgararuiz !!

I've tried, but I'm getting the following error:

```

## This works
DBI::dbGetQuery(conn = jdbcConnection, statement = "SELECT * FROM PROD_DIM_C zzz1 WHERE (0=1)")

## This doesn't
dplyr::tbl(jdbcConnection, "PROD_DIM_C")
```

Error in as.character.default(x) : 
  no method for coercing this S4 class to a vector

**Comment by hadley** [comment]
@edgararuiz does JDBC provide the driver name as a class or an attribute? Is there some other way we can retrieve?

**Comment by edgararuiz** [comment]
Yes, it's in the `jc` slot:
```
jdbcConnection@jc 
[1] "Java-Object{oracle.jdbc.driver.T2CConnection@143dfa7c}"
```

**Comment by hadley** [comment]
Did we discuss a general approach to translations for jdbc drivers somewhere? I have a vague memory.

**Comment by edgararuiz** [comment]
Yes, in Slack back in June. And in the PR I submitted and then closed: https://github.com/tidyverse/dbplyr/pull/26.  The approach was to use a conditional statement to route some functions to the respective DB translation based on the slot value.

**Comment by hadley** [comment]
Subsumed by #3160
