### ISSUE TITLE
Feature request: mutate.list method

### ISSUE THREAD

**Issue by twolodzko** [tidyverse/dplyr#2942]
Consider the following example. We could use purrr to interact with lists, but the obvious thing that one would possibly like to do, is to _mutate_ the elements of the lists. The obvious choice would be to use `dplyr::mutate` as follows:

```
library(tidyverse)
library(repurrrsive)

map(sw_people, ~ mutate(.x, name = paste(name, "the King")))
## Error in UseMethod("mutate_") : 
##   no applicable method for 'mutate_' applied to an object of class "list"
```

Unfortunately this doesn't work since there is no `mutate.list` method.

I understand that one could argue that such function possibly would not have the same functionality as standard `mutate` (e.g. interacting with grouped data), but still it would be helpful if `mutate` would work with non-data.frame/tibble structures as well. (Maybe this should go to to some kind of "listplyr" package, or just purrr, but dplyr sounds like a more reasonable place since it already has `mutate`).

The most basic implementation would be something like:

```
mutate.list <- function(.data, ...) {
  dots <- dplyr:::compat_as_lazy_dots(...)
  eval_dots <- lazyeval::lazy_eval(dots, data = .data)
  .data[names(eval_dots)] <- eval_dots
  .data
}
```

**Comment by mgirlich** [comment]
This is already possible with purrr thanks to `update_list`:

``` r
library(purrr)

map(repurrrsive::sw_people, ~ update_list(.x, name = paste(.x$name, "the King")))
```

**Comment by hadley** [comment]
I agree that it would be useful, but it's outside the scope of dplyr.
