### ISSUE TITLE
arrange() throws error when used with UQ()

### ISSUE THREAD

**Issue by bergsmat** [tidyverse/dplyr#2944]
arrange() gives an error when sorting argument is unquoted. I would have expected the three  arrange calls below to give identical results. 

```r
x <- head(Theoph)
x <- x[rev(rownames(x)),]
arrange_(x, 'Time')
arrange(x, Time)
arrange(x, UQ('Time'))
#Error in arrange_impl(.data, dots) :  incorrect size (1) at position 1, expecting : 6
```

**Comment by Hong-Revo** [comment]
I think you want `sym` not `UQ` in the 3rd one.

**Comment by bergsmat** [comment]
Thanks for your thoughts.  ```sym``` did not work for me. 
```r
arrange(x, sym('Time'))
# Error in arrange_impl(.data, dots) : object 'Time' not found
```
```UQ```, however worked well for upgrading many other SE verbs (trailing underscore) to NSE counterparts.

**Comment by echasnovski** [comment]
When working with character names one should convert them to symbols and then unquote:
```
arrange(x,` UQ(sym('Time'))
```

**Comment by lionel-** [comment]
@Hong-Revo and @echasnovski are right.

You can look at the result of the unquoting by using the `expr()` function from rlang. All these functions will be exported in the next version of dplyr:

```r
expr <- rlang::expr

expr(arrange(x, UQ(sym("Time")))
#> arrange(x, Time)

expr(arrange(x, UQ("Time"))
#> arrange(x, "Time")
```

The goal is to build the same expression as what you'd have typed directly. We'll make these points clearer in the next vignette update.

**Comment by bergsmat** [comment]
Thanks all for your helpful guidance.

```arrange(x, UQ(sym('Time'))``` does indeed work in this case.  But then, my repex was too simple.  My real use case has ```'Time'``` as part of a vector of sort variables, say ``` vars <- c('Subject','Time')```.  What I am trying to do is replace ```arrange_(x, .dots = vars)``` with the appropriate no-underscore equivalent.  I look forward to reading the updated vignette.

**Comment by lionel-** [comment]
when you have several variables, you can create a list of symbols with `syms()` and splice them in the call with `!!!`, e.g. `!!! syms(vars)`. Don't forget the `expr()` trick to check what kind of expression you get once the unquoting is done.

**Comment by bergsmat** [comment]
Thanks!  It works for me. 
```
arrange_(x, .dots = vars)
``` 
... becomes ....
```
arrange(x, UQS(syms(vars)))
```
And ```vars``` can be length zero, one, or many.  Very nice.

**Comment by AjarKeen** [comment]
In case anyone else is trying to figure out why their chain of functions doesn't work and comes across this issue, the `arrange` behaviour differs from e.g. `select`:

``` r
library(lubridate, quietly = TRUE, warn.conflicts = FALSE)
library(dplyr, quietly = TRUE, warn.conflicts = FALSE)
library(rlang, quietly = TRUE, warn.conflicts = FALSE)

set.seed(2501)

df <- data_frame(time = seq(ymd("2017-01-01"), ymd("2017-01-10"), by = 1),
                 val1 = seq(10, 1),
                 val2 = sample(c(0, 1, NA), 10, replace = TRUE))

df
#> # A tibble: 10 x 3
#>          time  val1  val2
#>        <date> <int> <dbl>
#>  1 2017-01-01    10     1
#>  2 2017-01-02     9     0
#>  3 2017-01-03     8     1
#>  4 2017-01-04     7    NA
#>  5 2017-01-05     6     1
#>  6 2017-01-06     5    NA
#>  7 2017-01-07     4     0
#>  8 2017-01-08     3     0
#>  9 2017-01-09     2    NA
#> 10 2017-01-10     1     0

# example 1
my_col <- quo("val1")

df %>% 
  na.omit %>%
  select(time, !!my_col) %>%
  arrange(!!sym(UQE(my_col)))
#> # A tibble: 7 x 2
#>         time  val1
#>       <date> <int>
#> 1 2017-01-10     1
#> 2 2017-01-08     3
#> 3 2017-01-07     4
#> 4 2017-01-05     6
#> 5 2017-01-03     8
#> 6 2017-01-02     9
#> 7 2017-01-01    10

# example 2
my_col <- "val1"

df %>% 
  na.omit %>%
  select(time, !!my_col) %>%
  arrange(!!sym(my_col))
#> # A tibble: 7 x 2
#>         time  val1
#>       <date> <int>
#> 1 2017-01-10     1
#> 2 2017-01-08     3
#> 3 2017-01-07     4
#> 4 2017-01-05     6
#> 5 2017-01-03     8
#> 6 2017-01-02     9
#> 7 2017-01-01    10
```

**Comment by lionel-** [comment]
`select()` is the only verb that accepts strings (column names) or integers (column positions).
