### ISSUE TITLE
Scoped rename functions don't work on grouped_df

### ISSUE THREAD

**Issue by echasnovski** [tidyverse/dplyr#2947]
In dplyr 0.7.1 these work:
```
mtcars %>% rename_all(toupper)
mtcars %>% group_by(vs) %>% rename(VS = vs)
```
But these don't (throw an error `All arguments must be named`):
```
mtcars %>% group_by(vs) %>% rename_all(toupper)
mtcars %>% group_by(vs) %>% rename_if(rlang::is_integerish, toupper)
mtcars %>% group_by(vs) %>% rename_at("mpg", toupper)
```

**Comment by mdpead** [comment]
I've run into the same problem (in version 0.7.2). I noticed that the scoped `select` variant works as expected, and given the similarities between `select `and `rename` thought that this could help give a clue as to the fix.

So: 

```
mtcars %>% group_by(vs) %>% select_all(toupper)
mtcars %>% group_by(vs) %>% select_if(rlang::is_integerish, toupper)
mtcars %>% group_by(vs) %>% select_at("mpg", toupper)
```

all work as expected. Sorry I can't be of more assistance, thanks for the awesome package!

**Comment by billdenney** [comment]
I've seen the same issue with version 0.7.3 (installed about a week ago):

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
obj <- data.frame(A_B = rep(1:2, each = 2), C_D = 1:4)
obj %>% rename_all(function(x) gsub("_", " ", x))
#>   A B C D
#> 1   1   1
#> 2   1   2
#> 3   2   3
#> 4   2   4
obj %>% group_by(A_B) %>% rename_all(function(x) gsub("_", " ", x))
#> Error: All arguments must be named
```
For the work I'm doing right now, a reasonable work-around is to add a `group_by() %>%` just before the `rename_all` call.

**Comment by dpeterson71** [comment]
It's not just grouped or not.  The rename function is broken in 0.7.4.  Even the iris example in the documentation fails.  The select function appears to be OK, though, as observed above.  From running "example(rename)":

rename> # Renaming -----------------------------------------
rename> # * select() keeps only the variables you specify
rename> select(iris, petal_length = Petal.Length)
# A tibble: 150 x 1
   petal_length
          <dbl>
 1         1.40
 2         1.40
 3         1.30
 4         1.50
 5         1.40
 6         1.70
 7         1.40
 8         1.50
 9         1.40
10         1.50
# ... with 140 more rows

rename> # * rename() keeps all variables
rename> rename(iris, petal_length = Petal.Length)
Error: `petal_length` = Petal.Length must be a symbol or a string, not formula

**Comment by batpigandme** [comment]
FTR, the examples using ungrouped select and rename, as in @dpeterson71's example, _do_ work in the dev version (I'm currently running `tidyverse/dplyr@f49115b` f49115b). 👍 

``` r
library(tidyverse)

# select() keeps only the variables you specify
s <- select(iris, petal_length = Petal.Length)
head(s)
#>   petal_length
#> 1          1.4
#> 2          1.4
#> 3          1.3
#> 4          1.5
#> 5          1.4
#> 6          1.7
# rename() keeps all variables
r <- rename(iris, petal_length = Petal.Length)
head(r)
#>   Sepal.Length Sepal.Width petal_length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
#> 6          5.4         3.9          1.7         0.4  setosa
```

Created on 2018-01-16 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by dpeterson71** [comment]
Following up on this I checked the behavior on two other machines and found the rename function working.  The common feature of the _working_ machines was rlang 0.1.6.  The broken implementation has the development version of rlang (0.16.9002) installed as seen in the sessionInfo() in my initial comment.  I'll file a bug report there.

**Comment by batpigandme** [comment]
@dpeterson71 it works fine with 0.16.9003, so no need.

**Comment by bkayser** [comment]
@dpeterson71  @batpigandme @JohnMount FWIW rlang `0.1.6.9003` did not resolve the issue for me but inserting `group_by()` did work around the problem.
