### ISSUE TITLE
Add `distinct_at`?

### ISSUE THREAD

**Issue by vnijs** [tidyverse/dplyr#2948]
Many of the `_` verb versions have an `_at` option in 0.7.1. Not so for `distinct_`. Could this be added?

**Comment by hadley** [comment]
We should add all scoped variants: `distinct_if()`, `distinct_at()` and `distinct_all()`.

**Comment by romainfrancois** [comment]
@lionel- I can take this one if you like

**Comment by lionel-** [comment]
Sure thanks!
