### ISSUE TITLE
error/warning/message on variable from environment / column ambiguity in filter

### ISSUE THREAD

**Issue by danielsjf** [tidyverse/dplyr#2949]
In filter, you can use both variable names and column names. When there is an ambiguity, dplyr silently uses the column name instead of the variable name, but this can cause some nasty bugs.

```r
df <- data.frame(color = c('red','blue','black'), value = c(1,2,3))
filter(df, color == 'blue')

# now let's use a variable
val <- 'blue'
filter(df, color == val)

# however, when there is an ambiguity, it silently takes the column name
value <- 'blue'
filter(df, color == value) # notice that there is both a column named `value` and a variable named
                           # `value`. dplyr silently uses the column name here and returns no rows since
                           # not a single value of the color column is equal to the value in the value column
```

It would be really convenient if dplyr would throw an error when there is an ambiguity.

In addition to this, there could be a helper function that specifies which behaviour is used.
```
value <- 'blue'
filter(df, color == eval_col(value)) # would parse value as a column name and would return no matches
filter(df, color == eval_var(value)) # would parse value as a variable and would return the row where value == 'blue'
filter(df, color == value) # would throw an error along the lines of: "value is both a column name and a variable in this environment. Please use eval_col or eval_var to specify the desired behaviour"
```

**Comment by krlmlr** [comment]
Thanks. We do offer explicit access, but currently no error on ambiguity. Please take a look at the [programming vignette](https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html), e.g. the section "Programming recipes".

**Comment by lionel-** [comment]
This is standard R semantics for datawise operations but tidy evaluation provides a way to be more explicit. You can unquote a value to bypass the data:

```r
filter(df, color == (!! value))
```
