### ISSUE TITLE
dbplyr encoding: Latin1 text column from SQL Server transferred to memory dataframe via collect() contains encoding errors

### ISSUE THREAD

**Issue by carioca67** [tidyverse/dplyr#2953]
Hadley, very simple code below. I basically connect to an SQL Server, fetch a particular table which contains a few text columns with accented chars (encoded as Latin1). Then use collect() to bring the table into memory, but said text columns get messed up in terms of encoding. Not sure if the problem is within dplyr, dbplyr, DBI, or the odbc driver. The same problem does not occur with library(RODBC)

```r
# load libs
library(tidyverse)
library(dbplyr)
library(DBI)
library(odbc)

# connect to SQL Server
con <- dbConnect(odbc(),
                   Driver    = "SQL Server", 
                   Server    = "ssss",
                   Database  = "dddd",
                   UID       = "uuuu",
                   PWD     = rstudioapi::askForPassword("passwd: "),
                   Port      = 1433)

# get a table for which some columns are nvarchar() and Latin1
myT <- tbl(con, in_schema("dan","tttt"))

# the text columns w accented chars will look messed up within df
df <- myT %>% head(1000) %>% collect()
```

**Comment by krlmlr** [comment]
Thanks. What does `dbReadTable()` or `dbGetQuery()` return for this database?

**Comment by carioca67** [comment]
Hi Kirill, I just did:

df <- dbGetQuery(con,"SELECT TOP 10 txt_col from dan.ttt")

and the result looks exactly replicates the encoding problems as in 

df <- myT %>% head(10) %>% collect()

For example, the first line, in the database looks like (it comes from a portuguese language table):

Descrição: colaborador solicita configuração da impressora Zebra.

However, both collect() and dbQuery() will return the following string with the accented chars garbled:

Descri<e7><e3>o: colaborador solicita configura<e7><e3>o da impressora Zebra.

**Comment by krlmlr** [comment]
Thanks @carioca67. Could you please file an issue with the odbc package? This is unlikely to be a dbplyr problem.

**Comment by krlmlr** [comment]
Please do check existing issues beforehand: https://github.com/rstats-db/odbc/search?q=encoding&type=Issues&utf8=%E2%9C%93

**Comment by carioca67** [comment]
Wow, Kirill I am incredibly thankful for your knowledge and efficiency. I did follow your link and found a solution: the dbConnect call should contain an extra "encoding" parameter (see below), thanks my friend!

con <- dbConnect(odbc::odbc(),
Driver = "SQL Server",
Server = "sss",
Database = "ddd",
UID = "uuu",
PWD = askForPassword("passwd: "),
Port = 1433,
encoding = "latin1") # fixed in odbc

**Comment by krlmlr** [comment]
You're welcome. The odbc manual would be a better venue I think.
