### ISSUE TITLE
dplyr::distinct appears to consider empty rows different

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2954]
`dplyr::distinct()` appears to consider empty rows different.  Notice in the example below `dplyr::distinct()` returns a 2 row data frame where both rows are identical.  This is a corner-case where there are no columns, but I think in this case `dplyr::distinct()` should not return more than 1 row in this case.  Notice adding a column in the example then decreases the number of rows considered distinct.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.1.9000'

d <- data.frame(x= c(1, 1))

d0 <- select(d, one_of(character(0)))
dD <- distinct(d0)
print(dD)
#> data frame with 0 columns and 2 rows

d2 <- mutate(dD, newCol = 1)
print(d2)
#>   newCol
#> 1      1
#> 2      1

distinct(d2)
#>   newCol
#> 1      1
```

**Comment by krlmlr** [comment]
Thanks. Honestly, I'd rather throw an error here, `distinct()` on a data frame without columns smells like division by zero to me. @hadley?

**Comment by JohnMount** [comment]
Error out is not a bad idea.  I consider this enough of a dangerous corner case that I already re-coded my application check for this situation and not call `distinct()` in this situation.

**Comment by hadley** [comment]
I think if there are no columns, we could just special case `distinct()` to return the first row.

**Comment by romainfrancois** [comment]
just returning 1 row feels less surprising than error. I'll do that.
