### ISSUE TITLE
Feature request: decimate

### ISSUE THREAD

**Issue by Enchufa2** [tidyverse/dplyr#2959]
Currently, if you want to decimate your observations (say, taking 1 of every 3 observations; use case: you have too much data for a quick plot), your only options (AFAIK) are

``` r
library(dplyr)

data_frame(x=seq(1:20)) %>% 
  .[c(T, F, F),]
#> # A tibble: 6 x 1
#>       x
#>   <int>
#> 1     1
#> 2     4
#> 3     7
#> 4    10
#> 5    13
#> 6    16
#> 7    19
```

which doesn't work for grouped data, and

``` r
data_frame(x=seq(1:20)) %>% 
  filter(((row_number()-1) %% 3)==0)
#> # A tibble: 6 x 1
#>       x
#>   <int>
#> 1     1
#> 2     4
#> 3     7
#> 4    10
#> 5    13
#> 6    16
#> 7    19
```

which seems clunky to me. I think that having a `decimate()` verb would be more convenient and readable, and it would allow more advanced use cases. Basic example:

``` r
data_frame(x=seq(1:20)) %>% 
  decimate(3)
#> # A tibble: 6 x 1
#>       x
#>   <int>
#> 1     1
#> 2     4
#> 3     7
#> 4    10
#> 5    13
#> 6    16
#> 7    19
```

Maybe with limits:

``` r
data_frame(x=seq(1:20)) %>% 
  decimate(3, from=2, to=10)
#> # A tibble: 6 x 1
#>       x
#>   <int>
#> 1     2
#> 2     5
#> 3     8
```

Numeric patterns:

``` r
data_frame(x=seq(1:20)) %>% 
  decimate(c(2, 4))
#> # A tibble: 6 x 1
#>       x
#>   <int>
#> 1     1
#> 2     3
#> 3     7
#> 4     9
#> 5    13
#> 6    15
#> 7    19
```

Boolean patterns:

``` r
data_frame(x=seq(1:20)) %>% 
  decimate(c(F, T, F))
#> # A tibble: 6 x 1
#>       x
#>   <int>
#> 1     2
#> 2     5
#> 3     8
#> 4    11
#> 5    14
#> 6    17
#> 7    20
```

**Comment by hadley** [comment]
Or 

```R
tibble(x = 1:20) %>% slice(seq(1, n(), by = 5))
```

`decimate()` seems useful but not used frequently enough to go in dplyr.

**Comment by Enchufa2** [comment]
Yeap, that's right, but the problem with slice+seq is that if the data is huge (which is basically the use case for decimation), then generating another huge sequence for the slicing seems overkilling to me, and may saturate the memory.

**Comment by Enchufa2** [comment]
A side question before opening a new issue: would you consider adding a similar functionality to ggplot2? For instance, the `tuneR` package, by Uwe Ligges, defines Wave objects, which perform automatic decimation when you try to plot a signal with a huge number of samples.

**Comment by hadley** [comment]
That would be out of scope for ggplot2 too, sorry.
