### ISSUE TITLE
data is still grouped after a summarize (but not by original set of columns)

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2963]
Here we group by both of `cyl` and `gear`.  After the `summarize` I would expect either the data to be ungrouped (my preference) or grouped by `cyl` and `gear`, instead it is reported as being grouped by `cyl` alone.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.1.9000'

mtcars %>% 
  group_by(cyl, gear) %>% 
  summarize( mean_mpg = mean(mpg))
#> # A tibble: 8 x 3
#> # Groups:   cyl [?]
#>     cyl  gear mean_mpg
#>   <dbl> <dbl>    <dbl>
#> 1     4     3   21.500
#> 2     4     4   26.925
#> 3     4     5   28.200
#> 4     6     3   19.750
#> 5     6     4   19.750
#> 6     6     5   19.700
#> 7     8     3   15.050
#> 8     8     5   15.400
```

**Comment by krlmlr** [comment]
As far as I understand, this is by design -- this allows drilling up by `cyl` in the next step. We discussed automatic ungrouping before and decided against it, e.g. https://github.com/tidyverse/dplyr/issues/2021#issuecomment-258998755.

**Comment by JohnMount** [comment]
But it isn't grouped by `cyl` and `gear` (which is what the user specified).  This is just one more convention for users to learn and get confused on.  If I group by 3 columns is the result grouped by 1 or 2 columns after a summarize (which "drill down" is being supported).  I really think it makes more sense to have either the result ungrouped (expressing the grouping has been consumed) or grouped by the original grouping spec (expressing the granularity of the result, and hinting you are ready for a join).  I don't have a strong opinion as to each, but I really feel for teachability it should be one of those.

**Comment by Hong-Revo** [comment]
This is what dplyr has done since the beginning, or at least since 0.4.

**Comment by Enchufa2** [comment]
> help(summarize) says "One grouping level will be dropped" how is the user to know which one?

The last one. The examples are clear, although I agree that this should be clearly stated in the documentation.

> I really think it makes more sense to have either the result ungrouped (expressing the grouping has been consumed) or grouped by the original grouping spec (expressing the granularity of the result, and hinting you are ready for a join).

These are just two other possible conventions to have to memorise. If you don't have a strong opinion about them, which are basically opposite, then I think it's clear that there is no unique *correct* behaviour. This means that the user has to read the documentation anyway (well, the user should read the documentation anyway). Therefore, I see no benefit in changing the current behaviour, especially if dplyr has done this since the beginning, as @Hong-Revo says.

**Comment by hadley** [comment]
It seems reasonable to me to roll up the level that you just summarised since it now only occupies a single row. 

I don't think the alternatives are better enough to be worth changing at this point.

**Comment by JohnMount** [comment]
> It seems reasonable to me to roll up the level that you just summarised since it now only occupies a single row.

I get that you own the conclusion/decision.  But as a side-note: "`gear`" (presumably what was rolledu p or removed in the original example of this issue) is not "occupying a single row."

**Comment by krlmlr** [comment]
Each combination of `cyl` and `gear` is present in one row only. It makes little sense to keep the grouping unchanged, because each group consists of a single row.

**Comment by JohnMount** [comment]
Then the obvious transform is no grouping at all (i.e., automatic group removal) as it is the only one that is unique when there had been more than one grouping column (and what is already done when there was one grouping column).  I get this change is rejected, but this is my view.
