### ISSUE TITLE
anti_join ordering unpredictable across multiple R sessions in version 0.7.x

### ISSUE THREAD

**Issue by gtumuluri** [tidyverse/dplyr#2964]
When you use `anti_join` on two data frames, the resulting data frame differs across R sessions, giving unpredictable ordering. This problem does not exist in version 0.5.x of `dplyr`.

Here is a reproducible example:

Step 1: create and save up the example data frames, and the first result of the `anti_join`:

```
library(dplyr)
df1 <- data.frame(
  v1 = sample(1:10, 100, replace = TRUE),
  v2 = sample(c('a', 'b', 'c'), 100, replace = TRUE),
  v3 = sample(letters, 100, replace = TRUE),
  v4 = sample(LETTERS, 100, replace = TRUE),
  stringsAsFactors = FALSE
  )
 
df2 <- data.frame(
  v1 = sample(1:10, 100, replace = TRUE),
  v2 = sample(c('a', 'b', 'c'), 100, replace = TRUE),
  v3 = sample(letters, 100, replace = TRUE),
  stringsAsFactors = FALSE
  )
 
dfa1 <- anti_join(df1, df2)
 
write.csv(df1, 'df1.csv', row.names = FALSE)
write.csv(df2, 'df2.csv', row.names = FALSE)
write.csv(dfa1, 'dfa1.csv', row.names = FALSE)
```

Sep 2: Quit R session and re-start a new one.

Step 3: Execute the following code and see that the result of this execution of `anti_join` differs from the one that is saved up:

```
library(dplyr)
df1 <- read.csv('df1.csv', stringsAsFactors = FALSE)
df2 <- read.csv('df2.csv', stringsAsFactors = FALSE)
dfa1 <- read.csv('dfa1.csv', stringsAsFactors = FALSE)
 
dfa2 <- anti_join(df1, df2)
identical(dfa1, dfa2)
```

**Comment by krlmlr** [comment]
Thanks, confirmed; the session restart really seems necessary. `anti_join()` should keep the order of the first argument.
