### ISSUE TITLE
Assigning to a pronoun in grouped do() gives wrong result

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverse/dplyr#2970]
https://stackoverflow.com/questions/45105420/whats-going-on-when-i-assign-to-in-dplyrs-do-function

```r
df <- as.tbl(data.frame(grp=c("a", "b", "c", "d", "e"), a=1:5, b=6:10))
```

This works:
```r
df %>% group_by(grp) %>% do(
{
    d <- .
    d$product <- d$a * d$b
    d
})
```
This duplicates the result for `grp` = `"a"` across all groups:
```r
df %>% group_by(grp) %>% do(
{
    .$product <- .$a * .$b
    .
})
```
Using `.data` instead of `.` also fails.

**Comment by krlmlr** [comment]
Thanks, confirmed. @lionel-: Could you please take a look?

**Comment by hadley** [comment]
I don't think we should invest further development time into do.
