### ISSUE TITLE
Filter with group index

### ISSUE THREAD

**Issue by yueguoguo** [tidyverse/dplyr#2973]
Hi all, would like to know if there is a neat way to filter a grouped data frame with group index. Something like the following:

```r
# say I have a grouped data df. How can I do the following?

df %>% filter(group_index == certain_number)
```

Many thanks!

**Comment by krlmlr** [comment]
Thanks. Your question fits better on StackOverflow, when posting there please do include a reproducible example and perhaps a description of the problem you want to solve.
