### ISSUE TITLE
dplyr filter code not compatible with 0.7.1

### ISSUE THREAD

**Issue by danielsjf** [tidyverse/dplyr#2977]
After upgrading I've had some issues with code that worked before. Not certain if it is still supposed to work.

```r
# reprex compatible
library(dplyr)
value <- 50
tibble(x = c('A','B','C'), y = c(20,55,60)) %>%
    filter(y<=pmax(nth(y,2,default=value),50))
```

This worked before but now returns an error:
Error in filter_impl(.data, quo) : 
  Not compatible with requested type: [type=symbol; target=double].

**Comment by krlmlr** [comment]
Thanks, confirmed. For now you can work around with one of the following, both will trigger the standard version of `nth()`:

```r
tibble(x = c('A','B','C'), y = c(20,55,60)) %>%
  filter(y<=pmax(nth(default=value,y,2),50))
```

```r
tibble(x = c('A','B','C'), y = c(20,55,60)) %>%
  filter(y<=pmax(dplyr::nth(y,2,default=value),50))
```
