### ISSUE TITLE
 object not found

### ISSUE THREAD

**Issue by rajdeepn** [tidyverse/dplyr#2980]
InputCSV <- read.csv("FM_Variance.csv", header = TRUE)
Partout<-select(InputCSV,PartKeyword,Shipment.Date,Act)
Partout<-select(filter(InputCSV,PartKeyword == "ASSY - ENGINE" ),Shipment.Date,Act)

For the code above I get a data-frame output for select alone, however, when I add the filter in the code it gives me an error 
**_"Error in filter(InputCSV, PartKeyword == "ASSY - ENGINE") : 
  object 'PartKeyword' not found"_**
Please suggest, I can't share the data file but the CSV has the column PartKeyword

**Comment by cderv** [comment]
For next time, Know that you may be able to have an answer faster on [stackoverflow](https://stackoverflow.com/questions/tagged/dplyr) when you have a question about usage and not a bug to report.

If I use an example dataset with the same code, no problem : 
``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
InputCSV <- starwars
Partout<- select(InputCSV,name, height, mass)
Partout<-select(filter(InputCSV,name == "R2-D2" ),  height, mass)
```

As you see in the package startup message, `dplyr` masks a function `filter`, also included in `stats` package. 

check that `dplyr` package is loaded correct with `library(dplyr)`. `search` should tell you if `dplyr` is above `stats` in the search path 
``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
search()
#>  [1] ".GlobalEnv"        "package:dplyr"     "package:stats"    
#>  [4] "package:graphics"  "package:grDevices" "package:utils"    
#>  [7] "package:datasets"  "package:methods"   "Autoloads"        
#> [10] "package:base"
```
You can run your code with `dplyr::filter` to be sure or with `library` as first line

```r
library(dplyr)
InputCSV <- read.csv("FM_Variance.csv", header = TRUE)
Partout<-select(InputCSV,PartKeyword,Shipment.Date,Act)
Partout<-select(filter(InputCSV,PartKeyword == "ASSY - ENGINE" ),Shipment.Date,Act)
```` 

Can you try again with all this ? Thanks.

**Comment by rajdeepn** [comment]
Thanks 
But shouldn't it be library(dplyr, verbose = TRUE)? I had put it here because the code was working fine until the last time I opened it. Then things changed as R got updated. 
I did expect someone to point on the satckoverflow though... anyway detaching and attaching the package again helped.
