### ISSUE TITLE
Feature request: strict parameter for select_vars

### ISSUE THREAD

**Issue by twolodzko** [tidyverse/dplyr#2981]
`rename_vars` has `strict` parameter that enables user to turn off throwing errors when calling nonexistent variables. Similar parameter should be introduced for `select_vars` function. It is a reasonable to assume that if user asks for a column that does not exist in the dataset, he should expect the function to return nothing. Another reasonable behavior is to throw error, but introducing the `strict` parameter would make the function more flexible. 

Current behavior:

```
select_vars(colnames(mtcars), mpg, cyl, ff)
##  Error in overscope_eval_next(overscope, expr) : object 'ff' not found 
```

Expected behavior:

```
select_vars(colnames(mtcars), mpg, cyl, ff, strict = FALSE)
##   mpg   cyl 
## "mpg" "cyl" 
```

**Comment by krlmlr** [comment]
This seems to belong in tidyselect.
