### ISSUE TITLE
Show example of vars() with mutate_at() in select_helpers

### ISSUE THREAD

**Issue by eamoncaddigan** [tidyverse/dplyr#2984]
Tidy evaluation has hit CRAN and data analyzers everywhere are probably stumbling over it (I know I did).

The deprecation warning that appeared during a call mutate_each() was helpful for me, but perusing the docs wasn't enough to get my code to work. 

- The documentation for select_helpers would be more helpful if it included examples that explicitly show the necessity of calling vars() when working with mutate_at(). 
- The examples included with the documentation for summarize_all() should probably explain vars() a bit more. 
- The documentation for vars() includes no examples, and this should probably be rectified too.

```r
help(select_helpers, dplyr)
```

**Comment by pranayroy01** [comment]
Thanks for pointing it out. I had the same issue.

**Comment by lionel-** [comment]
I'm not sure how to document in select helpers because they are reexported from tidyselect.

It looks like `?mutate_at` and `?vars` are informative enough?

**Comment by romainfrancois** [comment]
Yeah, let’s close this one.
