### ISSUE TITLE
enquo(var) followed by !!var does not work in tidytext::unnest_token

### ISSUE THREAD

**Issue by carioca67** [tidyverse/dplyr#2987]
### loads required libraries
```{r}
library(tidyverse)
library(tidytext)
```
### creates to 2-row tibble, test simple operation (it works)
```{r}
df <- tribble(~id,~descr,1,"hello bug",2,"goodbye bug")
df %>% select(id,descr) %>% unnest_tokens(word,descr)
```
> A tibble: 4 x 2
>     id    word
>  <dbl>   <chr>
>1     1   hello
>2     1     bug
>3     2 goodbye
>4     2     bug

### creates a parametrized dplyr 0.7.* version of the above
```{r}
myFn <- function(df, col1,col2) {
  col1 <- enquo(col1)
  col2 <- enquo(col2)
  df %>%  select(!!col1, !!col2) %>% # works
    unnest_tokens(word, !!col2) # this won't work
}
```

### Call to myFn below pukes at unnest_tokens()
```{r}
myFn(df,id,descr)
```
>Error: Invalid column specification

**Comment by lionel-** [comment]
That's because tidytext isn't ported to tidyeval yet. Could you move the issue there please.

**Comment by carioca67** [comment]
Lionel thanks -- where should I move it to?

dan

**Comment by lionel-** [comment]
To the tidytext package please.

**Comment by carioca67** [comment]
thanks lionel! done! congrats on the EXCELLENT work!
