### ISSUE TITLE
dplyr feature request, between() for character variables.

### ISSUE THREAD

**Issue by lhunsicker** [tidyverse/dplyr#2995]
---
I was referred here by the folks at RStudio.  I'm not sure that I'm in the right place,  as this is not a bug, but a suggestion for a new feature.  If there is a more appropriate place for this, let me know.

The between() function in dplyr is very nice and much appreciated.  But it  presently only works for numeric variables.  It would be nice (and much appreciated) to have a version that works for character variables, perhaps with an option for locale to set the correct sorting sequence.

Larry Hunsicker

```r
# insert reprex here
```

**Comment by krlmlr** [comment]
Thanks for reporting, this feature looks useful to me, too. To change the collation order, you could use `withr::with_collate()`.

**Comment by romainfrancois** [comment]
Closing this in favor of https://github.com/r-lib/vctrs/issues/147
