### ISSUE TITLE
dplyr 0.7.0 can't inner join two tables from different src

### ISSUE THREAD

**Issue by konny0201** [tidyverse/dplyr#3002]
the new version of dplyr can't work when join two tables from two different src by setting copy=TRUE.While it works with the 5.0.0dplyr version .

**Comment by konny0201** [comment]
@hadley

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by konny0201** [comment]
library(dplyr)
#####create two remote data source#####
src_database1=database1<- src_sqlite("database1", create = TRUE)
src_database2<- src_sqlite("database2", create = TRUE)

######copy a local dataframe to remote sources#######
copy_to(src_database1,iris,'iris1',temporary = FALSE)
copy_to(src_database2,iris,'iris2',temporary = FALSE)

iris1=tbl(src_database1,'iris1')
iris2=tbl(src_database2,'iris2')

########join two tables from two data source with parameter copy=TRUE########
iris1  %>% inner_join(iris2,copy=TRUE)

Joining, by = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species")
Error in rsqlite_send_query(conn@ptr, statement) : no such table: iris2

It is not work,what is wrong?

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by konny0201** [comment]
library(dplyr)
#> 
#> 杞藉叆绋嬭緫鍖咃細'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data=structure(list(Sepal.Length = c(5.1, 4.9, 4.7, 4.6, 5), Sepal.Width = c(3.5, 3, 3.2, 3.1, 3.6), Petal.Length = c(1.4, 1.4, 1.3, 1.5, 1.4),Petal.Width = c(0.2, 0.2, 0.2, 0.2, 0.2), Species = structure(c(1L,1L, 1L, 1L, 1L), .Label = c("setosa", "versicolor", "virginica"), class = "factor")), .Names = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species"), row.names = c(NA,5L), class = "data.frame")

src_source1=database1<- src_sqlite("data_source1", create = TRUE)
src_source2<- src_sqlite("data_source2", create = TRUE)


copy_to(src_source1,data,'data1',temporary = FALSE)
copy_to(src_source2,data,'data2',temporary = FALSE)

data1=tbl(src_source1,'data1')
data2=tbl(src_source2,'data2')


data1 %>% inner_join(data2,copy=TRUE)
#> Joining, by = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species")
#> Error in rsqlite_send_query(conn@ptr, statement): no such table: data2

**Comment by cderv** [comment]
@konny0201 , when you copy your code, then you are using `reprex::reprex()`, the result is put directly in your in your clipboard, formatted the right way for github. You don't need to copy the text in the viewer pane - I think it is what you've done. It is easier to read formatted that way:

``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data=structure(list(Sepal.Length = c(5.1, 4.9, 4.7, 4.6, 5), Sepal.Width = c(3.5, 3, 3.2, 3.1, 3.6), Petal.Length = c(1.4, 1.4, 1.3, 1.5, 1.4),Petal.Width = c(0.2, 0.2, 0.2, 0.2, 0.2), Species = structure(c(1L,1L, 1L, 1L, 1L), .Label = c("setosa", "versicolor", "virginica"), class = "factor")), .Names = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species"), row.names = c(NA,5L), class = "data.frame")

src_source1=database1<- src_sqlite("data_source1", create = TRUE)
src_source2<- src_sqlite("data_source2", create = TRUE)

copy_to(src_source1,data,'data1',temporary = FALSE)
copy_to(src_source2,data,'data2',temporary = FALSE)

data1=tbl(src_source1,'data1')
data2=tbl(src_source2,'data2')

data1 %>% inner_join(data2,copy=TRUE)
#> Joining, by = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species")
#> Error in rsqlite_send_query(conn@ptr, statement): no such table: data2
```
I have the error too

**Comment by konny0201** [comment]
@hadley @cderv I do really got how to use the reprex!Thank you very much for your patience.

**Comment by hadley** [comment]
Simpler reprex:

```R
library(dplyr, warn.conflicts = FALSE)

src1 <- src_sqlite(":memory:", create = TRUE)
src2 <- src_sqlite(":memory:", create = TRUE)

db1 <- copy_to(src1, iris, 'data1', temporary = FALSE)
db2 <- copy_to(src2, iris, 'data2', temporary = FALSE)

db1 %>% inner_join(db2, copy = TRUE)
```

I'll delete all the other attempts to clean up the issue.

**Comment by hadley** [comment]
Even simpler reprex

``` r
library(dplyr, warn.conflicts = FALSE)

src1 <- src_sqlite(":memory:", create = TRUE)
src2 <- src_sqlite(":memory:", create = TRUE)

db1 <- copy_to(src1, iris, 'data1', temporary = FALSE)
db2 <- copy_to(src2, iris, 'data2', temporary = FALSE)

same_src(db1, db2)
#> [1] TRUE
```
