### ISSUE TITLE
Only evaluate necessary clauses in case_when

### ISSUE THREAD

**Issue by klmr** [tidyverse/dplyr#3004]
R base’s `switch`, for all its flaws, supports a very useful pattern that’s currently impossible to emulate with `case_when`, to check argument validity:

```r
switch(
    x,
    foo = 1,
    bar = 2,
    stop("only “foo” and ”bar” supported")
)
```

I was expecting the following to work with `case_when` and was surprised to find that it doesn’t work:

```r
library(dplyr)
x = c('foo', 'bar')

case_when(
    x == 'foo' ~ 1,
    x == 'bar' ~ 2,
    TRUE ~ stop("only “foo” and ”bar” supported")
)
```

This will **always** evaluate the default case, regardless of the input, and consequently abort execution.

**Comment by klmr** [comment]
Similarly, `case_when` doesn’t support non-trivial values; for instance, the following fails:

```r
case_when(x == 1 ~ quo(1), x == 2 ~ quo(2))
```

This behaviour should at least be documented. But ideally this should be supported.

**Comment by lionel-** [comment]
Here you'd expect `case_when()` to return quosures evaluated in the formula environment right?

**Comment by klmr** [comment]
@lionel- Yes, same as any other RHS. `quo` shouldn’t be special-cased. It’s just that `case_when`’s current implementation has a line of code — `out <- value[[1]][rep(NA_integer_, m)]` that fails when the RHS type is a formula because `[.formula` doesn’t support `NA` indices.

**Comment by hadley** [comment]
I don't think it's possible for `case_when()` to work this way - it's fundamentally vectorised, and to figure out how long the output should be, we have to evaluate all the outputs.
