### ISSUE TITLE
dplyr 0.7.0 ignores 'vars' argument to `tbl_sql`

### ISSUE THREAD

**Issue by nc6** [tidyverse/dplyr#3005]
There is an optional `vars` argument to `tbl_sql`, used to override the column names. `dplyr-0.7.0` and above ignore this argument and call `db_get_fields` non contingently. 

See https://github.com/tidyverse/dbplyr/blob/master/R/tbl-sql.r#L14 vs 
https://github.com/tidyverse/dbplyr/commit/eeebd39f67cea7c95cfdee680cc9251d9801e4d1#diff-e9a252c895b2b550a955f8f1fc1e37d6L127

**Comment by hadley** [comment]
Is this causing you problems?
