### ISSUE TITLE
rlang version clash on clean install

### ISSUE THREAD

**Issue by AkhilNairAmey** [tidyverse/dplyr#3009]
Building an image of the current `dplyr` version (`dplyr_0.7.2.9000`) on a clean `rocker/r-ver:3.4.1` base hits an error

```
installing to /usr/local/lib/R/site-library/dplyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.1.1 is being loaded, but >= 0.1.1.9000 is required
ERROR: lazy loading failed for package ‘dplyr’
* removing ‘/usr/local/lib/R/site-library/dplyr’
Installation failed: Command failed (1)
```

The `Dockerfile` built to reproduce this error is:

```
FROM rocker/r-ver:3.4.1

RUN apt update && apt install -y \
   zlib1g-dev \
   libssl-dev \
   libcurl4-openssl-dev \
   libmariadb-client-lgpl-dev \
   libmariadbclient-dev \
   libpq-dev

RUN R -e 'install.packages("devtools")'

RUN R -e 'devtools::install_github("tidyverse/dplyr")'
```

I could just use `rocker/tidyverse` to use `dplyr`, but I'm just surprised the straight install fails due to dependency mismatch.

**Comment by AkhilNairAmey** [comment]
Installation with `littler` from the docker image works though.

```
FROM rocker/r-ver:3.4.1

RUN apt update && apt install -y \
   zlib1g-dev \
   libssl-dev \
   libcurl4-openssl-dev \
   libmariadb-client-lgpl-dev \
   libmariadbclient-dev \
   libpq-dev

RUN install2.r --error \
    --deps TRUE \
    dplyr
```

**Comment by krlmlr** [comment]
This should work if you manually install rlang from GitHub first, or if you use `remotes::install_github()` or `remotes::install_local()` .

**Comment by AkhilNairAmey** [comment]
@krlmlr This worked cleaning with `remotes` :) thanks.  Please could you let me know what `devtools` and `remotes` are doing differently with dependencies?

**Comment by krlmlr** [comment]
This should have worked with devtools in the first place, eventually devtools will forward all call to remotes.
