### ISSUE TITLE
[dbplyr] Unclear logic in window vs. aggregate function checking

### ISSUE THREAD

**Issue by jarodmeng** [tidyverse/dplyr#3010]
`dbplyr` (v1.1.0.9000) currently checks if a SQL translator has a window function for each aggregate function in [this snippet of code](https://github.com/tidyverse/dbplyr/blob/master/R/translate-sql-helpers.r#L60).

```r
  # Need to check that every function in aggregate also occurs in window
  missing <- setdiff(ls(aggregate), ls(window))
  if (length(missing) > 1) {
    warn(paste0(
      "Translator is missing window functions:\n",
      paste0(missing, collapse = ", ")
    ))
  }
```

The warning message is only issued when there are at lest 2 missing window functions. It's unclear from the code why having 1 missing window function is tolerated, but not 2 or more.

**Comment by hadley** [comment]
Doh, thanks for spotting that!
