### ISSUE TITLE
Feature Request: combined group by for all groupings of supplied variables.

### ISSUE THREAD

**Issue by pmgurman** [tidyverse/dplyr#3011]
A workflow that I am currently using regularly requires summary statistics to be calculated using a combination of `group_by()` and `do()`. I also want the same summaries for higher level groupings. This code feeds into a shiny application that allows users to filter by NA's. An example should make more sense.

``` r
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats

df1 <- mtcars %>% group_by(cyl, gear) %>% summarise(mpg = mean(mpg))
df2 <- mtcars %>% group_by(cyl) %>% summarise(mpg = mean(mpg))
df3 <- mtcars %>% group_by(gear) %>% summarise(mpg = mean(mpg))
df4 <- mtcars %>% summarise(mpg = mean(mpg))

full_join(df1,df2) %>% full_join(df3) %>% full_join(df4)
#> Joining, by = c("cyl", "mpg")
#> Joining, by = c("gear", "mpg")
#> Joining, by = "mpg"
#> # A tibble: 15 x 3
#> # Groups:   cyl [?]
#>      cyl  gear      mpg
#>    <dbl> <dbl>    <dbl>
#>  1     4     3 21.50000
#>  2     4     4 26.92500
#>  3     4     5 28.20000
#>  4     6     3 19.75000
#>  5     6     4 19.75000
#>  6     6     5 19.70000
#>  7     8     3 15.05000
#>  8     8     5 15.40000
#>  9     4    NA 26.66364
#> 10     6    NA 19.74286
#> 11     8    NA 15.10000
#> 12    NA     3 16.10667
#> 13    NA     4 24.53333
#> 14    NA     5 21.38000
#> 15    NA    NA 20.09062
```
Can some kind of switch be added to the `group_by()` function to allow this functionality?

**Comment by Hong-Revo** [comment]
I think you want to do a `bind_rows`, not `full_join` as your last step.

I also find this kind of amusing given that SAS' `proc summary` has had this functionality since the year dot....

**Comment by WilDoane** [comment]
this is awful code, but consider...

library(tidyverse)

ff <-
  function(df, col1, col2, func = mean) {
    col1_eq <- enquo(col1)
    col2_eq <- enquo(col2)
    
    full_join(    
      df %>% 
        group_by(!!col1_eq, !!col2_eq) %>% 
        summarize(mpg = func(mpg))
      ,
      df %>% 
        group_by(!!col1_eq) %>% 
        summarize(mpg = func(mpg))
    ) %>% 
      full_join(
        df %>% 
          group_by(!!col2_eq) %>% 
          summarize(mpg = func(mpg))
      ) %>% 
      full_join(
        df %>% 
          summarize(mpg = func(mpg))
      )
  }

mtcars %>% 
  ff(cyl, gear, var)

**Comment by pmgurman** [comment]
The following code improves on the above code, allowing for any number of groups. I do think that there should be scope somehow in the `group_by()` statement for some kind of named argument that switches this functionality on at the C# level, maybe something like `margins = TRUE`?

``` r
suppressPackageStartupMessages(library(tidyverse))

vars <- c("vs","cyl","gear")
levels <- unlist(lapply(0:length(vars), function(x) combn(vars, x, simplify = FALSE)), recursive = FALSE)

calc_stats <- function(df, vars)  {
  if (length(vars) == 0) {
    df %>% summarise(mean = mean(mpg))
  } else {
    vars_quo <- sapply(vars, function(x) quo(!! rlang::sym(x)))
    df %>% group_by(!!! vars_quo) %>% summarise(mean = mean(mpg)) %>% ungroup()
  }

}

df_summary <- list()
for (i in 1:length(levels)) {
  # I have reversed the insertion order into the list so that the largest df columnwise is first
  df_summary[[(length(levels) - (i - 1))]] <- calc_stats(mtcars, levels[[i]])
}

bind_rows(df_summary)
#> # A tibble: 38 x 4
#>       vs   cyl  gear   mean
#>    <dbl> <dbl> <dbl>  <dbl>
#>  1     0     4     5 26.000
#>  2     0     6     4 21.000
#>  3     0     6     5 19.700
#>  4     0     8     3 15.050
#>  5     0     8     5 15.400
#>  6     1     4     3 21.500
#>  7     1     4     4 26.925
#>  8     1     4     5 30.400
#>  9     1     6     3 19.750
#> 10     1     6     4 18.500
#> # ... with 28 more rows
```

**Comment by hadley** [comment]
This may be something we consider in the future, but currently grouping assumes each row of input only appears once in the grouped output.
