### ISSUE TITLE
copy_to(con, df, in_schema(sch, tab)) broken for several SQL backends

### ISSUE THREAD

**Issue by baileych** [tidyverse/dplyr#3013]
When using dbplyr to interact with a Postgres database, attempts to write tables into schema "sch" via `copy_to` or `db_write_table` fail with an error indicating that "sch.table" does not exist.  This occurs because the backend `db_write_table` methods for several rdbms call `ident` on the table name, overriding any existing `ident_q` classification.

Proposed solution in https://github.com/tidyverse/dbplyr/pull/31 

```r
require(RPostgreSQL)
require(dplyr)

con <- dbConnect(PostgreSQL(), dbname = 'test');  # add credentials as needed
DBI::dbExecute(con, 'create schema if not exists testme');
copy_to(con, data.frame(x = c('1', '2')), in_schema('testme',' testing'), temporary = FALSE)
```

**Comment by sz-cgt** [comment]
The PR from @baileych doesn't universally fix this.  Or put differently, there's more than one issue here.  DBI-based connections break differently.

Reading dbi-s3.r. it looks like using `in_schema()` when calling `db_write_table()` (or `db_copy_to()`) on a DBI connection should pass through correctly.  `in_schema()` returns an `ident_q` object, which `as.sql()` should leave alone and `dbi_quote()` should wrap the value in `DBI::SQL()`.  

However, when I try that on a Hive database, something is quoting the entire schema.table combination.  Explicitly passing `DBI::SQL("schema.table")` works, but it feels like a hack having to do that.

**Comment by hadley** [comment]
Fixed in https://github.com/tidyverse/dbplyr/commit/3cc019dc1121480c44dbde65d60a19d6194b40c4.

@sz-cgt if this doesn't help you, please file a new issue with reprex.
