### ISSUE TITLE
[dplyr] SAP HANA (sqlscript) via odbc

### ISSUE THREAD

**Issue by Ferbster** [tidyverse/dplyr#3014]
Hi,

I am using the odbc package to connect to a SAP HANA database. 
Afterwards I want to do my data wrangling using dplyr.
So far everything works as expected, except for the n() function.

I am not sure how to create a reprex for this issue, but I will describe the issue a bit more in detail.
I want to do some standard operation on the table. First grouping the data and then counting the observations per group. However, I need it to work with mutate and while it works with summarise() it doesn't work with mutate().
Maybe it is just the start of errors concerning this sql dialect, but we have to start somewhere.

`db_table %>% group_by(var_1) %>% summarise(n = n()) `
This das work.

`db_table %>% group_by(var_1) %>% mutate(n = n()) `
Tis doesn't.

The error message is:

>  Error in new_result(connection@ptr, statement) : 
> nanodbc/nanodbc.cpp:1344: S1000: [SAP AG][LIBODBCHDB DLL][HDBODBC] General error;260 invalid column name: The column 'XXX/YYY.ZZZ' is invalid in the select list because the GROUP BY clause or an aggregation function does not contain it: line 1 col 8 (at pos 7) 

When I do the same operation on a local tibble it works just fine as expected.

**Comment by edgararuiz** [comment]
Hi @Ferbster , this issue affected more than just HANA sources.  I have made the correction in a branch.  Would you mind testing it and letting me know? `devtools::install_github("edgararuiz/dbplyr", ref = "fix-odbc-count")`
