### ISSUE TITLE
Feature request: re-export the functions from rlang

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverse/dplyr#3016]
By which I mean the functions for quosure manipulation, like `quo`, `sym` et al. Since you'll need them anyway if you want to use dplyr programmatically.

**Comment by lionel-** [comment]
This is planned for the next release.

**Comment by Hong-Revo** [comment]
Great! Would you know when the next release is likely to be?

(Before Sept would be ideal as that's when the next Microsoft R Server release is planned for.)

**Comment by hadley** [comment]
And `.data`

**Comment by romainfrancois** [comment]
up. do we have a list of what needs to be re exported ? @lionel-

**Comment by lionel-** [comment]
Oh I think we have everything already: https://github.com/tidyverse/dplyr/blob/master/R/utils-tidy-eval.R
