### ISSUE TITLE
Implement variant of desc() that doesn't rewrite the entire vector

### ISSUE THREAD

**Issue by rasmusrhl** [tidyverse/dplyr#3017]
Use of desc() outside arrange yields negative result:
```r
iris %>% count( dplyr::desc( Sepal.Width)) 
```

Outputs:

```r

# A tibble: 23 x 2
   `dplyr::desc(Sepal.Width)`     n
                        <dbl> <int>
 1                       -4.4     1
 2                       -4.2     1
 3                       -4.1     1
 4                       -4.0     1
 5                       -3.9     2
 6                       -3.8     6
 7                       -3.7     3
 8                       -3.6     4
 9                       -3.5     6
10                       -3.4    12
# ... with 13 more rows
```

Can't tell if it is a bug or a feature.

**Comment by bschneidr** [comment]
This seems like neither a bug nor a feature. This is sort of like calling a plumber and telling them that your plumbing doesn't correctly handle Lego castles: there's a problem, but it's not a design issue.

The following code would probably accomplish your goal, in a more idiomatic way for the tidyverse.

```r
iris %>% 
    count(Sepal.Width) %>% 
    arrange(desc(Sepal.Width))
```

**Comment by krlmlr** [comment]
This is how `desc()` works, but we could consider an `fdesc()` function that just adds an attribute to a vector which will mark it to be sorted in descending order.

**Comment by romainfrancois** [comment]
Also note that `desc` is handled internally inside of `arrange` and never calls the `dplyr::desc` R function inside arrange. 

https://github.com/tidyverse/dplyr/blob/master/src/arrange.cpp#L39
