### ISSUE TITLE
dplyr::select function is not working, leading to error

### ISSUE THREAD

**Issue by yuchenw** [tidyverse/dplyr#3018]
---
Today after I did package updates, suddenly I could not use the `dplyr::select` function.
```r
library(dplyr)
mtcars %>% select(cyl)

Error in mut_env_parent(overscope$.top_env, lexical_env) : 
  object 'rlang_mut_env_parent' not found
```
I am using `R 3.4.1` on a windows machine, with `dplyr_0.7.2` and `rlang_0.1.2` . Please let me know if you want to see complete session info.

**Comment by deandagan** [comment]
Have the exact same issue and I'm using R 3.3.2 with dplyr_0.7.2.

**Comment by yuchenw** [comment]
After installing the developmental version (dplyr_0.7.2.9000), the issue seems to be fixed. For people who encounter the same issue, try `devtools::install_github("hadley/dplyr")`.

**Comment by lionel-** [comment]
Apparently there's an issue on Windows if you install a package from source and that package is already loaded. In that case the installer may fail to copy over the loaded DLL.

Could you try reinstalling rlang on a fresh session of R please?
