### ISSUE TITLE
result of function mutate_each_ not consisit with old versions

### ISSUE THREAD

**Issue by earthcli** [tidyverse/dplyr#3020]
```r
mutate_each_(data.frame(t=30:35,x=1:6),funs(CDD=ifelse(.<33,33-.,0)),vars="t")
```

with dplyr>0.5 it yield t, x, CDD
with dplyr>0.7.2 it yield t, x, t_CDD

```r
mutate_each_(data.frame(t=30:35,x=1:6),funs(CDD=ifelse(.<33,33-.,0)),vars=c("t","x"))
```

**Comment by krlmlr** [comment]
Thanks, confirmed.

@lionel: One fix would be to make `vars` unnamed in https://github.com/tidyverse/dplyr/pull/2956/files#diff-b5604a13d7d44d0c36969db187e7e5bbR257, this conflicts with #2956 so needs to wait.

**Comment by krlmlr** [comment]
The same happens if more than one function is passed. @earthcli: Can you confirm?

**Comment by earthcli** [comment]
@krlmlr Yes, with this example:
mutate_each_(data.frame(t=30:35,x=1:6),funs(CDD=ifelse(.<33,33-.,0),GDD=ifelse(.>33,.-33.,0)),vars="t")
it results: t x t_CDD t_GDD

**Comment by krlmlr** [comment]
And with dplyr 0.5.0 this was different?

**Comment by earthcli** [comment]
@krlmlr Yes, it is different, it results: t x CDD GDD
