### ISSUE TITLE
How to properly return character values for dplyr's do function?

### ISSUE THREAD

**Issue by dfrankow** [tidyverse/dplyr#3021]
I'd appreciate anyone who can answer https://stackoverflow.com/questions/45678441/how-to-properly-return-character-values-from-dplyrs-do, reproduced below:

Consider the following code:

```
foo <- function() {
  if (runif(1) < 0.5) {
    return(data.frame(result="low"))
  } else {
    return(data.frame(result="high"))
  }
}

df = data.frame(val=c(1,2,3,4,5,6))
df %>% group_by(val) %>% do(foo())
```

It is random, but if there are both "low" and "high" results returned, you'll see errors like this:

```
Warning messages:
1: In bind_rows_(x, .id) : Unequal factor levels: coercing to character
2: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
3: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
4: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
5: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
```

I believe the first value being returned (say, "low") is converted into a factor with one level, and when the other level comes along, it incurs dplyr's wrath.

What is the proper way to code this example to avoid the warnings?

Edit: One solution is this:

```
foo <- function() {
  if (runif(1) < 0.5) {
    return(data.frame(result=factor("low", levels=c("low", "high"))))
  } else {
    return(data.frame(result=factor("high", levels=c("low", "high"))))
  }
}
```
But what if I don't know the factor levels ahead of time?

Also, more fundamentally, I'd like to return a character vector, not a factor.

**Comment by krlmlr** [comment]
Closing, the SO question seems to be answered now.
