### ISSUE TITLE
Treat NULL as empty vectors in `vars` argument of _at() variants?

### ISSUE THREAD

**Issue by earthcli** [tidyverse/dplyr#3023]
when the vars is NULL, mutate_each_ function will execute the functions on each column, while I expect do nothing!

mutate_each_(data.frame(x=1:5,y=3),funs(.*3),vars=NULL)

**Comment by lionel-** [comment]
These functions are deprecated. `mutate_at()` seems to do the right thing.

**Comment by earthcli** [comment]
Thanks!
but mutate_at also not work with .vars=NULL
mutate_at(data.frame(x=1:5,y=3),funs(.*3),.vars=NULL)

Error: `.vars` must be a character/numeric vector or a `vars()` object, not NULL

**Comment by lionel-** [comment]
It works with an empty vector, which you can create with `vars()`. We may want to treat `NULL` as empty vectors though, since we've been doing that in purrr's typed mappers in the last release.

**Comment by lionel-** [comment]
For now you can work around this with `myvars %||% vars()` if `myvars` might be `NULL`.

**Comment by earthcli** [comment]
Thank you very much!
I ask this because I have written some functions before.  I will wait for the new version, otherwise I have to modify all my old functions.
