### ISSUE TITLE
select() fails with columns named with numbers only

### ISSUE THREAD

**Issue by EBukin** [tidyverse/dplyr#3027]
Using `select()` and `select_()` with a data frame that contains columns named with the numbers returns different results and fails (in some cases).

I have faced the following problems while working on the windows machine with the recent version of `dplyr` installed with `devtools::install_github("hadley/dplyr")` and `rlang` version 0.1.2.

```r
tb <- tibble(a = letters[1:5],
             b = LETTERS[6:10],
             `1` = c(1:5),
             `2` = c(6:10))
columns <- names(tb)[!names(tb) %in% "c"]
all_equal(select(tb,  columns), select_(tb,  .dots = columns))
# Returns
[1] "Cols in x but not y: `1`, `2`. "
```
Naming columns with `3` and `4` instead of `1` and `2` returns correct results, however it only works when the column name corresponds to the column position. 
```r
tb <- tibble(a = letters[1:5],
             b = LETTERS[6:10],
             `3` = c(1:5),
             `4` = c(6:10))
columns <- names(tb)[!names(tb) %in% "c"]
all_equal(select(tb,  columns), select_(tb,  .dots = columns))
# Returns
[1] "Cols in x but not y: `1`, `2`. "
```
Having columns `5` and `6` instead of `3` and `4`  returns an error when using `select_()` .

```r
tb <- tibble(a = letters[1:5],
             b = LETTERS[6:10],
             `5` = c(1:5),
             `6` = c(6:10))
columns <- names(tb)[!names(tb) %in% "c"]

select(tb,  columns)
## A tibble: 5 x 4
#      a     b   `5`   `6`
#  <chr> <chr> <int> <int>
#1     a     F     1     6
#2     b     G     2     7
#3     c     H     3     8
#4     d     I     4     9
#5     e     J     5    10

select_(tb,  .dots = columns)
# Error in combine_vars(vars, ind_list) : Position must be between 0 and n
```
I've noticed some awkward returns in `eval_tidy()` used in the `select_vars()`. Could it be linked to the issue  #https://github.com/tidyverse/rlang/issues/227? Does this relates to the #3018?

**Comment by lionel-** [comment]
That's because

- In the evaluation environment of selecting functions, column names represent their own positions. `cyl` doesn't evaluate to `mtcars$cyl` but to `2`.

- `select_()` parses the input and finds numbers, not strings. Therefore it thinks it has column positions, not column names.

The underscored variants are no longer under development.

**Comment by lionel-** [comment]
Note that using a contextual object within selecting function is soon going to give an error. See https://github.com/tidyverse/tidyr/blob/master/NEWS.md for more information.

The recommended way to supply a character vector of column names is with quasiquotation: `select(df, !! col_names)`.

**Comment by lionel-** [comment]
Also the error you're seeing here is due to a fundamental ambiguity in the way SE functions treat their inputs, so it couldn't be fixed in principle.

**Comment by EBukin** [comment]
Thanks!
