### ISSUE TITLE
Not all doubles recognized by `dplyr::filter`

### ISSUE THREAD

**Issue by mwesthues** [tidyverse/dplyr#3031]
When I have the values `0.3`, `0.6` or `0.7` encoded as type `double`, I cannot select them unless I filter them while searching for the characters (*e.g.* `"0.3"`) instead. This is not the case for other decimal numbers that I have tested.

```r
# Example data
dummy <- tibble::data_frame(A = seq(from = 0, to = 1, by = 0.1))

# Works
dummy %>% dplyr::filter(A == 0.1)
dummy %>% dplyr::filter(A == 0.2)

# Returns tibble with zero rows.
dummy %>% dplyr::filter(A == 0.3)
dummy %>% dplyr::filter(A == 0.6)
dummy %>% dplyr::filter(A == 0.7)

# Works
dummy %>% dplyr::filter(A == "0.3")
dummy %>% dplyr::filter(A == "0.6")
dummy %>% dplyr::filter(A == "0.7")

```

**Comment by romainfrancois** [comment]
this is r faq 7.31: 

https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f

**Comment by Hong-Revo** [comment]
Also relevant:

[What every computer scientist should know about floating point arithmetic](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)

**Comment by mwesthues** [comment]
It surprised me that this problem consistently arose for those three numbers but not for the others. I'll be on the watch from now on and pay very close attention to this.

About the floating-point arithmetic: I didn't expect `sqrt(2) * sqrt(2) == 2` to be `TRUE`, but I have also never seen something like `0.3 == 0.3` to not evaluate to `TRUE` in `R`, hence my lack of care to this detail in subsetting. If you encounter a similar level of ignorance with other users, perhaps you could implement a warning when someone tries to `dplyr::filter()` using doubles.
