### ISSUE TITLE
Filtering Impala tables with regular expressions

### ISSUE THREAD

**Issue by thanosgatos** [tidyverse/dplyr#3032]
*Remark*: This is posted here, since I think that this functionality should be available in `dplyr`.

I've been playing around with Impala, using `implyr`, and I've realized that using `dplyr`'s `filter()` in conjuction with `stringr` functions, like `str_detect()` in my case, spits out an error.

Working with a local dataset, the following works just fine:

```r
iris %>% 
  filter(str_detect(Species, ".*osa$")) %>% 
  group_by(Species) %>% 
  tally()
```

What I have tried was the following, assuming we want to match all rows, where _type_ is "myowntype blah blah blah", where all "blah" could be whatever--I am using dummy variables in the place of my own, since it is impossible to provide a reprex:

```r
impala_tbl %>%
  filter(str_detect(type, "^myown.*")) %>%
  collect()
```

The error I get is the following:

```
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: HY000: [Cloudera][ImpalaODBC] (110) Error while executing a query in Impala: [HY000] : AnalysisException: default.str_detect() unknown
```

Looking into the SQL `dplyr` is generating, this makes sense--once again replacing the **same** dummy variables from above:

```sql
<SQL>
SELECT *
FROM default.press_in_anp_pin_table_string
WHERE (STR_DETECT(`type`, '^myown.*'))
```

Perfectly normal the fact that we're getting an error: `STR_DETECT(`type`,  '^myown.*')` is **not** valid SQL--not even going to whether it is supported by Impala. Therefore, the question becomes: What R code would cause `dplyr` to generate an SQL `LIKE` clause, since we essentially want to have the last line of the last block of code being

```sql
WHERE type LIKE '^myown.*'
```

This, in turn, would lead to our next problem: the regex, which would need to be converted to a regex that SQL understands.

**Comment by hadley** [comment]
We may consider this at some point in the future, but it's going to be challenging because regexp support differs from db to db. In the mean-time, you can use `%like%`:

```R
impala_tbl %>%
  filter(type %LIKE% "^myown.*") %>%
  collect()
```
