### ISSUE TITLE
Using slice with a function call and a substituted expression

### ISSUE THREAD

**Issue by matdoering** [tidyverse/dplyr#3034]
Hey, 
I'm using dplyr's slice function to determine unique pairs of indices that yield the smallest value in a data frame (*DeltaG* in the example). Since I don't want to have a local evaluation of the data frame variable because *R CMD check* will output a warning in this case, I am using *substitute()* instead. However,  
combining *which.min()* with the substitute expression seems to fail for some reason ... I'd be grateful if someone could comment whether there's another way to do this at the moment.

Here's the example:

```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
# Goal: find unique pair of indices with smallest DeltaG
results <- data.frame("Idx1" = c(1, 1, 2, 1), "Idx2" = c(2, 3, 3, 2), "DeltaG" = c(1.546, 1.222, 1.199, 1.785))
# doesn't work: empty tibble returned
result <- results %>% 
            dplyr::group_by(.dots = c("Idx1", "Idx2")) %>% 
            dplyr::slice(which.min(substitute(DeltaG)))
#> Warning in which.min(substitute(DeltaG)): (symbol) object cannot be coerced
#> to type 'double'

#> Warning in which.min(substitute(DeltaG)): (symbol) object cannot be coerced
#> to type 'double'

#> Warning in which.min(substitute(DeltaG)): (symbol) object cannot be coerced
#> to type 'double'
# works but produces R CMD check warning due to unbound variable 'DeltaG'
result <- results %>% 
            dplyr::group_by(.dots = c("Idx1", "Idx2")) %>% 
            dplyr::slice(which.min(DeltaG))
# alternatives to substituting the variable?
```

Thanks and best regards
 Matthias

**Comment by lionel-** [comment]
I would use `quote()` instead of `substitute()` here, since you don't want code expansion but simple quoting. You can inline the symbol with `!!`:

```r
slice(which.min(!! quote(DeltaG)))
```

Or use the `.data` pronoun. You can import the dummy object `rlang::.data` to avoid the NOTE:

```r
slice(which.min(.data$DeltaG))
```

**Comment by matdoering** [comment]
Thanks a bunch, both very nice solutions; I didn't know about neither *!!* nor *.data*. I also found another solution by using the underscore variant of arrange, which is not as concise:

```{r}
library(dplyr)
# Goal: find unique pair of indices with smallest DeltaG
results <- data.frame("Idx1" = c(1, 1, 2, 1), "Idx2" = c(2, 3, 3, 2), "DeltaG" = c(1.546, 1.222, 1.199, 1.785))
# this works (one additional line)
result <- results %>% 
            dplyr::group_by(.dots = c("Idx1", "Idx2")) %>% 
            dplyr::arrange_("DeltaG") %>%
            dplyr::slice(1)
```
