### ISSUE TITLE
summarise_all(max) does not preserve integer type

### ISSUE THREAD

**Issue by heavywatal** [tidyverse/dplyr#3036]
The results of `summarise_all(max)` and `summarise_all(min)` are converted to double, whereas `max()` and `summarise_all(sum)` preserve integer type as expected.

``` r
library(dplyr)
tbl = tibble(x=seq_len(3L))
tbl %>% summarise_all(max)
#> # A tibble: 1 x 1
#>       x
#>   <dbl>
#> 1     3
tbl$x %>% max() %>% class()
#> [1] "integer"
tbl %>% summarise_all(sum)
#> # A tibble: 1 x 1
#>       x
#>   <int>
#> 1     6
```

**Comment by krlmlr** [comment]
Thanks, confirmed.

**Comment by krlmlr** [comment]
@hadley: What should `max(integer())` return in hybrid evaluation? Currently it returns `-Inf` without warning, but this is why `max()` *always* returns numerics. Another option would be `-INT_MAX`, seems okay because this use case looks sufficiently rare.

**Comment by hadley** [comment]
Is this really a problem?

**Comment by krlmlr** [comment]
Only in corner cases (zero-row tibbles, later perhaps for empty groups #341), but we do need to account for it. I'd opt for changing to integer and return `-INT_MAX` or `NA_integer_` in this case.

**Comment by hadley** [comment]
I think I'd rather have `max()` consistently return a double - I think it's better to enforce type stability by widening the type to include all possible outputs, rather than returning a different value to base R.

**Comment by krlmlr** [comment]
That's the way it is currently implemented. We do have a few other inconsistencies between hybrid and standard, even with our own functions (#2792).

**Comment by krlmlr** [comment]
Closing, consistency between the grouped and ungrouped cases is now part of the issue linked from above.
