### ISSUE TITLE
case_when fails in mutate with zero-row tbl_df

### ISSUE THREAD

**Issue by peterwsetter** [tidyverse/dplyr#3041]
When using case_when in mutate, if the input tbl_df has zero rows, I receive the error: Error in Error in mutate_impl(.data, dots) : 
  Evaluation error: LHS of case 1 (`price > 900`) must be length 1 (the longest input), not 0.

```r
tibble::tibble(
	price = numeric(0)
) %>%
	dplyr::mutate(new_col = dplyr::case_when(price > 900 ~ "Super Expensive", 
									   price >= 500 ~ "Expensive", 
									   price >= 100 ~ "Mild",
									  TRUE ~ "Cheap"))
```

**Comment by lionel-** [comment]
Simpler rexprex:

```r
case_when(
  lgl() ~ "foo",
  TRUE ~ "bar"
)
```

@hadley Would it make sense to special-case a `TRUE` lhs so that it's length doesn't count? It would need to be a literal `TRUE`, e.g. `identity(TRUE)` would not be interpreted in that way.

**Comment by hadley** [comment]
The only time it's a problem is when the input has length zero, so I think a special case for that is probably better (i.e. just subset the first rhs with `[0]`).

**Comment by krlmlr** [comment]
I'll take a look.
