### ISSUE TITLE
Accelerate CharacterVectorOrderer

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3044]
https://github.com/tidyverse/dplyr/pull/2969#issuecomment-324138511

It currently calls `sort()` and `match()`, we might make do with a single `order()` call.

**Comment by krlmlr** [comment]
Alternatively, we could use sort keys:

1. Compute sort key for each string, see bottom of http://userguide.icu-project.org/collation
2. Use radix sort via `Rf_sort()` (or a custom implementation)

It would be great if we could cache the sort key somewhere, maybe as an attribute to each `CHARSXP`?

**Comment by romainfrancois** [comment]
`CharacterVectorOrderer` will likely disappear when we start using `vctrs::vec_compare_proxy`
