### ISSUE TITLE
dplyr unnest_tokens not working

### ISSUE THREAD

**Issue by AngryR11** [tidyverse/dplyr#3052]
I am loading one of the 5-core datasets from

[Reviews](http://jmcauley.ucsd.edu/data/amazon/)

using

```
library(sparklyr)
library(dplyr)
```

```
config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "2G"
sc = spark_connect(master = "local",config = config)
df=spark_read_json(sc = sc, name = "videos", path = "Path/to/reviews_Office_Products_5.json")
```
where one of the variables is a column of text reviews, likewise:

`select(df,reviewText)`

```
# Source: lazy query [?? x 1]

# Database: spark_connection reviewText

1 I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 wh

2 "WHY THIS BELATED REVIEW? I feel very obliged to share my views about this old workhor

3 I have an HP 48GX that has been kicking for more than twenty years and an HP 11 that i

4 I've started doing more finance stuff recently and went looking for a good time-value-

5 For simple calculations and discounted cash flows, this one is still the best. I used

6 While I don't have an MBA, it's hard to believe that a calculator I learned how to use

7 I've had an HP 12C ever since they were first available, roughly twenty years ago. I'

8 Bought this for my boss because he lost his. He loves this calculator & would not be

9 This is a well-designed, simple calculator that handles typical four-function math. La

10 I love this calculator, big numbers and calculate excellent so easy to use and make my

# ... with more rows
```

I want to split the reviews into tokens, with each row containing a word, but that has proven to be difficult. When I try to use the function unnest_tokens, I get the following error message:

```
library(stringr)
library(tidytext) 

Word_by_Word <- df %>% unnest_tokens(word

, reviewText)
```
`Error in unnest_tokens_.default(., word, reviewText) : unnest_tokens expects all columns of input to be atomic vectors (not lists)`
How do I fix this without using the command "pull" (which stores the data in memory) and coercing the data into the requested format? I can not pull the data as suggested in [Extract a dplyr tbl column as a vector](https://stackoverflow.com/questions/21618423/extract-a-dplyr-tbl-column-as-a-vector)  or convert the data into a tibble format, because if the database is too big and I do any of those, the computer runs out of memory even after increasing the 2G limit and running the program on a computer with a lot of memory (that's the hole point of using dplyr instead).

**Comment by AngryR11** [comment]
I am loading one of the 5-core datasets from

[](http://jmcauley.ucsd.edu/data/amazon/)

using

```
library(sparklyr)
library(dplyr)
```

```
config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "2G"
sc = spark_connect(master = "local",config = config)
df=spark_read_json(sc = sc, name = "videos", path = "Path/to/reviews_Office_Products_5.json")
```
where one of the variables is a column of text reviews, likewise:

`select(df,reviewText)`
**# Source: lazy query [?? x 1]

# Database: spark_connection reviewText

1 I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 wh

2 "WHY THIS BELATED REVIEW? I feel very obliged to share my views about this old workhor

3 I have an HP 48GX that has been kicking for more than twenty years and an HP 11 that i

4 I've started doing more finance stuff recently and went looking for a good time-value-

5 For simple calculations and discounted cash flows, this one is still the best. I used

6 While I don't have an MBA, it's hard to believe that a calculator I learned how to use

7 I've had an HP 12C ever since they were first available, roughly twenty years ago. I'

8 Bought this for my boss because he lost his. He loves this calculator & would not be

9 This is a well-designed, simple calculator that handles typical four-function math. La

10 I love this calculator, big numbers and calculate excellent so easy to use and make my

# ... with more rows
I want to split the reviews into tokens, with each row containing a word, but that has proven to be difficult. When I try to use the function unnest_tokens, I get the following error message:**

```
library(stringr)
library(tidytext) 

Word_by_Word <- df %>% unnest_tokens(word

, reviewText)
```
**Error in unnest_tokens_.default(., word, reviewText) : unnest_tokens expects all columns of input to be atomic vectors (not lists)**
How do I fix this without using the command "pull" (which stores the data in memory) and coercing the data into the requested format? I can not pull the data as suggested in [](https://stackoverflow.com/questions/21618423/extract-a-dplyr-tbl-column-as-a-vector)  or convert the data into a tibble format, because if the database is too big and I do any of those, the computer runs out of memory even after increasing the 2G limit and running the program on a computer with a lot of memory (that's the hole point of using dplyr instead).

**Comment by AngryR11** [comment]
I am also not being able to run regressions. After running 
```
regression<-df %>%  do(reg = lm( unixReviewTime ~  numbstars, data = .))
tidy(regression, reg)
```
I got the following error message:
```
Error in as.data.frame.default(x) : 
  cannot coerce class "c("simpleError", "error", "condition")" to a data.frame
```
So, can I only use dplyr to do simple data manipulation? I can not use it to run regressions or do anything more complex without storing the data in memory, is that it?

**Comment by edgararuiz** [comment]
Hi @AngryR11 , `unnest_tokens()` should only work with "local" data in you R environment, not data that's loaded in Spark via `sparklyr`.  To do this inside Spark, you'll need to use a Spark specific feature transformer to create the tokens, `sparklyr` has a wrapper for it, and it's called `ft_tokenizer()`, here's the reference page for it: https://spark.rstudio.com/reference/ft_tokenizer.html

**Comment by AngryR11** [comment]
Hi @edgararuiz, thank you for the reply. I hv tried using ft_tokenizer, but got the following error:
```
> tr %>% ft_tokenizer("reviewText")
Error in ensure_scalar_character(output.col) : 
  'NULL' is not a length-one character vector
```

**Comment by edgararuiz** [comment]
Right, these kinds of functions require an input and output column:

```
df %>% ft_tokenizer("reviewText", "word")
```

**Comment by AngryR11** [comment]
I see, but according to this website I still hv to collect the data into memory in order to unnest the tokens

[https://campus.datacamp.com/courses/introduction-to-spark-in-r-using-sparklyr/going-native-use-the-native-interface-to-manipulate-spark-dataframes?ex=6](https://campus.datacamp.com/courses/introduction-to-spark-in-r-using-sparklyr/going-native-use-the-native-interface-to-manipulate-spark-dataframes?ex=6)

**Comment by edgararuiz** [comment]
You're correct, there are a couple of new functions in `sparklyr` that can help you do this inside Spark, but it will require creating a variable per each word in a line and then creating one big table with all of them.  Lots of grunt work, but it will keep the process in Spark.  If interested, I'd suggest opening an issue to create a function that simplifies that unnesting of these tokens.  Here's an example code:

```
library(dplyr)
library(sparklyr)
library(janeaustenr)

sc <- spark_connect(master = "local", version = "2.1.0")

austen     <- austen_books()
austen_tbl <- copy_to(sc, austen, overwrite = TRUE)


tokenized2 <-  austen_tbl %>% 
  na.omit() %>%
  ft_tokenizer(input.col = "text", output.col = "tokens")

word <- tokenized2 %>%
  sdf_separate_column("tokens", c("w1", "w2", "w3"))

all_words <-  select(word , book, word = w1) %>%
  sdf_bind_rows(select(word, book, word = w2)) %>%
  sdf_bind_rows(select(word, book, word = w3))


all_words

```

**Comment by kevinykuo** [comment]
@AngryR11 You can also unnest on the Spark side with `explode()`, e.g.

```
tokenized3 <- austen_tbl %>% 
  na.omit() %>%
  ft_tokenizer(input.col = "text", output.col = "tokens") %>%
  mutate(word = explode(tokens))

glimpse(tokenized3)
# Observations: 25
# Variables: 4
# $ text   <chr> "SENSE AND SENSIBILITY", "SENSE AND SENSIBILITY", "SENSE AND SEN...
# $ book   <chr> "Sense & Sensibility", "Sense & Sensibility", "Sense & Sensibili...
# $ tokens <list> [["sense", "and", "sensibility"], ["sense", "and", "sensibility...
# $ word   <chr> "sense", "and", "sensibility", "by", "jane", "austen", "(1811)",...
```

Although we ought to provide better verbs for doing things like this.

Also better documentation because how were you supposed to know about `explode()`? ;)

FYI @richierocks

**Comment by AngryR11** [comment]
Thank you @kevinushey, it worked on my database as well.

It would indeed be nice to hv a better documentation. And I might be asking too much, but if all the standard commands in R  worked with sparklyr objects, that would be great!

Anyway, I am closing the issue now, since this solves the problem.
