### ISSUE TITLE
FR: mutate() should accept functions

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3054]
and then use them in a `map()` call:

```r
mutate(data = function(type, data) { ... }))
```

should be equivalent to

```r
mutate(data = map2(
  type, data,
  function(type, data) {
    ...
  }
))
```

Currently, `mutate()` just throws an error if a function is passed.

**Comment by krlmlr** [comment]
Maybe even simpler: Make it equivalent to

```r
mutate(data =
  (function(type, data) { ... })(type, data)
)
```

and let `rowwise()` handle rowwise operations.

**Comment by hadley** [comment]
Hmmm, interesting idea.

**Comment by romainfrancois** [comment]
I like the idea of passing a function, or a lambda, with lists columns I often end up using `mutate` + `map*`. 

For non list columns, this would encourage r level loops (even hidden in a map), so 💣 performance. 

Also, there's the output type. Would we always want a list ?

**Comment by hadley** [comment]
Yeah, I think I'd like to leave for now. I don't want to end up in another `do()` situation.
