### ISSUE TITLE
group_by introducing extra column to data.frame

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3056]
Expected behavior: to either group by the `homeworld` column or signal that this is not an allowed form.  

Observed behavior: `group_by()` adds a new column to the `data.frame`.  

I know this is related to some earlier issue reports, but this `reprex` seems like it might be simple enough to be helpful.  Obviously this is a good place to use `group_by_at()`.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.2.9000'

starwars %>% 
  group_by(!!"homeworld") %>%
  colnames() %>% 
  setdiff(colnames(starwars))
#> [1] "\"homeworld\""
```

**Comment by DaweiCheng** [comment]
What`s the purpose of using !!"homeworld" ? 
group_by(homeworld) works fine.

**Comment by lionel-** [comment]
`group_by()` has mutate semantics so you're creating a new column by recycling when you supply a string.

**Comment by JohnMount** [comment]
Thanks, sorry about that.
