### ISSUE TITLE
dbplyr does not translate base R integer division %/%

### ISSUE THREAD

**Issue by emilyriederer** [tidyverse/dplyr#3057]
Base R integer division (%/%) is translated to normal division (/) in SQL. 

Apologies for non-reprex. I couldn't think of a way to get around the fact that a user must establish a connection to get this to run. When run connected to a AWS Redshift DB, data$z contains values 0, 1, and 2 while data_db$z contains floating point values.

The cause is that %/% is translated as / without accounting for integer-format. One correct SQL translation (at least for Redshift) would be CAST("x"/5 AS INTEGER) or FLOOR("x"/5)

``` r
library(dplyr)

data <- data.frame(x=as.integer(1:10))
data_db <- copy_to(con, data, "data_db", temporary = FALSE)

data <- mutate(data, z = x %/% 5)
data_db <- mutate(data_db, z = x %/% 5)

data
collect(data_db)

show_query(data_db)
```

**Comment by edgararuiz** [comment]
Hi @emilyriederer , does a regular using forward slash by itself works in you environment:

```
data <- mutate(data, z = x / 5)
```

**Comment by emilyriederer** [comment]
Hi @edgararuiz -- unfortunately not. 

It might work just as happenstance due to integer division, but the SQL translation also turns 5 into a floating point:

<SQL>
SELECT "x", "x" / 5.0 AS "z"
FROM "data_db"

**Comment by edgararuiz** [comment]
Ok, can we try appending an "L" to the right of 5?

```
data <- mutate(data, z = x / 5L)
```

**Comment by hadley** [comment]
Minimal reprex

``` r
dbplyr::translate_sql(x %/% 5)
#> <SQL> "x" / 5.0
```

**Comment by hadley** [comment]
To make equivalent to `1 %/% 0.2` will probably need to implement via modulo arithmetic.

```
x == (x %/% m) * m + (x %% m)  
x %/% m == (x - (x %% m)) / m
```

**Comment by hadley** [comment]
But this needs to be thought through correctly - I have a vague recollection that negative values might cause issues.

**Comment by hadley** [comment]
```R
sql_int_div <- function() {
  function(x, m) {
    build_sql("((", x, " - (", x, " % ", m, ")) / ", m, ")")
  }
}
```

That definition gets us pretty close, but it turns out that `%%` in R and `%` in SQL have slightly different semantics when the signs are different:

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

df <- tibble(
  x = c(10, 10, -10, -10), 
  y = c(3, -3, 3, -3)
)
df %>% mutate(x %% y, x %/% y)
#> # A tibble: 4 x 4
#>       x     y `x%%y` `x%/%y`
#>   <dbl> <dbl>  <dbl>   <dbl>
#> 1    10     3      1       3
#> 2    10    -3     -2      -4
#> 3   -10     3      2      -4
#> 4   -10    -3     -1       3

con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
mf <- con %>% copy_to(df)
mf %>% mutate(x %% y, x %/% y)
#> # Source:   lazy query [?? x 4]
#> # Database: sqlite 3.19.3 [:memory:]
#>       x     y `x%%y` `x%/%y`
#>   <dbl> <dbl>  <dbl>   <dbl>
#> 1    10     3      1       3
#> 2    10    -3      1      -3
#> 3   -10     3     -1      -3
#> 4   -10    -3     -1       3
```

I'm not sure how to handle this :(

**Comment by alex-gable** [comment]
This is a result of C98 and beyond (and by extension SQLite) using truncated division where the modulo operator takes the sign of the dividend, and R using the mathematically preferred floored division with the modulo sign taking the sign of the divisor.

Quite frankly, C(SQLite) and R are doing fundamentally different arithmetic. There's some fascinating reading on the subject [here](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/divmodnote-letter.pdf) and of course an abridged version on [Wikipedia](https://en.wikipedia.org/wiki/Modulo_operation). This will likely also vary across SQL dialects, which makes it more difficult to pin down in a unified way. 

Given the above, I'm not sure it is reasonable to expect equivalent output in every language. Python covered some of the complexities in this discussion in [PEP-228: Reworking Python's Numeric Model](https://www.python.org/dev/peps/pep-0228/) and [PEP-238: Changing the Division Operator](https://www.python.org/dev/peps/pep-0238/), highlighting that this is not just a "dplyr issue", but rather a significantly larger architectural decision in R and computer arithmetic itself.

**Comment by hadley** [comment]
@alex-gable thanks for that awesome summary of the problem!

**Comment by hadley** [comment]
I think the best way to handle this is simple to document it.

**Comment by emilyriederer** [comment]
Wow - thank you all for the very helpful, detailed responses. All of the context here is fascinating. I'm embarrassed to discover that I completely "went dark" on this thread. Somehow, I'm not getting notifications but luckily spotted this atop the new GitHub feed. Thanks again!
