### ISSUE TITLE
`arrange` loses row names

### ISSUE THREAD

**Issue by EmilRehnberg** [tidyverse/dplyr#3058]
When running the `arrange` function as below I would expect the row names to stay intact. 

```r
library(dplyr)
mtcars %>% head
mtcars %>% head %>% arrange(mpg)
```

**Comment by lionel-** [comment]
In general dplyr does not preserve row names. You'll have to transform them to a column with `tibble::rownames_to_column()`. This is the best way to work with row identifiers in the tidyverse.
