### ISSUE TITLE
Support copy_to with database source as well as destination

### ISSUE THREAD

**Issue by mungojam** [tidyverse/dplyr#3064]
Allow for:

```
sourceConn <- dbConnect(RSQLite::SQLite()) #Usually Oracle or SQL in reality

copy_to(sourceConn, iris, "iris")

destConn <- dbConnect(RSQLite::SQLite())

query <- tbl(sourceConn, "iris") %>% select(everything())

copy_to(destConn, query, "iris") #This line errors with 'Error: df is not a data frame'
```

Motivation: For large datasets, we sometimes pull data from a database into a local SQLite database. This is because, even with sub-setting, the data is too large to fit in RAM. We can then analyse the data using dplyr against SQLite. But we need a way to stream the data from the remote to the local database. Currently we resort to doing this in another language, but the above would allow us to do it really easily with dplyr.

**Comment by Hong-Revo** [comment]
I think the ideal solution is to turn `copy_to` into an S4 generic. This would allow dispatching on more than just the first argument, so you could write methods to copy tables in one DBMS to another DBMS; from a DBMS into Spark; etc.

This would be a major rewrite though.

**Comment by mungojam** [comment]
Thanks for giving it some thought. Figured it might be a big one to change. Hope you can do it, feels like a reasonably common scenario.

**Comment by Hong-Revo** [comment]
On reflection, dispatching on multiple arguments is probably what you _don't_ want to do, because it leads to quadratic complexity: you'd need a separate method for every distinct pair of srcs. This can rapidly become unmaintainable as dplyr is extended to support more backends.

**Comment by mungojam** [comment]
In C# it was pretty easy to do as Entity Framework has a standard interface that lets you iterate through rows in one database provider while adding to rows in another. I guess it's not so simple in R.

Presumably each backend must provide some common functionality for things like collect() to work, Could there be an additional required generic method to support iterating through rows. That could then be called by copy_to.

You can probably tell, I only have a vague idea of how these things work..

**Comment by hadley** [comment]
I think we could just add a switch in `copy_to.src_sql`, but this would still stream the data through R.

**Comment by mungojam** [comment]
Going through R is ok, and would be very usable as long as it is streaming and not pulling it all into RAM.

I guess it would be quicker in C++, but the time it takes isn't so important as it tends to only be done once, at the start of some extended analysis work, or for a one-off migration of data.

**Comment by hadley** [comment]
I'll probably pull it all into RAM for this pass, unless streaming it seems easy.

**Comment by hadley** [comment]
Reprex

```R
library(dplyr, warn.conflicts = FALSE)

src1 <- src_sqlite(":memory:", create = TRUE)
src2 <- src_sqlite(":memory:", create = TRUE)

# Create from dataframe
iris_1 <- copy_to(src1, iris, "iris1")

# Create from tbl in same database
iris_2 <- copy_to(src1, iris_1, "iris2")

# Create from tbl in another data
db2 <- copy_to(src2, iris, 'data2', temporary = FALSE)
iris_3 <- copy_to(src3, iris_1, "iris3")
```

**Comment by mungojam** [comment]
Thanks, totally understand going for this simple approach at this stage. I've raised #3163 for doing the more memory efficient method, though I know it would be much more complicated to implement.

**Comment by mungojam** [comment]
The cool use case I hadn't thought of from this improved copy_to you've done is using dplyr to implement a workflow like in SAS where datasets are all disk-based. We could now do that with SQLite tables very easily. That can be very useful when working with large datasets.
