### ISSUE TITLE
summarise_all() not working with any function

### ISSUE THREAD

**Issue by Fredo-XVII** [tidyverse/dplyr#3066]
***Brief description of the problem:***
I am trying to sum up all my columns with summarise_all(sum), but instead I get the following error:
    - Error in !funs : invalid argument type
It doesn't matter what function I use.  I have tried "mean" and "sd" but no functions are working.  
This was working just fine a few days ago, but I don't know what happened since then.  Everything on StackOverflow tells me to use dplyr::summarise_all(sum). 
Yes, I have re-installed packages.
I am running R.3.3.1

***reprex() example:***
I have to be honest, I believe the "pipe" is working just fine.  I don't know why it thinks that it is the %>% that is the issue.  I split up the code so that I code make sure that up to the group_by the code is working as expected.
```r
ITEM_RANK_SUM_0 <- ITEM_RANK_BASE[POST_PER == 0,] %>%
                   select(-GREG_D,-ACCT_WK_END_D,-ACCT_WK_DAY) %>%
                   dplyr::group_by(MDSE_ITEM_I,POST_PER)
#> Error in eval(expr, envir, enclos): could not find function "%>%"
                   
ITEM_RANK_SUM_0 <- ITEM_RANK_SUM_0 %>% dplyr::summarise_all(sum)
#> Error in eval(expr, envir, enclos): could not find function "%>%"
```

Sorry if I didn't get the reprex() right.  This is my first time using it.

Thank you,

Alfredo

**Comment by lionel-** [comment]
Have you attached dplyr?

```r
library("dplyr")
```

**Comment by Fredo-XVII** [comment]
Yup, multiple times.  I even reinstalled dplyr and tidyverse. I wish it would have been that simple :)

Thanks.

**Comment by lionel-** [comment]
What happens when you type this?

```r
library("dplyr")
letters %>% identity()
```

If this works, could you try to build that expression up until it doesn't please? (By the way the example you posted is not a reprex because it's not reproducible, I can't run that code on my computer.)

**Comment by Fredo-XVII** [comment]
Yes, the code above works...prints the alphabet to console.

What your asking is what I showed above.  The object ITEM_RANK_SUM_0 gets built just fine.  When I try to run the second line in order to aggregate all the columns, that is when I get the error (Error in !funs : invalid argument type) that I listed above.

Sorry, I can't paste output because it is sensitive my company.

I resolve the issue using data.table commands to sum up all the columns because I need to get stuff done.  I couldn't find a solution online for this so I thought it was a new unique issue for dplyr.

**Comment by lionel-** [comment]
What does this print:

```r
class(ITEM_RANK_SUM_0)
```

**Comment by Fredo-XVII** [comment]
Hi Lionel,

I got busy at work and I couldn't get back to you sooner.

The out for the code above is below:
    > class(ITEM_RANK_SUM_0)
    [1] "grouped_dt" "tbl_dt"     "tbl"        "tbl_dt"     "tbl"        "data.table" "data.frame"

**Comment by krlmlr** [comment]
This looks like an issue with the dtplyr package. Can you try converting to a data frame?

**Comment by Fredo-XVII** [comment]
@krlmr Just ran into this issue again.  Your suggestion to convert to a data frame worked! Thank you so much!!!
