### ISSUE TITLE
dplyr::tally does not work for data.frame with no columns

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3071]
In attempting to find a good work-around for [`dplyr` issue 3069](https://github.com/tidyverse/dplyr/issues/3069) I ran into this.  If we form a `data.frame` that happens to have no columns (by dropping a column), then `dplyr::tally` does not return a count.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.2.9000'

data.frame(n = as.raw(1:3)) %>% 
  select(-n) %>% tally
#> data frame with 0 columns and 3 rows
```

**Comment by krlmlr** [comment]
Thanks, confirmed. Same behavior with `summarise()`.
