### ISSUE TITLE
tally() returns incorrect result on database table with n variable

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3075]
`dbplyr` issue: `dplyr::tally()` results on database different than on `data.frame`.  This is a very low priority for me as I do not use `tally()`.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.2.9000'
library("sparklyr")
packageVersion("sparklyr")
#> [1] '0.6.2'
packageVersion("dbplyr")
#> [1] '1.1.0.9000'
packageVersion("DBI")
#> [1] '0.7'

db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

dLocal <- data.frame(n = 1:3)
print(dLocal)
#>   n
#> 1 1
#> 2 2
#> 3 3

dRemote <- dplyr::copy_to(db, dLocal)
print(dRemote)
#> # Source:   table<dLocal> [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>       n
#>   <int>
#> 1     1
#> 2     2
#> 3     3


tally(dLocal)
#> Using `n` as weighting variable
#>   nn
#> 1  6

tally(dRemote)
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>      nn
#>   <int>
#> 1     3

DBI::dbDisconnect(db)
```

**Comment by hadley** [comment]
Minimal reprex

``` r
library(dplyr, warn.conflicts = FALSE)

db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

dLocal <- data.frame(n = 1:3)
tally(dLocal)
#> Using `n` as weighting variable
#>   nn
#> 1  6

dRemote <- dplyr::copy_to(db, dLocal)
tally(dRemote)
#> # Source: lazy query [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>      nn
#>   <int>
#> 1     3
```

Note the absence of "Using `n` as weighting variable`

**Comment by hadley** [comment]
(probably due to use of `names()` instead of `tbl_vars()` on line 64)

**Comment by krlmlr** [comment]
There's another inconsistency between `tally()` and `count()`, which is been present in v0.5.0 already (tested with #3412):

``` r
library(tidyverse)
tibble(a = 1:3, n = 4:6) %>% group_by(a) %>% tally()
#> Using `n` as weighting variable
#> # A tibble: 3 x 2
#>       a    nn
#>   <int> <int>
#> 1     1     4
#> 2     2     5
#> 3     3     6
tibble(a = 1:3, n = 4:6) %>% count(a)
#> # A tibble: 3 x 2
#>       a    nn
#>   <int> <int>
#> 1     1     1
#> 2     2     1
#> 3     3     1
```

> Created on 2018-03-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I propose to stop guessing the weighting variable in `tally()` altogether, partly because it doesn't work as expected if there's an `nn` variable but not an `n` variable. First we change the message, then we warn if there's an `n` variable in the data but no `wt` argument is used, then we stop caring about it.

**Comment by hadley** [comment]
Eliminating guessing is not acceptable to me because it's important that `tally(tally(x))` continue to work and return the correct answer (i.e. the total count)

**Comment by krlmlr** [comment]
We agreed to not support guessing in `tally(tally(tally(x)))`, and `tally(count(x))` currently is different from `tally(tally(x))` with respect to guessing. How can we make this a bit more consistent?
