### ISSUE TITLE
Database source seems unable to represent a numeric column that is all NA

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3081]
Database source seems unable to represent a numeric column that is all NA.  I ran into a related issue with [`sparklyr` issue 985](https://github.com/rstudio/sparklyr/issues/985), so I don't know if the issue is just `SQLite` (maybe it doesn't store enough shema data), or also with other `dbplyr` sources.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.2.9000'
packageVersion("dbplyr")
#> [1] '1.1.0.9000'

db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

dRemote <- dplyr::copy_to(db, 
                          data.frame(x = 1:2), 
                          'dRemote')

dRemote <- dRemote %>%
  mutate(z=0.0) %>%
  mutate(z = z*as.numeric(NA_real_))
print(dRemote)
#> # Source:   lazy query [?? x 2]
#> # Database: sqlite 3.19.3 [:memory:]
#>       x     z
#>   <int> <lgl>
#> 1     1    NA
#> 2     2    NA
# notice z column type is logical, not numeric
```

**Comment by hadley** [comment]
That's because in SQLite columns don't have types, cells have types. RSQLite has to guess the type of column, and it can't always guess correctly.
