### ISSUE TITLE
print() not using sql_optimise() causing some queries to fail

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/dplyr#3084]
It looks like when a `print()` function is called, the query is not being optimize causing some MSSQL queries to fail.  It occurs in these instances:

```
tbl(con, "airlines")  %>%
  arrange(name) %>%
  head() 
```
```{r}
t <- tbl(con, "airlines")  %>%
  arrange(name) %>%
  head()

print(t)
```
But it works if I use `collect()` prior to printing, I theorize because the query is running through the optimizer, these work:

```
tbl(con, "airlines")  %>%
  arrange(name) %>%
  head() %>%
  collect
```
```
t <- tbl(con, "airlines")  %>%
  arrange(name) %>%
  head() %>%
  collect

print(t)
```
And these are the differences between the two SQL render functions:
```
> t <- tbl(con, "airlines")  %>%
+   arrange(name) %>%
+   head() 
> 
> show_query(t)
<SQL>
SELECT  TOP 6 *
FROM "airlines"
ORDER BY "name"
> sql_render(t)
<SQL> SELECT  TOP 6 *
FROM (SELECT *
FROM "airlines"
ORDER BY "name") "uefzzwxbpt"
```
I think this is being cause the `fecth()` function in `query.r` but I'm not 100% sure.

@hadley  - If you'd like to take a look, I've added a new RNotebook to the `mssql-translation` project in the sol-eng server, which contains a working reprex.

**Comment by hadley** [comment]
I think the problem is actually a sequence of two heads in a row:

```R
tbl(con, "airlines")  %>%
  arrange(name) %>%
  head() %>%
  head() %>% 
  show_query()
#> SELECT  TOP 6 *
#> FROM (SELECT  TOP 6 *
#> FROM (SELECT *
#> FROM "airlines"
#> ORDER BY "name") "qstjsbjfny") "zyupzfuixm"
```

which you get because `print` automatically calls head to ensure that the database doesn't try and retrieve too much data.

**Comment by hadley** [comment]
It might be possible to consider this as a general sql optimisation problem - i.e. can we simplify this:

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

memdb_frame(x = 1) %>%
  head(5) %>%
  head(5) %>% 
  show_query()
#> <SQL>
#> SELECT *
#> FROM (SELECT *
#> FROM `zjgugmseeo`
#> LIMIT 5)
#> LIMIT 5
```
