### ISSUE TITLE
bind_cols Error message has odd output and maybe wrong values

### ISSUE THREAD

**Issue by darrkj** [tidyverse/dplyr#3085]
I was trying to take all the columns of data in a tibble, split a text column on a certain string and then attach that column, now having 1 or more items, back onto the original data. To make it even simpler I did it with just one row of data. I can resolve the issue by using crossing from tidyr, or even cbind from base R. The issue here thought is related to the error message given. It seems to say it needs what it actually has, and even then when you meet that need it fails, the crazy case says this, Argument 2 must be length 1, not 1.

```r
library(tidyverse)
data <- tibble(a = 1, b = 2)
new_c <- 1:3


bind_cols(data, tibble(new_c = new_c))
# Error in cbind_all(x) : Argument 2 must be length 3, not 1
bind_cols(data, new_c = new_c)
# Error in cbind_all(x) : Argument 2 must be length 1, not 1

# This is probably the way to do this.
crossing(data, new_c)
```

**Comment by darrkj** [comment]
That issue also seems to originate with the behind the scenes function as can be seen here.

```r
x <- dplyr:::flatten_bindable(list(data, newc = new_c))
dplyr:::cbind_all(x)
```

Which is not easy to track further because this calls out to C code.

```r
dplyr:::cbind_all
```

```
function (dots) 
{
    .Call(dplyr_cbind_all, dots)
}
<environment: namespace:dplyr>
```

**Comment by cderv** [comment]
From the documentation `help("bind_cols", package = "dplyr")`, it shows an example which throws an error.

> \# Rows do need to match when column-binding
> `bind_cols(data.frame(x = 1), data.frame(y = 1:2))` 


It is why you have this error message. It seems to be by design for `bind_cols`. You can use list column for a case like yours:

``` r
library(dplyr, warn.conflicts = F)data <- tibble(a = 1, b = 2)
new_c <- 1:3

bind_cols(data, tibble(new_c = list(new_c)))
#> # A tibble: 1 x 3
#>       a     b     new_c
#>   <dbl> <dbl>    <list>
#> 1     1     2 <int [3]>
```

In this case, you bind two _one-row_ tibbles so it is compatible with `bind_cols`. You can manipulate your nested tibble like this after or unnest it with `tidyr::unnest`

``` r
bind_cols(data, tibble(new_c = list(new_c))) %>% tidyr::unnest()
#> # A tibble: 3 x 3
#>       a     b new_c
#>   <dbl> <dbl> <int>
#> 1     1     2     1
#> 2     1     2     2
#> 3     1     2     3
```

You see you get something similar to `crossing`.

This may help your more sophisticated use case, and in the end I am note sure what you describe is a bug.

**Comment by kennethdarrell** [comment]
The bug is with the error message, Argument 2 must be length 1, not 1.

**Comment by krlmlr** [comment]
Thanks, confirmed. The error message is just wrong. There's also `tibble::add_column()`, but it won't add more rows either. If you need a cross product, `crossing()` looks like the right way to do it indeed.
