### ISSUE TITLE
distinct() does not work if a column of the tbl is a list column

### ISSUE THREAD

**Issue by dkincaid** [tidyverse/dplyr#3088]
If a data frame contains a list column then distinct is not working. It simply returns all rows.

```r
library(tibble)
library(dplyr)
testTbl <- tibble(a=c("1", "1", "2", "2", "3","3"), b=c(list("A"), list("A"), list("B"), list("B"), list("C"), list("C")))
testTblDistinct <- testTbl %>% distinct()
```

**Comment by krlmlr** [comment]
Thanks, confirmed. This is related to #2355, but we should emit an error or at least a warning here for the time being.
