### ISSUE TITLE
na_matches argument not mentioned in documentation

### ISSUE THREAD

**Issue by sfirke** [tidyverse/dplyr#3097]
The `na_matches` argument isn't mentioned in the `?dplyr::join` documentation.  Mentioned on this StackOverflow post: https://stackoverflow.com/a/46161655/4470365

**Comment by cderv** [comment]
It is said in the help for `dplyr::join` : 
> ... other parameters passed onto methods

You can find `na_matches` information in `?dplyr::join.tbl_df` documentation as this argument is only valid for data.frame as said in the NEWS.

**Comment by sfirke** [comment]
Good to know.  I think very few users will find their way to `?dplyr::join.tbl_df` from the starting point of `?inner_join` and thus won't become aware of this argument.

If it won't be documented in `?join`, where it would be immediately discoverable, then maybe the "passed onto methods" text could be followed by "see `?dplyr::join.tbl_df` for additional options" to bridge the gap.  I still think most users won't make the connection, but at least it makes it possible. 

Right now, it seems that aside from having read the NEWS release, it's very unlikely users will ascertain this functionality.

**Comment by cderv** [comment]
Yep, a link to the method documentation could be helpful but not sure it is the practice with S3 methods. Right now, the generic documentation says explicitly to look for method documentation. one today but possibly several later. 

Know that for help on the tidyverse package, the website is very helpful: 
+ [About the tidyverse](http://www.tidyverse.org/)
+ [dplyr documentation reference page](http://dplyr.tidyverse.org/reference/index.html) where you can easily find about `join` documentation for data.frame [there](http://dplyr.tidyverse.org/reference/join.tbl_df.html)

I'll wait the tidyverse team advices on this before proposing any change.
