### ISSUE TITLE
dot within group

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#3103]
This works as intended:

```
BOD %>% rowwise() %>% mutate(sum = sum(Time, demand)) # ok -- 1 + 8.3 = 9.3
##    Time demand   sum
## 1     1    8.3   9.3
## ...

```

but this does not -- here it seems that dot (.) still refers to the entire data frame and not just the current row.  The result is that all elements of the data frame are summed, not just the elements on the current row..

```
BOD %>% rowwise() %>% mutate(sum = sum(.)) # bad -- got sum(BOD) = 111 but wanted 1+8.3=9.3
##    Time demand   sum
## 1     1    8.3   111
## ...

```

It would be desirable to have some way of referring to the current row or current group if within `group_by`.

**Comment by cderv** [comment]
I am not sure how to refer to the current row or group in `group_by` but, in the meantime you can easily get what you want using `purrr` package. Its `pmap` function, when use on a data.frame, applies a function to each column by row.
``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
DF <- tribble(
  ~ a, ~b,
  1, 10,
  2, 11
)

DF %>%
  mutate(sum = purrr::pmap_dbl(., sum))
#> # A tibble: 2 x 3
#>       a     b   sum
#>   <dbl> <dbl> <dbl>
#> 1     1    10    11
#> 2     2    11    13
```
You can use `dplyr::do` too with `rowwise` but I find purrr solution more elegant.

**Comment by ggrothendieck** [comment]
Thanks but the point of this is really how to refer to the current group in rowwise/group_by.

**Comment by hadley** [comment]
I no longer believe that`rowwise()` is a good idea, so it will not be gaining any new features.
