### ISSUE TITLE
date field stored in SQLite database table as double.

### ISSUE THREAD

**Issue by eduardgrebe** [tidyverse/dplyr#3105]
---

When a date field from a tibble is copied to an SQLite database using dplyr's copy_to() and RSQLite, it appears to be converted to a double.

``` r
test.db <- dplyr::src_sqlite("test.sqlite3", create = T)
test.df <- dplyr::data_frame(date_field = lubridate::ymd(c("2017-09-12","2017-09-13","2017-09-14")))
dplyr::glimpse(test.df)
#> Observations: 3
#> Variables: 1
#> $ date_field <date> 2017-09-12, 2017-09-13, 2017-09-14
test.dbtbl <- dplyr::copy_to(test.db, test.df, temporary = FALSE, name = "test", overwrite = TRUE)
dplyr::glimpse(test.dbtbl)
#> Observations: 3
#> Variables: 1
#> $ date_field <dbl> 17421, 17422, 17423
test.tbl <- dplyr::tbl(test.db, "test")
dplyr::glimpse(test.tbl)
#> Observations: 3
#> Variables: 1
#> $ date_field <dbl> 17421, 17422, 17423
```

**Comment by drf5n** [comment]
lubridate dates are doubles with a class of 'Date', so it isn't so much a conversion as a loss of class information:

    > dput(lubridate::ymd(c("2017-09-12","2017-09-13","2017-09-14")))
    structure(c(17421, 17422, 17423), class = "Date")

Since SQLite doesn't have a field type for date, http://www.sqlite.org/datatype3.html#datetime , the loss of fidelity means you'd have to  manage that externally, or use a string type.

**Comment by hadley** [comment]
As @drf5n mentions, date/time behaviour in SQLite is a little different to what you might expect. But I think we can do a bit better with the default translation: https://github.com/rstats-db/RSQLite/issues/237
