### ISSUE TITLE
Compile error in 0.7.3

### ISSUE THREAD

**Issue by Jafet** [tidyverse/dplyr#3106]
The 0.7.3 CRAN package fails to compile. The error is the same as reported in #3078:

```
> install.packages("dplyr")
[...]
join_exports.cpp: In function ‘Rcpp::DataFrame semi_join_impl(Rcpp::DataFrame, Rcpp::DataFrame, Rcpp::CharacterVector, Rcpp::CharacterVector, bool)’:
join_exports.cpp:174:21: error: ‘Rcpp::DataFrame {aka class Rcpp::DataFrame_Impl<Rcpp::PreserveStorage>}’ has no member named ‘nrow’; did you mean ‘nrows’?
   indices.reserve(x.nrow());
                     ^~~~
                     nrows
/usr/lib/R/etc/Makeconf:141: recipe for target 'join_exports.o' failed
```

This is just a typo, isn't it? Changing to `x.nrows()` makes the install succeed. Line: [join_exports.cpp:174](https://github.com/tidyverse/dplyr/blob/master/src/join_exports.cpp#L174)

This happened when installing dplyr over Debian's R packages. Environment:
```
% lsb_release -d
Description:	Debian GNU/Linux testing (buster)

% R --version
R version 3.3.3 (2017-03-06) -- "Another Canoe"
...

% g++ --version
g++ (Debian 7.2.0-4) 7.2.0
...
```

**Comment by krlmlr** [comment]
Thanks. What Rcpp version do you have? This should disappear when you upgrade, but we might just change it too.

**Comment by Jafet** [comment]
It is Debian's r-cran-rcpp 0.12.9-1. I see that `DataFrame::nrow` wasn't available until 0.12.10.

**Comment by krlmlr** [comment]
:man_facepalming: :man_facepalming:

I'll try to push a fix soon.

**Comment by Jafet** [comment]
✓

**Comment by chanwy3** [comment]
I am having the same error, seems like it haven't been fixed yet?

**Comment by krlmlr** [comment]
The GitHub version should work, the CRAN submission is underway.

**Comment by podalv** [comment]
GitHub version has still the same problem. Does nobody test stuff before release?

**Comment by lionel-** [comment]
```r
install_github("tidyverse/dplyr#3098")
```

**Comment by chanwy3** [comment]
@podalv , I download it from GitHub and fixed the problem manually, and then install it locally.

**Comment by podalv** [comment]
Yeah, had to do the same, I was just being a bit frustrated that 3 days ago this issue was marked as fixed in GitHub. Oh well :)

**Comment by krlmlr** [comment]
@lionel-: Thanks, there seems to be a downside to not merging release candidates.

**Comment by chanwy3** [comment]
@krlmlr : No worries, as long as everything works.  Thanks for your effort fixing the problem!
