### ISSUE TITLE
data_grid .model parameter

### ISSUE THREAD

**Issue by kravhowe** [tidyverse/dplyr#3111]
Error in overscope_eval_next(overscope, expr) : object 'G' not found
---

Brief description of the problem
"A model. If supplied, any predictors needed for the model not present in ... will be filled in with "typical" values."  This seems to work for the given example in the documentation. However, there seems to be a problem with the given example below. 
There was no problem with previous versions. 
```r
# insert reprex here
library(tidyverse)
library(hexbin)
library(modelr)
smaller <- diamonds %>% filter(carat < 3)
mod_diamond2 <- lm(price ~ carat + color + cut + clarity, data = smaller)
grid <- smaller %>%  data_grid(cut, .model = mod_diamond2) %>% 
  add_predictions(mod_diamond2)

**Comment by hadley** [comment]
I think you've filed this in the wrong place - this looks like a model bug.
