### ISSUE TITLE
Issues with SQL Server JDBC driver

### ISSUE THREAD

**Issue by cmhh** [tidyverse/dplyr#3112]
There are some issues with the Linux ODBC driver for SQL Server (I can't seem to stop it truncating very long character fields--a big issue for SQL Server spatial tables), so I use the JDBC driver occasionally.  But I'm getting some odd results with `dbplyr`...

First, the preview doesn't work because of SQL Server's `SELECT * LIMIT 10` versus `SELECT TOP 10 *` issue:

```r
> p <- system.file("java/sqljdbc42.jar", package = "RJDBC")
> drv <- RJDBC::JDBC("com.microsoft.sqlserver.jdbc.SQLServerDriver" , p)
> con <- DBI::dbConnect(drv,
+                       "jdbc:sqlserver://SNZ-CORP1-PRD-SQL.stats.govt.nz:1433;
+                        databaseName=Census2013_Output;
+                        integratedSecurity=true;
+                        authenticationScheme=JavaKerberos")
> tbl(con, "individual")
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT *
FROM "individual"
LIMIT 10 (Incorrect syntax near '10'.)
```

(This works correctly when using the odbc driver with `odbc::odbc()`).

In addition, getting a row count with `summarise(n = n())` doesn't work right:

```r
> tbl(con, "individual") %>%
+   group_by(wklfs_code) %>%
+   summarise(n = n()) %>% 
+   collect()
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT "wklfs_code", COUNT() AS "n"
FROM "individual"
GROUP BY "wklfs_code" (The COUNT function requires 1 argument(s).)
```

(This works fine with the odbc driver--there the query comes back with `COUNT(*)` rather than `COUNT()`).  

None of this is a massive issue--I can use `n = sum(1)` instead of `n = n()` to get row counts, and I don't necessarily need the 10-row previews.  But in case there's something obvious...

Thanks

**Comment by edgararuiz** [comment]
Hi @cmhh ,  `dbplyr` uses the connection class to choose the SQL syntax that it will use for syntax translations.  The most likely reason `RJDBC` is not working for you is because its class is not recognized as a MS SQL connection.  An easy workaround is to add these lines of code at the top of your script:

```
  sql_translate_env.JDBCConnection <- dbplyr:::`sql_translate_env.Microsoft SQL Server`
  sql_select.JDBCConnection <- dbplyr:::`sql_select.Microsoft SQL Server`
  sql_subquery.JDBCConnection <- dbplyr:::`sql_subquery.Microsoft SQL Server`
```
The `JDBCConnection` value is what I'm assuming your JDBC connection returns as its `class()`.  Please verify that by using: `class(con)`.

Also, I'm curious about the driver that you are using in your Linux environment, is that the MS provided driver? https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server

**Comment by cmhh** [comment]
Thanks.  I'll give that a go shortly...

Yes, the ODBC driver we use is [the official MS driver](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#microsoft-odbc-driver-11-for-sql-server-on-linux), and that works fine in most situations.  However, I can't seem to get it to stop truncating large text fields and, in particular, large MULTIPOLYGON fields using SQL Server spatial.  In that case, I use the JDBC driver and cast the geometries to WKT using STAsText.  Interestingly, the freeTDS driver seems to work better in this respect, but we use trusted authentication almost exclusively and I couldn't get that going on Linux.

**Comment by cmhh** [comment]
Yes, the class of `con` is `JDBCConnection`.  Your workaround _mostly_ works.  I got the following for the third line:

```r
> sql_subquery.JDBCConnection <- dbplyr:::`sql_subquery.Microsoft SQL Server`
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'sql_subquery.Microsoft SQL Server' not found
```

But the original example above, `tbl(con, "individual")`, works just fine now.  

Thanks.

**Comment by edgararuiz** [comment]
Hi @cmhh, my bad, the MS SQL translation does not have a custom `sql_subquery` hence the error.  But it does have a custom `db_analyze`, which may be needed if you create new tables: https://github.com/tidyverse/dbplyr/blob/master/R/db-odbc-mssql.R
