### ISSUE TITLE
Update Programming with dpyr article to reference group_by_at ?

### ISSUE THREAD

**Issue by rgknight** [tidyverse/dplyr#3114]
The [programming with dyplr](http://dplyr.tidyverse.org/articles/programming.html#capturing-multiple-variables) article has a section on capturing multiple variables that uses `group_by` as the example. 

However, it appears that `group_by_at` may be the preferred "recipe", or at least an acceptable solution worth mentioning, for capturing multiple variables using `group_by` (and the `_at`  scoped variants more generally)?

I think it would be helpful to mention the `_at` variant in the reference, as training users to look to `_at` and `vars` seems to be the way of the future?

For example, using the provided `my_summarise` example, I don't know how to use `invoke_map` with it
```
df <- tibble(
  g1 = c(1, 1, 2, 2, 2),
  g2 = c(1, 2, 1, 2, 1),
  a = sample(5), 
  b = sample(5)
)

my_summarise <- function(df, ...) {
  group_by <- quos(...)

  df %>%
    group_by(!!!group_by) %>%
    summarise(a = mean(a))
}

my_summarise(df, g1, g2)
invoke(my_summarise, df=df, vars(g1, g2) )  # took a lot of guessing before I got this

my_mutate <- function(df, ...){
  group_by <- quos(...)
  df %>%
    group_by(!!!group_by) %>%
    mutate(a_mean = mean(a))
}

my_mutate(df, g1, g2)
invoke(my_mutate, df=df, vars(g1, g2))

invoke_map(list(my_summarise, my_mutate), df=df, vars(g1, g2)) # Fails
```
In contrast, using the `_at` scoped variant behaves as expected, and is simple: 
```
my_summarise <- function(df, by) {
  df %>%
    group_by_at(.vars = by) %>%
    summarise(a = mean(a))
}

my_summarise(df, by = vars(g1, g2))
invoke(my_summarise, df=df, by = vars(g1, g2) ) 

my_mutate <- function(df, by){
  df %>%
    group_by_at(.vars = by) %>%
    mutate(a_mean = mean(a))
}

my_mutate(df, vars(g1, g2))
invoke(my_mutate, df=df, by = vars(g1, g2))

invoke_map(list(my_summarise, my_mutate), df=df, by = vars(g1, g2))
```
I am happy to take a stab at adding a reference to the `_at` variants if that sounds worthwhile.

**Comment by hadley** [comment]
The `_at` functions are somewhat orthogonal to tidy eval, and I'd rather keep them separate. We'll be working on the tidy eval docs soon.
