### ISSUE TITLE
Function group_vars not found in dplyr

### ISSUE THREAD

**Issue by MargaretJones** [tidyverse/dplyr#3115]
I expect this code to reproduce the example given at the bottom of this page: http://dplyr.tidyverse.org/reference/group_by.html (The output should be a vector containing "vs" and "am").

However, I am receiving an error message. 

I have dplyr version '0.5.0' and should have all the depends installed as well. I'm fairly new to R, and I'm not sure why this has started failing for me.  
EDIT: I know this is probably some kind of operator error with me know having the right version of a package somewhere, so please let me know if I should look elsewhere for help. Thank you!

```r
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats

by_cyl <- mtcars %>% group_by(cyl)
by_cyl %>%
   group_by(vs, am) %>%
   dplyr::group_vars()
#> Error: 'group_vars' is not an exported object from 'namespace:dplyr'
```

**Comment by lionel-** [comment]
You need to install a more recent version of dplyr.

**Comment by MargaretJones** [comment]
Oh how embarrassing... I could have sworn I'd tried that. Totally works with v0.7.0+ of course. Thank you so much!
