### ISSUE TITLE
dbplyr db_write_table(...,append=True) doesn't work as non-deprecated alternative to db_insert_into()

### ISSUE THREAD

**Issue by drf5n** [tidyverse/dplyr#3120]
Per https://stackoverflow.com/a/26784801/1653571 

The docs say db_insert_into() is deprecated in favor of db_write_table(): https://github.com/tidyverse/dplyr/blob/f9096e9c4d47b8da047aa88f05a064c2d521e281/docs/reference/backend_dbplyr.html#L213 

However, using db_write_table() seems to require an append=True, which does not work as expected.

This works as expected:

```r
require(dplyr)

my_db <- src_sqlite( "my_db.sqlite3", create = TRUE)                 # create src
copy_to( my_db, iris, "my_table", temporary = FALSE)                 # create table
newdf = iris                                                         # create new data
db_insert_into( con = my_db$con, table = "my_table", values = newdf) # insert into
```
 But these variants fail:

```r
require(dplyr)

my_db <- src_sqlite( "my_db.sqlite3", create = TRUE)                 # create src
copy_to( my_db, iris, "my_table", temporary = FALSE)                 # create table
newdf = iris                                                         # create new data

db_write_table( con = my_db$con, table = "my_table", values = newdf) # insert into
# Error: Table `my_table` exists in database, and both overwrite and append are FALSE
db_write_table( con = my_db$con, table = "my_table", values = newdf,append=True) # insert into
# Error: Table `my_table` exists in database, and both overwrite and append are FALSE

```

The code near https://github.com/tidyverse/dbplyr/blob/master/R/dbi-s3.r#L41 should pass the `...` argument along to dbWriteTable() if db_write_table() is the alternative to the deprecation.

**Comment by JohnMount** [comment]
Here is a variation that appears to work around some of the issues (though it probably cycles the new values through memory).  My guess is `dplyr:: db_write_table()` is indeed incomplete, but it is hard to be sure when so much of the interface is controlled through "`...`" arguments.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.4'

# create src
my_db <- DBI::dbConnect(RSQLite::SQLite(), 
                        ":memory:")
copy_to( my_db, iris, "my_table", temporary = FALSE)                 # create table
newdf = iris                                                         # create new data
# works, but is likely bringing newdf into local memory
# even when newdf is in a database
DBI::dbWriteTable(conn = my_db, name = "my_table", value = newdf,    # insert into
                  append= TRUE)                      
# count rows to confirm
my_table = tbl(my_db, "my_table")
tally(iris)
#>     n
#> 1 150
tally(my_table)
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>       n
#>   <int>
#> 1   300
```

**Comment by drf5n** [comment]
In `dplyr::db_write_table()`, none of the `DBI::dbWriteTable()` is controlled by `...` arguments because the `...` argument is ignored and not passed. 

 See https://github.com/tidyverse/dbplyr/blob/master/R/dbi-s3.r#L41

**Comment by hadley** [comment]
I think the solution is to undeprecate `db_insert_into()`. I wasn't thinking of this use case when I deprecated it.

**Comment by hadley** [comment]
Actually, I don't think you should be using these functions at all. Despite that SO post, these are not user facing functions. You should be calling the DBI functions directly.
