### ISSUE TITLE
how to trans tibble into a dataframe?

### ISSUE THREAD

**Issue by amjiuzi** [tidyverse/dplyr#3122]
after: dplyr:: dt %>% group_by (col) %>% do(tmp2=func1())
i got a result like this:
`> tmp2
Source: local data frame [354 x 3]
Groups: <by row>`

`# A tibble: 354 x 3
   loc_clus4 KC_score                tmp2
 *    <fctr>    <int>              <list>
 1         1        5   <tibble [9 x 20]>
 2         1        6  <tibble [37 x 20]>
 3         1        7 <tibble [109 x 20]>
 4         1        8  <tibble [66 x 20]>
 5         1        9  <tibble [16 x 20]>
 6         1       10   <tibble [4 x 20]>
 7         1       11   <tibble [2 x 20]>
 8         1       12   <tibble [1 x 20]>
 9         2        5   <tibble [1 x 20]>
10         2        6  <tibble [21 x 20]>`
`# ... with 344 more rows`

but i need a dataframe to do the next, so any help about it ??

**Comment by romainfrancois** [comment]
You are likely looking for `tidyr::unnest()`
