### ISSUE TITLE
dbplyr - Add the `append` argument to `compute()`

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/dplyr#3124]
Today, `dbWriteQuery()` accepts only local R data frames, so to to take advantage of the `append` argument, the user will have to `collect()` the results of a query before saving it back to an existing table.  The preferred approach is to use the query as the source of the data that will be appended, and thus no data is collected into R.  The `compute()` command already does this but only for new tables.  The suggestion is to add the `append` argument, that will in essence just name the existing table, without sending the `CREATE TABLE` suffix.  

Please see this twitter thread:  https://twitter.com/theotheredgar/status/912027928359251973, and this StackOverflow question: https://stackoverflow.com/questions/38592195/how-can-i-append-data-to-a-postgresql-table-with-dplyr-without-collect/39222001#39222001

**Comment by edgararuiz** [comment]
Another option is to re-write `db_insert_into`  to use a custom routine instead of just being a wrapper for `dbWriteTable()`

**Comment by hadley** [comment]
I'd prefer not to overload `compute()` in this way, so I think we should have a new function instead.

What's the SQL for inserting the result of a query into an existing table? Currently I'm using `CREATE TABLE AS`, but that obviously won't work for inserting. How should the column names be matched?

**Comment by edgararuiz** [comment]
To append I believe `INSERT INTO ... SELECT ...`  is what we would need to use, here's a w3 article about it, and also has the way we can do the column matching: https://www.w3schools.com/sql/sql_insert_into_select.asp .

**Comment by hadley** [comment]
OTOH it's not clear where to draw the line here - dplyr is about working with data in databases, not modifying data in databases (which in an analysis environment is generally considered sacrosanct).

If I do implement this, it's most likely to be with `append_to()` that parallels `copy_to()`. In conjunction with #3064, this would effectively remove the need for `compute()` (which I don't particularly like since I can never remember the name)

**Comment by edgararuiz** [comment]
Ha! How about `cache()`? :)  

IMHO - I would say that the line for `dplyr` should be temp tables.  The purpose will be for users to be able to "cache" complex queries into temp tables in order to ease IOs on the database side, and for the analyses to run faster. Any permanent table should be done using `DBI`.

**Comment by hadley** [comment]
I just realised that `append_to()` would be the **only** dplyr function that would modify something in place, so I think it's off the table.

**Comment by OssiLehtinen** [comment]
Hi, first of all big thanks for the powerful tool you are developing!

I have just recently discovered dbplyr, and it looks like quite a promising tool for many data science related tasks we currently do with graphical tools such as IBM SPSS Modeler etc. Implementing db-side workloads, for example, for our Shiny Pro -dashboards seems quite streamlined with dbplyr.

To the (closed) topic of this thread: appending results of sometimes quite long running computations in the database directly to another table is something we do regularly here. We might, for example do some timestamped classifications of the +200k products times +1000 outlets to be later used in further analysis without having to recompute everytime etc.

dbplyr almost gets us there, but not quite, without the possibility to directly append to an existing table (which might be sacrosanct for some, but definitely not for us :) ).

So what would be sweet, would be to be able to do something like this:

`source_table %>% ... operations after operations ... %>% append_to(table_name)`

and have the whole computation pushed back to the database with the 'insert into' and all. Having to lug the data from db to R and back is pretty much a show stopper for us in many cases.

One can of course first use compute() to write the result to some temp table and then use a custom dbSendStatement to insert from the temp table to where ever, but that is unnecessarily awkward and also requires writing the data twice. (Such stuff can be quite off putting for 'less technically oriented users', whom I'm pretty sure I could lure into the wonderland of R with the help of dbplyr :D )

So my main point is, I can definitely tell you there would be use cases for this kind of feature in dbplyr! I'm sure there would be good ways to implement this without breaking the rest of the machinery.

In any case, thanks again for your work on the nice package!

**Comment by krlmlr** [comment]
I wonder if `append_to()` and a related `upsert_to()` could be provided by a separate package. Implementation sketch:

```r
append_to <- function(x, target_table) {
  query <- paste(
    "INSERT INTO ", dbQuoteIdentifier(..., target_table), "\n",
   "(", paste(dbQuoteIdentifier(..., tbl_vars(x)), collapse = ", "), ")\n",
    sql_render(x)
  )
}
```

This would have to be a generic that dispatches on the table source, to be able to accommodate different SQL flavors.
