### ISSUE TITLE
as_data_frame doesn't work

### ISSUE THREAD

**Issue by srlivingstone** [tidyverse/dplyr#3125]
The function `as_data_frame` fails to return a data.frame object.  It's counterpart `as.data.frame` works as intended.

``` r
tibble::as_data_frame(tibble::tibble())
#> # A tibble: 0 x 0
```

**Comment by cderv** [comment]
What is the result your are expecting? 
A *tibble* is already a `data.frame`. It is a `tbl_df` object that inherits of class `data.frame`, you can check with `class` function.  It is possible to use all of data.frame aware function with a tibble. 
`as_data_frame` is an aliases of `as_tibble` and helps convert list object to a *tibble*. 
Use `as.data.frame` if you do not want a tibble anymore.
