### ISSUE TITLE
Feature request: option for show_query() and explain() to return character (instead of message)

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3130]
Feature request: it would be very helpful to have an option for `show_query()` and `explain()` to return character (instead of message).  One can not always reliably/conveniently capture the message output using `utils::capture.output()` if other code (such as `reprex`, `knitr`/`rmarkdown`; they have `message=FALSE` controls, but these work at a very course granularity) are controlling/capturing the messaging path.

**Comment by hadley** [comment]
Unfortunately it's not possible to change the signature of these functions as they're designed to be run inside a pipeline, providing the output explicitly as a side-effect.

We could, however, introduce pure version that just do the computation.
