### ISSUE TITLE
bind_rows() error with survival:Surv and splines::bs columns

### ISSUE THREAD

**Issue by dhicks** [tidyverse/dplyr#3134]
bind_rows() seems to choke on certain kinds of multi-dimensional columns.  I'm seeing what looks like the same behavior in another case with a splines::bs column.  But it seems easiest to create a MWE with a survival::Surv column.  

```
library(tidyverse)
library(survival)

dataf = tibble(status = rbernoulli(10), 
               time = rgamma(10, 5))
bind_rows(dataf)

dataf$Surv = Surv(dataf$time, dataf$status)

bind_rows(dataf)
```
The first bind_rows() works as expected; the second throws this error: 
```
Error in bind_rows_(x, .id) : Argument 3 must be length 10, not 20
```

**Comment by hadley** [comment]
A special case of the general problem in #2457
