### ISSUE TITLE
db_write_table has differing defaults for temporary argument

### ISSUE THREAD

**Issue by jcheng5** [tidyverse/dplyr#3136]
The three methods for `db_write_table` have differing defaults for `temporary`:

```r
> formals(dbplyr:::db_write_table.DBIConnection)$temporary
[1] FALSE
> formals(dbplyr:::db_write_table.MySQLConnection)$temporary
[1] TRUE
> formals(dbplyr:::db_write_table.PostgreSQLConnection)$temporary
[1] TRUE
```

I assume this was unintentional?

**Comment by hadley** [comment]
Yeah, it should always be `TRUE`

**Comment by hadley** [comment]
Fixed in https://github.com/tidyverse/dbplyr/commit/e54d82f610300f668d63bf99c3cb97e7aae1fde9
