### ISSUE TITLE
print() should not say "with more rows" as often as it does

### ISSUE THREAD

**Issue by MZLABS** [tidyverse/dplyr#3137]
I have seen the following on many data-sources (`sparklyr` and `SQLite` as examples) so I figure it is in the `dplyr`/`tbl` printing code.  When printing a 10-row table the formatting ends with "with more rows", which is in fact false (and makes one more very minor, but completely avoidable, corner case in teaching and debugging).  It is a small thing but a change of the message to something like "with possibly more rows" would be a benefit.  A more clever fix would be to limit to (n+1) rows when displaying n rows (which lets the system know if the answer was n or not).

``` r
suppressPackageStartupMessages(library("dplyr"))
#> Warning: package 'dplyr' was built under R version 3.4.2
packageVersion("dplyr")
#> [1] '0.7.4'

db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

d <- copy_to(db, data.frame(x=1:10), 'd')

print(d)
#> # Source:   table<d> [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>        x
#>    <int>
#>  1     1
#>  2     2
#>  3     3
#>  4     4
#>  5     5
#>  6     6
#>  7     7
#>  8     8
#>  9     9
#> 10    10
#> # ... with more rows
```

**Comment by krlmlr** [comment]
Closing in favor of https://github.com/tidyverse/tibble/issues/371.

**Comment by krlmlr** [comment]
Thanks for reporting!
