### ISSUE TITLE
throw error when providing invalid column to `distinct()`

### ISSUE THREAD

**Issue by fmichonneau** [tidyverse/dplyr#3140]
When providing an invalid column name to `distinct()`, the full dataset is being returned without indication that the column specified is not in the dataset. `distinct()` already does throw an error if it's a grouped data frame.

```r
library(dplyr)
## no indication that foo isn't a column in  `iris`
distinct(iris, foo)
as.tbl(iris) %>% distinct(foo)
## however, with grouped data it throws an error
iris %>% group_by(species) %>% distinct(foo)
```

This is with dplyr 0.7.4.9000 (1a0730a3bae22cd3ac1fbd491e6d4b9ab339ff75)

**Comment by foo-bar-baz-qux** [comment]
This was feature merged and then reverted due to being a breaking change: #2955 and #3055. Should be included in the next release for breaking changes (0.9 probably).

**Comment by krlmlr** [comment]
This feels sufficiently dangerous that it warrants a message for the next release.

**Comment by krlmlr** [comment]
Thanks! I've decided to give a warning, let's hope downstream packages will adapt eventually.
