### ISSUE TITLE
Feature Request: Select Helper Functions inside Filter?

### ISSUE THREAD

**Issue by timothyslau** [tidyverse/dplyr#3141]
I find the Select helper functions in dplyr to be super useful to avoid digging into regular expressions. Is there a way to apply these to the filter function as well?

    #works
    CO2 %>% 
      select(starts_with("Pla"))
    
    # doesn't work
    CO2 %>% 
      select(starts_with("Pla")) %>% 
      filter(starts_with("Q"))

If we could just apply this regex magic under the hood to filter, it would make life a little easier.

**Comment by foo-bar-baz-qux** [comment]
I think you're better off using `startsWith()`, `endsWith()` and `stringr` functions.

Right now, the family of `dplyr` functions like `starts_with` return a vector of indices, while `filter()` requires a boolean vector. You could manually convert between the two if you really wanted to re-use those dplyr functions:

```r
set_mask <- function(mask, len) {
  ret <- rep(FALSE, len)
  ret[mask] <- TRUE
  ret
}

iris %>%
  filter(set_mask(starts_with('ver', vars = Species), n()))
```
but this is cleaner:

```r
iris %>%
  filter(startsWith(as.character(Species), 'ver'))
```

or 

```r
library(stringr)
iris %>%
  filter(str_detect(Species, 'ver'))  # equivalent to contains()
```

**Comment by bschneidr** [comment]
This issue should almost certainly be closed. The answer from @foo-bar-baz-qux is totally what you're looking for. In the future, it would be a good idea to research this kind of issue on StackOverflow or read up  on string manipulation functions in R before turning this into a Github issue.
