### ISSUE TITLE
Deprecated functions fail

### ISSUE THREAD

**Issue by WaterworthD** [tidyverse/dplyr#3143]
The function` summarise_each()` has been deprecated, it produces a warning when used. However deprecation means the function will be removed in the future but existing code should continue to run. The code below displays an error after the warning from`summarise_each()` and stops. I'm finding supporting R in a production environment which uses dply to be a significant challenge as each release breaks a significant amount of our code base!

```r
data <- data.frame(
  Date = c('2017-10-01','2017-10-02','2017-10-01'),
  Generator = c('g1','g1','g2'),
  CapacityFactor = c(.9,.8,.1)
)

data %>%
  select(Date,Generator,CapacityFactor) %>% 
  spread(Generator, CapacityFactor) %>%                  
  group_by(Date) %>%                                      
  summarise_each(funs(sum(., na.rm = TRUE)), -Date) %>%
  gather(Generator, CapacityFactor, -Date, factor_key = FALSE) %>%               
  mutate(CapacityFactor = ifelse(CapacityFactor == 0.0,NA,CapacityFactor))
```

**Comment by lionel-** [comment]
I think it was a bug that this used to work. `-Date` is not doing anything in that `summarise_each()` call because it's a grouping variable and those are not mapped over. It is thus misleading to the reader.

**Comment by hadley** [comment]
Generally, I'd recommend pinning package versions per project in a production environment so that you can deliberately perform upgrades when desired.
