### ISSUE TITLE
backend_dbplyr functions not working with only dplyr loaded

### ISSUE THREAD

**Issue by dpprdan** [tidyverse/dplyr#3145]
The [`backend_dbplyr`](https://github.com/tidyverse/dplyr/blob/master/R/dbplyr.R) functions are part of `dplyr` (and not `dbplyr`), but do not work when only `dplyr` (and not `dbplyr`) is loaded. I'd say this is a bug, or am I missing something?

``` r
suppressPackageStartupMessages(library(dplyr))
library(RSQLite)
con <- dbConnect(SQLite(), path = ":memory:")
dbWriteTable(con, "mtcars", mtcars[1:5, ])
db_list_tables(con)
#> Error in UseMethod("db_list_tables") : no applicable method for 'db_list_tables' applied to an object of class "c('SQLiteConnection', 'DBIConnection', 'DBIObject')

suppressPackageStartupMessages(library(dbplyr))
db_list_tables(con)
#> [1] "mtcars"
```

`db_list_tables` *does* work with only `dplyr` loaded, when `copy_to` is called before. But that's not the usual workflow with existing DBs. 

FWIW the dividing line between when a db-related function is in `dplyr` (e.g.`sql_translate_env`) and when it is in `dbplyr` (e.g.`translate_sql`) is not really apparent to me, but maybe that's just for backward compatibility?

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.2 (2017-09-28)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2017-10-18
#> Packages -----------------------------------------------------------------
#>  package    * version    date       source                          
#>  assertthat   0.2.0      2017-04-11 CRAN (R 3.4.2)                  
#>  backports    1.1.1      2017-09-25 CRAN (R 3.4.1)                  
#>  base       * 3.4.2      2017-09-28 local                           
#>  bindr        0.1        2016-11-13 CRAN (R 3.4.0)                  
#>  bindrcpp     0.2        2017-06-17 CRAN (R 3.4.0)                  
#>  bit          1.1-12     2014-04-09 CRAN (R 3.4.0)                  
#>  bit64        0.9-7      2017-05-08 CRAN (R 3.4.0)                  
#>  blob         1.1.0      2017-06-17 CRAN (R 3.4.0)                  
#>  compiler     3.4.2      2017-09-28 local                           
#>  datasets   * 3.4.2      2017-09-28 local                           
#>  DBI          0.7        2017-06-18 CRAN (R 3.4.0)                  
#>  dbplyr     * 1.1.0      2017-06-27 CRAN (R 3.4.0)                  
#>  devtools     1.13.3     2017-08-02 CRAN (R 3.4.1)                  
#>  digest       0.6.12     2017-01-27 CRAN (R 3.4.2)                  
#>  dplyr      * 0.7.4      2017-09-28 CRAN (R 3.4.2)                  
#>  evaluate     0.10.1     2017-06-24 CRAN (R 3.4.0)                  
#>  glue         1.1.1.9000 2017-10-09 Github (tidyverse/glue@d24c855) 
#>  graphics   * 3.4.2      2017-09-28 local                           
#>  grDevices  * 3.4.2      2017-09-28 local                           
#>  htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)                  
#>  knitr        1.17       2017-08-10 CRAN (R 3.4.1)                  
#>  magrittr     1.5        2014-11-22 CRAN (R 3.4.2)                  
#>  memoise      1.1.0      2017-10-16 Github (hadley/memoise@d63ae9c) 
#>  methods    * 3.4.2      2017-09-28 local                           
#>  pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.0)                  
#>  R6           2.2.2      2017-06-17 CRAN (R 3.4.0)                  
#>  Rcpp         0.12.13    2017-09-28 CRAN (R 3.4.2)                  
#>  rlang        0.1.2      2017-08-09 CRAN (R 3.4.1)                  
#>  rmarkdown    1.6        2017-06-15 CRAN (R 3.4.0)                  
#>  rprojroot    1.2        2017-01-16 CRAN (R 3.4.2)                  
#>  RSQLite    * 2.0        2017-06-19 CRAN (R 3.4.0)                  
#>  stats      * 3.4.2      2017-09-28 local                           
#>  stringi      1.1.5      2017-04-07 CRAN (R 3.4.1)                  
#>  stringr      1.2.0      2017-02-18 CRAN (R 3.4.2)                  
#>  tibble       1.3.4      2017-08-22 CRAN (R 3.4.1)                  
#>  tools        3.4.2      2017-09-28 local                           
#>  utils      * 3.4.2      2017-09-28 local                           
#>  withr        2.0.0      2017-10-16 Github (jimhester/withr@d1f0957)
#>  yaml         2.1.14     2016-11-12 CRAN (R 3.4.2)
```

</details>

**Comment by edgararuiz** [comment]
Hi @dpprdan , I believe that the `db_...` functions are intended as wrapper functions to make it easy to write translations for `dbplyr`.  For writing an analysis, then the `DBI` functions are the ones we should use.  More to your point, it makes sense (to me) that `dplyr` does not load `dbplyr` by default because your analysis may not involve databases, so that's why it needs to be explicitly called (`library(dbplyr`).  This can also be gleaned from the `dbplyr` article: http://dbplyr.tidyverse.org/articles/dbplyr.html

**Comment by dpprdan** [comment]
First off, this is a very minor issue, akin to nitpicking IMO, but since I brought it up 😉 .

It totally makes sense to me that `dplyr` does not load `dbplyr `by default and that `dbplyr `should be explicitly loaded when working with DBs. 

The thing is that 

a) in the [intro](http://dbplyr.tidyverse.org/articles/dbplyr.html) you mention, `dbplyr `is *not* loaded explicitly (there is only a `install.packages("dbplyr")`. In the [SQL Translation article](http://dbplyr.tidyverse.org/articles/sql-translation.html) OTOH `dbplyr `*is* loaded explicitly.)

b) the `backend_dbplyr` functions are part of `dplyr`, not `dbplyr`. Why is that then? Apparently @hadley [moved them back to dplyr](https://github.com/tidyverse/dplyr/commit/97c22c32abebd4ef83bf9f5f7aa9a8734eb7e1ed), so there probably is a good reason for that? But when they are part of `dplyr`, shouldn't they work with only `dplyr `loaded?

**Comment by hadley** [comment]
They're generic functions for which dbplyr provides an implementation. This is by design, to avoid some challenges related to separating dplyr and dbplyr. I wouldn't do it if starting from scratch.
