### ISSUE TITLE
dbplyr - Oracle - select, summaries, n, group_by not working

### ISSUE THREAD

**Issue by juliangkr** [tidyverse/dplyr#3147]
Hi @edgararuiz, 

I am opening an new issue that was started in #2940, as there might be several further issues.

after I used you update (from #2940 ) the one problem was solved, but I ended up with several new ones. First of all, maybe a view words on my connection setup. I have a function which returns me a connection. 

```R
connect = function(...) {
  connection_str = paste0('(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=', host, ')(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=', service_name, ')))')

   drv = dbDriver("Oracle") 
   con = DBI::dbConnect(drv, 
      user=username,
      password=password,
      dbname=connection_str)
   return(con)
}
```

Afterwards I'am using the following code to access the Tables within my oracle db

```R
con = connect()
schema = 'TEST_DB'
table_name = 'FOO'

table_obj = dplyr::sql(base::paste(schema, table_name, sep='.'))
table_obj = splyr::tbl(con, table_sql)
```

and than I am working on the `table_obj` variable for further filtering, selections, ... I have a whole set of functions that worked, when I was using my scripts with the dplyrOracle GitHub repository. 

The following is happening now:

``` R
table_obj %>% collect() # not working
Error in .oci.SendQuery(conn, statement, data=data, prefetch=prefetch)
  ORA-00900: invalid SQL statement

table_obj %>% show_query()
<SQL>
TEST_DB.FOO

table_obj %>% dplyr::filter(bar == 123) %>% collect() %>% class()  # works fine
[1] "tbl_df"  "tbl"  "data.frame"
```

Somehow it is only working, if I filter on anything.

Another issue is that `group_by()` and `summarize()` or `n()` seem not to work anymore.

```R
table_obj %>% 
  dplyr::filter(bar==123)
  dplyr::group_by(faa) %>%
  dplyr::summarise(cnt=n())

Error in .oci.SendQuery(conn, statement, data=data, prefetch=prefetch)
  ORA-00900: invalid number of arguments

table_obj %>% 
  dplyr::filter(bar==123)
  dplyr::group_by(faa) %>%
  dplyr::summarise(cnt=n()) %>%
  dplyr::show_query()

<SQL>
SELECT "bar", COUNT() AS "cnt"
FROM (TEST_DB.FOO) "asfasdas"
WHERE ("bar" = 123)
GROUP BY "faa"
```

Could you have a look on these issues, please as I would really like to use the dbplyr package instead of the old dplyrOracle workaround?

**Comment by edgararuiz** [comment]
Hi @juliangkr , can we try replacing these lines?

```
table_obj = dplyr::sql(base::paste(schema, table_name, sep='.'))
table_obj = splyr::tbl(con, table_sql)
```
with this one?

```
table_obj <- dplyr::tbl(con, dbplyr::in_schema(schema, table_name))
```

**Comment by juliangkr** [comment]
Hi @edgararuiz , when I'am trying your code, no statement is working, I always get the Error:

```
Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-00933: SQL command not properly ended 
```

**Comment by edgararuiz** [comment]
Hi @juliangkr , I think this is because the database you are trying to work with is Oracle 11 or below.  The SQL clause I initially used to get the top rows is only supported on Oracle 12c.  I have a PR that fixes that here: https://github.com/tidyverse/dbplyr/pull/27, you can try this version using: `devtools::install_github("tidyverse/dbplyr", ref = devtools::github_pull(27))`

**Comment by edgararuiz** [comment]
Hi @juliangkr , I was reminded yesterday of another way to switch schemata in Oracle, if `in_schema()` is not being recognize by a particular server connection.  The idea is to send an Oracle command that changes the current schema for your session:

```
DBI::dbExecute(con, "ALTER SESSION SET CURRENT_SCHEMA = MY_SCHEMA")
```

**Comment by juliangkr** [comment]
Hi @edgararuiz , I was trying both your recommendations, but both did not work completely. 
The suggested PR 27 fixed the issue with the need for a filter step, in order to print and `collect` the data. But with that fix the `is.na` issue from #2940 is back, which was fixed within PR 34. Is it possible for me to merge these PR's? Another issue seems to be that after 2-4 database calls, the connection expires with this setting, is there a reason for thar?

The second suggestion with `DBI::dbExecute(con, "ALTER SESSION SET CURRENT_SCHEMA = MY_SCHEMA")` did not work at all, the command returns `0`. (I changed MY_SCHEMA to the schema used before)

Might there be a mistake with my connection proceedure, which is stated above? My database version is:

``` SQL
SELECT * FROM V$VERSION
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production	0
PL/SQL Release 12.1.0.2.0 - Production	0
"CORE	12.1.0.2.0	Production"	0
TNS for Linux: Version 12.1.0.2.0 - Production	0
NLSRTL Version 12.1.0.2.0 - Production	0
```

The settings on my machine are, an installation of the Oracle Instant Client 12.2 and the following package versions:

```R
sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dbplyr_1.1.0.9000 ROracle_1.3-1     magrittr_1.5      dplyr_0.7.4       DBI_0.7          

loaded via a namespace (and not attached):
 [1] assertthat_0.2.0 R6_2.2.2         tools_3.3.3      bindrcpp_0.2     glue_1.1.1       tibble_1.3.4     Rcpp_0.12.12    
 [8] tidyr_0.7.1      pkgconfig_2.0.1  rlang_0.1.2      purrr_0.2.4      bindr_0.1 
```

Additionally, I have set `ORACLE_HOME, OCI_LIB64` to the main folder of oracle 12.2 and also added that path to my PATH variable

**Comment by edgararuiz** [comment]
Hi @juliangkr , good news! Hadley merged both PRs yesterday!  Can you try again after reinstalling and let me know please?

**Comment by juliangkr** [comment]
Hi @edgararuiz , for the reinstallation I used `devtools::install_github("tidyverse/dbplyr")` and tested my queries. The issue with the schema issue and PR 27 seem to work, but somehow  I still can't filter on`!is.na()`, which was fixed in PR 34

```R
table_obj  %>% 
  dplyr::filter(FOO=="bar", !is.na(FAA)) 
Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-00920: invalid relational operator

table_obj %>% 
  dplyr::filter(FOO=="bar", !is.na(FAA))  %>% 
  show_query()
<SQL>
SELECT *
FROM (TEST_DB.FOO) 
WHERE (("FOO" = 'bar') AND (NOT(CASE WHEN"FAA" IS NULL THEN 1 ELSE 0 END )))
``

**Comment by hadley** [comment]
@edgararuiz can you please file an new issue specifically for this problem

**Comment by juliangkr** [comment]
Hi @edgararuiz,

Recently I keep getting the errors, which I mentioned in this issue, again. I wondered, if anything was changed on the master branch, which introduced the wrong behavior.

I installed dbplyr using devtools and when I want to run `collect()` on one of my database tables without filtering the table I receive the error: `ORA-00920: invalid relational operator`. The system should still be the same.

Additionally, I tested it with PR 27, but I receive the same error. Do you have any idea?
