### ISSUE TITLE
Documentation: if DBI::dbConnect() is the way to connect dplyr to DBs then should require initExtension()

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3150]
If `DBI::dbConnect()` is now the preferred  way to connect `dplyr` to DBs then the documentation should include how to trigger `initExtension()` (or the equivalent) for each common database.  For example this is functionality that is in `dplyr::src_sqlite()`, but not triggered when using `DBI::dbConnect()` directly on a `SQLite` database.  This means switching the connection method can break downstream code.

Example:

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.4'

d <- data.frame(x = 1:2)
small <- 1

# SQLite example

#my_db <- dplyr::src_sqlite(":memory:", create = TRUE)
my_db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
#RSQLite::initExtension(my_db) # needed for many summary fns.

dSQLite <- copy_to(my_db, d, 'dSQLite')

dSQLite %>% 
  mutate(z = STDEV(x))
#> Error in rsqlite_send_query(conn@ptr, statement): no such function: STDEV
```

**Comment by hadley** [comment]
I think we should just handle this in RSQLite: https://github.com/rstats-db/RSQLite/issues/236
