### ISSUE TITLE
dbplyr::copy_to() not working with logical values on MySQL

### ISSUE THREAD

**Issue by petehobo** [tidyverse/dplyr#3151]
When I use copy_to() to create a MySQL database table, using a source dataframe containing logicals, the corresponding column is numeric, containing all zeroes.  I'd expect TRUE to be converted to 1.

In addition (not problematic for me, I just note it), the data type is at odds with the `sql_escape_logical()` result type, which is a string.

For example:
```r
library(tidyverse)
dbcon <- src_mysql(dbname = "database",
          host = "localhost",
          port = 3306,
          user = "user",
          password = rstudioapi::askForPassword("Database password"))


df <- tribble(
    ~colA, ~colB,
    "a",   TRUE,
    "b",   FALSE,
    "c",   TRUE
)

copy_to(dbcon, df, name = "logical_test", overwrite = FALSE, temporary = FALSE)

# Shows colB to be all 0
tbl(dbcon, "logical_test") %>% collect()

# In addition, data type contrasts with these
dbplyr::sql_escape_logical(dbcon$con, TRUE)
dbplyr::sql_escape_logical(dbcon$con, FALSE)
```

**Comment by hadley** [comment]
This is likely to be a bug lower down the chain, probably in RMySQL.  Might already be fixed in [RMariaDB](https://github.com/rstats-db/RMariaDB)

**Comment by hadley** [comment]
Or possibly related to https://github.com/tidyverse/dplyr/issues/2614

**Comment by hadley** [comment]
Fixed https://github.com/tidyverse/dbplyr/commit/038860c13320b7f3db4d957aa2606f13cf6f5fe6

**Comment by petehobo** [comment]
Thanks for the quick turnaround Hadley - much appreciated
