### ISSUE TITLE
dbplyr - is.na translation for Oracle does not work with filter()

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/dplyr#3166]
The translation in `dbplyr` used for `is.na()` in Oracle works with `mutate()` but not with `filter()`.  Same issue as https://github.com/tidyverse/dplyr/issues/3007, but for Oracle connections instead of MS SQL connections.

**Comment by edgararuiz** [comment]
Adding reference to this issue: https://github.com/tidyverse/dplyr/issues/3147

**Comment by edgararuiz** [comment]
Just confirmed that negating `mutate()` also fails: `mutate(x = is.na(mpg)`

**Comment by hadley** [comment]
Per slack discussion: using boolean expressions at the top level of select queries is not that common
and you can always work around it by writing the `if` yourself:

 ```R
# won't work
df %>% mutate(x = is.null(y))

# will work
df %>% mutate(x = ifelse(is.null(y), 1, 0))
```

Due to the complexity and risk of working around the limitation automatically, we'll leave the behaviour as is.
