### ISSUE TITLE
progress bar: `stop()` does not print completion time if the last change is too recent.

### ISSUE THREAD

**Issue by jarauh** [tidyverse/dplyr#3171]
The following outputs a completion time if sent to R one line at a time, but if sent to R in one batch, the completion time is not printed:

    p <- progress_estimated(10)
    for (i in 1:10) p$pause(0.1)$tick()$print()
    p$stop()

The problem seems to be: `print()` only prints when the last change to the progress bar was at least 50ms earlier, to avoid that printing the progress bar takes longer than progress itself.  However, this is not appropriate when the bar is in the stopped state.

**Comment by hadley** [comment]
I'd recommend using instead https://github.com/r-lib/progress

**Comment by jarauh** [comment]
Ok, but `dplyr` itself uses `progress_estimated`?  And it never completes its own progress bars, which is a shame.  Is there a plan to move `dplyr` to `progress`?

**Comment by hadley** [comment]
They're only used in `do()`, which is unlikely to see any changes in the future and I now believe that a list-col based workflow is a better idea.
