### ISSUE TITLE
dbplyr - Add support for common type evaluation functions

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/dplyr#3173]
Create translations that can handle common type evaluation functions, such as:

- `is.character()`
- `is.numeric()`

**Note:** Confirm that the solution works in the `SELECT` clause and the `WHERE` clause.  Also confirm that it works when negated (e.g.: `!is.numeric`)

**Comment by hadley** [comment]
I can't imagine how you'd use this in a database since the types of the variables are defined statically.

**Comment by edgararuiz** [comment]
One I can think of is when figuring out if a ZipCode field contains all numbers.  This would happen in QA cases or to identify US vs other zip codes.

**Comment by hadley** [comment]
But you can't make that sort of assertion on a row by row basis - it would be either TRUE or FALSE for every entry in that row.
