### ISSUE TITLE
dbplyr - MS SQL - copy_to() fails with local a data frame

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/dplyr#3174]
The `copy_to()` function fails on MS SQL connections because the `db_copy_to()` method  called does not use the unique way MS creates temp tables. 

Attempted command:
```
copy_to(con, mtcars, "mtcars2")
```

Error message: 
```
 Error: <SQL> 'CREATE TEMPORARY TABLE "mtcars2" (
  "row_names" varchar(255),
  "mpg" FLOAT,
  "cyl" FLOAT,
  "disp" FLOAT,
  "hp" FLOAT,
  "drat" FLOAT,
  "wt" FLOAT,
  "qsec" FLOAT,
  "vs" FLOAT,
  "am" FLOAT,
  "gear" FLOAT,
  "carb" FLOAT
)
'
  nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Unknown object type 'TEMPORARY' used in a CREATE, DROP, or ALTER statement. 
```

**Comment by imanuelcostigan** [comment]
@hadley @edgararuiz feel free to port across any code from my RSQLServer repo where I've had to tackle a lot of these MSSQL issues already. I don't think i'll be doing much dev work on RSQLServer given the recent changes to dplyr have "Sherlocked" the package.
