### ISSUE TITLE
Netezza backend

### ISSUE THREAD

**Issue by andreaspano** [tidyverse/dplyr#3178]
I would like to contribute at the translation of dplyr for ibm netezza

**Comment by edgararuiz** [comment]
Hi @andreaspano , thank you for moving the conversation here.  I recall that you mentioned that you already have some work done, is this in a fork I can take a look at?

**Comment by andreaspano** [comment]
Hi Edgard
At the moment I have connected Netezza to R by usung the odbc package and the simba driver from a Ubuntu desktop machine.
This is what I have done and it works smoothly.
Before moving forward, I was asking if you have a predefined set of tests that I can run on Netezza,
Otherwise, I will develop  the tests by my self 

require(odbc)
require(dplyr)
require(dbplyr)
con <- dbConnect(odbc::odbc(),
                   driver = "Simba",
                   database = "NYCFLIGHTS",
                   uid = "userR",
                   pwd = "xxx",
                   server = "192.168.69.xxx",
                   port = 5480)

dbListTables(con)
########################################
planes <- tbl(con, 'PLANES')
vars <- list('YEAR', 'TYPE', 'MANUFACTURER')
limit <- 10
arrange <- list('YEAR', 'TYPE', 'MANUFACTURER')
tbl <- 'PLANES'

df_dplyr <- planes %>%
  select_(.dots = vars) %>%
  arrange_(.dots = arrange) %>%
  head(limit) %>%
  collect()


qry <- paste('select', paste(vars, collapse = ', '),
      'from' , tbl,
      'order by', paste(arrange, collapse = ', '),
      'limit', limit )
df_sql <- dbGetQuery(con, qry) %>% as_tibble()

identical(df_dplyr, df_sql)
################################################
dbDisconnect(con)

**Comment by edgararuiz** [comment]
Ok great, it looks like the default translation is working for you so far.  Here's the package I use to test translations: https://github.com/rstudio/dbtest 

Please let me know if you have questions or issues using it in your environment

**Comment by metanoid** [comment]
Using the `dbtest` package I get a fatal crash on R using the below:

```
# R 3.4.2
library(dbtest) # github version 0.1.0
library(odbc) # version 1.1.5
library(dbplyr) #version 1.2.0
con = dbConnect(odbc(), dsn = “NetezzaDSN”) # Using driver NetezzaSQL
test_connection(con) # --> fatal error
```
