### ISSUE TITLE
SE verbs in dplyr >= 0.7 doesn't recognize Names

### ISSUE THREAD

**Issue by HuangRicky** [tidyverse/dplyr#3181]
Hi,
in dplyr < 0.7 , there's the SE version of verbs like select_ , mutate_ , etc..
in dplyr>=0.7 i saw there're changes to have select(!!SOME_CHAR_VECTOR) which is suppose to work as SE version.
however, they are not equivalent in terms of functionalities. The Name of the vector is ignored now.

```r
library(dplyr)
library(seplyr)
d <- tbl_df(iris)
a <- setNames('Sepal.Length','ff')

d %>% select(!!a)

# # A tibble: 150 x 1
# Sepal.Length
# <dbl>
# 1          5.1
# 2          4.9
# 3          4.7
# 4          4.6
# 5          5.0
```
code above shows that in 0.7.4, dplyr will not recognize the Name of the vector a.

in dplyr <0.7, the code below should return the new column with name "ff":
```r
d %>% select_(.dots = a)
```

meanwhile, i'm trying the package seplyr, which can successfully replicate select_ , even in dplyr=0.7.4 environment:
```r
d %>% select_se(a)
# A tibble: 150 x 1
# ff
# <dbl>
# 1   5.1
# 2   4.9
# 3   4.7
# 4   4.6
# 5   5.0
```

Is it possible to have the name recognized when dealing with SE?

**Comment by lionel-** [comment]
The next version of dplyr will use tidyselect which has support for character vectors in select functions. See https://www.tidyverse.org/articles/2017/09/erratum-tidyr-0.7.0/ for more information.

**Comment by JohnMount** [comment]
I think the following works:

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.4'
d <- dplyr::tbl_df(iris)

a <- setNames(c('Sepal.Length', 'Sepal.Width') , c('ff', 'gg'))
d %>% select(!!!a)
#> # A tibble: 150 x 2
#>       ff    gg
#>    <dbl> <dbl>
#>  1   5.1   3.5
#>  2   4.9   3.0
#>  3   4.7   3.2
#>  4   4.6   3.1
#>  5   5.0   3.6
#>  6   5.4   3.9
#>  7   4.6   3.4
#>  8   5.0   3.4
#>  9   4.4   2.9
#> 10   4.9   3.1
#> # ... with 140 more rows
```

**Comment by HuangRicky** [comment]
Thank you, three "!" version works:
```r
library(dplyr)
library(seplyr)
d <- tbl_df(iris)
a <- setNames('Sepal.Length','ff')

d %>% select(!!!a)
```

Thanks!

**Comment by JohnMount** [comment]
`seplyr` supplies a notation you might like.  Essentially with `seplyr` loaded `A := B` works a lot like `setNames(B, A)`.  So you could re-write your last example as:

``` r
suppressPackageStartupMessages(library("dplyr"))
library("seplyr")
#> Loading required package: wrapr
d <- tbl_df(iris)
a <- 'ff' := 'Sepal.Length'

d %>% select(!!!a)
#> # A tibble: 150 x 1
#>       ff
#>    <dbl>
#>  1   5.1
#>  2   4.9
#>  3   4.7
#>  4   4.6
#>  5   5.0
#>  6   5.4
#>  7   4.6
#>  8   5.0
#>  9   4.4
#> 10   4.9
#> # ... with 140 more rows

b <- 'ff2' := 'ff+1'
d %>% select(!!!a) %>% mutate(!!!b)
#> # A tibble: 150 x 2
#>       ff   ff2
#>    <dbl> <chr>
#>  1   5.1  ff+1
#>  2   4.9  ff+1
#>  3   4.7  ff+1
#>  4   4.6  ff+1
#>  5   5.0  ff+1
#>  6   5.4  ff+1
#>  7   4.6  ff+1
#>  8   5.0  ff+1
#>  9   4.4  ff+1
#> 10   4.9  ff+1
#> # ... with 140 more rows

d %>% select_se(a) %>% mutate_se(b)
#> # A tibble: 150 x 2
#>       ff   ff2
#>    <dbl> <dbl>
#>  1   5.1   6.1
#>  2   4.9   5.9
#>  3   4.7   5.7
#>  4   4.6   5.6
#>  5   5.0   6.0
#>  6   5.4   6.4
#>  7   4.6   5.6
#>  8   5.0   6.0
#>  9   4.4   5.4
#> 10   4.9   5.9
#> # ... with 140 more rows
```

**Comment by HuangRicky** [comment]
thank you, seems we can leverage seplyr package.

**Comment by lionel-** [comment]
> However, it doesn't work for "mutate" verb:

Neither should it. `mutate()` accepts strings as well, e.g. `mutate(mtcars, "foo")` is a valid expression that creates a new column by recycling. Interpreting strings as column names would be ambiguous. This ambiguity doesn't apply to select functions which is why they handle strings (and soon character vectors).
