### ISSUE TITLE
Add Support for Delayed Evaluation of Database Pools in tbl()

### ISSUE THREAD

**Issue by russellpierce** [tidyverse/dplyr#3184]
When I create a `tbl()` the database connection is baked into the resulting object.  If my database connection is lost (the db restarted, I opened too many connections and the original connection got pruned, etc), then I can no longer get un-evaluated dplyr SQL back out of the `tbl_dbi`.  I saw `package:pool` and thought, surely this will come to my rescue; if I only call tbl() using a database pool, then surely the connection inside the `tbl` will be evaluated in a lazy fashion and fetched from the pool. But no such luck, a bare con is baked into the tbl.

```r
library(RSQLite)
library(DBI)
library(dplyr)
library(pool)
dbPool(
  RSQLite::SQLite(), 
  dbname = ":memory:",
  validateQuery = "select 10"
) %>% 
  tbl(sql("select 1")) %>% 
  str()
```

If there is some other 'right' approach to be using here instead of adding a feature to dbplyr, please let me know!

**Comment by russellpierce** [comment]
The only "work-around" I've come up with so far is something like...

```
durableTbl <- R6Class("durableTbl",
        public = list(
          initialize = function(pool, target) {
            private$target <- target
            private$pool <- pool
          }
        ),
        active = list(
          tbl = function () {
            dplyr::tbl(src = private$pool, private$target)
          }
        ),
        private = list(
          target = NULL,
          pool = NULL
        )
)

selectoid <- durableTbl$new(
  dbPool(
    RSQLite::SQLite(),
    dbname = ":memory:",
    validateQuery = "select 10"
  ),
  sql('select 1')
)

selectoid$tbl
```

... but I'm not sure if that'll really work in practice and it seems... weird.

**Comment by hadley** [comment]
I think this is a pool issue. (Fixing it might need coordination from dplyr/dbplyr, but it'll be driven from the pool side). Can you please file an issue there?

**Comment by russellpierce** [comment]
Will do!
