### ISSUE TITLE
Different behaviour of dplyr::mutate depending on data source

### ISSUE THREAD

**Issue by jarekj71** [tidyverse/dplyr#3186]
I found that depending on the data source dplyr::mutate function returns different results. It happens when we divide two integers. If the data source is internal R data.frame etc. it returns full division (as one can expect), if data.source is external (i.e SQL database) dplyr uses Lazy Evaluation and directly apply SQL function inside the database to perform the calculation. SQL, however, perform integer division instead of full (floating point). Below is an example which shows the problem:

```r
cn <- src_sqlite("base.db",create=TRUE) # ceate sqlite database
tab <- tibble(x=as.integer(c(1,2,3,4)),y=as.integer(c(10,20,30,40))) # create testing tibble
copy_to(cn,tab,temporary = FALSE) # insert tible into database
btab <- tbl(cn,"tab") # create connection with table in database

#1 base on tible
tab %>% mutate(z=x/y) %>% collect
# A tibble: 4 x 3
#      x     y     z
 # <int> <int> <dbl>
#1     1    10   0.1
#2     2    20   0.1
#3     3    30   0.1
#4     4    40   0.1

#2 base on database
btab %>% mutate(z=x/y) %>% collect

# A tibble: 4 x 3
 #     x     y     z
 # <int> <int> <int>
#1     1    10     0
#2     2    20     0
#3     3    30     0
#4     4    40     0

```

**Comment by hadley** [comment]
Yes, you'll need to coerce one side of the division to a floating point number.
