### ISSUE TITLE
dplyr crashes R 3.4.*

### ISSUE THREAD

**Issue by anescalc** [tidyverse/dplyr#3191]
I have just installed R version 3.4 in a MacOS-El Capitan. When trying to load the `dplyr` package in RStudio, it kept crashing. I tried it with both versions 3.4.2 and 3.4.0., with no other packages or data loaded (only base packages).

To see if any informative errors appeared, I opened the console, and it again crashed. Here is the output:

    R version 3.4.2 (2017-09-28) -- "Short Summer"
    Copyright (C) 2017 The R Foundation for Statistical Computing
    Platform: x86_64-apple-darwin15.6.0 (64-bit)
    ....

    > library(dplyr)

     *** caught segfault ***
    address 0x0, cause 'memory not mapped'

    Traceback:
     1: dyn.load(file, DLLpath = DLLpath, ...)
     2: library.dynam(lib, package, package.lib)
     3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
     4: asNamespace(ns)
     5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     
        .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
     6: loadNamespace(package, lib.loc)
     7: doTryCatch(return(expr), name, parentenv, handler)
     8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
     9: tryCatchList(expr, classes, parentenv, handlers)
    10: tryCatch({    
            attr(package, "LibPath") <- which.lib.loc    
            ns <- loadNamespace(package, lib.loc)    
            env <- attachNamespace(ns, pos = pos, deps)
        }, error = function(e) {    
            P <- if (!is.null(cc <- conditionCall(e)))         
            paste(" in", deparse(cc)[1L])    else ""    
            msg <- gettextf("package or namespace load failed for %s%s:\n %s",         
            sQuote(package), P, conditionMessage(e))    
            if (logical.return)         
            message(paste("Error:", msg), domain = NA)    
            else stop(msg, call. = FALSE, domain = NA)
        })
    11: library(dplyr)

    Possible actions:
    1: abort (with core dump, if enabled)
    2: normal R exit
    3: exit R without saving workspace
    4: exit R saving workspace
    Selection: 

And this is the `dplyr`version I have installed:

    > packageVersion("dplyr")
    [1] ‘0.7.4’   

Also tried to run:

    > devtools::install_github("hadley/dplyr", build_vignettes = FALSE)

But it gave another segfault error. 

    ** R
    ** data
    *** moving datasets to lazyload DB
    ** inst
    ** tests
    ** preparing package for lazy loading

     *** caught segfault ***
    address 0x0, cause 'memory not mapped'
    Traceback:
     1: dyn.load(file, DLLpath = DLLpath, ...)
     2: library.dynam(lib, package, package.lib)
     3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
     4: asNamespace(ns)
     5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     
        .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
     6: loadNamespace(package, lib.loc, keep.source, partial = TRUE)
     7: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
     8: suppressPackageStartupMessages(loadNamespace(package, lib.loc,     keep.source, partial = TRUE))
     9: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     compress = compress)
    10: makeLazyLoading(pkg_name, lib, keep.source = keep.source)
    11: doTryCatch(return(expr), name, parentenv, handler)
    12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
    13: tryCatchList(expr, classes, parentenv, handlers)
    14: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
    15: try({    suppressPackageStartupMessages(.getRequiredPackages(quietly = TRUE))    makeLazyLoading(pkg_name, lib, keep.source = keep.source)})
    16: do_install_source(pkg_name, instdir, pkg, desc)
    17: do_install(pkg)
    18: tools:::.install_packages()
    An irrecoverable exception occurred. R is aborting now ...
    /Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 43363 Done                    echo 'tools:::.install_packages()'
     43364 Segmentation fault: 11  | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
    Installation failed: Command failed (139)

What can cause this behaviour? I previously had installed R 3.3.3 which worked well, and I haven't instaled other software or updates near the installation time. 

Thnks & sorry for the lenghty issue

**Comment by hadley** [comment]
This is typically because you've installed two incompatible binary packages. Start by re-installing dplyr and all its deps with `install.packages("dplyr", dep = TRUE)`. If that doesn't work, probably the best thing is to just delete all install packages and start again from scratch 😢

**Comment by anescalc** [comment]
I did the first option... so It seems I have no other one than to clean  `/library` and start from scratch :sweat_smile: :minidisc:
