### ISSUE TITLE
dplyr::copy_to(overwrite = TRUE) causes PostgreSQL to issue a spurious warning

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3197]
dplyr::copy_to(overwrite = TRUE) causes PostgreSQL to issue a spurious warning.  When deep in larger scripts are procedures this has been causing users to question the correctness of results as they do not have enough context to know which "tables did not exist" and what effect that has had on a larger process.  In context it looks like an unconditional drop was issued, perhaps there is a conditional drop that will not trigger this issue?

Below is a `reprex` showing the effect (using the dev version of `reprex` to capture the message).

```r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-08

# https://github.com/tidyverse/reprex/issues/90
# devtools::install_github("tidyverse/reprex")
# reprex::reprex(std_out_err = TRUE)
suppressPackageStartupMessages(library(dplyr))
packageVersion("dplyr")
#> [1] '0.7.4'
library("RPostgreSQL")
#> Loading required package: DBI
packageVersion("RPostgreSQL")
#> [1] '0.6.2'
my_db <- DBI::dbConnect(dbDriver("PostgreSQL"), 
                        host = 'localhost',
                        port = 5432,
                        user = 'postgres',
                        password = 'pg')
d <- copy_to(my_db, data.frame(x = 1), 
             name = 'd',
             overwrite = TRUE, temporary=TRUE)
```

standard output and standard error

```
#> NOTICE:  table "d" does not exist, skipping
```

**Comment by krlmlr** [comment]
I'm not even sure what's causing this notice, maybe libpq? Does the behavior differ with RPostgres?

**Comment by hadley** [comment]
Minimal reprex

``` r
library(dplyr, warn.conflicts = FALSE)

con1 <- DBI::dbConnect(RPostgres::Postgres())
d <- copy_to(con1, 
  data.frame(x = 1), 
  name = 'd',
  overwrite = TRUE, 
  temporary = TRUE
)
#> NOTICE:  table "d" does not exist, skipping
```

I suspect this is a RPostgres issue, not a dplyr one, but let me check.

**Comment by hadley** [comment]
It is not:

```R
con1 <- DBI::dbConnect(RPostgres::Postgres())
DBI::dbRemoveTable(con, "d")
DBI::dbWriteTable(con, "d", data.frame(x = 1), overwrite = TRUE)
```

runs without errors.  It's possible dbplyr takes a different root because of the pre-existing shims.

**Comment by hadley** [comment]
With latest dbplyr, dplyr, DBI, and RPostgres, I no longer see this problem:

``` r
library(dplyr, warn.conflicts = FALSE)

con1 <- DBI::dbConnect(RPostgres::Postgres())
d <- copy_to(con1, 
  data.frame(x = 1), 
  name = 'd',
  overwrite = TRUE, 
  temporary = TRUE
)
```

Created on 2018-06-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Oops, no running from wrong directory.
