### ISSUE TITLE
distinct(.data, ..., .keep_all) does not allow "negative" selection in ...

### ISSUE THREAD

**Issue by tvedebrink** [tidyverse/dplyr#3199]
If I want to identify the unique rows in a data.frame/tibble but only considers a subset of the columns I could ideally make "positive" or "negative" specification of the columns. However, it seems that only the positive variant is possible?

These lines refer to finding unique rows considering only `gear` and `carb`. However, the last approach fails.
```r
mtcars %>% distinct(gear,carb, .keep_all = TRUE)
mtcars %>% distinct(-(mpg:am), .keep_all = TRUE)
```

**Comment by RodrigueJr** [comment]
Hello,
I think the best way is :
` mtcars %>% select(-(mpg:am)) %>% distinct()`

**Comment by tvedebrink** [comment]
I think you are right - I had considered this, but found it suboptimal as I would look the information in the other columns. However, on an afterthought this would not make any sense as I would need to aggregate the rows in some manner when "marginalizing" over them. Sorry for the chatter...
