### ISSUE TITLE
Assigning NA yields error in case_when

### ISSUE THREAD

**Issue by mexindian** [tidyverse/dplyr#3202]
Not sure if this is a bug or feature-request... I've seen several `NA` errors related to `case_when`, like #2000, but I think they are all with the LHS, but what about assigning an NA? 

I know that technically NA is class `logical`, which explains the error I got... but shouldn't I be able to assign NAs to otherwise consistent vectors? Check out the reprex:

```r
library(dplyr)
iris %>% mutate(
  Sepal.Width=case_when(
    Sepal.Length == 5.1 ~ NA,
    TRUE ~ 2)) %>% head
#> Error in mutate_impl(.data, dots): Evaluation error: must be type logical, not double.

iris %>% mutate(
  Sepal.Width=case_when(
    Sepal.Length == 5.1 ~ 9999,
    TRUE ~ 2)) %>% head
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1        9999          1.4         0.2  setosa
#> 2          4.9           2          1.4         0.2  setosa
#> 3          4.7           2          1.3         0.2  setosa
#> 4          4.6           2          1.5         0.2  setosa
#> 5          5.0           2          1.4         0.2  setosa
#> 6          5.4           2          1.7         0.4  setosa
```

**Comment by cderv** [comment]
Know that it will work if you are precise with type declaration. 
In `case_when` help documentation page , it is precised  that

> Inconsistent lengths or types will generate an error.

`NA` is of type `logical`. You have other `NA` values for other types : `NA_real_`, `NA_character_`, `NA_integer_`, `NA_complex_`.  You need to use the right one for your case. Here, `NA_real_`

``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-10

library(dplyr)
iris %>% mutate(
  Sepal.Width=case_when(
    Sepal.Length == 5.1 ~ NA_real_,
    TRUE ~ 2)) %>% head
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1          NA          1.4         0.2  setosa
#> 2          4.9           2          1.4         0.2  setosa
#> 3          4.7           2          1.3         0.2  setosa
#> 4          4.6           2          1.5         0.2  setosa
#> 5          5.0           2          1.4         0.2  setosa
#> 6          5.4           2          1.7         0.4  setosa
```

**Comment by mexindian** [comment]
I confirm this works. I didn't know about those `NA_real_`. Would you guys accept a PR adding a sentence to the documentation and perhaps an example?

**Comment by krlmlr** [comment]
Thanks. A pull request that improves documentation would be most welcome.
