### ISSUE TITLE
clang command not found 

### ISSUE THREAD

**Issue by SeabassWells** [tidyverse/dplyr#3207]
Hi, I tried to install and load dplyr into my R instance, but I got an error having to do with a clang file.

It said -- 
/bin/sh: x86_64-apple-darwin13.4.0-clang++: command not found
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package ‘dplyr’
* removing ‘/Users/u/anaconda2/lib/R/library/dplyr’
* restoring previous ‘/Users/u/anaconda2/lib/R/library/dplyr’

I'm not sure where that command should be or how to get it. Any tips?

**Comment by batpigandme** [comment]
Hi @SeabassWells,
It looks like this might be an issue with your PATH/environmental variables. Since this is most likely not an issue with dplyr itself, it might be easier to get help with this over on community.rstudio.com.

**Comment by SeabassWells** [comment]
Got it, thank you

**Comment by WendyCui1018** [comment]
I have the same problem with you now. How did you solve it?

**Comment by SeabassWells** [comment]
I did not, sorry Wendy!

-- 
Sebastian Heyneman
415.513.7629 <(415)%20513-7629> | LinkedIn
<https://www.linkedin.com/in/sebastianhwells/>
Business Analyst @ BuildingConnected <http://www.buildingconnected.com>

On Nov 15, 2017 at 10:33 AM, Mara Averick <notifications@github.com> wrote:


Hi @SeabassWells <https://github.com/seabasswells>,
It looks like this might be an issue with your PATH/environmental
variables. Since this is most likely not an issue with dplyr itself, it
might be easier to get help with this over on community.rstudio.com.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tidyverse/dplyr/issues/3207#issuecomment-344685483>,
or mute
the thread

**Comment by WendyCui1018** [comment]
I just uninstalled Rstudio in anaconda, then installed it from official
website. The problem was solved. Maybe you can have a try!
