### ISSUE TITLE
case_when semantics

### ISSUE THREAD

**Issue by t-kalinowski** [tidyverse/dplyr#3208]
Hello,

`case_when` is great. As I've been using it more and more, I have two minor requests for changes that I think would make it easier to use.

can `case_when` get fall-through for missing supplied values similar to `base::switch`?

example usage:
``` r
x <- letters[1:5]
case_when(
   x == "a" ~ "case a", 
   x == "b" ~ , 
   x == "c" ~ "case b or c", 
            ~ "all other cases")
```
would give
``` r
[1] "case a"    "case b or c"   "case b or c"   "all other cases"   "all other cases"
```
Essentially what I'm proposing is that `case_when` supplies a `TRUE` on the left hand side if the last argument has a missing left hand side, and for earlier arguments missing a right hand side, the logical vector(s) on the left hand side keep getting `reduce`'d with `|` until an argument with a supplied right-hand-side is encountered.

**Comment by krlmlr** [comment]
Thanks. You can use the following syntax:

```r
x <- letters[1:5]
case_when(
   x == "a" ~ "case a", 
   x == "b" ~ , 
   x == "c" ~ "case b or c", 
   TRUE     ~ "all other cases")
```

It feels better to be explicit in this case.

**Comment by krlmlr** [comment]
We don't have fallthrough yet, and I'm not sure it's a good idea to add it. (For starters, a formula needs a RHS, you can't omit it.) Does the following work for you?

```r
case_when(
   x == "a" ~ "case a", 
   x == "b" |
   x == "c" ~ "case b or c", 
   TRUE     ~ "all other cases")
 ```

**Comment by romainfrancois** [comment]
agree with @krlmlr on both cases. I'll close this for now.
