### ISSUE TITLE
S4 definitions of "sql" and "ident" classes

### ISSUE THREAD

**Issue by lawremi** [tidyverse/dplyr#3212]
This line: https://github.com/tidyverse/dplyr/blob/d310ad1cef1c14d770c94e1a9a4c79c888f46af6/R/src_dbi.R#L179
has a couple of issues.
1. According to `dbplyr::ident()`, the S3 "ident" class derives directly from "character", not "sql". 
2. It seems that d(b)plyr assumes that objects of class "ident" (and the same applies to "sql", defined the line above) are actually character vectors, not just of class "character", i.e., there are `is.character()` checks. That means that any S4 class that would derive from "ident" would need to jump through some hoops to both have a character vector as its prototype _and_ derive from "ident" (currently a virtual class with a dummy S4 object as its prototype). A simple solution is to pass `ident()` as the prototype for the old class, i.e.,
```
setOldClass(c("ident", "sql", "character"), ident())
```
That might necessitate moving the class definitions to the dbplyr package. So I guess the general moral of the story is that any old class that wants to be implemented by a base type needs to provide a prototype. In S4, there is a difference between deriving from a class and actually inheriting the implementation of the class.

Here are some additional findings:
1. This line:
https://github.com/tidyverse/dbplyr/blob/3cc019dc1121480c44dbde65d60a19d6194b40c4/R/ident.R#L29
in dbplyr is not going to do anything right now, since `setOldClass()` defines classes lazily. If they already exist (from dplyr), they are not changed.
2. This:
https://github.com/tidyverse/dbplyr/blob/3cc019dc1121480c44dbde65d60a19d6194b40c4/R/ident.R#L24
for some reason returns a "sql" object instead of a "ident" object in the zero length case, so that will need to be fixed for the suggestion mentioned above to work.

**Comment by krlmlr** [comment]
Thanks for the detailed explanation. Do we also need to provide a prototype for the `"tbl_df"` class in tibble? https://github.com/tidyverse/tibble/blob/60281b31a6e67219abdfef012a8fc6c655c531df/R/tbl-df.r#L2

**Comment by hadley** [comment]
Hmmm, these class definitions seem to come from a confused place. 

@lawremi I've added the prototypes to dbplyr as you recommended, and in the next release of dplyr I'll remove the `setOldClass()` definitions from dplyr. Thanks for the help!

Fixing the zero-length input breaks a bunch of tests, presumably because I'm explicitly checking for empty sql, rather than empty ident somewhere. Working on that now.

**Comment by hadley** [comment]
It turns out the source of the problem was the semantics of `sql_vector()` - I had not correctly thought through the return values for zero-length inputs, coupled with borrowing paste semantics where the presence/absence of `collapse` changes it between an n-n transformation and a 1-n summary.

**Comment by hadley** [comment]
@lawremi this causes R CMD check to fail for R 3.2 and R 3.3:

[R 3.2](https://travis-ci.org/tidyverse/dbplyr/jobs/322931571)

```
0.48schecking whether the namespace can be unloaded cleanly ... WARNING
---- unloading
Error in .getClassFromCache(what, resolve.confl = "all") : 
  argument "where" is missing, with no default
Calls: unloadNamespace ... <Anonymous> -> .removeSuperclassBackRefs -> .getClassFromCache
Execution haltedchecking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘tibble’ ‘utf8’
  All declared Imports should be used.
```


[R 3.3](https://travis-ci.org/tidyverse/dbplyr/jobs/322931574)

```
Quitting from lines 82-91 (dbplyr.Rmd) 
Error: processing vignette 'dbplyr.Rmd' failed with diagnostics:
unable to find an inherited method for function 'dbExecute' for signature '"SQLiteConnection", "sql"'
Execution halted
```

But not in R 3.4 or R-devel. Any ideas what might be the problem?

**Comment by krlmlr** [comment]
I restarted the build after purging the cache, just to be very sure. FWIW, tic is running `update.packages()` by default.

**Comment by hadley** [comment]
Conditionally defining the sql class fixed the problem - https://github.com/tidyverse/dbplyr/commit/d7024a05b47e9f8e17a3d9070db3f9e32988cf5f

**Comment by krlmlr** [comment]
Can we close this?
