### ISSUE TITLE
dplyr prior versions

### ISSUE THREAD

**Issue by VikrantDogra** [tidyverse/dplyr#3213]
Hi,
Which packages can dplyr replace? What is the chronology of development of these packages?
Your response to this question will help me focus on current packages and help avoid duplication with older ones.

If this question is found relevant, it’ll also be nice if you could provide such package progression details for other current packages too. 

Thanks,
Vikrant

**Comment by batpigandme** [comment]
Hi @VikrantDogra,

This might be a better fit over on community.rstudio.com, as it's not really a bug, and the request isn't necessarily dplyr-specific. That, and there are more eyeballs over on the community site to help out! 

As for the history of dplyr packages and their changes, you can check out the [News](http://dplyr.tidyverse.org/news/index.html) section of the dplyr page. 

There's also a great (albeit somewhat older) post on the relationship between dplyr and dplyr by Jim Hester here: https://jimhester.github.io/plyrToDplyr/
