### ISSUE TITLE
Support everything() in transmute()

### ISSUE THREAD

**Issue by mungojam** [tidyverse/dplyr#3215]
Following the discussion [here](https://community.rstudio.com/t/conceptual-reason-for-transmute/2984/9), it would be useful to be able to use everything() in transmute so that cases where I want to just add a couple of columns at the start of the tibble are dealt with.

This would then be possible:

```r
library(dplyr)
myTibble <- tibble(
                        c = c(1, 2, 3), 
                        d = c(5, 6, 7)
                     )

fullTibble <- myTibble %>% 
                         transmute(
                                 a = c + 1,  
                                 b = c + 2, 
                                 everything()
                         ) 
#Error in mutate_impl(.data, dots) : 
#Evaluation error: Variable context not set.
```

I'd actually rather be able to do this with select and remove need for transmute, but if not, then transmute would be next best thing.

**Comment by krlmlr** [comment]
`select()` doesn't support mutates by design, so it'd have to be with `transmute()`. I like the idea, but the next release is planned to be bugfix-only.

**Comment by romainfrancois** [comment]
Let's not mix select and mutate semantics. You can do this I two steps, a mutate followed by a select. 

```r
myTibble %>% 
    mutate( a = c + 1,  b = c + 2 ) %>% 
    select(a, b, everything())
```
