### ISSUE TITLE
Function recode is not matching by position

### ISSUE THREAD

**Issue by AndreMikulec** [tidyverse/dplyr#3221]
Function `recode` is not matching by position.
The example says that it can.

```r
> x <- sample(c("a", "b", "c"), 10, replace = TRUE)
> x
 [1] "b" "a" "a" "c" "a" "b" "b" "b" "b" "c"
> recode(x, "a", "b", "c", .default = "other")
Error: Arguments 2, 3, 4 must be named, not unnamed
> recode(x, "a", "b", "c")
Error: Arguments 2, 3, 4 must be named, not unnamed
> decode
Error: object 'decode' not found

? recode
```

**Comment by cderv** [comment]
Hi, 

the documentation says that it can only for numeric vector. 
> Replacements. These **should be** named for character and factor .x, and **can be** named for numeric .x. 

The examples are showing exactly this.

1. First `x`  is a character vector to show it **should be** named
``` r
# Recode values with named arguments
x <- sample(c("a", "b", "c"), 10, replace = TRUE)
recode(x, a = "Apple")
#>  [1] "c"     "c"     "Apple" "b"     "Apple" "c"     "b"     "Apple"
#>  [9] "c"     "c"
recode(x, a = "Apple", .default = NA_character_)
#>  [1] NA      NA      "Apple" NA      "Apple" NA      NA      "Apple"
#>  [9] NA      NA
```
2. After `x` changes and becomes a numeric vector, and it shows you **could** also use named format
```r
# Named arguments also work with numeric values
x <- c(1:5, NA)
recode(x, `2` = 20L, `4` = 40L)
#> [1]  1 20  3 40  5 NA

# Note that if the replacements are not compatible with .x,
# unmatched values are replaced by NA and a warning is issued.
recode(x, `2` = "b", `4` = "d")
#> Warning: Unreplaced values treated as NA as .x is not compatible. Please
#> specify replacements exhaustively or supply .default
#> [1] NA  "b" NA  "d" NA  NA
```
3. Same numeric vector `x` is used to show you **could** also use a match by position.
```r
# If you don't name the arguments, recode() matches by position
recode(x, "a", "b", "c")
#> Warning: Unreplaced values treated as NA as .x is not compatible. Please
#> specify replacements exhaustively or supply .default
#> [1] "a" "b" "c" NA  NA  NA
recode(x, "a", "b", "c", .default = "other")
#> [1] "a"     "b"     "c"     "other" "other" NA
recode(x, "a", "b", "c", .default = "other", .missing = "missing")
#> [1] "a"       "b"       "c"       "other"   "other"   "missing"
```

In conclusion, with current version of `dplyr`, and per the documentation, 
* For vector of type character or vector, you have to use named replacements.
* For numeric vector, you can use both named replacements or match by position.

**Comment by AndreMikulec** [comment]
Thanks.
That explanation makes sense.  I am satisfied.
Maybe that explanation should be included in the docs?

.x ( position given ) looks in ( ... ), then grabs ( ... value at position )
``` 
> recode(c(1,2,3,NA_real_), 11, 13, 99, .default = 0, .missing = -1)
[1] 11 13 99 -1
```
Nothing at position number 5 (11,33,99), therefore .default
```
> recode(c(1,3,5,NA_real_), 11, 13, 99, .default = 0, .missing = -1)
[1] 11 99  0 -1
```

**Comment by krlmlr** [comment]
Thanks. I think it would be worthwhile to add an example for `recode()` on a numeric vector matched by position to the examples, and maybe add a sentence or two that better explains how positional matching is done. Would you like to contribute a PR?

**Comment by romainfrancois** [comment]
Anyone with a pr ? @cderv, @AndreMikulec ?

**Comment by cderv** [comment]
👍  I'll do it.
