### ISSUE TITLE
Assigning to the same column twice throws an error when using dbplyr 

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3222]
Assigning to the same column twice throws an error when using `dbplyr`. The below code may seem silly, but is a simplified version of a situation that can easily occur.

``` r
library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '0.7.4'

my_db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
d <- copy_to(my_db, data.frame(x = 1), 'd')

mutate(d, y = 1, y = 1)
#> Error: Column `y` must have a unique name
```

**Comment by edgararuiz** [comment]
@JohnMount - But, why? :)

**Comment by JohnMount** [comment]
Showed up in client code of the form `mutate(d, sel = f(), a = ifelse(sel, newa, a), sel = g(), b = ifelse(sel, newb, b))`.  I.e., they were re-cycling control variables that they didn't need later.

**Comment by edgararuiz** [comment]
Is this related to #3223 & #3216?

My recommendation would be to at the very least throw an error if there are any duplicate names inside `mutate()`, ideally, an error should be thrown if the `mutate()` command produces a duplicate name from its base query.  

@hadley  - Thoughts?

**Comment by JohnMount** [comment]
@edgararuiz I ran into it in the same debugging session as https://github.com/tidyverse/dplyr/issues/3223 .  No idea if it is a related issue.  This variation is easy to teach away from (don't assign a LHS twice in a mutate()), so I don't really see much point of fix beyond documentation and defining the intended semantics of mutate.  Mostly I'd like to see the in-memory and over-database code bases agree more closely on what is valid and what is not valid.

**Comment by hadley** [comment]
Yes, these are likely to all be the same underlying issue.

**Comment by MZLABS** [comment]
``` r
library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '0.7.4'
packageVersion("dbplyr")
#> [1] '1.2.0'

my_db <- DBI::dbConnect(RSQLite::SQLite(), 
                        ":memory:")
d <- copy_to(my_db, data.frame(x = 1), 'd')

# Users might expect the following
# two pipelines to be interchangeable.

d %>%
  mutate(y = 1, 
         v1 = y,
         y = 2,
         v2 = y,
         y = 3,
         v3 = y)
#> # Source: lazy query [?? x 5]
#> # Database: sqlite 3.19.3 [:memory:]
#>       x     y    v1    v2    v3
#>   <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  1.00  1.00  1.00  1.00  1.00

d %>%
  mutate(y = 1) %>% 
  mutate(v1 = y) %>%
  mutate(y = 2) %>%
  mutate(v2 = y) %>%
  mutate(y = 3) %>%
  mutate(v3 = y)
#> # Source: lazy query [?? x 5]
#> # Database: sqlite 3.19.3 [:memory:]
#>       x     y    v1    v2    v3
#>   <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  1.00  3.00  1.00  2.00  3.00
```
