### ISSUE TITLE
escaping numerics which are whole numbers should look like integers

### ISSUE THREAD

**Issue by lbakerIsazi** [tidyverse/dplyr#3230]
The current behaviour of escape() when applied to a numeric vector of whole numbers is to add a trailing '.0'. However, this can cause issues in some cases, for instance when dealing with PostgreSQL bigint columns which are usually drawn in to R as numerics.

In my case, I have a very large SQL table _big_table_ (~250 000 000 rows) with an indexed bigint column _customer_number_. I have a specific value `c = 37256083835234` of _customer_number_ for which I want to pull all records in _big_table_ as follows:
```r
tbl(db, "big_table") %>% filter(customer_number == c) %>% collect()
```

However, looking at the generated SQL query the 'where' filter generated is `customer_number == 37256083835234.0`, which forces PostgreSQL to perform a sequential scan over _big_table_, turning each customer_number into a double before doing the comparison, instead of simply doing an index scan, which it does if I generate and execute the SQL query as follows:
```r
dbGetQuery(db, paste("select * from big_table where customer_number =", c))
```

This behaviour would be avoided if small enough whole number numerics were output without any decimal point and digits thereafter, looking like integers, either by default or as an option. This does mean that the DB might need to do some conversions from bigints to doubles, but I think that is preferable to behaviour like this.

**Comment by krlmlr** [comment]
Thanks. This behavior is deliberate, because we want numeric values to be represented as such on the database. I'm not sure if `integer64` works, but we might support this so that the generated query doesn't have the `.0`.

**Comment by lbakerIsazi** [comment]
Hi. Adding support for `integer64` would be great! However, I don't have any experience with `integer64` or the `bit64` package. I've written up a little function which worked on the few examples I tried, which may work in general.
