### ISSUE TITLE
Hybrid evaluation bug in ungrouped summarise()

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#3233]
```r
df <- tibble(a = c(2, 2))
summarise(df, a = sum(a), sum(a))
#> # A tibble: 1 x 2
#>       a  `sum(a)`
#>   <dbl>     <dbl>
#> 1     4 4.94e-324
```

**Comment by thelatemail** [comment]
The issue seems to disappear when a `group_by` is involved:

    df %>% group_by(1) %>% summarise(A=sum(A),B=sum(A))
    ## A tibble: 1 x 3
    #    `1`     A     B
    #  <dbl> <dbl> <dbl>
    #1     1     4     4

**Comment by krlmlr** [comment]
Thanks, confirmed.
