### ISSUE TITLE
union the exactly same two copies gives different number of rows

### ISSUE THREAD

**Issue by jerryzhujian9** [tidyverse/dplyr#3238]
tested with latest tidyverse 

setequal(union(iris,iris),iris)  
union(iris,iris)  (149) has different number of rows from iris (150)! How can this be?

**Comment by cderv** [comment]
I often think that data.frame with rownames does not play well with `dplyr`. It may be related here.
If I pass rownames to columns, it works as expected.
``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
# with rownames
intersect(iris, iris) %>% nrow()
#> [1] 149
union(iris, iris) %>% nrow()
#> [1] 149
setequal(union(iris,iris),iris)
#> FALSE: Different number of rows
# Without rownames 
iris <- tibble::rownames_to_column(iris)
intersect(iris, iris) %>% nrow()
#> [1] 150
union(iris, iris) %>% nrow()
#> [1] 150
setequal(union(iris,iris),iris)
#> TRUE
```
Created on 2017-12-02 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

I think it is a good practice to not have rownames when working with `tidyverse`. 
From the `tibble` `rownames` documentation 
> Generally, it is best to avoid row names, because they are basically a character column with different semantics to every other column. 
It is why `tibble` provides some helpers to delete them or convert back and forth.

However, I am not sure why this behaviour with `union` and others. it is not consistent with `base` function. Don't know if it is intended or not. 

Hope It helps.

**Comment by JohnMount** [comment]
I think some of this is that one of `dplyr::union_all()` or `dplyr::bind_row()` may be the better operator for what I assume is your intended application.  Also definitely do not use `rownames` with `dplyr`, `tibble::rownames_to_column()` is strongly advised.

**Comment by jerryzhujian9** [comment]
Thank you all for the insights.  How about issuing a warning message then when having a input with rownames?

**Comment by jerryzhujian9** [comment]
Just a follow-up:
```
a=b=iris
rownames(a) <- NULL
rownames(b) <- NULL
union(a,b) %>% nrow  # still 149.  
```
Seems rownames() <- NULL would not have an effect here

**Comment by MZLABS** [comment]
There is a duplicate row and `union()` removes duplicates:

``` r

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
iris %>% group_by_at(., colnames(.)) %>% summarize(n = n()) %>% filter(n > 1)
#> # A tibble: 1 x 6
#> # Groups:   Sepal.Length, Sepal.Width, Petal.Length, Petal.Width [1]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width   Species     n
#>          <dbl>       <dbl>        <dbl>       <dbl>    <fctr> <int>
#> 1          5.8         2.7          5.1         1.9 virginica     2
```

Please try `union_all`:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
union_all(iris, iris) %>% nrow()
#> [1] 300
```

**Comment by krlmlr** [comment]
Thanks. Looks like `union()` does work as expected. Maybe we should be explicit in the documentation that duplicate rows are removed?

**Comment by edublancas** [comment]
I can help with this, what is the best way to proceed? Add the clarification at the beginning of the docs, add one example, both?

**Comment by krlmlr** [comment]
Clarification and example would be great. Does this affect `intersect()` and other verbs?

**Comment by batpigandme** [comment]
@edublancas, are you still interested in submitting a PR for this? If so, awesome, and, if not, that's totally fine, too. If you wouldn't mind letting us know when you get a chance (or if you have any questions), that'd be great so I know whether to add to my TODO list! 👍 
Thanks.

**Comment by edublancas** [comment]
@batpigandme Yes, I can work on this. I can probably find some time to do it during this week. Will  post updates here.

**Comment by edublancas** [comment]
Submitted PR (#3474), let me know what you think.
