### ISSUE TITLE
Edgecase handling of pull() with inexistent columns

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/dplyr#3244]
In some situations where the column to select does not exist, the supplied value is `NULL` or similar, it would be nice if `dplyr::pull()` could return something similar to what subsetting operations in base R or in tibble return (instead of an error), so no extra handling of these cases has to be done by the user. If `dplyr::pull()` does not behave like that by design, please ignore this issue.

Base R does this:
``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-12-07

library(dplyr)

mtcars$abcd
#> NULL
mtcars[["abcd"]]
#> NULL
mtcars[,character(0)]
#> data frame with 0 columns and 32 rows
mtcars[character(0), ]
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 Zeilen> (oder row.names mit Länge 0)
```

Using S3 methods for tibbles, we get
```r
tbl <- as_tibble(mtcars)
tbl$abcd
#> Warning: Unknown or uninitialised column: 'abcd'.
#> NULL
tbl[["abcd"]]
#> NULL
tbl[,character(0)]
#> # A tibble: 32 x 0
tbl[character(0), ]
#> # A tibble: 0 x 11
#> # ... with 11 variables: mpg <dbl>, cyl <dbl>, disp <dbl>, hp <dbl>,
#> #   drat <dbl>, wt <dbl>, qsec <dbl>, vs <dbl>, am <dbl>, gear <dbl>,
#> #   carb <dbl>
```
However, with `dplyr::pull()` we always seem to get an error:
```r
pull(tbl, character(0))
#> Error: `var` must evaluate to a single number or a column name, not a character vector
pull(tbl, NULL)
#> Error: `var` must evaluate to a single number or a column name, not NULL
pull(tbl, "abc")
#> Error: Strings must match column names. Unknown columns: abc
```

**Comment by krlmlr** [comment]
Thanks. The strict error is by design. If you need to distinguish cases, maybe it's better to use an `if()` beforehand, or maybe `purrr::possibly()`?

**Comment by lorenzwalthert** [comment]
Ok, thanks. I did not know about `purrr::possibly()` and friends. Neat.
