### ISSUE TITLE
case_when: issue with zero length RHS values

### ISSUE THREAD

**Issue by cipherz** [tidyverse/dplyr#3246]
dplyr::case_when (tested with dplyr 0.7.4), does not seem to behave correctly in situations where a part of the RHS returns a zero length character vector (see below).

```r
dplyr::case_when(
  0 == 1 ~ sprintf("%s", c()),
  TRUE   ~ "True"
)
#> character(0)
dplyr::case_when(
  0 == 1 ~  "False",
  TRUE   ~  "True"
)
#> [1] "True"
```

**Comment by krlmlr** [comment]
Thanks. What output do you expect in the first example?

**Comment by cipherz** [comment]
I expected the same output in both examples.

**Comment by krlmlr** [comment]
I see the documentation to `case_when()` matches your expectation, but this is not how it is designed. We now allow vectors of length != 1, but all lengths must be the same. If there is at least one vector of length one (in LHS and/or RHS), that's the length of the returned vector.

Would you like to contribute a PR that corrects the documentation?

**Comment by batpigandme** [comment]
So is it now the opposite of what it says under `@return`? It actually returns a vector as long as the _shortest_ vector, or is that a special case for lengths one or zero?

```r
#' @return A vector as long as the longest LHS or RHS, with the type (and
#'   attributes) of the first RHS.  Inconsistent lengths or types will
#'   generate an error.
```

**Comment by krlmlr** [comment]
We only allow vector of length 1 or `n`, and we return vectors of length `n`. The value of `n` must be consistent across all cases and `n == 0` is just a variant of `n != 1`.
