### ISSUE TITLE
dplyr::recode will not work when %>% from tibble

### ISSUE THREAD

**Issue by sammcq** [tidyverse/dplyr#3253]
I expected dplyr::recode to recode a column when using df %>% recode(column...) with a tibble, similar to mutate. Instead, it produces the following error: 

> Error in UseMethod("recode") : no applicable method for 'recode' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

```r
df <- tibble(x = 1:3,
             y = letters[1:3])

df %>%
  dplyr::recode(x,
                `1` = "a",
                `2` = "b",
                `3` = "c")
```

However, it works with the following alternatives. 

```r
  dplyr::recode(df$x,
                `1` = "a",
                `2` = "b",
                `3` = "c")
```
```r
df %>%
  mutate(x=dplyr::recode(x,
                `1` = "a",
                `2` = "b",
                `3` = "c"))
```

It would be great if recode could work with a tibble directly from %>% without using mutate or calling the df. This would help chaining arguments after recode with fewer commands. There are probably some unforseen complications with this that I am not aware of.

**Comment by batpigandme** [comment]
As reprexes [_n.b. df reset for each case, just removed for easier reading_]:
``` r
suppressPackageStartupMessages(library(tidyverse))
df <- tibble(x = 1:3,
             y = letters[1:3])

df %>%
  dplyr::recode(x,
                `1` = "a",
                `2` = "b",
                `3` = "c")
#> Error in UseMethod("recode"): no applicable method for 'recode' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

dplyr::recode(df$x,
              `1` = "a",
              `2` = "b",
              `3` = "c")
#> [1] "a" "b" "c"

df %>%
  mutate(x=dplyr::recode(x,
                         `1` = "a",
                         `2` = "b",
                         `3` = "c"))
#> # A tibble: 3 x 2
#>       x     y
#>   <chr> <chr>
#> 1     a     a
#> 2     b     b
#> 3     c     c
```
Created on 2017-12-17 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by lionel-** [comment]
It is by design that `recode()` takes vectors rather than data frames. A function that takes both would be confusing for several reasons. The vector version would be a regular function while the tibble version would be a quoting function, the arguments for each version would be different, etc.
