### ISSUE TITLE
if_else converts matrix into vector (unlike base::ifelse)

### ISSUE THREAD

**Issue by paulponcet** [tidyverse/dplyr#3256]
If `m` is the matrix: 

    m <- matrix(1:4, 2, 2)

then the following returns a matrix of the same size: 

    ifelse(m < 3, 1, 0)

while dplyr's `if_else` returns a vector: 

    dplyr::if_else(m < 3, 1, 0)

I would expect the latter to return a matrix too.

**Comment by krlmlr** [comment]
Thanks. How should this function behave if it's passed two or more matrices with different dimensions? Would you expect similar behavior from `case_when()` or perhaps other functions?

**Comment by romainfrancois** [comment]
`if_else` is clearly meant for vectors. I'd rather have it fail on matrices.

**Comment by hadley** [comment]
I think we should leave this for now; the correct resolution is to use the full type coercion system (which will eventually encompass matrices).

**Comment by hadley** [comment]
You can see my latest thinking about this at https://vctrs.r-lib.org/articles/stability.html#ifelse — we currently require the condition to be a vector, but the `true` and `false` values can be vectors or data frames.
