### ISSUE TITLE
Eliminate use of SET_NAMED

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3258]
```cpp
SEXP shared_SEXP(SEXP x) {
  SET_NAMED(x, 2);  // <============= here
  return x;
}
```

**Comment by krlmlr** [comment]
Needs to be replaced by `MARK_NOT_MUTABLE(x)`? Is there any downside to just making this change?

Reference: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Named-objects-and-copying

**Comment by lionel-** [comment]
No downside that I know of. Tomas said the named macros currently suffer from a bug which is why we need to switch.
