### ISSUE TITLE
Feature request: Add na.rm to pull()

### ISSUE THREAD

**Issue by msberends** [tidyverse/dplyr#3260]
For convenience in data analysis, I think it's a good idea to add `na.rm` as a parameter to the function `pull()` and let it obviously default to FALSE.
```r
pull(.data, var = -1, na.rm = FALSE)
```

I really like this new function by the way!

**Comment by krlmlr** [comment]
Thanks. Have you tried `purrr::discard()`?

``` r
library(magrittr)
c(NA, 1:3, NA) %>% purrr::discard(is.na)
#> [1] 1 2 3
```

> Created on 2017-12-27 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by edgararuiz** [comment]
Hi @msberends , just curious, are you using `pull()` with local data, or remote data (as in a database)?

**Comment by msberends** [comment]
Hello, local data only. Primarily tibbles, where I must use `pull` for getting a vector of the values of a variable. 
Hence, 
`data.frame[, col]` != `tibble[, col]`
But
`data.frame[, col]` == `tibble %>% pull(col)`

But since this is a separate function, I thought having `na.rm` would be really convenient.

**Comment by hadley** [comment]
This is out of scope for pull because adding `na.rm` would change the length of the response, and I think that would be a bad idea.
