### ISSUE TITLE
`copy_to` throws error for oracle-odbc

### ISSUE THREAD

**Issue by vitallish** [tidyverse/dplyr#3265]
When I run `copy_to` on an oracle database using oracle-odbc I get the error shown below:

```
Error: <SQL> 'ANALYZE TABLE "mtcars"'
  nanodbc/nanodbc.cpp:1587: HY000: [Oracle][ODBC][Ora]ORA-01490: invalid ANALYZE command
```

mtcars does get properly added as a table to the database, but the code throws an error only on the analyze statement.

**Comment by edgararuiz** [comment]
Hi, can you try running: `dbSendQuery(con, build_sql("analyze table ", as.sql("MTCARS")))`? I wonder if this is due to case matching

**Comment by vitallish** [comment]
I think this was fixed in https://github.com/tidyverse/dbplyr/commit/3ffd96cf19db790b4a4a5df376d61552178426c5. I had also tried to run this directly in Oracle and the error was still thrown. This https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_4005.htm looks like it explains the syntax.
