### ISSUE TITLE
Function Argument 

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/dplyr#3269]
df <- data.frame(A=c(1,2),B=c(3,4),C=c(5,6),D=c(7,7),E=c(8,8),F=c(9,9))
df %>% select(A, B, G)
Error in overscope_eval_next(overscope, expr) : object 'G' not found

Can we add argument  to the function to give warnings if the one of the object is not found, rather than error, or select whatever columns available  
Thanks

**Comment by cderv** [comment]
You can use `one_of` helper inside `select` to this purpose. It throws a warning if one a the variable is not found.
``` r
df <- data.frame(A=c(1,2),B=c(3,4),C=c(5,6),D=c(7,7),E=c(8,8),F=c(9,9))
library(dplyr, warn.conflicts = FALSE)
df %>% select(one_of("A", "B", "G"))
#> Warning: Unknown variables: `G`
#>   A B
#> 1 1 3
#> 2 2 4
df %>% select(one_of("A", "B", "G", "D"))
#> Warning: Unknown variables: `G`
#>   A B D
#> 1 1 3 7
#> 2 2 4 7
```

Created on 2017-12-30 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by krlmlr** [comment]
Thanks @cderv for chiming in!
