### ISSUE TITLE
dbplyr & sparklyr - `compute()` returns error, but it still creates the new table

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/dplyr#3285]
`as.sql()` is returning an error when using  using `dbplyr` 1.2.0, and `sparklyr` 0.6.4.  The trace-back from the first error says that the failure happened in the Analyze phase, so that's why I included a second test with `analyze` set to FALSE

cc @javierluraschi ; @kevinykuo
---

Brief description of the problem

```r
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", version = "2.1.0")

m <- copy_to(sc, mtcars)
compute(m, "new_mtcars1")
#> Error in UseMethod("as.sql"): no applicable method for 'as.sql' applied to an object of class "NULL"
compute(m, "new_mtcars2", analyze = FALSE)
#> Error in UseMethod("as.sql"): no applicable method for 'as.sql' applied to an object of class "NULL"
DBI::dbListTables(sc)
#> [1] "mtcars"      "new_mtcars1" "new_mtcars2"
spark_disconnect(sc)
```

**Comment by mstei4176** [comment]
I am getting the same error, using dbplyr 1.2.0, sparklyr 0.7.0-9106 with Spark 2.2.1.  

`all_sentences_tbl <- calls_csv_tbl %>%
  na.omit() %>%
  ft_regex_tokenizer(input.col = "transcript", output.col = "sentences_list",
                     gaps = FALSE, min_token_length = 2L, pattern = "[^.!?]*[\\.?!]", to_lower_case = TRUE)  %>%
  mutate(sent = explode(sentences_list)) %>%
  compute("all_sentences_tbl")`

Adding compute to the pipe throws the message:

`Error in UseMethod("as.sql") : 
  no applicable method for 'as.sql' applied to an object of class "NULL"`

**Comment by javierluraschi** [comment]
@edgararuiz we can close this one since a fix is being provided in `sparklyr`.
