### ISSUE TITLE
.env pronoun error, only when piped

### ISSUE THREAD

**Issue by karldw** [tidyverse/dplyr#3286]
Using the `.env` pronoun gives an error, but only when I'm piping in the data.  I'm pretty sure this is a bug, but I'm still trying to get a handle on tidyeval and I could easily be wrong.

Thanks, as always, tidyverse crew!

```r
library(dplyr)
disp <- 4
dplyr::filter(mtcars, .data$cyl == .env$disp)  # Works, 11 rows returned
mtcars %>% dplyr::filter(.data$cyl == .env$disp)
#> Error in filter_impl(.data, quo) : Result must have length 32, not 0
```
Package versions: dplyr 0.7.4 and 0.7.4.9000 (tidyverse/dplyr@db13e83), rlang 0.1.6.

**Comment by lionel-** [comment]
It's more of a misfeature than a bug, it's because magrittr evaluates in a child of the current environment rather than in the environment itself.

We are now recommending to use `!!` rather than the `.env` pronoun. Unquoting always evaluates in the current environment:

```r
disp <- 4
mtcars %>% filter(.data$cyl == !!disp)
```

**Comment by lionel-** [comment]
> Unquoting always evaluates in the current environment:

Well, actually in a magrittr pipe that environment is still a child of the current environment. But evaluating a symbol causes a lookup through the parents so `!!sym` works in more situations than `.env$sym` as the latter doesn't look through the ancestry. Note that a workaround is to use `get("sym", envir = .env)` but that's quite verbose compared to unquoting.

**Comment by karldw** [comment]
Bummer, I was a fan of the symmetry of `.data` and `.env`, but this makes sense.  Thank you!
