### ISSUE TITLE
Connecting to views in postgresqls using Rpostgresql

### ISSUE THREAD

**Issue by fnamugera** [tidyverse/dplyr#3296]
I amtrying to connect R to the postgresql remote database but am having challenges. I have followed the clues from <https://github.com/tidyverse/dplyr/issues/1007>  and <https://github.com/r-dbi/RPostgres/issues/27> but the problem still remains `LINE 1: SELECT * FROM "select * from view_name`. 

I am able to see `dbListTables()` but am interested in views.

```r
dbGetQuery(con, sql("select * from view_name"))

Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "select * from view_name limit 5" does not exist
LINE 1: SELECT * FROM "select * from view_name
                      ^)
```

**Comment by batpigandme** [comment]
Per @krlmlr's comment in the RPostgres thread you linked to, it sounds like `dbListTables()` should _include_ the views:
https://github.com/r-dbi/RPostgres/issues/27#issuecomment-347343059

Is that not the case? What comes up when you run `dbListTables()`?

**Comment by fnamugera** [comment]
`dbListTables(con)` lists the main tables but not the views in the database

**Comment by edgararuiz** [comment]
Hi @fnamugera , what happens if you use:

```
library(dplyr)
v <- tbl(con, "view_1")
```

The code that you currently shared in this issue has no `dplyr` components, so this may not be the best repo to report it on.  From the error, it looks like there's an issue with the quotations of sub-queries, which I hope `dplyr` 's version of the query may address that for you.

**Comment by fnamugera** [comment]
Thanks for the feedback. I have tried several codes including `tbl(con, "formview")`  but the error is still the same 
```r
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "formview" does not exist
LINE 1: SELECT * FROM "formview" AS "zzz32" WHERE 0=1
                      ^
)
```

**Comment by colearendt** [comment]
Do you have different schemas?  Can you provide the output of the following query?

```sql
select table_catalog, table_schema, table_name, table_type from information_schema.tables where table_name ilike '%formview%';
```

In order to work with schemas, you typically need to either reference the schema explicitly (i.e. `select * from schema.view`) or set your search path accordingly (i.e. `dbExecute(con,"SET search_path=schema)`)

The below verifies that RPostgres works as expected.

```r
library(RPostgres)
library(DBI)
library(dbplyr)
library(dplyr)

con <- dbConnect(Postgres(), host = "sol-eng-postgre.cihykudhzbgw.us-west-2.rds.amazonaws.com", 
  port = 5432, user = "rstudioadmin", password = "ABCd4321", db = "airontime")

dbExecute(con, "CREATE VIEW vairport AS select * from airport;")
#> [1] 0


dbListTables(con)
#>  [1] "airport"  "vairport" "iris"     "feedback" "faithful" "cars"    
#>  [7] "airports" "airlines" "flights"  "bank"

dbReadTable(con, "vairport")
#>                 aiport             city state country     lat      long
#> 1              Thigpen      Bay Springs    MS     USA 31.9538  -89.2345
#> 2 Livingston Municipal       Livingston    TX     USA 30.6859  -95.0179
#> 3          Meadow Lake Colorado Springs    CO     USA 38.9457 -104.5699
#> 4         Perry-Warsaw            Perry    NY     USA 42.7413  -78.0521

dbGetQuery(con, "select * from vairport")
#>                 aiport             city state country     lat      long
#> 1              Thigpen      Bay Springs    MS     USA 31.9538  -89.2345
#> 2 Livingston Municipal       Livingston    TX     USA 30.6859  -95.0179
#> 3          Meadow Lake Colorado Springs    CO     USA 38.9457 -104.5699
#> 4         Perry-Warsaw            Perry    NY     USA 42.7413  -78.0521

tbl(con, "vairport") %>% collect()
#> # A tibble: 4 x 6
#>   aiport               city             state country   lat   long
#>   <chr>                <chr>            <chr> <chr>   <dbl>  <dbl>
#> 1 Thigpen              Bay Springs      MS    USA      32.0 - 89.2
#> 2 Livingston Municipal Livingston       TX    USA      30.7 - 95.0
#> 3 Meadow Lake          Colorado Springs CO    USA      38.9 -105  
#> 4 Perry-Warsaw         Perry            NY    USA      42.7 - 78.1

dbExecute(con, "DROP VIEW vairport")
#> [1] 0
```

**Comment by fnamugera** [comment]
This 
```r
select table_catalog, table_schema, table_name, table_type from information_schema.tables where table_name ilike '%formview%';
```
return the list of views:
```r
    table_catalog table_schema       table_name                                   table_type
1  lg-ug              public                formview_u1_follow_up                         VIEW
2  lg-ug              public                formview_prophylaxis_follow_up            VIEW
```
However, `> dbListTables(mycon)` only still lists main tables  without views
```r
[1] "chp_muting"          "couchdb"             "couchdb_progress"    "couch2pg_migrations" "xmlforms_migrations"
```

and finally 
```r
> dbReadTable(mycon, "formview_u1_follow_up")
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "formview_u1_follow_up" does not exist
LINE 1: SELECT * from "formview_u1_follow_up"
                      ^
)
Error in names(out) <- make.names(names(out), unique = TRUE) : 
  attempt to set an attribute on NULL
In addition: Warning message:
In postgresqlQuickSQL(conn, statement, ...) :
  Could not create execute: SELECT * from "formview_u1_follow_up"


> tbl(mycon, "formview_u1_follow_up")
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "formview_u1_follow_up" does not exist
LINE 1: SELECT * FROM "formview_u1_follow_up" AS "zzz4" WHERE 0=1
                      ^
)
````

I really don't what am failing out on here!

**Comment by colearendt** [comment]
Do you mind entertaining one more request?  What is the output of:
```
select table_catalog, table_schema, table_name, table_type from information_schema.tables where table_schema='public';
```

**Comment by fnamugera** [comment]
```r
> dbGetQuery(mycon, "select table_catalog, table_schema, table_name, table_type from information_schema.tables where table_schema='public';")
    table_catalog table_schema                                                 table_name table_type
1  lg-ug       public                                           impactview_month       VIEW
2  lg-ug       public                                    impactview_chw_facility       VIEW
3  lg-ug       public                                  impactview_month_facility       VIEW
4  lg-ug       public                                           ancview_delivery       VIEW
```

And
```r 

> dbGetQuery(mycon,"SHOW search_path");      
 search_path 
1 "$user", public
--

```

**Comment by colearendt** [comment]
I'm thoroughly perplexed!  Where do `couchdb` and `chp_muting` or other "tables" live? Do you have a user-schema?

```
dbGetQuery(con, "select table_catalog, table_schema, table_name, table_type from information_schema.tables where table_name ilike ANY(array['chp_muting','couchdb','couchdb_progress','couch2pg_migrations','xmlforms_migrations']);")

```

Does the following work?
```
dbGetQuery(con,"select * from public.formview_u1_follow_up")
```

**Comment by fnamugera** [comment]
Other tables are within the lg postgresql database. They are the base tables 
```r
> dbGetQuery(mycon, "select table_catalog, table_schema, table_name, table_type from information_schema.tables where table_name ilike ANY(array['chp_muting','couchdb','couchdb_progress','couch2pg_migrations','xmlforms_migrations']);")
   table_catalog table_schema          table_name table_type
1 lg-ug       public xmlforms_migrations BASE TABLE
2 lg-ug       public couch2pg_migrations BASE TABLE
3 lg-ug       public    couchdb_progress BASE TABLE
4 lg-ug       public             couchdb BASE TABLE
5 lg-ug       public          chp_muting BASE TABLE

```

I have tried `dbGetQuery(con,"select * from public.formview_u1_follow_up")` several times but with no success

```r
> dbGetQuery(mycon,"select * from public.formview_u1_follow_up") Error in result_create(conn@ptr, statement) :    Failed to prepare query: ERROR:  permission denied for schema public LINE 1: select * from public.formview_u1_follow_up                       ^
--
```
These are the schemers i have from the postgresql database:
**scheme_name**
pg_catalog
information_schema
public
static

**Comment by colearendt** [comment]
Ohhh.  Are you changing `mycon` in between these queries you are executing?  "Database" is a part of the connection string, and I have been presuming thus far that you are working all within the same database (i.e. the same public schema, etc.).  It looks now like these views / tables are in separate databases?  You will need to be sure that you are connected to the database you are interested in.

That would explain the differences in what you are seeing. 

As for reading the views, `RPostgres` does not have any problem reading views like tables.  However, you will need the permission to read the views, just like you need permissions to read tables. 

> `ERROR:  permission denied for schema public LINE 1: select * from public.formview_u1_follow_up`

This makes it look like the issue here is schema permissions.  Your user needs read access to the schema that has the views you want to read.  Your user will also need read privileges on the view itself, and on the underlying tables.  

I suspect that this is not so much a `RPostgres` issue as a database permission / setup issue.  It will be very difficult to debug the issue without access to the database, so I suggest you spend some time with the (very good) [Postgres docs](https://www.postgresql.org/docs/10/static/ddl-schemas.html) or enlist the help of a DBA who has access to your system.

**Comment by fnamugera** [comment]
Thanks for the detailed explanation. The database am using is the same i simply changed the connection name from `con` to `mycon`.

Let me inquiry from the database admin to see if this `ERROR: permission denied for schema public LINE 1: select * from public.formview_u1_follow_up` can be solved from within.

thanks much.

**Comment by fnamugera** [comment]
Thanks @colearendt  true the problem was with permission to the database views. 

Thanks am now sorted.
