### ISSUE TITLE
Links to data not showing up in tidyverse reference page

### ISSUE THREAD

**Issue by apreshill** [tidyverse/dplyr#3300]
In both Chrome and Safari. I looked at the [index.html generated by pkgdown](https://github.com/tidyverse/dplyr/blob/master/docs/reference/index.html), and the links are missing there too. 

<img width="700" alt="screen shot 2018-01-15 at 7 08 29 am" src="https://user-images.githubusercontent.com/12160301/34948755-ebaecf86-f9c2-11e7-802e-6a72dc8728a2.png">

The links exist though: [http://dplyr.tidyverse.org/reference/starwars.html](http://dplyr.tidyverse.org/reference/starwars.html); [http://dplyr.tidyverse.org/reference/storms.html](http://dplyr.tidyverse.org/reference/storms.html)

I don't know enough about pkgdown to offer a PR to fix- thank you!

**Comment by batpigandme** [comment]
Thanks, @apreshill.

Can confirm builds fine with `pkgdown::build_site()` (did not generate correctly using `build_reference()` or `build_reference_index()`), but doing so changes all the docs (beyond CRAN release state).

**Comment by batpigandme** [comment]
Fixed in d6b1f98e47cc6dca557c531e596eee0950f907a9.
