### ISSUE TITLE
citation('dplyr') ends up with "unexpected symbol" error

### ISSUE THREAD

**Issue by SulevR** [tidyverse/dplyr#3301]
citation('dplyr') command ends up with "unexpected symbol" error:

Error in parse(text = x) : <text>:5:25: unexpected symbol
4:     person("Lionel", "Henry", role = "aut"),
5:     person("Kirill", "M"uller
                           ^

```r
citation('dplyr')

#returns:
#Error in parse(text = x) : <text>:5:25: unexpected symbol
#4:     person("Lionel", "Henry", role = "aut"),
#5:     person("Kirill", "M"uller                           ^
```
R version:
                      
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          2.3                         
year           2015                        
month          12                          
day            10                          
svn rev        69752                       
language       R                           
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree

**Comment by batpigandme** [comment]
It works in 3.4.2 (and, I'd assume, in the latest version, 3.4.3, as well).  Do you have the utf-8 package installed?

``` r
suppressPackageStartupMessages(library(dplyr))
citation("dplyr")
#> 
#> To cite package 'dplyr' in publications use:
#> 
#>   Hadley Wickham, Romain Francois, Lionel Henry and Kirill Müller
#>   (2017). dplyr: A Grammar of Data Manipulation. R package version
#>   0.7.4. https://CRAN.R-project.org/package=dplyr
#> 
#> A BibTeX entry for LaTeX users is
#> 
#>   @Manual{,
#>     title = {dplyr: A Grammar of Data Manipulation},
#>     author = {Hadley Wickham and Romain Francois and Lionel Henry and Kirill Müller},
#>     year = {2017},
#>     note = {R package version 0.7.4},
#>     url = {https://CRAN.R-project.org/package=dplyr},
#>   }
```

**Comment by SulevR** [comment]
No, "utf8" is not installed. Is this required? For some reason, installation of utf8 package currently fails and I cannot check:

> install.packages("utf8", repos="https://cran.r-project.org")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     100  1008    0  1008    0     0    742      0 --:--:--  0:--:--  0:00:01 --:--:--   7 0
tar: Failed to set default locale
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Warning in install.packages :
  'tar' returned non-zero exit code 1
Error in install.packages : file '/var/folders/81/2g8bxwys2sx87_rywpngrvdc0000gn/T//Rtmp2h5Y6t/downloaded_packages/utf8_1.1.3.tgz' is not an OS X binary package

**Comment by krlmlr** [comment]
Can you please show the output of `Sys.getlocale()`?

**Comment by krlmlr** [comment]
For the utf8 package: The OS X builds are lagging, you'll need xcode to install packages from source, or just wait until version 1.1.3 becomes available in binary form: https://cran.r-project.org/web/packages/utf8/index.html.

CC @patperry.

**Comment by SulevR** [comment]
> Sys.getlocale()
[1] "C"

**Comment by krlmlr** [comment]
Thanks. This must be the problem. Can you try in a UTF-8 locale?

**Comment by SulevR** [comment]
Yes, seems to be some error due to unset locale:
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
But this seems to be some other problem, not related to dplyr package. Probably it is just worth to add a workaround to dplyr if locale is not set.

**Comment by patperry** [comment]
I don't know why this is happening but I don't think it has anything to do with the `utf8` package.

You can probably fix the issue by changing the `DESCRIPTION` file. Replace

```r
person("Kirill", "Müller")
```

with

```r
person("Kirill", "M\u00fcller")
```

**Comment by krlmlr** [comment]
@patperry: That's a nice trick, thanks! CC'd you to notify you of the situation on CRAN.

**Comment by krlmlr** [comment]
This looks differently on Linux. I need to test this on OS X to get a better idea about what's wrong here.

**Comment by krlmlr** [comment]
Thanks! Saw the same behavior on OS X.
