### ISSUE TITLE
apply multiple patterns and replacements

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/dplyr#3302]
Dear 
I have dataframe (x) and I would like to mutate one of the columns
x <- x %>% mutate(
  var = ifelse(category == "Exchange rate anchor", 
               description, NA_character_), 
  var = str_replace_all(var, c(as.charintToUtf8(160) = " ",
                               "U.S.", "US")))
Error: unexpected '=' in:
"               description, NA_character_), 
  var = str_replace_all(var, c(as.charintToUtf8(160) ="
>                                "U.S.", "US")))
Error: unexpected ',' in "                               "U.S.","

I get this error, because I am trying to apply multiple patterns and replacements to the same column.
Please advise

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer)
