### ISSUE TITLE
Database filter on DBIConnection no longer works with latest development version of DBI

### ISSUE THREAD

**Issue by ckarras** [tidyverse/dplyr#3303]
I'm trying to build a dynamic SQL query using dplyr (latest dev version installed with devtools::install_github) and filter on a DBIConnection.

I get the following error:
```
    Error in getMethod("dbQuoteString", c("DBIConnection", "character"), asNamespace("DBI")) : 
    no method found for function 'dbQuoteString' and signature DBIConnection, character
```

After investigation, I found that the dbQuoteString methods have recently been modified in DBI, and
setMethod("dbQuoteString", c("DBIConnection", "character") has been removed:
https://github.com/r-dbi/DBI/commit/6c111b7f49632b03eff5f934ec9691f57f5f9702#diff-6d14eaf8cb28fc7edffaeb9d1337c374

I can workaround the issue by downgrading DBI to v0.7-12 (instead of 0.7-13):
devtools::install_github("rstats-db/DBI@v0.7-12")

```r
library(DBI)
library(plyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:plyr':
#> 
#>     arrange, count, desc, failwith, id, mutate, rename, summarise,
#>     summarize
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

sqlconn <- DBI::dbConnect(odbc::odbc(), Driver = "{SQL Server Native Client 11.0}", Server = "...", Database = "...", UID = "...", PWD = "...", Port = 1433)

sqlQuery <- "SELECT * FROM sys.tables"
tblQuery <- tbl(sqlconn, sql(sqlQuery))

queryResults <- tblQuery %>% 
  filter(name %in% c("Job","Schedule")) %>% 
  collect()
```

With version v0.7-13 of DBI, the following methods are available:
```r
showMethods("dbQuoteString")
#> Function: dbQuoteString (package DBI)
#> conn="DBIConnection"
```

By downgrading to version v0.7-12, the following methods are available (which solves the error):

```r
showMethods("dbQuoteString")
#> Function: dbQuoteString (package DBI)
#> conn="DBIConnection", x="character"
#> conn="DBIConnection", x="SQL"
```

Note: I'm reporting this here instead of the DBI project because I assume dplyr needs to be updated to work with the latest DBI. If this was an unintended breaking change in DBI, I could report the issue in DBI instead.

**Comment by edgararuiz** [comment]
Hi @ckarras , this may actually be an issue in the `odbc` package: https://github.com/r-dbi/odbc/issues/146, which has since been resolved.  Can you try again but with the dev version of `odbc` please?

**Comment by ckarras** [comment]
Hi @edgararuiz, I tried updating odbc. I tested both from r-dbi/odbc and your fork with the referenced fix:
```
devtools::install_github("r-dbi/odbc")
devtools::install_github("edgararuiz/odbc")
```
but I still get the same error with DBI v0.7.13 (and can resolve it if I revert to DBI v0.7.12)

After updating, the version I have of odbc is 1.1.3.9000, is it the expected version that should include the fix?

Thanks

**Comment by edgararuiz** [comment]
Ok, would you mind closing the issue in this repo and opening one in the DBI repo please?

Thanks!
