### ISSUE TITLE
as.integer64 compability for SQL SERVER

### ISSUE THREAD

**Issue by jnolis** [tidyverse/dplyr#3305]
Currently, when converting from R to a SQL Server query, d[b]plyr incorrectly handles "as.integer64" This is the function I would expect to use if I want to cast as a bigint within SQL Server. What ends up happening is dplyr uses "AS.INTEGER64" as a SQL Command

1. In SQL SERVER create an example table
```sql
CREATE TABLE Example (Number int)
```

2. In R using dbplyr, try and query the table after casting Number as an integer64
```r
tbl(con,"Example") %>%
  mutate(Number64 = as.integer64(Number))
```

3. This yields:
```
Error: <SQL> 'SELECT  TOP 10 "Number", AS.INTEGER64("Number") AS "Number64"
FROM "Example"'
  nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near the keyword 'AS'.
```

Which wouldn't happen if the SQL Query was the correct:
```
SELECT TOP 10 Number, CAST(Number AS BIGINT) AS NUMBER64
FROM EXAMPLE
```

**Comment by batpigandme** [comment]
See https://github.com/tidyverse/dplyr/issues/1092

**Comment by jnolis** [comment]
Thanks for the link. I'm not sure I fully understand though, if dplyr doesn't support 64 bit integers, why does extracting an existing SQL Server table with bigints in it create tables with integer64 columns? It is just partially supported somehow?

Here is an example where it creates an integer64:

1. In SQL Server:
```sql
CREATE TABLE Example2 (Number bigint)
INSERT INTO Example2 SELECT 3
```

2. In R:
```r
tbl(con,"Example2")
```

3. Results in:
```
# Source: table<Example2> [?? x 1]
# Database: Microsoft SQL Server 12.00.1000[jadler@lenatianalytics/MecMember]
  Number         
  <S3: integer64>
1 3         
```

Sorry if this is coming across as pedantic! I'm just trying to understand since I have some tables with bigints and once I bring them into R joining is causing problems (since some are ints and some are int64s). Thanks!

**Comment by batpigandme** [comment]
I'm not totally sure (someone more knowledgeable will, cc @edgararuiz), but based on the code I've linked to below, it looks like `integer64` is considered a "known class" when collected. But `as.integer64()` isn't a function in base or dplyr (the function from bit64 is used in [tests](https://github.com/tidyverse/dplyr/search?utf8=%E2%9C%93&q=as.integer64&type=). 
https://github.com/tidyverse/dplyr/blob/b3837f5dbf435458358f28ae47bbd0eb71796daa/tests/testthat/helper-combine.R#L180

**Comment by edgararuiz** [comment]
Ok, I think the right answer is to get `as.integer64()` to translate to `sql_cast("BIGINT")`.  I need to check on the other DB translations to see how they should handle it. 

@batpigandme - Can we mark this as `database` `feature` please?

Thanks all!

**Comment by hadley** [comment]
@edgararuiz do you want to have a go at this one too?

**Comment by edgararuiz** [comment]
Yes, I'll take it
