### ISSUE TITLE
Documentation of filter() return "value" is perhaps incorrect?

### ISSUE THREAD

**Issue by KasperSkytte** [tidyverse/dplyr#3308]
The documentation of `filter()` specifically says that the return value is *"an object of the same class as `.data`"* ([link](http://dplyr.tidyverse.org/reference/filter.html#value)). This is not true, any additional classes are dropped. I know this may be the desired behavior of filter and other functions, as this has been discussed in several issues and hasn't been changed, but then the documentation should perhaps be adjusted accordingly? 

```r
##### example tbl #####                         
tbl <- tibble::tibble(a = 1:3, b = letters[1:3])
tbl                                             
#> # A tibble: 3 x 2
#>       a b    
#>   <int> <chr>
#> 1     1 a    
#> 2     2 b    
#> 3     3 c
##### set a custom class #####                  
class(tbl) <- append(class(tbl), "test")        
class(tbl)                                      
#> [1] "tbl_df"     "tbl"        "data.frame" "test"
##### use filter to remove 3rd row #####        
tbl <- dplyr::filter(tbl, a < 3)                
tbl                                             
#> # A tibble: 2 x 2
#>       a b    
#>   <int> <chr>
#> 1     1 a    
#> 2     2 b
##### now the custom class is gone #####        
class(tbl)                                      
#> [1] "tbl_df"     "tbl"        "data.frame"
```

Personally, I like to just "tag" objects with a small ID or string now and then without having to create custom object systems and methods and what not

**Comment by krlmlr** [comment]
Thanks. With the upcoming approach to inheritance (https://adv-r.hadley.nz/s3.html#inheritance) we won't be able to maintain a custom class unless you provide a `reconstruct()` method for that class. We should revise all "return type" documentation.

**Comment by batpigandme** [comment]
Are we aiming to revise all the "return type" docs for the next release? If no, I'm not sure what the best way is to describe this concisely as a stop-gap measure: a `tbl_*` or `data.frame`, depending on the class of `.data`? _(though that ignores the option of a reconstructed class)_

``` r
suppressPackageStartupMessages(library(dplyr))
starwars_tibble <- filter(starwars, species == "Human")
head(starwars_tibble)
#> # A tibble: 6 x 13
#>   name      height  mass hair_color skin_color eye_color birth_year gender
#>   <chr>      <int> <dbl> <chr>      <chr>      <chr>          <dbl> <chr> 
#> 1 Luke Sky…    172   77. blond      fair       blue            19.0 male  
#> 2 Darth Va…    202  136. none       white      yellow          41.9 male  
#> # ... with 5 more variables: homeworld <chr>, species <chr>, films <list>,
#> #   vehicles <list>, starships <list>

# data.frame
sw_df <- as.data.frame(starwars)
res_df <- filter(sw_df, species == "Human")
class(res_df)
#> [1] "data.frame"

# tbl_df
sw_tbl_df <- tbl_df(starwars)
res_tbl_df <- filter(sw_tbl_df, species == "Human")
class(res_tbl_df)
#> [1] "tbl_df"     "tbl"        "data.frame"

# data.table
starwars_dt <- data.table::as.data.table(starwars)
class(starwars_dt)
#> [1] "data.table" "data.frame"
res_dt <- filter(starwars_dt, species == "Human")
class(res_dt)
#> [1] "data.frame"

# dtplyr
starwars_dtply <- dtplyr::tbl_dt(starwars)
res_dtply <- filter(starwars_dtply, species == "Human")
class(res_dtply)
#> [1] "tbl_dt"     "tbl"        "data.table" "data.frame"
```
Created on 2018-03-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by krlmlr** [comment]
The reprex looks correct, it's interesting that merely loading *dtplyr* already changes the value of the third example:

``` r
suppressPackageStartupMessages(library(dplyr))
starwars_tibble <- filter(starwars, species == "Human")

# data.table
requireNamespace("dtplyr")
#> Loading required namespace: dtplyr
starwars_dt <- data.table::as.data.table(starwars)
class(starwars_dt)
#> [1] "data.table" "data.frame"
res_dt <- filter(starwars_dt, species == "Human")
class(res_dt)
#> [1] "data.table" "data.frame"
```

> Created on 2018-03-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Already now we have the situation that methods from other packages may change the return value depending on the input. So I guess we can write "if data frame -> data frame, if tibble -> tibble, methods from other packages may override this for their own classes".

This looks like a fairly comprehensive documentation update. Important, but other documentation issues might be easier to solve first.

**Comment by hadley** [comment]
I don't think precisely describing the semantics (which are complex), is going to be terribly useful. While not 100% true, the current documentation at least defines the desired behaviour, and it will become more consistent in 0.9.0.
