### ISSUE TITLE
dbplyr can't be installed from CRAN because tibble is broken

### ISSUE THREAD

**Issue by ilyaminati** [tidyverse/dplyr#3311]
tibble is broken on CRAN:

https://cran.rstudio.com/web/checks/check_results_tibble.html

dbplyr 1.2.0 imports tibble (≥ 1.4.1), and because tibble is broken, dbplyr is unavailable for R 3.4.3 on OS X.

https://cran.rstudio.com/web/checks/check_results_dbplyr.html

**Comment by edgararuiz** [comment]
Linking to the issue reported in `tibble`: https://github.com/tidyverse/tibble/issues/356

**Comment by krlmlr** [comment]
Thanks. I'm releasing tibble very soon, sorry for the inconvenience.
