### ISSUE TITLE
Link to tidyselect from ?select and ?rename

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3314]
The documentation of `select()` and `rename()` should link to the functions in *tidyselect* for more details and examples.

**Comment by BruceZhaoR** [comment]
@krlmlr  what's wrong?
```r
dplyr::rename(iris, petal_length = Petal.Length)
#> Error: `petal_length` = Petal.Length must be a symbol or a string, not formula
packageVersion("dplyr")
#> [1] ‘0.7.4’
```

**Comment by krlmlr** [comment]
@BruceZhaoR: This works for me. Please file a new issue (and check your version of tidyselect). Deleting this comment and yours to keep this thread clean.
