### ISSUE TITLE
Standardise evaluation semantics

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#3316]
If possible we should have only two kinds of eval semantics: select and mutate.

There are currently small variations such as `group_by()` not finding symbols in the lexical context.

**Comment by krlmlr** [comment]
We still shouldn't allow names in `filter()` and `arrange()`.

Is this related to https://github.com/tidyverse/tidyselect/issues/48?

**Comment by lionel-** [comment]
> We still shouldn't allow names in filter() and arrange()

Why not?

> Is this related to tidyverse/tidyselect#48?

Ah yes, looks like it. We've been thinking with @hadley we should just teach about qq rather than making evaluation sematics more complicated. The selection semantics we experimented with this summer seemed to make things more confusing.

The bottom issue is that we are reproducing R evaluation semantics (e.g. such as you'd find in `subset()` or model formulas) but with quasiquotation the ideal semantics would be:

- find symbols in function position in data mask + lexical context
- find symbols in argument position only in data mask
- use qq to get objects in the lexical context

Alas this ship has already sailed, so I think we have to make do with mutate semantics.

**Comment by hadley** [comment]
By names, I think @krlmlr means named arguments - we currently have a custom message for `filter(mtcars, cyl = 4)` because it's a very common typo.

**Comment by lionel-** [comment]
That makes sense. This doesn't seems to contradict the standardisation of eval semantics because argument names pertain to capture rather than evaluation.

**Comment by romainfrancois** [comment]
I think there can be cases where having select semantics inside mutate would be useful, e.g. a function that `p_sum` below might like to be able to call `peek_vars`

``` r
library(tidyverse)

p_sum <- function(..., .vars){
  dots <- quos(...)
  vars <- tidyselect::vars_select(.vars, !!!dots)
  dplyr:::quo_reduce(!!!syms(vars), .op = `+`)
}

iris %>% 
  head() %>% 
  mutate( s = !!p_sum(-Species, .vars = names(.)) )
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species    s
#> 1          5.1         3.5          1.4         0.2  setosa 10.2
#> 2          4.9         3.0          1.4         0.2  setosa  9.5
#> 3          4.7         3.2          1.3         0.2  setosa  9.4
#> 4          4.6         3.1          1.5         0.2  setosa  9.4
#> 5          5.0         3.6          1.4         0.2  setosa 10.2
#> 6          5.4         3.9          1.7         0.4  setosa 11.4
```

would be nice if `p_sum` could be written: 

```
p_sum <- function(...){
  dots <- quos(...)
  vars <- tidyselect::vars_select(tidyselect::peek_vars(), !!!dots)
  dplyr:::quo_reduce(!!!syms(vars), .op = `+`)
}
```

Maybe that's a different matter though.

**Comment by lionel-** [comment]
Interesting suggestion. I think the use of unquoting would make things really confusing though. 

Perhaps these functions could make the assumption that `peek_vars()` reports variables defined in the caller environment? I'm not sure this would be reasonable but perhaps it is. Then you'd transform `vars` to a list of quosures scoped in the caller env and use `eval_tidy()` on your expanded expression.

**Comment by romainfrancois** [comment]
So we'd have this ?

```
iris %>% 
  head() %>% 
  mutate( s = p_sum(-Species) )
```

Is this not just a case of calling scoped_vars in mutate ?

**Comment by lionel-** [comment]
`p_sum()` will be trivial to implement and won't require unquoting once we have https://github.com/r-lib/rlang/issues/726

**Comment by romainfrancois** [comment]
`pick()` from #4586 gives this: 

``` r
library(tidyverse)

p_sum <- function(...) {
  rowSums(pick(...))
}

iris %>% 
  head() %>% 
  mutate( s = p_sum(-Species))
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species    s
#> 1          5.1         3.5          1.4         0.2  setosa 10.2
#> 2          4.9         3.0          1.4         0.2  setosa  9.5
#> 3          4.7         3.2          1.3         0.2  setosa  9.4
#> 4          4.6         3.1          1.5         0.2  setosa  9.4
#> 5          5.0         3.6          1.4         0.2  setosa 10.2
#> 6          5.4         3.9          1.7         0.4  setosa 11.4
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
Closing this because I think `across()` resolves the case of selection in an action context
