### ISSUE TITLE
Move data mask cleaning from rlang to dplyr

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#3318]
As we're no longer cleaning the mask by default.

Also investigate whether we can avoid active binding crashes without cleaning the data mask.

**Comment by krlmlr** [comment]
We might be able to avoid cleaning the data mask with weak references (`WEAKREFSXP`), need to look into it. But:

> At the time of writing no CRAN or Bioconductor package uses weak references.

That's not very promising...

**Comment by krlmlr** [comment]
On the other hand, we might also use a C++ implementation of weak references.

To recap: We need to clean the data mask because otherwise a pointer to an object with limited lifetime might leak. We are not in control of the lifetime of the objects for which we share an `XPtr`. We can overcome this by sharing only proxy objects that contain an internal weak reference to the real C++ object; when the real C++ object goes out of scope, the proxy returns some default value when accessed.

**Comment by lionel-** [comment]
Maybe an alternative is to add a `stale` flag in the data mask. When that flag is set a default value would be returned?

Or: adding a finalizer to the environment containing the active bindings and clean up the relevant dplyr objects from that finalizer?

**Comment by krlmlr** [comment]
One way or another, the proxy object needs to know that the data source isn't available anymore. I prefer controlling lifetime of internal *dplyr* classes from *dplyr* code.

**Comment by krlmlr** [comment]
This needs an enhancement to *bindrcpp*, which I meant to release anyway before updating *dplyr*: https://github.com/krlmlr/bindrcpp/issues/7. The current interface only supports naked pointers, I need to give up ownership at least for a proxy object.

**Comment by lionel-** [comment]
Is it useful to keep bindrcpp as a separate package?

**Comment by krlmlr** [comment]
It has two downstream dependencies ;-)

**Comment by krlmlr** [comment]
And, yes, the ping-pong between R and C++ is pretty convoluted, it helps to isolate it from the rest of the codebase.

**Comment by krlmlr** [comment]
I have an implementation that uses `boost::weak_ptr`, will share soon.

**Comment by krlmlr** [comment]
@lionel-: Is there functionality in *rlang* that can replace *bindr* and *bindrcpp*? I kept these packages separate to avoid the *Rcpp* dependency in *bindr*.

**Comment by lionel-** [comment]
I don't understand completely what those packages do but I don't think so.

**Comment by krlmlr** [comment]
*bindr* creates an environment full of almost identical active bindings. *bindrcpp* is the *Rcpp* interface to *bindr*.

**Comment by lionel-** [comment]
I think this functionality is too specific for rlang.
