### ISSUE TITLE
MSSQL: summarize adds GROUP BY "" statement for ungrouped data

### ISSUE THREAD

**Issue by jschelbert** [tidyverse/dplyr#3319]
I've just run into an error which was not there in an old version of dbplyr/dplyr (unfortunately can't say exactly when the error was introduced...)
When using the `summarize` function with a MSSQL database dplyr adds a `GROUP BY ""` to the SQL statement which should not be there...
With SQLite for example the correct SQL statement is given (without the GROUP BY "").

```r
library(odbc)
library(dplyr)
#> 
#> Attache Paket: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

connection <- dbConnect(odbc(),
                        driver = "SQL Server",
                        server = serverName,
                        database = databaseName,
                        encoding = "latin1")

copy_to(connection, mtcars, "test_mtcars")

tbl(connection, "test_mtcars") %>% 
    summarize(max_mpg = max(mpg, na.rm = TRUE)) %>% 
    show_query()
#> <SQL>
#> SELECT "", MAX("mpg") AS "max_mpg"
#> FROM "test_mtcars"
#> GROUP BY ""
```
In order to test above code you have to provide a valid server and database name.

Packages used:
```{r}
#>  dbplyr       1.2.0   2018-01-03 CRAN (R 3.4.3) 
#>  dplyr      * 0.7.4   2017-09-28 CRAN (R 3.4.2)   
#>  odbc       * 1.1.4   2018-01-10 CRAN (R 3.4.3) 
```

**Comment by edgararuiz** [comment]
Hi @jschelbert , would you mind trying it again with the dev version of `odbc`? 

```
devtools::install_github("r-dbi/odbc")
```

**Comment by jschelbert** [comment]
Hi @edgararuiz ,
I can confirm that with the dev version the error seems to be gone. I now get the correct SQL statement
```{SQL}
SELECT MAX("mpg") AS "max_mpg"
FROM "test_mtcars"
```
Do you have an estimated date when the dev version will be available on CRAN?
