### ISSUE TITLE
select_helpers do not work with summarize_at

### ISSUE THREAD

**Issue by jarauh** [tidyverse/dplyr#3323]
The documentation of `summarize_at` says:

    summarise_at(), mutate_at() and transmute_at() allow you to select columns using the same name-based select_helpers just like with select().

The `select_helpers` documentation gives the following example:

```r
> iris <- tbl_df(iris)
> select(iris, starts_with("Petal"))
```

However, the following analogue gives an error message:
```r
> mutate_at(iris, starts_with("Petal"), sum)
Error: Variable context not set
```

To make it work:
```r
> mutate_at(iris, starts_with("Petal", vars = names(iris)), sum)
```

dplyr-Version: 0.7.4

**Comment by lionel-** [comment]
You need to supply the selection in `vars()`:

```r
mutate_at(iris, vars(starts_with("Petal")), sum)
```
