### ISSUE TITLE
Ungrouped filter()/mutate() if only "creation" or "mutating" functions are used

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3326]
If a filter or mutate expression isn't affected by the grouping, we can process it all at once, without splitting in groups:

```r
iris %>% group_by(Species) %>% filter(Petal.Width < 1.3)
```

is the same as

```r
iris %>% filter(Petal.Width < 1.3) %>% group_by(Species)
```

and should be processed as such. This should be accompanied with a message (and a way to turn off that message or to enforce grouped processing), for cases where we misclassify the filter or mutate expression.

This only works if *all* filtering or mutating expressions only use "creation" or "mutating" functions, see http://r4ds.had.co.nz/transform.html#mutate-funs.

**Comment by krlmlr** [comment]
I agree it's tricky, and some functions under the link I shared don't even qualify. 

Is there a name for functions that work identically when turning off the grouping? What properties do they need to satisfy? I'd say the following might be sufficient, not sure if they're necessary:

```r
identical(f(a), c(f(a[[1]]), f(a[-1])))
identical(f(c(a, b)), f(c(b, a)))
```

**Comment by romainfrancois** [comment]
I think it is *very* difficult to do this automatically, and not so difficult for the user to switch order. 

One thing where we will gain, is that `iris %>% group_by(Species) %>% filter(Petal.Width < 1.3)` currently does a second hidden `group_by` to put together indices. That will change.

**Comment by romainfrancois** [comment]
`filter` is now smarter about remaking the grouping metadata, which I believe was the problem. 

I'll close this now as: 
 - I think it's very difficult (and so expensive) to come up with the rule
 - don't want dplyr to surprisingly change the order of functions

**Comment by krlmlr** [comment]
I agree it's fairly low priority, users should keep in mind to `ungroup()`.
