### ISSUE TITLE
summarize() changing integer result to double

### ISSUE THREAD

**Issue by behrman** [tidyverse/dplyr#3328]
Why does the following code change an integer result to a double?

Is there any way to avoid this?

Thanks,

Bill

```r
suppressMessages(library(tidyverse))

class(max(c(1L, 2L)))
#> [1] "integer"

tibble(x = "a", y = c(1L, 2L)) %>% 
  group_by(x) %>% 
  summarize(y = max(y)) %>% 
  pull(y) %>% 
  class()
#> [1] "numeric"
```

**Comment by krlmlr** [comment]
Because `max()` returns `-Inf` for empty vectors (or all-`NA` vectors with `na.rm = TRUE`), and we want type stability. Use `as.integer()` if you need an integer, this will warn if an `Inf` is passed.

**Comment by behrman** [comment]
Many thanks for the explanation and suggestion.

**Comment by krlmlr** [comment]
You're welcome. (Depending on your application, it may be faster to do a separate `mutate( = as.integer(...))` than to do it all in one like `summarize( = as.integer(max(...)))`.
