### ISSUE TITLE
Add documentation about what constitutes a "level of grouping."

### ISSUE THREAD

**Issue by jarauh** [tidyverse/dplyr#3329]
For example, when grouping by several variables and summarizing, the returned data frame is still grouped, but by one variable less.  Thus, it seems that grouping by several variables introduces several levels of grouping. This is not what I would have expected.  And this means that the grouping depends on the order of the variables in `...`. By the way, when applying `group_by_all/if/at` and `summarize`, the grouping of the result is difficult to control.

Also, the `...`-argument to `ungroup` is not explained.

**Comment by krlmlr** [comment]
Thanks, agreed that the documentation can be improved here. Would you like to submit a PR that updates documentation for `summarise()` and `ungroup()`?

What do you mean by "difficult to control"? `group_by_at(vars(...))` has `select()` semantics:

``` r
library(magrittr)
suppressPackageStartupMessages(library(dplyr))
iris %>% group_by_at(vars(starts_with("Petal"))) %>% groups()
#> [[1]]
#> Petal.Length
#> 
#> [[2]]
#> Petal.Width
iris %>% group_by_at(vars(Petal.Width, starts_with("Petal"))) %>% groups()
#> [[1]]
#> Petal.Width
#> 
#> [[2]]
#> Petal.Length
```

> Created on 2018-01-30 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by hadley** [comment]
I think `summarise()` needs a new section that describes what happens to grouping variables.
