### ISSUE TITLE
Translator is missing window variants of the following aggregate functions: * sd * sdp * varp

### ISSUE THREAD

**Issue by WaterworthD** [tidyverse/dplyr#3330]
Every time I do a basic aggregation using RSQLServer, I get the warning

Translator is missing window variants of the following aggregate functions: * sd * sdp * varp

i.e. something as simple as

```
connection <- dbConnect(RSQLServer::SQLServer(), server='server',database='database',properties=list(user='user',password='password'))
tbl(connection, "Table")%>%
    group_by(Col1) %>%
    summarise(Total = sum(Col2))
```

If I'm preforming multiple aggregations I get the message multiple times. It's not clear if this is a dplyr issue, or RSQLServer?

Regards
Dave

**Comment by krlmlr** [comment]
Thanks. I'm seeing two distinct issues here:

- *RSQServer*'s translation of SQL is incomplete and needs to be updated
- dbplyr reports about this every time it runs a query, but there's nothing the user can do about it

For the second, seems that we just need to use *memoise* for the `sql_translate_env()` methods.

**Comment by vjcitn** [comment]
"Translator is missing window variants of the following ...." should this even be a user-facing warning?  It sounds like a condition that should be raised for a developer in a test.  I get this warning with bigrquery.

**Comment by WaterworthD** [comment]
RSQLServer has been archived, they're suggesting the odbc package is better but on first glance it doesn't support dplyr?

**Comment by hadley** [comment]
I'd say now you should just use odbc. 

@WaterworthD odbc definitely does support dplyr.
