### ISSUE TITLE
Connecting to a Netezza source causes crash using newest `dbplyr`

### ISSUE THREAD

**Issue by metanoid** [tidyverse/dplyr#3334]
I use a combination of packages to pull data from a Netezza database server into R, and write data back to the same server: `dplyr`, `odbc`, and `dbplyr`.  This technique no longer works if I use the latest version of `dbplyr` (1.2.0). Specifically, using `copy_to` function causes a crash (i.e. a fatal error).  Using `dbplyr` version 1.1.0 does not cause a crash.

To reproduce, you will need an ODBC connection to a Netezza database server. I called the DSN of the connection "NetezzaDSN".  (I'm on Windows).

Reproducing using the package `dbtest`:
```
# Using R 3.4.2
library(dplyr)
library(dbtest) # github version 0.1.0
library(odbc) # version 1.1.5
library(dbplyr) #version 1.2.0
con = dbConnect(odbc(), dsn = “NetezzaDSN”) # Using driver NetezzaSQL
test_connection(con) # --> fatal error
``` 

Reproducing using the function `copy_to` :
 
```
library(dplyr)
library(odbc)
library(dbplyr)
con = dbConnect(odbc(), "NetezzaDSN")
data(mtcars)
copy_to(con, mtcars, name = "test_table", temporary = FALSE, analyze = FALSE)
```

**Comment by edgararuiz** [comment]
Hi @metanoid , does it also fail using DBI? `dbWriteTable(con, "mtcars", mtcars)`

**Comment by metanoid** [comment]
@edgararuiz sorry for the late response - didn't see a notification
No, using `DBI::dbWriteTable` works as expected.
I will use that instead.
