### ISSUE TITLE
summarize() give wrong results on particular vectors

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#3336]
For some particular vectors (but not all!), at least on my computer, dplyr 0.7.4 (did not test other versions) gives wrong results when applying the function summarize():
```r
foo <- c(178, 175, 159, 164, 183, 160, 181, 189, 174, 177)
level <- c(rep("A", 6), rep("B", 4))
c(mean(foo[level == "A"]), mean(foo[level == "B"]))
```
gives as expected
```r
[1] 169.8333 180.2500
```
But in dplyr:
```r 
d <- data.frame(foo, level)
d %>%
  group_by(level) %>%
  summarize(Mean = mean(foo))
```
I get:
```r
# A tibble: 2 x 2
  level  Mean
  <fct> <dbl>
1 A       170
2 B       180
```
Am I too tired, misusing dplyr in this simple case (possible), or is there some serious issue here?

**Comment by krlmlr** [comment]
Thanks. This is just a printing artifact, we should definitely print at least the decimal dot here. The numbers should be accurate, they're only shown with three significant numbers (rounded).

**Comment by krlmlr** [comment]
The display will improve when r-lib/pillar#40 is fixed.
