### ISSUE TITLE
dbplyr: Invalid column reference  'UQCALIASFORSQ1'

### ISSUE THREAD

**Issue by jamesthurgood34** [tidyverse/dplyr#3338]
I am using HIVE as a backend using dbplyr thus this example may be difficult to reproduce.

This is using a hortonworks distribution of HIVE 1.2.1000.2.5.0.0-1245

I can connect to the database and execute without simple commands such as: select, filter, group_by and summarise.
Here is an an example query that works:
```r
table %>%
   filter(key == 'a') %>%
   group_by(date) %>%
   summarise( summed_a = sum(value))
```

I encounter a problem when I try and join two of these intermediate tables.

Here is an example which returns an error:

```r
left_join( 
   table %>%
   filter(key == 'a') %>%
   group_by(date) %>%
   summarise( summed_a = sum(value)),

   table %>%
   filter(key == 'b') %>%
   group_by(date) %>%
   summarise( summed_b = sum(value)),

   by = c('date')
)
```

The error returned on this statement is:

Invalid column reference  'UQCALIASFORSQ1'.

This is confusing as when check the query that is being executed there is no reference to 'UQCALIASFORSQ1':

```sql
SELECT `TBL_LEFT`.`date` AS `date`, `TBL_LEFT`.`a` AS `a`, `TBL_RIGHT`.`b` AS `b`
  FROM (SELECT `date`, SUM(`value`) AS `a`
FROM (SELECT *
FROM schema.database
WHERE (`key` = 'a')) `ubfopsdmdf`
GROUP BY `reporting_date`) `TBL_LEFT`
  LEFT JOIN (SELECT `date`, SUM(`value`) AS `b`
FROM (SELECT *
FROM schema.database
WHERE (`key` = 'b')) `modxtdqtpu`
GROUP BY `date`) `TBL_RIGHT`
  ON (`TBL_LEFT`.`date` = `TBL_RIGHT`.`date`)
```

What confuses me even more is that the above SQL statement works when run with odbc::dbGetQuery

**Comment by edgararuiz** [comment]
Hi @jamesthurgood34 , is the SQL code returned by `sql_render()` the same? And if not, can you try that code and let me know if it works?

**Comment by hadley** [comment]
Closing since there was no answer.
