### ISSUE TITLE
substr() not being translated correctly into PostgreSQL/Redshift SUBSTRING

### ISSUE THREAD

**Issue by josnarog** [tidyverse/dplyr#3339]
When connected to a Redshift database using odbc, dplyr and dbplyr, submitting a 'substr()' query is not successfully translated into ~~Postrgresql~~ Redshift ('SUBSTRING') but is instead passed as 'SUBSTR' causing a SQL error when executed on the Redshift database. 

Packages and versions:

other attached packages:
[1] bindrcpp_0.2 dbplyr_1.2.0 dplyr_0.7.4  DBI_0.7   odbc_1.1.5  

Relevant connection Details:

con <- DBI::dbConnect(odbc::odbc(),
                      Driver       = "Amazon Redshift (x64)",
                      servername   = ******,
                      database     = ******,
                      UID          = *******,
                      PWD          = ******,
                      Port         = ****)

R command:
*translate_sql(substr(date_string, 6,7), con=con )*
Output Observed:
*<SQL> substr("date_string", 6, 2)*
Expected Output:
*<SQL> substring("date_string", 6, 2)*

```r
con <- DBI::dbConnect(odbc::odbc(),
                      Driver       = "Amazon Redshift (x64)",
                      servername   = ******,
                      database     = ******,
                      UID          = *******,
                      PWD          = ******,
                      Port         = ****)

translate_sql(substr(date_string, 6,7), con=con )
```

**Comment by edgararuiz** [comment]
Hi @josnarog , you're correct.  Even thought Redshift is based on PostgreSQL 8, the `substr` function does not seem to have been ported over.  We'll have to make an override for the Redshift translation, or switch the underlying PostgreSQL translation to use `substring`:  https://docs.aws.amazon.com/redshift/latest/dg/String_functions_header.html

**Comment by asantucci** [comment]
For other users that are struggling with the recent update to dbplyr which may have broken their work-flow...

Simply changing `substr` to `substring` in your dplyr chain of commands will fix the following error.

tbl(db, "name") %>% mutate(newvar = substr(char_var, 1, 4))
Error in postgresqlExecStatement(conn, statement, ...) : RS-DBI driver: (could not Retrieve the result : Error: function pg_catalog.substring(character varying, integer, numeric) does not exist
Line 1: SELECT ..., SUBSTRING(..., 1, 4.0) AS ...

**Comment by edgararuiz** [comment]
Hi @asantucci , would you mind testing a fix I have in a PR I just sent over?  I'd love to have a second confirmation that it's now fixed before I ask for a review: 
`devtools::install_github("tidyverse/dbplyr", ref = devtools::github_pull(70))`

**Comment by asantucci** [comment]
@edgararuiz I've ran the `install_github` command provided above and re-run the section of code which "previously" yielded an error. I place "previously" in quotes since after changing `substr` to `substring`, the error was resolved. After updating the package via `install_github`, and continuing to use `substring`, I do not encounter an error.

I hope this is helpful.

**Comment by edgararuiz** [comment]
Yes is it, thanks!
