### ISSUE TITLE
string filter issue using `odbc` with SAP HANA ODBC Drivers

### ISSUE THREAD

**Issue by washcycle** [tidyverse/dplyr#3343]
The issue:

*The Goal*:

I want the sql generated to have this form or equivalent:

```
SELECT COLUMN1
FROM SCHEMA.TABLE
WHERE (LOCATE(COLUMN1, 'pattern') = 1) 
LIMIT 6;
```

I am trying to find strings that start with a specific pattern.

** The Issue**

If I use a `dplyr` `filter(...)` these solutions don't work...

`stringr::str_locate`, `string::str_detect` I tried a whole slew of things, these all create some malformed SQL.

`str_detect` gets translated into INSTR which is a MySQL specific function from what I can tell.

```
<SQL>
SELECT *
FROM SCHEMA.TABLE
WHERE (INSTR('pattern', "COLUMN") > 0)
LIMIT 6
```

This last one below will work, but isn't documented; I found it by trying things until something worked.

`locate(COLUMN, 'pattern')` this translates into the expected LOCATE 

I am not even sure how this works because locate isn't a function from what I can tell.

```r
library(DBI)                                                     
library(dplyr)                                                   
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(dbplyr)                                                  
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql
library(readr)                                                   
                                                                 
con <- DBI::dbConnect(odbc::odbc(),                              
driver = "/Applications/sap/hdbclient/libodbcHDB.dylib",         
servernode = "host:port",                                        
uid = rstudioapi::askForPassword("UID"),                         
pwd = rstudioapi::askForPassword("PWD"),                         
CHAR_AS_UTF8 = TRUE # need this set because ASCII default is dumb
)                                                                
#> Error: RStudio not running
                                                                 
tbl_ref <- tbl(con, in_schema("schema","table"))                 
#> Error in tbl(con, in_schema("schema", "table")): object 'con' not found
                                                                 
tbl_ref %>%                                                      
filter(stringr::str_locate(COLUMN1, "pattern") == 1) %>%                      
head() %>% show_query()                                      
#> Error in eval(lhs, parent, parent): object 'tbl_ref' not found
```

Database is SAP HANA, there is a free version now if you wanted to replicate down to the database layer.
https://www.sap.com/developer/topics/sap-hana-express.html

Thanks,
Matt

**Comment by edgararuiz** [comment]
Hi @washcycle ,this makes sense since there are no HANA specific translations yet in `dbplyr`.  Also, your workaround makes sense, and it's probably the best way going forward until we have a customization for HANA.  At this point, a new page in the site, which contains the workaround, is the best short-term solution, until we can get a customization for this connection.

**Comment by washcycle** [comment]
Gotcha. I think, I was going to start working on making the translation.
Seems those translation files are pretty straight forward. If I get around
to it I'll send ya'll a pull request.

Cheers!
