### ISSUE TITLE
error in bind_rows column can't be converted from date

### ISSUE THREAD

**Issue by jrubinstein** [tidyverse/dplyr#3345]
I'm trying to pull down a big ugly SQL table using RPostgres 
```
res <- dbSendQuery(con, sessions_query)
datalist<-c()
i=0
while(!dbHasCompleted(res)){
  i=i+1
  chunk <- dbFetch(res, n = 10000)
  datalist[[i]] <- chunk
} 
```

when I attempt to bind_rows using  `experiment_session_df <- dplyr::bind_rows(datalist)`
I get this error message: 

>   Error in bind_rows_(x, .id) :   Column `sessionduration` can't be converted from Date to integer64
Calls: &lt;Anonymous&gt; ... withVisible -&gt; eval -&gt; eval -&gt; &lt;Anonymous&gt; -&gt; bind_rows_ -&gt; .Call
Execution halted

First, the column "sessionduration" is not a Date formatted column. 
Second, it doesn't always choke on that column, sometimes it's one of my 84 other columns. 
Third, sometimes it doesn't choke at all, usually on the 2nd or 3rd try, it works just fine. 

This is a massive problem when I am trying to knit a large R markdown report because it takes 5 minutes just to run the SQL and then _sometimes_ I get this failure. 

I'd use rbind (which works 100% of the time) but it's much, much slower. I'd use data.table::rbindlist, but not all data.frame commands work with data.table, so I'd have to rewrite my code. 

Is there a workaround to this issue? 
Thanks!

**Comment by edgararuiz** [comment]
Hi, are the data transformations you are doing after the data is downloaded something that we could possibly operate inside the database using dbplyr?

**Comment by jrubinstein** [comment]
@edgararuiz  I'm not any data transformations. I do a bit of light filtering, but that's in the SQL statement. The rest of the script is analysis.

**Comment by hadley** [comment]
This looks more like a RPostgres issue than a dplyr issue. I'd recommend creating a proper reprex (even if it runs only on your computer it's more likely to get a response than your current problem, which is very vague).
