### ISSUE TITLE
deplyr package is not found on window for R-version 3.4.3

### ISSUE THREAD

**Issue by dadwalrajiv** [tidyverse/dplyr#3350]
Hello,

I am quite new to R, i have installed R version 3.4.3 on my window machine, Now i am trying to install deplyr package but it seems that is not available in repository. Kindly suggest me how to fix this. I tried to change the version form tools> Global option but it didn't work for me.  

Regards,
Rajiv

**Comment by batpigandme** [comment]
This might be a spelling issue (there is no _e_ in dplyr:
```r
install.packages("dplyr")
```

**Comment by dadwalrajiv** [comment]
Thanks batpigandme, that is silly mistake.......
