### ISSUE TITLE
order_by() could have an error hint when confused with arrange()

### ISSUE THREAD

**Issue by econandrew** [tidyverse/dplyr#3357]
For those of us who sometimes have SQL on the brain...

```r
> df <- df %>% order_by(value)
Error: `call` must be a function call, not a symbol
> df <- df %>% order_by(-value)
Error: Can't use matrix or array for column indexing
> df <- df %>% arrange(-value)
```
e.g. Did you mean to use arrange()?

**Comment by Lef-F** [comment]
I just stumbled upon this while trying to figure out why `order_by` is "not working for me today"...  😆

**Comment by AmeliaMN** [comment]
Similarly, `select()` could have an error hint when confused with `filter()`. (Students often mix those two up, and so too does my jetlagged brain.)

**Comment by baderstine** [comment]
This is a great suggestion ('did you mean to use arrange()?', why yes, I did but I scrmalbed the R/SQL in my head.

**Comment by hadley** [comment]
@AmeliaMN @baderstine I can't see any easy way to disambiguate `select()`, `filter()`, or `pull()` so I've hidden your comments. If you can think of a good approach, please feel free to open new issues.

**Comment by hadley** [comment]
This would be relatively simple to implement — `order_by()` just needs to check if `call` is a symbol, and if so, offer a hint about `arrange()`.

**Comment by dennet** [comment]
stumbled upon this after a long break from the tidyverse. Hint about 'arrange()' in the error message would be a nice touch.
