### ISSUE TITLE
combine(NULL) should return logical() instead of error

### ISSUE THREAD

**Issue by zeehio** [tidyverse/dplyr#3365]
Given that `combine()` acts like `c()` I don't understand why `combine()` (without args) does not work like `c()` returning `NULL` and raises an error instead.

If I am combining a list that may contain all `NULL` elements, I'd rather get back a `NULL` than tryCatching or checking for that condition myself in advance. It's not a big deal, but it does not seem consistent with for instance `bind_rows()` that returns an empty tibble.

If you agreed I'd be happy to provide a pull request.

``` r
c(1, NULL, 2)
#> [1] 1 2
dplyr::combine(1, NULL, 2)
#> [1] 1 2
c()
#> NULL
dplyr::combine(NULL)
#> Error in combine_all(args): no data to combine, all elements are NULL
c(NULL, NULL)
#> NULL
dplyr::combine(NULL, NULL)
#> Error in combine_all(args): no data to combine, all elements are NULL
```

As always, thanks for your time

**Comment by krlmlr** [comment]
@romainfrancois: Do you remember why you made `combine()` raise an error in response to #1596? I feel this and `combine(NULL)` or `combine(list())` should return `logical()`, for consistency with `tibble::enframe(NULL)` .

**Comment by romainfrancois** [comment]
I don’t recall. Why logical ?

**Comment by krlmlr** [comment]
Because `logical()` can be coerced to anything, see also https://github.com/tidyverse/tibble/issues/352.

**Comment by romainfrancois** [comment]
That makes sense. Not sure why we went for strict error.

**Comment by krlmlr** [comment]
Thanks.

@zeehio: Would you like to submit a PR?

**Comment by zeehio** [comment]
I will be happy to submit a PR next week, if you don't mind the delay :smiley:

**Comment by zeehio** [comment]
@krlmlr submitted, feel free to review whenever you have the time :smile:  https://github.com/tidyverse/dplyr/pull/3387
