### ISSUE TITLE
The output of show_query() gets truncated

### ISSUE THREAD

**Issue by OssiLehtinen** [tidyverse/dplyr#3366]
Hello,

I ran into a problem with show_query():

I have constructed quite acomplex stream of operations with dbplyr. The final aim is to take the generated SQL and use it as the basis for a database view.

The issue is, that due to the complexity of the calculation, the resulting SQL becomes quite long and ends up getting truncated in R.

Probably I'm missing some obvious method for setting the maximum output length, but Google-Fu is not good enough right now.

Can something be done here?

**Comment by edgararuiz** [comment]
Hi @OssiLehtinen , can you try `remote_query()` instead of `show_query()`?

**Comment by OssiLehtinen** [comment]
Dear @edgararuiz ,

that seems to do the trick!

Thanks a lot!
Ossi

**Comment by horowitza** [comment]
The function `remote_query`, and it's counterparts, aren't imported directly into `dplyr`. Should they be?

**Comment by edgararuiz** [comment]
Hi, I believe that the `remote_...` functions are considered tools for developers, so they are more internal to `dbplyr`: https://github.com/tidyverse/dbplyr/blob/master/NEWS.md
