### ISSUE TITLE
Improve error message when a function is supplied quoted to funs()

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#3368]
See https://github.com/r-lib/rlang/issues/411:

```r
library("dplyr")
packageVersion("dplyr")
# [1] ‘0.7.4’
packageVersion("rlang")
# [1] ‘0.2.0’
mp <- c("cyl" = "cylinders", "gear" = "gears")
rename_at(.tbl = datasets::mtcars, 
          .vars = names(mp), 
          .funs = funs(function(si) { mp[si] }))
# Error: All arguments must be named 
```

**Comment by lionel-** [comment]
Or should we treat quoted functions specially? The UI of `funs()` is weird because it supports calls as in `funs(my_function(.))` and symbols as in `funs(my_function)`. The latter might suggest you should be able to pass a lambda function as well, e.g. `funs(function(x) do(x))`. It might make the UI a bit more predictable if we special-case calls to `function`.

I think ideally `funs()` would only support calls and not symbols then there would be no ambiguity. Of course this is now too late to change.

cc @JohnMount @hadley

**Comment by hadley** [comment]
I think we need to rework/replace funs with a version that does not quote, but instead accepts purrr style anonymous functions. I've been trying to teach `funs()` and it's currently just too confusing.
