### ISSUE TITLE
Error in inner_join 

### ISSUE THREAD

**Issue by hameddashti** [tidyverse/dplyr#3369]
I used inner_join function as bellow:

```r
q<- df1 %>% inner_join(df2, "chromosome") %>% 
    mutate(geneID_motif = paste(id, motif, sep = ","),
           n = if_else(position >= start & position <= end, 1, 0)) %>% 
    select(icgc_samlpe_id, geneID_motif, n) %>%
    group_by(icgc_samlpe_id, geneID_motif) %>% 
    summarise(n = sum(n)) %>%
    spread(key = geneID_motif, value = n, fill = 0)
```
then I get this error:
Error in inner_join_impl(x, y, by$x, by$y, suffix$x, suffix$y, check_na_matches(na_matches)) : 
  std::bad_alloc
What should I do?

**Comment by batpigandme** [comment]
This question might be a better fit for https://community.rstudio.com until we can determine if it's actually a bug. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer)

It's much easier to answer questions _about_ code _with_ code, so if you could include [reprex](http://reprex.tidyverse.org/) (short for **repr**oducible **ex**ample), that would help us help you.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

**Comment by romainfrancois** [comment]
@hameddashti I'm closing this for lack of a usable reprex. please resubmit with a reprex if/when you still have the problem.
