### ISSUE TITLE
filter can not use inline pull

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3374]
In the example below we can use the value of a `pull` inside a `filter`, if it is first landed in a variable.  But we can not use the `pull` directly in an filter expression.

``` r
library("dplyr")

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

db <- DBI::dbConnect(RSQLite::SQLite(),
                     ":memory:")
table <- dplyr::copy_to(db,
                        data.frame(idx = 1:5))
t2 <- dplyr::copy_to(db,
                        data.frame(idx = 1:2))


# works
vals <- pull(t2, idx)
table %>% filter(idx %in% vals)

    ## # Source:   lazy query [?? x 1]
    ## # Database: sqlite 3.19.3 [:memory:]
    ##     idx
    ##   <int>
    ## 1     1
    ## 2     2

# throws
table %>% filter(idx %in% pull(t2, idx))

    ## Error in UseMethod("escape"): no applicable method for 'escape' applied to an object of class "c('tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"

DBI::dbDisconnect(db)
```

**Comment by edgararuiz** [comment]
Hi John, that's because is assumed that `pull()` is a DB operation not a `dplyr` operation, to correct that you should be able to use `!!`, try:

```r
library(rlang)
table %>% filter(idx %in% !! pull(t2, idx))
```

**Comment by JohnMount** [comment]
Not sure. `dplyr::pull(data.frame(x =1), x)` works.  And the following works:

```r
library("dplyr")

table <- data.frame(idx = 1:5)
t2 <- data.frame(idx = 1:2)

# works
vals <- pull(t2, idx)
table %>% filter(idx %in% vals)

# works
table %>% filter(idx %in% pull(t2, idx))
```

**Comment by edgararuiz** [comment]
That's correct.  Conversely, in-memory will not support `table %>% filter(date = current_date)` but a PostgreSQL backed connection will :)

**Comment by JohnMount** [comment]
I know there is going to be variation (especially with functions).  Really all one needs to know is if the code in question is well formed or not.  And I know that is not for me to determine.

**Comment by hadley** [comment]
Within a variable expression, dbplyr can only translates vector operations, not other whole table operations. This is out of scope.
