### ISSUE TITLE
Inconsistant column names renaming with $ and []

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#3376]
Renaming columns mixing base R and tibbles create different results with $ and []:
```r
> colnames(data.frame(goodname = dplyr::tibble(badname = "test")$badname))
[1] "goodname"
> colnames(data.frame(goodname = dplyr::tibble(badname = "test")[, "badname"]))
[1] "badname"
```

For comparison, in pure base R:
```r
> colnames(data.frame(goodname = data.frame(badname = "test")$badname))
[1] "goodname"
> colnames(data.frame(goodname = data.frame(badname = "test")[, "badname"]))
[1] "goodname"
```

I did not investigate the underlying cause.
Best,
Alex

**Comment by cderv** [comment]
If we compare the inner result there is already some différences
Your second example with `[, "badname]` returns a tibble, not the content,  so you cannot be put inside a data.frame. I do not know if this is intented. I recall some questions and issues on this but I can't find it...

Some details as reprex:
``` r
# this is the content : a character vector
dplyr::tibble(badname = "test")$badname
#> [1] "test"
# this is still a tibble - all comes from this fact
dplyr::tibble(badname = "test")[, "badname"]
#> # A tibble: 1 x 1
#>   badname
#>   <chr>  
#> 1 test

# this is the content : a factor
data.frame(badname = "test")$badname
#> [1] test
#> Levels: test
# this is a content too, no more a data.frame
data.frame(badname = "test")[, "badname"]
#> [1] test
#> Levels: test
```

when you try to make those into data.frame the result is then different
because putting a tibble inside a data.frame do not result with what you expect.
You’ll get the tibble not a tibble inside a data.frame.

``` r
# goodname = a character here
data.frame(goodname = dplyr::tibble(badname = "test")$badname)
#>   goodname
#> 1     test
# goodname = a tibble, this does not work, you get the tibble as data.frame. 
# no goodname column
data.frame(goodname = dplyr::tibble(badname = "test")[, "badname"])
#>   badname
#> 1    test
```

you must use tibble and list column for that. Goodname is the column name then

``` r
dplyr::tibble(goodname = list(dplyr::tibble(badname = "test")[, "badname"]))
#> # A tibble: 1 x 1
#>   goodname        
#>   <list>          
#> 1 <tibble [1 x 1]>
```

Hope it helps.

Created on 2018-02-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by courtiol** [comment]
Thanks for this clarification.

I like very much the philosophy that in dplyr you have less surprises about the class of the returned object than in base R, but this example shows a strong exception.

In this situation should tibble[, col] not return a content instead of a tibble, so to be consistent with its parent class data.frame?

My view is that datasets prepared with dplyr should be fully compatible with R code working with data.frame. But I know that no everyone share that view.

So design choice or bug, that is the question... Either way, it creates issues for users.

Up to you guys.
All the best,
Alex

**Comment by krlmlr** [comment]
Thanks @courtiol for reaching out, and @cderv for the clarification.

Type stability for `[` in the default case is a design choice, as is the default to never convert strings to factors. For compatibility with data frames, use `[, drop = TRUE]` .

The `data.frame()` constructor tries to be smart when it sees a data frame passed as an argument, I'd argue this is part of the confusion:

``` r
colnames(data.frame(goodname = data.frame(badname = "test")[, "badname", drop = FALSE]))
#> [1] "badname"
```

> Created on 2018-02-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by courtiol** [comment]
I understand, thanks for the explanation! If it is a design choice, then there is no issue.
++
