### ISSUE TITLE
Pipe after assignment Arrow doesn't work.

### ISSUE THREAD

**Issue by wodsworth** [tidyverse/dplyr#3377]
Code:
 tibble(x = 1:100)-> tib %>% head()

Error message: 
Error in tib %>% head() <- tibble(x = 1:100) : 
  could not find function "%>%<-"

If I did tibble(x = 1:100) %>% head() -> tib 
I'd only store the head in tib.
If I did 
tibble(x = 1:100) -> tib 
tib %>% head() 

I have to repeat the tibble name I wrote into, which is sort of against the whole idea.

(Depending on how you see it, this is a bug report or feature request)

**Comment by lionel-** [comment]
This should be a report for the magrittr package, but I don't think the pipe operator should be used in this way. The `->` operator is special, it is translated by the _R parser_ (not by magrittr) from:

```r
tibble(x = 1:100) -> tib %>% head()
```

to

```r
tib %>% head() <- tibble(x = 1:100)
```

To see the translation try to type this in your console: `quote(x -> y)`. So there's basically no way for magrittr to behave the way you'd like. Note that in general we don't recommend using the rightward arrow operator.
