### ISSUE TITLE
filter date with database

### ISSUE THREAD

**Issue by xuefliang** [tidyverse/dplyr#3378]
When I use dplyr in database , filter can not execute on dttm

```r
class(child_db)
[1] "tbl_dbi"  "tbl_sql"  "tbl_lazy" "tbl"
library(lubridate)
child_db %>% filter(CHIL_BIRTHDAY==ymd_hms('2013-01-01 05:00:00'))
```

**Comment by edgararuiz** [comment]
Hi, yes, that's because there's not `lubridate` support for `dbplyr` yet.  But, depending on the database you're working with, you may be able to use the native time stamp SQL command directly inside the `filter()` verb.

**Comment by hadley** [comment]
You can also use `lubridate::` to force local evaluation of that code

``` r
library(dplyr, warn.conflicts = FALSE)

lf1 <- dbplyr::lazy_frame(date = Sys.Date(), src = dbplyr::simulate_oracle())
lf1 %>% 
  filter(date == lubridate::ymd_hms('2013-01-01 05:00:00')) %>%
  show_query()
#> <SQL> SELECT *
#> FROM (`df`) 
#> WHERE (`date` = '2013-01-01T05:00:00Z')
```

Created on 2018-05-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
