### ISSUE TITLE
Documentation: dplyr::filter note about base subsetting.

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3379]
From `help(filter)` (for `dplyr`):

> [dplyr::filter] Unlike base subsetting, rows where the condition evaluates to NA are dropped.

I believe `base::subset()` does drop rows where the condition is `NA`.

```r
library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
subset(mtcars, NA)
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 rows> (or 0-length row.names)
filter(mtcars, NA)
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 rows> (or 0-length row.names)
```

The `[ ]` operator does not drop with `NA`, but I think many readers will take "base subsetting" to mean `base::subset`.

**Comment by krlmlr** [comment]
Thanks, let's be explicit and write "base subsetting with `[`" instead.

**Comment by batpigandme** [comment]
Updated in #3457, @JohnMount and Kiril, let me know if you think it's still too ambiguous!

**Comment by krlmlr** [comment]
Looks good, thanks!

**Comment by JohnMount** [comment]
That seems enough to clear it up, thanks.
