### ISSUE TITLE
dplyr::distinct() gives different results on MS SQL backend than in-memory data frame.

### ISSUE THREAD

**Issue by thomascwells** [tidyverse/dplyr#3382]
In short, `collect()` first then `distinct()` gives different results than `distinct()` then `collect()`.
 
I don't know how to provide a reprex for database examples. Hopefully the below example demonstrating a different set of results when `distinct()` is performed in `R` vs on the database is sufficient. 

Please let me know if you need more information, and I'll try to reconstruct a reprex with public data. 

Setup: 
```r
> # dbplyr package version
> packageVersion('dbplyr')
[1] ‘1.2.1.9000’
> 
> # MS SQL Server connection
> ac_use_db
<OdbcConnection> [REDACTED]
  Database: [REDACTED]
  Microsoft SQL Server Version: 13.00.1601
> 
> # Connect to table
> my_table <- ac_use_db %>% tbl("SG_CVA_HAN_DEVICES")
> class(my_table)
[1] "tbl_dbi"  "tbl_sql"  "tbl_lazy" "tbl"     
```
Note differing row counts when the `collect()` statement is reordered. This is concerning.
```r
> # Collect then distinct
> my_table %>% 
+   collect() %>%  # <-- Collect first
+   dplyr::distinct(MAC_ADDRESS, PSEUDO_METER_ID) %>% 
+   nrow()
[1] 2411
> 
> # Distinct then collect
> my_table %>% 
+   dplyr::distinct(MAC_ADDRESS, PSEUDO_METER_ID) %>% 
+   collect() %>%  # <-- Collect after
+   nrow()
[1] 2360
```
Look at the query from the dbplyr translation. 
```r
> # Show query for distinct then collect 
> my_table %>% 
+   dplyr::distinct(MAC_ADDRESS, PSEUDO_METER_ID) %>% 
+   show_query()
<SQL>
SELECT "MAC_ADDRESS", "PSEUDO_METER_ID"
FROM "SG_CVA_HAN_DEVICES"
GROUP BY "MAC_ADDRESS", "PSEUDO_METER_ID"
```
I tried using a different formulation of the SQL query (using DISTINCT instead of GROUP BY), but it gives the same results as the GROUP BY version.
```r
> # Manually create the SQL query. This gives the correct results
> DBI::dbGetQuery(ac_use_db,
+                'SELECT DISTINCT "MAC_ADDRESS", "PSEUDO_METER_ID"
+                 FROM "SG_CVA_HAN_DEVICES"') %>% 
+   nrow()
[1] 2360
```

**Comment by thomascwells** [comment]
I also confirmed that NAs are not the issue:
```r
> my_table %>% 
+   collect() %>% 
+   select(MAC_ADDRESS, PSEUDO_METER_ID) %>% 
+   filter(is.na(MAC_ADDRESS))
# A tibble: 0 x 2
# ... with 2 variables: MAC_ADDRESS <chr>, PSEUDO_METER_ID <chr>
> my_table %>% 
+   collect() %>% 
+   select(MAC_ADDRESS, PSEUDO_METER_ID) %>% 
+   filter(is.na(PSEUDO_METER_ID))
# A tibble: 0 x 2
# ... with 2 variables: MAC_ADDRESS <chr>, PSEUDO_METER_ID <chr>
```

**Comment by thomascwells** [comment]
Ah ha! By running `anti_join` on the two different results (which contain sensitive data, so I can't share here), I found that the difference in the `distinct()` row count results stems from SQL's DISTINCT being **case-insensitive** for my table. 

This page explains it well: https://www.mssqltips.com/sqlservertip/1506/problem-using-distinct-in-case-insensitive-sql-server-databases/). 

Per the last two examples at the previous link, maybe `dbplyr` should append `COLLATE sql_latin1_general_cp1_cs_as` to the translated `SELECT` statement. Other options could be a warning about the case (in)sensitivity or a parameter to the distinct statement to adopt (or not) the case-sensitivity default of the remote table.

**Comment by hadley** [comment]
Setting up a database as case insensitive seems like a bad idea in general? Unfortunately, I don't think it's worth the additional dbplyr complexity to fix this corner case for one database system.
