### ISSUE TITLE
Postgres table creation not behaving like RPostgreSQL 

### ISSUE THREAD

**Issue by mwillumz** [tidyverse/dplyr#3389]
I need to modify the postgres connection ever so slightly to avoid a warning and undesired behavior in a greenplum database. If I don't provide a "distributed by" clause upon table creation the data is loaded according to the first column of the data provided. 

With PostgreSQL I am able to accomplish this with the first code chunk below. However, the corresponding approach does not work with the PqConnection 
class from RPostgres.

RPostgreSQL (works as expected and distributes randomly):

```r
#' @importFrom assertthat assert_that
#' @importFrom rlang is_string
#' @importFrom dbplyr build_sql as.sql
#' @export
db_create_table.PostgreSQLConnection <- function(con, table, types, temporary = TRUE, ...) {
  assertthat::assert_that(rlang::is_string(table), is.character(types))

  field_names <- escape(ident(names(types)), collapse = NULL, con = con)
  fields <- sql_vector(
    paste0(field_names, " ", types),
    parens = TRUE,
    collapse = ", ",
    con = con
  )
  sql <- dbplyr::build_sql(
    "CREATE ", if (temporary) sql("TEMPORARY "),
    "TABLE ", dbplyr::as.sql(table), " ", fields,
    " DISTRIBUTED RANDOMLY",
    con = con
  )

  DBI::dbExecute(con, sql)
}
```
RPostgres(not implemented... so uses first column for distribution as per db default):

```r
#' @importFrom assertthat assert_that
#' @importFrom rlang is_string
#' @importFrom dbplyr build_sql as.sql
#' @export
db_create_table.PqConnection <- function(con, table, types, temporary = TRUE, ...) {
  assertthat::assert_that(rlang::is_string(table), is.character(types))

  field_names <- escape(ident(names(types)), collapse = NULL, con = con)
  fields <- sql_vector(
    paste0(field_names, " ", types),
    parens = TRUE,
    collapse = ", ",
    con = con
  )
  sql <- dbplyr::build_sql(
    "CREATE ", if (temporary) sql("TEMPORARY "),
    "TABLE ", dbplyr::as.sql(table), " ", fields,
    " DISTRIBUTED RANDOMLY",
    con = con
  )

  DBI::dbExecute(con, sql)
}
```

**Comment by edgararuiz** [comment]
Hi @mwillumz , would you like to submit a Pull Request for this change?  That way you can get credit for your work.  I'll be happy to help you with it.

**Comment by mwillumz** [comment]
Hi @edgararuiz , can you take a brief look at [RGreenplum](https://github.com/mwillumz/RGreenplum)?

Ultimately I'd like to add a `distributed_by` parameter to the copy_to method. But the current repo adds the "DISTRIBUTED RANDOMLY" clause to the dbWriteTable method. (Greenplum is basically a fork of Postgresql for parallel databases). This is the key difference in the api.

I think a new backend package might be the best/only way to do this but I wanted to get your opinion on whether the way I'm doing it is the preferred approach. 

If you agree that this is the best way to go I think this issue can be closed.

**Comment by edgararuiz** [comment]
Yes, I think your approach is the correct one.  For two reasons, the first is that this not a "translation" package, most of the customization you're making sit in the intersection of `dbplyr` and `odbc`.  The second is that with your package, the end user will not need a driver because it looks like you're leveraging the `RPostgres` driver to connect.  The package is looking great by the way!
