### ISSUE TITLE
Feature Request: count to percent

### ISSUE THREAD

**Issue by mdancho84** [tidyverse/dplyr#3391]
It's fairly common to want to turn counts into percentages. In fact, since I made this function I use it all the time... Anyways, it's basically an add-on to `dplyr::count()` that takes a count column and generates percentages by group if desired. Leave empty if not by group. I use it a lot in this blog post - http://www.business-science.io/learning-r/2018/03/03/how_to_learn_R_pt1.html. Let me know if you want it. Thanks!

```
> library(tidyverse)
> 
> count_to_pct <- function(data, ..., col = n) {
+     
+     grouping_vars_expr <- quos(...)
+     col_expr <- enquo(col)
+     
+     data %>%
+         group_by(!!! grouping_vars_expr) %>%
+         mutate(pct = (!! col_expr) / sum(!! col_expr)) %>%
+         ungroup()
+ }
> 
> mtcars %>%
+     count(cyl, gear) %>%
+     count_to_pct(gear)
# A tibble: 8 x 4
    cyl  gear     n    pct
  <dbl> <dbl> <int>  <dbl>
1  4.00  3.00     1 0.0667
2  4.00  4.00     8 0.667 
3  4.00  5.00     2 0.400 
4  6.00  3.00     2 0.133 
5  6.00  4.00     4 0.333 
6  6.00  5.00     1 0.200 
7  8.00  3.00    12 0.800 
8  8.00  5.00     2 0.400 
```

**Comment by krlmlr** [comment]
@hadley: Do we want a verb that computes (weighted) percentages in a new column? I don't have anything better to offer than the suggested `count_to_pct()`.

**Comment by hadley** [comment]
I don't think that this belongs in dplyr - now that you can express this sort of function simply and elegantly using tidy eval, I expect that many dplyr extension packages will arise.
