### ISSUE TITLE
str_detect() translation for dbplyr generates reverse effect in SQL statement

### ISSUE THREAD

**Issue by leungi** [tidyverse/dplyr#3397]
**Problem**
str_detect() translation for dbplyr generates reverse effect in SQL statement.

Usage: str_detect(string, pattern)

Following the usage above, the equivalent SQL statement generated is INSTR(pattern, string ); the expected SQL statement is INSTR(string, pattern). As a workaround, I'd have to use str_detect() inversely, that is, str_detect(pattern, string) to get the desired result.

``` r

require(tidyverse)
#> Loading required package: tidyverse
require(dbplyr)
#> Loading required package: dbplyr
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

master %>% 
  filter(COUNTY_NAME == 'REEVES'
         , CURR_COMP_STATUS == 'ACTIVE'
         , str_detect('PROD', CURR_COMP_TYPE)  #'PROD' is the pattern and 'CURR_COMP_TYPE' is string
  ) %>% show_query()
#> 
<SQL>
SELECT *
FROM (MASTER) 
WHERE (("COUNTY_NAME" = 'REEVES') AND ("CURR_COMP_STATUS" = 'ACTIVE') AND (INSTR("CURR_COMP_TYPE", 'PROD') > 0))
```

Created on 2018-03-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

``` r

require(tidyverse)
#> Loading required package: tidyverse
require(dbplyr)
#> Loading required package: dbplyr
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

master %>% 
  filter(COUNTY_NAME == 'REEVES'
         , CURR_COMP_STATUS == 'ACTIVE'
         , str_detect(CURR_COMP_TYPE, 'PROD')  #'PROD' is the pattern and 'CURR_COMP_TYPE' is string
  ) %>% show_query()
#> 
<SQL>
SELECT *
FROM (MASTER) 
WHERE (("COUNTY_NAME" = 'REEVES') AND ("CURR_COMP_STATUS" = 'ACTIVE') AND (INSTR('PROD', "CURR_COMP_TYPE", ) > 0))
```

Created on 2018-03-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by edgararuiz** [comment]
Hi @leungi , does this fail when you run it against your specific database?  I ran the current code against multiple DBs successfully: https://github.com/tidyverse/dbplyr/pull/35

**Comment by leungi** [comment]
@edgararuiz, thanks for reply.
I tested against 2 Oracle servers and issue was replicated. There's no problem when querying against SQL, as expected.

**Comment by edgararuiz** [comment]
He @leungi , thank you for testing that. I'll follow up once we have a PR for the fix.  Thanks again!

**Comment by leungi** [comment]
Thanks for your work! Having stringr support is such a great utility (especially those not comfortable with regex), and I've been promoting it in house.

Hope this is not an isolated issue, so your time is well spent.
