### ISSUE TITLE
rename_all fails with odd characters - possibly smart quotes

### ISSUE THREAD

**Issue by simonthelwall** [tidyverse/dplyr#3401]
I've been trying to use rename_all to sanitise my column names. However, it fails with an error as below. 
```r
temp_dat <- structure(list(`a ‘timeline’ for patient movement` = character(0)), 
                        .Names = c("a ‘timeline’ for patient movement"), 
                        row.names = integer(0), 
                        class = c("tbl_df", "tbl", "data.frame"))
rename_all(temp_dat, funs(gsub("‘", "\\_", .)))
Error: `a ‘timeline’ for patient movement` contains unknown variables
```
I've tried to narrow it down with `debugonce(rename_all)` and everything works up to line 6 of `rename_all` which is `rename(.tbl, !(!(!syms)))`

The output I would I expect is 
```r
> temp_dat
# A tibble: 0 x 1
# ... with 1 variable: `a _timeline’ for patient movement` <chr>
```

**Comment by batpigandme** [comment]
Hi @simonthelwall,

Can you try updating to the dev version of dplyr? I just ran the code you gave above, and it seems to be working as expected `dplyr@27becad` (_i.e._ the dev version).

``` r
suppressPackageStartupMessages(library(dplyr))
temp_dat <- structure(list(`a ‘timeline’ for patient movement` = character(0)), 
                      .Names = c("a ‘timeline’ for patient movement"), 
                      row.names = integer(0), 
                      class = c("tbl_df", "tbl", "data.frame"))
temp_dat
#> # A tibble: 0 x 1
#> # ... with 1 variable: `a ‘timeline’ for patient movement` <chr>
rename_all(temp_dat, funs(gsub("‘", "\\_", .)))
#> # A tibble: 0 x 1
#> # ... with 1 variable: `a _timeline’ for patient movement` <chr>
```
Created on 2018-03-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by simonthelwall** [comment]
Thanks @batpigandme , am failing to install bindrcpp at the moment, will update once I've got that sorted.

**Comment by simonthelwall** [comment]
Perfect, yes dev version of dplyr fixes this. Thank you.
