### ISSUE TITLE
bind_rows() behaves oddly with list of vectors, but no warning or error

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/dplyr#3403]
When given a list of vectors, `bind_rows()` column binds them into a data frame. 

I would expect `bind_rows()` to row bind the vectors into a data frame with a single column, or to throw an error. I find it confusing that `bind_rows()` silently proceeds as if it were `bind_cols()` (which admittedly is probably failing in the same way: coercing the list to a data frame and then binding nothing to it.  The result happens to look like what one would expect `bind_cols()` to do).

```{r}
list_of_vecs <- list(a = c(1,1,1,1), b = c(2, 2, 2, 2), c = c(3, 3, 3, 3))
list_of_vecs %>% bind_rows()
## # A tibble: 4 x 3
##       a     b     c
##   <dbl> <dbl> <dbl>
## 1     1     2     3
## 2     1     2     3
## 3     1     2     3
## 4     1     2     3

list_of_vecs %>% bind_cols()
## # A tibble: 4 x 3
##       a     b     c
##   <dbl> <dbl> <dbl>
## 1     1     2     3
## 2     1     2     3
## 3     1     2     3
## 4     1     2     3
```
This is almost identical to #1450, but instead of asking for `bind_rows()` to work with a list of vectors (which would still be nice), I'm asking for `bind_rows()`to  _not_ work with a list of vectors in an unintuitive way.

This relates to https://github.com/tidyverse/purrr/issues/472 where the behavior appears in `map_dfr()`. The behavior seems even more confusing with `map_dfr()` because, conceptually,  `map_dfr()`is iterating through the vectors one at a time and column binding them.

**Comment by krlmlr** [comment]
Thanks, confirmed. The best we can do for this release is to give a message about auto-coercion to a data frame, and document this behavior:

``` r
library(tidyverse)
list_of_vecs <- list(a = c(1,1,1,1), b = c(2, 2, 2, 2), c = c(3, 3, 3, 3))
list_of_vecs %>% bind_rows()
#> Argument 1 to `bind_rows()` is a list of vectors, coercing to a data frame.
#> # A tibble: 4 x 3
#>       a     b     c
#>   <dbl> <dbl> <dbl>
#> 1    1.    2.    3.
#> 2    1.    2.    3.
#> 3    1.    2.    3.
#> 4    1.    2.    3.
list_of_vecs %>% as_data_frame() %>% bind_rows()
#> # A tibble: 4 x 3
#>       a     b     c
#>   <dbl> <dbl> <dbl>
#> 1    1.    2.    3.
#> 2    1.    2.    3.
#> 3    1.    2.    3.
#> 4    1.    2.    3.
```

> Created on 2018-03-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by krlmlr** [comment]
#3407 will help resolve the ambiguity here.

**Comment by krlmlr** [comment]
FWIW, the behavior is documented (emphasis mine):

> Each argument can either be a data frame, **a list that could be a data frame**, or a list of data frames.

Both `bind_rows()` and `bind_cols()` see just one argument, a data-frame-ish. If two such lists are passed, it still works:

``` r
dplyr::bind_rows(list(a = 1:2), list(a = 3:4, b = 5:6))
#> # A tibble: 4 x 2
#>       a     b
#>   <int> <int>
#> 1     1    NA
#> 2     2    NA
#> 3     3     5
#> 4     4     6
```

> Created on 2018-03-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Altering documented behavior feels more like a breaking change. I think we should consider simplifying the interface (and limiting the possible inputs) in #3407. Closing for now, happy to discuss there.
