### ISSUE TITLE
R CMD check problems

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3405]
https://cran.r-project.org/web/checks/check_results_dplyr.html

Need to replicate locally. Also, the note on four UTF-8 marked strings in the data would spoil an overall "OK" result, maybe we can convert the data to ASCII.

**Comment by JohnMount** [comment]
The checks went red right after `rlang` 0.2.0 was pushed to CRAN https://github.com/r-lib/rlang/commit/01c57762b57e05fabde66c96798d05a275832efd .

**Comment by krlmlr** [comment]
Thanks. Now testing archive/0.7.4-current with `RDsan` of https://github.com/wch/r-debug.

**Comment by krlmlr** [comment]
Got nowhere with `RDsan`, retrying tomorrow.

**Comment by krlmlr** [comment]
@lionel-: If the CRAN failures started to occur with the CRAN release of rlang 0.2.0, could this be an ABI incompatibility of sorts? Have you tried installing rlang < 0.2.0, then dplyr, then rlang 0.2.0?

**Comment by krlmlr** [comment]
@lionel-: I was confused, I don't think an ABI change causes this, because the package under test is rebuilt with R CMD check. Will look further.

**Comment by krlmlr** [comment]
Fixed in 866df05.

**Comment by wlandau** [comment]
More CRAN check errors just popped up, and they all seem to relate to tidy eval. And it's not just `dplyr`. [`drake`] is having problems too (https://github.com/ropensci/drake/issues/356), so I am very interested in finding out what is happening.

**Comment by lionel-** [comment]
@wlandau Deparsing of `!!` is now fixed in R 3.5.0, i.e. `!!x` is now deparsed to `"!!x"` instead of `"!(!x)"`. Using deparse makes unit tests dependent on the way R formats deparsed expressions and so may be brittle.

**Comment by wlandau** [comment]
So glad to hear that the deparsing of `!!` was fixed and that these errors are happening for a good reason.
