### ISSUE TITLE
Revisit inherits_from()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3406]
- avoid `set_intersection()`, prefer shortcut
- support testing inheritance from one class
- compare `CHARSXP` and not strings
- replace use of `Rf_inherits()` with calls to `inherits_from()`

**Comment by romainfrancois** [comment]
what's wrong with `Rf_inherits` ?

**Comment by krlmlr** [comment]
IIRC, `inherits_from()` is a vectorized operation.

**Comment by romainfrancois** [comment]
We no longer need that.
