### ISSUE TITLE
Add ORCIDs

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3411]
CC @lionel- @romainfrancois.

**Comment by romainfrancois** [comment]
relevant discussion here: https://github.com/r-lib/usethis/issues/108

Also perhaps either dump my email address from the DESCRIPTION or add the ones from the other authors.

**Comment by romainfrancois** [comment]
maybe that can wait until `roxygen2` knows better how to handle them. https://github.com/klutometis/roxygen/issues/721

**Comment by krlmlr** [comment]
I don't mind the formatting. It's not ideal, but then I doubt many will care. And it will be fixed when *roxygen2* is fixed.

**Comment by lionel-** [comment]
I don't have one.
