### ISSUE TITLE
Can sample_n accept n()?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#3413]
The following works for shuffling the observations in a data frame:

```r
mtcars %>% 
  sample_n( nrow(mtcars) )
```

but using `n()` doesn't

```r
mtcars %>% 
  sample_n( n() )
```

and gives the error `Error: This function should not be called directly`.

For consistency with other dplyr functions it would be nice for the latter to work as well.

**Comment by krlmlr** [comment]
Thanks. This works naturally with `sample_frac()` if the `size` argument is omitted, we could make it work for `sample_n()` (default `size = NULL` means `size = nrow(...)`). I'd rather avoid changing the behavior of `n()` here: that function works only in verbs that implement hybrid evaluation, and the documentation is explicit about it.

**Comment by romainfrancois** [comment]
`sample_*` currently don't go to the c++ side, so can't use any of the hybrids. 

Not sure what to do with this, in the meantime, here is an implementation going through `slice`:

``` r
library(dplyr)
sample_nn <- function(data, n, replace = FALSE, weight = NULL){
  n <- enquo(n)
  slice(data, sample.int(n(), !!n, replace = replace, prob = weight))
}

d <- data.frame(x = 1:10, y = rep( c("a", "b"), each = 5))

d %>% 
  sample_nn(n())
#>     x y
#> 1   8 b
#> 2   1 a
#> 3   5 a
#> 4   2 a
#> 5   6 b
#> 6   7 b
#> 7  10 b
#> 8   3 a
#> 9   9 b
#> 10  4 a

d %>% 
  group_by(y) %>% 
  sample_nn(n())
#> # A tibble: 10 x 2
#> # Groups:   y [2]
#>        x y    
#>    <int> <fct>
#>  1     4 a    
#>  2     5 a    
#>  3     3 a    
#>  4     1 a    
#>  5     2 a    
#>  6    10 b    
#>  7     9 b    
#>  8     6 b    
#>  9     8 b    
#> 10     7 b
```

Created on 2018-04-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by krlmlr** [comment]
I'm suggesting to make `sample_n()` work without passing an `n` argument, would that help?

**Comment by krlmlr** [comment]
Oh, I misread -- we can actually make that work!?

We already have `sample_n_basic()`, looks like we only need to replace the last `[` call by a `slice()`.

**Comment by romainfrancois** [comment]
I think `sample_n( n() )` visually makes sense

**Comment by krlmlr** [comment]
Agreed. Let's go for it!
