### ISSUE TITLE
Apply styler

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3415]
When this is closed, rebase your branches with

```sh
git fetch --all
git rebase origin/master -X theirs
```

assuming `origin` is the tidyverse remote.

**Comment by krlmlr** [comment]
@lionel-: Okay to remove the space after `!!!`?

**Comment by lionel-** [comment]
Only if that's how you like it :)

**Comment by krlmlr** [comment]
That's how *styler* implements this right now. Removing spaces for now, we can adapt later if we decide that there needs to be a space after `!!!`.

**Comment by lionel-** [comment]
I'd prefer not being pressed to chose a style for that operator by automatic tooling, but your call. I'm also not a fan of all the commit noise, I wish there would be a way to mark commits as trivial in git so they don't show up in history/blame by default.

**Comment by krlmlr** [comment]
Thanks, noted. Happy to delay pushes to `master`.

I don't have a strong opinion, I just want consistent coding style: https://twitter.com/krlmlr/status/973507164571623425.
