### ISSUE TITLE
The join operations causes R to crash, when tibble column names are messed up

### ISSUE THREAD

**Issue by JLYJabc** [tidyverse/dplyr#3417]
# this chunk of code gives a nice error message
```
df_a <- data.frame(A = 1:3, B = c("a", "b", "c"))
names(df_a) <- c("AA")
df_b <- data.frame(A = 2:4, C = c("aa", "bb", "cc"))
names(df_b) <- c("AA")
df_ab <- dplyr::full_join(df_a, df_b, by = "AA")
```
Error: Column 2 must be named

# wheras these lines causes R to crash
```
df_a <- tibble::tibble(A = 1:3, B = c("a", "b", "c"))
names(df_a) <- c("AA")
df_b <- tibble::tibble(A = 2:4, C = c("aa", "bb", "cc"))
names(df_b) <- c("AA")
df_ab <- dplyr::full_join(df_a, df_b, by = "AA")
```

(It also crashes with base::data.frame())

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

**Comment by JLYJabc** [comment]
I've updated the post, let me know if it is ok now?
(first time doing this)

**Comment by batpigandme** [comment]
Hi @JLYJabc,

OK, so I sent you on a bit of a goose chase, because (since it causes a crash, or, for me, an endless process), it's un-reprex-able.

So, here's a lengthy reprex, printing all but that final step (which isn't in the reprex because, well, see above).

``` r
df_a <- data.frame(A = 1:3, B = c("a", "b", "c"))
df_a
#>   A B
#> 1 1 a
#> 2 2 b
#> 3 3 c
names(df_a) <- c("AA")
df_a
#>   AA NA
#> 1  1  a
#> 2  2  b
#> 3  3  c
df_b <- data.frame(A = 2:4, C = c("aa", "bb", "cc"))
df_b
#>   A  C
#> 1 2 aa
#> 2 3 bb
#> 3 4 cc
names(df_b) <- c("AA")
df_b
#>   AA NA
#> 1  2 aa
#> 2  3 bb
#> 3  4 cc
df_ab <- dplyr::full_join(df_a, df_b, by = "AA")
#> Error: Column 2 must be named

df_a <- tibble::tibble(A = 1:3, B = c("a", "b", "c"))
names(df_a) <- c("AA")
df_a
#> # A tibble: 3 x 2
#>      AA `NA` 
#>   <int> <chr>
#> 1     1 a    
#> 2     2 b    
#> 3     3 c
df_b <- tibble::tibble(A = 2:4, C = c("aa", "bb", "cc"))
names(df_b) <- c("AA")
df_b
#> # A tibble: 3 x 2
#>      AA `NA` 
#>   <int> <chr>
#> 1     2 aa   
#> 2     3 bb   
#> 3     4 cc
```
Created on 2018-03-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

After this, the line below ⇨ wonkiness…
```r
df_ab <- dplyr::full_join(df_a, df_b, by = "AA")
```

I don't have a solution yet, just reproducing for now!

**Comment by romainfrancois** [comment]
I can reproduce the endlessness.

**Comment by romainfrancois** [comment]
➡️  https://github.com/tidyverse/dplyr/blob/master/src/join_exports.cpp#L83

**Comment by krlmlr** [comment]
I'm working on it as part of #3307.

**Comment by krlmlr** [comment]
In 0.7.4 I'm seeing *dplyr* caught in an endless loop with the original example. This means we can safely raise an error here without breaking "compatibility".
