### ISSUE TITLE
Unexpected error yield by `case_when()`

### ISSUE THREAD

**Issue by zenggyu** [tidyverse/dplyr#3422]
Sorry for any ambiguity, but I don't know how to interpret this issue in a more clear way.

`case_when()` yields an error in the following code:

```r
set.seed(1)                                                 
suppressPackageStartupMessages(library(tidyverse))          
tibble(tmp1 = sample(c(T, F), size = 32, replace = T),      
tmp2 = sample(c(T, F), size = 32, replace = T),             
tmp3 = sample(c(T, F), size = 32, replace = T)) %>%         
mutate(tmp = apply(cbind(tmp1, tmp2, tmp3), 1, function(x) {
case_when(                                                  
all(x == F) ~ "N",                                          
any(x == T) ~ "Y"                                           
)                                                           
}))                                                         
#> Error in mutate_impl(.data, dots): Evaluation error: object 'x' not found.
```

If I use `if-else` statement instead of `case_when()`, it works as expected:

```r
set.seed(1)                                                 
suppressPackageStartupMessages(library(tidyverse))          
tibble(tmp1 = sample(c(T, F), size = 32, replace = T),      
tmp2 = sample(c(T, F), size = 32, replace = T),             
tmp3 = sample(c(T, F), size = 32, replace = T)) %>%         
mutate(tmp = apply(cbind(tmp1, tmp2, tmp3), 1, function(x) {
if (all(x == F)) {                                          
"N"                                                         
} else if(any(x == T)) {                                    
"Y"                                                         
}                                                           
}))                                                         
#> # A tibble: 32 x 4
#>    tmp1  tmp2  tmp3  tmp  
#>    <lgl> <lgl> <lgl> <chr>
#>  1 T     T     F     Y    
#>  2 T     T     T     Y    
#>  3 F     F     T     Y    
#>  4 F     F     F     N    
#>  5 T     F     T     Y    
#>  6 F     T     F     Y    
#>  7 F     F     T     Y    
#>  8 F     T     F     Y    
#>  9 F     F     T     Y    
#> 10 T     F     T     Y    
#> # ... with 22 more rows
```

If I define the anonymous function outside of `apply()`, and pass that function to `apply()`, it also works as expected:

```r
set.seed(1)                                           
suppressPackageStartupMessages(library(tidyverse))    
f <- function(x) {                                    
if (all(x == F)) {                                    
"N"                                                   
} else if(any(x == T)) {                              
"Y"                                                   
}                                                     
}                                                     
tibble(tmp1 = sample(c(T, F), size = 32, replace = T),
tmp2 = sample(c(T, F), size = 32, replace = T),       
tmp3 = sample(c(T, F), size = 32, replace = T)) %>%   
mutate(tmp = apply(cbind(tmp1, tmp2, tmp3), 1, f))    
#> # A tibble: 32 x 4
#>    tmp1  tmp2  tmp3  tmp  
#>    <lgl> <lgl> <lgl> <chr>
#>  1 T     T     F     Y    
#>  2 T     T     T     Y    
#>  3 F     F     T     Y    
#>  4 F     F     F     N    
#>  5 T     F     T     Y    
#>  6 F     T     F     Y    
#>  7 F     F     T     Y    
#>  8 F     T     F     Y    
#>  9 F     F     T     Y    
#> 10 T     F     T     Y    
#> # ... with 22 more rows
```

Or, if `apply()` is called outside of `mutate()`, it also works as expected (though the output is not a data frame):

```r
set.seed(1)                                          
suppressPackageStartupMessages(library(tidyverse))   
cbind(tmp1 = sample(c(T, F), size = 32, replace = T),
tmp2 = sample(c(T, F), size = 32, replace = T),      
tmp3 = sample(c(T, F), size = 32, replace = T)) %>%  
apply(1, function(x) {                               
case_when(                                           
all(x == F) ~ "N",                                   
any(x == T) ~ "Y"                                    
)                                                    
})                                                   
#>  [1] "Y" "Y" "Y" "N" "Y" "Y" "Y" "Y" "Y" "Y" "Y" "Y" "N" "Y" "Y" "Y" "Y"
#> [18] "N" "Y" "Y" "Y" "Y" "Y" "Y" "Y" "Y" "Y" "Y" "N" "Y" "Y" "Y"
```

The behavior of the first example is inconsistent and unexpected. Is it a bug or am I missing anything?

**Comment by krlmlr** [comment]
Thanks, confirmed, also with the current dev version.

@lionel-: Why would `case_when()` fail when used in an anonymous function in `mutate()`?

``` r
library(tidyverse)
tibble(a = 1:3) %>%
  mutate(b = purrr::map_lgl(
    a,
    function(x) case_when(x < 2 ~ TRUE, TRUE ~ FALSE)
  ))
#> Error in mutate_impl(.data, dots): Evaluation error: object 'x' not found.
```

> Created on 2018-03-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by krlmlr** [comment]
Perhaps related: #3133.

**Comment by lionel-** [comment]
Does the search&replacer of the hybrid evaluator do anything with formulas?

**Comment by krlmlr** [comment]
Subsetting perhaps? That's a good hint, I'll look into it and ping you for more input if necessary.

**Comment by lionel-** [comment]
It is likely something to do with quosures. I think it's because of quosure rechaining: https://github.com/r-lib/rlang/issues/382#issuecomment-360849977

**Comment by krlmlr** [comment]
Is this related to #3019, where we found out that the environment of inner formulas is different?

**Comment by lionel-** [comment]
Oh hmm that would be a good guess. I wonder if we should use mirror environments to duplicate the data masks cheaply until we find a good solution with altrep. That's a bit naughty but should work reliably for current and past versions of R.

**Comment by krlmlr** [comment]
Mirroring environments was the only way I saw to achieve what *mockr* does: Create a view of a package namespace with the implementation of some functions changed. Let's go for it.

(I don't understand why we need to duplicate the data mask.)

ALTREP for environments still needs some time, according to the vignette. We shouldn't hold our breath for that. Another option would be objectables, they're faster only if the environments contain many symbols.

**Comment by lionel-** [comment]
> I don't understand why we need to duplicate the data mask

Because environments escaping from the mask must inherit from both the environments containing the masking data and their original lexical scope. Conceptually we need two parents. In practice we use single-parent environments so we'll have to duplicate the masks (with mirror envs then?) to get different parents at each nested quosure level.

**Comment by krlmlr** [comment]
An example would help me understand the problem ;-)

**Comment by lionel-** [comment]
I'm bad at coming up with compelling examples but hopefully this will illustrate the problem:

```r
nested_quo <- local({
  foo <- "foo"
  quo(function() paste(foo, a))
})

quo <- local({
  bar <- "bar"
  quo(list(
    !!nested_quo,
    function() paste(bar, z)
  ))
})

x <- eval_tidy(quo, set_names(letters))

x[[1]]()
#> Error in paste(foo, a) : object 'foo' not found

x[[2]]()
#> [1] "bar z"
```

In this example functions get evaluated (which is when their closure env is set) in the data mask. When the inner quosure is evaluated the data mask inherit from the inner quosure lexical env, but then it gets rechained to the outer quosure lexical env.

If we duplicate the mask and set the right parent for each quosure, we'll fix that problem. Mirror envs will make that operation cheap and also semantically correct: if an expression modifies the data mask that will be reflected in all of the mask mirrors.

**Comment by krlmlr** [comment]
I need some time to fully understand the example, but then how is mirroring environments a cheap operation? Wouldn't you need to copy (a reference to) every object in the environment.

**Comment by lionel-** [comment]
A mirror env just copies the 3 node components of the ENVSXP, see https://github.com/lionel-/rlanglabs/pull/3/

Unlike a clone it actually shares the bindings with the original env.

**Comment by lionel-** [comment]
That's a naughty use of the R API but we can replace this with ALTENV once they're usable.

**Comment by romainfrancois** [comment]
With the code

```
tibble(a = 1:3) %>% mutate(b = (function(x) case_when(x < 2 ~ TRUE, TRUE ~ FALSE))(a))
``` 

the problem seems to occur on that `Rcpp_eval` : 

```
SEXP GroupedHybridEval::eval_with_indices() {
  Call call = hybrid_call.simplify(get_indices());
  LOG_INFO << type2name(call);

  if (TYPEOF(call) == LANGSXP || TYPEOF(call) == SYMSXP) {
    LOG_VERBOSE << "performing evaluation in overscope";
    return Rcpp_eval(call, hybrid_env.get_overscope());
  }
  return call;
}
```

If I replace by `Rf_eval` I get this instead: 

```
 Error in eval_bare(f[[2]], env) : object 'x' not found 
```

**Comment by krlmlr** [comment]
I think it's the same as #3019, which probably needs a fix in *rlang*. Lionel, can you confirm?

**Comment by lionel-** [comment]
I need to investigate these issues but it looks like the same problem.

**Comment by romainfrancois** [comment]
Now getting this

```r
> tibble(a = 1:3) %>% mutate(b = (function(x) case_when(x < 2 ~ TRUE, TRUE ~ FALSE))(a))
 Show Traceback
 
 Rerun with Debug
 Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'x' not found. 
> 
> f <- function(x) case_when(x < 2 ~ TRUE, TRUE ~ FALSE)
> tibble(a = 1:3) %>% mutate(b = f(a))
# A tibble: 3 x 2
      a b    
  <int> <lgl>
1     1 TRUE 
2     2 FALSE
3     3 FALSE
```
