### ISSUE TITLE
Avoid dealing with variable names in the C++ code

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3423]
We should be using integer indices (one-based) as much as possible on the C++ side. They're faster and easier to display in the debugger. Also, we won't need to care as much about character encodings in the C++ part anymore.

**Comment by romainfrancois** [comment]
Do we still need this ?

**Comment by krlmlr** [comment]
I still think the general idea makes sense, but it's more of a principle to keep in mind than an issue to solve.
