### ISSUE TITLE
unquote fails in `bind_rows`

### ISSUE THREAD

**Issue by deeenes** [tidyverse/dplyr#3428]
When I unquote variables in any processing chain embedded in `bind_rows` it fails with various errors, depending on the context, for example:

```
`Error: `quote(var)` must resolve to integer column positions, not a symbol`
```

See more also here: https://stackoverflow.com/questions/47230211/dplyr-how-to-unquote-in-bind-rows

```r
require(dplyr)

f1 <- function(d, var){

    qvar <- enquo(var)

    d1 <- d %>% group_by(!!qvar) %>% summarize_all(first)
    d2 <- d %>% group_by(!!qvar) %>% summarize_all(first)

    bind_rows(d1, d2)

}

f2 <- function(d, var){

    qvar <- enquo(var)

    bind_rows(
        d %>%  group_by(!!qvar) %>% summarize_all(first),
        d %>%  group_by(!!qvar) %>% summarize_all(first)
    )
}

d <- data.frame(
    x = c(rep('a', 3), rep('b', 3)),
    y = seq(6)
)

f1(d, x) # works

f2(d, x) # fails
```

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can see the output as well as the code (you're almost there as is).

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

At the moment it needs to be installed from github:
```r
devtools::install_github("tidyverse/reprex")
```

**Comment by batpigandme** [comment]
You might first try updating to the dev. version of dplyr, though, as the one you've suggested should fail seems to be working with the latest version.

``` r
suppressPackageStartupMessages(library(dplyr))

f1 <- function(d, var){
  
  qvar <- enquo(var)
  
  d1 <- d %>% group_by(!!qvar) %>% summarize_all(first)
  d2 <- d %>% group_by(!!qvar) %>% summarize_all(first)
  
  bind_rows(d1, d2)
  
}

f2 <- function(d, var){
  
  qvar <- enquo(var)
  
  bind_rows(
    d %>%  group_by(!!qvar) %>% summarize_all(first),
    d %>%  group_by(!!qvar) %>% summarize_all(first)
  )
}

d <- data.frame(
  x = c(rep('a', 3), rep('b', 3)),
  y = seq(6)
)

f1(d, x) # works
#> # A tibble: 4 x 2
#>   x         y
#>   <fct> <int>
#> 1 a         1
#> 2 b         4
#> 3 a         1
#> 4 b         4

f2(d, x) # fails
#> # A tibble: 4 x 2
#>   x         y
#>   <fct> <int>
#> 1 a         1
#> 2 b         4
#> 3 a         1
#> 4 b         4
```

Created on 2018-03-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by deeenes** [comment]
Hi @batpigandme, Thank you for your reply. Actually I didn't even need the development version of dplyr only the recent one and the issue is resolved. I am very sorry for filing a bug from an old version. Also apologies for not including output in my reprex. I will update this also on Stackoverflow.

Another thing, with the new version the behavior of `!!` also has changed. Before to be completely safe I needed to write ``rlang::`!!`(var)`` because `!! var` and `(!! var)` failed in some cases. Now ``rlang::`!!`(var)`` does not work any more but `!! var` started to work. Maybe it's stupid thing, but is it possible the precedence of `::` and `!!` changed? It looks like first it unquotes `var` and then it tries to look up `var` in the `rlang` package. Anyways `!!` finally seems to work.
