### ISSUE TITLE
getting unexpected error because of exclamatory sign

### ISSUE THREAD

**Issue by danishahmadamu** [tidyverse/dplyr#3447]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the mailing list <Error: unexpected '!' in:
<regression <- colnames(newsheet[, colnames(newsheet)!= "Id" & colnames(newsheet)! = "returns" & colnames(newsheet) !="Dep" & colnames(newsheet) !="Year"])

Please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://github.com/jennybc/reprex#what-is-a-reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.  

Delete these instructions once you have read them.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

**Comment by romainfrancois** [comment]
@danishahmadamu did you get a chance to turn your question into a reprex ?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
