### ISSUE TITLE
Confusing error message across many dplyr verbs when improperly indexed

### ISSUE THREAD

**Issue by brooke-watson** [tidyverse/dplyr#3451]
(re [this Tweet](https://twitter.com/hadleywickham/status/952259891342794752))

I frequently get error messages of the following variety:

 `Error in filter_impl(.data, quo) : Result must have length 87, not 0`.

`Error in mutate_impl(.data, dots) : 
  Column `color` must be length 20 (the group size) or one, not 177`

This usually happens when I inadvertently use `df$col` instead of `col` to name a variable that I have either mutated or grouped by further up in a pipeline. 

Reprex below:  

```r
starwars <- starwars %>%
  mutate(age_bracket = case_when(
    birth_year < 21 ~ "kids",
    birth_year >= 18 & birth_year < 65 ~ "adults",
    TRUE ~ "Senior citizen discounts for Yoda & friends, woo"
  )) %>%
    filter(starwars$age_bracket == "kids")
```
```
Error in filter_impl(.data, quo) : Result must have length 87, not 4
```

It was much more common (and perplexing) when I was new to the tidyverse and accustomed to indexing variable names with `df$`.

I'm not sure what the most succinct and helpful error message would be. I like the new "Did you use %>% instead of +?" in ggplot, but I'm not sure how broad this error structure is (I've seen it for multiple dplyr verbs, and it's the same error if the df is indexed in other ways too. (e.g. `df[[14]]`). I would support "you probably have some stray `$`s in your pipeline, you Silly Billy", but I assume that's too specific. 

Thanks!

**Comment by krlmlr** [comment]
Thanks for raising this. One thing we definitely want is to show which expression causes problems with `filter()`, but we need #2605 to do that. For `mutate()`, the bad column name is given.

Accessing a data frame from an expression is a legitimate operation, but we might be able to look for `$` if an error occurs, and check if that variable is part of the data. We have to be very careful with the wording of the error message (http://style.tidyverse.org/error-messages.html#hints).

**Comment by hadley** [comment]
This now gives 

``` r
library(dplyr, warn.conflicts = FALSE)

starwars <- starwars %>%
  mutate(age_bracket = case_when(
    birth_year < 21 ~ "kids",
    birth_year >= 18 & birth_year < 65 ~ "adults",
    TRUE ~ "Senior citizen discounts for Yoda & friends, woo"
  )) %>%
    filter(starwars$age_bracket == "kids")
#> Warning: Unknown or uninitialised column: `age_bracket`.
#> Error: `filter()` argument `..1` is incorrect
#> x It must be of size 87 or 1, not size 0
```

<sup>Created on 2020-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

which I think is probably as good as we can do without starting to hit false positives.
