### ISSUE TITLE
Support for schemas using DBI::Id

### ISSUE THREAD

**Issue by etiennebr** [tidyverse/dplyr#3452]
The new `DBI::Id()` (https://github.com/r-dbi/DBI/pull/220) facilitates the usage of schemas, but it is not yet supported by `dbplyr`.

```r
library(dplyr)
library(dbplyr)

con <- DBI::dbConnect(RPostgres::Postgres())
copy_to(con, mtcars)
mt <- tbl(con, DBI::Id(table = "mtcars"))
#> Error in UseMethod("as.sql"): no applicable method for 'as.sql' applied to an object of class "Id"
```

**Comment by edgararuiz** [comment]
Hi, why wouldn't using `in_schema()` be sufficient for your use case?

**Comment by etiennebr** [comment]
It is indeed sufficient for my use case (`PostgreSQL`). I plan to test other databases and I might be anticipating, but I understand from [DBI#220](https://github.com/r-dbi/DBI/pull/220) that `DBI:Id` is more robust to the multiple ways of naming tables and namespaces (for instance to handle `database.schema.table`).

I'll re-open the issue if I meet the limitation of `in_schema()`.
