### ISSUE TITLE
filter issue

### ISSUE THREAD

**Issue by wenbostar** [tidyverse/dplyr#3455]
```r
df <- data.frame(x=1:3, y = 3:1)
var_name <- "x"

## It works.
df %>% dplyr::select(var_name) 
```
>  x
>1 1
>2 2
>3 3

```r
## It works.
df %>% dplyr::select(!!var_name)
```
>  x
>1 1
>2 2
>3 3

However, the following code doesn't work as expected.
```r
df %>% filter( (!!var_name) ==1 )
```
>[1] x y
><0 rows> (or 0-length row.names)

What is the best way to use variable when using filter?

**Comment by batpigandme** [comment]
This is an example of when you need to use `quo()` and not actual quotation marks as you have, above.

I use `quo()` below to inspect the dplyr calls before executing them as done in the [vignette here](http://dplyr.tidyverse.org/articles/programming.html#quasiquotation). In the bottom example, when I use `var_name <- quo(x)`, it returns the result you would expect (I believe) from your example above.

``` r
suppressPackageStartupMessages(library(tidyverse))
df <- data.frame(x=1:3, y = 3:1)
var_name <- "x"
quo(filter(df, !! var_name == 1))
#> <quosure>
#>   expr: ^filter(df, "x" == 1)
#>   env:  global
filter(df, !! var_name == 1)
#> [1] x y
#> <0 rows> (or 0-length row.names)

df <- data.frame(x=1:3, y = 3:1)
var_name <- quo(x)
quo(filter(df, !! var_name == 1))
#> <quosure>
#>   expr: ^filter(df, (^x) == 1)
#>   env:  global
filter(df, !! var_name == 1)
#>   x y
#> 1 1 3
```
Created on 2018-03-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
_n.b. this also works fine with the piped syntax, I just followed the conventions used in the vignette in the reprex above_
``` r
suppressPackageStartupMessages(library(tidyverse))

df <- data.frame(x=1:3, y = 3:1)
var_name <- quo(x)
quo(filter(df, !! var_name == 1))
#> <quosure>
#>   expr: ^filter(df, (^x) == 1)
#>   env:  global
df %>%
  filter(!! var_name == 1)
#>   x y
#> 1 1 3
```
Created on 2018-03-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by wenbostar** [comment]
I though it's related to tidyr package. I can ask it over here:  https://community.rstudio.com.

**Comment by batpigandme** [comment]
Yep. The GitHub-repo issues is really more for bugs and/or feature requests.
