### ISSUE TITLE
At windows7, read_csv() keeps encoding of multibites colnames and select() can't treat it with unquoted expressions.

### ISSUE THREAD

**Issue by cuttlefish44** [tidyverse/dplyr#3467]
Thank you for your works.

At windows 7, when colnames (1st row of csv file) are Japanese, read_csv() keeps the encoding and select(), pull(), ..., can't treat them with unquoted expressions.
I wonder this problem is made by read_csv(') or select(), but in any case I feel this is a bug.

Below is an example code (I can't show the output of reprex because of Garbled, sorry):

```
library(tidyverse)
data_frame(てすと = 1:5, test = 1:5) %>% write_csv("test.csv")

d1 <- read_csv("test.csv", locale = locale(encoding = "utf-8"))
d2 <- read.csv("test.csv", fileEncoding = "utf-8")

list(d1, d2) %>% map(~ Encoding(names(.)))
# [[1]]
# [1] "UTF-8"   "unknown"
# [[2]]
# [1] "unknown" "unknown"

d1 %>% select(てすと)    # Error in FUN(X[[i]], ...) : object 'てすと' not found

d1 %>% select("てすと")  # work
d1 %>% select(test)      # work
d2 %>% select(てすと)    # work
```

**Comment by cuttlefish44** [comment]
I reprinted this issue into dplyr git.

**Comment by batpigandme** [comment]
Hi,

I see you closed this same issue in the readr repo:
https://github.com/tidyverse/readr/issues/815
> Because no one have interests, I closed this issue and reprinted it into dplyr git.

As described in the [tidyverse contribute](https://www.tidyverse.org/contribute/) page, the _development of tidyverse packages tends to be very bursty_; i.e. the solution won't come faster for its being filed in the dplyr repo. If you think it's definitely an issue in dplyr (though select is actually powered by the [tidyselect](https://github.com/tidyverse/tidyselect) package), then this is the right place, but if it's a readr issue, I'd suggest reopening the issue there, and closing this one.

Either way, here's a reprex of the code above, as you can see, I was not able to reproduce your error, so you might try updating to the development versions of dplyr/readr:
``` r
library(tidyverse)
data_frame(てすと = 1:5, test = 1:5) %>% write_csv("test.csv")
d1 <- read_csv("test.csv", locale = locale(encoding = "utf-8"))
#> Parsed with column specification:
#> cols(
#>   てすと = col_double(),
#>   test = col_double()
#> )
d2 <- read.csv("test.csv", fileEncoding = "utf-8")

list(d1, d2) %>% map(~ Encoding(names(.)))
#> [[1]]
#> [1] "UTF-8"   "unknown"
#> 
#> [[2]]
#> [1] "unknown" "unknown"

d1 %>% select(てすと)
#> # A tibble: 5 x 1
#>   てすと
#>    <dbl>
#> 1     1.
#> 2     2.
#> 3     3.
#> 4     4.
#> 5     5.
d1 %>% select("てすと")  # work
#> # A tibble: 5 x 1
#>   てすと
#>    <dbl>
#> 1     1.
#> 2     2.
#> 3     3.
#> 4     4.
#> 5     5.
d1 %>% select(test)      # work
#> # A tibble: 5 x 1
#>    test
#>   <dbl>
#> 1    1.
#> 2    2.
#> 3    3.
#> 4    4.
#> 5    5.
d2 %>% select(てすと)    # work
#>   てすと
#> 1      1
#> 2      2
#> 3      3
#> 4      4
#> 5      5
```
Created on 2018-03-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by cuttlefish44** [comment]
You're right. I followed your advice. 
Thank you for your comment.
