### ISSUE TITLE
Joins lose custom attributes

### ISSUE THREAD

**Issue by msberends** [tidyverse/dplyr#3468]
Much like #3259, the join functions also lose custom attributes. We use attributes to save the query to the object it produced:
```r
my_get_data_function <- function(query) {
  data <- db_function_to_connect_and_collect_and_so_forth(sql(query))
  attr(data, "qry") <- sql(query)
  data
}
qry <- function(object) {
  q <- attributes(object)$qry
  if (!is.null(q)) {
    q
  } else {
    cat("No query found.\n")
  }
}
```

So, for example with `dplyr` data:
```r
library(dplyr)
attributes(band_members)
# $names
# [1] "name" "band"
# 
# $class
# [1] "tbl_df"     "tbl"        "data.frame"
# 
# $row.names
# [1] 1 2 3

# save this attributes to this dataset:
attr(band_members, 'qry') <- sql("SELECT * FROM tbl1")
attributes(band_members)
# $names
# [1] "name" "band"
# 
# $class
# [1] "tbl_df"     "tbl"        "data.frame"
# 
# $row.names
# [1] 1 2 3
# 
# $qry
# <SQL> SELECT * FROM tbl1

# and here it vanishes:
band_members %>% left_join(band_instruments) %>% attributes()
# Joining, by = "name"
# $class
# [1] "tbl_df"     "tbl"        "data.frame"
# 
# $row.names
# [1] 1 2 3
# 
# $names
# [1] "name"  "band"  "plays"
```

Is this intended? Especially for `left_join`, we would like to keep the attributes of `x`.

**Comment by batpigandme** [comment]
I think this probably can be one issue with  #3259, but I'll let a second set of eyes come across it to decide first.

Thanks for filing.

**Comment by krlmlr** [comment]
Thanks. Yes, currently you can't rely on attributes being preserved. We're working on it, but the attributes of an object will be preserved only if it is a subclass of `data.frame` or `tbl_df`.

Currently, the safest way is to implement a custom S3 class and methods for that class.
