### ISSUE TITLE
  BLAS/LAPACK routine 'DLASCL' gave error code -4 in R

### ISSUE THREAD

**Issue by Sidt1** [tidyverse/dplyr#3469]
Hi

I am novice w.r.to R, Can any one help me to understand about this error in R. Below is the code and error I get

ABC.SVD<-irlba(ABC.TFIDF, n = 300,  maxit = 600)
Error in ABC.SVD<-irlba(ABC.TFIDF, n = 300,  maxit = 600) : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4

**Comment by batpigandme** [comment]
Are you using the dplyr package?

This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (However, you'll want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer, without a reproducible example it's nigh impossible to say what's gone wrong.)
