### ISSUE TITLE
case_when is inefficient

### ISSUE THREAD

**Issue by jgellar** [tidyverse/dplyr#3475]
As currently constructed, `case_when` is inefficient. First it evaluates the RHS of each of the formulas, then it picks the one to actually return based on the LHS. If the code on the RHS for some of the options takes awhile to evaluate, this will be much slower than necessary, and much slower than using if/if else logic.

It seems trivial to change the implementation so that the LHS is evaluated first, and the RHS is only evaluated for the one case that the function will return.

Compare:

```
t0 <- Sys.time()
res <- case_when(TRUE  ~ "A",
                 FALSE ~ {Sys.sleep(5); "B"})
t1 <- Sys.time()
res <- if (TRUE) "A" else if (FALSE) {Sys.sleep(5); "B"}
t2 <- Sys.time()

t1 - t0
t2 - t1
```

The former takes 5 unnecessary seconds.

**Comment by krlmlr** [comment]
Thanks. How do you suggest we should deal with expressions of length > 1 on either the LHS or the RHS?

**Comment by jgellar** [comment]
I don't follow what the problem is.

I haven't looked too deeply into your implementation, but here's some quick pseudocode that I should work:

```
status <- FALSE
i <- 0
while(!status & (i < length(lhs))) {
  i <- i + 1
  status <- eval(lhs[[i]])
}
if (status) {
  eval(rhs[[i]])
} else {
  # do whatever you want to do if there are no TRUE conditions
}
```

**Comment by jgellar** [comment]
could you give an example of how the formula would have an expression of length > 1 on either side?

**Comment by krlmlr** [comment]
```r
case_when(
  1:10 > 4 ~ 5,
  TRUE ~ 10:1
)
```

**Comment by hadley** [comment]
I don't think it's possible to lazily evaluate and support vectorised expressions.

**Comment by jgellar** [comment]
How about if you only evaluate the LHS of the formulas? The RHS is typically where the heaviest computation could be. You wouldn't be able to check that everything on the RHS is the correct length/type, but I think it's okay to leave this burden on the user.

Once you determine which of the LHS expressions are TRUE, you only need to evaluate those on the RHS that are necessary. At that point you can do length/type checks on the evaluated expressions.

**Comment by jgellar** [comment]
This seems to work:

```
case_when2 <- function (...) {
  formulas <- dots_list(...)
  n <- length(formulas)
  if (n == 0) {
    abort("No cases provided")
  }
  
  query <- vector("list", n)
  for (i in seq_len(n)) {
    f <- formulas[[i]]
    if (!inherits(f, "formula") || length(f) != 3) {
      non_formula_arg <- substitute(list(...))[[i + 1]]
      header <- glue("Case {i} ({deparsed})", deparsed = fmt_obj1(deparse_trunc(non_formula_arg)))
      glubort(header, "must be a two-sided formula, not a {type_of(f)}")
    }
    env <- environment(f)
    query[[i]] <- eval_bare(f[[2]], env)
    if (!is.logical(query[[i]])) {
      header <- glue("LHS of case {i} ({deparsed})", deparsed = fmt_obj1(deparse_trunc(f_lhs(f))))
      glubort(header, "must be a logical, not {type_of(query[[i]])}")
    }
    # value[[i]] <- eval_bare(f[[3]], env)
  }
  lhs_lengths <- map_int(query, length)
  all_lengths <- unique(lhs_lengths)
  if (length(all_lengths) <= 1) {
    m <- all_lengths[[1]]
  } else {
    non_atomic_lengths <- all_lengths[all_lengths != 1]
    m <- non_atomic_lengths[[1]]
    if (length(non_atomic_lengths) > 1) {
      inconsistent_lengths <- non_atomic_lengths[-1]
      lhs_problems <- lhs_lengths %in% inconsistent_lengths
      bad_calls(formulas[lhs_problems],
                check_length_val(inconsistent_lengths,  m, header = NULL,
                                 .abort = identity))
    }
  }
  
  query <- lapply(query, function(q) {
    if (length(q) == 1) rep(q, m) else q
  })
  which_rhs <- apply(do.call("cbind", query), 1, which.max)
  
  value <- vector("list", n)
  for (i in unique(which_rhs)) {
    f <- formulas[[i]]
    v <- eval_bare(f[[3]], environment(f))
    if (length(v) == 1) {
      v <- rep(v, m)
    } else if (length(v) != m) {
      stop("length mismatch between LHS and at least one expression on RHS")
    }
    value[[i]] <- v
  }
  
  out <- value[[1]][rep(NA_integer_, m)]
  for (i in unique(which_rhs)) {
    out <- replace_with(out, which_rhs == i, value[[i]], NULL)
  }
  out
}
```

**Comment by krlmlr** [comment]
I'm not even sure I understand the original problem. The `if () ... else () ...` construct is perfectly fine if all your conditions are of length one and you want to evaluate only one branch. Can you please describe your use case?

**Comment by jgellar** [comment]
Sure, I can use if/else for my use case, so for my use case this isn't a problem. The reason I would prefer `case_when` is for conciseness of the code and for readability. In general though, I wanted to point out that `case_when` is performing a lot of unnecessary computation, evaluating expressions that will never be used, and if those evaluations take time to evaluate it will be slower than it has to be. It's your package, so it's up to you what you want to do with this.

**Comment by hadley** [comment]
I'm reasonable certain your analysis is incorrect - I did think this through when writing the function and concluded that it would break other desirable properties.
