### ISSUE TITLE
Document how scoped verbs interact with grouping variables

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3480]
A `select_if()` should give a message if the criteria don't include the grouping variables. There should be a straightforward declarative way to turn off this message, e.g. via `vars(one_of(group_vars()))`. Currently no message (both 0.7.4 and devel):

``` r
library(tidyverse)
tibble(a = 1:2, b = 1) %>% 
  group_by(b) %>% 
  select_if(is.integer)
#> # A tibble: 2 x 2
#> # Groups:   b [1]
#>       b     a
#>   <dbl> <int>
#> 1    1.     1
#> 2    1.     2
```

> Created on 2018-04-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

https://github.com/tidyverse/dplyr/pull/3409#discussion_r179595688

**Comment by romainfrancois** [comment]
A message like this ? 

```
> tibble(a = 1:2, b = 1) %>% 
+     group_by(b) %>% 
+     select(a)
Adding missing grouping variables: `b`
# A tibble: 2 x 2
# Groups:   b [1]
      b     a
  <dbl> <int>
1    1.     1
2    1.     2
```

**Comment by krlmlr** [comment]
Yes, but the message should include a hint on how to turn it off, similarly to the message when joining and omitting `by`.

**Comment by romainfrancois** [comment]
🤔 I'm not sure how to express this in an `_if` predicate 

```
tibble(a = 1:2, b = 1) %>% 
  group_by(b) %>% 
  select_if(is.integer)
```

How would we suggest to change `is.integer` so that it catches `a` ?

**Comment by hadley** [comment]
I think we should just document that `select_if()` always includes the grouping variables.

**Comment by hadley** [comment]
Let's start by adding a new section "@section Grouping variables` to the documentation for the colwise helpers that describes what we currently do with a brief motivation.
