### ISSUE TITLE
Dynamically filtering my data using Selectinput

### ISSUE THREAD

**Issue by saberbouabid** [tidyverse/dplyr#3485]
Hi , 
I am working on a shiny app and i try to filter dynamically my data-set. I have three **Selectinput** and i try to make reactive subset using these parameters to **drill-down** through my data.

But this code is not working as expected and i try to figure out what is exactly  my mistake 

```r
  observe({
    constituencies  <- if (is.null(input$election)) character(0) else {
      filter(dataset, ELECTION_FR %in% input$election) %>%
        `$`('CONSTITUENCY_AR') %>%
        unique() %>%
        sort()
    }
    stillSelected <- isolate(input$constituency[input$constituency %in% constituencies ])
    updateSelectInput(session, "constituency", choices = c("All states"="",constituencies ),
label =" constituency :"  , selected = stillSelected)
  })
  

  
  observe({
      cities <- if (is.null(input$election)) character(0) else {
        dataset %>%
          filter(ELECTION_FR %in% input$election,
                 is.null(input$constituency) | CONSTITUENCY_AR %in% input$constituency) %>%
          `$`('DELEGATION_AR') %>%
          unique() %>% 
          sort()
      }
      
    stillSelected <- isolate(input$delegation[input$delegation %in% cities])
    updateSelectInput(session, "delegation", choices = c("All states"="",cities),label = "City :"
                      selected = stillSelected)
  })
  
  
  dataelec <- reactive({
        dataset %>%
      filter( ELECTION_FR %in% input$election,
        is.null(input$constituency) | CONSTITUENCY_FR %in% input$constituency,
        is.null(input$delegation) | DELEGATION_FR %in% input$delegation
       )})
  
```

I will be thankful if someone help me to understand this issue .
Best,
Saber

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by saberbouabid** [comment]
I posted this issue here because i think there is bug related to ``dplyr::filter``. It seems that ``is.null()`` don't work for some reason .
I found this issue (#2940) and it was pretty helpful 
Anyway thanks for closing this issue .
I replaced ``is.null()`` by ``==""`` and everything works fine
