### ISSUE TITLE
Caution of the classes deriving from SlicingIndex

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3488]
Do they need the extra care about indices, e.g. 

```
class NaturalSlicingIndex : public SlicingIndex {
... 
virtual int operator[](int i) const {
    if (i < 0 || i >= n)
      stop("Out of bounds index %d queried for NaturalSlicingIndex", i);
    return i;
  }
...
}
```

I understand what this is about, but are we not in control of these indices ?
It feels expensive to do these bounds check all the time

**Comment by romainfrancois** [comment]
They were added in this commit @krlmlr https://github.com/tidyverse/dplyr/commit/56fd9b0416300e955ed58ccdeef39ee8be31a4ab

and I don't see tests associated with it, so I'm just wondering if this is being expensively extra cautious

**Comment by krlmlr** [comment]
How expensive are these checks?

**Comment by romainfrancois** [comment]
This would be hard to measure I guess. How useful are they ? If they are useful, there should be tests about them right ?

**Comment by krlmlr** [comment]
They aren't useful up to the point when they are. Remember, there is only one kind of error in programming -- accessing a stale cache, and off-by-one errors. And in that (or any other faulty) case I'd rather see an error message in a bug report than a segmentation fault.

So, unless it turns out that the bounds checks really kill the performance, I'd suggest we keep them in. I'm happy with making them conditional on a preprocessor define, but the default should be on.

**Comment by romainfrancois** [comment]
I'd like to see tests with these messages in `expect_error`. 

In C++, you typically only want to pay for what is really used. I'll make my case with benchmarks then.

**Comment by romainfrancois** [comment]
btw, things like this were removed from Rcpp. 
https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/Vector.h#L339

**Comment by romainfrancois** [comment]
I'm also interested in the cost of virtual for things that are very often called.

**Comment by romainfrancois** [comment]
`operator[]` is fine. I'm just concerned about losing performance edge by doing unnecessary things. 
Having bounds checks "just in case" and not backing it with tests triggers my radar.

**Comment by krlmlr** [comment]
Do you think the bounds check should live further downstream in the processing?

**Comment by krlmlr** [comment]
A bounds check may be more useful when we're actually accessing a data frame row. I agree it's unnecessarily expensive if done for every column, but once per row should be fine -- there are many other places where much more time is spent.

We still might get invalid `group_indices`, perhaps through a hard-to-catch aliasing mistake (forgetting to duplicate an `SEXP`). I don't see how we could possibly guarantee that slicing indices are always valid.
