### ISSUE TITLE
group_indices on rowwise data

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3491]
```r
> group_indices(rowwise(data.frame(x = 1:10)))
 [1] 1 1 1 1 1 1 1 1 1 1
```

**Comment by romainfrancois** [comment]
With the code in the #3490 pr, I get this with the `group_indices()` within `mutate`: 

```
> mutate(rowwise(data.frame(x = 1:10)), g = group_indices() )
Source: local data frame [10 x 2]
Groups: <by row>

# A tibble: 10 x 2
       x     g
   <int> <int>
 1     1     1
 2     2     2
 3     3     3
 4     4     4
 5     5     5
 6     6     6
 7     7     7
 8     8     8
 9     9     9
10    10    10
```

**Comment by romainfrancois** [comment]
Fixed in https://github.com/tidyverse/dplyr/pull/3490/commits/bd8484e0bbe27261cdf2d20d3d5067a062fb33ad

**Comment by hadley** [comment]
In general, I don't think we should be making changes to `rowwise()`.

**Comment by romainfrancois** [comment]
yes. the way rowwise is done needs too much code. 
Starting to think about these things as part of #3489 and how we structure the meta data in various groupings. 

Separating rowwise and grouped_df does not buy that much
