### ISSUE TITLE
n_distinct not counting negative integer64 values

### ISSUE THREAD

**Issue by alexiglaser** [tidyverse/dplyr#3496]
I've been using dplyr to aggregate some info from a database. Some of the columns are being read in as integer64, and some of these are negative. I'm finding that n_distinct counts all negative integer64 numbers as a single number.

A minimal example is as follows, with the expected answer being 41, but n_distinct gives us 22:
```r
> library(bit64)
> library(dplyr)
> x = as.integer64(-20:20 * 10^9)
> n_distinct(x)
[1] 22
> length(unique(x))
[1] 41
```

An example using only negative numbers is as follows:
```r
> x = as.integer64(-20:-1 * 10^9)
> n_distinct(x)
[1] 1
> length(unique(x))
[1] 20
```

**Comment by batpigandme** [comment]
I believe this is fixed in the dev version. Can you try updating and see if this works for you?
```r
devtools::install_github("tidyverse/dplyr")
```

``` r
suppressPackageStartupMessages(library(bit64))
suppressPackageStartupMessages(library(dplyr))
x <- as.integer64(-20:20 * 10^9)
n_distinct(x)
#> [1] 41
length(unique(x))
#> [1] 41

x <- as.integer64(-20:-1 * 10^9)
n_distinct(x)
#> [1] 20
length(unique(x))
#> [1] 20
```
Created on 2018-04-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by alexiglaser** [comment]
Unfortunately I cannot install via devtools (work restrictions), but that looks like it has been fixed.

**Comment by batpigandme** [comment]
Sounds good. I'll close then!
