### ISSUE TITLE
only extract the relevant boost headers 

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3497]
We don't need all of BH. just hash maps and shared pointers.

**Comment by romainfrancois** [comment]
What BH does to extract all these headers, we can do the same to extract the things we need.

**Comment by krlmlr** [comment]
We do gain a bit of independence, but I'm not sure the extra effort of maintaining the extract is worth it. Also, I'm not convinced that this will solve the original "noisy headers" problem.

**Comment by hadley** [comment]
It is necessary for other reasons - bh is a huge dependency and slow to install on many OSes (because it contains >20,000 files)

**Comment by coatless** [comment]
At the same time, other packages do use `BH`. So, by creating another package that moves away from `BH` -- but is in essence a skinner clone -- the larger _R_ community is ill-served as it now has work duplication and doubled storage cost. I think a better part of valor here would be a diaspora of `BH` headers into smaller more _concise_ packages in a manner similar to `assertive`.

**Comment by hadley** [comment]
@coatless We work on many packages in service to the broader R community but in this case we have a need for a lighter-weight BH replacement, on a short time scale. If someone split BH up into independent fragments and got it onto CRAN soon, we’d be very interested in that!

**Comment by coatless** [comment]
@hadley "short time scale" would be about a week or are we talking days? A week should be okay.

**Comment by hadley** [comment]
A couple of weeks probably

**Comment by coatless** [comment]
So, I've had some time to sit down sketch out different scenarios as well as discuss it with the maintainer of `BH`. Unfortunately, I think splitting apart BH into individual units might be a bit more complex than anticipated. The split is a bit problematic due to:

1. library dependency 
     - view dependency graph with https://www.boost.org/doc/libs/1_67_0/tools/bcp/doc/html/index.html
     - breaking down libraries to an atomic form is not likely.
1. requires more than one directory target under `LinkingTo`.
     - fundamental this means that the `BH` package would cease being useful.

So, likely, a clean break is the best... I'll try to think a bit more on this and post a response on Friday if my thoughts change.

**Comment by romainfrancois** [comment]
Because we plan to do hashing based on `vctrs` in 0.9.0, we'll most likely stop using boost anyway. So closing this.
