### ISSUE TITLE
Non-hybrid first() and last() fail if dplyr is not attached

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3498]
``` r
library(magrittr)
tibble::tibble(a = 1:3) %>% dplyr::summarise(a = dplyr::first(.data$a))
#> Error in summarise_impl(.data, dots): Evaluation error: could not find function "nth".
```

> Created on 2018-04-11 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

I think this is due to how `firstlast_prototype()` is implemented. Several downstream packages fail because of this.

The other question is why hybrid doesn't work here. Would a handler for `$` that looks for a `.data` LHS be sufficient here?

@romainfrancois: Could you please take a look? I'll rerun revdepchecks when this is fixed.

**Comment by romainfrancois** [comment]
Using `callr` to run code with dplyr not loaded: 

```
test_that("first() and last() can be called without dplyr loaded (#3498)", {
  skip_if_not_installed("callr")
  df <- callr::r( function(){
    dplyr::summarise( tibble::tibble(a = 1:3), first = dplyr::first(.data$a), last = dplyr::last(.data$a) )
  })
  expect_equal( df$first, 1L)
  expect_equal( df$last, 3L)
})
```
