### ISSUE TITLE
An unexpected `select` output ?

### ISSUE THREAD

**Issue by VincentGuyader** [tidyverse/dplyr#3499]
Shouldn't both code below return the same résult ?

```r
iris %>% 
  .[c("Species","Species")] %>%
  setNames(c("a","b"))
```

```r
iris%>% select(a=Species,b=Species)
```

the `select` version return only the `b` variable

Regards

**Comment by lionel-** [comment]
Indeed this is a tidyselect issue.

**Comment by romainfrancois** [comment]
I promoted this as a tidy select issue: https://github.com/tidyverse/tidyselect/issues/59
