### ISSUE TITLE
Simplify generated sql

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#35]
By recognising that from can be:
- table name
- join
- select

And when it's a table name or a join, you can omit a layer of selects.

**Comment by russellpierce** [comment]
I know this is a very old issue at this point, but I couldn't find the contemporary version of it.

I wonder if `filter()` might be an easy win for this - at least visually if not from a performance standpoint.  Right now comma separated filter commands are processed one subquery per filter.  But, in abstract each comma seperated filter is an AND in the same WHERE clause for dbplyr.

**Comment by hadley** [comment]
@russellpierce that's not my understanding of what the generated SQL would look like, so could you please create a new issue with a small reprex (using SQLite + show_query())
