### ISSUE TITLE
Unpredictable handling of attributes

### ISSUE THREAD

**Issue by renlund** [tidyverse/dplyr#3507]
I'm wondering about the behaviour of attributes in dplyr. It is sometimes nice to be able to assign an attribute, e.g. 'label', to a variable when it is being defined. However, these attributes sometimes vanish.
In the exampel below, attributes assigned within `data_frame` and `mutate` are kept, but not within the `group_by` and `mutate` combination. 

```r
require(dplyr)
data_frame(x = 1:4 %>% structure(label = 'Id')) %>%
    mutate(gr = rep(letters[1:2], 2) %>% structure(label = 'Group')) %>%
    group_by(gr) %>%
    mutate(z = mean(x) %>% structure(label = 'Mean x, by Group')) %>%
    ungroup() %>%
    str()
## Classes 'tbl_df', 'tbl' and 'data.frame':	4 obs. of  3 variables:
##  $ x : atomic  1 2 3 4
##   ..- attr(*, "label")= chr "Id"
##  $ gr: atomic  a b a b
##   ..- attr(*, "label")= chr "Group"
##  $ z : num  2 3 2 3
```

I know there have been related issues with attributes (e.g. #1984 and #2752).

**Comment by romainfrancois** [comment]
In that example the code `mean(x) %>% structure(label = 'Mean x, by Group')` would be executed once per group. Conceptually you'd end up with something like this: 

``` r

library(tidyverse)

d <- data_frame(x = 1:4 %>% structure(label = 'Id')) %>%
  mutate(gr = rep(letters[1:2], 2) %>% structure(label = 'Group')) %>%
  group_by(gr)

summarise(d, x = list(x) ) %>% 
  pull(x) %>% 
  map( ~ structure(rep(mean(.x), length(.x)), label='Mean x, by Group' ) )
#> [[1]]
#> [1] 2 2
#> attr(,"label")
#> [1] "Mean x, by Group"
#> 
#> [[2]]
#> [1] 3 3
#> attr(,"label")
#> [1] "Mean x, by Group"
```

It is not clear what that means to combine those attributes.

**Comment by renlund** [comment]
Right, that makes sense. In my mind the attribute 'label' is just a constant, but the general case could have it varying with the grouping variable, in which case it is much more unclear what that would mean. Thanks for taking the time to answer this.
