### ISSUE TITLE
Don't support overriding n() for now

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3508]
Earlier, there was no way to use `n()` in a package and pass `R CMD check` because *dplyr* wasn't exporting `n()`:

> older dplyr did not export `n()`, so other packages needed a biding to avoid CRAN issues (https://github.com/tidyverse/dplyr/issues/3500#issue-313527497)

Currently, only two CRAN packages are affected, but I'd like to suggest to stop using `n()` from the user's environment for now, show a message to that effect, and change this later.

**Comment by romainfrancois** [comment]
Can't we just ask these packages to remove their `n` function ?

**Comment by krlmlr** [comment]
I think so, one already did.
