### ISSUE TITLE
Support R 3.1 again

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3509]
`R_DoubleColonSymbol` isn't available there, earlier I suggested to @romainfrancois to use it. I do wonder which tests will fail.

It seems worthwhile to use R 3.1 as development environment to avoid these problems in the future. What's a good way to set up a parallel R installation so that it's used on the command line and by RStudio? Maybe a `bash` script that patches `$PATH`, and a local `.Rprofile` that checks the R version?

**Comment by romainfrancois** [comment]
Why is it not a travis thing ?

**Comment by romainfrancois** [comment]
Thanks. So I'd rather trust travis then. This will only be a problem occasionally.
