### ISSUE TITLE
Better tracebacks

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3510]
When a complex expression inside `mutate()` or most other verbs fails, the traceback is not informative:

``` r
library(tidyverse)
f <- function(x) if (x < 3) 5 else g()
g <- function() stop("oops")
tibble(a = 1:10) %>% group_by(a) %>% mutate(b = f(a))
#> Error in mutate_impl(.data, dots): Evaluation error: oops.
```

> Created on 2018-04-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

It does contain the error message, but not the location. I wonder if the traceback can be made available.

If not, we could fix this by creating unrolled optimized R code in the C++ part, which then is passed to the R evaluator, and then transforming the results in C++ again:

```r
mutate <- function(.data, ...) {
  code <- unroll_mutate(.data, !!!quos(...))
  res <- eval(code)
  apply_mutate(.data, res)
}
```

**Comment by romainfrancois** [comment]
Sounds like this could be an `r-lib` project in its own.

**Comment by krlmlr** [comment]
Maybe if we `try {} catch {}` at the C++ level? Is there a way to do Go-style evaluation in *Rcpp*, returning the result or an exception?

**Comment by romainfrancois** [comment]
For now, we will replace this by #3662
