### ISSUE TITLE
`dplyr::arrange` does not return same class object as promised

### ISSUE THREAD

**Issue by stufield** [tidyverse/dplyr#3523]
I'm debugging an issue that came up with `dplyr::arrange` when a unique object class is passed, the object is recast as a data frame in the returned object. I am surprised not to find anyone else with this issue, perhaps few of you are recasting their data frames or tibbles to unique object classes as I have. In the `?arrange`, it says that the returned object *should* be the same class as the input argument `.data`. While this is true for class `data.frame` and class `tbl`, other objects are recast if they are unique (unknown?) classes. Is this the intended behaviour? Here is a `reprex`:

```r
reprex::reprex({
  df <- data.frame(a = letters, b = 26:1)
  class(df) <- c("my_class", class(df))
  head(df, 3)
  class(df)
  new <- dplyr::arrange(df, b)
  class(new)
})
```
Any advice or workarounds (for now I'm using base R `df[ order(df$b), ]` as a patch ... boo!) are welcomed.
Thank you,
Stu

**Comment by cderv** [comment]
I think this is related to #1429. The advice there is to the subclass creator to deal with `tidverse` compatibility.  in you case something like `arrange.my_class` that deals with that. 

There is two examples where you'll find this:
* `sf` 📦 has implement custom methods (see [here](https://github.com/r-spatial/sf/blob/master/R/tidyverse.R))
* `tibbletime` 📦 did also the same (see [here](https://github.com/business-science/tibbletime/blob/master/R/compat-dplyr.R))
Both made different choices but the common point is to check is subclass still exists and add it if not (with all others things that goes with this class - attributes for example)

There is currently a helper function `tibble::new_tibble` that allows to add subclass easily.

Here is a small example to illustrate:
``` r
library(dplyr,)
df <- data.frame(a = letters, b = 26:1)
# create subclass
df <- tibble::new_tibble(df, subclass = "my_class")
head(df, 3)
#> # A tibble: 3 x 2
#>   a         b
#>   <fct> <int>
#> 1 a        26
#> 2 b        25
#> 3 c        24
class(df)
#> [1] "my_class"   "tbl_df"     "tbl"        "data.frame"
# with dplyr arrange
new <- dplyr::arrange(df, b)
#> Warning: le package 'bindrcpp' a été compilé avec la version R 3.4.4
class(new)
#> [1] "tbl_df"     "tbl"        "data.frame"
tibble::new_tibble(new, subclass = "my_class") %>% class()
#> [1] "my_class"   "tbl_df"     "tbl"        "data.frame"
# with custom arrange method - the clean way
arrange.my_class <- function(.data, ...) {
  tibble::new_tibble(NextMethod(), subclass = "my_class")
}
new2<- arrange(df, b)
new2
#> # A tibble: 26 x 2
#>    a         b
#>    <fct> <int>
#>  1 z         1
#>  2 y         2
#>  3 x         3
#>  4 w         4
#>  5 v         5
#>  6 u         6
#>  7 t         7
#>  8 s         8
#>  9 r         9
#> 10 q        10
#> # ... with 16 more rows
class(new2)
#> [1] "my_class"   "tbl_df"     "tbl"        "data.frame"
```

Created on 2018-04-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by stufield** [comment]
Thank you for the advice ... S3 method work around was simple and easy to implement.

**Comment by romainfrancois** [comment]
Thanks @cderv. Closing this one now.
