### ISSUE TITLE
DATEADD translation for MS SQL Server

### ISSUE THREAD

**Issue by WaterworthD** [tidyverse/dplyr#3524]
Hi

I'm trying to translate the tsql DATEADD function using dbplyr

DATEADD (datepart , number , date )  

The datepart argument is a string literal which should not be quoted, however dbplyr quotes it as it appears to assume all function arguments are numeric literals or text column names. i.e.

Actual behaviour:

`dbplyr::translate_sql(DATEADD(dd,1L,Date))`
`<SQL> DATEADD("dd", 1, "Date")`

Required behaviour:

`dbplyr::translate_sql(DATEADD(dd,1L,Date))`
`<SQL> DATEADD(dd, 1, "Date")`

Is there a workaround for this?

Also is there a way of passing a workspace variable as either the number of data argument and have dbplyr evaluate to a literal before passing to the SQL engine? 

Regards
Dave

**Comment by hadley** [comment]
You're looking for `sql()`

``` r
library(dplyr, warn.conflicts = FALSE)

my_table <- dbplyr::lazy_frame(my_date = 1:4, src = dbplyr::simulate_mssql())                         
my_table %>%                                    
  mutate(new_date = sql('DATEADD(dd, 1, [my_date])')) %>%
  show_query()
#> <SQL> SELECT `my_date`, DATEADD(dd, 1, [my_date]) AS `new_date`
#> FROM `df`
```

Created on 2018-05-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
