### ISSUE TITLE
hybrid all or nothing 

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3526]
meta issue to discuss the hybrid all or nothing.  
problems caused by hybrid : #2080

Currently the hybrid evaluation can be used in two ways. 

 - to handle the whole expression, i.e. `summarise(df, x = mean(y))` 

`mean(y)` is identified as something that can be handled internally, because we know `mean` and we know that `y` is a variable from the data. This is where hybrid eval really is useful

 - hybrid folding, to handle part of the expression, e.g. `summarise( df, x = mean(y) + 1)`

Here we do not know how to deal directly with `mean(y) + 1`, so what happens is a sort of hybrid folding where we traverse the expression and hunt for things that can be handled. This happens in each group, and is the source of most of the hybrid related problems. 

The idea would be to remove the hybrid folding entirely which would
- simplify the code base
- potentially make hybrid more aggressive/useful for the use case we keep, esp if this happens in parallel to #2311

**Comment by romainfrancois** [comment]
Once we have hybrid operate only on whole expression, it should be easier to hybrid more things.

**Comment by romainfrancois** [comment]
Installing functions in the data mask has some problems, for example (adapted from test-rank.R): 

``` r
library(dplyr, warn.conflicts = FALSE)

# we find the `n` function first
ntile_h <- function(x, n) {
  tibble(x = x) %>%
    mutate(y = ntile(x, n)) %>%
    pull(y)
}
ntile_h(1:5, 3)
#> Error in mutate_impl(.data, dots, hybrid_functions(.data)): Evaluation error: non-numeric argument to binary operator.

# workaround using a different name
ntile_h <- function(x, nn) {
  tibble(x = x) %>%
    mutate(y = ntile(x, nn)) %>%
    pull(y)
}
ntile_h(1:5, 3)
#> [1] 1 1 2 2 3

# unquoting
ntile_h <- function(x, n) {
  tibble(x = x) %>%
    mutate(y = ntile(x, !!n)) %>%
    pull(y)
}
ntile_h(1:5, 3)
#> [1] 1 1 2 2 3
```

The workarounds make it work, but that feels very hostile to forbid function arguments called `n`.

**Comment by hadley** [comment]
We’ll need to put them in an environment that the data mask is a child of. @lionel- can point you in the right direction.

**Comment by lionel-** [comment]
If your data mask is several environments deep, you can use `new_data_mask()`. It takes the bottom and the top environments as arguments. It also has a C callable interface for native code:

```r
fns_env <- env(n = function() "mille milliards")
data_env <- env(fns_env, n = 1e12)

mask <- new_data_mask(data_env, fns_env)

eval_tidy(quote(n), mask)
#> [1] 1e+12

eval_tidy(quote(n()), mask)
#> [1] "mille milliards"
```

**Comment by romainfrancois** [comment]
🤦‍♂️ for some reason I inverted the environment in the call to `new_data_mask`. Works better now. Thanks.

**Comment by romainfrancois** [comment]
We can close this when we merge #3799
