### ISSUE TITLE
Suggestion: pass a string to dplyr functions and use that as the whole argument

### ISSUE THREAD

**Issue by 2533245542** [tidyverse/dplyr#3530]
Hi, I just have a quick suggestion. Sometimes when using dplyr functions, we might encounter the situation where we have to manually input a lot of variable names, and I want to automate that. Is it possible that I first use paste0 to creste a long string and then pass that to dplyr functions? For example, I want to convert this, (Using flights from package nycflights13 as a dataset)

##code1##
mutate(flights, gain  = arr_delay - dep_delay, speed = distance + arr_delay + dep_delay)

to the following,
 
##code2##
string = “flights, gain  = arr_delay - dep_delay, speed = distance + arr_delay + dep_delay”
#after some magic
mutate(string)

In my mind, code1 and code2 have the same functions. 

Does that make sense? 

It would be even better if there is already a way to accomplish that, and please let me know. Thanks!

**Comment by krlmlr** [comment]
Thanks. This is already possible (with a different syntax) using tidy evaluation, see the programming vignette: http://dplyr.tidyverse.org/articles/programming.html .

For the future: questions like this are better suited at StackOverflow or https://community.rstudio.com/ . Your contribution here is very welcome if you think you found a bug in *dplyr* or if you want to suggest a change in the code.

**Comment by 2533245542** [comment]
Thanks krlmlr! I actually looked at the programming guide before but I was not able to find the exact solution I want. I also checked StackOverflow. Could you give me a quick solution?

**Comment by JohnMount** [comment]
That sort of notation is something supported by the `seplyr` package.  It allows one to work using string representations of expressions and variables. Here is an example.

```r
library("seplyr")
#> Loading required package: wrapr

exrps <- c("gain" = "arr_delay - dep_delay", 
           "speed" = "distance + arr_delay + dep_delay")
vars <- qc(arr_delay, dep_delay, distance, gain, speed)
nycflights13::flights %.>%
  mutate_se(., exrps) %.>%
  select_se(., vars)
#> # A tibble: 336,776 x 5
#>    arr_delay dep_delay distance  gain speed
#>        <dbl>     <dbl>    <dbl> <dbl> <dbl>
#>  1       11.        2.    1400.    9. 1413.
#>  2       20.        4.    1416.   16. 1440.
#>  3       33.        2.    1089.   31. 1124.
#>  4      -18.       -1.    1576.  -17. 1557.
#>  5      -25.       -6.     762.  -19.  731.
#>  6       12.       -4.     719.   16.  727.
#>  7       19.       -5.    1065.   24. 1079.
#>  8      -14.       -3.     229.  -11.  212.
#>  9       -8.       -3.     944.   -5.  933.
#> 10        8.       -2.     733.   10.  739.
#> # ... with 336,766 more rows
```
