### ISSUE TITLE
Long var names bug in dbplyr and OCDB

### ISSUE THREAD

**Issue by congdanh8391** [tidyverse/dplyr#3534]
I have problem that mentioned here: https://github.com/r-dbi/odbc/issues/10

I'm SQL query newbie so I prefer to query by dbplyr but I found out the big bug as mentioned above. How can I fix it? Or does it have any tips to pass over it?

I practice on an example database with a few long var name so every thing went unsuccessful.  I know that I would  see the databases like these in the future.
![untitled](https://user-images.githubusercontent.com/38421401/39170800-008f149a-47c7-11e8-9eeb-45b69f46e10c.png)

Please give me some advises. 

Thanks

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Right now the best way to install reprex is:
```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```
If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste (or drag and drop) the contents here.

```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```

Thanks

**Comment by hadley** [comment]
This issue doesn't seem to be related to dplyr, and you have failed to provide code that we can easily run as requested.
