### ISSUE TITLE
Cannot pull views (using dbplyr & RMariaDB)

### ISSUE THREAD

**Issue by foundinblank** [tidyverse/dplyr#3541]
Hi,

I'm unable to pull views via my RMariaDB connection. Here's an example below where I'm trying to pull a view called `video_product_lookup`, but I can replicate the issue with all other views. I can pull regular tables just fine. 

Thanks,
Adam

``` r
# Load packages
library(RMariaDB)
#> Warning: package 'RMariaDB' was built under R version 3.4.4
library(tidyverse)
library(DBI)
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

# Connect to database
reporting <- dbConnect(RMariaDB::MariaDB(), group = "reporting")
dbListTables(reporting) # This does list the table (view) I want to connect to
#> ...        
#> [67] "video_product_lookup"
#> ...        

# Get the view
df <- tbl(reporting, "video_product_lookup")
#> Error in result_create(conn@ptr, statement, is_statement): Prepared statement needs to be re-prepared [1615]

# Get the view a different way
df <- dbReadTable(reporting, "video_product_lookup")
#> Error in result_create(conn@ptr, statement, is_statement): Prepared statement needs to be re-prepared [1615]

# Get a regular table - this works fine. 
df <- tbl(reporting, "biz_orders")
```

Created on 2018-04-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by foundinblank** [comment]
Nope, that doesn't work either. Trying to figure out if the view is default or non-default. (I'm pulling from MySQL dbs/tables).

**Comment by foundinblank** [comment]
Upon closer research it turns out MySQL doesn't have default schema. https://stackoverflow.com/questions/12426320/how-do-i-set-the-default-schema-for-a-user-in-mysql

**Comment by hadley** [comment]
Can you please include the SQL needed to create a view in your reprex?

**Comment by foundinblank** [comment]
I created the view via a different avenue (using PopSQL and/or Sequel Pro). It's a generic CREATE VIEW statement, something like this: 

```
CREATE VIEW video_product_lookup AS
SELECT * ... etc
FROM * ... etc
```

Let me know if that helps...

**Comment by hadley** [comment]
Can you please make a complete reprex including actual sql required to make a simple view? I have hundreds of issues I could work on and anything you can do you to make this one easier for me is appreciated.

**Comment by foundinblank** [comment]
Done, @hadley! The second half of the reprex shows me creating a `mtcars` table, then a view of it (`mtcars_view`), then attempting to query the view, which gives me the same `Prepared statement needs to be re-prepared [1615]` error. 

I am able to use other SQL programs to verify that `SELECT * FROM mtcars_view` returns expected results. It's just inside R that I can't work with views, only with tables. 

Thanks for any help you can provide in debugging this. 

``` r
library(RMariaDB)
library(tidyverse)
library(DBI)
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

# Connect to database
reporting <- dbConnect(RMariaDB::MariaDB(), group = "reporting")
dbListTables(reporting) # This does list the table (view) I want to connect to
#>  ...         
#> [71] "video_product_lookup"
#>  ...     

# Get the view
tbl(reporting, "video_product_lookup")
#> Error in result_create(conn@ptr, statement, is_statement): Prepared statement needs to be re-prepared [1615]

# Get the view a different way
dbReadTable(reporting, "video_product_lookup")
#> Error in result_create(conn@ptr, statement, is_statement): Prepared statement needs to be re-prepared [1615]

# Get a regular table - this works fine. 
tbl(reporting, "biz_orders")
#> # Source:   table<biz_orders> [?? x 7]
#> # Database: mysql 10.1.14-MariaDB [adamstone@127.0.0.1:/reporting]
#>    company       state user      number expenses since               owner
#>    <chr>         <chr> <chr>     <chr>     <dbl> <dttm>              <chr>
#>  <data goes here>


# Create a mtcars table and populate it
dbCreateTable(reporting, "mtcars", mtcars) 
dbAppendTable(reporting, "mtcars", mtcars) # writing mtcars data to created table
#> [1] 32

dbReadTable(reporting, "mtcars") # checking mtcars has data in it
#>     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> 1  21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
#> 2  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
#> 3  22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> ... 

# Create "mtcars_view" - a view of mtcars table
dbExecute(reporting,'CREATE VIEW mtcars_view AS SELECT mpg, cyl, disp FROM mtcars')
#> [1] 0

# Check if mtcars_view exists
dbListTables(reporting)
#> ...
#> [41] "mtcars"                         "mtcars_view"                   
#> ...

# Get the view - throws same errors
tbl(reporting, "mtcars_view")
#> Error in result_create(conn@ptr, statement, is_statement): Prepared statement needs to be re-prepared [1615]
dbReadTable(reporting, "mtcars_view")
#> Error in result_create(conn@ptr, statement, is_statement): Prepared statement needs to be re-prepared [1615]
```

**Comment by edgararuiz** [comment]
Ok, does your MySQL `options` file sets the `database` (https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html#option_mysql_database) or some related switch?  As per this article: https://dev.mysql.com/doc/refman/8.0/en/create-view.html, the View is created in the *default* database, so if the `options` file changes that somehow, then that may be the root cause of the problem.  Also, can run `SHOW DATABASES` to see which databases you have access to?

**Comment by foundinblank** [comment]
I'm not using an `options` file here (no `.my.cnf` file). The default database is set to `reporting` which is where all these tables and views are made, and which I have access to. `SHOW DATABASES;` shows the reporting db which I'm connected to. Using `dbSendQuery(reporting, 'USE reporting;')` does not change the results when I attempt to query or pull rows from a view. 

I know, it's a weird issue, isn't it? It should work but I'm simply unable to pull views.

**Comment by foundinblank** [comment]
Sure. Same problem. 

```
> dbGetQuery(reporting, "Select * from reporting.mtcars_view")
Error in result_create(conn@ptr, statement, is_statement) : Prepared statement needs to be re-prepared [1615]

> dbGetQuery(reporting, "Select * from reporting.mtcars")
    mpg cyl  disp  hp drat    wt  qsec vs am gear carb
1  21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
2  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
3  22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
4  21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
...
```

**Comment by edgararuiz** [comment]
oh wait, does `SHOW DATABASES` only displays `reporting`? Is that both the only and the default db in the server?

**Comment by foundinblank** [comment]
Running `dbGetQuery(reporting, "SHOW DATABASES;")` displays several other databases too with which I have access to. But does that matter...? All my `db**` commands use `conn = reporting` in them.

**Comment by edgararuiz** [comment]
I think so, because as per this article: https://dev.mysql.com/doc/refman/8.0/en/create-view.html, if we don't specify a schema for the temp table, then it will use the default schema to record the View.  So it should be accessed via: `dbGetQuery(reporting, "Select * from [default schema name].mtcars_view")`

**Comment by foundinblank** [comment]
We already tried this a few replies above - https://github.com/tidyverse/dplyr/issues/3541#issuecomment-391351684

I get the `re-prepared` error with `reporting.mtcars_view`, but not with `reporting.mtcars`. Both the table and view are definitely in the `reporting` schema according to `SHOW TABLES IN reporting;`

**Comment by krlmlr** [comment]
Is this still relevant? Maybe move it to dbplyr then?

**Comment by foundinblank** [comment]
Yes - still getting this error. Thanks for checking in.
