### ISSUE TITLE
"no rule to make target c++" when installing on RStudio environment separate from OS.

### ISSUE THREAD

**Issue by danielcanueto** [tidyverse/dplyr#3542]
Dear Mr/Mrs, 

I'm not able to install dplyr in an RStudio environment prepared by a firm for a data science project because of "no rule to make target c++" errors when compiling. The lack of this package hampers the installation of vital packages and endangers the project viability. My suspicion is that the error is caused by the possibility shown here:

https://stackoverflow.com/questions/17888259/no-rule-to-make-target-class-cpp-needed-by-build-x86-class-o-stop

So a necessary file in the OS from where the environment was created cannot be read.

Could the dplyr installation avoid the issue commented so the package can be installed in the environment created by the firm? I guess that other packages have similar c++ compilation but these ones can be installed.

Thank you.

**Comment by batpigandme** [comment]
Can you please clarify what you mean by "RStudio environment separate from OS"? Are you using RStudio Server? If so, what is its environment?

Are you trying to install the CRAN release version of dplyr or the development version from GitHub?

**Comment by romainfrancois** [comment]
presumably the machine don't have tools like make and the compilers, ... I guess you'd need to ask the firm

**Comment by romainfrancois** [comment]
Can you run devtools::has_devel()

**Comment by danielcanueto** [comment]
_presumably the machine don't have tools like make and the compilers, ... I guess you'd need to ask the firm_

Yes, that's my intuition. But I wanna explore options and develop a clear response so they can't ignore demands.

Results of   devtools::has_devel()

```
devtools::has_devel()
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD SHLIB foo.c 

gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c foo.c -o foo.o
gcc -m64 -std=gnu99 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o foo.so foo.o -L/usr/lib64/R/lib -lR
[1] TRUE
```

Thank you very much.

**Comment by romainfrancois** [comment]
So you can compile C code fine. Let's try C++ now, what does this give you ? 

```
> Rcpp::evalCpp( "42")
[1] 42
```

**Comment by danielcanueto** [comment]
```
Rcpp::evalCpp( "42")

42
```

By the way, sessioninfo:

```
sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)


Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=es_ES.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=es_ES.UTF-8        LC_COLLATE=es_ES.UTF-8    
 [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=es_ES.UTF-8   
 [7] LC_PAPER=es_ES.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_1.3.1          shiny_1.0.0         data.table_1.10.4-3

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  R6_2.2.0        htmltools_0.3.5 tools_3.4.1    
 [5] withr_2.1.2     memoise_1.1.0   Rcpp_0.12.9     digest_0.6.12  
 [9] xtable_1.8-2    httpuv_1.3.3    mime_0.5        devtools_1.13.5
```
I'd happily share more details about about the kind of errors shown, but their R version is in Spanish and I'd need to do some cleaning before.

**Comment by romainfrancois** [comment]
🤔 that looks good. What about: 

devtools::install_github("tidyverse/dplyr" )

**Comment by danielcanueto** [comment]
Hah, it seems that with install_github option it has been installed. I find strange not to have tried myself the install_github option before. However, it is not possible thourgh install.packages to install "tidyverse" or "dplyr". This is the kind of message that appears:

```
make: *** No hay ninguna regla para construir el objetivo `hybrid_minmax.cpp', necesario para `hybrid_minmax.o'.  Alto.
ERROR: compilation failed for package ‘dplyr’
```
Every way I try to install it, the .cpp file that fails is a different one.

It is a little tricky to try to install through install_github for this kind of project, but I should be able to be allowed to do it. Thank you very much. However, feel free to ask me to do tests to solve the current problems when trying to install dplyr through install.packages.

Cheers,

Daniel

**Comment by romainfrancois** [comment]
It is odd, but this feels like a problem in how R was setup rather than a dplyr issue. 

I’ll close this now, given you can install the dev version from github.
