### ISSUE TITLE
Feature Request: Chatty dplyr/summarize message when group by is changed

### ISSUE THREAD

**Issue by CerebralMastication** [tidyverse/dplyr#3553]
Proposal: give a message back to the user when `summarize` changes the grouping

Background:
I just spent many hours trying to understand some `dplyr` behavior which I ultimately traced back to the throughly documented feature where `dplyr` drops the last `group_by` element after `summarize` is run. I notice that I am not the only one being surprised by this:

#3315 dplyr::summarise removes a grouping variable
#2963 data is still grouped after a summarize (but not by original set of columns

I've seen more but these two popped up in a quick search. The reason this was so confusing to me was that I had explicitly set the grouping and all my experience with R and SQL didn't prepare me for the system to silently change something I had explicitly set. I notice that in other functions when dplyr does helpful things or makes assumptions it's pretty chatty about it. For example, when I do: 

```
inner_join(data.frame(a=1) ,data.frame(a=1) )
```
dplyr chattily reminds me that it's making an assumption about my join preference, thus warning me not to be surprised:
```
Joining, by = "a" 
```
I would love to see that same sort of chattiness when the `group_by` is changed automagically. Something like:
```
group_by reset to (groupA, broupB) after summarize()
```

cheers, 

JD

**Comment by krlmlr** [comment]
Thanks. I agree this might help reduce confusion. How do you suggest to turn off that new chattiness? For instance, for joins this is done by explicitly setting the `by` argument.

**Comment by romainfrancois** [comment]
idk, in the case of joins, the message pops up when you have not specified what to join by, so a decision has been taken automatically, so it's fair to have a message. 

otoh, for summarise, this is what it does, always. it peels off one level of grouping. Maybe this is a documentation issue, but I don't think we need a message for that. It's always possible to do something like `trace( dplyr:::summarise.tbl_df, exit = { ... } ) ` where `...` is some expression that prints the message ...

**Comment by CerebralMastication** [comment]
> How do you suggest to turn off that new chattiness? 

Valid point. There could be a `drop=TRUE` default option and if `drop` is not passed then it defaults and throws the message.

Just to beat this conceptual horse a bit more before Hadley shows up and gives judgement:

the auto drop is a significant conceptual change in a couple of ways:

1. Order of `group_by` elements now matters. In my 25+ years of using group by type constructs the order of the elements never mattered. Now the order matters because the last one is going to get dropped with every `summarize`. This is really handy now that I understand it, but it was really surprising at first. 
2. While it's "expected behavior" it's not the same as what users would expect unless they really poured over the docs. 

So just to reiterate, I think the behavior is sane, correct, and really useful. I think it can just be surprising to new users and there should be some type of nudge or breadcrumb to help users see what's going on.

**Comment by batpigandme** [comment]
> There could be a `drop=TRUE` default option and if drop is not passed then it defaults and throws the message.

Maybe I'm misunderstanding the meaning, but what would happen in the case of `drop = FALSE`, since there isn't an option to _not_ drop a level of grouping (if I'm understanding correctly)?

**Comment by CerebralMastication** [comment]
yeah, that's the trade off. `drop=FALSE` would have to not drop the grouping. Not that I can think of a use case for that, other than turn the next `summarize` into a `rowwise` operation (but that's a different thread altogether) 

Yeah, there are certainly trade offs here.

**Comment by hadley** [comment]
This is how `summarise()` works - it makes sense when you think about it because once you have summarised, each group becomes a single row and there's no point keeping the grouping.
