### ISSUE TITLE
Implement nest_join

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3570]
A `nest_join()` would create a list-column:

``` r
library(tibble)

df1 <- tibble(x = c(1, 2), y = c(2, 3))
df2 <- tibble(x = c(1, 1), z = c(2, 3))

# nest_join(df1, df2)
# Would yield:
out <- df1
out$df2 <- list(df2, NULL)
out
#> # A tibble: 2 x 3
#>       x     y df2             
#>   <dbl> <dbl> <list>          
#> 1     1     2 <tibble [2 × 2]>
#> 2     2     3 <NULL>
```

The output would always have exactly the same rows as the input, but with one new column, named (by default) with the name of `y`.  `unnest()`ing this data frame would yield an `inner_join()` (or a `left_join()` with https://github.com/tidyverse/tidyr/issues/358)

@romainfrancois how hard would this be to implement?

**Comment by hadley** [comment]
Hmmmm, good question; for now, I'd say let's include column `x`.

**Comment by romainfrancois** [comment]
That makes it easier to test it. I’ll 🤹‍♂️ with this, should be easy enough.
