### ISSUE TITLE
Match error message formatting to tidyverse style guide.

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/dplyr#3575]
A rolling thought, obviously, it just came up in one of the style guide examples (described https://github.com/tidyverse/style/issues/80) — particularly the separation of the follow up question as a bullet on its own line. 

https://github.com/tidyverse/dplyr/blob/4c2487a9dae88f7968315b35f64de48ae957fd58/R/tbl-df.r#L55-L62

**Comment by hadley** [comment]
Fixed by #4476
