### ISSUE TITLE
sample_frac() sample size

### ISSUE THREAD

**Issue by rtaph** [tidyverse/dplyr#3577]
I would like to raise the issue about the sample size returned by `sample_frac()`.  Here is a simple example of current behaviour:

```r
library(dplyr)
sample_frac(data.frame(x = 1:3), size = 0.5)
#>   x
#> 2 2
#> 1 1
```

The frame has 3 elements, but the function always returns 2 rows, implying a true sampling probability of of 2/3 over repeated sampling, not 1/2. This is because `dplyr:::sample_n_basic()` rounds the size to be sampled up or down to an integer.

I believe it would be more appropriate for the sample size to be random in these cases, so that the long-run performance of the sampling mechanism evaluates exactly to the expected sample size (even if this is fractional).

Here is what I have in mind (for `dplyr:::sample_n_basic`):
```r
# determine size stochastically such that E[nrow(result)] = fraction
expected_size <- size * n
size <- floor(expected_size) + rbernoulli(1, expected_size - floor(expected_size))
```

What are the developers' opinions on this matter? Can this be implemented (perhaps via an additional argument `random_size = FALSE` to ensure backwards compatibility)?

**Comment by krlmlr** [comment]
If you need more control, please implement your own sampling, e.g. with a nested data frame created with `tidyr::nest()` and a `map()` over the `data` column. See also https://github.com/tidyverse/dplyr/issues/3681#issuecomment-398277694 for a similar feature request.
