### ISSUE TITLE
diff() by groups is applied globally instead of by group under Linux

### ISSUE THREAD

**Issue by s-geissler** [tidyverse/dplyr#3578]
I am trying to calculate the diff() over a column in a data.frame by grouping the rows. This works fine under Windows and MacOS. Under Linux Mint 18 (Xenial), the behavior is as shown below for R versions 3.3 as well as 3.4.

Instead of calculating the diff() over entries of each group, hence having NA for the first element of each group, the diff() is applied globally as shown below. The same result can be observed when using `c = a - lag(a)`, indicating, that it is not an issue with the diff() function.

```r
A <- data.frame(a = c(1, 3, 5, 8), b = c(1, 1, 2, 2))

B <- A %>%
  group_by(b) %>%
  mutate(c = c(NA, diff(a)))

> B
# A tibble: 4 x 3
# Groups:   b [2]
      a     b     c
  <dbl> <dbl> <dbl>
1    1.    1.   NA 
2    3.    1.    2.
3    5.    2.    2.
4    8.    2.    3.
```
Expected output would be
```r
> B
# A tibble: 4 x 3
# Groups:   b [2]
      a     b     c
  <dbl> <dbl> <dbl>
1    1.    1.   NA 
2    3.    1.    2.
3    5.    2.   NA
4    8.    2.    3.
```

**Comment by s-geissler** [comment]
The problem was loading plyr after dplyr which masked mutate and let to the error. Closed.

**Comment by hadley** [comment]
FWIW you would've discovered this problem immediately if you'd used the reprex package.

**Comment by jennybc** [comment]
At first I wasn't sure this statement re: reprex was necessarily true, because reprex does quiet some messages about within-the-tidyverse masking by default (it's controlled by an argument). So I checked. But yes it really is true in this case.

Just for posterity, if people use reprex, the plyr masking problem is called out.

---
Case A: load dplyr and plyr as individual packages

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(plyr)
#> -------------------------------------------------------------------------
#> You have loaded plyr after dplyr - this is likely to cause problems.
#> If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
#> library(plyr); library(dplyr)
#> -------------------------------------------------------------------------
#> 
#> Attaching package: 'plyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     arrange, count, desc, failwith, id, mutate, rename, summarise,
#>     summarize
```

Created on 2018-05-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

---
Case B: load the tidyverse and then plyr as an individual package

``` r
library(tidyverse)
library(plyr)
#> -------------------------------------------------------------------------
#> You have loaded plyr after dplyr - this is likely to cause problems.
#> If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
#> library(plyr); library(dplyr)
#> -------------------------------------------------------------------------
#> 
#> Attaching package: 'plyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     arrange, count, desc, failwith, id, mutate, rename, summarise,
#>     summarize
#> The following object is masked from 'package:purrr':
#> 
#>     compact
```

Created on 2018-05-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
