### ISSUE TITLE
Column can't be used as a grouping variable because it's a list

### ISSUE THREAD

**Issue by ketansahils** [tidyverse/dplyr#3579]
Hi, I have the following dataframe:

temp_id | temp_sent
---------------------------------- | ----------------------------------
0.5-0.5-0-0_1 | the powerful achaemenid persians led cambyses began th...
0.5-0.5-0-0_1 | june update currently offering services lte services were u...
0.5-0-0.5-0_2 | garlic fried with coriander added molokhiya popular green...
0.5-0-0-0.5_3 | the republic egypt arabic was the official name egypt...

which I want to group by temp_id. But I'm getting an error saying:
`Error in grouped_df_impl(data, unname(vars), drop) : Column `temp_id` can't be used as a grouping variable because it's a list`. Please help.

**Comment by krlmlr** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximize your chances of getting a good answer.)

**Comment by ketansahils** [comment]
Ok. Thanks.
