### ISSUE TITLE
all.equal.tbl_df doesn’t compare NaN correctly

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3582]
On phone, but just needs simple reprex of one row one col df containing NaN

**Comment by krlmlr** [comment]
Works for me in 0.7.4, though:

``` r
library(tidyverse)
tibble(a = NaN) %>% all.equal(., .)
#> [1] TRUE
tibble(a = NA) %>% all.equal(., .)
#> [1] TRUE
```

> Created on 2018-05-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by romainfrancois** [comment]
``` r
library(tidyverse)
df1 <- tibble(x = c(NaN, 2))
df2 <- tibble(x = c(2, NaN))
all_equal(df1, df2)
#> [1] TRUE
```

@Hadley can't reproduce the problem

**Comment by hadley** [comment]
Hmmmm, weird. If I see it again, I'll dig into it more.
