### ISSUE TITLE
csv files as dbplyr backend?

### ISSUE THREAD

**Issue by rkrug** [tidyverse/dplyr#3583]
Hi

It might be already possible, but I can't find it:

Can I use standard .csv files (or any variant thereof) as a backend for dplyr / dbplyr? 

My scenario is to have the possibility to initially store data in csv files on github (as sqlite is binary and github is not that binary friendly it makes the choice of sqlite initially less suitable), but it will be later necessary to use an external database due to space constraints.

Is this possible already with dplyr?

Thanks

Rainer

**Comment by hadley** [comment]
It’s not currently possible, and if implemented would be a separate package (and mostly likely it would be by someone in the community, not us)
