### ISSUE TITLE
Suggestion for .id in bind_rows

### ISSUE THREAD

**Issue by ramongallego** [tidyverse/dplyr#3591]
When you bind 2 tibbles, you can create an .id column to keep track of the original tibble they came from. If you want to add a third tibble to the newly created tibble, bind_rows creates a new .id variable, even if the name specified is the same. 

So my suggestion would be, if the .id column already exists, to get the counter continuing from where the last tibble left it

**Comment by hadley** [comment]
This is out of scope for dplyr. I’d suggest asking on RStudio community for alternative ways to attack the same problem.
