### ISSUE TITLE
Inconsistency self join and pipping

### ISSUE THREAD

**Issue by dustindall** [tidyverse/dplyr#3592]
I ran into an issue trying to self join on a table. 

```r
iris %>%
  left_join(., . %>% select(Species, x = Sepal.Width), by = c("Species" = "Species"))
```
The code produced the following error -

> Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "c('fseq', 'function')"

I could not find this issue else where. After sometime playing around with it, I noticed the error went away if i put the ```.``` inside the ```select``` statement.

```r
iris %>%
  left_join(., select(., Species, x = Sepal.Width), by = c("Species" = "Species"))
```

 I do not know if this is intentional or a bug, so I though I would share.

I'm using dplyr v0.7.5 and ran into the same error testing v0.7.0.

Thanks,
Dustin

**Comment by romainfrancois** [comment]
pipelines that start with `.` are understood by magrittr as lambda function creation, e.g. 

``` r
library(magrittr)

f <- . %>% 
  rnorm(mean = 0, sd = 4) %>% 
  mean()

f(10)
#> [1] 1.246612
```

What the message is trying to say is that tou can't join a data frame with a function. 

I don't think there's anything to be done here.
