### ISSUE TITLE
scoped functions won't work with tbl_lazy when the function is created by ~

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#3594]
This fails (if I use `funs()` instead of `~`, it works):

``` r
library(DBI)
library(dplyr, warn.conflicts = FALSE)

con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)

tbl(con, "mtcars") %>%
  dplyr::summarise_all(~ any(is.na(.)))
#> Error in (function (..., .x = ..1, .y = ..2, . = ..1) : object 'mpg' not found
```

The error comes from here: https://github.com/tidyverse/dbplyr/blob/81419cab7d831e5a9d7e4279a4f893fa5750e8a1/R/tbl-lazy.R#L124

The root cause seems that `partial_eval()` won't accept expressions that generate a function in-place:

``` r
library(dbplyr)

q1 <- rlang::quo((function(x) is.na(x))(a))
q2 <- rlang::quo(is.na(a))

partial_eval(q1, vars = "a")
#> Error in (function(x) is.na(x))(a): object 'a' not found

partial_eval(q2, vars = "a")
#> <quosure>
#>   expr: ^is.na(a)
#>   env:  global
```

Another example here:

``` r
add_n <- function(n) {
  function(x) x + n
}

q3 <- rlang::quo(add_n(1)(a))

partial_eval(q3, vars = "a")
#> Error in add_n(1)(a) : object 'a' not found
```

The fix would probably come around here, but I didn't come up with the proper way of distinguishing the expression that generates function or not.

https://github.com/tidyverse/dbplyr/blob/ae86fb351bf3511aa73f622946db3a9ed7469fc4/R/partial-eval.r#L96

**Comment by hadley** [comment]
Part of #3433

**Comment by krlmlr** [comment]
Added reference in #3433, and copied reprex there.
