### ISSUE TITLE
bind_rows fails with data_frame containing NULL

### ISSUE THREAD

**Issue by adder** [tidyverse/dplyr#3596]
Hey 
I stumbled upon this issue while using `unnest()` from `tidyr`.
But I could trace the error back to `bind_rows()`

This is a minimal example.

```r
library(tidyverse)
#> -- Attaching packages ---------------------------------- tidyverse 1.2.1 --
#> <U+221A> ggplot2 2.2.1     <U+221A> purrr   0.2.4
#> <U+221A> tibble  1.4.2     <U+221A> dplyr   0.7.5
#> <U+221A> tidyr   0.8.1     <U+221A> stringr 1.3.1
#> <U+221A> readr   1.1.1     <U+221A> forcats 0.3.0
#> -- Conflicts ------------------------------------- tidyverse_conflicts() --
#> x dplyr::filter() masks stats::filter()
#> x dplyr::lag()    masks stats::lag()
bind_rows(data_frame(a = NULL), data_frame(a = 1))
#> Error: Column `a` must be a 1d atomic vector or a list
```

I would expect that only the second dataframe is returned.

Greetz

**Comment by batpigandme** [comment]
The error in the example above says `could not find function "bind_rows"` – likely because the library isn't loaded. 

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? 

If you've never heard of reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Thanks

**Comment by adder** [comment]
Ha, I actually used reprex output but I didn't know that I also had to load the tidyverse library inside the reprex function. And I didn't reread the reprex output before I copy pasted. My bad :s sorry.

I updated  the originally post.

**Comment by romainfrancois** [comment]
`bind_rows` does not play here, the error comes from `data_frame`

``` r
library(tibble)
data_frame(a = NULL)
#> Error: Column `a` must be a 1d atomic vector or a list
```

@adder Can you make another reprex inspired from the original problem you saw with `unnest` ?

**Comment by romainfrancois** [comment]
@adder thanks. it's fine here.

**Comment by adder** [comment]
`unnest()` example:

```r
library(tidyverse)
data_frame(b = c(list(new_tibble(list(a = NULL))), list(new_tibble(list(a = 1))))) %>% 
  unnest
#> Error in bind_rows_(x, .id): Argument 1 is a list, must contain atomic vectors
```
I would expect a  dataframe with column `a` that contains the single value `1`

**Comment by hadley** [comment]
I think you need to provide some more detail about how you get this weird data frame. There's no expectation that bind rows should work with pathological data frames.

**Comment by hadley** [comment]
If you're going to use `new_tibble()` directly, it's up to you to check that the data frames are correctly formed. I suspect there's probably a faster way that doesn't involve `new_tibble()`; asking on community.rstudio.com is probably the way to go (with a reprex of your overall problem)

**Comment by adder** [comment]
Okey, thanks.
Indeed, a better/safer implementation of my custom function is probably the way to go.
