### ISSUE TITLE
Cannot install dplyr

### ISSUE THREAD

**Issue by cmohamma** [tidyverse/dplyr#36]
I'm having trouble installing the dplyr package. Im running a mac osx 10.8.5 and I've installed Xcode and the command line tools and uninstalled them and installed them again (3 or 4 times over), restarted my computer numerous times and each time I get this error:

```
* installing *source* package 'dplyr' ...
** libs
llvm-g++-4.2 -arch x86_64 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.0/Resources/library/Rcpp/include"   -fPIC  -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
/bin/sh: llvm-g++-4.2: command not found
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package 'dplyr'
* removing '/Library/Frameworks/R.framework/Versions/3.0/Resources/library/dplyr'
Error: Command failed (1)
```

Any ideas? Thanks!

**Comment by dilinigunasena** [comment]
Hi,
I also tried to install 'dplyr' in kali linux. But could not install it success fully The ERROR I'm getting is as follows. If anybody can helpally it`s re appriciated.
install.packages("/root/SoftwareCollection/R/tiq-test/dplyr_0.3.tar",repos=NULL,type="source")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘dplyr’ ...
** package ‘dplyr’ successfully unpacked and MD5 sums checked
** libs
clang++ -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/dplyr.h:134:
../inst/include/dplyr/JoinVisitorImpl.h:175:13: error: cannot initialize a member subobject of type 'int *' with an rvalue of type 'const_iterator' (aka 'const int *')
            left_ptr(left_.begin()), 
            ^        ~~~~~~~~~~~~~
../inst/include/dplyr/JoinVisitorImpl.h:236:13: error: cannot initialize a member subobject of type 'int *' with an rvalue of type 'const_iterator' (aka 'const int *')
            right_ptr(right_.begin()), 
            ^         ~~~~~~~~~~~~~~
2 errors generated.
/usr/lib/R/etc/Makeconf:137: recipe for target 'RcppExports.o' failed
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘dplyr’
* removing ‘/usr/local/lib/R/site-library/dplyr’
Warning in install.packages :
  installation of package ‘/root/SoftwareCollection/R/tiq-test/dplyr_0.3.tar’ had non-zero exit status
