### ISSUE TITLE
Compatibility with grouped data frames created with dplyr <= 0.7.5

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3604]
We might still see old-style grouped data frames if a user deserializes a file that has been created with dplyr <= 0.7.5 (perhaps unintentionally, e.g. when using a *knitr* cache).

Reference: https://github.com/tidyverse/dplyr/pull/3595#issuecomment-391994182.

**Comment by romainfrancois** [comment]
I'll do #3605 first. 

Not sure how much code I want in for this. I guess `GroupedDataFrame` should take care of it.

**Comment by hadley** [comment]
I think we should just re-group in that case.

**Comment by romainfrancois** [comment]
I'm ok with that. So just picking up the `vars` attribute and remake the groups tibble from it.
