### ISSUE TITLE
Inconsistent behaviour of group_by/summarise_at in version 0.7.5

### ISSUE THREAD

**Issue by privefl** [tidyverse/dplyr#3613]
In new version (0.7.5), 
```
iris %>%
  group_by(Species) %>%
  summarise_at(-1, mean)
```
> Error in summarise_impl(.data, dots) : 
>  Column `Species` can't be modified because it's a grouping variable

I'm pretty sure that the grouping variable was automatically excluded in previous versions.

Is this a bug or a feature? (in order for me to change my code only if necessary)

**Comment by romainfrancois** [comment]
We are currently thinking about scoped verbs as a whole. This feels like a 🐛 . 

In the meantime, you can also exclude `Species` e.g. : 

```r
> iris %>%
+   group_by(Species) %>%
+   summarise_at(vars(-1, -Species), mean)
# A tibble: 3 x 4
  Species    Sepal.Width Petal.Length Petal.Width
  <fct>            <dbl>        <dbl>       <dbl>
1 setosa            3.43         1.46       0.246
2 versicolor        2.77         4.26       1.33 
3 virginica         2.97         5.55       2.03 
```
