### ISSUE TITLE
copy_to: out of disk space error message unclear

### ISSUE THREAD

**Issue by mschilli87** [tidyverse/dplyr#3615]
## Update (II)

The whole original issue below turned out to boil down to me running out of
disk space when writing the second table with the big indexes.
Closing my R session freed some space which is why it did work in the new session.

I'll leave the issue open as I *really* think a more clear error message
would be appropriate but feel free to close as wontfix as this is 
probably caused by upstream (sqlite) and should then better be fixed there.

---
## Original issue

A word of warning: I am new to the whole DBI world so I am not sure how to
further narrow-down this issue by myself.

I am working on porting existing `dplyr`-based code from writing tibbles to
disk and reading them into memory via `saveRDS`/`readRDS` to using an SQLite
backend.

I have several big tibbles (up to ~ 1e7 x 10) that I want to write to a local
SQLite database using `copy_to`:

```r
# use temporary database file (no NFS!)
tmp.sqlite <- tempfile(fileext = ".sqlite")

# open connection
tmp.db <- dbConnect(SQLite(), dbname = tmp.sqlite)

# write first tibble
tibble.one %>%
  copy_to(dest = tmp.db, name = "tibble.one", temporary = FALSE,
          indexes = list("column.one", "column.three", "column.six"),
          overwrite = TRUE)

# close connection
dbDisconnect(tmp.db)

# some more code
# ...

# re-open connection
tmp.db <- dbConnect(SQLite(), dbname = tmp.sqlite)

# write second tibble
tibble.two %>%
  #head(1e5) %>%
  copy_to(dest = tmp.db, name = "tibble.two", temporary = FALSE,
          indexes = list("column.two", "column.three", "column.five"),
          overwrite = TRUE)

# close connection again
dbDisconnect(tmp.db)
```

While this works fine for `tibble.one` it fails for `tibble.two` with the
following error:

```
Error in result_create(conn@ptr, statement) :
  cannot rollback - no transaction is active
```

When I uncomment the `head(1e5)` line it works.
When I try with `head(1e6)` it sometimes works but sometimes doesn't.
With `head(5e6)` it worked once but failed many times.

I am working on a sharable data set that reproduces the error but there are
many unknowns for me and I figured I might be doing something fundamentally
wrong and someone could point me in the right direction.

I considered asking a Q/A on SO but at any rate I consider this a bug as the
error message is not helpful at all and I posted it here as my guess is
`dplyr::copy_to` generates invalid/unstable SQL code for some inputs.

---
## Update (I)

I simplified my actual `tibble.two` and ensured it still failed every attempt
of using `copy_to` on the whole data.

I then saved the tibble via `saveRDS` to a webserver.

I copy/pasted the code I used before and added a few lines to load the data
from the URL:

```r
library(dplyr)
library(RSQLite)

# set seed to issue number
set.seed(3615)

# load problematic tibble
url("https://bimsbstatic.mdc-berlin.de/rajewsky/mschilli/tibble2.Rds") %>%
  gzcon %>%
  readRDS -> tibble.two

# create SQLite connection on tmpfile (no NFS!)
tmp.sqlite <- tempfile(fileext = ".sqlite")
tmp.db <- dbConnect(SQLite(), dbname = tmp.sqlite)

# try to write problematic tibble
tibble.two %>%
copy_to(dest = tmp.db, name = "tibble.two", temporary = FALSE,
        indexes = list("col1", "col2", "col3"),
        overwrite = TRUE)

# try to write part of problematic tibble
tibble.two %>%
slice(sample(1:n(), 1e6)) %>%
copy_to(dest = tmp.db, name = "tibble.two.part", temporary = FALSE,
        indexes = list("col1", "col2", "col3"),
        overwrite = TRUE)

# close database connection
dbDisconnect(tmp.db)
```

Running this in a new R session, I was not able to reproduce the issue anymore.

I will keep investigating further but any suggestion where to start looking
would be very helpful.

---
PS: I removed the data file as it turned out unrelated to the issue.

**Comment by hadley** [comment]
It seems most likely that this is a SQLite issue so could you please file at http://github.com/r-dbi/RSQLite?
