### ISSUE TITLE
All-NA argument in `coalesce` throws error unless all other arguments are type logical

### ISSUE THREAD

**Issue by wdearden** [tidyverse/dplyr#3619]
Since the default type of `NA` is `logical` and `coalesce` calls `check_type`, if one argument is `NA` then `coalesce` will throw an error.

```
dplyr::coalesce(NA, 1)
# Error: Argument 2 must be type logical, not double
dplyr::coalesce(1, NA)
# Error: Argument 2 must be type double, not logical
dplyr::coalesce(NA, TRUE)
# [1] TRUE
dplyr::coalesce(NA_real_, 1)
# [1] 1
```

If this error is intentional, I can write a PR with a test to expect this error. If it's not, I can write a PR to skip type checking for all-NA arguments.

**Comment by hadley** [comment]
I'd rather leave this until we have a better general purpose system for coercing types. Then we'll fix all vector functions in one fell swoop.

**Comment by Williampio** [comment]
Enviado desde mi iPhone

**Comment by romainfrancois** [comment]
#4389
