### ISSUE TITLE
Reconsider auto-dropping matching columns in nest_join

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3620]
I confused myself during a talk

**Comment by hadley** [comment]
One reason that it's nice to leave the join column (or at least have the option to) is that you can more easily see what each component consists of

**Comment by romainfrancois** [comment]
I'm not sure what you mean 😬

**Comment by hadley** [comment]
In the nested column, we appear to be removing the `by` columns

**Comment by romainfrancois** [comment]
Will that break the nest_join()+unnest()

**Comment by hadley** [comment]
I think we should resolve that in `unnest()`.  But maybe make it an option (defaulting to `FALSE`) for now?
