### ISSUE TITLE
nest_by

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3622]
so that `nest_by(...)` is equivalent to `group_by(...) %>% nest()` 

Here is a draft implementation in R: 

``` r
library(tidyverse)

nest_by <- function(.data, ..., .key = "data"){
  key_var <- quo_name(enexpr(.key))
  g <- group_by(.data, ...)
  rows <- group_rows(g)
  
  to_nest <- select(ungroup(g), setdiff(tbl_vars(g), group_vars(g)))
  
  g %>% 
    group_data() %>% 
    select(-.rows) %>% 
    mutate( !!key_var := map(rows, ~to_nest[.x,, drop = FALSE]) )
  
}
nest_by(iris, Species)
#> # A tibble: 3 x 2
#>   Species    data             
#>   <fct>      <list>           
#> 1 setosa     <tibble [50 × 4]>
#> 2 versicolor <tibble [50 × 4]>
#> 3 virginica  <tibble [50 × 4]>
```

**Comment by romainfrancois** [comment]
potentially makes more sense in tidyr

**Comment by krlmlr** [comment]
I often use `iris %>% nest(-Species)`, which has the same effect.

**Comment by romainfrancois** [comment]
Of course, but the focus is different. nest_by positively selects the variables to nest by, instead of nest that selects the variables that are nested, or negatively those to nest by.

**Comment by hadley** [comment]
And there's a nice parallel between `group_by()` + `group_vars()` and `nest_by()`
