### ISSUE TITLE
select() error message is a little confusing

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidyverse/dplyr#3631]
Trying to `select()` a column name that doesn't exists in the data.frame results in an error message I feel could be made more clear.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
select(iris, wrongname)
#> Error in .f(.x[[i]], ...): object 'wrongname' not found
```

Something like "The data.frame doesn't contain column with name 'wrongname'." or "Column of name 'wrongname' doesn't exist in data.frame, please double check spelling of selected variables." would point the user in the right direction. This problem is especially common when column names are selected with wrong cases.

 ``` r
select(iris, sepal.length)
#> Error in .f(.x[[i]], ...): object 'sepal.length' not found
```

**Comment by hadley** [comment]
This is not currently possible due to technical limitations, but you can rest assured that we are aware of the problem.
