### ISSUE TITLE
MS SQL mutate(ifelse()) translation not working

### ISSUE THREAD

**Issue by bogdanrau** [tidyverse/dplyr#3632]
Duplicate issue filed under dbplyr before I realized I should file here. https://github.com/tidyverse/dbplyr/issues/93

I'm running into an issue when using mutate and ifelse (or if) on a SQL Server backend. The following sample query:
```
df <- tbl(con, in_schema("schema", "table_name")) %>%
   mutate(field = ifelse(field %in% c('test1', 'test2', 'test3'), 'string1', 'string2') %>%
   collect()
```

... will give the following translation:

```
SELECT CASE WHEN (("field" IN ('test1', 'test2', 'test3')) = 'TRUE') THEN ('string1') 
            WHEN (("field" IN ('test1', 'test2', 'test3')) =  'FALSE') THEN ('string2') 
            END AS "field"
```

Which will return an error. The correct translation should be:

```
SELECT CASE WHEN ("field" IN ('test1', 'test2', 'test3')) THEN 'string1' 
            WHEN ("field" NOT IN ('test1', 'test2', 'test3')) THEN 'string2' 
            END AS "field"
```

Will correcting this in the mssql_if function create any issues in other queries, or is there a better way to do mutate(ifelse()) in mssql?

https://github.com/tidyverse/dbplyr/blob/477480e3c488fe6338ce5f142142d280dd61487b/R/db-odbc-mssql.R#L225

**Comment by bogdanrau** [comment]
Anybody? I'm thinking of just making that change but can't figure out if it'll have cascading effects on other queries. @edgararuiz ?

**Comment by edgararuiz** [comment]
Hi, yes, I think that may have cascading effect, let me take a closer look and close the loop by Friday

**Comment by bogdanrau** [comment]
Thanks Edgar! I can do some testing if you need help with that.
