### ISSUE TITLE
Unexpected output for glimpse for an empty list

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#3633]
I'm using `tibble::glimpse` to print out the entire row of a data frame. Some of the columns are list columns, and the output for cells with empty lists is unexpected.

``` r
library(tidyverse)

starwars %>% 
  slice(2) %>%
  glimpse()
#> Observations: 1
#> Variables: 13
#> $ name       <chr> "C-3PO"
#> $ height     <int> 167
#> $ mass       <dbl> 75
#> $ hair_color <chr> NA
#> $ skin_color <chr> "gold"
#> $ eye_color  <chr> "yellow"
#> $ birth_year <dbl> 112
#> $ gender     <chr> NA
#> $ homeworld  <chr> "Tatooine"
#> $ species    <chr> "Droid"
#> $ films      <list> [<"Attack of the Clones", "The Phantom Menace", "R...
#> $ vehicles   <list> [<>]
#> $ starships  <list> [<>]
```

Created on 2018-06-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by romainfrancois** [comment]
🤷‍♂️ @krlmlr can you invite me to tibble or run the bot command. (bit weird that we need write permission to the target repo to open an issue)

**Comment by krlmlr** [comment]
@hadley: I don't have access to tibble's repo setting, would you mind adding Romain to tibble?

**Comment by romainfrancois** [comment]
Maybe this is just something to tweak in the org or the bot settings @batpigandme.

**Comment by batpigandme** [comment]
@romainfrancois I think the write access bot setting makes sense, other than in this case, if that makes sense…

**Comment by batpigandme** [comment]
@hadley if we were to change a setting, I would think it would be the default repository permission for tibble
![image](https://user-images.githubusercontent.com/831732/41031023-a3c0e47a-694d-11e8-831b-0f4827fd221a.png)

**Comment by romainfrancois** [comment]
We might not need to do anything thanks to https://github.com/dessant/move-issues/issues/3
