### ISSUE TITLE
access git revision of currently running dplyr

### ISSUE THREAD

**Issue by jangorecki** [tidyverse/dplyr#3635]
I would like to know from inside the code which dplyr git revision I am running at the moment. So I can easily confirm I am on proper branch/revision when testing some new features/bug fixes.
Is it possible in dplyr? If it isn't I would like this issue to be FR for such functionality. Just git commit hash is enough.

**Comment by krlmlr** [comment]
This information is available if you install the package from GitHub via `devtools::install_github()`. Then, `devtools::session_info()` should show the SHA1 of the Git revision. Does it work for you?

**Comment by jangorecki** [comment]
perfect
```r
dplyr.git = function() {
  dcf = read.dcf(system.file("DESCRIPTION", package="dplyr"), fields="RemoteSha")
  toString(dcf[, "RemoteSha"])
}
```
this works for me
