### ISSUE TITLE
case_when generating unnecessary warnings

### ISSUE THREAD

**Issue by psychelzh** [tidyverse/dplyr#3637]
A brief description of the problem

```r
x <- -5.1:5.1
dplyr::case_when(
  x >= 0 ~ sqrt(x),
  TRUE ~ x
)
#> Warning in sqrt(x): NaNs produced
#>  [1] -5.1000000 -4.1000000 -3.1000000 -2.1000000 -1.1000000 -0.1000000
#>  [7]  0.9486833  1.3784049  1.7029386  1.9748418  2.2135944
```

I might think it is best to do `sqrt()` for those numbers no less than 0, but it is not. Why should it behave in this way? Is there a walkaround?

**Comment by hadley** [comment]
This is a fundamental part of the way `case_when()` works. We need to make that more clear in the docs.

**Comment by psychelzh** [comment]
Thanks! Only it is very distractive in this circumstances, which leads me to wonder whether there is really an error.

**Comment by psychelzh** [comment]
What's more, I have found `if_else` behaves like `case_when`. For example,

```r
if_else(FALSE, stop("Stops it!"), "Error-proof.")
# Error in if_else(FALSE, stop("Stops it!"), "Error-proof.") : 
#  could not find function "if_else"
```

The behavior for `ifelse` will not throw an error.

```r
ifelse(FALSE, stop("Stops it!"), "Error-proof.")
# "Error-proof."
```

**Comment by krlmlr** [comment]
I'm seeing:

``` r
dplyr::if_else(FALSE, stop("Stops it!"), "Error-proof.")
#> Error in dplyr::if_else(FALSE, stop("Stops it!"), "Error-proof."): Stops it!
```

> Created on 2018-06-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Both branches are always evaluated, even if one of them isn't needed at all. That should be part of the documentation too.

**Comment by psychelzh** [comment]
Yes. That will make users informed, and make a choice between `ifelse` and `if_else`.

**Comment by hadley** [comment]
Please don't document this as the behaviour may change in the future.

**Comment by psychelzh** [comment]
Okay. @hadley

**Comment by krlmlr** [comment]
Can we document it but note that the behavior may change? After all it's existing behavior, and potentially surprising too.

**Comment by psychelzh** [comment]
Hi, @hadley @krlmlr These days I found again current behavior of `case_when` is sort of like chicken ribs. Error does occur when very different functions are applied to different branches. But that will be unnecessary and thus makes the usage of `case_when` much more limited. So I do think for each branch, only the part of data matching the condition of that branch should be evaluated in the function. I am looking forward to the behavior change of `case_when`, and, likely, `if_else`. Thanks!

**Comment by hadley** [comment]
I’m now confident that every branch of a case_when or if_else must be evaluated in order for the result to have a stable type.

**Comment by krlmlr** [comment]
Does this mean we can document the behavior that all branches are evaluated?

**Comment by Nihasa** [comment]
I find that this is more than just a distraction. Some of the branches might be more computationally intensive than others and if one has to evaluate all cases for a large dataset, it can really slow things down. 
Additionally, if any of your cases have global level side effects, they can be overwritten by cases that should not be evaluated. I know that this is likely not the intended use, but without a neon warning sign, you have to troubleshoot that kind of problem on your own.
e.g. 
case_when(
my_cond == TRUE ~ x->>y,
TRUE ~ print(x)
)

Anyways, all that to say that I think there are valid situations where I would give up built in type stability and coerce it myself.

**Comment by psychelzh** [comment]
I think it should be supported that only rows matching the condition of one branch should be evaluated by the function of that branch. Just like the example in the first post,

```r
x <- -5.1:5.1
dplyr::case_when(
  x >= 0 ~ sqrt(x),
  TRUE ~ x
)
#> Warning in sqrt(x): NaNs produced
#>  [1] -5.1000000 -4.1000000 -3.1000000 -2.1000000 -1.1000000 -0.1000000
#>  [7]  0.9486833  1.3784049  1.7029386  1.9748418  2.2135944
```

Those rows less than 0 should not be evaluated by `sqrt`. Will this be possible?

**Comment by hadley** [comment]
It is not possible, sorry.

**Comment by psychelzh** [comment]
I have come out a workaround to do that job. I still want to know if there is official method to complete the type of `case_when` I wanted.
