### ISSUE TITLE
Namespace C++ call to sort

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3644]
https://github.com/r-lib/conflicted/issues/8#issuecomment-395228008

**Comment by krlmlr** [comment]
Will add to 0.7.6.

**Comment by romainfrancois** [comment]
@krlmlr we have a 0.7.6 branch ?

**Comment by krlmlr** [comment]
I'll open one based on v0.7.5, fix three urgent issues that don't touch much code and then submit to CRAN.
