### ISSUE TITLE
Code of Conduct path not working properly with usethis

### ISSUE THREAD

**Issue by filipefilardi** [tidyverse/dplyr#3649]
[Code of Conduct path](https://github.com/tidyverse/dplyr/pull/3580/commits/c94ca005873430a6d10501f5456fe5bd11e54499) with the same path in [usethis](https://github.com/r-lib/usethis/blob/44bbf646ebcc2dd5a0d739ba04fe3727f788ff3f/R/code-of-conduct.R#L19) is breaking CI in #3580

**Comment by batpigandme** [comment]
Is there any reason to think it wouldn't do this for other repos? If not (i.e. this will be a problem in all repos in which it is used), can you file an issue in usethis please?

**Comment by filipefilardi** [comment]
Depends, do you think this problem is related to [.Rbuildignore]?(https://github.com/filipefilardi/dplyr/commit/63570a97a98a661d90a01f66d6dd21c9e33c469d)

I'm not sure how usethis works but after looking in another repositories i found it.

**Comment by batpigandme** [comment]
Yeah, but everything under `.github/` is .Rbuildignore(d)
https://github.com/tidyverse/dplyr/blob/8bd650a9a3784c0ec49448c07dc7c51b3b5f8795/.Rbuildignore#L36

**Comment by filipefilardi** [comment]
But Code of Conduct isn't under `\.github`, is it?

**Comment by batpigandme** [comment]
Yes it is. See in usethis repo, too. And it shows up if you go to submit an issue there as well.

**Comment by batpigandme** [comment]
Yup
