### ISSUE TITLE
corrupt grouped_df issue with bind_rows_() on Fedora 27/R 3.4.4/tidyverse 1.21.9000

### ISSUE THREAD

**Issue by kartiksubbarao** [tidyverse/dplyr#3652]
[ Wasn't sure whether to submit this to multidplyr or here, but decided to post it here since I noticed other dplyr issues with the same error message ]

I'm running into a corrupt grouped_df issue with the following code. The error goes away if I decrease the 100000 number to somewhere around 40000 or lower, or if I increase the number of cores:

```r
#! /usr/bin/Rscript

library(tidyverse)
library(multidplyr)

f = function(a=0, PARTITION_ID) {
  t = as_tibble(list(a=1, b=2))
  return(list(t=list(t)))
}

cluster = create_cluster(cores = 2)
#> Initialising 2 core cluster.
t = as_tibble(rep(1, 100000))
colnames(t) = "a"
t = partition(t, cluster = cluster)
cluster_library(cluster, c("tidyverse"))
cluster_copy(t, f)
t = do(t, pmap_dfr(., f)) %>% collect
#> Error in bind_rows_(x, .id): `.data` is a corrupt grouped_df
```

Created on 2018-06-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
```

**Comment by kartiksubbarao** [comment]
Looks like 79d158a6b62a0c71b5a27ea67d80d6a92da4d7ea fixed the problem outright! If I run `master` as-is, I don't get any errors. If I revert line 515 of `src/group_indices.cpp` from `static String rows ...` back to `static SEXP rows ...`  I get this error:

    `.data` is a corrupt grouped_df, the `"groups"` attribute must have a list column named `.rows` as last column

So it looks like the fix on line 515 did the trick :-)

**Comment by krlmlr** [comment]
Great, thanks!
