### ISSUE TITLE
dplyr left_join only outputs the left column from the "by" condition.

### ISSUE THREAD

**Issue by jblivongo** [tidyverse/dplyr#3654]
I have noticed that dplyr::left_joins only preserve one of the join variable columns. All columns not used in the join are preserved from both sides.  This is behavior is not what I would expect based on the docs:

https://dplyr.tidyverse.org/reference/join.html 
> left_join()
return all rows from x, and _**all columns from x and y**_. Rows in x with no match in y will have NA values in the new columns. If there are multiple matches between x and y, all combinations of the matches are returned.

There are fine workarounds for this (like duplicated the join column before the join).  But it seems cleaner to return all columns and then let people select down if they want to.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#Column y is not represerved post join 
#(in SQL you can have both the right and left columns in the select list)
df1 <- data.frame(x=1:10)
df2 <- data.frame(y=c(2,5,8),z=c(1,2,3))
dplyr::left_join(df1, df2, by=c("x"="y")) 
#>     x  z
#> 1   1 NA
#> 2   2  1
#> 3   3 NA
#> 4   4 NA
#> 5   5  2
#> 6   6 NA
#> 7   7 NA
#> 8   8  3
#> 9   9 NA
#> 10 10 NA
```

**Comment by romainfrancois** [comment]
This is what `by=c("x"="y")` means, the column "x" from the lhs is the "y" column from the rhs, so it does not make sense to keep them both. 

The wording you quote is more about keeping columns "a" and "z" as well as "x" in this example: 

``` r
library(dplyr, warn.conflicts = FALSE)
df1 <- data.frame(x=1:10, a = letters[1:10])
df2 <- data.frame(y=c(2,5,8),z=c(1,2,3))
dplyr::left_join(df1, df2, by=c("x"="y")) 
#>     x a  z
#> 1   1 a NA
#> 2   2 b  1
#> 3   3 c NA
#> 4   4 d NA
#> 5   5 e  2
#> 6   6 f NA
#> 7   7 g NA
#> 8   8 h  3
#> 9   9 i NA
#> 10 10 j NA
```
