### ISSUE TITLE
Feature Request: Make between Generic

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#3655]
I often need to find values between other values when the original value is not numeric.  As an example:

```r
between("2018-06-01", "2018-05-01", "2018-05-31")
```

Could `between` be made generic-- perhaps also including methods for character and POSIXt?

**Comment by romainfrancois** [comment]
Related to #3540 and #2995

**Comment by romainfrancois** [comment]
Closing this in favor of https://github.com/r-lib/vctrs/issues/147
