### ISSUE TITLE
Documentation Suggestion: Suggest link between coalesce, na_if and replace_na

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#3656]
It'd be helpful to have a link to show that `tidyr::replace_na`, `dplyr::coalesce`, and `dplyr::na_if` have complementary functions.  Can you please add a See Also section entry linking all of them?

And it would also be useful to see `dplyr::recode` in the See Also section for `dplyr::na_if` and `tidyr::replace_na`.

(The same was just suggested as an issue in tidyverse/tidyr#461.)

**Comment by hadley** [comment]
Would you like to do a PR?

**Comment by billdenney** [comment]
Done!
