### ISSUE TITLE
CRAN release 0.7.6

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3658]
* [x] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [x] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`
* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::check_win_devel()` (again!)
* [x] `devtools::submit_cran()`
* [x] `pkgdown::build_site()`
* [x] Approve email
* [x] Tag release
* [x] Bump dev version
* [ ] Write blog post
* [ ] Tweet

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by hadley** [comment]
This is now done?

**Comment by krlmlr** [comment]
Still need to build site, will send a PR later today.

**Comment by krlmlr** [comment]
Done in dbbb91877.
