### ISSUE TITLE
filter() discards rownames

### ISSUE THREAD

**Issue by kforner** [tidyverse/dplyr#366]
Hello,

filter() does discard rownames, e.g.:

> rownames(filter(mtcars, cyl == 4))
>  [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11"
> rownames(mtcars[mtcars$cyl == 4, ])
>  [1] "Datsun 710"     "Merc 240D"      "Merc 230"       "Fiat 128"  
>  [5] "Honda Civic"    "Toyota Corolla" "Toyota Corona"  "Fiat X1-9"  
>  [9] "Porsche 914-2"  "Lotus Europa"   "Volvo 142E"    

Is it on purpose, a limitation or planned ? 
I could not find any explanation in the documentation.

Thanks
Karl

**Comment by ronammar** [comment]
Is it possible to include a flag to instruct dplyr functions to include rownames?

**Comment by hadley** [comment]
No, sorry.

**Comment by liyun831229** [comment]
keep row names is really important

**Comment by DNB86** [comment]
Use subset() instead ...
