### ISSUE TITLE
Include an add_pct functionality similar to add_count or count

### ISSUE THREAD

**Issue by dylanjm** [tidyverse/dplyr#3664]
Ever since learning about the `count()` or `add_count()` function in dplyr, I've had a lot more clean and concise pipe statements. A functionality that I think would be relatively easy to code up and create more explicit pipe statements is to add an `add_pct()` function to go the one more extra step and compute percent of a group observations. 

---

Something similar to:

```r
iris %>% 
  count(Species) %>% 
  mutate(n_pct = n/sum(n))

# A tibble: 3 x 3
  Species        n n_pct
  <fct>      <int> <dbl>
1 setosa        50 0.333
2 versicolor    50 0.333
3 virginica     50 0.333
```

**Comment by romainfrancois** [comment]
I think this is out of scope for `dplyr` and can be easily enough done in another 📦.
