### ISSUE TITLE
Suggestion: Multi replace function

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidyverse/dplyr#3668]
I was thinking of this function that would act as this multi replace function. It would replace multiple values depending on values in a different data structure. I'm sure this has a proper name, but I'm running into a chicken and egg problem.

This suggestion is best displayed with an example: Supposed you have a data.frame where one of the variables Is a mix between good values and bad values that you have the correct corresponding good values for. In this example Is there a mix between full country names and iso codes. It would be a pain to set up all the necessary ifelse statements.

``` r
df <- data.frame(num = 1:10,
                 name = c("Canada", "MX", "Ireland", "DK", "US",
                          "Sweden", "Australia", "Canada", "Canada", "Canada"),
                 stringsAsFactors = FALSE)

index <- data.frame(from = c("MX", "DK", "US", "DE"),
                    to = c("Mexico", "Denmark", "United States", "Germany"),
                    stringsAsFactors = FALSE)
```

We would like the `df` data.frame to be all full country names. The following `all_replace` is an adhoc example of the function.

``` r
library(dplyr)
all_replace <- function(tbl, reference, tbl_match, ref_match, ref_out) {
  by_vector <- ref_match
  names(by_vector) <- tbl_match
  joined_df <- left_join(tbl, reference, by = by_vector)
  
  ifelse(is.na(joined_df[[ref_out]]), 
         joined_df[[tbl_match]], 
         joined_df[[ref_out]])

}
```
Which when used would result in the following:

``` r
df %>%
  mutate(name = all_replace(., index, "name", "from", "to"))
#>    num          name
#> 1    1        Canada
#> 2    2        Mexico
#> 3    3       Ireland
#> 4    4       Denmark
#> 5    5 United States
#> 6    6        Sweden
#> 7    7     Australia
#> 8    8        Canada
#> 9    9        Canada
#> 10  10        Canada
``` 

I don't know if this kind of function is within the scope of `dplyr` but I feel like it is a problem that occurs for time to time.

**Comment by cderv** [comment]
`dplyr` already have a `recode` function that could be use for the use case you are describing.

`recode` applies on a vector and describe as a vectorized version of base `switch`. Replacement can be done by name (or position in specific cases). 

Here is how it can be done in your example. Two things: 

* index must be a named vector not a dataframe. `tibble::deframe` allows to transform a two columns tibble in a named vector
* `recode` use tidy_dots to take the replacement values. `!!!` must be used to _unquote-splice_ the object containing the replacements here indexv. 

``` r
library(dplyr, warn.conflicts = FALSE)
df <- data_frame(num = 1:10,
                 name = c("Canada", "MX", "Ireland", "DK", "US",
                          "Sweden", "Australia", "Canada", "Canada", "Canada"))

index <- data_frame(from = c("MX", "DK", "US", "DE"),
                    to = c("Mexico", "Denmark", "United States", "Germany"))

# use a named vector. Need to deframe as we have a index data.frame
indexv <- index %>%
  tibble::deframe()
indexv
#>              MX              DK              US              DE 
#>        "Mexico"       "Denmark" "United States"       "Germany"

# we need to use tidy_dots to give the replacement
df %>%
  mutate(name = recode(name, !!! indexv))
#> Warning: le package 'bindrcpp' a été compilé avec la version R 3.4.4
#> # A tibble: 10 x 2
#>      num name         
#>    <int> <chr>        
#>  1     1 Canada       
#>  2     2 Mexico       
#>  3     3 Ireland      
#>  4     4 Denmark      
#>  5     5 United States
#>  6     6 Sweden       
#>  7     7 Australia    
#>  8     8 Canada       
#>  9     9 Canada       
#> 10    10 Canada
```

Created on 2018-06-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

`recode` does multi-replacement: Is it something that could play well for the problems that occurs from time to time ?

**Comment by EmilHvitfeldt** [comment]
That is exactly was I was looking for! Sorry for the issue.
