### ISSUE TITLE
Docs: `rename` needs more detail

### ISSUE THREAD

**Issue by kenahoo** [tidyverse/dplyr#3676]
It would be useful in the docs to say whether the old name is supposed to go on the LHS and the new name on the LHS of the equal signs, or vice versa.

**Comment by romainfrancois** [comment]
Fair enough. Would you like to work on a pull request ?

**Comment by kenahoo** [comment]
Can do.  I think there are some other docs that could be more explicit too, in theory would you be up for several at once?

**Comment by romainfrancois** [comment]
Sure. Might take more time to review it when the PR is big, but that's ok. Thanks.

**Comment by hadley** [comment]
And you're better off starting with a couple of smaller things so that you get some initial feedback and can check that you're heading the right direction.

**Comment by kenahoo** [comment]
PR opened, feel free to pick & choose from it, and/or ask for changes.

**Comment by dpprdan** [comment]
PR #3689 has been merged, so this can be closed, right?

**Comment by romainfrancois** [comment]
Yes. Thanks.
