### ISSUE TITLE
if_else can't output closure objects

### ISSUE THREAD

**Issue by andrewjpfeiffer** [tidyverse/dplyr#3677]
I want to use `dplyr::if_else` to output a function object, which is of type `closure`. It's easy to see why this returns an error from the source code of the function and the error message. However, the same construct works with `base::ifelse`.

```r
typeof(mean)
#> [1] "closure"
my_function <- dplyr::if_else(TRUE, mean, median)
#> Error in true[rep(NA_integer_, length(condition))]: object of type 'closure' is not subsettable
my_function <- ifelse(TRUE, mean, median)
```

**Comment by hadley** [comment]
I don’t think it makes sense to use ifelse with functions because they are not vectors. You just need an inline if.
