### ISSUE TITLE
relational tibbles - does it need to be joined?

### ISSUE THREAD

**Issue by ramongallego** [tidyverse/dplyr#3680]
I work with relatively large datasets: the main tibble is a tidy, long tibble (millions of rows) with three columns: Sample, Hash, number of occurrences. Each row is an observation. In order to plot, model, etc, I need to group samples according to their metadata, and hence there is another tibble with as many rows as samples (~100 rows and ~10 columns: Site, Month,...).

Let's say that I want to plot a boxplot of the number of unique sequences per sample at each site. A workflow will look like

```r
require(RCurl)
library(tidyverse)

long_tibble<- read_csv(file = getURL("https://raw.githubusercontent.com/ramongallego/dplyr_question/master/example_long_tible.csv") )

factor_tibble <- read_csv (file = getURL("https://raw.githubusercontent.com/ramongallego/dplyr_question/master/example_factor_tible.csv"))

together<- left_join(long_tibble, factor_tibble) 

ggplot (data = together, aes (x= Site, y = nunique)) + 
  geom_boxplot(data = together %>%
 group_by(sample, Site) %>%
 summarise(nunique = n_distinct(Hash)))

```
My question is - and apologies if this is not the right forum to ask it - is whether I need to join all data in a unique tibble, or if I can tell tidyverse to look for the group_by grouping outside the tibble. 

My guess is that for every new column added to the long table we increase the size of the file by a lot so I was wondering which is the most 'tidy' way of dealing with relational tibbles

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
