### ISSUE TITLE
multiple test affected by group_by

### ISSUE THREAD

**Issue by htc502** [tidyverse/dplyr#3682]
I am wandering if anyone forget to add "ungroup" before doing multiple test correction like me?
code like this:

```r
wilcT.res = Expression %>%
  group_by(gene_id) %>%
  do(broom::tidy(wilcox.test(.$Exp~.$Group))) %>%
  mutate(q = p.adjust(p.value,'BH'))
```

This will do multiple test correction for each gene (which means actually no multiple test correction is done). Not sure if needs to at least add a warning message here?

The right way to do it in my thought:

```r
wilcT.res = Expression %>%
  group_by(gene_id) %>%
  do(broom::tidy(wilcox.test(.$Exp~.$Group))) %>%
  ungroup() %>%
  mutate(q = p.adjust(p.value,'BH'))
```

**Comment by romainfrancois** [comment]
Please use markdown formatting in the future for better readability. 

This looks like a question that is better suited for places like community.rstudio.com
