### ISSUE TITLE
Windows: dplyr::select raises error if non-ASCII characters in column names

### ISSUE THREAD

**Issue by hidekoji** [tidyverse/dplyr#3684]
On Windows, with R3.5 and dplyr0.7.4, dplyr::select gives following error  if non-ASCII characters in column names.

Error in FUN(x[[i]], ...) : object 'フラグ' not found

---

A brief description of the problem

``` r
library(dplyr)
#> 
#>  次のパッケージを付け加えます: 'dplyr'
#>  以下のオブジェクトは 'package:stats' からマスクされています: 
#> 
#>      filter, lag
#>  以下のオブジェクトは 'package:base' からマスクされています: 
#> 
#>      intersect, setdiff, setequal, union
library(readr)
df <- readr::read_csv(file = "https://www.dropbox.com/s/glmdnph1tesmje7/non-ascii.csv?dl=1")
#> Parsed with column specification:
#> cols(
#>   フラグ = col_integer(),
#>   Test = col_integer()
#> )
df %>% dplyr::select(フラグ)
#> Error in FUN(X[[i]], ...):  オブジェクト 'フラグ' がありません
```

It works fine on R3.4 + dplyr 0.7.4. also it works fine on Mac even with R3.5 + dplyr 0.7.4

**Comment by romainfrancois** [comment]
This works fine for me: 

```r
> library(dplyr)
> library(readr)
> df <- readr::read_csv(file = "https://www.dropbox.com/s/glmdnph1tesmje7/non-ascii.csv?dl=1")
Parsed with column specification:
cols(
  フラグ = col_integer(),
  Test = col_integer()
)
> df
# A tibble: 1 x 2
  フラグ  Test
   <int> <int>
1      1     2
> df %>% dplyr::select(フラグ)
# A tibble: 1 x 1
  フラグ
   <int>
1      1
```

@krlmlr any idea ?

**Comment by krlmlr** [comment]
The behavior is likely different on Windows. Can you please update packages (in particular _rlang_ and _tidyselect_) and install _dplyr_ 0.7.5?

**Comment by hidekoji** [comment]
Thank you for the update.

I updated rlang from 0.2.0 to 0.2.1 and dplyr from 0.7.4 to 0.7.5 and now it works. (tidyselect was already latest version)

**Comment by romainfrancois** [comment]
Thanks.
