### ISSUE TITLE
Feature request: grouped operations with vectorised attributes

### ISSUE THREAD

**Issue by Enchufa2** [tidyverse/dplyr#3691]
This is a reminder about issue #2773, locked by the bot. I briefly exposed the case there, but FYI further motivation and analysis can be found in [this vignette](https://github.com/r-quantities/quantities/blob/master/vignettes/introduction.Rmd). The TLDR is that `dplyr` works fine with vectorised attributes except for grouped operations and joins (cc @edzer).

**Comment by hadley** [comment]
I'm not sure why you are re-filing. As I said, this is on our long term to do list. Another issue does not help.

**Comment by Enchufa2** [comment]
Simply because more than a year has passed, and I would like to ask whether there are any prospects on what that *long term* could mean, or any action line open in which we could help.

I would have asked in the old issue, but it's locked. Moreover, it's locked as "resolved", and it's not.

**Comment by batpigandme** [comment]
> I would have asked in the old issue, but it's locked. Moreover, it's locked as "resolved", and it's not.

No clue why the bot is locking as resolve – working on that now (my unlock relock was just to make sure that threads were lockable without categories). Going forward there will be a message describing the intended use of the bot, we just didn't want to have it mass commenting for the initial roll-out.
