### ISSUE TITLE
afi

### ISSUE THREAD

**Issue by abouf** [tidyverse/dplyr#3701]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by batpigandme** [comment]
Hi,

Don't know if you meant to submit this or not – I'm going to close it for lack of information…

😶
