### ISSUE TITLE
Feature Request (or Documentation and Error Message Request): Vectorize between

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#3703]
`between` currently appears to only support scalar values for `left` and `right`.  It would be helpful to have `left` and `right` optionally vectorized such that any of the following would work:

``` r
library(dplyr)                    
#> Warning: package 'dplyr' was built under R version 3.4.4
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
between(1:5, c(1, 3:6), c(1, 3:6))
#> Error in between(1:5, c(1, 3:6), c(1, 3:6)): Expecting a single value: [extent=5].
between(1:5, 1, c(1, 3:6))        
#> Error in between(1:5, 1, c(1, 3:6)): Expecting a single value: [extent=5].
between(1:5, c(1, 3:6), 1)        
#> Error in between(1:5, c(1, 3:6), 1): Expecting a single value: [extent=5].
```

If this is not reasonable, it would help if both the documentation and error messages were updated.  The documentation for `left` and `right` currently says "Boundary values", but it would be more accurate to say "Boundary scalar values".  The error would be more helpful if it indicated where the single value were expected:  "Expecting a single value for 'left': [extent=5]" and "Expecting a single value for 'right': [extent=5]"

**Comment by rpruim** [comment]
I was just going to make a similar comment.

Note: this (from the documentation) is also misleading:

> This is a shortcut for `x >= left & x <= right`

**Comment by mkoohafkan** [comment]
The error you get is also hard to interpret when `between` is used inside a `mutate` statement: 

    Error in mutate_impl(.data, dots) : Evaluation error: 
      Expecting a single value: [extent=4208]..

**Comment by romainfrancois** [comment]
Closing this in favor of https://github.com/r-lib/vctrs/issues/147
