### ISSUE TITLE
Feature request: inner join on character and factor columns

### ISSUE THREAD

**Issue by jnolis** [tidyverse/dplyr#3707]
Currently when you join a character vector and a factor together the join works, but the joined column is converted into a character vector. This is definitely what you would want for most joins, but an inner join seems like it should (or at least could) have the result be a factor. By the definition of an inner join all of the results should be levels of the factor column, so it is hard to imagine situations where the user would prefer the output to be a character over a factor.

For example

```r
library(tidyverse)
base_data <-
  data_frame(raw_string = c("a","b","c","d"), 
             raw_value  = c( 1 , 2 , 3 , 4 ))
lookup_info <-
  data_frame(fancy_string = factor(c("a","b")),
             fancy_other_thing =   c(100,200))
       
inner_join(base_data, lookup_info, by = c("raw_string"="fancy_string"))
```

Gives the warning
```r
Column `raw_string`/`fancy_string` joining character vector and factor, coercing into character vector
```

But the column could be a factor with the levels of `fancy_string`.

**Comment by hadley** [comment]
The downside of this is that it would make the column type less predictable as we'd need to special case `inner_join()`. We're moving towards a consistent system of type promotion across the tidyverse, and this unfortunately moves in the wrong direction.
