### ISSUE TITLE
Use different alias for funs(), do() and source data reference

### ISSUE THREAD

**Issue by bakaburg1** [tidyverse/dplyr#3708]
Hello,

Dplyr use . as reference to the manipulated element in `*_all, *_if, *_at`, etc... function, as reference to the manipulated rows with `do()` and as reference to the source data in almost every dplyr function.

Wouldn't be useful to define different aliases for different purposes? for example `.x, .rows, .data`, so that something like this (totally invented example) is possible:

```R
Data %>% 
    group_by(Age) %>% 
    do({
        Other.Data %>% filter(Age == DF$Age) %>%
            mutate_at(vars(matches('Foo')), funs(.x > rowMeans(.rows))) %>% 
            mutate(Bar = sum(Bar > mean(.data$Bar)))
    })
```
Would prevent me to define alias before and avoid errors.

Thanks

**Comment by krlmlr** [comment]
Thanks. We already support `.env` and `.data` to disambiguate column names and variables from the local environment. Other aliases seem out of scope, I don't understand their semantics too.
