### ISSUE TITLE
Select Failure with NA Name

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#3712]
When trying to select columns from a data.frame when one name is `NA`, select fails (even when not trying to select the column named `NA`).

``` r
library(dplyr)             
#> Warning: package 'dplyr' was built under R version 3.4.4
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
foo <- data.frame(A=1, B=2)
names(foo)[1] <- NA        
names(foo)                 
#> [1] NA  "B"
foo %>%                    
select(B)                  
#> Error in select_impl(.data, vars): Column `1` cannot have NA as name
```

This is a real issue that I just ran into when trying to clean up some data from a messy source where I needed to elevate a row of the data to the column names.

**Comment by eibanez** [comment]
I don’t think it’s a bug. See https://github.com/tidyverse/dplyr/issues/3603

**Comment by billdenney** [comment]
Yes, this is a duplicate of that issue. Thanks for linking them.  I’m closing the issue here so that the discussion can happen there.
