### ISSUE TITLE
Feature Request: fill-option for bind_rows()

### ISSUE THREAD

**Issue by epetrovski** [tidyverse/dplyr#3729]
Could `bind_rows()` have a fill-option like `rbind()` on data.tables so that binding data frames with different amounts of columns and/or different column names provides an error when set to `fill = FALSE`?

Simply filling missing columns with NAs is sometimes risky.

``` r
library(data.table)
library(dplyr, warn.conflicts = FALSE)

dt_a <- data.table(a = c(1))
dt_b <- data.table(a = c(2), b = c(1))

# dplyr
bind_rows(dt_a, dt_b)
#>    a  b
#> 1: 1 NA
#> 2: 2  1

# data.table
rbind(dt_a, dt_b, fill = FALSE) # default
#> Error in rbindlist(l, use.names, fill, idcol): Item 2 has 2 columns, inconsistent with item 1 which has 1 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.

rbind(dt_a, dt_b, fill = TRUE)
#>    a  b
#> 1: 1 NA
#> 2: 2  1
```

**Comment by hadley** [comment]
That is currently outside the scope of `bind_rows()`. We may consider as part of type related overhaul, but it seems fairly unlikely.

**Comment by krlmlr** [comment]
We already have `union()` but this accepts only two operators, unlike `bind_rows()`:

``` r
library(tidyverse)
union(tibble(a = 1), tibble(a = 1, b = 2))
#> Error in union_data_frame(x, y): not compatible: Cols in y but not x: `b`.
```

> Created on 2018-08-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
