### ISSUE TITLE
Error: package or namespace load failed for ‘dplyr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):  namespace ‘Rcpp’ 0.12.14 is being loaded, but >= 0.12.15 is required

### ISSUE THREAD

**Issue by PPICARDO** [tidyverse/dplyr#3730]

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by PPICARDO** [comment]
Solved, I updated RCPP to 0.12.15.
