### ISSUE TITLE
Feature Request: case_when helping with factors

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#3731]
I occasionally need to work with factors in case_when statements.  The only way that I know to do it right now is to move to characters, do the work, and move back to factors.  It would help to have a version of `case_when` that helped specifically with factors.

Inspired by https://stackoverflow.com/questions/49572416/r-convert-to-factor-with-order-of-levels-same-with-case-when, what would you think about a solution like the following:

```r
fct_case_when <- function(.f, ...) {
  factor(dplyr::case_when(...),
         levels=levels(.f),
         ordered=is.ordered(.f))
}
```

**Comment by hadley** [comment]
This is too specialised for dplyr. It’s possible my exploration of vector types will yield a better solution, assuming at least one output contains the complete level set.
