### ISSUE TITLE
Make add_count() and add_tally() generic

### ISSUE THREAD

**Issue by mikmart** [tidyverse/dplyr#3739]
Most **dplyr** verbs are generic, which enables efficient reuse by subclasses of `tbl_df`. However, `add_tally()` and `add_count()`, wrappers of a grouped mutate (#2078), are not generic, and both return the result of a `grouped_df()` call: a `grouped_df` or just a `tbl_df`.

https://github.com/tidyverse/dplyr/blob/95845968725831e6a4f42fc78fb018781be952d7/R/count-tally.R#L145

As a result, there isn't currently a way to pass a `tbl_df` subclass object to these functions and retain its class. 

``` r
library(dplyr)
library(tibble)

df <- new_tibble(head(mtcars), subclass = "foo")
class(df)
#> [1] "foo"        "tbl_df"     "tbl"        "data.frame"

out <- df %>% add_count(gear)
class(out)
#> [1] "tbl_df"     "tbl"        "data.frame"
```

I would propose to remedy the situation by either:
1) making `add_tally()`/`add_count()` generic, enabling custom methods for subclasses; or
2) replacing the `grouped_df()` return calls with `group_by()` calls instead: then both functions would pass the input data down a chain of generic verbs, enabling indirect control over the return type _via_ `mutate`/`arrange`/`summarize`/`group_by` methods (this is what already happens with `tally`/`count`).

I have a small branch ready for a PR implementing the former [here](https://github.com/mikmart/dplyr/tree/generic-add-tally). I wouldn't mind giving a shot at implementing a different method, either. Does this sound like a reasonable feature?

**Comment by krlmlr** [comment]
Thanks. The second approach seems easiest, in particular because `group_by(df)` returns a plain data frame. A useful test case would be:

```r
con <- DBI::dbConnect(RPostgres::Postgres())
tbl <- copy_to(con, mtcars)
tbl %>% add_count(gear)
tbl %>% add_count()
```

**Comment by krlmlr** [comment]
Reprex that demonstrates the problem:

``` r
library(tidyverse)

dbplyr::memdb_frame(a = 1:3) %>%
  add_count(a)
#> Error: data is not a data frame
```

<sup>Created on 2019-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mikmart** [comment]
I finally got around to attempting a fix with #4469: the fix itself is of course very straightforward, but I never could figure out how to write a test, which always stopped me before.

**Comment by bschneidr** [comment]
Is there any plan or general interest towards making `count()` or `tally()` generics?

This could be potentially be useful for other packages, e.g. [for the `srvyr` package which makes extensive use of dplyr's generics](https://github.com/gergness/srvyr/issues/53).

**Comment by hadley** [comment]
I'd like to wait on the resolution of #4086 before making these functions generic — the main challenge is that as soon as you make a function a generic, you can no longer change the function arguments without breaking downstream packages that provide methods. And I think #4086 should resolve most issues in practice.
