### ISSUE TITLE
bind_rows does not work with sf objects

### ISSUE THREAD

**Issue by adrfantini** [tidyverse/dplyr#3741]
`bind_rows()` seems to cause issues when used with `sf` objects; I am unsure whether this is a `dplyr` or `sf` problem. I'm guessing this is related to #2457. I'm sorry if this has been discussed before.
Reprex:

```R
library(dplyr)
library(sf)
nc = st_read(system.file("shape/nc.shp", package="sf"))
bind_rows(nc, nc)
```
Returns:
```
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
In addition: Warning messages:
1: In bind_rows_(x, .id) :
  Vectorizing 'sfc_MULTIPOLYGON' elements may not preserve their attributes
2: In bind_rows_(x, .id) :
  Vectorizing 'sfc_MULTIPOLYGON' elements may not preserve their attributes
```

This of course also means that stuff like `map_dfr` is not working with `sf` objects.

**Comment by batpigandme** [comment]
You can work around this (well, to the point of just warnings) by converting the sf object to a tbl, but I think you're right in suggesting that this is part of #2457.

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.3, proj.4 4.9.3
nc <- st_read(system.file("shape/nc.shp", package = "sf"))
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs
class(nc)
#> [1] "sf"         "data.frame"
nc2 <- as_tibble(nc)
class(nc2)
#> [1] "tbl_df"     "tbl"        "data.frame"
nc_combo <- bind_rows(nc2, nc2)
#> Warning in bind_rows_(x, .id): Vectorizing 'sfc_MULTIPOLYGON' elements may
#> not preserve their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'sfc_MULTIPOLYGON' elements may
#> not preserve their attributes
```
Created on 2018-08-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by adrfantini** [comment]
Well yes converting to a table of some sort is an option, but you lose all the `sf`iness. You can convert back, it's true, but then it's just faster to use `do.call("rbind", map(...))` instead of `map_dfr(...)`.

**Comment by batpigandme** [comment]
Just offering a workaround whilst it gets sorted! 😉 But yeah, `do.call(...)` would probably be faster.

**Comment by hadley** [comment]
Yup, duplicate.
