### ISSUE TITLE
Documentation request: Clarify use of "tbls" / coercion of data.frame arguments

### ISSUE THREAD

**Issue by afdta** [tidyverse/dplyr#3743]
From the documentation for join:
`x, y    tbls to join`

From this, it's not clear if I can use base data frames (I'm 99% sure I can, but would like to be 100% sure). 

At first, I thought "tbls" might be a way to refer to data frame-like objects (i.e. tibbles AND data frames). This is because I had thought tibbles were denoted by the class "tbl_df". But then I noticed tibbles have both the classes tbl and tbl_df, which led me to wonder about the difference between tbl versus a tbl_df (this bit is probably better handled in the documentation for tibbles).

For dplyr, I'd like the documentation to more clearly spell out how dplyr methods are able to handle base data frames (e.g., created by data.frame()). I looked through the dplyr source for something to indicate that data.frame arguments are coerced to tibbles, but haven't found evidence of that yet. If this is true, please add that data.frame arguments are coerced to tibbles.

Cheers

**Comment by afdta** [comment]
Update: Using debug(inner_join) I was tipped off to the fact that inner_join has a data.frame method, so clearly data.frames are supported.

**Comment by cderv** [comment]
Just to complete with some documentation, here are all the method in `dplyr` for data.frame class
``` r
library(dplyr, warn.conflicts = FALSE)
# list all object in package dplyr
dplyr_obj <- ls("package:dplyr")
# list all method loaded for class data.fame (and delete .data.frame)
df_meth <- gsub(pattern = "\\.data\\.frame$", "", methods(class = "data.frame"))
# keep on those contains in dplyr
intersect(df_meth, dplyr_obj)
#>  [1] "anti_join"      "arrange"        "arrange_"       "as.tbl"        
#>  [5] "as.tbl_cube"    "as_data_frame"  "as_tibble"      "collapse"      
#>  [9] "collect"        "compute"        "distinct"       "distinct_"     
#> [13] "do"             "do_"            "filter"         "filter_"       
#> [17] "full_join"      "glimpse"        "group_by"       "group_by_"     
#> [21] "group_indices"  "group_indices_" "group_size"     "groups"        
#> [25] "inner_join"     "intersect"      "left_join"      "mutate"        
#> [29] "mutate_"        "n_groups"       "pull"           "rename"        
#> [33] "rename_"        "right_join"     "same_src"       "sample_frac"   
#> [37] "sample_n"       "select"         "select_"        "semi_join"     
#> [41] "setdiff"        "setequal"       "slice"          "slice_"        
#> [45] "summarise"      "summarise_"     "tbl_vars"       "type_sum"      
#> [49] "ungroup"        "union"          "union_all"
```

You can see that there is lots of verbs that applies today on data.frame, without conversion to tibble. I do not know if it will stay forever as is but you can use dplyr on data.frame without conversion. 

The whole [intro vignette](https://dplyr.tidyverse.org/articles/dplyr.html) explains how to apply dplyr on data.frame, and that, if one desire, you can use `as.tibble` to work with _tibble_ instead (which is done in the examples, mainly for printing nicely)

**Comment by batpigandme** [comment]
Hey @afdta,

Looking through some of the docs, you're right, not all of the functions (which is most of them, thx for making that @cderv) which accept traditional data frames use that language. From the [tibbles](http://r4ds.had.co.nz/tibbles.html) chapter in R for Data Science:
> In most places, I’ll use the term tibble and data frame interchangeably.

I think it's likely _more efficient_ to point out functions that _must_ take a data frame of class `tbl_df`, but we could change the docs to say a data frame or tbl for join.

``` r
library(tidyverse)
mtcars <- as_tibble(mtcars)
class(mtcars)
#> [1] "tbl_df"     "tbl"        "data.frame"
mtcars
#> # A tibble: 32 x 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>  * <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#> # ... with 29 more rows
```
Created on 2018-08-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).
