### ISSUE TITLE
Critical bug: filter 

### ISSUE THREAD

**Issue by ignacio82** [tidyverse/dplyr#3748]
I get different answers if i run `dplyr::filter(partitionGroup == 1) ` and `dplyr::filter(partitionGroup == partition)` when `partition<-1`

The following screenshot illustrates the bug:

![image](https://user-images.githubusercontent.com/1833309/43985795-4612845a-9cd8-11e8-9c5b-cf332ff6411f.png)

Alas, I cannot share that data.

**Comment by cderv** [comment]
Can you share the variable names of your data? 
By any chance, do you have a column named _partition_?

**Comment by ignacio82** [comment]
Thanks @cderv  ! That was the problem

**Comment by cderv** [comment]
Know that using _tidyevalutation_ and `!!` (bang bang) operator should solve your issue. It will evaluates `partition` outside of the tibble and will return the correct rows.
``` r
library(dplyr, warn.conflicts = FALSE)
#> Warning: le package 'dplyr' a été compilé avec la version R 3.4.4
tab <- tibble(
  partitionGroup = c(1, 1, 2, 2),
  partition = 1:4)
partition <- 1
tab %>%
  filter(partitionGroup == partition)
#> Warning: le package 'bindrcpp' a été compilé avec la version R 3.4.4
#> # A tibble: 1 x 2
#>   partitionGroup partition
#>            <dbl>     <int>
#> 1              1         1
tab %>%
  filter(partitionGroup == !!partition)
#> # A tibble: 2 x 2
#>   partitionGroup partition
#>            <dbl>     <int>
#> 1              1         1
#> 2              1         2
```

Created on 2018-08-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
