### ISSUE TITLE
join "incompatible types (integer / numeric)" with Attributes

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#3751]
I have an error identical to #2164.  The reprex there is the same as the reprex here.

My starting point is that I'm loading SAS data with `rio::import()` which uses `haven::read_sas` which automatically adds a `label` attribute to columns.  A work around for the join issue is that I can remove all labels.  Other column types which match simply get a warning "Column `STUDYID` has different attributes on LHS and RHS of join".

Could a similar warning and handling about different attributes be done for integer/numeric?

**Comment by hadley** [comment]
All of these issues will be handled once vctrs support is merged (in the next 6-9 months).
