### ISSUE TITLE
Unexpected behaviour of slice in summarize

### ISSUE THREAD

**Issue by cfhammill** [tidyverse/dplyr#3757]
Slice does not work as expected within a summarize call:

```r
library(dplyr)
f <- data_frame(a = 1:10, g = rep(1:2, each = 5))
f %>% 
  group_by(g) %>% 
  summarize(as = list(slice(f, a)))
```

outputs

```
# A tibble: 2 x 2
      g as               
  <int> <list>           
1     1 <tibble [10 × 2]>
2     2 <tibble [10 × 2]>
```

expected

```
# A tibble: 2 x 2
      g as               
  <int> <list>           
1     1 <tibble [5 × 2]>
2     2 <tibble [5 × 2]>
```

can be fixed by using `[` instead

```r
f %>% 
  group_by(g) %>% 
  summarize(as = list(f[a,])))
```

which produces the expected output. 

The unexpected behaviour is due to `a` getting picked up from the second use of `f`. Not a bug so much as a tripping hazard.

**Comment by cderv** [comment]
> The unexpected behaviour is due to a getting picked up from the second use of f.
I think this is the correct behaviour as you are using `slice(f, a)`. 

One correct way to do this would be to use the group `a` from grouped df
``` r
library(dplyr)
tab <- data_frame(a = 1:10, g = rep(1:2, each = 5))
tab <- tab %>% 
  group_by(g) %>% 
  # use a dot to get the pipe to use the previous grouped table
  summarize(as = list(slice(., a)))
str(tab)
#> Classes 'tbl_df', 'tbl' and 'data.frame':    2 obs. of  2 variables:
#>  $ g : int  1 2
#>  $ as:List of 2
#>   ..$ :Classes 'grouped_df', 'tbl_df', 'tbl' and 'data.frame':   5 obs. of  2 variables:
#>   .. ..$ a: int  1 2 3 4 5
#>   .. ..$ g: int  1 1 1 1 1
#>   .. ..- attr(*, "vars")= chr "g"
#>   .. ..- attr(*, "drop")= logi TRUE
#>   .. ..- attr(*, "indices")=List of 1
#>   .. .. ..$ : int  0 1 2 3 4
#>   .. ..- attr(*, "group_sizes")= int 5
#>   .. ..- attr(*, "biggest_group_size")= int 5
#>   .. ..- attr(*, "labels")='data.frame': 1 obs. of  1 variable:
#>   .. .. ..$ g: int 1
#>   .. .. ..- attr(*, "vars")= chr "g"
#>   .. .. ..- attr(*, "drop")= logi TRUE
#>   ..$ :Classes 'grouped_df', 'tbl_df', 'tbl' and 'data.frame':   5 obs. of  2 variables:
#>   .. ..$ a: int  1 2 3 4 5
#>   .. ..$ g: int  1 1 1 1 1
#>   .. ..- attr(*, "vars")= chr "g"
#>   .. ..- attr(*, "drop")= logi TRUE
#>   .. ..- attr(*, "indices")=List of 1
#>   .. .. ..$ : int  0 1 2 3 4
#>   .. ..- attr(*, "group_sizes")= int 5
#>   .. ..- attr(*, "biggest_group_size")= int 5
#>   .. ..- attr(*, "labels")='data.frame': 1 obs. of  1 variable:
#>   .. .. ..$ g: int 1
#>   .. .. ..- attr(*, "vars")= chr "g"
#>   .. .. ..- attr(*, "drop")= logi TRUE
```

Created on 2018-08-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).


or you can assign the `a` column you want before `slice`
``` r
library(dplyr)
tab <- data_frame(a = 1:10, g = rep(1:2, each = 5))
tab <- tab %>% 
  group_by(g) %>% 
  summarize(as = {vec <- a; list(slice(tab, vec))})
str(tab)
#> Classes 'tbl_df', 'tbl' and 'data.frame':    2 obs. of  2 variables:
#>  $ g : int  1 2
#>  $ as:List of 2
#>   ..$ :Classes 'tbl_df', 'tbl' and 'data.frame': 5 obs. of  2 variables:
#>   .. ..$ a: int  1 2 3 4 5
#>   .. ..$ g: int  1 1 1 1 1
#>   ..$ :Classes 'tbl_df', 'tbl' and 'data.frame': 5 obs. of  2 variables:
#>   .. ..$ a: int  6 7 8 9 10
#>   .. ..$ g: int  2 2 2 2 2
```

Created on 2018-08-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

As you se with `str`, the result will not be exactly the same. One will be a grouped tibble, the other a not grouped tibble. This is because first apply `slice` on the grouped tibble, the other on the original tibble.

For this specific usecase of using `slice` in summarize with `group_by`, I wonder if `tidyr::nest` is not better. 
``` r
library(dplyr)
tab <- data_frame(a = 1:10, g = rep(1:2, each = 5))
tab <- tab %>%
  tidyr::nest(-g)
#> # A tibble: 2 x 2
#>       g data            
#>   <int> <list>          
#> 1     1 <tibble [5 x 1]>
#> 2     2 <tibble [5 x 1]>
```

the `g` column will not be present twice in the data, which is a good practice I think. 

Hope it helps.

**Comment by cfhammill** [comment]
Thanks @cderv, but unfortunately this is not my actual use case, so neither `nest` nor using the `.` would solve the problem. The sliced table is another table entirely. Using standard subsetting as mentioned above does work. A combination of column binding and `nest` would work but standard subsetting is cleaner.

I guess the surprises in the example above are two-fold, variable interpolation in `summarize` does not proceed by substitution as the unwary might expect. The second is that slice uses tidy eval at all, it's seems like a pretty rare thing to have a column of indices you would want to slice by.

**Comment by romainfrancois** [comment]
Columns have priority so when you do `slice(f, a)`, the `a` stands for the `a` column from `f`.
