### ISSUE TITLE
Named .vars in mutate_at

### ISSUE THREAD

**Issue by the-knife** [tidyverse/dplyr#3758]
When using **mutate_at**, a named **.vars** creates an additional column if the name is different than the value of the element :

```r
iris_1 <- iris[1:2, 1, drop = FALSE]

# unnamed var : works as expected
iris_1 %>%
  mutate_at(
    "Sepal.Length", 
    round
  )
#>   Sepal.Length
#> 1            5
#> 2            5

# named var, same name as the value : works as expected
iris_1 %>%
  mutate_at(
    setNames("Sepal.Length", "Sepal.Length"),
    round
  )
#>   Sepal.Length
#> 1            5
#> 2            5

# named var, different name : unexpected
iris_1 %>%
  mutate_at(
    setNames("Sepal.Length", "SEPAL.LENGTH"),
    round
  )
#>   Sepal.Length SEPAL.LENGTH
#> 1          5.1            5
#> 2          4.9            5
```

**Comment by cderv** [comment]
I think this is intended : `mutate` add a variable to a tibble or modify existing one. `mutate_at` is a variant to target specific columns of a data frame to apply a transformation.  They work the same way: if you name a column with a new name, it will add the column to the existing table.

If you only want to keep the new column(s), this is the role of `transmute`. When using variante `transmute_at` with a named _vars_, you'll only keep the column specified in vars
``` r
library(dplyr, warn.conflicts = FALSE)
iris_1 <- iris[1:2, 1, drop = FALSE]
iris_1 %>%
  transmute_at(
    setNames("Sepal.Length", "SEPAL.LENGTH"),
    round
  )
#>   SEPAL.LENGTH
#> 1            5
#> 2            5
```

Created on 2018-08-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
