### ISSUE TITLE
auto print bug when tibble is loaded in a dplyr vignette

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3761]
When this vignette inside dplyr loads the tibble 📦, we get : 

```
Building dplyr vignettes
Quitting from lines 11-13 (a.Rmd) 
Error: processing vignette 'a.Rmd' failed with diagnostics:
subscript out of bounds
```

Not sure what this is. The `subscript out of bounds` message seems to come from R internals. Might be a markdown, dplyr, tibble, or something else issue. 

Minimal vignette to trigger the bug: 

````md
---
title: "autoprint bug"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{auto print bug}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(tibble)
tibble(a = 1:10)
```
````

**Comment by hadley** [comment]
Did this get resolved?

**Comment by romainfrancois** [comment]
apparently not, I've rebased #4024 and sent a job yesterday but it still fails :/

https://travis-ci.org/tidyverse/dplyr/jobs/537666716#L131

**Comment by hadley** [comment]
Resolved yet?
