### ISSUE TITLE
bind_rows quietly drops columns with duplicate names

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/dplyr#3765]
`bind_rows` quietly drops columns with duplicate names if a user passes a badly-named `data.frame` or `tibble`. A check for duplicate column names in `bind_rows` (e.g. like in `as_tibble`) would prevent this. 

```r
library(dplyr)
# simple data frame
one = tibble(a = 1:5, b = LETTERS[1:5], c = 6:10)
# reassign names with duplicates
names(one) = c("a", "b", "a")

# use bind_rows with single argument: first column gets dropped
bind_rows(one)
## # A tibble: 5 x 2
##       a b    
##   <int> <chr>
## 1     6 A    
## 2     7 B    
## 3     8 C    
## 4     9 D    
## 5    10 E    

# same thing happens with two or more arguments
bind_rows(one, one)
## # A tibble: 10 x 2
##        a b    
##    <int> <chr>
##  1     6 A    
##  2     7 B    
##  3     8 C    
##  4     9 D    
##  5    10 E    
##  6     6 A    
##  7     7 B    
##  8     8 C    
##  9     9 D    
## 10    10 E   
```

**Comment by hadley** [comment]
It's not clear to me that it should be the job of `bind_rows()` to check that you're passing it a valid data frame.

**Comment by mkoohafkan** [comment]
Actually, I'd argue that as long as `bind_rows` wants to provide broad support for objects like standard `data.frames` rather than just `tibbles`, it *hsould* be the job of `bind_rows` to check that the objects can be coerced to valid `tibbles`. Part of the issue may also be that a `tibble` won't complain when you set invalid names with duplicates using `names<-`. Hopefully this will occur less often if people get accustomed to using `tidy_names` instead of `names`, but I didn't even know `tidy_names` existed until I yesterday (also, `tidy_names` isn't re-exported by `dplyr`).

While I agree in general that users should be responsible for their own data, having this specific check in `bind_rows` is also helpful given that many users moving to the tidy approach will expect `bind_rows` to operate the same as `rbind.data.frame`, which seems to have no problem with identical names:

```
rbind.data.frame(one, one)
# follows the positional order of duplicates names which can yield bad results, but doesn't drop columns
rbind.data.frame(one,one[c(2,3,1)])
```

I came across this issue when mining HDF5 files generated by a computer model. The data itself is stored in a matrix while the row and column labels are stored in separate tables (in this case, each row is a timestamp and each column is a labeled location). The model data can get very large, and it turns out that the model doesn't mind duplicate labels for different locations. While I did figure it out eventually, a warning from `bind_rows` that some columns were being dropped would have saved me a lot of time.

**Comment by mkoohafkan** [comment]
select(one, b)
## Error in select_impl(.data, vars) : Column `a` must have a unique name
arrange(one, b)
## Error in select_impl(.data, vars) : Column `a` must have a unique name
mutate(one, foo = "bar")
## Error in select_impl(.data, vars) : Column `a` must have a unique name
bind_cols(one,one)
## # A tibble: 5 x 6
##       a b        a1    a2 b1       a3
##   <int> <chr> <int> <int> <chr> <int>
## 1     1 A         6     1 A         6
## 2     2 B         7     2 B         7
## 3     3 C         8     3 C         8
## 4     4 D         9     4 D         9
## 5     5 E        10     5 E        10

**Comment by mkoohafkan** [comment]
Fair enough. My concern isn't that `bind_rows` is giving me an "incorrect" result, just that it is doing it quietly. I don't need `bind_rows` to actually fix the issue for me, I just it want it to be loud when something isn't right. I think a simple warning that duplicate names were detected would be sufficiently loud. In the case of factors, `bind_rows` is already loud about columns with the same name but different factor levels, and then goes the extra mile by converting them to character (which is perfectly reasonable, and leaves it to the user to turn it back into a factor if they need to).

My specific problem occurred because I was getting my data from an external program, and that program allows duplicate names. Also, the column names and the column data were stored in two separate tables. I would first read in the data from one table, and then assign the column names with `names<-` based on the values in the other table. Duplicate names are pretty rare (even though they are technically allowed) and I hadn't thought to check for it because I had never come across it before. I'm now working around it by checking that the names are valid via `any(duplicated(names))`. A warning or error from `bind_rows` would have tipped me off to the problem much earlier though, and I would have been thankful for it.

**Comment by hadley** [comment]
But how did you get that data into R?

**Comment by mkoohafkan** [comment]
The data is stored in an HDF5 file. I read in a series of matrices using `package:hdf5r`: one or more *m x n* matrices of data (numeric) and an *n x 1* matrix of column labels (locations, as strings). The column names and orders are consistent across all the data matrices. I read in the data matrices and convert them to dataframes, then overwrite the column names of each dataframe with the values from the *n x 1* matrix of names using `names<-`. Lastly, I bind the dataframes together using `bind_rows`. It is at this point that one or more columns get silently dropped when there are duplicate names. I've now added a step that checks for duplicate names (and fixes them) right before I call `bind_rows`.

**Comment by mkoohafkan** [comment]
I guess https://github.com/tidyverse/tibble/issues/466 is the "upstream"solution to this issue.

**Comment by krlmlr** [comment]
The upcoming version of _tibble_ will be less restrictive about column names. Is the exact definition of the semantics of `bind_rows()` now a _vctrs_ issue, in particular for data frames with non-unique column names?

**Comment by hadley** [comment]
Moved to https://github.com/r-lib/vctrs/issues/704, since it's now vctrs job, and we do generally provide more help for data frames with duplicate names.
