### ISSUE TITLE
bind_cols() needs to use new renaming scheme

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3772]
From https://github.com/tidyverse/tibble/pull/469/commits/0940489171c974342c16e76597417326d5683743#r212790878.

**Comment by jennybc** [comment]
This instance of `as_tibble(..., validate = FALSE)` also needs to change (moving from #3786):

https://github.com/cran/dplyr/blob/fe5edb1b273e1c6f091f88bd64f627a0a2aee6f6/R/dataframe.R#L240

**Comment by hadley** [comment]
Should now be fixed by use of `vec_cbind()`
