### ISSUE TITLE
Feature Request: Automatically Elevate data.frames within data.frames

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#3779]
While working in a slightly unusual way with a data.frame earlier this evening, I found an unusual case that I think can be handled by automatic elevation to a more normal structure:

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.4.4
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

foo1 <- data.frame(A = 1:3)
foo2 <- data.frame(B = 4:6, C = 7:9)
foo3 <- data.frame(A = 10:12)
foo1$bar <- foo2
foo1
#>   A bar.B bar.C
#> 1 1     4     7
#> 2 2     5     8
#> 3 3     6     9


bind_rows(foo1, foo3)
#> Error in bind_rows_(x, .id): Argument 2 can't be a list containing data frames
```

In the above example, the error is the fact that the column named `bar` is actually a `data.frame` and not two columns named `bar.B` and `bar.C` (as I thought was the case).

It seems that when finding this structure (a data.frame within a data.frame) and trying to work with it in the tidyverse that it would be a rational help to the user to update the structure such that `foo1` has names of `c("A", "bar.B", "bar.C")` (with a warning, perhaps) and then to progress.

**Comment by hadley** [comment]
Data frame columns get a better print method in tibbles in the dev version, and [vctrs](https://github.com/r-lib/vctrs) will handle the general problem of binding data frames within data frames within data frames etc.
