### ISSUE TITLE
The help page of `arrange` says it accepts only unquoted variable names

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#3781]
`arrange` accepts expression as well, such as in `iris %>% arrange(Sepal.Width * Sepal.Length)`.

This is not mentioned in the doc nor in the examples.

**Comment by krlmlr** [comment]
This is already fixed in the dev version:

> ... Comma separated list of unquoted variable names, or expressions involving variable names. Use desc() to sort a variable in descending order.
