### ISSUE TITLE
Grouped arrange() not computed group-wise

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#3782]
`arrange` seems to be ignoring groups when variables are provided to a function.

Row-wise transformations usually used in `arrange` don't trigger this behavior, but other functions such as `order` used in the example below, or `accumulate` (used in [my real case](https://stackoverflow.com/questions/52014985/how-to-order-the-ties-in-data-so-that-the-previously-observed-value-appears-firs/)) do.

The doc doesn't help because it doesn't mention the possibility of using expressions in place of unquoted names (see https://github.com/tidyverse/dplyr/issues/3781 ).

In the example below we first build a sample dataset, which is a subset of `iris`, grouped by `Species`, with a column `order_` giving the order by group. 

When trying to sort the data frame using directly in `arrange` the call that built `order_`  we get a different output than if we simply sort by `order_`. 

I believe it might not be the intended effect, at least it does confuse me.

```r
library(dplyr)
set.seed(4)
iris2 <- iris[4:5] %>% sample_n(4) %>% group_by(Species) %>% mutate(order_ = order(Petal.Width))
iris2
#> # A tibble: 4 x 3
#> # Groups:   Species [2]
#>   Petal.Width Species    order_
#>         <dbl> <fct>       <int>
#> 1         1.3 versicolor      1
#> 2         0.2 setosa          1
#> 3         0.6 setosa          3
#> 4         0.3 setosa          2
```

I can sort this data set by `order_ ` using `arrange`, and I get the expected output (`order_` sorted within groups)

```r
iris2 %>% arrange(Species, order_)
#> # A tibble: 4 x 3
#> # Groups:   Species [2]
#>   Petal.Width Species    order_
#>         <dbl> <fct>       <int>
#> 1         0.2 setosa          1  # <= Right!
#> 2         0.3 setosa          2
#> 3         0.6 setosa          3
#> 4         1.3 versicolor      1
```

However if I use in `arrange` the call that built `order_ `, I don't get the same result :

```r
iris2 %>% arrange(Species, order(Petal.Width))
#> # A tibble: 4 x 3
#> # Groups:   Species [2]
#>   Petal.Width Species    order_
#>         <dbl> <fct>       <int>
#> 1         0.3 setosa          2  # <= Wrong!
#> 2         0.6 setosa          3
#> 3         0.2 setosa          1
#> 4         1.3 versicolor      1
```
This behaves as if the grouping was ignored, indeed I get the same result with the following :

```r 
iris2 %>% arrange(Species, order(iris2$Petal.Width))
#> # A tibble: 4 x 3
#> # Groups:   Species [2]
#>   Petal.Width Species    order_
#>         <dbl> <fct>       <int>
#> 1         0.3 setosa          2  # <= Wrong!
#> 2         0.6 setosa          3
#> 3         0.2 setosa          1
#> 4         1.3 versicolor      1
```

I tried to use the `.by_group` argument and the `.data` pronoun but the output remains the same.

```r
iris2 %>% arrange(Species, order(.data$Petal.Width))
#> # A tibble: 4 x 3
#> # Groups:   Species [2]
#>   Petal.Width Species    order_
#>         <dbl> <fct>       <int>
#> 1         0.3 setosa          2  # <= Wrong!
#> 2         0.6 setosa          3
#> 3         0.2 setosa          1
#> 4         1.3 versicolor      1

iris2 %>% arrange(.by_group = TRUE, order(Petal.Width))
#> # A tibble: 4 x 3
#> # Groups:   Species [2]
#>   Petal.Width Species    order_
#>         <dbl> <fct>       <int>
#> 1         0.3 setosa          2  # <= Wrong!
#> 2         0.6 setosa          3
#> 3         0.2 setosa          1
#> 4         1.3 versicolor      1
```

I would have expected the `order_` column to be sorted among each group, shouldn't it be ?

------------------

copy/paste code:

```r
library(dplyr)
set.seed(4)
iris2 <- iris[4:5] %>% sample_n(4) %>% group_by(Species) %>% mutate(order_ = order(Petal.Width))
iris2 %>% arrange(Species, order_)
iris2 %>% arrange(Species, order(Petal.Width))
iris2 %>% arrange(Species, order(iris2$Petal.Width))
iris2 %>% arrange(Species, order(.data$Petal.Width))
iris2 %>% arrange(.by_group = TRUE, order(Petal.Width))
````

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more (e.g. use a made up data set with only 2-3 columns and 4 rows)? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by moodymudskipper** [comment]
Thanks for bearing with me :). Hopefully it's now clearer!

**Comment by romainfrancois** [comment]
`arrange` currently does not evaluate the expressions within groups, so you get `order(Petal.Width)` with `Petal.Width` the entire column: 

```r
> iris2 %>% arrange(print(Species), print(order(Petal.Width)))
[1] versicolor setosa     setosa     setosa    
Levels: setosa versicolor virginica
[1] 2 4 3 1
# A tibble: 4 x 3
# Groups:   Species [3]
  Petal.Width Species    order_
        <dbl> <fct>       <int>
1         0.3 setosa          2
2         0.6 setosa          3
3         0.2 setosa          1
4         1.3 versicolor      1
> iris2 %>% arrange(print(Species), print(order_))
[1] versicolor setosa     setosa     setosa    
Levels: setosa versicolor virginica
[1] 1 1 3 2
# A tibble: 4 x 3
# Groups:   Species [3]
  Petal.Width Species    order_
        <dbl> <fct>       <int>
1         0.2 setosa          1
2         0.3 setosa          2
3         0.6 setosa          3
4         1.3 versicolor      1
```

but mutate does: 

```r
> set.seed(4)
> iris2 <- iris[4:5] %>% sample_n(4) %>% group_by(Species) %>% mutate(order_ = print(order(Petal.Width)))
[1] 1 3 2
[1] 1
integer(0)
```

hence the difference

**Comment by moodymudskipper** [comment]
The only documented use of arrange is to use variable names as arguments, so it's not really a bug but `arrange` is widely used with more sophisticated expressions, so IMHO it is misleading. 

My example using `.data` It is also unconsistent with `?rlang::.data` which says :

> Sometimes a computation is not about the whole data but about a subset. For example if you supply a grouped data frame to a dplyr verb, the .data pronoun contains the group subset.

**Comment by hadley** [comment]
Documentation needs a new "grouping" section that describes the `by_group` argument and how, unlike `mutate()` and `filter()`, expressions aren't evaluated per group.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)  

df <- tribble(
  ~ g, ~x,
  1, 1,
  1, 2,
  2, 1,
  2, 2,
  3, 3
)

df %>% 
  group_by(g) %>% 
  arrange(if (n() %% 2 == 0) x else desc(x))
#> # A tibble: 5 x 2
#> # Groups:   g [3]
#>       g     x
#>   <dbl> <dbl>
#> 1     3     3
#> 2     1     2
#> 3     2     2
#> 4     1     1
#> 5     2     1
```

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
