### ISSUE TITLE
no applicable method for 'recode' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

### ISSUE THREAD

**Issue by rupesh2017** [tidyverse/dplyr#3790]
a <- c("Mango","Metro","Rain","M")
 b <- c("s","h","M","MMM")
 p <- data.frame(a,b)
t <- as.tibble(p)
t[,2] <- recode(t[,2],"s"=1)
Error in UseMethod("recode") : 
  no applicable method for 'recode' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

**Comment by cderv** [comment]
`recode` is a function that applies on vector only, not data.frame or tibble as the error says. See `?recode`
You need to use it correctly on a column not on the whole table. when you use `t[, 2]`, you are subsetting the data.frame, resulting with an object data.frame. You need to either use `dplyr` workflow with `mutate` or base R with correct syntax (Note: `as.tibble` does not exist, it is `as_tibble`)
``` r
library(dplyr, warn.conflicts = FALSE)
a <- c("Mango","Metro","Rain","M")
b <- c("s","h","M","MMM")
p <- data.frame(a,b)
t <- as_tibble(p)
# using dplyr way (recommended)
t %>%
  mutate(b = recode(b, s = 1))
#> # A tibble: 4 x 2
#>   a         b
#>   <fct> <dbl>
#> 1 Mango     1
#> 2 Metro    NA
#> 3 Rain     NA
#> 4 M        NA

# using base R
t$b <- recode(t$b, s = 1)
# or 
# t[, 2][] <- recode(t[, 2, drop = TRUE], s = 1)
t
#> # A tibble: 4 x 2
#>   a         b
#>   <fct> <dbl>
#> 1 Mango     1
#> 2 Metro    NA
#> 3 Rain     NA
#> 4 M        NA
```

Created on 2018-09-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

For this kind of question, do not hesitate to ask on https://community.rstudio.com. The audience is broader with lots of people that can help you.

**Comment by rupesh2017** [comment]
thanks
