### ISSUE TITLE
Error in arrange_impl(.data, dots) :    Argument 1 is of unsupported type matrix

### ISSUE THREAD

**Issue by rupesh2017** [tidyverse/dplyr#3791]
> new_economic_value
    # A tibble: 279,566 x 8
       EVTYPE                    PROPDMG PROPDMGEXP CROPDMG CROPDMGEXP totalproperty_damage totalcrop_damage total_damage
       <chr>                       <dbl>      <dbl>   <dbl>      <dbl>                <dbl>            <dbl>        <dbl>
     1 HURRICANE OPAL/HIGH WINDS     0.1 1000000000      10    1000000            100000000         10000000    110000000
     2 THUNDERSTORM WINDS            5      1000000     500       1000              5000000           500000      5500000
     3 HURRICANE ERIN               25      1000000       1    1000000             25000000          1000000     26000000
     4 HURRICANE OPAL               48      1000000       4    1000000             48000000          4000000     52000000
     5 HURRICANE OPAL               20      1000000      10    1000000             20000000         10000000     30000000
     6 THUNDERSTORM WINDS           50            1      50       1000                   50            50000        50050
     7 THUNDERSTORM WINDS          500            1      50       1000                  500            50000        50500
     8 TORNADO                     500            1       5       1000                  500             5000         5500
     9 TORNADO                     500            1      50       1000                  500            50000        50500
    10 THUNDERSTORM WINDS/HAIL       5            1      15       1000                    5            15000        15005
    # ... with 279,556 more rows
    > new_economic_value %>% group_by(EVTYPE)%>%
    + summarise(total_damage=sum(total_damage))
    # A tibble: 125 x 2
       EVTYPE                 total_damage
       <chr>                         <dbl>
     1 ASTRONOMICAL HIGH TIDE          5  
     2 ASTRONOMICAL LOW TIDE         320  
     3 AVALANCHE                 2100286. 
     4 BLIZZARD                195871181  
     5 COASTAL FLOOD           160407181. 
     6 COASTAL FLOODING         25056300  
     7 COLD AIR TORNADO               50.0
     8 COLD/WIND CHILL            601990  
     9 DENSE FOG                    2842  
    10 DENSE SMOKE                   100

     new_economic_value %>% group_by(EVTYPE)%>%
    + summarise(total_damage=sum(total_damage))%>%
    + arrange(desc(total_damage))
    Error in arrange_impl(.data, dots) : 
      Argument 1 is of unsupported type matrix
     

I am getting error in arrange function ,
i have stormdata dataset from which i created economic dataset using select function and now new_economic_value was created using mutate function 
now i like to do arrange on it but gives error?

**Comment by JohnMount** [comment]
I suspect one or more of your columns have extra attributes set declaring them as matrices.  So it isn't a `dplyr` issue as a data isn't quite in the right format yet issue (how that happened may or may not be an issue).  I can build an  example showing the problem and also show how to clear the attributes and fix it using `mutate_if()`.

There is no indication in the `tbl` summary that any of your columns are already matrices, but I suspect one or more of them are.

Roughly what is happening is an `R` matrix can be `R` numeric vector with extra annotations.  Sub-sequences of a `R` matrix are also matrices.  They behave a lot like numbers (so you can add them, which is why the summarize worked), but I believe matrices also declare themselves as incomparable (as there different matrix orderings, and `R` doesn't know in general which one you want).  The `as.numeric()` strips out a lot of attributes, giving you a numeric vector column that behave more like what you expect.


```r
library("dplyr")

new_economic_value <- tribble(
  ~EVTYPE, ~PROPDMG, ~PROPDMGEXP, ~CROPDMG, ~CROPDMGEXP, ~totalproperty_damage, ~totalcrop_damage, ~total_damage,
  "HURRICANE, OPAL/HIGH, WINDS", 0.1, 1000000000, 10, 1000000, 100000000, 10000000, 110000000,
  "THUNDERSTORM, WINDS", 5, 1000000, 500, 1000, 5000000, 500000, 5500000,
  "HURRICANE, ERIN", 25, 1000000, 1, 1000000, 25000000, 1000000, 26000000,
  "HURRICANE, OPAL", 48, 1000000, 4, 1000000, 48000000, 4000000, 52000000,
  "HURRICANE, OPAL", 20, 1000000, 10, 1000000, 20000000, 10000000, 30000000,
  "THUNDERSTORM, WINDS", 50, 1, 50, 1000, 50, 50000, 50050,
  "THUNDERSTORM, WINDS", 500, 1, 50, 1000, 500, 50000, 50500,
  "TORNADO", 500, 1, 5, 1000, 500, 5000, 5500,
  "TORNADO", 500, 1, 50, 1000, 500, 50000, 50500,
  "THUNDERSTORM, WINDS/HAIL", 5, 1, 15, 1000, 5, 15000, 15005)

# look at column
str(new_economic_value$total_damage)

# damage the column
new_economic_value$total_damage <- as.matrix(new_economic_value$total_damage, ncol = 1)

# see difference in column
str(new_economic_value$total_damage)

# reproduce effects

# works
new_economic_value %>% group_by(EVTYPE)%>%
  summarise(total_damage=sum(total_damage))

# errors-out
new_economic_value %>% group_by(EVTYPE)%>%
  summarise(total_damage=sum(total_damage))%>%
  arrange(desc(total_damage))
# Error in arrange_impl(.data, dots) : 
#   Argument 1 is of unsupported type matrix

# fix
new_economic_value <- new_economic_value %>%
  mutate_if(., is.numeric, as.numeric)

# works
new_economic_value %>% group_by(EVTYPE)%>%
  summarise(total_damage=sum(total_damage))%>%
  arrange(desc(total_damage))
```

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
