### ISSUE TITLE
Hybrid evaluation issue in summarise()?

### ISSUE THREAD

**Issue by dah33** [tidyverse/dplyr#3797]
Is this a bug in the hybrid evaluation of `summarise()`? I'm trying to build models by group. I don't get the expected response with `summarise()` but I do with `do()`.

``` r
library(dplyr)

# This does not work as expected
mtcars %>%
     group_by(cyl) %>%
     summarise(r2 = summary(lm(mpg ~ wt, data = .))$r.squared)
#> # A tibble: 3 x 2
#>     cyl    r2
#>   <dbl> <dbl>
#> 1     4 0.753
#> 2     6 0.753
#> 3     8 0.753

# Confirm output matches a single model applied to entire dataset
summary(lm(mpg ~ wt, data = mtcars))$r.squared
#> [1] 0.7528328

# Expected response, uses do() to subset each group
mtcars %>%
     group_by(cyl) %>%
     do(data.frame(r2 = summary(lm(mpg ~ wt, data = .))$r.squared))
#> # A tibble: 3 x 2
#> # Groups:   cyl [3]
#>     cyl    r2
#>   <dbl> <dbl>
#> 1     4 0.509
#> 2     6 0.465
#> 3     8 0.423

packageVersion("dplyr")
#> [1] ‘0.7.99.9000’
```

**Comment by krlmlr** [comment]
It seems to work if you omit the `data` argument. Can you confirm?

@lionel-: Setting `data = .data` didn't work, though. How to create a data frame from the data mask?

``` r
library(tidyverse)
mtcars %>%
  group_by(cyl) %>%
  summarise(r2 = summary(lm(mpg ~ wt))$r.squared)
#> # A tibble: 3 x 2
#>     cyl    r2
#>   <dbl> <dbl>
#> 1     4 0.509
#> 2     6 0.465
#> 3     8 0.423
```

> Created on 2018-09-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
Is this supposed to work without nest? [When I struggled to get away from `do()` a few time ago](https://community.rstudio.com/t/should-i-move-away-from-do-and-rowwise/2857/20), I learned that I had to use `nest()` and `purrr::map()`. I don't know well about data mask yet, but, `data = .data` seems a big news to me!

```r
library(dplyr)

mtcars %>%
  nest_by(cyl) %>%
  mutate(
    r2 = purrr::map_dbl(data, ~ summary(lm(mpg ~ wt, data = .x))$r.squared)
  )
```

**Comment by romainfrancois** [comment]
@dah33 `.` has no meaning for `summarise` so it is magrittr who passes it down, so it is the entire tibble. 

@krlmlr as far as I understand it `.data` is only meant to be used to extract one column with `$` or `[[`. @yutannihilation `nest_by` seems about right.  

We don't have a way to refer to the current subset of the data, i.e. what iirc `.SD` does in `data.table`. We would need I guess an `as.data.frame.rlang_data_pronoun` for it to work. 

```r
> mtcars %>%
+     group_by(cyl) %>%
+     summarise(r2 = summary(lm(mpg ~ wt, data = .data))$r.squared)

 Error: Evaluation error: cannot coerce class ‘"rlang_data_pronoun"’ to a data.frame. 
```

**Comment by moodymudskipper** [comment]
This would work :

```
.Data <- quote(with(.data, invoke_map_dfc(as.list(src))))

mtcars %>%
  group_by(cyl) %>%
  summarise(r2 = summary(lm(mpg ~ wt, data = eval(.Data)))$r.squared)
# # A tibble: 3 x 2
#     cyl        r2
#   <dbl>     <dbl>
# 1     4 0.5086326
# 2     6 0.4645102
# 3     8 0.4229655
```
