### ISSUE TITLE
`recode` does not work on labelled vector

### ISSUE THREAD

**Issue by elbersb** [tidyverse/dplyr#3800]
see previous bug report: https://github.com/tidyverse/haven/issues/400

`recode` will fail when applied to a labelled vector. The expectation seems to be that the `labelled` vector, coming from haven, will be transformed into a factor before manipulating it further, but the `labelled` class is actually a useful data structure. Because a labelled vector is just a numeric vector plus the labels, it seems like the following should work:

``` r
d <- data.frame(s = haven::labelled(c(1, 1, 2), c(Male = 1, Female = 2))) 
dplyr::mutate(d, dplyr::recode(s, `1` = 2))
#> Error in mutate_impl(.data, dots): Evaluation error: no applicable method for 'recode' applied to an object of class "labelled".
```

Created on 2018-09-03 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Can you please keep this as a haven issue?
