### ISSUE TITLE
Feature request: Unquote string character

### ISSUE THREAD

**Issue by AnthonyEbert** [tidyverse/dplyr#3801]
Most R functions use standard evaluation so the most common way to program with dplyr is a variation of the following 

```r
some_fun <- function(x){
  out <- iris %>% group_by(Petal.Length, !! sym(x) )
  return(out)
}

some_fun("Species") %>% summarise(n())
```

Convert `x` from a character to a symbol and then unquote it within a quasiquoted argument. Suppose we could do this operation `!! sym(x)` directly with one set of symbols, say `{x}` from glue, then I think the code would look nicer and be easier to understand. 

```r
some_fun <- function(x){
  out <- iris %>% group_by(Petal.Length, {x} )
  return(out)
}
```

**Comment by hadley** [comment]
I would write that as:

```R
some_fun <- function(x){
  x <- enquo(x)
  group_by(iris, Petal.Length, !!x)
}
```

It is unfortunately not possible to collapse quoting and unquoting into a single operation.

**Comment by krlmlr** [comment]
I'm curious, this seems to work for me:

``` r
library(tidyverse)

my_group_by <- function(.data, x) {
  .data %>% group_by(!!enquo(x))
}

iris %>% my_group_by(Species) %>% group_vars()
#> [1] "Species"
```

> Created on 2018-09-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Yes, it works but then you think oh, why I can't I do this:

```R
requo <- function(x) !!enquo(x)

my_group_by <- function(.data, x) {
  .data %>% group_by(requo(x))
}
``
