### ISSUE TITLE
`mutate` does not work if the global environment contains a function named `missing`

### ISSUE THREAD

**Issue by choisy** [tidyverse/dplyr#3803]
The following example from the help of the `mutate` function works as expected:

```r
mtcars %>% mutate(displ_l = disp / 61.0237)
```

However, if I happen to define in the global environment a function named `missing`, the `mutate` function doesn't work any more and returns an error. Example:

```r
missing <- function() {}
mtcars %>% mutate(displ_l = disp / 61.0237)
```

If I delete the function `missing` from the global environment, the `mutate` function works properly again:

```r
rm(missing)
mtcars %>% mutate(displ_l = disp / 61.0237)
```

... and this behavior is observed whatever the function `missing` does. Maybe a conflict issue?

**Comment by JohnMount** [comment]
Possibly not  `dplyr` issue.  I'd say `help(missing)` is wrong in that it shows code calling `missing()` (which turns out to be unsafe) instead of the qualified-form `base::missing()`.  Here is a variation of the example code from `help(missing)` showing the same problem.  User facing advice: don't override the `missing()` function.

```r
# from help(missing)
myplot <- function(x, y) {
  if(missing(y)) {
    y <- x
    x <- 1:length(y)
  }
  plot(x, y)
}

# works
myplot(sin(1:10))

missing <- function() {}

# fails
myplot(sin(1:10))

myplot2 <- function(x, y) {
  if(base::missing(y)) {
    y <- x
    x <- 1:length(y)
  }
  plot(x, y)
}

# works
myplot2(sin(1:10))
```

**Comment by romainfrancois** [comment]
I can reproduce this with the `master` branch but not with the new hybrid evaluation described in #3799. So I guess this was an hybrid issue that has been fixed for free.
