### ISSUE TITLE
Redesign interface to slice()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3804]
From https://github.com/tidyverse/dplyr/pull/3799#discussion_r215931144, we now silently gobble extra arguments to `slice()`. Need to check extra arguments or change the signature to `slice(.data, expr)` .

**Comment by hadley** [comment]
Something like this this:

```R
slice.data.frame <- function (.data, ...) {
    slice_impl(.data, c(...))
}
```
