### ISSUE TITLE
install.packages("dplyr")

### ISSUE THREAD

**Issue by riship2009** [tidyverse/dplyr#3806]
i wanna install "dplyr" package but i get this error ,

" > install.packages("dplyr")
            Warning in install.packages :
            unable to access index for repository https://cran.rstudio.com/src/contrib:
            cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
            Installing package into ‘C:/Users/user/Documents/R/win-library/3.4’
            (as ‘lib’ is unspecified)
            Warning in install.packages :
            unable to access index for repository https://cran.rstudio.com/src/contrib:
            cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
            Warning in install.packages :
            package ‘dplyr’ is not available (for R version 3.4.3)
            Warning in install.packages :
            unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.4:
            cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/PACKAGES'
>  
"

please help me .... been stuck with this for hours ......

**Comment by cderv** [comment]
Hello, 

This question is better asked on https://community.rstudio.com. There is a broader community there to help you and you'll find similar issue that has been resolve in the past. 

I invite you to consult [similar issues](https://community.rstudio.com/search?q=unable%20to%20access%20index%20for%20repository%20) and ask you question there if you do not find your solution in previous one.

Thanks.
