### ISSUE TITLE
summarize +  .preserve = FALSE ?

### ISSUE THREAD

**Issue by ldecicco-USGS** [tidyverse/dplyr#3807]
I've read and understand the reasoning behind the new behavior described here (well...at least until the Hybrid evaluation cleanup section....and maybe that's my current downfall):
https://github.com/tidyverse/dplyr/blob/master/vignettes/future/dplyr_0.8.0.Rmd

I'm wondering though if there's any way to add an argument or something to revert to the behavior that is currently on CRAN for summarize (and other summarizy functions like tally)? For example, with version 0.7.99.9000, if I run:

```r
library(dplyr)
library(ggplot2)

x <- tibble(
  x = c(0,1,0,1), 
  f1 = factor(c("a", "b", "a","b"), levels = c("a", "b", "c")),
  f2 = factor(c("d","e","d", "d"), levels = c("d","e","f"))
) 

y <- x %>%
  group_by(f1, f2) %>%
  summarize(sum_x = sum(x), .preserve = FALSE) 

nrow(y)
[1] 9

ggplot(data=y) +
  geom_point(aes(x=f1, y=sum_x)) +
  facet_grid(f2 ~ ., scales = "free") +
  theme_bw()
```
![image](https://user-images.githubusercontent.com/1105215/45319850-9d66ee80-b506-11e8-8038-75f414703232.png)

But, if I use today's CRAN version 0.7.6, I get 3 rows for y and the following graph (and in many of my use-cases, this is exactly what I want):
![image](https://user-images.githubusercontent.com/1105215/45319427-60e6c300-b505-11e8-9ec0-f9e8516b33dd.png)

In this (and many other of my cases), I only want to show the data that existed from the original tibble...and having a "0" in the sum could mean either there were 0's grouped with a f1 category...or not...and now I don't know. 

I thought based on the vignette the solution might be:
```r
y <- x %>%
  group_by(f1, f2) %>%
  filter(x > 0, .preserve = FALSE) %>%
  summarize(sum_x = sum(x)) 
```
but that still produces 9 rows of data instead of the 3 I'm looking for. In this case, I could do:
```r
y <- x %>%
  group_by(f1, f2) %>%
  summarize(sum_x = sum(x)) %>%
  filter(sum_x > 0) 
```
but... then I get:
![image](https://user-images.githubusercontent.com/1105215/45319898-c25b6180-b506-11e8-98f4-79192169905a.png)
not the same (missing that 0 sum).

**Comment by romainfrancois** [comment]
If this is what you want, that implies that you discard the factor-ness of the factors. The reasoning is that if you have structured your data with factors, you *do* want all the levels to show up in summaries. 

You can get back the behavior you had if you use character vectors instead of factors: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)

x <- tibble(
  x = c(0,1,0,1), 
  f1 = c("a", "b", "a","b"),
  f2 = c("d","e","d", "d")
) 

y <- x %>%
  group_by(f1, f2) %>%
  summarize(sum_x = sum(x), .preserve = FALSE) 

nrow(y)
#> [1] 3

ggplot(data=y) +
  geom_point(aes(x=f1, y=sum_x)) +
  facet_grid(f2 ~ ., scales = "free") +
  theme_bw()
```

![](https://i.imgur.com/fnZpZOw.png)

Created on 2018-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)
