### ISSUE TITLE
assignments inside the data mask

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3813]
This is related to #1452 but we can discuss about it again after the hybrid redesign. 

``` r
library(dplyr, warn.conflicts = FALSE)
tibble(x = 1) %>% 
  mutate(y = { xx <- 2; xx }, z = xx)
#> # A tibble: 1 x 3
#>       x     y     z
#>   <dbl> <dbl> <dbl>
#> 1     1     2     2
```

Previous versions made that an error, similar to: 

``` r
library(dplyr, warn.conflicts = FALSE)
tibble(x = 1) %>% 
  mutate(y = local({ xx <- 2; xx }), z = xx)
#> Error: Evaluation error: object 'xx' not found.
```

There are obviously ways around it, but I'm opening this issue as a place to talk about the desired behavior.

**Comment by krlmlr** [comment]
The following behavior is perhaps more surprising:

``` r
library(dplyr, warn.conflicts = FALSE)
tibble(x = 1) %>% 
  mutate(y = { x <- 2; x }, z = x)
#> # A tibble: 1 x 3
#>       x     y     z
#>   <dbl> <dbl> <dbl>
#> 1     1     2     1
```

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Looks like it would be safest to disallow assignments.

**Comment by romainfrancois** [comment]
Yeah that's a special case where the column is directly returned. However: 

```
> library(dplyr, warn.conflicts = FALSE)
> tibble(x = 1) %>% 
+     mutate(y = { x <- 2; x }, z = get("x"))
# A tibble: 1 x 3
      x     y     z
  <dbl> <dbl> <dbl>
1     1     2     2
```

Pehaps we can lock the environment

**Comment by hadley** [comment]
Or we could just declare that the using `<-` gives undefined behaviour, and document that it's not recommended?

**Comment by hadley** [comment]
The current behaviour seems reasonable to me:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = 1:2)

df %>% mutate(y = { xx <- 2; xx }, z = xx)
#> # A tibble: 2 x 3
#>       x     y     z
#>   <int> <dbl> <dbl>
#> 1     1     2     2
#> 2     2     2     2
df %>% mutate(y = { x <- 2; x }, z = x)
#> # A tibble: 2 x 3
#>       x     y     z
#>   <int> <dbl> <dbl>
#> 1     1     2     2
#> 2     2     2     2

xx
#> Error in eval(expr, envir, enclos): object 'xx' not found
x
#> Error in eval(expr, envir, enclos): object 'x' not found
```

<sup>Created on 2020-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
