### ISSUE TITLE
select does not drop variables not in the selection.

### ISSUE THREAD

**Issue by wolski** [tidyverse/dplyr#3817]
Dear Developers,

I did spend for the umpteenth time chasing a bug in my program which is related to the behavior of `dplyr::select`

The select documentation states:
"Selection drops variables that are not in the selection" but it behaves differently in the following example:

```{r}
l <- sample(letters[1:4],10,replace=10)
df <- data.frame(a = l, B=toupper(l), n = rnorm(10))
df <- df %>% group_by_at(c("a","B")) 
is.grouped_df(df)
df %>% select_at(c("a","n"))
```

After selecting only columns ("a","n") I do not expect:

```
> df %>% select_at(c("a","n"))
# A tibble: 10 x 3
# Groups:   a, B [4]
   B     a          n
   <fct> <fct>  <dbl>
 1 A     a     -1.03 
 2 A     a      1.46 
...
```

I can get it working by calling `ungroup`. But then my code ends up looking like:

```{r}
select_vars <- c("a","n")
if( !all(group_vars(df) %in% select_vars) ){
    df <- ungroup(df)
}
df %>% select_at(select_vars)
```

I feel that `select` should do what it declares to do "drops variables that are not in the selection." Keeping the grouping is all very well, but should happen only if the grouping vars are present in the selection.

kind regards
Witek

PS. Love dplyr

**Comment by romainfrancois** [comment]
Please submit a reprex, we do not have `l`: 

```
> df <- data.frame(a = l, B=toupper(l), n = rnorm(10))
Error in data.frame(a = l, B = toupper(l), n = rnorm(10)) : 
  object 'l' not found
```

**Comment by wolski** [comment]
Updated the original comment  to make it `reprex`.

**Comment by romainfrancois** [comment]
Seems related to #3480

**Comment by hadley** [comment]
I think we should a documentation fix for this

**Comment by wolski** [comment]
Why do grouping variables in a data frame should have precedence over an explicit select (not selecting)?
What is the use case for keeping the grouping vars if they are NOT selected? 
Could you please give a motivation?


Keeping variables in a data.frames when they are explicitly not selected, repeatedly had broken my code. Not having a grouping on a data frame never did. I write functions which manipulate data frames and return a data frame.

**Comment by hadley** [comment]
@wolski because many people complained when they weren't kept. Regardless of the reasoning, it is too late to change this behaviour as many people will already rely on it.

**Comment by wolski** [comment]
@hadley  
I need grouping vars only in connection with group_by/summarize and group_by/nest and write both commands usually on the same or adjacent lines. 
I would not rely on grouping vars otherwise. Just see the following example. If keeping grouping vars is so important, that even a select statement can't drop them, then I am wondering why summarise drops them?

```{r}
l <- sample(letters[1:4],10,replace=10)
df <- data.frame(a = l, B=toupper(l), n = rnorm(10))
df <- df %>% group_by_at(c("a","B"))
is.grouped_df(df)
group_vars(df)
df2 <- df %>% summarise(!!"nr" := n())
group_vars(df2)

df <- df %>% group_by_at(c("B","a"))
is.grouped_df(df)
group_vars(df)
df2 <- df %>% summarise(!!"nr" := n())
group_vars(df2)

```

generates the following output:

```
> l <- sample(letters[1:4],10,replace=10)
> df <- data.frame(a = l, B=toupper(l), n = rnorm(10))
> df <- df %>% group_by_at(c("a","B"))
> is.grouped_df(df)
[1] TRUE
> group_vars(df)
[1] "a" "B"
> df2 <- df %>% summarise(!!"nr" := n())
> group_vars(df2)
[1] "a"
> 
> df <- df %>% group_by_at(c("B","a"))
> is.grouped_df(df)
[1] TRUE
> group_vars(df)
[1] "B" "a"
> df2 <- df %>% summarise(!!"nr" := n())
> group_vars(df2)
[1] "B"
```
 

`select` as documented is _tidy_. The exceptions for keeping grouping vars make it really hard to use. 

"Strive to keep functions as simple as possible (but no simpler!). Generally, each function should do one thing well, and you should be able to describe the purpose of the function in one sentence."

**Comment by yutannihilation** [comment]
To me, it's `summarise()` the exception is; verbs can modify `data.frame`s, but they should return the same class of object as input. For example,
