### ISSUE TITLE
Potential for performance improvement in n_distinct()?

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3819]
https://github.com/tidyverse/dplyr/pull/3799/files#diff-008a2f10a80625555ffe0c9b64370a97R39

**Comment by hadley** [comment]
Unless you see any easy fix, I think this issue is now a vctrs issue (and will be tackled as part of a general performance review of hashing + dictionaries)

**Comment by krlmlr** [comment]
The fix is to insert unconditionally and then check if `NA` has been found and adjust the count accordingly. Need to make sure that we do this for _vctrs_ too, but we could also fix here.
