### ISSUE TITLE
Unresolved issues from redesign of hybrid and standard evaluation

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3822]
From #3799.

- [x] Make sure no naked `XPtr` are used in R, https://github.com/tidyverse/dplyr/pull/3799/files#diff-ad9966080c9d875d5bc39b788d52e9cdR9
- [ ] Double-check protection
    - https://github.com/tidyverse/dplyr/pull/3799/files#diff-6c2ddd5e8b6d77c35198d5ad6305b166R165
- [ ] Naming of functions that have a side effect *and* return a value
    - `DataMask::eval()` should be `DataMask::update_group_and_eval()`, but this feels clumsy
    - Perhaps avoid these functions altogether, and separate in two functions?
- [ ] `check_range_one_based()` feels misleading because of combined side effect and return value; revert to returning `void`
- [ ] Consider bringing back `get_index()` from https://github.com/tidyverse/dplyr/pull/3799/files#diff-ca7da8d879dfcf6cc318d8846ea801c3
    - avoid calling `base::match()` if not necessary
- [ ] Talk about skipped test: https://github.com/tidyverse/dplyr/pull/3799/files#diff-fab0bdbf11c34a1453a6784df41437e0R150
- [ ] Make sure that hybrid tests also check the result of the evaluation, https://github.com/tidyverse/dplyr/pull/3799/files#diff-26dc2875c1d102cbdcd1041fc6ebb1a8
    - `check_hybrid_result()` checked that evaluation was hybrid *and* that the result is correct
    - Result of `hybrid_call()` should offer a way to evaluate in hybrid
- [ ] `expect_warning(..., NA)` in https://github.com/tidyverse/dplyr/pull/3799/files#diff-03bffeb44f43927987c3313d501fe336R359
- [ ] Move test from https://github.com/tidyverse/dplyr/pull/3799/files#diff-26dc2875c1d102cbdcd1041fc6ebb1a8R526 to a better place
- [ ] Add test for setting a column to `NULL` in some groups only: https://github.com/tidyverse/dplyr/pull/3799/files#diff-7060a3128044caf1d3c4f2a2c25a5d65R832
- [x] Check for inline `Rf_install()` calls and extract to static variables, https://github.com/tidyverse/dplyr/pull/3799/files#r215951461
- [x] Simplify hybrid `first()` and `last()`, after #3821, https://github.com/tidyverse/dplyr/pull/3799/files#r215955814
- [ ] Make sure breaking changes are mentioned in `NEWS.md`
    - Empty `slice()`, https://github.com/tidyverse/dplyr/pull/3799/files#diff-b8b49bd2e356f33437111fe02c1b8edb
- [ ] Warn only once in `sum()`, https://github.com/tidyverse/dplyr/pull/3799#discussion_r215959899
- [ ] Use `int64_t` for summing integers, perhaps chunked if we support `R_xlen_t`, https://github.com/tidyverse/dplyr/pull/3799#discussion_r215961932
- [ ] Use partial specialization more sparingly, e.g. https://github.com/tidyverse/dplyr/pull/3799#discussion_r215962244 and https://github.com/tidyverse/dplyr/pull/3799#discussion_r215968171
- [ ] Double-check use of quosures, https://github.com/tidyverse/dplyr/pull/3799#discussion_r215952452

**Comment by hadley** [comment]
I'm going to close this issue given that hybrid eval is no more.
