### ISSUE TITLE
Evaluate empty cases?

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3826]
From https://github.com/tidyverse/dplyr/issues/3545#issuecomment-385150055, should we skip evaluating cases where there is no match?

``` r
library(tidyverse)

noisy_case_when <- function(..., .default = NA_character_) {
  case_when(..., TRUE ~ {
    warning("case not covered")
    .default
  })
}

noisy_case_when(
  TRUE ~ "case covered"
)
#> Warning in eval_bare(f[[3]], env): case not covered
#> [1] "case covered"
```

<sup>Created on 2018-09-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
I think this is impossible to do without changing the vectorisation properties — i.e. the RHS affects the type/shape of the output even if it doesn't affect the values. I think this will become more clear when reimplemented using the improved understanding of the problem that vctrs has yielded.
