### ISSUE TITLE
ImpalaDB: USING() on JOIN gives error because column reference is ambiguous

### ISSUE THREAD

**Issue by piersharding** [tidyverse/dplyr#383]
Hi -

I'm writing a src for ImpalaDB and have struck a problem with the example:

```
player_info <- select(tbl(lahman_impaladb(), "Master"), playerid, hofid, birthyear)
hof <- select(filter(tbl(lahman_impaladb(), "HallOfFame"), inducted == "Y"),hofid, votedby, category)
inner_join(player_info, hof)
```

The resultant SQL is:

```
select `hofid`, `playerid`, `birthyear`, `votedby`, `category` FROM (SELECT `playerid` AS `playerid`, `hofid` AS `hofid`, `birthyear` AS `birthyear` FROM `Master`) AS `nwsrxxxpxw` INNER JOIN (SELECT `hofid` AS `hofid`, `votedby` AS `votedby`, `category` AS `category` FROM `HallOfFame` WHERE `inducted` = 'Y') AS `slijllmyxg` USING (`hofid`) LIMIT 10;
Query: select `hofid`, `playerid`, `birthyear`, `votedby`, `category` FROM (SELECT `playerid` AS `playerid`, `hofid` AS `hofid`, `birthyear` AS `birthyear` FROM `Master`) AS `nwsrxxxpxw` INNER JOIN (SELECT `hofid` AS `hofid`, `votedby` AS `votedby`, `category` AS `category` FROM `HallOfFame` WHERE `inducted` = 'Y') AS `slijllmyxg` USING (`hofid`) LIMIT 10
ERROR: AnalysisException: Unqualified column reference 'hofid' is ambiguous
```

If the hofid is fully qualified as ``nwsrxxxpxw`.`hofid``, then the problem is resolved, so I was wondering if you had any suggestions for doing this in a sensible way from within build_sql() as only the `con` object is passed at the time ident values are rendered?

Thanks,
Piers Harding.

**Comment by mjacobs** [comment]
Hi, just curious- was there ever a pull request or any other discussions on this topic?

**Comment by piersharding** [comment]
Hi -

The requirements for ImpalaDB are such that it does not behave like other DB interfaces on JOINs, and ORDER BY so I always to had to modify the way that they are performed in the standard dplyr API.  This may change as the ImpalaDB (based on the Hive) interface matures, but for this reason and the reliance on the RJDBC interface (that doesn't support all the DBI features necessary) made it a better decision (IMO) to keep the implementation separate.  dplyrimpaladb is here  https://github.com/piersharding/dplyrimpaladb if you are curious.

Cheers,
Piers Harding.

**Comment by mjacobs** [comment]
Ok, thanks. Just FYI, I'm not sure it's an Impala bug. What if hofid had different types in the two tables you're joining, e.g. one is a SMALLINT and the other is an INT. Would the outer column reference have the type SMALLINT or INT? I can imagine just "picking one", but that's kind of ambiguous.

**Comment by piersharding** [comment]
With the JOIN, I would think that the optimiser should figure out what type it has used for the join (relating to the the original example I provided) and then bubble that up to the outer selection and realise that it should take one of the original selection values and cast to this to the equated type.  I don't know exactly what SQL interfaces for databases such as PostgreSQL and MySQL do, but they must figure this out some how as it 'works'.

Cheers,
Piers Harding.

**Comment by mjacobs** [comment]
The types can be comparable but there isn't necessarily a "correct" type to
use as the result. E.g. a SMALLINT and an INT can be compared, though
clearly only values that fit within a SMALLINT are possible matches. Maybe
you would choose to then use the SMALLINT as the type of the column you
selected, but there's no "correct" answer. I think either is somewhat
arbitrary. I just checked postgres, and it looks like it took the column
from the larger type (also the right side of the join).

**Comment by mjacobs** [comment]
Hi @piersharding and @hadley,

Sorry for the delay. If we were to change Impala's behavior to be compatible with what PostgreSQL, would that unblock your work on dplyrimpaladb? Would we be able to have the Impala src be merged upstream into dplyr?

Thanks,
Matt

**Comment by hadley** [comment]
@mjacobs that seems like a reasonable strategy to me

BTW since this issue, I've changed how dplyr backends work - there's now a documented interface (see the vignette) so interfaces can (and should) go in their own packages.

**Comment by piersharding** [comment]
@mjacobs ImpalaDB compatibility with PostgreSQL would be an awesome goal!  If this could be achieved, then I don't think there would be much rework for me to do on https://github.com/piersharding/dplyrimpaladb to bring it into line with @hadley 's dplyr interface.  There are some limitations with RJDBC (doesn't support all the expected functions), but it should be possible to extend this without being too brittle.
Cheers,
Piers Harding.

**Comment by mjacobs** [comment]
@piersharding Great! Just to be clear, I meant compatibility with PostgreSQL _specifically_ for this issue  where an unqualified column selects one of the two columns referenced by the using clause of an equi-join.

Thanks!
Matt

**Comment by piersharding** [comment]
@mjacobs I'll take any improvements!

Cheers.

**Comment by mjacobs** [comment]
@piersharding while we're doing this, is there anything else that might be blocking you? Other things you might need?

Thanks

**Comment by piersharding** [comment]
@mjacobs I stopped at that point, with joins as trying to fix it by anticipating how to deal with fully qualifying the table.column names when the nesting gets deeper (with multiple joins) meant that I ended up breaking the way that dplyr wanted to work naturally.  Also, while it's not ideal, it is easy to switch to using another fully supported datasource once the dataset has been paired down to a manageable size, so shifting from ImpalaDB to PostgreSQL, MySQL, or SQLite (for instance) is an option for many users.

Outside of this, there is a large dependency on rhdfs for inserts where that is used to load data as a CSV, and then move it with LOAD DATA INPATH ... to the table.   Admittedly, this isn't that important as it is unlikely that dplyrimpaladb users would do much table creation/loading.

Cheers.

**Comment by mjacobs** [comment]
@piersharding OK, thanks. I've updated an existing JIRA to track the work of selecting the non-qualified column from the equijoin, you can track it here if you're interested: https://issues.cloudera.org/browse/IMPALA-1635

Is there anything in particular you'd need from Impala for the data ingestion? I'm not sure I see the problem.

**Comment by piersharding** [comment]
OK, thanks - moving the rest of the discussion from here if it's OK with you as it's not strictly dplyr - https://github.com/piersharding/dplyrimpaladb/issues/3 .
