### ISSUE TITLE
dplyr::filter doesn't work as expected with variables named after a column

### ISSUE THREAD

**Issue by roumail** [tidyverse/dplyr#3840]
filter doesn't work as expected when using a variable for filtering that has the same name as a column

See example below when I use a variable named Sepal.Length within my filtering condition and I see unexpected behaviour. I would prefer an error in such a case...
```r
library(dplyr)

Sepal.Length <- 5
# Works
iris %>% dplyr::filter(Sepal.Length < 5) %>% nrow

# expected this to work - or give error
iris %>% dplyr::filter(Sepal.Length < Sepal.Length) %>% nrow

nrow(iris)
```

**Comment by moodymudskipper** [comment]
Doc says `These arguments are automatically quoted and evaluated in the context of the data frame`, so your `Sepal.Length <- 5` call is irrelevant here. The expressions is about the same as calling : `iris %>% dplyr::filter(.$Sepal.Length < .$Sepal.Length) %>% nrow`.

Note that `iris %>% dplyr::filter(5 < 5) %>% nrow` would give the same output.

So it seems you want `filter` to consider the lhs and rhs differently, but `Sepal.Length < Sepal.Length` is really just `'<'(Sepal.Length, Sepal.Length)`, so it would be really strange to consider arguments differently depending on their position wouldn't it ?

**Comment by batpigandme** [comment]
As @moodymudskipper mentioned, the arguments are evaluated in the context of the data frame, so you need to use tidy evaluation in order to explicitly state that you want to use a variable captured outside of that context. This is meant to avoid exactly the situation you've depicted above, where a name-value pair in the global environment is used erroneously. 

If you wanted to use `Sepal.Length` as a variable with the value 5, you can use `expr()`.
``` r
library(tidyverse)

# Works
iris %>% dplyr::filter(Sepal.Length < 5) %>% nrow
#> [1] 22

# expected this to work - or give error
Sepal.Length <- expr(5)
iris %>% dplyr::filter(Sepal.Length < !!Sepal.Length) %>% nrow
#> [1] 22
```
<sup>Created on 2018-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
In this case you don't even need the `expr()` since `5` is an scalar value.

**Comment by roumail** [comment]
Hey everyone, thanks for the response and the clarification. 

This reprex was an error I made and it took me a while to discover my mistake. The reason to post was so that next time someone makes a mistake like this, (dplyr::filter(iris, Sepal.Length < Sepal.Length)), an error is thrown since people miss things in the documentation from time to time.

**Comment by batpigandme** [comment]
So, is this a request for an error here?

The challenge is that there _are_ valid reasons to compare two columns in a dataframe, so this scenario wouldn't always be an error (even if a variable that shares the name of a data frame column has been defined in the global environment).

**Comment by roumail** [comment]
Yes, the intention was to have an error/warning to be thrown if I use a variable (from GlobalEnv) in my filter statement that has the same name as the dataframe column I'm applying the filter on:
dplyr::filter(lhs < rhs), where lhs and rhs share the same name, with lhs being a column name and rhs being a variable name. 

As mentioned by @moodymudskipper, this would translate to '<'(lhs, rhs) which would be weird if both the variables are named identically. I don't see this as the same as comparing two columns in a dataframe but maybe I didn't completely understand you there. Could you perhaps share an example of what you mean?

**Comment by batpigandme** [comment]
> have an error/warning to be thrown if I use a variable (from GlobalEnv) in my filter statement that has the same name as the dataframe column I'm applying the filter on
How would dplyr know which was which? I guess, as you describe, it could just be if you're comparing two identical things, regardless of what's in your GlobalEnv.
