### ISSUE TITLE
Hybrid evaluation fails on Windows if the arg is a call instead of a symbol

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#3842]
As I reported at https://github.com/tidyverse/dplyr/pull/3828#issuecomment-421875522, AppVeyor still keeps failing. This issue is about one of the errors.

The functions of hybrid evaluation work fine when the argument is a symbol.

``` r
mtcars %>%
  mutate(rank = min_rank(mpg))
```

But, when it is a call, it stops with a error. The error seems to occur at `rlang_quo_get_expr()`, but I don't get the details.

``` r
mtcars %>%
  mutate(rank = min_rank(-mpg))
#> Error: `quo` must be a quosure
```

(I guess Windows is not high priority to you in this stage of development, so, feel free to close this if it's not yet the time to report Windows bugs...)

**Comment by krlmlr** [comment]
Thanks, this is very valuable. I keep on wondering why certain tests fail on Windows.

Would you like to submit a reprex to help narrow down this issue?

CC @lionel-.

**Comment by yutannihilation** [comment]
Thanks. Sorry for not submitting a reprex, currently my rlang is full of dirty print debugs (I wish I were a GDB expert), so... 🙄  Anyway, I will try to create a more helpful reprex later.

**Comment by krlmlr** [comment]
@romainfrancois: Perhaps it's the new hybrid, though I don't understand the OS difference:

## Windows

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

df <- data_frame(x = rep(1:2, 2), g = rep(1:2, each = 2)) %>% group_by(g)
df %>% mutate(y = lead(x))
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       x     g     y
#>   <int> <int> <int>
#> 1     1     1     2
#> 2     2     1    NA
#> 3     1     2     2
#> 4     2     2    NA
df %>% mutate(y = (lead(x)))
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       x     g     y
#>   <int> <int> <int>
#> 1     1     1     2
#> 2     2     1    NA
#> 3     1     2     2
#> 4     2     2    NA
df %>% mutate(y = lead(x > 3))
#> Error: `quo` must be a quosure
```

<sup>Created on 2018-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Linux

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

df <- data_frame(x = rep(1:2, 2), g = rep(1:2, each = 2)) %>% group_by(g)
df %>% mutate(y = lead(x))
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       x     g     y
#>   <int> <int> <int>
#> 1     1     1     2
#> 2     2     1    NA
#> 3     1     2     2
#> 4     2     2    NA
df %>% mutate(y = (lead(x)))
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       x     g     y
#>   <int> <int> <int>
#> 1     1     1     2
#> 2     2     1    NA
#> 3     1     2     2
#> 4     2     2    NA
df %>% mutate(y = lead(x > 3))
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       x     g y    
#>   <int> <int> <lgl>
#> 1     1     1 FALSE
#> 2     2     1 NA   
#> 3     1     2 FALSE
#> 4     2     2 NA
```

<sup>Created on 2018-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by krlmlr** [comment]
Thanks. I pasted the wrong regex, fixed. Will look into it.

**Comment by krlmlr** [comment]
The signature of the C++ function `rlang::is_quosure()` is incorrect, needs to return a `bool` and not an `SEXP`. This fixes the problems on Windows. I can submit a PR later today, unless you do it first.

**Comment by romainfrancois** [comment]
Thanks. I'm on something else now, no I'll probably review your PR later.

**Comment by lionel-** [comment]
Good catch @krlmlr!

**Comment by yutannihilation** [comment]
Thanks so much for the fix! I'm glad that I can play with new dplyr on my Windows at last!

**Comment by krlmlr** [comment]
Thank you for reporting!
