### ISSUE TITLE
do() function "object not found" error

### ISSUE THREAD

**Issue by jflynn264** [tidyverse/dplyr#3848]
I am running the do() function on grouped data but it is not recognizing the variable names: 

df %>%
group_by(id) %>%
do(test=ellipsoidhull(cbind(p1, p2)))

Error in cbind(p1, p2) : object 'p1' not found

p1 and p2 are numeric vectors in df. When I use df$p1 and df$p2, then it uses estimates from the entire data frame rather than the grouped data. 

```r
# insert reprex here
```

**Comment by romainfrancois** [comment]
Please update your example to include a `reprex`, i.e. we don't have `df` so we can't reproduce the problem you have.

**Comment by romainfrancois** [comment]
The `.` pronoun in `do` stands for the subset of the data, so I guess you are looking for using `.$p1` and `.$p2`.
