### ISSUE TITLE
Weird output when using lag() with group_by()

### ISSUE THREAD

**Issue by skylarhopkins** [tidyverse/dplyr#3849]
I'm using R version 3.5.1 and trying to do a simple lag by group. It is partially working correctly, but the first/lowest year should receive an NA in the LagYear column in both groups in the example below. On my machine, row 8 should have an NA in the LagYear column, but it does not (see my screenshot). However, it works fine in reprex.

![screen shot 2018-09-21 at 6 09 17 pm](https://user-images.githubusercontent.com/32105098/45908239-84ddba80-bdc9-11e8-874e-04257b605b35.png)

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
df = data.frame(Site=rep(c('A1','A2'),7),
                Year=rep(seq(2012, 2018, 1),2))

df <- df %>%
  arrange(Site, Year) %>%
  group_by(Site) %>%
  mutate(LagYear = lag(Year, default=NA, order_by = Year))
df
#> # A tibble: 14 x 3
#> # Groups:   Site [2]
#>    Site   Year LagYear
#>    <fct> <dbl>   <dbl>
#>  1 A1     2012      NA
#>  2 A1     2013    2012
#>  3 A1     2014    2013
#>  4 A1     2015    2014
#>  5 A1     2016    2015
#>  6 A1     2017    2016
#>  7 A1     2018    2017
#>  8 A2     2012      NA
#>  9 A2     2013    2012
#> 10 A2     2014    2013
#> 11 A2     2015    2014
#> 12 A2     2016    2015
#> 13 A2     2017    2016
#> 14 A2     2018    2017
```

<sup>Created on 2018-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by batpigandme** [comment]
Hi @skylarhopkins,

The code works fine for me as well. Typically reprex is "right"—i.e. if your code works in reprex, but you aren't getting the same results in your interactive session, there's a collision of sorts happening in your working environment.

What happens if you run the code in a fresh R session? If it's something related to another package you have attached, the [conflicted](https://github.com/r-lib/conflicted) package can be helpful in sorting things out.

**Comment by romainfrancois** [comment]
Also, it is not clear from the code and the screenshot how is `ybc` made ? Can you double check @skylarhopkins and reopen if the problem is still there.

**Comment by skylarhopkins** [comment]
Apologies, I renamed ybc to LagYear to make the example more clear when I shared it, but I took a screenshot of the ybc version.

For posterity, the conflict is with the package plyr. Detaching plyr fixed the issue. Thanks!
