### ISSUE TITLE
dplyr::select() returns a wrong column, should probably throw a "no such column/value" style exception

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3851]
`dplyr::select()` returns a wrong column, should probably throw a "no such column/value" style exception.

```R
library("dplyr")
packageVersion("dplyr")


    ## [1] '0.7.6'


packageVersion("rlang")


    ## [1] '0.2.2'


packageVersion("tidyselect")


    ## [1] '0.2.4'


y <- "x"

dxy <- data.frame(x = 1, y = 2)
dx <- data.frame(x = 1) 

# returns column x (correct)
dx %>%
 select(y)


    ##   x
    ## 1 1


# returns column y (incorrect)
dxy %>%
 select(y)

    ##   y
    ## 1 2
```

**Comment by romainfrancois** [comment]
This is the documented behavior. Columns have priority in `dxy %>% select(y)` so the `y` column is selected. There is no `y` in `dx` so `y` is evaluated (to "x"). 

This is in essence, `tidyselect` semantics, I guess what you describe is `[` standard evaluation semantics.
