### ISSUE TITLE
Use LEVELS for obtaining the gp flags

### ISSUE THREAD

**Issue by zslajchrt** [tidyverse/dplyr#3853]
The `gp` function in `src/address.cpp` directly accesses the `gp` flag, although the `LEVELS` API function is available for this purpose.

It prevents `dplyr` from being used in FastR since FastR uses its own internal structures and relies on using the API.

```
 // [[Rcpp::export]]
 unsigned short gp(SEXP x) {
-  return reinterpret_cast<sxpinfo_struct*>(x)->gp;
+  return LEVELS(x);
 }
```

**Comment by romainfrancois** [comment]
I don't think `LEVELS` is available for *this purpose*. It just happens to use the same thing. Perhaps we can simply remove the `gp` function, it's only used in one test. 

But then, those macros also use the gp: 

```cpp
#ifndef IS_ASCII
#define IS_ASCII(x) (reinterpret_cast<sxpinfo_struct*>(x)->gp & ASCII_MASK)
#endif

#ifndef IS_UTF8
#define IS_UTF8(x) (reinterpret_cast<sxpinfo_struct*>(x)->gp & UTF8_MASK)
#endif
```

**Comment by zslajchrt** [comment]
OK, I thought that `LEVELS` is there to obtain the `gp` field. Nevertheless, I am sure it would be enough if you remove the `gp` function. Thanks.

As far as those macros, we know about them, however, we haven't experienced a problem with them, maybe just due to good luck. We thought they could also use the `LEVELS` function.

**Comment by lukasstadler** [comment]
FastR defines the `IS_ASCII` and `IS_UTF8` macros with its own implementation, so these are not a problem.
