### ISSUE TITLE
Error in UseMethod("select_")

### ISSUE THREAD

**Issue by zzygyx9119** [tidyverse/dplyr#3863]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
Dear All,

I was trying to run "Rscript  dosth.R" on the command line. In the script, I used "select( )" method. I got the following error message: 

---
Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "factor"
Calls: %>% ... withVisible -> <Anonymous> -> select -> select.default -> select_
Execution halted
---

However, I could successfully run the main function inside the script in RStudio. I was wondering whether you have met this problem and would greatly appreciate your kind help. I want to solve this problem because eventually i would like to put all the codes in a script which can be run in the command line.

Best regards,

Jeff

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
