### ISSUE TITLE
Conditionally enable Rcpp fast evaluation

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3871]
I think @lionel- suggests that this is still a bit unstable so we should start testing with it on, but not enable by default for users.

Part of closing this issue will involve adding another item to the travis build matrix so we test with it turned on.

**Comment by krlmlr** [comment]
I have set up a build matrix to test this: https://github.com/tidyverse/dplyr/tree/f-2295-ci, will merge/cherry-pick once all jobs pass.

Given the size (=compilation time) of the project and the size of the build matrix, testing for `master` and PRs only seems like a good idea. We don't need to apply it universally yet, but we could test-drive here.
