### ISSUE TITLE
conditional na_if 

### ISSUE THREAD

**Issue by S-UP** [tidyverse/dplyr#3875]
I sometimes want to set the value of a particular variable to NA if a certain condition is met. It seems one cannot use na_if() for this. Would it make sense to add this feature here?

```r
df <- tibble(k = c(1,0,1,1), y = c("abc", "def", "", "ghi"))
df %>% mutate(z = na_if(y, k == 0))
```

**Comment by hadley** [comment]
In that case, you should use the more general `ifelse()`:

```R
df <- tibble(k = c(1,0,1,1), y = c("abc", "def", "", "ghi"))
df %>% mutate(z = ifelse(k == 0, NA, y))
```

**Comment by S-UP** [comment]
Thanks! 

I then feel slightly confused by the different use-cases for ```if_else``` and ```ifelse```. I was under the impression that ```if_else``` is preferred in the tidyverse. Would be great to allow for NA or missing value situations as well. Type consistency is nice, but it's also one of the more tedious things in R that there are so many ways to do one and the same thing.

**Comment by krlmlr** [comment]
You can also use `if_else(k == 0, NA_character_, y)` . With _vctrs_ we'll be able to use `NA` in this situation too.

**Comment by S-UP** [comment]
Thanks! Now I learned something new... ;-)
