### ISSUE TITLE
With v0.7.99.9000 group_by() reacts unexpectedly when a factor level has no occurrences

### ISSUE THREAD

**Issue by philstraforelli** [tidyverse/dplyr#3877]
As per below, `group_by()` is behaving very oddly if a factor variable has a level with no occurrences, with the version of dplyr I just downloaded from Github (v0.7.99.9000).

```r
library(tidyverse)
iris_tbl <- filter(iris, Species != "setosa")
iris_tbl %>% group_by(Species) %>% nest()
#> # A tibble: 2 x 2
#>   Species    data             
#>   <fct>      <list>           
#> 1 versicolor <tibble [50 x 4]>
#> 2 virginica  <NULL>
```

The code above behaves as expected on the CRAN version of `dplyr` (v0.7.6).

**Comment by romainfrancois** [comment]
Looks like a problem in `nest`. In the meantime, yo can use the new `nest_by` instead. 

``` r
library(tidyverse)
iris_tbl <- filter(iris, Species != "setosa")
iris_tbl %>% nest_by(Species)
#> # A tibble: 3 x 2
#>   Species    data             
#>   <fct>      <list>           
#> 1 setosa     <tibble [0 × 4]> 
#> 2 versicolor <tibble [50 × 4]>
#> 3 virginica  <tibble [50 × 4]>
```

Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)

**Comment by krlmlr** [comment]
Interesting. Why would the behavior change between `v0.7.6`  and `master` ?

Bisection gave (because of `-std=gnu++98`):

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
b908e26dde4f0aa3bbefd94b19ff3396c0cda86d
c5636ee0644ac6fd0ac9c86807664f913edae5d3
5db836544f17f4664f83ecf35ee2a34b779b83ae
7747db9a0036fe7d467a837baf980a3a5996dc7f
a823541eb5965b81366dcbb980883c85ac8b52cd
bd06e4ae869a272776e5ead90541f0e3e3d03ab0
06d78c9f90f9d754c5de21fac16c557556008024
ebfd9482a7f613accff79570ce67c9ae2220aa28
fba9bf1affdb33c357a2e6547a20651ee7d6939d

**Comment by krlmlr** [comment]
I think this is the underlying issue:

## master

``` r
library(dplyr)
iris %>%
  filter(Species != "setosa") %>%
  group_indices(Species)
#>   [1] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
#>  [36] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
#>  [71] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
```

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

## v0.7.6

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
iris %>%
  filter(Species != "setosa") %>%
  group_indices(Species)
#>   [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
#>  [36] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
#>  [71] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
```

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by krlmlr** [comment]
Only few packages seem to use `group_indices()`: https://github.com/search?q=group_indices+org%3Acran&type=Code.

At least we need to document this as a breaking change. Marking this a "docs" issue for now, let's resolve in _tidyr_.

**Comment by EronitaCosta** [comment]
nice discussion!

**Comment by romainfrancois** [comment]
Right, this is part of treating factors responsibly and deal with empty groups.
