### ISSUE TITLE
Lead and lag cannot accept bare symbols as default value when inside mutate

### ISSUE THREAD

**Issue by Zedseayou** [tidyverse/dplyr#3878]
There is some unintuitive and possibly buggy behaviour around `lead` and `lag` when used inside `mutate`. If the `default` argument is a bare symbol referencing an previously defined value, an error is thrown by `mutate`. Raised in [this SO question](https://stackoverflow.com/questions/52636377/calculating-lead-variable-within-mutate-in-r-with-dates/52636548#52636548).

This can be avoided by quoting and unquoting, using an expression that evaluates to the same value, and does not happen with using `lead` or `lag` by themselves.

``` r
library(dplyr)
df <- data.frame(x = 1:5)
fillin <- 0L
df %>%
  mutate(y = lag(x, 1, fillin))
#> Error in mutate_impl(.data, dots): Not compatible with requested type: [type=symbol; target=integer].
df %>%
  mutate(y = lead(x, 1, !!quo(fillin)))
#>   x y
#> 1 1 2
#> 2 2 3
#> 3 3 4
#> 4 4 5
#> 5 5 0
df %>%
  mutate(y = lag(x, 1, as.integer(fillin)))
#>   x y
#> 1 1 0
#> 2 2 1
#> 3 3 2
#> 4 4 3
#> 5 5 4
lead(df$x, 1, fillin)
#> [1] 2 3 4 5 0
```

Created on 2018-10-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
It seems this is already fixed in the dev version.

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(x = 1:5)
fillin <- 0L
df %>%
  mutate(y = lag(x, 1, fillin))
#>   x y
#> 1 1 0
#> 2 2 1
#> 3 3 2
#> 4 4 3
#> 5 5 4
```

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by krlmlr** [comment]
Thanks, confirmed that the dev version fixes it.
