### ISSUE TITLE
Benchmark new RCPP_USE_UNWIND_PROTECT

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3881]
From https://github.com/tidyverse/dplyr/pull/3872#issuecomment-426625925.

**Comment by romainfrancois** [comment]
That would I think require a lot of care and avoid any C++ objects with destructors ...

**Comment by hadley** [comment]
Current dplyr uses `Rcpp_eval()` right?

**Comment by lionel-** [comment]
Yes.

**Comment by romainfrancois** [comment]
We no longer use `Rcpp`
