### ISSUE TITLE
recode loses non-described values for integer vectors

### ISSUE THREAD

**Issue by BobMuenchen** [tidyverse/dplyr#3882]
The recode function accepts numeric variables, recoding the values as expected and copying over the undescribed ones as they were. But with integer variables, it says, "Warning message:
Unreplaced values treated as NA as .x is not compatible. Please specify replacements exhaustively or supply .default".  This sounds like a bug that could be fixed by adding as.numeric inside recode.

---

```r
# This loses undescribed values:
x <- 1:5
dplyr::recode(x, `1` = 2, `5` = 4)

# This keeps them:
y <- as.numeric(x)
dplyr::recode(y, `1` = 2, `5` = 4)
```

**Comment by romainfrancois** [comment]
Maybe with this: 

```r
recode.integer <- function(.x, ...) recode(as.numeric(.x), ...)
```

**Comment by hadley** [comment]
I don't think there's any way to quickly fix this with out breaking existing code, but this will get authoritatively fixed once we rewrite to use vctrs thinking as in https://github.com/r-lib/funs/issues/29
