### ISSUE TITLE
top_n improperly omits groups where all(is.na(wt))

### ISSUE THREAD

**Issue by igoldin2u** [tidyverse/dplyr#3895]
```
> foo <- data_frame(g=c("a", "a", "b", "b"), x=c(1, NA, NA, NA))
> foo %>% group_by(g) %>% top_n(1, x)
# A tibble: 1 x 2
# Groups:   g [1]
  g         x
  <chr> <dbl>
1 a         1
```

Note that group "b" is entirely missing from top_n's output. I expected instead that top_n would keep a row per group.

**Comment by batpigandme** [comment]
From the dplyr docs:

> [`top_n()`](https://dplyr.tidyverse.org/reference/top_n.html) is a convenient wrapper that uses filter() and min_rank() to select the top or bottom entries in each group, ordered by wt.

[`dplyr::filter()`](https://dplyr.tidyverse.org/reference/filter.html) drops NAs:

> `filter()` find rows/cases where conditions are true. Unlike base subsetting with `[`, rows where the condition evaluates to NA are dropped.

As a result, this is, in fact, the expected output.
