### ISSUE TITLE
Incorrect calculation of difference between maximum and minimum timestamp in group

### ISSUE THREAD

**Issue by dewoller** [tidyverse/dplyr#3897]
---

When I calculate the difference between maximum and minimum timestamp with a single event, calculation is correct.  When I group it with another event, calculation is incorrect. 

``` r
library( tidyverse )
minimal_example = structure(list(text_event = c("event1", "event2", "event2"), ts = structure(c(1230728400, 1230814800, 1230728400), class = c("POSIXct", "POSIXt"), tzone = "Australia/Melbourne")), .Names = c("text_event", "ts"), row.names = c(NA, -3L), class = c("tbl_df", "tbl", "data.frame"))
#
minimal_example
#> # A tibble: 3 x 2
#>   text_event ts                 
#>   <chr>      <dttm>             
#> 1 event1     2009-01-01 00:00:00
#> 2 event2     2009-01-02 00:00:00
#> 3 event2     2009-01-01 00:00:00
#
# this example does not calculate duration correctly
minimal_example %>%
  group_by( text_event) %>%
  summarise(  duration= difftime( max( ts ) , min( ts )), 
            max(ts), 
            min(ts)
            ) %>% 
  filter(  text_event == 'event2') 
#> # A tibble: 1 x 4
#>   text_event duration `max(ts)`           `min(ts)`          
#>   <chr>      <time>   <dttm>              <dttm>             
#> 1 event2     1 secs   2009-01-02 00:00:00 2009-01-01 00:00:00
#
# this example calculates duration correctly
minimal_example %>%
  group_by( text_event) %>%
  filter(  text_event == 'event2') %>%
  summarise(  duration= difftime( max( ts ) , min( ts )), 
            max(ts), min(ts) )  
#> # A tibble: 1 x 4
#>   text_event duration `max(ts)`           `min(ts)`          
#>   <chr>      <time>   <dttm>              <dttm>             
#> 1 event2     1 days   2009-01-02 00:00:00 2009-01-01 00:00:00
```

<sup>Created on 2018-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Edited with better dates

**Comment by hadley** [comment]
Can you please construct your `minimal_example` so that the correct value is immediately obvious? (i.e. don't use fractional minutes)

**Comment by hadley** [comment]
Thanks! 

The root problem here is that difftime uses an attribute to declare the units (second vs day, here). Fixing this problem is surprisingly complicated and far-reaching, and we're tracking already elsewhere. Basically, the goal of the [vctrs package](https://vctrs.r-lib.org) is to fix this type of problem, and we'll be integrating vctrs and dplyr in a future dplyr release.

**Comment by krlmlr** [comment]
A practical option now would be to use the _hms_ package, it wraps `difftime` but uses only seconds as a unit.
