### ISSUE TITLE
Named vectors as arguments to recode()

### ISSUE THREAD

**Issue by behrman** [tidyverse/dplyr#3899]
It would be good if recode() could take named vectors as arguments.

For example, instead of

`recode(x, a = "Apple", b = "Banana")`

it would also allow

`y <- c(a = "Apple", b = "Banana")`
`recode(x, y)`

This would have the advantage of being able to separate data -- the recordings -- from code.

Thanks

**Comment by moodymudskipper** [comment]
Try this :

```
x <- letters[c(1,2,2,1)]
y <- c(a = "Apple", b = "Banana")
recode(x, !!!as.list(y))
# [1] "Apple"  "Banana" "Banana" "Apple" 
invoke(recode, x, .x=y)
# [1] "Apple"  "Banana" "Banana" "Apple" 
```

**Comment by hadley** [comment]
`!!!` is the preferred way of doing this as it will (eventually) work with every function that takes ... in the tidyverse.

@moodymudskipper there's no need to do `as.list()` anymore

``` r
x <- letters[c(1,2,2,1)]
y <- c(a = "Apple", b = "Banana")
dplyr::recode(x, !!!y)
#> [1] "Apple"  "Banana" "Banana" "Apple"
```

<sup>Created on 2018-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by behrman** [comment]
Thanks. Let me suggest adding this example to the help page for recode().

**Comment by batpigandme** [comment]
@hadley is there any reason to prefer a list to named character vector, or vice versa? If not, I can just add it as an "or" option with / after:
https://github.com/tidyverse/dplyr/blob/1573f60be3bb1f0efc54d8868301277711df427b/R/recode.R#L103-L105

**Comment by hadley** [comment]
Oh that should just be a character vector, not a list.
