### ISSUE TITLE
Group_by for columns with dates as column name

### ISSUE THREAD

**Issue by ThiAmm** [tidyverse/dplyr#3907]
Suppose we create a tibble as follows:

```r
firstColumnName <- "a"
date <- "2017-06-06"
dat <- tibble(!!firstColumnName := c(1,2,1),!!date := c(2,1,1))
```
If i want to group the tibble by a column name which is stored in a variable, i think the correct way to do this is as follows:
```r
dat %>% group_by(.dots = firstColumnName)
```
But this approach does not work for the column created based on the variable "date" which is in date format:
```r
dat %>% group_by(.dots = date) 
```
The above code produces a tibble with the column names "a", "2017-06-06" and "2017 - 06 - 06". I would have expect the tibble to have the column names "a" and "2017-06-06".

**Comment by romainfrancois** [comment]
This seems the be the ❤️ of the issue: 

``` r
dplyr:::compat_lazy_dots("2017-06-06", environment())
#> [[1]]
#> <quosure>
#>   expr: ^2017 - 6 - 6
#>   env:  global
dplyr:::compat_lazy_dots("3-2", environment())
#> [[1]]
#> <quosure>
#>   expr: ^3 - 2
#>   env:  global
dplyr:::compat_lazy_dots("3   + 2", environment())
#> [[1]]
#> <quosure>
#>   expr: ^3 + 2
#>   env:  global
```

@hadley @lionel- is this expected that we can use the `.dots` argument on `group_by` ? I get it on `group_by_` but I was surprised it works with `group_by`.

**Comment by romainfrancois** [comment]
As for the original issue, you can use `!!sym` i.e.: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

firstColumnName <- "a"
date <- "2017-06-06"
dat <- tibble(!!firstColumnName := c(1,2,1),!!date := c(2,1,1))

dat %>% 
  group_by(!!sym(date))
#> # A tibble: 3 x 2
#> # Groups:   2017-06-06 [2]
#>       a `2017-06-06`
#>   <dbl>        <dbl>
#> 1     1            2
#> 2     2            1
#> 3     1            1
```

Created on 2018-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)

**Comment by ThiAmm** [comment]
I see. The generic solution to my problem seems to be the following (in case date is a vector; see also https://github.com/r-lib/rlang/issues/321):
```r
firstColumnName <- "a"
date <- "2017-06-06"
dat <- tibble(!!firstColumnName := c(1,2,1),!!date := c(2,1,1))
dat %>% group_by(!!!syms(date))
```
