### ISSUE TITLE
Clearer documentation for grouping behavior with `count`

### ISSUE THREAD

**Issue by jschelbert** [tidyverse/dplyr#3910]
I've recently run in some behavior with the `count` function that I did not expect and which - in my opinion - is not precisely described in the documentation. The docu reads as follows:
> tally() is a convenient wrapper for summarise that will either call n() or sum(n) depending on whether you're tallying for the first time, or re-tallying. count() is similar but calls group_by() before and ungroup() after.

I would have expected that the `count` function does not respect existing groups (opposed to their cousins `add_count`). More precisely, I'd expected it to work like `df %>% group_by(...) %>% summarize(n=n()) %>% ungroup()`, while it actually works more like `df %>% group_by(..., add = TRUE) %>% summarize(n=n()) %>% ungroup()`.
My suggestion would be to make the docu clearer on this issue.

This issue is potentially linked to #2078 and #3739.

RepRex:
``` r
library(tidyverse)
df <- mtcars
df2 <- df %>% group_by(gear)

df2 %>% count(carb)
#> # A tibble: 11 x 3
#> # Groups:   gear [3]
#>     gear  carb     n
#>    <dbl> <dbl> <int>
#>  1     3     1     3
#>  2     3     2     4
#>  3     3     3     3
#>  4     3     4     5
#>  5     4     1     4
#>  6     4     2     4
#>  7     4     4     4
#>  8     5     2     2
#>  9     5     4     1
#> 10     5     6     1
#> 11     5     8     1

# expected behavior?
# Docs say: count() is similar [to 'tally()'] but calls group_by() before and ungroup() after.
# what I expected was behavior like the following:
df2 %>% ungroup() %>% count(carb)
#> # A tibble: 6 x 2
#>    carb     n
#>   <dbl> <int>
#> 1     1     7
#> 2     2    10
#> 3     3     3
#> 4     4    10
#> 5     6     1
#> 6     8     1
```

<sup>Created on 2018-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by batpigandme** [comment]
The expected behaviour you've described is what happens if you run the code below (just `count(carb)` on mtcars). So, just to zoom in on what you'd like to be better-documented, I think you're describing what `count()` does in the face of existing groups. Right?

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>%
  count(carb)
#> # A tibble: 6 x 2
#>    carb     n
#>   <dbl> <int>
#> 1     1     7
#> 2     2    10
#> 3     3     3
#> 4     4    10
#> 5     6     1
#> 6     8     1

mtcars %>%
  tally(carb)
#>    n
#> 1 90
```

<sup>Created on 2018-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by jschelbert** [comment]
Hi batpigandme,
yes, what is missing from the docu in my opinion is a more concise explanation what happens if the data is already grouped. 
I would have expected different results with `count` and `add_count` in the following way:
`count(xyz)` does neglect existing groups and just uses the groups (`xyz`)that it is provided to compute the count, where as `add_count(xyz)` uses the existing grouping and adds another grouping variable for computation.

**Comment by romainfrancois** [comment]
Would you offer a pull request with these documentation changes ? @jschelbert
