### ISSUE TITLE
hybrid evaluation for slice and filter

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3919]
Background: https://github.com/tidyverse/dplyr/pull/3912

Identify some cases of `filter()` and `slice()` expressions that can be handled in a hybrid way, e.g. 

```r
filter( <column> <op> <constant> )
filter( <column> <op> <column> )
filter( row_number() <op> <constant> )
filter( <column> %in% <constant> )

slice( 1:<constant>)
slice( <constant> )
```

**Comment by hadley** [comment]
Closing this since there's no hybrid eval right now, and we'll think about the problem holistically as we tackle the new implementation.
