### ISSUE TITLE
filter gets confused when the same variable name is used as a filtering variable

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/dplyr#3922]
Hello there,

Consider this:

```
df <- data_frame('mydate' = c(ymd('2018-08-08'),
                             ymd('2018-07-06')),
                 'mystring' = c('hello', 'world'))

mydate <- ymd('2018-07-06')
mystring <- 'hello'
```
Now running either of 

```
df %>% filter(mydate == mydate)
df %>% filter(mystring == mystring)
```
will **NOT** work. Is there a fundamental reason for that? I dont think I have read anywhere in the tidyverse docs that re-using variable names is forbidden? Am I missing something here?

Thanks!!

**Comment by hadley** [comment]
Because `x == x` is always `TRUE`. There's no way for dplyr to tell that you are thinking of different variables.

**Comment by randomgambit** [comment]
OK thank you. I would add this in the gotcha part of your book. I think this is a very natural mistake (and easy to overlook because filter wont throw any error)
