### ISSUE TITLE
summarise() output with empty `...` has 1 row

### ISSUE THREAD

**Issue by echasnovski** [tidyverse/dplyr#3928]
I don't know if it is intended change (didn't find any mention), but with current dplyr version (commit 19f742d) `summarise()` returns output with 1 row and 0 columns when called with empty `...`: 
``` r
dplyr::summarise(tibble::tibble(x = 1))
#> # A tibble: 1 x 0
```
<sup>Created on 2018-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

In current CRAN version output has 0 rows and 0 columns.

**Comment by romainfrancois** [comment]
it might be an accidental fix, but it makes sense. `summarise()` of non grouped tibbles produces tibbles of 1 row.
