### ISSUE TITLE
filter() on grouped data reorders rows

### ISSUE THREAD

**Issue by echasnovski** [tidyverse/dplyr#3929]
Reordering seems to be done according to `group_indices()`.
``` r
library(dplyr)
mtcars_grouped <- mtcars %>%
  select(mpg, am) %>%
  mutate(.id = seq_len(n())) %>%
  group_by(am)

mtcars_grouped %>% filter(mpg > 22)
#> # A tibble: 9 x 3
#> # Groups:   am [2]
#>     mpg    am   .id
#>   <dbl> <dbl> <int>
#> 1  24.4     0     8
#> 2  22.8     0     9
#> 3  22.8     1     3
#> 4  32.4     1    18
#> 5  30.4     1    19
#> 6  33.9     1    20
#> 7  27.3     1    26
#> 8  26       1    27
#> 9  30.4     1    28
```

<sup>Created on 2018-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
Yes, the current `filter()` implementation squashes the groups together. We can do that more efficiently, and further operations benefit from having the data for a group contiguous. 

There was never guarantees on the order of the rows.

**Comment by echasnovski** [comment]
Even if there was no formal guarantees about the order of the rows, there were intuitive ones.

For example, as [stated in "R for Data Science"](http://r4ds.had.co.nz/transform.html#grouped-mutates-and-filters): "A grouped filter is a grouped mutate followed by an ungrouped filter". This seems reasonable. However, it is not true in current version of dplyr (commit 19f742d):

``` r
library(dplyr)

mtcars_grouped <- mtcars %>%
  select(mpg, am) %>%
  mutate(.id = seq_len(n())) %>%
  group_by(am)

mtcars_grouped %>% filter(mpg > 22)
#> # A tibble: 9 x 3
#> # Groups:   am [2]
#>     mpg    am   .id
#>   <dbl> <dbl> <int>
#> 1  24.4     0     8
#> 2  22.8     0     9
#> 3  22.8     1     3
#> 4  32.4     1    18
#> 5  30.4     1    19
#> 6  33.9     1    20
#> 7  27.3     1    26
#> 8  26       1    27
#> 9  30.4     1    28

# This should give the same result but it doesn't
mtcars_grouped %>%
  mutate(is_big_mpg = mpg > 22) %>%
  ungroup() %>%
  filter(is_big_mpg) %>%
  select(-is_big_mpg) %>%
  group_by(am)
#> # A tibble: 9 x 3
#> # Groups:   am [2]
#>     mpg    am   .id
#>   <dbl> <dbl> <int>
#> 1  22.8     1     3
#> 2  24.4     0     8
#> 3  22.8     0     9
#> 4  32.4     1    18
#> 5  30.4     1    19
#> 6  33.9     1    20
#> 7  27.3     1    26
#> 8  26       1    27
#> 9  30.4     1    28
```

<sup>Created on 2018-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
There are identical if you disregard the order of the rows. 

Thanks for bringing this up. We will discuss it, but this would be more expensive to reorganize the rows in the order of the original data, and will also hurt performance of further operations...

**Comment by romainfrancois** [comment]
I'll mention that in the blog post about the dplyr 0.8.0 release candidate. https://github.com/tidyverse/tidyverse.org/pull/220

**Comment by echasnovski** [comment]
Thank you very much.

**Comment by hughjonesd** [comment]
Here are some examples from my own code of how this could cause problems. 


Here, the `do` creates a grouped tibble of regression results. The `filter` could now silently reorder the rows, and hence the coefficients:

```
dfr %>% 
  filter(!is.na(gender1), ! is.na(year1)) %>% 
  group_by(gender1, year1) %>% 
  do({
    m <- lm(egal2 ~ p_egal1 + egal1 + Ftreat, .)
    tidy(m, conf.int = TRUE)
  }) %>% 
  filter(term=='p_egal1TRUE') ->
  yg_coefs
```

A similar example:
```
pnr %>% 
      group_by(degree.f, degree.m) %>% 
      do(mod = lm(ea2_ps_r.f ~ ea2_ps_r.m, .)) %>% 
      do(cbind(.$degree.f, .$degree.m, tidy(.$mod))) %>% 
      filter(term =='ea2_ps_r.m')
```


The next one currently ends up ordered by `to` then `from`. In future, I don't know. Luckily this is a small script so I can easily check if it breaks anything. The previous example, OTOH, is from a 50 page paper with about 10 graphs and more than 10 tables:

```
years_han <- readRDS("hansard_year_counts.rds")
years_han %<>% 
      as_tibble(rownames = "from") %>% 
      mutate(from = as.numeric(from)) %>% 
      tidyr::gather("to", "count", -from, convert = TRUE) %>% 
      group_by(from) %>% 
      filter(sum(count) > 0)
```


The next beast involves joining three data frames. It is a small part of a 1000 line script. (Yes, I should write more elegant code. But code written with a scientist's hat on is different from programmer's code...) I include it so you can imagine the joy of working out if I need to change anything. (In the end I don't, because `sch_ks2` is not grouped... I think!)

```

sch_ks2 <- suppressMessages(read_csv('./school performance 2010-2011/england_ks2.csv'))
sch_ks2 %<>% filter(RECTYPE == 1) %>% mutate(
        PTEALGRP2 = parse_number(PTEALGRP2),
        TOTPUPS   = parse_number(TOTPUPS)
      )
sch_census <- suppressMessages(read_csv('./school performance 2010-2011/england_census.csv'))
sch_ks2 %<>% left_join(sch_census, by = 'URN')

# done with http://gridreferencefinder.com/postcodeBatchConverter:
pconv <- suppressMessages(read_csv('postcode-conversion.csv')) 
sch_ks2 %<>% 
      left_join(pconv %>% dplyr::select(1, 4, 5), by = c('PCODE' = 'Postcode')) %>% 
      rename(easting = `X (easting)`, northing = `Y (northing)`) %>% 
      filter(! is.na(easting), ! is.na(northing))
sch_ks2 <- st_as_sf(sch_ks2, coords = c('easting', 'northing'), remove = FALSE)
st_crs(sch_ks2) <- projection
sch_lgds <- st_over(sch_ks2, lgds)
sch_ks2$lgd <- lgds$lad09cd[sch_lgds]
sch_lsoa <- st_over(sch_ks2, uk)
sch_ks2$CD2011 <- uk$CD2011[sch_lsoa]

dists <- RANN::nn2(st_coordinates(sch_ks2), bdgw_sp[,c('east_now', 'north_now')],  k = 3) 
# k gives number of schools
# dists$nn.idx is [bdgw_sp row, nth nearest neighbour] and the matrix values are the rows of sch_ks2
# dists$nn.dists is the same and gives the distances
# now to each school we assign the indivs who are nearer that school than any other, and within some distance (say 4 km)
# and we get the mean ea2_ps_r, also the mean educ_level from those indivs
bdgw_sp$nn_idx <- dists$nn.idx[, 1]
bdgw_sp$nn_dists <- dists$nn.dists[, 1]

# same again for place born:
dists_born <- RANN::nn2(st_coordinates(sch_ks2), bdgw_sp[,c('east_born', 'north_born')],  k = 1) # k gives number of schools
bdgw_sp$nn_idx_born <- dists_born$nn.idx[,1]
bdgw_sp$nn_dists_born <- dists_born$nn.dists[,1]

school_locals <- bdgw_sp  %>% 
      group_by(nn_idx)        %>% 
      filter(nn_dists < 4000) %>% 
      dplyr::summarize(
        n_locals        = n(),
        mean_ea2        = mean(ea2_ps_r, na.rm = TRUE),
        mean_educ_level = mean(educ_level, na.rm = TRUE),
        mean_ea2_movers = mean(ea2_ps_r[dist > 20000], na.rm = TRUE)
      )

school_locals_born <- bdgw_sp  %>% 
  group_by(nn_idx_born)        %>% 
  filter(nn_dists_born < 4000) %>% 
  dplyr::summarize(
    n_locals_born        = n(),
    mean_ea2_born        = mean(ea2_ps_r, na.rm = TRUE),
    mean_educ_level_born = mean(educ_level, na.rm = TRUE)
  )

sch_ks2$idx <- 1:nrow(sch_ks2)
sch_ks2 %<>% 
      as.data.frame %>% 
      left_join(school_locals, by = c('idx' = 'nn_idx')) %>% 
      left_join(school_locals_born, by = c('idx' = 'nn_idx_born')) %>% 
      left_join(uk %>% as.data.frame %>% select(CD2011, town11))
sch_ks2$ptengmatx <- parse_number(sch_ks2$PTENGMATX) # performance on english and maths at key stage 2

```

SQL is not guaranteed to be ordered unless you use ORDER BY. Data frames are intrinsically ordered by row. I don't think most R users expect them to be reordered by surprise.

Here's a relevant comment from @hadley at https://stackoverflow.com/a/27840349/10522567 :


> One really important thing that dplyr does for you is that it constrains your options. I claim that most single table problems can be solved with just five key verbs filter, select, mutate, arrange and summarise, along with a "by group" adverb. That constraint is a big help when you're learning data manipulation, because it helps order your thinking about the problem. In dplyr, each of these verbs is mapped to a single function. <b>Each function does one job, and is easy to understand in isolation.</b>
...
>Memory and performance

> I've lumped these together, because, to me, they're not that important. Most R users work with well under 1 million rows of data, and dplyr is sufficiently fast enough for that size of data that you're not aware of processing time. <b>We optimise dplyr for expressiveness on medium data</b>; feel free to use data.table for raw speed on bigger data.

Emphasis added.

The change creates dependencies across different operations. `filter` will do things differently before and after a `group_by`, even if it doesn't refer to a grouping variable or a function like `n()`. `dfr %>% arrange(...) %>% filter(...)` is no longer the same as `dfr %>% filter(...) %>% arrange(...)`, even for simple cases. I now need to think harder about the order of operations.

My largest data is half a million rows and the speed of `filter` has never been a problem. I appreciate that those working with truly big data may benefit from the speedup, and that R needs to keep up in this area. I just want to point out the downsides. 

I wonder if an alternative would be to reorder things, do the filter, then reorder them back.

**Comment by romainfrancois** [comment]
Can you please open a new issue, and if you share some examples please make sure we can run them.

**Comment by hughjonesd** [comment]
I think the issue is that filter with grouped data reorders rows! These examples are also not meant to be run, but just to be looked at to demonstrate the problem. And the point was that they come from real working code. But no problem, I will open a new issue and provide some runnable examples.
