### ISSUE TITLE
User friendly enhancements to == in filter()

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3937]
These are common problems (particularly amongst newer users), that would be very nice to hint about:

```R
blah <- 5
filter(df, blah == blah)
#> Warning: You did `x == x` which always equals TRUE.

filter(df, blah == c("x", "y"))
#> Warning: the right hand side of == has multiple values.
#> Did you mean blah %in% c("x", "y")?
filter(df, blah != c("x", "y"))
```

I think we could implement by providing a custom `==` override in the scope.

**Comment by romainfrancois** [comment]
Do we want this for 0.8.0. This might be related to #3919 but could also be done independently if we want this right now.

**Comment by hadley** [comment]
I don't think we need to push this to the next release.

**Comment by S-UP** [comment]
Would be great to have this fixed somehow. I ran into this by accident as a variable was named the same as the input of a function. It's a rather confusing issue for me as conceptually, it should work.

 ``` lookup_tibble <- tibble(level = c('A', 'B', 'C'), value = c(1,3,5))
    lookup_tibble %>% filter(level == 'B')
    
    level = 'B'
    lookup_tibble %>% filter(level == level)

```

**Comment by hadley** [comment]
@S-UP that is unrelated. `x == x` is going to be TRUE in R.

**Comment by hadley** [comment]
Now tracking in https://github.com/r-lib/funs/issues/33
