### ISSUE TITLE
warning with `R 3.6.0`

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/dplyr#3943]
With the development version of `R 3.6.0` I am getting the following warning once per session (because overwriting `S3` methods has become verbose).

```
Registered S3 method overwritten by 'dplyr':
  method               from  
  as.data.frame.tbl_df tibble
```

It will be nice if `dplyr` can be changed so that these warnings aren't displayed to the user who might get confused.

**Comment by romainfrancois** [comment]
@krlmlr can you have a look, perhaps we can import and reexport `tibble::as.data.frame.tbl_df` ?

**Comment by krlmlr** [comment]
I think we can just remove our override?
