### ISSUE TITLE
Documentation: duplicate & missing entry on reference page; `distinct()` instead of `filter()`

### ISSUE THREAD

**Issue by wmayner** [tidyverse/dplyr#3945]
The [reference page](https://dplyr.tidyverse.org/reference/) has an incorrect link to `distinct()`, where `filter()` should be instead: https://github.com/tidyverse/dplyr/blob/dbbb918771bb6f803f5f9a126a38b613f7af0211/docs/reference/index.html#L130-L133

**Comment by batpigandme** [comment]
Duplicate of #3917
