### ISSUE TITLE
Improve documentation of group_indices, + maybe `method` argument?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#3948]
The way `group_indices` assigns an id to a group is not documented.

The value seems to be the rank of the unique interactions sorted by values, which is fair, but might not always be what ones expect.

One might expect ids to be assigned by order of appearance, in my opinion a parameter allowing to switch to that behavior would be useful.

My use case involved sorting a data frame by an aggregated value by group, and filtering on the top n groups.

current behavior:

```
tibble(x = c("b","a","a")) %>% group_indices(x)
# [1] 2 1 1
```

my fix:

```
tibble(x = c("b","a","a")) %>% group_indices(factor(x,unique(x))) 
# [1] 1 2 2
```

That's a bit clunky and would be much worse with a grouping of several variables.

proposed behavior:

```
tibble(x = c("b","a","a")) %>% group_indices(x, method = "by_occurence")
# [1] 1 2 2
```

**Comment by hadley** [comment]
I don't think you should assume anything about the indices except that they uniquely identify a group.
