### ISSUE TITLE
dplyr functions causing crash instead of error windows 32-bit R 3.5.1

### ISSUE THREAD

**Issue by libbieweimer** [tidyverse/dplyr#3956]
When I using dplyr functions like summarise, filter, mutate etc. and call on columns that do not exist (because typos) R crashes instead of throwing an error. It is behavior like described in [#1835](https://github.com/tidyverse/dplyr/issues/1835) and [#1881](https://github.com/tidyverse/dplyr/issues/1881)

Windows 32 bit R 3.5.1 Rstudio v. 1.1.456

I tried uninstalling and reinstalling dplyr and Rccp but that didn't help

``` r

df <- df %>% 
  mutate(new_col = colthatdoesntexist)

```

<sup>Created on 2018-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
I can't reproduce this locally on 🍎OS, maybe @krlmlr will be more lucky on windows. @libbieweimer can you share the results of `sessioninfo::session_info("dplyr")` ?

**Comment by hadley** [comment]
This is almost always a result of incompatible package versions, and on windows it's easy to trick yourself into thinking you've reinstalled when you haven't.

**Comment by libbieweimer** [comment]
Thanks for your attention to this - the root of the problem seems to be Anaconda's package management as a fresh install of R and Rstudio outside the anaconda environment is working fine. I'll take the issue to them.
