### ISSUE TITLE
summarise() docs: demo sequential evaluation

### ISSUE THREAD

**Issue by rensa** [tidyverse/dplyr#3957]
We had [a recent thread on the RStudio Community](https://community.rstudio.com/t/summarize-anomaly/17562/2) that demonstrated some misunderstanding about how arguments are evaluated. We talked about submitting a PR to amend the docs for `summarise()` to more explicitly demonstrate both the upside and downside of the data frame backend working this way.

I have a PR ready to go, but I wasn't sure whether to commit both the source file (`R/*.R`) and the compiled doc file (`man/*.Rd`). Plus, it's a fairly substantial change to the text; maybe it's better to talk it out here before submitting the PR.

Here's the revised "Backend variations" section and example I'm proposing in `R/manip.r`:

```r
#' @section Backend variations: 
#' 
#' The data frame backend supports creating a variable and using it in the 
#' using it in the same summary. See examples for more details. 
#' same summary. This means that previously created summary variables can be 
#' further transformed or combined within the summary, as in \code{mutate}. 
#' However, it also means that summary variables with the same names as previous 
#' variables overwrite them, making those variables unavailable to later summary 
#' variables. This is illustrated in the examples. 
#' 
#' Other backends do not support this: summary variables cannot be refered to 
#' within the same summary.
```

```r
#' # Because the groups are single rows, and sd refers to mean(disp) for data 
#' # frames (rather than the original disp column), sd evaluates to NA for 
#' # each group. But double_disp, which is also calculated grouped, evaluates 
#' # as expected. This behaviour may be different for other backends.
#' mtcars %>%
#'   group_by(cyl) %>%
#'   summarise(disp = mean(disp), sd = sd(disp), double_disp = disp * 2)
```

**Comment by romainfrancois** [comment]
Please submit both R and Rd files (after running `devtools::document()`). A PR is easier to review here.

**Comment by rensa** [comment]
No worries :)
