### ISSUE TITLE
Pipe notation and double colon notation

### ISSUE THREAD

**Issue by ipofanes** [tidyverse/dplyr#3958]
---

There seems to be a clash between the pipe notation as implemented in dplyr and the double colon notation. I didn't find anything about it in the documentation.

This works:
```r
base::mean(1:10)
```

This doesn't:
```r
1:10 %>% base::mean
```

It works after parenthesizing though:
```r
1:10 %>% (base::mean)
```

It could be made a bit more prominent in the docs.

**Comment by romainfrancois** [comment]
The pipe comes from the [magrittr](https://github.com/tidyverse/magrittr) 📦

**Comment by hadley** [comment]
@ipofanes `1:10 %>% base::mean()` works, which is why we recommend that style

@romainfrancois can you please use the "transfer this issue" in future?

**Comment by romainfrancois** [comment]
I don't think I have the feature (yet), and have not seen how to opt in for it.

**Comment by hadley** [comment]
Oh interesting - you don't see it on the RHS?

<img width="209" alt="screenshot 2018-11-08 at 6 41 09 am" src="https://user-images.githubusercontent.com/4196/48199291-4b352480-e321-11e8-81bc-4c747063becc.png">

**Comment by romainfrancois** [comment]
I don't. I've asked @github on twitter 🤞
https://twitter.com/romain_francois/status/1060512391061012480

**Comment by ipofanes** [comment]
Thanks for the quick clarification, but could you leave me out of the discussion on github features?

**Comment by romainfrancois** [comment]
You can unsubscribe from an issue thread to leave yourself out.

**Comment by ipofanes** [comment]
cheers
