### ISSUE TITLE
Support intersect all and except all

### ISSUE THREAD

**Issue by kevinykuo** [tidyverse/dplyr#3960]
These are available in e.g. [Postgres](https://www.postgresql.org/docs/9.4/queries-union.html) and Spark.

**Comment by romainfrancois** [comment]
Can you give some details of what these do ?

**Comment by kevinykuo** [comment]
From the Postgres doc:
```
INTERSECT returns all rows that are both in the result of query1 and in the result of query2. Duplicate rows are eliminated unless INTERSECT ALL is used.

EXCEPT returns all rows that are in the result of query1 but not in the result of query2. (This is sometimes called the difference between two queries.) Again, duplicates are eliminated unless EXCEPT ALL is used.
```

Basically they differ from `intersect()` and `setdiff()` in how duplicates are handled.

[SPARK-21274](https://issues.apache.org/jira/browse/SPARK-21274) also has some details on how these can be implemented using other verbs.

**Comment by hadley** [comment]
I don't understand what the semantics are here. Intersection and set difference are fundamentally set operators; what does keeping duplicates mean?

**Comment by kevinykuo** [comment]
It's *kinda* like how `?dplyr::union_all` keeps duplicates. E.g. if a record appears in A *m* times and in B *n* times, then `intersect_all(A, B)` would return `max(m, n)` instances of that record.

**Comment by jangorecki** [comment]
> `intersect_all(A, B)` would return `max(m, n)` instances of that record.

@kevinykuo I believe you wanted to write `min(m, n)` rather than `max(m, n)`. For `EXCEPT ALL` it will be `max(0, xn-yn)`.

**Comment by romainfrancois** [comment]
I still don't get it. @kevinykuo do you have some simple examples of ins and outs ?

**Comment by hadley** [comment]
These seems of limited use to me, and unfortunately any increase in API scope inevitably makes things more confusing for people.
