### ISSUE TITLE
dplyr no longer available on R-studio with my MacBook

### ISSUE THREAD

**Issue by aloes2512** [tidyverse/dplyr#3962]
I used dplyr some time on R- Studio, suddenly it is no longer available in the list of packages. Tried to install again from CRAN failed. Results in error messages. I am using a MacBook: RStudio
Version 1.0.136 – © 2009-2016 RStudio, Inc.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko)

```r
# insert reprex here
```

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by aloes2512** [comment]
Thank You, but I found the solution myself. After downloading I was asked, whether I want to  the compiled compile the data. When I said „no“ the last version of „tidyverse“ was available and works with the updated OsX.
kind regards
Alf Löffler
