### ISSUE TITLE
Should `by` parameters of join functions support vars() specifications?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#3965]
Would allow things like:

```r
left_join(df1, df2, by = vars(starts_with("s"))
full_join(df1, df2, by = vars(foo:bar)
```

**Comment by hadley** [comment]
I think we'll eventually also need something like mutate-like semantics (i.e. `left.y < right.y`) so we need to be a little careful about going down this route.

**Comment by romainfrancois** [comment]
We could have `.left$` and `.right$` pronouns

**Comment by krlmlr** [comment]
Related: #2240.

**Comment by hadley** [comment]
Closing in favour of linked issue
