### ISSUE TITLE
group_map()

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3966]
Following #3964, we could have a `group_map` that would allow iteration over groups, e.g. 

```
iris %>%
  group_by(Species) %>%
  group_map( ~ lambda)
```

where lambda would be a function of: 
  - `.key` : a 1-row tibble identifying the group
  - `.subset` : the subset of `.data` for that group

**Comment by romainfrancois** [comment]
https://github.com/tidyverse/dplyr/pull/3949#issuecomment-436719037 had a version (although obsoletely based on the old split_by, nest_by, ...

**Comment by hadley** [comment]
Would we have the same interface as `do()`? i.e a single unnamed lambda which returns a data frame, or multiple named lambdas that return scalars?

```r
iris %>%
  group_by(Species) %>%
  group_map(~ .subset[1, ])

# vs

iris %>%
  group_by(Species) %>%
  group_map(n = ~ nrow(.subset))
```

Either way, I think `group_map()` would always return a data frame, which makes it a bit different to the solution you proposed in #3949.

**Comment by hadley** [comment]
This would be clearly different to the other `group_` functions since we're using `...` for lambdas, not grouping variables.

**Comment by jennybc** [comment]
I think it would be good for `group_map()` to be very clearly laid out w.r.t. related workflows that use `group_nest()` + `mutate(?? = map(data, ...)` + `unnest()` and `group_split() + map_dfr()`. Is it an alternative way to express something possible with the other workflows or is it needed to complete a set of operations?

**Comment by hadley** [comment]
I'm pretty sure these are all equivalent:

```R
df %>% 
  nest_by(g1, g2) %>% 
  mutate(
    out = map(data, f)
  ) %>% 
  unnest(out)

df %>% 
  group_by(g1, g2) %>% 
  group_map(f)

df %>% 
  group_by(g1, g2) %>% 
  do(f(.))
```

**Comment by romainfrancois** [comment]
If we look for syntax like this: 

```r
iris %>%
  group_by(Species) %>%
  group_map(n = ~ nrow(.subset))
```

Then how does this differ from something like : 

```r
iris %>%
  group_by(Species) %>%
  summarise(n = nrow(.subset))
```

Where `.subset` would be a pronoun (not sure we could use `.data` here, @lionel- ?) that would lazily give you the subset of the data, sort of like the `.SD` of data.table I suppose.

**Comment by lionel-** [comment]
`.data` wouldn't work here because it doesn't represent a data frame but an environment or a chain of environments. It's not trivial to transform it to a data frame because it has no notion of ordering, and what objects in the mask (which might have been modified by the user) are part of the df. Also things like `.data$foo` shouldn't materialise the whole data frame when the columns are lazily generated.

It still seems it would be better to work on .data shortcomings rather than introducing a new pronoun. Maybe `.data()` should return a data frame? That'd be surprising syntax from the user point of view though. And would have to be dplyr-only?

**Comment by hadley** [comment]
@romainfrancois good point; I think that's an argument for eliminating the named argument form in favour of better pronouns. My feeling is also that this is not the feature of `do()` that people actually want.

Maybe we could support `.subset` and `.keys` in all dplyr verbs? Maybe `.group` would be a better name than `.subset`? We could prototype the pronouns here, and then later roll out to the other verbs.

**Comment by romainfrancois** [comment]
I opened #3972 to discuss the pronouns separately.
