### ISSUE TITLE
Flexible joining of data frames

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#3967]
With the upcoming support of df-cols in tibble, it would be useful to have a more flexible tool for joining data frames. The purpose of df-cols is to group columns together under a given name. As @hadley puts it, df-cols provide namespacing for data frames.

Because namespacing is an important aspect of df-cols, it might make sense to create a joiner taking a variable number of data frames with `...`, since dots have natural support for names. The following is a proposal for a single joiner function `join()` that:

- Supports joining data frames as df-cols, or as individual columns.

- Supports fully inner joins (drop all unmatched rows), fully outer joins (keep all unmatched rows), or throw an error when unmatched rows are detected. The latter feature is useful in functions where data structures are expected to be fully matched.

- With duplicate keys, takes the cartesian probuct or throws an error.

- Supports nesting the joined data frames, either as separate list-columns, or as a nested list-column of data frames.

A partial implementation of `join()` is available in https://github.com/r-lib/revdepcheck/pull/164/files. A more complete implementation would support multiple keys and have this signature:

```r
join <- function(.by,
                 ...,
                 .keep = FALSE,
                 .unmatched = c("keep", "drop", "error"),
                 .duplicates = c("error", "product"))
```

Here is the output of `nest_join()` as a point of reference. The RHS data frame is joined into the LHS one as a nested df-col:

```r
foo <- tibble(x1 = 1:3, x2 = 4:6, key = c("a", "b", "c"))
bar <- tibble(y1 = 7:9, y2 = 10:12, key = c("a", "c", "d"))

# For reference
nest_join(foo, bar, "key", name = "bar")
#> # A tibble: 3 x 4
#>      x1    x2 key   bar
#> * <int> <int> <chr> <list>
#> 1     1     4 a     <tibble [1 × 2]>
#> 2     2     5 b     <tibble [0 × 2]>
#> 3     3     6 c     <tibble [1 × 2]>
```

It is not possible to create this output wih `join()` because all inputs are treated equally. All unmatched rows are either kept or dropped. If you need non-symmetrical joining, you'll have to use one of the binary joiner as an intermediate step.

If you pass the data frames without names, they are joined as individual columns:

```r
join("key", foo, bar, .unmatched = "drop")
#> # A tibble: 2 x 5
#>   key      x1    x2    y1    y2
#>   <chr> <int> <int> <int> <int>
#> 1 a         1     4     7    10
#> 2 c         3     6     8    11
```

Note how all unmatched rows from both `foo` and `bar` have been dropped. It is also possible to keep them:

```r
join("key", foo, bar, .unmatched = "keep")
#> # A tibble: 2 x 5
#>   key      x1    x2    y1    y2
#>   <chr> <int> <int> <int> <int>
#> 1 a         1     4     7    10
#> 2 b         2     5    NA    NA
#> 3 c         3     6     8    11
#> 4 d        NA    NA     9    12
```

Or throw an error if you expect matching rows:

```r
join("key", foo, bar, .unmatched = "error")
#> Error: Join keys can't be unmatched
```

If you have duplicate matches, that's an error by default:

```r
quux <- tibble(z = 7:9, key = c("a", "a", "b"))

join("key", foo, quux)
#> Error: Join keys can't be duplicated
```

The `.duplicates` argument lets you take the product instead:

```r
join("key", foo, quux, .duplicates = "product")
#> # A tibble: 2 x 5
#>   key      x1    x2     z
#>   <chr> <int> <int> <int>
#> 1 a         1     4     7
#> 2 a         1     4     8
#> 3 b         2     5     9
#> 4 c         3     6    NA
```

Now onto the interesting stuff. If you give a name to an input, you have namespaced it. It becomes a df-col:

```r
join("key", foo, bar = bar, .unmatched = "drop")
#> # A tibble: 2 x 4
#>   key      x1    x2 bar$y1   $y2
#>   <chr> <int> <int>  <int> <int>
#> 1 a         1     4      7    10
#> 2 c         3     6      8    11

join("key", foo = foo, bar = bar, .unmatched = "drop")
#> # A tibble: 2 x 3
#>   key   foo$x1   $x2 bar$y1   $y2
#>   <chr>  <int> <int>  <int> <int>
#> 1 a          1     4      7    10
#> 2 c          3     6      8    11
```

df-cols provide namespacing. In practical terms, you can access the underlying data frame with `$`:

```r
data <- join("key", foo = foo, bar = bar, .unmatched = "drop")

data$bar
#> # A tibble: 2 x 2
#>      y1    y2
#>   <int> <int>
#> 1     7    10
#> 2     8    11

data$foo$x2
#> [1] 4 6
```

`join()` also supports list-columns with the `nesting()` adverb. You can nest both named and unnamed inputs:

```r
data <- join("key", nesting(foo), bar = nesting(bar), .unmatched = "drop")

data
#> # A tibble: 2 x 4
#>   key   x1        x2        bar
#>   <chr> <list>    <list>    <list>
#> 1 a     <int [1]> <int [1]> <tibble [1 × 2]>
#> 2 c     <int [1]> <int [1]> <tibble [1 × 2]>

data$x1
#> [[1]]
#> [1] 1
#>
#> [[2]]
#> [1] 3

data$bar
#> [[1]]
#> # A tibble: 1 x 2
#>      y1    y2
#>   <int> <int>
#> 1     7    10
#>
#> [[2]]
#> # A tibble: 1 x 2
#>      y1    y2
#>   <int> <int>
#> 1     8    11
```

Nested columns are suitable for mapping over.

The df-cols lose their key columns by default, but you can also keep them with `.keep`:

```r
data <- join("key", foo = foo, bar = nesting(bar), .unmatched = "drop", .keep = TRUE)

data
#> # A tibble: 2 x 3
#>   key   foo$x1   $x2 $key  bar
#>   <chr>  <int> <int> <chr> <list>
#> 1 a          1     4 a     <tibble [1 × 3]>
#> 2 c          3     6 c     <tibble [1 × 3]>

data$foo
#> # A tibble: 2 x 3
#>      x1    x2 key
#>   <int> <int> <chr>
#> 1     1     4 a
#> 2     3     6 c

data$bar
#> [[1]]
#> # A tibble: 1 x 3
#>      y1    y2 key
#>   <int> <int> <chr>
#> 1     7    10 a
#>
#> [[2]]
#> # A tibble: 1 x 3
#>      y1    y2 key
#>   <int> <int> <chr>
#> 1     8    11 c
```

**Comment by lionel-** [comment]
Perhaps `.duplicated` should not apply to `nesting()` objects, since the list elements can be length > 1? Then `nesting()` could have its own `.duplicated = "error"` option to get additional checking?

**Comment by lionel-** [comment]
From @hadley

The nests are always size 1 with this scheme, which might be useful for row-mapping but can always be done in a separate step. A more interesting approach would be to have `.duplicates = c("error", "nest")`, which would nest inputs with duplicate keys in list-columns.

**Comment by lionel-** [comment]
Nests should refer to 2d nests, so the `nesting()` above should really be `splitting()`.

**Comment by yutannihilation** [comment]
`dicing()`? https://twitter.com/hadleywickham/status/1094985371136475137

**Comment by hadley** [comment]
I think this should probably be incubated in another package, at the least until the dust settles with dplyr 1.0.0

**Comment by mgirlich** [comment]
I think the proposed arguments `.unmatched = c("keep", "drop", "error")` and `.duplicates = c("error", "product")` would be a great addition. I regularly have to add extra code just to check that no rows were accidentally duplicated or unmatched. Would be great to have that integrated into `dplyr`!

**Comment by hadley** [comment]
@mgirlich I think I'm willing to accept this feature now. Would you mind filing an new issue so it doesn't get lost? (I think we'd just add arguments to existing joins, rather than recreating the join function from scratch)
