### ISSUE TITLE
Cannot install dplyr on Fedora

### ISSUE THREAD

**Issue by waynelapierre** [tidyverse/dplyr#3968]
I tried to install dplyr on a Fedora 28 machine, but got the error message

`"cc1: error: '-fcf-protection=full' requires Intel CET support. Use -mcet or both of -mibt and -mshstk options to enable CET"`

**Comment by batpigandme** [comment]
Presume this is the same as your issue on community (not that it was solved there, but linking for continuity):
https://community.rstudio.com/t/cannot-install-tidyverse-on-fedora-28/17187

**Comment by romainfrancois** [comment]
I'm not sure how to help. Perhaps this docker from @r-hub has some information that can help you https://hub.docker.com/r/rhub/fedora-gcc-devel/

**Comment by waynelapierre** [comment]
I figured it out, it is a Fedora 28 issue. This issue is gone for other Fedora versions. I guess it is not worth reporting this as a bug for dplyr or Fedora, since now Fedora 29 has been released.
