### ISSUE TITLE
Grouping variable gets dropped when applying both do() and summarise()

### ISSUE THREAD

**Issue by langbe** [tidyverse/dplyr#3969]
Applying `summarise()` or `do()` to a grouped tbl results in a tibble where the
first column represents the levels of the grouping variable, e.g.

```r
by_cyl <- mtcars %>%
  group_by(cyl)

by_cyl %>% 
  summarise(mean_mpg = mean(mpg))
#> # A tibble: 3 x 2
#>    cyl mean_mpg
#>  <dbl>    <dbl>
#>1     4     26.7
#>2     6     19.7
#>3     8     15.1

by_cyl %>% 
  do(mod = lm(mpg ~ disp, data = .))
#> # A tibble: 3 x 2
#>    cyl mod     
#>* <dbl> <list>  
#>1     4 <S3: lm>
#>2     6 <S3: lm>
#>3     8 <S3: lm>
```

However, when applied in combination the grouping variable gets dropped from the
resulting tibble:

```r
by_cyl %>% 
  do(mod = lm(mpg ~ disp, data = .)) %>%
  summarise(mean_mpg = mean(mod$model$mpg))
#> # A tibble: 3 x 1
#>  mean_mpg
#>     <dbl>
#>1     26.7
#>2     19.7
#>3     15.1
```

I would have expected the grouping variable in the result here as well. Of course, this can easily be obtained by replacing the `summarise()` call by `summarise(cyl = cyl, mean_mpg = mean(mod$model$mpg))`. But why is the default behaviour without the grouping variable?

**Comment by hadley** [comment]
Both `summarise()` and `do()` drop one grouping variable.
