### ISSUE TITLE
Summarise and summarize give different error messages

### ISSUE THREAD

**Issue by antaldaniel** [tidyverse/dplyr#3971]
There was an ancient issue ([#505](https://github.com/tidyverse/dplyr/issues/505)) about error messages, and I ran into them. I found it confusing that two, supposedly identical functions give different error messages. 

Below is the usual mtcars example, and then the variable `disp`  misspelled with `summarise` and `summarize`.  For me the error messages are different. 

```r
mtcars %>%
  group_by(cyl) %>%
  summarise(mean = mean(disp), n = n())

mtcars %>%
  group_by(cyl) %>%
  summarise(mean = mean(disq), n = n())

mtcars %>%
  group_by(cyl) %>%
  summarize(mean = mean(disq), n = n())
```

Error in summarize(., mean = mean(disq), n = n()) : 
  argument "by" is missing, with no default

Error in summarise_impl(.data, dots) : 
  Evaluation error: object 'disq' not found.

I find the second more meaningful, but generally I wonder why the two functions are not in synch.

**Comment by hadley** [comment]
I would recommend creating a [reprex](http://reprex.tidyverse.org/articles/reprex.html) because I'm pretty sure that will reveal that you've loaded another package that masks `summarise()`.
