### ISSUE TITLE
.subset and .keys pronouns

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3972]
Follow up to #3966

New pronouns: 
 - `.subset` : the subset of the data frame for the current group
 - `.keys` : a one row tibble with information about the current group

These would be expensive operations, so should be dealt with lazily, with e.g. an active binding. 

Also, if `.subset` is resolved, then other bindings can just go look in there.

**Comment by jennybc** [comment]
Other possibilities for the current group's data subset: `.df`, `.split`

**Comment by hadley** [comment]
Just a note that I think we are moving away from these magical pronouns in favour of functions like `n()` and `across()` that give a clear error message when called in the incorrect context.

**Comment by hadley** [comment]
I think is almost resolved — you can access the current grouping vars with `current_key()` and the non-grouping vars with `across()`

**Comment by hadley** [comment]
Fixed in #4700
