### ISSUE TITLE
update starwars

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#3983]
```r
> filter(starwars, name == "Luke Skywalker") %>% pull(films)
[[1]]
[1] "Revenge of the Sith"     "Return of the Jedi"      "The Empire Strikes Back" "A New Hope"             
[5] "The Force Awakens"      
```

**Comment by romainfrancois** [comment]
Related to https://github.com/phalt/swapi/issues/108

**Comment by Ryo-N7** [comment]
I'll work on  this for tidy-dev-day! 
@batpigandme please add a tidy-dev-day label.

**Comment by Ryo-N7** [comment]
hmm it looks like I'll have to PR swapi by updating the info in there and THEN dplyr should automatically update when starwars.R is run? 

I'll go ahead and start on a PR for swapi then!

**Comment by hadley** [comment]
Closing this since swapi still not updated; feel free to update if you do manage to get a PR merged with updated data.
