### ISSUE TITLE
summarise conditional sum

### ISSUE THREAD

**Issue by grizzthepro64** [tidyverse/dplyr#3984]
---

In the past, I have been able to use summarise to sum conditionally based on another variable. Now, it throws an error. See message below:

Error in summarise_impl(.data, dots) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.

```r
ex <- tibble(foobar = c('foo','bar','foo','bar'), ab = c('a','b','b','a'), nums = c(2,2,4,6))
ex %>% group_by(foobar) %>% summarise( acount = sum(nums[ab == 'a']), bcount = sum(nums[ab == 'b']))
```

**Comment by romainfrancois** [comment]
@grizzthepro64 you most likely have some version mismatch, I'd suggest to reinstall `dplyr` and `rlang`. 

This works fine for me : 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
ex <- tibble(
  foobar = c('foo','bar','foo','bar'), 
  ab = c('a','b','b','a'), 
  nums = c(2,2,4,6)
)
ex %>% 
  group_by(foobar) %>% 
  summarise(
    acount = sum(nums[ab == 'a']), 
    bcount = sum(nums[ab == 'b'])
  )
#> # A tibble: 2 x 3
#>   foobar acount bcount
#>   <chr>   <dbl>  <dbl>
#> 1 bar         6      2
#> 2 foo         2      4
```

<sup>Created on 2018-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
