### ISSUE TITLE
Adding a "suffix" argument to bind_cols()

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/dplyr#3985]
When you use `bind_cols()` on 2 data frames with same names, automatic integers suffixes are added.

I know `bind_cols` uses `tibble::repair_names` which itself calls `base::make.unique` which adds integers, but it would  be very useful to be able to add custom suffixes,  as seen in `dplyr:::join_vars` used in the `dplyr::*_join()` verbs.

Related:
https://github.com/tidyverse/dplyr/issues/2248
https://github.com/tidyverse/dplyr/issues/3772

```r
x=data.frame(A=c(1,2,3), B=c(4,5,6))
y=data.frame(A=c(7,8,9), B=c(3,2,1))
bind_cols(x, y)
#  A  B A1 B1
#  1  4  7  3
#  2  5  8  2
#  3  6  9  1

#Expected:
bind_cols(x, y, suffix=c(".x", ".y"))
#  A.x B.x A.y B.y
#    1   4   7   3
#    2   5   8   2
#    3   6   9   1
```

**Comment by hadley** [comment]
We are moving to standard system for disambiguating names throughout the tidyverse: https://principles.tidyverse.org/names-attribute.html

**Comment by DanChaltiel** [comment]
I'm sorry but your answer is not very informative, I think the link you provided doesn't adress the feature request at all. Could you explain a little why the request is rejected ? Or how it will be adressed  by the concept you linked ?

**Comment by batpigandme** [comment]
As Hadley said, we're currently working on a way to deal with name repair (what we're calling name disambiguation) in the tidyverse, and the principles are (roughly) outlined at the link. The very last section shows an example of using the `.name_repair` argument with the ~level of repair specified as "universal" https://principles.tidyverse.org/names-attribute.html#messaging-user-about-name-repair

There are three-levels of "naminess" (again, this is a WIP) that we're distinguishing. 
> **Minimal**: The names attribute is not NULL. The name of an unnamed element is "" and never NA.
> **Unique**: No element of names is "" or a duplicate.
> All columns can be accessed by name via df[["name"]].
> **Universal**: The names are unique and syntactic.
> Names work everywhere, without quoting: df$name and lm(name1 ~ name2, data = df) and dplyr::select(df, name) all work.

name repair will be offloaded to `as_tibble()` (see the threads below for more detail):
https://github.com/tidyverse/tibble/issues/539
https://github.com/tidyverse/dplyr/issues/2401
