### ISSUE TITLE
filter() on grouped data: breaks assumptions about how data frames work

### ISSUE THREAD

**Issue by hughjonesd** [tidyverse/dplyr#3989]
Data frames can be thought of as ordered by row, and subsetting operations do not change the order. Up till now (I believe!) this has been true of `filter`. dplyr 0.8.0 changes this: grouped data can be reordered by a `filter` operation. This has some problems:

* It breaks existing code which assumes that `filter` is order-preserving. `filter` never gave an explicit guarantee to preserve row order -- nor does `select` or `mutate` -- but it has probably been expected, by the analogy between `dfr[dfr$foo < x,]` and `filter(dfr, foo < x)`. #3929 gives some examples of the kinds of real code which could be broken by the change.
* It may introduce a source of bugs, by breaking people's assumptions about how data frames work.
* It makes it harder to understand what dplyr code is doing.

Here are some MWEs. 

1. This example shows how statistical results can be silently changed by upgrading.

```
set.seed(27101975)
library(tidyverse)
dfr <- tibble(g = c(1, 2, 1, 2, 1), time = 5:1, x = 5:1, y = x + rnorm(5)) %>%
      group_by(g) %>%
      arrange(time) %>%
      filter(x <= 4)

lm(y ~ lag(x), dfr) 
# under 0.8.0, coefficients are 2.942 and 0.01903
# under CRAN, coefficients are 3.037 and -0.038
``` 

2. The next example shows three simple pipes that look as if they do the same thing:

```
tibble(g = c(1, 2, 1, 2, 1), time = 5:1, x = 5:1) %>%
      group_by(g)   %>%
      arrange(time) %>%
      filter(x <= 4)

tibble(g = c(1, 2, 1, 2, 1), time = 5:1, x = 5:1) %>%
      group_by(g)  %>%
      filter(x <= 4)  %>%
      arrange(time)

tibble(g = c(1, 2, 1, 2, 1), time = 5:1, x = 5:1) %>%
      filter(x <= 4)  %>%
      arrange(time) %>%
      group_by(g) 
```

Under 0.8.0, the first gives different results. You have to rearrange your data every time that you filter it. You also must know whether your data is currently grouped, before understanding what `filter` will do.

To repeat my earlier comment, I appreciate there may be good performance-related reasons for the change, but I want to point out that it can silently break existing code and analyses, and make it harder to reason about new code.

I did a basic and very non-scientific microbenchmark on my Macbook Air, under 0.8.0:

```
big_dfr <- tibble(x = rnorm(1e6), g = sample(1000, 1e6, replace = TRUE))
microbenchmark::microbenchmark(big_dfr %>% group_by(g) %>% filter(x < 0))
Unit: milliseconds
                                      expr      min       lq   mean   median       uq      max neval
 big_dfr %>% group_by(g) %>% filter(x < 0) 76.23991 85.65879 103.34 91.30641 98.61864 212.9976   100
```

And under CRAN:
```
Unit: milliseconds
                                      expr      min       lq     mean   median       uq      max neval
 big_dfr %>% group_by(g) %>% filter(x < 0) 116.2923 122.3737 138.8151 130.0683 148.0006 321.7637   100
```

This is a huge relative speedup, but in absolute terms it is 40 milliseconds; fixing code breakages seems likely to take much longer than this. So for those of us working with < 1m rows in our data, I am not sure the gain is worthwhile.

**Comment by hadley** [comment]
Your example would be easier to understand if you included a reprex:

``` r
library(dplyr, warn.conflicts = FALSE)
tb <- tibble(g = c(1, 2, 1, 2, 1), time = 5:1, x = 5:1)

tb %>%
  group_by(g) %>%
  arrange(time) %>%
  filter(x <= 4)
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       g  time     x
#>   <dbl> <int> <int>
#> 1     1     1     1
#> 2     1     3     3
#> 3     2     2     2
#> 4     2     4     4

tb %>%
  group_by(g) %>%
  filter(x <= 4) %>%
  arrange(time)
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       g  time     x
#>   <dbl> <int> <int>
#> 1     1     1     1
#> 2     2     2     2
#> 3     1     3     3
#> 4     2     4     4

tb %>%
  filter(x <= 4) %>%
  arrange(time) %>%
  group_by(g)
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       g  time     x
#>   <dbl> <int> <int>
#> 1     1     1     1
#> 2     2     2     2
#> 3     1     3     3
#> 4     2     4     4
```

To be clear, the order _within_ groups is preserved, so for this to be a problem you need to be depending on order _across_ groups. That sort of code feels very fragile to me. That said, it does seem to introduce a inconsistency between `arrange()` (which deliberately ignores grouping) and `filter()` (which now imposes grouping).

**Comment by hadley** [comment]
OTOH this makes `filter()` more consistent with `summarise()`.

**Comment by hughjonesd** [comment]
I think it is true that if you are writing robust code, you won't be hit by this. But I am not sure that I have always done that: under pressure to get results out, I often write inelegant code that "just works". And, I think that "filter won't reorder things" is probably quite a basic assumption, that many people won't have expected to break when they wrote stuff.

Maybe the main question is, who benefits and by how much from the change? I don't benefit significantly, but perhaps others will.

**Comment by hughjonesd** [comment]
Thank you for listening and responding. Hope I helped you make a good choice.

**Comment by echasnovski** [comment]
Issue with possible reordering got me thinking that people might have implicit expectations about preservation of row/column order in dplyr functions.

Maybe it would be a good idea to explicitly document package expectation for basic dplyr functions' outputs? For example "`select()` never reorders rows and returns columns as user requested". This might be useful not only for users but for developers (both tidyverse and other packages) too.
