### ISSUE TITLE
%not_in%

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#3993]
Several packages define a variation of  `Negate("%in%")`, but it would be useful to have one in the `tidyverse` (if there's one I didn't find it!). The most prominent package that has it as far as I can tell is `Hmisc` with `nin`.

Wouldn't it be relevant in `dplyr` ?

**Comment by hadley** [comment]
I have yet to see a compelling argument for why you would prefer `x %not_in% y` to the shorter `!x %in% y`.

**Comment by moodymudskipper** [comment]
I understand. Here why it's compelling to me :

- It's not always the case that `!` and `%in%` are close to one another, there might be a sophisticated or operation in between : 
`! some_variable * something_else %in% some_set`, when you have a code sandwich probem of the same nature than the one pipes help to solve, harder to read and to edit.
- It's a very common operation, it's nice to be able to do a common operation with one operator rather than two, that's a precious little piece of cognitive load to spare.
- An example: `!=` exists, and I'm happy that I don't have to type `!x == y` for `x != y` though it's just an extra character.
- It's not necessarily longer, `%ni%`, `%nin%` and `%!in%` are shorter or as long
- If we look at `! u %in% v && x %in% y` : the operator precedence is not obvious (to everyone), to be safe a user might type `(!(u %in% v)) && x %in% y`, while `u %!in% v && x %in% y` is fairly unambiguous.
- That's one `!` less in the `tidyverse`, which has a lot of them
- it doesn't cost much

That's all I have!
