### ISSUE TITLE
Strange bug with group_by() and min() 

### ISSUE THREAD

**Issue by gowerc** [tidyverse/dplyr#3997]
Very strange bug where warning messages are suppressed based upon where a function input is `TRUE` or `T` please see example below:

```
library(tidyverse)

data_frame(
    x = c(NA, NA,NA, 1), 
    y = c("a","a","b","b")
) %>% 
    group_by(y) %>% 
    summarise( z = min(x, na.rm=TRUE))

# A tibble: 2 x 2
  y         z
  <chr> <dbl>
1 a       Inf
2 b         1
```

compared to 

```
library(tidyverse)

data_frame(
    x = c(NA, NA,NA, 1), 
    y = c("a","a","b","b")
) %>% 
    group_by(y) %>% 
    summarise( z = min(x, na.rm=T))

# A tibble: 2 x 2
  y         z
  <chr> <dbl>
1 a       Inf
2 b         1
Warning message:
In min(x, na.rm = T) : no non-missing arguments to min; returning Inf
```

Note that the only difference between these two blocks of code is that the first one uses `na.rm=TRUE` and the second uses `na.rm=T`. I have not yet been able to reduce this any further to understand what is driving this behavior

This was tested in versions:
R 3.5.1 , 
tidyverse 1.2.1
dplyr 0.7.8

**Comment by romainfrancois** [comment]
`TRUE` is a reserved word so the expression `min(x, na.rm=TRUE)` can be handled by hybrid evaluation. 

`T` is not, so it cannot., so the expression is evaluated by R, which throws this warning. 

We could add the warning in the hybrid path too, perhaps.
