### ISSUE TITLE
count() ignores non-factor empty groups

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#4013]
This is because regrouping happens before `tally()` here:

https://github.com/tidyverse/dplyr/blob/7105bbd9ad3fba9f33a30b35ef0506ed0a4208ec/R/count-tally.R#L122

I'm still thinking if this is the expected behaviour. If this needs to be fixed, I feel it would be tricky; to regroup them, we need to know the original levels, but it's already lost if the variable is not factor.

``` r
library(dplyr, warn.conflicts = FALSE)

d <- data.frame(x = c("a", "a", "b", "b"),
                value = 1:4,
                stringsAsFactors = FALSE)

g <- d %>%
  group_by(x) %>%
  filter(value > 3, .preserve = TRUE)

count(g)
#> # A tibble: 1 x 2
#> # Groups:   x [1]
#>   x         n
#>   <chr> <int>
#> 1 b         1

summarise(g, n = n())
#> # A tibble: 2 x 2
#>   x         n
#>   <chr> <int>
#> 1 a         0
#> 2 b         1
```

<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
Something like this would fix it I guess: 

```r
  if(rlang::dots_n(...)){
    x <- group_by(x, ..., add = TRUE)  
  }
```

Full reprex below, @hadley ?

``` r
library(dplyr, warn.conflicts = FALSE)

d <- data.frame(x = c("a", "a", "b", "b"),
  value = 1:4,
  stringsAsFactors = FALSE)

g <- d %>%
  group_by(x) %>%
  filter(value > 3, .preserve = TRUE)

count <- function(x, ..., wt = NULL, sort = FALSE) {
  groups <- group_vars(x)
  
  if(rlang::dots_n(...)){
    x <- group_by(x, ..., add = TRUE)  
  }
  x <- tally(x, wt = !!enquo(wt), sort = sort)
  x <- group_by(x, !!!syms(groups), add = FALSE)
  x
}

count(g)
#> # A tibble: 2 x 2
#> # Groups:   x [2]
#>   x         n
#>   <chr> <int>
#> 1 a         0
#> 2 b         1

summarise(g, n = n())
#> # A tibble: 2 x 2
#>   x         n
#>   <chr> <int>
#> 1 a         0
#> 2 b         1
```

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by yutannihilation** [comment]
Thanks, looks good. But, I'm still wondering if `count()` invokes regrouping, it should always invoke, not conditionally. I can't decide which is more predictable behaviour...

**Comment by romainfrancois** [comment]
I would prefer to get the same result as `summarise(n())` but I might miss the bigger picture.

**Comment by hadley** [comment]
Your proposal sounds good. We should double-check that there aren't other functions like `count()` that also need to be modified.
