### ISSUE TITLE
feature request for distinct(): ignore certain values (i.e. introducing the incomparables argument)

### ISSUE THREAD

**Issue by yiqinfu** [tidyverse/dplyr#4015]
I'm hoping to find rows in my df that are distinct across multiple columns. I'd also like the distinct() function to ignore `NA`s when making comparisons. For example, for the following df, I hope to retain four rows when finding distinct values across columns `a` and `b`. But `distinct()` returns three rows (as it should).

```r
df = data.frame(a = c(1, 1, 2, 2, 2), b = c(NA, NA, 1, 1, 2), c = rep(1, 5)) %>%
distinct(a, b, .keep_all = T)
```

Adding this feature would be great because although the base function ``duplicated`` has an argument called `incomparables` that lets you ignore certain values, it doesn't take `incomparables` as an argument when one tries to find distinct across *multiple* columns.

I found a blog post from 2016 that documents the same issue:

> As I found out, the duplicated function can handle multiple columns, but the incomparables argument does not work for multiple columns, let alone different incomparable values for each column.

> One hack would be to paste0() the columns together and work on a single pasted column, but this doesn’t handle multiple incomparable values.

**Comment by romainfrancois** [comment]
There is no notion of incomparable, you can do something like this to separate the comparable from the incomparables

``` r
library(dplyr, warn.conflicts = FALSE)

distinct2 <- function(df, predicate_incomparable, ...) {
  predicate_incomparable <- enquo(predicate_incomparable)
  
  # rows for which the predicate os true for at least one variable
  incomparables <- filter_all(df, any_vars(!!predicate_incomparable))
  
  # rows for which the predicate is false for all variables
  comparables <-  filter_all(df, all_vars(!(!!predicate_incomparable)))
  
  bind_rows(
    distinct(comparables, ...), 
    incomparables
  )
}

df <- tibble(
  a = c(1 , 1 , 2, NA, 2, 2, 2), 
  b = c(NA, NA, 1, 1 , 2, 2, 1), 
  c = rep(1, 7), 
)
distinct2(df, is.na(.))
#> # A tibble: 5 x 3
#>       a     b     c
#>   <dbl> <dbl> <dbl>
#> 1     2     1     1
#> 2     2     2     1
#> 3     1    NA     1
#> 4     1    NA     1
#> 5    NA     1     1
```

<sup>Created on 2018-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
