### ISSUE TITLE
Feature request: top_frac

### ISSUE THREAD

**Issue by zx8754** [tidyverse/dplyr#4017]
Similar to `sample_n` and `sample_frac`, can we have `top_frac`?

**Task:** Using _mtcars_ data, sort by _mpg_, then get 5%. 

Currently, we could use `top_n` as below:
```R
library(dplyr)
top_n(x = mtcars, n = round(nrow(mtcars) * 0.05), wt = mpg)
#    mpg cyl disp hp drat    wt  qsec vs am gear carb
# 1 32.4   4 78.7 66 4.08 2.200 19.47  1  1    4    1
# 2 33.9   4 71.1 65 4.22 1.835 19.90  1  1    4    1
```

But with `top_frac` it would look neater, something like:
```R
top_frac(x = mtcars, size = 0.05, wt = mpg)
```

**Comment by romainfrancois** [comment]
Before we can do that, `top_n()` should allow quosures for `n`, i.e. this should be alright: 

``` r
library(dplyr, warn.conflicts = FALSE)

top_n(mtcars, n() / 2)
#> Selecting by carb
#> n() should only be called in a data context
```

<sup>Created on 2019-06-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
