### ISSUE TITLE
dplyr 0.8.0 cannot find n() if dplyr is not attached

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#4030]
This code works with dplyr 0.7.8 without attaching dplyr, but fails with the current dev version.

``` r
dplyr::mutate(data.frame(), n = n())
#> Error in n(): could not find function "n"
```

I feel the 0.8.0's behavior is valid, but I found prophet package use them without specifying `dplyr::` or attaching dplyr.

https://github.com/facebook/prophet/blob/c9f1ccaa63233f5c3e9e1f013aadd1e97dc5538c/R/R/prophet.R#L888

If this is the supposed behavior, you may need to educate package developers about this.

**Comment by romainfrancois** [comment]
Thanks. I think the behaviour is right, we'll see if that triggers revdep problems in #3931

**Comment by yutannihilation** [comment]
Thanks, then, I close this issue for now :)
