### ISSUE TITLE
bind_rows() Column `x` can't be converted from character to Date

### ISSUE THREAD

**Issue by damianooldoni** [tidyverse/dplyr#4040]
Binding a empty data.frame with a not empty data.frame I got this erorr: `Column 'colname' can't be converted from character to Date`:

```r
> a <- tibble::tibble(dateAdded = character())
> class(a$dateAdded) <- "Date"
> a
# A tibble: 0 x 1
# ... with 1 variable: dateAdded <date>
> b <- tibble::tibble(dateAdded = as.Date("2018-01-01"))
> b
# A tibble: 1 x 1
  dateAdded 
  <date>    
1 2018-01-01
> dplyr::bind_rows(a, b)
Error in bind_rows_(x, .id) : 
  Column `dateAdded` can't be converted from character to Date
```

The errror is quite strange, as the column `dateAdded` of both dataframes is not of type `character`, but `date`. I get the same error with basic data.frame instead of tibble.

**Comment by krlmlr** [comment]
Dates are numerics (or integers) with class `"Date"`, not strings:

``` r
typeof(Sys.Date())
#> [1] "double"
dput(Sys.Date())
#> structure(17884, class = "Date")
```

<sup>Created on 2018-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by damianooldoni** [comment]
Thanks @krlmlr. Just changing the very first line:
```
a <- tibble::tibble(dateAdded = double())
```
solved the issue. 

However, I find confusing that R doesn't show any difference between the date column of my original `a` and `b`:
```
> a
# A tibble: 0 x 1
# ... with 1 variable: dateAdded <date>
> b
# A tibble: 1 x 1
  dateAdded 
  <date>    
1 2018-01-01
```
and most of all that R allows assigning class `Date` to an empty character column:
```r
> a <- tibble::tibble(dateAdded = character())
> class(a$dateAdded) <- "Date"
> class(a$dateAdded)
[1] "Date"
```
Still thanks.

**Comment by hadley** [comment]
@damianooldoni I'd recommend reading https://adv-r.hadley.nz/s3.html#s3-classes — R does not offer the sort of guarantee that you seem to be looking for.

**Comment by damianooldoni** [comment]
Thanks @hadley . Yes, sometimes I forget that types and classes are definitely not the same stuff. Nice tutorial. Thanks again.
Issue can be closed.

**Comment by romainfrancois** [comment]
Done. Please note @damianooldoni that as the author of the issue you have the right to close it too :-)
