### ISSUE TITLE
case_when() to skip NA or at least add example in doc to explicit convert NA

### ISSUE THREAD

**Issue by statsccpr** [tidyverse/dplyr#4041]
Hi,

Before getting familiar with `case_when()` i expected its behavior to be similar to  `base::ifelse()` where it skips input cases that are NA by default

```
> x=c(NA,5,-1); ifelse(x>=1,x,'FALSE')
[1] NA      "5"     "FALSE"
```

i've been burned by the situation when there are NA's in the input data that i then heavy handedly mutate with `case_when()`. This results in true input NAs to unexpectedly be converted to whatever the last foo value in the final clause `TRUE~foo` was used

```
dat_in = iris
dat_in[1:5,"Species"] = NA

# dplyr version
[1] dplyr_0.7.8
```

```
dat_in %>%
  mutate(species_isna = 
           case_when(
             Species == 'setosa' ~ '1',
             TRUE ~ 'other'
           )) %>% 
  View()
```
The 5 NAs of Species are converted into the value 'other'

Currently, the user is expected to have the foresight to explicitly add a clause to check for NAs and then carry forward that NA , via the nice feature implemented since https://github.com/tidyverse/dplyr/pull/2000

```
dat_in %>%
  mutate(species_isna = 
           case_when(
             Species == 'setosa' ~ '1',
             is.na(Species) ~ NA_character_,
             TRUE ~ 'other'
           )) %>% 
  View()
```

If I'm a first time user or if I didn't follow those guidelines, I would get burned by the true NAs not being passed forward, leading to possibly wrong conclusions / sideeffects down the line.

I think a quick improvement would be to add to the help documentation of `?case_when` . Where you either add an example about explicitly converting NAs or some disclaimer on how it's different than `base::ifelse()` when it comes to skipping NAs.

A bigger question is, do you think an optional toggle `case_when(...,na_skip=TRUE)` would be good?
where `na_skip=FALSE` is the current behavior and when `na_skip=TRUE` gives the `base::ifelse()` type of behavior

**Comment by jschelbert** [comment]
I'd rather include some hint in the doc. From my understanding `case_when` works by consecutively checking the statements given by the user. If you provide a statement that is always true (i.e. `TRUE`) then this value is used an all other checks that might come after that are not run. I'll try to update the docu.

**Comment by jschelbert** [comment]
I've added one more example to the docu. Hope this clarifies the behavior of the function a bit better. Unfortunately, it got mixed up with another PR #4003 but the changes are minimal, so I hope it goes through without an explicit new one.

**Comment by romainfrancois** [comment]
The example from @jschelbert was merged
