### ISSUE TITLE
Should verbs raise error when the corresponding group info is unavailable?

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#4047]
If dplyr allows external packages to modify/create the `group` attributes (c.f. #4045), there's no garantee that the group structure is always consistent with the actual data. I see the functions that depends on the group information (e.g. `n()`) behave unexpectedly (maybe they reference uninitialized memory...?). This seems dangerous.

``` r
library(dplyr, warn.conflicts = FALSE)

g <- data.frame(x = 1:3) %>%
  group_by(x)

attr(g, "groups") <- attr(g, "groups")[1:2, ]

g %>%
  mutate(n = n())
#> # A tibble: 3 x 2
#> # Groups:   x [3]
#>       x         n
#>   <int>     <int>
#> 1     1         1
#> 2     2         1
#> 3     3 504875720
```

<sup>Created on 2018-12-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
I'd say it's up to the packages to do it right, they can use `new_grouped_df()` and `validate_grouped_df()`. 

The `"groups"` attribute is still an implementation detail, it just happens to be easier to work with than the previous structure. 

Testing all the time that the "groups" attribute is valid is expensive. I'm fine with having "undefined behaviour"

**Comment by yutannihilation** [comment]
I see.
