### ISSUE TITLE
separate_rows() on empty tibble drops column

### ISSUE THREAD

**Issue by behrman** [tidyverse/dplyr#4057]
`separate_rows()` on an empty tibble is not a no-op. Instead, it drops the column to be separated. If you have a pipe that calculates a tibble that might be empty, this would break any following code that tries to reference that column. I would consider making `separate_rows()` a no-op for empty tibbles.

``` r
library(tidyverse, warn.conflicts = FALSE)

tibble(col = character()) %>% 
  separate_rows(col)
#> # A tibble: 0 x 0
```

<sup>Created on 2018-12-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
`separate_rows()` is a tidyr's function. Maybe https://github.com/tidyverse/tidyr/issues/470 is the same issue?

**Comment by behrman** [comment]
Yes, I should have checked tidyr. This is the same issue.
