### ISSUE TITLE
Mask operators with vctrs-powered aliases?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#4059]
Probably not realistic because it would likely break existing code. However, we'd get much more sensible behaviour and fail early with informative diagnostics when beginners make mistakes:

```r
x <- "height"

filter(starwars, x < 200)
#> # A tibble: 0 x 13
#> # … with 13 variables: name <chr>, height <int>, mass <dbl>,
#> #   hair_color <chr>, skin_color <chr>, eye_color <chr>, birth_year <dbl>,
#> #   gender <chr>, homeworld <chr>, species <chr>, …

"height" < 200
#> [1] FALSE
```

**Comment by hadley** [comment]
Yeah, I think this would have to be opt-in somehow.

**Comment by hadley** [comment]
Moved to https://github.com/r-lib/funs/issues/33
