### ISSUE TITLE
filter function failed

### ISSUE THREAD

**Issue by htc502** [tidyverse/dplyr#4065]
---
filter fails when using a vector that has the same name of a tibble column.
```r
# insert reprex here
cls = c('a','b')
df = tbl_df(data.frame(ID = 1:10, cls = rep(c('a','b'),each = 5)))
filter(df, cls == cls[1]) ##work properly
filter(df, cls == cls[2]) ## will not work
```
sessionInfo():
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2   dplyr_0.7.7      RevoUtils_10.0.9

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     utf8_1.1.3       crayon_1.3.4     assertthat_0.2.0
 [5] R6_2.2.2         magrittr_1.5     pillar_1.1.0     cli_1.0.0       
 [9] rlang_0.3.0.1    glue_1.2.0       purrr_0.2.4      compiler_3.4.4  
[13] pkgconfig_2.0.1  bindr_0.1.1      tidyselect_0.2.3 tibble_1.4.2

**Comment by yutannihilation** [comment]
You need to unquote `cls[2]`. Otherwise, `cls` refers to `cls` column, not the variable you defined outside of the data.frame.

``` r
library(dplyr, warn.conflicts = FALSE)

cls = c('a','b')
df = tbl_df(data.frame(ID = 1:10, cls = rep(c('a','b'),each = 5)))
filter(df, cls == cls[2])
#> # A tibble: 5 x 2
#>      ID cls  
#>   <int> <fct>
#> 1     1 a    
#> 2     2 a    
#> 3     3 a    
#> 4     4 a    
#> 5     5 a
filter(df, cls == !!cls[2]) 
#> # A tibble: 5 x 2
#>      ID cls  
#>   <int> <fct>
#> 1     6 b    
#> 2     7 b    
#> 3     8 b    
#> 4     9 b    
#> 5    10 b
```

<sup>Created on 2019-01-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
Indeed, this is a feature, and unquoting is the way around it.
