### ISSUE TITLE
Replace uses of data_frame() by tibble()

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4069]
_This issue is to be dealt with on [Tidyverse developer day 2019](https://rstd.io/tidy-dev-day). 🙏 don't submit pull requests for it outside of the event. We are of course interested in having this fixed, but much more interested in doing it as part of the developer day_

 - [ ] identify uses of the deprecated function `data_frame()` in the dplyr codebase: code, docs, tests, vignette. 
 - [ ] replace with uses of `tibble()`  

Bonus: other 📦 might be using `data_frame()`: 

 - identify them, perhaps using `gh` to search github or maybe `crandb`
 - submit pull requests

**Comment by Copepoda** [comment]
I'm working on this :)
