### ISSUE TITLE
Deprecation scavenger hunt 🕵️‍♀️ 

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4070]
_This issue is to be dealt with on [Tidyverse developer day 2019](https://rstd.io/tidy-dev-day). 🙏 don't submit pull requests for it outside of the event. We are of course interested in having this fixed, but much more interested in doing it as part of the developer day_

Some dplyr functions are deprecated, soft deprecated, ... but might still be used by dependent 📦s in the wild. 

 - [ ] identify which functions are deprecated, ... perhaps with https://github.com/r-lib/lifecycle/issues/2
 - [ ] write a document about migrating to newer approaches
 - [ ] identify which packages use deprecated functions
 - [ ] communicate with package authors, with email or pull requests

**Comment by markvanderloo** [comment]
Hi Romain,

I'm a bit confused about the term 'soft deprecated'. I've seen the term being used around RStudio's packages more often, but AFAIK, R only has a `.Deprecated()` status. Could you clarify?

Mark

**Comment by romainfrancois** [comment]
This will be defined as part of the [lifecycle](https://github.com/r-lib/lifecycle) package. Until, then some of our packages have the [compat-lifecycle.R](https://github.com/r-lib/rlang/blob/master/R/compat-lifecycle.R) file that contains some information.

**Comment by romainfrancois** [comment]
I'm closing this now, as it does not have an easily accessible success criteria. I'll open similar issues for the next tdd.
