### ISSUE TITLE
Tally naming behaviour changed

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#4076]
``` r
library(dplyr, warn.conflicts = FALSE)
tibble(n = 1:3) %>% tally()
#> Using `n` as weighting variable
#> # A tibble: 1 x 1
#>       n
#>   <int>
#> 1     6
```

<sup>Created on 2019-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It used to create a column called `nn` — I think this is a result of https://github.com/tidyverse/dplyr/pull/3991#discussion_r242492031

I just wanted to check that this was deliberate and correct

**Comment by romainfrancois** [comment]
Probably related to #3838. This might at least need more work on the doc, currently: 

```
#' @note
#' The column name in the returned data is usually `n`, even if you
#' have supplied a weight.
#'
#' If the data already has a column named `n`, the output column
#' will be called `nn`. If the table already has columns called `n` and `nn`
#' then the column returned will be `nnn`, and so on.
#'
#' To control the output column name use `name`.
```

**Comment by hadley** [comment]
The more I think about it, the more I think that the new behaviour is correct — we only use `nn` if `n` would otherwise be present in the output.

**Comment by hadley** [comment]
But yes, the docs do need to be updated too.

**Comment by hadley** [comment]
Let's do this in 0.9.0 to avoid breaking new revdeps.

**Comment by hadley** [comment]
Replaced by #4284
