### ISSUE TITLE
Double Numeric Precision Comparison: dplyr::near() Family

### ISSUE THREAD

**Issue by jtelleria** [tidyverse/dplyr#4078]
dplyr::near() is a safe way of comparing if two vectors of floating point numbers are (pairwise) equal. This is safer than using ==, because it has a built in tolerance.

However, it would be very interesting to integrate into dplyr the whole family of Double Point Precision Comparison Functions ("fpCompare" Package): 

```{r}
b %<=% a    # b <= a 
b %<<% a    # b <  a
b %>=% a    # b >= a 
b %>>% a    # b >  a
b %==% a    # b == a
b %!=% a    # b != a 
````

http://predictiveecology.org/2015/05/16/fpCompare.html

https://cran.r-project.org/web/packages/fpCompare/index.html

Code could be ported from this contributed package functions directly (With minor modifications) into dplyr, and give recognition to the package author. If "ok" I could port the functions myself and do a pull request.

**Comment by romainfrancois** [comment]
I'm not sure I understand why that would have to be integrated into dplyr.

**Comment by jtelleria** [comment]
Newcomers to R might not understand double precision comparison:

```{r}

>* 0.1+0.1==0.2
*[1] TRUE
>* 0.1+0.1+0.1+0.1==0.4
*[1] TRUE
>* 0.1+0.1+0.1==0.3
*[1] FALSE
>* 0.1+0.1+0.1==0.1*3
*[1] TRUE
>* 0.3==0.1*3
*[1] FALSE

```
By adding this flaoting point "safe" functions, and properly documenting
them in the dplyr cheatsheets we would avoid error as above to be done by R
new users.

When I started programming in R, I was myself fooled by previous
comparisons a couple of times.

**Comment by jtelleria** [comment]
Newcomers to R might not understand double precision comparison:

```{r}
0.1+0.1==0.2
[1] TRUE
0.1+0.1+0.1+0.1==0.4
[1] TRUE
0.1+0.1+0.1==0.3
[1] FALSE
0.1+0.1+0.1==0.1*3
[1] TRUE
0.3==0.1*3
[1] FALSE
```
By adding this flaoting point "safe" functions, and properly documenting them in the dplyr cheatsheets we would avoid error as above to be done by R new users.

When I started programming in R, I was myself fooled by previous comparisons a couple of times.

**Comment by romainfrancois** [comment]
Sure. But people have to learn about this at some point. One could also argue that introducing funny looking operators to newcomers might also be a source of confusion. 

I do understand the value of the `fpCompare` package, but I believe this is our of scope here. 

We have already some issues with tolerance, i.e. #2751 and #2264 and probably some other related to joins, but this is a separate problem.

**Comment by hadley** [comment]
This is out of scope for dplyr, since we are not planning to add any more vector functions. You could file an issue in https://github.com/r-lib/funs/issues instead, but I don't really see the advantage over simply telling people about the fpCompare package.
