### ISSUE TITLE
count()/add_count() should preserve input classes

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#4086]
(Originally reported at https://github.com/tidyverse/dplyr/issues/4051#issuecomment-451820740.)

<details>
``` r
library(dplyr, warn.conflicts = FALSE)

x <- as_tibble(iris)
g <- group_by(x, Species)
class(g) <- c("myclass", class(g))

x %>%
  add_tally() %>%
  class()
#> [1] "tbl_df"     "tbl"        "data.frame"

x %>%
  add_count() %>%
  class()
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
</details>

**Comment by romainfrancois** [comment]
Note that the original reprex used `x` instead of `g`. 

``` r
library(dplyr, warn.conflicts = FALSE)

x <- as_tibble(iris)
g <- group_by(x, Species)
class(g) <- c("myclass", class(g))
class(g)
#> [1] "myclass"    "grouped_df" "tbl_df"     "tbl"        "data.frame"

g %>%
  add_tally() %>%
  class()
#> [1] "grouped_df" "tbl_df"     "tbl"        "data.frame"

g %>%
  add_count() %>%
  class()
#> [1] "grouped_df" "tbl_df"     "tbl"        "data.frame"
```

This is part of our design for the 0.9.* series. We essentially need to find a way to let some method of `myclass` express this. At the moment we have no idea what an object of class `myclass` would need to do in that situation, so treating it as a `grouped_df` is "the best we can do"

**Comment by yutannihilation** [comment]
Ah, I don't know why I didn't used `g`, sorry... Looking forward to v0.9!

**Comment by elinw** [comment]
This is really inconsistent with the fact that elsewhere in dplyr 0.8.0 you have stopped stripping classes.

**Comment by romainfrancois** [comment]
Fixing these things is planned for the 0.9.* series because we’ll benefit from better vctrs support.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

x <- data.frame(x = 1:3)
x %>% count() %>% class()
#> [1] "tbl_df"     "tbl"        "data.frame"
x %>% add_count() %>% class()
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2019-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(`tally()` and `add_tally()` don't touch the classes so don't need to be considered further)

**Comment by hadley** [comment]
We might want to solve this with a generic mechanism for temporarily grouping, performing some operation, and then restoring groups (some sort of `with_groups()`), which we could also export.

**Comment by hadley** [comment]
Somewhat more comprehensive reprex:

```R
df <- structure(data.frame(x = 1:3), class = c("myclass", "data.frame"))
df %>% count() %>% class()
df %>% count(x) %>% class()
df %>% add_count() %>% class()
df %>% add_count(x) %>% class()
```
