### ISSUE TITLE
joining by different variables

### ISSUE THREAD

**Issue by eijoac** [tidyverse/dplyr#4087]
When joining by different variables, it would be better if the resulting tibble can keep both the variables.

```r
t1 <- tribble(
  ~pk, ~t1c1,
     1, "a"
)
t2 <- tribble(
  ~fk, ~t2c1,
     3, "e"
)

right_join(t1, t2, by = c("pk" = "fk"))

## # A tibble: 1 x 3
##      pk t1c1  t2c1 
##   <dbl> <chr> <chr>
## 1    3. <NA>  e
```
Although OK, but the value `3` under the `pk` column is a bit confusing (not ideal). The following would be better.

```r
  pk    t1c1     fk t2c1 
  <dbl> <chr> <dbl> <chr>
1 NA    NA       3. e 
```

**Comment by romainfrancois** [comment]
That would no longer be a join then ?

**Comment by eijoac** [comment]
Why? Maybe this example is better?

```r
t1 <- tribble(
  ~pk, ~t1c1,
     1, "a",
     2, "b"
)
t2 <- tribble(
  ~fk, ~t2c1,
     1, "c",
     1, "d",
     3, "e"
)

right_join(t1, t2, by = c("pk" = "fk"))

# A tibble: 3 x 3
     pk t1c1  t2c1 
  <dbl> <chr> <chr>
1    1. a     c    
2    1. a     d    
3    3. NA    e    
```

Why do i have to combine the two key variables into one (moreover, put the values of `fk` to `pk` when no right-matching in left table)? As i said, it's OK, but it's a bit confusing (not too good a design).

**Comment by batpigandme** [comment]
You fundamentally need a key column to join, but I think what you're describing is closer to a full join than a one-sided one…

https://dplyr.tidyverse.org/reference/join.html

``` r
library(dplyr)

t1 <- tribble(
  ~pk, ~t1c1,
  1, "a",
  2, "b"
)
t2 <- tribble(
  ~fk, ~t2c1,
  1, "c",
  1, "d",
  3, "e"
)

full_join(t2, t1, by = c("fk" = "pk"))
#> # A tibble: 4 x 3
#>      fk t2c1  t1c1 
#>   <dbl> <chr> <chr>
#> 1     1 c     a    
#> 2     1 d     a    
#> 3     3 e     <NA> 
#> 4     2 <NA>  b
```
<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by eijoac** [comment]
I do have the two key columns in the two tables for the join. I don't need a full join. Your full join result is different from my right join.

I think this is more of a design choice. My point is that the current choice is not too good (although OK). For example, SQL (I tried MySQL implementation) would give me what i described.

```
SELECT *
FROM t1
  RIGHT JOIN t2
  ON t1.pk = t2.fk;
```
The would give me

| pk	| t1c1	| fk	| t2c1	|
|:-----:|:-----:|:-----:|:-----:|
| 1	| a	| 1	| c	|
| 1	| a	| 1	| d	|
|null	| null	| 3	| e	|

**Comment by hadley** [comment]
I don't see the point in storing the same values in two columns.
