### ISSUE TITLE
dplyr scoped verbs not working with non-syntactic variable names

### ISSUE THREAD

**Issue by brooke-watson** [tidyverse/dplyr#4094]
dplyr verbs are throwing errors when they encounter a column name that starts with two dots (e.g. `..1`). 

This came up in the context of the recent readxl updates, which changed the handling of missing column names from `x_1`, `x_2` etc. to `..1`, `..2`. 

I ran into it with mutate_all, but it seems that the error persists across summarize, rename, select and filter, for both scoped and non-scoped variants. 

Here's a reprex: 

```r
mutate_all(tibble(`..1` = "1"), toupper)
```
```r
Error in mutate_impl(.data, dots) : 
  Evaluation error: ..1 used in an incorrect context, no ... to look in.
```

The introduction of `..n` variables can be avoided with a different .name_repair argument call in readxl, but I wanted to flag in case this is error is not desired behavior for dplyr. Thanks!

**Comment by romainfrancois** [comment]
Thanks, yeah I guess `.name_repair = "universal"` in `read_xls` would avoid names like `..1` which have special meaning. ping @jennybc 

I don't think we can make it work, i.e. it's the same as: 

``` r
`..1` <- "1"
toupper(`..1`)
#> Error in toupper(..1): ..1 used in an incorrect context, no ... to look in
```

What we could do is make `manip_all` emit a better error message on such names (ping @lionel-) and fail early. The problem does not exist when this goes through hybrid evaluation, e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)
dplyr::mutate_all(tibble(`..1` = 1), mean)
#> # A tibble: 1 x 1
#>     ..1
#>   <dbl>
#> 1     1
```

But I guess it should also be an error. 

Alternatively we could handle calls of the form `<rlang lambda>(<symbol from the mask>)` separately in `DataMask`, @lionel- ?

**Comment by krlmlr** [comment]
Can we translate using `.data`, e.g. to `toupper(.data$"..1")` ?

``` r
list("..1" = 42)$"..1"
#> [1] 42
```

<sup>Created on 2019-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by jennybc** [comment]
> Thanks, yeah I guess .name_repair = "universal" in read_xls would avoid names like ..1 which have special meaning. ping @jennybc

Yeah I was involved in finding this reprex, since it presented as a readxl problem.

I think part of the surprise is that the variable names even matter for `mutate_all()`. To a user, it feels like you're just doing something to all variables in the input and it's unclear how their names figure into it.

**Comment by romainfrancois** [comment]
@krlmlr I suppose we could yes: 

``` r
library(dplyr, warn.conflicts = FALSE)
mutate(tibble(`..1` = "1"), `..1` = toupper(.data$`..1`))
#> toupper(.data$..1)
#> # A tibble: 1 x 1
#>   ..1  
#>   <chr>
#> 1 1
```

**Comment by romainfrancois** [comment]
@jennybc I agree conceptually, however `_all` functions work by splicing generated expressions into the "real function", e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)
trace(dplyr:::mutate_impl, tracer = quote(print(dots)))
#> Tracing function "mutate_impl" in package "dplyr
#> (not-exported)"
#> [1] "mutate_impl"
mutate_all(tibble(x = 2, `..1` = "1"), toupper)
#> Tracing mutate_impl(.data, dots) on entry 
#> <list_of<quosure>>
#> 
#> $x
#> <quosure>
#> expr: ^toupper(x)
#> env:  global
#> 
#> $..1
#> <quosure>
#> expr: ^toupper(..1)
#> env:  global
#> 
#> toupper(x)
#> toupper(..1)
#> Error in toupper(..1): ..1 used in an incorrect context, no ... to look in
```

**Comment by jennybc** [comment]
> however _all functions work by splicing generated expressions into the "real function"

Ah, interesting. Not knowing anything about the implementation, I think I was implicitly assuming scoped verbs of the `_all` and `_if` flavours would not care about variable names.

**Comment by jennybc** [comment]
I guess this underscores that this family of verbs should really know about `.name_repair`. And the verbs should enact that before doing the real work.

**Comment by krlmlr** [comment]
I'd expect `mutate_all()` and friends to leave the names untouched.

**Comment by romainfrancois** [comment]
reopen on #4178

**Comment by romainfrancois** [comment]
Current state: 

``` r
library(dplyr, warn.conflicts = FALSE)
mutate_all(tibble(`..1` = "1", .name_repair = "minimal"), toupper)
#> Error in (function (x) : the ... list contains fewer than 1 element
```

<sup>Created on 2019-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by krlmlr** [comment]
I wonder if we should just look for these evil column names and throw an informative error.

**Comment by romainfrancois** [comment]
The way `mutate_all()` works, we currently get this, but `mutate() + across()` gives a more acceptable error. 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(`..1` = "1", .name_repair = "minimal")
mutate_all(df, toupper)
#> Error in (function (x) : the ... list contains fewer than 1 element

mutate(df, across(everything(), toupper))
#> Error: Names must not be of the form `...` or `..j`.
```

<sup>Created on 2019-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

I'll close this for now, as we might automatically benefit from the better error when we migrate `mutate_all()` on top of `mutate() + across()`
