### ISSUE TITLE
Develop flexible SQL backend

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#41]
Packages reviewed: RPostgreSQL, RMySQL, MonetDB.R, RODBC, RJDBC

Differences:
- RPostgreSQL: has `dbApply` which could be used to implement `do`, multiple open connections, prepared queries use [special syntax](http://www.postgresql.org/docs/9.3/static/sql-prepare.html), windowing, explain output is json, subqueries need to be named, ANALYZE called automatically (but not on temporary tables)
- MonetDB.R: looks like prepared statements might be supported through dbSendQuery, no semi_joins?
- RMySQL: also has `dbApply`, no prepared queries
- RODBC: non-DBI, manual transactions

Other things that I may need to make generic:
- variable name escaping
- translation of R variable types to db types (for creation)

Steps to make dplyr adapt to different sql variants:
- Make query a base class and add subclasses for other databases
- Turn tbl_sqlite object into a tbl_sql object - method would dispatch on src/con

Changes needed:
- Query needs to become base class
- Existing tbl_sqlite methods should become tbl_sql methods
- When implementing first non-sqlite sql adaptor, gradually change

Postgresql and MonetDB clearly the most important and should be tackled first. MonetDB might be simpler to start with since it implements a more limited subset of sql.

**Comment by urspine** [comment]
Hi Hadley, Can dplyr and rodbc work in tandem?
