### ISSUE TITLE
suggestions  group_by

### ISSUE THREAD

**Issue by maicel1978** [tidyverse/dplyr#4105]
Hello,
I would like to make a proposition incorporating a new argument to the function group_by.
It is an argument as group_by(all=T) that, once groups are built saves a group with the total sum. I believe that it would make easier working with tables requiring totals, given that the vast majority of reports demand total values when we are giving sums measures by group. I think that that would be worth when publishing reports but also an analytical view of every group and the total at the same time.    
mtcars %>% 
    group_by (cyl) %>% 
    summarise (n=n()) %>%
   tibble::add_row(cyl="all",n=sum(.$n))
    
something similar was describe, some time ago, in
https://github.com/tidyverse/dplyr/issues/1253 
Thank you very much,

**Comment by maicel1978** [comment]
In my opinion this would bring advantages such as:
- display of group and global summaries simultaneously
- ease to create tables and graphics for publications
- New functionalities in conjunction with verbs such as filter and mutate

**Comment by romainfrancois** [comment]
This is out of scope for dplyr
