### ISSUE TITLE
Weak/non-strict selection of columns

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [tidyverse/dplyr#4111]
I was surprised to see no straightforward way to select multiple columns and drop non-existing ones using names. Such behaviour can be achieved through `one_of`, but it requires a character vector.

``` r
library(dplyr)
mtcars %>% select(one_of(c("gear", "gear2"))) %>% head(2)
#> Warning: Unknown columns: `gear2`
#>               gear
#> Mazda RX4        4
#> Mazda RX4 Wag    4
```

I'd prefer to be able to select like this

``` r
library(dplyr)
mtcars %>% select(gear, gear2)
#> Error in .f(.x[[i]], ...): object 'gear2' not found
```

because this allows to use all other standard selection tools as well as to integrate such `select_*` in the custom functions. A crude example of how it might be achieved (abusing some of the `tidyselect` functions)

``` r
    library(dplyr)
    library(tidyselect)
    select_weak <- function(.data, ...) {
        args <- enquos(...)
        select(.data, vars_select(peek_vars(), !!!args, .strict = FALSE))
    }
    mtcars %>% select_weak(gear, gear2) %>% head(2)
#   mtcars %>% select_weak(starts_with("ge")) %>% head(2)
#   mtcars %>% select_weak(one_of(c("gear", "gear2"))) %>% head(2)
#>               gear
#> Mazda RX4        4
#> Mazda RX4 Wag    4
```

I believe `.strict` option can be useful in certain scenarios.

<sup>Created on 2019-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
@lionel- it looks like `select()` is actually defensive against passing `...` through. 

```r
select.data.frame <- function(.data, ...) {
  # Pass via splicing to avoid matching vars_select() arguments
  vars <- tidyselect::vars_select(sel_vars(.data), !!!quos(...))
  select_impl(.data, vars)
}
```

I guess this is about making to possible to have columns named `.include`, `.exclude` and `.strict`. 

Would it make sense to add a `.strict` argument to `select.data.frame()` ? 

If we do it with an extra function like `select_weak()` above then I'd say this would have to be incubated in another package first.

**Comment by lionel-** [comment]
I guess it makes sense to add that argument.

**Comment by romainfrancois** [comment]
I'll make a PR then, thanks.

**Comment by hadley** [comment]
I don't think the amount of work that this requires is worth the result, especially given that you can already achieve what you want by calling `vars_select()` directly, or by using `names()` + `setdiff()`.

**Comment by Ilia-Kosenkov** [comment]
Ok, I thought it might be a useful extension. Thanks for the feedback.
