### ISSUE TITLE
Scoped mutate/summarize not working with unnamed list of functions

### ISSUE THREAD

**Issue by skaltman** [tidyverse/dplyr#4119]
If you supply the scoped variants of `summarize()` and `mutate()` with an unnamed list of functions, they don't create one variable per function. They also name the new variables with the suffix `_<fn>` instead of the function name.

This doesn't happen if you supply the functions as anonymous functions or supply variable names explicitly.

``` r
library(dplyr)

# Only creates two variables, using median()
# Ends names in _<fn>
storms %>% 
  summarize_at(vars(wind, pressure), list(mean, median)) 
#> # A tibble: 1 x 2
#>   `wind_<fn>` `pressure_<fn>`
#>         <dbl>           <dbl>
#> 1          45             999

# works
storms %>% 
  summarize_at(vars(wind, pressure), list(~ mean(.), ~ median(.))) 
#> # A tibble: 1 x 4
#>   wind_mean pressure_mean wind_median pressure_median
#>       <dbl>         <dbl>       <dbl>           <dbl>
#> 1      53.5          992.          45             999

# works
storms %>% 
  summarize_at(vars(wind, pressure), list(mean = mean, median = median)) 
#> # A tibble: 1 x 4
#>   wind_mean pressure_mean wind_median pressure_median
#>       <dbl>         <dbl>       <dbl>           <dbl>
#> 1      53.5          992.          45             999
```

<sup>Created on 2019-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
We should probably autoname the list with `fn1`, `fn2` or similar

**Comment by romainfrancois** [comment]
Is this something to delegate to name repair somehow ?

**Comment by hadley** [comment]
I don't _think_ so, because this is a list of functions, not a data frame.

**Comment by romainfrancois** [comment]
Can `rlang::exprs_auto_name` do it @lionel- ? This is where it happens: 

https://github.com/tidyverse/dplyr/blob/master/R/funs.R#L65

``` r
library(rlang)
#> Warning: package 'rlang' was built under R version 3.5.2

qs <- list(
  quo((!!mean)), 
  quo((!!median))
)
exprs_auto_name(qs)
#> $`<fn>`
#> <quosure>
#> expr: ^<function(x, ...) UseMethod("mean")>
#> env:  global
#> 
#> $`<fn>`
#> <quosure>
#> expr: ^<function(x, na.rm = FALSE, ...) UseMethod("median")>
#> env:  global
```

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
I think in this case you need to name explicitly: `list(mean = mean, median = median)`.

Or delegate auto-naming by creating the list with tibble: `tibble::lst(mean, median)`

**Comment by romainfrancois** [comment]
It used to be possible and taken care of (with the `funs()` interface), so even though we might prefer to have the user be explicit, I guess we have to do it in stages: 

 - have something sort of sensible now
 - in version +1, issue a warning about it, or a message about it
 - eventually make it an error

`tibble::lst()` did not help:  

``` r
library(rlang)

qs <- list(
  quo((!!mean)), 
  quo((!!median))
)
lst(!!!qs)
#> $`<fn>`
#> function (x, ...) 
#> UseMethod("mean")
#> <bytecode: 0x7f9d9577f490>
#> <environment: namespace:base>
#> 
#> $`<fn>`
#> function (x, na.rm = FALSE, ...) 
#> UseMethod("median")
#> <bytecode: 0x7f9d944857b8>
#> <environment: namespace:stats>
```

**Comment by romainfrancois** [comment]
~~`tibble::lst()` did not help:~~ I understand what you mean now. This is still asking the user to change their code.

**Comment by romainfrancois** [comment]
We are, but at the moment we have nothing to replace `funs(mean, median)`: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tibble(x = 1:10, y = 1:10) %>% 
  summarise_all(funs(mean, median))
#> Warning: funs() is soft deprecated as of dplyr 0.8.0
#> please use list() instead
#> 
#> # Before:
#> funs(name = f(.)
#> 
#> # After: 
#> list(name = ~f(.))
#> This warning is displayed once per session.
#> # A tibble: 1 x 4
#>   x_mean y_mean x_median y_median
#>    <dbl>  <dbl>    <dbl>    <dbl>
#> 1    5.5    5.5      5.5      5.5
```

Maybe the deprecation message needs to be reworked ?

**Comment by lionel-** [comment]
I'm not sure we want the message to be longer. Maybe we could create some kind of page to link to?

**Comment by lionel-** [comment]
Or maybe add this note:

```
"See the life cycle section in `?funs`"
```

**Comment by romainfrancois** [comment]
Fair enough, maybe I can just close the `)` of the `Before`  thing 🤕.

**Comment by romainfrancois** [comment]
I still need a strategy for when the list is unnamed, I'm fine with making it a loud error, but the test suite is not ...

**Comment by lionel-** [comment]
Currently dplyr labellises literals with non-syntactic names. We could just keep the current auto-naming until rlang gets more options, and change the labelling within all of dplyr at once. I have opened an issue in https://github.com/r-lib/rlang/issues/721. 

cc @jennybc
