### ISSUE TITLE
joining by columns with different names passed by as arguments

### ISSUE THREAD

**Issue by damianooldoni** [tidyverse/dplyr#4120]
Here below a classic dplyr (left)join:
```r
df_1 <- tibble::tibble(col1_df1 = c("aaa","bbb"), 
                      col2_df1 = c(1,2))
df_2 <- tibble::tibble(col1_df2 = c("aaa", "bbb", "ccc"), 
                      col2_df2 = c(1,2, 4))
left_join(df_1, df_2, by = c("col1_df1" = "col1_df2"))
```

I am wondering how to use a (left)join in a function where I pass the columns for joining as variables, something like this:

```r
dummy_function <- function(df1, df2, col_df1_join, col_df2_join) {
  df1 <- 
    df1 %>% 
    left_join(df2,
              by = c(col_df1_join, col_df2_join)
    )
  return(extension_name)
}
a <- "col1_df1"
b <- "col1_df2"
dummy_function(df_1, df_2, a , b)
```

Unfortunately I get this error:

```r
Error: `by` can't contain join column `col1_df2` which is missing from LHS
```
I can do it via base R function `merge()` by using `by.x` and `by.y` parameters. However, same kind of parameters (`by_x` and `by_y`) are in the inner and hidden function `left_join_impl()` so I cannot use them.

Any idea how to solve this? I tried with NSE but I always get stuck with the `by = c(... = ...)` structure.
Thanks a lot.

**Comment by hadley** [comment]
There's no need for NSE; you just need `setNames()`
