### ISSUE TITLE
Informative error message when "primary pipe input" is missing

### ISSUE THREAD

**Issue by rappster** [tidyverse/dplyr#4127]
Just a really minor thing I noticed (and possibly this is rather a `magrittr` issue?):

While refactoring a function, I accidentally dropped the initial `df %>%` part of a pipe that used `:=`.

But before I realized this, I was puzzled for a couple minutes by the error below as it didn't suggest the reason was the missing `df %>%` but not being able to find function `:=`.

Maybe one could come up with error messages along the lines of `primary pipe input 'x' missing`?

```r
library(magrittr)

df <- tibble::tibble(x = 1:3)
col <- rlang::sym("x")

df %>% 
  dplyr::mutate(!!col := !!col * 10)
#> # A tibble: 3 x 1
#>       x
#>   <dbl>
#> 1    10
#> 2    20
#> 3    30

# When accidentally dropping `df %>%`:
  dplyr::mutate(!!col := !!col * 10)
#> Error in `:=`(!!col, !!col * 10): could not find function ":="
```

**Comment by romainfrancois** [comment]
Unfortunately, I don't think there is much we can do here, as the error happens before S3 dispatch, i.e. the first argument has to be evaluated before the `mutate` generic knows which method to call.

**Comment by krlmlr** [comment]
We can do a `tryCatch()` in the `mutate()` generic:

```r
mutate <- function(.data, ...) {
  quo <- enquo(.data)

  tryCatch(
    force(.data),
    error = function(e) {
      abort(paste0("`.data` must be a data source. ", conditionMessage(e)))
    }
  )

  UseMethod("mutate")
}
```

This doesn't look very helpful right now, perhaps if we had a `tryCatch()` implementation with better call traces:

``` r
dplyr::mutate(!!col := !!col * 10)
#> Error: `.data` must be a data source. could not find function ":="
#> Backtrace:
#>     █
#>  1. └─dplyr::mutate(`:=`(!!col, !!col * 10))
#>  2.   └─base::tryCatch(...) /home/kirill/git/R/dplyr/R/manip.r:442:2
#>  3.     └─base:::tryCatchList(expr, classes, parentenv, handlers)
#>  4.       └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  5.         └─value[[3L]](cond)
```

<sup>Created on 2019-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
We'd have to do that for every generic then. Sounds painful.

**Comment by krlmlr** [comment]
We do this in `ggplot()`, and it really helps, especially for beginners. The `tryCatch()` could be extracted into a helper function, so we only need to remember to call that function (using the new whiskers syntax in rlang) at the beginning of each generic.
