### ISSUE TITLE
Granular `.drop` argument?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#4129]
My first expectation would have been that `.drop` only applies for specific variables, i.e. in the following `a` and `b` would still keep their groups:

```r
data %>% group_by(a, b, .drop = FALSE) %>% group_by(c, .drop = TRUE)
```

Since creating empty groups is expensive, a more granular drop attribute might be useful.

_Originally posted by @lionel- in https://github.com/tidyverse/dplyr/pull/4091_

**Comment by hadley** [comment]
I think we'll solve this by allowing the user to supply their own grouping data frame, which we're tracking in #4722
