### ISSUE TITLE
Confusing error message if type differs between units objects

### ISSUE THREAD

**Issue by kendonB** [tidyverse/dplyr#4138]
See below:
``` r
library(dplyr)
library(units)
#> udunits system database from C:/R/Library/3.5/units/share/udunits
if_else(TRUE, c(1) %>% set_units("m"), c(1L) %>% set_units("m"))
#> Error: `false` must be a `units` object, not a `units` object
```

<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
🤔 so this happens in `check_type()`: 

```r
check_type <- function(x, template, header) {
  if (identical(typeof(x), typeof(template))) {
    return()
  }

  glubort(header, "must be {friendly_type_of(template)}, not {friendly_type_of(x)}")
}
```

where it checks the underlying type but then errors based on a higher level class. It might be something `vctrs` could help with, perhaps with implementations of `vctrs::vec_ptype_abbr()` and/or `vctrs::vec_ptype_full()` for `units` objects.

**Comment by hadley** [comment]
This will be fixed through a complete overhaul of ifelse

**Comment by kendonB** [comment]
This is also a problem with `case_when`, fyi.

**Comment by hadley** [comment]
Yeah, it's a problem with a bunch of functions. We know about it and we have a plan to fix it.

**Comment by hadley** [comment]
Duplicate of #2432
