### ISSUE TITLE
Suggestion: %<>% in mutate()

### ISSUE THREAD

**Issue by Zanidean** [tidyverse/dplyr#4144]
I often use mutate() to transform a variable in place, often leading to code that looks like this:
 ``` r 
dataframe %>%
  mutate(
    Var1 = Var1 %>% str_to_upper(),
    Var2 = Var2 %>% fct_shift(4)
    )
```
A possible improvement might be to include the `%<>%` infix inside of dplyr. 
 ``` r 
dataframe %>%
  mutate(
    Var1 %<>% str_to_upper(),
    Var2 %<>% fct_shift(4)
    )
```

**Comment by moodymudskipper** [comment]
This has frustrated me as well

Maybe an additional function `mutate_self` which would be somewhat of a mix between `mutate` and `mutate_at`:

```
dataframe %>% mutate_self(Var1 = str_to_upper, Var2 = fct_shift)
```

**Comment by moodymudskipper** [comment]
Here is a raw implementation :

```
mutate_self <- function(...){
  args <- substitute(list(...))
  tbl  <- eval.parent(args[[2]])
  args <- eval.parent(args[-2])
  purrr::reduce2(names(args), args, mutate_at, .init = tbl)
}

iris %>% head(2) %>% mutate_self(
  Sepal.Length = ~.*100, 
  Sepal.Width = . %>% sqrt, 
  Species = toupper)

#   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
# 1          510    1.870829          1.4         0.2  SETOSA
# 2          490    1.732051          1.4         0.2  SETOSA
```

**Comment by hadley** [comment]
I don’t like `%<>%` because I believe assignment is sufficiently important that it should be clearly visible with standard syntax. For that reason mutate, will not gain modify “in place” support.
