### ISSUE TITLE
Documentation of name repair in scoped "mutating" verbs

### ISSUE THREAD

**Issue by echasnovski** [tidyverse/dplyr#4146]
In current version of dplyr (on commit e9902f1fa9f21bfee4ad6addf4acadf085ce6796) there is a name repair going on inside scoped "mutating" verbs. This seems to be intentional (because there is a separate commit 5cfde4a89b7c59440cc1ea927a3f668bb08c6170) but this change is not documented.

So I have a question and an issue:

- Is this change intentional? In previous version there is no aggressive name repair policy.
- If intentional, could this be documented somewhere? At least in 'NEWS.md', but in some roxygen-linkable help page would be better. Thanks.

Reprex:

``` r
suppressPackageStartupMessages(library(dplyr))

summarise_all(mtcars, list(`@@@fun` = ~ mean(.) > 1)) %>% names()
#>  [1] "mpg_...fun"  "cyl_...fun"  "disp_...fun" "hp_...fun"   "drat_...fun"
#>  [6] "wt_...fun"   "qsec_...fun" "vs_...fun"   "am_...fun"   "gear_...fun"
#> [11] "carb_...fun"
transmute_if(mtcars, ~ mean(.) < 10, list(`@@@fun` = ~ . + 1)) %>% names()
#> [1] "cyl_...fun"  "drat_...fun" "wt_...fun"   "vs_...fun"   "am_...fun"  
#> [6] "gear_...fun" "carb_...fun"
```

<sup>Created on 2019-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by echasnovski** [comment]
There is also a seemingly unnecessary remove of `..i` from the end of the manually supplied names:

``` r
suppressPackageStartupMessages(library(dplyr))

summarise_all(mtcars, list(`fun..1` = ~ mean(.) > 1)) %>% names()
#>  [1] "mpg_fun"  "cyl_fun"  "disp_fun" "hp_fun"   "drat_fun" "wt_fun"  
#>  [7] "qsec_fun" "vs_fun"   "am_fun"   "gear_fun" "carb_fun"
transmute_if(mtcars, ~ mean(.) < 10, list(`fun..1` = ~ . + 1)) %>% names()
#> [1] "cyl_fun"  "drat_fun" "wt_fun"   "vs_fun"   "am_fun"   "gear_fun"
#> [7] "carb_fun"
```

<sup>Created on 2019-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Is *this* intentional? Because I have functionality that depends on "save the input function name" behaviour and these changes would introduce some problems.

**Comment by romainfrancois** [comment]
The conversation is in the #4125 PR. I'll add some documentation.

**Comment by echasnovski** [comment]
Thanks. And how about dropping manually supplied `..1` in names? Is this intentional?

**Comment by romainfrancois** [comment]
@krlmlr will know better.

**Comment by krlmlr** [comment]
Maybe we should do the name repair only for the result after combining column and function names?

**Comment by echasnovski** [comment]
@krlmlr, I don't think it will help with `..1` situation. The problem seems to be that [`unique_names()`](https://github.com/tidyverse/dplyr/blob/e9902f1fa9f21bfee4ad6addf4acadf085ce6796/R/compat-name-repair.R#L24) strips position even if it is not needed to make names unique:

``` r
# There is no need to remove `..1`, as string is already "unique"
dplyr:::unique_names("mpg_fun..1")
#> New names:
#> * mpg_fun..1 -> mpg_fun
#> [1] "mpg_fun"

# This string is also syntactic
identical(make.names("mpg_fun..1"), "mpg_fun..1")
#> [1] TRUE
```

<sup>Created on 2019-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by echasnovski** [comment]
Should I open separate issue for `..1` behavior? As it seems to be an unintended change.

**Comment by krlmlr** [comment]
This is by design: Any `..#` suffix is assumed to be "ours", and we strip it prior to normalization. This helps avoiding weird corner cases.

I still think we should apply name repair only on the combination of column and function names.

**Comment by echasnovski** [comment]
Ok, thanks. It is really helpful to know, although it introduces some problems for me down the way.

**Comment by hadley** [comment]
We were forced into adding this behaviour to the scoped verbs a little earlier than otherwise optimal, but a future version of dplyr (probably 0.9.0) will use these principles robustly every where, as we roll out consistent naming behaviour across the tidyverse.
