### ISSUE TITLE
Is `.args` functionality of `funs()` completely dropped?

### ISSUE THREAD

**Issue by echasnovski** [tidyverse/dplyr#4150]
Function `funs()` seems to be soft-deprecated starting from dplyr 0.8.0. The suggested alternative is to use list of formulas. However, I didn't find any recommendation about how to recreate `.args` behaviour of `funs()`. So my question is, is this functionality completely dropped? If so, what is the suggested alternative for recreating this behaviour?

Reprex (using current GitHub version of dplyr, e9902f1fa9f21bfee4ad6addf4acadf085ce6796):
``` r
dplyr::funs(mean, sd, .args = list(na.rm = TRUE))
#> Warning: funs() is soft deprecated as of dplyr 0.8.0
#> please use list() instead
#> 
#> # Before:
#> funs(name = f(.)
#> 
#> # After: 
#> list(name = ~f(.))
#> This warning is displayed once per session.
#> <fun_calls>
#> $ mean: mean(., na.rm = TRUE)
#> $ sd  : sd(., na.rm = TRUE)
```

<sup>Created on 2019-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
it does not have to be formulas, it can be actual functions, e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

fns <- map(list(mean = mean, sd = sd), partial, na.rm = TRUE)
summarise_at(iris, vars(starts_with("Sepal")), fns)
#>   Sepal.Length_mean Sepal.Width_mean Sepal.Length_sd Sepal.Width_sd
#> 1          5.843333         3.057333       0.8280661      0.4358663
```

<sup>Created on 2019-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by echasnovski** [comment]
Oh, yes, that is true. With this in mind, I guess my question can be expanded to "Do you now suggest users to manually set common arguments for functions?" (with use of `purrr::partial()` or any other way)?

**Comment by romainfrancois** [comment]
Common arguments may also directly go in the `...`: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

summarise_at(iris, vars(starts_with("Sepal")), list(mean = mean, sd = sd), na.rm = TRUE)
#>   Sepal.Length_mean Sepal.Width_mean Sepal.Length_sd Sepal.Width_sd
#> 1          5.843333         3.057333       0.8280661      0.4358663
```

This is documented in `?summarise_at` do you have suggestions on how to improve it ?

**Comment by echasnovski** [comment]
Missed this, my bad. Maybe this functionality is worth adding to `.args` description in `funs()`? Because this was the place I went to see what are recommendations to replace it.

Maybe [these lines](https://github.com/tidyverse/dplyr/blob/e9902f1fa9f21bfee4ad6addf4acadf085ce6796/R/funs.R#L26-L27) can be something like "A named list of additional arguments to be added to all function calls. As `funs()` is being deprecated, use other methods to supply arguments: `...` argument in [scoped verbs][summarise_at()] or make own functions with [purrr::partial()]."

**Comment by krlmlr** [comment]
Would you like to submit a pull request?
