### ISSUE TITLE
Search is broken on the dplyr pkgdown site

### ISSUE THREAD

**Issue by jayhesselberth** [tidyverse/dplyr#4151]
Should work after https://github.com/tidyverse/tidytemplate/pull/39 is merged and docs are re-built.

**Comment by jayhesselberth** [comment]
Search now works with a recent travis build.

BUT the docsearch index build from [this config](https://github.com/algolia/docsearch-configs/blob/b424985df4644c4738c2f34f6fe73798864d581c/configs/tidyverse.json) isn't quite right and the results aren't as rich as they're supposed to be. This is likely caused by differences in tidytemplate (relative to the pkgdown templates).

**Comment by batpigandme** [comment]
Copy that, I'm in the air with incredibly slow internet, but I'll look into it tomorrow! ✔️

**Comment by batpigandme** [comment]
@jayhesselberth, is this a fix that should be in the config you linked to, or am I missing something in the internal docsearch setup in tidytemplate around the lines below? https://github.com/tidyverse/tidytemplate/blob/6d7af6575d6de117752231acb55904abae2b396a/inst/pkgdown/templates/head.html#L29-L33

**Comment by jayhesselberth** [comment]
Someone (@hadley?) will need to ask that the tidyverse docsearch config be updated.

Here's the current config:

https://github.com/algolia/docsearch-configs/blob/b424985df4644c4738c2f34f6fe73798864d581c/configs/tidyverse.json

but it needs to be configured like this:

https://github.com/algolia/docsearch-configs/blob/b424985df4644c4738c2f34f6fe73798864d581c/configs/valr.json

In particular, the `lvl0` selector is missing in the dplyr config, and the `lvl2` selector does not have `.contents dt`, which contain param descriptions.

**Comment by batpigandme** [comment]
Ah! OK, thanks for the clarification.

**Comment by jayhesselberth** [comment]
The dplyr sitemap in the index also needs to be updated—the correct one is https://dplyr.tidyverse.org/sitemap.xml.

**Comment by jayhesselberth** [comment]
This is the updated config:

``` json
{
  "index_name": "tidyverse",
  "start_urls": [
    "https://dplyr.tidyverse.org"
  ],
  "stop_urls": [
    "http://dplyr.tidyverse.org/index.html"
  ],
  "selectors": {
    "lvl0": ".contents h1",
    "lvl1": ".contents h2",
    "lvl2": ".contents h3, .contents th, .contents dt",
    "lvl3": ".contents h4",
    "lvl4": ".contents h5",
    "text": ".contents p, .contents li, .usage, .template-article .contents .pre"
  },
  "selectors_exclude": [
    ".dont-index"
  ],
  "sitemap_urls": [
    "https://dplyr.tidyverse.org/sitemap.xml"
  ]
}

```

**Comment by batpigandme** [comment]
Thanks, Jay.
@hadley, I created a tidyverse fork of algolia's configs to submit as a PR. Would you mind taking a look before I do so? (Once it's merged, I'll delete the fork, I just thought it'd make more sense coming from tidyverse to algolia).
https://github.com/tidyverse/docsearch-configs/commit/e7585a7be0f136f3a74a519ed33886e7afa99b4b

**Comment by batpigandme** [comment]
OK, see: https://github.com/algolia/docsearch-configs/pull/738

**Comment by batpigandme** [comment]
Still broken for items that are only in articles: https://dplyr.tidyverse.org/undefined?q=joins#filtering-joins

**Comment by batpigandme** [comment]
@jayhesselberth, sorry to bug you, can you tell where I've gone wrong here? The algolia docsearch-config is updated 😳

**Comment by jayhesselberth** [comment]
Hmm I'm not sure. Perhaps @s-pace could chime in—why do pages end up "undefined" in a docsearch index? Is this an indication that the config is broken? Or that there are problems with the pages?

**Comment by s-pace** [comment]
Fix by https://github.com/algolia/docsearch-configs/commit/e3e6a22562773f6e95ee6d3312c93e71bcb69685

(The "undefined" param is `url_without_anchor `)

**Comment by batpigandme** [comment]
🙏  Thank you so much, @s-pace!
