### ISSUE TITLE
group_by and group_by_ does not drop empty groups by default

### ISSUE THREAD

**Issue by PascalKieslich** [tidyverse/dplyr#4152]
In the NEWS file for the upcoming dplyr release 0.8.0 it says "`group_by()` gains the `.drop` argument.  When set to `FALSE` the groups are generated based on factor levels, hence some groups may be empty."

It also says that the "default behaviour drops the empty groups as in the previous versions".

However, in the most recent version of dplyr from GitHub, `group_by` (and `group_by_`) does **not** drop empty groups by default (I think this is also evident from the underlying R code at https://github.com/tidyverse/dplyr/blob/master/R/group-by.r#L92)

```r
tibble(
  x = 1:2, 
  f = factor(c("a", "b"), levels = c("a", "b", "c"))
) %>% 
  group_by(f)
```

I think it would be preferable if the **default behavior** was to **drop empty groups** by default (as stated in the NEWS). If not, this would e.g. also cause problems for other packages that use `group_by` and `group_by_` internally (like the `mousetrap` package that I maintain).

(Note: I hope that I checked the most recent version of dplyr, i.e., the one for the upcoming 0.8.0 release - if not, I am sorry and it would be great if you could direct me to the most recent version)

**Comment by yutannihilation** [comment]
It does drop. Did you installed dplyr from GitHub before #4091 was merged?

``` r
library(dplyr, warn.conflicts = FALSE)

packageDescription("dplyr")$Version
#> [1] "0.8.0"
packageDescription("dplyr")$GithubSHA1
#> [1] "e9902f1fa9f21bfee4ad6addf4acadf085ce6796"

tibble(
  x = 1:2, 
  f = factor(c("a", "b"), levels = c("a", "b", "c"))
) %>% 
  group_by(f)
#> # A tibble: 2 x 2
#> # Groups:   f [2]
#>       x f    
#>   <int> <fct>
#> 1     1 a    
#> 2     2 b
```

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

For the R code, you should have looked at here:

https://github.com/tidyverse/dplyr/blob/160b349b870667e408cfcdc0a07d26653a7a4061/R/dataframe.R#L32

**Comment by PascalKieslich** [comment]
Thanks for pointing this out. I think you might be right in that I installed the development version before #4091 was merged. I tried to install the most recent version via `install_github` but maybe this failed. I tried it again by cloning dplyr and then building it myself and now I also don't have the problem. Thanks!
