### ISSUE TITLE
I need to calculate Q1, Median, Average and Q75 for my data

### ISSUE THREAD

**Issue by salmansyed0709** [tidyverse/dplyr#4160]
Hi guys
I have total 7 columns, first column is alphanumeric and others 6 are numeric i.e

ID : 122.1253M 125.3699E 125.3699E 125.3699M 125.3699S 125.3699P ............................
A : 123456 23654 3265 12364 5896 2365
B : .............................
C :.....................
D :............................
E  :........................
F :.................................

I want my solution group by ID and the descriptive statistics( Count Q1, Median, Average, Q4 for each of the numerical column  and look like

ID 22.1253M 125.3699E 125.3699E 125.3699M 125.3699S 125.3699P
Count_A : 3 5 1 6 9 10
Q1_A : 56.3 12.3 52.1 3.3 65.3 12.3
Median_A : 65.3 58.2 14.3 36.0 12.5 59.0
Average_A : 12.5 15.3 48.6 49.3 15.6 36.1
Q4_A : 26.8 39.1 19.0 75.2 36.4 39.

Count_B :..............
Q1_B :................
Median_B :............
Average_B :.................
Q4_B :................ 

Same for C , D, E, and F column, as the ID is same for all the variable I wanted them group the ID.

 data %>%
  group_by(ID) %>% 
  summarise(Q1_A = quantile(0.25), 
            Median_A = median(A),
            Average_A = mean(A), 
            Q4_A= quantile() %>% 
  
but this code is not working and throwing the given below error.

Error in summarise_impl(.data, dots) : 
  Column `Q1_A` must be length 1 (a summary value), not 5

Please help !

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by IndigoJay** [comment]
Quantile function needs both the variable (A), and a defined single probability. 

```
data %>%
  group_by(ID) %>%
  summarise(Q25_A = quantile(A,probs=0.25),
            Median_A = median(A),
            Average_A = mean(A),
            Q75_A= quantile(A, probs=0.75))
```
