### ISSUE TITLE
Broadly consider grouping pain

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#4166]
* Speed of grouped filters causes pain

* Can we make grouping more obvious when printing? RStudio doesn't print it. Do we need to make it more obvious on the console? (i.e. colour the grouping variables differently)

* Can we probably a helper for grouping and ungrouping?

* Can we make mutating a grouped variable less painful? Just regroup? 

* Can we make selecting off a grouped variable less painful? Return ungrouped variable. Maybe need heuristic that we don't drop by default, but can explicitly drop (e.g. with `-group_var`)

**Comment by krlmlr** [comment]
Perhaps a forgetful version of `group_by()` would get us halfway there? Could be implemented by returning a subclass of `"grouped_df"` that ungroups after the next operation.

**Comment by hadley** [comment]
* IDE issue at https://github.com/rstudio/rstudio/issues/5970
* Syntax for temporary grouping at https://github.com/tidyverse/dplyr/issues/4711
* Modified grouping variables in `mutate()` at https://github.com/tidyverse/dplyr/issues/4709
* Consensus is to leave selection of group vars as is.
