### ISSUE TITLE
case_when should return an error with zero length RHS values

### ISSUE THREAD

**Issue by BenjaminLouis** [tidyverse/dplyr#4170]
With this three examples of `case_when` utitlisation, I exepected to see examples 1 and 3 behavior but not the second one 

```r
library(dplyr, warn.conflicts = FALSE)
library(stringr)

xx <- c("a", "b")
zz <- c("a", "b", "Autre")
# Example 1
case_when(
  length(setdiff(xx, zz)) == 0 ~ NA_character_,
  length(setdiff(xx, zz)) != 0 ~ str_c(xx, collapse = ";")
)
#> [1] NA

# Example 2
case_when(
  length(setdiff(xx, zz)) == 0 ~ NA_character_,
  length(setdiff(xx, zz)) != 0 ~ str_c(setdiff(xx, zz), collapse = ";")
)
#> character(0)

# Example 3
case_when(
  length(setdiff(xx, zz)) == 0 ~ NA_character_,
  length(setdiff(xx, zz)) != 0 ~ paste(setdiff(xx, zz), collapse = ";")
)
#> [1] NA
```
I think the problem is related to issue #3246 since `str_c(character(0), collpase = ";")` returns `character(0)` when  `paste(character(0), collpase = ";")` return `""`. Maybe it should be useful for users of `case_when` that the function returns an error when RHS values have zero length.

**Comment by krlmlr** [comment]
The current behavior of `case_when()` seems consistent with the tidyverse recycling rules: length 1 can be recycled, everything else (including length 0) remains unchanged.

Can you please simplify the reprex to use constants instead of complicated expressions?

**Comment by cderv** [comment]
Here is a minimal reprex of what I believe is the issue
``` r
library(dplyr, warn.conflicts = FALSE)
packageVersion("dplyr")
#> [1] '0.8.0.9000'
xx <- c("a")
dplyr::case_when(
  xx  == "a" ~ "A",
  xx  == "b" ~ character(0)
)
#> character(0)
```

<sup>Created on 2019-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Should it be here an error or `"A"` ? 
It shouldn't returns `character(0)` I think.

**Comment by krlmlr** [comment]
Thanks, Christophe. I still think this is consistent with the recycling rules, but I agree it's confusing. We accept vectors on each LHS and RHS, and will recycle length-1 vectors to a common length, if possible. In your example, 0 is the only length different from 1, and this is what is used for the result:

``` r
library(dplyr, warn.conflicts = FALSE)

my_recode <- function(xx, yy) {
  dplyr::case_when(
    xx == "a" ~ "A",
    xx == "b" ~ yy
  )
}

my_recode("a", "B")
#> [1] "A"
my_recode("a", LETTERS)
#>  [1] "A" "A" "A" "A" "A" "A" "A" "A" "A" "A" "A" "A" "A" "A" "A" "A" "A"
#> [18] "A" "A" "A" "A" "A" "A" "A" "A" "A"
my_recode("a", character(0))
#> character(0)
my_recode(letters, character(0))
#> Error: `xx == "b" ~ yy` must be length 26 or one, not 0
#> Backtrace:
#>     █
#>  1. └─global::my_recode(letters, character(0))
#>  2.   └─dplyr::case_when(xx == "a" ~ "A", xx == "b" ~ yy)
#>  3.     └─dplyr:::validate_case_when_length(query, value, fs) /home/kirill/git/R/dplyr/R/case_when.R:160:2
#>  4.       └─dplyr:::bad_calls(...) /home/kirill/git/R/dplyr/R/case_when.R:230:2
#>  5.         └─dplyr:::glubort(fmt_calls(calls), ..., .envir = .envir) /home/kirill/git/R/dplyr/R/error.R:29:2
```

<sup>Created on 2019-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by cderv** [comment]
Ok it is clearer. I believe this is the part of the documentation that explains it: 
> The case of n == 0 is treated as a variant of n != 1
Considering the tidyverse recycling rule, `case_when` behavior is ok.

But yes, it is a bit confusing to get `character(0)` as the result because we expect something, not nothing as first condition is met. 

Maybe some improvement of documentation is needed ? 
Some examples and your explanation
> the tidyverse recycling rules: length 1 can be recycled, everything else (including length 0) remains unchanged.

**Comment by hadley** [comment]
We'll handle this centrally for the tidyverse: https://github.com/tidyverse/principles/issues/13
