### ISSUE TITLE
More flexible `new_grouped_df()`

### ISSUE THREAD

**Issue by earowang** [tidyverse/dplyr#4172]
Current `new_grouped_df()` strips off the newly defined data class `tbl_xyz`. A typical subclassing example would be defining a new class built on top of `tbl_df` and then the grouped version on top of `grouped_df`. How do you think `new_grouped_df()` keeps the original data classes and then add new grouped class? So it returns  `[1] "grouped_xyz" "grouped_df"  "tbl_xyz" "tbl_df"      "tbl"         "data.frame"`?

``` r
library(dplyr, warn.conflicts = FALSE)
class(iris) <- c("tbl_xyz", "tbl_df", "tbl", "data.frame")
grped_iris <- group_by(iris, Species)
my_grped_iris <- new_grouped_df(iris, groups = group_data(grped_iris), 
  class = "grouped_xyz")
class(my_grped_iris)
#> [1] "grouped_xyz" "grouped_df"  "tbl_df"      "tbl"         "data.frame"
```
I could do a PR, if you think this looks fine.

**Comment by hadley** [comment]
I'm reasonably certain that's not correct, or at least it request a lot more thought because this is no longer a simple subclassing situation.

**Comment by romainfrancois** [comment]
I'm with @Hadley here, I don't think you can just squeeze in a class between `tbl_df` and `grouped_df`. Closing this now.
