### ISSUE TITLE
read_csv omits rare numerics if most are integer

### ISSUE THREAD

**Issue by oscci** [tidyverse/dplyr#4190]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

I tried using read_csv to read a giant .csv file.
(I have downloaded it, but it is available here:
"https://ofslivefs.blob.core.windows.net/files/TEF%20data%20updated/Metrics/TEF_YearFour_AllMetrics.csv"
There is one variable called DENOMINATOR which is usually integer, but occasionally has a decimal. I found that read_csv had assigned it to be integer, and this meant that any values with a decimal were just deleted. 
It imports OK with read.csv.

```r
# insert reprex here
```

**Comment by romainfrancois** [comment]
This is more suited for https://community.rstudio.com/ but even then I'd encourage you to make a reprex as explained above. 

Ultimately, if this really is a `read_csv()` problem, it should be in the [readr]() repository instead. https://github.com/tidyverse/readr
