### ISSUE TITLE
`group_by()` 's `.drop` default argument is considered as `TRUE` when not explicit

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#4192]
The release blog post says : 

> The internal grouping algorithm has been redesigned to make it possible to better respect factor levels and empty groups. To limit the disruption, we have not made this the default behaviour. To keep empty groups, you have to set group_by()’s .drop argument to FALSE.

but the default argument actually is `FALSE`, except that it behaves as if it's `TRUE` when missing. 

``` r

library(dplyr, warn.conflicts = F,quietly = T)
#> Warning: le package 'dplyr' a été compilé avec la version R 3.5.2
formals(group_by)
#> $.data
#> 
#> 
#> $...
#> 
#> 
#> $add
#> [1] FALSE
#> 
#> $.drop
#> [1] FALSE

species_count <- function(...) {
  iris %>% 
    filter(...) %>% 
    group_by(Species, .drop = FALSE) %>% 
    summarise(n = n()) %>% 
    tidyr::spread(Species, n)
}

species_count(Petal.Length > 3)
#> # A tibble: 1 x 3
#>   setosa versicolor virginica
#>    <int>      <int>     <int>
#> 1      0         49        50

species_count <- function(...) {
  iris %>% 
    filter(...) %>% 
    group_by(Species) %>% 
    summarise(n = n()) %>% 
    tidyr::spread(Species, n)
}

species_count(Petal.Length > 3)
#> # A tibble: 1 x 2
#>   versicolor virginica
#>        <int>     <int>
#> 1         49        50
```

Created on 2019-02-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
You are looking at the wrong `group_by()`. The default argument of the method for data.frame is `group_drops(.data)`, and `group_drops()` returns `TRUE` for bare data.frames.

``` r
formals(dplyr:::group_by.data.frame)
#> $.data
#> 
#> 
#> $...
#> 
#> 
#> $add
#> [1] FALSE
#> 
#> $.drop
#> group_drops(.data)

dplyr:::group_drops(iris)
```

<sup>Created on 2019-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by moodymudskipper** [comment]
I see, thanks, I had never noticed that a method could override the generic's default, i thought they were passed to it.

``` r
test <- function(x, lgl = TRUE) UseMethod("test")
test.data.frame <- function(x, lgl = FALSE) lgl
test(iris)
#> [1] FALSE
```

I believe this behavior is far from intuitive however. Why not set it to `TRUE` by default in the generic ? Or not set it at all and handle it all in methods ?

**Comment by yutannihilation** [comment]
I don't think the behaviour is counter-intuitive, but I agree the doc is. That `.drop = FALSE` is not actually used by any functions, so it seems safe to change it to `TRUE`.

**Comment by romainfrancois** [comment]
Thanks. I'll change the default to TRUE, but yeah this is only the perceived default

**Comment by earowang** [comment]
Is it possible to export `group_drops()` so that dependent packages can also use it as its default argument?

**Comment by romainfrancois** [comment]
I'm not sure it's the good name at the moment. We'll consider it.

**Comment by romainfrancois** [comment]
@earowang can you open another issue about exporting `group_drops()` so that we can brainstorm a good name for it there ?
