### ISSUE TITLE
`group_by` with `.drop = FALSE` still drops groups if data is sliced or filtered on grouping columns

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#4193]
There might be a reason for this but it's not clear for me from the doc which just says : 

> When .drop = TRUE, empty groups are dropped.

``` r

library(dplyr, warn.conflicts = F,quietly = T)
#> Warning: le package 'dplyr' a été compilé avec la version R 3.5.2
mtcars2 <- mtcars %>% 
  select(mpg, cyl) %>% 
  group_by(cyl,.drop = FALSE) %>%
  arrange(mpg)

group_keys(mtcars2)
#> # A tibble: 3 x 1
#>     cyl
#>   <dbl>
#> 1     4
#> 2     6
#> 3     8

mtcars2 %>% 
  slice(8) %>%
  group_keys()
#> # A tibble: 2 x 1
#>     cyl
#>   <dbl>
#> 1     4
#> 2     8

mtcars2 %>%
  filter(cyl !=6) %>%
  group_keys()
#> # A tibble: 2 x 1
#>     cyl
#>   <dbl>
#> 1     4
#> 2     8
```

Created on 2019-02-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
You need `.preserve = TRUE`, which was not mentioned in the latest blog post.

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars2 <- mtcars %>% 
  select(mpg, cyl) %>% 
  group_by(cyl,.drop = FALSE) %>%
  arrange(mpg)

mtcars2 %>% 
  slice(8, .preserve = TRUE) %>%
  group_keys()
#> # A tibble: 3 x 1
#>     cyl
#>   <dbl>
#> 1     4
#> 2     6
#> 3     8
```

<sup>Created on 2019-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Could the default of `.preserve` also be `group_drops(.data)`? Sorry, I think there was some discussion, but I can't find it...

**Comment by romainfrancois** [comment]
@yutannihilation I like this, chances are if you `.drop = FALSE` you also want `.preserve = TRUE` down the line, but that kind of makes it magical

**Comment by yutannihilation** [comment]
Yes, I expect it's the most likely case. But, as @earowang suggested in #4192, maybe you need to export it (with some nice name) first, otherwise the dependent packages cannot behave consistently with that magic...?

**Comment by moodymudskipper** [comment]
Maybe a verb `preserve(data, preserve=TRUE)` could be used to return a tibble that always preserves its factors, by adding an attribute or a class to the input ? It could be referenced in the definitions of `.drop` and `.preserve` arguments and contain more explicit info on factor preservation.

I think that most of the time you want to either preserve the factors or not in your task, so you might as well disclaim it at the start of your pipe chain and not worry about it anymore.

**Comment by hadley** [comment]
If you want to preserve the levels, why are you storing them in a factor? I don't see any factors in the example code here.

**Comment by romainfrancois** [comment]
I've tried to have `.preserve = group_by_drop_default(.data)` as the default in `filter()` but that breaks a lot of tests, so is probably not a good idea to have `.preserve` set automatically. 

It's easy enough to define your own version that either always preserve or use that default: 

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars2 <- mtcars %>% 
  select(mpg, cyl) %>% 
  group_by(cyl,.drop = FALSE) %>%
  arrange(mpg)

group_keys(mtcars2)
#> # A tibble: 3 x 1
#>     cyl
#>   <dbl>
#> 1     4
#> 2     6
#> 3     8

slice2 <- function(.data, ..., .preserve = group_by_drop_default(.data)) {
  slice(.data, ..., .preserve = .preserve)
}
filter2 <- function(.data, ..., .preserve = group_by_drop_default(.data)) {
  filter(.data, ..., .preserve = .preserve)  
}

mtcars2 %>% 
  slice2(8) %>%
  group_keys()
#> # A tibble: 3 x 1
#>     cyl
#>   <dbl>
#> 1     4
#> 2     6
#> 3     8

mtcars2 %>%
  filter2(cyl !=6) %>%
  group_keys()
#> # A tibble: 3 x 1
#>     cyl
#>   <dbl>
#> 1     4
#> 2     6
#> 3     8
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
