### ISSUE TITLE
Should we interpolate tilde functions before inlining?

### ISSUE THREAD

**Issue by kperkins** [tidyverse/dplyr#4199]
```r
# I am getting the following error when using quasiquotation and mutate_at (also happens with mutate_if):
# Error in is_quosure(e2) : argument "e2" is missing, with no default
# I have upgraded all my packages and R to the latest version (MacOS R 3.5.2) and tidyverse (v1.2.1)
# and I have no other major packages installed (see the (.packages()) list below

# > (.packages())
# [1] "forcats"   "stringr"   "dplyr"     "purrr"     "readr"     "tidyr"     "tibble"    "ggplot2"   "tidyverse" "stats"    
# [11] "graphics"  "grDevices" "utils"     "datasets"  "methods"   "base"   

library(tidyverse)
df <- tibble(a = 1:10, b = runif(1:10), c = letters[1:10])
varname <- "a"
symname <- rlang::sym(varname)
quoname <- enquo(symname)

# This simpler version works
df1 <- df %>% 
  dplyr::mutate(b = mean(!!quoname))

# This more advanced version does not, gives this error:
# Error in is_quosure(e2) : argument "e2" is missing, with no default
df2 <- df %>% 
  dplyr::mutate_at(vars(matches("b")), list(~mean(!!quoname)))

```

**Comment by kperkins** [comment]
library(tidyverse)
df <- tibble(a = 1:10, b = runif(1:10))
varname <- names(df)[1]
symname <- rlang::sym(varname)
quoname <- enquo(symname)
df2 <- df %>% 
  dplyr::mutate_at(vars(matches("b")), list(~mean(!!quoname)))
#> Error in is_quosure(e2): argument "e2" is missing, with no default

**Comment by kperkins** [comment]
# slightly simpler version
library(tidyverse)
df <- tibble(a = 1:10, b = runif(1:10))
varname <- 'a'
symname <- rlang::sym(varname)
quoname <- enquo(symname)
df %>% dplyr::mutate_at("b", list(~mean(!!quoname)))
#> Error in is_quosure(e2): argument "e2" is missing, with no default

**Comment by romainfrancois** [comment]
I'm not sure I understand what this would even mean, when you use `mutate_at()` you are supposed to use `.` in the lambdas to be replaced by each selected variable in turn, e.g. 

``` r
library(tidyverse)

df <- tibble(a = 1:10, b = runif(1:10))
df %>% 
  dplyr::mutate_at("b", list(~mean(.)))
#> # A tibble: 10 x 2
#>        a     b
#>    <int> <dbl>
#>  1     1 0.531
#>  2     2 0.531
#>  3     3 0.531
#>  4     4 0.531
#>  5     5 0.531
#>  6     6 0.531
#>  7     7 0.531
#>  8     8 0.531
#>  9     9 0.531
#> 10    10 0.531
```

If you want to do `b = mean(a)` I don't understand why you'd use `mutate_at()`. Closing this now, but maybe @lionel- has more.

**Comment by lionel-** [comment]
With dev rlang, this error is now:

```r
Error: Quosures can only be unquoted within a quasiquotation context.

  # Bad:
  list(!!myquosure)

  # Good:
  dplyr::mutate(data, !!myquosure)
```

When you use the scoped variants, the only quoting context is inside `vars()`. But you can also supply character vectors of names or numeric vectors of positions instead of vars. In general, the scoped variants do not use tidy eval.

**Comment by yutannihilation** [comment]
I guess this issue is asking about how to refer to the other column than the one supplied as a function argument. But, I think this cannot be done with `~` lambda notation (right?).

``` r
library(tidyverse)
df <- tibble(scale1 = 1:3, scale2 = 11:13, value = runif(3))
df %>% dplyr::mutate_at("value", list(~ . / .data$scale1))
#> # A tibble: 3 x 3
#>   scale1 scale2    value
#>    <int>  <int>    <dbl>
#> 1      1     11 0.818   
#> 2      2     12 0.000974
#> 3      3     13 0.0536

# cannot work
col <- "scale2"
df %>% dplyr::mutate_at("value", list(~ . / !!sym(col)))
#> Error in !sym(col): invalid argument type
df %>% dplyr::mutate_at("value", list(~ . / .data[[!!col]]))
#> Error in !col: invalid argument type
```

<sup>Created on 2019-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
You'd have to do your own quoting/unquoting for this to work, e.g. 

``` r
library(tidyverse)
#> Warning: package 'tibble' was built under R version 3.5.2
library(rlang)
#> Warning: package 'rlang' was built under R version 3.5.2
#> 
#> Attaching package: 'rlang'
#> The following objects are masked from 'package:purrr':
#> 
#>     %@%, as_function, flatten, flatten_chr, flatten_dbl,
#>     flatten_int, flatten_lgl, flatten_raw, invoke, list_along,
#>     modify, prepend, splice

df <- tibble(scale1 = 1:3, scale2 = 11:13, value = runif(3))

col <- "scale2"
df %>% 
  mutate_at("value", list(~ eval_bare(expr(. / !!sym(col)))))
#> # A tibble: 3 x 3
#>   scale1 scale2   value
#>    <int>  <int>   <dbl>
#> 1      1     11 0.00155
#> 2      2     12 0.0763 
#> 3      3     13 0.00234
```

<sup>Created on 2019-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

This is sort of related to https://github.com/r-lib/rlang/pull/591

**Comment by lionel-** [comment]
@yutannihilation I'm not sure that's what @kperkins meant, but that's a good point. It's a pattern I had never really considered.

I would do it this way (note the absence of `!!` inside `.data[[col]]`):

```r
df %>% dplyr::mutate_at("value", list(~ . / .data[[col]]))
```

I'm considering introducing `enstring(arg)` as a shortcut for `as_string(ensym(arg))` for this sort of things.

**Comment by yutannihilation** [comment]
@romainfrancois @lionel- I got it, thanks!

**Comment by lionel-** [comment]
@romainfrancois Since we already treat rlang lambdas differently, I now wonder if it would make sense to interpolate them at inlining time. That would be a departure from normal unquoting semantics, which I'm wary to introduce since it's tricky to fully understand timings of evaluation as it is. But maybe the door opens the wrong way here and we can do better?

cc @hadley

**Comment by kperkins** [comment]
Thanks for taking a look at this @lionel- @romainfrancois @yutannihilation !  Much appreciated and I can use the .data[[]] syntax to overcome my problems right now.  

Before dplyr 0.8 I was using the funs() function and it worked fine with the quasinotation for a different column name the one I was mutating on.  Now with list(), the same operation isn't working, but knowing the .data[[col]] syntax will help me overcome it.

Thanks again!

**Comment by lionel-** [comment]
Reopening as it seems this causes confusion: https://community.rstudio.com/t/getting-argument-e2-is-missing-with-no-default-error-when-using-tidyeval-within-dplyr-summarize-at/25954
