### ISSUE TITLE
feature group_filter: a compact notation for filtering by group

### ISSUE THREAD

**Issue by jhrcook** [tidyverse/dplyr#4200]
Hello,

I have never contributed to another's repo, but I will do my best to follow the guidelines. I fully respect the owners' decision as to whether this feature would be worth including. Also, I apologize if this is already a function, in which case, please close this issue.

I would like to contribute a feature called `group_filter`. It is a simple function for the common idiom of

```r
tib %>%
    group_by(...) %>%
    filter (expr) %>%
    ungroup()
```

The code is really straight forward

```r
group_filter <- function(.data, .expr, ...) {
    .expr <- enquo(.expr)
    .data %>%
        dplyr::group_by(...) %>%
        filter(!!.expr) %>%
        ungroup()
}
```

and the replacement for the idiom is now

```r
tib %>%
    group_filter(expr, ...)
```

Please let me know if this is worth opening a PR for.

Thank you,
Josh Cook

**Comment by romainfrancois** [comment]
You'd probably want to regroup based on how `.data` was initially grouped, instead of ungroup()ing, i.e. 

```r
group_filter <- function(.data, .expr, ...) {
    .expr <- enquo(.expr)
    groups <- groups(.data)
    .data %>%
        group_by(...) %>%
        filter(!!.expr) %>%
        group_by(!!!groups)
}
```

However that's the kind of function that is easily built with the tools `dplyr` provides and can easily live in another package.

**Comment by jhrcook** [comment]
Thank you for your time and feedback!

- Josh Cook
