### ISSUE TITLE
Double-check use of recycling rules

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#4207]
https://github.com/tidyverse/dplyr/blob/22b923e2fc79dae488d20f9ed584de870a40cd6e/src/distinct.cpp#L68-L77

What about length 0 vectors?

Unrelated, but we also might be able to simplify a bit, avoiding the repetition of `get_size(...)`. (Would be curious if a compiler detects the optimization potential):

```r
 int length = 1;
  
 for (int i = 0; i < n; i++) { 
   int curr_length = get_size(variables[i]); 
   if (length == curr_length) continue; 
  
   // TODO: What about inconsistent lengths?
   if (length == 1 && curr_length != 1) { 
     length = curr_length;
   } 
} 
```

**Comment by romainfrancois** [comment]
I guess 0-length may be ignored as well. I'm ok with the simplification. Will you submit a pr @krlmlr ?

**Comment by hadley** [comment]
Let's leave this until 0.9.0 so we can tackle as part of general application of vctrs recycling and coercion rules.

**Comment by romainfrancois** [comment]
yeah, chances are a lot of this code would disappear anyway for a more R facing interface using vctrs (which in turn might use C(++) internally). We can probably even close this.
