### ISSUE TITLE
group_indices.data.frame() should use .drop = TRUE by default?

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#4208]
Related: https://github.com/tidyverse/tidyr/issues/555#issuecomment-465416880

I think this `.drop`, which is passed to `group_by()`, should be `TRUE` or `group_drops(.data)` (which should return `TRUE` for `data.frame`) by default.

https://github.com/tidyverse/dplyr/blob/160b349b870667e408cfcdc0a07d26653a7a4061/R/group-indices.R#L37

https://github.com/tidyverse/tidyr/issues/555#issuecomment-465416880 might be a tidyr's fault in that it should not expect the group indices are always consecutive integers. But, I feel the behaviour below is inconsistent and should be fixed.

``` r
library(dplyr, warn.conflicts = FALSE)

d <- tibble(x = letters[1:10], y = rep(1:2, each = 5), z = factor(rep(LETTERS[1:2], each = 5)))

d %>% 
  group_by(y, z) %>%
  group_indices()
#>  [1] 1 1 1 1 1 2 2 2 2 2

d %>% 
  group_indices(y, z)
#>  [1] 1 1 1 1 1 4 4 4 4 4
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
indeed, can you send a pull request please ?

**Comment by yutannihilation** [comment]
Sure!
