### ISSUE TITLE
group_by no longer accepts NULL

### ISSUE THREAD

**Issue by kyzphong** [tidyverse/dplyr#4210]
group_by no longer accepts NULL and returns the error:
> Column `NULL` is unknown

This is a problem when programming with quosures of unknown length.

```r
band_members %>% group_by(NULL)
```

**Comment by romainfrancois** [comment]
I'm not sure this was ever supposed to work, was it ?

Anyway, here are some alternatives: 

``` r
library(dplyr, warn.conflicts = FALSE)

band_members %>% group_by(!!!NULL)
#> # A tibble: 3 x 2
#>   name  band   
#>   <chr> <chr>  
#> 1 Mick  Stones 
#> 2 John  Beatles
#> 3 Paul  Beatles
band_members %>% group_by(!!!list())
#> # A tibble: 3 x 2
#>   name  band   
#>   <chr> <chr>  
#> 1 Mick  Stones 
#> 2 John  Beatles
#> 3 Paul  Beatles
band_members %>% group_by_at(c())
#> # A tibble: 3 x 2
#>   name  band   
#>   <chr> <chr>  
#> 1 Mick  Stones 
#> 2 John  Beatles
#> 3 Paul  Beatles
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by kyzphong** [comment]
Thanks for the alternatives! I don't know if it was ever supposed to work, but from an end-user's perspective it feels inconsistent that _select_ allows the use of NULL, but not _group_by_ or _arrange_.
