### ISSUE TITLE
`filter(df, TRUE)` converts factors into integers

### ISSUE THREAD

**Issue by burchill** [tidyverse/dplyr#4218]
When you `filter` a `data.frame` with the predicate `TRUE`, it turns all the factors into integers whose value seems to represent the level of the factor a particular value was before.

I was trying to find a predicate that would always evaluate to `TRUE` (i.e. to filter nothing), and found this odd bug. I checked `TRUE==TRUE`, and that works fine. But this unexpected behavior with just `TRUE` should either be stopped by an error or changed, I assume!

```r
# Using dplyr 0.8.0.1
df <- data.frame(x=c("A","B","B"), y=c("X","Y","X"), stringsAsFactors = TRUE)
df
#>   x y
#> 1 A X
#> 2 B Y
#> 3 B X
# Weird behavior
dplyr::filter(df, TRUE)
#>   x y
#> 1 1 1
#> 2 2 2
#> 3 2 1
# Works fine
dplyr::filter(df, TRUE==TRUE)
#>   x y
#> 1 A X
#> 2 B Y
#> 3 B X
```

I'm running `dplyr v0.8.0.1`, by the way.

**Comment by batpigandme** [comment]
Hmm, can you run a reprex of what you're getting;
``` r
df <- data.frame(x=c("A","B","B"), y=c("X","Y","X"), stringsAsFactors = TRUE)
df
#>   x y
#> 1 A X
#> 2 B Y
#> 3 B X
# Weird behavior
dplyr::filter(df, TRUE)
#>   x y
#> 1 A X
#> 2 B Y
#> 3 B X
# Works fine
dplyr::filter(df, TRUE==TRUE)
#>   x y
#> 1 A X
#> 2 B Y
#> 3 B X
```
<sup>Created on 2019-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by burchill** [comment]
Ah, sorry about that, I've updated my previous message to include the output!

**Comment by romainfrancois** [comment]
I cannot reproduce this. 

``` r

df <- data.frame(x=c("A","B","B"), y=c("X","Y","X"), stringsAsFactors = TRUE)
dplyr::filter(df, TRUE)
#>   x y
#> 1 A X
#> 2 B Y
#> 3 B X
```

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
