### ISSUE TITLE
Data frame methods for joins lack `na_matches` argument

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#4225]
as far as I understand : 

```
left_join.data.frame
function (x, y, by = NULL, copy = FALSE, ...) 
{
    as.data.frame(left_join(tbl_df(x), y, by = by, copy = copy, 
        ...))
}
```

could just as well be :

```
left_join.data.frame
function (x, y, by = NULL, copy = FALSE, ..., na_matches = pkgconfig::get_config("dplyr::na_matches")) 
{
    as.data.frame(left_join(tbl_df(x), y, by = by, copy = copy, 
        ..., na_matches = na_matches))
}
```

As `na_matches` is passed through the `...` anyway. Then `left_join.data.frame` and `left_join.tbl_df` would have the same formals, which I believe would be less confusing. Same thing for other joins.

Also, the help page for `?dplyr:::left_join.data.frame` is confusing, it leads to `?
nest_join.data.frame` and the only `data.frame` method that is described is `nest_join.data.frame`, next to `tbl_df` methods for all other joins.

The doc says "see the method documentation for details of individual data sources" but it's not clear to me why not everything is documented on the main page, as all methodq (just 2, for `data.frame` and `tbl_df`)  have the same parameters apart from `na_matches` which is not explicit but may as well be.

**Comment by romainfrancois** [comment]
SGTM, joins are not the priority for the next release, but we'd carefully review a PR that goes in that direction.

**Comment by moodymudskipper** [comment]
I took a shot, it's my first tidyverse real PR, I hope I did OK.

**Comment by hadley** [comment]
I am refocussing this issue on the lack of the `na_matches` argument in the data frame join methods. The related documentation issue is now at https://github.com/tidyverse/dplyr/issues/4682

**Comment by hadley** [comment]
Best approach is probably to generate all data.frame wrappers with code, using something like this:

```R
wrap_tbl_method <- function(generic) {
  method_name <- paste0(generic, ".tbl_df")
  method_impl <- get(method_name)
  method_args <- formals(method_impl)

  method_call <- call2(method_name, !!!syms(set_names(names(method_args))))

  new_function(
    method_args,
    expr(as.data.frame(!!method_call)),
    env = caller_env()
  )
}
```

That will require generating these methods after the `tbl_df` methods so the formals can be found.

**Comment by hadley** [comment]
Or maybe we should just rewrite the existing method hierarchy to make sure the `data.frame` method is always generic, so that it works the same way on data frames, tbls, and grouped tibbles, returning the same output type as the input type.

**Comment by hadley** [comment]
@romainfrancois can you please take this one on? This is now just a matter of merging the `data.frame` and `tbl_df` methods since we now have the technology to conditionally return either a data frame or tibble depending on the input (and the `data.frame` and `tbl_df` methods are now placed next to each other so it's easy to compare). 

(Eventually I expect we'll also unify the `data.frame` and `grouped_df` methods, but that's will happen a little later)

**Comment by hadley** [comment]
Ok, this probably needs a bit more discussion, but here are my notes about how we'll tackle the same problem in tidyr: https://github.com/tidyverse/tidyr/pull/812#issuecomment-571679549
