### ISSUE TITLE
need weighted_mean() to avoid common problem

### ISSUE THREAD

**Issue by behrman** [tidyverse/dplyr#4229]
I teach classes where students learn and use the tidyverse, and I've been noticing that a large proportion are getting wrong results from `weighted.mean()` without knowing it.

The students learn to use `count()` with the `wt` argument. When they then use `weighted.mean()`, they also use the `wt` argument. But `weighted.mean()` does not have a `wt` argument. Its argument for the weights is `w`. It doesn't give an error message when users use `wt` instead of `w`, since it uses `...`. Instead of an error message, it returns the mean, which is almost certainly not what the user wanted.

May I suggest a new tidyverse function `weighted_mean()` that uses `wt` for its weights argument to be consistent with `count()` and that gives an error message when used incorrectly. Otherwise, many tidyverse users may make the same mistake with `weighted.mean()` and get the wrong results without knowing it.

**Comment by hadley** [comment]
This is definitely something we should do, although it might take awhile to get around to it since we have some bigger changes planned for dplyr in the next release.

**Comment by romainfrancois** [comment]
I removed the `IMPORTANT: ` prefix in the title. This could also easily be a function in some other 📦 ?

**Comment by hadley** [comment]
I think this probably should live in funs (or whatever we eventually call it)

**Comment by romainfrancois** [comment]
@behrman can you open an issue here please: https://github.com/r-lib/funs/issues

**Comment by behrman** [comment]
@romainfrancois [Done](https://github.com/r-lib/funs/issues/27). Thanks
