### ISSUE TITLE
[Feature request] Be able to change column headers using dplyr

### ISSUE THREAD

**Issue by anuj2054** [tidyverse/dplyr#4236]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
Be able to rename headers instead of having to use baseR

names(iris) <- c("hello","birdy")
Something like dplyr::renameheader(newheader = old header)
Brief description of the problem

```r
dplyr::renameheader(newheader = old header)

# insert reprex here
```

**Comment by batpigandme** [comment]
By header, do you mean the column names? If so, it's `rename()` https://dplyr.tidyverse.org/reference/select.html

**Comment by anuj2054** [comment]
Sorry, let me expand. More like how in base R we can rename multiple column
names like this :

`Names(my table)[1:4] <- c("name1","name2","name3","name4")`

**Comment by romatik** [comment]
`dplyr::rename` already allows you to do something similar and (arguably) a bit more safely:
``` r
library(magrittr)

new_nms <- names(iris) %>%
  purrr::set_names(nm = letters[1:length(.)])

tibble::as_tibble(iris) %>%
  dplyr::rename(!!!new_nms)
#> # A tibble: 150 x 5
#>        a     b     c     d e     
#>    <dbl> <dbl> <dbl> <dbl> <fct> 
#>  1   5.1   3.5   1.4   0.2 setosa
#>  2   4.9   3     1.4   0.2 setosa
#>  3   4.7   3.2   1.3   0.2 setosa
#>  4   4.6   3.1   1.5   0.2 setosa
#>  5   5     3.6   1.4   0.2 setosa
#>  6   5.4   3.9   1.7   0.4 setosa
#>  7   4.6   3.4   1.4   0.3 setosa
#>  8   5     3.4   1.5   0.2 setosa
#>  9   4.4   2.9   1.4   0.2 setosa
#> 10   4.9   3.1   1.5   0.1 setosa
#> # … with 140 more rows
```

<sup>Created on 2019-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
This way you make sure that you rename each column with exactly the name you want since you are not relying on position as in your example.

**Comment by romainfrancois** [comment]
You can also use `rename_at()` as in: 

``` r
library(dplyr, warn.conflicts = FALSE)

iris %>% 
  head() %>% 
  rename_at(1:4, ~paste0("name", 1:4))
#>   name1 name2 name3 name4 Species
#> 1   5.1   3.5   1.4   0.2  setosa
#> 2   4.9   3.0   1.4   0.2  setosa
#> 3   4.7   3.2   1.3   0.2  setosa
#> 4   4.6   3.1   1.5   0.2  setosa
#> 5   5.0   3.6   1.4   0.2  setosa
#> 6   5.4   3.9   1.7   0.4  setosa
```

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by anuj2054** [comment]
Great thanks.
