### ISSUE TITLE
[Feature Request] lastnonmissing() function for dplyr

### ISSUE THREAD

**Issue by Ranonymous** [tidyverse/dplyr#4237]
Consider the following dataset. It is a minimal example which represents a common data cleaning issue in econonmics/buisness research: You have a unique id variable and a name associated with it, but the names varies slightly. When summarizing data you dont care a lot aobut the different spellings but would like to "keep the last non missing" observation. The closest I can get with the current ``dplyr`` tools is the following:

```r
df= data.frame(
  id=c(1,1,1,2,2,2),
  name=c('michael c.','mike', 'michael','','John',NA),
  time=c(1,2,3,1,2,3),
  var=1:6
)
df %>% 
  arrange(id, time) %>% 
  group_by(id) %>% 
  summarise(sum=sum(var), Name=last(name))

# A tibble: 2 x 3
     id   sum Name   
  <dbl> <int> <fct>  
1     1     6 michael
2     2    15 NA    
```
which is not ideal, since the ```last()``` function takes the ``NA`` value, where I would like it to take the last non missing value. There are of course work arrounds, but inspired by ``Stata``'s ``collapse (lastnm)`` command, I would imagine this a valuable feature for future ``dplyr`` versions.

**Comment by romainfrancois** [comment]
I don't think it needs to be a function in dplyr, i.e. you can do: 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  id=c(1,1,1,2,2,2),
  name=c('michael c.','mike', 'michael','','John',NA),
  time=c(1,2,3,1,2,3),
  var=1:6
)

df %>% 
  arrange(id, time) %>% 
  group_by(id) %>% 
  summarise(sum=sum(var), Name=last(name[!is.na(name)]))
#> # A tibble: 2 x 3
#>      id   sum Name   
#>   <dbl> <int> <chr>  
#> 1     1     6 michael
#> 2     2    15 John
```

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
