### ISSUE TITLE
New list() input does not name columns correctly from bare function names

### ISSUE THREAD

**Issue by DesiQuintans** [tidyverse/dplyr#4238]
- dplyr 0.8.0.1
- R 3.5.2

---

Columns created by `summarise_at()` and with the new `list()` input are not properly named when a list of bare function names is offered:

```
warpbreaks %>%  
    group_by(wool, tension) %>% 
    summarise_at(vars(breaks), list(mean, median, sd)) %>% 
    names()

## [1] "wool"    "tension" "fn1"     "fn2"     "fn3" 

warpbreaks %>%  
    group_by(wool, tension) %>% 
    summarise_at(vars(breaks), list(~mean, ~median, ~sd)) %>% 
    names()

## [1] "wool"    "tension" "mean"    "median"  "sd" 

```

Note that bare names still work with the now-deprecated `funs()`:

```
warpbreaks %>%  
    group_by(wool, tension) %>% 
    summarise_at(vars(breaks), funs(mean, median, sd)) %>% 
    names()

## [Soft deprecation warning]
## [1] "wool"    "tension" "mean"    "median"  "sd"

```

**Comment by echasnovski** [comment]
In your examples `list(mean, median, sd)` represents an already created *list of functions*. When supplied to `summarise_at()` the knowledge of their origin is already lost. Earlier, when supplied to `funs()`, it did some non-standard evaluation magic to deduce the names of input functions, which `list()` doesn't do.

Use strings to supply a *function name* or *name elements of the list* to get custom column names in output.

See reprex below:

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars_grouped <- mtcars %>% group_by(vs)

mtcars_grouped %>%
  summarise_at(vars(am), list("mean", median, my_fun_3 = sd)) %>%
  names()
#> [1] "vs"       "mean"     "fn1"      "my_fun_3"
```

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
There are a number of ways to create a named list, which will get the behavior, e.g. `tibble::lst()` : 

``` r
library(dplyr, warn.conflicts = FALSE)

warpbreaks %>%  
  group_by(wool, tension) %>% 
  summarise_at(vars(breaks), tibble::lst(mean, median, sd)) %>% 
  names()
#> [1] "wool"    "tension" "mean"    "median"  "sd"

tibble::lst(mean, median, sd)
#> $mean
#> function (x, ...) 
#> UseMethod("mean")
#> <bytecode: 0x7fbc760a4aa8>
#> <environment: namespace:base>
#> 
#> $median
#> function (x, na.rm = FALSE, ...) 
#> UseMethod("median")
#> <bytecode: 0x7fbc745865b0>
#> <environment: namespace:stats>
#> 
#> $sd
#> function (x, na.rm = FALSE) 
#> sqrt(var(if (is.vector(x) || is.factor(x)) x else as.double(x), 
#>     na.rm = na.rm))
#> <bytecode: 0x7fbc7a1476f8>
#> <environment: namespace:stats>
```

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
