### ISSUE TITLE
select() stops working in chains over time

### ISSUE THREAD

**Issue by jsonbecker** [tidyverse/dplyr#424]
This one may be hard to replicate, but I consistently find after a few hours I am no longer able to use `select()` as part of chained `dplyr` operations using the `%.%` operator.

Each time, I get the error:

```
Error in select(`__prev`, ...) : 
  unused arguments (...)
```

Where `...` is whatever I'm using for `select`. Quiting and reopening R seems to fix this issue.

**Comment by tmwaring** [comment]
dplyr's select() will get masked by the MASS package.

**Comment by alexander-healey** [comment]
This ^ is probably missed by most but is super important
