### ISSUE TITLE
Possible to export `group_drops()`?

### ISSUE THREAD

**Issue by earowang** [tidyverse/dplyr#4245]
Possible to export `group_drops()` to achieve consistent behaviours with the dependent packages? Probably a better name instead of `group_drops()`?

**Comment by romainfrancois** [comment]
To add some context, `group_drops()` currently looks like this: 

```r
> dplyr:::group_drops
function(x) {
  !is_grouped_df(x) || is.null(attr(x, "groups")) || !identical(attr(group_data(x), ".drop"), FALSE)
}
```

and is used for e.g. the default value for `.drop` in `group_by()`. It probably should be a generic. I'm just not sure about the name at the moment.

**Comment by earowang** [comment]
It's probably too late to change the `.drop` argument to `.preserve` as in `filter()`, both `!.drop` and `.preserve` describing the same behaviour?

`group_drops()` is (and will be) used in the context of `group_by()` and `filter()`/`slice()`? maybe a more general name other than `group_*`?

**Comment by romainfrancois** [comment]
They don't exactly do the same thing : 

 - `group_by(.drop=)` is only about factors. 
 - `filter(.preserve)` is about empty groups after the filtering, that can happen when grouping variables are non factors too.
