### ISSUE TITLE
.preserve: function default FALSE, man page default TRUE

### ISSUE THREAD

**Issue by msberends** [tidyverse/dplyr#4252]
The usage section of the `filter_all()` family shows:

```r
filter_all(.tbl, .vars_predicate, .preserve = FALSE)

filter_if(.tbl, .predicate, .vars_predicate, .preserve = FALSE)

filter_at(.tbl, .vars, .vars_predicate, .preserve = FALSE)
```

Where the arguments sections below it, says:

`.preserve` | `when TRUE (the default), the grouping structure is preserved, otherwise it is recalculated based on the resulting data.`
-- | --

I assume the usage section is right?

**Comment by romainfrancois** [comment]
Thanks. I'll update the doc.
