### ISSUE TITLE
Can't load dplyr.  Error:  there is no package called ‘purrr’

### ISSUE THREAD

**Issue by rinebob** [tidyverse/dplyr#4253]
Hi,
I can't believe I'm the only one with this but I haven't found a specific reference anywhere.  My apologies if this is already answered.

I am simply trying to install dplyr.  It installs to my default package directory no problem (see reprex below).  However, when I run library(dplyr) I get the following error:

Error: package or namespace load failed for ‘dplyr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘purrr’

I can't get beyond this.  I turned off virus and firewall and tried again but no luck.

Thanks for your help!
Bob

Here's some other output:
RStudio version Version 1.1.463

>install.packages("dplyr")
Installing package into ‘C:/Users/Bob/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/dplyr_0.8.0.1.zip'
Content type 'application/zip' length 3240598 bytes (3.1 MB)
downloaded 3.1 MB

package ‘dplyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Bob\AppData\Local\Temp\Rtmp8CcKKU\downloaded_packages

>library(dplyr)
Error: package or namespace load failed for ‘dplyr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘purrr’

>loadedNamespaces()
 [1] "Rcpp"       "grDevices"  "crayon"     "assertthat" "R6"         "magrittr"   "datasets"   "pillar"     "rlang"     
[10] "utils"      "graphics"   "base"       "tools"      "glue"       "compiler"   "pkgconfig"  "stats"      "methods"   
[19] "tibble"    

>.libPaths()
[1] "C:/Users/Bob/Documents/R/win-library/3.5" "C:/Program Files/R/R-3.5.2/library"   

>Sys.getenv() R_LIBS_USER
R_LIBS_USER                         C:/Users/Bob/Documents/R/win-library/3.5

```r
install.packages("dplyr")
library(dplyr)
```

**Comment by romainfrancois** [comment]
Judging from what I see on CRAN right now, https://cran.r-project.org/?package=dplyr

<img width="788" alt="image" src="https://user-images.githubusercontent.com/2625526/53868287-02069000-3ff6-11e9-87c8-5e33efd03b81.png">

it is possible you were just unlucky, and perhaps `purrr` 0.3.1 is just being released on windows, note the discrepancy between versions of binary packages for `purrr` on the various windows versions. 

Maybe you can just try to install `purrr` again 🤷‍♂️ .
