### ISSUE TITLE
pull behavior

### ISSUE THREAD

**Issue by joel23888** [tidyverse/dplyr#4254]
In the help entry for `pull` it says "This works like [[ for local data frames" but I find when using it with a list column containing `data.frame` it returns a list of `data.fame` even if I pull what should be a single `data.frame`. Is this expected behavior?

In the example below I expected the pipeline which uses `filter` then `pull` to return a `data.frame` not a list because there is only one element.

```r
> x
# A tibble: 2 x 1
      a
  <int>
1     1
2     2
> y <- tibble(b=1:2, d=list(x))
> y
# A tibble: 2 x 2
      b d               
  <int> <list>          
1     1 <tibble [2 × 1]>
2     2 <tibble [2 × 1]>
> y %>% filter(b==1) %>% pull(d)
[[1]]
# A tibble: 2 x 1
      a
  <int>
1     1
2     2

> (y %>% pull(d))[[1]]
# A tibble: 2 x 1
      a
  <int>
1     1
2     2
```

**Comment by romainfrancois** [comment]
Please use the `reprex` package to prepare the example code, this way we can easily copy, paste and execute your code.

**Comment by romainfrancois** [comment]
`pull()` returns a single column from the data frame, in this case, the column happens to be a list of data frames, so that's what you get. 

``` r
library(dplyr, warn.conflicts = FALSE)

x <- tibble(a = 1:2)
y <- tibble(b = 1:2, d = list(x))

pull(y, d)
#> [[1]]
#> # A tibble: 2 x 1
#>       a
#>   <int>
#> 1     1
#> 2     2
#> 
#> [[2]]
#> # A tibble: 2 x 1
#>       a
#>   <int>
#> 1     1
#> 2     2
y[[2]]
#> [[1]]
#> # A tibble: 2 x 1
#>       a
#>   <int>
#> 1     1
#> 2     2
#> 
#> [[2]]
#> # A tibble: 2 x 1
#>       a
#>   <int>
#> 1     1
#> 2     2

filter(y, x == 1)[[2]]
#> [[1]]
#> # A tibble: 2 x 1
#>       a
#>   <int>
#> 1     1
#> 2     2
y %>% filter(x == 1) %>% pull(d)
#> [[1]]
#> # A tibble: 2 x 1
#>       a
#>   <int>
#> 1     1
#> 2     2
```

<sup>Created on 2019-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
