### ISSUE TITLE
error with count in dplyr:::rename.data.frame

### ISSUE THREAD

**Issue by nolistic** [tidyverse/dplyr#4270]
---

Brief description of the problem

When trying to make a histogram with dbplot, I ran into this error.
`Error: `count` = n must be a symbol or a string, not a formula`

Pulling out, this seems to be the simplest reproducible example.

```r
dplyr:::rename.data.frame(tibble(x=1,n=4),count=n)
```

**Comment by romainfrancois** [comment]
I cannot reproduce the problem either with the code above : 

``` r
dplyr:::rename.data.frame(tibble::tibble(x=1,n=4),count=n)
#> # A tibble: 1 x 2
#>       x count
#>   <dbl> <dbl>
#> 1     1     4
```

or with the more traditional: 

``` r
library(dplyr, warn.conflicts = FALSE)

rename(tibble(x=1,n=4),count=n)
#> # A tibble: 1 x 2
#>       x count
#>   <dbl> <dbl>
#> 1     1     4
```

Did you perhaps simplify too much ?
