### ISSUE TITLE
top_n doesn't work with as.data.frame

### ISSUE THREAD

**Issue by ZahraEconomist** [tidyverse/dplyr#4274]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

I used the top_n inside of the function like this (print(data %>% top_n(10, varname)) which works as expected and print 10 observations, when I use it in combine with as.data.frame to give output a better look, it starts printing the whole dataset (print(data %>% top_n(10, varname) %>% as.data.frame)
```r
# insert reprex here
```

**Comment by batpigandme** [comment]
I'm not able to reproduce your problem, could you please include a reprex:
``` r
suppressPackageStartupMessages(library(tidyverse))
print(mtcars %>% top_n(10, mpg) %>% as.data.frame())
#>     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> 1  22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> 2  24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
#> 3  22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
#> 4  32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
#> 5  30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
#> 6  33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
#> 7  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
#> 8  27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
#> 9  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
#> 10 30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
```

<sup>Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
