### ISSUE TITLE
summarise_all performance notoriously  degraded  after packages update

### ISSUE THREAD

**Issue by nicokuz** [tidyverse/dplyr#4275]
Until recently this expression worked fine in terms of speed, usually took few seconds. 
After I updated several packages to last version (including dplyr to  0.8.0.1), same expression with same data now take more than 2 minutes. I'm  pretty sure it's related to the updates, but not certain if it's a dplyr problem. I don't know exactly which other packages where updated besides dplyr, even less their versions... Wonder if I could provide any other information for help. Thanks

```r
customerVals <- products %>% group_by(NationalID) %>% summarise_all(n_distinct) 
```
Data
> str(products)
'data.frame':	115148 obs. of  19 variables:
 $ NationalID         : num  1 2 3 4 5 6 7 7 8 8 ...

**Comment by romainfrancois** [comment]
Chances are this was fixed by #4205. 

For future reference, a [reprex](https://reprex.tidyverse.org) would have been useful, e.g. we don't have `products`.
