### ISSUE TITLE
Update functions using `quos()` to use `enquos()`

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/dplyr#4277]
From the community thread here: https://community.rstudio.com/t/should-i-use-quos-or-enquos/25976

The following functions use `quos()`:
`dplyr:::filter.tbl_df`
`dplyr:::arrange.tbl_df`
`dplyr:::select.data.frame`

and should be updated to use `vars()`.

**Comment by hadley** [comment]
I think you mean they should use `enquos()`, not `vars()`.
