### ISSUE TITLE
mutate with is.primitive(get()) doesn't give correct results

### ISSUE THREAD

**Issue by cgrandin** [tidyverse/dplyr#4280]
The following function creates a tibble with two columns, ```name``` and ```is.primitive```. In this case, ```scan``` is not primitive and ```is.array``` is primitive but the values inserted by ```mutate()``` are both FALSE.

Browsing into the function, you can get the correct values with ```is.primitive(get(j$name[1]))``` and ```is.primitive(get(j$name[2]))``` so it isn't an environment issue with ```get()```.

```r
xx <- function(){
  j <- tibble(name = c("scan", "is.array")) %>%
    mutate(is.primitive = is.primitive(get(name)))
}
```

**Comment by batpigandme** [comment]
Adding reprex with output:

``` r
library(dplyr)

xx <- function(){
  j <- tibble(name = c("scan", "is.array")) %>%
    mutate(is.primitive = is.primitive(get(name)))
}

j <- xx()
j
#> # A tibble: 2 x 2
#>   name     is.primitive
#>   <chr>    <lgl>       
#> 1 scan     FALSE       
#> 2 is.array FALSE
```

<sup>Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by moodymudskipper** [comment]
`name` in `get(name)` is a character vector, `get` takes a length 1 argument.
Strangely it doesn't warn when you feed it a longer character vector but only considers the first one. So your result is `FALSE` and is recycled.

`mget` can take a character vector argument, but you'd still have a problem because `is.primitive` will return false if you feed it a list of functions.

The proper way to do it would be : 

```
tibble(name = c("scan", "is.array")) %>%
    mutate(is.primitive = map_lgl(name,~is.primitive(get(.))))
# # A tibble: 2 x 2
#   name     is.primitive
#   <chr>    <lgl>       
# 1 scan     FALSE       
# 2 is.array TRUE        
```

**Comment by romainfrancois** [comment]
Thanks @moodymudskipper for the detailed explanation. 😠 `get()` for silently taking only the first element of `x`.

**Comment by cgrandin** [comment]
Thanks @moodymudskipper, totally makes sense and I appreciate the workaround!
