### ISSUE TITLE
bind_rows() Feature Suggestion: Allow coercion to character for non-matching column classes

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#4281]
I'd like to suggest an argument for bind_rows to allow conversion of non-matching column types to character. Currently it fails in either direction:

``` r
suppressPackageStartupMessages(require(tidyverse))

mtcars_char <- mtcars %>% mutate(mpg = as.character(mpg))

bind_rows(mtcars_char, mtcars)
#> Error: Column `mpg` can't be converted from character to numeric

bind_rows(mtcars, mtcars_char)
#> Error: Column `mpg` can't be converted from numeric to character
```

<sup>Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I often come across data sets from different time periods where the same column only happened to have numeric data one time, but had some character another time, and I would be fine to have it all as numeric.

One alternative is to specify when reading in the data for each column that has this issue that it be classed as character.  However, this is a bad solution when there are many columns with this issue in a very wide data set, as it requires a lot of specifying.  It also requires loading both tables first and then determining which don't match, then reloading with the correct column class specifications.

Another alternative is to read in the data with the default for all columns set to character, but of course this then adds a lot of work in re-applying the correct class to all the columns where the matching wouldn't have been an issue.  (I've been known to do this with something like `mutate_if(funs(Hmisc::all.is.numeric(., extras = c(".", "NA", NA, NA_character_))), as.numeric)`, but it's slow and clunky).

My suggestion would be to add an argument such as `convert.conflicts.to.char = T` that would make all conflicting columns character class, and issue a warning about each one.

**Comment by romainfrancois** [comment]
`bind_rows()` will slowly be replaced by `vctrs::vec_rbind()` which has a more fully featured concept for type conversion, ...

``` r
library(dplyr, warn.conflicts = FALSE)
library(vctrs)

mtcars_char <- mtcars %>% mutate(mpg = as.character(mpg))

vec_rbind(mtcars, mtcars_char, .ptype = mtcars) %>% 
  as_tibble() # for printing
#> # A tibble: 64 x 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 54 more rows
```

Note that you have to be explicit about the `.ptype` in that case because conversion from double to character is possible but not automatic.
