### ISSUE TITLE
group_by() with .drop=FALSE gives potentially unexpected results when one or more grouping columns is not coded as factor

### ISSUE THREAD

**Issue by eipi10** [tidyverse/dplyr#4282]
I'm not sure if this is a bug or the intended behavior, but using `.drop=FALSE` with`group_by()` can give potentially unexpected results (well, at least I didn't expect it) when one or more grouping variables are not coded as factors. I've included an example below. Specifically, empty combinations of the non-factor grouping variable with other (factor) variables are not included in the output. 

I realize this can be resolved by coding all grouping variables as factors, but is there a reason why `.drop=FALSE` shouldn't preserve all empty combinations of groups, even if some are coded as character or integer (or integers coded as numeric)? Also, under the current approach, if you want to keep empty groups and one of your groups is coded as integer, you have to recode it as a factor or create a new column equal to the integer column but coded as a factor, neither of which seems sensible to me.

    library(dplyr)
    data(iris)
    
    # Add an additional level to Species
    iris$Species = factor(iris$Species, levels=c(levels(iris$Species), "empty_level"))
    
    # Species is a factor and empty groups are included in the output
    iris %>% group_by(Species, .drop=FALSE) %>% tally

    #>   Species         n
    #> 1 setosa         50
    #> 2 versicolor     50
    #> 3 virginica      50
    #> 4 empty_level     0
    
    # Add character column
    iris$group2 = c(rep(c("A","B"), 50), rep(c("B","C"), each=25))
    
    # Empty groups involving combinations of Species and group2 are not included in output, but
    #  the last row has a missing value for group2, indicating that something has not 
    #  gone as expected
    iris %>% group_by(Species, group2, .drop=FALSE) %>% tally

    #>   Species     group2     n
    #> 1 setosa      A         25
    #> 2 setosa      B         25
    #> 3 versicolor  A         25
    #> 4 versicolor  B         25
    #> 5 virginica   B         25
    #> 6 virginica   C         25
    #> 7 empty_level <NA>       0
    
    # Turn group2 into a factor
    iris$group2 = factor(iris$group2)
    
    # Now all possible combinations of Species and group2 are included in the output, 
    #  whether present in the data or not
    iris %>% group_by(Species, group2, .drop=FALSE) %>% tally

    #>    Species     group2     n
    #>  1 setosa      A         25
    #>  2 setosa      B         25
    #>  3 setosa      C          0
    #>  4 versicolor  A         25
    #>  5 versicolor  B         25
    #>  6 versicolor  C          0
    #>  7 virginica   A          0
    #>  8 virginica   B         25
    #>  9 virginica   C         25
    #> 10 empty_level A          0
    #> 11 empty_level B          0
    #> 12 empty_level C          0

    Created on 2019-03-13 by the reprex package (v0.2.1)

**Comment by romainfrancois** [comment]
This is what is expected here, `.drop` only concerns factors: 

``` r
library(dplyr, warn.conflicts = FALSE)

iris$Species = factor(iris$Species, levels=c(levels(iris$Species), "empty_level"))
iris %>% group_by(Species, .drop=FALSE) %>% tally
#> # A tibble: 4 x 2
#>   Species         n
#>   <fct>       <int>
#> 1 setosa         50
#> 2 versicolor     50
#> 3 virginica      50
#> 4 empty_level     0
iris$group2 = c(rep(c("A","B"), 50), rep(c("B","C"), each=25))
iris %>% group_by(Species, group2, .drop=FALSE) %>% tally
#> # A tibble: 7 x 3
#> # Groups:   Species [4]
#>   Species     group2     n
#>   <fct>       <chr>  <int>
#> 1 setosa      A         25
#> 2 setosa      B         25
#> 3 versicolor  A         25
#> 4 versicolor  B         25
#> 5 virginica   B         25
#> 6 virginica   C         25
#> 7 empty_level <NA>       0
```

The data is first conceptually split in 4 groups, one for each Species. 
Then within each Species, the data is again divided according to the observed values for `group2`, there is no data to observe for `empty_level` so it's not divided here and the `group2` is artificially set to NA.

**Comment by eipi10** [comment]
Maybe it would make sense to add a note in the documentation of `group_by` noting explicitly that `.drop=FALSE` affects only grouping columns that are coded as factors.
