### ISSUE TITLE
summarise bug with multiple uses of variable name

### ISSUE THREAD

**Issue by mjherold** [tidyverse/dplyr#4285]
### Description of problem

The `summarise` function in dplyr seems to have a bug when you use as variable name for a summary statistic the same name as for the variable for which the statistic is being evaluated. With subsequent calculations of statistics for the same variable you get wrong answers! This can be seen with the example that is provided under help for `summaries`:

~~~~
> mtcars %>%
+   group_by(cyl) %>%
+   summarise(disp = mean(disp), sd = sd(disp))
# A tibble: 3 x 3
    cyl  disp    sd
  <dbl> <dbl> <dbl>
1     4  105.    NA
2     6  183.    NA
3     8  353.    NA
~~~~

Notice how `disp` is used as reference to the mean values, while also being the variable holding the values for which the mean per group is being calculated! The column for `sd` will show NA's.

If we rename the summary variable `disp` to `mean` we get the correct answer for the SD's.

~~~~
> mtcars %>%
+   group_by(cyl) %>%
+   summarise(mean = mean(disp), sd = sd(disp))
# A tibble: 3 x 3
    cyl  mean    sd
  <dbl> <dbl> <dbl>
1     4  105.  26.9
2     6  183.  41.6
3     8  353.  67.8
~~~~

The problem only appears if you calculate multiple statistics for the same variable, and in the first instance use as name for the variable holding the summary the same as for the variable for which you calculate the statistic.

---

```r
mtcars  %>% 
   group_by(cyl) %>% 
   summarise(disp = mean(disp), sd = sd(disp))
```

**Comment by batpigandme** [comment]
`summarise()` is a special kind of [`mutate()`](https://dplyr.tidyverse.org/reference/mutate.html) and uses the same semantics, such that:
> New variables overwrite existing variables of the same name.
The operations are executed sequentially.

**Comment by mjherold** [comment]
I think the example provided in the documentation, and which I copied above, gives an unexpected answer for the SD's, which makes you think it is a bug. This could be a bit clearer!

**Comment by batpigandme** [comment]
Currently it reads
```
# Note that with data frames, newly created summaries immediately
# overwrite existing variables
mtcars %>%
  group_by(cyl) %>%
  summarise(disp = mean(disp), sd = sd(disp))
```

https://github.com/tidyverse/dplyr/blob/919f4457dddd3930565e4aa51042a3957af0af7a/R/manip.r#L249-L254

I think it's expected that the standard deviation of a mean is NA, but we could state that explicitly in words.

**Comment by mjherold** [comment]
Maybe just add "with the same name" to the comment above that code example?
~~~~
# Note that with data frames, newly created summaries immediately
# overwrite existing variables with the same name
~~~~

**Comment by batpigandme** [comment]
Nice — that'd match the `mutate()` docs, too, then.

**Comment by JohnMount** [comment]
Just a small point: the documentation you are considering is inconsistent with `dbplyr`'s semantics.  I think some care may be needed to say if `dbplyr` is an realization of `dplyr` or not.

``` r
library("dplyr")
#> Warning: package 'dplyr' was built under R version 3.5.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

mtcars %>%
    group_by(cyl) %>%
    summarise(disp = mean(disp, na.rm = TRUE), sd = sd(disp, na.rm = TRUE))
#> # A tibble: 3 x 3
#>     cyl  disp    sd
#>   <dbl> <dbl> <dbl>
#> 1     4  105.    NA
#> 2     6  183.    NA
#> 3     8  353.    NA

db <- DBI::dbConnect(RSQLite::SQLite(),
                     ":memory:")
DBI::dbWriteTable(db, "mtcars_db", mtcars)
mtcars_db <- tbl(db, "mtcars_db")

mtcars_db %>%
  group_by(cyl) %>%
  summarise(disp = mean(disp, na.rm = TRUE), sd = sd(disp, na.rm = TRUE))
#> # Source:   lazy query [?? x 3]
#> # Database: sqlite 3.22.0 [:memory:]
#>     cyl  disp    sd
#>   <dbl> <dbl> <dbl>
#> 1     4  105.  26.9
#> 2     6  183.  41.6
#> 3     8  353.  67.8

DBI::dbDisconnect(db)
```

<sup>Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by batpigandme** [comment]
@edgararuiz, do you want me to open an issue in dbplyr re. @JohnMount's point, above?
