### ISSUE TITLE
Avoiding error when using rename in combination with a list of old and new column names

### ISSUE THREAD

**Issue by ThiAmm** [tidyverse/dplyr#4288]
Suppose i have two tibbles `t1` and `t2`:
```r
t1 <- tibble(a = c(1,2),b=c(2,3))
t2 <- tibble(b = c(2,3),c = c(3,2))
t1
# A tibble: 2 x 2
      a     b
  <dbl> <dbl>
1     1     2
2     2     3
t2
# A tibble: 2 x 2
      b     c
  <dbl> <dbl>
1     2     3
2     3     2
```
and a list `columnNamesToRename`:
```r
columnNamesToRename <- list(f = "b", h = "c")
```
---

If i want to rename the tibble `t2` based on the convention defined list `columnNamesToRename`, i get the following error 
```r
t1 %>% rename(!!!columnNamesToRename)
Error: Unknown column `c` 
Call `rlang::last_error()` to see a backtrace
```

Is it reasonable to introduce a parameter warn_missing like in `plyr` so that 
```r
t1 %>% rename(!!!columnNamesToRename, warn_missing = FALSE)
```
would return 
```
# A tibble: 2 x 2
      a     f
  <dbl> <dbl>
1     1     2
2     2     3
```

**Comment by romainfrancois** [comment]
If you're ok with splicing, one thing you can do is splice less, i.e. programmatically select only the elements that you want, e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

t1 <- tibble(a = c(1,2),b=c(2,3))
t2 <- tibble(b = c(2,3),c = c(3,2))
t1
#> # A tibble: 2 x 2
#>       a     b
#>   <dbl> <dbl>
#> 1     1     2
#> 2     2     3

columnNamesToRename <- c(f = "b", h = "c") %>% keep(~. %in% tbl_vars(t1))

t1 %>% 
  rename(!!!columnNamesToRename)
#> # A tibble: 2 x 2
#>       a     f
#>   <dbl> <dbl>
#> 1     1     2
#> 2     2     3
```

<sup>Created on 2019-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
Closing this now, I don't think it's worth making `rename()` etc ... more complicated, the `%>% keep()` can "easily" be generalized in a function
