### ISSUE TITLE
Vignette on grouped data frames

### ISSUE THREAD

**Issue by jennybc** [tidyverse/dplyr#4290]
I think it would be a good idea to create a vignette on grouped operations to organize and advertise useful mental models and workflows around grouped data frames.

I'd be happy to initiate or contribute but can't do it right now. Dumping some thoughts here, inspired by recent conversations around the PR revising `group_map()` and friends (#4251 Simpler `group_map()`).

Vocabulary/concept: key variables vs data variables.

General pattern for grouped operations where we want to retain data-frame-iness:
  1. designate keys
  1. group
  1. nest
  1. map inside mutate, then unnest or simplify through some other means
  1. or ... `map2_dfr()` or `pmap_dfr()` on keys and data

The general pattern has specific desirable properties:
  * The role of key variables vs grouping variable is clear and actively maintained.
    - Contrast this with a true split where grouping variables are retained but are identifiable only implicitly, i.e. as "the variables that are constant within group, for all groups". A property which is also only guaranteed at the very start and could be inadvertently lost.
  * Key variables are not vulnerable to losing their type / unwanted coercion or just going missing altogether.
    - Contrast this with a split where grouping variables are not retained, but instead are crammed into list names (coercion, type loss) or not (complete loss).

The general pattern has some undesirable properties:
  * Many people are not comfortable with list-columns.
  * Many people are not comfortable with "map inside mutate".
  * Getting back out of the nested state is not a cut-and-dried operation and often involves judgment and specific bag of tricks.

The `group_map()` family of functions provides a more approachable front-end for 👆 workflow that covers many people's use cases.

Important thing to think about when choosing which function to use:
  * Do you need the key variables inside your grouped operation, i.e. do you actually use them?
  * Or do you just need the key variables to remain attached and re-unified with the results of your grouped operation?

**Comment by jennybc** [comment]
Proposal: create an example along these lines -- maybe from the starwars data? -- that allows compare and contrast re: what sort of output one gets, how/if the key data is available in the computation, if the key data makes it into the result, etc. This is based on an example from a @coolbutuseless [blog post](https://coolbutuseless.github.io//03/17/group_map-in-dplyr-0.8.1-still-in-development/).

``` r
library(tidyverse)
library(glue)

df <- tibble(
  type  = factor(c('a', 'a', 'b', 'b', 'b'), levels = c('a', 'b', 'c')),
  value = c(1, 2, 3, 4, 5)
)

gdf <- group_by(df, type, .drop = FALSE) 
data_part <- group_split(gdf, keep = FALSE)
keys_part <- group_keys(gdf) %>% pmap(list)

my_func <- function(.x, .y) {
  glue("Group '{.y$type}' has {nrow(.x)} rows")
}

map2(data_part, keys_part, my_func)
#> [[1]]
#> Group 'a' has 2 rows
#> 
#> [[2]]
#> Group 'b' has 3 rows
#> 
#> [[3]]
#> Group 'c' has 0 rows
gdf %>%
  group_map(my_func)
#> [[1]]
#> Group 'a' has 2 rows
#> 
#> [[2]]
#> Group 'b' has 3 rows
#> 
#> [[3]]
#> Group 'c' has 0 rows

my_func2 <- function(.x, .y) {
  tibble(text = glue("Group '{.y$type}' has {nrow(.x)} rows"))
}

gdf %>%
  group_modify(my_func2)
#> Warning in bind_rows_(x, .id): Vectorizing 'glue' elements may not preserve
#> their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'glue' elements may not preserve
#> their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'glue' elements may not preserve
#> their attributes
#> # A tibble: 3 x 2
#> # Groups:   type [3]
#>   type  text                
#>   <fct> <chr>               
#> 1 a     Group 'a' has 2 rows
#> 2 b     Group 'b' has 3 rows
#> 3 c     Group 'c' has 0 rows

my_func3 <- function(.x, .y) {
  glue("Group '{.y}' has {nrow(.x)} rows")
}

gdf %>% 
  group_nest() %>% 
  mutate(text = map2_chr(data, type, my_func3)) %>% 
  select(-data)
#> # A tibble: 3 x 2
#>   type  text                
#>   <fct> <chr>               
#> 1 a     Group 'a' has 2 rows
#> 2 b     Group 'b' has 3 rows
#> 3 c     Group 'c' has 0 rows
```

<sup>Created on 2019-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
Thanks for opening the issue and volunteering to bootstrap it at some point. 

The warnings come form `bind_rows()` which have not received a lot of ❤️ leading to the 0.8.0, part of it is that it will be replaced by `vctrs::vec_rbind()`, perhaps once https://github.com/r-lib/vctrs/issues/229 this dealt with.

**Comment by rcorty** [comment]
looks like the URL changed for the blog post @jennybc mentioned.  New link is: https://coolbutuseless.github.io/2019/03/17/group_map-in-dplyr-0.8.1-still-in-development/
I believe

**Comment by hadley** [comment]
@jennybc do you think you could commit to turning this into a rough outline (just a couple of levels of headings) so we could tackle for TDD 2020?

**Comment by jennybc** [comment]
Yes I can provide an outline. I can't do it right now, so if the date is approaching and this has not happened, anyone who comes through here is encouraged to remind me.

**Comment by hadley** [comment]
Other issues to mine for ideas: #3782, #4518.

**Comment by hadley** [comment]
I'll take point on turning this issue into a form more suitable for TDD.

Another notes:

* Existing content in https://dplyr.tidyverse.org/articles/dplyr.html#grouped-operations (scheduled for deletion)
* Introduce the envelope vs. contents of the envelope metaphor

**Comment by jennybc** [comment]
The materials for my [row-oriented workflows webinar](https://github.com/jennybc/row-oriented-workflows) might have good examples to revisit with the current tools. Some specific ones that seem relevant:

  * [Generate data from different distributions via `pmap()`](https://github.com/jennybc/row-oriented-workflows/blob/master/ex06_runif-via-pmap.md)
  * [Work on groups of rows via `dplyr::group_by()` + `summarise()`](https://github.com/jennybc/row-oriented-workflows/blob/master/ex07_group-by-summarise.md) *was about how `summarise()` requires one-row per group, which is no longer true*
  * [Row-wise Summaries](https://github.com/jennybc/row-oriented-workflows/blob/master/ex09_row-summaries.md)

**Comment by hadley** [comment]
Now in #4767 — I'd gotten slightly confused about what the topic of this thread was.
