### ISSUE TITLE
Wrong result for bind_rows on a list of character vectors

### ISSUE THREAD

**Issue by AntoineHffmnn** [tidyverse/dplyr#4300]
Description of the problem:
I wanted to use bind_rows on a list of named character vectors (all the same length) to get a data.frame where every row is one of the vectors in the list. The result I get is the same as for bind_cols: each vector is in a column instead of a row. I get the right result with do.call(rbind,list).

Example:

```
> list<-list(rep("a",3),rep("b",3),rep("c",3))
> names(list)<-c("A","B","C")
> bind_rows(list)
> bind_cols(list)
>#what I wanted and expected to get:
> do.call(rbind,list)
```

Cheers,
Antoine

**Comment by romainfrancois** [comment]
Please use the `reprex` package to prepare minimal reproducible examples.

**Comment by romainfrancois** [comment]
The `list` object passed in is interpreted as a single data frame like object, as it's a named list of vectors of the same size, this is for better or worse  what `bind_*()` functions do. 

If you want each of the element to be a data frame, you'd have to perform the conversion, e.g. something like this. There might be easier ways. Alternatively, you can use `vctrs::vec_rbind()` : 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

list<-list(rep("a",3),rep("b",3),rep("c",3))
names(list)<-c("A","B","C")

list %>% 
  map(~tibble(!!!., .name_repair = ~c("x", "y", "z"))) %>% 
  bind_rows()
#> # A tibble: 3 x 3
#>   x     y     z    
#>   <chr> <chr> <chr>
#> 1 a     a     a    
#> 2 b     b     b    
#> 3 c     c     c

vctrs::vec_rbind(!!!list)
#> New names:
#>  -> ..1
#>  -> ..2
#>  -> ..3
#> New names:
#>  -> ..1
#>  -> ..2
#>  -> ..3
#> New names:
#>  -> ..1
#>  -> ..2
#>  -> ..3
#>   ..1 ..2 ..3
#> 1   a   a   a
#> 2   b   b   b
#> 3   c   c   c
```

<sup>Created on 2019-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
