### ISSUE TITLE
Support unquote splicing (!!!) in list inside function verbs like summarize_at

### ISSUE THREAD

**Issue by codetrainee** [tidyverse/dplyr#4302]
```r
library(tidyverse)
library(purrr)

p <- c(0.2, 0.5, 0.8)

p_names <- map_chr(p, ~paste0(.x*100, "%"))

p_funs <- map(p, ~partial(quantile, probs = .x, na.rm = TRUE)) %>% 
  set_names(nm = p_names) 

mtcars %>% 
  group_by(cyl) %>% 
  summarize_at(vars(mpg), funs(!!!p_funs))
#> Warning: funs() is soft deprecated as of dplyr 0.8.0
#> please use list() instead
#> 
#> # Before:
#> funs(name = f(.)
#> 
#> # After: 
#> list(name = ~f(.))
#> This warning is displayed once per session.
#> # A tibble: 3 x 4
#>     cyl `20%` `50%` `80%`
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     4  22.8  26    30.4
#> 2     6  18.3  19.7  21  
#> 3     8  13.9  15.2  16.8
```

After switching to `list`, the code broke. 
```
mtcars %>% 
  group_by(cyl) %>% 
  summarize_at(vars(mpg), list(~ !!!p_funs))
#> Error in !p_funs: invalid argument type
```

[Moody Mudskipper](https://stackoverflow.com/users/2270475/moody-mudskipper) pointed it out that on [stackoverlfow](https://stackoverflow.com/questions/55396890/unquote-a-list-of-functions-inside-r-dplyr-functions): `list` doesn't support splicing `(!!!)`, use `list2` or `lst` instead. 

```
mtcars %>% 
  group_by(cyl) %>% 
  summarize_at(vars(mpg), rlang::list2(!!!p_funs))
#> # A tibble: 3 x 4
#>     cyl `20%` `50%` `80%`
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     4  22.8  26    30.4
#> 2     6  18.3  19.7  21  
#> 3     8  13.9  15.2  16.8

mtcars %>% 
  group_by(cyl) %>% 
  summarize_at(vars(mpg), lst(!!!p_funs))
#> # A tibble: 3 x 4
#>     cyl `20%` `50%` `80%`
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     4  22.8  26    30.4
#> 2     6  18.3  19.7  21  
#> 3     8  13.9  15.2  16.8
```

The workaround does work but the code, in my view, looks inconsistent. Therefore, I was wondering if you have any plan to support the unquote splicing feature in these dplyr function verbs.

**Comment by moodymudskipper** [comment]
I answered a bit fast on SO (just updated my answer), here the simplest way is just: 

```
mtcars %>% 
  group_by(cyl) %>% 
  summarize_at(vars(mpg), p_funs)
```

But maybe the doc should say "please use lst() instead" as it seems now to imply that `list` and `funs` are equivalent when they aren't.

**Comment by romainfrancois** [comment]
We'll look into updating the warning from `funs()`

**Comment by romainfrancois** [comment]
Can we just re-export `rlang::list2` and then say `please use list2() instead` ?

**Comment by hadley** [comment]
Sounds like a good approach to me.

**Comment by lionel-** [comment]
In that case `list2()` should probably only be shown in examples featuring `!!!`, otherwise it might increase net confusion / weird code as people will use `list2()` where `list()` would have been sufficient. This might be wrongly suggestive that `list2()` is needed because of some unknown magic property.
