### ISSUE TITLE
goup_by and mutate error

### ISSUE THREAD

**Issue by amitusa17** [tidyverse/dplyr#4311]
I am trying to calculate percentage change using mutate:

here is the data and code:
BRAND <- c('Brand1', 'Brand1', 'Brand2', 'Brand2', 'Brand3', 'Brand3', 'Brand3', 'Brand4')
YEAR <- c(2015, 2016, 2015, 2016, 2015, 2016, 2017, 2015)
EUR <- c(10, 20, 30, 40, 50, 60, 70, 80)
df <- data.frame(BRAND, YEAR, EUR)

df %>% group_by(BRAND) %>% 
  mutate(pChange = (EUR - lag(EUR))/lag(EUR) * 100)

This is what i am seeing:
![Capture](https://user-images.githubusercontent.com/49172888/55365100-d1a4fb00-54a8-11e9-939e-9d987bbe4a10.PNG)

while i was expecting this to do something similar:
![image](https://user-images.githubusercontent.com/49172888/55366160-2185c100-54ad-11e9-899f-6f3a40107ebe.png)

NAs should have been created for every group

P.S. : **R version 3.4.1**  
**dplyr version 0.7.2**

**Comment by amitusa17** [comment]
I am trying to calculate percentage change using mutate:

here is the data and code:
BRAND <- c('Brand1', 'Brand1', 'Brand2', 'Brand2', 'Brand3', 'Brand3', 'Brand3', 'Brand4')
YEAR <- c(2015, 2016, 2015, 2016, 2015, 2016, 2017, 2015)
EUR <- c(10, 20, 30, 40, 50, 60, 70, 80)
df <- data.frame(BRAND, YEAR, EUR)

df %>% group_by(BRAND) %>% 
  mutate(pChange = (EUR - lag(EUR))/lag(EUR) * 100)

This is what i am seeing:
![Capture](https://user-images.githubusercontent.com/49172888/55365100-d1a4fb00-54a8-11e9-939e-9d987bbe4a10.PNG)

while i was expecting this to do something similar:
![image](https://user-images.githubusercontent.com/49172888/55366160-2185c100-54ad-11e9-899f-6f3a40107ebe.png)

NAs should have been created for every group

**Comment by cderv** [comment]
This is what I get with last dev version of dplyr
``` r
library(dplyr)
packageVersion("dplyr")
#> [1] '0.8.0.9000'
BRAND <- c('Brand1', 'Brand1', 'Brand2', 'Brand2', 'Brand3', 'Brand3', 'Brand3', 'Brand4')
YEAR <- c(2015, 2016, 2015, 2016, 2015, 2016, 2017, 2015)
EUR <- c(10, 20, 30, 40, 50, 60, 70, 80)
df <- data.frame(BRAND, YEAR, EUR)

df %>% group_by(BRAND) %>%
  mutate(pChange = (EUR - lag(EUR))/lag(EUR) * 100)
#> # A tibble: 8 x 4
#> # Groups:   BRAND [4]
#>   BRAND   YEAR   EUR pChange
#>   <fct>  <dbl> <dbl>   <dbl>
#> 1 Brand1  2015    10    NA  
#> 2 Brand1  2016    20   100  
#> 3 Brand2  2015    30    NA  
#> 4 Brand2  2016    40    33.3
#> 5 Brand3  2015    50    NA  
#> 6 Brand3  2016    60    20  
#> 7 Brand3  2017    70    16.7
#> 8 Brand4  2015    80    NA
```

<sup>Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Seems ok.

**Comment by batpigandme** [comment]
Can confirm what @cderv is seeing. Looks like whatever's happening has been fixed in the development version, @amitusa17.

If you have further questions, the best place to ask them is on community.rstudio.com. If it turns out there is a bug, we can always re-open this, or open a new thread when we have more information.

Thanks

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '0.8.0.9012'

BRAND <- c('Brand1', 'Brand1', 'Brand2', 'Brand2', 'Brand3', 'Brand3', 'Brand3', 'Brand4')
YEAR <- c(2015, 2016, 2015, 2016, 2015, 2016, 2017, 2015)
EUR <- c(10, 20, 30, 40, 50, 60, 70, 80)
df <- data.frame(BRAND, YEAR, EUR)

df %>% group_by(BRAND) %>%
  mutate(pChange = (EUR - lag(EUR))/lag(EUR) * 100)
#> # A tibble: 8 x 4
#> # Groups:   BRAND [4]
#>   BRAND   YEAR   EUR pChange
#>   <fct>  <dbl> <dbl>   <dbl>
#> 1 Brand1  2015    10    NA  
#> 2 Brand1  2016    20   100  
#> 3 Brand2  2015    30    NA  
#> 4 Brand2  2016    40    33.3
#> 5 Brand3  2015    50    NA  
#> 6 Brand3  2016    60    20  
#> 7 Brand3  2017    70    16.7
#> 8 Brand4  2015    80    NA
```
<sup>Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
