### ISSUE TITLE
Add a version of 'mutate()' that only applies to rows satisfying a condition

### ISSUE THREAD

**Issue by paulponcet** [tidyverse/dplyr#4315]
This relates to the locked issue #425. 
Would you accept a PR for the following function, which applies only to a subset of rows defined by '.condition'? 

    mutate_which <- function(.data, .condition, ...) {
      .condition <- rlang::enquo(.condition)
      i <- rlang::eval_tidy(.condition, .data)
      dots <- quos(...)
      n <- setdiff(names(dots), names(.data))
      .data[, n] <- NA
      .data[which(i), ] <- dplyr::mutate(.data[which(i), ], ...)
      .data
}

**Comment by romainfrancois** [comment]
This should rather be incubated in another package.
