### ISSUE TITLE
Get warinig in install.packages("polyPK") : package ‘‘polyPK’ is not available (for R Under development)

### ISSUE THREAD

**Issue by hanyroze** [tidyverse/dplyr#4318]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by batpigandme** [comment]
It sounds like this is an issue with a different package. So, it's not something we can fix in dplyr.
https://CRAN.R-project.org/package=polyPK 

This sort of question is a better fit for https://community.rstudio.com or stackoverflow.com 

Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
