### ISSUE TITLE
Fix PROTECT issues

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#4333]
From Tomas Kalibera:

---

please have a look at PROTECT bug reports from rchk for your package. This one is a real bug:

Function child_env(SEXPREC*)
  [UP] calling allocating function Rf_eval with argument allocated using Rf_lang3(S:new.env,?,?) dplyr/src/utils.cpp:15

In the following,
Rf_eval(Rf_lang3(symbols::new_env, Rf_ScalarLogical(TRUE), parent), R_BaseEnv)

the result of Rf_lang3 needs to be protected before being passed to Rf_eval.

The remaining ones may be real bugs or at least things that robust code might want to prevent.

Rchk is complaining about things like

return structure_filter(gdf, group_indices, quo.env()) ;

where an unprotected SEXP (result of quo.env()) is passed to structure_filter; I guess that probably quo.env() would usually be protected indirectly via the quosure, but the getter is implemented in another package, implementation seems pluggable via function pointers, so perhaps one could also protect explicitly. Certainly defensive programs would do so.

Similarly, rchk is complaining about

is_column_impl(val, column, false))

possibly destroying "val", which comes from quo_get_expr.

**Comment by romainfrancois** [comment]
I think this was fixed, but I'll triple check before submitting `0.8.1`

**Comment by romainfrancois** [comment]
This is definitely fixed in the 0.8.1 release candidate. https://builder.r-hub.io/build/SUCCESS/dplyr_0.8.1.tar.gz-971d2596bb5848f586457c3746b8b796/2019-04-30T13:04:11Z
