### ISSUE TITLE
progress_estimated: Error: No more ticks - change to warning?

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#4335]
If using `progress_estimated` in a map statement and it hits it's max ticks (because for some reason you ticked one early or miscounted) it generates an error and kills the map, causing all the work to be lost before it gets assigned.  This is a pretty minor reason to kill a map loop and has the potential to lose a lot of work (20,000 geocodes that cost money in my case).

Might I suggest the "Error: No more ticks" be downgraded to a warning?

**Comment by romainfrancois** [comment]
Maybe using a progress bar from the progress package would be better: https://github.com/r-lib/progress
