### ISSUE TITLE
dense_rank() can be simplified

### ISSUE THREAD

**Issue by bkmontgom** [tidyverse/dplyr#4352]
dense_rank() doesn't need the initial ranking:
```r
# Old
dense_rank <- function(x) {
  r <- rank(x, na.last = "keep")
  match(r, sort(unique(r)))
}
# New
dense_rank <- function(x) {
  match(x, sort(unique(x)))
}
```
I can't find a counter-example.

**Comment by romainfrancois** [comment]
Have you tried to change it in the code and run `devtools::check()` perhaps one of the unit test would show the reason for this.
