### ISSUE TITLE
Possible bug with ft_bucketizer and ft_binarizer: Error: `call` must be a quoted call

### ISSUE THREAD

**Issue by abirasathiy** [tidyverse/dplyr#4353]
I am trying to use the ft_bucketizer function with sparklyr. I'm using RStudio 3.5.1, dplyr package 0.8.0.1 and sparklyr package 0.8.4. Here is my code below: 

```
data(iris)
iris_as <- copy_to(sc, iris)
iris_ft <- iris_as %>% ft_binarizer(input_col = 'Sepal_Length', output_col = 'Sepal_Length_Bin', threshold = 5)
```

After running the code, I get the following error: 

`
Error: `call` must be a quoted call

Call `rlang::last_error()` to see a backtrace
> rlang::last_error()

<error>
message: `call` must be a quoted call
class:   `rlang_error`
backtrace:
  1. sparklyr::ft_binarizer(...)
 10. sparklyr:::ml_new_stage_modified_args()
 11. rlang::lang_name(caller_frame)
 13. rlang::call_name(lang)
 14. rlang:::abort_call_input_type("call")
 15. sparklyr::ft_binarizer(...)
Call `rlang::last_trace()` to see the full backtrace

> rlang::last_trace()
     █
  1. └─`%>%`(...)
  2.   ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  3.   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  4.     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5.       └─global::`_fseq`(`_lhs`)
  6.         └─magrittr::freduce(value, `_function_list`)
  7.           ├─base::withVisible(function_list[[k]](value))
  8.           └─function_list[[k]](value)
  9.             ├─sparklyr::ft_binarizer(...)
 10.             └─sparklyr:::ft_binarizer.tbl_spark(...)
 11.               └─sparklyr:::ml_new_stage_modified_args()
 12.                 ├─base::sub("\\..*$", ".spark_connection", rlang::lang_name(caller_frame))
 13.                 └─rlang::lang_name(caller_frame)
 14.                   └─rlang::call_name(lang)
 15.                     └─rlang:::abort_call_input_type("call")`

**Comment by romainfrancois** [comment]
This looks like a `sparklyr` issue, please open it here instead: https://github.com/rstudio/sparklyr/issues

Also, using the `reprex` package will format the issue better.
