### ISSUE TITLE
mutate_at: how to force inclusion of name even when not needed?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/dplyr#4356]
When one use a named function, `mutate_at()` has a different behaviour whether there is one or multiple input variables:

* if one input variable: do not append name (i.e. behave like `mutate()`)
* if more than one input variable: append name

This can surprise users (see stack question [dplyrmutate-at-behaves-like-mutate-when-fed-a-single-variable](https://stackoverflow.com/questions/49588197/dplyrmutate-at-behaves-like-mutate-when-fed-a-single-variable)) and creates a complication as function writer needs to know ex-ante if one or multiple inputs. 

It would be great also if documentation could be clearer on this?

* Reading the three cases, this situation does not fall in case 1 or 2, so user can reasonably expect case 3 to happen (*otherwise in the most general case, the created names are created by concatenation*)
* Documentation mentions: *To force inclusion of a name, even when not needed, name the input (see examples for details)*. But this does not seem to work, and there is no example about this specifically?

Thanks!

**Comment by romainfrancois** [comment]
One might use e.g. `vars(c(a = "a"))` :

``` r
library(dplyr, warn.conflicts = FALSE)
x <- tibble("a" = 1:3, "b" = 4:6)
f <- function(y){2L * y}

x %>% mutate_at(vars(c("a", "b")), list(x = f))
#> # A tibble: 3 x 4
#>       a     b   a_x   b_x
#>   <int> <int> <int> <int>
#> 1     1     4     2     8
#> 2     2     5     4    10
#> 3     3     6     6    12

x %>% mutate_at(c("a"), list(x = f))
#> # A tibble: 3 x 3
#>       a     b     x
#>   <int> <int> <int>
#> 1     1     4     2
#> 2     2     5     4
#> 3     3     6     6
x %>% mutate_at(c(a = "a"), list(x = f))
#> # A tibble: 3 x 3
#>       a     b   a_x
#>   <int> <int> <int>
#> 1     1     4     2
#> 2     2     5     4
#> 3     3     6     6
```

**Comment by MatthieuStigler** [comment]
great, that does the trick, thanks!

**Comment by MatthieuStigler** [comment]
oops, I talked too fast: what if we are using tidyselect helpers likes `contains()`? It seems it won't work? I found a hack with `colnames(x)[matches("a", vars = colnames(x))] ` but I guess that not the recommended way to do it?

``` r
library(dplyr, warn.conflicts = FALSE)
x <- tibble("a" = 1:3, "b" = 4:6)
f <- function(y){2L * y}

x %>% mutate_at(c(a="a"), list(x = f))
#> # A tibble: 3 x 3
#>       a     b   a_x
#>   <int> <int> <int>
#> 1     1     4     2
#> 2     2     5     4
#> 3     3     6     6
x %>% mutate_at(vars(contains("a")), list(x = f))
#> # A tibble: 3 x 3
#>       a     b     x
#>   <int> <int> <int>
#> 1     1     4     2
#> 2     2     5     4
#> 3     3     6     6

inp <- colnames(x)[matches("a", vars = colnames(x))] 
names(inp) <-  inp
x %>% mutate_at(inp, list(x = f))
#> # A tibble: 3 x 3
#>       a     b   a_x
#>   <int> <int> <int>
#> 1     1     4     2
#> 2     2     5     4
#> 3     3     6     6
```

<sup>Created on 2019-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
Here's a way using `tidyselect::vars_select()` manually. 

``` r
library(dplyr, warn.conflicts = FALSE)

x <- tibble("a" = 1:3, "b" = 4:6)
f <- function(y){2L * y}

tidyselect::vars_select(names(x), contains("a"))
#>   a 
#> "a"

x %>% 
  mutate_at(tidyselect::vars_select(names(.), contains("a")), list(x = f))
#> # A tibble: 3 x 3
#>       a     b   a_x
#>   <int> <int> <int>
#> 1     1     4     2
#> 2     2     5     4
#> 3     3     6     6
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by MatthieuStigler** [comment]
awesome, question solved now, merci Francois!
