### ISSUE TITLE
join on factor fields having different levels

### ISSUE THREAD

**Issue by jangorecki** [tidyverse/dplyr#4359]
It would be nice (and probably much faster) if joining data.frames on a factor columns will handle different levels internally. It is now handled by coercing to character, which I believe is sub-optimal.
```r
library(dplyr)
d1 = data.frame(id=as.factor(c("a","b","c")))
d2 = data.frame(id=as.factor(c("c","d")))
inner_join(d1, d2, by="id")
#  id
#1  c
#Warning message:
#Column `id` joining factors with different levels, coercing to character vector 
```

**Comment by romainfrancois** [comment]
This is likely to be considered as part of the 0.9.* series, following guidelines from `vctrs`: 

``` r
vctrs::vec_c(as.factor(c("a","b","c")), as.factor(c("c","d")))
#> [1] a b c c d
#> Levels: a b c d
```

<sup>Created on 2019-05-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by krlmlr** [comment]
I'm rather fond of the current behavior -- factors with different levels are usually worth a second look. I agree that we should make it easier to align the factor levels -- maybe a wrapper around `fct_unify()` ?

**Comment by hadley** [comment]
We're moving towards consistent behaviour across the tidyverse, so we'll have to make some compromises. I don't think we need a separate issue to track this.

**Comment by jangorecki** [comment]
@hadley so maybe at least an option to print that message to STDOUT instead of STDERR?
