### ISSUE TITLE
group_by mutually compatible conditions

### ISSUE THREAD

**Issue by jackdolgin** [tidyverse/dplyr#4365]
Is it possible to group_by mutually compatible (not mutually exclusive) parameters before applying summarize, and/or would that be an addition that you'd consider worthwhile? [This stackoverflow post](https://stackoverflow.com/questions/33421531/adding-another-grouping-with-dplyr) asks a similar question, and I've posted a repex below (I realize this specific repex could be worked-around in other ways, but it's just for the general idea):

```r
library(dplyr)
mtcars %>%
    group_by(mpg > 20, mpg > 25, mpg > 30, add = TRUE) %>%
    summarise(totals = n())
# group_by: 3 grouping variables (mpg > 20, mpg > 25, mpg > 30)
# summarise: now 4 rows and 4 columns, 2 group variables remaining (mpg > 20, mpg > 25)
# A tibble: 4 x 4
# Groups:   mpg > 20, mpg > 25 [3]
  `mpg > 20` `mpg > 25` `mpg > 30` totals
  <lgl>      <lgl>      <lgl>       <int>
1 FALSE      FALSE      FALSE          18
2 TRUE       FALSE      FALSE           8
3 TRUE       TRUE       FALSE           2
4 TRUE       TRUE       TRUE            4
```

**Comment by romainfrancois** [comment]
I'm not sure I follow what you mean, what about something like : 

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>%
  group_by(mpg = cut(mpg, c(0, 20, 25, 30, 35))) %>%
  summarise(totals = n())
#> # A tibble: 4 x 2
#>   mpg     totals
#>   <fct>    <int>
#> 1 (0,20]      18
#> 2 (20,25]      8
#> 3 (25,30]      2
#> 4 (30,35]      4
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jackdolgin** [comment]
Sorry, I should have been more specific. I was hoping for an output like the following:
(Note the total in the created column, 42, is greater than the total number of rows in mtcars, 32); it's like saying, treat each group_by independently, which might result in a number/mpg being classified in more than one group_by category and therefore getting counted twice

```
library(dplyr)
mtcars %>%
    group_by(mpg > 20, mpg > 25, mpg > 30, add = TRUE) %>%
    summarise(totals = n())
# group_by: 3 grouping variables (mpg > 20, mpg > 25, mpg > 30)
# summarise: now 4 rows and 4 columns, 2 group variables remaining (mpg > 20, mpg > 25)
# A tibble: 4 x 4
# Groups:   mpg > 20, mpg > 25 [3]
  `mpg > 20` `mpg > 25` `mpg > 30` totals
  <lgl>      <lgl>      <lgl>       <int>
1 FALSE      FALSE      FALSE          18
2 TRUE       FALSE      FALSE           14 # instead of 8
3 TRUE       TRUE       FALSE           6 # instead of 2
4 TRUE       TRUE       TRUE            4 # instead of 4
```

**Comment by romainfrancois** [comment]
I see. As far as `group_by()` is concerned, a row can only be in one group. You'd have to define your own modified version of `group_by()`. The strapgod package does something like that (for a different purpose though). 

Something like that: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

thresholds <- c(0, 20, 25, 30)
indices <- map(thresholds, ~which(mtcars$mpg > .))

df <- new_grouped_df(mtcars, 
  tibble(threshold = paste0("mpg > ", thresholds), .rows := indices)
)
df %>% summarise(totals = n())
#> # A tibble: 4 x 2
#>   threshold totals
#>   <chr>      <int>
#> 1 mpg > 0       32
#> 2 mpg > 20      14
#> 3 mpg > 25       6
#> 4 mpg > 30       4
```

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
