### ISSUE TITLE
`arrange(-x)` not working as I expect with `integer64` class

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#4366]
I get `integer64` columns when collecting from a postgresql databsewith *dplyr*/*dbplyr*, `arrange(x)` and `arrange(desc(x))` work as expected on these columns, but `arrange(-x)` doesn't.

See below : 

``` r
library(dplyr,warn.conflicts = FALSE)
df1 <- data.frame(x = letters[1:3], y = c(1,3,2))

identical(arrange(df1, -y), arrange(df1, desc(y)))
#> [1] TRUE

df1$y <- bit64::as.integer64(df1$y)
identical(arrange(df1, -y), arrange(df1, desc(y)))
#> [1] FALSE

# not what I expect
arrange(df1, -y)
#>   x y
#> 1 a 1
#> 2 b 3
#> 3 c 2
```

<sup>Created on 2019-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by moodymudskipper** [comment]
Another issue with `integer64`, with *tidyr* but these might stem from the same issue so I'll put it here. When using `spread`, instead of `NA` we find the value  `9218868437227407266`: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
data.frame(id = c(1,2,2), key = c("a","a","b"), value = 1:3) %>% 
  mutate(value = bit64::as.integer64(value)) %>%
  tidyr::spread(key, value)
#>   id a                   b
#> 1  1 1 9218868437227407266
#> 2  2 2                   3
```

<sup>Created on 2019-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
Eventually (after https://github.com/r-lib/vctrs/issues/348, for version 0.9.*) we should be able to use `vec_order()`. I'll put a workaround in for 0.8.2
