### ISSUE TITLE
installation error ubuntu 18.04 mutate.cpp

### ISSUE THREAD

**Issue by artidata** [tidyverse/dplyr#4371]
Hi, I am having an installation issue. When I am using packrat::restore(), most packages are installing smoothly, in an instant. When it starts installing dplyr, I have waited for 2 hours, the installation is not completed, and I decide to force stop the program. This keeps happening after multiple tries of removing and and retrieving the repository.

I set packrat option for package installation, quiet = F, it still happens, and the last peace I seen is always mutate.cpp. Here is the message:

```
C/usr/lib/R/etc/Makeconf:176: recipe for target 'mutate.o' failed                                                                                                           
make: *** [mutate.o] Interrupt                                                                                                                                                 
ERROR: compilation failed for package 'dplyr'
```
I am using ubuntu-bionic-18.04-amd64-server, any help is greatly appreciated.

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
