### ISSUE TITLE
Is the tidyverse packages owned by company that makes Rstudio ?

### ISSUE THREAD

**Issue by anuj2054** [tidyverse/dplyr#4377]
Just asking this question. 

Is the tidyverse packages owned by company that makes Rstudio ?

Or is it just an independent project still owned by Hadley.

**Comment by batpigandme** [comment]
Here's the info on authorship and corporate sponsorship from DESCRIPTION:
https://github.com/tidyverse/dplyr/blob/d13c66a801de79f3cc40c9d131de87d6db7c0f54/DESCRIPTION#L5-L11

For more detail see the DESCRIPTION section of Writing R Extensions:
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file
