### ISSUE TITLE
select_if doesn't work if a column in the tibble is named "i"

### ISSUE THREAD

**Issue by alejandroschuler** [tidyverse/dplyr#4380]
This one took me a few minutes to track down... It appears that if a column in the tibble is named `i`, `select_if` will fail. This also applies to `mutate_if` and possibly others.

```r
packageVersion("dplyr")
[1] ‘0.8.1’

iris %>% 
rename(i=Sepal.Length) %>% 
select_if(is.numeric)

Error in tibble_vars[[i]] : 
  attempt to select more than one element in vectorIndex
```

**Comment by barryrowlingson** [comment]
works for me in 0.8.0.1, so I upgraded and now its broken in 0.8.1.

**Comment by JohnMount** [comment]
Silent data corruption variation of the issue.

```r
packageVersion("dplyr")
# [1] ‘0.8.1’
dplyr::select_if(data.frame(i = 2, j = "a"), is.numeric)
# data frame with 0 columns and 1 row
```

**Comment by cderv** [comment]
This come from the internal  `dplyr:::tbl_if_vars`, here is a reprex.

``` r
library(dplyr, warn.conflicts = FALSE)


.tbl <- iris %>% 
  rename(i = Sepal.Length)

.predicate <- dplyr:::as_fun_list(is.numeric, caller_env())
vars <- dplyr:::tbl_if_vars(.tbl, .predicate, caller_env(), .include_group_vars = TRUE)
#> Error in tibble_vars[[i]]: attempt to select more than one element in vectorIndex
```

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

There is a for if loop with `i` as iterator variable. I guess tidy eval is mixing things up. I'll dig a bit more ans see what I can find.

**Comment by romatik** [comment]
@cderv, you are right, the error is there. I suggest that this can be fixed like this:

```
  for (i in seq_len(n)) {
    selected[[i]] <- eval_tidy(quo(.p(.tbl[[tibble_vars[[!!i]]]], ...)), mask)
  }
```

This corresponds to this line:
https://github.com/tidyverse/dplyr/blob/d13c66a801de79f3cc40c9d131de87d6db7c0f54/R/colwise.R#L209

**Comment by cderv** [comment]
Thanks @romatik for chiming in! 
I planned initially to look for a fix tonight - glad to know it has been handled! 😊👍
