### ISSUE TITLE
accessing column names in list approach inside function not working with 0.8.1

### ISSUE THREAD

**Issue by madmark81** [tidyverse/dplyr#4383]
the following code worked fine in 0.8.0.1, but in 0.8.1 it print dots instead of the column names
I used to access the column names to print them inside sweetalerts during long calculations to keep the user of my shiny app up to date of progress

```r
funx <- function(x) {
    print(substitute(x))
    multires <- multimode::modetest(x, method = 'SI') 
    p <- multires$p.value
}
mtcars %>% 
    select(1:2) %>%
    summarise_all(list(~funx(.)))
```

Is there a new way to achieve the desired result?

**Comment by romainfrancois** [comment]
The way lambdas (formulas using `.`) works has changed slightly. You can use a non lambda form if you want that. 

``` r
library(dplyr, warn.conflicts = FALSE)
funx <- function(x) {
  print(substitute(x))
  multires <- multimode::modetest(x, method = 'SI') 
  p <- multires$p.value
}
mtcars %>% select(1:2) %>% summarise_all(list(funx))
#> mpg
#> cyl
#>     mpg  cyl
#> 1 0.696 0.21
mtcars %>% select(1:2) %>% summarise_all(funx)
#> mpg
#> cyl
#>     mpg   cyl
#> 1 0.716 0.242
mtcars %>% select(1:2) %>% summarise_all(~funx(.))
#> .
#> .
#>     mpg  cyl
#> 1 0.716 0.29
mtcars %>% select(1:2) %>% summarise_all(list(~funx(.)))
#> .
#> .
#>     mpg  cyl
#> 1 0.712 0.21
```

btw, in the future it's best to use the `reprex` package, so that the code has nice syntax highlighting here as well as the observed results so that we can see what happens at a glance.

**Comment by madmark81** [comment]
many thanks for the answer!
