### ISSUE TITLE
Confusing error with new version summarise_all

### ISSUE THREAD

**Issue by madmark81** [tidyverse/dplyr#4388]
A follow up on my previous issue concerning change in syntax which was related to lamda form 
I tried the new approach, but now I get errors on running basic formulas such as trying to sample ```x```  

What do I need to do to access the numbers as vector? 

previous issue: [https://github.com/tidyverse/dplyr/issues/4383](url)
```r
library(dplyr)
AutoselectEValuation <- function(x) { 
    
    ## needs to be expanded with custom formula
    print(substitute(x))
    print(length(x))
    D_sample <- sample(x, size = 10, replace = FALSE) 
}

mtcars %>%
    select_if(is.numeric) %>% 
    summarise_all(list(AutoselectEValuation))

mpg
[1] 32
Error: Column `mpg` must be length 1 (a summary value), not 10

```

**Comment by hadley** [comment]
Could you please start by reworking your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

Then describe what exactly you are trying to achieve.

**Comment by madmark81** [comment]
Sorry hadley, I figured out why I got the error. I forgot to generate a single value output at the end of my function, and summarise_all wants either that, or a list(tibble( ... )) output which I forgot. Combination of being fairly new to dplyr plus previous code made with version 0.8.0.1 is driving me crazy a bit
