### ISSUE TITLE
Proposal for an infill_join operator

### ISSUE THREAD

**Issue by danielecook** [tidyverse/dplyr#4395]
I propose a new `infill_join` function which would be beneficial for merging datasets or comparing / diffing datasets.

The operator would work by combining a second dataset by row and column and fill in missing values present in that second dataset. Two optional arguments would be:

* `by` - Specifies the columns to use as a row-based key to match on.
* `existing` - Default="ignore"; Specifies how value collisions are handled. Can be set to either `ignore` (the default), `replace` to replace values with the dataset being merged, or the idea of cataloging differences can be explored with a `mark` or similar option. A list of value collisions could be produced following the join.

### Why an `infill_join` function?

* Datasets are often handled by multiple systems or programs which produce similar outputs  but may have incomplete or missing information. For example, a laboratory management system and a medical electronic records system.
* Datasets often change over time; This operator would be helpful for updating older datasets and/or identifying problems such as missing.
* Few `diff` tools exist in R.

### Example

`orig_dataset`

| car               | mpg   | disp   |
|:------------------|:------|:-------|
| Mazda RX4         | 21    | NA     |
| Mazda RX4 Wag     | 21    | 160    |
| Datsun 710        | NA    | 108    |
| Hornet 4 Drive    | 21.4  | NA     |
| Hornet Sportabout | 18.7  | 360    |
| Valiant           | 18.1  | 225    |
| Duster 360        | 14.3  | NA     |
| Merc 240D         | 24.4  | 146.7  |
| Merc 230          | NA    | 140.8  |

`df_mtcars_updated`

| car            |   mpg |   cyl |   disp |
|:---------------|------:|------:|-------:|
| Mazda RX4      |  3000   |     6 |  160   |
| Datsun 710     |  22.8 |     4 |  108   |
| Hornet 4 Drive |  21.4 |     6 |  258   |
| Duster 360     |  14.3 |     8 |  360   |
| Merc 230       |  22.8 |     4 |  140.8 |

```r
orig_dataset %>% dplyr::infill_join(df_mtcars_updated, by="car")
```

##### Output

| car               |   mpg |   disp | cyl   |
|:------------------|------:|-------:|:------|
| Mazda RX4         | _21_   | __160__   | __6__     |
| Mazda RX4 Wag     |  21   |  160   | NA  |
| Datsun 710        |  __22.8__ |  108   | __4__     |
| Hornet 4 Drive    |  21.4 |  __258__   | __6__     |
| Hornet Sportabout |  18.7 |  360   | NA  |
| Valiant           |  18.1 |  225   | NA  |
| Duster 360        |  14.3 |  __360__   | __8__     |
| Merc 240D         |  24.4 |  360   | NA  |
| Merc 230          |  __22.8__ |  140.8 | __4__     |

* Bolded values have been filled in from the `df_cars_updated` dataframe.
* Note that the Mazda RX4 mpg=3000 value is ignored (in italics)
* The `cyl` column has been added

### Example 2

Using the same `orig_dataset`, but a slightly different dataset (`df_mtcars_updated_2`), and using some crazy numbers so this is easier to see.

`df_cars_updated_2`:

| car           |    mpg |   disp |
|:--------------|-------:|-------:|
| Mazda RX4     |   5000 |      0 |
| Mazda RX4 Wag |  10000 |    160 |
| Datsun 710    | 100000 |    108 |

```
orig_dataset %>% dplyr::infill_join(df_cars_updated2, existing="replace")
```
##### Output

| car               | mpg    | disp   |
|:------------------|:-------|:-------|
| Mazda RX4         | __5000__   | __0__      |
| Mazda RX4 Wag     | __10000__  | 160    |
| Datsun 710        | __100000__ | 108    |
| Hornet 4 Drive    | 21.4   | NA     |
| Hornet Sportabout | 18.7   | 360    |
| Valiant           | 18.1   | 225    |
| Duster 360        | 14.3   | NA     |
| Merc 240D         | 24.4   | 146.7  |
| Merc 230          | NA     | 140.8  |

**Comment by romainfrancois** [comment]
At the moment we are going to enter a phase where we are going to both simplify existing code in dplyr to lower its use of C++ internals and leverage changes to `vctrs`. 

I'd suggest this is done in a separate package, at least to incubate the idea.

**Comment by moodymudskipper** [comment]
@danielecook I use a `conflict` argument in *safejoin* functions, which allow to provide a behavior in case of columns present in both lhs and rhs. It will handle your case with `conflict = "patch"`. Functions are wrappers around dplyr functions : 

https://github.com/moodymudskipper/safejoin
