### ISSUE TITLE
Is dplyr::arrange guaranteed to be stable for equivalent/NA values?

### ISSUE THREAD

**Issue by LukeGoodsell** [tidyverse/dplyr#4409]
For a given set of inputs - some with NAs or other equivalent values - is it the case that dplyr::arrange will produce stable output, or are there other uncontrolled factors that may result in different ordering of the output?

E.g. would the following always produce the same output?

```r
library("dplyr")
df <-
  tribble(
    ~colA, ~colB, ~colC,
    "A", "orange", 5,
    "B", "orange", 4,
    "C", "orange", 4,
    "D", "yellow", NA,
    "E", "orange", 5,
    "F", "yellow", NA,
    "G", "yellow", NA
  )

df %>%
  group_by(colB) %>%
  arrange(colC) %>%
  filter(row_number() == 1) %>%
  ungroup()

# # A tibble: 2 x 3
#   colA  colB    colC
#   <chr> <chr>  <dbl>
# 1 B     orange     4
# 2 D     yellow    NA
```

**Comment by romainfrancois** [comment]
yes, please find an issue showing symptoms if you see otherwise.
