### ISSUE TITLE
group_map: when calling function ungroup the dataframe passed to it

### ISSUE THREAD

**Issue by matheus-donato** [tidyverse/dplyr#4411]
when using

```{r}
fn <- function(df,x) { df %>% ungroup() %>% ... }
df %>% group_by(col) %>% group_map(fn)
```

suggestions:

* the `df` passed to fn foir every group should already be ungrouped, as there is no point in it being grouped within fn, other than forcing us to always type ungroup() as in the above
* the 2nd arg passed by group_map to fn (`x` above) should *not* be a dataframe of the constant group key, but just the key itself, as a scalar.

**Comment by romainfrancois** [comment]
Can you share a reprex that illustrate the first • ? e.g. do you see something different to this: 

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  group_by(cyl, am) %>% 
  group_map(~ is_grouped_df(.x))
#> [[1]]
#> [1] FALSE
#> 
#> [[2]]
#> [1] FALSE
#> 
#> [[3]]
#> [1] FALSE
#> 
#> [[4]]
#> [1] FALSE
#> 
#> [[5]]
#> [1] FALSE
#> 
#> [[6]]
#> [1] FALSE
```

**Comment by romainfrancois** [comment]
The second • is not possible, tibbles might be grouped by more than one variables, structuring `.y` in a data frame makes it consistent.

**Comment by romainfrancois** [comment]
Closing this now, please reopen if/when you can show the problem with a reprex.
