### ISSUE TITLE
Provide a more informative error with summarise_all

### ISSUE THREAD

**Issue by Nelson-Gon** [tidyverse/dplyr#4412]
I was working on something that is reproducible as follows:

```
dplyr vesrsion dplyr 0.8.1

R version 3.5.3

```

**Reproducible Data**
```
df<-structure(list(A = c(NA, 3.2, 3.1, NA, NA, 2, 1, 3.2, 3.1, 1, 
2, 5, 2, NA, NA, NA, NA, 2, 3.1, 1), B = c(NA, 3.1, 3.1, NA, 
NA, 2, 1, 4, 3.1, 1, NA, 5, 3.1, 3.2, 2, 3.1, NA, 2, 3.1, 1), 
    C = c(NA, NA, 3.1, NA, NA, 3.2, 1, 4, NA, 1, NA, NA, 3.2, 
    NA, 2, 3.2, NA, NA, 2, 1), D = c(NA, NA, 3.1, NA, NA, NA, 
    1, 4, NA, 1, NA, NA, NA, 4, 2, NA, NA, NA, 2, 1), E = c(NA, 
    NA, 2, NA, NA, NA, 1, 5, NA, NA, NA, NA, 3.2, NA, 2, 3.2, 
    NA, NA, 2, 1)), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
-20L))

```

**Aim**: Summarise all variables to obtain the sum of values equal to a given number(strictly dplyr). 

**Code**:
````
df %>%
rowid_to_column() %>%
mutate_all(function(x) isna=ifelse(is.na(x) & !is.na(lag(x)),1,0)) %>%
summarise_all(sum(.==1))

````

The above fails with the error:

>Error: not expecting this
Call `rlang::last_error()` to see a backtrace

**Suggestion**:

I would like to suggest that a more informative error be provided. For instance, this error could be due to syntax violation in which case it would be more useful to provide the user with a message that tells them to review their syntax.  Apologies if this issue was already raised, could not readily find one.

**Comment by romainfrancois** [comment]
what is `rowid_to_column` ? Please use the [reprex](https://reprex.tidyverse.org) package to prepare reproducible examples, you might also like @MilesMcBain's [datapasta](https://github.com/MilesMcBain/datapasta) 📦 to prepare human readable data dumps. 

Also, I believe this error you mentioned has a different wording in the dev version, please try that.

**Comment by Nelson-Gon** [comment]
Sorry that my issue was not immediately reproducible, I have not used `reprex` before. 

`row_id_to_column` is from `tibble` part of the `tidyverse`. I used the developer version and it seems to give a different error. Sorry for not having checked this earlier.

>Error: expecting a one sided formula, a function, or a function name.
