### ISSUE TITLE
Suppress "Column `...` must be length 1 (a summary value), not ..."

### ISSUE THREAD

**Issue by deliciouslytyped** [tidyverse/dplyr#4418]
Would it be possible to add a feature for suppressing the error in the title for `summarise`?

Maybe I just haven't figured out the appropriate part of dplyr to use. My use case would be aggregating values in a data structure like a vector so that I can inspect them with R properly later - as opposed to using a hack like making a comma separated string.

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by deliciouslytyped** [comment]
I'll try out this reprex thing in a bit.
Here's a quick reproduction I threw together by hand:
```R
library(dplyr)
library(ggplot2)
mpg %>% group_by(model) %>% summarise(year=as.vector(year))
```
results in
```
Error in summarise_impl(.data, dots) : 
  Column `year` must be length 1 (a summary value), not 6
```

**Comment by krlmlr** [comment]
`summary()` really requires a scalar for each group. Are you looking for `nest(-model)` ?

``` r
library(tidyverse)
mpg %>%
  nest(-model)
#> # A tibble: 38 x 2
#>    model              data              
#>    <chr>              <list>            
#>  1 a4                 <tibble [7 × 10]> 
#>  2 a4 quattro         <tibble [8 × 10]> 
#>  3 a6 quattro         <tibble [3 × 10]> 
#>  4 c1500 suburban 2wd <tibble [5 × 10]> 
#>  5 corvette           <tibble [5 × 10]> 
#>  6 k1500 tahoe 4wd    <tibble [4 × 10]> 
#>  7 malibu             <tibble [5 × 10]> 
#>  8 caravan 2wd        <tibble [11 × 10]>
#>  9 dakota pickup 4wd  <tibble [9 × 10]> 
#> 10 durango 4wd        <tibble [7 × 10]> 
#> # … with 28 more rows
```

<sup>Created on 2019-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Closing, because this isn't really a problem with dplyr. This sort of question is a better fit for https://community.rstudio.com. Do you mind following up there?
