### ISSUE TITLE
`vec_type2()` and grouped data frames

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#4426]
From r-lib/vctrs#417

I think this is somewhat related to r-lib/vctrs#211, but I'd be curious to collect thoughts on what this should return. I imagine it is straightforward. The second result should be a grouped data frame with all of the grouping columns of `grouped_starwars` maintained?

We think the implementation of this should live in dplyr.

``` r
library(vctrs)
library(dplyr, warn.conflicts = FALSE)

grouped_starwars <- starwars %>% group_by(eye_color)

vec_type2(starwars, starwars)
#> # A tibble: 0 x 13
#> # … with 13 variables: name <chr>, height <int>, mass <dbl>,
#> #   hair_color <chr>, skin_color <chr>, eye_color <chr>, birth_year <dbl>,
#> #   gender <chr>, homeworld <chr>, species <chr>, films <list>,
#> #   vehicles <list>, starships <list>

vec_type2(starwars, grouped_starwars)
#>  [1] name       height     mass       hair_color skin_color eye_color 
#>  [7] birth_year gender     homeworld  species    films      vehicles  
#> [13] starships 
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Response from Lionel:

> I think this should be dealt with in dplyr. Tibble methods will probably live in the tibble repo as well.

**Comment by romainfrancois** [comment]
Sounds about right. not sure about other cases like e.g. `vec_type2(starwars %>% group_by(eye_color), starwars %>% group_by(skin_color)` ...

**Comment by DavisVaughan** [comment]
I imagine it would take the union of the groups since the `vec_type2()` of two data frames holds the union of their columns, and with two factors you have the union of their levels

``` r
library(vctrs)
library(dplyr, warn.conflicts = FALSE)

vec_type2(cars, iris)
#> [1] speed        dist         Sepal.Length Sepal.Width  Petal.Length
#> [6] Petal.Width  Species     
#> <0 rows> (or 0-length row.names)

vec_type2(factor("a"), factor("b"))
#> factor(0)
#> Levels: a b
```

<sup>Created on 2019-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
@lionel- is now working on this, and in the interim the code will live in vctrs.

**Comment by lionel-** [comment]
Given the new insights about the grouped-df class, I'm no longer sure we can separate the vctrs methods from the constructors.
