### ISSUE TITLE
dplyr::filter freezes RStudio

### ISSUE THREAD

**Issue by arider2** [tidyverse/dplyr#4440]
---

Hello,

I've been encountering a strange issue with dplyr::filter.

RStudio freezes when I try to execute code like that shown below...

```r
people <- data.frame(age = c(12, 40, 9, 37, 88, 24, 71, 19),
                     fav_colour = c("green", "red", "blue", "red", "orange", "yellow", "purple", "blue"),
                     fav_food = c("pizza", "burger", "chocolate", "pie", "pineapple", "pizza", "burrito","pie"),
                     num_siblings = c(1, 1, 0, 4, 0, 2, 1, 3))
rownames(people) <- paste("Person", rownames(people), sep = "_")

people2 <- people %>% filter(num_siblings == 1)
```

When I try to execute the filtering part of the code above (where the data frame people2 is being created) RStudio freezes and can only be closed in task manager.
The weird part is I don't even have to hit enter, just typing this, for example...

```r
people2 <- people %>% filter()
```

...causes RStudio to freeze. 

The other frustrating thing is that this doesn't always happen. It can work fine for a while and then just stop working. I've tried loading and unloading different packages but this doesn't seem to have an effect on the frequency of this bug. There doesn't seem to be any rhyme or reason to it.

I've tried uninstalling and reinstalling dplyr and Rcpp but this hasn't helped. 

This is my R version information:

```r
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo  
```

My RStudio version is 1.1.463.

Any help would be appreciated, and if you don't think this is an issue with dplyr then feel free to tell me off.

Thank you!

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there (especially helpful since this sounds like it might be IDE-related)?
