### ISSUE TITLE
"NAs introduced by coercion" even though this replacement is desired

### ISSUE THREAD

**Issue by urskalbitzer** [tidyverse/dplyr#4442]
---
I am cleaning up tables where different codes are used for NA values. Therefore, I am using `case_when` in combination with `mutate` to replace these codes by NA. This works well, but I always get the warning "NAs introduced by coercion" even though this is my intention (reprex below).

As a consequence of this warning, I always have to check all NA replacements to make sure that no other values where replaced by NA. Is this warning intentional ?

``` r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(x = c(1, "T"))
mutate(df, x = case_when(x == "T" ~ NA_real_,
                         TRUE ~ as.numeric(x)))
#> Warning in eval_tidy(pair$rhs, env = default_env): NAs introduced by
#> coercion
#> # A tibble: 2 x 1
#>       x
#>   <dbl>
#> 1     1
#> 2    NA
```

<sup>Created on 2019-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by echasnovski** [comment]
This is not a warning from `case_when()`, but from `as.numeric()`:

``` r
library(dplyr, warn.conflicts = FALSE)

# This throws "`NA` coersion" warning
as.numeric(c(1, "T"))
#> Warning: NAs introduced by coercion
#> [1]  1 NA

# If `x` has only "numericish" values, there is no warning
df <- tibble(x = c(1, "2"))
mutate(df, x = case_when(x == "2" ~ NA_real_,
                         TRUE ~ as.numeric(x)))
#> # A tibble: 2 x 1
#>       x
#>   <dbl>
#> 1     1
#> 2    NA
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by urskalbitzer** [comment]
Thanks for your answer, @echasnovski.

I understand that `as.numeric` coerces something like "T" to NA and gives the warning. But that's exactly why I tried to 'manually' coerce  these values (with the first line in `case_when`) into NA so that when `as.numeric` is called, these values are already NA.

My understanding of `case_when` is that, if the last line is `TRUE ~ as.numeric(x)`, this only applies to all x that were not changed in one of the lines above. That's why I don't understand why in my example `as.numeric` ever tries to coerce "T" into a number. At that point, this "T" should have been transformed to NA already.

**Comment by echasnovski** [comment]
Oh, I see your point.
It does seem that `case_when()` evaluates all elements in supplied formulas before computing actual output.

Then, in your case solution might be to divide into two steps recoding values to `NA` and converting column to numeric.

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = c(1, "T"))

# Using `na_if()` to recode certain values to `NA`
df %>% 
  mutate(
    x = na_if(x, "T"),
    x = as.numeric(x)
  )
#> # A tibble: 2 x 1
#>       x
#>   <dbl>
#> 1     1
#> 2    NA

# Using `case_when()` if there is a complex definition of `NA`
df %>% 
  mutate(
    x = case_when(x == "T" ~ NA_character_, TRUE ~ x),
    x = as.numeric(x)
  )
#> # A tibble: 2 x 1
#>       x
#>   <dbl>
#> 1     1
#> 2    NA
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
This is how `case_when()` works, see e.g. this example from `?case_when` : 

```
# case_when() evaluates all RHS expressions, and then constructs its
# result by extracting the selected (via the LHS expressions) parts.
# In particular NaN are produced in this case:
y <- seq(-2, 2, by = .5)
case_when(
  y >= 0 ~ sqrt(y),
  TRUE   ~ y
)
```

**Comment by urskalbitzer** [comment]
Thanks @echasnovski for the solution how to avoid the warning.
And thanks @romainfrancois for the clarification why this warning is shown such situations.
