### ISSUE TITLE
Group consecutively

### ISSUE THREAD

**Issue by jxu** [tidyverse/dplyr#4445]
The idea is to be able to group consecutive rows that have the same values or combination of values. I know dplyr doesn't really focus on row order (what I can think of is `lag` and `lead`) but this may be convenient. 

Example:

````
df <- data.frame(x = c(0, 0, 1, 0), y = c(2, 2, 2, 2))
````

Currently I would do something like 

```
rlel <- rle(df$x)$lengths
df$group <- lapply(1:length(rlel), function(i) rep(i, rlel[i])) %>% unlist 
df
  x y group
1 0 2     1
2 0 2     1
3 1 2     2
4 0 2     3
```

To consider a combination of columns, I think I have to use `group_indices` with `rle`. 

Ideally we have a new function like `df %>% group_consecutive(x, y)`

**Comment by romainfrancois** [comment]
This feels out of scope for dplyr, but other packages have used alternative forms of grouping, e.g. `strapgod` from @DavisVaughan, I suppose one of us could help you when you implement consecutive grouping on another package. 

Closing this here however.
