### ISSUE TITLE
bind_rows drops names of list columns

### ISSUE THREAD

**Issue by rcorty** [tidyverse/dplyr#4446]
I would like to row-bind two tibbles where each has a named list column with the same name.  I believe I'm getting some unexpected behavior, but maybe this is how it's supposed to work -- not totally sure.  I believe this is a separate issue from https://github.com/tidyverse/dplyr/issues/1337, the closest thing I could find in the issues page.

In the below reprex, I would expect `inside_tibble` and `outside_tibble` to be the same.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

l1 <- list(first = 1, second = 2)
l2 <- list(third = 3, fourth = 4)

outside_tibble <- c(l1, l2)

df1 <- tibble(named_list_col = l1)
df2 <- tibble(named_list_col = l2)

inside_tibble <- bind_rows(df1, df2)$named_list_col

outside_tibble
#> $first
#> [1] 1
#> 
#> $second
#> [1] 2
#> 
#> $third
#> [1] 3
#> 
#> $fourth
#> [1] 4

inside_tibble
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2
#> 
#> [[3]]
#> [1] 3
#> 
#> [[4]]
#> [1] 4
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
Names in columns are generally stripped even with the `tibble()` call, I'm kind of surprised that this even works with list columns:

``` r
library(tibble)

x1 <- c(a = 1, b = 2)
l1 <- list(first = 1, second = 2)
df1 <- tibble(named_col = x1, named_list_col = l1)
df1$named_col
#> [1] 1 2
df1$named_list_col
#> $first
#> [1] 1
#> 
#> $second
#> [1] 2
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@hadley: Should `tibble()` remove the names from all vectors via `vec_names<-()` (which currently isn't exported)? Should the validator check that no vector has names (via a new `vec_has_names()` perhaps?)

**Comment by lgaborini** [comment]
This issue also affects `filter`, not only `bind_rows` (but not `mutate`):
``` r
l1 <- list(first = 1, second = 2)
df1 <- tibble(named_list_col = l1)

# Is named
df1
#> # A tibble: 2 x 1
#>   named_list_col
#>   <named list>  
#> 1 <dbl [1]>     
#> 2 <dbl [1]>

# Named
df1 %>% 
   mutate(col = 1:2)
#> # A tibble: 2 x 2
#>   named_list_col   col
#>   <named list>   <int>
#> 1 <dbl [1]>          1
#> 2 <dbl [1]>          2

# Not named
df1 %>% 
   mutate(col = 1:2) %>% 
   filter(col == 1)
#> # A tibble: 1 x 2
#>   named_list_col   col
#>   <list>         <int>
#> 1 <dbl [1]>          1
```

<sup>Created on 2019-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Under the current implementation, this depends on https://github.com/r-lib/vctrs/issues/689

**Comment by hadley** [comment]
Closing since this is now tracked in vctrs, and labelled with dplyr (so we'll definitely deal with it before releasing dplyr
