### ISSUE TITLE
"Programming with dplyr" should include a reference, not just tutorial

### ISSUE THREAD

**Issue by qdread** [tidyverse/dplyr#4447]
I greatly appreciate the documentation and tutorials that you have developed. However, I have noticed something that would improve my user experience. The vignette "Programming with dplyr" was a great introduction to dplyr programming for me. It is the first search result when you Google search for "dplyr nonstandard evaluation" or similar queries. It is an excellent tutorial, but I feel like I have had to search through the tutorial tons of times to get to the "answer" when I just want to quickly refer to the correct syntax for quasiquotation. Would it be possible to create an easily Googleable and concise reference for the correct syntax for quotation and quasiquotation, or perhaps add it to the existing dplyr reference? Thanks very much in advance.

**Comment by jxu** [comment]
For a quick guide this may help https://github.com/rstudio/cheatsheets/blob/master/tidyeval.pdf

**Comment by romainfrancois** [comment]
The programming vignette is being replaced by the tidyeval book from @lionel- and @Hadley. https://tidyeval.tidyverse.org

The vignette will disappear once the book is ready, so currently is no longer being worked on.
