### ISSUE TITLE
Cannot load 'vctrs' package following installation from CRAN

### ISSUE THREAD

**Issue by CSheehan1** [tidyverse/dplyr#4448]
Hi, I'm very new to RStudio and have been unable to install ggplot2 to my library. I believe the problem is I cannot install the dependency "vctrs" package. I have been trying to install this from CRAN, but keep getting the following error that loading has failed. Any advice on how I can fix this would be greatly appreciated. Thanks!

###########################################################
> install.packages("vctrs")
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘vctrs’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘vctrs’

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  402k  100  402k    0     0  1121k      0 --:--:-- --:--:-- --:--:-- 1122k
* installing *source* package ‘vctrs’ ...
** package ‘vctrs’ successfully unpacked and MD5 sums checked
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c compare.c -o compare.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c dictionary.c -o dictionary.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c dim.c -o dim.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c equal.c -o equal.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c fields.c -o fields.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c growable.c -o growable.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c hash.c -o hash.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c init.c -o init.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c types.c -o types.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c unspecified.c -o unspecified.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -L/usr/local/lib -o vctrs.so compare.o dictionary.o dim.o equal.o fields.o growable.o hash.o init.o types.o unspecified.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.2/Resources/library/vctrs/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'vctrs', details:
  call: NULL
  error: 'import' is not an exported object from 'namespace:backports'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/vctrs’
Warning in install.packages :
  installation of package ‘vctrs’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/fx/khbs9n3554l0qn14xgy11n480000gn/T/RtmpdOSX8f/downloaded_packages’
>

**Comment by romainfrancois** [comment]
`vctrs` has its own issues here: https://github.com/r-lib/vctrs/issues. Please open this issue there instead. Or maybe this is a question more suitable for community.rstudio.com ?
