### ISSUE TITLE
Confusing/offensive use of "gender" in `starwars` dataset

### ISSUE THREAD

**Issue by dhicks** [tidyverse/dplyr#4456]
The `starwars` sample dataset includes a `gender` variable, which currently takes 4+1 values:  "female," "male," "hermaphrodite," and "none" (plus NA).  There are two problems with this variable and the way that it is coded.  

The first problem is that the codes refer to characters' biological sex, not their gender.  (For background on the sex/gender distinction, see here:  <https://en.wikipedia.org/wiki/Sex_and_gender_distinction>.)  For example, Jabba the Hutt is consistently referred to using masculine pronouns (he/him/his; see <https://en.wikipedia.org/wiki/Jabba_the_Hutt>).  But Hutts are biologically hermaphroditic, with both male and female sex organs (<https://starwars.fandom.com/wiki/Sexes/Legends>; <https://starwars.fandom.com/wiki/Hutt/Legends>).  So Jabba has a masculine gender, but he's not biologically male.  

Fixing this problem is simply a matter of renaming the variable `sex`; though of course this breaks many examples using the dataset.  

The second problem is that, outside of specifically biological contexts, "hermaphrodite" is an offensive term for intersex people.  Specifically, the term has been used historically to pathologize and medicalize intersex people (see Anne Fausto-Sterling's *Sexing the Body* or this *Daily Beast* piece:  <https://www.thedailybeast.com/dont-call-them-hermaphrodites>).  It also continues to be used to objectify intersex people as sexual curiosities.  For example, many of the top results for a web search of the term are for porn videos; examples can be seen at <https://duckduckgo.com/?q=hermaphrodite&atb=v17&ia=web>, though obviously the results at that link are NSFW.  

While the term is appropriate in the context of describing the sex of Starwars characters, it's easy for this context to be lost when the dataset is used for examples.  The result can be problematic or even outright offensive examples.  (Here's the Twitter thread that prompted me to write up this issue:  <https://twitter.com/danieljhicks/status/1144656643906404352>.  I also want to note that Mara handled this really well!)  

I suggest this second problem can be addressed by switching to adjectival forms.  "Hermaphroditic" carries more technical connotations than the noun form of the term; a web search turns up mostly dictionaries, specifically biological discussions, and discussions of intersex people, without any porn:  <https://duckduckgo.com/?q=hermaphroditic&atb=v17&ia=web>.  The "none" value, which could be confused with NA, could also be replaced with an "asexual" value, which is more descriptive.  (Though potentially confusing in its own way, because that term is also used for a sexual orientation.)

**Comment by batpigandme** [comment]
Hey @dhicks ,

Thanks for writing this up _and_ for the suggestion that would keep the variable names consistent - ideal! It'd be a pretty brittle test if one exists that relies on exact values in this dataset, but it wouldn't be that hard to sweep for those (I don't think). 

@hadley, what do you think about adding this to dev-day issues?

**Comment by dhicks** [comment]
Just remembered that I wrote up a PR for this and #4455 but forgot to actually submit it

**Comment by romainfrancois** [comment]
That could be included as part of #3983, probably also related to https://github.com/phalt/swapi/issues/126.

**Comment by hadley** [comment]
I am a little worried about breaking existing examples. Could we rename the existing `gender` column to `sex` (along with @dhicks' suggested terms) and a new `gender` column that captures the actual gender of the character? (I'm not sure how much research that would involve, and how much is knowable; but it's probably ok even if the column is mostly NA)

**Comment by MeganBeckett** [comment]
Hi! I just picked up this issue at the Tidy Dev Day :)

To confirm, would one need to determine the actual `gender` of each character by researching them or use, by default, what is currently specified in `gender`?

Except for some examples, ie. Jabba, who's sex is hermaphroditic, but gender is probably male? As referenced on Wikipedia: https://en.wikipedia.org/wiki/Jabba_the_Hutt

**Comment by hadley** [comment]
Yeah, you'd need to determine it by doing some research. I suspect you'll only need to research the gender of characters that don't have male or female sex, but I might be wrong.

**Comment by dhicks** [comment]
“Feminine” and “masculine” are better labels for gender than “female” and “male.”  Jabba is the only hermaphroditic character in the dataset (that was the example I used above), and he’s gendered masculine.  IIRC there was one asexual character, and everyone else was female, male, or NA.

**Comment by MeganBeckett** [comment]
Great, thanks! Yes, I looked up Jabba and saw that he is masculine gender.

For each of the Droids, who's "biological sex" is none, I also looked up their gender as defined in how they were programmed, and have added these in.

**Comment by MeganBeckett** [comment]
For now though, I've left the current male and female genders as is, rather than renaming to masculine and feminine, respectively. Otherwise I'm not sure if this is too great a change at once that would break examples, etc?

**Comment by hadley** [comment]
@dhicks oops, yes, I was blanking on the correct terms.

@MeganBeckett I think switching to masculine/feminine would be fine
