### ISSUE TITLE
0.8.2 summarise min(POSIXct) incredibly slow compared to 0.8.1

### ISSUE THREAD

**Issue by shane-kercheval** [tidyverse/dplyr#4462]
Hello, if I run this snippet of code in `0.8.1` it takes about 4 seconds, but in `0.8.2` it takes about 14 minutes.

```r
library(dplyr)
set.seed(42)
random_date_times <- as.POSIXct(sample.int(10000000,
                                           100000,
                                           replace = TRUE),
                                origin = '1970-01-01')
set.seed(42)
random_users <- sample.int(500000,
                           100000,
                           replace = TRUE)

random_date_data <- data.frame(random_users=random_users,
                               random_date_times=random_date_times)        
start <- Sys.time()
random_date_data %>%
    group_by(random_users) %>%
    summarise(min_date = min(random_date_times)) %>%
    ungroup()
difftime(Sys.time(), start, units = 'sec')
```

In `0.8.1` i get an output of `Time difference of 3.631464 secs`

In `0.8.2` i get an output of `Time difference of 839.2222 secs`

I can reproduce reliably by going from 0.8.1->0.8.2 and back with the dplyr version as the only difference.

**Comment by shabbychef** [comment]
Likely a duplicate of #4458 ?

**Comment by shabbychef** [comment]
I have tried this under 0.8.2 and under the 0.8.3 release candidate that I installed via
```
library(remotes)
remotes::install_github('tidyverse/dplyr')
```
I killed it after two minutes in 0.8.2, but it took around 5 seconds in 0.8.2.9000. So I believe this is a duplicate.

**Comment by shane-kercheval** [comment]
Perfect, I confirmed the same. Thank you!
