### ISSUE TITLE
enhance rank functions to multiple columns

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#4482]
`rank`, `dense_rank`, etc. only have an `x` argument so that they only operate on one column.  Would be nice to be able to be able to operate on multiple columns.  For example, with this table:

```
DF <- data.frame(V1 = c("A", "A", "B", "B", "A"), V2 = c("a", "aa", "b", "b", "a"), no = 1:5)
```

one could do this in SQL for those databases having windowing functions:

``` 
select *, dense_rank() over (order by V1, V2) as grp from DF
```
and in data.table one has `rleid`
```
library(data.table)
DT <- as.data.table(DF)
setkey(DT, V1, V2)
rleid(DT$V1, DT$V2)
```

Would like to be able to do this in dplyr:

```
DF %>%  mutate(grp = dense_rank(V1, V2))
```

**Comment by hadley** [comment]
I've moved this issue to the funs package, which is where the fix will eventually happen.
