### ISSUE TITLE
Boostrap

### ISSUE THREAD

**Issue by shauyin520** [tidyverse/dplyr#4483]
Hi, I have many individuals, and each individual has multiple movement fix. How can i use boostrap for all the individuals with different movement fix

**Comment by bschneidr** [comment]
Hi @shauyin520, I think this is a question that should be asked in a different forum.

Here's what the readme file for dplyr says about requests for help:

> ### Getting help
> If you encounter a clear bug, please file a minimal reproducible example on github. **For questions and other discussion, please use community.rstudio.com, or the manipulatr mailing list.**

In addition to those two resources, you could also consult StackOverflow.
Here is one example post on StackOverflow that perhaps addresses your question:
[StackOverflow: Using dplyr's `do` to perform bootstrap replications](https://stackoverflow.com/questions/25793383/using-dplyrs-do-to-perform-bootstrap-replications)
