### ISSUE TITLE
clearer messaging when factor levels don't match in bind_rows

### ISSUE THREAD

**Issue by sfirke** [tidyverse/dplyr#4489]
I find this set of messages not as clear as it could be:
```
library(dplyr)
a <- data.frame(x = "one")
b <- data.frame(x = "two")
bind_rows(a, b)
#> Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector
#>     x
#> 1 one
#> 2 two
```
There are three warnings when one column doesn't match, and given that it started out as two factors, it's confusing to see warnings about character and factor (I gather from warning 1 that the character is produced along the way).

Similarly binding a character and factor produces two warnings:
```
c <- data.frame(x = "three", stringsAsFactors = FALSE)
bind_rows(a, c)
```
> Warning messages:
>1: In bind_rows_(x, .id) :
>  binding factor and character vector, coercing into character vector
>2: In bind_rows_(x, .id) :
>  binding character and factor vector, coercing into character vector

I'd find it clearer if there were a single warning issue per variable name that doesn't match class and/or levels.  Right now, I get a bunch of warnings and can't assess from that exactly how many problems I have.

Even 2 and 1 warnings in the respective cases above would be preferable to 3 and 2 currently.

Related, users might also find it helpful if the problem variable(s) are named.

**Comment by sfirke** [comment]
Naming the columns would feel consistent with https://github.com/tidyverse/dplyr/issues/2448

**Comment by romainfrancois** [comment]
This will be dealt with as part of the 0.9.0 release when we start using `vctrs`, esp. `vctrs::vec_rbind()` .

**Comment by hadley** [comment]
With current dev version:

``` r
library(dplyr, warn.conflicts = FALSE)
a <- data.frame(x = "one")
b <- data.frame(x = "two")
bind_rows(a, b)
#>     x
#> 1 one
#> 2 two
```

<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
