### ISSUE TITLE
select helpers inside transmute / mutate give an error

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/dplyr#4496]
I am redefining a function of a package, where I want to admit a variable of a data frame, like `f(iris, Sepal.Length)`, but also a formula, like `f(iris, Sepal.Length > 5)`. Because of this reason I am using the function `dplyr::transmute` inside, instead of `dplyr::select`. The problem is that in another function of the same package (which is not mine) a select helper is send to this function, giving place to an error.

In fact, I can do
```
iris %>% transmute(Sepal.Length,Sepal.Width)
```
without problem, but
```
iris %>% transmute(starts_with("Sepal"))
```
gives an error. In fact, I saw the error proceeds from `mutate` and before from `mutate_impl`, but I am not able to follow the problem. Is it expected? If not, could be solved?
``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.5.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
transmute(iris,contains("Sepal"))
#> No tidyselect variables were registered
rlang::last_trace()
#>      x
#>   1. +-dplyr::transmute(iris, contains("Sepal"))
#>   2. +-dplyr:::transmute.default(iris, contains("Sepal"))
#>   3. | +-dplyr::mutate(.data, !!!dots)
#>   4. | \-dplyr:::mutate.data.frame(.data, !!!dots)
#>   5. |   +-base::as.data.frame(mutate(tbl_df(.data), ...))
#>   6. |   +-dplyr::mutate(tbl_df(.data), ...)
#>   7. |   \-dplyr:::mutate.tbl_df(tbl_df(.data), ...)
#>   8. |     \-dplyr:::mutate_impl(.data, dots, caller_env())
#>   9. \-tidyselect::contains("Sepal")
#>  10.   +-base::tolower(vars)
#>  11.   \-tidyselect::peek_vars()
#>  12.     \-vars_env$selected %||% abort("No tidyselect variables were registered")
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Thank you very much!

**Comment by romainfrancois** [comment]
You may use `transmute_at()` to separate selection (with e.g. `contains("Sepal")`) from action, which here I guess is the identity, e.g. : 

``` r
library(dplyr, warn.conflicts = FALSE)

as_tibble(iris) %>% 
  transmute_at(vars(contains("Sepal")), identity)
#> # A tibble: 150 x 2
#>    Sepal.Length Sepal.Width
#>           <dbl>       <dbl>
#>  1          5.1         3.5
#>  2          4.9         3  
#>  3          4.7         3.2
#>  4          4.6         3.1
#>  5          5           3.6
#>  6          5.4         3.9
#>  7          4.6         3.4
#>  8          5           3.4
#>  9          4.4         2.9
#> 10          4.9         3.1
#> # … with 140 more rows
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

I don't really understand what the `f` function is supposed to do though.

**Comment by iago-pssjd** [comment]
The original function is essentially
```
get_dot_data <- function(x, ...) {
  qs <- dplyr::enquos(...)
  if (sjmisc::is_empty(qs))
    x
  else
    suppressMessages(dplyr::select(x, !!!qs))
}
```
and I wanted to change `select` by `transmute`. It is an auxiliary function of other with multiple purposes. I don't see how can I use `transmute_at` here, or if there is another option.

**Comment by romainfrancois** [comment]
I still don't understand. Maybe try community.rstudio.com ?

**Comment by iago-pssjd** [comment]
I've already redefined the function in another way, so I don't call select helpers from `transmute` or `mutate` any more. 
The goal of this issue is to warn that calling a select helper from these functions produces the error specified. If this was expected, since these callings have not much sense, fine.
Nevertheless, I thought that maybe a functionality like can do
```
iris %>% mutate(contains("Length") > 4)
```
for
```
iris %>% mutate(Sepal.Length > 4, Petal.Length > 4)
```
could be interesting.

Thank you.
