### ISSUE TITLE
multiplying two numbers and use of %>% requires the brackets in the preceeding command

### ISSUE THREAD

**Issue by aakhmetz** [tidyverse/dplyr#4499]
I am confused with combining multiplication and %>%

```r
(16*16) %>% sqrt
```
gives the correct answer ```16```, but 
```r
16*16 %>% sqrt 
```
says that it should be ```64```.

Is it not supposed that %>% takes the whole expression in the left hand side?

**Comment by cderv** [comment]
Hi, 

`%>%` operator is from the `magrittr` 📦. You'll find the documentation on https://magrittr.tidyverse.org

Inside the document you'll find this: 

> Another note is that special attention is advised when using non-magrittr operators in a pipe-chain (+, -, $, etc.), as operator precedence will impact how the chain is evaluated. In general it is advised to use the aliases provided by magrittr.

Source: https://magrittr.tidyverse.org/reference/pipe.html#technical-notes

Operator have precedence and `%>%` has lower than `*` in your example. It is why you have to specify that `(16*16)` need to be grouped. This is also why `magrittr` specify some aliases for this
``` r
library(magrittr)

16 %>%
  multiply_by(16) %>%
  sqrt()
#> [1] 16
```

<sup>Created on 2019-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Hope it helps.

For this kind of question, do not hesitate to asked on https://community.rstudio.com. There is a large community ready to help you. GH issues are more dedicated to bugs and feature request. Thank you ! 

Hope it helps.

**Comment by aakhmetz** [comment]
@cderv Thank you very much for your quick and detailed response!
