### ISSUE TITLE
Suggestion: group_split() allow argument to name the elements of a list

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#4506]
`group_split()` intentially chose the behavior to not name the elements based on the group names, but I find that this reduces functionality in some cases.  I'd like to suggest an argument that does name the items but defaults to not doing so.

**Comment by moodymudskipper** [comment]
It seems that it won't happen. It is discussed here: 
https://github.com/tidyverse/dplyr/issues/4223

**Comment by romainfrancois** [comment]
Not happening, easy enough to write on top of `group_split()`

**Comment by tungmilan** [comment]
FYI, this functionality is now available in the [`tidytable` package](https://github.com/markfairbanks/tidytable/commit/aec2165390e85dd477038972a00c177d5d225f8a)
