### ISSUE TITLE
join warning with a "novelty" class

### ISSUE THREAD

**Issue by jennybc** [tidyverse/dplyr#4508]
I don't expect this warning when joining a tibble that has a column of class `package_version`. I'm not sure if this is a general problem or is specific to this class, which is admittedly a bit peculiar. FYI my original use case came from the pkgsearch package, which returns a tibble with a column of this class.

``` r
library(tidyverse)

df <- tibble(
  package = "dplyr",
  version = packageVersion("dplyr")
)

tibble(package = c("dplyr", "vctrs")) %>% 
  left_join(df)
#> Joining, by = "package"
#> Warning in y[bad] <- rep.int(list(integer()), length(bad)): number of items
#> to replace is not a multiple of replacement length
#> # A tibble: 2 x 2
#>   package version   
#>   <chr>   <pckg_vrs>
#> 1 dplyr   0.8.3     
#> 2 vctrs   <NA>

df2 <- df %>% 
  mutate(version = as.character(version))

tibble(package = c("dplyr", "vctrs")) %>% 
  left_join(df2)
#> Joining, by = "package"
#> # A tibble: 2 x 2
#>   package version
#>   <chr>   <chr>  
#> 1 dplyr   0.8.3  
#> 2 vctrs   <NA>
```

<sup>Created on 2019-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
With dev versions, you get:

``` r
library(tidyverse)

df <- tibble(
  package = "dplyr",
  version = packageVersion("dplyr")
)
#> Error: All columns in a tibble must be 1d or 2d objects:
#> * Column `version` is package_version
```

<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think that is correct because the `package_version` object is so weird
