### ISSUE TITLE
vctrs based n_distinct()

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4510]
`vctrs::vec_unique_count()` feels right for implementing a `vctrs` based version of `n_distinct()` but does not have `na.rm=`

``` r
library(dplyr, warn.conflicts = FALSE)
library(vctrs)

data <- tibble(x = c(NA, 1, 2), y = c(1, 2, NA)) 

n_distinct(data$x, data$y)
#> [1] 3
n_distinct(data$x, data$y, na.rm = TRUE)
#> [1] 1
vctrs::vec_unique_count(data)
#> [1] 3
```

I guess it could `vec_slice()` the rows that are not NA, do we have something for that ?

**Comment by lionel-** [comment]
We already have `equal_na` parameter in other vctrs functions. I wonder if we need a more general `na_spec` parameter.

* For equality, it could be set to `"none"` or `"propagate"`.
* For counting, it could be set to `"none`, `"propagate"`, and `"remove"`.

```r
vctrs::vec_unique_count(data, na_spec = "none")
#> [1] 3

vctrs::vec_unique_count(data, na_spec = "propagate")
#> [1] NA

vctrs::vec_unique_count(data, na_spec = "remove")
#> [1] 2
```

cc @hadley @DavisVaughan

**Comment by romainfrancois** [comment]
in the meantime, this gives back the current `n_distinct()` but I guess is a bit heavy: 

```r
n_distinct <- function(..., na.rm = FALSE) {
  data <- tibble(...)
  if (isTRUE(na.rm)){
    data <- vec_slice(data, !reduce(map(data, vec_equal_na), `|`))
  }
  vec_unique_count(data)
}
```

**Comment by romainfrancois** [comment]
Closing this for now, as we have a, albeit heavy, vctrs based implementation.
