### ISSUE TITLE
group_by, mutate(), ifelse() combination produce wrong result.

### ISSUE THREAD

**Issue by ETaSky** [tidyverse/dplyr#4513]
I came across this strange situation where a combination of group_by, mutate, and ifelse failed to generate expected output.

A simple repres:
```r
data.frame(Factor = c(rep("A", 4), rep("B", 4), rep("C", 4)), 
           Value = seq(12), stringsAsFactors = F) %>% 
    group_by(Factor) %>% mutate(V = ifelse(T, Value, 0))
# A tibble: 12 x 3
# Groups:   Factor [3]
   Factor Value     V
   <chr>  <int> <int>
 1 A          1     1
 2 A          2     1
 3 A          3     1
 4 A          4     1
 5 B          5     5
 6 B          6     5
 7 B          7     5
 8 B          8     5
 9 C          9     9
10 C         10     9
11 C         11     9
12 C         12     9
```
In this simple test, the V should be exact the same as Value. However, in the actual output V is equal to the first value of each group.

My tidyverse version is 1.2.1

Thanks!

**Comment by cderv** [comment]
Hello, 

base `ifelse` is not vectorized as you may think. 
``` r
ifelse(TRUE, letters, 0)
#> [1] "a"
ifelse(rep(TRUE, 2), letters, 0)
#> [1] "a" "b"
```
From `?ifelse`:
> ifelse(test, yes, no)
> ifelse returns a value with the same shape as test which is filled with elements selected from either yes or no depending on whether the element of test is TRUE or FALSE.

As you see, you get as many values as the test vector from either yes or no. 
This means that dplyr works perfectly well : You ask for one `TRUE` so you get the first group value recycled. You'll need to have vectors of correct length in `ifelse` for what you want.
``` r
library(dplyr)
data.frame(Factor = c(rep("A", 4), rep("B", 4), rep("C", 4)), 
           Value = seq(12), stringsAsFactors = F) %>% 
  group_by(Factor) %>% 
  mutate(V2 = ifelse(rep(T, n()), Value, rep(0L, n())))
#> # A tibble: 12 x 3
#> # Groups:   Factor [3]
#>    Factor Value    V2
#>    <chr>  <int> <int>
#>  1 A          1     1
#>  2 A          2     2
#>  3 A          3     3
#>  4 A          4     4
#>  5 B          5     5
#>  6 B          6     6
#>  7 B          7     7
#>  8 B          8     8
#>  9 C          9     9
#> 10 C         10    10
#> 11 C         11    11
#> 12 C         12    12
```

<sup>Created on 2019-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Know that there is also a `dplyr::if_else` that could be useful here.
`dplyr::case_when` can be useful here too. But it depends on your real use case
``` r
library(dplyr)
data.frame(Factor = c(rep("A", 4), rep("B", 4), rep("C", 4)), 
           Value = seq(12), stringsAsFactors = F) %>% 
  group_by(Factor) %>% 
  mutate(V = case_when(
    TRUE ~ Value
  ))
#> # A tibble: 12 x 3
#> # Groups:   Factor [3]
#>    Factor Value     V
#>    <chr>  <int> <int>
#>  1 A          1     1
#>  2 A          2     2
#>  3 A          3     3
#>  4 A          4     4
#>  5 B          5     5
#>  6 B          6     6
#>  7 B          7     7
#>  8 B          8     8
#>  9 C          9     9
#> 10 C         10    10
#> 11 C         11    11
#> 12 C         12    12
```

<sup>Created on 2019-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Hope it helps.

**Comment by ETaSky** [comment]
@cderv Thank you so much! This is really helpful. I did not realize I was using base R ifelse function. Thank you!
