### ISSUE TITLE
Observations about filter() with a grouped data frame

### ISSUE THREAD

**Issue by jennybc** [tidyverse/dplyr#4518]
Writing down some lengthy 😬 reflections as I work on revdeps for the upcoming release
of tidyr v1.0.0.

`tidyr::nest()` now returns a grouped data frame and this has implications
for downstream manipulations with dplyr verbs. We should mull this over and,
assuming it’s all intended and part of the plan, write up our preferred
approaches for manipulating grouped data frames. One of the selling points for working in the nested form is that "you can use your usual data frame manipulation toolkit", so this seems worth studying.

This example is inspired by a tidyr revdep investigation.

``` r
library(tidyverse)

df <- tibble(
  foo = c("a", "a", "a", "b", "b", "b"),
  yo = c(1, NA, 1, 1, 1, 2),
  bar = c(1:4, NA, 6)
)
```

Group it on two variables, `foo` and `yo`, where `yo` contains an `NA`. So
does the remaining variable, `bar`.

``` r
(df_grouped <- df %>% 
    group_by(foo, yo))
#> # A tibble: 6 x 3
#> # Groups:   foo, yo [4]
#>   foo      yo   bar
#>   <chr> <dbl> <dbl>
#> 1 a         1     1
#> 2 a        NA     2
#> 3 a         1     3
#> 4 b         1     4
#> 5 b         1    NA
#> 6 b         2     6
```

Nest it.

``` r
(df_nested <- df_grouped %>%
    nest())
#> # A tibble: 4 x 3
#> # Groups:   foo, yo [4]
#>   foo      yo           data
#>   <chr> <dbl> <list<df[,1]>>
#> 1 a         1        [2 × 1]
#> 2 a        NA        [1 × 1]
#> 3 b         1        [2 × 1]
#> 4 b         2        [1 × 1]
```

Note that we have 4 groups: (a, 1), (a, NA), (b, 1), (b, 2).

We want to limit downstream analyses such that there’s no missing data for
the grouping variables. Your instinct is to use `filter()` and
`complete.cases()`… somehow. But how do you apply `complete.cases()` just
to the grouping vars inside `filter()`? I’m not sure it’s even possible.
Instead, people will pre-compute a logical vector.

``` r
(keepers_grouped <- df_grouped %>% 
    select(group_cols()) %>% 
    complete.cases())
#> [1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE

(keepers_nested <- df_nested %>% 
    select(group_cols()) %>% 
    complete.cases())
#> [1]  TRUE FALSE  TRUE  TRUE
```

Then they will try to `filter()` with it. And fail.

``` r
df_grouped %>% 
  filter(keepers_grouped)
#> Error: Result must have length 2, not 6

df_nested %>% 
  filter(keepers_nested)
#> Error: Result must have length 1, not 4
```

Our toolkit seems to be pushing people to work inside the data frame and, with
a grouped data frame, map the manipulations over the groups.

``` r
df_grouped %>%
  # remember: .x is the data for a group, .y is a 1-row df of group cols
  group_modify(~ filter(.x, complete.cases(.y))) %>% 
  nest()
#> # A tibble: 3 x 3
#> # Groups:   foo, yo [3]
#>   foo      yo           data
#>   <chr> <dbl> <list<df[,1]>>
#> 1 a         1        [2 × 1]
#> 2 b         1        [2 × 1]
#> 3 b         2        [1 × 1]
```

This works, but many users might not find this solution. Should there be a
simpler solution? Also, we lost a (empty) group – is that correct? I see no
way to control that.

A similar approach also works on the nested form, but we get a lot of
warnings that aren’t particularly easy to interpret.

``` r
df_nested %>% 
  group_modify(~ filter (.x, complete.cases(.y)))
#> Warning in bind_rows_(x, .id): Vectorizing 'vctrs_list_of' elements may not
#> preserve their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'vctrs_list_of' elements may not
#> preserve their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'vctrs_list_of' elements may not
#> preserve their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'vctrs_list_of' elements may not
#> preserve their attributes
#> # A tibble: 3 x 3
#> # Groups:   foo, yo [3]
#>   foo      yo data            
#>   <chr> <dbl> <list>          
#> 1 a         1 <tibble [2 × 1]>
#> 2 b         1 <tibble [2 × 1]>
#> 3 b         2 <tibble [1 × 1]>
```

There’s obviously some sort of difference in how vctrs is brought to bear
here. There are differences in the return object.
I imagine most people will just get frustrated and `ungroup()` prior to
`filter()`ing.

``` r
df_nested %>%
  ungroup() %>% 
  filter(keepers_nested)
#> # A tibble: 3 x 3
#>   foo      yo           data
#>   <chr> <dbl> <list<df[,1]>>
#> 1 a         1        [2 × 1]
#> 2 b         1        [2 × 1]
#> 3 b         2        [1 × 1]
```

But, in general, though, we think grouped-ness should be retained, to permit
proper `nest()` \<–\> `unnest()` roundtrips, so it’s a bummer if we encourage
`ungroup()`ing when we don’t mean to.

You can also temporarily add the external variable using
`tibble::add_column()`, and then remove it. You can’t add it using
`mutate()`, because, like `filter()`, it’s hard to use with external data in
an grouped data frame.

``` r
df_nested %>%
  add_column(keepers = keepers_nested) %>%
  filter(keepers) %>% 
  select(-keepers)
#> # A tibble: 3 x 3
#> # Groups:   foo, yo [3]
#>   foo      yo           data
#>   <chr> <dbl> <list<df[,1]>>
#> 1 a         1        [2 × 1]
#> 2 b         1        [2 × 1]
#> 3 b         2        [1 × 1]
```

This also seems a bit goofy, i.e. the use of `add_column()` is a hack to
circumvent the group structure.

Finally, if you aren’t working in a piped fashion, you don’t require
`dplyr::filter()`’s `NA` handling, and you aren’t using tidy eval (e.g.
`enquo()` followed by `!!` or `{{x}}`), it’s possible that `[` is the right
solution.

``` r
df_nested[keepers_nested, ]
#> # A tibble: 3 x 3
#> # Groups:   foo, yo [3]
#>   foo      yo           data
#>   <chr> <dbl> <list<df[,1]>>
#> 1 a         1        [2 × 1]
#> 2 b         1        [2 × 1]
#> 3 b         2        [1 × 1]
```

But it feels self-inconsistent to recommend an approach that bypasses the
most obvious dplyr verb, `filter()`.

<sup>Created on 2019-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
If you want to select all "complete cases", I think you'll be able to use `across()`:

```R
df %>% filter(complete.cases(across(everything())))`
```

Can you please confirm @romainfrancois?

**Comment by hadley** [comment]
I think `across()` is the general solution here, because it allows you to retrieve a data frame that you can pass to `complete.cases()`:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  foo = c("a", "a", "a", "b", "b", "b"),
  yo = c(1, NA, 1, 1, 1, 2),
  bar = c(1:4, NA, 6)
)

df %>% filter(complete.cases(across(everything())))
#> # A tibble: 4 x 3
#>   foo      yo   bar
#>   <chr> <dbl> <dbl>
#> 1 a         1     1
#> 2 a         1     3
#> 3 b         1     4
#> 4 b         2     6
```

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We will need a vignette on `across()`: #4704

**Comment by jennybc** [comment]
I just reread my epic comment.

I think the goal was to only apply `complete.cases()` to the grouping vars, though. So I'm not sure that the above solution addresses that. There's no grouping at all? But I haven't completely re-immersed myself in this.

**Comment by hadley** [comment]
I convinced myself that you'd probably do that before grouping

**Comment by jennybc** [comment]
> I convinced myself that you'd probably do that before grouping

Well, yeah ... ideally. That speaks to the difficulties of revdep fixing adventures, where you're torn re: how much you're willing to understand / refactor. The immediate presentation of my motivating problem was definitely a post-grouping filter predicament.

**Comment by hadley** [comment]
We have considered having another variant of `across()` that focusses exclusively on the grouping cols, but I'm worried about making the interface too big. I'd like to see more compelling use cases before adding it.

**Comment by romainfrancois** [comment]
Same difference I guess, but one could also use the second argument of `across()`, you'll get a data frame back and internal code does the reducing: 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  foo = c("a", "a", "a", "b", "b", "b"),
  yo = c(1, NA, 1, 1, 1, 2),
  bar = c(1:4, NA, 6)
)

df %>% 
  filter(across(everything(), purrr::negate(is.na)))
#> # A tibble: 4 x 3
#>   foo      yo   bar
#>   <chr> <dbl> <dbl>
#> 1 a         1     1
#> 2 a         1     3
#> 3 b         1     4
#> 4 b         2     6
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by romainfrancois** [comment]
There is a bit of tension about which variables should be including in what `across()` is allowed to select, i.e. in the canonical `across()` example it feels natural that `everything()` is all the non grouping variables: 

``` r
library(dplyr, warn.conflicts = FALSE)

iris %>% 
  group_by(Species) %>% 
  summarise(across(everything(), mean))
#> # A tibble: 3 x 5
#>   Species    Sepal.Length Sepal.Width Petal.Length Petal.Width
#>   <fct>             <dbl>       <dbl>        <dbl>       <dbl>
#> 1 setosa             5.01        3.43         1.46       0.246
#> 2 versicolor         5.94        2.77         4.26       1.33 
#> 3 virginica          6.59        2.97         5.55       2.03
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

but this discussion seems to suggest it might be useful to be allowed to select grouping columns as well, perhaps how #4716 does it, but I'm not convinced about the ui: 

``` r
library(tidyverse)

df <- tibble(
  foo = c("a", "a", "a", "b", "b", "b"),
  yo = c(1, NA, 1, 1, 1, 2),
  bar = c(1:4, NA, 6)
)

(df_grouped <- df %>% 
    group_by(foo, yo))
#> # A tibble: 6 x 3
#> # Groups:   foo, yo [4]
#>   foo      yo   bar
#>   <chr> <dbl> <dbl>
#> 1 a         1     1
#> 2 a        NA     2
#> 3 a         1     3
#> 4 b         1     4
#> 5 b         1    NA
#> 6 b         2     6

(df_nested <- df_grouped %>%
    nest())
#> # A tibble: 4 x 3
#> # Groups:   foo, yo [4]
#>   foo      yo data            
#>   <chr> <dbl> <list>          
#> 1 a         1 <tibble [2 × 1]>
#> 2 a        NA <tibble [1 × 1]>
#> 3 b         1 <tibble [2 × 1]>
#> 4 b         2 <tibble [1 × 1]>

df_nested %>% 
  filter(complete.cases(across(c(foo, yo), .including_grouping = TRUE)))
#> # A tibble: 3 x 3
#> # Groups:   foo, yo [3]
#>   foo      yo data            
#>   <chr> <dbl> <list>          
#> 1 a         1 <tibble [2 × 1]>
#> 2 b         1 <tibble [2 × 1]>
#> 3 b         2 <tibble [1 × 1]>
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

There would be two back to back selections: 
 - one to select the domain, controlled by a logical argument
 - one to select within that domain

**Comment by hadley** [comment]
From conversation with @jennybc: `across()` works with the contents of the envelope (the insides of the group data frames); we also need an equivalent function for the labels on the envelope (the grouping keys)

**Comment by hadley** [comment]
Another observation: might be able to resolve problem with temporary grouping (#4711):

```R
df_nested %>% 
  with_groups(NULL, filter, complete.cases(across()))
```

**Comment by hadley** [comment]
Now that we have `with_groups()`, I think we can close again, and wait until this crops up again before thinking about other interfaces.
