### ISSUE TITLE
False branch of `if` is evaluated within mutate assignment

### ISSUE THREAD

**Issue by banfai** [tidyverse/dplyr#4525]
When there is an `if-else` condition within a `mutate` assignment the `FALSE` expression is evaluated. This can cause errors if those expressions only make sense if the condition is `TRUE`.

The expected behavior would be to not try to evaluate `sym(name)`, but return `NULL` (i.e. no assignment) in the second example.

``` r
library(rlang)
library(dplyr)

name1 <- "Species"
iris %>% 
  slice(1:5) %>% 
  mutate(
    Name := if (!is.na(name1)) {!!sym(name1)} else {NULL}
  )
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species   Name
#> 1          5.1         3.5          1.4         0.2  setosa setosa
#> 2          4.9         3.0          1.4         0.2  setosa setosa
#> 3          4.7         3.2          1.3         0.2  setosa setosa
#> 4          4.6         3.1          1.5         0.2  setosa setosa
#> 5          5.0         3.6          1.4         0.2  setosa setosa

name2 <- NA
iris %>% 
  slice(1:5) %>% 
  mutate(
    Name := if (!is.na(name2)) {!!sym(name2)} else {NULL}
  )
#> Only strings can be converted to symbols
```

<sup>Created on 2019-08-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The same happens with `dplyr 0.8.3` and `rlang 0.4.0`, as well as `dplyr 0.8.3.9000` and `rlang 0.4.0.9001`.

**Comment by romainfrancois** [comment]
The unquoting (‼️) is done before `dplyr` gets involved, and so before the `if` is evaluated. 

``` r
library(rlang)

name1 <- "Species"
expr(
  if (!is.na(name1)) {!!sym(name1)} else {NULL}
)
#> if (!is.na(name1)) {
#>     Species
#> } else {
#>     NULL
#> }

name2 <- NA
expr(
  if (!is.na(name2)) {!!sym(name2)} else {NULL}
)
#> Only strings can be converted to symbols
```

What you can do is to first create the expression conditionally, e.g. 

``` r
library(rlang)
library(dplyr, warn.conflicts = FALSE)

name2 <- NA
expr2 <- if (!is.na(name2)) {
  expr(!!sym(name2))
}
iris %>% 
  slice(1:5) %>% 
  mutate(Name = !!expr2)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
```

<sup>Created on 2019-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by banfai** [comment]
Hi Romain,
Thanks for you answer, your example makes it clearer what was going wrong.

I have found another way of handling this, in case anyone comes across this issue:

```r
library(rlang)
library(dplyr, warn.conflicts = FALSE)

name2 <- NA
iris %>% 
  slice(1:5) %>% 
  mutate(Name = .[[name2]],
         Name = rlang::.data[[name2]])
```

Both `.` and `rlang::.data` handle `NA` with double-bracket indexing, returning `NULL` (i.e. no assignment), so actually there's no need for unquoting.
