### ISSUE TITLE
select helpers for count and group_by ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#4538]
This https://github.com/tidyverse/dplyr/issues/3939 is closed so I'm reopening for further details and requests.

Above link suggests to use `group_by_at`, but why wouldn't `group_by` support select helpers ? This would feel natural to have it consistent with `select`, along with `count` (which doesn't have a `count_at` counterpart).

``` r
library(tidyverse, warn.conflicts = FALSE)
#> Registered S3 method overwritten by 'rvest':
#>   method            from
#>   read_xml.response xml2
#> Warning: package 'dplyr' was built under R version 3.6.1

# workaround
iris[1:4] %>% 
  map_dfc(`>`,4.3) %>% 
  count(!!!select(.,starts_with("Sepal")))
#> # A tibble: 3 x 3
#>   Sepal.Length Sepal.Width     n
#>   <lgl>        <lgl>       <int>
#> 1 FALSE        FALSE           1
#> 2 TRUE         FALSE         148
#> 3 TRUE         TRUE            1

# expected to give same result
iris[1:4] %>% 
  map_dfc(`>`,4.3) %>% 
  count(starts_with("Sepal"))
#> No tidyselect variables were registered
```

<sup>Created on 2019-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`count()` is also behaving inconsistently with `select()` when fed numeric arguments,
is there a reason for that ?

``` r
iris %>% select(1,2) %>% head()
#>   Sepal.Length Sepal.Width
#> 1          5.1         3.5
#> 2          4.9         3.0
#> 3          4.7         3.2
#> 4          4.6         3.1
#> 5          5.0         3.6
#> 6          5.4         3.9

iris[1:4] %>% count(1,2)
#> # A tibble: 1 x 3
#>     `1`   `2`     n
#>   <dbl> <dbl> <int>
#> 1     1     2   150
```

**Comment by hadley** [comment]
In dplyr 1.0.0, you'll be able to use `across()` to perform selection in mutation contexts, e.g. `count(df, across(starts_with("Sepal"))`
