### ISSUE TITLE
group_by tolerance for floating point equality

### ISSUE THREAD

**Issue by mk6ve** [tidyverse/dplyr#4539]
Hello,

I am working on some time series where I import the measurements, but to align and average experiments, I generate the time information separately. I could not effectively summarize these with dplyr, nor plot them with ggplot.

I figured out that it has to do with summary functions not grouping seemingly identical floats together. For now I am dealing with it by round()ing the sequences which works fine, but adds
a degree of uncertainty about whether it will always work predictably.

I would like to know if this is by design, and if it would be possible to add an option to make grouping and summarizing floats have some degree of tolerance, like comparing with `near`.

I would expect to get means of `y` for values of `x` between -0.4 and 0.5 in the example below. Instead, some values of `x` are treated as different.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

a <- tibble(x = seq(-0.5,0.5,0.1), y = 0:10)
b <- tibble(x = seq(-0.4, 0.6, 0.1), y = 20:30)

c <- bind_rows(a,b)

c %>% group_by(x) %>%
  summarise(z = mean(y))
#> # A tibble: 15 x 2
#>         x     z
#>     <dbl> <dbl>
#>  1 -0.5     0  
#>  2 -0.4    10.5
#>  3 -0.3    21  
#>  4 -0.3     2  
#>  5 -0.2    22  
#>  6 -0.200   3  
#>  7 -0.100  13.5
#>  8  0      14.5
#>  9  0.100  25  
#> 10  0.1     6  
#> 11  0.2    16.5
#> 12  0.3    17.5
#> 13  0.4    18.5
#> 14  0.5    19.5
#> 15  0.6    30
```

<sup>Created on 2019-08-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thank you!

**Comment by hadley** [comment]
I think rounding these yourself is the right thing to do — grouping by floating point numbers is inherently problematic, and I don't think dplyr has enough information to reliably handle it automatically.
