### ISSUE TITLE
if we can use all_vars in mutate

### ISSUE THREAD

**Issue by WonDerSoKo** [tidyverse/dplyr#4540]
> I want to create a feature called "flag" to show if all values in an observation is NA.But it seems complicated to write it with R.

---

For instance, x is a 3x3 **tibble**.
```r
x <- tibble(a=c(1,2,NA),b=c(NA,NA,NA)%>% as.numeric,c=c(NA,4,NA))
x
```
![image](https://user-images.githubusercontent.com/45867107/63672639-f6fa2300-c814-11e9-975a-64ea565fa616.png)

I have to use below to solve my problem.
```r
x %>% mutate(flag = is.na(a)&is.na(b)&is.na(c))
```
![image](https://user-images.githubusercontent.com/45867107/63672749-39bbfb00-c815-11e9-8870-a26dbd006c2c.png)

In fact, I have 80 features to 
If I use **apply**, it returns a vector and it's not what I want.

I know **all_vars** in help pages, but it can only be used in filtering verbs.
I try to use it in **mutate**, and got error.
```r
x %>% mutate(flag = all_vars(is.na(.)))
```
I think it would be a lot easier and cooler to use **all_vars**  in **mutate**.

**Comment by romainfrancois** [comment]
This is a perfect use case for `across()` from #4586 : 

``` r
library(dplyr, warn.conflicts = FALSE)

x <- tibble(
  a=c(1,2,NA),
  b=as.numeric(c(NA,NA,NA)),
  c=c(NA,4,NA)
)

x %>% 
  mutate(flag = rowSums(across(a:c, is.na)) == 3)
#> # A tibble: 3 x 4
#>       a     b     c flag 
#>   <dbl> <dbl> <dbl> <lgl>
#> 1     1    NA    NA FALSE
#> 2     2    NA     4 FALSE
#> 3    NA    NA    NA TRUE
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
