### ISSUE TITLE
Make all verb_if/all generic S3 function? E.g. group_by_if?

### ISSUE THREAD

**Issue by xiaodaigh** [tidyverse/dplyr#4541]
I am building disk.frame which leverage `dplyr::group_by`'s S3ness to make it work for disk.frame. But, I noticed that `dplyr::group_by_if` isn't an S3 function. I am happy to make PRs to make them all S3 including `filter_all/if`

**Comment by hadley** [comment]
We are going to be reducing the full set of these verbs in the near future, so I think we should revisit this after dplyr 1.0.0 is out.
