### ISSUE TITLE
Consistency & interoperability between dplyr and recipes selectors

### ISSUE THREAD

**Issue by dgkf** [tidyverse/dplyr#4548]
I recently saw @topepo give a talk about tidymodel's [`recipes`](https://github.com/tidymodels/recipes) package where he used the `recipes::all_numeric()` selector to select columns for data preprocessing steps.

In `dplyr` I'd approach this with `mutate_if(is.numeric, ...)`. I like the flexibility of the `*_if` and `*_at` flavors of the `dplyr` verbs, but also really appreciate the simplicity and readability of `all_numeric()` and the like. It would be nice if both of these packages used the same selectors, at least for generic selection criteria like variable types. Moreover, these functions also can't currently be mix-and-matched. Using `all_numeric()` with `dplyr` functions selects no variables. I think this is because the context variable info is stored in the attached `recipes` namespace, invisible to `dplyr`, but I haven't dug into it too deeply.

With new package-specific selector functions popping up, I can easily see it getting a bit overwhelming trying to keep track of which packages provide which selection shorthands. Is there any way to bring some harmony and interoperability to selectors across these packages?

**Comment by hadley** [comment]
We're going to be unifying dplyr and recipes selectors with the next version of tidyselect. Once that happens you'll be able to do (e.g.) `select(iris, is.numeric)` or `mutate_at(iris, is.numeric, ...)`.
