### ISSUE TITLE
If there are codes for exactly matching every elements in a list to each element in a column

### ISSUE THREAD

**Issue by LoveYukee** [tidyverse/dplyr#4555]
The problem is, a doctor who received payments from different companies must report where the money come from. I have a list of officially recorded companies and a list of company names that doctor reports. The goal of the code is to check if that the database's record is accurate(There is no specific sequence of the names in the column or in the list) But that doctor only write part of the company name. I expect the output of a list of correct Boolean value, the size of this list should be the same as CompanyInDataBase's.
---
The actual list or column are much larger, and I just construct a simpler model in following codes. I have tried to vary the max.distance parameter. I found out when max.distance is 5 or larger, I will get 4 TRUE; otherwise I will get 4 False. I am not sure if my codes have logic problems or I didn't adjust the max.distance properly. Hoping for any suggestions

```r
df <- data.frame(CompanyInDataBase = c('Pfizer Inc', 'Shire North America Group Inc', 'Roche Inc', 'Bayor Inc'), 
                 stringsAsFactors = FALSE)
report = c('Shire', 'Pfizer', 'Genetech')

for(i in 1:length(report)){
  match <- agrepl(report[i], df$CompanyInDataBase, max.distance = 0.1)
}
```
I expect the output of a list of correct Boolean value, the size of this list should be the same as CompanyInDataBase's.

**Comment by cderv** [comment]
Hi @LoveYukee , I think it is better to ask this kind of questions in https://community.rstudio.com.
There is a broad community there ready to help. Github issue in the repository are more suited for known bugs and feature resquest. 
See [Getting Help](https://github.com/tidyverse/dplyr#getting-help) in the README.

Thank you

**Comment by batpigandme** [comment]
Thanks, @cderv. 
@LoveYukee, I'm going to go ahead and close this. If it turns out it is an actual bug in dplyr, we can always come back and re-open it.
