### ISSUE TITLE
Error in UseMethod("mutate_") :    no applicable method for 'mutate_' applied to an object of class "c('xts', 'zoo')"

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/dplyr#4556]
I was trying to build a general answer to [this question](https://stackoverflow.com/questions/18189753/rowsums-but-keeping-na-values), with `dplyr`, so I started with
```
library(xts)
library(dplyr)
set.seed(120)
dd <- xts(rnorm(100),Sys.Date()-c(100:1))
dd1 <- ifelse(dd<(-0.5),dd*-1,NA)
dd2 <- ifelse((dd^2)>0.5,dd,NA)
mm <- merge(dd1,dd2)
```
But when I change the next step `mm$m <- rowSums(mm,na.rm=TRUE)` (which returns a numeric class object computed by `rowSums`) by 
```
mm <- mm %>% mutate(m = rowSums(mm, na.rm = TRUE))
```
I get
```
Error in UseMethod("mutate_") : 
  no applicable method for 'mutate_' applied to an object of class "c('xts', 'zoo')"
```
Thank you!

**Comment by cderv** [comment]
`mm` is a xts object in your example. You can't use mutate from dplyr on such object. That is what the error is saying. 

You need to work from the beginning with a data.frame or a tibble, or use packages that extend the tidyverse towards timeseries, like [tsibble](https://tsibble.tidyverts.org/). You can also convert to with other like [tsbox](https://www.tsbox.help/) to handle the conversion from xts to other format.

**Comment by iago-pssjd** [comment]
Thank you! I hadn't noticed the class of the object.
