### ISSUE TITLE
Suggestion: add function to retype variables

### ISSUE THREAD

**Issue by Spiritspeak** [tidyverse/dplyr#4560]
Often, somewhere during my data pre-proc pipeline I need to change the class of many variables in a data frame. This is the only relevant functionality that I use, that is missing from dplyr. I usually run: 
```r
dataset$subject_id%<>%as.character()
dataset$condition%<>%as.factor()
dataset$reaction_time%<>%as.numeric()
```
But this can be greatly simplified using the logic that dplyr already uses for functions like rename():
```r
dataset %<>% retype(subject_id = character(), condition = factor(), reaction_time = numeric())
```
I believe this would be a great addition to the package.

**Comment by batpigandme** [comment]
You can currently do this with mutate (though you do have to specify the variable a second time). I think this might be made easier with the vctrs integration:
https://vctrs.r-lib.org/

**Comment by hadley** [comment]
This seems like a relatively special purpose function, so I think `mutate_at()` is fine for now. We are actively exploring ways of making `mutate_at()` and friends more flexible in the future.
