### ISSUE TITLE
In group_modify, "." is not always equivalent to ".x"

### ISSUE THREAD

**Issue by jonjhitchcock** [tidyverse/dplyr#4563]
The help for `group_modify()` says that "In the formula, you can use . or .x to refer to the subset of rows of .tbl for the given group".  This is not always true.
The following example gives the error "The result of .f should be a data frame" but it can be fixed by just changing "." to ".x"

```r
mystats <- function(x) {
  data.frame(mean=mean(x), sd=sd(x))
}
library(MASS)
library(dplyr)
Cars93 %>%
  group_by(Type) %>%
  group_modify( ~ . %>% pull(Price) %>% mystats)
```
Note that "." and ".x" ARE equivalent if the final line is changed to
```r
group_modify( ~ pull(., Price) %>% mystats)
```
or 
```r
group_modify( ~ pull(.x, Price) %>% mystats)
```

**Comment by romainfrancois** [comment]
This is because there is special treatment in `magrittr` for the `. %>%` pattern :

``` r
library(magrittr)

# this creates a function
fun <- . %>% mean()

# using the function
fun(1:10)
#> [1] 5.5
```

It comes from a time where we were not using the shortcut `~` notation to make functions.
