### ISSUE TITLE
sample_frac should not return 0 rows 

### ISSUE THREAD

**Issue by roelhogervorst** [tidyverse/dplyr#4567]
When I sample a fraction of the data I expect at least one result back, not 0.
I believe something like this happens: `round(n_rows * fraction)` 0.4 rounded is 0 in this case. 
I understand what happens, I think it rounds to the nearest integer, but if I sample from something shouldn't there be at least 1 row back? Or is this not the right way to think about sampling?

---
I believe sample frac should at least return 1 row when both size and fraction are smal. 

```r
library(dplyr)
data <- tibble(dat = c(1,2))
data %>% sample_frac(0.2)
```
```
# A tibble: 0 x 1
# … with 1 variable: dat <dbl>

```

**Comment by romainfrancois** [comment]
You may write this version of `sample_frac()`, e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)

sample_up <- function(.data, frac) {
  sample_n(.data, ceiling({{frac}} * n()) )
}

tibble(dat = c(1,2))  %>% 
  sample_up(0.2)
#> # A tibble: 1 x 1
#>     dat
#>   <dbl>
#> 1     1
```

<sup>Created on 2019-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
