### ISSUE TITLE
FR: select/rename methods for lists()

### ISSUE THREAD

**Issue by t-kalinowski** [tidyverse/dplyr#4569]
`select` semantics are great, particularly with how easy it is to rename elements at the same time as subsetting. I frequently find myself wishing I could have the same convenience when working with things other than data frames, in particular lists but also sometimes environments. 

Would there be interest in a PR for exporting some list methods that look something like this:
```r
select.list <- function(.data, ...) {
  vars <- tidyselect::vars_select(names(.data), ...)
  .data <- .data[unname(vars)]
  names(.data) <- names(vars)
  .data
}

rename.list <- function(.data, ...) {
  vars <- tidyselect::vars_rename(names(.data), ...)
  .data <- .data[unname(vars)]
  names(.data) <- names(vars)
  .data
}
```

I'm aware that there is some prior discussion related to this topic ([here](https://github.com/tidyverse/dplyr/issues/4279) and [here](https://github.com/tidyverse/dplyr/issues/2817)), but nothing directly addressing whether these methods would be welcome as far as I know.

**Comment by romainfrancois** [comment]
I believe this is out of scope for dplyr, and would be better in another package, however two "problems". 

 - The unfortunately named `utils::select.list()` gets in the way
 - So `dplyr` has a `select.list()` to mask it, but it just aborts

**Comment by t-kalinowski** [comment]
Indeed, those two bullets are why I posted the issue!. In my personal package I have a version of those functions which worked great until dplyr started to export the aborting `select.list()`. I filed this issue right after adding this to my `.onLoad()`:
```
  dplyr_ns <- asNamespace("dplyr")
  unlockBinding("select.list", dplyr_ns)
  assignInNamespace("select.list", select.list, dplyr_ns)
  lockBinding("select.list", dplyr_ns)
```

Surely others would find being able to use `select` and `rename` with lists useful.

**Comment by hadley** [comment]
Yeah, this is definitely out of scope for dplyr.
