### ISSUE TITLE
Feature request: pull, named vector

### ISSUE THREAD

**Issue by ramongallego** [tidyverse/dplyr#4577]
---

Sometimes the last step of a series of pipes is pulling out one of the columns created in the tibble. The returned value is a vector - it would be nice if one had the chance of automatically name the vector with another column of the same dataframe

```r
library(dplyr)
df <- tibble(a = LETTERS[1:5], b = 1:5)

df %>%
pull(b) 

# Desired output

named_pull <- function(x, values_from, names_from){
  
  
names.output<- pull(x, {{names_from}})
output <- pull(x, {{values_from}})
names(output)<- names.output
return(output)
}
df %>%
named_pull(b, names_from= a) 

```

**Comment by romainfrancois** [comment]
There is already a pull request for this: https://github.com/tidyverse/dplyr/pull/4102 closing here as a duplicate.
