### ISSUE TITLE
Filter operation doesn't work if variable name intersects with column name

### ISSUE THREAD

**Issue by mattsgithub** [tidyverse/dplyr#4578]
**TL;DR:**
Using variable names that conflict with dataframe column names in a `filter` does not yield expected results.

Example:
``` r
library("tidyverse")
library("reprex")

df <- tibble(x = c(1, 1, 2, 2),
             y = c(1, 2, 3, 4))

# Create a variable with a name
# that conflicts with column name
x <- 2

# Now filter by this column
df %>% filter(x == x)
#> # A tibble: 4 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     1
#> 2     1     2
#> 3     2     3
#> 4     2     4
```

<sup>Created on 2019-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I'd recommend at minimum, logging a warning.

**Comment by batpigandme** [comment]
I think this is a duplicate of the issue here (which includes a fuller explanation of why this is the case). 

https://github.com/tidyverse/dplyr/issues/3840

@romainfrancois I can't find the issue for a warning here, but I feel like I've seen it before

**Comment by mattsgithub** [comment]
Ah, I see the technical reasons why. Well, given this is a duplicate, I will close.
