### ISSUE TITLE
Feature request: please Depend on magrittr

### ISSUE THREAD

**Issue by cvoeten** [tidyverse/dplyr#4580]
dplyr is kind enough to export magrittr's `%>%` operator, but it does not export other similar operators that can be similarly useful in data-wrangling pipelines, such as the compound-assignment operator `%<>%` (which I frequently use in my pipelines when assigning contrasts to factors).

I could make a feature request that dplyr also export `%<>%`, but I was wondering: why not simply Depend on magrittr and get everything loaded automatically for free? It's already installed (as it is an Import of dplyr), and dplyr even exports one specific function from it -- why not make the other useful things available as well? This seems in line with the spirit of what dplyr's exporting of `%>%` is trying to do for the user. Conversely, exporting `%>%` but not the other functions could mislead some users users (such as a younger version of myself) to think that magrittr has been loaded for them, while in fact it has not.

I'm sure that it was a well-thought-out decision to do things this way, but I couldn't find any documentation why (and hence do not know if the reasons are still valid today). I apologize in advance for the naiveté of this feature request.

---

Brief description of the problem

```r
library(dplyr)
iris %>% head(1) #works, so makes me think I can use magrittr functions
iris %<>% head(1) #function not found
```

**Comment by hadley** [comment]
I personally regret `%<>%` as I think assignment is sufficiently special that it should be done with its own operator. See https://style.tidyverse.org/pipes.html#assignment-1
