### ISSUE TITLE
Tidy evaluation with columns starting with .d

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#4587]
I saw this today in a different context:

``` r
library(tidyverse)

tibble(d = 1) %>%
  rename(.d = d)
#> Error in rename(., .d = d): object 'd' not found
```

<sup>Created on 2019-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The call is interpreted as `rename(.data = d, tibble(d = 1))` . I wonder if we should enforce positional matching by using only `...` in the definition of the function.

**Comment by hadley** [comment]
We have an existing workaround for this, so I'm not too worried about it at the moment:

``` r
library(tidyverse)

tibble(d = 1) %>%
  rename(".d" := d)
#> # A tibble: 1 x 1
#>      .d
#>   <dbl>
#> 1     1
```

<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
