### ISSUE TITLE
Coalesce crashes integer and double

### ISSUE THREAD

**Issue by Fablepongiste** [tidyverse/dplyr#4590]
Long time already reported issue but was closed without having been fixed. 
Why is coalesce crashing and not automatically converted integer to double or double to integer, following usual coercion rules. 

Linked to https://github.com/tidyverse/dplyr/issues/2254

```r
a <- data.frame("b" = c(1L, NA, 3L), "c" = c(-1, -2, -3))
a <- dplyr::mutate(a, b = dplyr::coalesce(b, c))
Error: Argument 2 must be an integer vector, not a double vector
Call `rlang::last_error()` to see a backtrace

dplyr::coalesce(as.integer(1), 0)
Error: Argument 2 must be an integer vector, not a double vector
Call `rlang::last_error()` to see a backtrace
```

This makes coalesce really annoying to use

**Comment by batpigandme** [comment]
I think it was closed because of _where_ it's going to be fixed (in vctrs).

Either way, here's the above code as a reprex, and the backtrace I get:
``` r
a <- data.frame("b" = c(1L, NA, 3L), "c" = c(-1, -2, -3))
a <- dplyr::mutate(a, b = dplyr::coalesce(b, c))
#> Argument 2 must be an integer vector, not a double vector


dplyr::coalesce(as.integer(1), 0)
#> Argument 2 must be an integer vector, not a double vector
```

```
<error/rlang_error>
Argument 2 must be an integer vector, not a double vector
Backtrace:
 1. dplyr::coalesce(as.integer(1), 0)
 2. dplyr:::replace_with(...)
 3. dplyr:::check_type(val, x, name)
 4. dplyr:::glubort(header, "must be {friendly_type_of(template)}, not {friendly_type_of(x)}")
```

**Comment by Fablepongiste** [comment]
vctrs has been released since though,, I will check if an issue in this package relative to this.

**Comment by hadley** [comment]
This will be fixed in the next release of dplyr because will use a new version of coalesce that will use vctrs.
