### ISSUE TITLE
Regression 0.8.0.1 -> 0.8.3, using return with a purrr-style formula in rename_at

### ISSUE THREAD

**Issue by mstr3336** [tidyverse/dplyr#4596]
# Description 

From 0.8.0.1 to 0.8.3, some of my unit tests started failing on a line in which I tried to perform the following:

## My example

```r
 out <- journeys %>%
    dplyr::mutate(JKEY_OLD = JOURNEY_KEY) %>%
    dplyr::mutate(FINAL_ENC = ...) %>%
    dplyr::rename_at(dplyr::last(names(.)),
                     ~ return("IS_FINAL"))
```

*(To be honest, that code snippet probably needs a refactor anyway, looking at it 8 months later, I was still grappling with tidy semantics when I wrote it and it seems a bit hacky)*

# Related

This is analogous to the following issue: #2804 , and perhaps is an intentional design choice, but if that is the case, I would imagine it would merits a minor or major version bump, given it breaks the interface.

# Reprex

``` r
`%>%` <- magrittr::`%>%`
mtcars %>% dplyr::rename_at(dplyr::last(.), ~ return("last"))
#> Error in mtcars %>% dplyr::rename_at(dplyr::last(.), ~return("last")): could not find function "%>%"
```

<sup>Created on 2019-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
> could not find function "%>%"

Do you need to call `library(tidyverse)` in your reprex?

**Comment by romainfrancois** [comment]
if you want `return` to work, you need to actually make a function, it's not guaranteed that `~` actually makes a function or skip using `return` : 

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars <- head(mtcars, 2)

fun <- function(.x) {
  return("last")
}

mtcars %>% 
  rename_at(last(names(.)), fun)
#>               mpg cyl disp  hp drat    wt  qsec vs am gear last
#> Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4

mtcars %>% 
  rename_at(last(names(.)), ~"last")
#>               mpg cyl disp  hp drat    wt  qsec vs am gear last
#> Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

Also the `last(names(.))` might be replaced by using `last_col()` as a tidy selection: 

```
mtcars %>% 
  rename_at(vars(last_col()), fun)
#>               mpg cyl disp  hp drat    wt  qsec vs am gear last
#> Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4

mtcars %>% 
  rename_at(vars(last_col()), ~"last")
#>               mpg cyl disp  hp drat    wt  qsec vs am gear last
#> Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
