### ISSUE TITLE
`bind_cols()` crashes with tibble columns

### ISSUE THREAD

**Issue by DaniMori** [tidyverse/dplyr#4599]
Say you have two tibbles. At least one of them has a column which is a nested tibble. One would expect `bind_cols()` to be able to bind them properly. However, it throws an error.

Ideally, it should work smoothly the same way any other column binding does.

``` r
library(dplyr, quietly = TRUE)

tibble_1 <- tibble(col = "foo")
tibble_2 <- tibble(nested = tibble(bar = 33))

bind_cols(tibble_1, tibble_2)
#> Error: Argument 1 can't be a list containing data frames

# Expected:
#> # A tibble: 1 x 2
#>   col   nested$bar
#>   <chr>      <dbl>
#> 1 foo           33
```

<sup>Created on 2019-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Things are slightly better in `dev_0_9_0` but not there yet. 

``` r
library(dplyr, warn.conflicts = FALSE)

tibble_1 <- tibble(col = "foo")
tibble_2 <- tibble(nested = tibble(bar = 33))

bind_cols(tibble_1, tibble_2)
#> Warning: Outer names are only allowed for unnamed scalar atomic inputs
#> # A tibble: 1 x 2
#>   col     bar
#>   <chr> <dbl>
#> 1 foo      33
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
