### ISSUE TITLE
min_rank(), dense_rank(), cume_dist(), and percent_rank() crash R

### ISSUE THREAD

**Issue by baderstine** [tidyverse/dplyr#4603]
~~Running any code that includes~~ The functions `min_rank`, `dense_rank`, `cume_dist`, and `percent_rank` cause R/RStudio crash, when used within following MWE context.  ~~Not sure if this should be here or on RStudio's github.~~. 

```r
library(tidyverse)
data("mtcars")

tmp <- mtcars %>%
  group_by(cyl, am) %>%
  arrange(mpg, .by_group=T) %>%
  mutate(num_row_grp = min_rank())

# also try dense_rank(), cume_dist(), and percent_rank()
# row_number() is fine.

```

> > sessionInfo()
> R version 3.5.3 (2019-03-11)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Mojave 10.14.6
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] forcats_0.4.0   stringr_1.4.0   dplyr_0.8.3     purrr_0.3.2     readr_1.3.1     tidyr_1.0.0     tibble_2.1.3    ggplot2_3.2.1   tidyverse_1.2.1
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.2       cellranger_1.1.0 pillar_1.4.2     compiler_3.5.3   tools_3.5.3      zeallot_0.1.0    jsonlite_1.6     lubridate_1.7.4 
>  [9] lifecycle_0.1.0  nlme_3.1-137     gtable_0.3.0     lattice_0.20-38  pkgconfig_2.0.3  rlang_0.4.0      cli_1.1.0        rstudioapi_0.10 
> [17] haven_2.1.1      withr_2.1.2      xml2_1.2.2       httr_1.4.1       generics_0.0.2   vctrs_0.2.0      hms_0.5.1        grid_3.5.3      
> [25] tidyselect_0.2.5 glue_1.3.1       R6_2.4.0         readxl_1.3.1     modelr_0.1.5     magrittr_1.5     backports_1.1.5  scales_1.0.0    
> [33] rvest_0.3.4      assertthat_0.2.1 colorspace_1.4-1 stringi_1.4.3    lazyeval_0.2.2   munsell_0.5.0    broom_0.5.2      crayon_1.3.4

**Comment by mikmart** [comment]
Seems to also happen when running R from the terminal, so I think this is the right place.

Also, seems to be related specifically to calling `min_rank()` without arguments inside a mutating verb (`mutate`, `transmute`, `group_by`), as giving an argument works, and no argument outside these verbs throws the appropriate error.

**Comment by baderstine** [comment]
I guess my example wasn't quite "minimum".  Following also crashes:

`
library(tidyverse)
data("mtcars")
tmp <- mtcars %>%
  mutate(num_row_grp = dense_rank())

`

**Comment by batpigandme** [comment]
Traceback for above code from terminal:
```
*** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: mutate_impl(.data, dots, caller_env())
 2: mutate.tbl_df(tbl_df(.data), ...)
 3: mutate(tbl_df(.data), ...)
 4: as.data.frame(mutate(tbl_df(.data), ...))
 5: mutate.data.frame(., num_row_group = dense_rank())
 6: mutate(., num_row_group = dense_rank())
 7: function_list[[k]](value)
 8: withVisible(function_list[[k]](value))
 9: freduce(value, `_function_list`)
10: `_fseq`(`_lhs`)
11: eval(quote(`_fseq`(`_lhs`)), env, env)
12: eval(quote(`_fseq`(`_lhs`)), env, env)
13: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
14: mtcars %>% mutate(num_row_group = dense_rank())
```

**Comment by baderstine** [comment]
All is fine with an argument: 
```r
library(tidyverse)
tmp <- mtcars %>%
  mutate(r = dense_rank(mpg))

```

**Comment by romainfrancois** [comment]
Appears to be fixed in dev version (branch `dev_0_9_0`), i.e. you get a proper error: 

``` r
library(tidyverse)
tmp <- mtcars %>%
  mutate(rk = dense_rank())
#> Error in match(x, sort(unique(x))): argument "x" is missing, with no default
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

``` r
library(tidyverse)
data("mtcars")

tmp <- mtcars %>%
  group_by(cyl, am) %>%
  arrange(mpg, .by_group=T) %>%
  mutate(num_row_grp = min_rank())
#> Error in rank(x, ties.method = "min", na.last = "keep"): argument "x" is missing, with no default
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
