### ISSUE TITLE
inconsistent naming convention in mutate_at with name post-fix when .vars only has one column

### ISSUE THREAD

**Issue by Seanatpr** [tidyverse/dplyr#4606]
When input of .vars from variable, the behavior of post-fix is inconsistent between multiple columns and a single column. When multiple columns are passed in, post-fix on new column names are working as expected. However, If the input only has one column, the post-fix is not working.
Example:

> aDf <- data.frame(x = 1:3, y= 3:5)
> aDf
  x y
1 1 3
2 2 4
3 3 5
> aColsToCheck <- c('x', 'y')
> mutate_at(aDf, aColsToCheck, .funs = list(d = ~.)) 
  x y x_d y_d
1 1 3   1   3
2 2 4   2   4
3 3 5   3   5
> aColsToCheck <- c('x')
> mutate_at(aDf, aColsToCheck, .funs = list(d = ~.)) 
  x y d
1 1 3 1
2 2 4 2
3 3 5 3

**Comment by batpigandme** [comment]
Just for future reference, it's slightly easier for us to understand the problem if you use the reprex package, since it's easier to copy and paste into R and run directly. I've made one for your code, below:

``` r
library(dplyr, warn.conflicts = FALSE)
aDf <- data.frame(x = 1:3, y= 3:5)
aDf
#>   x y
#> 1 1 3
#> 2 2 4
#> 3 3 5

aColsToCheck <- c('x', 'y')
mutate_at(aDf, aColsToCheck, .funs = list(d = ~.))
#>   x y x_d y_d
#> 1 1 3   1   3
#> 2 2 4   2   4
#> 3 3 5   3   5

aColsToCheck <- c('x')
mutate_at(aDf, aColsToCheck, .funs = list(d = ~.))
#>   x y d
#> 1 1 3 1
#> 2 2 4 2
#> 3 3 5 3
```

<sup>Created on 2019-10-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Seanatpr** [comment]
@batpigandme Nice formatting from Reprex. Thank you.

**Comment by romainfrancois** [comment]
This is a feature of the `_at()` functions, you can use a named vector to disallow it: 

``` r
library(dplyr, warn.conflicts = FALSE)
aDf <- tibble(x = 1:3, y= 3:5)

aColsToCheck <- c('x')
mutate_at(aDf, aColsToCheck, .funs = list(d = ~.))
#> # A tibble: 3 x 3
#>       x     y     d
#>   <int> <int> <int>
#> 1     1     3     1
#> 2     2     4     2
#> 3     3     5     3

aColsToCheck <- c(x = 'x')
mutate_at(aDf, aColsToCheck, .funs = list(d = ~.))
#> # A tibble: 3 x 3
#>       x     y   x_d
#>   <int> <int> <int>
#> 1     1     3     1
#> 2     2     4     2
#> 3     3     5     3
```

We are currently working on alternative ways with `mutate()` + `across()` which might or might not be better for you (this needs the `across_simpler` branch: 

```
# with branch across_simpler you can get 
# "d" as a pack of columns
aDf %>% 
  mutate(across("x", list(d = ~ .)))
#> # A tibble: 3 x 3
#>       x     y   d$x
#>   <int> <int> <int>
#> 1     1     3     1
#> 2     2     4     2
#> 3     3     5     3

# which you may unpack()
aDf %>% 
  mutate(across("x", list(d = ~ .))) %>% 
  tidyr::unpack(d, names_sep = "_")
#> # A tibble: 3 x 3
#>       x     y   d_x
#>   <int> <int> <int>
#> 1     1     3     1
#> 2     2     4     2
#> 3     3     5     3
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
