### ISSUE TITLE
Grouped column dropped with no warning

### ISSUE THREAD

**Issue by leungi** [tidyverse/dplyr#4607]
Reprex below.

`group_by` contains 3 variables, but only 2 variables remain after `summarise()`; expected 3 variables.

``` r
library(dplyr)

mtcars %>% group_by(cyl, vs, am) %>% summarise(hp = mean(hp))
#> # A tibble: 7 x 4
#> # Groups:   cyl, vs [5]
#>     cyl    vs    am    hp
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     4     0     1  91  
#> 2     4     1     0  84.7
#> 3     4     1     1  80.6
#> 4     6     0     1 132. 
#> 5     6     1     0 115. 
#> 6     8     0     0 194. 
#> 7     8     0     1 300.

packageVersion("dplyr")
#> ‘0.8.3’
```

<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by cderv** [comment]
I think this is expected when you use summarise on a grouped data.frame
See https://dplyr.tidyverse.org/reference/summarise.html

> Value
> An object of the same class as .data. **One grouping level will be dropped.**

When you summarise, you reduce the number of row by applying a function to the groups. The last group is no more needed as you already applied a function to it. This allows to chain summarised operation from last group to first one
``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

mtcars %>% 
  group_by(cyl, vs, am) %>% 
  # mean by cyl, vs, am
  summarise(hp = mean(hp)) %>%
  # sum by cyl, vs (loosing am column)
  summarise(hp = sum(hp)) %>%
  # max by cyl (loosing vs column)
  summarise(hp = max(hp))
#> # A tibble: 3 x 2
#>     cyl    hp
#>   <dbl> <dbl>
#> 1     4  165.
#> 2     6  132.
#> 3     8  494.
```

<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by leungi** [comment]
Thanks for reply @cderv; point taken.

Apologies for missing on documentation; I've used `group_by` + `summarise()` combo, and this is the first time I realized of this behaviour 😅.

**Comment by cderv** [comment]
No worries. It can be suprising at first. 
Don't forget to `ungroup` after a grouped opération when you don't need groups anymore 😉 
That can prevent some undesired effect.

**Comment by leungi** [comment]
Indeed. To always `ungroup()` is what we preach in our internal R class too 👍
