### ISSUE TITLE
Should `filter()` allow named constants?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#4612]
That'd be useful for this use case: https://stackoverflow.com/a/58798578/1725177

Maybe the name-check should only be made for symbolic inputs, that would solve the issue for both `!!!` and auto-splicing.

**Comment by hadley** [comment]
Can you expand on this a bit more? What's a named constant?

**Comment by lionel-** [comment]
Examples:

```r
filter(mtcars, a = TRUE)
filter(mtcars, !!!c(a = rep(TRUE, nrow(mtcars))
```

The idea of the SO post is to prepare a data frame of filtering columns, and splice it (or auto-splice it) in `filter()`. The spliced data frame would materialise as named constants.

**Comment by hadley** [comment]
I still don't get it 😞

**Comment by lionel-** [comment]
```r
filters <- mtcars %>%
  transmute(
    cyl %in% 6:8,
    hp / drat > 50
  )

# Fails because of the name check
mtcars %>% filter(!!!filters)

# Works
mtcars %>% filter(!!!unname(filters))
```

**Comment by lionel-** [comment]
The name-check error is not very useful when constants are supplied anyway:

```r
mtcars %>% filter(!!!filters)
#> Error: `cyl %in% 6:8` (`cyl %in% 6:8 = c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE,
#> TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE,
#> FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE,
#> TRUE, FALSE)`), `hp/drat > 50` (`hp/drat > 50 = c(FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE,
#> FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE,
#> FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE,
#> FALSE, TRUE, FALSE)`) must not be named, do you need `==`?
```

**Comment by hadley** [comment]
Ah got it — it's just a matter of ignoring inputs that are constants in https://github.com/tidyverse/dplyr/blob/master/R/tbl-df.r#L166-L169
