### ISSUE TITLE
Improve error message when trying to bind list columns containing data.frames

### ISSUE THREAD

**Issue by EdwinTh** [tidyverse/dplyr#4613]
This bit me quite hard recently, very much related to #3630. 

When trying to call `bind_rows()` on  tibbles that contain data.frames the following happens (v 0.8.3)

```r
df1 <- tibble(x = 1, y = data.frame(w = 1:3, z = letters[1:3]))
df2 <- tibble(x = 2, y = data.frame(w = 4:5, z = letters[5:6]))

bind_rows(df1, df2)
#> Error: Argument 2 can't be a list containing data frames
```
It was unclear to me that "Argument 2" refers to the second column in the data frame, especially because from printing the tibbles, it did not seem my tibbles contained data.frames in the first place.

```r
df2
#> # A tibble: 2 x 2
#>       x   y$w $z   
#>   <dbl> <int> <fct>
#> 1     2     4 e    
#> 2     2     5 f   
```
If future versions will accommodate for the use of `data.frames` as suggested in #3630 this will be resolved as well. Otherwise a more informative error would be much appreciated. Suggestion:

"Column 2 is a list of data.frames. For the moment dplyr does not support this data type."

**Comment by romainfrancois** [comment]
This will work in `0.9.0` (live in the `dev_0_9_0` branch): 

``` r
library(dplyr, warn.conflicts = FALSE)

df1 <- tibble(x = 1, y = data.frame(w = 1:3, z = letters[1:3]))
df2 <- tibble(x = 2, y = data.frame(w = 4:5, z = letters[5:6]))

bind_rows(df1, df2)
#> # A tibble: 5 x 2
#>       x   y$w $z   
#>   <dbl> <int> <fct>
#> 1     1     1 a    
#> 2     1     2 b    
#> 3     1     3 c    
#> 4     2     4 e    
#> 5     2     5 f
```

**Comment by EdwinTh** [comment]
Perfect!

Wouldn't it be desirable to make it obvious from the printing that y is a list column? Such as is done when y was a `tibble` instead of a `data.frame`.  I think the current way of printing suggests the `tibbles` `df1` and `df2` are already flattened out

**Comment by romainfrancois** [comment]
Not sure what you mean, i.e. 

```r
bind_rows(df1, df2)$y
  w z
1 1 a
2 2 b
3 3 c
4 4 e
5 5 f
```

Perhaps it's a conversation to have in tibble or pillar repos ? @krlmlr

**Comment by EdwinTh** [comment]
I mean this:

```r
> tibble(x = 1, y = data.frame(w = 1:3, z = letters[1:3]))
# A tibble: 3 x 2
      x   y$w $z   
  <dbl> <int> <fct>
1     1     1 a    
2     1     2 b    
3     1     3 c    
```
as opposed to  this:

```r
> tibble(x = 1, w = 1:3, z = letters[1:3]) %>% nest(-x)
# A tibble: 1 x 2
      x           data
  <dbl> <list<df[,2]>>
1     1        [3 × 2]
```
To me the printing of `<int>` and `<fct>` very much suggests that the whole thing is flattened out.

**Comment by romainfrancois** [comment]
The `y$w` and `$z` thing hints that `w` and `z` are columns inside the `y` pack. `y` is not a list column, but a "packed" column, i.e. a column that also is a data frame : 

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = 1, y = data.frame(w = 1:3, z = letters[1:3]))
#> # A tibble: 3 x 2
#>       x   y$w $z   
#>   <dbl> <int> <fct>
#> 1     1     1 a    
#> 2     1     2 b    
#> 3     1     3 c
tibble(x = 1, y = list(data.frame(w = 1:3, z = letters[1:3])))
#> # A tibble: 1 x 2
#>       x y               
#>   <dbl> <list>          
#> 1     1 <df[,2] [3 × 2]>
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by EdwinTh** [comment]
Ah yes, that is indeed a difference. Indeed the `$` is an indication, which you'll learn soon enough (after you have been puzzled the first time you encountered it).

Even with the dollars I think the printing is confusing. From the way tibbles with list columns are displayed and how regular data frames are displayed, the way tibbles with "packed" columns signs to me their content are flattened out.

Imho the example above should be printed as:
```r
tibble(x = 1, y = data.frame(w = 1:3, z = letters[1:3]))
#> # A tibble: 3 x 2
#>       x   y
#>   <dbl> <df> 
#> 1     1 [3 x 2]
```
or maybe as:
```r
tibble(x = 1, y = data.frame(w = 1:3, z = letters[1:3]))
#> # A tibble: 3 x 2
#>       x   y
#>   <dbl> <df> 
#> 1     1 [1 x 2]
#> 2     1 [1 x 2]
#> 3     1 [1 x 2]
```
to clearly signal the content of `y` is a data frame.

**Comment by garrettgman** [comment]
FWIW I agree @EdwinTh's recommendation about printing packed columns. Eric and I got burnt by the printing/error message combo; neither highlights the presence of packed columns if you do not already know what is going on. Many new R users do not even realize that their data frame could have a column filled with data frames, but they're likely to get them if they're working with JSON, etc.

**Comment by garrettgman** [comment]
The printing seems especially likely to mislead when the column names appear in the list of column names that do not appear in the window. Being able to scan the types to spot `[df]` would make it easy to detect the presence of super-ordinary columns and debug messages like that from `bind_rows()`.
