### ISSUE TITLE
No way to remove duplicate column names

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#4615]
Some joins will allow a tibble to end up with two columns with identical names. Doing any sort of tidyselect operation on the tibble results in:

`Error: Can't bind data because some arguments have the same name`

However, there doesn't appear to be any way to remove the duplicated column.  It seems to me that using `select(-matches("duplicate name"))` or `select(-contains("duplicated name"))` ought to work since they allow catching multiples.  In addition, selecting based on the index should also work.  If columns 100 and 101 have the same name, I should be able to `select(-101)` however these all result in the same `Error: Can't bind data because some arguments have the same name`

**Comment by moodymudskipper** [comment]
I have already encountered this issue too. I believe the logic is that *dplyr* wants to enforce tidy data so you need to clean it first using tibble or tidyr, and then use dplyr functions, but the tidyverse only proposes `tibble::repair_names()` to deal with duplicate names as far as I can tell, which sometime feels clunky. Maybe an option `.name_repair = "drop"` to `tibble::as_tibble()` would help ?.

I think in any case it would be helpful to add a suggestion for a workaround to the error message select triggers.

Here's a workaround : 

``` r
packageVersion("dplyr")
#> [1] '0.8.3'
library(dplyr, warn.conflicts = F)
test <- setNames(data.frame(a=1,b=2,b=3,c=4), c("a","b","b","c"))
test
#>   a b b c
#> 1 1 2 3 4
tibble::repair_names(test,sep= "***") %>%
  select(-contains("***"))
#>   a b c
#> 1 1 2 4
```

<sup>Created on 2019-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jzadra** [comment]
Thanks for that.  My only concern about this as a long term solution would be the risk of affecting other names in the tibble unintentionally.

**Comment by moodymudskipper** [comment]
`test[!duplicated(names(test))]` is probably the safest way to go

**Comment by hadley** [comment]
We now have the tooling to handle this in the dev version of tidyselect and it should be straight forward to update dplyr.
