### ISSUE TITLE
Proposal for `pull_where()`

### ISSUE THREAD

**Issue by Shians** [tidyverse/dplyr#4616]
Would it be useful to include a `pull_where(data, var, ...)` function that works identically to `data %>% filter(...) %>% pull(var)`? This is common enough a use-case for me that I'd appreciate the compound operation.

**Comment by romainfrancois** [comment]
This is a perfect use case for `{{` but out of scope for dplyr: 

``` r
library(dplyr, warn.conflicts = FALSE)

pull_where <- function(.data, var, ...) {
  .data %>% 
    filter(...) %>% 
    pull({{var}})
}

iris %>% 
  pull_where(Sepal.Length, Species == "setosa", Sepal.Width > 3)
#>  [1] 5.1 4.7 4.6 5.0 5.4 4.6 5.0 4.9 5.4 4.8 5.8 5.7 5.4 5.1 5.7 5.1 5.4
#> [18] 5.1 4.6 5.1 4.8 5.0 5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.0 5.5 4.9 5.1
#> [35] 5.0 4.4 5.0 5.1 5.1 4.6 5.3 5.0
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
