### ISSUE TITLE
`if_else` not allowing `missing()` argument when included as part of function.

### ISSUE THREAD

**Issue by jeffreyxparker** [tidyverse/dplyr#4626]
`if_else` doesn't seem to allow `missing()` arguments when included as part of a function.

```r
# Working
working_function <- function(input_arg) {
  ifelse(missing(input_arg),"there is no input",paste0("you inputted: ", input_arg))
}
working_function()
working_function("test")

# Not working
non_working_function <- function(input_arg) {
  if_else(missing(input_arg),"there is no input",paste0("you inputted: ", input_arg))
}
non_working_function()
non_working_function("test")
```

**Comment by jeffreyxparker** [comment]
I *think* this is because `if_else` is tries to evaluate both the `true` and `false` parts of the function. But since the `input_arg` is missing it can't evaluate the `false` part. But it's odd because it should never have to evaluate the `false` part. It's weird that it would work only some of the times.

**Comment by romainfrancois** [comment]
``` r

fun <- function(input_arg) {
  if(missing(input_arg)) {
    "there is no input"
  } else {
    paste0("you inputted: ", input_arg)
  }
}
fun()
#> [1] "there is no input"
fun("test")
#> [1] "you inputted: test"
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by jeffreyxparker** [comment]
Is there a principle behind this? I see the workarounds, but I thought it was strange that `if_else` would work sometimes and not other times.

**Comment by romainfrancois** [comment]
`if_else()` checks that both have same type, therefore it has to evaluate them. the doc says it: 

```
Values to use for TRUE and FALSE values of condition. They must be either the same length as condition, or length 1. They must also be the same type: if_else() checks that they have the same type and same class. All other attributes are taken from true.
```
