### ISSUE TITLE
Would it be beneficial for na_if() to accept NaN as a y argument?

### ISSUE THREAD

**Issue by hlynurhallgrims** [tidyverse/dplyr#4627]
I got to thinking. I was using `tidyr::fill()`, expecting it to replace some `NaN`s in the same way as it does for `NA`s. Seeing that it doesn't and understanding that it's [not desireable for it to do so](https://github.com/tidyverse/tidyr/issues/274) I wanted to raise the question if  `dplyr::na_if()` should perhaps be made a more convenient alternative to `dplyr::if_else()` when you want to explicitly turn `NaN`s to `NA`s. 

In the cases where you'd want to carry forward the last observation before a `NaN` you could use `na_if(x, y = NaN)` before using `tidyr::fill()`.

A reprex follows:

``` r
vector <- c(1:5, rep(NaN, 5))
vector
#>  [1]   1   2   3   4   5 NaN NaN NaN NaN NaN

#This changes nothing
dplyr::na_if(x = vector, y = NaN)
#>  [1]   1   2   3   4   5 NaN NaN NaN NaN NaN

# Perhaps this is desireable? Perhaps not?
na_if <- function(x, y) {
# check_length() function left out for convenience here

if (is.nan(y)) {
  x[is.nan(x)] <- NA
} else {
  x[x == y] <- NA
}
x
}

# Our updated na_if function:
na_if(x = vector, y = NaN)
#>  [1]  1  2  3  4  5 NA NA NA NA NA
```

Created on 2019-11-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Minimal reprex:

``` r
dplyr::na_if(c(NA, NaN, 1), 1)
#> [1]  NA NaN  NA
```

<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Moving this issue to funs, which is where the fix will eventually happen.
