### ISSUE TITLE
Add argument to recode to allow for replacement of empty string

### ISSUE THREAD

**Issue by snaut** [tidyverse/dplyr#4628]
Recode currently does not allow to replace the empty string by a value directly, because the empty string can't be used as a name in a named argument.

```r
test <- c("", "A", NA_character_)

dplyr::recode(test, "A"=1, .missing=2)
# [1] NA  1  2
# Warning message:
# Unreplaced values treated as NA as .x is not compatible. Please specify
# replacements exhaustively or supply .default 
dplyr::recode(test, "A"=1, .missing=2, ``=3)
# Error: attempt to use zero-length variable name
```

It would be handy to have an argument for replacement of the empty string, like `.missing` for missing values. This could look like this in practice:

```r
test <- c("", "A", NA_character_)
dplyr::recode(test, "A"=1, .missing=2, .emptystring=3)
# [1] 3 1 2
```

A relevant stack-overflow question regarding this is [here](https://stackoverflow.com/questions/49006519/recode-empty-string-with-dplyrrecode).

**Comment by hadley** [comment]
Closing this issue here because it really requires a full rethinking of `recode()`, which is going to happen in the funs package.
