### ISSUE TITLE
mutate( <grouping function -- n(), mean()> ) %>% filter( )  with null set results

### ISSUE THREAD

**Issue by cochetti** [tidyverse/dplyr#4629]
Using `mutate` with a `filter` seems to provide inconsistent results when the filter results in a null set. I have included examples below. 

When using `mutate` with a multi-line function like `n()` or `mean()`, mutate correctly computes the count of rows by a variable as needed for ungrouped or grouped data. The manpage for `mutate` uses the starwars example to compute normalized masses `mass / mean( mass )` and demonstrates the differences between grouped and ungrouped data.  **Example 4** uses this same example with a filter to show where this leads to inconsistent output from using `summarise` in regards to null set results. 

**Example 1** -- expected behavior
```r
a=c(1, 1, 2, 3) 
b=c(11, 11, 22, 33)
c <- data.frame( a, b )
c %>% group_by( a ) %>% mutate( N = n() )  %>% filter( N > 1 )  %>% summarise( nDupes = n() ) %>% pull()
[1] 2
c %>% group_by( a ) %>% mutate( N = n() )  %>% filter( N == 1 )  %>% summarise( nSingles = n() ) %>% pull(nSingles)
[1] 1 1
```

In Example 2, the filter results in a null set. Here trying to use pull() or even summarise gives a NA integer(0) result and refuses to provide an output because of the null set encountered.  This seems like an inconsistent result than the behavior one expects given that the above works. 

**Example 2**  --null set behavior with `mutate`
```r
a=c(1, 2, 3) 
b=c(11, 22, 33)
c <- data.frame( a, b )
c %>% group_by( a ) %>% mutate( N = n() ) %>% filter( N > 1 ) %>% summarise( nDupes = n() ) 
# A tibble: 0 x 2
# ... with 2 variables: a <dbl>, nDupes <int>
c %>% group_by( a ) %>% mutate( N = n() )
# A tibble: 3 x 3
# Groups:   a [3]
      a     b     N
  <dbl> <dbl> <int>
1     1    11     1
2     2    22     1
3     3    33     1
c %>% group_by( a ) %>% mutate( N = n() )  %>% filter( N > 1 ) 
# A tibble: 0 x 3
# Groups:   a [0]
# ... with 3 variables: a <dbl>, b <dbl>, N <int>

c %>% group_by( a ) %>% mutate( N = n() )  %>% filter( N > 1 )  %>% summarise( nDupes = n() ) 
# A tibble: 0 x 2
# ... with 2 variables: a <dbl>, nDupes <int>

c %>% group_by( a ) %>% mutate( N = n() )  %>% filter( N > 1 )  %>% summarise( nDupes = n() ) %>% pull(nDupes)
integer(0)

c %>% group_by( a ) %>% mutate( N = n() )  %>% filter( N == 1 )  %>% summarise( nSingles = n() ) %>% pull(nSingles)
[1] 1 1 1
```

In Example 3, the same computation when performed with summarise computes accurately.  I realize this has to do with minute differences between mutate/summarise and how they interact with grouped data.  

**Example 3** -- null set behavior with `summarise`
```r
c %>% group_by( a ) %>% summarise( N = n() ) %>% filter( N > 1 ) %>% count() 
# A tibble: 1 x 1
#      n
#  <int>
#1     0
c %>% group_by( a ) %>% summarise( N = n() ) %>% filter( N > 1 ) %>% summarise( nDupes = n() ) 
# A tibble: 1 x 1
#  nDupes
#   <int>
#1      0
```

The reason I raise the issue is that the manpage for mutate points out that mean( ) is interpreted differently if used on it's own or in grouped data (https://dplyr.tidyverse.org/reference/mutate.html#grouped-tibbles). That said, if one were to filter on that data, it too is subject to this null set problem (Example 4). 

**Example 4** -- starwars data with `mutate` and `filter` with null sets
```r
starwars %>%
+     group_by(gender) %>%
+     mutate( normalizedMass = mass / mean(mass, na.rm = TRUE)) %>%
+     pull( normalizedMass )
# [1] 0.9505639 1.6187050 0.6906475 1.6789181 0.9070715 1.4813984 1.3883747 0.6906475 #1.0369788 0.9505639 1.0369788        NA 1.3826385 0.9875989 0.9135290 1.0000000
#[17] 0.9505639 1.3579485 0.2098648 0.9258740 0.9653779 1.0000000 1.3949834 0.9752539 #0.9752539 1.0246339        NA        NA 0.2468997 0.8394591 1.0987038 1.1110488
#[33]        NA 0.8147691 1.0122889        NA        NA        NA 0.4937995        NA        NA #0.9875989        NA 1.0181414 0.5555244        NA 0.8024241 1.0369788
#[49] 1.0122889 1.0740138        NA 0.9255831        NA        NA 0.9875989        NA 1.0493238        #NA        NA 0.9875989 1.0403554 0.9255831        NA 0.9875989
#[65]        NA 0.9752539 1.0181414 1.2591886 1.0863588        NA        NA 0.1851748        NA #0.5925593        NA 1.0551648 1.9628528 1.6789181 0.9752539 0.8885598
#[81] 0.9875989        NA        NA        NA        NA        NA 0.8330248

starwars %>%
+     group_by(gender) %>%
+     mutate( normalizedMass = mass / mean(mass, na.rm = TRUE)) %>%
+     filter( normalizedMass > 3 ) %>% 
+     pull( normalizedMass )
#numeric(0)

starwars %>%
+     group_by(gender) %>%
+     mutate( normalizedMass = mass / mean(mass, na.rm = TRUE)) %>%
+     filter( normalizedMass > 1 ) %>% 
+     pull( normalizedMass )
# [1] 1.618705 1.678918 1.481398 1.388375 1.036979 1.036979 1.382638 1.357948 1.394983 #1.024634 1.098704 1.111049 1.012289 1.018141 1.036979 1.012289 1.074014
#[18] 1.049324 1.040355 1.018141 1.259189 1.086359 1.055165 1.962853 1.678918
```

**Comment by hadley** [comment]
Can you please provide a minimal reproducible example using the [reprex](http://reprex.tidyverse.org) package? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never made a minimal reprex before, there is lots of good advice [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by hadley** [comment]
And can you please just provide one clear example of the problem?

**Comment by cochetti** [comment]
Just seeing this due to Gmail filtering the reply notice to the wrong folder. I need to learn how to use reprex and will get back to you.

**Comment by hadley** [comment]
I've re-read your issue, and unfortunately I can't see the problem. In the following simple example, all the results look consistent to me:

``` r
library(dplyr, warn.conflicts = FALSE)
df <- data.frame(g = c(1, 2, 2, 3, 3, 3))

df %>% group_by(g) %>% filter(n() == 1) %>% summarise(n = n())
#> # A tibble: 1 x 2
#>       g     n
#>   <dbl> <int>
#> 1     1     1
df %>% group_by(g) %>% summarise(n = n()) %>% filter(n == 1)
#> # A tibble: 1 x 2
#>       g     n
#>   <dbl> <int>
#> 1     1     1

df %>% group_by(g) %>% filter(n() > 1) %>% summarise(n = n())
#> # A tibble: 2 x 2
#>       g     n
#>   <dbl> <int>
#> 1     2     2
#> 2     3     3
df %>% group_by(g) %>% summarise(n = n()) %>% filter(n > 1)
#> # A tibble: 2 x 2
#>       g     n
#>   <dbl> <int>
#> 1     2     2
#> 2     3     3

df %>% group_by(g) %>% filter(n() > 3) %>% summarise(n = n())
#> # A tibble: 0 x 2
#> # … with 2 variables: g <dbl>, n <int>
df %>% group_by(g) %>% summarise(n = n()) %>% filter(n > 3)
#> # A tibble: 0 x 2
#> # … with 2 variables: g <dbl>, n <int>
```

<sup>Created on 2019-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
