### ISSUE TITLE
Segfault in rbind_all

### ISSUE THREAD

**Issue by hoesler** [tidyverse/dplyr#463]
rbind_all applied to a list of data frames with special columns like in

``` R
dfl <- data.frame(x = I(list(1:2, 1:3, 1:4)))
rbind_all(list(dfl, dfl))
```

results in a segfault:

```
Invalid memory access of location 0x0 rip=0x10a21b5a8

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .Call("dplyr_rbind_all", PACKAGE = "dplyr", dots)
 2: rbind_all(list(dfl, dfl))
```

This could be related to #459.

**Comment by yasminlucero** [comment]
I just ran into this. 

------------------------
*** caught segfault ***
address 0x20000010, cause 'memory not mapped'

Traceback:
 1: .Call("dplyr_rbind_all", PACKAGE = "dplyr", dots)
 2: rbind_all(data)
 3: readData()
aborting ...
Segmentation fault (core dumped)
------------------------

The object 'data' is a list where each element is a data.frame with 22 columns. Each data.frame in the list was produced by reading a delimited file using fread and passing this list of column classes: 

class = c(rep('character', 4), rep('integer', 8), rep('numeric', 4), rep('integer', 6))

This same code runs fine on dplyr_0.2. Upgrading dplyr surfaced this issue.

I am running dplyr_0.3.0.2 and R v 3.1.2 on Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-69-generic x86_64).

**Comment by yasminlucero** [comment]
@romainfrancois I will, as soon as I find a moment
