### ISSUE TITLE
 [Feature request]: Add_row to insert a dataframe row

### ISSUE THREAD

**Issue by sibojan9** [tidyverse/dplyr#4632]
Right now, add_row can easily add a vector. e.g.
` df %>% add_row(x  = 4, y = 0, .before = 2)`

Is it possible to add a row from a dataframe, e.g.
`df %>% add_row(mtcars[2] .before = 2)`?

I have not not find any function within dplyr to allow easy insertion of a row to a dataframe.

Thanks,

Sibo

**Comment by romainfrancois** [comment]
`mtcars[2]` is not a row, `add_row()` can handle adding a row: 

``` r
library(tibble)

mtcars[2]
#>                     cyl
#> Mazda RX4             6
#> Mazda RX4 Wag         6
#> Datsun 710            4
#> Hornet 4 Drive        6
#> Hornet Sportabout     8
#> Valiant               6
#> Duster 360            8
#> Merc 240D             4
#> Merc 230              4
#> Merc 280              6
#> Merc 280C             6
#> Merc 450SE            8
#> Merc 450SL            8
#> Merc 450SLC           8
#> Cadillac Fleetwood    8
#> Lincoln Continental   8
#> Chrysler Imperial     8
#> Fiat 128              4
#> Honda Civic           4
#> Toyota Corolla        4
#> Toyota Corona         4
#> Dodge Challenger      8
#> AMC Javelin           8
#> Camaro Z28            8
#> Pontiac Firebird      8
#> Fiat X1-9             4
#> Porsche 914-2         4
#> Lotus Europa          4
#> Ford Pantera L        8
#> Ferrari Dino          6
#> Maserati Bora         8
#> Volvo 142E            4

mtcars[1, ] %>% 
  add_row(mtcars[2, ])
#>   mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> 1  21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> 2  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by sibojan9** [comment]
I meant the rows of mtcars[2, ]. I am using dplyr 0.8.3, but I got this error. 

``` r
library(tidyverse)
mtcars[1, ] %>% add_row(mtcars[2, ])
#> Error: New rows in `add_row()` must use columns that already exist:
#> * Can't find column `mtcars[2, ]` in `.data`.
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks for your help.

**Comment by romainfrancois** [comment]
This works with the dev version.

**Comment by sibojan9** [comment]
Hi,

I struggled to install the dev version of dplyr from Github. The installation reported many errors (see belows) and stopped run. Do you mind sharing the source code of the new add_row function? So I can use it in advance. Hopefully, the CRAN version will be updated soon. Thanks.

![Snap25](https://user-images.githubusercontent.com/11802171/69724750-5fd18f80-10d1-11ea-958b-9b172de8600b.jpg)
![Snap26](https://user-images.githubusercontent.com/11802171/69724763-69f38e00-10d1-11ea-88a1-aafacb78991d.jpg)

**Comment by romainfrancois** [comment]
`add_row()` is in the `tibble` package.

**Comment by RemPsyc** [comment]
Sorry for reopening this issue. This works, as said before:

```
library(tibble)
mtcars[1, ] %>% add_row(mtcars[2, ])
```

But not e.g., adding row names:

```
mtcars[1, ] %>% add_row(names(mtcars))

Error: New rows can't add columns.
x Can't find column `names(mtcars)` in `.data`.
```

It would be nice to be able to provide any vector such as row names to fill the row automatically without having to define them manually such as:

```
mtcars[1,] %>% 
    mutate(across(everything(), as.character)) %>%
    add_row(
        mpg = "mpg",
        cyl = "cyl",
        disp = "disp",
        hp = "hp",
        drat = "drat",
        wt = "wt",
        qsec = "qsec",
        vs = "vs",
        am = "am",
        gear = "gear",
        carb = "carb"
)
```

Note: this would be useful for purposes of presenting long tables.

**Comment by romainfrancois** [comment]
One could define a `add_row2()` function, e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)
library(rlang)

add_row2 <- function(.data, x) {
  add_row(
    .data, 
    tibble(!!!set_names(x, names(.data)))
  )
}

mtcars[1,] %>% 
  mutate(across(everything(), as.character)) %>%
  add_row2(names(mtcars))
#>           mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> Mazda RX4  21   6  160 110  3.9 2.62 16.46  0  1    4    4
#> ...2      mpg cyl disp  hp drat   wt  qsec vs am gear carb
```

<sup>Created on 2022-01-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by RemPsyc** [comment]
Beautiful! And really helpful. I don't think I could have come up with that myself. I suppose it is for personal use only and there's little chance it will make it as `tibble::add_row2`?

**Comment by Sibojang9** [comment]
Thank you all. That is very useful.
