### ISSUE TITLE
filter() with named predicate vector

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#4638]
throws an unrelated error. The two expressions below should produce identical results.

``` r
library(tidyverse)
tibble(a = TRUE) %>% filter(a)
#> # A tibble: 1 x 1
#>   a    
#>   <lgl>
#> 1 TRUE
tibble(a = c(a = TRUE)) %>% filter(a)
#> Error: filter() expressions should return logical vectors of the same size as the group
```

<sup>Created on 2019-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This is new in the dev version

**Comment by romainfrancois** [comment]
I can use `is.logical()` instead, this comes from : 

```r
> vctrs::vec_is(c(a = TRUE), logical())
[1] FALSE
```

**Comment by hadley** [comment]
Or possibly `inherits(x, "logical")`.  But why does `vec_is()` not think this is a logical?
