### ISSUE TITLE
Proposal of 'validate_length' TRUE/FALSE for case_when()

### ISSUE THREAD

**Issue by msberends** [tidyverse/dplyr#4644]
I understand that functions should be strict and always have the same type of output, which is why `dplyr` contains `if_else()`. But for `case_when()` I would really like an argument like `validate_length` to allow different lengths as output. It should always return the same class, as it does now, but I would like a user option to allow the output length to be more flexible.

I think it's easy to come up with a lot of use cases, but I'll share one of ours I ran into this week. We are sending weekly mails to hospitals in our region about the regional trend of flu. For some hospitals, the 'flu team' consists of 2 people, for other hospitals this could be 10. And although we would like fluteam@hospA.com to exist, it does not and that's out of our hands. So I would like something like this:
```r
for (hospital in all_hospitals) {
  send_to <- case_when(hospital == "Hospital A" ~ c("person_1@hospA.com",
                                                    "person_2@hospA.com"),
                       hospital == "Hospital B" ~ c("person_1@hospB.com",
                                                    "person_2@hospB.com",
                                                    "person_3@hospB.com"),
                       hospital == "Hospital C" ~ c("person_1@hospC.com",
                                                    "person_2@hospC.com"),
                       hospital == "Hospital D" ~ c("person_1@hospD.com",
                                                    "person_2@hospD.com",
                                                    "person_3@hospD.com",
                                                    "person_4@hospD.com"),
                       validate_length = FALSE)
  mail_it("some content", to = send_to)
}
```

Without `validate_length` it takes an annoying number of lines with `if_else()`s to accomplish the same thing. It does good that `case_when()` is very strict about its output, but for *length* I think users should be able to choose for less strictness when they need to.

**Comment by romatik** [comment]
Can you give another example where something like this is helpful/needed? In your specific case I would just use list and extract elements with the name:

``` r
send_to <- list("Hospital A" = c("person_1@hospA.com", "person_2@hospA.com"),
                "Hospital B" = c("person_1@hospB.com", "person_2@hospB.com", 
                                 "person_3@hospB.com"),
                "Hospital C" = c("person_1@hospC.com", "person_2@hospC.com"),
                "Hospital D" = c("person_1@hospD.com", "person_2@hospD.com", 
                                 "person_3@hospD.com", "person_4@hospD.com"))
hospital <- "Hospital A"
send_to[[hospital]]
#> [1] "person_1@hospA.com" "person_2@hospA.com"
```

<sup>Created on 2019-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by msberends** [comment]
Thanks for your suggestion. 

I don’t think the point is to come up with more examples. There are always a dozen solutions to not use `if_else()`s due to the flexibility of R, so pretty much any example would have multiple solutions, without the use of `if_else()` or `case_when()` at all. 
I think the point is that `case_when()` was meant as a replacement for (a lot of) `if_else()`s. And sometimes a fixed output length is too restrictive IMHO.

I don’t think it’s a big change to add it. If you like, I could open a pull request?

**Comment by romatik** [comment]
I just realized I have "Contributor" next to my name, so it might look like I can actually decide something like that :). This is not the case, I was just trying to elaborate on your use-case for actual maintainers of the package to understand it better.

I agree with you, that in general, it might look like it's possible to have a situation like yours and it makes sense to extend `case_when`, but one of cornerstones in `tidyverse` is to make functions do one thing and do it well. The more things you add to it, more difficult it becomes to reason about and maintain such function. That was the only reason I've asked for a different example where it will be obvious that it's only `case_when` that can solve your problem.

Just as an example of added complexity: how should `case_when` behave with `validate_length = FALSE` when applied to a column of a database?

**Comment by msberends** [comment]
> so it might look like I can actually decide something like that :)

Jup 😝 
No problem!

> Just as an example of added complexity: how should case_when behave with validate_length = FALSE when applied to a column of a database?

Now that's a great counterargument. Erm, no idea. I guess R will throw an error, but I don't know if that's solid enough...

**Comment by hadley** [comment]
It sounds like you are looking for a non-vectorised `case_when()`, which in this case is `switch()`:

```R

send_to <- switch(hospital,
  A = c("person_1@hospA.com","person_2@hospA.com"),
  B = c("person_1@hospB.com","person_2@hospB.com", "person_3@hospB.com"),
  C = c("person_1@hospC.com","person_2@hospC.com"),
  D = c("person_1@hospD.com","person_2@hospD.com", "person_3@hospD.com", "person_4@hospD.com"),
  stop("Unknown hospital")
)
```

I don't think `validate_length` argument is appropriate for `case_when()` because it would fundamentally change the operation of the function, which I generally believe is a bad thing to do with an argument.
