### ISSUE TITLE
everything() is not documented

### ISSUE THREAD

**Issue by jpeacock29** [tidyverse/dplyr#4650]
The `everything()` function is not documented. The documentation for [`select()`](https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/select) has a link, but [that link](https://www.rdocumentation.org/link/everything()?package=dplyr&version=0.7.8&to=%3Deverything) redirects to the homepage.

**Comment by JoshuaSturm** [comment]
The helper functions for select are imported from [tidyselect](https://tidyselect.r-lib.org/), where they are documented ([see here](https://tidyselect.r-lib.org/reference/select_helpers.html)).

Would a pull request with an updated link pointing to the tidyselect documentation suffice?

**Comment by hadley** [comment]
I think we'll want to come back to this in a little bit since the next version of tidyselect is going to provide more/different functions, so we'll want to make sure that we get them all.

**Comment by hadley** [comment]
Merged into #4597
