### ISSUE TITLE
top_n() and top_frac() have optional argument `wt` with no default

### ISSUE THREAD

**Issue by rossellhayes** [tidyverse/dplyr#4695]
`top_n()` and `top_frac()`'s argument `wt` is optional but has no default.
This results in warning "argument 'wt' is missing, with no default" in Rstudio if diagnostic option "Check arguments to R function calls" is enabled.

Should these definitions be changed to `top_*(x, n, wt = NULL)` to match, for example, the default used in `count()` and `tally()`?

``` r
library(dplyr)

mtcars %>%
  top_n(1)
#> Selecting by carb
#>   mpg cyl disp  hp drat   wt qsec vs am gear carb
#> 1  15   8  301 335 3.54 3.57 14.6  0  1    5    8

mtcars %>%
  top_frac(1/32)
#> Selecting by carb
#>   mpg cyl disp  hp drat   wt qsec vs am gear carb
#> 1  15   8  301 335 3.54 3.57 14.6  0  1    5    8
```

**Comment by hadley** [comment]
This is fixed in #4687 with the introduction of new `slice_min()`/`slice_head()` which have a better interface (including better defaults)
