### ISSUE TITLE
bind_rows() old edge case

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4697]
We have these in a skipped test. 

``` r
library(dplyr, warn.conflicts = FALSE)

my_list <- list(list(x = 1, y = "a"), list(x = 2, y = "b"))
bind_rows(my_list)
#> Error: Column names `x`, `y` must not be duplicated.
bind_rows(list(x = 1, y = "a"), list(x = 2, y = "b"))
#> Error: Column names `x`, `y` must not be duplicated.
```

<sup>Created on 2020-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

```r
test_that("bind_rows can handle lists (#1104)", {
  skip("to be discussed")
  my_list <- list(list(x = 1, y = "a"), list(x = 2, y = "b"))
  res <- bind_rows(my_list)
  expect_equal(nrow(res), 2L)
  expect_is(res$x, "numeric")
  expect_is(res$y, "character")

  res <- bind_rows(list(x = 1, y = "a"), list(x = 2, y = "b"))
  expect_equal(nrow(res), 2L)
  expect_is(res$x, "numeric")
  expect_is(res$y, "character")
})
```

Is that time to let this old behavior go ?

**Comment by romainfrancois** [comment]
Also: 

```r
test_that("bind_cols() err for non-data frames (#2373)", {
  skip("to be discussed")
  df1 <- tibble(x = 1)
  df2 <- structure(list(x = 1), class = "blah_frame")

  expect_error(
    bind_cols(df1, df2),
    "Argument 2 must be a data frame or a named atomic vector, not a blah_frame",
    fixed = TRUE
  )
})
```

**Comment by hadley** [comment]
I think we should deprecate this behaviour, but we'll need to preserve it because I think otherwise we'll break too much existing code.

**Comment by hadley** [comment]
To be clear, I think we should keep the behaviour where `bind_rows()` and `bind_cols()` automatically splace lists as much as possible, but that code path should be deprecated with a warning to tell the user to use explicit splicing with `!!!`.

**Comment by hadley** [comment]
I realised that this behaviour is actually quite important for `map_dfr()` support so I figured out a way to fix it 😄 

(The absence of the `bind_col()` error is, fine I think)

**Comment by romainfrancois** [comment]
Thanks. I had been working on this yesterday, without much satisfaction 😬
