### ISSUE TITLE
Write colwise vignette

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#4704]
Focussing on `across()` function, with a little bit about df-columns.

Topics:

* Using `across()` in `summarise()` and `mutate()`

* How to convert existing `_if`, `_at`, `_all` calls

* Compare `mutate_all()` with `mutate(across(everything()))` wrt to progressive modification of a column, like `~ .x / cyl`

* Applying multiple functions 
   * Repeated use of across(), 
   * `across()` and with multiple functions
   * briefly explain df-columns and reference tidyr::unpack()

(Matches #4767)

**Comment by hadley** [comment]
Call it `colwise` to match.

**Comment by hadley** [comment]
* How to convert existing `_if`, `_at`, `_all` calls
* Compare `mutate_all()` with `mutate(across(everything()))` wrt to progressive modification of a column
* Apply multiple functions, with repeated use of `across()`, and with multiple functions. Need to briefly explain df-columns and reference `tidyr::unpack()`

**Comment by BenCarlsen** [comment]
This is a better name than `across`
