### ISSUE TITLE
broken links in installed documentation

### ISSUE THREAD

**Issue by archenemies** [tidyverse/dplyr#4725]
The vignettes that come with the Dplyr package (which I just installed) are great, but they have some broken links:

This file file:///home/me/.local/lib/x86_64/R/packages/dplyr/doc/index.html

links to e.g. file:///home/me/.local/lib/x86_64/R/library/dplyr/doc/dplyr.html

which is nonexistent; but if I change "library" to "packages" then it works.

I got there from here:

    > library(help=dplyr)
                    Information on package ‘dplyr’

    Description:

    Type:               Package
    Package:            dplyr
    Title:              A Grammar of Data Manipulation
    Version:            0.8.3

    ....
    Further information is available in the following vignettes in
    directory ‘/home/me/.local/lib/x86_64/R/packages/dplyr/doc’:

    compatibility: dplyr compatibility (source, pdf)
    dplyr: Introduction to dplyr (source, pdf)
    programming: Programming with dplyr (source, pdf)
    two-table: Two-table verbs (source, pdf)
    window-functions: Window functions (source, pdf)

**Comment by hadley** [comment]
This is some sort of package install issue; dplyr doesn't generate these links.

**Comment by archenemies** [comment]
Meaning an R bug? Anyways, it fixed with:

    ln -sr .local/lib/x86_64/R/{packages,library}
