### ISSUE TITLE
New [.tbl_df method breaks many dplyr methods

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4736]
Should `df` be grouped after `$<-` ? 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- group_by(tibble(x = 1), x)
df$y <- 2
df
#> # A tibble: 1 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
```

<sup>Created on 2020-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
Hmmm, I see

``` r
library(dplyr, warn.conflicts = FALSE)

df <- group_by(tibble(x = 1), x)
df$y <- 2
df
#> # A tibble: 1 x 2
#> # Groups:   x [1]
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
```

<sup>Created on 2020-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Might be different versions of tibble; your fix is safer.

**Comment by romainfrancois** [comment]
Yeah that's very likely a problem from dev `tibble` or `vctrs` these few things started on actions when sending jobs for #4733 which is unrelated.

**Comment by romainfrancois** [comment]
I can only do a wild guess at this time, but this commit seem related: 

https://github.com/tidyverse/tibble/commit/ba216dc4bd4c100b579fe07630b28c035880d0bd#diff-540c0e3edd23d1e0767808051997d469

**Comment by hadley** [comment]
Ok, makes sense.
