### ISSUE TITLE
mutate(<rowwise>) should return a rowwise_df

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4740]
``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = 1:2) %>% 
  rowwise() %>% 
  mutate(y = x) %>% 
  str()
#> tibble [2 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ x: int [1:2] 1 2
#>  $ y: int [1:2] 1 2
```

<sup>Created on 2020-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by romainfrancois** [comment]
Looks like this is because there's no `[.rowwise` : 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- rowwise(tibble(x = 1:2))
df[, "y"] <- 2
df
#> # A tibble: 2 x 2
#>       x     y
#>   <int> <dbl>
#> 1     1     2
#> 2     2     2
```

<sup>Created on 2020-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
I think we might change `rowwise()` to be an attribute of `group_by()` so we can leave this for now.

**Comment by hadley** [comment]
Part of #4736
