### ISSUE TITLE
Documentation Request -- Black Box Warnings

### ISSUE THREAD

**Issue by cochetti** [tidyverse/dplyr#4757]
**Background:** The US Federal Drug Administration will include a "black box warning" on any medication that is related to a serious hazard to patients. It contains serious warnings about the medicine which every prescriber should review due to serious implications for patient health and outcomes. For example, the well-known drug thalidomide which was used to ease nausea ("morning sickness") in pregnancy in the 1950s and was later discovered to cause serious birth defects. As such, thalidomide now carries a "black box warning" in the prescribers information to convey important information that may otherwise be overlooked. Here is an example of how they look in the medication context: [thalidomide package insert](https://www.accessdata.fda.gov/drugsatfda_docs/label/2006/021430lbl.pdf)

**Proposal:** Include a similar "black box warning" on functions in the tidyverse that mimic those that appear in other languages and have important caveats or differences that would result in discrepancies. Additionally, a "black box warning" could be included on updates that are not backward compatible and may cause code based on legacy versions to run and provide inaccurate results. 

I realize all efforts are taken to limit these scenarios, and this may be a feature of limited-use, and frankly that is ideal. It is available and it's relative sparing use adds to the import that should be taken to the message therein.

Examples where a "black box warning" might have be included: 

- #4494 - top_n(df, n) returns bottom n rows 
- #3493 - translation of setdiff for Oracle should be MINUS
- #3216 - as.data.frame() does not respect column order for DB backends

These wouldn't have to be permanent demarcations. I would just hope that they existed on the documentation and manual pages while exists a discrepancy between the R/other language or current/legacy function results.

**Comment by hadley** [comment]
I think the idea has some merits, but I don't think there's anything in dplyr that's as dangerous to your health as thalidomide. Unfortunately, I don't find your selection of issues particularly compelling — `top_n()` is being superseded by `slice_min()`/`slice_max()` in dplyr 1.0.0 (and `top_n()` now contains a description of why), and the other two are bugs that have been fixed.
