### ISSUE TITLE
na.rm = TRUE argument for first and last functions

### ISSUE THREAD

**Issue by zx8754** [tidyverse/dplyr#4759]
Similar to `n_distinct(..., na.rm = FALSE)` can we have `na.rm` argument for `first/last` functions?

Current solution for `dplyr::first`:

```R
library(dplyr) # R version 3.6.2 | dplyr_0.8.3

first(c(NA, 11, 22))
# [1] NA

# current solution
first(na.omit(c(NA, 11, 22)))
# [1] 11
```

Suggested feature:
```R
first(c(NA, 11, 22), na.rm = TRUE)
```

Related SO post: [dplyr::first() to choose first non NA value](https://stackoverflow.com/q/52221044/680068)

**Comment by hadley** [comment]
I think `na.rm` makes sense for summarising functions that compute on the values, but it feels a bit weird to me in these functions that are primarily about indexing.
