### ISSUE TITLE
Reorder function reference sections?

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/dplyr#4761]
The current order of sections in function reference is:
- Single-table verbs
- Two-table verbs
- Grouping
- Vector functions
- Data
- Computation on groups
- Remote tables
- Questioning/retired
- Single-table helpers

At the very least, I think `Questioning/retired` should be last; but I also think `Data` is in an odd spot.

**Comment by hadley** [comment]
It's because "computation of groups" is experimental, "remote tables" is being deprecated (moved to dbplyr), and the "single-table helpers" will be retired.

**Comment by batpigandme** [comment]
OK, that's sound enough reasoning.
