### ISSUE TITLE
Coercion rules section in two table vignettes needs an update

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#4765]
* [ ] Refer to vctrs for underlying logic
* [ ] Emphasise that this is same logic used by `mutate()` etc
* [ ] Make sure text is matches latest results

**Comment by djnavarro** [comment]
Spoke with @DavisVaughan, we are wondering if this is a bug. It is different from the CRAN version

development version:

``` r
library(tibble)
library(dplyr)
df1 <- tibble(x = 1, y = factor("a"))
df2 <- tibble(x = 2, y = factor("b"))
full_join(df1, df2)
#> Joining, by = c("x", "y")
#> # A tibble: 2 x 2
#>       x y    
#> * <dbl> <fct>
#> 1     1 a    
#> 2     2 <NA>
```

<sup>Created on 2020-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


cran version:

``` r
library(tibble)
library(dplyr)
df1 <- tibble(x = 1, y = factor("a"))
df2 <- tibble(x = 2, y = factor("b"))
full_join(df1, df2) 
#> Joining, by = c("x", "y")
#> Warning: Column `y` joining factors with different levels, coercing to character
#> vector
#> # A tibble: 2 x 2
#>       x y    
#>   <dbl> <chr>
#> 1     1 a    
#> 2     2 b
```

<sup>Created on 2020-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Tracked in #4828
