### ISSUE TITLE
case_when(): warning for duplicates on the left hand side

### ISSUE THREAD

**Issue by einGlasRotwein** [tidyverse/dplyr#4766]
Heya everyone,
consider the following case:

```r
woops <- rep(1:4, 2)
case_when(woops == 1 ~ "x",
          woops == 2 ~ "y",
          woops == 1 ~ "oh no",
          TRUE ~ "rest")
[1] "x"    "y"    "rest" "rest" "x"    "y"    "rest" "rest"
```

The duplicate on the left hand side of the formula does not result in a warning, which I would have expected. I can't think of an occasion where the user actually wants the input to be this way, so I thought a warning message for left hand side duplicates would prevent errors, but won't annoy anyone.
Or are there any other reasons speaking against this?

Thank you for your amazing package!

**Comment by seasmith** [comment]
Good idea.  Seems simple enough in theory to implement.

```r
fs <- dplyr:::compact_null(rlang:::list2(woops == 1 ~ "x",
                                         woops == 2 ~ "y",
                                         woops == 1 ~ "oh no",
                                         TRUE ~ "rest"))

lhs <- lapply(fs, function (x) x[[2]])
warning(paste0(c("Duplicated logical conditions at postions:", 
                 which(duplicated(lhs))), 
                 collapse = " "),
        call. = TRUE)
# Warning message:
# Duplicated logical conditions at postions: 3 
```

**Comment by hadley** [comment]
This just feels a bit too magical to me — I get where you're coming from but it just doesn't feel right (for reasons I can't fully articulate) to throw an error here.
