### ISSUE TITLE
across() should use glue syntax to name output

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#4781]
This resolves a few problems:

* it makes it easier to use multiple sets of `across()` on the same variables without name clashes
* you can put the function names before the variable names if so desired
* the average user is less likely to be unnecessarily exposed to df-cols

(this wouldn't give you the ability to change the order of the variables, which judging from tidyr issues, people will want)

**Comment by romainfrancois** [comment]
It was like this at some point, it should not be too hard to bring it back. 

- Would the glue syntax also work when there is only one function, as opposed to a list of functions ? Currently with a single function, the output are simply named after the selected columns.
- Should we allow an unnamed list of functions and then use `fn1`, `fn2` ... ?

BTW, someone like me who liked the previous behavior can still wrap it up in a custom function: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

packcross <- function(cols = everything(), fns){
  cols <- enquo(cols)
  out <- tibble(!!!map(fns, function(fn) across(!!cols, fn)))
  out
}

iris %>% 
  group_by(Species) %>% 
  summarise(
    packcross(starts_with("Sepal"), list(mean = mean, sd = sd))
  )
#> # A tibble: 3 x 3
#>   Species    mean$Sepal.Length $Sepal.Width sd$Sepal.Length $Sepal.Width
#>   <fct>                  <dbl>        <dbl>           <dbl>        <dbl>
#> 1 setosa                  5.01         3.43           0.352        0.379
#> 2 versicolor              5.94         2.77           0.516        0.314
#> 3 virginica               6.59         2.97           0.636        0.322
```

<sup>Created on 2020-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
I think we'd default to `names = NULL` would be `"{col}"` if `fn` is a function, and `"{col}_{fn}"` if `fn` is a list. I like the idea to auto name, but we could also just number so that by default you'd get (e.g.) `a_1, a_2, b_1, b_2` and if you wanted a different prefix you'd do (e.g.) `names = "{col}.fn{fn}"`
