### ISSUE TITLE
summaries order matters

### ISSUE THREAD

**Issue by uzhao** [tidyverse/dplyr#4784]
I tried to aggregate some stock data from minute level into daily level. 

When I

```r
  summarise(
    volume = sum(volume),
    average = sum(average * volume) / sum(volume)
  )
```
average become much larger than correct value.
However,
 
```r
 summarise(
    average = sum(average * volume) / sum(volume),
    volume = sum(volume)
  )
```

gives correct answer.

This looks strange to me

**Comment by romainfrancois** [comment]
This is by design, the second expression is allowed to use results from the first expression, so in the first case `average = sum(average * volume) / sum(volume)`, `volume` is already `sum(volume)`.

**Comment by uzhao** [comment]
Isn't this design strange?

**Comment by hadley** [comment]
It happens because people expect to be able to use summaries that they just created.
