### ISSUE TITLE
commit mutate results to remote database

### ISSUE THREAD

**Issue by ChristelSwift** [tidyverse/dplyr#4801]
is there a way to commit the result of a mutate to a remote database?  I understand that `compute` stores the result in a temporary table but i'd like to commit the transformation permanently without having to collect the data into the session.

```r
library(tidyverse)
library(RSQLite)

my_db <- src_sqlite("my_iris_db", create=TRUE) # create remote database
copy_to(my_db, iris, temporary = FALSE) # upload iris data
my_iris_table <- tbl(my_db, "iris") # create table alias
my_iris_table %>% head()

my_iris_table <- my_iris_table %>% mutate(my_var = ifelse(Species == "setosa", 1, 0))
my_iris_table %>% head()
```
The transformation is available in session but is not permanently committed to the external database.  Is there a way around this?

**Comment by hadley** [comment]
`compute(temporary = FALSE)` — https://dbplyr.tidyverse.org/reference/collapse.tbl_sql.html
