### ISSUE TITLE
Add a symmetric difference set function

### ISSUE THREAD

**Issue by felipegerard** [tidyverse/dplyr#4811]
I often have the need to find elements (rows) that two vectors (data frames) *don't* have in common. Finding these elements using setops is straightforward, but I wonder if it would be ok to add the symmetric difference (aka. union \ intersection) function to save a few key strokes. Below is my proposed solution. I can make the PR if we agree it makes sense to add this.

```r
symdiff <- function(x, y) {
  setdiff(union(x, y), intersect(x, y))
}
```

**Comment by seasmith** [comment]
would it also be worth having a symmetrical anti-join?

```r
sym_anti_join <- function (x, y, by = NULL, copy = FALSE, ...) {
  x_only <- anti_join(x, y, by = by, copy = copy, ...)
  y_only <- anti_join(y, x, by = by, copy = copy, ...)
  bind_rows(x_only, y_only)
}
```

**Comment by hadley** [comment]
Implementation might look something like this:

```R
symdiff <- function(x, y, ...) {
  check_dots_empty()
  UseMethod("symdiff")
}

symdiff.data.frame <- function(x, y) {
  check_compatible(x, y)
  
  cast <- vec_cast_common(x = x, y = y)
  only_x <- vec_slice(cast$x, !vec_in(cast$x, cast$y)
  only_y <- vec_slice(cast$y, !vec_in(cast$y, cast$x)
  
  out <- vec_unique(vec_rbind(only_x, only_y))
  reconstruct_set(out, x)
}
```

@seasmith I don't think a symmetric antijoin makes sense because there's generally no reason to expect the data frames on either side of a join to look at all alike.
