### ISSUE TITLE
tidyselect inside mutate

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/dplyr#4837]
A common step in psychology data wrangling is computing composite or summary scores across several items. With `rowwise()`, it's possible to compute such composites by specifying each variable by name:
```r
library(dplyr)
df <- tibble(x = runif(6), y = runif(6), z = runif(6))
df %>% rowwise() %>% mutate(a = mean(c(x, y, z)))
```

This can get tedious and error-prone if the number of variables being composited is large (e.g., 20 items on a personality scale). I wonder if it would be possible to provide support to use tidyselect-type arguments within mutate, without having to resort to `purrr`. For example, something like:
```r
df %>% rowwise() %>% mutate(a = mean(c(x:z)))
```

or, perhaps with a function such as:
```r
df %>% rowwise() %>% mutate(a = mean(c(vars(x:z))))
```

The current alternative is to invoke `purrr::pmap`, which feels like overkill and is a barrier when initially teaching `dplyr` to new R users:
```r
df %>% rowwise() %>% mutate(a = purrr::pmap_dbl(select(cur_data(), x:z), ~ mean(c(...))))

**Comment by courtiol** [comment]
The new `across()` does what you want here: `df %>% mutate(a = rowMeans(across(x:z)))`

**Comment by bwiernik** [comment]
That words for `rowMeans`, which is designed to work with matrices and data.frames, but for, e.g., `mean`, which expects a vector, not a data.frame, this still errors:

```{r}
df <- tibble(x = runif(6), y = runif(6), z = runif(6))
df %>% rowwise() %>% mutate(a = mean(across(x:z)))
```

**Comment by courtiol** [comment]
You need to turn one row tibbles into a vector. This works: 
```
df %>% rowwise() %>% mutate(a = mean(unlist(across(x:z))))
```

**Comment by hadley** [comment]
We’re aware of this problem (ie missing row wise versions of common verbs) and are thinking about it, but it’s currently out of scope for dplyr.
