### ISSUE TITLE
Rowwise across() does not like mean()

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#4840]
Perhaps I don't quite get how (not) to use `across()` but I find it puzzling that rowwise `sd()` and `sum()` work fine but not `mean()`:
``` r
library(dplyr, warn.conflicts = FALSE)
d <- tibble(x = c(1, 3), y = c(3, 4))

d %>% rowwise() %>% mutate(sum = sum(across(c(x, y))))
#> # A tibble: 2 x 3
#> # Rowwise: 
#>       x     y   sum
#>   <dbl> <dbl> <dbl>
#> 1     1     3     4
#> 2     3     4     7
d %>% rowwise() %>% mutate(sd = sd(across(c(x, y))))
#> # A tibble: 2 x 3
#> # Rowwise: 
#>       x     y    sd
#>   <dbl> <dbl> <dbl>
#> 1     1     3 1.41 
#> 2     3     4 0.707
d %>% rowwise() %>% mutate(mean = mean(across(c(x, y))))
#> Warning in mean.default(across(c(x, y))): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(across(c(x, y))): argument is not numeric or logical:
#> returning NA
#> # A tibble: 2 x 3
#> # Rowwise: 
#>       x     y  mean
#>   <dbl> <dbl> <dbl>
#> 1     1     3    NA
#> 2     3     4    NA
```

**Comment by courtiol** [comment]
Humm... nothing to do with `{dplyr}`:
``` r
d <- data.frame(x = 1, y = 2)
sum(d)
#> [1] 3
sd(d)
#> [1] 0.7071068
mean(d)
#> Warning in mean.default(d): argument is not numeric or logical: returning NA
#> [1] NA
```
Perhaps we need a "tidy" `mean()`...

**Comment by courtiol** [comment]
`across()` provides a one row tibble to the function, so `unlist()` solves the issue:
``` r
d %>% rowwise() %>% mutate(mean = mean(unlist(across(c(x, y)))))
#> # A tibble: 2 x 3
#> # Rowwise: 
#>       x     y  mean
#>   <dbl> <dbl> <dbl>
#> 1     1     3   2  
#> 2     3     4   3.5
```

<sup>Created on 2020-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
You need to be a little careful using unlist in this way, since it will always succeed, even if you have accidentally selected columns with different types.

**Comment by courtiol** [comment]
I guess we could use `purrr::flatten()` but this raises the question of whether a `dplyr` function should work like `rowwise()+across()` but always return a vector so to allow these kind of things.
I saw that you (@hadley) are currently thinking about the design of new functions to work at the row level, so it is perhaps the above example is worth keeping this in mind...
