### ISSUE TITLE
Should relocate() inform when .before/.after is not specified?

### ISSUE THREAD

**Issue by mikmart** [tidyverse/dplyr#4842]
Like joins do when `.by` is not specified, could `relocate()` show a concise message about what's happening when neither `.before` or `.after` is specified? Something like `Relocating, .before = 1`?

Without reading the docs, it doesn't seem obvious that the selected columns should be moved to the left-hand side, and having the message would protect against misspellings of the argument names.

For example, I tried the following, and it took me a while to figure out why "it wasn't working"; i.e. that I had forgotten the dot prefix from `.after`:
``` r
library(dplyr)

df <- tibble(a = 1, b = 1, c = 1, d = "a", e = "a", f = "a")
df %>% relocate(f, after = is.numeric)
#> # A tibble: 1 x 6
#>   f         a     b     c d     e    
#>   <chr> <dbl> <dbl> <dbl> <chr> <chr>
#> 1 a         1     1     1 a     a
```

Just like with the join message, it would be simple enough to explicitly specify `.before = 1` to suppress the message, while still having the shorthand for when you don't care about it.

**Comment by mikmart** [comment]
Or perhaps more to the point, something like `Destination not specified, using .before = 1`?

**Comment by hadley** [comment]
That feels a little verbose to me — I think it’s reasonably obvious that relocate would move things to the left, unless otherwise specified. We might reconsider in the future, but for now I’m happy with the current behaviour.
