### ISSUE TITLE
grouped_df / compute_groups() overly aggressive with 'implicit NA' warning?

### ISSUE THREAD

**Issue by bbimber** [tidyverse/dplyr#4843]
We have code that recently started to give the following warnings whenever we subset a grouped dataframe that results in zero rows. I understand what 'Factor x contains implicit NA' refers to, and understand that I could use fct_explicit_na to fix the warning; however, this doesnt seem correct to report it in the situation of zero rows (as opposed to actually having NAs). I only see this with grouped dataframes (this warning is coming from compute_groups()). See this example:

```r

library(dplyr)

#Create DF:
test <- data.frame(x = factor(c('A', 'B')))

#Group by make grouped_df:
test <- test %>% group_by(x)

#Subset, resulting in zero rows:
ss <- test[test$x == 'C',]

# Warning message:
# Factor `x` contains implicit NA, consider using `forcats::fct_explicit_na`

```

Again, I know warning isnt an error, but it seems like in the zero row situation the warning isnt warranted.  Perhaps compute_groups() ~line 45 could also test:

```r

if (is.factor(x) && length(x) > 0 && anyNA(x)) {
      warn(glue("Factor `{var}` contains implicit NA, consider using `forcats::fct_explicit_na()`"))
    }

```

I am using dplyr_0.8.3. Thanks for any comments.

**Comment by romainfrancois** [comment]
This is what I get with the current dev version: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

#Create DF:
test <- data.frame(x = factor(c('A', 'B')))

#Group by make grouped_df:
test <- test %>% group_by(x)

#Subset, resulting in zero rows:
ss <- test[test$x == 'C',]

ss
#> # A tibble: 0 x 1
#> # Groups:   x [0]
#> # … with 1 variable: x <fct>
```

<sup>Created on 2020-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
