### ISSUE TITLE
A .remove argument for condense()?

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#4847]
Based on the following example, I wonder if the `mutate() + list()` combo could be abbreviated with a call to `condense()` -- similarly to what is already available for `summarise() + list()`.
For this to be possible, we would just need to add something like a `.remove` argument to `condense()` (as in `tidyr::hoist()`).

``` r
library(dplyr)

(iris %>%
  group_by(Species) %>%
  condense(Sepal.Length = Sepal.Length) -> foo)  ## the data for the test
#> # A tibble: 3 x 2
#> # Rowwise:  Species
#>   Species    Sepal.Length
#>   <fct>      <list>      
#> 1 setosa     <dbl [50]>  
#> 2 versicolor <dbl [50]>  
#> 3 virginica  <dbl [50]>

foo %>%
  summarise(q = list(quantile(Sepal.Length)))  ## the "old" way
#> # A tibble: 3 x 2
#> # Rowwise:  Species
#>   Species    q        
#>   <fct>      <list>   
#> 1 setosa     <dbl [5]>
#> 2 versicolor <dbl [5]>
#> 3 virginica  <dbl [5]>

foo %>%
  condense(q = quantile(Sepal.Length))  ##  the "new" way
#> # A tibble: 3 x 2
#> # Rowwise:  Species
#>   Species    q        
#>   <fct>      <list>   
#> 1 setosa     <dbl [5]>
#> 2 versicolor <dbl [5]>
#> 3 virginica  <dbl [5]>
  
foo %>%
  mutate(q = list(quantile(Sepal.Length)))  ## the "old" way?
#> # A tibble: 3 x 3
#> # Rowwise:  Species
#>   Species    Sepal.Length q        
#>   <fct>      <list>       <list>   
#> 1 setosa     <dbl [50]>   <dbl [5]>
#> 2 versicolor <dbl [50]>   <dbl [5]>
#> 3 virginica  <dbl [50]>   <dbl [5]>
```

<sup>Created on 2020-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I don't really understand what you're getting at here, but regardless, I'm happy with the current interface of `condense()` and plan to leave it for a while so we can get more experience with it.

**Comment by courtiol** [comment]
OK, I just meant that condense() drops the non-grouping variables and that sometimes it is good to keep them. Think of .remove in tidyr::hoist or .keep in mutate.
