### ISSUE TITLE
curly has unexpected behavior

### ISSUE THREAD

**Issue by gadepallivs** [tidyverse/dplyr#4850]
Curly does not return the expected result from the below code. However, if I uncomment `print(y)`, it returns the expected result. Is it a bug ? or I am using the curly in a wrong way ?
``` r
UpDownCount <- function(x, y) {
  # print(y)
  df <- x %>%
    dplyr::mutate(
      Up = sum({{ y }} >= 6),
      Down = sum({{ y }} <= 6)
    )

  lst <- list(
    Up = unique(df$Up),
    Down = unique(df$Down),
    Toal = unique(df$Up) + unique(df$Down)
  )
  return(lst)
}

mtcars %>% UpDownCount(sym("cyl"))
#> Error in mtcars %>% UpDownCount(sym("cyl")): could not find function "%>%"
```

<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

</details>

**Comment by hadley** [comment]
There are a few problems with your code:

* you didn't load dplyr so you get a weird error message
* the first argument is `x` but you use `df` in your code
* you're using `sym("cyl")` instead of just `cyl`

**Comment by gadepallivs** [comment]
Hello Hadley, than you for reply. I updated the code with sessioninfo . The top one gives expected result and the bottom one does not. The only difference is commenting the `print` statement.  I was pas mutating on the x and then storing in `df`, to access the new columns `Up` and `Down`.  I am passing a vector where the column name is stored in a variable. If I don't use `sym` I get the second result.
