### ISSUE TITLE
Flag recode() as questioning

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#4851]
Since the arguments are in the wrong order

**Comment by bczucz** [comment]
FWIW, just a minor remark for the discussion on "questioning":

In my scripts I do a lot of simple "lookup"-ing in the following way: 
```
a <- sample(letters[1:4], 10, replace=T)
b <- c(a=1, b=2, c=3)[a]
```
This is straightforward way to do simple recoding in base R. From the this perspective the current order of 'old ' and 'new' in dplyr::recode is just natural. 
(I would give my "user vote" for keeping this order.) 
My 2 cents.
Balint
