### ISSUE TITLE
case_when bug

### ISSUE THREAD

**Issue by mac-pfa** [tidyverse/dplyr#4852]
In the `case_when` function, if any RHS option is an empty vector, then that vector is automatically returned.

```r
case_when(TRUE  ~ "Hello",
          FALSE ~ character(0))
```

**Comment by romatik** [comment]
I'm not sure it's a bug, but more of an undocumented feature. There is this function -https://github.com/tidyverse/dplyr/blob/30363bf501349be8536f9e332f1ce8846883c46b/R/case_when.R#L215 - that specifically checks for non-atomic length and if there is any, then it just returns empty element of correct type.

**Comment by cderv** [comment]
I think this is documented here in [`case_when`](https://dplyr.tidyverse.org/reference/case_when.html) doc
> Both LHS and RHS may have the same length of either 1 or n. The value of n must be consistent across all cases. The case of n == 0 is treated as a variant of n != 1.

In your example, all of RHS does not have the same length.
This issue is also related to https://github.com/tidyverse/dplyr/issues/4170 where maybe it will evolved https://github.com/tidyverse/dplyr/issues/4170#issuecomment-496247028

**Comment by mac-pfa** [comment]
I have read the documentation for the function, but given my example, I have trouble following your logic that the function correctly returns `character(0)`.
If you do no wish to change the functionality, could you help suggest another way of returning the RHS of the first formula in a vectorised way?

**Comment by cderv** [comment]
> If you do no wish to change the functionality

I am not the one to change anything. Sorry if I mislead you. 
I just wanted to help by pointing out the piece of documentation that talks about that, and also the other issue because I participated in that one earlier, where an answer was given. So linking the two seems interesting for reference.

**Comment by hadley** [comment]
@mac-pfa This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
