### ISSUE TITLE
performance of dplyr_col_modify()

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4855]
I'm looking at performance for `mutate()` and it seems `dplyr_col_modify()` is taking some time it is not really supposed to: 

```r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(x = rnorm(1e6), g = sample(rep(1:1e4, 100))) %>% group_by(g)
profvis::profvis(
  for(i in 1:500) mutate(df, y = x + 0L)
)
```

![image](https://user-images.githubusercontent.com/2625526/74342741-3e1ba680-4daa-11ea-9752-7ced6c1ccce6.png)

I'm also suspicious about `tibble:::update_tibble_attrs()` which seems to be taking way too much time for what it does, i.e. replacing attributes. 

I understand that `dplyr_col_modify()` brings very welcome genericity, but perhaps we can have a fast pass for "basic data frame and tibbles"

**Comment by hadley** [comment]
Yeah, we can definitely have a faster version for data.frames — the idea of these functions were to extract out as much common code as possible so we can optimise in one place. Do you want to take a stab, or do you want me to take a look next week?

**Comment by romainfrancois** [comment]
I'll start it.

**Comment by romainfrancois** [comment]
Might just be `tibble:::vectbl_restore()` and specifically `attributes<-` as discussed in https://github.com/tidyverse/tibble/pull/717

![image](https://user-images.githubusercontent.com/2625526/74524337-24e83680-4f1f-11ea-97c5-024fd8d349a3.png)
