### ISSUE TITLE
right_join() no longer rearranges the rows correctly!

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#4856]
The current output of `right_join()` is no longer what it used to be.
I believe this is a bug:

In dplyr 0.8.3:
```r
dplyr::right_join(data.frame(x = 2:1), data.frame(x = 1:2, y = 1:2))
#>Joining, by = "x"
#>  x y
#> 1 1 1
#> 2 2 2
```

In current devel:
``` r
dplyr::right_join(data.frame(x = 2:1), data.frame(x = 1:2, y = 1:2))
#> Joining, by = "x"
#>   x y
#> 1 2 2
#> 2 1 1
```

**Comment by courtiol** [comment]
This is a symmetrical issue than that of #4639

**Comment by hadley** [comment]
Please provide a reprex

**Comment by hadley** [comment]
This works for me:

``` r
dplyr::right_join(data.frame(x = 2:1), data.frame(x = 1:2, y = 1:2))
#> Joining, by = "x"
#>   x y
#> 1 2 2
#> 2 1 1
```

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by courtiol** [comment]
No @hadley this does not work: read again your output, the rows from `y` should be untouched in their order since this is a _right join_. Before, it used to behave correctly. If this is intended, this is a big breaking change.

**Comment by hadley** [comment]
Ok, you haven't read the docs — we are now very clear that joins always preserve the ordering (and other properties) of `x`.

**Comment by courtiol** [comment]
OK, then this is intended and it is unfortunately breaking a lot of my code on various projects...
Please clearly label it in the NEWS file as a breaking change for others to know...
