### ISSUE TITLE
add a complete scoped -> across list change to documentation 

### ISSUE THREAD

**Issue by msberends** [tidyverse/dplyr#4860]
I think the documentation of the `across()` function could use a bit more love (and [the oneliner of the current NEWS file](https://github.com/tidyverse/dplyr/blob/92a3fbb275b897ee0250a1d58b9623b5b1dff833/NEWS.md#across) as well) before the 1.0.0 release, to make it better adaptable to users that are very much used to the `_at`, `_if` and `_all` functions.

Something like a clean list (no, not a `list` 😉) where most old options are shown with the `across()` counterpart:

```r
mutate_if(x, y, ...)       # old
mtuate(across(x, y, ...))  # new

mutate_all(x)
mtuate(across(x))

mutate_at(x, y)
# you get the point :)
```

And then perhaps the same for `summarise()` if that is not so obvious?

I would like to start using `across()` as soon as dplyr hits 1.0.0, but find it a bit hard to get its potential and 'translation' from the documentation.

Thanks for the great idea and implementation! Awesome function.

**Comment by hadley** [comment]
We've included the translation in the old documentation, so that if you look at (e.g.) `?mutate_all()` you'll see how to use `across()` instead. But the bulk of the documentation will be in a new vignette, #4704.

**Comment by msberends** [comment]
Fair enough, many thanks!
