### ISSUE TITLE
glue renaming issue

### ISSUE THREAD

**Issue by Nicktz** [tidyverse/dplyr#4864]
Hi guys,

I recently updated my dplyr to 0.8.4, and it caused breaks when using glued vector inputs in rename.

In particular, it says the subscript has the wrong type `glue`.

This is causing tons of code to break on my side where I used glued objects as vector inputs - is this intentional - i.e. should I change my code backward - or is this a fixable issue?

Versions:
dplyr_0.8.4 ; glue_1.3.1

```r
library(tidyverse)
df <- tibble(col_1 = rnorm(100), col_2 = rnorm(100))
string <- "col"
gluevar <- glue::glue("{string}_1")

# Breaks:
df %>% rename(newname := gluevar)
# Works:
df %>% rename(newname := as.character(gluevar))
```
Ideally rename should be able to handle glued objects by default as was previously done using dplyr 0.8.3

**Comment by lionel-** [comment]
This is from tidyselect 1.0.0. You can fix this by installing dev glue:

```r
remotes::install_github("tidyverse/glue")
```

It will be released to CRAN within 1 or 2 weeks.

**Comment by Nicktz** [comment]
Great thanks. V happy glue will be part of tidyverse!
