### ISSUE TITLE
sample_n() is slow because of slice()?

### ISSUE THREAD

**Issue by vlepori** [tidyverse/dplyr#4865]
I realized that `sample_n` was the bottleneck of my simulations, and was shocked by how much slower it is than base `sample`+subsetting. Turns out this is due to `slice` (which I understand is being called) being much slower than base `[` for me.

Example with a tibble since this [issue ](https://github.com/tidyverse/dplyr/issues/4312) suggested it as a fix

```r
df <- data.frame(A = rep('A', 20), C = seq(1:20))
df2 <- dplyr::as_tibble(df)

microbenchmark::microbenchmark(
  
  'sample_n'     = {dplyr::sample_n(df2,size = 1,weight = C)},
  
  'sample+['     = {df2[sample(1:20, size = 1, prob = df2$C),]},
  
  'sample+slice' = {dplyr::slice(df2, sample(1:20, size = 1, prob = df2$C))}
  
)

# Unit: microseconds
# expr         min    lq    mean   median   uq   max   neval
# sample_n     149.1 155.5 162.925 159.70 163.65 342.9   100
# sample+[     31.0  37.3  42.335  42.65  44.70  80.3    100
# sample+slice 127.5 132.9 138.887 135.45 138.50 324.1   100
```

Also happens without sampling

```r
microbenchmark::microbenchmark(
  
  '['     = {df2[5,]},
  'slice' = {dplyr::slice(df2, 5)}
  
)

# Unit: microseconds
# expr  min    lq    mean median     uq   max neval
# [     22.6  25.4  29.572  30.55  32.55  60.1   100
# slice 104.9 108.2 114.078 110.40 112.80 280.3  100
```
Using R 3.6.1, dplyr 0.8.3
Am missing something ? Thanks!

**Comment by courtiol** [comment]
I don't think there is much of a problem here.

This seem to be just caused by the (small) overhead.

On a dataset with 1 million rows, there is no difference:
``` r

nrow <- 1e6
df <- data.frame(A = rep('A', nrow), C = seq(1:nrow))
df2 <- dplyr::as_tibble(df)

microbenchmark::microbenchmark(
  
  'sample_n'     = {dplyr::sample_n(df2, size = 1, weight = C)},
  
  'splice_sample' =  {dplyr::slice_sample(df2, n = 1, weight_by = C)}, ## new syntax
  
  'sample+['     = {df2[sample(1:nrow, size = 1, prob = df2$C),]},
  
  'sample+slice' = {dplyr::slice(df2, sample(1:nrow, size = 1, prob = df2$C))}
  
)
#> Unit: milliseconds
#>           expr      min       lq      mean   median       uq      max neval cld
#>       sample_n 85.58024 88.77524  99.05304 95.44487 101.6844 245.3572   100   a
#>  splice_sample 85.88346 88.86592 103.32628 93.71099 102.6933 267.8975   100   a
#>       sample+[ 84.43784 88.83985  99.87693 94.19601 102.0008 231.4375   100   a
#>   sample+slice 86.17100 90.48105  98.11867 94.79614 101.0937 251.9265   100   a
```

<sup>Created on 2020-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And for a small dataset, it is on the order of microseconds, so...

The problem is that you probably call the function many times, which should be avoided (even when using sample()): try not to sample one row many times but instead sample many rows (with replacement) a single time and then loop (or map) on the rows of the newly produced dataset.

**Comment by vlepori** [comment]
Thanks for the answer! You make a good point that the difference arises from multiple calls to the function and disappears when sampling many rows at once.

For my purposes (modelling of stochastic processes) I have no choice but to re-calculate the likelihoods of events (based on the system state) at each step, sample one event, and iterate over thousands of steps. Here, switching from `sample_n` to `sample`+`[` saves me ~75% computing time. I reckon that this might be a pretty specific use case though.
