### ISSUE TITLE
Mutate cannot handle certain classes of vectors (e.g.  haven_labelled)

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#4866]
I am not sure whether the following issue comes from {vctrs} or {dplyr}, but simply adding a haven_labelled vector to a data.frame (or tibble) using mutate() no longer works:

``` r
library(dplyr)

var1 <- factor(1)
var2 <- haven::labelled(1, labels = c("1" = 1))

data.frame(a = 1) %>% mutate(b = var1)
#>   a b
#> 1 1 1
data.frame(a = 1) %>% mutate(c = var2)
#> Error: `mutate()` argument `c` errored.
#> ℹ `c` is `var2`.
#> x Can't find vctrs or base methods for concatenation.
#> vctrs methods must be implemented for class `haven_labelled`.
#> See <https://vctrs.r-lib.org/articles/s3-vector.html>.

data.frame(a = 1, b = var1, c = var2)
#>   a b c
#> 1 1 1 1
```

<sup>Created on 2020-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by courtiol** [comment]
This is because:
``` r
var2 <- haven::labelled(1, labels = c("1" = 1))
var2list <- list(var2)
vctrs::vec_c(!!!var2list)
#> Error: Can't find vctrs or base methods for concatenation.
#> vctrs methods must be implemented for class `haven_labelled`.
#> See <https://vctrs.r-lib.org/articles/s3-vector.html>.
```

<sup>Created on 2020-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
So I guess this should be sorted out in {haven} (I will post an issue), but I wonder if they could be a fall back method in {dplyr}...

**Comment by hadley** [comment]
Yes, this is a haven issue
