### ISSUE TITLE
Order seems important when using !grepl in filter

### ISSUE THREAD

**Issue by programgirl** [tidyverse/dplyr#4871]
I've encountered a problem using !grepl in the filter command in dplyr. In the work I am doing, the use of  ! is important. I'm removing the Chatham Islands from a data.frame, which will be linked later in my code

Works (grepl): 
SIAreasNoDups2013 <- AreasNoDups2013 %>%
   filter(AU2013_V1_ >= 580200 | grepl("Chatham", AU2013_label))

Doesn't work (!grepl):
SIAreasNoDups2013 <- AreasNoDups2013 %>%
   filter(AU2013_V1_ >= 580200 | !grepl("Chatham", AU2013_label))

Doesn't work (!grepl):
SIAreasNoDups2013 <- AreasNoDups2013 %>%
  filter(!grepl("Chatham", AU2013_label) | AU2013_V1_ >= 580200)

Works:
SIAreasNoDups2013 <- AreasNoDups2013 %>%
  filter(!(grepl("Chatham", AU2013_label) | AU2013_V1_ < 580200))

The data is from a public file, so I have uploaded it to my repository. I'm new to using GitHub so let me know if you can't access this file: https://github.com/programgirl/TestData/blob/master/AreasNoDups2013.rds

**Comment by programgirl** [comment]
* The ordering in the filter is important.

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
