### ISSUE TITLE
Mutate on a column of exprs produces a list rather than updates the columns

### ISSUE THREAD

**Issue by md0u80c9** [tidyverse/dplyr#4874]
Another weird case from using expr in a tibble (I do appreciate doing this throws up problems)...

If you mutate a normal column using .data, you affect each row in the table using that row's value. (demonstrated in the example using column x, from which we produce x2. So far so normal.

If you mutate where our .data variable is an expression column however, in this case column y, we get returned a list of values for the entire column, which is then placed in each row.

``` r
library(rlang)
test <- tibble::tibble(x =c("A", "B"), y = c(expr(a), expr(b)))
dplyr::mutate(test, x2 = paste(x, "A"))
#> # A tibble: 2 x 3
#>   x     y      x2   
#>   <chr> <list> <chr>
#> 1 A     <sym>  A A  
#> 2 B     <sym>  B A
dplyr::mutate(test, y2 = expr_text(y))
#> # A tibble: 2 x 3
#>   x     y      y2        
#>   <chr> <list> <chr>     
#> 1 A     <sym>  list(a, b)
#> 2 B     <sym>  list(a, b)

<sup>Created on 2020-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
```

**Comment by courtiol** [comment]
Nothing surprising here: `paste(x, "A")` generates a vector of length 2 so it completes the column, but `expr_text(y)` generate a single element and is thus recycled. This has IMO nothing to do with {dplyr} and expressions.

**Comment by md0u80c9** [comment]
OK - so is this result because instead of creating a vector of length 2, expression_text generates a list of length 2?

I had expected the output to be a vector of strings of length 2, but am I correct in thinking it interprets them as a list, and because they're a list it treats them as a single AST. Therefore the result has length 1, so all items in the column have the same value?

**Comment by courtiol** [comment]
Correct!
