### ISSUE TITLE
Feature Requested, across: Summarise by condition : mean for some columns dynamically, sum for others, non primitive function for others

### ISSUE THREAD

**Issue by philibe** [tidyverse/dplyr#4892]
Hello,

Akrun, from Stackoverflow (I don't know his alias name on github), answer me than `across()` will be enable to have conditional summarise function depending dynamically of the columns, for example mean for some columns, sum for others. 

It's a good news :) :+1:  And It's why I write this feature requested (or question if it's implemented in the next release).

I post this link  because his answer seems to work with dev branch, that I've not installed yet, but with column name and not dynamic column name, and only for primitive functions. :)

# My feature requested 
## Is `across()` will work  with the tidyselect select_helpers ?
because I don't see it, or I missed it, in R.across.R and test-across.R 

## Is `across()` will work  with not only primitive function ?

# A reprex, and the result expected, but with a workaround in the previous version of dplyr

This reprex is with dbplyr because there is `tbl()` and `sql_render()` but in fact the core of my question is about dplyr.

```R
library(RSQLite)
library(dbplyr)
library(tidyverse)
library(DBI)

db <- dbConnect(SQLite())

mtcars_table <- mtcars %>% rename(mpg_sum=mpg,cyl_mean=cyl,disp_mean=disp )

RSQLite::dbWriteTable(db, "mtcars_table", mtcars_table)

req<-as.character((tbl( db, build_sql( con=db,"select * from mtcars_table" ))
                   %>% group_by(carb)
                   %>% summarise_at(vars(c(ends_with("mean"), ends_with("sum")) ), ~sum(.))

) %>% sql_render())
#> Warning: Missing values are always removed in SQL.
#> Use `SUM(x, na.rm = TRUE)` to silence this warning
#> This warning is displayed only once per session.

req<-gsub("(SUM)(\\(.{1,30}mean.{1,10}\\))", "AVG\\2", req, perl=TRUE)
print(req)
#> [1] "SELECT `carb`, AVG(`cyl_mean`) AS `cyl_mean`, AVG(`disp_mean`) AS `disp_mean`, 
# SUM(`mpg_sum`) AS `mpg_sum`\nFROM (select * from mtcars_table)\n
# GROUP BY `carb`"

dbGetQuery(db, req)
#>   carb cyl_mean disp_mean mpg_sum
#> 1    1 4.571429  134.2714   177.4
#> 2    2 5.600000  208.1600   224.0
#> 3    3 8.000000  275.8000    48.9
#> 4    4 7.200000  308.8200   157.9
#> 5    6 6.000000  145.0000    19.7
#> 6    8 8.000000  301.0000    15.0
```

sessionInfo() extract:    

dplyr_0.8.4     purrr_0.3.3      tidyr_1.0.2     tibble_2.1.3  tidyverse_1.3.0
 dbplyr_1.4.2     tidyselect_1.0.0    magrittr_1.5    

# Feature expected

## Example of:  Is `across()` will work  with the tidyselect select_helpers ?
```R
summarise(
  across(
     one_of(contains("price")), list(mean = mean), 
     one_of(contains("quantity")), list(mean = sum)
  )
)
```

## Example of:  Is `across()` will work  with not only primitive function ?
```R
summarise(
  across(
     one_of(contains("price"),contains("quantity")), 
	 function (x) {
          ifelse(vars(contains(names(.),"price")),
	     list(myfunction1(.)), 
	     list(myfunction2(.))
	   )	
     }	 
  )
) 
```

Ps 1:Here is my [stackoverflow question](https://stackoverflow.com/questions/60306857/r-summarise-at-dynamically-by-condition-mean-for-some-columns-sum-for-others)  and my [workarounded answer](https://stackoverflow.com/a/60323823/10489562]), which some of my reprex are extracted

Ps 2:  I written a similar message in [comment of R.across.R and test-across.R](https://github.com/tidyverse/dplyr/commit/b30c2a4e42f86569f1f0aa6654f27f947bb26721) but I think it wasn't seen because it was maybe not the good place, so I deleted this comment.

**Comment by batpigandme** [comment]
Yes, we're working on supplying `across()` equivalents for various verbs in the forthcoming documentation and release versions. It will also be easier if you have a minimal reproducible example for each of your questions. You may not see it in the code, but it's possible that it's being addressed in https://github.com/r-lib/tidyselect/. So, the best way to figure it out is to actually run the code.

I'm not sure how to proceed with this issue as it contains several questions which would be best addressed in the documentation, but that are unlikely to be covered by a single pull request (which is how we usually go about closing issues).

I'll leave that call up to @hadley and @romainfrancois.

**Comment by hadley** [comment]
You seem to be a bit confused about the basic syntax of `across()`; I'd recommend starting with `?across()`. 

You could write your two examples above as something like this:

```R
df %>% summarise(
  across(contains("price"), mean), 
  across(contains("quantity"), sum)
)

my_fun <- function(var, val) {
  if (str_detect("price", var)) {
    myfunction1(val)
  } else {
    myfunction2(val)
  }
}
df %>% summarise(across(contains("price") | contains("quantity"), ~ my_fun(cur_column(), .))
```

**Comment by philibe** [comment]
Thank you @hadley  for your examples as answer :)
