### ISSUE TITLE
Option to choose the separator in summarise_all [feature request]

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/dplyr#4897]
When you use `summarise_all`, it can often be interesting to pivot the result, for instance for plotting purpose.

Here is something similar to what I usually do:

```r
iris %>% 
  group_by(Species) %>% 
  summarise_all(list(mean=mean, sd=sd)) %>% 
  pivot_longer(cols=-Species, names_to = c("variable", "fun"), names_sep="_")   
```
Unfortunately, I often find myself dealing with variable names having underscores inside (as it is the recommended way in the tidyverse IIRC). Of course, this leads to this kind of errors, where the pivoting cannot know which underscore is supposed to be used:

```r
iris %>% 
  group_by(-Species) %>% 
  rename_all(~str_replace_all(.x, "\\.", "_")) %>% 
  summarise_all(list(mean=mean, sd=sd)) %>% 
  pivot_longer(cols=-Species, names_to = c("variable", "fun"), names_sep="_") 
```

There are some workarounds but they don't always work. If it was possible to explicitly choose the separator, I could write something like this and it should work every time:

```r
iris %>% 
  group_by(-Species) %>% 
  rename_all(~str_replace_all(.x, "\\.", "_")) %>% 
  summarise_all(list(mean=mean, sd=sd), sep="__") %>% 
  pivot_longer(cols=-Species, names_to = c("variable", "fun"), names_sep="__") 
```

Alternatively (or even additionally, as it may handle other cases), `pivot_longer` could have a `use_last_only` option to force it to only use the last occurrence of a said separator.

**Comment by hadley** [comment]
`across()` which is superseding `summarise_all()` (and all related variants) lets you control the names:

``` r
library(dplyr, warn.conflicts = FALSE)

iris %>% 
  group_by(Species) %>% 
  summarise(across(everything(), list(mean = mean, sd = sd), names = "{col}**{fn}"))
#> # A tibble: 3 x 9
#>   Species `Sepal.Length**… `Sepal.Length**… `Sepal.Width**m… `Sepal.Width**s…
#>   <fct>              <dbl>            <dbl>            <dbl>            <dbl>
#> 1 setosa              5.01             3.43             1.46            0.246
#> 2 versic…             5.94             2.77             4.26            1.33 
#> 3 virgin…             6.59             2.97             5.55            2.03 
#> # … with 4 more variables: `Petal.Length**mean` <dbl>,
#> #   `Petal.Length**sd` <dbl>, `Petal.Width**mean` <dbl>,
#> #   `Petal.Width**sd` <dbl>
```

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(You could also use `names_pattern` in `pivot_longer()`)

**Comment by DanChaltiel** [comment]
Thanks for the `names_pattern` option I didn't know. 

`across`, which I didn't know either, is absolutely awesome and I'm sure I'll use it a lot from now on. 

However, IMHO, its existence is not an absolute reason not to implement a separator choice in `summarise_all`, which would be far more readable and less verbous in this case. But of course it is your call after all.

**Comment by hadley** [comment]
In dplyr 1.0.0 `summarise_all()` is superseded which means that it only receives critical bug fixes, not new features.
