### ISSUE TITLE
progress_estimated not sown with non-interactive use

### ISSUE THREAD

**Issue by vspinu** [tidyverse/dplyr#4913]
When run in R scripts, progress_estimated is not shown. 

```sh
Rscript-3.6.1 -e 'pb <- dplyr::progress_estimated(10); for (i in 1:10) pb$pause(0.5)$tick()$print()'
```
produces no output.

I think whether the progress should be shown in non-interactive sessions should be controlled by the user. 

This one might be the consequence of the ancient #428.

**Comment by hadley** [comment]
I think we'd generally recommend using https://github.com/r-lib/progress, which provides much much much more control.
