### ISSUE TITLE
Error piping to typeof()

### ISSUE THREAD

**Issue by yaakovfeldman** [tidyverse/dplyr#4916]
I have noticed a possible issue when piping to functions such as `class` and `typeof`. The following example works without a pipe but errors when a pipe is used. 

```
> library(dplyr)
> (as.Date("2020-01-01") - as.Date("2010-01-01"))/2 %>%  typeof()
Error in unclass(e1)/e2 : non-numeric argument to binary operator
> typeof((as.Date("2020-01-01") - as.Date("2010-01-01"))/2)
[1] "double"
```

**Comment by hadley** [comment]
This is a precedence issue; you need an extra layer of parentheses:

``` r
library(magrittr)
((as.Date("2020-01-01") - as.Date("2010-01-01"))/2) %>%  typeof()
#> [1] "double"
```

<sup>Created on 2020-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
