### ISSUE TITLE
mutate_all() and multi-line purrr-style function

### ISSUE THREAD

**Issue by bcjaeger** [tidyverse/dplyr#4922]
Hello! It looks like mutate_all may exhibit inconsistent behaviour when purrr-like functions with multiple operations are passed inside of brackets. In the output below, using this type of input function results in unexpected output, whereas creating the same function in the working environment or explicitly writing it as an anonymous function works great. 

``` r
library(dplyr)

df = data.frame(x = c("A", "B"), y = c(NA_character_, "B"),
  stringsAsFactors = FALSE)

# this should change column y from c(NA, B) to c(--, B)
fill_na <- function(.x){
  .x[is.na(.x)] <- '--'
  .x
}

# works great!
mutate_all(df, fill_na)
#>   x  y
#> 1 A --
#> 2 B  B

# works less great
mutate_all(df,
  .funs = ~ {
    .x[is.na(.x)] <- '--'
    .x
  }
)
#>   x y
#> 1 A A
#> 2 B B

# using explicit function fixes it
mutate_all(df,
  .funs = function(.x){
    .x[is.na(.x)] <- '--'
    .x
  }
)
#>   x  y
#> 1 A --
#> 2 B  B
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
In dplyr 1.0.0, `mutate_all()` is superseded by `mutate()` + `across()` which means that `mutate_all()` will only receive critical bug fixes. And we seem to have already resolved your problem with `across()`:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = c("A", "B"), y = c(NA_character_, "B"))

df %>% mutate(across(everything(), ~ {
    .x[is.na(.x)] <- '--'
    .x
  }
))
#> # A tibble: 2 x 2
#>   x     y    
#>   <chr> <chr>
#> 1 A     --   
#> 2 B     B
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bcjaeger** [comment]
That makes sense. Thanks for the fast response!
