### ISSUE TITLE
Unclear error message in bind_rows()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#4931]
when binding with a factor.

``` r
library(dplyr)

df <- tibble(a = "foo", b = "bar")
f <- setNames(factor(c("B", "B")), c("a", "b"))

bind_rows(df, f)
#> Error: Column name `<fct>` must not be duplicated.
```

<sup>Created on 2020-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Is this what `rlang` is expected to do in this case with named factors @lionel- ?

``` r
library(rlang)

list2(!!!c(a = "a", b = "b"))
#> $a
#> [1] "a"
#> 
#> $b
#> [1] "b"
list2(!!!factor(c(a = "a", b = "b")))
#> [[1]]
#> a 
#> a 
#> Levels: a b
#> 
#> [[2]]
#> b 
#> b 
#> Levels: a b
```

<sup>Created on 2020-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

because then `tibble()` gives: 

``` r
library(rlang)
library(tibble)

tibble(!!!c(a = "a", b = "b"))
#> # A tibble: 1 x 2
#>   a     b    
#>   <chr> <chr>
#> 1 a     b
tibble(!!!factor(c(a = "a", b = "b")))
#> Error: Column name `<fct>` must not be duplicated.
#> Use .name_repair to specify repair.
```

<sup>Created on 2020-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
@romainfrancois This is the behaviour of `base::as.list()`. Not sure what's the best approach to fixing this. Ideally we'd use `vctrs::vec_chop2()` here. Maybe we could immitate the chop2 behaviour by relying on `[[`, `length()`, and `names()` methods instead of a single `as.list()` method?

**Comment by DavisVaughan** [comment]
@romainfrancois I think this example with `quos(.named = TRUE)` might get more to the point. I think the auto naming is the issue.

``` r
library(rlang)

f <- setNames(factor(c("B", "B")), c("a", "b"))

qs <- quos(!!!f, .named = TRUE)

qs
#> <list_of<quosure>>
#> 
#> $`<fct>`
#> <quosure>
#> expr: ^<fct>
#> env:  empty
#> 
#> $`<fct>`
#> <quosure>
#> expr: ^<fct>
#> env:  empty

lapply(qs, eval_tidy)
#> $`<fct>`
#> a 
#> B 
#> Levels: B
#> 
#> $`<fct>`
#> b 
#> B 
#> Levels: B
```

<sup>Created on 2020-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
@DavisVaughan The issue is that `!!!` in rlang transforms S3 objects to lists with `as.list()`.

**Comment by DavisVaughan** [comment]
Yea I'm working on doing what you said and replacing `tibble(!!!x)` with 

```r
# TODO: Replace with `vctrs::vec_chop2()`
# https://github.com/r-lib/vctrs/pull/626
dplyr_chop2 <- function(x) {
  n <- length(x)
  names <- names(x)

  out <- vector("list", n)

  for (i in seq_len(n)) {
    out[[i]] <- x[[i]]
  }

  names(out) <- names

  out
}

as_tibble_row <- function(x) {
  as_tibble(dplyr_chop2(x))
}
```

**Comment by lionel-** [comment]
I think we should fix in rlang though.
