### ISSUE TITLE
feature request: suppress progress bars from function or package

### ISSUE THREAD

**Issue by jessekps** [tidyverse/dplyr#4934]
I often use multiple dplyr operations in functions in my packages. This can result in multiple progress bars being shown, giving a very misleading indication of true progress. The dplyr progress bars can also disrupt my own progress bars.

I would like to have a way of disabling dplyr progress bars on something like a call by call basis. Maybe a named argument .show_progress? I vaguely recall that this was possible in plyr but dplyr seems to lack this functionality.  I hope you will consider it. 

Thanks,
Jesse

**Comment by hadley** [comment]
You can turn it off with `options("dplyr.show_progress" = FALSE)`

But `do()` is the only function that uses it, so I'm surprised that you're getting many progress bars.

**Comment by jessekps** [comment]
Oh of course, I can just set that at the start and reset it at the end of the function. Sorry, having a slow day I guess.

I like do, sorry to see it will be deprecated. Thanks for the quick response
