### ISSUE TITLE
Feature request: annotated mutates (show definition of columns)

### ISSUE THREAD

**Issue by klin333** [tidyverse/dplyr#4954]
One advantage excel has over dplyr/data.table/pandas/SQL is that non-technical users can click on to each cell and see the cell definition. This is useful to allow our non-technical managers/external stakeholders to understand what are the transforms done on the data. 

One middle ground for dplyr might be annotated columns, eg the following

---

```r
library(tidyverse)  # version 1.2.1


mutate_annotated <- function(.data, ...) {
  arg_vars <- enquos(...)
  my_labels <- map(arg_vars, rlang::as_label)
  .data <- .data %>% mutate(...)
  for(col_name in names(my_labels)) {
    attr(.data[[col_name]], 'label') <- sprintf('= %s', my_labels[[col_name]]) 
  }
  .data
}

display_annotated <- function(df, to_excel = FALSE) {
  my_labels <- map(df, function(x) ifelse(!is.null(attr(x, 'label')), attr(x, 'label'), ''))
  if (to_excel) {
    my_labels <- map(my_labels, function(x) str_c(" ", x))
  }
  df_display <- bind_rows(as_tibble(my_labels), df %>% mutate_all(as.character))
  df_display
}

display_annotated_alternate <- function(df, to_excel = FALSE) {
  my_labels <- map(df, function(x) ifelse(!is.null(attr(x, 'label')), attr(x, 'label'), ''))
  my_labels <- as.character(my_labels)
  if (to_excel) {
    my_labels <- str_c(' ', my_labels)
  }
  colnames(df) <- str_c(colnames(df), my_labels, sep = '\n')
  df
}


df <- tibble(a = c(1, 2), b = c(3, 4)) %>% 
  mutate_annotated(
    c = a + b,
    d = c/b,  
    e = d - lag(d, 1)
  )

display_annotated(df, to_excel = TRUE) %>% write_delim("clipboard-16384", delim = '\t', na = '')
```

above output copied to clipboard and pasted to excel becames:

a | b | c | d | e
-- | -- | -- | -- | --
  |   | = a + b | = c/b | = d - lag(d, 1)
1 | 3 | 4 | 1.333333 |  
2 | 4 | 6 | 1.5 | 0.166667

Please let me know if this seems promising or if there are other better ways to do this... I would imagine a similar thing can be done for summarise(). Of course, this gets tricky once users do renames, but not impossible.

**Comment by hadley** [comment]
This is out of scope for dplyr. It might be a better fit for [tidylog](https://github.com/elbersb/tidylog) or similar.
