### ISSUE TITLE
Error: Can't cast <glue> to <glue>.

### ISSUE THREAD

**Issue by ddsjoberg** [tidyverse/dplyr#4960]
I updated dplyr to test on my package before the 1.0.0 release.  I am now seeing this error when using `glue()` in a `mutate()`.  Is this expected? Thank you!

``` r
library(dplyr)
packageVersion('dplyr')
#> [1] '0.8.99.9000'
mtcars %>%
  mutate(
    new_col = glue::glue("am = {am}")
  )
#> Error: Can't cast <glue> to <glue>.
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
You'll also need to update glue.
