### ISSUE TITLE
Potential missing method for class "table" in dplyr v1.0.0

### ISSUE THREAD

**Issue by ddsjoberg** [tidyverse/dplyr#4963]
Using `mutate()` with a data frame created from `table()` was previously not an issue.  But now there is no method for a column of class `"table"`.  I would understand if this was a choice, but wanted to point it out just in case it's a bug. 🐛 

``` r
library(dplyr, warn.conflicts = FALSE)
packageVersion("dplyr")
#> [1] '0.8.99.9000'
packageVersion("vctrs")
#> [1] '0.2.99.9010'

ex <-
  table(iris$Species) %>%
  expand.grid() 
ex
#>   Var1
#> 1   50
#> 2   50
#> 3   50
class(ex)
#> [1] "data.frame"
class(ex$Var1)
#> [1] "table"

mutate(ex,
       Var2 = Var1)
#> Error: `mutate()` argument `Var2` errored.
#> i `Var2` is `Var1`.
#> x Can't find vctrs or base methods for concatenation.
#> vctrs methods must be implemented for class `table`.
#> See <https://vctrs.r-lib.org/articles/s3-vector.html>.
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
This has come up in a few rev dep checks, but this is actually more of a `vctrs` issue: 

``` r
vctrs::vec_c(table("tennis"))
#> Error: Can't find vctrs or base methods for concatenation.
#> vctrs methods must be implemented for class `table`.
#> See <https://vctrs.r-lib.org/articles/s3-vector.html>.
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
