### ISSUE TITLE
across() argument names and argument order

### ISSUE THREAD

**Issue by mikmart** [tidyverse/dplyr#4965]
I’ve just read the [blog post about dplyr 1.0.0](https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-is-coming-soon/) and couldn’t wait to get my hands on `across()` – it looks great\! I did some quick testing and ran into a couple of issues with the arguments:

  - Should `across()`'s argument names be prefixed with dots to avoid `...` collisions? Partial argument name matching is a particularly nasty problem otherwise.
  - Should the `names` argument be moved after `...` so that it’s easier to pass positional arguments to `fns` like you would in `purrr::map()` et al? It doesn’t seem like it would ever really be a good idea to pass `names` by position, anyway.

``` r
library(tidyverse)

tbl <- tibble(
  x = c("a", "a", "b", "c"),
  y = c("a", "b", "b", "c")
)

# this is what I was after:
mutate_at(tbl, vars(x, y), fct_lump, n = 1)
#> # A tibble: 4 x 2
#>   x     y    
#>   <fct> <fct>
#> 1 a     Other
#> 2 a     b    
#> 3 Other b    
#> 4 Other Other

# unfortunate partial match collision:
mutate(tbl, across(c(x, y), fct_lump, n = 1))
#> Error: Column 2 must be named.
#> Use .name_repair to specify repair.
mutate(tbl, across(x, fct_lump, n = 1))
#> # A tibble: 4 x 3
#>   x     y     `1`  
#>   <chr> <chr> <fct>
#> 1 a     a     a    
#> 2 a     b     a    
#> 3 b     b     b    
#> 4 c     c     c

# workaround:
mutate(tbl, across(c(x, y), fct_lump, n = 1, names = "{col}"))
#> # A tibble: 4 x 2
#>   x     y    
#>   <fct> <fct>
#> 1 a     Other
#> 2 a     b    
#> 3 Other b    
#> 4 Other Other

# this is a pretty common pattern I use to modify
# a column without having to type out the name twice
mutate_at(tbl, vars(x), str_c, "_foo")
#> # A tibble: 4 x 2
#>   x     y    
#>   <chr> <chr>
#> 1 a_foo a    
#> 2 a_foo b    
#> 3 b_foo b    
#> 4 c_foo c

# but alas:
mutate(tbl, across(x, str_c, "_foo"))
#> # A tibble: 4 x 3
#>   x     y     `_foo`
#>   <chr> <chr> <chr> 
#> 1 a     a     a     
#> 2 a     b     a     
#> 3 b     b     b     
#> 4 c     c     c
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Good catches! Want to do a PR?

**Comment by mikmart** [comment]
Yeah, I'll have a look!
