### ISSUE TITLE
`bind_rows()` drops vector class without warning

### ISSUE THREAD

**Issue by zenggyu** [tidyverse/dplyr#4966]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

When performing row binding with two tibbles that contain a column of class `yearmonth`, `bind_rows()` will drop the `yearmonth` class attribute, leaving the resulting column to be of class `Date`, without any warning.

In contrast, the `rbind()` function produces the expected output.

``` r
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tsibble))

tibble(ym = yearmonth("2020 03"))
#> # A tibble: 1 x 1
#>         ym
#>      <mth>
#> 1 2020 Mar

rbind(
  tibble(ym = yearmonth("2020 03")),
  tibble(ym = yearmonth("2020 04"))
)
#> # A tibble: 2 x 1
#>         ym
#>      <mth>
#> 1 2020 Mar
#> 2 2020 Apr

bind_rows(
  tibble(ym = yearmonth("2020 03")),
  tibble(ym = yearmonth("2020 04"))
)
#> # A tibble: 2 x 1
#>   ym        
#>   <date>    
#> 1 2020-03-01
#> 2 2020-04-01
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Already fixed in the development version:

``` r
library(dplyr, warn.conflicts = FALSE)
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following object is masked from 'package:dplyr':
#> 
#>     id
  
rbind(
  tibble(ym = yearmonth("2020 03")),
  tibble(ym = yearmonth("2020 04"))
)
#> # A tibble: 2 x 1
#>         ym
#>      <mth>
#> 1 2020 Mar
#> 2 2020 Apr
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
