### ISSUE TITLE
mutate crashes R if assigning new variable(s) and removing variables at once

### ISSUE THREAD

**Issue by atusy** [tidyverse/dplyr#4974]
The issue happens with the latest dplyr on GitHub.
dplyr 0.8.3 is okay.

Here is an example.

```r
reprex::reprex(
  dplyr::mutate(data.frame(x = 1, y = 1), z = 1, x = NULL, y = NULL)
)
# Error: <callr_status_error in get_result(output = out, options):
# callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed>
```

Following works fine

``` r
dplyr::mutate(data.frame(x = 1, y = 1), x = NULL, y = NULL)
#> data frame with 0 columns and 1 row
dplyr::mutate(data.frame(x = 1, y = 1), z = 1, y = NULL)
#>   x z
#> 1 1 1
dplyr::mutate(data.frame(x = 1, y = 1), x = NULL, y = NULL, z = 1)
#>   z
#> 1 1
```

<sup>Created on 2020-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by batpigandme** [comment]
If helpful, here's the Traceback from the caught segfault if I run this in the terminal
 <details><summary>Caught segfault</summary>
<pre>
<code>
*** caught segfault ***
address 0x40000013, cause 'memory not mapped'

Traceback:
 1: .Call(dplyr_mask_eval_all_mutate, quo, private)
 2: mask$eval_all_mutate(dots[[i]])
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
 6: doTryCatch(return(expr), name, parentenv, handler)
 7: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
 8: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
11: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
12: doTryCatch(return(expr), name, parentenv, handler)
13: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
14: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
17: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
18: doTryCatch(return(expr), name, parentenv, handler)
19: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
20: tryCatchList(expr, classes, parentenv, handlers)
21: tryCatch({    for (i in seq_along(dots)) {  ...
22: mutate_cols(.data, ...)
23: mutate.data.frame(data.frame(x = 1, y = 1), z = 1, x = NULL,     y = NULL)
24: dplyr::mutate(data.frame(x = 1, y = 1), z = 1, x = NULL, y = NULL)
</code>
</pre>
</details>
