### ISSUE TITLE
GitHub news out of sync with CRAN

### ISSUE THREAD

**Issue by smingerson** [tidyverse/dplyr#4980]
GitHub has 0.8.4 listed as the development version, while 0.8.5 is on CRAN. Further, the changes in the GH news for 0.8.4 are not present on CRAN. I think the GH news should be updated to reflect the CRAN releases and their associated small changes, and the dev version bumped to 0.8.6.

**Comment by krlmlr** [comment]
Thanks. We need to merge the [`release-0-8-5` branch](https://github.com/tidyverse/dplyr/tree/release-0-8-5) into `master`.

**Comment by hadley** [comment]
@lionel- will do that when he's back from vacation. It's very low priority since 0.8.5 contains no user facing changes.

**Comment by smingerson** [comment]
No problem, I wanted to make sure you all were aware. I went through some confusion as I thought I could get that `group_modify()` fix from CRAN.

**Comment by lionel-** [comment]
@krlmlr @hadley This issue wasn't about the recent CRAN release, but about a typo in the NEWS headings that stranded some bullets in a fake release.
