### ISSUE TITLE
Regression: group_by() with dependent expressions

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#4984]
Is this a mistake? I haven't found a NEWS entry.

This is related to #4983, I can take a look once we decide what's the right behavior.

## dev version

``` r
library(tidyverse)

tibble(a = 1, b = 2) %>%
  group_by(c = a * b, d = c + 1)
#> Error: `mutate()` argument `d` errored.
#> ℹ `d` is `c + 1`.
#> x non-numeric argument to binary operator
```

<sup>Created on 2020-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## CRAN version

``` r
library(tidyverse)

tibble(a = 1, b = 2) %>%
  group_by(c = a * b, d = c + 1)
#> # A tibble: 1 x 4
#> # Groups:   c, d [1]
#>       a     b     c     d
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     1     2     2     3
```

<sup>Created on 2020-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Yes, this is definitely an error — `group_by()` should have `mutate()` semantics.
