### ISSUE TITLE
Allow bind_rows() to evaluate "." in a pipe

### ISSUE THREAD

**Issue by colearendt** [tidyverse/dplyr#4988]
When working with a dataset that has multiple "types" of records that need to be dealt with in a pipe, it would be nice to have a way to "split" paths. I.e. in my pipe, provide two or three "branches" where I can behave differently and then merge the dataset back together again.

`bind_rows()` is very close to providing this behavior, but it does not allow piping with the `.` within its arguments. I'm not sure if this is even feasible, but is something that I have used in various other functions with success (`join` variants, etc.), and seems to work with named variables.

Alternatively, some other way to "split" a pipe into branches would be nice.

``` r
suppressPackageStartupMessages(library(dplyr))

nrow(iris)
#> [1] 150

# works for doubling rows
iris %>%
  bind_rows(., .) %>%
  nrow()
#> [1] 300

# fails for piped arguments with "."
iris %>%
  bind_rows(
    . %>% filter(Sepal.Length < 5),
    . %>% filter(Sepal.Length >= 5)
  )
#> Error: Argument 2 must be a data frame or a named atomic vector

# works with a named variable
bind_rows(
  iris %>% filter(Sepal.Length < 5),
  iris %>% filter(Sepal.Length >= 5)
) %>%
nrow()
#> [1] 150
```

<sup>Created on 2020-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This is an unfortunate confluence of magrittr features:

* `. %>% foo` returns `function(.) foo(.)`
* if you don't want the LHS to be passed as the first argument you need to wrap in `{}`

So you can achieve what you want:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = 1:2)

df %>%
  {bind_rows(
    filter(., x > 1),
    filter(., x <= 1)
  )}
#> # A tibble: 2 x 1
#>       x
#>   <int>
#> 1     2
#> 2     1
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Fixing these issues are outside the scope of dplyr, and I can't easily see a way to modify magrittr to make it work without breaking a bunch of existing code 😞
