### ISSUE TITLE
rowwise vignette references an error that's not there

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#4992]
https://github.com/tidyverse/dplyr/blob/ac2e33d8759ba20cfbb71346ec86ef6ee0953d38/vignettes/rowwise.Rmd#L288

End of the line above says "particularly given the hint in the error message", but the code chunk following it does not produce an error.

**Comment by hadley** [comment]
Something very odd is going on here:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(g = 1:2, y = list(1:3, "a"))
rf <- df %>% rowwise(g)
rf %>% mutate(l1 = length(y), y2 = y, l2 = length(y))
#> # A tibble: 2 x 5
#> # Rowwise:  g
#>       g y            l1 y2           l2
#>   <int> <list>    <int> <list>    <int>
#> 1     1 <int [3]>     3 <int [3]>     1
#> 2     2 <chr [1]>     1 <chr [1]>     1
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@romainfrancois can you please take a look? I suspect this is related to the special stuff `mutate()` is doing with symbols.
