### ISSUE TITLE
case_when: support tibble on RHS

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#4998]
Sometimes it is useful to return multiple values from a `case_when()` call (e.g. a name of a property and a short description). Currently, this only works indirectly by wrapping the RHS in an extra list:

``` r
library(dplyr, quietly = TRUE, warn.conflicts = FALSE)

x <- rep.int(c(TRUE, FALSE), times = 5)
case_when(
  x ~ list(tibble(a = 1, b = 1)),
  !x ~ list(tibble(a = 0, b = 2))
) %>% 
  bind_rows()
#> # A tibble: 10 x 2
#>        a     b
#>  * <dbl> <dbl>
#>  1     1     1
#>  2     0     2
#>  3     1     1
#>  4     0     2
#>  5     1     1
#>  6     0     2
#>  7     1     1
#>  8     0     2
#>  9     1     1
#> 10     0     2
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

and this approach doesn't work for a multi row tibble

``` r
case_when(
  x ~ list(tibble(a = 1:10, b = 1:10)),
  !x ~ list(tibble(a = -(1:10), b = 2*(1:10)))
) %>% 
  bind_rows()
#> # A tibble: 100 x 2
#>        a     b
#>  * <int> <dbl>
#>  1     1     1
#>  2     2     2
#>  3     3     3
#>  4     4     4
#>  5     5     5
#>  6     6     6
#>  7     7     7
#>  8     8     8
#>  9     9     9
#> 10    10    10
#> # … with 90 more rows
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Following the theory of vctrs I would expect something like this to work

``` r
case_when(
  x ~ tibble(a = 1:10, b = 1:10),
  !x ~ tibble(a = -(1:10), b = 2*(1:10))
)
#> # A tibble: 10 x 2
#>        a     b
#>    <int> <dbl>
#>  1     1     1
#>  2    -2     4
#>  3     3     3
#>  4    -4     8
#>  5     5     5
#>  6    -6    12
#>  7     7     7
#>  8    -8    16
#>  9     9     9
#> 10   -10    20
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Yes, your expectation is correct, but we haven't yet rewritten `case_when()` to use vctrs. That's likely to happen when we move these functions to another package so is tracked elsewhere: https://github.com/r-lib/funs/issues/38
