### ISSUE TITLE
Feature request: sample_n samples UP TO n rows

### ISSUE THREAD

**Issue by jarauh** [tidyverse/dplyr#5006]
I want to take up the old issue #3681 by @kevinmneal:

> Let's say I have a dataframe with several groups, with varying numbers of samples (rows) in each group. I'd like to be able to sample up to 10 rows from each group. However, some groups have fewer than 10 samples, and so the function returns an error (will only sample 10, and no fewer, from each group), with a suggestion to sample with replacement. Sampling with replacement will, of course, not return 10 unique samples from groups with 10 or more available, and so my desired condition of subsampling my dataframe to up to 10 samples per group is not met.

It has been closed with a rather cryptic remark.  I believe that at least a workaround should be documented here.  I could also offer to work on this: the proposal would be to add a logical option `allow_smaller_sample` to `sample_n`, which is `FALSE` by default.  If it is true, the returned sample either has the correct size or is either everything (per group).

**Comment by jarauh** [comment]
Workaround with dplyr-0.8.4:

> group_by(mtcars, cyl) %>% group_modify(function(x, y) if (nrow(x) <= 8L) x else sample_n(x, 8L))

**Comment by hadley** [comment]
I think this is already straightforward with `slice()`:

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  group_by(cyl) %>%
  slice(sample(min(2, n())))
#> # A tibble: 6 x 11
#> # Groups:   cyl [3]
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#> 2  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#> 3  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#> 4  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#> 5  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#> 6  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
```

<sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jarauh** [comment]
Thanks for the quick help!

While that looks elegant, it does not really do what it is supposed to do.  `sample(min(2, n()))` never returns any number larger than two, so the sample will always consist of the first two rows (or less).

I guess the following should be correct, though, which is not much more complicated:

```r
> group_by(mtcars, cyl) %>% slice(sample(n(), min(2, n())))
# A tibble: 6 x 11
# Groups:   cyl [3]
     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
 1  33.9     4  71.1    65  4.22  1.84  19.9     1     1     4     1
 2  30.4     4  95.1   113  3.77  1.51  16.9     1     1     5     2
 3  21.4     6 258     110  3.08  3.22  19.4     1     0     3     1
 4  18.1     6 225     105  2.76  3.46  20.2     1     0     3     1
 5  18.7     8 360     175  3.15  3.44  17.0     0     0     3     2
 6  15.8     8 351     264  4.22  3.17  14.5     0     1     5     4
```

So I agree, `dplyr` already supplies all the tools that are needed to address this point.
