### ISSUE TITLE
Please support classed atomic vectors in tidy framework

### ISSUE THREAD

**Issue by leonawicz** [tidyverse/dplyr#5014]
Support for classed atomic vectors in dplyr is very important for various use cases. It has long been very helpful and powerful that this could be done with Tidyverse packages.

The way this worked prior to dplyr 1.0, it was great for both readability (`x` and `y` below were not masked as opaque list columns for example), but far more importantly, only with the necessary classes on these atomic vectors could functions be meaningfully applied to them so that analysis and data manipulation could be done in a tidy framework. For example below, without the classes, it seems I basically can't use the tidyverse for this any longer. Am I missing some work around?

```r
library(dplyr)
library(tabr)

x <- as_vector_time("c e_g c'e_'g'")
x
<Noteworthy string>
  Format: vectorized time
  Values: c <e_g> <c'e_'g'>

# transpose notes by two semitones, then recover pitch interval
tibble(x = x) %>% 
  mutate(y = transpose(x, 2), interval = pitch_interval(x, y))
# A tibble: 3 x 3
  x          y          interval
  <notwrthy> <notwrthy>    <int>
1 c          d                 2
2 e_g        fa                2
3 c'e_'g'    d'f'a'            2

# slightly different example; this is a lag function, not element-wise
x <- as_vector_time("a, c e r r c a, g#, a ac'e'")
x
<Noteworthy string>
  Format: vectorized time
  Values: a, c e r r c a, g#, a <ac'e'>

tibble(pitch = x) %>% mutate(scale_interval = scale_diff(pitch))
# A tibble: 10 x 2
   pitch      scale_int
   <notwrthy> <chr>    
 1 a,         NA       
 2 c          m3       
 3 e          M3       
 4 r          NA       
 5 r          NA       
 6 c          M3       
 7 a,         m3       
 8 g#,        m2       
 9 a          m9       
10 ac'e'      P1  
```

The above examples are using the current release of dplyr. With the upcoming v1.0, I get errors like `mutate() argument pitch errored.` It seems like it has to do with the vectors having classes.

Tibbles can still hold these objects, e.g., `tibble(pitch = x)` works fine alone and I can even mutate `pitch`, as long as the function does not create another classed atomic variable. E.g., the second example will still work because it creates a character variable.

`tibble(pitch = x) %>% mutate(pitch2 = pitch)` works as well. 

But not `tibble(pitch = x) %>% mutate(pitch2 = x)`

Going forward, it seems any such variables would have to be pulled out of tibbles, manipulated, and  then reinserted into a new tibble, just to have them in a tibble (and all done with the `tibble` call). But actually analyzing and manipulating the data "the tidy way" becomes impossible for all such data structures. Is it necessary to remove such a broad functionality? This was one of the beauties of using tibbles and a tidy framework when working with classed atomic objects.

**Comment by hadley** [comment]
Obviously we’re not getting rid of such an important feature — do you really think that we’d eliminate all use of factors, dates, and date-times? Please provide a reprex with the current version of dplyr so we can more quickly figure out what your problem is and suggest a solution.

**Comment by leonawicz** [comment]
Here is a specific errorring example for 1.0. The reason I thought this was intentional was based on what I read in the [NEWS.md](https://github.com/tidyverse/dplyr/blob/master/NEWS.md) about the classed atomic vectors. It was mentioned in the context of `bind_rows` (which I have similar trouble with) near the top.

```
library(dplyr)
library(tabr)
> x <- as_vector_time("c d e f g a b")
> d <- tibble(x = x)
> 
> transpose(d$x, 2) # this works
<Noteworthy string>
  Format: vectorized time
  Values: d e g_ g a b d_'
> 
> mutate(d, y = transpose(x, 2)) # operations inside functions like mutate do not work
Error: `mutate()` argument `y` errored.
i `y` is `transpose(x, 2)`.
x Cannot have zero timesteps. # (thrown by applied function; maybe internal coercion going on?)
Run `rlang::last_error()` to see where the error occurred.
```

That makes complete sense about other popular classes. I'm unsure why it works for some such atomics but not others.

**Comment by leonawicz** [comment]
It looks like it's related to the custom `[` method for `x`. The index function is called when the function is used inside mutate. This returned the expected result in the current release version but errors with the upcoming version as shown above. The specific error thrown about zero timesteps only happens  when `i = 0` in the definition of the custom method:

```
`[.noteworthy` <- function(x, i){
  if(all(i == 0)) stop("Cannot have zero timesteps.", call. = FALSE)
  # unimportant code
}
```

It looks like the difference from the current release is that the argument `i` to `[` is `1:7` in the current release, because the underlying string is 

```
> as.character(x)
[1] "c" "d" "e" "f" "g" "a" "b"
```

but in the upcoming release `i` appears to be `integer(0)`.

**Comment by leonawicz** [comment]
Okay so I'm not sure why, but I think I can circumnavigate this issue by adding more checks to my custom method for `[` like the following:

```
`[.noteworthy` <- function(x, i){
  if(!length(i) || any(is.na(i))) i <- seq_along(x)
  if(all(i == 0)) stop("Cannot have zero timesteps.", call. = FALSE)
  # unimportant code
}
```

Maybe I should have before, I don't know, but the change with the upcoming release is that when using functions like `mutate` I have to check my custom `[` method for cases where index `i` in `x[i]` can either be `integer(0)` or a vector of `NA` equal to the length of `x`.

Don't know if that's intended, but I can work with it. My apologies for confusing it with the `bind_rows`-related mention about classed atomics not being supported in some manner. I misunderstood what that was about. Thank you.

**Comment by jeffreypullin** [comment]
Hi @leonawicz 

Consider having a look at [this](https://vctrs.r-lib.org/articles/type-size.html) for an explanation of why the changes you mentioned are needed for `vctrs/mutate`.

I think that a minimal reprex for the problem you are having with `dplyr` is really:

``` r
library(tabr)
library(vctrs)

x <- as_vector_time("c d e f g a b")
vec_ptype(x)
#> Error: Cannot have zero timesteps.
```

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by leonawicz** [comment]
@jeffreypullin thank you. This is a very helpful resource.

I think the take away message here is that if I am implementing a lot of methods for generics like `[`, `length`, `rep`, etc., and I also want a class to work seamlessly in the Tidyverse, then I need to know how `vctrs` functions will interpret it.
