### ISSUE TITLE
possible circularity when installing dplyr 1.0 with devtools

### ISSUE THREAD

**Issue by bergsmat** [tidyverse/dplyr#5016]
Hi.  Romain asked me to post this.  I tried to install dplyr from github using `devtools::install_github()` to resolve expected CRAN package incompatibilities with dplyr 1.0.0.  However, head of master currently needs rlang_0.4.5.9000, and devtools imports rlang, which can't be re-installed while in use. (I can't use devtools to update rlang for the same reason.)  Happy to post the output if helpful.  And apologies in advance if I've missed an obvious workaround.  I'm not seeing a solution on SO for "install devtools dependencies from github".

**Comment by krlmlr** [comment]
In this particular situation I'd advise to use `remotes::install_github("r-lib/rlang")` . The remotes package only depends on base packages.

**Comment by romainfrancois** [comment]
Thanks @krlmlr I'll close this now, @bergsmat feel free to come back if this is not enough of a fix.

**Comment by bergsmat** [comment]
This works for me, thanks.  I also had to remove the 'glue' package manually, and I had to use `remotes::install_github` both for 'rlang' and 'dplyr'.
