### ISSUE TITLE
Unusual Subsetting Behavior

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#5018]
I have an issue that I can't quite isolate to a simple reprex.  When I run the code below with the first `sessionInfo()` below, it works correctly.  When I run it with the second `sessionInfo()`, `d_dose$Subject` is an ordered factor instead of numeric.

```r
d_conc <-
  datasets::Theoph %>%
  mutate(Subject=as.numeric(as.character(Subject)))
## Generate the dosing data
d_dose <- d_conc[d_conc$Time == 0,]
d_dose$Time <- 0
class(d_conc$Subject)
class(d_dose$Subject)
```

First sessioninfo: *************
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_0.3.0.9001 dplyr_0.8.99.9002

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        rstudioapi_0.11   knitr_1.28        magrittr_1.5      tidyselect_1.0.0  R6_2.4.1          rlang_0.4.5.9000  styler_1.3.2     
 [9] highr_0.8         tools_3.6.2       xfun_0.12         clipr_0.7.0       htmltools_0.4.0   yaml_2.2.1        digest_0.6.25     tibble_2.1.3     
[17] lifecycle_0.2.0   crayon_1.3.4      processx_3.4.2    callr_3.4.2       purrr_0.3.3       ps_1.3.2          vctrs_0.2.99.9010 fs_1.3.2         
[25] glue_1.3.2        evaluate_0.14     rmarkdown_2.1     compiler_3.6.2    pillar_1.4.3      backports_1.1.5   pkgconfig_2.0.3  

Second sessioninfo: *************
 R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.99.9002 PKNCA_0.9.3       testthat_2.3.2   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3             compiler_3.6.2         pillar_1.4.3           prettyunits_1.0.2.9000 remotes_2.1.1          tools_3.6.2           
 [7] digest_0.6.25          pkgbuild_1.0.6         pkgload_1.0.2          praise_1.0.0           memoise_1.1.0          lifecycle_0.2.0       
[13] tibble_2.1.3           nlme_3.1-145           lattice_0.20-40        pkgconfig_2.0.3        rlang_0.4.5.9000       cli_2.0.2             
[19] rstudioapi_0.11        parallel_3.6.2         withr_2.1.2            desc_1.2.0             fs_1.3.2               vctrs_0.2.99.9010     
[25] devtools_2.2.2         grid_3.6.2             rprojroot_1.3-2        tidyselect_1.0.0       glue_1.3.2             R6_2.4.1              
[31] processx_3.4.2         fansi_0.4.1            sessioninfo_1.1.1      tidyr_1.0.2.9000       callr_3.4.2            purrr_0.3.3           
[37] magrittr_1.5           MASS_7.3-51.5          backports_1.1.5        ps_1.3.2               ellipsis_0.3.0         usethis_1.5.1         
[43] assertthat_0.2.1       crayon_1.3.4

**Comment by romainfrancois** [comment]
I cannot reproduce this: 

``` r
library(dplyr, warn.conflicts = FALSE)

d_conc <- datasets::Theoph %>%
  mutate(Subject=as.numeric(as.character(Subject)))
## Generate the dosing data
d_dose <- d_conc[d_conc$Time == 0,]
d_dose$Time <- 0
class(d_conc$Subject)
#> [1] "numeric"
class(d_dose$Subject)
#> [1] "numeric"
```

<sup>Created on 2020-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-03-23                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date       lib source                      
#>  assertthat    0.2.1       2019-03-21 [1] CRAN (R 3.6.0)              
#>  backports     1.1.5       2019-10-02 [1] CRAN (R 3.6.0)              
#>  callr         3.4.2       2020-02-12 [1] CRAN (R 3.6.0)              
#>  cli           2.0.2       2020-02-28 [1] CRAN (R 3.6.0)              
#>  crayon        1.3.4       2017-09-16 [1] CRAN (R 3.6.0)              
#>  desc          1.2.0       2018-05-01 [1] CRAN (R 3.6.0)              
#>  devtools      2.2.2       2020-02-17 [1] CRAN (R 3.6.0)              
#>  digest        0.6.25      2020-02-23 [1] CRAN (R 3.6.0)              
#>  dplyr       * 0.8.99.9002 2020-03-23 [1] local                       
#>  ellipsis      0.3.0       2019-09-20 [1] CRAN (R 3.6.0)              
#>  evaluate      0.14        2019-05-28 [1] CRAN (R 3.6.0)              
#>  fansi         0.4.1       2020-01-08 [1] CRAN (R 3.6.0)              
#>  fs            1.3.2       2020-03-05 [1] CRAN (R 3.6.0)              
#>  glue          1.3.2       2020-03-12 [1] CRAN (R 3.6.0)              
#>  highr         0.8         2019-03-20 [1] CRAN (R 3.6.0)              
#>  htmltools     0.4.0       2019-10-04 [1] CRAN (R 3.6.0)              
#>  knitr         1.28        2020-02-06 [1] CRAN (R 3.6.0)              
#>  lifecycle     0.2.0       2020-03-06 [1] CRAN (R 3.6.0)              
#>  magrittr      1.5         2014-11-22 [1] CRAN (R 3.6.0)              
#>  memoise       1.1.0       2017-04-21 [1] CRAN (R 3.6.0)              
#>  pillar        1.4.3       2019-12-20 [1] CRAN (R 3.6.0)              
#>  pkgbuild      1.0.6       2019-10-09 [1] CRAN (R 3.6.0)              
#>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 3.6.0)              
#>  pkgload       1.0.2       2018-10-29 [1] CRAN (R 3.6.0)              
#>  prettyunits   1.1.1       2020-01-24 [1] CRAN (R 3.6.0)              
#>  processx      3.4.2       2020-02-09 [1] CRAN (R 3.6.0)              
#>  ps            1.3.2       2020-02-13 [1] CRAN (R 3.6.0)              
#>  purrr         0.3.3.9000  2020-03-18 [1] local                       
#>  R6            2.4.1       2019-11-12 [1] CRAN (R 3.6.0)              
#>  Rcpp          1.0.4       2020-03-17 [1] CRAN (R 3.6.0)              
#>  remotes       2.1.1       2020-02-15 [1] CRAN (R 3.6.0)              
#>  rlang         0.4.5.9000  2020-03-19 [1] Github (r-lib/rlang@a90b04b)
#>  rmarkdown     2.1         2020-01-20 [1] CRAN (R 3.6.0)              
#>  rprojroot     1.3-2       2018-01-03 [1] CRAN (R 3.6.0)              
#>  sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 3.6.0)              
#>  stringi       1.4.6       2020-02-17 [1] CRAN (R 3.6.0)              
#>  stringr       1.4.0       2019-02-10 [1] CRAN (R 3.6.0)              
#>  testthat      2.3.2       2020-03-02 [1] CRAN (R 3.6.0)              
#>  tibble        2.1.3       2019-06-06 [1] CRAN (R 3.6.0)              
#>  tidyselect    1.0.0       2020-01-27 [1] CRAN (R 3.6.0)              
#>  usethis       1.5.1       2019-07-04 [1] CRAN (R 3.6.0)              
#>  vctrs         0.2.99.9010 2020-03-20 [1] Github (r-lib/vctrs@69cff44)
#>  withr         2.1.2       2018-03-15 [1] CRAN (R 3.6.0)              
#>  xfun          0.12        2020-01-13 [1] CRAN (R 3.6.0)              
#>  yaml          2.2.1       2020-02-01 [1] CRAN (R 3.6.0)              
#> 
#> [1] /Users/romainfrancois/.R/library/3.6
#> [2] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by billdenney** [comment]
I'm having difficulty defining exactly how to reproduce it, too.  I'll close it now, and if someone has a similar issue in the future, hopefully this will provide a hint to find the underlying issue.

**Comment by billdenney** [comment]
@romainfrancois, this has come back up, and PKNCA is getting an error on current CRAN builds.  I'm able to duplicate it with the current rocker/r-devel Docker container (https://hub.docker.com/r/rocker/r-devel/dockerfile).

``` r
library(dplyr)
#>
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#>
#>     filter, lag
#> The following objects are masked from 'package:base':
#>
#>     intersect, setdiff, setequal, union
library(PKNCA)

d_conc <-
  datasets::Theoph %>%
  mutate(Subject=as.numeric(as.character(Subject)))
## Generate the dosing data
d_dose <- d_conc[d_conc$Time == 0,]
d_dose$Time <- 0
class(d_conc$Subject)
#> [1] "numeric"
class(d_dose$Subject)
#> [1] "ordered" "factor"
```

<sup>Created on 2020-06-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 4.0.0 (2020-04-24)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Debian GNU/Linux bullseye/sid
#>
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#>
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
#>
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base
#>
#> other attached packages:
#> [1] PKNCA_0.9.3 dplyr_1.0.0
#>
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.4.6     knitr_1.28       magrittr_1.5     tidyselect_1.1.0
#>  [5] lattice_0.20-41  R6_2.4.1         rlang_0.4.6      stringr_1.4.0
#>  [9] highr_0.8        tools_4.0.0      parallel_4.0.0   grid_4.0.0
#> [13] nlme_3.1-147     xfun_0.14        htmltools_0.4.0  ellipsis_0.3.1
#> [17] yaml_2.2.1       digest_0.6.25    tibble_3.0.1     lifecycle_0.2.0
#> [21] crayon_1.3.4     tidyr_1.1.0      purrr_0.3.4      vctrs_0.3.0
#> [25] glue_1.4.1       evaluate_0.14    rmarkdown_2.2    stringi_1.4.6
#> [29] compiler_4.0.0   pillar_1.4.4     generics_0.0.2   pkgconfig_2.0.3
```

</details>

**Comment by billdenney** [comment]
Update: with a look at the CRAN check results and my experience on my local systems, the problem appears to be specific to Linux (and Solaris from CRAN) but not Windows (or Mac from CRAN).

**Comment by billdenney** [comment]
Kurt Hornik and I have been emailing separately from this, and he isolated the fact that the error appears to be that `mutate()` drops all classes but "data.frame" when running on Windows (and I'd guess Mac) while it leaves them when running on Linux (and I'd guess Solaris).

Linux:

```r
> library(dplyr)
> d_conc <-
+   datasets::Theoph %>%
+   mutate(Subject=as.numeric(as.character(Subject)))
> class(d_conc)
[1] "nfnGroupedData" "nfGroupedData"  "groupedData"    "data.frame"
```

Windows:

```r
> library(dplyr)
> d_conc <-
+   datasets::Theoph %>%
+   mutate(Subject=as.numeric(as.character(Subject)))
> class(d_conc)
[1] "data.frame"
```

Casting the input with `as.data.frame()`, both systems give the same output:

```
> d_conc <-
+   as.data.frame(datasets::Theoph) %>%
+   mutate(Subject=as.numeric(as.character(Subject)))
> class(d_conc)
[1] "data.frame"
```

I think that leaving the classes intact is the correct result given the way that dplyr generally works (so the Windows class output from mutate appears to be an issue).  With the Linux behavior, Kurt noted that `[.groupedData()` from `nlme` is being called for the `[` at the end of the reprex, and that is likely where the change back to an ordered factor is occurring.

**Comment by hadley** [comment]
It seems extremely unlikely that the problem is windows specific; it's far more likely that you have a different version of dependencies on the different platforms.

**Comment by gaborcsardi** [comment]
This is R 4.0.2 and dplyr 1.0.1 on Windows:

```r
> library(dplyr, warn.conflicts = FALSE)
> df <- mutate(datasets::Theoph, Subject = as.numeric(as.character(Subject)))
> class(df)
[1] "nfnGroupedData" "nfGroupedData"  "groupedData"    "data.frame"    
```

**Comment by billdenney** [comment]
Yes, it has resolved on my system with the current versions of everything.

**Comment by billdenney** [comment]
@gaborcsardi and @hadley, it has come up a few times in the past where dplyr changes the class of its inputs accidentally.  I think that adding a test to confirm that something more complex like this is not affected could help.  Would you accept a PR that adds a test to confirm that the class is not changed?

```r
expect_equal(class(mutate(datasets::Theoph, Subject = as.numeric(as.character(Subject)))), class(datasets::Theoph))
```

**Comment by hadley** [comment]
I don't think adding tests without some idea of the generating process is a good idea.

**Comment by billdenney** [comment]
@hadley, This was coming up not just on my system but also on CRAN checks.  While I cannot point to a specific generating process, I was able to point to a very specific scenario that generated the issue.  Putting this in as a test will ensure that similar problems won't come up in the future for both me
