### ISSUE TITLE
Explore using more explicit column referencing

### ISSUE THREAD

**Issue by colearendt** [tidyverse/dplyr#5019]
https://github.com/tidyverse/dplyr/blob/30363bf501349be8536f9e332f1ce8846883c46b/R/group_data.R#L44

This illustrated a bug in a package I maintain - it extends `[`, but we did not realize `[` with a single argument does column reference.

``` r
obj <- tibble::tibble(col1 = c(1,2), col2 = c(3,4))

obj[0]
#> # A tibble: 2 x 0
obj[1]
#> # A tibble: 2 x 1
#>    col1
#>   <dbl>
#> 1     1
#> 2     2
obj[1,]
#> # A tibble: 1 x 2
#>    col1  col2
#>   <dbl> <dbl>
#> 1     1     3
obj[,1]
#> # A tibble: 2 x 1
#>    col1
#>   <dbl>
#> 1     1
#> 2     2
```

<sup>Created on 2020-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I wonder whether using `[,0]` would be a "better" or more explicit practice here, or if it makes a difference. 🤷‍♂ 

I have fixed the bug in my package now, but it definitely threw me for a loop!! Wanted to mention it in case others are affected.

**Comment by krlmlr** [comment]
Do we need

```r
out <- vec_init(vec_slice(.data, 0), 1) 
```

for the general case?

**Comment by romainfrancois** [comment]
@krlmlr this is not what we want here, @colearendt yes perhaps `[, 0]` protects against wrong implementations of `[`, which is so weird.
