### ISSUE TITLE
dplyr 0.8.9.9000 group_modifiy backwards incompatability 

### ISSUE THREAD

**Issue by edwindj** [tidyverse/dplyr#5020]
The `group_modify` generic has changed the name of its first argument `.tbl` into `.data` which introduces a backwards incompatability for other packages that implement the method. They will not pass CRAN check with the current < 1.0.0 dplyr version. 

It generates the following warning:
```r
devtools:check()
``` 
```
...
W  checking S3 generic/method consistency (3.8s)
   group_modify:
     function(.tbl, .f, ..., keep)
   group_modify.chunkwise:
     function(.data, .f, ..., keep)
...
```

**Comment by romainfrancois** [comment]
Unfortunately there is not much we can do to have a smooth transition. `group_modify()` is an experimental concept and `.data` is the right name for the argument

In these cases I think releasing your package very soon after dplyr 1.0.0 is released is fine.

**Comment by hadley** [comment]
It is possible to conditionally export different versions of the function depending on dplyr. It's moderately complicated, but I'm happy to show you how to do it if you want.

**Comment by edwindj** [comment]
It would be really helpful if you could show me the code for that! 

Best,

Edwin

**Comment by hadley** [comment]
Basically you need to do something like this:

```R
delayedAssign("group_modify.chunkwise", {
  if (".data" %in% names(formals(dplyr::group_modify))) {
    function(.data, .f, ..., keep) {
      ...
    }
  } else {
    function(.tbl, .f, ..., keep) {
      ...
    }
  }
}
```

The idea of using `delayedAssign` is that the if statement will only get evaluated (a) if the function is actually used (so there's no performance impact) and (b) at the right time, i.e. when someone is actually using the package.

We just added support for `delayedAssign()` in the latest version of roxygen2, so you might need to upgrade if you're using roxygen2. Also, while we've tried out this idea in practice, we haven't used it in a CRAN package yet, so although I don't expect any problems, you are pioneering this technique. (If it doesn't work, there's a slightly less elegant approach we can use)

**Comment by hadley** [comment]
(Also I'm assuming that you're not actually documenting this method in a `.Rd`; if you are, things get much harder)

**Comment by edwindj** [comment]
Thanks! Currently testing, I will upload the fix to CRAN.

**Comment by edwindj** [comment]
On its way to CRAN
