### ISSUE TITLE
dplyr 1.0.0 depends on rlang 0.4.5.9000

### ISSUE THREAD

**Issue by knausb** [tidyverse/dplyr#5023]
Trying to prepare vcfR for dplyr 1.0.0. Thank you for the detailed e-mail! In order to troubleshoot this I've followed directions at [your blog](https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-is-coming-soon/) to install dplyr. Following the directions

```
remotes::install_github("tidyverse/dplyr")
```

fails to install dplyr on my machine. I feel the relevant line is below.

```
E>   namespace ‘rlang’ 0.4.5 is being loaded, but >= 0.4.5.9000 is required
```

I do not know how `rlang` handles versioning, but I'm used to this sort of number being used for a development version and not a production version. If my interpretation is correct then I am concerned that this is not a good idea. Just checking that this is your intent. Thanks!

**Comment by hadley** [comment]
Yes, the dev version of dplyr currently depends on the dev version of rlang. We’ll be releasing rlang before we release dplyr.
