### ISSUE TITLE
lag() does not work similarly on matrices

### ISSUE THREAD

**Issue by sewouter** [tidyverse/dplyr#5028]
The lag() function works differently in the new version of dplyr, which was not documented in the infopage https://github.com/tidyverse/dplyr/blob/master/NEWS.md.

First time posting an issue, please correct me if I'm doing this wrong in any way

```
# test difference with dplyr 0.8.5 and development version

m       <- matrix(1:120, ncol = 12)
n       <- 1L
default <- NA
  
res <- lag(m, n, default = default)

```

**Comment by romainfrancois** [comment]
Thanks for the issue @sewouter. I'll have a look. 

You might enjoy the `reprex` package, which I've used to produce the content below based on the code you shared: 

``` r
library(dplyr, warn.conflicts = FALSE)

m       <- matrix(1:120, ncol = 12)
lag(m, 1L)
#> Error: Can't subset elements that don't exist.
#> x The locations 11, 12, 13, 14, 15, etc. don't exist.
#> ℹ There are only 10 elements.
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

See e.g. this talk https://resources.rstudio.com/rstudio-conf-2020/object-of-type-closure-is-not-subsettable-jenny-bryan
