### ISSUE TITLE
Missing documentation of `grouped_df`, `is.grouped_df` and `is_grouped_df`

### ISSUE THREAD

**Issue by jarauh** [tidyverse/dplyr#5030]
These three functions share a documentation page, which does not describe any of these functions.

**Comment by hadley** [comment]
Because they're for internal use. What are you trying to do?

**Comment by jarauh** [comment]
I'm trying to figure out if a data.frame is grouped.  Sometimes, starting a pipe with a data.frame that is grouped "by accident" may lead to unexpected results, so I want to check.  I thought that `is_grouped_df()` would sound like a natural option.
