### ISSUE TITLE
new segfault found in dplyr 1.0 dev version

### ISSUE THREAD

**Issue by gergness** [tidyverse/dplyr#5033]
When trying to prepare a downstream dependency for the 1.0 release, I was getting inconsistent results from my checks. I think I've narrowed down the problem to this code, which can reliably cause a segfault when using valgrind. 

I think each part is required, the df needs to have an attribute, the `bind_cols` must be done with a list and the `data.frame` must be converted to a `tibble`.

For my purposes, I think I can avoid by coercing the list to a data.frame, but still felt worth mentioning here.

```r
library(dplyr)

df <- data.frame(x = 1:2)
attr(df, "something") <- list("something")

new_col <- list(y = 3:4)
df <- bind_cols(df, new_col)

df <- as_tibble(df)

df %>%
  mutate(new_var = as.character(x))
```

[Attached is the valgrind output](https://github.com/tidyverse/dplyr/files/4376890/valgrind.output.txt)

**Comment by lionel-** [comment]
Can you try again with the latest dev vctrs please? It's possible this was fixed in https://github.com/r-lib/vctrs/commit/71aedcf42d8fdedc2e3f344af18813d9cf71acff

**Comment by gergness** [comment]
Indeed it did, thanks!
