### ISSUE TITLE
Errors crash R session

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#5035]
The following code will crash the R session:

```
require(tidyverse)
mtcars2 <- mtcars %>% mutate(mpg = as.character(mpg))
bind_rows(mtcars, mtcars2)
```

I can reproduce this every time on one of my computers.  On another, it works fine and produces the error `Column mpg can't be converted from numeric to character` as it should.

On the crashing computer, I recently made some changes in an attempt to get my nemesis rJava to work.  Including updating gcc to version 9.  Could this be the cause?  Let me know what diagnostics I can provide from one or both computers.

**Comment by hadley** [comment]
This almost always implies that you have a mismatched version of a dependency, and that you'll need to reinstall all your packages. Make sure you close all existing R processes then run `install.packages("tidyverse", dependencies = TRUE)`

**Comment by jzadra** [comment]
Thanks Hadley.  For whatever reason it only updated the feather dependency and still had the issue.  I burned everything down, deleted all my libraries, and reinstalled the latest R.  Seems to have fixed it.
