### ISSUE TITLE
HIVE functions in summarize_all does not work for SPARK data frames

### ISSUE THREAD

**Issue by cat-zeppelin** [tidyverse/dplyr#5043]
dplyr does not handle hive functions under 'summarize_all' (see reprex below) while working with spark data frames

```r

library(sparklyr)
library(tidyverse)
library(reprex)

sc <- spark_connect(master = "local")

df <- tibble(
    a = seq(10),
    b = seq(10) + 2
)

df <- copy_to(sc, df)

# HIVE function in 'summarize' - works

df %>% 
    summarise(
        a = collect_list(a),
        b = collect_list(b)
    )
#> # Source: spark<?> [?? x 2]
#>   a           b          
#>   <list>      <list>     
#> 1 <list [10]> <list [10]>

# R function in 'summarize_all' - works

df %>% 
    summarise_all(
        sum
    )

#> # Source: spark<?> [?? x 2]
#>       a     b
#>   <dbl> <dbl>
#> 1    55    75

# HIVE function in 'summarize_all' - does not work

df %>% 
    summarise_all(
        collect_list
    )
#> Error in is_fun_list(.funs): object 'collect_list' not found```

**Comment by romainfrancois** [comment]
This probably belongs to the `sparklyr` issue: https://github.com/sparklyr/sparklyr/issues cc @javierluraschi.

**Comment by cat-zeppelin** [comment]
> This probably belongs to the `sparklyr` issue page: https://github.com/sparklyr/sparklyr/issues
> 
> cc @javierluraschi.

i only put it here because

_We can access the functions by calling them as if they were R functions. Instead of failing, **dplyr** passes functions it does not recognize as is to the query engine_

from https://therinspark.com/analysis.html Section 3.3.1 Built-in Functions, 1st paragraph

**Comment by hadley** [comment]
Or in dbplyr; it's definitely not a dplyr issue.
