### ISSUE TITLE
Found the following significant warnings:   Warning: `select_()` is deprecated as of dplyr 0.7.0.

### ISSUE THREAD

**Issue by tfkillian** [tidyverse/dplyr#5062]
I maintain the [depmap Bioconductor package](https://github.com/UCLouvain-CBIO/depmap) which fully depends on dplyr. I wanted to get a head start to update the package in line for the dplyr 1.0 release. After installing the development version of dplyr, I have updated the code in the vignettes in the depmap package to be line with the scheduled dplyr 1.0 changes, however I still get the same warning when checking the package: 

```
* checking whether package ‘depmap’ can be installed ... WARNING
Found the following significant warnings:
  Warning: `select_()` is deprecated as of dplyr 0.7.0.
  Warning: `filter_()` is deprecated as of dplyr 0.7.0.
```

Do you know why this error is being displayed? I find this confusing because nowhere in my package are the select_`*`() or filter_`*`() functions utilized, only the plain vanilla  select() or filter() functions as shown below in an example:

```
rnai %>% dplyr::select(entrez_id, cell_line,  gene_name, dependency) %>%
                dplyr::filter(entrez_id == "4780")
```

Could this error be cause by not using the .data pronoun in the select() or filter() functions?

**Comment by hadley** [comment]
I'd recommend using `options(warn = 2)` to convert the warning into an error so you can figure out where it's coming from.

**Comment by hadley** [comment]
(I forgot to say, no, it's unlikely that the presence or absence of `.data` has anything to do with this)

**Comment by melissagwolf** [comment]
I am getting this same error.  I too am only using select() not select_().

**Comment by tfkillian** [comment]
@melissagwolf does your package depend on other packages that might be using select_()? I found that in my case, even though I only used select() in my package, I got this same error upon checking and it was in fact due to code found in one of my package dependencies, BiocFileCache which used that function. https://github.com/Bioconductor/BiocFileCache/issues/23

**Comment by melissagwolf** [comment]
Ahhhhh, I didn't think of that. I'm not actually maintaining a package (just regular code), but I'm only using tidyverse and one other package.  I think I get the warning after running select() from dplyr.  I am also using lavaan somewhere else in the script, so it's possible it's using select_() somewhere and that's the issue.

**Comment by hadley** [comment]
If you use `options(warn = 2)` then the warning will become and error, and then you can use a traceback to figure out exactly where the error is coming from.
