### ISSUE TITLE
Consider bind_cols() alternatives

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#5063]
So we can have experimental solution without forcing logic into vctrs.

**Comment by elinw** [comment]
Is this potentially why bind_rows() is throwing "No common type" errors? It doesn't make sense to me that if the same-named variables are the same type that binding rows with other columns should require the same type of data (especially since the documentation doesn't seem to mention this).
```
bind_rows(
  c(a = 1, b = 2),
   c(a = 3, c = "a")
 )
Error: No common type for `..1$a` <double> and `..2$a` <character>.
```

**Comment by hadley** [comment]
@elinw that seems unrelated — using `c()` coerces all inputs to same type so I think dplyr is doing the right thing here.

**Comment by hadley** [comment]
I'm starting to think that perhaps `bind_cols()` is not well specified — I presume we implemented it to parallel `bind_rows()`, but it's not clear to me that this is a case where it makes sense to have an exact parallel (or perpendicular 😆). 

Perhaps it would make more sense to have `left_bind(x, y)` and `right_bind(x, y)` which would behave more like `left_join()` and `right_join()`, i.e. they always take two data frames, and the type of the output is determined by `x`. This idea appeals to me for a few reasons:

1. People often seem confused by whether they need a join or a bind, so placing them nearby in the interface, would make it more clear what the two basic options are.

2. It means we don't have to think about the type of the output; if `x` and `y` are different types, then the user has a simple control over which type they get. 

3. `left_bind(x, y)` binds `y` to `x`, so I think saying the result type is the same as x should be reasonable intuitive

4. It's substantially simpler than `bind_cols()` which takes cues from `cbind()` and allows you to bind both frames and free floating vectors, and because it takes `...` also has to wrestle with issues of outer vs inner names.

5. Unlike row-binding, when column-binding you can use `reduce()` without a significant performance penalty.

(I also considered `bind_right()` and `bind_left()` but I think these new functions are more analogous to the existing join functions (despite the use of the somewhat inconsistent `join` suffix)

**Comment by hadley** [comment]
@jennybc noticed that `left_bind(x, y)` is very similar to `mutate(x, y)` and `mutate()` already has `.before` and `.after` arguments that control where the columns would go. 

So maybe these functions aren't needed at all, and we should just mark `bind_cols()` as questioning?

**Comment by lionel-** [comment]
> left_bind(x, y) is very similar to mutate(x, y) and mutate() already has .before and .after arguments that control where the columns would go.

oh because of auto-splicing? Neat! Maybe `left_bind()` will still be useful as a user-friendly entry point, it's still unclear how intuitive auto-splicing will be for end users.

Just a note that the tidyr internals rely on `append_df()` (see https://github.com/tidyverse/tidyr/blob/master/R/append.R). I initially imagined this function would eventually be based on a vctrs colwise `c()` operation, but it looks like it could be implemented using left-bind / mutate instead.

I think it'd be better not to mark `bind_cols()` as questioning, we need more time to think about this and in the worst case it'll just be superseded.

**Comment by hadley** [comment]
Let's keep thinking about this; I don't think we need to resolve it before the 1.0.0 release.

**Comment by elinw** [comment]
Wouldn't losing the ability to work on a list of data frames a substantial change?

**Comment by hadley** [comment]
@elinw you can still call `vctrs::vec_cbind()`, or use `reduce()` + `left_bind()`. It's odd to have a list of data frames that just happen to line up exactly the right way when you bind them together. Because there's no way to tell if you've actually lined them up correctly, it's a fundamentally dangerous operation, and not one that I think dplyr needs to make terribly easy.

**Comment by elinw** [comment]
That's totally correct, but with both of these one of the practical reasons people use them is that dealing with more than two data frames is complicated. The description in the documentation of dplyr bind is "This is an efficient implementation of the common pattern of do.call(rbind, dfs) or do.call(cbind, dfs) for binding many data frames into one." So most likely that is what many users are using it for (there are plenty of easy ways to combined exactly two data frames).  Most likely yes using something based on a join would be better.

**Comment by hadley** [comment]
@elinw the documentation is wrong — `bind_cols()` isn't actually much more efficient than `do.call(cbind, dfs)`. The discussion here isn't about eliminating these functions altogether (and even if we decided they should go, they'd still be superseded for a long time); it's about spitballing ideas for what the optimal interface really should be.

**Comment by cochetti** [comment]
Is related to and could potentially be solved by my cross_join concern in #5246.

A bind_cols is just a rowwise cross_join... is it not?

**Comment by romainfrancois** [comment]
Is this perhaps in the territory of `relocate()` ? 

``` r
library(dplyr)

blend <- function(x, y, .before = NULL, .after = NULL) {
  z <- vctrs::vec_cbind(x, y)  
  relocate(z, !!!syms(names(y)), .before = {{.before}}, .after = {{.after}})
}

df1 <- tibble(x = 1:3, y = 11:13)
df2 <- tibble(a = letters[1:3], b = 1:3  )

df1 %>% 
  blend(df2, .after = x)
#> # A tibble: 3 x 4
#>       x a         b     y
#>   <int> <chr> <int> <int>
#> 1     1 a         1    11
#> 2     2 b         2    12
#> 3     3 c         3    13
```

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by romainfrancois** [comment]
could be a `x, ...` interface making `y` with `new_data_frame(df_list(...))`: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

blend <- function(x, ..., .before = NULL, .after = NULL, .name_repair = c("check_unique", "unique", "universal", "minimal")) {
  y <- vctrs::new_data_frame(vctrs::df_list(..., .name_repair = .name_repair))
  z <- vctrs::vec_cbind(x, y)  
  relocate(z, !!!syms(names(y)), .before = {{.before}}, .after = {{.after}})
}

df1 <- tibble(x = 1:3, y = 11:13)
df2 <- tibble(a = letters[1:3], b = 1:3  )

df1 %>% 
  blend(df2, .after = x)
#> # A tibble: 3 x 4
#>       x a         b     y
#>   <int> <chr> <int> <int>
#> 1     1 a         1    11
#> 2     2 b         2    12
#> 3     3 c         3    13

df1 %>% 
  blend(a = letters[1:3], b = 1:3, .after = x)
#> # A tibble: 3 x 4
#>       x a         b     y
#>   <int> <chr> <int> <int>
#> 1     1 a         1    11
#> 2     2 b         2    12
#> 3     3 c         3    13
```

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
I'm no longer convinced that we need to do anything here. `bind_cols()` is relatively rarely used and seems to generate few issues, so I don't think we need to fully explore the semantics. For now, I'll separate the docs for `bind_rows()` and `bind_cols()` because I'd like to emphasise the risks of `bind_cols()` a little more.
