### ISSUE TITLE
Error: 'vec_as_subscript' is not an exported object from 'namespace:vctrs'

### ISSUE THREAD

**Issue by Michael-Sheppard** [tidyverse/dplyr#5064]
See https://github.com/tidyverse/dplyr/issues/5048. Now I am getting this error again, except for vec_as_subscript instead of vec_as_subscript2. I've reinstalled vctrs, made sure my packages were up to date, and it still seems like this hasn't truly been solved. 

This occurred when trying to run a chunk of code containing standard tidyverse functions like filter, gather, etc. The only solution is to close the session and start a new one. The only libraries being loaded are tidyverse, lubridate, and janitor. 

I hope this is fixed soon because this is starting to occur more frequently and interfere with my work.

**Comment by hadley** [comment]
The most likely scenario is that you're on windows, and you're trying to install a package while it's in another R session. This is a known bug with `install.packages()`.

**Comment by Michael-Sheppard** [comment]
No, this is not the case. I am using an instance of RStudio Server Pro. This occurs when only running one session as well.

**Comment by hadley** [comment]
Can you please provide a reprex + traceback? But I'm almost certain it's an install problem

**Comment by Michael-Sheppard** [comment]
I will provide a reprex and traceback the next time this happens. Adding in that this only happens _**sometimes**_. That is what is so weird about the error. This usually occurs an hour so into my session. All libraries are loaded at the very beginning so there are no strange collisions occurring. 
Restarting the session has been the only solution for me and my colleagues when we experience this error.

**Comment by Michael-Sheppard** [comment]
I am no longer experiencing this issue after I uninstalled tidyverse, pillar, and vctrs and then reinstalling all 3.
