### ISSUE TITLE
Suggestion: remember() and recall()

### ISSUE THREAD

**Issue by msberends** [tidyverse/dplyr#5068]
I would like to suggest two new functions: `remember()` and `recall()`. The idea is to (temporarily) save values to the global environment that can later be used in the same command. This way, saved values can be used in functions like `ggplot()` following after a series of pipes, without having to save the value using an intermediate command.

For example (schematic):

```r
data %>%
  filter(...) %>%
  remember(rows = nrow(.)) %>%
  group_by(...) %>%
  summarise(...) %>%
  ggplot() +
  labs(subtitle = paste("Number of observations:", recall(rows)))
```

For the field of epidemiology (and probably other fields as well) it is important to state e.g. the number of observations to be able to interpret the data, but you could think of endless ways of using this. I would now do:

```r
obs <- data %>%
  filter(...) %>%
  nrow()

data %>%
  filter(...) %>%
  group_by(...) %>%
  summarise(...) %>%
  ggplot() +
  labs(subtitle = paste("Number of observations:", obs))
```

This means the initials transformations (that could be very complex) have to be run twice. Another option is then of course:
```r
my_complex_transformation <- data %>%
  very_complex_stuff(...)

obs <- my_complex_transformation %>%
  nrow()

my_complex_transformation %>%
  group_by(...) %>%
  summarise(...) %>%
  ggplot() +
  labs(subtitle = paste("Number of observations:", obs))
```

WIth `remember()` and `recall()`, this process would be more convenient and very flexible.

----

The functions code:
```r
remember <- function(.data, ...) {
  dots <- list(...)
  for (i in seq_len(length(dots))) {
    assign(x = names(dots)[i],
           value = dots[[i]],
           envir = globalenv())
  }
  .data
}

recall <- function(x, delete = TRUE) {
  x_name <- deparse(substitute(x))
  x_val <- x
  if (delete == TRUE) {
    rm(list = x_name, envir = globalenv())
  }
  x_val
}
```

**Comment by hadley** [comment]
This just doesn’t feel like a great fit to dplyr to me since it’s really more about temporary assignment within a pipeline. Might something well suited for its own package.

**Comment by msberends** [comment]
No prob 👍
