### ISSUE TITLE
dplyr: trying to rename a column using cbind() fails

### ISSUE THREAD

**Issue by greg-minshall** [tidyverse/dplyr#5074]
i am not sure if this is a bug or a feature.  i expected to end up with columns named "aaa" and "XXXX" for both x and y below.  rather, x ends up with two columns named "aaa" (which, i assume, gets x "kicked out" of its "tbl.df" status).  i (now) realize i can do something similar in a more-tibble-native way, but the 'principle of least surprise' appears to be being violated here.  cheers.

```r
  require(dplyr)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
  y <- as.tbl(data.frame(aaa=1:3))
  cat(sprintf("y:\n%s\n", str(y)))
#> Classes 'tbl_df', 'tbl' and 'data.frame':    3 obs. of  1 variable:
#>  $ aaa: int  1 2 3
  cat("cbinding\n")
#> cbinding
  y <- cbind(y, XXXX=y[,"aaa"]/3)
  cat(sprintf("y:\n%s\n", str(y)))
#> 'data.frame':    3 obs. of  2 variables:
#>  $ aaa: int  1 2 3
#>  $ aaa: num  0.333 0.667 1
  ## 
  z <- data.frame(bbb=1:3)
  z <- cbind(z, XXXX=z[,"bbb"]/3)
  cat(sprintf("z:\n%s\n", str(z)))
#> 'data.frame':    3 obs. of  2 variables:
#>  $ bbb : int  1 2 3
#>  $ XXXX: num  0.333 0.667 1
```

**Comment by hadley** [comment]
I think using `cbind()` in this way is ill-advised (because the exact semantics of `cbind()` are so complex), so while it might be surprising, we don't have any plans to change the behaviour.

**Comment by greg-minshall** [comment]
va bene così.  stay safe.

**Comment by greg-minshall** [comment]
though i guess: can this (sort of) situation be detected and a warning issued (for the benefit  of the user/programmer)?
