### ISSUE TITLE
name of first argument differs across functions

### ISSUE THREAD

**Issue by elbersb** [tidyverse/dplyr#5082]
While working on the [tidylog](https://github.com/elbersb/tidylog) package, I realized that the first argument of tibble-centric functions is often different: For instance, for `filter`, the first argument is called `.data`, while for `filter_all` (I know, it's deprecated), the first argument is called `.tbl`. There is also `x` for `top_n` and `tbl` (no dot!) for `sample_n`. In tidyr, mainly `data` seems to be used.

This may be a bit late for dplyr 1.0.0, but it would be really nice to have these consistent across functions. Of course, a change might produce a lot of breaking code, so maybe this is too minor an issue to take on.

**Comment by hadley** [comment]
Yes, we use `data`/`.data` on all new functions.

**Comment by hadley** [comment]
Changing existing functions means that every package who has defined a method also needs to change, and given that these arguments are rarely named in actual calls, we don't think the cost of the change is worth the benefit.
