### ISSUE TITLE
Confusing error message inside `c_across()`

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/dplyr#5096]
I am using `rowwise()` and `c_across()` and encountered a confusing error message. Here is a toy case of my situation. I was counting the number of columns containing several strings. The selection inside the second `c_across()` captures the first variable that was `mutate`d, so it is trying to combine character and integer columns. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(stringr)
tibble(ai = c("a", "b", "a"), 
       bi = c("b", "b", "b"), 
       ci = c("a", "b", "c"), 
       d = c("a", "b", "a")) %>% 
  rowwise() %>% 
  mutate(ai_count = sum(str_detect(c_across(contains("i")), pattern = "a")),
         bi_count = sum(str_detect(c_across(contains("i")), pattern = "b")))
#> Error: `mutate()` argument `bi_count` must return compatible vectors across groups.
#> i `bi_count` is `sum(str_detect(c_across(contains("i")), pattern = "b"))`.
```

<sup>Created on 2020-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The error message `Error: `mutate()` argument `bi_count` must return compatible vectors across groups.` is confusing here. It seems to suggest it's a problem across the groups/rows, but it's actually an issue with concatenating variables of different types within the same group. Could this error message be made clearer here?

I also am rather confused as to why this errors at all. I would have expected `c_across()` to have similar coercion behavior as `c()` and to coerce the integer values to charcter.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by bwiernik** [comment]
Done.

**Comment by hadley** [comment]
The reason you get the error is because `ai_count()` contains `i` in it.  

@romainfrancois why don't we get a more informative error message here?

**Comment by bwiernik** [comment]
Yes, I know why the columns are matching. 

What is surprising is that it's erroring because `ai` is character but `ai_count` is integer. It's surprising that `c_across()` doesn't permit concatenation of variables of different types via coercion (like `c()` does). I would expect in case for the second `c_across()` to return a character vector for the first rrow containing `c("a", "b", "a", "2")`, as that is what `c()` does, and the documentation for `c_across()` suggests that it behaves like `c()` except for allowing tidy-select.

**Comment by romainfrancois** [comment]
I see, the problem is that the `tryCatch()` in `mutate_cols()` intercepts a `vctrs_error_incompatible_type` error and believes it comes from unchopping the chunks, but in fact  is unrelated and is thrown from `vec_c(!!!cols)` inside `c_across()`.

**Comment by hadley** [comment]
The error now looks like:

```
Error: Problem with `mutate()` input `bi_count`.
x Can't combine `ai` <character> and `ai_count` <integer>.
ℹ Input `bi_count` is `sum(str_detect(c_across(contains("i")), pattern = "b"))`.
ℹ The error occured in row 1.
```
