### ISSUE TITLE
first() and last() are only able to select single columns. Is this a joke?

### ISSUE THREAD

**Issue by chillywings** [tidyverse/dplyr#5097]
Okay, I use dplyr a lot and I've got a real love/hate relationship going on with it. I have NO shortage of annoyances with these functions, but this is the last straw.

I've just discovered that using the first() or last() selecting functions are ONLY capable of selecting a single column. Are you freaking kidding me? That means the function `first()` does- read carefully here- jack flipping squat. `select(.data, first(3))` LITERALLY equals `select(.data, 3)`. WHY am I going to type extra things for absolutely no purpose?? Sure, `last(n)` is ever so slightly better than `length(.data)-n`, but... are you joking?? Why should I use this if I STILL have to count??

How did I expect these functions to operate such that would ACTUALLY be useful? If type `first(3)`, I expect columns 1, 2, and 3 to be selected. If I type `last(3)`, I expect ALL of the last 3 columns to be selected... not the 3rd from last. Yes, nothing mind blowing here.. equivalents are `1:3` and `length(.data)-3:length(.data)`, but `last()` would actually save me a fair bit of typing and be much easier to read. 

This brings me to the last and most important point- and I don't think I can stress this enough- tidyverse functions are all about being very clean and readable (aka intuitive). So to give a human-friendly/linguistic example here- if you were to say "Select the first 3 marbles" and I hand you only marble number 3, is that going to seem sensible to you? Absolutely not. Unless you've lost your marbles. I would argue the lack of intuitiveness is the primary issue here.

So yeah.. feature request please.

**Comment by hadley** [comment]
I think you've misunderstood the purpose of the `first()` and `last()` functions.
