### ISSUE TITLE
mutate_if "breaks" when used for normalisation

### ISSUE THREAD

**Issue by benjbuch** [tidyverse/dplyr#5101]
When a transformation is applied across columns with a predicate selection, the value of the updated columns is used instead of the original value before the update has completed. Presumably, this behaviour is not expected and leads to unintended results.

Here is an example in which we would like to "normalise" `Sepal.Length`, `Sepal.Width` etc. to `Sepal.Width`:

```r
iris %>% head

#   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
# 1          5.1         3.5          1.4         0.2  setosa
# 2          4.9         3.0          1.4         0.2  setosa
# 3          4.7         3.2          1.3         0.2  setosa
# 4          4.6         3.1          1.5         0.2  setosa
# 5          5.0         3.6          1.4         0.2  setosa
# 6          5.4         3.9          1.7         0.4  setosa

iris %>% mutate_if(is.numeric, ~ . / Sepal.Width) %>% head

#   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
# 1     1.457143           1          1.4         0.2  setosa
# 2     1.633333           1          1.4         0.2  setosa
# 3     1.468750           1          1.3         0.2  setosa
# 4     1.483871           1          1.5         0.2  setosa
# 5     1.388889           1          1.4         0.2  setosa
# 6     1.384615           1          1.7         0.4  setosa
```

Only  the first and the second column are correctly updated. After `Sepal.Width` is "self-normalised", this value (1) is used for `Petal.Width` and `Petal.Length`.

It might be a matter of debate if this behaviour is a "feature" or a "bug", but as the result is solely dependent on the position of the column (the column order), this is rather a bug …

**Comment by hadley** [comment]
This is one of the reasons we now recommend `across()`; see discussion at end of https://dplyr.tidyverse.org/dev/articles/colwise.html#how-do-you-convert-existing-code-
