### ISSUE TITLE
Vignette titles: rowwise and colwise

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#5103]
I think the vignettes called "colwise operations" and "rowwise operations" should be renamed to "Column-wise operations" and "Row-wise operations", respectively. There is a function called `rowwise` but not a function called `colwise`, but the naming and how these are displayed in the vignettes menu (especially the fact that they both start with small letters) makes it seem like there may be a function called `colwise`.

<img width="224" alt="Screenshot 2020-04-13 at 13 22 27" src="https://user-images.githubusercontent.com/5965649/79120104-ee496380-7d89-11ea-955b-93b6de580f59.png">

**Comment by hadley** [comment]
Do you want to do a PR? You just need to update the vignette title in the `.Rmd` (in two places 😬)
