### ISSUE TITLE
Use predicate functions in `across` similar to `mutate_if`

### ISSUE THREAD

**Issue by caldwellst** [tidyverse/dplyr#5105]
Previously, we could provide predicates to `mutate_if` (and `summarize_if`) like:

```r
iris %>%
  mutate_if(~"virginica" %in% .x, paste0, "_")
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2 setosa_
#> 2          4.9         3.0          1.4         0.2 setosa_
#> 3          4.7         3.2          1.3         0.2 setosa_
#> 4          4.6         3.1          1.5         0.2 setosa_
#> 5          5.0         3.6          1.4         0.2 setosa_
#> 6          5.4         3.9          1.7         0.4 setosa_
```
However, using `across`, we are restricted to the tidy-select framework, so either with an `is_` function:
```r 
is_virgin <- function(x) {
  "virginica" %in% x
}

iris %>%
  mutate(across(is_virgin, paste0, "_"))
```
Or column specification:
```r
iris %>%
  mutate(across(which(sapply(., function(x) "virginica" %in% x)), paste0, "_"))
```
Given that `across` is replacing scoped verbs, including `mutate_if` and `summarize_if`, the use of a predicate function would be useful. The former example can be time consuming and confusing when doing multiple `mutate_if` style operations, and the latter is not ideal even for a single use. I think it would be useful to pass in anonymous functions directly, just as the named function can be, in the same syntax as in `mutate_if`. 
```r
iris %>%
  mutate(across(~"virginica" %in% .x, paste0, "_"))
```
I see this isn't likely as it's not able to combine with other tidy select operators, so could this be a use case for a tidy helper that takes anonymous functions and can be combined with other helpers. For lack of a better naming idea, something like `matches_pred`:
```r
iris %>%
  mutate(across(matches_pred(~"virginica" %in% .x), paste0, "_"))
```

**Comment by hadley** [comment]
Would you mind filing in https://github.com/r-lib/tidyselect please?

**Comment by caldwellst** [comment]
Yep! Filed [here](https://github.com/r-lib/tidyselect/issues/187).
