### ISSUE TITLE
Count doesn't work when there is a column named "n"

### ISSUE THREAD

**Issue by brianmsm** [tidyverse/dplyr#5108]
When there is a column called "n" in the database, the count function will generate an error. When you specify the `name =" new_name "` argument, you don't get a runtime error, however the calculation is wrong because it uses the column named "n" automatically as weighting variable.

``` r
library(dplyr, warn.conflicts = FALSE)

example <- tibble(
  x = c("a", "b", "c", "d", "e"),
  y = 1:5,
  n = 11:15
)


example %>% 
  count(x)
#> Using `n` as weighting variable
#> Error: Column 'n' is already present in output
#>  * Use `name = "new_name"` to pick a new name

example %>% 
  count(x, name = "test")
#> Using `n` as weighting variable
#> # A tibble: 5 x 2
#>   x      test
#> * <chr> <int>
#> 1 a        11
#> 2 b        12
#> 3 c        13
#> 4 d        14
#> 5 e        15

table(example$x)
#> 
#> a b c d e 
#> 1 1 1 1 1
```

<sup>Created on 2020-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This is long standing behaviour of count that's unlikely to change.

**Comment by hadley** [comment]
If you want to override this default, you can now set `wt = 1`:

``` r
library(dplyr, warn.conflicts = FALSE)

example <- tibble(
  x = c("a", "b", "c", "d", "e"),
  y = 1:5,
  n = 11:15
)

example %>% count(x)
#> Using `n` as weighting variable
#> # A tibble: 5 x 2
#>   x         n
#> * <chr> <int>
#> 1 a        11
#> 2 b        12
#> 3 c        13
#> 4 d        14
#> 5 e        15
example %>% count(x, wt = 1)
#> # A tibble: 5 x 2
#>   x         n
#> * <chr> <dbl>
#> 1 a         1
#> 2 b         1
#> 3 c         1
#> 4 d         1
#> 5 e         1
```

<sup>Created on 2020-05-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by brianmsm** [comment]
Great!. Although it seems strange to me about the default behavior, because I have code from about 5 months ago that worked well having a column called "n". I guess it was dplyr version 0.8.0.
