### ISSUE TITLE
Is there a reason why there is no is_distinct?

### ISSUE THREAD

**Issue by JBGruber** [tidyverse/dplyr#5111]
I wonder if it would make sense to have a function called `is_distinct()`. It would work like `duplicated()` but with all the `tidyverse` goodness of finding distinct cases by considering unique combinations in several columns. I already typed one up and happy to put it in a PR:

``` r
library(tidyverse)
df <- data.frame(col1 = c(1:3, 1, 4, 4),
                 col2 = c(1, 1:3, 4, 4))
is_distinct <- function(...) {
  columns <- map(enquos(..., .named = TRUE), rlang::eval_tidy)
  data <- as_tibble(columns, .name_repair = "minimal")
  
  loc <- vctrs::vec_unique_loc(data)
  
  out <- logical(nrow(data))
  out[loc] <- TRUE
  out
}
df %>% mutate(unique_case = is_distinct(col1, col2))
#>   col1 col2 unique_case
#> 1    1    1        TRUE
#> 2    2    1        TRUE
#> 3    3    2        TRUE
#> 4    1    3        TRUE
#> 5    4    4        TRUE
#> 6    4    4       FALSE
```
Sometimes I want to know which columns were duplicated before removing them (e.g., to assess whether cases differed in another column). But maybe there is already a solution for this which I couldn't find.

**Comment by hadley** [comment]
I think this would be a good candidate for [funs](https://github.com/r-lib/funs/issues) when it exists. Would you mind filing an issue over there?
