### ISSUE TITLE
Why does row-wise drop attributes?

### ISSUE THREAD

**Issue by mlane3** [tidyverse/dplyr#5116]
I have never done a request on a major package.  However, I really care about this issue. Why does row-wise or a rowbase tidy operation drop attributes and groups?  

https://github.com/tidyverse/dplyr/blob/0c41b4a29d69a807ceac28c5729a01ecad5d43ab/R/rowwise.r#L77

Inside the code for  #rowwise
```r
  group_data <- new_tibble(vec_data(group_data), nrow = nrow) # strip attributes
  group_data$.rows <- new_list_of(as.list(seq_len(nrow)), ptype = integer())
  new_tibble(data, groups = group_data, nrow = nrow, class = "rowwise_df")
```

I am trying to understand better why row-wise currently drops attributes and (optionally) groups.  I been reading up on issue [3558](https://github.com/tidyverse/dplyr/issues/3558), but I am very new to this so I am trying to understand things better.

Best wishes,

mlane

**Comment by hadley** [comment]
Because it's a new type of object, and it's best to start from a clean slate so you know exactly what you have.

**Comment by mlane3** [comment]
I am trying to understand why would it be good to start with a clean slate.
Would there be any harm if someone coded a version that rbinds selected attributes at the end? Or adding a wrapper that does so?  Or trying to make a class that does so?

Certain attributes equal to the rows I though of carrying over as columns, but other attributes seem to be more difficult.

**Comment by hadley** [comment]
We don't know anything about the attributes, whether they should be the same length as the rows or the columns or something else. So to be safe, we ignore them. In general, you can expect to add arbitrary attributes to a data frame and expect them to be carried around.
