### ISSUE TITLE
Rethink count()

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#5117]
Something seems fundamentally wrong with the design of `count()`, `add_count()`, `tally()`, and `add_tally()`. The functions are fragile, and seem to have too much magic.

**Comment by hadley** [comment]
* Consider deprecating `tally()`, `add_count()`, and `add_tally()` (with informative messages showing you how to use `mutate()`/`summarise()` instead)

* Consider always returning ungrouped data from `count()`.

**Comment by seasmith** [comment]
I do not find any of these functions are more magical than `n()`.

`add_count()` allows one to think in the abstract by removing the tedious process of grouping, summarizing, and rejoining the summarized data to the original data.  Very useful for filtering un-summarized data sets by group counts.

**Comment by hadley** [comment]
@seasmith all it is is a `group_by()` + `mutate()`. And if you're filtering afterwards, you can usually skip straight to `df %>% group_by(g) %>% filter(n() > 5)`

**Comment by hadley** [comment]
With the simplifications in 1.0.1, I think this is probably fine now, and we can leave as is.

**Comment by jtr13** [comment]
I can't find a good explanation with examples of the difference between `count()` and `tally()`. Would you recommend not teaching them, and sticking with `group_by()` / `summarize()`? It's a little more work but probably a good idea for students to have to think about whether they want `n()` or `sum()` anyway.

**Comment by hadley** [comment]
@jtr13 `tally()` expects you to have grouped the data, and `count()` does the grouping for you. I think providing `tally()` was probably a mistake and I wouldn't teach it any more. As of dplyr 1.0.1 (coming out soon) `count()` and `tally()` will have the same behaviour for counting vs summing: neither will do it automatically.

**Comment by jtr13** [comment]
Got it, very helpful. I was going to suggest making `count()` the first function in the help file but I see that's already done in the dev version which is great since seeing `tally()` first made me think that was the go-to.  Overall the documentation is much clearer.
