### ISSUE TITLE
Allow summarise() to explicitly control grouping

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#5118]
The current grouping behaviour causes much confusion, and it's not correct now that summary expressions can return multiple values and rowwise is back to life. I now think the way to fix this is to add a `.groups` argument that could take any of the following values:

* `NULL` (default) = `"drop_last"` + message displaying the new grouping vars
* `"drop_last"`: current behaviour
* `"drop"`: returns ungrouped tibble
* `"keep"`: preserves existing grouping
* `"rowwise"`: one group per row

`summarise()` is the only verb that operates on "groups" (rather than rows or columns), so is the only function that needs this option.

cc @MilesMcBain

**Comment by MilesMcBain** [comment]
I like this.

I already treat these type of messages coming out of `dplyr` as warnings and I try to make them go away by adding args to the function call. E.g. the column spec printed by `read_csv`, and the join keys by the `left_join` when none are specified.

Can I suggest that the message refer to the `.groups` arg in some way? It'll make it clear that behaviour can (and probably should) be specified. Maybe:

```
Summarised tibble contains groups: group1, group2
.groups = "drop_last" (default) 
```

I do think that the main issue with sticky groups comes with summarise(). The classic mistake for me is grouping by n > 1 groups and forgetting the result will have n-1. 

In my own defensive hacks I've made `mutate` erase groups as well but it seems that in practice when I'm mutating groupwise I think I'm already doing something a little tricky and am treading more carefully.
