### ISSUE TITLE
between() support for character vectors

### ISSUE THREAD

**Issue by jayqi** [tidyverse/dplyr#5122]
Hello, rerequesting a feature that doesn't look like it was ever made available.

---

`between` currently (v0.8.5) only supports numeric inputs, and not character.

```
Error: Not compatible with requested type: [type=character; target=double].
```

I found this earlier closed issue #2995 which was closed in favor of an issue opened for `vctrs`.

I followed to the `vctrs` issue, which looks like it got moved to the [r-lib/funs](https://github.com/r-lib/funs/) repository: https://github.com/r-lib/funs/issues/26

Which I can see was closed with this commit implementing such a function with `vctrs`: https://github.com/r-lib/funs/commit/057146f5d90d9173530f2e5b169b6218c7af4be8

But as far as I can tell, [r-lib/funs](https://github.com/r-lib/funs/) is not actually a package that is available on CRAN for people to easily use. (There is not much documentation so I'm not exactly sure what that package is.)

So support for character inputs to `between` is still a missing feature for dplyr users. 

I understand that I can copy the small amount of code there is and define a custom function, but I believe there is still good reason to want dplyr to support it in the existing function with that name that works for numeric inputs.

Thank you!

**Comment by hadley** [comment]
We're tracking this issue at the funs repo (as you discovered). There's no need for another issue here.
