### ISSUE TITLE
bind_rows on tibble with extra class breaks

### ISSUE THREAD

**Issue by richardjtelford** [tidyverse/dplyr#5123]
I have a function that returns a tibble. I add an extra class to the tibble so I can use autoplot.myclass etc. This works fine. 

I need to use `bind_rows` to combine two such tibbles. This worked fine in ‘0.8.5’ but breaks in '0.8.99.9002'. I think the problem arises when there is a factor with different levels in each tibble.

Here is a minimal reprex

``` r
library("dplyr")
packageVersion("dplyr")
#> [1] '0.8.99.9002'
a <- tibble(a = factor("a"))
b <- tibble(a = factor("b"))
bind_rows(a, b) #works
#> # A tibble: 2 x 1
#>   a    
#> * <fct>
#> 1 a    
#> 2 b

class(a) <- c("myclass", class(a))
class(b) <- class(a)
bind_rows(a, b) #fails
#> Error: No common type for `..1` <myclass<a:factor<127a2>>> and `..2` <myclass<a:factor<ddf10>>>.
```

<sup>Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This is a vctrs error — to be safe, dplyr now requires that if you define a class, you need to define how to stitch the results back together again if you want to use it inside of `bind_rows()` and friends. 

It looks like the dev version of vctrs has a bug with your example, https://github.com/r-lib/vctrs/issues/1015. I'd recommend filing a separate issue asking what vctrs methods you need to define to get your class working again.
