### ISSUE TITLE
pipe operator fails when passing a dataframe to data.table::as.data.table

### ISSUE THREAD

**Issue by danoreper** [tidyverse/dplyr#5125]
Hi all, 
I'm running into an issue with dplyr pipes and data.table.
Specifically, the following code block fails:
``` 
x <- data.frame(x=1)
x %>% data.table::as.data.table

Error in .::data.table : unused argument (as.data.table)
```

However, this code block succeeds:
```
x <- data.frame(x=1)
library(data.table)  
x %>% as.data.table
```

I've found this behavior on both R-3.6.1 and R-3.6.3, with dplyr-0.8.3/0.8.4/0.8.5, and data.table-1.12.8.
Perhaps easiest to test: a brand new install of R-3.6.3 on mac reproduces the issue. 

Thanks,
Dan

**Comment by hadley** [comment]
This is unrelated to dplyr. You need to use `()` when also using `::`

``` r
library(magrittr)

x <- data.frame(x=1)
x %>% data.table::as.data.table()
#>    x
#> 1: 1
```

<sup>Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
