### ISSUE TITLE
Small improvements for erroring expressions

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#5127]
I think this:

```
Error: `filter()` argument `..1` errored.
ℹ `..1` is `!is.na(SWD)`.
✖ object 'SWD' not found
```

would be slightly clearer by indicating that `..1` is the user input in the `i` bullet:

```
Error: `filter()` argument `..1` errored.
ℹ Input `..1` is `!is.na(SWD)`.
✖ object 'SWD' not found
```

By the way for vctrs we discussed the idea of standardising on "input" rather than "argument", as the former sounds a little less technical. So the header could use input as well:

```
Error: `filter()` input `..1` errored.
ℹ Input `..1` is `!is.na(SWD)`.
✖ object 'SWD' not found
```

Finally, not a big deal but I think "errored" looks a bit strange and could be improved, though I'm not sure how. Maybe one of these:

```
Error: A problem occurred with `filter()` input `..1`.
Error: There is a problem with `filter()` input `..1`.
Error: Problem with `filter()` input `..1`.
```

Maybe the last one? It's very short yet user friendly.

```
Error: Problem with `filter()` input `..1`.
ℹ Input `..1` is `!is.na(SWD)`.
✖ object 'SWD' not found
```

**Comment by DavisVaughan** [comment]
I also could see the error and info bullets being switched. I think it matches how I mentally process the problem

1. There was a problem with X
2. What was the problem with X?
3. What was X?
