### ISSUE TITLE
Transporse with respect to a variable

### ISSUE THREAD

**Issue by Jagadeeshkb** [tidyverse/dplyr#5128]
Brief description of the problem
The data frame cant transposed with respect to few variables there should a parameter which keep the column fixed and transporse values and columns

**Comment by hadley** [comment]
I don't understand the question, sorry.

**Comment by romainfrancois** [comment]
I don't either, is `tidy::pivot_wider()` what you are looking for @Jagadeeshkb ?

**Comment by Jagadeeshkb** [comment]
> I don't either, is `tidyr::pivot_wider()` what you are looking for @Jagadeeshkb ?

yeah! Got it romainfrancois .  wider function what i am looking for.
