### ISSUE TITLE
export functions for writing external S3 methods

### ISSUE THREAD

**Issue by topepo** [tidyverse/dplyr#5129]
For objects that are tibbles with extra classes, we need to write new S3 methods for `dplyr` verbs for 1.0.0. I would base a new `filter()` method on `filter.data.frame()`: 

```r
filter.data.frame <- function(.data, ..., .preserve = FALSE) {
  if (missing(...)) {
    return(.data)
  }
  loc <- filter_rows(.data, ...)
  dplyr_row_slice(.data, loc, preserve = .preserve)
}
```

but `filter_rows()` is not exported. 

Can you export this and any other critical functions for the other verbs? Maybe including `ensure_group_vars()`, `arrange_rows()`, and anything else I might have missed?

**Comment by hadley** [comment]
You shouldn't need to implement a `filter` method. Instead you can implement a `dplyr_row_slice()` method.
