### ISSUE TITLE
Coalesce returns wrong units for "difftime" class object

### ISSUE THREAD

**Issue by mir-cat** [tidyverse/dplyr#5130]
I was using `dplyr::coalesce` with `difftime` objects, and I discovered that instead of finding the first non-missing value, it converts an NA `difftime` to a `difftime` with a value of 1 second.

In the example below, `coalesce(y, x)` should return `Time difference of 1 hours` not `Time difference of 1 secs`

```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:dplyr':
#> 
#>     intersect, setdiff, union
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

x <- difftime(as_datetime('2020-01-01 01:00:00'), as_date('2020-01-01'))

y <- difftime(as_date('2020-01-01'), NA)

x
#> Time difference of 1 hours

y
#> Time difference of NA secs

coalesce(x, y)
#> Time difference of 1 hours

coalesce(y, x)
#> Time difference of 1 secs
```

**Comment by mir-cat** [comment]
I tracked it to this chunk in the function `replace_with` used within `coalesce`

```r
  if (length(val) == 1L) {
    x[i] <- val
  }
```

When the `val` is assigned to `x[i]` it keeps the units of `x[i]`. Here, `val` is 1 hour and `x[i]` is NA seconds. When val is assigned to `x[i]` it takes the number, `1` and maintains the original units, seconds.

**Comment by hadley** [comment]
This is a special case of the issue that the [funs](https://github.com/r-lib/funs/issues) will eventually solve, namely that we need to use vctrs in all our vector functions.
