### ISSUE TITLE
Mutate Wrong Behavior 

### ISSUE THREAD

**Issue by ponnet** [tidyverse/dplyr#5133]
When assigning a column based on the flag - only the 1st value of the column is populated:

```
tabDat = tibble("Country 1" = c("C1", "c 2", "c 3"),
                                 "Region 1"  = c("R1", "R2", "R3"), 
                                 "Region 2"  = c("R4", "R5", "R6"))

flag = "case1"
#flag = "case2"

tabFilt1 =  tabDat %>%
  mutate(Region =  ifelse(flag == "case1", `Region 1`,`Region 2`)) %>% 
  select(c(`Country 1`,`Region`))
 
tabFilt1
```
The result is:

> A tibble: 3 x 2
>   `Country 1` Region
>   <chr>       <chr> 
> 1 C1          R1    
> 2 c 2         R1    
> 3 c 3         R1

Expected behavior:

```
ifelse(flag == "case1")
{
  tabFilt1 =  tabDat %>%
    mutate(Region =  `Region 1`) %>% 
    select(c(`Country 1`,`Region`))
}

tabFilt1
```

> A tibble: 3 x 2
>   `Country 1` Region
>   <chr>       <chr> 
> 1 C1          R1    
> 2 c 2         R2    
> 3 c 3         R3

**Comment by hadley** [comment]
This is unfortunately a problem with `ifelse()`:

``` r
df <- data.frame(
  "R1" = c("R1", "R2", "R3"),
  "R2" = c("R4", "R5", "R6")
)

flag <- "case1"
ifelse(flag == "case1", df$R1, df$R2)
#> [1] 1
```

<sup>Created on 2020-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
