### ISSUE TITLE
duplicated() does not function in mutate when preceded by arrange(on factor)

### ISSUE THREAD

**Issue by Auld-Greg** [tidyverse/dplyr#5136]
---

When piping factors into dplyr, mutate(dupes = duplicated(x)) will not function as I would expect if it follows arrange(). If the code is not piped, everything works as I would anticipate. 

```r
x <- factor(c('chandler@email','chandler@email','Danielle@email','Danielle@email','jw@email'))

test <- as.data.frame(matrix(nrow=5,ncol=1))
names(test)  <- 'factors'
test$factors <- x

test$order <- factor(c(2,3,4,1,5))
require(dplyr)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
test <- test %>% mutate(dupes1 = duplicated(test$factors)) %>%
                 arrange(desc(order)) %>%
                 mutate(dupes2 = duplicated(test$factors))
```

**Comment by hadley** [comment]
What exactly do you expect? And what do you see?

**Comment by Auld-Greg** [comment]
Thanks for the quick reply. 

test$dupes3 <- duplicated(test$factors)

I would expect dupes2 to look like dupes3. Perhaps this is intended behavior, but i found it confusing since the function works differently when it's not piped into mutate() after arrange(): 

![results](https://user-images.githubusercontent.com/8216425/79926476-04e75e80-840b-11ea-8b7e-6af27f1ca6f9.PNG)

**Comment by hadley** [comment]
I think maybe the thing you're missing is that `duplicated()` returns `TRUE` for the second and subsequence duplicate, so the order is very important.

**Comment by Auld-Greg** [comment]
Yes. That would be the intended behavior. It doesn't behave that way inside of mutate() after arrange(). It appears to randomly assign duplicates. If you don't pipe arrange() into mutate(), the function will behave correctly.

**Comment by hadley** [comment]
That's not the case. I think you need to look more closely at your code and output.

**Comment by Auld-Greg** [comment]
I would expect These two statements to work in the same way. They don't. 

# This works
test <- test %>%  arrange(desc(order))
test <- test %>%  mutate(dupes1 = duplicated(test$factors))

# This doesn't work
test <- test %>%  arrange(desc(order)) %>%
                  mutate(dupes2 = duplicated(test$factors))


![results2](https://user-images.githubusercontent.com/8216425/79984946-df446e80-8477-11ea-88aa-78171f0d76db.PNG)

**Comment by batpigandme** [comment]
The issue with the latter example is that you're only using the pipe halway there, since you're passing in `test$factors` instead of `factors`, and, since you're using the pipe, you haven't yet modified the order, since it hasn't executed (you're basically overriding it to send the _un_reordered factor):

**Your first example**
``` r
library(dplyr)

x <- factor(c('chandler@email','chandler@email','Danielle@email','Danielle@email','jw@email'))
test <- as.data.frame(matrix(nrow=5,ncol=1))
names(test)  <- 'factors'
test$factors <- x

test$order <- factor(c(2,3,4,1,5))

test <- test %>% arrange(desc(order))
test
#>          factors order
#> 1       jw@email     5
#> 2 Danielle@email     4
#> 3 chandler@email     3
#> 4 chandler@email     2
#> 5 Danielle@email     1
test <- test %>% mutate(dupes1 = duplicated(test$factors))
test
#>          factors order dupes1
#> 1       jw@email     5  FALSE
#> 2 Danielle@email     4  FALSE
#> 3 chandler@email     3  FALSE
#> 4 chandler@email     2   TRUE
#> 5 Danielle@email     1   TRUE
```
**Your second example, plus one without using `test$faactors` in the pipe**
``` r
library(dplyr)

x <- factor(c('chandler@email','chandler@email','Danielle@email','Danielle@email','jw@email'))

test <- as.data.frame(matrix(nrow=5,ncol=1))
names(test)  <- 'factors'
test$factors <- x

test$order <- factor(c(2,3,4,1,5))

test %>% arrange(desc(order)) %>%
  mutate(dupes2 = duplicated(test$factors))
#>          factors order dupes2
#> 1       jw@email     5  FALSE
#> 2 Danielle@email     4   TRUE
#> 3 chandler@email     3  FALSE
#> 4 chandler@email     2   TRUE
#> 5 Danielle@email     1  FALSE

test %>% arrange(desc(order)) %>%
  mutate(dupes2 = duplicated(factors))
#>          factors order dupes2
#> 1       jw@email     5  FALSE
#> 2 Danielle@email     4  FALSE
#> 3 chandler@email     3  FALSE
#> 4 chandler@email     2   TRUE
#> 5 Danielle@email     1   TRUE
```
<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by Auld-Greg** [comment]
Well. Perhaps I can learn to read.

Thanks,
