### ISSUE TITLE
group_modify fails with matrix columns

### ISSUE THREAD

**Issue by FlukeAndFeather** [tidyverse/dplyr#5138]
If a data frame has a matrix column then `group_modify()` encounters an error in `dplyr:::cbind_all()`. Without digging into the guts of it, my intuition is the matrix column gets flattened into a vector, which increases the number of rows and prevents column binding.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
foo <- tibble(x = c("a", "b"), y = matrix(1:4, ncol = 2))
foo %>% group_by(x) %>% group_modify(~ .x)
#> Error: Argument 1 must be length 1, not 2
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by FlukeAndFeather** [comment]
I can't reproduce this error in the development version of dplyr

**Comment by FlukeAndFeather** [comment]
Since it's working on the dev version, I wrote a test to catch regressions (see above). If someone on the tidyverse team thinks it's worthwhile I'll issue a pull request.

**Comment by hadley** [comment]
A test isn't worth it because handling different types of columns is now the job of vctrs.
