### ISSUE TITLE
Is `slice(df, numeric(0))` an undocumented feature or UB?

### ISSUE THREAD

**Issue by antoine-sachet** [tidyverse/dplyr#5141]
I sometimes use `slice(df, 0)` to obtain an empty data.frame with preserved column structure. I just realized that this behavior is not documented.

``` r
library(dplyr)

# Convenient
slice(mtcars, 0)
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 rows> (or 0-length row.names)

# And similar to base R behavior
mtcars[0,]
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2020-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The doc only mentions positive or negative indices:

> Integer row values. Provide either positive values to keep, or negative values to drop. The values provided must be either all positive or all negative. Indices beyond the number of rows in the input are silently ignored.

So if `0` is silently ignored, the call is equivalent to `slice(mtcars, numeric(0))`

Is `slice(mtcars, numeric(0))` effectively undefined behavior that one should not rely upon, or is it an undocumented feature of `slice`?

I looked at the tests for `slice` and none checks that slicing with an empty index vector gives an empty data.frame with preserved column structure.

The closest was:

```R
test_that("slice skips 0 (#3313)", {
  d <- tibble(x = 1:5, y = LETTERS[1:5], g = 1)
  expect_identical(slice(d, 0), slice(d, integer(0)))
  # Truncated
}
```

**Comment by hadley** [comment]
You can rely on it, but I'm not sure I'd recommend it over `df[0, , drop = FALSE]`. `slice()` can't work with databases, so it doesn't give you much additional genericity.

**Comment by romainfrancois** [comment]
Maybe `vctrs::vec_ptype()` ?
