### ISSUE TITLE
Feature Request: Allow recode.character to accept a single unnamed argument

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#5146]
I have a character string with an empty string that I'd like to replace using `recode()`.  `recode()` requires that all arguments are named, but a rational input would allow for a single, unnamed argument to replace empty strings.  Or, is there another way to replace empty strings with `recode()`?

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
recode(c("", "A"), A="D")
#> [1] ""  "D"
recode(c("", "A"), "C", A="D")
#> Error: Argument 2 must be named, not unnamed
```

<sup>Created on 2020-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
As I tried to implement this, I determined that it may be impossible while keeping `recode()` with `...` arguments instead of a named-list as an argument.  So, perhaps the correct solution would be to add a `.blank` argument that would replace `""`.

**Comment by hadley** [comment]
Recode is fundamentally weird because it's `old_name = new_name` unlike basically every other function. That means we're unlikely to add any new features to it, but we will eventually consider a more featureful replacement: https://github.com/r-lib/funs/issues/29
