### ISSUE TITLE
Continuing to get "Warning: Factor '??' contains implicit NA, consider using `forcats::fct_explicit_na`"

### ISSUE THREAD

**Issue by nzbart** [tidyverse/dplyr#5149]
I'm getting warnings about implicit NAs when working with a tibble with no rows. I've searched and found a previous issue that has a minimal example to reproduce the problem: #4460. That issue was apparently fixed in 0.8.4, but I am currently running 0.8.5 and am still able to reproduce the problem with the same steps.

There is a comment on that issue that says:
>If you believe you have found a related problem, please file a new issue (with reprex) and link to this issue. 

So, I've done just that.

``` r
library(dplyr, warn.conflicts = FALSE)
ig <- group_by(iris, Species)
ig[0,]
#> Warning: Factor `Species` contains implicit NA, consider using
#> `forcats::fct_explicit_na`

#> Warning: Factor `Species` contains implicit NA, consider using
#> `forcats::fct_explicit_na`
#> # A tibble: 0 x 5
#> # Groups:   Species [1]
#> # … with 5 variables: Sepal.Length <dbl>, Sepal.Width <dbl>,
#> #   Petal.Length <dbl>, Petal.Width <dbl>, Species <fct>
```

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This is already fixed in the dev version.
