### ISSUE TITLE
error loading 'dplyr' package

### ISSUE THREAD

**Issue by tonyvibe** [tidyverse/dplyr#5150]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
after installing package, i loaded it then got this error message in my console...
Error: package or namespace load failed for ‘dplyr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘pillar’
```r
# insert reprex here
```

**Comment by cderv** [comment]
> there is no package called ‘pillar’

I think you need to install the `pillar` 📦  that seems to be missing. 

For this kind of question, you could ask on https://community.rstudio.com, there is already several questions related to this kind of errors where you can get some hints of. Search for some keyword about your issue in the website search box. 

Hope it helps.

**Comment by tonyvibe** [comment]
thank you very much, i'll check it out
