### ISSUE TITLE
Could rowwise() become a generic?

### ISSUE THREAD

**Issue by tilltnet** [tidyverse/dplyr#5151]
`rowwise()` is currently not a generic (neither in dev nor cran version), thusly I can't define methods for it in my package. Can you please make it a generic?

 #2934 asks for the same, but at the time `rowwise()` was expected to be dropped, now with the 1.0.0 announcement it seems to be a permanent concept in the tidyverse.

**Comment by hadley** [comment]
It's not a generic, it's a constructor. What do you need it for?

**Comment by tilltnet** [comment]
I see that @romainfrancois  already committed a change (#5152), I'll still answer @hadley's question here, to provide an example.

In the egor package we have an object structure similar to the one tidygraph uses for network data. It's basically a list of data.frames and the user can switch between them with `activate()`. We have methods for all dplyr functions that operate on data frames. As `rowwise()` is very useful I'd like to be able to make it available for our users as well. I am currently exporting a `rowwise_egor()` function and that works, but it would be more intuitive to have a method.

**Comment by hadley** [comment]
Oh, sorry, I closed this prematurely. It does seem reasonable for `rowwise()` become a generic because it has the same interface as `group_by()`.
