### ISSUE TITLE
Use methods illicit no applicable function on POSIXct objects when used inside function and subsequent apply calls.

### ISSUE THREAD

**Issue by krispiepage** [tidyverse/dplyr#5155]
Whenever I try to create a function that manipulates a posixct class in a custom function and then use the function in say an mapply call it fails with the following error messages:

```R
Error in UseMethod("mutate_") : 
  no applicable method for 'mutate_' applied to an object of class "c('POSIXct', 'POSIXt')" 
 Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('POSIXct', 'POSIXt')"

monthly_plot <- function(data, monthone, monthtwo) {
  dplyr::mutate(data, date = as.Date(newdatetime)) %>%
  dplyr::filter(data, date >= monthone & date < monthtwo) %>%
  ggplot2::ggplot(aes(x = newdatetime, y = ork_demand_live)) + geom_line()
}

# A tibble: 6 x 7
  newdatetime         datetime ork_demand_live ork_demand_wint~ ork_generation_~
  <dttm>                 <dbl>           <dbl>            <dbl>            <dbl>
1 2020-04-23 13:01:00   1.59e9            14.3             35.7             1.17
2 2020-04-23 13:02:00   1.59e9            14.4             35.7             1.17
3 2020-04-23 13:03:00   1.59e9            14.2             35.7             1.14
4 2020-04-23 13:04:00   1.59e9            14.0             35.7             1.19
5 2020-04-23 13:05:00   1.59e9            14.0             35.7             1.18
6 2020-04-23 13:06:00   1.59e9            14.4             35.7             1.23

month_1 <- seq.POSIXt(as.POSIXct("2019-01-01", format = "%Y-%m-%d"), as.POSIXct("2020-04-01", format = "%Y-%m-%d"), by = "2 month")
month_2 <- seq.POSIXt(as.POSIXct("2019-02-01", format = "%Y-%m-%d"), as.POSIXct("2020-05-01", format = "%Y-%m-%d"), by = "2 month")

plots <- mapply(monthly_plot, data = ANM2019_2020, monthone = month_1, monthtwo = month_2)
```

The code works if you call it straight into the console, but within a function and a apply function it does not work.

It is confusing me :/

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by krispiepage** [comment]
``
newdatetime <- as.POSIXct(c("2020-04-23 13:01:00 BST", "2020-04-23 13:02:00 BST", "2020-04-23 13:03:00 BST",
                            "2020-04-23 13:04:00 BST", "2020-04-23 13:05:00 BST", "2020-04-23 13:06:00 BST"), 
                          format="%Y-%m-%d %H:%M:%S", tz = "Europe/London")

ork_demand_live <- c(14.29, 14.38, 14.25, 14.02, 14.03, 14.37)

ANM <- data.frame(newdatetime,ork_demand_live)


monthly_plot <- function(dataset, dateone, datetwo) {
  dplyr::filter(dataset, newdatetime >= dateone & newdatetime < datetwo) %>%
    ggplot2::ggplot(aes(x = newdatetime, y = ork_demand_live)) + geom_line()
}

date1 <- as.POSIXct("2020-04-23 13:01:00", tz = "Europe/London")

date2 <- as.POSIXct("2020-04-23 13:05:00", tz = "Europe/London")

plots <- mapply(monthly_plot, data = ANM, dateone = date1, datetwo = date2)
``

**Comment by hadley** [comment]
I'm not sure what you're expecting here, but it's probably because `mapply()` is iterating in a way that you don't expect. 

``` r
library(dplyr, warn.conflicts = FALSE)

newdatetime <- as.POSIXct(c("2020-04-23 13:01:00 BST", "2020-04-23 13:02:00 BST", "2020-04-23 13:03:00 BST",
                            "2020-04-23 13:04:00 BST", "2020-04-23 13:05:00 BST", "2020-04-23 13:06:00 BST"), 
                          format="%Y-%m-%d %H:%M:%S", tz = "Europe/London")

ork_demand_live <- c(14.29, 14.38, 14.25, 14.02, 14.03, 14.37)

ANM <- data.frame(newdatetime,ork_demand_live)
date1 <- as.POSIXct("2020-04-23 13:01:00", tz = "Europe/London")
date2 <- as.POSIXct("2020-04-23 13:05:00", tz = "Europe/London")

monthly_plot <- function(dataset, dateone, datetwo) {
  str(dataset)
  cat("\n")
}

plots <- mapply(monthly_plot, dataset = ANM, dateone = date1, datetwo = date2)
#>  POSIXct[1:6], format: "2020-04-23 13:01:00" "2020-04-23 13:02:00" "2020-04-23 13:03:00" ...
#> 
#>  num [1:6] 14.3 14.4 14.2 14 14 ...
```

<sup>Created on 2020-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
