### ISSUE TITLE
slice_max() inconsistency with prop argument

### ISSUE THREAD

**Issue by dkahle** [tidyverse/dplyr#5164]
Love the systematization of the `slice()` variants, well done! 

Check this out:

``` r
tb <- tibble(x = sample(5))


tb %>% slice_min(x, prop = .40)
#> # A tibble: 2 x 1
#>       x
#>   <int>
#> 1     1
#> 2     2

tb %>% slice_max(x, prop = .40)
#> # A tibble: 0 x 1
#> # … with 1 variable: x <int>
```
I assume that's unintentional, since when you use the `n` parameter, you get the expected:
```r
tb %>% slice_min(x, n = 2)
#> # A tibble: 2 x 1
#>       x
#>   <int>
#> 1     1
#> 2     2

tb %>% slice_max(x, n = 2)
#> # A tibble: 2 x 1
#>       x
#>   <int>
#> 1     5
#> 2     4
```
And when you use the older `top_frac()` you get the same expected:
```r
tb %>% top_frac(.40, x)
#> # A tibble: 2 x 1
#>       x
#>   <int>
#> 1     5
#> 2     4
```
I haven't had time to look into the internals of `slice_max.data.frame()`, but thought I'd point it out since I know y'all are looking to get it out the door soon.

**Comment by hadley** [comment]
Thanks for spotting this!
