### ISSUE TITLE
Strange issue when Spectrum and dplyr are loaded together

### ISSUE THREAD

**Issue by sjmgarnier** [tidyverse/dplyr#5168]
Here is a strange problem that I ran into today. In RStudio with R 4.0 on both Mac and Linux, If I load the following packages together: 

```r
library(dplyr)
library(Spectrum)
```

and then try to run any function starting with "wrap", e.g.:

```r
wrap_test <- function() {
  "test"
}

wrap_test()
```

after using the RStudio autocomplete feature (tab) to complete the function's name, the R session freezes and starts using 100% of my CPU. I could not figure out what the issue was but I could reproduce it on my Mac and my Linux machines. I'm guessing some weird interaction between Spectrum and dplyr. I'll cross-post this on the Spectrum Github page.

**Comment by hadley** [comment]
I can't reproduce this sorry 😞

**Comment by sjmgarnier** [comment]
@hadley Yeah, I figured that was a strange one. If I can find out what triggers it, I'll post more info here. Thanks for looking into it.

**Comment by agranado** [comment]
I do get freezes and errors when dplyr and Spectrum are loaded together. The error always comes when calling a dplyr command. However, is very hard to predict. It almost seems random. The session freezes for a several seconds and comes back with a "Error: C stack usage  7970244 is too close to the limit" or something like that.  I tried a new clean installation of R on a new Windows machine and get the same error!
