### ISSUE TITLE
Feature request: allow tidyselect in coalesce()

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#5170]
It would be very useful if `coalesce()` could take tidyselect specifications.  I sometimes run into situations where the number of columns I need to coalesce is variable but partially share a name (ie a result from pivot_wider), so I'd like to use `starts_with`, etc.

**Comment by hadley** [comment]
Duplicate of #5110

**Comment by LukasWallrich** [comment]
This feature would be very helpful - just raising this again because #5110 does not seem to exist, either open or closed ...

**Comment by eutwt** [comment]
Related to https://github.com/tidyverse/funs/issues/54. That issue gives some workarounds (`tidyselect::vars_select` and `do.call` + `across`)
