### ISSUE TITLE
relocate .after doesn't play nicely with subclasses

### ISSUE THREAD

**Issue by hughjonesd** [tidyverse/dplyr#5172]
Attached is a minimal package that shows the problem. Load it, then run

```r
registerS3method("relocate", "foo", packagefileprob:::relocate.foo,
      envir = asNamespace("dplyr")) # normally the package would do this on onLoad

tmp <- structure(data.frame(a=1,b=2), class = c("foo", "data.frame"))
relocate(tmp, b, a) # fine
relocate(tmp, a, .after = b) # dies
```

My output:

```
> relocate(tmp, b, a) # fine
got to relocate.foo
  b a
1 2 1
> relocate(tmp, a, .after = b) # dies
got to relocate.foo
Error: object 'b' not found
```

This seems to come from somewhere deep within `tidyselect::eval_sym`, but don't ask me to debug this wizardry.

[packagefileprob_0.1.0.tar.gz](https://github.com/tidyverse/dplyr/files/4560961/packagefileprob_0.1.0.tar.gz)

**Comment by hadley** [comment]
Could you please expose the guts of the class in a way that's easier to see? `relocate()` calls `[`, so it's likely that the problem lies with `[.foo`.

**Comment by hughjonesd** [comment]
`foo` is an empty subclass. The only code in this package is:

```
relocate.foo <- function (.data, ..., .before = NULL, .after = NULL) {
  cat("got to relocate.foo\n")
  NextMethod()
}
```

**Comment by hadley** [comment]
`.before` and `.after` use tidy evaluation, so don't work with `NextMethod()`. We haven't figured out a great solution for this yet, but we're aware of it and thinking about it.
