### ISSUE TITLE
Summarise Quantile Potential Bug

### ISSUE THREAD

**Issue by melissagwolf** [tidyverse/dplyr#5176]
The quantile function under summarise is no longer working.  I get the following error message:

Error: Column `test` must be length 1 (a summary value), not 2

---

```r
mat <- matrix(rnorm(100*4,mean=0,sd=1), 100, 4) 

colnames(mat) <- c("X1","X2","X3","X4")

mat %>% 
  as.data.frame() %>% 
  summarise(test=quantile(X1,c(.25,.5)),
            q=c(.25,.5))

mat %>% 
  as.data.frame() %>% 
  summarise(test=quantile(X1,c(.25,.5)))
```
---

I expect the 25th and 50th percentile for X1.

**Comment by hadley** [comment]
You need the development version of dplyr for this to work.

**Comment by melissagwolf** [comment]
Hi Hadley,

I can't install the developer version:

---

These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                   
2: CRAN packages only                    
3: None                                  
4: rlang (0.4.5 -> ea3d09a1c...) [GitHub]
5: vctrs (0.2.4 -> 29e1101a0...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
1
rlang (0.4.5 -> ea3d09a1c...) [GitHub]
vctrs (0.2.4 -> 29e1101a0...) [GitHub]

Downloading GitHub repo r-lib/rlang@master
r-lib-rlang-ea3d09a/revdep: Can't create '\\\\?\\C:\\Users\\missg\\AppData\\Local\\Temp\\RtmpkT7O4k\\remotes5f9c54a7e17\\r-lib-rlang-ea3d09a\\revdep'
tar.exe: Error exit delayed from previous errors.

Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\missg\OneDrive\Documents\R\win-library\4.0\00LOCK-rlang\rlang\libs\x64\rlang.dll to C:\Users\missg\OneDrive\Documents\R\win-library\4.0\rlang\libs\x64\rlang.dll: Permission denied
Execution halted
Error: Failed to install 'dplyr' from GitHub:
  Failed to install 'rlang' from GitHub:
  (converted from warning) installation of package ‘C:/Users/missg/AppData/Local/Temp/RtmpkT7O4k/file5f9c655b4e06/rlang_0.4.6.tar.gz’ had non-zero exit status
In addition: Warning message:
In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\missg\AppData\Local\Temp\RtmpkT7O4k\file5f9c3bb87ab8.tar.gz" -C "C:/Users/missg/AppData/Local/Temp/RtmpkT7O4k/remotes5f9c18613393"’ returned error code 1
---

Google isn't telling me much about how to resolve this.  Do you have any ideas?  My current version of R is 4.0 and I am on a PC.

Melissa

**Comment by melissagwolf** [comment]
Hi again,

I uninstalled and reinstalled many things from various google searches. I am not sure what I did or why it worked, but I was finally able to successfully install the dev version of dplyr and the code works now.  Thank you!!
