### ISSUE TITLE
Investigate rows_merge()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#5179]
https://blog.jooq.org/2020/04/10/the-many-flavours-of-the-arcane-sql-merge-statement/

**Comment by romainfrancois** [comment]
Is this now done in the `rows_*()` functions ?

**Comment by krlmlr** [comment]
I think this was about implementing a `rows_merge()` generic and method for dplyr that mimics the very powerful `MERGE` SQL statement. It's explained in the blog post.

The `WHEN MATCHED`and `WHEN NOT MATCHED` parts might be handled by functions that receive data frame subsets as input. Could be one way to solve conditional `mutate()` (#4050). Difficult to port to the database though.

**Comment by hadley** [comment]
Given that we've made no real progress on this in two years, I'm going to close this issue. I think we'll also need some time to fully understand the remaining gaps once `mutate_when()` makes it into main.
