### ISSUE TITLE
`is_grouped_df()` does not return correct grouping status after calling `rowwise()`

### ISSUE THREAD

**Issue by jhuntergit** [tidyverse/dplyr#5192]
I'm using the dev version of dplyr `0.8.99.9002` and reading the help page for `?rowwise`:

> A row-wise tibble maintains its row-wise status until explicitly removed by group_by(), ungroup(), or as_tibble().

That would lead me to believe that the output of `mtcars %>% rowwise() %>% is_grouped_df()` would be `TRUE`, because I did not call any of the functions listed above after calling `rowwise()` in this pipe:

```R
mtcars %>% rowwise() %>% is_grouped_df()
#> [1] FALSE
```

Could this be a bug, or perhaps something was overlooked with either the `rowwise()` or `is_grouped_df()` functions?

**Comment by hadley** [comment]
It's not a grouped data frame, it's a rowwise data frame (which is grouped by row, but not a `grouped_df`). You're not the first person that this has confused, so I'll think about how to improve the docs.

**Comment by romainfrancois** [comment]
Should there be a `is_rowwise_df()` ?

**Comment by jhuntergit** [comment]
For an end user like me (non-programmer, non-CS person) the function I'd like to see would be called `is_grouped` without the `_df` and would tell me if my data set (whether data frame, tibble, etc.) is grouped, or not. And the definition of "grouped" would include "rowwised".

There's likely many implications I don't understand about this suggestion, just wanted to throw it out there.

**Comment by hadley** [comment]
What precisely are you trying to establish? In some sense, there's no "ungroup"ed data frames in dplyr, there are just data frames where all the rows are in one group.

**Comment by jhuntergit** [comment]
_In the not too distant past..._

A lot of pipes that I created required grouping at some point, and would resemble something like:

```R
df %>% 
  group_by(x) %>%
  "operations that require grouped data sets" %>% 
  ungroup() %>% 
  "operations that require UNgrouped data sets"
```

I'd often forget to include the `ungroup()` step above, and would always get some type of error or weird result, because of this oversight. Eventually, I learned of the `is_grouped_df()` function, and my problems went away.

The catch, and motivation for the post, is that I now need to use the `rowwise()` function, due to the introduction of a new `across()` function in dplyr you may have heard of. I speculate that `rowwise()` is basically `df %>% mutate(row = row_number()) %>% group_by(row)`. Anyways, a lot of my pipes in the future will look like:

```R
df %>% 
  rowwise() %>%
  "operations utilizing across()" %>% 
  ungroup() %>% 
  "operations that require UNgrouped data sets"
```

My fear is that I may forget to include `ungroup()` above and have no way to know if my data set is really grouped or not because `df %>% rowwise() %>% is_grouped_df` will return FALSE.

I refer to my data as "data sets" because I just don't understand all the different classes such as "grouped_df", "tbl_df", "tbl", "data.frame", etc. When I run `is_grouped_df()` I'm thinking "_Is the data set in front of me grouped or not_". I'm not thinking "_Is this a data frame, tibble, etc. and is it grouped or not. If it is a tibble does that mean that all grouping has coercively been removed_". Clearly understanding these type of things would be beneficial but I'm just not there yet. Hope that helps.

**Comment by hadley** [comment]
Yeah, I'd say you've accidentally picked up a very mild bad habit of using `is_grouped_df()`, which really has a specific programming intent. I think you'd be better off testing for something like `n_groups(x) > 1).
