### ISSUE TITLE
Summarise_at/_if summarize_at/if >1 times for multiple column sets

### ISSUE THREAD

**Issue by SimonDedman** [tidyverse/dplyr#5208]
Issue described (with solutions) [here](https://stackoverflow.com/questions/48944369/using-dplyr-summarize-with-different-operations-for-multiple-columns) but I feel like this would be an excellent feature, contingent on it not being too nightmarish to program.

Currently summarise_at/summarise_if/summarize_at/summarize_if can only be used once, on a single selection of column variables. It's easy to conceive cases when one might want to, e.g. group by date, and summarise mean values for all numeric columns, but the first value for character columns.
Conceptually this would also open the door for selecting the same columns multiple times for different operations e.g. min mean max on the same set. Though this may already be handled elsewhere, this would be a neat way of simplifying feature extraction using dplyr.

```r
iris %>%
group_by(Species) %>%
summarise_at(matches(".Length"), mean, na.rm = T,
             matches("Sepal"), min, na.rm = T)
```

**Comment by hadley** [comment]
See upcoming `across()` in dplyr 1.0.0: https://www.tidyverse.org/blog/2020/04/dplyr-1-0-0-colwise/

**Comment by SimonDedman** [comment]
Happy days - cheers!
