### ISSUE TITLE
Emphasise grouping in print method 

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#5209]
using colour

**Comment by romainfrancois** [comment]
This is really burried in `tibble::format.trunc_mat` https://github.com/tidyverse/tibble/blob/3892a7f8e75595824ff26089d02c7f868526e16c/R/print.R#L186

```r
format.trunc_mat <- function(x, width = NULL, ...) {
  if (is.null(width)) {
    width <- x$width
  }

  width <- tibble_width(width)

  named_header <- format_header(x)
  if (all(names2(named_header) == "")) {
    header <- named_header
  } else {
    header <- paste0(
      justify(
        paste0(names2(named_header), ":"),
        right = FALSE, space = NBSP
      ),
      # We add a space after the NBSP inserted by justify()
      # so that wrapping occurs at the right location for very narrow outputs
      " ",
      named_header
    )
  }

  comment <- format_comment(header, width = width)
  squeezed <- pillar::squeeze(x$mcf, width = width)
  mcf <- format_body(squeezed)

  # Splitting lines is important, otherwise subtle style may be lost
  # if column names contain spaces.
  footer <- pre_dots(format_footer(x, squeezed))
  footer_comment <- split_lines(format_comment(footer, width = width))

  c(style_subtle(comment), mcf, style_subtle(footer_comment))
}
```

We *could* define a `format.trunc_mat_grouped_df` but that would duplicate most of this so that we can call e.g. `pillar::style_bold()` instead of `pillar::style_subtle()`. 

Othewise, perhaps we could squeeze in some information in `tbl_sum.grouped_df()` 

```
#' @export
tbl_sum.grouped_df <- function(x) {
  c(
    NextMethod(),
    c("Groups" = group_sum(x))
  )
}
```

ping @krlmlr

**Comment by hadley** [comment]
BTW I realised we probably can't use colour in `tbl_sum()` because now it's called from the IDE: https://github.com/rstudio/rstudio/pull/6688

**Comment by romainfrancois** [comment]
Perhaps `tibble` could pick up the "Groups" element of what it returns and apply a different style ? Or maybe we add some attribute to what `group_sum()` returns ?

**Comment by hadley** [comment]
Now that we're printing during the from the only non-obvious function that changes grouping (i.e. `summarise()`), I think we can close this issue.
