### ISSUE TITLE
trying to replace filter_if with across

### ISSUE THREAD

**Issue by ericemc3** [tidyverse/dplyr#5210]
---
I want to filter a tibble, eliminating rows whose numeric columns are all NA.
I am just looking for a replacement to filter_if, using across.

```r
# insert reprex here
t <-  tribble(
  ~id, ~x1, ~x2,
  "a", NA, NA,
  "b",  1,  1,
  "c", NA,  1,
)

t %>% filter_if( is.numeric, any_vars( !is.na(.) ) )  #works
# A tibble: 2 x 3
#  id       x1    x2
#  <chr> <dbl> <dbl>
#1 b         1     1
#2 c        NA     1

t %>% filter( across(is.numeric, any_vars( !is.na(.) )) )  # does not filter
# A tibble: 3 x 3
#  id       x1    x2
#  <chr> <dbl> <dbl>
#1 a        NA    NA
#2 b         1     1
#3 c        NA     1
```

**Comment by hadley** [comment]
See the details in https://dplyr.tidyverse.org/dev/articles/colwise.html#how-do-you-convert-existing-code-

**Comment by ericemc3** [comment]
Thank you for your prompt reply!

If i understand well, i should replace
```r
t %>% filter_if( is.numeric, any_vars( !is.na(.) ) ) 
```
with
```r
rowAny <- function(x) rowSums(x) > 0
t %>% filter( rowAny(across(is.numeric, ~ !is.na(.x))) )
```

I am sorry, but i will stick to the first one, which is much more elegant and legible...

**Comment by hadley** [comment]
Not sure why you're apologising, you're free to write whatever code you prefer.

**Comment by ericemc3** [comment]
As a user and teacher, I have found that the _if variants (mutate_if, filter_if) are intuitive, easy to learn and teach.  Although I welcome "across" and am really happy that it will solve some problems that were difficult to address before, in many cases it just adds a new word and two parentheses that do not help with readability.

So I'd be really _sorry_ if you had to actually deprecate filter_if (and others), without any "so simple" replacement. It's precisely because of your _supersede_ announcement_ about these that I, and many others i guess, are trying to rewrite their code with across... 

https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-is-coming-soon/ : 

> There’s no rush, but we suggest that you learn about their replacements and phase out your use of the superseded functions over the next year or two

Needless to say, I'm a fan of tidyverse, it has saved me a lot of time. The elegance of the code is also a major criteria for me.
