### ISSUE TITLE
rror: package or namespace load failed for ‘dplyr’ 

### ISSUE THREAD

**Issue by elcega** [tidyverse/dplyr#5214]
I have been using dplyr, but suddenly it stopped working, I re-started R and when loading
library(dplyr) I get the following error:

> Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
>  namespace ‘rlang’ 0.4.0 is already loaded, but >= 0.4.3 is required

How could I fix this?

**Comment by elcega** [comment]
That is it,

I removed and reinstalled rlang

> remove.packages("rlang")
> install.packages("rlang")
> library(rlang)
> library(dplyr)

**Comment by danihyder** [comment]
Thank you <3 you are a life-saver 👍

**Comment by Karlheinzniebuhr** [comment]
Having the same issue. The proposed solution doesn't solve my problem
```
Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.8 is already loaded, but >= 0.4.9 is required
```

**Comment by Vinit-Sehgal** [comment]
Figured just a slight modification to the first answer worked best for me:
restart R, then:
remove.packages("rlang")
remove.packages("dplyr")

install.packages("rlang")
install.packages("dplyr")

library(rlang)
library(dplyr)

**Comment by yyang97** [comment]
> Figured just a slight modification to the first answer worked best for me:
> restart R, then:
> remove.packages("rlang")
> remove.packages("dplyr")
> 
> install.packages("rlang")
> install.packages("dplyr")
> 
> library(rlang)
> library(dplyr)

Thanks, my life saver

**Comment by yyang97** [comment]
> Having the same issue. The proposed solution doesn't solve my problem
> 
> ```
> Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
>  namespace ‘rlang’ 0.4.8 is already loaded, but >= 0.4.9 is required
> ```

Did you try to remove and check that it is actually removed?

**Comment by sekhar183** [comment]
best solution is to install libraries it is asking like:
* Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.8 is already loaded, but >= 0.4.9 is required

so you install.packages('rlang')

*after executing above step it might show another error similar to above but asking for another library:
so you install that library.

**Comment by UsmanJah** [comment]
thank you guys its works well for me. it was very hepfull

**Comment by saicoangel1** [comment]
> library(rlang)
Warning message:
package ‘rlang’ was built under R version 4.0.5 
> library(dplyr)
The package `vctrs` (>= 0.3.8) is required as of rlang 1.0.0.
! Would you like to update it now?
  You will likely need to restart R if you update now.
i Not updating now is completely safe and will only cause import warnings.

1: Yes
2: No

Selection:

**Comment by meisdee** [comment]
> library(dplyr)
Error: package or namespace load failed for ‘dplyr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘vctrs’

This is still the issue for me, i tried all the solutions posted above, any help?

**Comment by DavisVaughan** [comment]
I am locking this issue as most comments are unrelated to the original issue and are more appropriate as questions on https://community.rstudio.com/. If you feel there is an issue with dplyr, feel free to open a new issue, as that is easier for us to track.
