### ISSUE TITLE
select_if => select

### ISSUE THREAD

**Issue by ericemc3** [tidyverse/dplyr#5216]
---

Hi,
still following your suggestions (move away from _if, _at functions), i am testing new _select_ implementation againts _select_if_

```r
t <-  tribble(
  ~id, ~x1, ~x2,
  "a", NA, NA,
  "b",  1,  1,
  "c", NA,  1,
)

isSignificantNAColumn = function( x, threshold=0.5, nrows ) {
  ( sum( is.na(x) ) + sum( is.null(x), na.rm=T ) + sum( x=="", na.rm=T ) ) / nrows < threshold
} 

tf <- t %>% select_if( ~isSignificantNAColumn( .x, 0.5, nrow(t) ) ) #works

tf <- t %>% select( ~isSignificantNAColumn( .x, 0.5, nrow(t) ) )  #error
```

**Comment by hadley** [comment]
You have, at a minimum, several years to update your code. So there’s no rush and because they’re not really issues with the package, you’d be better off asking these questions in RStudio community.

**Comment by hadley** [comment]
Also `is.null()` only ever returns a single true or false, and a null can’t be a column of a data frame. 

You could also use `mean(is.na(x))` to compute the proportion of missing values in a column.

**Comment by ericemc3** [comment]
Thanks, i'll use that!

**Comment by ericemc3** [comment]
I know that dplyr 1.0.0 is a huge challenge. And i am respectful for all the hard work.
So let's articulate a simplier example:
```r
t <-  tribble(
  ~id, ~x1, ~x2,
  "a", NA, NA,
  "b",  1,  1,
  "c", NA,  1,
)

isSignificantNAColumn = function( x, threshold=0.5 ) {
  mean( is.na(x) ) < threshold
} 

tf <- t %>% select_if( ~isSignificantNAColumn( .x, 0.25) ) #works

tf <- t %>% select( isSignificantNAColumn )  #works with the default 0.5

tf <- t %>% select( ~isSignificantNAColumn( .x, 0.25 ) )  
#Error : Must subset columns with a valid subscript vector.
```
Maybe i am missing something obvious here with my last line not working.

My concern is not about beeing free to use `select_if` (for _several years_ only) or the new extended `select`. It is about (i am working in a software company and there is a strong debate between R and Python):
- writing production code that lasts, and then i won't use `select_if` if it will be eventually dropped, 
- as a teacher also (delivering a Tidyverse course next week), explaining things in the simpliest way. It is hard to say : here is `select` and use it because it has real magic and flexibility in it (especially with dplyr 1.0),  but when the magic stops working, learn and try the scoped variants as `select_if`, but i can't tell you how long `select_if` will be still supported.

Or maybe it is just a matter of patience and this will be probably adressed in dplyr 1.0.x

**Comment by hadley** [comment]
I think you are reading too much into what "superseded" means — we are committed to keeping these functions around for a long time. The _soonest_ we would remove them is in several years, but if we look around and see that people are still using them, we would keep them around for longer. You absolutely do not need to commit to learning replacements for them right now, partly because, as you have discovered, the replacements are not fully mature yet.

**Comment by ericemc3** [comment]
Thank you for taking the time to reply.
I understand and i agree.
