### ISSUE TITLE
Export `context_env`?

### ISSUE THREAD

**Issue by danzafar** [tidyverse/dplyr#5217]
Hello, I'd like to use `context_env` in my package. It's a workaround to get `n()` working for a yet unsupported data type. Since `n()` does not have arguments and thus cannot be an S3 class this is really the only way I've found to get the functionality. 

Here is my workaround where I'm using this:
```
.onLoad <- function(...) {
  rlang::env_bind_lazy(dplyr:::context_env, ..group_size = get_count())
}
```

Have worked pretty hard to avoid a namespace conflict here, really hoping I can use this workaround on CRAN. Any thoughts?

Dan

**Comment by hadley** [comment]
It would be a bad idea to expose dplyr internals in this way. What precisely are you trying to do? There’s almost certainly a better approach.

**Comment by danzafar** [comment]
Thanks Hadley :)

I'm trying to do something like this:

```
as_my_s3_class(iris) %>% 
  group_by(Species) %>%
  mutate(n = n())
```

I wrote methods for all of the `dplyr` S3 generics working, but `n()` is the sticker. Going into more depth, here is the `n()` function:

```
> dplyr::n
function () 
{
    from_context("..group_size")
}
<bytecode: 0x7fdd950419d8>
<environment: namespace:dplyr>
```

```
> dplyr:::from_context
function (what) 
{
    context_env[[what]] %||% abort(glue("{expr} should only be called in a data context", 
        expr = deparse(sys.call(-1))))
}
<bytecode: 0x7fdd8eff4d70>
<environment: namespace:dplyr>
```

The problem is that I can't really set anything in `context_env` because it is in the `dplyr` package namespace. 

I believe the way `tibble` objects do this is they set the `context_env` for each group in in a data frame eagerly, though I don't have a deep understanding of the back-and-forth from C++. In most cases `n()` probably isn't even called because it goes directly to C++ and just goes back if there was something wrong. 

Would be great if there is a better way. Any pointers very much appreciated!

**Comment by hadley** [comment]
What does `group_by()` return for your custom S3 class and how does it behave differently from a `grouped_df()`?

**Comment by danzafar** [comment]
It returns the same object and class but with a new attribute `groups` specifying the groups being used. Then my `mutate`/`filter`/`summarize` checks to see if there are groups and if so applies a window function or equivalent to deal with that case. Works well. 

If we can get it working even without the grouping I should be able to take care of the rest. At this point I don't think there is any way to interface with `n()` other than through `context_env`. I suppose I could hack it by expression parsing, but it would be messy.

**Comment by hadley** [comment]
But how do you do perform the mutate? You're doing it yourself, and not calling dplyr?

**Comment by danzafar** [comment]
I just wrote an S3 method for my class. A simplified version looks like this:

```
mutate.spark_tbl <- function(.data, ...) {
  dots <- rlang::enquos(...)

  sdf <- attr(.data, "jc")

  for (i in seq_along(dots)) {
    name <- names(dots)[[i]]
    dot <- dots[[i]]

    # grab java objects that reference columns as a named list to act as a data mask
    df_cols <- get_jc_cols(sdf) 

    # this is where n() gets evaluated
    eval <- rlang::eval_tidy(dot, df_cols) 

   # <excluded code here>

    sdf <- call_method(sdf, "withColumn", name, jcol)
  }

  new_spark_tbl(sdf, groups = attr(.data, "groups"))
}
```

As you can see it more or less follows the pattern you described in your book, thanks for that btw :D

**Comment by danzafar** [comment]
And then right now I have this working by running this code:

```
get_count <- function() {
  if (!exists(".sparkRCon", SparkR:::.sparkREnv)) return(NULL)
  jc <- call_static("org.apache.spark.sql.functions", "count", "*")
  new("Column", jc)
}

.onLoad <- function(...) {
  rlang::env_bind_lazy(dplyr:::context_env, ..group_size = get_count())
}
```

So what happens is in the `eval_tidy` it sees `n()` which has it look for `..group_size` in `dplyr:::context_env`. Then I have that lazily bound to a count query which will get me the count. In the data is grouped then I just wrap that expression in a window. Easy peasy.

**Comment by hadley** [comment]
Please don’t do that. You’re using dplyr internals which we have no obligation to keep stable. Instead, bind your own `n()` in the environment where you evaluate the groups.

**Comment by danzafar** [comment]
![image](https://user-images.githubusercontent.com/57200935/81514244-35743700-92eb-11ea-8bb8-ae275d634c73.png)

Thank you so much Hadley that worked. Can't believe I didn't think of it. Very grateful for you and your help here.
