### ISSUE TITLE
`slice()` should validate inputs with `vec_as_location()`

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#5242]
And call `vec_as_subscript()` first to cause an error with logical inputs.

**Comment by romainfrancois** [comment]
This would be stricter than the current behavior that is somewhat forgiving: 

``` r
library(dplyr, warn.conflicts = FALSE)

data.frame(x = 1:4) %>% slice(3:10)
#>   x
#> 1 3
#> 2 4

vctrs::vec_as_location(3:10, 4)
#> Error: Can't subset elements that don't exist.
#> x Locations 5, 6, 7, 8, 9, etc. don't exist.
#> ℹ There are only 4 elements.
```

<sup>Created on 2020-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Can you look at `vec_as_subscript()` to standardise the base type and then `num_as_location()` which has more parameters than `vec_as_location()` please? I think we might need to add `"ignore"` to the possible options for `oob`.

**Comment by hadley** [comment]
@lionel- is there some reason you think we need to change the existing semantics?

**Comment by lionel-** [comment]
This is not about changing the semantics, this is about using vctrs errors with exactly the same semantics.

**Comment by lionel-** [comment]
Or are you asking if we should change `slice()` to improve its semantics?

**Comment by hadley** [comment]
I'm trying to understand the motivation for this change.

**Comment by lionel-** [comment]
The motivation is to use vctrs for validating subscript vectors in all tidyverse packages, to get uniform error messages.

**Comment by lionel-** [comment]
Another one: `dplyr_row_slice()`, before dispatch.

**Comment by romainfrancois** [comment]
IIRC the oob forgiveness is for things like `slice(df, 1:5)` to get the first 5 rows in each group of `df` and be fine in groups where there are fewer rows.

**Comment by hadley** [comment]
This would change the semantics, so we'll need to carefully consider it.

**Comment by lionel-** [comment]
Sorry I haven't been clear, I didn't mean to suggest we should change the semantics. But we should add an option in vctrs to handle the particular OOB semantics of `slice()`. This way we have vctrs errors without breaking changes (at least no breaking changes in the intended semantics).

Maybe it's still a good idea to make `slice()` more strict, but then it will be less useful interactively to quickly check out the `n` first observations for groups of varying sizes.
