### ISSUE TITLE
Cartesian Products and cross_join() for unequal joins

### ISSUE THREAD

**Issue by cochetti** [tidyverse/dplyr#5246]
Currently it appears that a cartesian product can only be created with a full_join using a dummy variable for the by clause. There are times that I need to just cross-join...  Just simple deck of cards type processing: 14 numbers ( A, K, Q,, J, 10 - 2) x Suits ( C, D, H, S ) for A Clubs, K Clubs .... 2 Spades.

It seems that `joins` don't current support unequal relationships such as greater than or between. I would like to be able to cross-join and then apply a filter to do relationships such as a dataset with intervals 0 - 30, 31 - 60, and 61 - 90 days and show me every event with event_day < cut point or between 31 - 60 for example.  

I use this type of logic a lot in medical and insurance claims data where I need to look queries like "all events which occurred prior to 30-, 60-, 90- days and then summarize say sum of all costs at each point within a department".

As SQL supports these in the left_ , right_ and inner_joins, I would naturally do something like: 

```
SELECT cutpoint, sum( cost_var )
FROM ( SELECT event_id, cost_var, cutpoint
            FROM tblCuts 
             LEFT JOIN tblEvents by event_day <= day)
GROUP BY cutpoint; 
```

Here's a dataset for a reprex

tblEvents
id cost_var event_day department
1 90.00 3 A
1 120 43 B
1 0.09 45 C
1 1290,10 92 A

tblCuts
cut_day department depart_id_cd manager
30 A 123 smith
30 B 456 jones
30 C 789 love
60 A 123 smith
60 B 456 jones
60 C 789 love
90 A 123 smith
90 B 456 jones
90 C 789 love

I need days before the interval end date and department group_by accumulations assuming there is other data about the the department on the tblCuts that I also need to process. 

Is there a way to do this which I am unaware of without adding a dummy "fake" join variable to a full_join and then apply my filter for the condition when the two variables are on the same data row? 

*** Note: ***
This is a toy example as I legally can't use my data or code to make reprex for you so I make up toy examples of the problem to get at the root of my need. I'm very sorry as sometimes the toy is easily solved and the real situation involves more complex data / inputs. Offering a simple solution to the toy problem that doesn't  that are easier processed with the crosses that are like the ones here and have other confidential data.

**Comment by hadley** [comment]
Already done in the dev version:

``` r
library(dplyr, warn.conflicts = FALSE)
mtcars %>% 
  as_tibble() %>% 
  full_join(mtcars, by = character())
#> # A tibble: 1,024 x 22
#>    mpg.x cyl.x disp.x  hp.x drat.x  wt.x qsec.x  vs.x  am.x gear.x carb.x mpg.y
#>    <dbl> <dbl>  <dbl> <dbl>  <dbl> <dbl>  <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl>
#>  1    21     6    160   110    3.9  2.62   16.5     0     1      4      4  21  
#>  2    21     6    160   110    3.9  2.62   16.5     0     1      4      4  21  
#>  3    21     6    160   110    3.9  2.62   16.5     0     1      4      4  22.8
#>  4    21     6    160   110    3.9  2.62   16.5     0     1      4      4  21.4
#>  5    21     6    160   110    3.9  2.62   16.5     0     1      4      4  18.7
#>  6    21     6    160   110    3.9  2.62   16.5     0     1      4      4  18.1
#>  7    21     6    160   110    3.9  2.62   16.5     0     1      4      4  14.3
#>  8    21     6    160   110    3.9  2.62   16.5     0     1      4      4  24.4
#>  9    21     6    160   110    3.9  2.62   16.5     0     1      4      4  22.8
#> 10    21     6    160   110    3.9  2.62   16.5     0     1      4      4  19.2
#> # … with 1,014 more rows, and 10 more variables: cyl.y <dbl>, disp.y <dbl>,
#> #   hp.y <dbl>, drat.y <dbl>, wt.y <dbl>, qsec.y <dbl>, vs.y <dbl>, am.y <dbl>,
#> #   gear.y <dbl>, carb.y <dbl>
```

<sup>Created on 2020-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
