### ISSUE TITLE
Unclear warning from summarise

### ISSUE THREAD

**Issue by eribul** [tidyverse/dplyr#5251]
I am currently running some time-consuming R-scripts and have recently updated dplyr to v. 0.8.99.9003. Now, a couple of days into the process I have noticed the following warning:

`r summarise() ungroup (override with .groups argument)`

I have now reaed the documentation and understand the ungrouping applies to the **output** of  `summarise`. That was not very clear from the message however, as I first interpreted as the grouping was ignored **within** the function.

If the run-time for my script was short, I would just have inspected the result to find out. Now, I would have risked to terminate the process for such inspection, just to loose several days of the process.

This is just to say that I would recomment to perhaps change the message to:
`r summarise() have ungrouped the outcome (override with .groups argument)`
or similar.

**Comment by hadley** [comment]
That's why we've already improved it:

``` r
library(dplyr, warn.conflicts = FALSE)

out <- mtcars %>% group_by(vs, cyl) %>% summarise(n = n())
#> `summarise()` regrouping output by 'vs' (override with `.groups` argument)
```

<sup>Created on 2020-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You must be running an old dev version.
