### ISSUE TITLE
dplyr::lag fails on all time series

### ISSUE THREAD

**Issue by AHoerner** [tidyverse/dplyr#5256]
I assume this is intentional, perhaps in the hope of avoiding the many different time series formats that R packages offer. But as lag( ) does not actually make sense except when there is at least implicit time, I think it would be a fine thing if, minimally, it accepted objects in the base R time series class as data. Currently this results in:

with dplyr loaded,

ts1 <- ts(1:4)
lag(ts1,1)
Error: `x` must be a vector, not a ts object, do you want `stats::lag()`?
and rlang::last_trace() shows the error as deriving from dplyr::lag(ts1, 1)

**Comment by hadley** [comment]
Correct. We are not planning to reconsider that behaviour at this time.
