### ISSUE TITLE
colwise vignette needs an update re where()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/dplyr#5258]
The `_if`, `_at`, `_all` section of the colwise vignette needs an update in light of the tidy-select changes around predicate functions and `where()`.

In this vicinity:

https://github.com/tidyverse/dplyr/blame/master/vignettes/colwise.Rmd#L186

**Comment by hadley** [comment]
@lionel- can you take a look please?

**Comment by jennybc** [comment]
Context: I spotted a broom PR to remove reshape2 that switches to `mutate_if()`. So I tried to find the best resource for getting away from scoped verbs. Which I think is the colwise vignette? But then the vignette shows syntax around predicate functions that will also become superseded at the same time.
