### ISSUE TITLE
mutate in dplyr

### ISSUE THREAD

**Issue by BlondeauSylvain** [tidyverse/dplyr#5261]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
I've updated my package cartograflow that it uses dplyr. 
In my function I use mutate function of dplyr with .data pronoum o fthe package rlang.
#' @importFrom rlang .data
myfunction<-function(){ 
tab<- tab%>% 
              mutate(minFij = ifelse(.data$Fij < .data$Fji, .data$Fij, .data$Fji)) %>%
              mutate(maxFij = ifelse(.data$Fij > .data$Fji, .data$Fij, .data$Fji))
}

-----checking R code for possible problems ... NOTE
          myfunction: no visible binding for global variable ‘maxFij’
          myfunction: no visible binding for global variable ‘minFij’
  Undefined global functions or variables:   maxFij minFij

To fix this issue I added to my code 
myfunction<-function(){ 
        maxFij<-Fij<-Fji<-NULL 
        minFij<-Fij<-Fji<-NULL
tab<- tab%>% 
              mutate(minFij = ifelse(.data$Fij < .data$Fji, .data$Fij, .data$Fji)) %>%
              mutate(maxFij = ifelse(.data$Fij > .data$Fji, .data$Fij, .data$Fji))
}
All things it's Ok after R CMD check
Is this a regression of the dplyr package or is it a normal functionning?

```r
myfunction<-function(){ 
tab<- tab%>% 
              mutate(minFij = ifelse(.data$Fij < .data$Fji, .data$Fij, .data$Fji)) %>%
              mutate(maxFij = ifelse(.data$Fij > .data$Fji, .data$Fij, .data$Fji))
}
```
[donnee.zip](https://github.com/tidyverse/dplyr/files/4664564/donnee.zip)

**Comment by hadley** [comment]
Could you please include a link to your package source? I don't see why your function would generate that note, so I suspect it's coming from somewhere else.

**Comment by BlondeauSylvain** [comment]
Hi, 
You will find hereafter the link of the cartograflow package. 
 The function I'm working on is flowtype; it is currently on the branch: preparation v1.1.0 in the cartogRaflow/inst/ directory.

fbahoken/cartogRaflow

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
fbahoken/cartogRaflow

Tips and tricks for flow and movement mapping. Contribute to fbahoken/cartogRaflow development by creating an ac...
 |

 |

 |





    Le vendredi 22 mai 2020 à 00:10:39 UTC+2, Hadley Wickham <notifications@github.com> a écrit :  
 
 


Could you please include a link to your package source? I don't see why your function would generate that note, so I suspect it's coming from somewhere else.

**Comment by romainfrancois** [comment]
I suppose this is where it's happening: https://github.com/fbahoken/cartogRaflow/blob/preparation-v1.1.0/inst/preparation%20version%201.1.0/flowtype.R#L104

You might want to declare those with `utils::globalVariables()`, e.g. in a `zzz.R` file: 

```r
utils::globalVariables(c("maxFij", "minFij"))
```

**Comment by BlondeauSylvain** [comment]
I understand!
I'm sorry, but the maxFij et minFij is not the variable.
I added `.data` in `mutate(rangeFij = .data$maxFij - .data$minFij)`. 
R CMD Check is OK
