### ISSUE TITLE
Perf issue with across and summarise

### ISSUE THREAD

**Issue by ericemc3** [tidyverse/dplyr#5264]
I am having a perf issue with across.

2s versus 74s depending on the writing.

My dplyr version: 0.8.99.9003
```r
mun2014 <- vroom("https://data.regardscitoyens.org/elections/2014_municipales/MN14_Bvot_T1_01-49.txt", 
                 col_select = -c('X4','X9','X10','X11'),
                 col_names = FALSE, 
                 locale = locale(encoding = "WINDOWS-1252")) 
# 275000 obs, 9 variables

system.time( dataag1 <- mun2014 %>%
               group_by_if( is.character )  %>%
               summarise_if( is_numeric, sum ) 
)
# 1.4s

system.time( dataag2 <- mun2014 %>%
              group_by( across(where(is.character)) )  %>%
              summarise( across(where(is_numeric), sum) ) 
)
# 74 s

all.equal(dataag1,dataag2)
# true

# by the way: is there a simplier manner to use across here?
```

**Comment by romainfrancois** [comment]
Performance of `across()` and `summarise()` is on our radar for version 1.1.0

**Comment by ericemc3** [comment]
Thank you. What would be your estimated date for that 1.1.0 version?

**Comment by hadley** [comment]
We don't have a date yet. But there's no rush to stop using `filter_if()`; it'll be around for at least several more years before we even begin to consider if it should be deprecated.

**Comment by tarouikemen** [comment]
Now using dplyr 1.0.0, and today  summarise(), arrange(), across() are coming surprisingly too slow about 100 or 1000 times.
Is there any solution ?

**Comment by mscbuck** [comment]
> Now using dplyr 1.0.0, and today summarise(), arrange(), across() are coming surprisingly too slow about 100 or 1000 times.
> Is there any solution ?

I actually have experienced the same thing after updating to 1.0.0, both on my PC and Mac. Specifically, for me it has been group_by + summarise combinations

**Comment by lionel-** [comment]
Is this with natively interpreted expressions like `mean()` or `sum()`? If so, this is what will be fixed in 1.1.

**Comment by ericemc3** [comment]
Good news!

**Comment by romainfrancois** [comment]
Minor changes to the code, I turned off altrep in `vroom` so that it would not interfere with the timings (the `vroom()` time would be greater, but that's not the point here). 

``` r
library(dplyr, warn.conflicts = FALSE)
library(vroom)

mun2014 <- vroom("https://data.regardscitoyens.org/elections/2014_municipales/MN14_Bvot_T1_01-49.txt", 
                 col_select = -c('X4','X9','X10','X11'),
                 col_names = FALSE, 
                 locale = locale(encoding = "WINDOWS-1252"), altrep = FALSE) 
#> Rows: 275,446
#> Columns: 9
#> Delimiter: ";"
#> chr [4]: X2, X3, X5, X12
#> dbl [5]: X1, X6, X7, X8, X13
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
# 275000 obs, 9 variables

bench::workout({
  a <- mun2014 %>% group_by_if( is.character )
  b <- a %>% summarise_if( is.numeric, sum ) 
})
#> # A tibble: 2 x 3
#>   exprs                                       process     real
#>   <bch:expr>                                 <bch:tm> <bch:tm>
#> 1 a <- mun2014 %>% group_by_if(is.character)    129ms    129ms
#> 2 b <- a %>% summarise_if(is.numeric, sum)      708ms    709ms

bench::workout({
  c <- mun2014 %>% group_by( across(where(is.character)))
  d <- c %>% summarise( across(where(is.numeric), sum) ) 
})
#> `summarise()` has grouped output by 'X2', 'X3', 'X5'. You can override using the `.groups` argument.
#> # A tibble: 2 x 3
#>   exprs                                                   process     real
#>   <bch:expr>                                             <bch:tm> <bch:tm>
#> 1 c <- mun2014 %>% group_by(across(where(is.character)))  119.5ms 119.66ms
#> 2 d <- c %>% summarise(across(where(is.numeric), sum))       7.8s    7.82s

all.equal(b, d)
#> [1] TRUE
```

<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
There are several angles we can use to try and improve on that. The flame graph for `summarisz() + `across()` gives: 

![image](https://user-images.githubusercontent.com/2625526/104910687-f7570900-5989-11eb-9048-bf931137ff43.png)

The part on the right is: 

```r
        map2(seq_along(result_type), names(result_type), function(j, nm) {
          mask$add(nm, pluck(chunks[[i]], j))
        })
```

which I believe could be done internally
