### ISSUE TITLE
count() has had major breaking changes

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#5265]
Count used to work twice in a row to find out how many count values you had, eg:

Counting a combination of vars, and then counting the n would produce a result that told you how many times you had a count of, say, 1 or 2, etc.

Ie, you'd get this:

![image](https://user-images.githubusercontent.com/25590353/82705497-fcb25700-9c34-11ea-850c-dc8a7da71803.png)

However, now you get an error:

``` r
require(tidyverse)
#> Loading required package: tidyverse

mtcars %>% 
  count(cyl, gear) %>% 
  count(n)
#> Using `n` as weighting variable
#> Error: Column `n` is already present in output.
#> ℹ Use `name = "new_name"` to pick a new name.
```

And if you give the second count a name so as to avoid the conflict, it auto-weights, so the result still is not what was produced originally.

``` r
require(tidyverse)
#> Loading required package: tidyverse

mtcars %>% 
  count(cyl, gear) %>% 
  count(n, name = "nn")
#> Using `n` as weighting variable
#>    n nn
#> 1  1  2
#> 2  2  6
#> 3  4  4
#> 4  8  8
#> 5 12 12
```

While I get that there are ways around this, it seems like an unexpected assumption that a weight should be applied, and it also requires a lot of recoding old things.

**Comment by hadley** [comment]
What do you mean by "now"?

**Comment by jzadra** [comment]
It seems like at some point a newer `dplyr` version had this change.  I think I've noticed it within the last few weeks.

**Comment by hadley** [comment]
I see this in dplyr 0.8.5:

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  count(cyl, gear) %>% 
  count(n)
#> # A tibble: 5 x 2
#>       n    nn
#>   <int> <int>
#> 1     1     2
#> 2     2     3
#> 3     4     1
#> 4     8     1
#> 5    12     1
```

<sup>Created on 2020-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So presumably you've installed the development version where the behaviour has changed, as described inhttps://github.com/tidyverse/dplyr/issues/4284.

**Comment by jzadra** [comment]
Yeah, so this will break a whole lot of existing code.  The ability to count the counts was a useful feature imho.

**Comment by hadley** [comment]
A whole lot of existing code is a rather hyperbolic claim, but I'll take a look next week.

**Comment by romainfrancois** [comment]
I believe this is related to #5109 which includes a way to disable the "use n as weighting variable" default: 

``` r
library(dplyr, warn.conflicts = FALSE)

data.frame(x = 1, n = 2) %>% 
  count(n, name = "nn")
#> Using `n` as weighting variable
#>   n nn
#> 1 2  2

data.frame(x = 1, n = 2) %>% 
  count(n, name = "nn", wt = NULL)
#>   n nn
#> 1 2  1
```

<sup>Created on 2020-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`wt` is documented as: 

```
#' @param wt <[`data-masking`][dplyr_data_masking]> If omitted, will count the
#'   number of rows. If specified, will perform a "weighted" count by summing
#'   the (non-missing) values of variable `wt`.
#'
#'   If omitted, and column `n` exists, it will automatically be used as a
#'   weighting variable, although you will have to specify `name` to provide
#'   a new name for the output.
```

**Comment by jzadra** [comment]
I meant within my post code. I didn't intend that to be a generalization to all R code.
On May 23, 2020, 08:45 -0600, Hadley Wickham <notifications@github.com>, wrote:
> A whole lot of existing code is a rather hyperbolic claim, but I'll take a look next week.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

--

**Comment by jzadra** [comment]
*past code.
On May 25, 2020, 19:24 -0600, Jonathan Zadra <jon.zadra@sorensonimpact.com>, wrote:
> I meant within my post code. I didn't intend that to be a generalization to all R code.
> On May 23, 2020, 08:45 -0600, Hadley Wickham <notifications@github.com>, wrote:
> > A whole lot of existing code is a rather hyperbolic claim, but I'll take a look next week.
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.

--

**Comment by nhols** [comment]
should this be listed as a breaking change in release notes? https://github.com/tidyverse/dplyr/releases

**Comment by hadley** [comment]
No, because we reverted it.

**Comment by nhols** [comment]
Ah perhaps what I'm seeing is only tangentially related to the issue raised here.

Not breaking in the sense that it throws an error, but in that default behavior changed.

0.8.5
``` r
library(dplyr, warn.conflicts = FALSE)
packageVersion("dplyr")
#> [1] '0.8.5'
tibble(x = 1:3, n = 3:1) %>% count(x)
#> # A tibble: 3 x 2
#>       x     n
#>   <int> <int>
#> 1     1     1
#> 2     2     1
#> 3     3     1
```
1.0.0
``` r
library(dplyr, warn.conflicts = FALSE)
packageVersion("dplyr")
#> [1] '1.0.0'
tibble(x = 1:3, n = 3:1) %>% count(x)
#> Using `n` as weighting variable
#> ℹ Quiet this message with `wt = n` or count rows with `wt = 1`
#> # A tibble: 3 x 2
#>       x     n
#>   <int> <int>
#> 1     1     3
#> 2     2     2
#> 3     3     1
```

**Comment by hadley** [comment]
@nhols can you please file a new issue?
