### ISSUE TITLE
Multiple groups using mutate

### ISSUE THREAD

**Issue by Turtle9er** [tidyverse/dplyr#5267]
Not sure if this is an expected outcome, but don't remember this happening when not using the new across() function in 0.8.99.9003. If I group by two columns, when I go to mutate the index is off by 1. This also happens if I use the column index number. So if I am looking to round column 3:4, to make it would I would have to put 2:3 so the right columns are rounded. See example below. I expect MPG and disp to be rounded. For my current project I am using column names like this, mutate(across(which(colnames(.)%in%round_met)-1, round, 1)) , to round the correct columns, but as you can see I have to subtract one to get the right columns to round. Maybe this is expected, but just wanted to check. Thanks.

```r

library(dplyr)
mtcars %>%
  group_by(`cyl`,`hp`) %>%
  summarise(across(where(is.numeric), mean,na.rm = TRUE)) %>%
  mutate(across(3:4, round, 1)) %>%
  as.data.frame()

#  cyl  hp    mpg  disp drat    wt   qsec    vs    am  gear carb
1    4  52 30.400  75.7  4.9 1.615 18.520 1.000 1.000 4.000    2
2    4  62 24.400 146.7  3.7 3.190 20.000 1.000 0.000 4.000    2
3    4  65 33.900  71.1  4.2 1.835 19.900 1.000 1.000 4.000    1
4    4  66 29.850  78.8  4.1 2.067 19.185 1.000 1.000 4.000    1
```

**Comment by hadley** [comment]
`across()` only operates on the non-grouping columns. This is one reason that selecting by position is best avoided where possible.
