### ISSUE TITLE
group_by / summarise on empty data frame behaves weirdly.

### ISSUE THREAD

**Issue by AshesITR** [tidyverse/dplyr#5278]
A `group_by() %>% summarise()` on an empty tibble creates a 1-row tibble and some warnings.
I'd expect it to just return a 0-row tibble with the grouping variable.

This would be useful in a case where we want to aggregate results but don't know a priori whether there are any matching rows to aggregate.

As-is, the case `nrow(.) == 0` needs special treatment.

NB I did not test this in the development version yet.

``` r
library(dplyr)
#> 
#> Attache Paket: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

iris <- as_tibble(iris)

iris %>% filter(is.na(Species)) %>% group_by(Species) %>% summarise()
#> Warning: Factor `Species` contains implicit NA, consider using
#> `forcats::fct_explicit_na`
#> # A tibble: 1 x 1
#>   Species
#>   <fct>  
#> 1 <NA>

# Expected result:
iris %>% filter(is.na(Species)) %>% select(Species) %>% distinct()
#> # A tibble: 0 x 1
#> # ... with 1 variable: Species <fct>

# Also weird:
iris %>% filter(is.na(Species)) %>% summarise()
#> # A tibble: 1 x 0
```

<sup>Created on 2020-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Here's what I see in the development version:

``` r
library(dplyr, warn.conflicts = FALSE)

iris %>% 
  filter(FALSE) %>% 
  group_by(Species) %>% 
  summarise()
#> `summarise()` ungrouping output (override with `.groups` argument)
#> # A tibble: 0 x 1
#> # … with 1 variable: Species <fct>
```

<sup>Created on 2020-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
