### ISSUE TITLE
top_n documentation error

### ISSUE THREAD

**Issue by MikeJohnPage** [tidyverse/dplyr#5279]
The [`top_n()`](https://dplyr.tidyverse.org/reference/top_n.html) example documentation is throwing an error on the dplyr website (at least for me). I believe this is an R error (roxygen perhaps) and not a web rendering error:

<img width="888" alt="Screenshot 2020-05-28 at 17 24 47" src="https://user-images.githubusercontent.com/38110953/83161000-29201480-a108-11ea-952b-18468596d044.png">

I just wanted to flag it for your attention.

**Comment by hadley** [comment]
It appears to be already fixed in the development version: https://dplyr.tidyverse.org/dev/reference/top_n.html
