### ISSUE TITLE
Weird behaviour with dplyr 1.0 while modifying NA level of a factor

### ISSUE THREAD

**Issue by oranwutang** [tidyverse/dplyr#5284]
Hi,

I have found, after upgrading to dplyr 1.0, that there is a weird behaviour in the interaction between group_by and mutate.

The thing is that while working with dplyr 0.8.5 I had a dataset which I grouped by date and then modified the NA level of another variable to finally make a plot. It worked nicely (besides the warnings that you can see in the reprex below, I wasn't aware of them till I made the reprex because the code was originally in an rmarkdown file with warnings set to off).

When I upgraded to dplyr 1.0 (and R 4.0) the levels of the variable where not correctly ordered (look at the legend in the first plot in the R 4.0 reprex).

I solved the problem by putting the mutate sentence before the grouping sentence, I don't understand why grouping should modify the action of fct_explicit_na() because I think that the lattter just substitutes NA for some other string.

I realize that to modify the factors before grouping the dataset may be more logical, but there is a clear different behaviour between the two versions of dplyr (I'm blaming dplyr for the issue but  maybe it is also due to the R 4.0 upgrade). 

In brief, with dplyr 0.8.5 the job was done right but with warnings but with dplyr 1.0 the job is incorrectly done and without warnings so I think that this may compromise the reproducibility of some projects or analysis.

Maybe the only weird behaviour was mine while ordering the sentences in the pipeline to get the plot.

Don't you think that the newer version should at least warn the user about this issue?

Thanks a lot and best regards!

PS: In the dplyr 0.8.5 reprex below I'am also showing the "correctly" ordered pipeline.
PS2: Sorry if a wasn't clear enough but my english is not so good ;)  

---

## R 3.6.3 and dplyr 0.8.5  

``` r
library(tidyverse)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:dplyr':
#> 
#>     intersect, setdiff, union
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

set.seed(123)
date_dummy <- sample(seq(as.Date('2016/01/01'), as.Date('2020/01/01'), by = "days"), 50, 
replace = TRUE)
mRS <- sample(c(NA_character_, "0", "1", "2", "3", "4", "5", "6"), 50, T)
dataset <- data.frame(date_dummy, mRS) 

str(dataset)
#> 'data.frame':    50 obs. of  2 variables:
#>  $ date_dummy: Date, format: "2017-02-18" "2017-04-07" ...
#>  $ mRS       : Factor w/ 7 levels "0","1","2","3",..: NA NA 2 NA 5 4 6 NA 6 1 ...

dataset %>% 
  group_by(Month=month(floor_date(date_dummy, "months"), abbr=TRUE, label=TRUE)) %>% 
  mutate(mRS_rec=fct_explicit_na(mRS, na_level = "Unk")) %>% 
  ggplot(aes(y=Month))+
  geom_bar(aes(fill=mRS_rec), position = "fill")
#> Warning in mutate_impl(.data, dots, caller_env()): Unequal factor levels:
#> coercing to character
#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector

#> Warning in mutate_impl(.data, dots, caller_env()): binding character and factor
#> vector, coercing into character vector
```

![](https://i.imgur.com/xdDzhoc.png)

``` r

dataset %>% 
  mutate(mRS_rec=fct_explicit_na(mRS, na_level = "Unk")) %>%
  group_by(Month=month(floor_date(date_dummy, "months"), abbr=TRUE, label=TRUE)) %>% 
  ggplot(aes(y=Month))+
  geom_bar(aes(fill=mRS_rec), position = "fill")
```

![](https://i.imgur.com/12uo3Zh.png)

## R 4.0 and dplyr 1.0  

``` r
library(tidyverse)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

set.seed(123)
date_dummy <- sample(seq(as.Date('2016/01/01'), as.Date('2020/01/01'), by = "days"), 50, 
replace = TRUE)
mRS <- sample(c(NA_character_, "0", "1", "2", "3", "4", "5", "6"), 50, T)
dataset <- data.frame(date_dummy, mRS) 

str(dataset)
#> 'data.frame':    50 obs. of  2 variables:
#>  $ date_dummy: Date, format: "2017-02-18" "2017-04-07" ...
#>  $ mRS       : chr  NA NA "1" NA ...

dataset %>% 
  group_by(Month=month(floor_date(date_dummy, "months"), abbr=TRUE, label=TRUE)) %>% 
  mutate(mRS_rec=fct_explicit_na(mRS, na_level = "Unk")) %>% 
  ggplot(aes(y=Month))+
  geom_bar(aes(fill=mRS_rec), position = "fill")
```

![](https://i.imgur.com/gCrbhzB.png)

``` r

dataset %>% 
  mutate(mRS_rec=fct_explicit_na(mRS, na_level = "Unk")) %>%
  group_by(Month=month(floor_date(date_dummy, "months"), abbr=TRUE, label=TRUE)) %>% 
  ggplot(aes(y=Month))+
  geom_bar(aes(fill=mRS_rec), position = "fill")
```

![](https://i.imgur.com/EubpKo3.png)

<sup>Created on 2020-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your explanation and code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster we can identify the problem and fix it.

**Comment by oranwutang** [comment]
Dear Hadley,

I've tried to make an shorter reprex but I couldn't do it.

I think that my issue (that is actually solved as shown in the reprex above) is due to a very very particular case with my data and the analysis that I need to perform.

So I guess that, if you agree, this issue could be closed.

Thanks for your attention @hadley!

**Comment by hadley** [comment]
This is what I see on dplyr 1.0.0:

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
library(lubridate, warn.conflicts = FALSE)

set.seed(123)
date_dummy <- sample(seq(as.Date('2016/01/01'), as.Date('2020/01/01'), by = "days"), 50, 
replace = TRUE)
mRS <- sample(c(NA_character_, "0", "1", "2", "3", "4", "5", "6"), 50, T)
dataset <- data.frame(date_dummy, mRS) 

dataset %>% 
  group_by(Month = month(floor_date(date_dummy, "months"), abbr=TRUE, label=TRUE)) %>% 
  mutate(mRS_rec = forcats::fct_explicit_na(mRS, na_level = "Unk")) %>%
  ggplot(aes(y=Month))+
  geom_bar(aes(fill=mRS_rec), position = "fill")
```

![](https://i.imgur.com/gk84mJU.png)

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So I can't replicate your problem; and unfortunately if you can't try and make it any simpler there's not much I can do.
