### ISSUE TITLE
Error in dplyr 1.0.0 when using mutate on objects extending data.frame 

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/dplyr#5286]
Since `dplyr 1.0.0`, when you use `mutate` on custom objects that inherit from `data.frame`, an error is thrown depending on the place of `data.frame` on the list of classes.

If `data.frame` is the last class in the list, the function performs normally, else, it throws this surprising error message: 

> Error: `x` must be a vector, not a `data.frame/myobject2` object.

Using `as.data.frame` beforehand has no effect but using `as_tibble` makes it right again.

Here is a reproducible example:

``` r
library(dplyr, warn.conflicts = FALSE)
tmp=iris
class(tmp) = c("myobject", "data.frame")
tmp %>% mutate(Sepal.Length=Sepal.Length*2) %>% head(2)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1         10.2         3.5          1.4         0.2  setosa
#> 2          9.8         3.0          1.4         0.2  setosa
class(tmp) = c("data.frame", "myobject2")
tmp %>% mutate(Sepal.Length=Sepal.Length*2) %>% head(2)
#> Error: `x` must be a vector, not a `data.frame/myobject2` object.
tmp %>% as.data.frame %>% mutate(Sepal.Length=Sepal.Length*2) %>% head(2)
#> Error: `x` must be a vector, not a `data.frame/myobject2` object.
class(tmp) = c("myobject", "data.frame", "myobject2")
tmp %>% mutate(Sepal.Length=Sepal.Length*2) %>% head(2)
#> Error: `x` must be a vector, not a `myobject/data.frame/myobject2` object.
tmp %>% as.data.frame %>% mutate(Sepal.Length=Sepal.Length*2) %>% head(2)
#> Error: `x` must be a vector, not a `data.frame/myobject2` object.
tmp %>% as_tibble %>% mutate(Sepal.Length=Sepal.Length*2) %>% head(2)
#> # A tibble: 2 x 5
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#> 1         10.2         3.5          1.4         0.2 setosa 
#> 2          9.8         3            1.4         0.2 setosa
```
<sup>Created on 2020-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Data frame should always be the last class in the list. Where are these objects coming from?

**Comment by DanChaltiel** [comment]
From the package [crosstable](https://github.com/DanChaltiel/crosstable), which I'm developing in my free time. 

I was not aware of such a rule, I'm going to correct my object, but I'm curious about why it should be the last one (any explanation or link would be much appreciated if you have time for this).

Still, I'm not sure this rule is widely known, so there might be a lot of objects with `data.frame` not as the last class in the wild. Therefore, the `mutate` function could be more robust if the error can be addressed, or maybe the message clarified.

**Comment by hadley** [comment]
A class of `c("myobject", "data.frame")` declares that `myobject` inherits behaviour from `data.frame. A class of `c("data.frame", "myobject")` declares that `data.frame` inherits behaviour from `myobject`; which doesn't make sense since only the "owner" of data.frame can declare what it inherits from.

**Comment by hadley** [comment]
We currently consider objects like this to be "corrupt" and the responsibility of the package maintainer to fix. If it turns out that these are very common in the wild, we'll reconsider our messaging.
