### ISSUE TITLE
version 1.0.0 cummean() function is providing weird results

### ISSUE THREAD

**Issue by cropgen** [tidyverse/dplyr#5287]
For testing, I have this small vector `x` where the long(er) way is giving me the results as expected version 1.0.0 `cummean()` is not. 

``` r
library(tidyverse)
x <- 1:5

# long(er) way
cumsum(x) / seq_along(x)
#> [1] 1.0 1.5 2.0 2.5 3.0

# dplyr 0.8.5 cummean()
cummean(x)
#> [1] 1.0 1.5 2.0 2.5 3.0

# dplyr 1.0.0 cummean()
cummean(x)
#> [1] 1.000000 1.000000 1.333333 1.750000 2.200000
```

<sup>Created on 2020-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by brianrice2** [comment]
It looks like the indexing is off by one for `dplyr_cummean` in /src/funs.cpp, causing the first index to be repeated twice (and the last index to be dropped). I'll submit a pull request with a slight change which I think makes it work as intended.

**Comment by cropgen** [comment]
Thanks @brianrice2 for the quick fix.
