### ISSUE TITLE
The .drop=FALSE option in group_by doesn't work if the grouping variables aren't already factors

### ISSUE THREAD

**Issue by pitakakariki** [tidyverse/dplyr#5292]
Groups with no observations are dropped, despite `.drop=FALSE` being explicitly set:

<details>

```r
mtcars %>%
    group_by(cyl, carb, .drop=FALSE) %>%
    summarise(count=n())

# `summarise()` regrouping output by 'cyl' (override with `.groups` argument)
# # A tibble: 9 x 3
# # Groups:   cyl [3]
#     cyl  carb count
#   <dbl> <dbl> <int>
# 1     4     1     5
# 2     4     2     6
# 3     6     1     2
# 4     6     4     4
# 5     6     6     1
# 6     8     2     4
# 7     8     3     3
# 8     8     4     6
# 9     8     8     1
```

If the grouping factors are converted to factors first, we get the expected behaviour:

```r
mtcars %>%
    mutate(cyl=as.factor(cyl), carb=as.factor(carb)) %>%
    group_by(cyl, carb, .drop=FALSE) %>%
    summarise(count=n())

# `summarise()` regrouping output by 'cyl' (override with `.groups` argument)
# # A tibble: 18 x 3
# # Groups:   cyl [3]
#    cyl   carb  count
#    <fct> <fct> <int>
#  1 4     1         5
#  2 4     2         6
#  3 4     3         0
#  4 4     4         0
#  5 4     6         0
#  6 4     8         0
#  7 6     1         2
#  8 6     2         0
#  9 6     3         0
# 10 6     4         4
# 11 6     6         1
# 12 6     8         0
# 13 8     1         0
# 14 8     2         4
# 15 8     3         3
# 16 8     4         6
# 17 8     6         0
# 18 8     8         1
```

</details>

**Comment by hadley** [comment]
Simpler reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>%
  group_by(gear, am, .drop=FALSE) %>%
  summarise(n = n(), .groups = "drop")
#> # A tibble: 4 x 3
#>    gear    am     n
#> * <dbl> <dbl> <int>
#> 1     3     0    15
#> 2     4     0     4
#> 3     4     1     8
#> 4     5     1     5

as.data.frame(table(mtcars[c("gear", "am")]))
#>   gear am Freq
#> 1    3  0   15
#> 2    4  0    4
#> 3    5  0    0
#> 4    3  1    0
#> 5    4  1    8
#> 6    5  1    5
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Did this use to work in 0.8.5?

**Comment by pitakakariki** [comment]
No, didn't work in 0.8.5 either. I was using 0.8.5 when I found this.

**Comment by hadley** [comment]
Ah, the problem is that the documentation is confusing. I'll fix that.

**Comment by pitakakariki** [comment]
No, I think it's the behaviour that's confusing rather than the documentation.

In a tidyverse context where `stringsAsFactors` is false by default, I wouldn't expect that `group_by` would treat categorical variables differently depending on whether they're stored as characters or as factors. Especially when an option like `.drop` is being set explicitly.

**Comment by hadley** [comment]
@pitakakariki there's no way to know what levels exist but are not present in the data with a character vector.

**Comment by pitakakariki** [comment]
@hadley I think you might be confusing levels for individual categorical variables with combinations of levels for multiple categorical variables?

For individual character variables, you're correct that there's no way to know about levels not present in the data.

But when you look at multiple variables, neither factors nor characters can tell you what combinations exist. It's implicit in either case: either all combinations present (`.drop=TRUE`) or all combinations (`.drop=FALSE`). Since it's implicit in both cases expected behaviour is the same in both cases.

**Comment by hadley** [comment]
That's why I meant it's a documentation issue; I don't think the intent here is to expand all combinations of empty groups that might exist but don't.

**Comment by pitakakariki** [comment]
The issue isn't "combinations of empty groups" though, it's "empty groups of level combinations". And there's no reason the behaviour there should be different between categorical variables encoded as factors or characters.

**Comment by pitakakariki** [comment]
Some additional findings: one character and one factor gives different results to one factor and one character.

<details>

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

mtcars %>%
  mutate(gear=as.factor(gear)) %>%
  group_by(gear, am, .drop=FALSE) %>%
  summarise(n = n(), .groups = "drop")
#> # A tibble: 4 x 3
#>   gear     am     n
#>   <fct> <dbl> <int>
#> 1 3         0    15
#> 2 4         0     4
#> 3 4         1     8
#> 4 5         1     5

mtcars %>%
  mutate(am=as.factor(am)) %>%
  group_by(gear, am, .drop=FALSE) %>%
  summarise(n = n(), .groups = "drop")
#> # A tibble: 6 x 3
#>    gear am        n
#>   <dbl> <fct> <int>
#> 1     3 0        15
#> 2     3 1         0
#> 3     4 0         4
#> 4     4 1         8
#> 5     5 0         0
#> 6     5 1         5
```

<sup>Created on 2020-06-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

**Comment by pitakakariki** [comment]
Could you please reopen this and put the "bug" tag back? The linked pulled request does not address this issue.

**Comment by hadley** [comment]
@pitakakariki I have documented the behaviour that we intended. Unfortunately I think the feature that you want is currently out of scope: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by pitakakariki** [comment]
The feature that I want is already available, as you can see from my initial reprex.

The problem is that the behaviour is inconsistent (and as far as I can tell basically unpredictable) depending on which grouping variables are factors or characters.

I don't see how the tweaked documentation addresses that inconsistent behaviour.

I know that you don't have unlimited time. But if you don't understand the issue could you please leave it open so that someone who does won't miss it because it's closed?

**Comment by pitakakariki** [comment]
Here's an example where the behaviour is unambiguously not as intended:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

mtcars %>%
  
  mutate(am=as.factor(am)) %>%
  
  group_by(gear, am, cyl, .drop=FALSE) %>%
  
  summarise(count=n())
#> `summarise()` regrouping output by 'gear', 'am' (override with `.groups` argument)
#> # A tibble: 12 x 4
#> # Groups:   gear, am [6]
#>     gear am      cyl count
#>    <dbl> <fct> <dbl> <int>
#>  1     3 0         4     1
#>  2     3 0         6     2
#>  3     3 0         8    12
#>  4     3 1        NA     0
#>  5     4 0         4     2
#>  6     4 0         6     2
#>  7     4 1         4     6
#>  8     4 1         6     2
#>  9     5 0        NA     0
#> 10     5 1         4     2
#> 11     5 1         6     1
#> 12     5 1         8     2
```

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pitakakariki** [comment]
I think where you went wrong is when you used `table` in your "simpler" reprex instead of adding a `mutate` step like in the original bug report. That meant that you lost sight of the fact that the intended behaviour already works in some cases.

**Comment by pitakakariki** [comment]
I've opened a second issue so that the inconsistent behaviour and documentation clarity can be resolved separately: https://github.com/tidyverse/dplyr/issues/5369
