### ISSUE TITLE
'scalar chr' type cannot be joined to a 'chr' type 

### ISSUE THREAD

**Issue by deann88** [tidyverse/dplyr#5296]
Hello,

I have a code which has been working for a long time. However, now I recreated the image and dplyr was updated to 1.0.0

I have a list which is turned to a tibble by bind_rows and then this tibble is joined to another one by `unique_id` variable. After the 1.0.0 update, bind_rows turns the type of `unique_id` to `'scalar' chr`. When this tibble is joined I get: 

>   tibbleFromListWithBindRows <- initialList %>% 
       map("desiredValues") %>% 
       bind_rows

> resultNeeded <- initialilTibble %>% 
         right_join(
           tibbleFromListWithBindRows,
           by = "unique_id"
         )

    Error: Can't join on `x$unique_id` x `y$unique_id` because of incompatible types.
    ℹ `x$unique_id` is of type character.
    ℹ `y$unique_id` is of type scalar.

> class(tibbleFromListWithBindRows$searchId)
[1] "scalar"    "character"
> typeof(tibbleFromListWithBindRows$searchId)
[1] "character"

In order to fix this I did: 

> resultNeeded <- initialilTibble %>% 
         right_join(
           tibbleFromListWithBindRows %>%
              mutate(unique_id = as.character(unique_id)),
           by = "unique_id"
         )

However, this seems like an ugly fix. Is this behavior intended, and if yes, why?

Also, where did these scalar types came from? 
I cannot find any documentation of them being mentioned in the release [notes](https://github.com/tidyverse/dplyr/releases/tag/v1.0.0).

P.S. Sorry for not being able to include a reproducible example. I tried but failed.

**Comment by hadley** [comment]
Unfortunately there's not much we can do without a reprex.

**Comment by krlmlr** [comment]
From `NEWS`:

* `bind_rows()`, `*_join()`, `summarise()` and `mutate()` use vctrs coercion 
  rules. There are two main user facing changes:

    * Combining factor and character vectors silently creates a character 
      vector; previously it created a character vector with a warning.
      
    * Combining multiple factors creates a factor with combined levels;
      previously it created a character vector with a warning.

Purely speculative, a reprex could look like this:

``` r
library(tidyverse)

tbl1 <- tibble(x = jsonlite:::as.scalar("a"))
tbl2 <- tibble(x = "b")
tbl11 <- bind_rows(tbl1, tbl1)

tbl11
#> # A tibble: 2 x 1
#>   x       
#>   <scalar>
#> 1 a       
#> 2 a

inner_join(tbl11, tbl2)
#> Joining, by = "x"
#> Error: Can't join on `x$x` x `y$x` because of incompatible types.
#> ℹ `x$x` is of type <scalar>>.
#> ℹ `y$x` is of type <character>>.
```

<sup>Created on 2020-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is the behavior different in dplyr < 1.0.0?

**Comment by hadley** [comment]
Now tracked in vctrs (assuming our guess at the root cause of the problem is correct)

**Comment by deann88** [comment]
Probably this one should also go to vctrs, but I'll post it also here as they seem connected and it is affecting dplyr
```
> # works fine
> bind_rows(
+   tibble(a = "chr", b = 2), 
+   tibble(b = 3, c = TRUE, d = FALSE)
+ )
# A tibble: 2 x 4
  a         b c     d    
  <chr> <dbl> <lgl> <lgl>
1 chr       2 NA    NA   
2 NA        3 TRUE  FALSE
```
```
> # doesn't bind on different classes
> bind_rows(
+   tibble(a = "chr", b = jsonlite:::as.scalar(2)), 
+   tibble(b = 3, c = TRUE, d = FALSE)
+ )
Error: Can't combine `..1` <scalar> and `..2` <double>.
Run `rlang::last_error()` to see where the error occurred.
```
```
> # doesn't bind on common_class_fallback 
> bind_rows(
+   tibble(a = jsonlite:::as.scalar("chr"), b = 2), 
+   tibble(b = 3, c = TRUE, d = FALSE)
+ )
Error: Can't combine `..1` <scalar> and `..2` <vctrs:::common_class_fallback>.
Run `rlang::last_error()` to see where the error occurred.

> bind_rows(
+   tibble(a = "chr", b = 2), 
+   tibble(b = 3, c = TRUE, d = jsonlite:::as.scalar(2))
+ )
Error: Can't combine `..1` <vctrs:::common_class_fallback> and `..2` <scalar>.
Run `rlang::last_error()` to see where the error occurred.
```
