### ISSUE TITLE
Issues with select function dplyr V1.0

### ISSUE THREAD

**Issue by RussellGrayxd** [tidyverse/dplyr#5301]
Using code that has worked for years, now after updating to dplyr v1.0 from dplyr v0.8.5 the code runs errors.

library(rgbif)
library(dplyr)

# Pull dataset records from GBIF
dat.all <- occ_search(datasetKey = "38fdd8b7-4e48-452c-8c05-673e6f6829af",
                      return = "data", limit = 2000)

Both this
dat <- dat.all%>%select(year, month, eventDate, 
                     family, genus, species, decimalLongitude, decimalLatitude)

and this
dat <- dplyr::select(dat.all, year, month, eventDate, 
                     family, genus, species, decimalLongitude, decimalLatitude)

run errors about x not being a vector, or select not functioning with tbl_df or data.frames

**Comment by lionel-** [comment]
With the error message (see https://reprex.tidyverse.org/):

```r
library(rgbif)
library(dplyr)

dat.all <- occ_search(datasetKey = "38fdd8b7-4e48-452c-8c05-673e6f6829af", return = "data", limit = 2000)
dat <- select(dat.all, year, month, eventDate, family, genus, species, decimalLongitude, decimalLatitude)
#> Error: `x` must be a vector, not a `tbl_df/tbl/data.frame/gbif` object.
```

**Comment by lionel-** [comment]
Reported downstream: https://github.com/ropensci/rgbif/issues/412
