### ISSUE TITLE
Global option for .groups argument to summarise

### ISSUE THREAD

**Issue by mike-lawrence** [tidyverse/dplyr#5303]
There’s a new message that prints when no explicit value is supplied for the .groups argument to summarise(). It would be great to have a global option to choose the default, then suppressing the warning thereafter so users don’t have to go through and set it explicitly throughout their codebase.

**Comment by hadley** [comment]
Unfortunately I think that would be rather a bad idea, because it would cause a similar problem to `stringsAsFactors`. I don't think it's a good idea to let options affect the results of computation.

**Comment by mike-lawrence** [comment]
Ah, that makes sense. Would it still be a bad idea to have a global option to toggle suppression of the warning message when no value is supplied to .groups?

**Comment by hadley** [comment]
That’s such a good idea that it in fact already exists 😉

**Comment by mike-lawrence** [comment]
*facepalm* sorry, I swear I RTFM, but somehow missed the new "dplyr.summarise.inform" option.
