### ISSUE TITLE
change in ntile behavior

### ISSUE THREAD

**Issue by r2evans** [tidyverse/dplyr#5309]
`ntile` changes behavior, and when the number of values is below `n`, it is reporting incorrect numbers.

```r
packageVersion("dplyr")
# [1] '0.8.3'
ntile(1:10, 100)
#  [1]  1 11 21 31 41 51 61 71 81 91

packageVersion("dplyr")
# [1] '1.0.0'
ntile(1:10, 100)
#  [1]  1  2  3  4  5  6  7  8  9 10
```

I expect that when the number of values is below `n`, that the returned values should span the range of `n`, not just count along the values.

**Comment by hadley** [comment]
See discussion for change in behaviour: https://github.com/tidyverse/dplyr/pull/5054

Note that it's not just returning the inputs:

``` r
dplyr::ntile(5:10 * 10, 100)
#> [1] 1 2 3 4 5 6
```

<sup>Created on 2020-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by r2evans** [comment]
I had always inferred (esp based on its previous behavior) that `ntile` facilitated percentile calculations/filtering, and using `quantile` twice seems inefficient. I wonder if I saw `ntile` before `percent_rank` and just latched onto it.

Thanks.
