### ISSUE TITLE
Retaining names of columns as symbol in across()

### ISSUE THREAD

**Issue by tjebo** [tidyverse/dplyr#5313]
First of all, thanks to all for those amazing packages. 

Having built my first package which I am about to submit, I was using `dplyr::mutate_at` and only today realised that this may not be a good idea it being superseded. 

However, a feature that was really nice with `mutate_at` got lost with across (or, I don't know how to apply it). 

The below demonstrates the problem: I would like to test each column and warn the user that sth happened, ideally giving the name of the column where. `mutate_at` retained the name of the column and passed it to the function, but `across` does not, therefore the warning becomes pointless. 

``` r
library(dplyr)

foo_warn <- function(x){
  if(any(x > 3)){
    warning(paste(deparse(substitute(x)), "has an implausible value"))
  }
  x
}

## this warning is helpful - it tells the user where the problem was. 

iris %>% mutate_at(vars(contains("Sepal")), foo_warn) %>% head
#> Warning in (function (x) : Sepal.Length has an implausible value 
#> Warning in (function (x) : Sepal.Width has an implausible value
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
#> 6          5.4         3.9          1.7         0.4  setosa

# name of columns was not retrieved and the warning becomes pointless

iris %>% mutate(across(contains("Sepal"), foo_warn)) %>% head
#> Warning in fn(col, ...): col has an implausible value
#> Warning in fn(col, ...): col has an implausible value
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
#> 6          5.4         3.9          1.7         0.4  setosa
```

<sup>Created on 2020-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
---

**Comment by hadley** [comment]
You can instead use `cur_column()` 😄

**Comment by tjebo** [comment]
@hadley Thanks for your swift reply! 
`cur_column()` looks great. Unfortunately I am not quite sure if I understand how to apply it to make it work in my example :( 

Well I guess I need to dig more into the matter :)

**Comment by tjebo** [comment]
One way would be the below, but it looks terrible to me... 
It requires adding another argument to my function and assignment within across... ??


``` r
library(tidyverse)
foo_warn <- function(x, sym){
  if(any(x > 3)){
    warning(paste(sym, "has an implausible value"))
  }
  x
}
iris %>% mutate(across(contains("Sepal"), 
                       ~ {sym <- cur_column(); foo_warn(.x, sym)})) %>% head
#> Warning in foo_warn(.x, sym): Sepal.Length has an implausible value
#> Warning in foo_warn(.x, sym): Sepal.Width has an implausible value
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
#> 6          5.4         3.9          1.7         0.4  setosa
```

<sup>Created on 2020-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Unfortunately you can't expect `substitute(deparse())` to work in general. Probably the best way to make this work is for dplyr to automatically add the column name to the warning, like it already does for errors.
