### ISSUE TITLE
rowSums not working on grouped data

### ISSUE THREAD

**Issue by nschwamm** [tidyverse/dplyr#5314]
If you create a tibble, and try to do rowSums on data that is grouped by row. This works even if the data is grouped by a unique ID value or using rowwise. 

For example, this code fails:
```r
tibble(
  a=c(1,2,3,4,5),
  b=c(6,7,4,2,1),
  c=c("A","B","C","D","E")
) %>%
  group_by(c) %>%
  mutate(
    total = rowSums(select(.,-c))
  )
```

While this doesn't: 
```r
tibble(
  a=c(1,2,3,4,5),
  b=c(6,7,4,2,1),
  c=c("A","B","C","D","E")
) %>%
  mutate(
    total = rowSums(select(.,-c))
  )
```

**Comment by hadley** [comment]
I'd recommend using `c_across()` instead:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  a = c(1, 2, 3, 4, 5),
  b = c(6, 7, 4, 2, 1),
  c = c("A", "B", "C", "D", "D")
)

df %>%
  rowwise() %>%
  mutate(
    total = sum(c_across(-c))
  )
#> # A tibble: 5 x 4
#> # Rowwise: 
#>       a     b c     total
#>   <dbl> <dbl> <chr> <dbl>
#> 1     1     6 A         7
#> 2     2     7 B         9
#> 3     3     4 C         7
#> 4     4     2 D         6
#> 5     5     1 D         6
```

<sup>Created on 2020-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

See https://dplyr.tidyverse.org/articles/rowwise.html for details.

**Comment by nschwamm** [comment]
Thanks for the suggestion - it did indeed work.

Quick follow up question - although the example was a bit contrived, imagine that the df was the result of an upstream equation was grouped. Is there a way to have rowwise override the grouping without an explicit call of ungroup(). In the example below, ungroup is uncommented and the code fails if it is commented out. I can deal with the grouping in an earlier function, but I was unsure if there was a better implementation without doing that.

```r
df <- tibble(
  a = c(1, 2, 3, 4, 5),
  b = c(6, 7, 4, 2, 1),
  c = c("A", "B", "C", "D", "D")
) %>%
  group_by(c)

df %>%
  ungroup() %>%
  rowwise() %>%
  mutate(
    total = sum(c_across(-c))
  )
```

**Comment by hadley** [comment]
You can a more flexible column selection specification:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  a = c(1, 2, 3, 4, 5),
  b = c(6, 7, 4, 2, 1),
  c = c("A", "B", "C", "D", "D")
) %>%
  group_by(c)

df %>%
  rowwise() %>%
  mutate(
    total = sum(c_across(where(is.numeric)))
  )
#> # A tibble: 5 x 4
#> # Rowwise:  c
#>       a     b c     total
#>   <dbl> <dbl> <chr> <dbl>
#> 1     1     6 A         7
#> 2     2     7 B         9
#> 3     3     4 C         7
#> 4     4     2 D         6
#> 5     5     1 D         6
```

<sup>Created on 2020-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by prabakar-tigeranalytics** [comment]
In the same example and the solution above, is it possible to get back the group after the rowwise() operation without calling the group_by() function again?
