### ISSUE TITLE
Replacing group_by_at(NULL) using across

### ISSUE THREAD

**Issue by danilinares** [tidyverse/dplyr#5316]
([I posted it  also to stackoverflow](https://stackoverflow.com/questions/62277996/replacing-group-by-atnull-using-across?noredirect=1#comment110151810_62277996))

Before, I used `group_by_at` to group by a vector of strings or by NULL:
```r
library(tidyverse)

grouping_1 <- c("cyl", "vs")
grouping_2 <- NULL

mtcars %>% group_by_at(grouping_1) 
mtcars %>% group_by_at(grouping_2) 
```
The help of `group_by_at` indicates that the function is superseded and that `across` should be used instead. But, grouping by NULL gives an error

```r
mtcars %>% group_by(across(grouping_1)) # this works
mtcars %>% group_by(across(grouping_2)) # this gives an error
```

For me, `group_by_at` used in the way described has been useful because in my functions I can use the same code without checking every time whether the grouping argument is empty (NULL) or not.

**Comment by lionel-** [comment]
You should wrap the vector in `all_of()`, like this:

```r
mtcars %>% select(all_of(grouping_2))
#> data frame with 0 columns and 32 rows
```

However I see that `across()` doesn't support `NULL` in the same way:

```r
mtcars %>% group_by(across(all_of(grouping_2)))
#> Error: `vars` must be a character vector.
```

**Comment by hadley** [comment]
I think we should probably make `across(NULL, ...)` a no-op.
