### ISSUE TITLE
Count when n exists and wt = 1

### ISSUE THREAD

**Issue by luispfonseca** [tidyverse/dplyr#5324]
The reprex describes some behaviour of `count` when n already exists that seems unclear to me.

Version: dplyr_1.0.0

``` r
suppressMessages(library(dplyr))

# Let's say I want to count how many 
# distinct combinations of gear & am
# exist for each value of gear

# a cleaner way than what I'm about 
# to do would be to do the following
# This gets my desired result
mtcars %>% 
  distinct(am, gear) %>% 
  count(gear)
#>   gear n
#> 1    3 1
#> 2    4 2
#> 3    5 1

# But I want to clarify something about count

# This step gets me half way, 
# with the unneeded n variable
# which will cause some chaos
mtcars %>% 
  count(am, gear)
#>   am gear  n
#> 1  0    3 15
#> 2  0    4  4
#> 3  1    4  8
#> 4  1    5  5

# If I just count gear now, 
# I get by default the wt = n
mtcars %>% 
  count(am, gear) %>% 
  count(gear)
#> Using `n` as weighting variable
#> ℹ Quiet this message with `wt = n` or count rows with `wt = 1`
#>   gear  n
#> 1    3 15
#> 2    4 12
#> 3    5  5
# This is just the equivalent 
# of doing count(mtcars, gear)

# However, the useful warning message 
# tells me I can count rows with wt = 1

# So, if I do that..
mtcars %>% 
  count(am, gear) %>% 
  count(gear, wt = 1)
#>   gear n
#> 1    3 1
#> 2    4 1
#> 3    5 1

# Why don't I get the value of 2 for gear == 4?
```

<sup>Created on 2020-06-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by s-pike** [comment]
Just found this too. Easy to see with:
`starwars %>% count(species, homeworld)`
adding in a spurious column called "n" should give the same result, but it doesn't
`starwars %>% mutate(n = 10) %>% count(species, homeworld)`
`starwars %>% mutate(n = 10) %>% count(species, homeworld, wt = 1)`

to make it work you can do:
`starwars %>% mutate(n = 10) %>% count(species, homeworld, wt = n())`
but that's not what the warning message tells you!

It looks like the `wt` defaults to `n` in count when it's present (I guess that could be intended behaviour, but would be surprising to me given that `tally` exists). But `wt = 1` giving `1` for every `n` must be a bug.

**Comment by kuriwaki** [comment]
I just got misguided on this too. Seems like only the console message just needs to be updated from "1" to "n()". :
https://github.com/tidyverse/dplyr/blob/fd08fe92621eba2206df305f17d635fb888c3172/R/count-tally.R#L149

**Comment by hadley** [comment]
Ooops, sorry about this — I forgot to update the hint when I updated the code.
