### ISSUE TITLE
unexpected column order when moving multiple columns with relocate and .after=last_col()

### ISSUE THREAD

**Issue by thackl** [tidyverse/dplyr#5328]
When selecting multiple columns with `relocate`, I would expect them to end up at the new location in the order I specified them in. This usually works, but it behaves unexpectedly in one particular case: when using (`after=last_col()`) and the last column is part of the columns to be relocated.

```r
df <- tibble(x=1, y=2, z=3)
relocate(df, y, z, .after=x) # x, y, z
relocate(df, z, y, .after=x) # x, z, y
relocate(df, y, z, .after=last_col()) # x, z, y << unexpected
relocate(df, z, y, .after=last_col()) # x, z, y
```
I might be off with my expectation here, but at least going by semantics ("move a bunch of columns to the end"), I feel like this specification should work...

**Comment by hadley** [comment]
You’re asking to move z after itself — I don’t really see what we could do better here.

**Comment by thackl** [comment]
Good chance this should just stay as-is. The behavior is technically correct, and this seems not like a too important issue.

The reason why it might be worth thinking about it nevertheless:
A major use case of relocate is to move columns to the front - super easy `relocate(df,z,x,y)`... And in this case, it does not matter whether or not the first column is part of the selection. You always get the specified order.
The opposite operation - move a bunch of columns to the back - to me seems similarly useful. I'm just asking if there is a good way to get the same behavior as for moving to the front, also if the last column is part of the selection. My intuition would be to use `relocate(df, y,z,x .after=last_col())`, but this leads to the issue at hand.

Ideas that might help: 
- relocate warns if the "anchor" column is also part of the selection -- this generally seems like it could cause problems
- last_col() returns the last column not marked for relocation -- ideal for this particular case, but not sure if robust/technically feasible


FYI, this might make more sense in examples with more than 3 columns:
```
tibble(a=1,x=1,b=1,z=1,y=1) %>%
 relocate(x,y,z,.after=last_col())
# A tibble: 1 x 5
      a     b     y     x     z
```
