### ISSUE TITLE
copy_to a MySQL db with RMySQL now yields an error: unused argument (immediate = TRUE)

### ISSUE THREAD

**Issue by ericemc3** [tidyverse/dplyr#5329]
rerunning a script that was working fine 1 month ago,
connection opened with drv = MySQL() (RMySQL)

```r
data <-  tribble(
  ~lib, ~x1, ~x2,
  "xxx", 2, 3,
  "yyy",  1,  1,
  "zzzz", 4,  1,
)
copy_to( DB, data, overwrite=TRUE)

# Error in .local(conn, statement, ...) : 
#  unused argument (immediate = TRUE)
```

**Comment by hadley** [comment]
This is a really a dbplyr issue, but switching to RMariaDB instead of RMySQL should fix the issue.

**Comment by ericemc3** [comment]
RMariaDB is much slower than RMySQL (still pending issue with LOAD DATA INFILE not supported within RMariaDB), which makes it unusable currently with real life tables...

RMySQL is fast, which is why it is still widely used

**Comment by hadley** [comment]
@krlmlr can you please look into

**Comment by ericemc3** [comment]
Hello, as I don't see much activity about this (here or on https://github.com/r-dbi/RMariaDB), maybe vacation time,

at the risk of sounding rude, I insist here
and I plead for efficient real-life DB support (bulk loading/LOAD DATA INFILE), stable (non breaking), UTF8 compatible, especially with MySQL.

I'm fighting hard within my company and also widely in France within our national statistics institute to promote R as a credible tool for database interaction, and it's really getting harder and harder, especially now that RMySQL is broken.

I see you're playing/experimenting with new features: review generated SQL, rows_upsert... which are really cool, and I love them. 

But I really don't understand why such fundamental and strategic things as strong and reliable database support, UTF8, performance, does not seem to be considered seriously.

**Comment by krlmlr** [comment]
Missed that.

Let's discuss in the RMariaDB repo, we have open issues there. If you're seeing UTF-8 problems, please file an issue or comment to an existing open issue.

**Comment by GoldbergData** [comment]
Any update on this? It happens for copy_nycflights13 as well, which calls copy_to().

**Comment by pachadotdev** [comment]
as a reference, I was trying to update databases.pacha.dev and I ended with this

```r
# SQL Server 2017 + odbc
# > tictoc::tic()
# > copy_to(con, sj_all_revenue_large_f, temporary = F)
# > tictoc::toc()
# 57.695 sec elapsed

# MySQL 5.7 + RMySQL
# > tictoc::tic()
# > copy_to(con, sj_all_revenue_large_f, temporary = F)
# > tictoc::toc()
# 40.755 sec elapsed

# MySQL 5.7 + RMariaDB
# cancelled after 5 minutes

# MySQL 5.7 + odbc
# cancelled after 5 minutes
```

this is how I installed the ODBC driver to test
```bash
cd ~/Downloads
tar xvf mysql-connector-odbc-8.0.27-linux-glibc2.12-x86-64bit.tar.gz
cd mysql-connector-odbc-8.0.27-linux-glibc2.12-x86-64bit 
sudo cp -r bin/* /usr/local/bin/
sudo cp -r lib/* /usr/local/lib/

sudo myodbc-installer -a -d -n "MySQL ODBC 8.0 Driver" -t "Driver=/usr/local/lib/libmyodbc8w.so"
sudo myodbc-installer -a -d -n "MySQL ODBC 8.0" -t "Driver=/usr/local/lib/libmyodbc8a.so"

cat /etc/odbcinst.ini
```

**Comment by kongdd** [comment]
I faced with the same issue. My data is only 10,000 rows. `RMySQL` is bloody faster, meanwhile `RMariaDB` died.

**Comment by krlmlr** [comment]
Thanks. Can you please open a new issue and describe your specific problem?
