### ISSUE TITLE
Mutate_if breaks when column name is "i"

### ISSUE THREAD

**Issue by fproske** [tidyverse/dplyr#5330]
`mutate_if` is broken (the condition applies to all columns) when a column is named `i`:

``` r
dplyr::mutate_if(tibble::tibble(i = "a", j = 1), is.character, 
    tidyr::replace_na, replace = "")
#> # A tibble: 1 x 2
#>   i     j    
#>   <chr> <chr>
#> 1 a     1
```

<sup>Created on 2020-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

---

I noticed this for the first time with version 1.0

**Comment by hadley** [comment]
What exactly is the problem?

**Comment by fproske** [comment]
The second column is converted to character, even though it is not a character column. Maybe the example could be improved:

 ``` r
dplyr::mutate_if(tibble::tibble(i = c("a", "b"), j = c(1, NA)), 
    is.character, tidyr::replace_na, replace = "")
#> # A tibble: 2 x 2
#>   i     j    
#>   <chr> <chr>
#> 1 a     "1"  
#> 2 b     ""
```

<sup>Created on 2020-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fproske** [comment]
The mutate/across/where equivalent works well btw:
``` r
dplyr::mutate(tibble::tibble(i = c("a", "b"), j = c(1, NA)), 
    dplyr::across(where(is.character), tidyr::replace_na, replace = ""))
#> # A tibble: 2 x 2
#>   i         j
#>   <chr> <dbl>
#> 1 a         1
#> 2 b        NA
```

<sup>Created on 2020-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
