### ISSUE TITLE
Wrong grouping type output - dplyr 1.00

### ISSUE THREAD

**Issue by Sade154** [tidyverse/dplyr#5335]
---

Hi,

In the example below (dplyr 1.0.0), grouping with 3 variables (lets say V1, V2, V3) gives an output of a tibble with only two groups of variable (V1, V2), which is really unexpected. This behaviour could be risky if people chain group_by/summarise with mutate for example.

Thanks,
Kind regards,

```r
library(dplyr)

data <- structure(list(V1 = c(920650, 920650, 920650, 920650, 920650),
                      V2 = structure(c(15643, 15666, 15631, 15631, 15568), class = "Date"),
                      V3 = c("Vr", "Vr", "Vr", "Vr", "Ch")),
                 class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -5L))

data %>%
  group_by(V1, V2, V3) %>%
  summarise(N = n())

## `summarise()` regrouping output by 'V1', 'V2' (override with `.groups` argument)

## A tibble: 4 x 4
## Groups:   V1, V2 [4]
#V1 V2         V3        N
#<dbl> <date>     <chr> <int>
#1 920650 2012-08-16 Ch        1
#2 920650 2012-10-18 Vr        2
#3 920650 2012-10-30 Vr        1
#4 920650 2012-11-22 Vr        1

```

**Comment by lionel-** [comment]
This has always been the behaviour, but it is now made more explicit by a verbose message. We can't really change the default now because it would break a lot of existing code, so you'll need to supply `.groups` manually if you want a different behaviour.

**Comment by Sade154** [comment]
I undestand by why the grouping result is done with V1 V2 ? It would'nt make more sense to ungroup ?
