### ISSUE TITLE
filter() doesn't work if variable name matches column name?

### ISSUE THREAD

**Issue by jwhendy** [tidyverse/dplyr#5338]
I was recently surprised by this. In my real example I have a tibble with a `date` column and wanted to filter by a certain value. I found that using the variable `date` to store this value and filtering on `date == date` returned all the rows, so I dug in.

I don't *think* I see a mention of this limitation in the docs, but maybe I'm missing something obvious!

```r
df <- tibble(x=c(1, 2, 3), y=c(4, 5, 6))
x <- 2
x1 <- 2

df %>% filter(x==x)
# A tibble: 3 x 2
      x     y
  <dbl> <dbl>
1     1     4
2     2     5
3     3     6

df %>% filter(x==x1)
# A tibble: 1 x 2
      x     y
  <dbl> <dbl>
1     2     5
```

**Comment by hadley** [comment]
`x == x` is always going to be true; unfortunately `filter()` can't magically know that you meant `x_in_dataframe == x_in_environment`. You could resolve this ambiguity using pronouns like `filter(df, .data$x == .env$x)`, but generally it's easy to just use a different variable name.

**Comment by jwhendy** [comment]
I am returning to R from a long time spent in pandas and admit it didn't even occur to me that one might `filter()` on matches *between* columns. In other words, I suspected this variable would be supplied directly (`filter(x==2)`) or must be from the environment.

Thanks for the clarification.
