### ISSUE TITLE
Feature Request: Clarify error source with bind_rows()

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#5339]
When using `bind_rows()` with incompatible column types, the error message can indicate the error is with a column that doesn't exist.  In the example below, the error is indicated to occur with a difference between `..1$B` and `..3$B`, but `..1$B` doesn't exist on input.

It appears that under the surface, `bind_rows()` assigns the class of the first found column to all prior tables without those columns.  But then, the error message indicates that the problem happens with the imputed `NA` rather than the first observed column.

It would be preferable if the error indicated `Error: Can't combine `..2$B` <double> and `..3$B` <character>.` (Note that it now says "..2" instead of "..1".)

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
bind_rows(
  tibble(A=1),
  tibble(A=1, B=2),
  tibble(B="A")
)
#> Error: Can't combine `..1$B` <double> and `..3$B` <character>.
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Thanks, I agree it's not optimal. Transferred to https://github.com/r-lib/vctrs/issues/1156
