### ISSUE TITLE
Feature Request: Make bind_rows() gives more specific errors

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#5343]
When binding a long list of data.frames with many columns each, it would help if error messages gave information about both what tables were giving the error and what columns in the tables were causing the problems.

The error message below of:

```
Error: `x` must be a vector with type <double>.
Instead, it has type <double>.
```

does not indicate what the problem is under the surface.  A few different items here would help:

* Please make the errors with `bind_rows()` indicate which column has the error.  (That took a long time to track down because I had about 50 columns.)
* Please make errors with `bind_rows()` indicate which input tables are giving the error.  (That also took a long-ish time to track down because in addition to having about 50 columns, I was binding a list of 15 different data.frames.)
* ~~This appears to be an issue binding doubles with different attributes.  I couldn't make a reprex that didn't use `hms()` rapidly, but if `A2 <- 1`, then there was no error.  I know that handling attributes can be a difficult question, but I don't think that the code I have below should cause an error (at least since currently `double` is coerced to a `hms` as is indicated by the warning).~~
    * As I was writing this issue, I realized that the error message is coming from `hms()`, so I will open that part over there.  But, the first two hold because the `bind_rows()` error message being more specific could have helped save significant troubleshooting time.

``` r
library(hms)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
A2 <- structure(1, label="Analysis Time", format.sas="TOD")
bind_rows(tibble(A=hms(seconds=1)), tibble(A=A2))
#> Warning: Coercion of <double> to <time> is deprecated and will be removed in a future version. Please use as_hms().
#> This warning is displayed once per session.
#> Error: `x` must be a vector with type <double>.
#> Instead, it has type <double>.
```

<sup>Created on 2020-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Thanks for these reports. The best place for reporting type issues is the vctrs package though. `bind_rows()` is a thin wrapper around `vctrs::vec_rbind()`.

**Comment by hadley** [comment]
This seems mostly like an hms problem to me. I'm not sure it's feasible to make `bind_rows()` display an informative error message for every possible failure mode. Unfortunately, we can't expect better error messages to be replace regular debugging tools.
