### ISSUE TITLE
https://dplyr.tidyverse.org/articles/programming.html

### ISSUE THREAD

**Issue by erinmkelley** [tidyverse/dplyr#5344]
Hello!

I thought the file on quo/enquo was super helpful but when I went back to the link it's now showing an entirely different help file.
https://dplyr.tidyverse.org/articles/programming.html

This link used to have the following examples (see below) and when you search for these examples in google it does bring you to this programming page. However, this page now doesn't take the reader through anything about quo/enquo/etc 

Any clarifications would be great- many thanks!! 

df <- tibble(
  g1 = c(1, 1, 2, 2, 2),
  g2 = c(1, 2, 1, 2, 1),
  a = sample(5),
  b = sample(5)
)

my_summarise <- function(df, group_var) {
  df %>%
    group_by(!!group_var) %>%
    summarise(a = mean(a))
}

my_summarise(df, quo(g1))

##

my_summarise <- function(df, group_var) {
  group_var <- enquo(group_var)
  print(group_var)
  
  df %>%
    group_by(!! group_var) %>%
    summarise(a = mean(a))
}

my_summarise(df, g1)

##

my_mutate <- function(df, expr) {
  expr <- enquo(expr)
  mean_name <- paste0("mean_", quo_name(expr))
  sum_name <- paste0("sum_", quo_name(expr))
  
  mutate(df,
         !! mean_name := mean(!! expr),
         !! sum_name := sum(!! expr)
  )
}

my_mutate(df, a)

**Comment by erinmkelley** [comment]
By clarification I mean is there a way to access that older help file?

**Comment by hadley** [comment]
No, because we no longer recommend that style. Do you have a specific question about it?

**Comment by erinmkelley** [comment]
Thanks for the quick reply! I had spent a couple of sessions teaching that code to my research team and had referenced the file as a helpful guide - which they highlighted today they could no longer access. But I will let them know that it's deprecated. May still be useful to add a note somewhere in this new guide that those styles are no longer recommended and why (since the switch must have been less than a month old). Thanks again!!

**Comment by lionel-** [comment]
You can find the old version (unrendered) at https://github.com/tidyverse/dplyr/blob/v0.8.5/vignettes/programming.Rmd

Hopefully you will find the new style easier to learn and teach :)

**Comment by erinmkelley** [comment]
Thanks so much Lionel - really appreciate it!! Will definitely change up my notes for next semester :)
