### ISSUE TITLE
Odd behaviour with ifelse() and grouped mutate()

### ISSUE THREAD

**Issue by siddharthprabhu** [tidyverse/dplyr#5345]
Continuing a discussion from [this RStudio Community thread](https://community.rstudio.com/t/mutate-multiple-columns-if-grouping-variable-has-all-observations-missing/70206/4). The OP was attempting to modify rows within each group if all the rows for that group were `NA` (leave them as-is otherwise).

Seemed like a pretty straightforward application of `ifelse()`. But this attempt generates an incorrect result for group C (values should be returned as-is since it contains only 1 `NA`).

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(num = c(NA, NA, 1, 1, NA, 1), 
             grp = c("A", "A", "B", "B", "C", "C"))

df %>% 
  group_by(grp) %>% 
  mutate(num = ifelse(sum(is.na(num)) == n(), 999, num))
#> # A tibble: 6 x 2
#> # Groups:   grp [3]
#>     num grp  
#>   <dbl> <chr>
#> 1   999 A    
#> 2   999 A    
#> 3     1 B    
#> 4     1 B    
#> 5    NA C    
#> 6    NA C
```

But breaking down the `mutate()` call into two sub-steps works.

``` r
df %>% 
  group_by(grp) %>% 
  mutate(lgl_test = sum(is.na(num)) == n(),
         num = ifelse(lgl_test == TRUE, 999, num))
#> # A tibble: 6 x 3
#> # Groups:   grp [3]
#>     num grp   lgl_test
#>   <dbl> <chr> <lgl>   
#> 1   999 A     TRUE    
#> 2   999 A     TRUE    
#> 3     1 B     FALSE   
#> 4     1 B     FALSE   
#> 5    NA C     FALSE   
#> 6     1 C     FALSE
```

However, `dplyr::if_else()` hints at what's going wrong. It seems that the comparison isn't performed element-wise because `num` is of length 2 (the group size).

``` r
df %>% 
  group_by(grp) %>% 
  mutate(num = if_else(sum(is.na(num)) == n(), 999, num))
#> Error: Problem with `mutate()` input `num`.
#> x `false` must be length 1 (length of `condition`), not 2.
#> i Input `num` is `if_else(sum(is.na(num)) == n(), 999, num)`.
#> i The error occured in group 1: grp = "A".
```

Breaking down into two steps works as with `ifelse()`.

``` r
df %>% 
  group_by(grp) %>% 
  mutate(lgl_test = sum(is.na(num)) == n(),
         num = if_else(lgl_test == TRUE, 999, num))
#> # A tibble: 6 x 3
#> # Groups:   grp [3]
#>     num grp   lgl_test
#>   <dbl> <chr> <lgl>   
#> 1   999 A     TRUE    
#> 2   999 A     TRUE    
#> 3     1 B     FALSE   
#> 4     1 B     FALSE   
#> 5    NA C     FALSE   
#> 6     1 C     FALSE
```

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

My question is whether this is the expected behaviour when performing grouped mutates? There are some ugly workarounds offered in that thread to do it in a single statement but intuitively it seems like the first attempt listed above should work.

**Note:** This isn't specific to dplyr 1.0.0. I tested it with 0.8.5 and it functions the same way.

**Comment by lionel-** [comment]
IIUC you are right that this should work, and a simple fix would be to call `vctrs::vec_recycle_common()` on the condition and the two branches.

**Comment by hadley** [comment]
We've already fixed it in `funs::if_else()` which will replace dplyr `if_else` in the not too distant future:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  num = c(NA, NA, 1, 1, NA, 1),
  grp = c("A", "A", "B", "B", "C", "C")
)

df %>%
  group_by(grp) %>%
  mutate(
    lgl_test = sum(is.na(num)) == n(),
    num = funs::if_else(lgl_test, 999, num)
  )
#> # A tibble: 6 x 3
#> # Groups:   grp [3]
#>     num grp   lgl_test
#>   <dbl> <chr> <lgl>   
#> 1   999 A     TRUE    
#> 2   999 A     TRUE    
#> 3     1 B     FALSE   
#> 4     1 B     FALSE   
#> 5    NA C     FALSE   
#> 6     1 C     FALSE
```

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by siddharthprabhu** [comment]
@hadley Okay, that's good to know. Would you mind showing the output of `funs::if_else()` without creating the `lgl_test` helper column? As demonstrated in my post, `base::ifelse()` and `dplyr::if_else()` also work if we use this two-step approach.

**Comment by hadley** [comment]
``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  num = c(NA, NA, 1, 1, NA, 1),
  grp = c("A", "A", "B", "B", "C", "C")
)

df %>%
  group_by(grp) %>%
  mutate(
    lgl_test = funs::if_else(sum(is.na(num)) == n(), 999, num)
  )
#> # A tibble: 6 x 3
#> # Groups:   grp [3]
#>     num grp   lgl_test
#>   <dbl> <chr>    <dbl>
#> 1    NA A          999
#> 2    NA A          999
#> 3     1 B            1
#> 4     1 B            1
#> 5    NA C           NA
#> 6     1 C            1
```

<sup>Created on 2020-06-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
