### ISSUE TITLE
Possible dplyr cheatsheet error for lag and lead functions

### ISSUE THREAD

**Issue by cpad0112** [tidyverse/dplyr#5346]
I downloaded dplyr cheat-sheet from https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf.  In **vectorized function** section, I see following:

```
OFFSETS
dplyr::lag() - Offset elements by 1
dplyr::lead() - Offset elements by -1
```

Should it not be as following?

```
OFFSETS
dplyr::lag() - Offset elements by -1
dplyr::lead() - Offset elements by 1
```

I am sorry if cheat-sheet is correct.

**Comment by romainfrancois** [comment]
Looks ok to me, in any case this issue would belong to the `rstudio/cheatsheets` repo, closing here. With the arrival of 1.0.0, the cheatsheet might entirely be remade.
