### ISSUE TITLE
Clarification in summarise() Documentation

### ISSUE THREAD

**Issue by jam1015** [tidyverse/dplyr#5350]
This isn't a problem with the code but rather a request for clarification in in the documentation for summarise() (https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-summarise/) I think is ambiguous.  For the ```.groups``` argument it says

"When .groups is not specified, you either get "drop_last" _when all the results are size 1_, or "keep" if the size varies."

My question is what is meant by "size 1" here? Does it mean that the summary returns one row as was the case for summaries before dplyr 1.0? Does mean the summary contains basic types like strings or numeric values, or list-cols where all the lists are of length one? Does it mean the summary only returns one column?  I can probably play around with this and figure it out but I think that these ambiguities should be covered in the main documentation, unless there is something that makes the meaning more clear that I am missing.

**Comment by romainfrancois** [comment]
This is about the number of rows: 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(a = c(1, 1, 2, 2), b = c(3, 4, 3, 4), x = 1:4) %>% 
  group_by(a, b)

# size 1, one "row"
summarise(df, y = 42)
#> `summarise()` regrouping output by 'a' (override with `.groups` argument)
#> # A tibble: 4 x 3
#> # Groups:   a [2]
#>       a     b     y
#>   <dbl> <dbl> <dbl>
#> 1     1     3    42
#> 2     1     4    42
#> 3     2     3    42
#> 4     2     4    42
summarise(df, y = 42, .groups = "drop_last")
#> # A tibble: 4 x 3
#> # Groups:   a [2]
#>       a     b     y
#>   <dbl> <dbl> <dbl>
#> 1     1     3    42
#> 2     1     4    42
#> 3     2     3    42
#> 4     2     4    42

# size > 1
summarise(df, y = c(43, 44))
#> `summarise()` regrouping output by 'a', 'b' (override with `.groups` argument)
#> # A tibble: 8 x 3
#> # Groups:   a, b [4]
#>       a     b     y
#>   <dbl> <dbl> <dbl>
#> 1     1     3    43
#> 2     1     3    44
#> 3     1     4    43
#> 4     1     4    44
#> 5     2     3    43
#> 6     2     3    44
#> 7     2     4    43
#> 8     2     4    44
summarise(df, y = c(43, 44), .groups = "keep")
#> # A tibble: 8 x 3
#> # Groups:   a, b [4]
#>       a     b     y
#>   <dbl> <dbl> <dbl>
#> 1     1     3    43
#> 2     1     3    44
#> 3     1     4    43
#> 4     1     4    44
#> 5     2     3    43
#> 6     2     3    44
#> 7     2     4    43
#> 8     2     4    44
```

<sup>Created on 2020-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
