### ISSUE TITLE
`all_equal()` lacks a `name_repair` parameter

### ISSUE THREAD

**Issue by salim-b** [tidyverse/dplyr#5352]
Since dplyr 1.0, I get messages about "new names" when comparing dataframes with columns having non-universal names:

```r
mtcars2 <- dplyr::rename(mtcars, "m p g" = mpg)

dplyr::all_equal(target = mtcars2,
                 current = mtcars2)
#> New names:
#> * `m p g` -> m.p.g
#> New names:
#> * `m p g` -> m.p.g
#> [1] TRUE
```
<sup>Created on 2020-06-23 by the reprex package (v0.3.0)</sup>

I'd like to avoid these name conversion but `all_equal()` doesn't know a `name_repair` (or `.name_repair`) argument as e.g. `tibble::as_tibble()` does.

Internally, `dplyr::all_equal()` calls the unexported `dplyr:::equal_data_frame()` which calls `dplyr::as_tibble()` with a hard-coded `.name_repair = "universal"`.

I guess this argument could just be exposed all the way through `all_equal()` which would allow me to avoid these name conversions, right? Any objections? I'd be happy to submit a PR for this if that is approved.

**Comment by hadley** [comment]
I don't think we plan to make any changes to `all_equal()` because we don't think you should be using it anymore. What are you trying to do with it?

**Comment by salim-b** [comment]
> What are you trying to do with it?

I'm using it in a custom function which compares two dataframes/tibbles (optionally with `ignore_col_order`/`ignore_row_order` -> thus I like `dplyr::all_equal()`) and opens the [daff comparison](https://stackoverflow.com/a/45890805/7196903) if they're different.

> I don't think we plan to make any changes to all_equal() because we don't think you should be using it anymore.

Well, is the decision to deprecate `all_equal()` final? If so, I'm gonna incorporate some code from the underlying `dplyr:::equal_data_frame()` into my function, I guess.

**Comment by hadley** [comment]
Yes, I think you're better off implementing yourself from first principles, borrowing code from dplyr as needed.
