### ISSUE TITLE
pull() equivalent to accept expressions

### ISSUE THREAD

**Issue by Freguglia** [tidyverse/dplyr#5355]
`pull()` only accepts a a column name/position as argument, what makes it equivalent to `$` or `'[['()`, except for quotation.
Most of the times I use `pull()` after a `transmute()` or `mutate()` call. In fact, even in `pull()`'s documentation, the example does the same:

```r
df %>%
  mutate(z = x * y) %>%
  pull()
}
```

It cannot accept an expression such as `pull(x*z)` because it would break the current implementation, e.g., `pull(-x)` would be ambiguous. Would it be interesting to have a single function equivalent to a `mutate() %>% pull()` chain?

**Comment by lionel-** [comment]
It would make the API more complex and would not have much advantage over `df %>% transmute(x * z) %>% pull()`.

In retrospect, `pull()` should have mutate semantics and you'd use a helper to retrieve a column by position. `pull(var)` would still work (for the same reason that `mutate(var)` works), and you could do `pull(loc(-1))`.

**Comment by hadley** [comment]
Unfortunately I don't think it's worth the work needed for such a specialised use case.
