### ISSUE TITLE
Across() unable to handle additional arguments for mean

### ISSUE THREAD

**Issue by rjogallagher17** [tidyverse/dplyr#5357]
This example attempts to remove NA from the mean calculation across a range of columns. When mean is supplied alone without parentheses, this code chunk functions correctly, however, adding the na.rm parameter to the mean function creates the error observed in this issue. 
---

``` r
library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

test = data.frame(group = c(1,2,2,3,1),
                  name = c("a","b","c","d","e"),
                  a = c(1,2,3,4,5),
                  b = c(1,2,NA,4,5), 
                  c = c(NA,2,3,NA,5))

test1 = test %>% group_by(group) %>% summarize(across(.cols = a:c,mean(na.rm = T)))
#> Error: Problem with `summarise()` input `..1`.
#> x argument "x" is missing, with no default
#> i Input `..1` is `across(.cols = a:c, mean(na.rm = T))`.
#> i The error occured in group 1: group = 1.
```

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
`across()` takes a function, just like `base::lapply()` or `purrr::map()`.

You can create a function and pass it to `across()`:

```r
across(a:c, ~ mean(.x, na.rm = TRUE))

# Equivalent to:
across(a:c, function(.x) mean(.x, na.rm = TRUE))
```

Or you can pass the function and its arguments separately:

```r
across(a:c, mean, na.rm = TRUE)
```

**Comment by rjogallagher17** [comment]
Worked perfectly. Thank you for explaining. I hadn't understood that from the documentation.
