### ISSUE TITLE
Using cur_column() within the .data pronoun

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidyverse/dplyr#5360]
Why does the following produce an error, where if I try to evaluate the same expression from within the browser it works just fine?

``` r
suppressPackageStartupMessages(library(dplyr))
#> Warning: package 'dplyr' was built under R version 3.6.3
test <- tibble(a = 1:5, b = 1:5)

# this errors
test %>% mutate(across(1:2, ~{.data[[cur_column()]]}))
#> Error: `cur_column()` must only be used inside `across()`.

# can call .data[[cur_column()]] from within the browser however
# test %>% mutate(across(1:2, ~{browser()}))
```

**Comment by lionel-** [comment]
Because `.data[[` is like `!!`, it evaluates very early to avoid any issue of data masking. This way `.data[[x]]` always works, even when there is an `x` column in the data frame.

If you run it inside a browser, you've passed the quasiquotation point so you don't have this issue.

**Comment by lionel-** [comment]
Note that there is no need to subset `.data` in this way inside `across()`, you should use the function argument to get the column. In this case, `.x` since you're using a purrr lambda.

**Comment by TylerGrantSmith** [comment]
Thanks @lionel- , very helpful!
