### ISSUE TITLE
Undocumented breaking change in 1.0.0 release notes

### ISSUE THREAD

**Issue by bersbersbers** [tidyverse/dplyr#5368]
Some code that runs in 0.8.5 (useful or not) throws an error in 1.0.0. See https://stackoverflow.com/q/62638400/ and https://github.com/lujunyan1118/DrugScreenExplorer/issues/1 for more information.

---
```r
library(dplyr)
x <- data.frame(1)
x %>% ungroup(x)
```

This change should at least be documented as breaking.

**Comment by hadley** [comment]
It's a genuinely useful error message — I think you meant `x %>% ungroup()`

**Comment by bersbersbers** [comment]
> It's a genuinely useful error message

Well, if that is your opinion, I shall agree. As a Python guy, however, who did not even write the above code, it took me almost a day to figure that `%>%` is from `dplyr` (how would you know from reading this code?), that `ungroup` is from `dplyr` (similar), what the `%>%` operator does,  what an ellipsis is (no other language I know uses this concept under this name), why ungroup(x, y) is not allowed despite the `dplyr` manual stating that it takes further arguments, etc. etc. Now, all this comes down to R being amazingly less beginner-friendly than Python is, and I don't blame this on `dplyr` at all. *But*, since the code *does* run fine in 0.8.5, and since the 1.0.0 release notes do *not* mention `ungroup()` in the section "breaking changes", I did actually not even go through all the steps above at first because I excluded `ungroup()` as the potential source of the error. That is the part you should fix, in your release notes. It's code that was working before, and your changes to `dplyr` broke the code. For me, it doesn't matter if the code incorrect and working only by accident (again, I did not write it): it was working, and your change made it break, so that's a breaking change for me. I don't say it's not a useful error message: but the release notes section is not titled "breaking changes without a useful error message that might help you figure out what's wrong in less than a day", it's "breaking changes".

> I think you meant `x %>% ungroup()`

Yes, I did. Well, the maintainer of the code I am using is. I guess. See https://github.com/lujunyan1118/DrugScreenExplorer/issues/1

**Comment by hadley** [comment]
I take your point that the error message could be better, so I've filed an issue upstream: https://github.com/r-lib/ellipsis/issues/36

FWIW, we generally don't consider bug fixes to be breaking changes in the sense we use the term in our news files (which is really shorthand for API changes).

**Comment by bersbersbers** [comment]
> I take your point that the error message could be better, so I've filed an issue upstream: [r-lib/ellipsis#36](https://github.com/r-lib/ellipsis/issues/36)

Great, thanks!

> FWIW, we generally don't consider bug fixes to be breaking changes in the sense we use the term in our news files (which is really shorthand for API changes).

Alright, understood. Thanks nonetheless :)

**Comment by bersbersbers** [comment]
> FWIW, we generally don't consider bug fixes to be breaking changes in the sense we use the term in our news files (which is really shorthand for API changes).

Just to note that I am not crazy ;) other projects do handle this differently, compare Google's TensorFlow:

![image](https://user-images.githubusercontent.com/12128514/87011160-d8501100-c1c7-11ea-9ebb-edee0944054f.png)

https://github.com/tensorflow/tensorflow/releases/tag/v2.3.0-rc1
