### ISSUE TITLE
distinct() error with sticky geom column

### ISSUE THREAD

**Issue by baderstine** [tidyverse/dplyr#5378]
When using `distinct()` with `sf` objects, the sticky `geom` column can cause unexpected errors because it is not ignored:

```r
library(maps)
library(sf)
library(dplyr)

county_sf = st_as_sf(maps::map(database = "county", plot=FALSE, fill=TRUE))

county_sf %>% distinct(vars(ID))
```

>> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at -104.96586608886719 40.0096435546875.

I would expect this to return all rows that have distinct IDs, ignoring 'geom' and not failing with an error.

**Comment by hadley** [comment]
I think this is a problem with the `distinct.sf` method, so I'd recommend asking about it over in sf.

**Comment by baderstine** [comment]
Thanks.  Created issue at sf:  https://github.com/r-spatial/sf/issues/1477
