### ISSUE TITLE
Possible bug in rowwise()?

### ISSUE THREAD

**Issue by fmmattioni** [tidyverse/dplyr#5388]
Hi, I am not sure I am missing something, of it this is really a bug. I have noticed that `rowwise()` is not working well with `ggplot2`. For example, if I have three rows, and I map columns of this row to my plot function, I am retrieving only the last plot in all the rows.

<details><summary>reprex with possible bug</summary>

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

plot_this <- function(.data, x, y, label) {
  ggplot() +
    geom_point(data = .data, aes(mpg, hp)) +
    geom_point(aes(x = {{ x }}, y = {{ y }}), color = "red", size = 4) +
    geom_text(aes(x = {{ x }}, y = {{ y }}, label = {{ label }}), color = "white", fontface = "bold")
}

df <- tibble(
  data = list(mtcars),
  x = c(16, 18, 19),
  y = c(80, 90, 100)
) %>% 
  tibble::rowid_to_column()

df
#> # A tibble: 3 x 4
#>   rowid data                    x     y
#>   <int> <list>              <dbl> <dbl>
#> 1     1 <df[,11] [32 × 11]>    16    80
#> 2     2 <df[,11] [32 × 11]>    18    90
#> 3     3 <df[,11] [32 × 11]>    19   100

df %>% 
  rowwise() %>% 
  mutate(
    plot = plot_this(data, x, y, rowid) %>% list()
  ) %>% 
  ungroup() %>% 
  pull(plot)
#> [[1]]
```

![](https://i.imgur.com/tj0ItW6.png)

    #> 
    #> [[2]]

![](https://i.imgur.com/eARv3Kb.png)

    #> 
    #> [[3]]

![](https://i.imgur.com/sldIRI6.png)

<sup>Created on 2020-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

<details><summary>reprex using purrr (working)</summary>

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

plot_this <- function(.data, x, y, label) {
  ggplot() +
    geom_point(data = .data, aes(mpg, hp)) +
    geom_point(aes(x = {{ x }}, y = {{ y }}), color = "red", size = 4) +
    geom_text(aes(x = {{ x }}, y = {{ y }}, label = {{ label }}), color = "white", fontface = "bold")
}

df <- tibble(
  data = list(mtcars),
  x = c(16, 18, 19),
  y = c(80, 90, 100)
) %>% 
  tibble::rowid_to_column()

df %>% 
  mutate(
    plot = purrr::pmap(
      .l = list(data, x, y, rowid),
      .f = ~ plot_this(.data = ..1, x = ..2, y = ..3, label = ..4)
    )
  ) %>% 
  pull(plot)
#> [[1]]
```

![](https://i.imgur.com/K0ZLLTG.png)

    #> 
    #> [[2]]

![](https://i.imgur.com/U7Y1vo4.png)

    #> 
    #> [[3]]

![](https://i.imgur.com/AHN7xvc.png)

<sup>Created on 2020-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

Thank you in advance!

**Comment by romainfrancois** [comment]
What's happening is that `rowid` is never touched during the `mutate()` call, see e.g. `.keep = "unused"` : 

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

plot_this <- function(.data, x, y, label) {
  ggplot() +
    geom_point(data = .data, aes(mpg, hp)) +
    geom_point(aes(x = {{ x }}, y = {{ y }}), color = "red", size = 4) +
    geom_text(aes(x = {{ x }}, y = {{ y }}, label = {{ label }}), color = "white", fontface = "bold")
}

df <- tibble(
  data = list(mtcars),
  x = c(16, 18, 19),
  y = c(80, 90, 100)
) %>% 
  tibble::rowid_to_column()
df
#> # A tibble: 3 x 4
#>   rowid data                    x     y
#>   <int> <list>              <dbl> <dbl>
#> 1     1 <df[,11] [32 × 11]>    16    80
#> 2     2 <df[,11] [32 × 11]>    18    90
#> 3     3 <df[,11] [32 × 11]>    19   100
df %>% 
  rowwise() %>% 
  mutate(
    plot = plot_this(data, x, y, rowid) %>% list(), 
    .keep = "unused"
  )
#> # A tibble: 3 x 4
#> # Rowwise: 
#>   rowid     x     y plot  
#>   <int> <dbl> <dbl> <list>
#> 1     1    16    80 <gg>  
#> 2     2    18    90 <gg>  
#> 3     3    19   100 <gg>
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Only later when the plot is printed, the symbol `rowid` is resolved, the promise triggered, and by that time the group is 3. I'm not sure there is something we can do about this, e.g. if you `force()` label before going to `ggplot2` it goes away: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

plot_this <- function(.data, x, y, label) {
  force(label)
  ggplot() +
    geom_point(data = .data, aes(mpg, hp)) +
    geom_point(aes(x = {{ x }}, y = {{ y }}), color = "red", size = 4) +
    geom_text(aes(x = {{ x }}, y = {{ y }}, label = label), color = "white", fontface = "bold")
}

df <- tibble(
  data = list(mtcars),
  x = c(16, 18, 19),
  y = c(80, 90, 100)
) %>% 
  tibble::rowid_to_column()
df
#> # A tibble: 3 x 4
#>   rowid data                    x     y
#>   <int> <list>              <dbl> <dbl>
#> 1     1 <df[,11] [32 × 11]>    16    80
#> 2     2 <df[,11] [32 × 11]>    18    90
#> 3     3 <df[,11] [32 × 11]>    19   100
df %>% 
  rowwise() %>% 
  mutate(
    plot = plot_this(data, x, y, rowid) %>% list(), 
    .keep = "unused"
  )
#> # A tibble: 3 x 3
#> # Rowwise: 
#>       x     y plot  
#>   <dbl> <dbl> <list>
#> 1    16    80 <gg>  
#> 2    18    90 <gg>  
#> 3    19   100 <gg>
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by fmmattioni** [comment]
Thank you very much, @romainfrancois! Does it happen because `x` and `y` are inside `data` and `rowid` not? 

Perhaps my reprex is not the best example of good practices, because I wonder what to expect if there is a `rowid` column inside `data` too.

**Comment by fmmattioni** [comment]
Thank you very much, @romainfrancois!

I have just given it a try, and although the `label` is correct, `x` and `y` are not evaluated (they are all from the third row).

Would you have written this function differently? Just to make sure I am not doing something incorrect here.

**Comment by romainfrancois** [comment]
What's happening essentially is that `dplyr` and `ggplot2` are both using tidy evaluation to delay things. I guess I would resolve the data in `plot_this` before involving `ggplot2`, something like this. #5401 is trying to make the original code illegal. 


``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

plot_this <- function(.data, x, y, label) {
  tib <- tibble(x, y, label)
  ggplot() +
    geom_point(data = .data, aes(mpg, hp)) +
    geom_point(aes(x, y), color = "red", size = 4, data = tib) +
    geom_text(aes(x, y, label = label), color = "white", fontface = "bold", data = tib)
}

df <- tibble(
  data = list(mtcars),
  x = c(16, 18, 19),
  y = c(80, 90, 100)
) %>% 
  tibble::rowid_to_column()
df
#> # A tibble: 3 x 4
#>   rowid data                    x     y
#>   <int> <list>              <dbl> <dbl>
#> 1     1 <df[,11] [32 × 11]>    16    80
#> 2     2 <df[,11] [32 × 11]>    18    90
#> 3     3 <df[,11] [32 × 11]>    19   100
df %>% 
  rowwise() %>% 
  mutate(
    plot = plot_this(data, x, y, rowid) %>% list(), 
    .keep = "unused"
  ) %>% 
  pull()
#> [[1]]
```

![](https://i.imgur.com/M2iQ82e.png)

    #> 
    #> [[2]]

![](https://i.imgur.com/4BlPmRY.png)

    #> 
    #> [[3]]

![](https://i.imgur.com/G2t8eEL.png)

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
