### ISSUE TITLE
"Using dplyr summarise_at with column index"

### ISSUE THREAD

**Issue by ETaSky** [tidyverse/dplyr#5389]
Hi, I was working on my code and found an issue with the question in the title. This question has been asked before on stackoverflow (https://stackoverflow.com/questions/45883513/using-dplyr-summarise-at-with-column-index), and was said not to be present after dplyr 0.7.5 version. But I came across this issue again even I am using dplyr-1.0.0. 

```r
> library(dplyr)
> packageVersion("dplyr")
[1] ‘1.0.0’
> data("mtcars")
> mtcars %>% group_by(gear) %>% summarise_at(3:4, mean)
# A tibble: 3 x 3
   gear  disp    hp
  <dbl> <dbl> <dbl>
1     3  326. 176. 
2     4  123.  89.5
3     5  202. 196. 
> mtcars %>% group_by(cyl) %>% summarise_at(3:4, mean)
# A tibble: 3 x 3
    cyl    hp  drat
  <dbl> <dbl> <dbl>
1     4  82.6  4.07
2     6 122.   3.59
3     8 209.   3.23
```

**Comment by hadley** [comment]
`summarise_at()` is now superseded in favour of ‘across()` which means that we’ll no longer change its behaviour. I don’t think it’s worth making an exception for this case since indexing by position is not something we generally recommend.

**Comment by ETaSky** [comment]
Thanks you!
