### ISSUE TITLE
Getting started vignette should use `!` to negate the selection instead of `-`

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#5392]
dplyr 1.0.0 introduced boolean operators, but it seems they are not advertised. At least, since `-` is no more documented, the vignette should use `!` instead.

c.f. https://tidyselect.r-lib.org/reference/language.html

If this sounds good, I'm happy to create a pull request for this.

**Comment by hadley** [comment]
Yes please!
