### ISSUE TITLE
Dealing with the new `summarise` messages as a package developer

### ISSUE THREAD

**Issue by burchill** [tidyverse/dplyr#5394]
I'm developing a package that uses dplyr and it's `summarise()` function. With the release of dplyr 1.0, `summarise()` now sends a message every time it is used without the `.groups` argument. 

I _could_ add `.groups = "drop_last"` to each instance of `summarise()`, but I'm a little worried that since the lifecycle of this argument is labeled "experimental" that I'll need to change it again relatively soon. Is this safe to use?

I also checked, and when used in a package, `summarise()` doesn't seem to raise any messages like it would normally. If this is intentional, is this (very cool) feature documented anywhere?  I can't seem to find it, but it might be helpful to let package developers know about it.

**Comment by lionel-** [comment]
Regarding interactive-only messages, you can check whether you're called from a script with:

```r
identical(topenv(parent.frame()), globalenv())
```

This (or at least the `parent.frame()` part) needs to be called by the user-facing function, not by a deeper util function in your package.

**Comment by hadley** [comment]
And that is what `summarise()` already does 😄 

The argument is experimental so I don't want to make any promises, but so far the reception has been positive, so it seems likely that it'll stay.

Another technique is to temporarily set the `dplyr.summarise.inform` option, with eg `with::local_options(list(dplyr.summarise.inform = FALSE))`
