### ISSUE TITLE
Negated select() and filter()

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidyverse/dplyr#5396]
Are there any plans on adding negated versions of `select()` and `filter()`?

For most parts, you can just wrap everything in `!`. On one hand, I feel you would be able to get more readable code, but on the other hand it might be too limited of a use-case. 

with proper naming, it might ease the confusion on. wether `filter()` keeps or removes cases. 😃

**Comment by lionel-** [comment]
Most likely not, but it is easy to write these negative versions :-)

For `select()`, just pass the dots:

```r
select_not <- function(data, ...) {
  select(data, !c(...))
}

mtcars %>% select_not(starts_with(c("c", "d"))) %>% head()
#>                    mpg  hp    wt  qsec vs am gear
#> Mazda RX4         21.0 110 2.620 16.46  0  1    4
#> Mazda RX4 Wag     21.0 110 2.875 17.02  0  1    4
#> Datsun 710        22.8  93 2.320 18.61  1  1    4
#> Hornet 4 Drive    21.4 110 3.215 19.44  1  0    3
#> Hornet Sportabout 18.7 175 3.440 17.02  0  0    3
#> Valiant           18.1 105 3.460 20.22  1  0    3
```

For `filter()` this needs a little tidy eval: capture the dots, wrap each of these in a new call to `!`, then splice them back in:

```r
```

**Comment by romainfrancois** [comment]
This works too, but for weird reasons:

``` r
library(dplyr, warn.conflicts = FALSE)

filter_not <- function(data, ...) {
  dots <- enquos(...)
  filter(data, !data.frame(!!!dots))
}
mtcars %>% 
  filter_not(mpg > 20) %>% head()
#>                    mpg cyl  disp  hp drat   wt  qsec vs am gear carb
#> Hornet Sportabout 18.7   8 360.0 175 3.15 3.44 17.02  0  0    3    2
#> Valiant           18.1   6 225.0 105 2.76 3.46 20.22  1  0    3    1
#> Duster 360        14.3   8 360.0 245 3.21 3.57 15.84  0  0    3    4
#> Merc 280          19.2   6 167.6 123 3.92 3.44 18.30  1  0    4    4
#> Merc 280C         17.8   6 167.6 123 3.92 3.44 18.90  1  0    4    4
#> Merc 450SE        16.4   8 275.8 180 3.07 4.07 17.40  0  0    3    3
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

i.e. that a `!` on a data frame gives a matrix

``` r
str(!data.frame(x = c(T, F, T), y = c(F, F, T)))
#>  logi [1:3, 1:2] FALSE TRUE FALSE TRUE TRUE FALSE
#>  - attr(*, "dimnames")=List of 2
#>   ..$ : NULL
#>   ..$ : chr [1:2] "x" "y"
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I agree with @lionel- that this is not likely to go in `dplyr` but that it can easily be hosted by another 📦. 

Another reason for `filter()` is that something like `mtcars %>% filter_not(mpg > 20, cyl < 6)` would be IMO confusing, e.g. does this mean: 

 - `filter(!(mpg > 20), !(cyl <6))`
 - `filter(!(mpg > 20 & cyl < 6))` 

both of which might be of interest.

**Comment by hadley** [comment]
If I could go back in time, I would have picked names that could more easily be reversed, but I think it's too late now, unfortunately.
