### ISSUE TITLE
Pipe and . alias return fseq instead of data.frame

### ISSUE THREAD

**Issue by ColeMiller1** [tidyverse/dplyr#5414]
On this [StackOverflow post](https://stackoverflow.com/questions/62924025/no-applicable-method-for-tbl-vars-applied-to-an-object-of-class-cfseq-fu/62924321), a user pointed out an error when chaining within ```_join()``` and self-referencing:

``` r
library(dplyr, warn.conflicts = FALSE)
iris%>%
    inner_join(.%>%
                   count(Species),
               copy = TRUE)
#> Error in as.data.frame.default(y): cannot coerce class 'c("fseq", "function")' to a data.frame
```

<sup>Created on 2020-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We can produce what is trying to happen by wrapping our calls in ```{```:

``` r
library(dplyr, warn.conflicts = FALSE)
iris%>%
    {
        . %>%
            count(Species)
    }
#> Functional sequence with the following components:
#> 
#>  1. count(., Species)
#> 
#> Use 'functions' to extract the individual functions.
```

<sup>Created on 2020-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Sorry if this is more of a magrittr issue. I attempted in both 1.0.0 and 0.8.3 and had similar issues. I was using magrittr 1.5,  vctrs 0.3.1., and R 4.0.1

**Comment by romainfrancois** [comment]
This is a magrittr feature, that allows you to create a function with the `. %>% ` syntax, e.g. 

``` r
library(magrittr)

f <- . %>% mean()
f(1:10)
#> [1] 5.5
```

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
