### ISSUE TITLE
Problem with dplyr::bind_rows under R 4.0.x

### ISSUE THREAD

**Issue by Waldi73** [tidyverse/dplyr#5421]
I have a list of dataframes with the same structure of POSIXct fields.
I use dplyr::bind_rows() to put these dataframes together in a single dataframe.
This worked perfectly in R 3.6 - dplyr 0.8.5 :
```r
data %>% bind_rows()
            startdate            stopdate
1 2020-07-15 22:02:00 2020-07-15 22:17:00
2 2020-07-15 21:02:00 2020-07-15 21:17:00
```
Since migration to R 4.0.x (I tried with 4.0.0 and 4.0.2) and dplyr 1.0.0, I get following error :
```
#> Error: `vec_ptype2.POSIXct.POSIXct()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```
This works without error using `do.call(rbind,data)`

Reprex :
``` r
data <- list(
  structure(
    list(
      startdate = structure(1594843320, class = "POSIXct"),
      stopdate = structure(1594844220, class = "POSIXct")
    ),
    class = "data.frame"
  ),
  structure(
    list(
      startdate = structure(1594839720, class = "POSIXct"),
      stopdate = structure(1594840620, class = "POSIXct")
    ),
    class = "data.frame"
  )
)
library(dplyr)
data %>% bind_rows
#> Error: `vec_ptype2.POSIXct.POSIXct()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

<sup>Created on 2020-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
How did you construct the `POSIXct` object? It's supposed to inherit from `POSIXt`:

```r
class(as.POSIXct(Sys.Date()))
#> [1] "POSIXct" "POSIXt"
```

**Comment by Waldi73** [comment]
This is a vector which I initialized in a function :   
```
stopdatebuf <- structure(rep(NA_real_, nstop), class = "POSIXct", 
      tzone = lubridate::tz(data$stopdate))
```
Surprisingly this worked in R 3.6 / dplyr 0.8.5, but not anymore in dplyr 1.0.0

**Comment by hadley** [comment]
It only worked by coincidence. That’s not a valid date-time class name.
