### ISSUE TITLE
across() should have an option to exclude columns generated by another across()

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#5433]
This example on [colwise vignette](https://dplyr.tidyverse.org/articles/colwise.html) also calculates `max()` of `min()`ed values (`max_min_*`), which I don't think is intended. This made me think `across()` should have some option to distinguish the columns that is generated by `across()`. Is it technically possible...?

``` r
starwars %>% summarise(
  across(where(is.numeric), ~min(.x, na.rm = TRUE), .names = "min_{col}"),
  across(where(is.numeric), ~max(.x, na.rm = TRUE), .names = "max_{col}")
)
#> # A tibble: 1 x 9
#>   min_height min_mass min_birth_year max_height max_mass max_birth_year
#>        <int>    <dbl>          <dbl>      <int>    <dbl>          <dbl>
#> 1         66       15              8        264     1358            896
#> # … with 3 more variables: max_min_height <int>, max_min_mass <dbl>,
#> #   max_min_birth_year <dbl>
```

**Comment by romainfrancois** [comment]
Options: 

``` r
library(dplyr, warn.conflicts = FALSE)

starwars %>% 
  summarise(
    across(where(is.numeric), ~min(.x, na.rm = TRUE), .names = "min_{col}"),
    across(where(is.numeric) & !starts_with("min"), ~max(.x, na.rm = TRUE), .names = "max_{col}")
  )
#> # A tibble: 1 x 6
#>   min_height min_mass min_birth_year max_height max_mass max_birth_year
#>        <int>    <dbl>          <dbl>      <int>    <dbl>          <dbl>
#> 1         66       15              8        264     1358            896

starwars %>% 
  summarise(
    across(where(is.numeric), list(min = ~min(.x, na.rm = TRUE), max = ~max(.x, na.rm = TRUE)), .names = "{fn}_{col}")
  )
#> # A tibble: 1 x 6
#>   min_height max_height min_mass max_mass min_birth_year max_birth_year
#>        <int>      <int>    <dbl>    <dbl>          <dbl>          <dbl>
#> 1         66        264       15     1358              8            896
```

<sup>Created on 2020-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

but yeah I guess the vignette needs fixing.

**Comment by romainfrancois** [comment]
Maybe the vignette could have a `select()` : 

``` r
library(dplyr, warn.conflicts = FALSE)

min_max <- list(
  min = ~min(.x, na.rm = TRUE), 
  max = ~max(.x, na.rm = TRUE)
)
starwars %>% 
  summarise(across(where(is.numeric), min_max, .names = "{fn}.{col}")) %>% 
  select(starts_with("min"), starts_with("max"))
#> # A tibble: 1 x 6
#>   min.height min.mass min.birth_year max.height max.mass max.birth_year
#>        <int>    <dbl>          <dbl>      <int>    <dbl>          <dbl>
#> 1         66       15              8        264     1358            896
```

<sup>Created on 2020-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by yutannihilation** [comment]
Thanks.

> Maybe the vignette could have a `select()` :

For this particular example, I agree. We don't need to write `across()` twice just to sort the columns.

And, yeah, adding a prefix to deselect it afterwards is a trick and it's nice if the vignette shows this workaround. But, IMHO, this is one of the common pitfalls many users face, so I think `across()` should have some formal solution to this.

**Comment by romainfrancois** [comment]
I don't think it's possible given how it works, i.e. `across()` just returns a data frame, that then gets spliced to columns. 

Another option would be to combine two `across()` calls into one data frame, e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)

starwars %>% 
  summarise(
    bind_cols(
      across(where(is.numeric), ~min(.x, na.rm = TRUE), .names = "min_{col}"),
      across(where(is.numeric), ~max(.x, na.rm = TRUE), .names = "max_{col}")
    )
  )
#> # A tibble: 1 x 6
#>   min_height min_mass min_birth_year max_height max_mass max_birth_year
#>        <int>    <dbl>          <dbl>      <int>    <dbl>          <dbl>
#> 1         66       15              8        264     1358            896
```

<sup>Created on 2020-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by lionel-** [comment]
> Another option would be to combine two across() calls into one data frame

I like this!

**Comment by yutannihilation** [comment]
I too like this option. I now feel `bind_cols()` is a kind of syntax.... Curious.

**Comment by yutannihilation** [comment]
`bind_cols()` is also a solution to this example of reusing a variable on `summarise()`'s help.

``` r
library(dplyr, warn.conflicts = FALSE)

# BEWARE: reusing variables may lead to unexpected results
mtcars %>%
  group_by(cyl) %>%
  summarise(disp = mean(disp), sd = sd(disp))
#> `summarise()` ungrouping output (override with `.groups` argument)
#> # A tibble: 3 x 3
#>     cyl  disp    sd
#>   <dbl> <dbl> <dbl>
#> 1     4  105.    NA
#> 2     6  183.    NA
#> 3     8  353.    NA

step <- bind_cols

# works
mtcars %>%
  group_by(cyl) %>%
  summarise(
    step(disp = mean(disp), sd = sd(disp))
  )
#> `summarise()` ungrouping output (override with `.groups` argument)
#> # A tibble: 3 x 3
#>     cyl  disp    sd
#>   <dbl> <dbl> <dbl>
#> 1     4  105.  26.9
#> 2     6  183.  41.6
#> 3     8  353.  67.8
```

<sup>Created on 2020-08-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
> I now feel bind_cols() is a kind of syntax.... Curious.

This is the combination of two dplyr principles:

1. Only the result of complete expressions is added to the result data frame by the dplyr evaluator

2. When an unnamed complete expression returns a data frame, all its columns are added to the result data frame (auto-splicing)

Because of (1) we can add columns to a temporary data frame. And because of (2) we can add the columns of this temporary data frame to the result.

Another way to do it would be:

```r
starwars %>%
  summarise(
    tibble(
      across(where(is.numeric), ~min(.x, na.rm = TRUE), .names = "min_{col}"),
      across(where(is.numeric), ~max(.x, na.rm = TRUE), .names = "max_{col}")
    )
  )
```

This works because the auto-splicing behaviour also applies in `tibble()`:

```r
identical(
  tibble(data.frame(x = 1)),
  tibble(x = 1),
)
#> [1] TRUE
```

Actually I think it would be better practice to use `tibble()` instead of `bind_cols()` for these examples, because it is more "elementary".

**Comment by yutannihilation** [comment]
Thanks! I vaguely understood those principles around auto-splicing, but had not found it super useful until recently I got to know `across()` is a function that returns a data.frame. Now the only problem I'm struggling about is how to teach other people about this semantics...

> Actually I think it would be better practice to use `tibble()` instead of `bind_cols()` for these examples, because it is more "elementary".

Agreed.

**Comment by romainfrancois** [comment]
Perhaps first introduce an expression that explicitly returns a data frame, and then present `across()` as something that makes a data frame. 

I agree that using `tibble()` in that example is better.

**Comment by yutannihilation** [comment]
Nice strategy, thanks :) As it seems we all agree to use `tibble()`, I created a pull request for this: #5458

**Comment by yutannihilation** [comment]
After some thinking, I noticed `tibble()` doesn't solve the problem in this case (but `bind_cols()` does).

``` r
mtcars %>%
  group_by(cyl) %>%
  summarise(
    tibble(
      disp = mean(disp),
      sd = sd(disp)
    )
  )
#> `summarise()` ungrouping output (override with `.groups` argument)
#> # A tibble: 3 x 3
#>     cyl  disp    sd
#>   <dbl> <dbl> <dbl>
#> 1     4  105.    NA
#> 2     6  183.    NA
#> 3     8  353.    NA
```

**Comment by lionel-** [comment]
oh of course, because it's an NSE constructor. We'll soon have `tibble0()` as a non-NSE ctor in tibble.

It will have roughly this implementation (requires dev vctrs):

```r
tibble0 <- function(...) {
  data <- df_list(...)
  new_data_frame(data, class = c("tbl_df", "tbl", "data.frame"))
}
```

**Comment by yutannihilation** [comment]
Wow, cool. Is `vctrs::data_frame()` a different thing?

**Comment by lionel-** [comment]
It's basically the same thing, it returns a base data frame instead of a tibble. `data_frame()` would work as well because it supports auto-splicing :) (and tidyverse recycling rules).
