### ISSUE TITLE
Plans to support cuDF as a backend?

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/dplyr#5438]
[cuDF](https://github.com/rapidsai/cudf/issues) leverages GPUs for typical dplyr operations like joining, aggregating or filtering, based on Apache Arrow. They implement a java and a pandas API and enjoy [massive speed gains](https://rapids.ai/about.html) from the implementation of the underlaying operations in CUDA. Looks like they are also exposing a C++ API (libcudf). What do you think about implementing a cuDF backend for dplyr? 
I was not sure if a GitHub issue is the right place to ask such a question, sorry if not. I have also no idea what it would entail to implement this, just curious if you'd consider it.

**Comment by hadley** [comment]
No plans in the near future. I suspect it doesn't work on windows or mac (given that neither are mentioned on https://github.com/rapidsai/cudf/blob/branch-0.15/CONTRIBUTING.md#setting-up-your-build-environment), which means that most of our audience wouldn't be able to use it.
