### ISSUE TITLE
Cumulative percent function

### ISSUE THREAD

**Issue by seasmith** [tidyverse/dplyr#5444]
A function that returns the cumulative percent of its members (regardless of ordering).  Accumulation order goes from smallest to largest number.

---

Possible implementation using base R.

```r
cumpct <- function (x) {
  i <- order(x)
  j <- order(i)
  xi <- x[i]
  res <- cumsum(xi) / sum(xi)
  res[j]
}
```

Example usage.

```r
d <- c(25, 10, 50, 15)
cumpct(d)
# [1] 0.50 0.10 1.00 0.25
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for dplyr: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I think the idea is sound, and hope you'll continue to contribute in the future 😄
