### ISSUE TITLE
Feature request: Allow multiple arguments to `.before` in `mutate()`

### ISSUE THREAD

**Issue by maia-sh** [tidyverse/dplyr#5462]
The `.before` argument is a great addition to `mutate()`. I occasionally want to create multiple, new columns at different locations, for which multiple arguments to `.before` would be useful. Below is my current workaround (using multiple calls to `mutate()`) and a proposed solution.

Thank you for considering this enhancement!

``` r
library(dplyr)

# Current syntax
mtcars %>% 
  mutate(color = "purple", .before = cyl) %>% 
  mutate(size = "tiny", .before = vs) %>% 
  colnames()
#>  [1] "mpg"   "color" "cyl"   "disp"  "hp"    "drat"  "wt"    "qsec"  "size" 
#> [10] "vs"    "am"    "gear"  "carb"

# Proposed syntax
mtcars %>% 
  mutate(color = "purple", size = "tiny", .before = c(cyl, vs)) %>% 
  colnames()
#>  [1] "mpg"   "color" "size"  "cyl"   "disp"  "hp"    "drat"  "wt"    "qsec" 
#> [10] "vs"    "am"    "gear"  "carb"
```

<sup>Created on 2020-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Thanks for the suggestion! This can't really work with the tidyselect syntax because this would conflict with other selection usages:

```r
mtcars %>% mutate(color = "purple", size = "tiny", .before = starts_with("c"))
```

**Comment by maia-sh** [comment]
Thanks for the clarification/reason!
