### ISSUE TITLE
Suggestion: lookup functions

### ISSUE THREAD

**Issue by shearerp** [tidyverse/dplyr#5465]
A lookup is a variant of left join that preserves row count and order of the base table. Lookups come up very frequently in data analysis, which is why Excel has VLOOKUP and other specialized functions to perform them. While dplyr's `left_join` can be used to perform lookups, users could perform lookups in a much more efficient and predictable fashion if they were implemented in their own function. In this issue I will make the case for specialized lookup functionality to be included in dplyr.

## Differences between lookups and left joins
Here are some key differences between `x <- left_join(a, b, by = keys)` and a putative lookup function `y <- lookup(a, b, by = keys)`. 

### 1. Lookups are unique and order-preserving
In a left join, when the matching key `a[i, keys]` doesn't identify a unique row in `b`, the left join output `x` will include _all_ the matching rows. In a lookup, `y[i,]` must always be a single match to `a[i,]` from `b`. It should either be the first match, or if the user wants to be strict, `lookup` could throw an error. Left joins can't do this since they don't ensure uniqueness, so the row count of `x` may not even be the same as `a`. 

It's very common in real-world analysis that the user asks for a left join but really wants a lookup. This can be fine (although less efficient, see point 3 below), but what if the join keys are unintentionally non-unique? This can lead to a catastrophic inflation in row count, which can easily cause an R session to thrash and crash. But if the user _asks_ for a lookup, it can either return the first match or check for non-uniqueness in the join keys of `b` and quickly throw an error if we find an issue. In either case, no catastrophic inflation occurs.

### 2. Lookups generate new columns rather than replacing the base table
`left_join(a, b)` creates an entirely new table - they must, because of potential non-uniqueness - while `lookup(a, b)` contains only the columns of `b` that would be appended to `a` during the join. For example, if `a` is 1-column table of words and `b` is a "dictionary table" with the columns `(word, definition)`, then `y <- lookup(a, b)` would be a 1-column table where `y[i,]` is the definition of the word `a[i,]`. To bring the definitions of words in `a` into our analysis, we could add them to `a` using `a <- bind_cols(a, y)`. Under the hood, this will just append `y` to the list of columns in `a`, so `a` need not be duplicated in memory.

### 3. Lookups don't duplicate the base table in memory
That last bit is what makes `lookup` really useful from a performance perspective. Suppose that `a` is a very big table, say 10GB of RAM, and in particular very wide, such that 99% of its columns are not join keys with `b`. (This is a _very_ common situation.) `left_join(a, b)` will create an entirely new table, forcing reallocation of >10G of memory in the process. Most laptops will start swapping and thrashing, and the analysis will slow to a crawl. `a <- left_join(a, b)` isn't much better, as both `a` and the under-construction version of `a` will live in memory together until the left join finishes and the old `a` can be replaced with the new `a`. 

Lookups can avoid this situation because they're order-preserving and unique, and they need only consider the join keys common to `a` and `b`, as well as the lookup columns of `b`. Even if you just implement `lookup` with `left_join`, you can drop the non-key columns of `a` when developing the output `y`. Since the non-key columns are 99% of the columns of `a`, the left join performed by `lookup` will only be duplicating a 100MB table instead of a 10GB table.

## Why should dplyr do this? Why not just roll your own?

Lookups can be implemented using either `left_join` or `match` (in my code I do the former). In either case, the benefits of `lookup` are non-obvious unless the analyst is acutely aware of all the issues pointed out above. Most analysts will either accept the blowup risk, slowdown & thrashing from doing lookups with `left_join` or find a workaround. It's not easy to think of `lookup`, and it would be great if dplyr nudged people in that direction.

## Do you have code for this?

I do and it's pretty simple, but I don't want to distract the discussion with those details yet. Let's first decide if lookup functions belong in dplyr, then think about the API and implementation. I know the dplyr team will come up with a much more robust solution than I've developed for my personal use.

Thanks for reading! I have been using dplyr since 2014 and I can't imagine my data analysis work without it. I hope this suggestion can be my small contribution to making it even better.

**Comment by hadley** [comment]
I think this is out of scope for dplyr because it's fundamentally a vector operation, not a data frame operation. It might be something we eventually add to [funs](https://github.com/tidyverse/funs); it's straightforward to implement on top of `vctrs::vec_match()`.

**Comment by hadley** [comment]
Sorry, I should have said that your reasons make sense and I totally agree that this is a good idea, it's just that dplyr isn't the right place.

**Comment by shearerp** [comment]
Fair point! But if that's the objection, I should explain my actual implementation a bit more, as it is more table-oriented than what I proposed above.

1. I have two functions implemented: `lookup(x, y, by, cols, drop = T)` and `bind_lookup(x, y, by, cols)`. The `cols` argument specifies which columns of `y` should be returned. Very often you want to return more than one, in which case you have to return a list of vectors, i.e. a data frame.
2. If `length(cols) == 1 && drop == T`, `lookup` returns a vector. Otherwise it returns a data frame.
3. `bind_lookup` just does appends the lookup result to the base table: ```bind_cols(x, lookup(x, y, by, cols, drop=FALSE))```

My usage follows two main patterns:
```
# Pattern 1: set a single column based on a lookup table
a <- a %>% mutate(x = lookup(., b, by, cols = 'target'))

# Pattern 2: append multiple columns, keeping original names from b
a <- a %>% bind_lookup(b, by, cols = c('target1', 'target2'))
```
And 90% of the time I'm using Pattern 2.

**Comment by shearerp** [comment]
And for what it's worth, here is my full implementation

```
#' Generate a column name that isn't used in a given data frame
#' @param data A data frame
find_unused_colname <- function(data) {
  colname <- 'x'
  while (colname %in% colnames(data)) colname <- paste0(colname,'_')
  colname
}

#' @title Look up values in a table
#' @description Essentially a dplyr::left_join, except it
#' - returns only user-specified columns.
#' - is order-stable.
#' - throws an error if a one-to-many match is detected (i.e. row number is not conserved).
#' @param x,y,by tbls and join condition passed to left_join
#' @param cols (chr)[optional] vector of `y` column(s) to return. Defaults to all non-by columns of y.
#' @param drop (bool) convert output to a vector if `cols` has one element, as in x[i, j, drop=TRUE]
#' @details `lookup` is more memory-efficient than `dplyr::left_join` when most LHS columns are not
#' keys in the join condition, because it only passes the necessary columns.
#' @return a vector or a tbl, depending on the values of drop and return.
lookup <- function(x, y, by, cols=NULL, drop=TRUE) {
  nrow_x <- nrow(x)
  rownum <- find_unused_colname(x)

  if (is.null(names(by))) names(by) <- by
  if (is.null(cols)) cols <- colnames(y)[!(colnames(y) %in% by)]

  x <- x[names(by)]
  y <- y[unique(c(as.character(by), cols))]
  x[[rownum]] <- seq_len(nrow(x))

  x <- left_join(x, y, by = by)
  if (nrow(x) != nrow_x) stop('values in lookup table are not unique')

  x <- x[order(x[[rownum]]), cols, drop = FALSE]
  if (drop && length(cols) == 1) pull(x, cols) else x
}

#' Append columns from a lookup table
#' @return a copy of x with appended lookup `cols` from y.
bind_lookup <- function(x, y, by = NULL, cols = NULL) {
  bind_cols(x, lookup(x, y, by = by, cols = cols, drop = FALSE))
}
```
