### ISSUE TITLE
`nth` error messages error

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidyverse/dplyr#5466]
I was trying to follow the [tidyverse style guide](https://style.tidyverse.org/error-messages.html#problem-statement) examples and noticed that `nth` is erroring when trying to print an error.

``` r
dplyr::nth(1:10, "x")
#> Error in format_error_bullets(x[-1]): nms %in% c("i", "x", "") is not TRUE
```

**Comment by romainfrancois** [comment]
``` r
dplyr::nth(1:10, "x")
#> Error: `nth()` argument `n=` should be a single integer
#> Backtrace:
#>     █
#>  1. └─dplyr::nth(1:10, "x")
```

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
