### ISSUE TITLE
docs of moved function still on pkgdown site

### ISSUE THREAD

**Issue by dpprdan** [tidyverse/dplyr#5476]
`group_indices(.data, ...)` was moved from `R/group-indices.R` to `R/group_data.R` with v1.0.0 (IIRC). However, the outdated `group_indices.html` page is still on the pkgdown site: https://dplyr.tidyverse.org/reference/group_indices.html

![grafik](https://user-images.githubusercontent.com/1423562/90003431-5fdfe280-dc94-11ea-8f78-93b46cc4da3e.png)

As such, it is also still indexed by Google for example.
![grafik](https://user-images.githubusercontent.com/1423562/90003547-8736af80-dc94-11ea-809e-9f465920c57b.png)

I assume this is not intended? I am not sure whether this is a general pkgdown problem or whether something in the pkgdown pipeline went wrong here for dplyr specifically?

**Comment by hadley** [comment]
This isn't specific to dplyr, so I've file an issue in pkgdown.
