### ISSUE TITLE
Can't use `n()` inside slice_sample

### ISSUE THREAD

**Issue by shahronak47** [tidyverse/dplyr#5478]
So `sample_n` has been superseded in favour of `slice_sample`. 

I want to sample 50% of each group with atleast 1 sample from each group. This is easy to do with `slice_sample` with `prop = 0.5` but certain groups have only 1 row which are dropped. I want to make sure that atleast 1 row is selected from each group. 

Consider this example, 

```
df <- data.frame(col1 = c('a', 'b', 'b', 'c'), col2 = 1:4)
```

With `sample_n`, I could do : 

```
df %>% group_by(col1) %>% sample_n(max(n() * 0.5, 1))
```

However, with `slice_sample` this fails : 

```
df %>% group_by(col1) %>% slice_sample(n = max(n() * 0.5,1))
```

returns an error
>Error: `n()` must only be used inside dplyr verbs.

Am I missing something or this is a bug?

**Comment by donojazz** [comment]
I am having same issue with slice_head(n=3), slice_tail(n=3) functions.   I believe my problem is because my DPLYR  version is 0.8.5 and those functions are in 1.0.  I have been trying to update my Tidyverse and DPLYR to latest versions and I keep getting errors.  You may want to check to see you are running DPLYR 1.0 or higher.

**Comment by shahronak47** [comment]
@donojazz Thanks for checking. I have `dplyr` 1.0.1 installed. 

```
packageVersion('dplyr')
#[1] ‘1.0.1’
```

**Comment by hadley** [comment]
In order to make the implementations simpler (and hence easier to reason about), the `n` and `prop` arguments need to be constant across groups. I'm not sure if we'll relax this requirement in the future to handle cases like yours but for now, we need to document it.
