### ISSUE TITLE
Adding proportions to `count()`

### ISSUE THREAD

**Issue by c-hoh** [tidyverse/dplyr#5485]
Dear maintainer, 

I find myself executing the following pattern regularly: 

```r
library("dplyr")
data("mtcars")

mtcars %>% 
    count(gear) %>% 
    mutate(prop = n / sum(n))
#>   gear  n    prop
#> 1    3 15 0.46875
#> 2    4 12 0.37500
#> 3    5  5 0.15625
```

Thus I wonder a whether a short-cut for this pattern might be a worthwhile addition to `dplyr`, i.e. providing proportions together with counts. This could either be an option to `count` and `add_count` or a wrapper around these (probably `prop` and `add_prop`). 

There exists a function providing proportions in `base`, but it is a bit clunky:
```
prop.table(table(mtcars$gear))
#> 
#>       3       4       5 
#> 0.46875 0.37500 0.15625
```

In case you think this would be a useful addition I am happy to implement this. If not (or if it is already somewhere in `dplyr`, but I did not discover it yet), this is of course fine as well.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package:  developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
