### ISSUE TITLE
between() is not vectorised

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#5493]
I'm seeing some odd behavior when using `case_when()` and `between()`.  NA's are generated when they shouldn't be, and then re-running the same code on the lines that got NA will yield some non-NAs (and more and more with each re-do).

    library(tidyverse)

    #Create dates to compare.
    set.seed(1234)

    x <- tibble(d1 = sample(1:1000, size = 10000, replace = T),
                d2 = sample(1:1000, size = 10000, replace = T),
                d3 = sample(1:1000, size = 10000, replace = T))

    #Determine where d2 falls relative to d1 and d3
    xbetween <- x %>% mutate(when = case_when(between(d2, d1, d3) ~ "between",
                              d2 < d1 ~ "before",
                              d2 > d3 ~ "after"))

    #First oddity: we get NAs for things that don't make sense and should be "between"
    xbetween %>% count(when)
    #> # A tibble: 4 x 2
    #>   when        n
    #>   <chr>   <int>
    #> 1 after    1477
    #> 2 before   2520
    #> 3 between  5542
    #> 4 <NA>      461

    xbetween %>% filter(is.na(when)) %>% slice(1:10)
    #> # A tibble: 10 x 4
    #>       d1    d2    d3 when 
    #>    <int> <int> <int> <chr>
    #>  1   561   836   997 <NA> 
    #>  2   131   159   778 <NA> 
    #>  3   218   249   753 <NA> 
    #>  4   276   977   980 <NA> 
    #>  5   169   282   991 <NA> 
    #>  6   163   243   637 <NA> 
    #>  7    19   157   975 <NA> 
    #>  8   497   856   935 <NA> 
    #>  9    10    44   307 <NA> 
    #> 10   534   900   946 <NA>

    #For instance manually doing this on the first row yields:

    between(836, 561, 997)
    #> [1] TRUE

    #Second oddity: when we redo the exact same code, some of the things that produced NAs get the correct value of "between" (but not all)
    xbetween %>% 
      filter(is.na(when)) %>% 
      mutate(when2 = case_when(between(d2, d1, d3) ~ "between",
                              d2 < d1 ~ "before",
                              d2 > d3 ~ "after")) %>% 
      count(when2)
    #> # A tibble: 2 x 2
    #>   when2       n
    #>   <chr>   <int>
    #> 1 between   127
    #> 2 <NA>      334

    #For comparison, doing this using standard comparisons produces expected results:
    xabsolute <- x %>% 
      mutate(when = case_when(d2 >= d1 & d2 <= d3 ~ "between",
                                    d2 < d1 ~ "before",
                                    d2 > d3 ~ "after"))

    xabsolute %>% count(when)  
    #> # A tibble: 3 x 2
    #>   when        n
    #>   <chr>   <int>
    #> 1 after    3359
    #> 2 before   4951
    #> 3 between  1690

    # This also occurs for dates, but I simplified it prior to reprex (hence the 'when')

<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.5      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/Denver              
    #>  date     2020-08-24                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version date       lib source        
    #>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
    #>  backports     1.1.8   2020-06-17 [1] CRAN (R 4.0.2)
    #>  blob          1.2.1   2020-01-20 [1] CRAN (R 4.0.2)
    #>  broom         0.7.0   2020-07-09 [1] CRAN (R 4.0.2)
    #>  callr         3.4.3   2020-03-28 [1] CRAN (R 4.0.2)
    #>  cellranger    1.1.0   2016-07-27 [1] CRAN (R 4.0.2)
    #>  cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.2)
    #>  colorspace    1.4-1   2019-03-18 [1] CRAN (R 4.0.2)
    #>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
    #>  DBI           1.1.0   2019-12-15 [1] CRAN (R 4.0.2)
    #>  dbplyr        1.4.4   2020-05-27 [1] CRAN (R 4.0.1)
    #>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
    #>  devtools      2.3.1   2020-07-21 [1] CRAN (R 4.0.2)
    #>  digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.2)
    #>  dplyr       * 1.0.2   2020-08-18 [1] CRAN (R 4.0.2)
    #>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
    #>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.1)
    #>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.2)
    #>  forcats     * 0.5.0   2020-03-01 [1] CRAN (R 4.0.2)
    #>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
    #>  generics      0.0.2   2018-11-29 [1] CRAN (R 4.0.2)
    #>  ggplot2     * 3.3.2   2020-06-19 [1] CRAN (R 4.0.1)
    #>  glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.2)
    #>  gtable        0.3.0   2019-03-25 [1] CRAN (R 4.0.2)
    #>  haven         2.3.1   2020-06-01 [1] CRAN (R 4.0.1)
    #>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.2)
    #>  hms           0.5.3   2020-01-08 [1] CRAN (R 4.0.2)
    #>  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.2)
    #>  httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.2)
    #>  jsonlite      1.7.0   2020-06-25 [1] CRAN (R 4.0.2)
    #>  knitr         1.29    2020-06-23 [1] CRAN (R 4.0.2)
    #>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.2)
    #>  lubridate     1.7.9   2020-06-08 [1] CRAN (R 4.0.2)
    #>  magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.2)
    #>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.2)
    #>  modelr        0.1.8   2020-05-19 [1] CRAN (R 4.0.1)
    #>  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.2)
    #>  pillar        1.4.6   2020-07-10 [1] CRAN (R 4.0.2)
    #>  pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
    #>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
    #>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.1)
    #>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
    #>  processx      3.4.3   2020-07-05 [1] CRAN (R 4.0.2)
    #>  ps            1.3.4   2020-08-11 [1] CRAN (R 4.0.2)
    #>  purrr       * 0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
    #>  R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.2)
    #>  Rcpp          1.0.5   2020-07-06 [1] CRAN (R 4.0.2)
    #>  readr       * 1.3.1   2018-12-21 [1] CRAN (R 4.0.1)
    #>  readxl        1.3.1   2019-03-13 [1] CRAN (R 4.0.1)
    #>  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
    #>  reprex        0.3.0   2019-05-16 [1] CRAN (R 4.0.2)
    #>  rlang         0.4.7   2020-07-09 [1] CRAN (R 4.0.2)
    #>  rmarkdown     2.3     2020-06-18 [1] CRAN (R 4.0.2)
    #>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.2)
    #>  rvest         0.3.6   2020-07-25 [1] CRAN (R 4.0.2)
    #>  scales        1.1.1   2020-05-11 [1] CRAN (R 4.0.2)
    #>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
    #>  stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.2)
    #>  stringr     * 1.4.0   2019-02-10 [1] CRAN (R 4.0.2)
    #>  testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.1)
    #>  tibble      * 3.0.3   2020-07-10 [1] CRAN (R 4.0.2)
    #>  tidyr       * 1.1.1   2020-07-31 [1] CRAN (R 4.0.2)
    #>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.2)
    #>  tidyverse   * 1.3.0   2019-11-21 [1] CRAN (R 4.0.1)
    #>  usethis       1.6.1   2020-04-29 [1] CRAN (R 4.0.1)
    #>  utf8          1.1.4   2018-05-24 [1] CRAN (R 4.0.2)
    #>  vctrs         0.3.2   2020-07-15 [1] CRAN (R 4.0.2)
    #>  withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.2)
    #>  xfun          0.16    2020-07-24 [1] CRAN (R 4.0.2)
    #>  xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.2)
    #>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.2)
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by richardjtelford** [comment]
I think I am having the same problem with `between`

``` r
library("dplyr")

between(c(5, 10), left = c(0, 6), right = c(6, 11)) #both TRUE
#> [1]  TRUE FALSE

between(c(5, 10), left = c(0, 11), right = c(11, 21))# TRUE, FALSE
#> [1] TRUE TRUE
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


It looks to me that `between` is not vectorised for arguments `left` and `right`, and doesn't give an error when the length of these arguments is > 1. It is not obvious from the help file `left, right	Boundary values` that these cannot be vectors.

**Comment by jzadra** [comment]
Yes, that appears to be the issue.  Adding `rowwise()` prior to the case when produces the expected behavior.

**Comment by hadley** [comment]
We will eventually revamp `between()` to be vectorised, but for now I'll just make it clear that it isn't.

**Comment by iangow** [comment]
> We will eventually revamp `between()` to be vectorised, but for now I'll just make it clear that it isn't.

Should a "revamp `between()` to be vectorised" issue be created?

This was a bit of a gotcha for me, as I mostly use (Postgre)SQL sources with `dplyr` and it's certainly vectorised (in effect) with those. The error message received after installing the GitHub version of `dplyr` was helpful.
