### ISSUE TITLE
Mutate: assign values to multiple columns at the same time

### ISSUE THREAD

**Issue by Mashin6** [tidyverse/dplyr#5494]
Data.table has a maybe not so often used, but useful feature to assign output of a function to multiple columns.
Here function returns a vector of 4 values that are assigned to 4 columns.
```
dt[ , c("nA", "nT", "nG", "nC") := mergeReads1(refseq, qualasc)]
```

I couldn't find anything similar for mutate and have to do:
```
df %>% mutate(temp.df = pmap(list(refseq, qualasc), mergeReads1) %>% unnest(temp.df)
```

If would be nice feature for dplyr if it really can't do that.

**Comment by hadley** [comment]
You can already do that in dplyr, just by returning a data frame:

    library(dplyr, warn.conflicts = FALSE)

    df <- data.frame(x = 1, y = 2)

    my_f <- function(x) {
      data.frame(x1 = x + 1, x2 = x * 2)
    }
    df %>% mutate(my_f(x))
    #>   x y x1 x2
    #> 1 1 2  2  2

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by Mashin6** [comment]
Thanks for the workaround.

Although I think it would be neat be able to do something like
``` 
df %>% mutate( c(x, y, z) = function(a,b,c))
-or-
df %>% mutate( c(x, y, z) = pmap(list(a,b,c), function))
```
