### ISSUE TITLE
Errors with dplyr

### ISSUE THREAD

**Issue by HaniAwad** [tidyverse/dplyr#5495]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

I installed dplyr and I get an error message when I try to load the library
I think the issue arises in errors during installatoin
# insert reprex here
---
> library(dplyr)
Error: package or namespace load failed for ‘dplyr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Rcpp’ 1.0.0 is already loaded, but >= 1.0.1 is required

--- here is the installation error message
installation of package ‘dbplyr’ had non-zero exit status
* installing *source* package ‘modelr’ ...
** package ‘modelr’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Rcpp’ 1.0.0 is being loaded, but >= 1.0.1 is required
ERROR: lazy loading failed for package ‘modelr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/modelr’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/modelr’
Warning in install.packages :
  installation of package ‘modelr’ had non-zero exit status

**Comment by hadley** [comment]
You need to restart R, then re-install Rcpp.
