### ISSUE TITLE
feature request: progress bar to  summarise_at/summarise_all functions

### ISSUE THREAD

**Issue by zackarno** [tidyverse/dplyr#5499]
The summarise_at/summarise_all functions are so powerful. It would be really cool if a progress bar option could be added. Maybe something like: pb=T. This would be handy when we are using these functions across large data sets. Additionally, we often use these dplyr functions inside of custom functions, but I do not know of an easy way to add a function bar.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's currently out of scope for dplyr since we don't generally provided progress bars for any operations. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
