### ISSUE TITLE
!!as.name() does not work with nested tibbles using map2()

### ISSUE THREAD

**Issue by vovoch** [tidyverse/dplyr#5511]
I ran into inability to use `!!as.name()` with `.x` or `.y` input variables inside of `mutate( map2( rename(...) )`.
I provide a reprex with several attempts below.

Also I would like to add it is very strange but `.x` and `.y` _global_ variables are _not visible_ on the Environment tab in Data or Values sections in RStudio 1.3.1073. It is a problem if you used them for debugging previously without further `rm()`. The only way to know about their presence is to print them in the console.
``` r
library(tidyverse)

df <- tibble(
  var_name = "new_name",
  data = list(data.frame(foo = 1))
)

df
#> # A tibble: 1 x 2
#>   var_name data            
#>   <chr>    <list>          
#> 1 new_name <df[,1] [1 x 1]>

df$data
#> [[1]]
#>   foo
#> 1   1

# OK example 1
df %>% mutate(data = map2(data, var_name, ~.x %>% mutate(foo = .y))) %>% .$data
#> [[1]]
#>        foo
#> 1 new_name

# OK example 2
df %>% mutate(data = map(data, ~.x %>% rename(!!as.name("new_name") := foo))) %>% .$data
#> [[1]]
#>   new_name
#> 1        1

# ERROR example 1
df %>% mutate(data = map2(data, "new_name", ~.x %>% rename(!!as.name(.y) := foo)))
#> Error in as.name(.y): object '.y' not found

# ERROR example 2
df %>% mutate(data = map2(data, var_name, ~.x %>% rename(!!as.name(.y) := foo)))
#> Error in as.name(.y): object '.y' not found

# ERROR example 3
df %>% mutate(data = map2(var_name, data, ~.y %>% rename(!!as.name(.x) := foo)))
#> Error in as.name(.x): object '.x' not found

# Example with global .y value 1
.y <- "global"
df %>% mutate(data = map2(data, var_name, ~.x %>% rename(!!as.name(.y) := foo))) %>% .$data
#> [[1]]
#>   global
#> 1      1

# Example with global .y value 2
.y <- list("a")
df %>% mutate(data = map2(data, var_name, ~.x %>% rename(!!as.name(.y) := foo))) %>% .$data
#> Error in as.name(.y): invalid type/length (symbol/1) in vector allocation

# repeating ERROR example 2
rm(.y)
df %>% mutate(data = map2(data, var_name, ~.x %>% rename(!!as.name(.y) := foo))) %>% .$data
#> Error in as.name(.y): object '.y' not found
```
<sup>Created on 2020-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
This is expected. `!!` happens _very_ early, at the time the first `mutate()` is called. At that point, the purrr lambda isn't executing yet, so there's no `.x` or `.y` argument.

We have plans to possibly change that in the next major version of rlang: https://github.com/r-lib/rlang/issues/845. Maybe this would be too large of a breaking change and we can't go through with it.
