### ISSUE TITLE
Unexpected error while using `safely()` inside a `mutate()` call

### ISSUE THREAD

**Issue by ngriffiths21** [tidyverse/dplyr#5512]
There is unexpected behavior when using `safely()`, `mutate()`, and `options(warn = 2)` together:

``` r
library(purrr)
suppressMessages(library(dplyr))

err_fun <- function (...) {
  stop("this is fine")
}

err_fun_opts <- function (...) {
  options(warn = 2)
  warning("throws only in mutate()")
  options(warn = 1)
}

# normal results
safely(err_fun)()
#> $result
#> NULL
#> 
#> $error
#> <simpleError in .f(...): this is fine>

safely(err_fun_opts)()
#> $result
#> NULL
#> 
#> $error
#> <simpleError in .f(...): (converted from warning) throws only in mutate()>

mutate(mtcars, test = list(safely(err_fun)()))$test[[1]]
#> $result
#> NULL
#> 
#> $error
#> <simpleError in .f(...): this is fine>


# weird results
mutate(mtcars, test = list(safely(err_fun_opts)()))
#> Error: (converted from warning) Problem with `mutate()` input `test`.
#> ℹ throws only in mutate()
#> ℹ Input `test` is `list(safely(err_fun_opts)())`.
```
<sup>Created on 2020-08-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It seems possible this is a purrr issue, but I'm starting here since I only have problems inside `mutate()`.

---

Version info:

```
R 4.0.2
purrr 0.3.4
dplyr 1.0.2
```

**Comment by lionel-** [comment]
That's a limitation from the `warn = 2` mechanism. A warning is only converted to error if it is unhandled. dplyr handles warnings to instrument them, and then rewarns. Only at that point is the warning converted to error, and then `safely()` catches it.

One alternative you could try is to install a handler with `withCallingHandlers()` to transform warnings to errors manually. You could write a purrr-like adverb (transforms functions) or a withr-like adverb (sets special contexts for expressions).
