### ISSUE TITLE
Conflicting licenses in dependencies

### ISSUE THREAD

**Issue by fproske** [tidyverse/dplyr#5513]
First of all, thanks for this great package!

Since version 1.0.0 dplyr has dependencies on both GPL-2-only (`generics`) and GPL-3-only (e.g. `lifecycle`, `ellipsis`, `rlang`) packages making it impossible to distribute the (unmodified) version of dplyr. It would be great if the the GPL-2-only dependency (`generics`) could either be removed or the license of `generics` be changed to e.g. GPL-2/GPL-3.

Again, thanks for the great work and best regards

**Comment by hadley** [comment]
Where in the process of converting of attempting to convert all tidyverse packages to MIT licenses. This obviously requires agreement of all copyright holders, so we're starting with the smaller packages that have fewer contributors. We can prioritise generics to avoid the license clash, and we'll get to the others in time.
