### ISSUE TITLE
summarize() evaluates tibble columns it creates instead of input columns

### ISSUE THREAD

**Issue by twest820** [tidyverse/dplyr#5515]
I was working with some kind of terribly named data and noticed two curious behaviors:

1. Summary statics weren't being calculated correctly.
2. The statics' values depended on summarise()/summarize()'s order of arguments.

It looks like what's going on is that if you write code like `summarize(inputTibble, foo = someFunction(bar), baz = someOtherFunction(foo))` then baz gets its value from the tibble `summarize()` returns rather than `inputTibble$foo`. So this appears to be a scope issue with name resolution. I'm not sure what the intended behavior is but it seems like a warning might be in order.

Repex:
```r
data = tibble(mean = seq(0, 10, by = 1)^2)
# unexpected: mean and median are both 35 because median gets calculated from the summary value of mean rather than data$mean
data %>% summarize(mean = mean(mean), median = median(mean)) 
# expected: mean is 35 and median is 25
data %>% summarize(unambiguousMean = mean(mean), median = median(mean)) 
# expected: mean is 35 and median is 25
data %>% summarize(median = median(mean), mean = mean(mean)) 
```

Workarounds:
- use names that are unique 
- order statements to avoid name collisions

Version: R 4.0.2, dplyr 1.0.1

**Comment by romainfrancois** [comment]
This is the intended behavior. Another way around it is to create a single expression that returns a data frame: 

``` r
library(dplyr, warn.conflicts = FALSE)

data = tibble(mean = seq(0, 10, by = 1)^2)
data %>% 
  summarise(
    data.frame(mean = mean(mean), median = median(mean))
  )
#> # A tibble: 1 x 2
#>    mean median
#>   <dbl>  <dbl>
#> 1    35     25
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
