### ISSUE TITLE
FR: circular shift elements in a vector

### ISSUE THREAD

**Issue by SarenT** [tidyverse/dplyr#5518]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
I think a circular shift function would be a good addition in dplyr. Just to clarify, a circular shift is similar to lead and lag but instead of introducing NA's it cycles last/first values to first/last positions. e.g.:
a vector of c(1, 2, 3, 4) would become after a circular shift of 1: c(4, 1, 2, 3).
In MatLAB it seems to be done already: https://www.mathworks.com/help/matlab/ref/circshift.html
One can also implement it easily:
Taken from:
https://stackoverflow.com/questions/30542128/circular-shift-of-vector-by-distance-n/30542172#30542172

```r
shifter <- function(x, n = 1) {
  if (n == 0) x else c(tail(x, -n), head(x, n))
}

a <- 1:4

shifter(a)
# [1] 2 3 4 1

shifter(a, 2)
# [1] 3 4 1 2
```
If there is an agreement I can submit a pull request.

**Comment by hadley** [comment]
We're no longer adding such function to dplyr, and anything new will go in to the [funs](https://github.com/tidyverse/funs) package. But this function feels just a bit too esoteric to me — developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
