### ISSUE TITLE
News link for 0.8.4 is broken

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#5521]
On https://dplyr.tidyverse.org/, the link for News item for Version 0.8.4 seems to be broken. Perhaps this is related to [this comment](https://github.com/tidyverse/dplyr/issues/4980#issuecomment-598511004)?

**Comment by batpigandme** [comment]
Yeah, there is no blog post for 0.8.4, so, if anything, that should probably just go to [its anchor](https://dplyr.tidyverse.org/news/index.html#dplyr-0-8-4-2020-01-30-2020-01-31) in the changelog.
