### ISSUE TITLE
bind_rows() doesn't work for date or time arrays with a dimension

### ISSUE THREAD

**Issue by cmarquardt** [tidyverse/dplyr#5525]
The following:

```r
    library(tidyverse)
    library(lubridate)

    setup <- function(n) {
      times  <- ymd_hms("2000-01-01 00:00:00", tz = "UTC") + seconds(seq(1, n)*86400.)
      floats <- seq(1:n)*2.
      
      tibble(date = as.Date(times), times = times, x = floats)
    }

    t.1 <- setup(3)
    t.2 <- setup(2)

    bind_rows(t.1, t.2)
```

works as expected:

```
    #> # A tibble: 5 x 3
    #>   date       times                   x
    #>   <date>     <dttm>              <dbl>
    #> 1 2000-01-02 2000-01-02 00:00:00     2
    #> 2 2000-01-03 2000-01-03 00:00:00     4
    #> 3 2000-01-04 2000-01-04 00:00:00     6
    #> 4 2000-01-02 2000-01-02 00:00:00     2
    #> 5 2000-01-03 2000-01-03 00:00:00     4
```

but when adding a dimension to the `times` variable, I get an error:

```r
    setup <- function(n) {
      times  <- ymd_hms("2000-01-01 00:00:00", tz = "UTC") + seconds(seq(1, n)*86400.)
      floats <- seq(1:n)*2.
      
      dim(times) <- length(times)
      
      tibble(date = as.Date(times), times = times, x = floats)
    }

    t.1 <- setup(3)
    t.2 <- setup(2)

    bind_rows(t.1, t.2)

    #> Error: `vec_cast.Date.Date()` is implemented at C level.
    #> This R function is purely indicative and should never be called.
```

If there's no `date` column, `bind_rows()` complains about a different casting routine, the problem remains:

    library(tidyverse)
    library(lubridate)

    setup <- function(n) {
      times  <- ymd_hms("2000-01-01 00:00:00", tz = "UTC") + seconds(seq(1, n)*86400.)
      floats <- seq(1:n)*2.
      
      dim(times) <- length(times)

      tibble(times = times, x = floats)
    }

    t.1 <- setup(3)
    t.2 <- setup(2)

    bind_rows(t.1, t.2)
    #> Error: `vec_cast.POSIXct.POSIXct()` is implemented at C level.
    #> This R function is purely indicative and should never be called.

I understand that by adding a dimension to a vector as in the second sample, I'm changing the atomic vector to an array which might behave different in some circumstances; Hadley mentions this briefly in his Advanced R book (section 3.3.3). 

The reason I'm writing this ticket anyway is that when adding a dimension to the `floats` vector instead of `times`, `bind_rows()` behaves as before:

    library(tidyverse)
    library(lubridate)

    setup <- function(n) {
      times  <- ymd_hms("2000-01-01 00:00:00", tz = "UTC") + seconds(seq(1, n)*86400.)
      floats <- seq(1:n)*2.
      
      dim(floats) <- length(floats)

      tibble(date = as.Date(times), times = times, x = floats)
    }

    t.1 <- setup(3)
    t.2 <- setup(2)

    bind_rows(t.1, t.2)
    #> # A tibble: 5 x 3
    #>   date       times                   x
    #>   <date>     <dttm>              <dbl>
    #> 1 2000-01-02 2000-01-02 00:00:00     2
    #> 2 2000-01-03 2000-01-03 00:00:00     4
    #> 3 2000-01-04 2000-01-04 00:00:00     6
    #> 4 2000-01-02 2000-01-02 00:00:00     2
    #> 5 2000-01-03 2000-01-03 00:00:00     4

Is the difference in the behaviour of `bind_rows()` depending on the data type intentional or a bug? 

**Edit**: Just to mention, it worked in dplyr 0.8.5, and started to fail with dplyr 1.0. Also, `rbind()` seems ok for variables with and without dimensions.

**Comment by DavisVaughan** [comment]
I would argue that Date shouldn't ever be treated like a matrix/array. It doesn't seem like it was built to support being treated that way. Just adding a `dim` attribute is often not good enough to make something work like an array.

For example, it doesn't print like a matrix, and cbind/rbind don't keep the class.

``` r
x <- Sys.Date() + 1:6
dim(x) <- c(2, 3)

x
#> [1] "2020-09-11" "2020-09-12" "2020-09-13" "2020-09-14" "2020-09-15"
#> [6] "2020-09-16"

cbind(x, x)
#>       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]
#> [1,] 18516 18518 18520 18516 18518 18520
#> [2,] 18517 18519 18521 18517 18519 18521

rbind(x, x)
#>       [,1]  [,2]  [,3]
#> [1,] 18516 18518 18520
#> [2,] 18517 18519 18521
#> [3,] 18516 18518 18520
#> [4,] 18517 18519 18521
```

<sup>Created on 2020-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

This SO post about factor matrices is similar
https://stackoverflow.com/questions/28723059/can-we-get-factor-matrices-in-r

**Comment by cmarquardt** [comment]
Many thanks for pointing me to that SO post - I wasn't aware of all the intricacies of `dim()`

I don't completely follow your example. In the ones I provided, both `rbind()` and `cbind()` work without stripping off the class (in R 4.0.2), though only if the dimension is set to a scalar:

    library(tidyverse)
    library(lubridate)

    setup <- function(n) {
      times  <- ymd_hms("2000-01-01 00:00:00", tz = "UTC") + seconds(seq(1, n)*86400.)
      floats <- seq(1:n)*2.
      
      dim(times) <- length(times)

      tibble(dates = as.Date(times), times = times, x = floats)
    }

    t.1 <- setup(3)
    t.2 <- setup(3)

    rbind(t.1, t.2)
    #> # A tibble: 6 x 3
    #>   dates      times                   x
    #>   <date>     <dttm>              <dbl>
    #> 1 2000-01-02 2000-01-02 00:00:00     2
    #> 2 2000-01-03 2000-01-03 00:00:00     4
    #> 3 2000-01-04 2000-01-04 00:00:00     6
    #> 4 2000-01-02 2000-01-02 00:00:00     2
    #> 5 2000-01-03 2000-01-03 00:00:00     4
    #> 6 2000-01-04 2000-01-04 00:00:00     6

    cbind(t.1, t.2)
    #>        dates      times x      dates      times x
    #> 1 2000-01-02 2000-01-02 2 2000-01-02 2000-01-02 2
    #> 2 2000-01-03 2000-01-03 4 2000-01-03 2000-01-03 4
    #> 3 2000-01-04 2000-01-04 6 2000-01-04 2000-01-04 6

<sup>Created on 2020-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
 
When using a vector dimension, the classes get indeed stripped off, as you showed. I guess this is another inconsistency in core R.

Still, my main point was that the error messages provided by dplyr were not particularly helpful in this case. If dplyr doesn't support non-atomic vectors/arrays (or something with a dimension) for certain data types, that's of course fine. However, the error message should state that there is a problem with the input data, but not refer to some functionality implemented in C that shouldn't be called as an R function. I mean, as a mere user, I have no idea what

    #> Error: `vec_cast.POSIXct.POSIXct()` is implemented at C level.
    #> This R function is purely indicative and should never be called.

means and what I can do about it. I certainly never called `vec_cast.POSIXct.POSIXct()`...

To be clear, I'm aware that this is very much an edge case. I do not even remember why I had added that dimension statement in the code that made me stumble over the error message - it isn't needed and gone by now. But I would still hope that good software issues error messages that point me to the actual problem.

**Comment by hadley** [comment]
Moved to https://github.com/r-lib/vctrs/issues/1290
