### ISSUE TITLE
After update, cant use any package

### ISSUE THREAD

**Issue by GabrielaCardenasF** [tidyverse/dplyr#5529]
I reinstalled R Studio. Now I can't load almost any package. I get this error:

Error: package or namespace load failed for ‘Hmisc’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so':
dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so, 6): Symbol not found: _inflateValidate
Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so (which was built for Mac OS X 10.13)
Expected in: /usr/lib/libz.1.dylib
in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so

**Comment by romainfrancois** [comment]
I don't understand how this relates to `dplyr` and/or how we can help here. Perhaps you can try to install `Hmisc` again ? You might otherwise get a more useful answer perhaps on community.rstudio.com
