### ISSUE TITLE
In rename() the order of the input vector for the renaming has changed

### ISSUE THREAD

**Issue by ChristineBlume** [tidyverse/dplyr#5531]
Previously, I was using the following code:

```r
data <- rename(data, c("V1" = "time", "V2" = "Expected Omission", "V3" = "ExpOmission_SE"))
```

Now, I receive an error message that the column "time" does not exist. If I run the following code, I receive the expected result. Counterintuitively, one now has to put the new vector name first and then the old one.

```r
data <- rename(data, c("time" = "V1", "Expected Omission" = "V2", "ExpOmission_SE" = "V3"))
```

**Comment by FelixErnst** [comment]
This also has additional implications.

Any package, which assumes, that rename from dplyr behaves like `rename` from base R in terms for the renaming scheme, such as the `S4Vectors` package from `BioC`, will make using dplyr so much harder.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
df <- 1:6
df %>% as.data.frame() %>% rename("b" = ".")
#>   b
#> 1 1
#> 2 2
#> 3 3
#> 4 4
#> 5 5
#> 6 6

library(S4Vectors)
#> Loading required package: stats4
#> Loading required package: BiocGenerics
#> Loading required package: parallel
#> 
#> Attaching package: 'BiocGenerics'
#> The following objects are masked from 'package:parallel':
#> 
#>     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
#>     clusterExport, clusterMap, parApply, parCapply, parLapply,
#>     parLapplyLB, parRapply, parSapply, parSapplyLB
#> The following objects are masked from 'package:dplyr':
#> 
#>     combine, intersect, setdiff, union
#> The following objects are masked from 'package:stats':
#> 
#>     IQR, mad, sd, var, xtabs
#> The following objects are masked from 'package:base':
#> 
#>     anyDuplicated, append, as.data.frame, basename, cbind, colnames,
#>     dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
#>     grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
#>     order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
#>     rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
#>     union, unique, unsplit, which, which.max, which.min
#> 
#> Attaching package: 'S4Vectors'
#> The following objects are masked from 'package:dplyr':
#> 
#>     first, rename
#> The following object is masked from 'package:base':
#> 
#>     expand.grid
df %>% as.data.frame() %>% rename("b" = ".")
#> Error in rename(., b = "."): Some 'from' names in value not found on 'x': b
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19041)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Germany.1252  LC_CTYPE=English_Germany.1252   
#> [3] LC_MONETARY=English_Germany.1252 LC_NUMERIC=C                    
#> [5] LC_TIME=English_Germany.1252    
#> 
#> attached base packages:
#> [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
#> [8] methods   base     
#> 
#> other attached packages:
#> [1] S4Vectors_0.26.1    BiocGenerics_0.34.0 dplyr_1.0.2        
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.30       magrittr_1.5     tidyselect_1.1.0 R6_2.4.1        
#>  [5] rlang_0.4.7      stringr_1.4.0    highr_0.8        tools_4.0.2     
#>  [9] xfun_0.17        htmltools_0.5.0  ellipsis_0.3.1   yaml_2.2.1      
#> [13] digest_0.6.25    tibble_3.0.3     lifecycle_0.2.0  crayon_1.3.4    
#> [17] purrr_0.3.4      vctrs_0.3.4      glue_1.4.2       evaluate_0.14   
#> [21] rmarkdown_2.4    stringi_1.5.3    compiler_4.0.2   pillar_1.4.6    
#> [25] generics_0.0.2   pkgconfig_2.0.3
```

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@hpages, @hadley, @mtmorgan

The intention behind the change might be admirable, but this has been a pain to debug and is really annoying.

Might I suggest keeping the old behavior for `rename` and introducing a new function name like `rename_column`? More to type, but I gladly type the seven additional letters to avoid the whole problem.

Any advice is much appreciated.

Felix

PS: Sorry for the bit of venting going on in the post.

**Comment by lionel-** [comment]
AFAICT the behaviour has never changed. It has always been `new = old`.

**Comment by lionel-** [comment]
ohhh you mean it has changed since plyr. In this case you're correct, we changed the behaviour in 2014 in the new dplyr package.

The advantage of the `new = old` syntax is that it makes `mutate()` and `select()` consistent. It's also consistent with `<-` where the new variable is on the left hand side. So this is a deliberate design decision.

**Comment by FelixErnst** [comment]
Thanks for the explanation.

This is really astonishing, that my Rmd files didn't complain earlier, when the change was so long ago. I am really not sure, what might have changed in the last couple of weeks, but I must have been using the `plyr` function for quite some time.

**Comment by hpages** [comment]
I see I was mentioned here, probably because I maintain S4Vectors. I don't know what `S4Vectors::rename()` does, I didn't add it. My take is to stay away from the verb because I can never remember the correct syntax (have to check the man page each time), probably because there are too many conflicting implementations around. I like my code to be readable so if there is the risk that my interpretation of what I read is the opposite of what the code does, then it's a no-go. Just my 2 cents.
