### ISSUE TITLE
slice_* need ellipsis::check_dots_used()

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#5540]

**Comment by hadley** [comment]
@romainfrancois can you do this one too? Let me know if you need more details.

**Comment by romainfrancois** [comment]
Oh. I missed this, `slice_head()`, `slice_tail()`, `slice_min()`, `slice_max()` and `slice_sample()` all use `ellipsis::check_dots_empty()` so I'm not sure what this is about ...

**Comment by hadley** [comment]
Oh maybe it was already done 😆
