### ISSUE TITLE
dplyr::filter() does not return an empty tibble when no entries match the logical conditions 

### ISSUE THREAD

**Issue by dariorrr** [tidyverse/dplyr#5546]
With R version 4.0.2 (and updated tidyverse package) I am having problems with the dply::filter() function applied to a tibble$column. When no entries/rows match the logical condition(s), R returns the following error message:

_"Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 0, 1"_

instead of an empty tibble like it did with previous versions.

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by romainfrancois** [comment]
@dariorrr can you comment with a reprex please ?
