### ISSUE TITLE
Feature suggestion: union_select()

### ISSUE THREAD

**Issue by nathaneastwood** [tidyverse/dplyr#5554]
I'm not sure if feature suggestions are accepted here but I couldn't see anything against it in the contributing guidelines. In my current line of work we generate multiple datasets from multiple processes. We eventually need to union these tables together however they typically have different columns or the columns might be in a different order. This might require some code like this:

```r
df1 %>%
  select(col1,  col2, col3) %>%
  union(df2 %>% select(col1, col2, col3)) %>%
  union(df3 %>% select(col1, col2, col3))
```

In a small example such as this, this is fine and sure, you could write a loop to do it. But this is actually what I did in my `sparkplugs::union_select()` function: https://github.com/nathaneastwood/sparkplugs/blob/master/R/union_select.R

I think this could be beneficial to {dplyr} and I wouldn't say that this is a domain specific problem? I guess the function interface might be different using tidyverse style, something more like

```r
union_select <- function(..., .cols = NULL, .all = TRUE) {}
``` 

though I don't claim to be an expert in your style guide.

**Comment by moodymudskipper** [comment]
I think you can do:

```
list(df1, df2, df3) %>%
  map_dfr(select, col1,  col2, col3) %>%
  distinct() 
```

**Comment by nathaneastwood** [comment]
Thanks @moodymudskipper. There are a couple of issues I see with this solution:

1. It introduces another dependency, `purrr`. Personally I do not know how the `purrr` API works as I have never found a valid use case for it.
2. It doesn't work with Spark (possibly databases as well): `Error: Argument 1 must be a data frame or a named atomic vector, not a tbl_spark/tbl_sql/tbl_lazy/tbl` (granted `sparklyr` imports `purrr` but this solution doesn't work regardless).

[My solution](https://github.com/nathaneastwood/sparkplugs/blob/master/R/union_select.R) avoids both of these problems.

**Comment by hadley** [comment]
I think in most cases I'd recommend `bind_rows()` followed by a `select()`. This is technically less performant, but I doubt it'll make much difference in practice, so I think this means that your proposal is a not good fit for this dplyr:  developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
