### ISSUE TITLE
coalesce fails when argument is a 1d-array

### ISSUE THREAD

**Issue by FrancoisGuillem** [tidyverse/dplyr#5557]
I have a table with a column that has been created by some python code using package `reticulate`. When I try to use `coalesce` on that column with last version of dplyr, I get the following error:
```
Can't coalesce matrices or arrays.
```
With a previous version of dplyr, I didn't have that error. After some investigation, I have found that the error comes from the fact that the column is of class array and has the "dim" attribute. So it fails because of the following test in the `coalesce` code:

```r
if (!is_null(attr(x, "dim"))) {
     abort("Can't coalesce matrices or arrays.")
}
```

Code to reproduce the issue:
```r 
x <- array(1:10)
coalesce(x, 0) # Does not work

# If we remove the "dim" attribute. it works
attr(x, "dim") <- NULL
coalesce(x, 0)
```

**Comment by courtiol** [comment]
@FrancoisGuillem, since {dplyr} v1.0, the package uses {vctrs} internally (a package handling operation on vectors).
The consequences is that {dplyr} has become stricter when it comes to variable class/types.
Here your `attr(x, "dim") <- NULL` turn the array into a vector and as {vctrs} can work with vectors it works.
But if you don't turn your input into a vector it does not work because {dplyr} is not designed to work with arrays (and I don't see why it should).
In your case, you should simply do:

```r
coalesce(as.numeric(x), 0)
```

**Comment by FrancoisGuillem** [comment]
Hello @courtiol , 

The code of `coalesce` is:
 ```r
function (...) 
{
    if (missing(..1)) {
        abort("At least one argument must be supplied.")
    }
    values <- list2(...)
    values <- vec_cast_common(!!!values)
    values <- vec_recycle_common(!!!values)
    x <- values[[1]]
    values <- values[-1]
    if (!is_null(attr(x, "dim"))) {
        abort("Can't coalesce matrices or arrays.")
    }
    if (is.data.frame(x)) {
        df_coalesce(x, values)
    }
    else {
        vec_coalesce(x, values)
    }
}
```

If I skip the test that fails and run directly the line `vec_coalesce(...)`, it works:

```r
x <- array(1:10)
values <- list(rep(0, 10))
dplyr:::vec_coalesce(x, values)
## [1]  1  2  3  4  5  6  7  8  9 10
```

An 1D-array is the same thing as a vector except it has the "dim" attribute, so I still think it should work in this specific case. I think that checking if there is more than one dimension should solve the issue:

```r 
 if (!is_null(attr(x, "dim")) || length(attr(x, "dim")) > 1) {
        abort("Can't coalesce matrices or arrays.")
    }
```

More generally, in a "phylosophical" point of view, arrays and matrices are simply vectors with a "dim" attribute, so I don't see why this kind of function should not work on them. Many R functions that accept vectors also accept arrays and matrices.
