### ISSUE TITLE
dplyr::if_else Behaviour and documentation mismatch.

### ISSUE THREAD

**Issue by antalk2** [tidyverse/dplyr#5561]
dplyr 1.0.0 if_else
Behaviour and documentation mismatch.

# Problem 1 Clarify "same type"?

> Description
> 
> Compared to the base ifelse(), this function is more strict.
> It checks that true and false are the same type.
> This strictness makes the output type more predictable, and makes it somewhat faster.

The statement "It checks that true and false are the same type." is
somewhat ambiguous. Is it meant as `base::typeof` or `rlang::type_of`
or in some other sense as suggested by "the same type and same class."
at the parameter description?

It does not check if two factors share the same levels.
(Maybe I should have guessed it from the Examples)

```
# Does this happily
if_else( c( TRUE, FALSE ),
         factor(c( "a", "b" ), levels=c("a","b","d")) ,
	 factor(c( "c", "d" )) )
```

```
# This raises a warning
if_else( c( FALSE, TRUE ),
         factor(c( "a", "b" ), levels=c("a","b","d")) ,
	 factor(c( "c", "d" )) )
```

Expected behaviour:  be consistent (if possible).

Considering the emphasis on type checking, might want to check
if factors share the same levels, unless it proves too costly.

# Problem 2 What types (for `true` and `false`) are expected (allowed)? 

> true, false	
> Values to use for TRUE and FALSE values of condition.
> They must be either the same length as condition, or length 1.
> They must also be the same type: if_else() checks that they have the same type and same class. 
> All other attributes are taken from true.

"Values to use" is vague. What kind of things are allowed? Apparently those that have `length`.
(And probably `[` or `[[` and corresponding assignment.)
So: vectors (yes), lists (yes), data.frames? (no, but already reported elsewhere), tibbles? (no), 
factors (yes)

More direct indications could be helpful.

```
if_else( c( TRUE, FALSE ),
         tibble( a=1, b=3 ),
         tibble( a=2, b=4 ) )
```

Expected: might have worked. (Does not)

Please clarify supported types in the documentation.

# Problem 3 "same class"?

> They must also be the same type: if_else() checks that they have the same type and same class. 

This suggests true and false may have a class attribute.

```
x = c(1,3); class(x)='xc'
y = c(2,4); class(y)='xc'
if_else( c(TRUE,FALSE), x, y )
```
Error: "`true` must have class `numeric`, not class `xc`."

----

Maybe only list-based classes are expected? (No, they do not work either)

```
x = list(1,3); class(x)='xc'
y = list(2,4); class(y)='xc'
if_else( c(TRUE,FALSE), x, y )
```
Error: "`true` must have class `numeric`, not class `xc`."

----

Expected behaviour:  class attribute of result being 'xc'.
   Alternatively: clarification of what is expected of the inputs `true` and `false`

# Problem 4 "All other attributes are taken from true."

> All other attributes are taken from true.

They are not copied. At least not usually:

```
x = c(1,3); attr(x, 'xatt' ) = 1;
y = c(2,4); attr(y, 'yatt' ) = 2;
str(if_else( c(TRUE,FALSE), x, y ))
```
(No attribute in result)
Expected: attr(x,'xatt')==1

---

The names attribute shows different bad behaviour:
it is not missing, but filled with NA values.

 ```
x = list(a=1,b=3)
y = list(a=2,b=4)
if_else( c(TRUE,FALSE), x, y )
```
Got: name(res) is c(NA,NA)
Expected: c("a","b")

---

I guess these may be due to the line

```
out <- true[rep(NA_integer_, length(condition))]
```
in the implementation of `if_else`.

According to `help("[")`:
"Subsetting (except by an empty index) will drop all attributes except
names, dim and dimnames."

Expected behaviour:  "All other attributes are taken from true."
    Alternatively: document what actually happens with the attributes.

**Comment by antalk2** [comment]
Types handled by if_else

# Positive examples

Date and time seems to work (type preserved)

```
if_else( c( TRUE, FALSE ),
        rep(Sys.Date(),2),
        rep(Sys.Date()+1,2) )
```

```
if_else( c( TRUE, FALSE ),
         rep(Sys.time(),2),
         rep(Sys.time()+1,2) )
```

# Negative example (stats::ts)

```
x=ts( rep(1,2), 1, frequency=1 )
typeof(x)
y=ts( rep(2,2), 99, frequency=99 )

if_else( c( TRUE, FALSE ), x, y ) # error `true` must have class `numeric`, not class `ts`.
ifelse(  c( TRUE, FALSE ), x, y ) #  num [1:2] 1 2
``

**Comment by hadley** [comment]
These are all good questions and are poorly defined with the current implementation — that's why we're changing to the implementation in `funs::if_else()`, which is based on the solid theoretical foundation provided by vctrs.
