### ISSUE TITLE
Feature suggestion: endlabelled.as.numeric() function

### ISSUE THREAD

**Issue by BernhardClemm** [tidyverse/dplyr#5562]
I hope this is the right place to suggest a feature.

People working with survey data will often encounter variables that are meant to be numeric, but come in factor or character format because of end-labelled scales in questionnaires. Imagine a question "Do you agree that...?" with a response scale with options "1 - do not agree at all", "2", "3", "4", "5 - Completely agree". A common way to recode this into a numeric variable might be:

```r
data <- data %>%
  mutate(var_num = case_when(var == "1 - do not agree at all" ~ 1,
                                                   var == "2" ~ 2,
                                                   var == "3" ~ 3,
                                                   var == "4" ~ 3,
                                                   var == ""5 - Completely agree" ~ 5))
```
This gets tiresome if the numeric information is always contained in the levels. I wrote a short function that just takes the first (or last, depending of the specification) number and turns into a numeric value (I am sure this function could be improved!):

```
endlabelled.as.numeric <- function(col, which_number = "first") {
  if (which_number == "first") {
    vector <- as.numeric(str_extract(col, "[0-9]+"))
  } else if (which_number == "last") {
    vector_list <- sapply(str_extract_all(col, "[0-9]+"), tail, 1)
    vector <- as.numeric(as.character(vector_list))
  }
  return(vector)
}
```
This would simplify my problem as follows:
```
data <- data %>%
  mutate(var_num = endlabelled.as.numeric(var))
```

**Comment by courtiol** [comment]
@BernhardClemm, if that does not exist in {haven}, that could be a feature for this package, not IMO for {dplyr}.
{haven} has been specifically designed to handle labelled variable --> https://github.com/tidyverse/haven

**Comment by BernhardClemm** [comment]
@courtiol many thanks, posted it over there!
