### ISSUE TITLE
support for `mutate(across())` where `.fns` returns a data.frame

### ISSUE THREAD

**Issue by BertrandSim** [tidyverse/dplyr#5563]
When `mutate` is called with a data.frame as an _unnamed_ argument, multiple columns are added. This is a useful feature of dplyr.

However, there seems to be no natural way to extend this idea with `mutate(across())`

---

Here is a reproducible example containing my attempt:
```
library(dplyr)
library(magrittr)

dat <- data.frame(x1=c(1,2,3), x2=c(4,5,6))
dat2 <- dat %>% mutate(across(c(x1, x2), ~ data.frame(m = min(.x), M = max(.x))))
```

The output of dat2 is 
```
> dat2
  x1.m x1.M x2.m x2.M
1    1    3    4    6
2    1    3    4    6
3    1    3    4    6

> glimpse(dat2)
Rows: 3
Columns: 2
$ x1 <df[,2]> <data.frame[3 x 2]>
$ x2 <df[,2]> <data.frame[3 x 2]>
```
, which contain nested data.frames.

What I was hoping for was 

```
  x1 x2 x1_m x1_M x2_m x2_M
1  1  4    1    3    4    6
2  2  5    1    3    4    6
3  3  6    1    3    4    6
```

Of course, `mutate(across(c(x1, x2), ~ data.frame(...)))` does not work as expected, since it is akin to passing a data.frame as a _named_ argument.

While one can workaround the issue and `tidyr::unpack()` dat2 into a regular data.frame, 
It would be good if one can obtain a regular data.frame just by using something along the lines of `mutate(across(.cols , .fns = ~ data.frame(...)))`.

**Comment by BertrandSim** [comment]
@courtiol Sorry for the late reply. While using a list of functions works in the simple example that I gave, the actual scenario is usually more complicated. In such scenarios, how could I use a single function that returns multiple values (or columns) with across()?

**Comment by courtiol** [comment]
For the result of across not to overwrite the input in this case, you should actually name the new columns using `.names =` (I am surprised this is needed, but it seems to be the case --> @romainfrancois ?).

Yet, as you can see below, multiple columns are added based on a single function.
I think this thus solves your issue @BertrandSim.

The content of such new columns is however still nested.
Why?
Because you run on multiple columns a function creating itself multiple columns, so you have 2 levels of nestedness (if that word exists). I am not surprised by such a behavior because I imagine that coming up with unpacking rules that work recursively brings a whole new level of complexity.

```r
    library(dplyr)
    dat <- tibble::tibble(x1 = c(1, 2, 3), x2 = c(4, 5, 6))

    dat2 <- dat %>% 
      mutate(across(c(x1, x2), ~ list(c(min = min(.x), max = max(.x))), .names = "stats_{.col}"))

    #> # A tibble: 3 x 4
    #>      x1    x2 stats_x1  stats_x2 
    #>   <dbl> <dbl> <list>    <list>   
    #> 1     1     4 <dbl [2]> <dbl [2]>
    #> 2     2     5 <dbl [2]> <dbl [2]>
    #> 3     3     6 <dbl [2]> <dbl [2]>

    glimpse(dat2)
    #> Rows: 3
    #> Columns: 4
    #> $ x1       <dbl> 1, 2, 3
    #> $ x2       <dbl> 4, 5, 6
    #> $ stats_x1 <list> [<1, 3>, <1, 3>, <1, 3>]
    #> $ stats_x2 <list> [<4, 6>, <4, 6>, <4, 6>]
```

**Comment by romainfrancois** [comment]
`across()` deals with unpacking in the case of multiple functions, but not in this case, as it might be legit to get a data frame column for each result. 

unpacking after the `mutate()` sort of works but you have to be careful about the names, instead one thing you can do is `unpack()`  the result of `across()` which just happens to be a data frame with 2 data frame columns, something like this: 

``` r
library(dplyr, warn.conflicts = FALSE)

unpackross <- function(...) {
  out <- across(...)
  tidyr::unpack(out, names(out), names_sep = "_")
}

dat <- data.frame(x1=c(1,2,3), x2=c(4,5,6))
dat %>% 
  mutate(unpackross(c(x1, x2), ~data.frame(m = min(.x), M = max(.x))))
#>   x1 x2 x1_m x1_M x2_m x2_M
#> 1  1  4    1    3    4    6
#> 2  2  5    1    3    4    6
#> 3  3  6    1    3    4    6
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by BertrandSim** [comment]
This works well. Thanks!
