### ISSUE TITLE
rename_with() is not quite consistent

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#5564]
The arguments referring to the selected columns and to the function(s) used to perform transformation are ordered differently in `rename_with()` (function then columns) and in `across()` (columns then functions).

~By default `.col = everything()` for both and I find the functions similar in spirit (although differing in scope), hence I think a reordering (or something more radical; see below) would make things more tidy.~

~I would guess that the flexible `across()` is already widely used but perhaps `rename_with()` not so much, so if reordering, doing so in `rename_with()` makes probably more sense than in `across()` (I also prefer the ordering used in `across()`).~

**Alternatively**, perhaps `rename()` could accept `across()` in its `...` as `mutate()`/`summarize()`/`filter()` do.
~Then there would no longer be a need for `rename_with()`.~
This latter solution would improve the consistency across function more generally.
That seems clearly the best option from a user perspective, but I don't know how much work that would represent under the hood... (I did not check how other functions do handle `across()`).

Here is an illustration:

```r
## current syntax
iris %>%
  rename_with(toupper, !where(is.numeric))

## proposition 1
iris %>%
  rename_with(!where(is.numeric), toupper)

## proposition 2
iris %>%
  rename(across(!where(is.numeric), toupper))

## proposition 2 would match the syntax of other functions best
iris %>%
  mutate(across(!where(is.numeric), toupper))
```

**Comment by lionel-** [comment]
This difference is intentional because the most common use case for `rename_with()` is to apply the function on all names, eg. `df %>% rename_with(toupper)`.

Maybe we should move `...` to the left of `.cols` to force named argument passing:

```r
iris %>%
  rename_with(toupper, .cols = !where(is.numeric))
```

This might solve the visual ambiguity introduced by the different order. Probably not worth the change though.

**Comment by courtiol** [comment]
Thanks @lionel- , I understand the rational. Don't you think that it would still be great if `rename()` would understand `across()`?
To rename all columns, one would thus do:
```r
iris %>%
  rename(across(fn = toupper))
```

**Comment by hadley** [comment]
It would be great if `rename()` could work like that, but it can't because it already uses select semantics, and `across()` relies on `mutate()` semantics.
