### ISSUE TITLE
slice_tail errors out with Error: `...` is not empty.

### ISSUE THREAD

**Issue by vzemlys** [tidyverse/dplyr#5567]
`slice_tail` produces an error.  My CI job with docker container errored out in the following job https://gitlab.com/vzemlys/covid19lt/-/jobs/797061303.  

Have succesfully reproduced on the docker image (rocker/verse:latest) on local machine. 

---

Reproducible eample
```r
data.frame(x=rnorm(100),y=rnorm(100)) %>% slice_tail(1)
```

The result is the following: 

```
Error: `...` is not empty.

We detected these problematic arguments:
* `..1`

These dots only exist to allow future extensions and should be empty.
Did you misspecify an argument?
```

The sessionInfo() produces the following:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testthat_2.3.2  tidyr_1.1.2     dplyr_1.0.2     lubridate_1.7.9 gert_1.0.1     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        rstudioapi_0.11   magrittr_1.5      tidyselect_1.1.0 
 [5] R6_2.4.1          rlang_0.4.7       fansi_0.4.1       tools_4.0.2      
 [9] sys_3.4           utf8_1.1.4        cli_2.0.2         askpass_1.1      
[13] ellipsis_0.3.1    openssl_1.4.3     assertthat_0.2.1  tibble_3.0.3     
[17] lifecycle_0.2.0   crayon_1.3.4      purrr_0.3.4       vctrs_0.3.4      
[21] credentials_1.3.0 glue_1.4.2        compiler_4.0.2    pillar_1.4.6     
[25] generics_0.0.2    pkgconfig_2.0.3  
```

There is a slight chance that some combination of my loaded packages causes this.  Happy to provide more details if needed.

**Comment by courtiol** [comment]
You need to write `slice_tail(n = 1)`, this is because the second argument after the data provided by the pipe is `...` and is there to define columns in `slice()`. Only the third argument is the one expecting the number of rows. So if not specifying `n = `, the function thinks you are providing something to the argument `...` but for slice_tail you should not.

**Comment by hadley** [comment]
Thanks @courtiol!

**Comment by AlbertRapp** [comment]
@courtiol Can you maybe elababorate why it is useful that one has to specify `n = 1`? I am trying to come up with an explanation for my students why this is indeed a good/necessary behavior but it still feels unnatural.

**Comment by courtiol** [comment]
It is not useful, just necessary because the arguments `...` that comes before `n` would otherwise capture the input.

This is a very general feature of how arguments work in function calls:
```r
foo <- function(..., n) print(n)
foo(1)
Error in print(n) : argument "n" is missing, with no default
```

In general, `...` are put at the end of the argument list to avoid this problem, but not in {dplyr} since they use `...` as a trick to capture any column name.

**Comment by AlbertRapp** [comment]
Couldn't the `...` argument be moved to the end of `slice_*` then?. After all, I don't see how `...` is of advantage within these functions but it potentially confuses first time users.

**Comment by hadley** [comment]
The dots are deliberately early to force you to spell out the `n`. This keeps usage more consistent across the full family of `slice_` functions

**Comment by AlbertRapp** [comment]
What is a use case of `...` within the `slice_` functions? One function that explicitly uses `...` is `slice()` but this function does not use `n = `. All other `slice_` functions do not really need `...` frequently but are enforced to be called via `n = `. 

At this point, I can see that we have consistency but for what sake? It just feels more practical to me to have `n` and `prob` come before `...` as the former two arguments are used way more often than the latter.

**Comment by courtiol** [comment]
It is useful to be able to pass variable names for some of the slice functions:
```r
library(dplyr)
iris %>%
  slice_max(Sepal.Length, n = 2)
```

**Comment by AlbertRapp** [comment]
What you are refering to is `order_by`, i.e.
`
library(dplyr)
iris %>%
  slice_max(order_by = Sepal.Length, n = 2)
`
In fact, the `...` cannot be used for anything right now. Hence the error "These dots only exist to allow future extensions and should be empty." So, I guess the question is: Is there any future extension planned that needs these dots? And if so, do these extensions need the dots to be at the second position? 

For instance `pull()` is also a `dplyr` function but places the `...` at the end of the function call, so maybe the same could be done for the `slice_` functions?
