### ISSUE TITLE
problem with dplyr::filter

### ISSUE THREAD

**Issue by JLYJabc** [tidyverse/dplyr#5570]
I have a df of timestamps and ids. There are multiple timestamps pr Id,

I want to filter the df by a date and then keep one unique ID.

However, I get the wrong results when I put the two requirements into the same filter compared with if I pipe the result into a new filter()

The result is sometimes the same so I have made a loop to run the comparisson 500 times. I find that the result is only identical about 100 times out of 500 times. (i'm struggeling to get consistent results with set.seed, so I used this quirky approach).

I'm running dplyr 1.0.2 with R: 4.0.2

I guess that the result should be the same always?

```r
num <- 1000
count <- 0
for(i in 1:500){

library(magrittr)
x <- tibble::tibble(
  id = LETTERS[rbinom(num, 25, 0.50)+1],
  timestamp = Sys.Date() - rbinom(num, 180, 0.50))

x1 <- x %>% 
  dplyr::filter(
    timestamp < as.Date("2020-08-01"),
    !duplicated(id))

x2 <- x %>% 
  dplyr::filter(
    timestamp < as.Date("2020-08-01")) %>% 
  dplyr::filter(
    !duplicated(id))

if(isTRUE(dplyr::all_equal(x1, x2))) count <- count+1

}

```

**Comment by moodymudskipper** [comment]
This is normal to have different results, these don't do the same thing.

In the first call duplicates are flagged looking at the unfiltered dataset, in the second case on the dataset filtered by timestamp. 

You might be thinking that filters are applied in sequence, as transformations are applied in sequence with mutate. However with filter using several conditions is like using `&` between them.

**Comment by JLYJabc** [comment]
Ah I see, thanks for the answer. Rereading the documentation I also found this described there. 

I do find this confusing, however, so if others express similar experiences it might be worth considering?

Thanks for all the great work, dplyr-people!
