### ISSUE TITLE
In summarise(), assigning variable a vector behaves as mutate() instead of throwing error

### ISSUE THREAD

**Issue by ssp3nc3r** [tidyverse/dplyr#5571]
summarise() behaves as mutate() when variable assigned a vector. I believe it should, instead, error.

dplyr version 1.0.2

```r
library(dplyr)
mtcars %>% group_by(am) %>% summarise(n = mpg)
```

**Comment by pedrocava** [comment]
Maybe returning the vector as a single element in a list (to enforce group/row ratios) and issue a warning suggesting revisions and a possible semantic error?

**Comment by lotard** [comment]
Same here, I think it's an issue of a recent version, it would error on this, for example:
```
tibble(group = c('a','a'), value = c(1,2)) %>% 
  group_by(group) %>%
  summarise(result = unique(value))
```
Now it just returns:
```
`summarise()` regrouping output by 'group' (override with `.groups` argument)
# A tibble: 2 x 2
# Groups:   group [1]
  group result
  <chr>  <dbl>
1 a          1
2 a          2
```

**Comment by romainfrancois** [comment]
This is a feature, `summarise()` can now handle results that are not size 1. 

It's useful for e.g. cases like: 

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  group_by(am) %>% 
  summarise(mpg = range(mpg))
#> `summarise()` regrouping output by 'am' (override with `.groups` argument)
#> # A tibble: 4 x 2
#> # Groups:   am [2]
#>      am   mpg
#>   <dbl> <dbl>
#> 1     0  10.4
#> 2     0  24.4
#> 3     1  15  
#> 4     1  33.9
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by romainfrancois** [comment]
Should we have an additional argument that would control whether we only allow size 1 results ? @hadley

**Comment by hadley** [comment]
I don't think we need to optionally error here. It's a bit confusing at first, but I'm pretty confident that the balance of usability lies with keeping the current behaviour.
