### ISSUE TITLE
group_split(): Reorders groups alphanumerically (Request - Preserve Group Order)

### ISSUE THREAD

**Issue by mdancho84** [tidyverse/dplyr#5575]
Love the `group_split()` function. It's a great way to simplify splitting. But, I continuously run into debugging errors because it reorders the splits alphanumerically. Should this be the default behavior or should there at least be an option to preserve the grouping order?

## Example - Reorders the Groups

``` r
library(dplyr)
library(tibble)

# Sample data
tbl <- tibble(
    group = c("c", "a", "b"),
    value = c(3, 1, 2)
) %>%
    group_by(group)

# Group order is c, a, b
tbl
#> # A tibble: 3 x 2
#> # Groups:   group [3]
#>   group value
#>   <chr> <dbl>
#> 1 c         3
#> 2 a         1
#> 3 b         2

# Group split order is a, b, c
tbl %>%
    group_split()
#> <list_of<
#>   tbl_df<
#>     group: character
#>     value: double
#>   >
#> >[3]>
#> [[1]]
#> # A tibble: 1 x 2
#>   group value
#>   <chr> <dbl>
#> 1 a         1
#> 
#> [[2]]
#> # A tibble: 1 x 2
#>   group value
#>   <chr> <dbl>
#> 1 b         2
#> 
#> [[3]]
#> # A tibble: 1 x 2
#>   group value
#>   <chr> <dbl>
#> 1 c         3
```

<sup>Created on 2020-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
It's already "too late" when you are in `group_split()`, i.e. the data is already in that order: 

``` r
library(dplyr, warn.conflicts = FALSE)

# Sample data
tbl <- tibble(
  group = c("c", "a", "b"),
  value = c(3, 1, 2)
) %>%
  group_by(group)

group_data(tbl)
#> # A tibble: 3 x 2
#>   group       .rows
#> * <chr> <list<int>>
#> 1 a             [1]
#> 2 b             [1]
#> 3 c             [1]
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Depending on the endgame here, you might be able to work with `mutate()` + `across()` instead of `group_split()`

**Comment by mdancho84** [comment]
Ok thanks a lot for your input. I'm instructing users to use as_factor() to maintain the order. This was just not intuitive for me but is a simple solution. Here's the video where I show students how easy it is to make a linear regression table with group_split(). Make a Linear Regression Table w/ Group Split + Map | R-Tip 011 https://youtu.be/wj_AAs4VC8M

The group_split() function is a big help.

**Comment by StefKirsch** [comment]
> Ok thanks a lot for your input. I'm instructing users to use as_factor() to maintain the order. This was just not intuitive for me but is a simple solution. Here's the video where I show students how easy it is to make a linear regression table with group_split(). Make a Linear Regression Table w/ Group Split + Map | R-Tip 011 https://youtu.be/wj_AAs4VC8M
> 
> The group_split() function is a big help.

Note that you have to use forcats::as_factor(). base::as.factor will still sort alphanumerically.

It also works when you are grouping by several variables.

```r
library(dplyr)
library(ggplot2) # for dataset mpg
library(forcats)
library(purrr)

# Group Split
mpg_it <- mpg |> 
  map_df(rev) |> # reverse order so volkswagen is at the top
  mutate(
    manufacturer = as_factor(manufacturer),
    model = as_factor(model)
    ) |>
  group_by(manufacturer, model) |> 
  group_split()
```
