### ISSUE TITLE
possible improvement of documentation message on colwise-select

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/dplyr#5578]
One can read in `?select_if`:

> These functions were superseded because mutate_if() and friends were superseded by across(). select_if() and rename_if() already use tidy selection so they can't be replaced by across() and instead we need a new function.

This message (*we need a new function*) makes mi think that some `across`-like function will be developed to replace `select_if` and `rename_if` functionality. But in fact, there is already `where` as later examples in same document show:
```r
# Selection drops unselected variables:
mtcars %>% select_if(is_whole, toupper)
# ->
mtcars %>% select(where(is_whole)) %>% rename_with(toupper)
```

So by *we need a new function* should I understand that I have to split `select_if` in 2 functions as above with `select` and `rename_with`? But, what if I do not want to use any function instead of `toupper`? It is enough for me to use `select(where(~...))`.

If I do not understand wrongly the message, I believe mentioning `where` in that paragraph would improve the message. Otherwise I am not sure of what do you mean; should I expect a future new function?

Thank you!

**Comment by romainfrancois** [comment]
One thing `across()` brings to the `summarise()` and `mutate()` world is that one can do e.g.

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  summarise(
    across(mpg:disp, mean), 
    across(hp:drat, max)
  )
#>        mpg    cyl     disp  hp drat
#> 1 20.09062 6.1875 230.7219 335 4.93
```

<sup>Created on 2020-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

There's no equivalent thing for `select()`, i.e. something that would put the `_if` "inside" the call, something like this (please don't mind the shady implementation): 

``` r
library(dplyr, warn.conflicts = FALSE)
library(tidyselect)
ibrary(rlang)
library(purrr)
library(vctrs)

rebrand <- function(fn, expr) {
  list(fn = rlang::as_function(fn), expr = enexpr(expr))
}

pick <- function(.data, ...) {
  qs <- enquos(...)
  env <- caller_env()
  
  loc <- vec_c(!!!map(qs, function(q) {
    expr <- quo_get_expr(q)
    rename <- identity
    if (is_call(expr, "rebrand")) {
      x <- eval_bare(expr)
      expr <- x$expr
      rename <- x$fn
    }
    res <- tidyselect::eval_select(expr, .data)
    names(res) <- rename(names(res))
    res
  }))
  
  loc <- dplyr:::ensure_group_vars(loc, .data, notify = TRUE)
  dplyr:::dplyr_col_select(.data, loc, names(loc))
}

as_tibble(mtcars) %>% 
  pick(
    rebrand(toupper, mpg:disp), 
    rebrand(~substr(., 1, 2), gear:carb)
  )
#> # A tibble: 32 x 5
#>      MPG   CYL  DISP    ge    ca
#>    <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160      4     4
#>  2  21       6  160      4     4
#>  3  22.8     4  108      4     1
#>  4  21.4     6  258      3     1
#>  5  18.7     8  360      3     2
#>  6  18.1     6  225      3     1
#>  7  14.3     8  360      3     4
#>  8  24.4     4  147.     4     2
#>  9  22.8     4  141.     4     2
#> 10  19.2     6  168.     4     4
#> # … with 22 more rows
```

<sup>Created on 2020-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
At this point, we're not planning any major changes to `select()` or `rename_with()`, but we'll certainly keep thinking about it.
