### ISSUE TITLE
Why all_equal() is marked as "Questioning lifecycle"

### ISSUE THREAD

**Issue by GitHunter0** [tidyverse/dplyr#5585]
dplyr::all_equal() provides a very useful functionality for a variety of purposes, it would be a pity to lose that function. 
Any particular reason why it is marked as "Questioning lifecycle" and is there a chance that it will get removed from dplyr?
Thank you.

**Comment by romatik** [comment]
I'm not going to speak for the maintainers of `dplyr` about why this specific function is in questioning lifecycle, but I can at least suggest this package - https://github.com/r-lib/waldo - that is likely a replacement for this specific functionality.

**Comment by GitHunter0** [comment]
@romatik , thank you for the hint! `waldo` seems very promising

**Comment by hadley** [comment]
I don't think `all_equal()` is particularly well designed — I now believe that if you want to ignore row or column order, you need to do so explicitly. Having it happen automatically leads to too many subtle problems. It's unlikely to be remove in the near future, but I don't really like it any more and it doesn't seem like a particularly good fit for dplyr, so I wouldn't rely on it being around in the long run.

**Comment by GitHunter0** [comment]
Thank you @hadley , I will use `waldo` instead.
