### ISSUE TITLE
bind_cols giving empty tibble if first argument has no rows if subsequent tibble's have 1 row

### ISSUE THREAD

**Issue by MarkEdmondson1234** [tidyverse/dplyr#5590]
I'm using dplyr_1.0.2.

I have two tibbles that have a data source via an API.  In some cases, the first tibble may have no rows, but the second has one row.  When I `bind_cols()` the tibbles, the resulting tibble has no rows.

I expect that the result should include the same number of rows as the second tibble, not 0 rows.

---

Reprex

```r
a <- tibble()
b <- tibble(a = c(1), b=c(2))
dplyr::bind_cols(a,b)
# A tibble: 0 x 2
# … with 2 variables: a <dbl>, b <dbl>

b
# A tibble: 1 x 2
#      a     b
#  <dbl> <dbl>
#1     1     2

a
# A tibble: 0 x 0
```

**Comment by romainfrancois** [comment]
This is from `vctrs` , which considers the common size to be 0: 

``` r
library(dplyr, warn.conflicts = FALSE)

a <- tibble()
b <- tibble(a = c(1), b=c(2))
dplyr::bind_cols(a,b)
#> # A tibble: 0 x 2
#> # … with 2 variables: a <dbl>, b <dbl>
vctrs::vec_cbind(a, b)
#> # A tibble: 0 x 2
#> # … with 2 variables: a <dbl>, b <dbl>
vctrs::vec_size_common(a, b)
#> [1] 0
```

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by lionel-** [comment]
This is the expected recycling rule in r-lib and the tidyverse: Collections of size 1 are always recycled to the size of other collections. Here the other collection is a zero row data frame, so you get a zero-row result. This is also how python broadcasting works.

**Comment by romainfrancois** [comment]
Thanks @lionel-. Closing this now.

**Comment by brianmsm** [comment]
Would it be possible to add an argument like `na.rm = TRUE`, or something similar?
