### ISSUE TITLE
Feature request: increasing the scoping for n and prop  slice_head/tail() arguments

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#5600]
The arguments `n =` and `prop =` in slice_head/tail cannot refer to columns in the table or to dplyr functions and yet this could be useful.

Consider the following example:

``` r
library(dplyr, warn.conflicts = FALSE)
iris2 <-  slice(iris, -c(6:50)) 

iris2 %>%
  group_by(Species) %>%
  slice_head(prop = 0.05)
#> # A tibble: 4 x 5
#> # Groups:   Species [2]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>     
#> 1          7           3.2          4.7         1.4 versicolor
#> 2          6.4         3.2          4.5         1.5 versicolor
#> 3          6.3         3.3          6           2.5 virginica 
#> 4          5.8         2.7          5.1         1.9 virginica
```
Here the species setosa is missing because there are less than 20 (=1/0.05) individuals in iris2.
That's OK but someone may still want to see one row in this case.
For this we could computation a value `z` to feed to `n = `:

``` r
iris2 %>%
  group_by(Species) %>%
  mutate(z = max(c(1, floor(0.05 * n()))))
#> # A tibble: 105 x 6
#> # Groups:   Species [3]
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species        z
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>      <dbl>
#>  1          5.1         3.5          1.4         0.2 setosa         1
#>  2          4.9         3            1.4         0.2 setosa         1
#>  3          4.7         3.2          1.3         0.2 setosa         1
#>  4          4.6         3.1          1.5         0.2 setosa         1
#>  5          5           3.6          1.4         0.2 setosa         1
#>  6          7           3.2          4.7         1.4 versicolor     2
#>  7          6.4         3.2          4.5         1.5 versicolor     2
...
```

Unfortunately, this is not possible because slice_min/max can neither refer to `z` nor `n()`:

``` r
iris2 %>%
  group_by(Species) %>%
  mutate(z = max(c(1, floor(0.05 * n())))) %>%
  slice_head(n = z)
#> Error in check_slice_size(n, prop): object 'z' not found

iris2 %>%
  group_by(Species) %>%
  slice_head(n = max(c(1, floor(0.05 * n()))))
#> Error: `n()` must only be used inside dplyr verbs.
```
Referring to `z` may not be ideal since the length of `z` is `n()` and not `1`, but the latter syntax using `n=` could be nice.

An alternative, less general, but solving this particular case, could also be to allow users to set both `n=` and `prop=` and in such case to consider the largest value.

Of course, workaround exist...:

``` r
library(dplyr, warn.conflicts = FALSE)
iris2 <-  slice(iris, -c(6:50)) 
iris2 %>%
  group_by(Species) %>%
  filter(row_number() <=  max(c(1, floor(0.05 * n()))))
#> # A tibble: 5 x 5
#> # Groups:   Species [3]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>     
#> 1          5.1         3.5          1.4         0.2 setosa    
#> 2          7           3.2          4.7         1.4 versicolor
#> 3          6.4         3.2          4.5         1.5 versicolor
#> 4          6.3         3.3          6           2.5 virginica 
#> 5          5.8         2.7          5.1         1.9 virginica
```

**Comment by hadley** [comment]
I agree that it would be useful, but when I implemented these, I deliberately chose to keep the scope very narrow because otherwise the implementation becomes complicated and (e.g) the translation to SQL becomes v. complex.

**Comment by peranti** [comment]
@hadley, currently, the documentation for `prop` says 

>  If the proportion of a group size does not yield an integer number of rows, the absolute value of prop*nrow(.data) is rounded down.

Would it be possible to take the ceiling value (e.g., 13) when it is higher than half (e.g., 12.85) rather than the floor value (12), similar to the `round()` behaviour in base R?
