### ISSUE TITLE
`dplyr::select()` reorders attribute elements of data frame

### ISSUE THREAD

**Issue by stufield** [tidyverse/dplyr#5603]
Performing `dplyr::select()` on a data frame reorders the basic elements of the data frame attributes. In the pseudo-reprex below, the `names` element is moved to the final position once modified as a result of removing `b`.

```
foo <- data.frame(a = 4, b = 100, c = 0.5)
attributes(foo)$new <- "cool stuff"
names(attributes(foo))
bar <- dplyr::select(foo, -b)
names(attributes(bar))
```

This makes comparison of attributes (beyond the expected different `names` element) difficult. Suggest not only preserving attributes, but also preserving their order to facilitate before/after comparison? (particularly of 'added' attributes like `new` above).

I *think* this is a different issue from actually preserving attributes mentioned in #5294

caveat: I'm using `dplyr v0.8.5` so untested in the current dev version (maybe no longer an issue?)

**Comment by lionel-** [comment]
Can you please update your packages to the latest CRAN version before posting please? Also can you please create your reprexes with the `reprex` package, so the output of your R code is included in your report?

AFAICT on the latest version the new attribute is not retained.

```r
foo <- data.frame(a = 4, b = 100, c = 0.5)
attributes(foo)$new <- "cool stuff"
names(attributes(foo))
#> [1] "names"     "class"     "row.names" "new"

bar <- dplyr::select(foo, -b)
names(attributes(bar))
#> [1] "names"     "row.names" "class"
```

Note that attributes are technically unordered. Preserving the order is nicer but not required. Also note that your attributes are not guaranteed to be preserved unless you make a class and implement the relevant methods for it. If a new class is not in scope for your case, it's better to use some other way for tracking metadata.

**Comment by stufield** [comment]
Thanks @lionel- , yes writing your own class-specific methods around the `dplyr` generic seems a perfectly reasonable solution, for both maintaining the attribute set and ordering. I just wanted to have this issue available so others who run into it have a solution they can point to. Thank you!
