### ISSUE TITLE
cur_group cannot be used inside group_modify

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/dplyr#5604]
Trying to use `cur_group()` inside `group_modify` produces the paradoxical ``Error: `cur_group()` must only be used inside dplyr verbs``.

Minimal reprex:
```r
library(dplyr)
mtcars %>%
  group_by(cyl) %>%
  group_modify(~ head(.x, as.integer(cur_group())))
Error: `cur_group()` must only be used inside dplyr verbs.
Run `rlang::last_error()` to see where the error occurred.
```

PS: It is interesting that, however one can do:
```r
mtcars %>%
  nest_by(cyl) %>%
  mutate(data = list(head(data, as.integer(cur_group()))))
```

**Comment by romainfrancois** [comment]
I understand the message is confusing, but `group_modify()` is an experimental function, and I would argue the alternative of using `summarise()` is better. 

In the meantime, getting the data for the current group is what `.y` does in `group_modify()`.

**Comment by iago-pssjd** [comment]
> I would argue the alternative of using `summarise()` is better.

It was just an example. The code I was trying is quite more complex.

> In the meantime, getting the data for the current group is what `.y` does in `group_modify()`.

I will try again with `.y`.

Thank you!
