### ISSUE TITLE
group_nest() VS group_by() %>% nest()  

### ISSUE THREAD

**Issue by dariorrr** [tidyverse/dplyr#5606]
This issue is more a clarification than a real problem.
I am used to nest tibbles using the `group_by()` function followed by the `nest()` function. I have recently learned that the same output can aslo be achieved using  the `group_nest()` function, which is more concise. 

However, when comparing the `class()` of the two nested columns, they are not exactly the same:

```r
library(tidyverse)

nst <- iris %>% 
  group_by(Species) %>% 
  nest()

class(nst$data)
#> [1] "list"
```

```r
library(tidyverse)

grp_nst <- iris %>% 
  group_nest(Species)

class(grp_nst$data)
#> [1] "vctrs_list_of" "vctrs_vctr"    "list"

```

Based on this, is one way better than the other for nesting tibbles?

**Comment by romainfrancois** [comment]
It should not be an important difference. Returning a `vctrs_list_of` allows us to declare that all elements of the list have the same type. But it should be the same data.

**Comment by stephematician** [comment]
I came across a problem with this when binding rows from data.frames constructed in two different ways. Using dplyr 1.0.7. As a minimal example:

```r
A <- tibble(x=1, y=list(tibble(z=1)))
B <- tibble(x=3, z=4) %>% group_by(x) %>% group_nest(.key='y')
bind_rows(A, B)
```

I get the following result

    Error: Can't combine `..1$y` <list> and `..2$y` <list_of<tbl_df<z:double>>>.
    Run `rlang::last_error()` to see where the error occurred.

By contrast

```r
A <- tibble(x=1, y=list(tibble(z=1)))
B <- tibble(x=3, z=4) %>% nest(y=z)
bind_rows(A, B)
```

Works ok.

**Comment by romainfrancois** [comment]
Probably fixed in https://github.com/r-lib/vctrs/pull/1231
