### ISSUE TITLE
list column not found when prefixed with .data

### ISSUE THREAD

**Issue by jey1401** [tidyverse/dplyr#5608]
Hi,

Here is an example of a mutate that works fine without the .data prefix and fails with.

```r
library(dplyr)
library(rlang)

f = function(i) i + 1 # also, this fails if directly defined inside list column

tibble(a = list(f), b = 1) %>% 
    rowwise() %>% 
    mutate(res = a(.data$b))

# A tibble: 1 x 3
# Rowwise: 
#   a          b   res
#   <list> <dbl> <dbl>
# 1 <fn>       1     2

tibble(a = list(f), b = 1) %>% 
    rowwise() %>% 
    mutate(res = .data$a(.data$b))

# Error: Problem with `mutate()` input `res`.
# x Column `a` not found in `.data`
# ℹ Input `res` is `.data$a(.data$b)`.
# ℹ The error occurred in row 1.

```

I use dplyr 1.0.2 and rlang 0.4.8.

Cheers

**Comment by DavisVaughan** [comment]
Note that this is specific to `rowwise()` data frames

``` r
library(dplyr)

f <- function(i) i + 1
df <- tibble(a = list(f), b = 1)

df %>% 
  mutate(res = .data$a)
#> # A tibble: 1 x 3
#>   a          b res   
#>   <list> <dbl> <list>
#> 1 <fn>       1 <fn>

df %>% 
  rowwise() %>% 
  mutate(res = .data$a)
#> Error: Problem with `mutate()` input `res`.
#> x Column `a` not found in `.data`
#> ℹ Input `res` is `.data$a`.
#> ℹ The error occurred in row 1.
```

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I looked at this a little and it seems to have to do with the fact that:

1. With rowwise data frames and list columns, we add the list _element_, i.e.`elt`, directly to the data mask, not a list of size 1, i.e. `list(elt)`. In this case `elt` is a function.

2. The rlang function, `rlang:::data_pronoun_get()`, which is responsible for getting the item from the mask, skips over function objects [here](https://github.com/r-lib/rlang/blob/37e8ddcc624f0b76ddbc2e09e0def69ab6f3ce57/src/internal/eval-tidy.c#L224). I am not entirely sure why. This is why it looks like `a`, a function, doesn't exist in the mask.

Maybe @lionel- has some thoughts on the rlang behavior

**Comment by lionel-** [comment]
hmm I don't remember. I have opened an issue at https://github.com/r-lib/rlang/issues/1061

**Comment by lionel-** [comment]
I think the idea was to skip over functions like `c()`, which are sometimes defined in data masks to implement things like tidy selections. It was to prevent `.data$c` to return a function if the `c` column is unexpectedly undefined.

Since we now use a different approach in tidyselect, and since that causes surprising behaviour with `rowwise()` data frames, we should probably remove that skip. What do you think @hadley?

**Comment by hadley** [comment]
@lionel- that sounds fine to me.
