### ISSUE TITLE
GitHub workflow for R < 3.5 fails due to Lahman requirement

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dplyr#5612]
Observed here:

https://github.com/tidyverse/dplyr/pull/5610

Workflow fails on R < 3.5 because Lahman now depends on R>=3.5:

https://cran.r-project.org/web/packages/Lahman/index.html

I guess that part of the vignette would have to skip execution.

**Comment by romainfrancois** [comment]
related to https://github.com/cdalzell/Lahman/issues/58
