### ISSUE TITLE
?filter broken when conflicted is loaded

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#5623]
due to `methods_rd()` erroring in this case.

Closes https://github.com/r-lib/conflicted/issues/56.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(conflicted)

filter
#> Error: [conflicted] `filter` found in 2 packages.
#> Either pick the one you want with `::` 
#> * dplyr::filter
#> * stats::filter
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("filter", "dplyr")
#> * conflict_prefer("filter", "stats")

?dplyr::filter
#> Error:  [conflicted] `filter` found in 2 packages.
#> Either pick the one you want with `::` 
#> * dplyr::filter
#> * stats::filter
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("filter", "dplyr")
#> * conflict_prefer("filter", "stats")

dplyr:::methods_rd("filter")
#> Error: [conflicted] `filter` found in 2 packages.
#> Either pick the one you want with `::` 
#> * dplyr::filter
#> * stats::filter
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("filter", "dplyr")
#> * conflict_prefer("filter", "stats")
```

<sup>Created on 2020-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Looks like this is happening in 

```r
info <- eval(expr(attr(utils::methods(!!x), "info")), envir = globalenv())
```

so `utils::methods("filter")`

**Comment by krlmlr** [comment]
Right:

``` r
library(dplyr)
library(conflicted)

x <- utils::methods(dplyr::filter)
#> Error: [conflicted] `filter` found in 2 packages.
#> Either pick the one you want with `::` 
#> * dplyr::filter
#> * stats::filter
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("filter", "dplyr")
#> * conflict_prefer("filter", "stats")
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is a limitation of `utils::methods()` then, can we resort to `utils::.S3methods()` ?

``` r
library(dplyr)
library(conflicted)

x <- .S3methods("filter", , asNamespace("dplyr"))
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
it's probably better than getting the error, but this would leave behind potential S4 methods.

**Comment by krlmlr** [comment]
Yeah, we need our own `utils::methods()` that is compatible with conflicted.

**Comment by romainfrancois** [comment]
so maybe this is a conflicted issue after all ? cc @hadley

**Comment by krlmlr** [comment]
I don't think we can do anything about it in conflicted. It's an omission in utils I think.

**Comment by romainfrancois** [comment]
`conflicted` could have a patched `utils::methods` maybe ?

**Comment by krlmlr** [comment]
I don't think conflicted should be patching anything. We can fix in utils or work around here.

**Comment by krlmlr** [comment]
To clarify, the error comes from our dynamic help pages.

**Comment by hadley** [comment]
I'll take a look at this.

**Comment by hadley** [comment]
It is probably fine to use `.S3methods()` here, or even just wrap the whole thing in `try()`, just so it doesn't cause an error.
