### ISSUE TITLE
across/where

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#5625]
If the first argument of `across` is a function it must be wrapped in `where`.  Why?  `across` could be a generic with a `function` method.

**Comment by romainfrancois** [comment]
This is more of a `tidyselect` question. This was a way to disambiguate things like `data`, `id` which are typical column names but also functions. 

`across(.cols = )` uses lazy evaluation anyway, so can't rely on S3 dispatch. 

Closing but ping @lionel- for possible more/better context.
