### ISSUE TITLE
Summarize silently drops rows if ANY zero-length vector is returned

### ISSUE THREAD

**Issue by lotard** [tidyverse/dplyr#5632]
Rows are silently dropped, if any of the `summarize` functions returns a zero-length vector.

I think this should give an error, so that the user can either catch these (unusual) outcomes explicitly (and convert to `NA`, for example), or `filter` explicitly before calling `summarize`. 

```r
tibble(a='a') %>% summarize(a = character(0), b = '') # empty rows returned
tibble(a='a') %>% summarize(a = a[F], b = '') # empty rows returned
tibble(a='a') %>% summarize(a = NULL, b = '') # error, as expected
```

Current implementation is in some sense consistent with the fact that `summarize` silently duplicates rows, if any of the functions returns multiple values, but my naive expectation is still that I don't suffer data loss just because ONE of many functions drew a blank.

**Comment by romainfrancois** [comment]
This is consistent with recycling rules from `vctrs` : 

``` r
vctrs::vec_size_common(character(0), "")
#> [1] 0
```

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

`a` and `b` get recycled to the common size, which just happens to be 0. 

You may enhance `summarise()` if you only want to allow size 1, something like this perhaps: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(rlang)

assert_size1 <- function(x) {
  stopifnot(vctrs::vec_size(x) == 1)
  x
}

strict_summarise <- function(.data, ..., .groups = NULL) {
  quos <- purrr::map(enquos(...), function(q) {
    new_quosure(
      expr(assert_size1(!!quo_get_expr(q))), 
      quo_get_env(q)
    )
  })
  summarise(.data, !!!quos, .groups = .groups)
}
tibble(a='a') %>% 
  strict_summarise(a = character(0), b = '')
#> Error: Problem with `summarise()` input `a`.
#> x vctrs::vec_size(x) == 1 is not TRUE
#> ℹ Input `a` is `assert_size1(character(0))`.
```

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by lotard** [comment]
@romainfrancois  Your `strict_summarise` sounds great, thank you! Any reason not to implement it as part of `tidyr`, perhaps just as a message (not error)?  `tidyr` warns/informs users about ungrouping behaviors and common join variables, both of which can have unintended consequences, why not this one?

Personally, I cannot imagine a practical data analysis situation where summarizing entire row of data out of existence is the expected behavior, or even desired for expediency, like perhaps the situation where more than one row is returned. I wasn't  aware of `vctrs::vec_size_common` returning 0 as common size of 1 and 0 (which, superficially, seems like the opposite of returning 2 as common size of 2 and 1, although I'm sure it makes sense in some context) and I'm sure most users aren't either.

**Comment by lotard** [comment]
For anyone who runs into that:
```
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.

Please use `reframe()` instead.

When switching from `summarise()` to `reframe()`, remember that `reframe()` always returns an ungrouped data frame and adjust accordingly.
```
