### ISSUE TITLE
Add clear error messages for dplyr in shiny

### ISSUE THREAD

**Issue by mutahiwachira** [tidyverse/dplyr#5636]
When using dplyr in Shiny, it is quite difficult to debug due to rather opaque messages as compared to `base` and other packages.

Here is an error message in Shiny.
```r
library(shiny)
library(dplyr)

options(shiny.error = NULL)

ui <- fluidPage(
  verbatimTextOutput("example")
)

server <- function(input, output, session) {
  output$example <- renderPrint({
    mtcars[,"wrong_col"]
    
    # mtcars %>% 
    #   select(wrong_col)
    
  })
}

shinyApp(ui, server)
```

```r
# Listening on http://127.0.0.1:7436
# Warning: Error in [.data.frame: undefined columns selected
#  102: stop
#  101: [.data.frame
#   99: renderPrint [C:/Users/<My_Name>/Desktop/testShiny.R#12]
#   98: func
#   82: origRenderFunc
#   81: output$example
#    1: runApp
```

The name of the reactive is printed with the line item in the exact file where the error occured.

Here is the error message when dplyr is used instead.

```r
library(shiny)
library(dplyr)

options(shiny.error = NULL)

ui <- fluidPage(
  verbatimTextOutput("example")
)

server <- function(input, output, session) {
  output$example <- renderPrint({
    #mtcars[,"wrong_col"]
    
     mtcars %>% 
       select(wrong_col)
    
  })
}

shinyApp(ui, server)
```

```r
# Listening on http://127.0.0.1:7436
# Warning: Error in : Can't subset columns that don't exist.
# x Column `wrong_col` doesn't exist.
#   120: <Anonymous>
```

Normally you have to use `rlang::last_error` and look through the summarised trace to find the error. This doesn't work in Shiny because you first have to stop the app and all context disappears so `rlang::last_error()` doesn't work. You might then think to use `options(shiny.error = browser)` and call `rlang::last_error()` from there but that still doesn't work. Instead, if you set the option you have to call the object `e` which contains a `vctrs` object containing the error. The output below is the error above with `options(shiny.error = browser)` set and includes commands called from the console session exploring the `browser()` environment. The `rlang` functions don't work, so you have to call `e`.

```r

Browse[1]> rlang::last_error()
# Error: Can't show last error because no error was recorded yet
Browse[1]> rlang::last_trace()
# Error: Can't show last error because no error was recorded yet
Browse[1]> e
# <error/vctrs_error_subscript_oob>
#   Can't subset columns that don't exist.
# x Column `wrong_col` doesn't exist.
# Backtrace:
#    1. shiny::runApp("C:/Users/<My_Name>/Desktop/testShiny.R")
#    8. shiny:::serviceApp()
#    9. shiny:::flushReact()
#   10. .getReactiveEnvironment()$flush()
#   11. ctx$executeFlushCallbacks()
#   12. base::lapply(...)
#   13. shiny:::FUN(X[[i]], ...)
#   14. shiny:::flushCallback()
#   33. shiny:::run()
#   34. ctx$run(.func)
#   41. env$runWith(self, func)
#   42. shiny:::contextFunc()
#   43. shiny:::`<observer:output$example>`(...)
#   78. shiny:::func()
#   79. shiny:::orig(name = name, shinysession = self)
#   81. shiny:::`output$example`(...)
#   82. shiny:::origRenderFunc(...)
#   98. shiny:::func()
#   99. renderPrint(...)
#   28. dplyr::select(., wrong_col)
#  110. tidyselect::eval_select(expr(c(...)), .data)
#  111. tidyselect:::eval_select_impl(...)
#  119. tidyselect:::vars_select_eval(...)
#  120. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
#  121. tidyselect:::eval_c(expr, data_mask, context_mask)
#  122. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
#  123. tidyselect:::walk_data_tree(new, data_mask, context_mask)
#  124. tidyselect:::as_indices_sel_impl(...)
#  125. tidyselect:::as_indices_impl(x, vars, strict = strict)
#  126. tidyselect:::chr_as_locations(x, vars)
#  127. vctrs::vec_as_location(x, n = length(vars), names = vars)
#  129. vctrs:::stop_subscript_oob(...)
#  130. vctrs:::stop_subscript(...)
```

-----------

**Summary**
Compared to the default behaviour for error messages, dplyr error messages are incredible difficult to debug. In multifile Shiny apps, normal error messages (from `[`) will often take you to the exact file and line where the issue is. By comparison, an inexperienced user can take a long time trying to hunt down a dplyr based error. Even if you are aware of `rlang::last_error()` and `options(shiny.error = browser()`, they don't actually work together like you would expect and instead you have to call `e` from the browser session and `traceback(e)` to get the same functionality.

Is there any way to change this behaviour in dplyr so that it prints out some kind of context (file and line) for errors in Shiny?

_(Note: This is my first issue raised on GitHub. I made a post on RStudio Community but didn't get a response and in any case I do have an indirect solution to my problem. So this is more of a feature request regarding what I consider to be undesirable behaviour in dplyr than an unsolved problem. Please tell me if I've submitted this issue correctly or if there's anything I need to add)._

-------------
My `sessionInfo()`:
```r
# R version 3.6.2 (2019-12-12)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19041)
# 
# Matrix products: default
# 
# locale:
# [1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252   
# [3] LC_MONETARY=English_South Africa.1252 LC_NUMERIC=C                         
# [5] LC_TIME=English_South Africa.1252    
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
#   [1] dplyr_1.0.2   shiny_1.4.0.2 reprex_0.3.0 
# 
# loaded via a namespace (and not attached):
#   [1] Rcpp_1.0.3       pillar_1.4.3     compiler_3.6.2   later_1.0.0      tools_3.6.2     
# [6] digest_0.6.23    jsonlite_1.6.1   evaluate_0.14    lifecycle_0.2.0  tibble_3.0.3    
# [11] pkgconfig_2.0.3  rlang_0.4.7      cli_2.0.2        rstudioapi_0.11  xfun_0.12       
# [16] fastmap_1.0.1    knitr_1.28       generics_0.0.2   fs_1.5.0         vctrs_0.3.2     
# [21] tidyselect_1.1.0 glue_1.4.1       R6_2.4.1         processx_3.4.1   fansi_0.4.1     
# [26] rmarkdown_2.1    callr_3.4.1      purrr_0.3.3      clipr_0.7.0      magrittr_1.5    
# [31] whisker_0.4      ps_1.3.0         promises_1.1.0   ellipsis_0.3.0   htmltools_0.4.0 
# [36] assertthat_0.2.1 rsconnect_0.8.16 mime_0.8         xtable_1.8-4     httpuv_1.5.2    
# [41] crayon_1.3.4 
```

**Comment by romainfrancois** [comment]
This is probably related to #5552

**Comment by romainfrancois** [comment]
This particular error comes straight from `tidyselect` / `vctrs`. `dplyr` does not do anything specific about it. 

I'm seeing the same problem with this: 

```r
library(shiny)
library(dplyr)

options(shiny.error = NULL)

ui <- fluidPage(
  verbatimTextOutput("example")
)

server <- function(input, output, session) {
  output$example <- renderPrint({
    # stop("bla bla")
    abort("bla bla")
  })
}

shinyApp(ui, server)
```

when using `stop()` I see: 

```
Listening on http://127.0.0.1:5572
Warning: Error in renderPrint: bla bla
  100: stop
   99: renderPrint [/private/tmp/sh.R#12]
   98: func
   82: origRenderFunc
   81: output$example
    1: shiny::runApp
```

but when using `abort()` I see: 

```
Listening on http://127.0.0.1:5572
Warning: Error in : bla bla
  103: <Anonymous>
```

I'm not sure if this is either an issue in shiny or with `rlang::abort()` ? ping @lionel- @wch

**Comment by hadley** [comment]
I think this is a Shiny issue, or at least it's best solved on the shiny side, by incorporating more of our error handling tools from rlang. Would you mind filing an issue here?

In general, it's also a good idea to keep reactive code as isolate as possible to make debugging easier.
