### ISSUE TITLE
between()'s left=/right= arguments don't support columns

### ISSUE THREAD

**Issue by xvrdm** [tidyverse/dplyr#5637]
_Adding this after discussing with @krlmlr_ 

When using `between()`, users might be tempted to provide columns to the "boundaries" argument `left=` and `right=`. It doesn't look like this use-case is supported at the moment. 

```r
between(c(5,6), left = c(1,4), right = c(2,10))
``` 
```
[1] FALSE FALSE
```

```r
tibble(val = c(5,6), min_threshold = c(1,4), max_threshold = c(2,10)) %>% 
  mutate(is_in_range = between(val, min_threshold, max_threshold))
```
```
# A tibble: 2 x 4
    val min_threshold max_threshold is_in_range
  <dbl>         <dbl>         <dbl> <lgl>      
1     5             1             2 FALSE      
2     6             4            10 FALSE 
```

This is not a bug per-say and the documentation doesn't indicate that vector/columns are supported for `left=` and `right=`. One can always go around it with `rowwise()` (example [here](https://gist.github.com/xvrdm/5f1bacaef8de15740f96ccca177d7f02)). However, it could be nice to have some kind of message rather than the current silent behavior. 

Not sure if you think it should be an error, warning or message. Happy to have a go at it in a PR if you think it's worthwhile.

**Comment by rdboyes** [comment]
I ran into this problem as well doing today's advent of code challenge. I think the latest dev version now fails if length != 1 for left and right

**Comment by xvrdm** [comment]
Thanks @rdboyes, you are right: it happened here: https://github.com/tidyverse/dplyr/pull/5501
Closing this then.

**Comment by psychelzh** [comment]
Seems that [`between()`](https://rdatatable.gitlab.io/data.table/reference/between.html) in {data.table} is vectorized. Wish for this feature in {dplyr}, too!

**Comment by stragu** [comment]
Are there plans to vectorise this? Maybe I misunderstood, but isn't that [what @hadley mentions here](https://github.com/tidyverse/dplyr/pull/5501#discussion_r480095753)?
