### ISSUE TITLE
all_of() inside across() can no longer(?) see variables

### ISSUE THREAD

**Issue by uhkeller** [tidyverse/dplyr#5639]
I have some code that I'm sure used to run with some earlier version of the tidyverse packages (not sure which, unfortunately), but no longer does after I've updated my packages. I've boiled it down to a simple reprex:

```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
dat <- tribble(
  ~a, ~b, ~v,
  1,  1,  "a",
  1,  1,  "b"
)
dat %>% 
  rowwise() %>% 
  mutate(across(all_of(v), ~ .x + 1))
#> Error: Problem with `mutate()` input `..1`.
#> x object 'v' not found
#> ℹ Input `..1` is `across(all_of(v), ~.x + 1)`.
#> ℹ The error occurred in row 1.
```

Apparently, `all_of()` no longer sees the variables in the tibble, so I can't use `v` to select the columns I want to transform. I tried using `cur_data()` as a workaround but that doesn't work either. Is this the intended behaviour?

R 4.0.3
dplyr 1.0.2
tidyselect 1.1.0
vctrs 0.3.5
rlang 0.4.9

**Comment by hadley** [comment]
It was a bug that this worked before — we've removed the ambiguity so that `all_of()` never looks in the current variables.
