### ISSUE TITLE
surpising `summarize` output when re-using variable name

### ISSUE THREAD

**Issue by SamDM** [tidyverse/dplyr#5640]
The `summarize` function has suprising behaviour when re-using a variable name, e.g.:

```r
foo <- tribble(
  ~a, ~b, ~c,
  0 ,  0,  1,
  0 ,  0,  2,
  0 ,  1,  3,
)
foo %>% group_by(a, b) %>%
  summarise(c=mean(c), c_sum=sum(c), c_len=length(c), n=n(), .groups = "drop")
```
```txt
# A tibble: 2 x 6
      a     b     c c_sum c_len     n
  <dbl> <dbl> <dbl> <dbl> <int> <int>
1     0     0   1.5   1.5     1     2
2     0     1   3     3       1     1
```
Notice the incorrect result of `c_sum` and `c_len`, due to `c` being updated after the `c=mean(c)` statement.
You could say I should've seen this coming, since other functions like `mutate` also work this way, but I believe the typical tidyverse user may trip up on this.
To me this seems like a typical use case in data science, e.g. for averaging out values over time intervals or such.

Maybe this situation should at least trigger a warning?

**Comment by hadley** [comment]
This behaviour is consistent with `mutate()` so I think unfortunately changing it has just as much risk of creating problems as leaving it as is. Similarly, a warning would be annoying if this is behaviour that you rely on (as people likely already do).
