### ISSUE TITLE
Function for reduced chi squared

### ISSUE THREAD

**Issue by zhuzp98** [tidyverse/dplyr#5645]
---

I am wondering if dplyr can add a function to calculate the reduced chi squared for linear or non linear model objects. 
Here is some of my personal attempt to constructing such a function. 

---

**Description**

The reduced chi-square statistic is used to show the goodness of model fitting. 
This function is to calculate the reduced chi-squared of a fitted model. 
It is based on the R *summary()* function which doesn't directly provide a reduced chi-square for the model fitted. 

**Input (Arguments)**

- `y`: a list of numeric value the response in the model, can be a column of an existing tibble. 
  - _Justification_: in model fitting, we usually have a response variable and one or several variables as input. The `y` here is the response variable and we use it to calculate the chi-squared value. 
- `model`: a fitted model either by linear fitting or non-linear fitting. 
  - _Justification_:  the fitted model will provide the fitted value involved in the calculation of chi-squared value. It also shows the number of variables involved in the model and this will be used to calculate the degree of freedom of the model. 
- ...

**Output**

This function returns a numeric value which is the reduced chi-square of the fitted model. 

```r
r.chi_cal <- function(y, model){
  if(!is.numeric(y)) {
    stop('I am so sorry, but this function only works for numeric response variable\n',
         'You have provided an object of class: ', class(y)[1])
  }
  
  if(class(model) != 'lm' & class(model) != 'nls') {
    stop('I am so sorry, but this function only works for linear or nonlinear least-squares models\n',
         'You have provided an object of class: ', class(model)[1])
  }
  
  se <- summary(model)$sigma
  chisq_val <- sum(((y - predict(model)) / se) ^ 2)
  df <- length(y) - summary(model)$df[1] + 1
  r.chi_val <- chisq_val / df
  r.chi_val
}
```

**Comment by hadley** [comment]
This seems a little out of scope for dplyr — dplyr contains tools for data manipulation not statistics.
