### ISSUE TITLE
c_across combines levels of incompatible factor variables without message

### ISSUE THREAD

**Issue by corybrunson** [tidyverse/dplyr#5650]
The new `c_across()` is exactly what i needed just now and i'm delighted to have found it. However, it took me a while to diagnose a problem with a calculation i was performing that involved converting factor columns to integers and taking their sum (see reprex below). While in most cases the factors had the same levels, in one case some levels were differently coded. (In practice, this can occur by accident or because categorical variables with different groups are being combined into meaningful scores.) I inferred that this caused the row vector to be redefined as a single factor variable with a concatenated vector of levels, which then took larger values when converted to integers. As a result, the row sums were much larger than their intended values.

While i think that this is appropriate behavior, i think it would preempt confusion to print an informative message when multiple factor variables with different levels are concatenated using `c_across()`. (This may only be an issue when someone is doing arithmetic on the result.) Incidentally, i've written a package that combines factors in this way (and currently does not print such a message), so i'd be interested in any general guidance folks have.

``` r
suppressMessages(library(dplyr))
#> Warning: package 'dplyr' was built under R version 4.0.2
# tibble with incompatible factor columns
d <- tibble(
  a = factor(letters[1:3][c(1, 3, 2)], levels = letters[1:3]),
  b = factor(letters[4:6][c(2, 1, 3)], levels = letters[4:6])
)
# expected or desired sum
d %>%
  mutate_all(as.integer) %>%
  mutate(c = a + b)
#> # A tibble: 3 x 3
#>       a     b     c
#>   <int> <int> <int>
#> 1     1     2     3
#> 2     3     1     4
#> 3     2     3     5
# sum using `c_across()` due (evidently) to factors being combined with
# concatenated levels
d %>%
  rowwise() %>%
  mutate(c = sum(as.integer(c_across(c(a, b)))))
#> # A tibble: 3 x 3
#> # Rowwise: 
#>   a     b         c
#>   <fct> <fct> <int>
#> 1 a     e         6
#> 2 c     d         7
#> 3 b     f         8
```

<sup>Created on 2020-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I could not find an existing issue about this, and the behavior was the same after CRAN and `master` branch installations.

**Comment by corybrunson** [comment]
As a point of reference, base R automatically converts factor vectors to integer vectors before concatenating them, even if they have the same levels. So the behavior of `c_across()` is different from what a base R user is primed to expect, which i think supports the case for a message.

``` r
a <- factor(letters[1:3][c(1, 3, 2)], levels = letters[1:3])
b <- factor(letters[1:3][c(2, 1, 3)], levels = letters[1:3])
c(a, b)
#> [1] 1 3 2 2 1 3
a <- factor(letters[1:3][c(1, 3, 2)], levels = letters[1:3])
b <- factor(letters[4:6][c(2, 1, 3)], levels = letters[4:6])
c(a, b)
#> [1] 1 3 2 2 1 3
```

<sup>Created on 2020-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Under the hood, `c_across()` uses `vctrs::vec_c()` which is principled about combining factors. This is a feature. 

One workaround is to use `across()`, convert and then combine, e.g. 

``` r
suppressMessages({
  library(dplyr)
  library(vctrs)
  library(purrr)
})
d <- tibble(
  a = factor(letters[1:3][c(1, 3, 2)], levels = letters[1:3]),
  b = factor(letters[4:6][c(2, 1, 3)], levels = letters[4:6])
)

c_across2 <- function(..., .convert = identity) {
  values <- as_tibble(map(across(...), .convert))
  vec_c(!!!values)
}
d %>%
  rowwise() %>%
  mutate(c = sum(c_across2(c(a, b), .convert = as.integer)))
#> # A tibble: 3 x 3
#> # Rowwise: 
#>   a     b         c
#>   <fct> <fct> <int>
#> 1 a     e         3
#> 2 c     d         4
#> 3 b     f         5
```

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
