### ISSUE TITLE
give `*_join()` more control on duplicated and unmatched rows

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#5661]
As @lionel- nicely proposed in #3967 it would be great to have more control on what the `*_join()` functions do on duplicated or unmatched rows. Proposed arguments:

* `.unmatched = c("keep", "drop", "error")`
* `.duplicates = c("error", "product")`

for example a 1:1 join would then simply be `.unmatched = "error"` and `.duplicates = "error"`.

As the arguments should rather be added to the existing `*_join()` functions the "keep" and "drop" options for `.unmatched` don't really make sense for all joins. Rather, one would have

`left/right/full_join()` -> `.unmatched = c("keep", "error")`
`inner_join()` -> `.unmatched = c("drop", "error")`

**Comment by mgirlich** [comment]
@lionel- I didn't fully understand your thoughts about `nesting` and `.duplicates = "keep"`. Maybe you'd like to add your thoughts here

**Comment by lionel-** [comment]
I think this was from a discussion with @hadley but I no longer fully understand it either 😅: https://github.com/tidyverse/dplyr/issues/3967#issuecomment-461877560. Might not be as much a concern if we're adding these arguments to existing join functions.
