### ISSUE TITLE
dplyr edition

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#5664]
Tracking list of things to do if we ever made a dplyr "edition"

* change default summarise behaviour
* change default join behaviour (#5661)

**Comment by markfairbanks** [comment]
Not sure if this thread is open to suggestions. I always thought that functions like `group_by()` and `distinct()` should use tidyselect and avoid the current `mutate()` step that requires `across()` to be used. However this is a backwards incompatible change that would only be possible with an "edition".

Basically it seems like this should be possible:
```r
df %>%
  group_by(where(is.character))
```

**Comment by iago-pssjd** [comment]
Would also be possible that the `by` in `join` functions worked with tidyselect (in order to, for example, joining by many columns except a few ones, or as in the example above, joining by the columns `where(is.character)`)?

**Comment by hadley** [comment]
No, think we’ll attack that a different way.

**Comment by hadley** [comment]
I'm going to close this since we've made big changes to the joins in this release and most of the grouping stuff is likely change via #6214, thus not needing an edition. This issue is still linked from the tidyverse wide edition issue, so we will look here again once we implement that.
