### ISSUE TITLE
group_by() assigns group indices in different order than they appear in data

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/dplyr#5668]
Simple example:
```r
library(dplyr)
d = tibble(id = c("B", "A"))
d.grp = group_by(d, id)
mutate(d.grp, grp.id = cur_group_id())
## # A tibble: 2 x 2
## # Groups:   id [2]
##   id    grp.id
##   <chr>  <int>
## 1 B          2
## 2 A          1
```
There are some cases where it it is convenient for the group IDs be ordered by how they appear in the data. What is the reasoning behind the decision to order the grouping by some other logic (in this case, I assume alphabetically)? Currently, the only way to guarantee that the group indices are in the order of the data is to first `arrange()` the data before grouping, which can be expensive.

**Comment by romainfrancois** [comment]
There is no concept of "how they appear in the data". For strings groups, data is organized in the dictionary order, so group 1 is "A" and group 2 is "B". 

A way to perhaps enforce that order is to use a factor and specify the levels so that they match the data order: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
d <- tibble(id = c("B", "A"))

d.grp <- group_by(d, id = factor(id, levels = unique(id)))
group_data(d.grp)
#> # A tibble: 2 x 2
#>   id          .rows
#> * <fct> <list<int>>
#> 1 B             [1]
#> 2 A             [1]
group_rows(d.grp)
#> <list_of<integer>[2]>
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2

mutate(d.grp, grp.id = cur_group_id())
#> # A tibble: 2 x 2
#> # Groups:   id [2]
#>   id    grp.id
#>   <fct>  <int>
#> 1 B          1
#> 2 A          2
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mkoohafkan** [comment]
@romainfrancois  thanks for the clarification---although I would argue that there is clearly a concept of "how they appear in the data" which is why your example using `factor()` works at all. Using `unique()` also preserves order, so using converting to factors is not strictly necessary. I was wondering **why** the decision was made to sort by dictionary order when assigning group ids rather than the order that they appear in the data, as sorting the groups by dictionary order is an additional (and possibly unnecessary) step.

**Comment by ahcyip** [comment]
I recently learned that this has been discussed a lot https://github.com/tidyverse/dplyr/issues/2159
