### ISSUE TITLE
*_join functions don't preserve labels in labelled vectors when one of the joined data sets contains more or less labels than the other

### ISSUE THREAD

**Issue by deschen1** [tidyverse/dplyr#5671]
When having labelled vectors like from `haven` package, these labels are not preserved in joining functions if the labels between the two to-be-merged data sets are not 100% identical. However, it is common that to-be-merged data sets might have additional (or fewer) labels, but should still be preserved.

E.g assume a usual social science survey where you have one data set for Jan/Feb/March and this information is stored in a labelled column. Now, you have a new survey with data from April, again labelled in a respective column. When joining these two data sets, it would be preferable to keep the lables if they are consistent, clear and non-overlapping.

So if data set 1 has labels like 1 = Jan, 2 = Feb, 3 = Mar; and data set 2 has labels 4 = Apr, labels should be preserved and merged (or there should be at least a parameter to turn on this feature).

```
library(tidyverse)
library(haven)

old <- data.frame(id = c(1, 2, 3),
                  x  = haven::labelled(x      = c(1, 2, 3),
                                       labels = c("first" = 1, "second" = 2, "third" = 3))) %>%
  as_tibble()
```
```
# A tibble: 3 x 2
     id          x
  <dbl>  <dbl+lbl>
1     1 1 [first] 
2     2 2 [second]
3     3 3 [third]
```
```
new <- data.frame(id = c(4),
                  x  = haven::labelled(x      = c(4),
                                       labels = c("first" = 1, "second" = 2, "third" = 3, "fourth" = 4))) %>%
  as_tibble()
```
```
# A tibble: 1 x 2
     id          x
  <dbl>  <dbl+lbl>
1     4 4 [fourth]
```

Now, `full_join(old, new)` deletes the labels.

```
Joining, by = c("id", "x")
# A tibble: 4 x 2
     id     x
  <dbl> <dbl>
1     1     1
2     2     2
3     3     3
4     4     4
```

whereas the expected output would be

```
# A tibble: 4 x 2
     id          x
  <dbl>  <dbl+lbl>
1     1 1 [first] 
2     2 2 [second]
3     3 3 [third]
4     4 4 [fourth]
```

**Comment by romainfrancois** [comment]
It happens here: https://github.com/tidyverse/dplyr/blob/617ff9e8ba478ee16563275331d404b4d7da0d01/R/join.r#L354

Might be fixed when `haven` implements `vctrs` support: 

``` r
library(haven)
library(vctrs)

x <- labelled(
  x      = c(1, 2, 3),
  labels = c("first" = 1, "second" = 2, "third" = 3)
)

y <- labelled(
  x      = c(4),
  labels = c("first" = 1, "second" = 2, "third" = 3, "fourth" = 4)
)

vec_ptype(x)
#> <labelled<double>[0]>
#> 
#> Labels:
#>  value  label
#>      1  first
#>      2 second
#>      3  third
vec_ptype(y)
#> <labelled<double>[0]>
#> 
#> Labels:
#>  value  label
#>      1  first
#>      2 second
#>      3  third
#>      4 fourth
vec_ptype2(x, y)
#> numeric(0)
vec_ptype_common(x, y)
#> numeric(0)
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
haven is now implemented with vctrs. I think it loses labels on purpose in the same way that combining factors and character vectors yields a character vector.

In general, labels should be converted to proper R data structures right after importing. `<labelled>` vectors are a transient data structure.

**Comment by romainfrancois** [comment]
Thanks @lionel-, I was about to open an issue on `haven`. Closing this now. 

@deschen1 one thing you can do is to convert each `x` into a data frame with "value" and "label" columns and then join these: 

``` r
library(tidyverse)
library(haven)

old <- data.frame(id = c(1, 2, 3),
                  x  = haven::labelled(x      = c(1, 2, 3),
                                       labels = c("first" = 1, "second" = 2, "third" = 3))) %>%
  as_tibble()

new <- data.frame(id = c(4),
                  x  = haven::labelled(x      = c(4),
                                       labels = c("first" = 1, "second" = 2, "third" = 3, "fourth" = 4))) %>%
  as_tibble()


# <labelled> -> data.frame(value, label)
unlabel <- function(x) {
  data.frame(
    value = as.vector(x),
    label = names(attr(x, "labels"))[vctrs::vec_match(as.vector(x), attr(x, "labels"))]
  )
}
mutate(old, x = unlabel(x))
#> # A tibble: 3 x 2
#>      id x$value $label
#>   <dbl>   <dbl> <chr> 
#> 1     1       1 first 
#> 2     2       2 second
#> 3     3       3 third
mutate(new, x = unlabel(x))
#> # A tibble: 1 x 2
#>      id x$value $label
#>   <dbl>   <dbl> <chr> 
#> 1     4       4 fourth

full_join(
  mutate(old, x = unlabel(x)),
  mutate(new, x = unlabel(x))
)
#> Joining, by = c("id", "x")
#> # A tibble: 4 x 2
#>      id x$value $label
#>   <dbl>   <dbl> <chr> 
#> 1     1       1 first 
#> 2     2       2 second
#> 3     3       3 third 
#> 4     4       4 fourth

# going full circle
full_join(
  mutate(old, x = unlabel(x)),
  mutate(new, x = unlabel(x))
) %>%
  mutate(x = haven::labelled(x$value, set_names(x$value, x$label)))
#> Joining, by = c("id", "x")
#> # A tibble: 4 x 2
#>      id          x
#>   <dbl>  <dbl+lbl>
#> 1     1 1 [first] 
#> 2     2 2 [second]
#> 3     3 3 [third] 
#> 4     4 4 [fourth]
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by deschen1** [comment]
Thanks @lionel- and @romainfrancois for the input and help. So just to prevent misunderstanding: this issues is probabbly `haven` related and _might_ (or might not) get fixed there?

Re the "correct" data structure,  @lionel- , I know this isn't the right place to discuss, but I disagree in the sense that any modern data analysis platform (at least when dealing with survey-like data) is using or offering to use human-friendly labelled data. We could of course always argue that R does not support these, but things change and I think R would benefit from natively supporting such structures (I know there are factors, but you can't e.g. calculate means on factors). Just my two cents.
