### ISSUE TITLE
Should rowwise() be called group_by_row()?

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#5674]
Might communicate what it does a little better, and it makes it more clear that you use `ungroup()` to revert it.

**Comment by gmonaie** [comment]
Agreed, `group_by_row()` is a more explicit function name - makes more sense.

**Comment by deschen1** [comment]
Wouldn't it make even more sense to just have the one `group_by` verb and instead adding the row specification as a parameter? Sth. like `group_by(rows = TRUE)`. It's more verbose than just having a dedicated `group_by_row` verb and I'm not sure if it would cause any problems, but from an enduser's perspective I feel it's a bit cleaner and more logical to me.

**Comment by Adrianf23** [comment]
I also agree with @deschen1. I was re-reading the `group_by` and `summarise `documentation to find the argument that would perform what `rowwise` function did before I found out that it was a thing. I think this is also because a lot of tidy examples online don't use the function and this was also something that wasn't taught in a lot of the learning materials in university for the tidyverse.

**Comment by hadley** [comment]
I don't think making `group_by()` more complex is the right solution. There are likely to be other ways of grouping in the future and I think stuffing all of them into one function is going to be confusing.

**Comment by tjebo** [comment]
Just stumbled by coincidence on this discussion and may I put in my two cents worth, as an enduser :) 
I actually did not know that row_wise would do grouping, so it would be very good to make this clear with such renaming. 
As an enduser, I would not mind a new function. If one is using RStudio (which I am sure most users of the tidy verse will do), the new option will pop up anyways when starting to type "group_by"

Just my thoughts:) 
Happy new year. Let's hope this will turn out different.

**Comment by moodymudskipper** [comment]
I don't mind the new name, but there are many `group_` functions that we will probably expect to work on row wise data then. For instance `groups(rowwise(iris))` currently returns an empty list.

**Comment by hadley** [comment]
Thanks for the discussion so far, but I'm not looking for more feedback at this time.

**Comment by hadley** [comment]
I think `group_by_row()` would be a better name, but we're unlikely to change it since future grouping working is like to be via #6214.
