### ISSUE TITLE
LazyData field in DESCRIPTION should be a logical

### ISSUE THREAD

**Issue by cjyetman** [tidyverse/dplyr#5676]
https://github.com/tidyverse/dplyr/blob/0c9900a11854bdb49a376d3bb56948c39e00e1e7/DESCRIPTION#L67

According to [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file), the `LazyData` field in [DESCRIPTION](https://github.com/tidyverse/dplyr/blob/master/DESCRIPTION) should be a "logical field", which probably means `true` or `false` rather than `yes` or `no`.

Presumably this hasn't caused any major issue yet, but it is at least inconsistent with a few other `tidyverse` packages that I've checked...
https://github.com/tidyverse/ggplot2/blob/0394b9f95bc028f558f4c6fde7c43e744c96bd95/DESCRIPTION#L72
https://github.com/tidyverse/purrr/blob/af06d457e92b95ad717a7bbb94153674b80852c6/DESCRIPTION#L42
https://github.com/tidyverse/tidyr/blob/35c0e733c7b17d4d1cd13ccc1e05e7dc12c502cf/DESCRIPTION#L50

**Comment by romainfrancois** [comment]
Thanks
