### ISSUE TITLE
data-raw/starwars.r still refers to swapi.co

### ISSUE THREAD

**Issue by hongooi73** [tidyverse/dplyr#5679]
The main package documentation has been revised to refer to swapi.dev, but the actual code to retrieve the data still refers to swapi.co.

**Comment by romainfrancois** [comment]
I can't get to `.dev` or `.co`. Perhaps the code should be marked as an historical artifact ...

**Comment by hadley** [comment]
Might be safer to link to a source github repo instead.

**Comment by hongooi73** [comment]
swapi.dev is back, for what it's worth
