### ISSUE TITLE
Lazy evaluation bug in `mutate`/`transmute` ? 

### ISSUE THREAD

**Issue by shahronak47** [tidyverse/dplyr#5680]
This is inspired from [this SO post ](https://stackoverflow.com/questions/65591282/an-object-inside-map-function-is-not-recognized-another-case ). I have made a smaller and simpler example. 

Consider this data : 

```r
library(dplyr)
library(purrr)

data <- data.frame(i1 = 1:3, i2 = 3:1)
data
#    i1 i2
#1   1  3
#2   2  2
#3   3  1
```

Now let's say I want to add a new column `temp` to above dataframe which is going to be list of dataframes. I try : 

1) 
```
data %>% mutate(t1 = map(i1, ~data %>% mutate(!!paste0('col', .x) := 1)))
```

This returns

>Error in paste0("col", .x) : object '.x' not found

But it works if I use this without `mutate` : 

2. 
```
map(data$i1, ~data %>% mutate(!!paste0('col', .x) := 1))

#[[1]]
#   i1 i2 col1
#1  1  3    1
#2  2  2    1
#3  3  1    1

#[[2]]
#  i1 i2 col2
#1  1  3    1
#2  2  2    1
#3  3  1    1

#[[3]]
#   i1 i2 col3
#1  1  3    1
#2  2  2    1
#3  3  1    1
```

It also works with `mutate` when we write a separate function to do the same thing. 

3.
```
fun_group <- function(i){
  data %>% mutate(!!paste0('col', i) := 1)
}

data %>% mutate(temp = map(i1, fun_group)) 
```

So why does 1 fail whereas 2 and 3 work fine. I have tried various modifications to the above to understand the reason but I failed to understand why it behaves differently. Tried changing `data` with `mtcars`, changing `mutate` with `transmute` but the error is still there.

**Comment by lionel-** [comment]
That's because `!!` injection happens eagerly by the outermost data masking function. This is tracked in r-lib/rlang#845. We'll fix this in the next major release of rlang if it's not too much of a breaking change (people might rely on this behaviour).
