### ISSUE TITLE
Bind_rows cannot combine bit64::integer64 with other types

### ISSUE THREAD

**Issue by schuemie** [tidyverse/dplyr#5684]
The `bind_rows()` function is nice in that it allows some differences in types. For example, a `numeric` column can be combined with an `integer` column without problem. However, this is not the case for `bit64::integer64` types. For example:

```r
library(dplyr)

# This works:
bind_rows(tibble(a = as.numeric(1)), 
          tibble(a = as.integer(2)))
# # A tibble: 2 x 1
#         a
#   <dbl>
#   1     1
#   2     2

# This fails:
bind_rows(tibble(a = as.numeric(1)), 
          tibble(a = bit64::as.integer64(2)))
# Error: Can't combine `..1$a` <double> and `..2$a` <integer64>.
# Run `rlang::last_error()` to see where the error occurred.
```

For consistency, it would be nice if `bit64::integer64` could be treated similar to other numeric types.

**Comment by romainfrancois** [comment]
`bind_rows()` inherits this from `vctrs::vec_rbind()`. This can be fixed either in `vctrs` or in `bit64` by providing vctrs methods. I'd suggest opening an issue in `vctrs` with the reprex below, perhaps linking here for context. 

``` r
suppressPackageStartupMessages({
  library(vctrs)
  library(tibble)
  library(bit64)
})

vec_rbind(
  tibble(a = as.numeric(1)), 
  tibble(a = as.integer64(2))
)
#> Error: Can't combine `..1$a` <double> and `..2$a` <integer64>.

vec_c(as.numeric(1), as.integer64(2))
#> Error: Can't combine `..1` <double> and `..2` <integer64>.
vec_ptype2(as.numeric(1), as.integer64(2))
#> Error: Can't combine <double> and <integer64>.
```

<sup>Created on 2021-01-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
