### ISSUE TITLE
`rows_*()` functions should be able to use different joins keys in `x` and `y`

### ISSUE THREAD

**Issue by deschen1** [tidyverse/dplyr#5685]
Currently, rows_* functions like `rows_update` require an unnamed character string for the `by` parameter, which makes it impossible to dynamically pass id column names. *_join functions, however, allow for a named by-vector so that names can be passed dynamically (see here for some reference: https://stackoverflow.com/questions/65688508/tidyverse-join-two-data-sets-with-dynamic-column-names-for-by-column).

It would be desirable if the rows_* function also allow for named vectors. 

```
library(tidyverse)
x <- data.frame(a1 = c(1, 2, 3))
y <- data.frame(a2 = c(1, 2, 4),
                new = c("a", "b", "c"))

z <- data.frame(a2  = 3,
                new = "d")

x_name <- "a1"
y_name <- "a2"

# works
x_new <- x %>%
  left_join(., y, by = setNames(y_name, x_name))

# doesn't work
x_new %>%
  rows_update(., z, by = setNames(y_name, x_name))

# Error: `by` must be unnamed.
```

**Comment by DavisVaughan** [comment]
I'm not quite sure I see the use case for this one. The column names that get the updates will have to have the same column names anyways, so it seems reasonable to me to require that they key columns have the same names too

**Comment by deschen1** [comment]
The use case is when having different by names in the two data frames, x and y. In the example I want to match a1 from x with a2 from y.

While I could hardcode this, there are often use cases where someone needs to pass the column names dynamically (e.g. when doing this for 20 different matches where the column names will differ).

Now, this works with *.join functions, but not for rows_* functions. But for these the same use case applies, i.e. I have a data frame where I want to update some rows, but the marching columns from both data sets have different names.

While I can understand that you'd assume that one would usually have two data frames with the same names for the matching/by columns, in reality this often is not the case.

**Comment by krlmlr** [comment]
Would it work to use `rename()` on the `y` argument first before calling the `rows_...()` functions?

**Comment by deschen1** [comment]
That's what I usually end up doing, yes. But a named vector like in join functions feels programmatically cleaner and less workaroundy.

**Comment by krlmlr** [comment]
I still don't see how it's cleaner if the `rows_...()` functions expect `colnames(y)` to be a subset of `colnames(x)` anyway, as you have also confirmed. On the contrary, adding this to the interface of `rows_...()` makes that interface more cluttered with limited gain.

I believe the use case is very different to joins -- with joins we add new columns and expect `colnames(x)` and `colnames(y)` to be mostly different. Also, the match must be perfect -- matching more than one row is an error. The other extensions for `by` in upcoming dplyr 1.1.0 don't apply either.

I'd be mildly curious to see an example where you have different "by" columns and otherwise same "non-by" columns (a prerequisite for `rows_...()`) so that a named `by` would actually help. I'm convinced that the current behavior is good and that we should keep supporting only same column names at the LHS and RHS.

**Comment by deschen1** [comment]
Sure, I just had one use case yesterday. Let's assume I have three data sets:

```
df1 <- data.frame(Q1        = c("adsahb", "hello"),
                  gibberish = c(0, 0))

df2 <- data.frame(Q2        = c("-----", "test"),
                  gibberish = c(0, 1))

df3 <- data.frame(Q3        = c("no", "xyz"),
                  gibberish = c(0, 0))
```

Then I also have a lookup list:
```
lookup <- data.frame(text      = c("adsahb", "-----", "test", "xyz", "sdfsdf"),
                     gibberish = c(1, 1, 0, 1, 1))
```

So what I want to do is to go through each of my data frames and update the `gibberish` column from my lookup. In the lookup, the `text` column doesn't have a match in the df1-df3's, where it's named Q1-Q3.

I know that there are workarounds, e.g. renaming the columns, using a `match` approach and probably other solutions. But I still think a named vector approach for the `by `argument like in joins would be a clean and also consistent behaviour. Both, the *rows and *join functions, do something with my data based on a matching column. So I still find it a bit confusing that the behaviour for the `by `argument is different.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's currently out of scope: developing good software requires relentless focus, which means that we have to say no to many good ideas, and it feels like this feature is just a bit too contentious at the moment. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
