### ISSUE TITLE
Internal lifecycle error after select_()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#5687]
``Internal error in lifecycle: Function in `what` (paste0) must have 1 argument, not 2.``

https://github.com/krlmlr/MultiLevelIPF/runs/1699350292?check_suite_focus=true#step:12:215

Could be either dev dplyr or dev lifecycle that trigger this, or both. Haven't checked further.

CC @lionel-.

**Comment by lionel-** [comment]
hmm this is from deprecate-warn becoming an NSE function: https://github.com/tidyverse/dplyr/blob/1be8cfa45fbec9981270c2670789b55067ddf799/R/deprec-lazyeval.R#L29

cc @hadley (who is working on the next version)

**Comment by romainfrancois** [comment]
However, we might defunct them soon: 

 https://github.com/tidyverse/dplyr/pull/5690

**Comment by romainfrancois** [comment]
Do we have a `reprex` for this, I can't seem to reproduce the problem ?

**Comment by lionel-** [comment]
This was fixed in https://github.com/r-lib/lifecycle/pull/90
