### ISSUE TITLE
Review use of the stale bot

### ISSUE THREAD

**Issue by Robinlovelace** [tidyverse/dplyr#5698]
Apologies if this is a bit a bit off-topic and 'none of my beeswax', but I just read an interesting article about the 'stale bot'. It made me recall encountering a stale issue in this repo and wondering why I (or anyone) was prevented from contributing, just because it had been a certain amount of time without anyone commenting. So could the use of the stale bot be reviewed? 

Article: https://blog.benwinding.com/github-stale-bots/

Discussion on Reddit: https://www.reddit.com/r/programming/comments/kzvryq/github_stale_bots_a_false_economy/

**Comment by romainfrancois** [comment]
I don't think we use that, but if there is an issue you want to contribute and can't for some reason, please open a new one with a link to the stale on.

**Comment by Robinlovelace** [comment]
Great, thanks for the response @romainfrancois. In terms of use of the stale bot, it seems some issues have been locked in that past, e.g. https://github.com/tidyverse/dplyr/issues/3488

![image](https://user-images.githubusercontent.com/1825120/105968357-e5a6ed00-607e-11eb-844e-2b08eb02ee1d.png)

Unfortunately I cannot remember which issue I wanted to comment on (apologies) but thought it worth asking the question. Great that the stale bot is not in use any more (if I understand your response correctly) and hope this feedback was more more useful than it was a hassle!

Amazing work on building intuitive and performant tools for data analysis, I will be teaching them this year on my Transport Data Science module :tada:
