### ISSUE TITLE
Unexpected behavior in na_if 

### ISSUE THREAD

**Issue by hjohns12** [tidyverse/dplyr#5711]
Tried using `na_if` today to turn values in a column that are less than zero to NA. Tried the `ifelse` alternative and that gave the behavior I expected to see when using `na_if`. 

---

```r
test <- tibble(Staff.Confirmed = c(0, 1, -999), Residents.Confirmed = c(12, -192, 0))
print(test)

out <-  test %>% 
  mutate(staff_conf_naif = na_if(Staff.Confirmed, Staff.Confirmed < 0),
        staff_conf_ifelse = ifelse(Staff.Confirmed < 0, NA, Staff.Confirmed),
        res_conf_naif = na_if(Residents.Confirmed, Residents.Confirmed < 0),
        res_conf_ifelse = ifelse(Residents.Confirmed < 0, NA, Residents.Confirmed)) %>% 
  select(Staff.Confirmed, staff_conf_naif, staff_conf_ifelse,
         Residents.Confirmed, res_conf_naif, res_conf_ifelse)
print(out)
```

When I use `na_if` in this mutate, it only makes changes to values equal to zero in the column referenced. Not sure if this is the intended behavior, but it seems a bit strange

**Comment by romainfrancois** [comment]
It looks like `na_if()` needs some attention. The second argument is not meant to be a predicate, but either a single value or a vector of same size as the first argument. 

This probably will be dealt with in the `funs` package. 

In the meantime, here is an alternative using `across()` : 

``` r
library(dplyr, warn.conflicts = FALSE)

test <- tibble(Staff.Confirmed = c(0, 1, -999), Residents.Confirmed = c(12, -192, 0))

na_if_negative <- function(x) {
  x[x < 0] <- NA
  x
}

test %>% 
  mutate(
    across(contains("Confirmed"), na_if_negative, .names = "res_{.col}")
  )
#> # A tibble: 3 x 4
#>   Staff.Confirmed Residents.Confirmed res_Staff.Confirmed res_Residents.Confirm…
#>             <dbl>               <dbl>               <dbl>                  <dbl>
#> 1               0                  12                   0                     12
#> 2               1                -192                   1                     NA
#> 3            -999                   0                  NA                      0
```

<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
`na_if()` is being redesigned in `funs::` here: https://github.com/tidyverse/funs/pull/65
