### ISSUE TITLE
slice_sample (and other slice_helpers) ellipsis order

### ISSUE THREAD

**Issue by lotard** [tidyverse/dplyr#5720]
Since ellipsis (...) is the second argument of all slice functions, I get an error `Error: ... is not empty.` when I try to do `slice_sample(1)`, which I expect to behave like `sample_n(1)` (or like `slice_sample(n=1)`). Even `base::sample` takes size as second (so `vect %>% sample(.,1)` will work). 

Of course, it still makes sense ellipsis is the second argument for `slice` itself.

It may be I'm missing some obvious purpose.

**Comment by romainfrancois** [comment]
This is by design I believe, to force the user to specify either `n=` or `prop=`.
