### ISSUE TITLE
group_by / summarise very slow together with bit64::integer64 columns

### ISSUE THREAD

**Issue by cnowzohour** [tidyverse/dplyr#5742]
I was surprised to see how much slower it is to operate on integer64 columns compared to int / string columns. The reprex below shows this for a small example. In my real use case the version with integer64 columns hadn't terminated after half an hour, whereas it did in a few seconds when I would convert it to strings before.

``` r
library(dplyr, warn.conflicts = FALSE)
suppressPackageStartupMessages(library(bit64))

df <- tibble(x = 1, x64 = integer64(1), xstr = "1", y = sample(10000, 1000000, replace = T))

system.time(df %>% group_by(y) %>% summarise(x = x[1]))
#>    user  system elapsed 
#>   0.071   0.007   0.078
system.time(df %>% group_by(y) %>% summarise(xstr = xstr[1]))
#>    user  system elapsed 
#>   0.059   0.009   0.068
system.time(df %>% group_by(y) %>% summarise(x64 = x64[1]))
#>    user  system elapsed 
#>   2.157   0.351   2.511
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Slightly modified reprex that factors out the grouping, since this is not what we're measuring here: 

``` r
library(dplyr, warn.conflicts = FALSE)
suppressPackageStartupMessages(library(bit64))

df <- tibble(x = 1, x64 = integer64(1), xstr = "1", y = sample(10000, 1000000, replace = T)) %>% group_by(y)

system.time(df %>% summarise(x = x[1]))
#>    user  system elapsed 
#>   0.037   0.003   0.040
system.time(df %>% summarise(xstr = xstr[1]))
#>    user  system elapsed 
#>   0.029   0.002   0.031
system.time(df %>% summarise(x64 = x64[1]))
#>    user  system elapsed 
#>   2.000   0.325   2.329
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
what seems to take the time is to `vctrs::vec_c()` many integer64 vectors together: 

![image](https://user-images.githubusercontent.com/2625526/107625879-4298ca80-6c5d-11eb-81e3-41964d64a137.png)

**Comment by romainfrancois** [comment]
Closing here because this should either be fixed in `vctrs` or `bit64`. I've opened this: https://github.com/r-lib/vctrs/issues/1323 to track it.
