### ISSUE TITLE
Preservation of NULL row names adds work to mutate/summarize pipes

### ISSUE THREAD

**Issue by dchiu911** [tidyverse/dplyr#5745]
I feel a common unit of work is to group by a categorical variable, calculate a summary measure on the continuous variables, then change the grouping variable to row names so that the data frame is entirely numeric (for some other downstream analyses). Possibly because of #5503 this workflow now requires an additional unit of work in reprex below.

I expected `column_to_rownames()` to just work after the call to `summarize()`. I see scenarios where the need to preserve row names is needed but here `has_rownames()` detects them after `summarize()` even though they're the same as a data frame with NULL row names (just row number). Do I simply need to add the pipe to  ``` `rownames<-`(NULL)``` now to adapt to the new changes?

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tibble)

# Medians for each species
iris_med <- iris %>% 
  group_by(Species) %>% 
  summarize(across(where(is.double), median))

# Error because summarize() preserved rownames
iris_med %>% column_to_rownames("Species")
#> Error: `.data` must be a data frame without row names.

# Verified it has row names
iris_med %>% has_rownames()
#> [1] TRUE

# It's just row numbers
rownames(iris_med)
#> [1] "1" "2" "3"

# But these are the same ones as when NULL
identical(
  rownames(iris_med),
  `rownames<-`(iris_med, NULL) %>% rownames()
)
#> [1] TRUE

# Need to add this line to every call before column_to_rownames()
iris_med %>% 
  `rownames<-`(NULL) %>% 
  column_to_rownames("Species")
#>            Sepal.Length Sepal.Width Petal.Length Petal.Width
#> setosa              5.0         3.4         1.50         0.2
#> versicolor          5.9         2.8         4.35         1.3
#> virginica           6.5         3.0         5.55         2.0
```

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by romainfrancois** [comment]
This, I believe is a bug `base::strructure()`: 

``` r
df <- data.frame(x = 1:10)
df2 <- structure(df, .drop = FALSE)
df3 <- `attr<-`(df, ".drop", FALSE)

.row_names_info(df, type = 0)
#> [1]  NA -10
.row_names_info(df2, type = 0)
#> [1] NA 10
.row_names_info(df3, type = 0)
#> [1]  NA -10
```

<sup>Created on 2021-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
