### ISSUE TITLE
add Bayesian option to slice_sample? (possible new feature)

### ISSUE THREAD

**Issue by bachlaw** [tidyverse/dplyr#5746]
`slice_sample` is an effective way to bootstrap samples, both individually and in blocks when used in connection with `group_by`.

However, one of the most common misconception of bootstrapped samples, particularly when used to form intervals, is that they somehow represent probabilities, which they usually don't. However, there is often no good reason _not_ to output probabilities when you can, particularly given the frequent similarity in results and the reality that you might as well give readers what they want.

This is easily done using the Bayesian version of the bootstrap and it requires only 1-2 lines of additional code that would assign and normalize positive numbers to form a Dirichlet distribution over the rows of the existing sample, which is then sampled from with replacement treating the normalized positive numbers as weights. Because the Dirichlet forms a prior distribution, we end up with a true distribution and resulting probabilities.

As suggested [here](https://www.baseballprospectus.com/news/article/64534/an-updated-system-of-park-factors-and-volatility/), we can perform a Bayesian sample with `slice_sample` by adding code like this:
``` 
df.2<- df.1 %>%
        dplyr::mutate(
### generate random positive weights ###
           exp_rand = rexp(nrow(df.1), 1),
### normalize to a Dirichlet distribution ###
           samp_weights = exp_rand / sum(exp_rand)) %>%
### sample from the new Dirichlet, with replacement ###
        dplyr::slice_sample(., prop = 1, 
                          weight_by=samp_weights, 
                          replace=TRUE)
```
The additional normalization is arguably unnecessary since I believe `slice_sample` normalizes anyway, but it's good to show your work.

Although this is simple enough to add by hand, I suspect it something many users will be afraid to code or even be aware of themselves, and having a flag available inside the function like `Bayesian = TRUE`  would probably be much easier for them.

Just a suggestion.

**Comment by romainfrancois** [comment]
I believe this would be out of scope for `dplyr` and can be done in another package on top of `dplyr`.

**Comment by hadley** [comment]
Yeah, out of scope.
