### ISSUE TITLE
Error with dplyr recode

### ISSUE THREAD

**Issue by samgardi** [tidyverse/dplyr#5756]
The dplyr recode command doesn't seem to be working correctly.

When running this very simple command:

num_vec <- c(1:4, NA)
recode(num_vec, `2` = 20L, `4` = 40L)

I get an error of:

Error in recode(num_vec, `2` = 20L, `4` = 40L) : 
  unused arguments (`2` = 20, `4` = 40)

I got similar problems when using different code of this unused arguements error but using the above code even gives this error...

Any help would be much appreciated!

**Comment by jmbarbone** [comment]
That error message appears to match the error when using `car::recode()`

``` r
num_vec <- c(1:4, NA)
dplyr::recode(num_vec, `2` = 20L, `4` = 40L)
#> [1]  1 20  3 40 NA
car::recode(num_vec, `2` = 20L, `4` = 40L)
#> Error in car::recode(num_vec, `2` = 20L, `4` = 40L): unused arguments (`2` = 20, `4` = 40)
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Please @samgardi use the `reprex` package when sharing examples, it makes it easier for everyone to see what happens. Here I get this, which seems to be fine: 

``` r
library(dplyr, warn.conflicts = FALSE)
num_vec <- c(1:4, NA)
recode(num_vec, `2` = 20L, `4` = 40L)
#> [1]  1 20  3 40 NA
```

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
