### ISSUE TITLE
Error in group_map() documentation for .f parameter

### ISSUE THREAD

**Issue by FlukeAndFeather** [tidyverse/dplyr#5757]
In the [documentation](https://github.com/tidyverse/dplyr/blob/76b963324861dd4113f0f0d58828e2a977e274a7/R/group_map.R#L37) for `group_map()`/`group_modify()`/`group_walk()`, it says the parameter `.f` "must return a data frame." I believe this is only true for `group_modify()`, not `group_map()` or `group_walk()`.

**Comment by romainfrancois** [comment]
Thanks. I removed it since it is already specified later that: 

```
#'  - `group_modify()` returns a grouped tibble. In that case `.f` must return a data frame.
```

**Comment by FlukeAndFeather** [comment]
Makes sense to me. Thanks!
