### ISSUE TITLE
case_when doesn't carry over var_label attributes (from haven package)

### ISSUE THREAD

**Issue by deschen1** [tidyverse/dplyr#5762]
I'm trying to recode a column that is a labelled object according to the haven package. When trying to create a new column with `case_when` the `var_label` is not retained, but it should be. The operation I'm asking to do `case_when` is just to change values, not anything else (e.g. var_label).

```{r}
library(tidyverse)
library(haven)

df <- structure(list(test = structure(c(NA, NA, 1, 1, 1, NA, NA, 1, 0, 1),
                                       label = "question label",
                                       format.spss = "F8.2",
                                       labels = c(`Not Selected` = 0, Selected = 1),
                                       class = c("haven_labelled", "vctrs_vctr", "double"))),
                row.names = c(NA, -10L),
                class = c("tbl_df", "tbl", "data.frame"))

df %>% var_label()

$test
[1] "question label"

# works fine with recode, but not with case_when
df %>%
  mutate(test_rec_1 = recode(test, "1" = 10, "2" = 20),
         test_rec_2 = case_when(test == 1 ~ 10,
                                test == 2 ~ 20)) %>%
  var_label()

$test
[1] "question label"

$test_rec_1
[1] "question label"

$test_rec_2
NULL
```

**Comment by romainfrancois** [comment]
What happens is that `recode()` has a method to deal with `haven_labelled` objects. 

OTOH, there's no way for `case_when()` to know that it is intended to add that information, it constructs the result based on the numbers `10` and `20`. 

I believe `recode()` is the right tool here, you would have to do some extra work if you really want to use `case_when()`

**Comment by deschen1** [comment]
Question is: if recode has a method to detect what to do about haven_labelled objects, why doesn't case_when? One option could be to allow for an optional parameter (e.g. sth. like "inherit_labels" = TRUE).

There's also a workaround in case_when, since per help function it takes over the structure from the first RHS condition. So

df %>%
  mutate(test_rec_2 = case_when(test == 999 ~test,
                                test == 1 ~ 10,
                                test == 2 ~ 20)) %>%

would work. I.e. creating the first RHS argument in a way that it takes the original vector, but making sure that there's no actual value from the original vector that would be recoded. However, this really is a dirty hack.

Also, the reasons, why I think the case_when is the better tool than recode in general are a) recode is currently questioning and b) case_when is more flexible, i.e. I could create much better recode commands because I can set conditions. With recode I can only recode the all respective values at once, whereas with case_when I can say that I only want to apply a recode if a certain condition is met.
