### ISSUE TITLE
c_across .names

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#5771]
Is there some reason that `across` has a `.names` argument but `c_across` does not?  I was trying to do something like this (which is not valid code) to add row percentage columns

```
BOD %>%
  rowwise %>%
  mutate(100 * proportions(c_across(.names = "%{.col}"))) %>%
  ungroup
```

but it seemed it was necessary to use both `across` and `c_across` to get the effect:

```
BOD %>%
  rowwise %>%
  mutate(100 * across(.names = "%{.col}") / sum(c_across())) %>%
  ungroup
```

giving:

```
# A tibble: 6 x 4
   Time demand `%Time` `%demand`
  <dbl>  <dbl>   <dbl>     <dbl>
1     1    8.3    10.8      89.2
2     2   10.3    16.3      83.7
3     3   19      13.6      86.4
4     4   16      20        80  
5     5   15.6    24.3      75.7
6     7   19.8    26.1      73.9
```

**Comment by hadley** [comment]
Or 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

rowPercent <- function(df) {
  df / rowSums(df) * 100
}

BOD %>%
  mutate(rowPercent(across(.names = "%{.col}")))
#>   Time demand    %Time  %demand
#> 1    1    8.3 10.75269 89.24731
#> 2    2   10.3 16.26016 83.73984
#> 3    3   19.0 13.63636 86.36364
#> 4    4   16.0 20.00000 80.00000
#> 5    5   15.6 24.27184 75.72816
#> 6    7   19.8 26.11940 73.88060
```

<sup>Created on 2021-03-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by romainfrancois** [comment]
We tried to have a `.names=` in #5800 but I was assuming that `c_across()` was only useable in rowwise cases, which it's not so it's not easy to generalize. 

And even there, for `mutate(100 * proportions(c_across(.names = "%{.col}")))` to do what is expected, it would have to return a data frame that can be auto spliced, but here `c_across()` would return a vector, so `proportions()` would too ...

... but `proportions()` does work fine on data frames, so you can actually just use `rowwise()` + `across()` here:

``` r
library(dplyr, warn.conflicts = FALSE)

BOD %>%
  rowwise() %>% 
  mutate(100 * proportions(across(.names = "%{.col}")))
#> # A tibble: 6 x 4
#> # Rowwise: 
#>    Time demand `%Time` `%demand`
#>   <dbl>  <dbl>   <dbl>     <dbl>
#> 1     1    8.3    10.8      89.2
#> 2     2   10.3    16.3      83.7
#> 3     3   19      13.6      86.4
#> 4     4   16      20        80  
#> 5     5   15.6    24.3      75.7
#> 6     7   19.8    26.1      73.9
```

<sup>Created on 2021-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
