### ISSUE TITLE
case_when returns unexpected NA if a whole column is NA

### ISSUE THREAD

**Issue by theOtherJLo** [tidyverse/dplyr#5781]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

If we have a whole column that is NA, then feed it into a case_when to see if it is TRUE, we would expect it to always skip to the next condition. Instead it returns an NA. 

What this means is that if you run the code below, it will throw an error because it should be creating a character vector, but it instead has returned logical values.   

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.0.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tibble(col = c("a", "b"), na = NA) %>% 
  mutate(test = case_when(na ~ TRUE,
                          TRUE ~ "a"))
#> Error: Problem with `mutate()` input `test`.
#> x must be a logical vector, not a character vector.
#> i Input `test` is `case_when(na ~ TRUE, TRUE ~ "a")`.
```

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by hadley** [comment]
Unfortunately, that's not how `case_when()` works; it has to evaluate every column. We'd like to fix that in the future, but it's quite a lot of work.
