### ISSUE TITLE
wrong arithmetic operation result when unquoting a named list using !!

### ISSUE THREAD

**Issue by abekhit** [tidyverse/dplyr#5786]
I may not be using unquotation for the right purpose, but using two `+` functions with unquotation give the wrong answer if unquoted variable comes first. Trying to understand why this is happening and how to correct it. 

related to #5344 

---

Brief description of the problem

```r
library(tidyverse)

multipliers <- list(m1 = 4, m2 = 5)
tb <- tibble(x=3, y= 2, z=5) 

# desired calculations x * y + m1 * x * z + 5 = 71 
(3 * 2) + (4 * 3 * 5) + 5
#> [1] 71

# expression below results in 95
tb %>% mutate(p = x * y + !!multipliers$m1 * x * z  + 5)
#> # A tibble: 1 x 4
#>       x     y     z     p
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     3     2     5    95
  
# if switched locations, it gives the right result 
tb %>% mutate(p = x * y + x * z * !!multipliers$m1 + 5)
#> # A tibble: 1 x 4
#>       x     y     z     p
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     3     2     5    71
```

**Comment by youssefshaker** [comment]
I've had the same problem

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code seems to do more than required to illustrate the problem, and the extra complexity is making it hard for me to understand. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by hadley** [comment]
Oh I figured it out how to make it simpler:

``` r
z <- 1
rlang::expr(x * y + !!z * x * z  + 5)
#> (x * y + 1 * x) * z + 5
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

@lionel- can you please take a look?

**Comment by lionel-** [comment]
It looks like it, I've opened r-lib/rlang#1125 to track this.
