### ISSUE TITLE
appending classes to date variables makes summarise fail

### ISSUE THREAD

**Issue by michaelcurry1123** [tidyverse/dplyr#5787]
If you append a class to Date variables and then try to summarise them the code fails with the error below. It is interesting because you can append the new class you want to work with in front of the date class and the summarise will work fine.  However, if you append the new class to the end the below code does not work. This is relevant because I was trying to determine if adding new classes to a variable would interfere with other R functions. Additionally the logic below seems inconsistent in the fact that order shouldn't matter if the new class was before or after the original date class. 

```R
library(dplyr)
packageVersion("dplyr")
#> [1] '1.0.4'

# data frame with date column
df_date <- data.frame(dates = rep_len(Sys.Date(), 5))

# this works
df_date %>%
  dplyr::summarise_at(vars(dates), min)
#>        dates
#> 1 2021-02-27

# adding another class to the column, and the summarize still works
class(df_date$dates)
#> [1] "Date"
class(df_date$dates) <- c("not_a_class", "Date")
df_date %>%
  dplyr::summarise_at(vars(dates), min)
#>        dates
#> 1 2021-02-27

# put the fake class at the end, and the min() fn works and summarise fails
class(df_date$dates) <- c("Date", "not_a_class")
min(df_date$dates)
#> [1] "2021-02-27"
df_date %>%
  dplyr::summarise_at(vars(dates), min)
# Error: Problem with `summarise()` input `dates`.
# x `vec_cast.Date.Date()` is implemented at C level.
# This R function is purely indicative and should never be called.
# i Input `dates` is `.Primitive("min")(dates)`.
# Run `rlang::last_error()` to see where the error occurred.
```

**Comment by hadley** [comment]
By putting `"not_a_class"` at the _end_ of the class vector the object is no longer a date, so it's not surprising that this doesn't work. The order is _really_ important — you might want to read more about S3 in https://adv-r.hadley.nz/s3.html.

**Comment by michaelcurry1123** [comment]
Ok thank you for  the reference above. I thought it was interesting because the base R min function still works even with the "not_a_class"at the end of the class vector. But I will read more on s3 in R.
