### ISSUE TITLE
%notin% operator implementation

### ISSUE THREAD

**Issue by GitHunter0** [tidyverse/dplyr#5788]
The negation of `%in%` operator is something very handy that allows a clear and concise syntax, however it is missing on base R.

Would you consider implement that in `dplyr`?

[tidytable package](https://github.com/markfairbanks/tidytable) implemented it and can also be created with simply ``` `%notin%`  <- base::Negate(`%in%`) ```.

Nonetheless, it would be far easier and more suitable to have `%notin%` natively loaded together with `dplyr` or `tidyverse`.

Thank you

**Comment by hadley** [comment]
This is something we might consider for the funs package, but I really don't see the advantage of `x %notin% y` over `!x %in% y`.

**Comment by GitHunter0** [comment]
`%notin%` logic is very direct and also avoids the addition of an enclosing parentheses.

For example:
`!( c(1, 4, 6, 9, 10) %in% c(1, 4) )`
versus:
`c(1, 4, 6, 9, 10) %notin% c(1, 4)

And the syntactic sugar of not using parentheses like below feels wrong:
`!c(1, 4, 6, 9, 10) %in% c(1, 4)`
It feels logically wrong because it won't work if we break the pieces and make this:
```
x = !c(1, 4, 6, 9, 10) 
x %in% c(1,4)
```

Nonetheless, thanks for the feedback @hadley  .
