### ISSUE TITLE
Error with  n() and data.table

### ISSUE THREAD

**Issue by matthieugomez** [tidyverse/dplyr#579]
```
library(data.table)
library(dplyr)
dt <- data.table(year = c(2000, 2001), name = c("Tom", "Tom"))
dt %>% group_by(year) %>% filter(n()==1)
```

gives the error
"Error in n() : This function should not be called directly"
but

```
library(data.table)
library(dplyr)
dt <- data.frame(year = c(2000, 2001), name = c("Tom", "Tom"))
dt %>% group_by(year) %>% filter(n()==1)
```

works.

**Comment by zslastman** [comment]
I"m still experiencing this bug, and I'm using dplyr_0.4..

e.g.

mtcars%>%data.table%>%group_by(gear)%>%filter(n()>1)
Error in n() : This function should not be called directly
