### ISSUE TITLE
group_by failing on columns without an order relation (e.g. complex numbers)

### ISSUE THREAD

**Issue by balwierz** [tidyverse/dplyr#5791]
Consider this simple example where a `data.frame` is grouped by a variable which is a complex number:
```r
data.frame(g = complex(real = c(1, 1, 2, 2), 
                       imaginary = c(5, 5, 6, 7)),
           d = 1:4) %>% 
    group_by(g)
```
It result in an error:
```
rlang::last_trace()
<error/rlang_error>
Invalid type returned by `vec_proxy_compare()`.
Backtrace:
    █
 1. ├─`%>%`(...)
 2. ├─dplyr::group_by(., g)
 3. └─dplyr:::group_by.data.frame(., g)
 4.   └─dplyr::grouped_df(groups$data, groups$group_names, .drop)
 5.     └─dplyr:::compute_groups(data, vars, drop = drop)
 6.       └─dplyr:::vec_split_id_order(group_vars)
 7.         ├─vctrs::vec_slice(split_id, vec_order(as.data.frame(split_id$key)))
 8.         └─vctrs::vec_order(as.data.frame(split_id$key))
 9.           └─vctrs:::order_proxy(...)
```

I presume that the problem arises from the code trying to call `vctrs::vec_proxy_compare` on a data type without `<`, `<=` (order) relation.
In my opinion grouping operation should be possible on any type with a `==` (equivalence relation in the mathematical sense) defined. `==` is much more general and easier to define than `<`.
Ordering of the grouping variable, while often useful, is not crucial for most grouping purposes.

PS. Base R `order` is defined for `complex` type.

**Comment by DavisVaughan** [comment]
I think this is just an oversight in vctrs. Complex types are definitely orderable. Will be fixed by https://github.com/r-lib/vctrs/issues/1330
