### ISSUE TITLE
tidyselect and if_all

### ISSUE THREAD

**Issue by essentialols** [tidyverse/dplyr#5802]
Not sure whether I should start a new issue. Closely related to https://github.com/tidyverse/dplyr/issues/5732

When I enter the following

`dplyr::filter(if_all(starts_with("something"), ~.x == 0))`

I get the error "x Can't convert from <integer> to <logical> due to loss of precision."

If I type the following:

`dplyr::filter(if_all(starts_with("something"), .fns = ~.x == 0))`

It works just fine. It took me a bit too long to figure out why it wouldn't accept the first solution.

**Comment by romainfrancois** [comment]
Can you reorganize your examples so that we can run them and see what is happening directly. I would recommend using the reprex package for this. For example, I can't copy and paste these examples, because the `filter()` is not given a data frame to work with.

**Comment by iago-pssjd** [comment]
The next example works to me
```r
anscombe %>% filter(if_all(starts_with("x"), ~.x == 8))
  x1 x2 x3 x4   y1   y2   y3   y4
1  8  8  8  8 6.95 8.14 6.77 5.76
```

**Comment by essentialols** [comment]
I no longer have the data/code where I experienced this behavior. If it's working with the anscombe data, then let's close it.
