### ISSUE TITLE
Add slice_min_max (complementing slice_min and slice_max)

### ISSUE THREAD

**Issue by zeehio** [tidyverse/dplyr#5803]
Hi,

I come with a minor feature request for convenience with a possible implementation: 

Have you considered worth having a `slice_min_max` function to complement `slice_min` and `slice_max`?

I find `slice_min_max()` function convenient to explore the most extreme values of a variable and apparently I'm not alone, since I also found an implementation of `slice_min_max` at Shona Wilde's  ["personal functions package"](https://github.com/shonawilde/shonarrr/blob/master/R/slice_min_max.R) (and we chose the same function name!).

Here is a suggestion of what could be added to the documentation of `slice.R` and a simple implementation.:

```r
#' * `slice_head()` and `slice_tail()` select the first or last rows.
#' * `slice_sample()` randomly selects rows.
#' * `slice_min()` and `slice_max()` select rows with highest or lowest values
#'   of a variable.
#' * `slice_min_max()` combines the respective outputs of `slice_min()` and `slice_max()`, returning `2*n` rows.

slice_min_max <- function(...) {
  bind_rows(
    slice_min(...),
    slice_max(...)
  )
}

```

I could provide a pull request adding that function, if you agree. (And a similar approach could be used on `slice_head_tail()`). Otherwise feel free to close this issue. :+1:  I'll keep using that function on my scripts.

Thanks for your time

**Comment by romainfrancois** [comment]
It feels like this can live outside of `dplyr`. I'm also not sure this would be the right implementation for grouped data frames.

**Comment by zeehio** [comment]
Thank you for the quick feedback. I will then close this issue.
