### ISSUE TITLE
Suggestion: concise switch-style case function implementation

### ISSUE THREAD

**Issue by cochetti** [tidyverse/dplyr#5811]
Brief description of the **suggestion**:

In many languages, there is a `case_when`-like conditional clause. Instead of requiring a full Boolean condition and output pair, it accepts a single input like `inputValue`. Each condition thereafter is assumed to be an exact match or "fall-through" case. 

It has a number of forms depending on the language:

- **SAS:**  `select-when`
- **SQL:** (some flavors)  `case var when comparator then`
- **Java** and **C++**: similar to `switch`

From SAS and SQL, this function is a nice was to create mutually exclusive categories with the first matching condition to output just like `case_when`.  In C++/Java this is a programmatic flow command more comparable to `if` than `if_else` or `case_when`. 

Here is a `case_when` as dplyr currently handles this situation, and the more parsimonious `switch-case` style statement. 

**dplyr `case_when`**
```r
inputObject <- tibble( shape = c( 'triangle', 'trapezoid', 'hexagon', 'pentagon', 'square', 'rectangle') )

inputObject %>%
mutate( vertices = case_when( shape == "triangle" ~ 3,
shape %in% c( 'square', 'rhombus', 'rectangle', 'parallelogram', 'trapezoid', 'quadrilateral') ~ 4,
shape == 'pentagon' ~ 5, 
shape == 'hexagon' ~ 6 ) )
```

**SQL `case` secondary implementation**
In some implementations of SQL there are two forms of the `CASE` statement. One is testing a specific variables against possible values (what I am suggesting to add to dplyr) and the other is arbitrary Boolean statements.  Here these two styles are described in the TERADATA SQL documentation [Using CASE Expressions to Optimize Query Design](https://docs.teradata.com/r/kmuOwjp1zEYg98JsB8fu_A/LMPRZogKY199S9IXIdCBOQ)
```sql

SELECT CASE shape 
WHEN 'triangle' THEN 3
WHEN 'square' THEN 4
WHEN 'pentagon' THEN 5
...
WHEN 'octagon' THEN 8 END as vertices
FROM inputObject;
```

**Suggested `switch` (loosely based on C++/Java)**
```c++
inputObject %>%
mutate( vertices = switch( shape,
case 'triangle': 3, 
case 'square':
case 'rhombus':
case 'rectangle':
case 'parallelogram':
case 'trapezoid':
case 'quadrilateral': 4,
case 'pentagon': 5
case 'hexagon': 6) )
```

This could even be further condensed and with tildes to be more stylistically similar: 

```r
inputObject %>%
mutate( vertices = switch( shape,
case 'triangle' ~ 3, 
case c( 'square', 'rhombus', 'rectangle', 'parallelogram', 'trapezoid', 'quadrilateral') ~ 4,
case 'pentagon' ~ 5,
case 'hexagon' ~ 6,
default ~ 9) )
```

It is still a case_when in form and function, the only difference being that it assumes an equal sign or an %in% relationship between the first parameter and the ... case-statements which then result in the value output. Switches are nice for recoding itemized questionnaires and Likert scales. 

**SAS style `SELECT-WHEN`**
SAS syntax uses SELECT-WHEN in its data step programming to handle these situations. 

Example pulled from SAS blog: [https://blogs.sas.com/content/iml/2016/06/20/select-when-sas-data-step.html](https://blogs.sas.com/content/iml/2016/06/20/select-when-sas-data-step.html)

```sas
/* example of using the SELECT statement */
data Heart / view=Heart;
set sashelp.heart;
select (Smoking_Status);
   when ('Non-smoker')        Smoking_Cat=1;
   when ('Light (1-5)')       Smoking_Cat=2;
   when ('Moderate (6-15)')   Smoking_Cat=3;
   when ('Heavy (16-25)')     Smoking_Cat=4;
   when ('Very Heavy (> 25)') Smoking_Cat=5;
   otherwise                  Smoking_Cat=.;
end;
run;
```

**Numeric Data in Switches:**
There is a language (maybe Java?) that additionally handles ranges when a switch is used with numeric types (and can conceivably be used with any numeric-like format such as dates). There is a caveat with numeric types that the -Inf and Inf ends would need to be used, and to avoid inclusion, exclusion, ambiguous, a direction of such as 40 - <50 years of age, 50 - <60 years. That would look something like this:

_Integer Example_
```r
inputTable <- tibble( inputAge = c( 6, 57, 83, 12, 15 ) )

inputTable %>%
mutate( ageCategory = switch( inputAge,
case -Inf - 17: Child,
case 18 - 65: Adult,
case 66 - Inf: Senior) )
```

_Real Example_
The problem with real numbers is knowing which side of the interval is inclusive and which is exclusive. A parameter **inclusivity** which specifies left or right can handle the continuity problem with real numbers instead of discrete integers as above. 
```r
expectantMoms <- tibble( daysFromConception = c( 6, 57, 83, 12, 15 ) )

expectantMoms %>%
mutate( trimester= switch( daysFromConception %/% 7, inclusivity = "left", 
case 0:13: 1,
case 13:24: 2,
case 24:Inf: 3 ) )
```

**Dates, Intervals, and other Numeric-like types**
```r

tblDates <- tibble( inputDate = c( 2021-01-06, 2021-03-10, 2021-04-01, 2021-11-09) )

tblDates %>%
mutate( season2021 = switch( inputDate, 
case intervalSpring:
case ymd_hms( 2021-03-20 05:37:00 ) [syntax tbd maybe : colon or - dash] ymd_hms( 2021-06-20 23:31:59 ): 
"Spring",

case intervalSummer:
case ymd_hms( 2021-06-20 23:32:00 ) : ymd_hms( 2021-09-22 15:20:59):
"Summer",

case intervalFall:
case ymd_hms( 2021-09-22 15:21:00 ) : ymd_hms( 2021-12-21 10:58:59):
"Fall",

case intervalWinter:
case ymd_hms( 2021-12-21 10:59:00 ) : ymd_hms( 2021-09-22 15:20:59):
"Winter") )
```

**Comment by rossellhayes** [comment]
I've had a stab at implementing this in my package [incase](https://github.com/rossellhayes/incase) which aims to extend `case_when()`.
The function [`switch_case()`](https://github.com/rossellhayes/incase/blob/main/R/switch_case.R) does what you describe. I'd love your feedback on it!
