### ISSUE TITLE
`...` of `across()` are evaluated too early?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#5813]
Not sure why this doesn't work:

```r
library(dplyr)

tibble(x = tibble(foo = 1)) %>%
  mutate(across(
    everything(),
    mutate,
    foo = foo + 1
  ))
#> Error: Problem with `mutate()` input `..1`.
#> ✖ object 'foo' not found
#> ℹ Input `..1` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
```

Ideally `across()` would work the same way as `map()`:

```r
tibble(x = tibble(foo = 1)) %>%
  map(
    mutate,
    foo = foo + 1
  )
#> $x
#> # A tibble: 1 x 1
#>     foo
#>   <dbl>
#> 1     2
```

**Comment by romainfrancois** [comment]
😞 it's again because of the instrumented "top across", e.g. regular across works fine: 

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = tibble(foo = 1)) %>%
  mutate(identity(across(
    everything(),
    mutate,
    foo = foo + 1
  )))
#> # A tibble: 1 x 1
#>   x$foo
#>   <dbl>
#> 1     2
```

<sup>Created on 2021-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Also, should it say ?

```r
Input `..1` is `dplyr:::top_across(...)`
```

**Comment by lionel-** [comment]
I think it's referring to the inner `mutate` that is passed directly to across. Maybe `top_across()` evaluates (parts of?) the expansion too early and should instead recreate the same calls? Then the error would refer to the symbol `mutate` instead of the result of evaluating that symbol.

**Comment by romainfrancois** [comment]
🤔 actually `...` are meant to be evaluated early, this however works fine: 

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = tibble(foo = 1)) %>%
  mutate(across(
    everything(),
    ~mutate(.x, foo = foo + 1)
  ))
#> # A tibble: 1 x 1
#>   x$foo
#>   <dbl>
#> 1     2
```

<sup>Created on 2021-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
nevermind, it's "just" that `top_across()` was eagerly evaluating `...` with `list(...)` when it can be more lazy with `enquos(...)`

**Comment by lionel-** [comment]
Need to be careful about multiple evaluations though. If the mapped function is not a data masking function, the arguments inside `...` must be evaluated only once. Maybe worth adding a unit test for that case.

The best thing is not to capture or collect `...` in any way but just pass them on in the calls, in the proper environment where they are defined. It's also possible to "forward" dots by binding the `...` symbol in an environment to the `DOTSXP` object of another environment. (I don't know if any of this applies here, just laying out the options in case it's useful).
