### ISSUE TITLE
a next group_by and summarise drop the last variable created by summarise

### ISSUE THREAD

**Issue by DavytJ** [tidyverse/dplyr#5818]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

I create a variable by summarise after filter the original data because de calculus need that, so after that I have to join again the data (because using group_by and summarise the data is losed). This variable is dropped when I do a second group_by and summarise. 
In the next example the variable new_variable_1 is dropped

```r
# insert reprex here
df2 <- df1 %>%
  filter(V1 %in% V(g1)$name)   %>% # g1 is a igraph object
  group_by(V2) %>%
  summarise(new_variable_1= case_when(
    is.nan(sum(dist_mat_1[unique(as.character(V1)),unique(as.character(V1))])/(n()*(n()-1))) ~ 0, #dist_mat_1 is a matrix of distance between nodes of the graph g1
    TRUE ~ sum(dist_mat_1[unique(as.character(V1)),unique(as.character(V1))])/(n()*(n()-1)))) %>%
  ungroup() %>%
  right_join(df1,by="V2") %>%
  filter(V1%in% V(g2)$name)   %>% # g1 is a second igraph object
  group_by(V2) %>%
  summarise(new_variable_2 = case_when(
    is.nan(sum(dist_mat_2[unique(as.character(V1)),unique(as.character(V1))])/(n()*(n()-1))) ~ 0, #dist_mat_2 is a matrix of distance between nodes of the graph g2
    TRUE ~ sum(dist_mat_2[unique(as.character(V1)),unique(as.character(V1))])/(n()*(n()-1)))) %>%
  ungroup() %>%
  right_join(df1,by="MRUNANIO")
```

**Comment by romainfrancois** [comment]
Can you please simplify the example to more precisely illustrate the problem. Also, please make sure it is reproducible, i.e. we don't have `df1` or `g1` etc ... You can use the [reprex](https://www.tidyverse.org/help/#reprex) package to assist you.

**Comment by romainfrancois** [comment]
Closing this now. @DavytJ please reopen with a simpler example that can be reproduced.
