### ISSUE TITLE
row_number() function and its documentation have errors, don't describe common use, and are misaligned with function's name

### ISSUE THREAD

**Issue by arencambre** [tidyverse/dplyr#5820]
The documentation for `row_number()` and the function itself needs improvement.

The documentation has two errors in its claim that `row_number()` is "mimicking the ranking functions described in SQL2003". Unlike its implementation in R, `ROW_NUMBER()` in SQL 2003:
1. is a window function, not a ranking function
2. takes no argument

The documentation is deficient because the text and example use of `row_number()` describe things unrelated to the primary use of the function in R, which is to get the current row's number in a data frame or tibble. My view on primary use is reinforced by books (e.g., https://www.tidytextmining.com/tidytext.html), a search on Github (e.g., https://github.com/search?l=R&q=%22row_number%22&type=Code), and the function's own name.

Here's what I propose:

1. Separate `row_number()` into its own documentation page, and make that new page be about the function's intended use, which is certainly not to rank a vector of data. Even if `row_number()` needs to be implemented as a ranking function for its intended use, that is just a coincidence and more of an implementation detail. Outside of that, `row_number()` does not relate to ranking functions, so that could be omitted or downplayed in the documentation.
2. In its documentation, give examples of `row_number()`'s use as a row-number generator. Drop the code example of ranking a vector as that is pointless as an example: it has nothing to do with the function's intended use except as an implementation detail. (It may be fine to document that as code comments as only people checking the source code will care about that behavior.)

Also, is the currently documented way that `row_number()` works, as a ranking function of a vector, necessary for it to function as something that counts rows in data frames or tibbles? If the answer is no, then the whole function needs rethinking. Why was it implemented as a ranking function? Separately, why does it accept an argument? If the argument is not necessary, then that argument needs to be deprecated.

**Comment by romainfrancois** [comment]
@arencambre would you like to work on a pull request ?

**Comment by hadley** [comment]
`row_number()` definitely is a ranking function, and ranking functions are window functions, so I don't think we need any changes here.

**Comment by arencambre** [comment]
@hadley the typical use of `row_number()` (as per my comments/findings above) is to give the row number of rows/observations in data frames or tibbles. That is absent from the documentation, and I think it should be added. If you agree, then this issue is still valid.

**Comment by hadley** [comment]
Yes, that's a valid point, but the overall tone of your issue was rather hostile.

**Comment by arencambre** [comment]
Sorry, was using direct language. I will revise and tighten issue scope to be about documentation.

Is `row_number()`'s `x` argument needed for its primary function of giving row numbers? That may inform if a separate issue is needed for that.

**Comment by arencambre** [comment]
Issue updated.
