### ISSUE TITLE
`if_else()` only gives an error for inconsistent lengths of the first problematic argument

### ISSUE THREAD

**Issue by rossellhayes** [tidyverse/dplyr#5821]
In the following code, `if_else()` gives an error only indicating a problem for `true`, when `false` is also inconsistent with the length of `condition`.
``` r
dplyr::if_else(logical(3), true = character(2), false = character(4))
#> Error: `true` must be length 3 (length of `condition`) or one, not 2.
```
<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

A user who came across this issue may have to run their code, fix the issue with `true`, and run the code again before discovering the issue with `false` (and this whole process again if `missing` is also inconsistent).

This issue occurs because each replacement's length is checked in `replace_with()`. If an extra step was added within `if_else()`, the lengths of `true`, `false`, and `missing` could be checked all at once. This would more closely match the behavior of `case_when()`, which uses `validate_case_when_length()` to report the lengths of all inconsistent conditions at the same time.

I'd be happy to submit a PR if this would be beneficial.

**Comment by romainfrancois** [comment]
it might be useful, but I believe we'll deal with this when we redesign `if_else()` as part of the `funs` package.

**Comment by rossellhayes** [comment]
Looking at the code of `funs` it seems to deal with this problem!
