### ISSUE TITLE
Include example of using a data frame in `mutate()`

### ISSUE THREAD

**Issue by r2evans** [tidyverse/dplyr#5823]
From https://github.com/tidyverse/dplyr/issues/5494#issuecomment-679990205:

> You can already do that in dplyr, just by returning a data frame:
> 
> ```
> library(dplyr, warn.conflicts = FALSE)
> 
> df <- data.frame(x = 1, y = 2)
> 
> my_f <- function(x) {
>   data.frame(x1 = x + 1, x2 = x * 2)
> }
> df %>% mutate(my_f(x))
> #>   x y x1 x2
> #> 1 1 2  2  2
> ```
> 
> Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)

I'm one of today's [lucky 10,000](https://xkcd.com/1053/). I've been using `dplyr` heavily for many years, and for some reason never knew that it was feasible (even desirable) to use unnamed expressions in `mutate`. I think this is one of the more under-sold capabilities of `mutate` and `summarize`. This was in response to a [SO comment](https://stackoverflow.com/questions/66763386/daily-correlation-in-r/66763782?noredirect=1#comment118019219_66763782).

I think it's absolutely useful to know that this works:

```r
mtcars %>%
  group_by(cyl) %>%
  summarize(as.data.frame(cor.test(disp,hp)[c("estimate","p.value")]))
# # A tibble: 3 x 3
#     cyl estimate p.value
# * <dbl>    <dbl>   <dbl>
# 1     4    0.435   0.182
# 2     6   -0.514   0.238
# 3     8    0.118   0.687
```

And while it might seem obvious to some, I cannot find reference to this method in `?mutate` or any of the package `.Rd` files. (It *is* used in several of the tests.)

I can provide a PR, is there interest in adding a mention to this in `mutate` and `summarize` help docs?

**Comment by romainfrancois** [comment]
This is a relatively new feature, that appeared in the 1.0.0 version. For example discussed here in the context of `summarise()` https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-summarise/ 

`as.data.frame(cor.test(disp,hp)[c("estimate","p.value")])` would be quite a chunk though, perhaps we could use something simpler that would immediately show the benefits of returning a data frame.

**Comment by r2evans** [comment]
Certainly, that was a discovery of mine for a SO question. Simpler is likely better, to demonstrate that `mutate(data.frame(..))` works.

**Comment by r2evans** [comment]
I've been thinking about this ... most of the good examples I keep coming up with are named `list`s, not frames, so they keep requiring `as.data.frame` or similar. As a naive example,

```r
tibble(a=c(2,5,9)) %>%
  mutate(approx(1:10, 11:20, xout=a)) # fails
```

(There are better ways to do *that*.) While it's not a beautiful example, it conveys both that it is a straight-forward operation, and that it requires frames.

Perhaps the feature is not intended to be used as such? I might be misinterpreting its intent.

Maybe I should submit a FR that would allow named-lists work like frames in that usage? ... off-topic for this question, but certainly arguable given how the utility seems straight-forward (to me).

**Comment by sajeelsam** [comment]
I am new to using github. I want to contribute to the documentation for `mutate()`
This is my proposed example
```
# Using a custom function in mutate to standardize the mass by dividing mass by its mean
  
stdize <- function(x) { 
  tibble(x = x / mean(x, na.rm = TRUE))
}
starwars %>%
  select(name, mass, species) %>%
  mutate(stdize(mass))
  ```

**Comment by sajeelsam** [comment]
I am new to github. I want to contribute to the documentation of `mutate()`
This is my proposed example
```
#Using a custom function in mutate to standardize the mass by dividing mass by its mean
stdize <- function(x) {
  tibble(x = x / mean(x, na.rm = TRUE))
}
starwars %>%
  select(name, mass, species) %>%
  mutate(stdize(mass))
  ```

**Comment by hadley** [comment]
I'm having a hard time coming up with a simple example, which I think implies that this should go in the programming vignette instead. Then we can do with @delabj's suggestion:

```R
#' # Get normalized and standardized values for mass
#' norm_and_std <- function(x) {
#'   tibble(
#'     "{{x}}_norm" := x / mean(x, na.rm = TRUE),
#'     "{{x}}_std" := (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
#'     )
#' }
#' 
#' starwars %>%
#'   select(name, mass, species) %>%
#'   mutate(norm_and_std(mass))
```
