### ISSUE TITLE
relocate.data.frame: factor out or make default method 

### ISSUE THREAD

**Issue by nealrichardson** [tidyverse/dplyr#5829]
Looking at [relocate.data.frame](https://github.com/tidyverse/dplyr/blob/614389a391504ee17708aca2cce3d92b123ac449/R/relocate.R#L53-L90) in https://github.com/apache/arrow/pull/9798, it seems that the logic there is pretty generic and does not actually require a data.frame. As long as `.data` has a `dim()` method (for `ncol()` on L81), a `[<-` method (L84, to apply the reordering), and a `names()` method (for `tidyselect::eval_select()`), this function should work. 

In the short run, it seems to make sense for us to copy and adapt the `relocate.data.frame` method for Arrow objects rather than try to use the (unexported) dplyr data.frame method off-label. But for the future, we were wondering if there was an opportunity to factor this code differently to allow reuse by non-data.frame backends. Ideas that occurred to us:

* Factor out the core logic and perhaps move to `tidyselect`, as in `vars_relocate` alongside `vars_select` et al. Maybe something like `function(.data, ..., .before = NULL, .after = NULL)` that would return an integer vector of selected/reordered column indices.
* Just rename `relocate.data.frame` to `relocate.default` and then this should just work for any `.data` that has those three methods implemented.

If you think this is worthwhile (or see a better alternative), we're happy to submit a PR.

cc @ianmcook @romainfrancois

**Comment by hadley** [comment]
Yeah, that would be great — dtplyr and dbplyr have also copied and pasted in the code from dplyr.
