### ISSUE TITLE
`transmute` does not work with multiple `across` and column name selection in certain order in first pass

### ISSUE THREAD

**Issue by HYoung1698** [tidyverse/dplyr#5840]
Whenever one try to feed`transmute` multiple value-name pairs (some of them might be `across`), it seems that `across` cannot work properly if it is not the second parameter feed to transmute, **for the first run**  whenever you start a new environment. But when you have run a transmute starting with across, then the error would be gone. Any idea why? 

Big thanks

```r
library(tidyverse)
##So this will return error at first run
transmute(
  .data = foobar, 
  var1, across(.cols = var2:var5))


##But if you run this it will work just fine
transmute(
  .data = foobar, 
  across(.cols = var2:var5), var1)


## And then even weirder, after you run the "across first, then select by name" command, now the first chunk will run normally: 
transmute(
  .data = foobar, 
  var1, across(.cols = var2:var5)) #This suddenly works 

```

**Comment by romainfrancois** [comment]
Can you turn this into a reproducible example, maybe with the help of the `reprex` package ? We do not have dataset `foobar`.

**Comment by romainfrancois** [comment]
It looks like this was fixed: 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(a = 1, b = 2, c = 3, d = 4, e = 5)

transmute(df, a, across(b:e))
#>   a b c d e
#> 1 1 2 3 4 5
transmute(df, across(b:e), a)
#>   b c d e a
#> 1 2 3 4 5 1
transmute(df, a, across(b:e))
#>   a b c d e
#> 1 1 2 3 4 5
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Please reopen with a reprex if mine did not capture the problem.
