### ISSUE TITLE
bind_rows() fails to bind date columns created from arrays

### ISSUE THREAD

**Issue by cboettig** [tidyverse/dplyr#5844]
`bind_rows()` can unexpected fail with an opaque error when given data.frames containing a Date column that has been created from an array.  Here's the reprex:

``` r
time <- array(1:3)
time <- as.Date(time, origin=Sys.Date())
M <- data.frame(time = time)
dplyr::bind_rows(M,M)
#> Error: `vec_cast.Date.Date()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Note that array-structures are often returned by scientific data formats like netcdf (from `ncdf4::ncvar_get`), and after coercion via `as.Date()` (or `lubridate::as_date()`  appear to the user as perfectly valid `Date` class vectors, but are left with a hanging additional attribute, `dim`, on the vector.  It appears to be the presence of this extra attribute that causes the panic and the opaque and seemingly unrelated error that can be very difficult  to debug.  

Note also that `rbind` works fine in the above example.

**Comment by romainfrancois** [comment]
Closing here, as this is tracked in https://github.com/r-lib/vctrs/issues/1329, I've copied the issue content for additional context.
