### ISSUE TITLE
Unfortunate result of `between()` when mixing Date and POSIXct input

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#5850]
Because `between()` converts to numeric and compares the underlying numeric values, the case of accidentally mixing Date and POSIXct input can slip through unnoticed, producing unfortunate results

``` r
today <- as.Date("2019-01-01")
tomorrow <- as.Date("2019-01-02")
now <- as.POSIXct("2019-01-01 01:01:01", tz = "America/New_York")

# unfortunate
dplyr::between(now, today, tomorrow)
#> [1] FALSE

today <- clock::as_date_time(today, "America/New_York")
tomorrow <- clock::as_date_time(tomorrow, "America/New_York")

dplyr::between(now, today, tomorrow)
#> [1] TRUE
```

I think that since `between()` already has a special check for when `x` is a Date or POSIXct, it should also check that `x`, `left`, and `right` all have the same type before continuing

Seen at:
https://twitter.com/asmae_toumi/status/1381695941879722001?s=20

**Comment by hadley** [comment]
I'm pretty sure we're already tracking this in funs.
