### ISSUE TITLE
remove excessive groupby warnings from summarise()

### ISSUE THREAD

**Issue by baderstine** [tidyverse/dplyr#5852]
When you run summarise after grouping by more than one variable, a warning is printed. 
```
`summarise()` has grouped output by 'varname1', 'varname2'. You can override using the `.groups` argument.
```

This warning is produced every single time a user uses the function in the way it was intended.  

---

Brief description of the problem

```r
> mtcars %>% group_by(am, cyl) %>% summarise(mean(mpg))
`summarise()` has grouped output by 'am'. You can override using the `.groups` argument.
# A tibble: 6 x 3
# Groups:   am [2]
     am   cyl `mean(mpg)`
  <dbl> <dbl>       <dbl>
1     0     4        22.9
2     0     6        19.1
3     0     8        15.0
4     1     4        28.1
5     1     6        20.6
6     1     8        15.4
```

To prevent the warning from being printed, I need to add an additional parameter.  But only when there is more than one grouping variable.  This seem arbitrary and against your own stated code standards. 

```
mtcars %>% group_by(am, cyl) %>% summarise(mean(mpg), .groups = "keep")
```

**Comment by pwwang** [comment]
```R
options(dplyr.summarise.inform = FALSE)
```
to disable.

**Comment by hadley** [comment]
We surveyed the community and this behaviour is what most people asked for. As @pwwang points you, you can use the documented option to suppress the messages if you don't like them.

**Comment by baderstine** [comment]
ok thanks

**Comment by benwhalley** [comment]
I don't want to reopen the debate on how noisy summarise should be, and it's great there is a specific option to silence them, but was confused about why these messages don't respond to `message=F` or `warning=F` in knitr output.  Do these 'inform' messages have a different status to regular messages or warnings?
