### ISSUE TITLE
Installation : Error: (converted from warning) package ‘lifecycle’ is not available (for R version 3.5.1)

### ISSUE THREAD

**Issue by rbreunev** [tidyverse/dplyr#5854]
First tried to install latest version of dplyr with : 

`install.packages("dplyr")`

This is the output : 

```
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2018-12-20/src/contrib/dplyr_0.7.8.tar.gz'
Content type 'application/octet-stream' length 719538 bytes (702 KB)
```
So version 0.7.8, not the latest 1.0.5

I then tried : 

`devtools::install_github('tidyverse/dplyr@v1.0.5')`

Output : 

```
Downloading GitHub repo tidyverse/dplyr@v1.0.5
ellipsis (NA -> 0.0.1) [CRAN]
generics (NA -> 0.0.2) [CRAN]
vctrs    (NA -> 0.1.0) [CRAN]
zeallot  (NA -> 0.1.0) [CRAN]
Skipping 1 packages not available: lifecycle
Installing 5 packages: ellipsis, generics, lifecycle, vctrs, zeallot
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Error: (converted from warning) package ‘lifecycle’ is not available (for R version 3.5.1)
Execution halted
```

Bit strange since both latest version of dplyr and lifecycle seems to requests >=3.3 

https://github.com/tidyverse/dplyr/blob/master/DESCRIPTION

https://github.com/r-lib/lifecycle/blob/master/DESCRIPTION 

---

My Environment : 

Docker container based on : rocker/r-ver:3.5.1 

Details : 

$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "3"

$minor
[1] "5.1"

$year
[1] "2018"

$month
[1] "07"

$day
[1] "02"

$`svn rev`
[1] "74947"

$language
[1] "R"

$version.string
[1] "R version 3.5.1 (2018-07-02)"

$nickname
[1] "Feather Spray"

-------------- 

As a fix I'll update the R version of my docker image. Either way DESCRIPTION seems a bit off no ?

**Comment by hadley** [comment]
dplyr is tested to work with R 3.3 and greater, so this seems likely to be some sort of config problem on your end.
