### ISSUE TITLE
Programming vignette: Showcase the difference between `{` and `{{` in tidyeval glue strings

### ISSUE THREAD

**Issue by aviast** [tidyverse/dplyr#5859]
When a new column is created with name calculated from an existing variable the new column name includes quote characters.

```r
library(dplyr)
foo <- tibble(a = 1:10)
prefix <- "prefix"
bar <- mutate(foo, "{{prefix}}_b" := a + 1)
colnames(bar)
```
The output is `[1] "a"            "\"prefix\"_b"` and I would expect to see `[1] "a"            "prefix_b"`

**Comment by romainfrancois** [comment]
This is probably an `rlang` issue: 

``` r
library(rlang)

prefix <- "prefix"
names(quos("{{ prefix }}_b" := 42))
#> [1] "\"prefix\"_b"
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
`{{` is only for function arguments. Strings in variables should be interpolated with the normal glue syntax `{`. You get the expected result with the correct syntax:

```r
mutate(foo, "{prefix}_b" := a + 1)
```

Ideally this usage of `{{` should fail with an error, but this is impossible for technical reasons having to do with bytecode compilation.

**Comment by aviast** [comment]
> `{{` is only for function arguments. Strings in variables should be interpolated with the normal glue syntax `{`.

I've copied the syntax from the documentation: [https://dplyr.tidyverse.org/articles/programming.html#one-or-more-user-supplied-expressions](https://dplyr.tidyverse.org/articles/programming.html#one-or-more-user-supplied-expressions)

**Comment by lionel-** [comment]
The documentation shows the syntax for tunnelling function arguments into a string, which is `{{`. Normal glue interpolation for strings stored in a variable uses `{`. While the documentation is correct, we should probably make it clearer by showing the difference.
