### ISSUE TITLE
summarise_all (with argument, .groups='drop') throws unhelpful error message: "invalid 'type' (character) of argument"

### ISSUE THREAD

**Issue by alwaysandeep** [tidyverse/dplyr#5861]
## What is the issue?
Using .groups='drop' argument in summarise_all throws Error: "invalid 'type' (character) of argument"

![image](https://user-images.githubusercontent.com/21002508/115632004-b8ec2580-a2bb-11eb-9215-411406c3d4f8.png)

![image](https://user-images.githubusercontent.com/21002508/115632032-c7d2d800-a2bb-11eb-87e4-0a63c5942919.png)

## what version of dplyr am i using?
   [1] ‘1.0.5’

## Is there a reproducable code for this issue?
    Yes. please check below
---

## Code reproducing the issue

```r
df_temp =  data.frame(c1=rep(letters[1:3],6),c2=rep(letters[4:6],6),c3=rnorm(18))
head(df_temp)
df_temp %>% group_by(c1,c2) %>% summarise_all( sum,.groups='drop')
```

**Comment by romainfrancois** [comment]
`summarise_all()` is superseded, so its interface is frozen. It predates the introduction of `.groups=` in `summarise()`. 

You can use `summarise(.groups=)` together with `across(everything())` to achieve what you need: 

``` r
library(dplyr, warn.conflicts = FALSE)

df_temp <-  data.frame(c1=rep(letters[1:3],6),c2=rep(letters[4:6],6),c3=rnorm(18))
head(df_temp)
#>   c1 c2         c3
#> 1  a  d  0.6308418
#> 2  b  e -0.3228642
#> 3  c  f  0.6891098
#> 4  a  d  0.8014228
#> 5  b  e -0.9424915
#> 6  c  f -0.4010710
df_temp %>% 
  group_by(c1,c2) %>% 
  summarise(across(everything(), sum), .groups='drop')
#> # A tibble: 3 x 3
#>   c1    c2        c3
#>   <chr> <chr>  <dbl>
#> 1 a     d      1.26 
#> 2 b     e     -2.26 
#> 3 c     f     -0.430
```

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by alwaysandeep** [comment]
@romainfrancois thank you for pointing that out.
