### ISSUE TITLE
across() and c_across() fail when anti-selecting grouping variables

### ISSUE THREAD

**Issue by djvill** [tidyverse/dplyr#5864]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

The `across()` help states "Because `across()` is used within functions like `summarise()` and `mutate()`, you can't select or compute upon grouping variables." It makes sense that we shouldn't alter our grouping variables. However, if I try to anti-select (or complement-select) a grouping variable within `across()` or `c_across()`, I get the error "Can't subset columns that don't exist".

Reprex:

``` r
library(dplyr, warn.conflicts = FALSE)
#> Warning: package 'dplyr' was built under R version 4.0.5

iris %>% 
  group_by(Species) %>%
  mutate(across(!Species, ~ .x * 1000))
#> Error: Problem with `mutate()` input `..1`.
#> x Can't subset columns that don't exist.
#> x Column `Species` doesn't exist.
#> i Input `..1` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
#> i The error occurred in group 1: Species = "setosa".

iris %>% 
  group_by(Species) %>%
  mutate(mySum = sum(c_across(-Species)))
#> Note: Using an external vector in selections is ambiguous.
#> i Use `all_of(Species)` instead of `Species` to silence this message.
#> i See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
#> This message is displayed once per session.
#> Error: Problem with `mutate()` input `mySum`.
#> x Can't subset columns that don't exist.
#> x Columns `setosa`, `setosa`, `setosa`, `setosa`, `setosa`, etc. don't exist.
#> i Input `mySum` is `sum(c_across(-Species))`.
#> i The error occurred in group 1: Species = "setosa".
```

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I got this error R version 4.0.3 and dplyr version 1.0.5

**Comment by hadley** [comment]
This is expected; the grouping variables are not included in the list of variables that you can select from.
