### ISSUE TITLE
Can a single polymorphic across() be defined for column-wise (default) and row-wise ops?

### ISSUE THREAD

**Issue by scottlyden** [tidyverse/dplyr#5867]
I'm questioning the need to have both across() and c_across().  Is there an actual use-case for the current across() in rowwise mode?  I'm not smart enough to think of one.  If there isn't a use-case, then can the behavior of across just be different in column-wise and row-wise modes, eliminating the need to know another function?

**Comment by hadley** [comment]
I don't recall the details of our analysis, but this is definitely something we consider and rejected.
