### ISSUE TITLE
tbl_df[, i] shouldn't coerce to vector

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#587]

**Comment by Fablepongiste** [comment]
So is this definitive or a rollback still studied ?

will this code always give different results :
df <- data.frame(a = c(1:3), b = c(2:10))
df[,'a'] -> returns vector numeric
# 
tbl_df(df)[,'a']  -> returns a local data frame with one column a ?

And if yes, you advise to use df[['a']] and tbl_df(df)[['a']] for consistent behaviour between both ?

**Comment by hadley** [comment]
I'm pretty sure this behaviour is going to stay. Use `[` to return a data frame, use `[[` to return a column.
