### ISSUE TITLE
using filter on a vector instead of tibble uses filter_ and gives strange error because of this: error: [....] filter_ is deprecated. 

### ISSUE THREAD

**Issue by vinnief** [tidyverse/dplyr#5870]
Brief description of the problem
calling dplyr::filter on a vector calls filter_ and then generates a small error about filter_ and a large warning which obfuscates the error:
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "date"  (note: also not for numeric, or character)
In addition: Warning message:
`filter_()` is deprecated as of dplyr 0.7.0.
Please use `filter()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

```r
# insert reprex here
using(tidyverse)
c(1,2,3) %>% filter("date" == "2020-09-17)

```
Note the error is correct, and this command is not going to work. But i got to the vector by subsetting a dataset: data$date by mistake. 
The issue is because it calls filter_  and i get the warnng about filter_ being deprecated, instead of debugging my own command I was looking where I was using the deprecated function. Tidyverse should not use its own deprecated function and then complain to me.

**Comment by romainfrancois** [comment]
This has been fixed in 1.0.6: 

``` r
library(tidyverse)
c(1,2,3) %>% 
  filter("date" == "2020-09-17")
#> Error in UseMethod("filter"): no applicable method for 'filter' applied to an object of class "c('double', 'numeric')"
```

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
