### ISSUE TITLE
Suggestion: case_when() should provide notification that NA values in the test were assigned the TRUE value

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#5871]
Having used `case_when()` for years, I was quite worried today when I discovered that `case_when()` handles NA values in the test differently than `if_else()` and `ifelse()`:

![image](https://user-images.githubusercontent.com/25590353/116913632-f7140e00-ac06-11eb-8fe4-653a1dba0688.png)

After discovering this behavior, I see that there is a note about this buried in the `case_when()` documentation examples section:

```
# Note that NA values in the vector x do not get special treatment. If you want
# to explicitly handle NA values you can use the `is.na` function:
x[2:4] <- NA_real_
case_when(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  is.na(x) ~ "nope",
  TRUE ~ as.character(x)
)
```

So now I know, but polling my team members at work reveals that none of them were aware of this behavior either. 

My assumption has been that `case_when()`handles NA values in the test the same way `if_else()` does and return an `NA`  UNLESS the NA values are specifically dealt with, rather than the other way around where they get the `TRUE` value if left unspecified.  Consider that a basic test like `NA == TRUE` yields `NA`, and `NA == NA` also yields `NA`, further adding to my feeling that this is unexpected behavior: NA test values should yield an NA result for the `TRUE ~ x` line in `case_when()`.

But regardless of whether this behavior is better for some reason (I'd love to understand if so!), it's obviously way too late to change it. I think it might be a good idea to include a warning/message when NAs exist in the tests but are treated as TRUE, ie "NA values in the data were handled by TRUE ~.  Did you mean to specify a case for NA values?".  There is precedent for this in other functions such as converting a character vector of mostly numeric values when there are some non-numeric values.

**Comment by romainfrancois** [comment]
Moved to the `funs` issue about `case_when()`
