### ISSUE TITLE
Feature request: coalesce working backwards, i.e. returning the last non-missing column

### ISSUE THREAD

**Issue by deschen1** [tidyverse/dplyr#5873]
Title explains it all. `coalesce` returns the first non-missing passed column/vector value. However, there are use-cases where the opposite would be helpful, i.e. returning the last non-missing value from several columns/vectors.

**Comment by romainfrancois** [comment]
Moving this to an issue of `funs` where we will revisit `coalesce()`: https://github.com/tidyverse/funs/issues/54
