### ISSUE TITLE
Unwanted type-check in case_when() when dealing with numerics

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/dplyr#5876]
`case_when()` and `if_else()` perform type-checks and it is for the best in most cases.

However, some data type are usually fully exchangeable, e.g. integers and doubles.

Therefore, you can experience some unwanted type-checking that makes little to no sense:

``` r
library(tidyverse)

df = read.table(header=TRUE, text="
  id check count_x
1  8     0       0
2  8     1       1
3  8     1       2
8  8     0       3
9  8     0       3")

case_when(
  df$count_x==0 ~ df$check,
  df$count_x>0 ~ 1,
)
#> Error: must be an integer vector, not a double vector.

if_else(df$count_x==0, df$check, 1)
#> Error: `false` must be an integer vector, not a double vector.
```
<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Of course, casting the variable to plain numeric will work, using `as.numeric()` or simply `+0`, but it seems quite unnecessary:

``` r
case_when(
  df$count_x==0 ~ df$check+0,
  df$count_x>0 ~ 1,
)
#> [1] 0 1 1 1 1
```
<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Maybe the type-checking could be a bit more flexible in some cases, such as this one.

**Comment by romainfrancois** [comment]
`case_when()` will be reworked here: https://github.com/tidyverse/funs/issues/38
