### ISSUE TITLE
[BUG  REPORT] read_delim issue

### ISSUE THREAD

**Issue by mewu3** [tidyverse/dplyr#5879]
I got a problem when I tried to use read_delim in R studio, the same code work fine thought in commanded line with Rstript. 
Maybe here is not the right place to report this bug, please alert me if I have mistaken. 

Here is an example of the file allOligo_before.tsv
```
	oligo	kmerCount	CG%	Entropy	Tm	homodimer-dG	hairpin-dG	start	end
23526	CTCCCACCGTACA	2	61.538	0.835	38.408	-2688.954	0.0	45933	46057
12427	CTCCCACCGTACA	2	61.538	0.835	38.408	-2688.954	0.0	45682	46057
22710	GGAGACTTGGAAA	2	46.154	0.88	32.1	-1364.491	0.0	45431	45932
33357	ACGTCAATGGAAA	2	38.462	0.917	28.946	-1955.659	0.0	45180	45681
29768	GCGGTATTTCACA	2	46.154	0.994	32.1	-2222.586	0.0	44929	45430
6673	TTTTAAATAAAAA	2	0.0	0.481	13.177	-1623.157	453.733	44678	45179
26049	CTTAACGTAAAAA	2	23.077	0.835	22.638	-3047.769	0.0	44427	44928
20921	GACGACATGTCAA	2	46.154	0.961	32.1	-7148.945	-574.652	44176	44677
140	CCCAGACTAATAA	2	38.462	0.869	28.946	-1274.076	0.0	43925	44426
31259	ACCGACGATACAA	2	46.154	0.869	32.1	-3820.339	0.0	43674	44175
``` 

```r
> read_delim(file="/home/meijun/Documents/server/data/MSSPE-variant/enterovirusCurated/kmer15/evaluation/allOligo_before.tsv", delim="\t")
Error in if (dark) { : valeur manquante là où TRUE / FALSE est requis
```

**Comment by batpigandme** [comment]
[`read_delim()`](https://readr.tidyverse.org/reference/read_delim.html) is a function from the [readr](https://readr.tidyverse.org/) package. So, if you find that there isn't already a related thread, you can open an issue there.
https://github.com/tidyverse/readr/issues

If you please turn it into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample), it'll be even easier to troubleshoot.

Thanks.
