### ISSUE TITLE
Changes in how internal functions are handled in across() breaks AMR

### ISSUE THREAD

**Issue by michaelquinn32** [tidyverse/dplyr#5881]
Hi team!

This was originally reported in ropensci/skimr/issues/664, but I'm not fully certain how to address it there.

The user defines their own `skimr` summary functions in a package, some of these functions are internal:
https://github.com/msberends/AMR/blob/551f99dc8fa6278b0a5bb5670153438e88135dec/R/aa_helper_pm_functions.R#L566

After updating to dplyr 1.0.6, their checks on CRAN on failing.
https://cran.r-project.org/web/checks/check_results_AMR.html

Please let me know if this is a `skimr` issue, and I can update accordingly.

Thanks for everything!

cc: @msberends

**Comment by msberends** [comment]
Note from AMR dev team: solved this in master by removing the dependency on an internal function. So not a problem for our package anymore. 

Important to note though; the `skimr:::sfl()` method uses `across()` to calculate statistics for all groups. Until dplyr 1.5.0 all was working fine.

**Comment by romainfrancois** [comment]
I believe this might be related to this comment: 

```r
# Note that the current implementation is not 100% correct in that
# regard as we ignore the environment of formulas and instead use the
# quosure environment. This means this doesn't work as expected:
#
# ```
# local({
#   prefix <- "foo"
#   f <- ~ paste(prefix, .x)
# })
# mutate(data, across(sel, f))
# ```
#
# If we inspected unevaluated calls instead, we would see a symbol `f`
# and fall through the `as_function()` branch.
```

here: https://github.com/tidyverse/dplyr/blob/cfb3b7146c22e03ef73bc5902c7220a36a4113a9/R/across.R#L580

I can reproduce the problem, with cran version of `AMR` (not current master which has an alternative fix) and this: 

``` r
library(AMR)
library(skimr)

skim(example_isolates)
#> Error: Problem with `summarise()` column `skimmed`.
#> ℹ `skimmed = purrr::map2(...)`.
#> x Problem with `summarise()` input `..1`.
#> ℹ `..1 = dplyr::across(variable_names, mangled_skimmers$funs)`.
#> x could not find function "pm_n_distinct"
```

<sup>Created on 2021-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by msberends** [comment]
Wow, you’re awesome 🤩
