### ISSUE TITLE
Number of storms in `storms`

### ISSUE THREAD

**Issue by speegled** [tidyverse/dplyr#5899]
The documentation of `storms` indicates that there are 198 storms in `storms`. I believe that 198 is the number of different names, but that there are 425 different storms. There are 426 unique name/year combinations, and I think that Zeta (2005-2006) is the only storm in the data set that was active over two calendar years.

**Comment by romainfrancois** [comment]
It might also be time to update the data, it looks like there is more data now here: https://www.nhc.noaa.gov/data/#hurdat
