### ISSUE TITLE
rows_update() is not sf friendly like other dplyr functions

### ISSUE THREAD

**Issue by andresrcs** [tidyverse/dplyr#5906]
When applied to an `sf` object,  `rows_update()` throws the error message `#> Error: Attempting to update missing rows.` but if I transform the object to a `tibble` first, it works just fine, and then I can get back to an `sf` object with `sf::st_as_sf()`, which is not an ideal workflow. Could you make  `rows_update()` function `sf` friendly like other `dplyr` functions?
``` r
library(dplyr)
library(rnaturalearth)

ne_states(country = "peru", returnclass = "sf") %>%
    select(name, name_len) %>% 
    filter(name %in% c("Arequipa", "Lima")) %>% 
    rows_update(tibble(name = "Arequipa", name_len = 0), by = "name")
#> Error: Attempting to update missing rows.

ne_states(country = "peru", returnclass = "sf") %>%
    select(name, name_len) %>% 
    filter(name %in% c("Arequipa", "Lima")) %>% 
    as_tibble() %>% 
    rows_update(tibble(name = "Arequipa", name_len = 0), by = "name")
#> # A tibble: 2 x 3
#>   name     name_len                                                     geometry
#>   <chr>       <int>                                           <MULTIPOLYGON [°]>
#> 1 Arequipa        0 (((-71.48848 -17.31799, -71.49771 -17.29713, -71.51452 -17.…
#> 2 Lima            4 (((-76.24919 -13.32044, -76.27428 -13.28729, -76.30695 -13.…
```

<sup>Created on 2021-06-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
Can you have a look @krlmlr ?

**Comment by krlmlr** [comment]
Thanks. My first instinct is to suggest implementing `rows_update()` and friends in the sf package, even if it's with a wrapper `as_tibble() %>% rows_update() %>% st_as_sf()` . I'll take a look and propose something.

**Comment by jbeaulie** [comment]
This issue was 'closed as completed' but the problem documented in the original post persists with dplyr_1.1.4, except the error message has changed:
Error in `rows_update()`:  
! Can't reconstruct data frame.  
✖ The `[` method for class <sf/data.frame> must return a data frame with 1 column.  
ℹ It returned a <sf/data.frame> of 2 columns.
