### ISSUE TITLE
bind_rows() Feature Suggestion: Allow coercion to character for non-matching column classes

### ISSUE THREAD

**Issue by RSchwinn** [tidyverse/dplyr#5907]
Please consider allowing coercion of column types in **bind_rows** commands.

```r
suppressPackageStartupMessages(require(tidyverse))

mtcars_char <- mtcars %>% mutate(mpg = as.character(mpg))

bind_rows(mtcars, mtcars_char)
# Error: Can't combine `..1$mpg` <double> and `..2$mpg` <character>.
```

This is a repeat of [Jonathon Zadra's suggestion from 2019.](https://github.com/tidyverse/dplyr/issues/4281) The given reply was that this was already available for **vctrs::vec_rbind()**, but it is not. The following fails:

```r
library(dplyr, warn.conflicts = FALSE)
library(vctrs)

mtcars_char <- mtcars %>% mutate(mpg = as.character(mpg))

vec_rbind(mtcars, mtcars_char, .ptype = mtcars) %>% 
  as_tibble()

# Error: Can't convert `$mpg` <character> to match type of `$mpg` <double>.
```

**Comment by romainfrancois** [comment]
`vctrs` does not consider the cast from numeric to character to be sensible: 

``` r
vctrs::vec_cast(mtcars$mpg, character())
#> Error: Can't convert <double> to <character>.
```

<sup>Created on 2021-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

One would have to specifically convert using e.g. `as.character()`.

**Comment by RSchwinn** [comment]
Please reopen. You obviously did not read my post.

**Comment by lionel-** [comment]
dplyr uses the tidyverse rules of coercion as defined in the vctrs package https://vctrs.r-lib.org/reference/faq-compatibility-types.html
