### ISSUE TITLE
Unexpected performance cost when passing additional arguments to across() after group_by()

### ISSUE THREAD

**Issue by nhols** [tidyverse/dplyr#5909]
I'm trying to pass extra arguments to `across()` on a grouped dataframe and I'm noticing an unexpected performance cost of ~5x. The 5 functions below do the same thing but `fun_across_plus_args()` is taking longer than expected. 

I'm migrating from the `[verb]_at()` syntax to `acorss()` so have included `[verb]_at()` benchmarks

Setting additional arguments in an anonymous function `fun_across_anon_fun()` avoids this performance hit

``` r
library(microbenchmark)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '1.0.6'

df <- tibble(x = 1:10, y = 1:10, z = 1:10)

fun_at_no_args <- function(df){
  df %>% group_by(x) %>% mutate_at(c("y", "z"), mean)
}

fun_across_no_args <- function(df){
  df %>% group_by(x) %>% mutate(across(c("y", "z"), mean))
}

fun_at_plus_args <- function(df){
  df %>% group_by(x) %>% mutate_at(c("y", "z"), mean, na.rm = FALSE)
}

fun_across_plus_args <- function(df){
  df %>% group_by(x) %>% mutate(across(c("y", "z"), mean, na.rm = FALSE))
}

fun_across_anon_fun <- function(df){
  df %>% group_by(x) %>% mutate(across(c("y", "z"), ~ mean(., na.rm = FALSE)))
}

bench <- 
  microbenchmark(
    fun_at_no_args(df),
    fun_at_plus_args(df),
    fun_across_no_args(df),
    fun_across_plus_args(df),
    fun_across_anon_fun(df)
  )

ggplot2::autoplot(bench)
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/qQTvm9X.png)

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
Unfortunately this form of `across()` can't benefit from optimizations we used elsewhere, dealing with `across(...)` is tricky and more expensive to do right. 

The workaround of using a lambda is the right way to get to best performance.
