### ISSUE TITLE
Variables created inside group_by with .add = TRUE do not respect existing groups

### ISSUE THREAD

**Issue by AltfunsMA** [tidyverse/dplyr#5913]
As per the title, the two code chunks below were previously equivalent. Some old code relied on this behaviour although I'm not sure I see the point of using it now. That old code was somewhat more complex than my sample below but I've now rewritten it more cleanly with `across` calls inside a large `summarise` call.

I've noticed this after upgrading to dplyr 1.0.6 on R 4.1.0. I'm unsure what my previous dplyr version was.

```r
mtcars %>% 
  group_by(cyl) %>% 
  group_by(mean_mpg= mean(mpg),
           .add = TRUE) %>% 
  summarise(final = mean(wt))

# A tibble: 3 x 3
# Groups:   cyl [3]
    cyl mean_mpg final
  <dbl>    <dbl> <dbl>
1     4     20.1  2.29
2     6     20.1  3.12
3     8     20.1  4.00



mtcars %>% 
  group_by(cyl) %>% 
  mutate(mean_mpg= mean(mpg)) %>% 
  group_by(mean_mpg, .add = TRUE) %>% 
  summarise(final = mean(wt))

 # A tibble: 3 x 3
# Groups:   cyl [3]
    cyl mean_mpg final
  <dbl>    <dbl> <dbl>
1     4     26.7  2.29
2     6     19.7  3.12
3     8     15.1  4.00



```

**Comment by romainfrancois** [comment]
This has been introduced in `dplyr` 1.0.3 (#5598). Doing the `mutate()`step explicitly is the right workaround. 

```
group_by() uses the ungrouped data for the implicit mutate step (#5598). You might have to define an ungroup() method for custom classes. For example, see https://github.com/hadley/cubelyr/pull/3.
```
