### ISSUE TITLE
Port plyr::mapvalues() equivalent into dplyr

### ISSUE THREAD

**Issue by aloboa** [tidyverse/dplyr#5919]
ref. https://github.com/tidyverse/dplyr/issues/4310
(cannot write into that issue because it was blocked).

The currently suggested alternatives for plyr::mapvalues() in dplyr are inconvenient.
In the case of

    dplyr::recode(z, `1`  = 10, `5` = 50, `9` = 90)

the solution is unbearable as soon as the "from" and "to" vectors are longer than 3 elements.

In the case of

    recode(z, !!! setNames(to, from))

the code is just inextricable.

It would be so much friendlier just having a function dplyr::mapvalues()
as a wrapper for the last solution, i.e. as suggested in
https://stackoverflow.com/questions/62216940/dplyr-alternative-for-plyrmapvalues-recode-using-dictionary

While implementing that solution as a personal function is easy, using personal functions for
such a general tool is not a good idea, as R scripts would easily become unintelligible to other people.

**Comment by romainfrancois** [comment]
We are in the process of designing a better `recode()` in the funs package. We're not sure at this point what it will be.

**Comment by aloboa** [comment]
I'm confused, do we have an equivalent to plyr::mapvalues() in dplyr or in any other tidyverse package?
If you have closed this, I understand it should exist, but cannot find it.

**Comment by hadley** [comment]
The new `case_switch()` is a good equivalent.

**Comment by thomasjwood** [comment]
Is `case_switch` documented somewhere?

**Comment by olivroy** [comment]
Probably referring to [`case_match()`](https://dplyr.tidyverse.org/reference/case_match.html).

**Comment by aloboa** [comment]
Could you include as an example the equivalent to:
```
z <- c(1, 4, 5, 9)
dict <- list(from=c(1,5,9), to=c("a","x","r"))
z.new <- mapvalues(z, from = dict$from to = dict$to)
```

which is what is really needed by users?
Please note that being able to include an object such as `dict` within `case_match() `is much needed. 
 Also, I would prefer a devoted, standard "recode()" function for this specific, very usual, application of case_match()
