### ISSUE TITLE
Random sampling from external databases

### ISSUE THREAD

**Issue by kylelundstedt** [tidyverse/dplyr#592]
Hello,

As an inexperienced R user, it's been a HUGE pleasure to find the dplyr package, along with the other "Hadleyverse" packages.  Recently, I've been using dplyr connected to an Amazon Redshift database cluster.  While most of the functions work great, I found that using the new "sample_n" function when connected to Redshift produces "Error: Don't know how to sample from objects of class tbl_postgres".

I looked at the [sample.R code](https://github.com/hadley/dplyr/blob/master/R/sample.R) that produces the error, but could not figure out a way to add the functionality myself.  However, I did some searching and found this [link](http://www.statsblogs.com/2014/02/26/taking-a-random-sample-on-amazon-redshift/), which describes a simple (five line) piece of SQL code for doing random samples on Redshift.

I don't know if this code is any help.  I'm also just learning how to use Git (along with R), so I apologize for not knowing how to code up a proposed solution and submit a pull request.  Thanks again for all of your hard work on behalf of R users!

Regards,
Kyle

**Comment by yijiang1121** [comment]
Thanks, kylelundstedt and hadley. So this means that dplyr currently doesn't support sample_n and sample_frac for Postgres, right?

**Comment by kylelundstedt** [comment]
Yijiang,
If you look at the [sample.R code](https://github.com/hadley/dplyr/blob/master/R/sample.R)  in this repo, it specifically states that the sampling functions only work on local data.  So, unless I'm missing something, we'll just need to patiently await further magic from Hadley.

BTW, as a fellow Bay Area person, did you see his "pipelines" presentation at Berkeley last week?  It was really interesting!  Here's a [link](http://bids.berkeley.edu/resources/videos/pipelines-data-analysis) to the video if you missed it.

Cheers,
Kyle

**Comment by kylelundstedt** [comment]
@garrettgman, you provide a method for random sampling from Redshift in [this file](https://github.com/rstudio/webinars/blob/master/14-Work-with-big-data/webinar.R).  As discussed in the thread above, does your random sampling code produce results equivalent to the sample_n function, if that function worked on Redshift?  Just trying to get my head around this.  😬

**Comment by kylelundstedt** [comment]
In case anyone is wondering, @garrettgman's sampling code works great on AWS Redshift.  Here's the code for a 1% sample:

```r
sample_dataset <- raw_table %>%
  select(variable1, variable2) %>%
  mutate(x = random()) %>% compute() %>%
  filter(x <= 0.01) %>% select(-x)
```
