### ISSUE TITLE
mutate() with empty RHS succeeds silently

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#5925]
but should fail perhaps?

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tibble() %>% 
  mutate(bogus = )
#> # A tibble: 0 x 0
```

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
It's because of this line in `dplyr_quosures()` : 

```r
quosures <- enquos(..., .ignore_empty = "all")
```

I don't think there is a way to say "ignore the *named* empty" cc @lionel-

**Comment by lionel-** [comment]
We could add `.ignore_empty = "unnamed"`?

**Comment by lionel-** [comment]
Actually this is a bug in `enquos()`:

```r
quos(x = , .ignore_empty = "all")
#> <list_of<quosure>>
#>
#> $x
#> <quosure>
#> expr: ^
#> env:  empty

fn <- function(...) enquos(..., .ignore_empty = "all")
fn(x = )
#> <list_of<quosure>>
#> named list()
```

Named missing arguments should not be considered "empty".

You could fix this in the meantime by using `quos()` @romainfrancois (which is currently faster as well).
