### ISSUE TITLE
Unexpected behaviour of factors created within groups

### ISSUE THREAD

**Issue by mkuhn** [tidyverse/dplyr#5930]
I have tried to create factors with different levels within groups on purpose to extract indices, and was surprised that `mutate` after `group_by` seems to merge the factors automatically across groups, even before creating the next variable. Not sure if this is a bug or a feature! 

See reprex below (dplyr version 1.0.7): I was expecting to see the values of column `h` in `g` as well. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tibble)

d <- tibble(
  a = c(1,1,1,2,2,2,3,3,3),
  b = c(1,2,3,2,3,4,3,4,5)
)

d %>% group_by(a) %>% 
  mutate(f = factor(b), 
         g = as.integer(f),
         h = as.integer(factor(b)))
#> # A tibble: 9 x 5
#> # Groups:   a [3]
#>       a     b f         g     h
#>   <dbl> <dbl> <fct> <int> <int>
#> 1     1     1 1         1     1
#> 2     1     2 2         2     2
#> 3     1     3 3         3     3
#> 4     2     2 2         2     1
#> 5     2     3 3         3     2
#> 6     2     4 4         4     3
#> 7     3     3 3         3     1
#> 8     3     4 4         4     2
#> 9     3     5 5         5     3
```

<sup>Created on 2021-06-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mkuhn** [comment]
Trawling through the repo I found this in the release notes for dplyr 1.0.0: 

> Combining multiple factors creates a factor with combined levels; previously it created a character vector with a warning.

So it seems like the silent combining is expected, though at the moment not documented for `mutate` in the section on [grouped data](https://github.com/tidyverse/dplyr/blob/a25657c46b1107e02d4961651250682b5f3d167e/man/mutate.Rd#L90).

**Comment by romainfrancois** [comment]
results from all groups are cast to their common type in https://github.com/tidyverse/dplyr/blob/b0d0e865af6811f795ede9cfbd2e1150328c6b92/R/mutate.R#L317

so you get: 

``` r
vctrs::vec_cast_common(factor(c(1, 2, 3)), factor(c(2, 3, 4)), factor(c(3, 4, 5)))
#> [[1]]
#> [1] 1 2 3
#> Levels: 1 2 3 4 5
#> 
#> [[2]]
#> [1] 2 3 4
#> Levels: 1 2 3 4 5
#> 
#> [[3]]
#> [1] 3 4 5
#> Levels: 1 2 3 4 5
```

<sup>Created on 2021-06-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
