### ISSUE TITLE
Is slice(0) giving an empty tibble off-label usage

### ISSUE THREAD

**Issue by charliejhadley** [tidyverse/dplyr#5934]
I've been using `slice(0)` to create an empty tibble but I now want to check if it's considered "off-label" use.

Here's a reprex

```r
library("tidyverse")

empty_data <- tibble(
  country = "character",
  pop = 1,
  lifeExp = 1,
  gdpPercap = 1
) %>% 
  slice(0)

empty_data %>% 
  add_row(country = "Antarctica", pop = 12, lifeExp = 120, gdpPercap = 10)
```

A real-world example of doing this is creating an empty tibble with correct column formatting in shiny apps within `reactiveValues()`

**Comment by romainfrancois** [comment]
it's probably ok, but I think I'd use `vctrs::vec_ptype()` instead.
