### ISSUE TITLE
temporary variables in `mutate()`

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#5937]
Sometimes one wants a temporary variable in mutate that is used by other variables defined in the same mutate.  One can add another column and then remove it again but that is quite ugly and it would be nice if there were some way to define a temporary variable.  For example, (1) a name convention or (2) temp(...) similarly to across(...) or (3) perhaps there could be a variation of mutate in which the first argument is automatically removed when the mutate ends.

Here is an example.  the code uses do({...}) to allow for creation of a temporary variable but it would be nice if there were some way to incorporate that into the mutate.  `indexList` is the temporary variable.

```r
library(dplyr)
library(zoo)

# input
set.seed(123)
A <- cumsum(rnorm(200))
Date <- as.Date("2021-06-29") + cumsum(sample(5, 200, replace = TRUE))
data <- data.frame(Date, A) %>% mutate(Year_Month = as.yearmon(Date))

# returns vector of indexes to prior 12 months
# ix is row number (scalar); ym is yearmon vector.
indexes <- function(ix, ym, x = ym[ix]) which(ym >= x-1 & ym <= x - 1/12) 

data %>%
 do( {   # "do" in case it later needs to be embedded in group_by
    indexList <- lapply(1:nrow(.), indexes, .$Year_Month) 
    mutate(., B = sapply(indexList, function(x) mean(A[x])), n = lengths(indexList))
  })
```

**Comment by romainfrancois** [comment]
I think I would approach this with returning a data.frame to be auto spliced. Something like the pseudo-code: 

```r
data %>%
  mutate({
     indexList <- <...>
     data.frame(B = <...>, n = <...>)
  })
```

preferably using a named function for clarity : 

```r
fun <- function(<...>) {
  indexList <- <...>
  data.frame(B = <...>, n = <...>)
}
data %>%
  mutate(fun(<...>))
```

**Comment by romainfrancois** [comment]
Another approach could be to have a function that signals the volatility of the variable(s) and a `mutate()` variant that handles the signal, e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)

volatile <- function(...) {
  out <- data.frame(...)
  rlang::signal("", class = "volatile", names = names(out))
  out
}

mutate2 <- function(.data, ...) {
  forget <- character()
  out <- withCallingHandlers(mutate(.data, ...), volatile = function(v) {
    forget <<- c(forget, v$names)
  })
  forget <- unique(forget)
  select(out, -all_of(forget))
}

data.frame(x = 1:2) %>% 
  mutate2(
    volatile(y = x + 1), 
    z = y + 1
  )
#>   x z
#> 1 1 3
#> 2 2 4
```

<sup>Created on 2021-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

That does not require a change in `dplyr`. Although if we desired to have it built-in, we could handle `volatile()` differently so that it would not have to signal the same variables `n_groups()` times.

**Comment by romainfrancois** [comment]
A name convention is another possibility: 

``` r
library(dplyr, warn.conflicts = FALSE)

mutate3 <- function(.data, ...) {
  mutate(.data, ...) %>% 
    select(!starts_with(".temp_"))
}

data.frame(x = 1:2) %>% 
  mutate3(
    .temp_y = x + 1, 
    z = .temp_y + 1
  )
#>   x z
#> 1 1 3
#> 2 2 4
```

<sup>Created on 2021-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ggrothendieck** [comment]
The name convention seems the easiest to use and is the shortest.

**Comment by romainfrancois** [comment]
If we had something like this in `mutate_cols()`: 

```r
          if (!inherits(result, "temporary")) {
            new_columns[names(result)] <- result
          }
          mask$add_many(result, chunks)
```

then we could have e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)

temp <- function(...) {
  vctrs::new_data_frame(rlang::list2(...), class = "temporary")
}
data.frame(x = 1:2) %>% 
  mutate(
    temp(y = x + 1), 
    z = y + 1
  )
#>   x z
#> 1 1 3
#> 2 2 4
```

<sup>Created on 2021-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

things created by the `temp()` wrapper would still have to appropriate size etc ... it's just that the columns wouldn't participate in the output at the end. 

For arbitrary objects that have to persist between different results, I still believe that returning a data frame is the best bet. 

``` r
library(dplyr, warn.conflicts = FALSE)

data.frame(x = 1:2) %>% 
  mutate({
    y <- x + 1
    data.frame(a = y + 1, b = y + 2)
  })
#>   x a b
#> 1 1 3 4
#> 2 2 4 5
```

<sup>Created on 2021-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

`y` can be any arbitrary thing, and be used for `a` and `b`. The data frame is automatically spliced.

**Comment by hadley** [comment]
This feels a bit too specific for dplyr to me. You can already get most of the way their with local:

```R
data %>%
  mutate(local({
    indexList <- lapply(1:nrow(cur_data()), indexes, .$Year_Month)
    data.frame(B = sapply(indexList, function(x) mean(A[x])), n = lengths(indexList))
  }))
```

Or use any of the variants that @romainfrancois suggested.

**Comment by eutwt** [comment]
This is about as hacky and off-label as it gets, but just for fun, the current versions `mutate` allows you to do this:

```r
.. <- function(x){
  class(x) <- c(class(x), 'rlang_zap')
  x
}
. <- function(x){
  class(x) <- setdiff(class(x), 'rlang_zap')
  x
}

data.frame(x = 1:2) %>% 
  mutate(
    y = ..(x + 1), 
    z = .(y) + 1
  )

#   x z
# 1 1 3
# 2 2 4
```

**Comment by romainfrancois** [comment]
Closing this as we can already use e.g. `local()` with some setup code, and then return a data frame that then gets auto spliced, as in Hadley's example.
