### ISSUE TITLE
Original grouping ignored in group_by(...)

### ISSUE THREAD

**Issue by luka-s** [tidyverse/dplyr#5938]
Hi there

I have encountered an unexpected behaviour with `group_by(...)`. Expressions in `...` ignore the original grouping in an already grouped data frame.

Example: group an already grouped data frame further into two equally populated bins calculated separately for each group. 

Below snippet does not lead to the expected result. The calculation of bins ignores the initial grouping, bins are calculated over the entire data frame instead:
```r
library(tidyverse)

iris %>%
    group_by(.data$Species) %>%
    group_by(bin = cut(.data$Petal.Width, 2), .add = TRUE) %>% 
    summarize(n = n(), .groups = "drop")
## # A tibble: 4 x 3
##   Species    bin              n
##   <fct>      <fct>        <int>
## 1 setosa     (0.0976,1.3]    50
## 2 versicolor (0.0976,1.3]    28
## 3 versicolor (1.3,2.5]       22
## 4 virginica  (1.3,2.5]       50
```

Below snippet works as expected. Bins are calculated independently for each group:
```r
iris %>%
    group_by(.data$Species) %>%
    mutate(bin = cut(.data$Petal.Width, 2)) %>% 
    group_by(.data$bin, .add = TRUE) %>% 
    summarize(n = n(), .groups = "drop")
## # A tibble: 6 x 3
##   Species    bin               n
##   <fct>      <fct>         <int>
## 1 setosa     (0.0995,0.35]    41
## 2 setosa     (0.35,0.6]        9
## 3 versicolor (0.999,1.4]      35
## 4 versicolor (1.4,1.8]        15
## 5 virginica  (1.4,1.95]       21
## 6 virginica  (1.95,2.5]       29
```

This example contradicts a statement on the `group_by` help page that grouping by expressions "is just short-hand for
a mutate() followed by a group_by()".

**Comment by romainfrancois** [comment]
This is because of this change in `dplyr` 1.0.3: 

```
* `group_by()` uses the ungrouped data for the implicit mutate step (#5598). 
  You might have to define an `ungroup()` method for custom classes.
  For example, see https://github.com/hadley/cubelyr/pull/3. 
```

Using the explicit `mutate()` is the recommended way to approach this. We'll consider updating the documentation.
