### ISSUE TITLE
Error in UseMethod("select")

### ISSUE THREAD

**Issue by Relindis2018** [tidyverse/dplyr#5940]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
I get the following error when I run the 'dplyr::select' or 'select':

Error in UseMethod("select") : 
  no applicable method for 'select' applied to an object of class "c('GRanges', 'GenomicRanges', 'Ranges', 'GenomicRanges_OR_missing', 'GenomicRanges_OR_GenomicRangesList', 'GenomicRanges_OR_GRangesList', 'List', 'Vector', 'list_OR_List', 'Annotated', 'vector_OR_Vector')"

This commands was working before but suddenly started generating an error since last week
```r
# insert reprex here
```

**Comment by DavisVaughan** [comment]
dplyr has never supplied a `select()` method for a GRanges/Ranges object, but plyranges does. 
https://github.com/sa-lee/plyranges/blob/c82b7eb8ec31478e0f8439207d20897f0c102a6f/R/dplyr-select.R#L62

Is it possible you just forgot to add:

```r
library(plyranges)
```

**Comment by Relindis2018** [comment]
I successfully used this command recently on GRanges object after installing dplyr, based on recommendations from some pages. Also, I do not have the MASS package loaded. I also loaded the plyranges packege and still got an error

**Comment by DavisVaughan** [comment]
Okay, at this point I am not sure we can help you much more without a reproducible example, so...

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by romainfrancois** [comment]
Closing this now. Please open a new issue, with a reprex, if this still happens.
