### ISSUE TITLE
allowing standard evaluation 

### ISSUE THREAD

**Issue by aljabadi** [tidyverse/dplyr#5949]
## Brief description of the problem

If I use a NSE function in a package environment, I need to make unnecessary variable declarations to avoid check warnings/notes. For instance, in a package code, the following would trigger a warning complaining that `cyl` was not found in scope:

```r
group_by(mtcars, cyl)
```

To avoid this, I usually do something like:

```
cyl <- NULL
group_by(mtcars, cyl)
```
An this happens quite frequently in our package. You can imagine how undesirable (and at times dangerous) such a workaround is.

I used to just use `group_by_` but now these functions are being deprecated and they'll create other warnings in the package build. I was wondering what is the best remedy to use such dplyr functions in a package environment.

**Comment by DavisVaughan** [comment]
We typically use `globalVariables()` for this rather than defining a variable directly in the package. i.e. https://github.com/tidymodels/yardstick/blob/036dbee5b1b20560cbd356a8a5d3ff9e8865aba2/R/aaa.R#L9
