### ISSUE TITLE
Speed up repeated `group_by()` with same grouping variables

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#5952]
When working with groups I frequently use `group_by()` on a data frame that already has the very same groups.

For example
```r
df <- tibble(id = sample(1:100e3, 1e6, replace = TRUE))
df2 <- df %>% 
  group_by(id) %>% 
  # calculate something

df2 %>% 
  group_by(id) %>% 
  # calculate something else
```

There are two reasons to do this:

1. In case I change some code above and delete the `group_by()` above or add an `ungroup()`. So, this is a more robust approach against code changes.
2. It is much more explicit.

Unfortunately, `group_by()` just ignores the fact that it already knows the groups and instead calculates them again which slows down code quite a bit.

--> `group_by()` should not calculate the groups again if it isn't necessary

Similarly, I also quite frequently I use a pattern of repeated `group_by()` + `ungroup()` (basically this simulates the experimental `with_groups()`). In the next line I often group by the same groups again. For example

```r
df <- tibble(id = sample(1:100e3, 1e6, replace = TRUE))
df2 <- df %>% 
  group_by(id) %>% 
  # calculate something
  ungroup()

df2 %>% 
  group_by(id) %>% 
  # calculate something else
  ungroup()
```

Using `ungroup()` at the end is much more robust as I frequently forget that the data frame is still grouped and then wonder about the results...

--> It would be great if this pattern could also be made faster.

## Benchmarks

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(id = sample(1:100e3, 1e6, replace = TRUE))

bench::mark(
  group = df %>% 
    group_by(id),
  group_group = df %>% 
    group_by(id) %>% 
    group_by(id),
  group_ungroup_group = df %>% 
    group_by(id) %>% 
    ungroup() %>% 
    group_by(id),
  iterations = 3
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 3 x 6
#>   expression               min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>          <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 group                   73ms   96.6ms      8.32      27MB    13.9 
#> 2 group_group            157ms  228.5ms      4.81    52.7MB    11.2 
#> 3 group_ungroup_group    156ms  216.1ms      4.30    52.6MB     7.16
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
I'm not sure it's worth adding this special case to support this pattern, but it does feel harmless. 

This could be done from the outside with a `group_by()` variant: 

``` r
library(dplyr, warn.conflicts = FALSE)

group_by2 <- function(.data, ..., .add = FALSE, .drop = group_by_drop_default(.data)) {
  groups <- group_by_prepare(.data, ..., .add = .add, caller_env = caller_env())
  if (identical(group_vars(groups$data), groups$group_names) && identical(.drop, group_by_drop_default(.data))) {
    groups$data
  } else {
    grouped_df(groups$data, groups$group_names, .drop)  
  }
}

df <- tibble(id = sample(1:100e3, 1e6, replace = TRUE)) %>% group_by(id)

bench::mark(
  group_by(df, id),
  group_by2(df, id)
)
#> # A tibble: 2 x 6
#>   expression             min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>        <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 group_by(df, id)    94.8ms   94.8ms      10.6    26.4MB    73.9 
#> 2 group_by2(df, id)  206.4µs  216.1µs    4168.         0B     8.20
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hadley** [comment]
The cost-benefit tradeoff here doesn't feel quite right to me — we're making performance better only in a very narrow case, and I think there's some risk of introducing verty subtle bugs if we forget to update this code if we ever change how grouping is represented internally.  If you want this behaviour in your code, you can just use @romainfrancois's `group_by2()` function.
