### ISSUE TITLE
Support additional S3 classes for input in `select()`

### ISSUE THREAD

**Issue by msberends** [tidyverse/dplyr#5955]
We use character vectors in a package for S3 extension, which can be column headers. Unfortunately, the tidyselect helpers are quite picky in that the input can apparently only be identical to `"character"` and cannot contain any other class alongside `"character"`:

```r
# example output of a package, that provides S3 extensions on "my_selector"
vars <- structure(c("hair_color", "skin_color"),
                  class = c("my_selector", "character"))

library(dplyr)

# although `vars` is a character vector, this breaks:
starwars %>% select(all_of(vars))
#> Error: Must subset columns with a valid subscript vector.
#> x Subscript has the wrong type `my_selector`.
#> ℹ It must be numeric or character.

# all fine:
starwars %>% select(all_of(unclass(vars)))
#> # A tibble: 87 x 2
#>    hair_color    skin_color 
#>    <chr>         <chr>      
#>  1 blond         fair       
#>  2 NA            gold       
#>  3 NA            white, blue
#>  4 none          white      
#>  5 brown         light      
#>  6 brown, grey   light      
#>  7 brown         light      
#>  8 NA            white, red 
#>  9 black         light      
#> 10 auburn, white fair       
#> # … with 77 more rows
```

I wonder why the type comparison is so strict - `vars` is after all a character type. Moreover, the error is erroneous (*It must be numeric or character*). Would it be possible to loosen up a bit here?

Thanks in advance!

**Comment by DavisVaughan** [comment]
The tidyselect helpers use vctrs under the hood, which means that custom classes have to conform to vctrs conventions to define how to convert between types. In other words, vctrs doesn't "know" that your class is coercible to a character, you have to "tell" it that by defining a few functions (`vec_ptype2()` and `vec_cast()` methods).

You can read more about this here https://vctrs.r-lib.org/articles/s3-vector.html

``` r
vars <- structure(c("hair_color", "skin_color"), class = c("my_selector", "character"))

# Fails at the beginning
vctrs::vec_as_subscript(vars)
#> Error: Must subset elements with a valid subscript vector.
#> x Subscript has the wrong type `my_selector`.
#> ℹ It must be logical, numeric, or character.

# Assume that if a <character> and <my_selector> are combined, that you want the
# result to be a <character>
vec_ptype2.character.my_selector <- function(x, y, ...) {
  x
}
vec_ptype2.my_selector.character <- function(x, y, ...) {
  y
}

# Define how to convert from <my_selector> to <character>
vec_cast.character.my_selector <- function(x, to, ...) {
  unclass(x)
}

# Now they are coercible
vctrs:::vec_is_coercible(vars, character())
#> [1] TRUE

# And casting works
vctrs::vec_cast(vars, character())
#> [1] "hair_color" "skin_color"

# So this works
vctrs::vec_as_subscript(vars)
#> [1] "hair_color" "skin_color"

library(dplyr)
starwars %>% select(all_of(vars))
#> # A tibble: 87 x 2
#>    hair_color    skin_color 
#>    <chr>         <chr>      
#>  1 blond         fair       
#>  2 <NA>          gold       
#>  3 <NA>          white, blue
#>  4 none          white      
#>  5 brown         light      
#>  6 brown, grey   light      
#>  7 brown         light      
#>  8 <NA>          white, red 
#>  9 black         light      
#> 10 auburn, white fair       
#> # … with 77 more rows
```

@lionel- were we thinking about adding some rule that if a subclass explicitly inherited from a base type (here, `"character"`), then it would automatically be coercible to that base type? It seems like it may make sense in this case.

**Comment by msberends** [comment]
Very informative, many thanks!

Yes, auto-coercing to an available underlying class would surely make sense. Especially for package maintainers, because we now have to:

* Add S3 extensions of `vctrs`
* Add `vctrs` to the `Suggests` field of the `DESCRIPTION` file
* Add units tests to check whether `vctrs` still works as expected with `dplyr` verbs (and what else?)
* Alter the code if any of this in `dplyr` or `vctrs` change in behaviour, exported functions or anything else

All in all, it requires pkg devs to add a lot more overhead while supporting `dplyr` is not even a goal of our package. Would be great if really obvious coercion would just work.

**Comment by jmbarbone** [comment]
Different error when reversing class

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(a = 1)

# foo and character
var <- structure("a", class = c("foo", "character"))
select(df, all_of(var))
#> Error: Must subset columns with a valid subscript vector.
#> x Subscript has the wrong type `foo`.
#> i It must be numeric or character.

# character and foo
var <- structure("a", class = c("character", "foo"))
select(df, all_of(var))
#> Error: `vec_ptype2.character.character()` is implemented at C level.
#> This R function is purely indicative and should never be called.

# just character
var <- structure("a", class = "character")
select(df, all_of(var))
#> Error: `vec_ptype2.character.character()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

<sup>Created on 2021-07-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


Could this be related to https://github.com/r-lib/vctrs/issues/1300?

**Comment by lionel-** [comment]
> were we thinking about adding some rule that if a subclass explicitly inherited from a base type (here, "character"), then it would automatically be coercible to that base type? It seems like it may make sense in this case.

I think this is https://github.com/r-lib/vctrs/issues/1135

**Comment by hadley** [comment]
Closing this since it's tracked in vctrs.
