### ISSUE TITLE
Unexpected warning with `group_indices()`

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/dplyr#5969]
Just trying out the example from https://dplyr.tidyverse.org/reference/group_indices.html gives a warning:

```r
> group_indices(mtcars, cyl)
 [1] 2 2 1 2 3 2 3 1 1 2 2 3 3 3 3 3 3 1 1 1 1 3 3 3 3 1 1 1 3 2 3 1
Warning message:
The `...` argument of `group_keys()` is deprecated as of dplyr 1.0.0.
Please `group_by()` first
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

dplyr version is 1.0.6.

**Comment by romainfrancois** [comment]
I'm not sure why the https://dplyr.tidyverse.org/reference/group_indices.html file is still generated when `group_indices()` is now documented as part of https://dplyr.tidyverse.org/reference/group_data.html 

Is this a `pkgdown` issue ? @hadley 

Also the version is set to 0.8.3: 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/2625526/128350919-7587d6b3-7a2f-4136-ba1d-7a68c2534a37.png">

**Comment by hadley** [comment]
It's https://github.com/r-lib/pkgdown/issues/1394 and is fixed in dev pkgdown.
