### ISSUE TITLE
`if_any()` doesn't work well on dataframe columns

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#5972]
`if_any()` doesn't work well with data frame columns

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(
  y = tibble(
    b = c(1, 2),
    a = c(NA, 1),
  )
) %>% 
  filter(if_any(.fns = is.na))
#> # A tibble: 0 × 1
#> # … with 1 variable: y <tibble[,2]>

tibble(
  y = tibble(
    b = c(1, 2),
    a = c(1, NA),
  )
) %>% 
  filter(if_any(.fns = is.na))
#> # A tibble: 0 × 1
#> # … with 1 variable: y <tibble[,2]>
```

<sup>Created on 2021-08-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by emmansh** [comment]
Does the following help?

``` r
library(dplyr, warn.conflicts = FALSE)
library(tidyr)

tibble(
  y = tibble(
    b = c(1, 2),
    a = c(NA, 1),
  )
) %>%
  unpack(cols = everything()) %>% ### <--- this is my addition
  filter(if_any(.fns = is.na))
#> # A tibble: 1 x 2
#>       b     a
#>   <dbl> <dbl>
#> 1     1    NA
```

<sup>Created on 2021-08-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
The underlying issue is that for some reason `is.na(<data.frame>)` returns a logical matrix: 

``` r
library(dplyr, warn.conflicts = FALSE)

column <- tibble(
  b = c(1, 2),
  a = c(NA, 1),
)
is.na(column)
#>          b     a
#> [1,] FALSE  TRUE
#> [2,] FALSE FALSE
str(is.na(column))
#>  logi [1:2, 1:2] FALSE FALSE TRUE FALSE
#>  - attr(*, "dimnames")=List of 2
#>   ..$ : NULL
#>   ..$ : chr [1:2] "b" "a"
```

<sup>Created on 2021-08-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This isn't really about how `if_any()` handles data frame columns, but more about how `filter()` handles logical matrices. below the code `filter(df, if_any(y, is.na))` expands to `filter(df, is.na(y))` and then `filter()` is confused: 

``` r
library(dplyr, warn.conflicts = FALSE)

column <- tibble(
  b = c(1, 2),
  a = c(NA, 1),
)
df <- tibble(y = column)

filter(df, if_any(y, is.na))
#> # A tibble: 0 x 1
#> # … with 1 variable: y <tibble[,2]>
filter(df, is.na(y))
#> # A tibble: 0 x 1
#> # … with 1 variable: y <tibble[,2]>
```

<sup>Created on 2021-08-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
A workaround is perhaps to mutate `df$y` and then filter based on that: 

``` r
library(dplyr, warn.conflicts = FALSE)

column <- tibble(
  b = c(1, 2),
  a = c(NA, 1),
)
df <- tibble(y = column)

mutate(column, if_any(.fns = is.na))
#> # A tibble: 2 x 3
#>       b     a `if_any(.fns = is.na)`
#>   <dbl> <dbl> <lgl>                 
#> 1     1    NA TRUE                  
#> 2     2     1 FALSE
pull(mutate(column, if_any(.fns = is.na)))
#> [1]  TRUE FALSE

filter(df, 
       pull(mutate(y, if_any(.fns = is.na)))
      )
#> # A tibble: 1 x 1
#>     y$b    $a
#>   <dbl> <dbl>
#> 1     1    NA
```

<sup>Created on 2021-08-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

It's perhaps a bit much. Another way would be to define a `is_na()` function that does the reduction: 

``` r
library(dplyr, warn.conflicts = FALSE)

column <- tibble(
  b = c(1, 2),
  a = c(NA, 1),
)
df <- tibble(y = column)

is_na <- function(x) UseMethod("is_na")
is_na.default <- function(x) is.na(x)
is_na.data.frame <- function(x) {
  apply(is.na(x), 1, any)
}

filter(df, is_na(y))
#> # A tibble: 1 x 1
#>     y$b    $a
#>   <dbl> <dbl>
#> 1     1    NA
```

<sup>Created on 2021-08-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Note that `vctrs` has `vctrs::vec_equal_na()` but it only considers the row to be missing when all values are missing. https://vctrs.r-lib.org/reference/vec_equal.html
