### ISSUE TITLE
`left_join()`: make it easier to add selected columns from `y`

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#5980]
To add specific columns from a tibble `y` to a tibble `x` via a join I need to `select()` all columns needed in `by` and then the columns I want to add to `x`. When one has to join by multiple columns to join by this feels quite cumbersome.

``` r
library(dplyr)

x <- tibble(id1 = "a", id2 = "b", id3 = "c", x = 1)
y <- tibble(id1 = "a", id2 = "b", id3 = "c", a = 1, b = 2, c = 3, d = 4)

left_join(
  x,
  y %>% 
    select(id1, id2, id3, a),
  by = c("id1", "id2", "id3")
)
#> # A tibble: 1 × 5
#>   id1   id2   id3       x     a
#>   <chr> <chr> <chr> <dbl> <dbl>
#> 1 a     b     c         1     1
```

One way around this is to use a variable

```r
join_cols <- c("id1", "id2", "id3")
left_join(
  x,
  y %>% 
    select(!!!join_cols, a),
  by = join_cols
)
```

but when joining multiple tables this also isn't very nice

```r
join_cols <- c("id1", "id2", "id3")
join_cols2 <- c("id1", "id2")
left_join(
  x,
  y %>% 
    select(!!!join_cols, a),
  by = join_cols
) %>% 
  left_join(
    z %>% 
      select(!!!join_cols2, b),
    by = join_cols2
  )
```

It would be great if there were an easier way to do this.

**Comment by williamlai2** [comment]
You could do it without the `!!!`. Not sure what `z` is meant to be, but I imagine it something like this:

```
library(dplyr)

x <- tibble(id1 = "a", id2 = "b", id3 = "c", x = 1)
y <- tibble(id1 = "a", id2 = "b", id3 = "c", a = 1, b = 2, c = 3, d = 4)
z <- tibble(id1 = "a", id2 = "b", id3 = "c", a = 1, b = 2, g = 3, h = 4)

join_cols <- c("id1", "id2", "id3")
join_cols2 <- c("id1", "id2")

left_join(
  x,
  y %>% 
    select(join_cols, a),
  by = all_of(join_cols)
) %>% 
  left_join(
    z %>% 
      select(join_cols2, b),
    by = all_of(join_cols2)
  )

# A tibble: 1 x 6
  id1   id2   id3       x     a     b
  <chr> <chr> <chr> <dbl> <dbl> <dbl>
1 a     b     c         1     1     2
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, it feels a bit too specialised to me. It sounds like we'd either need a new function (which would only be useful in fairly rare cases) or an argument to the join functions (which already have a lot of arguments). It feels maybe more appropriate in a helper package?
