### ISSUE TITLE
group_nest(x) sorts by group, whereas with_groups(x, nest) does not.

### ISSUE THREAD

**Issue by orgadish** [tidyverse/dplyr#5983]
Using dplyr 1.0.7 on R 4.0.3

`group_nest(x)` sorts by group, whereas `with_groups(x, nest)` does not.

This can be sneakily problematic if you `arrange`d prior to nesting. I came across it when using `slice_sample` to get a random set of rows (using a fixed `seed`) and got different results between the two methods.

``` r
library(tidyverse)

mtcars %>% 
  as_tibble %>% 
  rowid_to_column %>% 
  arrange(desc(rowid)) %>% 
  group_nest(rowid)
#> # A tibble: 32 x 2
#>    rowid                data
#>    <int> <list<tibble[,11]>>
#>  1     1            [1 × 11]
#>  2     2            [1 × 11]
#>  3     3            [1 × 11]
#>  4     4            [1 × 11]
#>  5     5            [1 × 11]
#>  6     6            [1 × 11]
#>  7     7            [1 × 11]
#>  8     8            [1 × 11]
#>  9     9            [1 × 11]
#> 10    10            [1 × 11]
#> # … with 22 more rows

mtcars %>% 
  as_tibble %>% 
  rowid_to_column %>% 
  arrange(desc(rowid)) %>% 
  with_groups(rowid, nest)  # same result as using group_by(rowid) %>% nest
#> # A tibble: 32 x 2
#>    rowid data             
#>    <int> <list>           
#>  1    32 <tibble [1 × 11]>
#>  2    31 <tibble [1 × 11]>
#>  3    30 <tibble [1 × 11]>
#>  4    29 <tibble [1 × 11]>
#>  5    28 <tibble [1 × 11]>
#>  6    27 <tibble [1 × 11]>
#>  7    26 <tibble [1 × 11]>
#>  8    25 <tibble [1 × 11]>
#>  9    24 <tibble [1 × 11]>
#> 10    23 <tibble [1 × 11]>
#> # … with 22 more rows
```

<sup>Created on 2021-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
`group_nest(df, rowid)` is essentially a shortcut to a `mutate()` on the `group_keys()`: 

``` r
library(tidyverse)

df <- mtcars %>% 
  as_tibble %>% 
  rowid_to_column %>% 
  arrange(desc(rowid))

df %>% 
  group_nest(rowid)
#> # A tibble: 32 x 2
#>    rowid                data
#>    <int> <list<tibble[,11]>>
#>  1     1            [1 × 11]
#>  2     2            [1 × 11]
#>  3     3            [1 × 11]
#>  4     4            [1 × 11]
#>  5     5            [1 × 11]
#>  6     6            [1 × 11]
#>  7     7            [1 × 11]
#>  8     8            [1 × 11]
#>  9     9            [1 × 11]
#> 10    10            [1 × 11]
#> # … with 22 more rows

g <- group_by(df, rowid)
mutate(
  group_keys(g), 
  data = group_split(g)
)
#> # A tibble: 32 x 2
#>    rowid                data
#>    <int> <list<tibble[,12]>>
#>  1     1            [1 × 12]
#>  2     2            [1 × 12]
#>  3     3            [1 × 12]
#>  4     4            [1 × 12]
#>  5     5            [1 × 12]
#>  6     6            [1 × 12]
#>  7     7            [1 × 12]
#>  8     8            [1 × 12]
#>  9     9            [1 × 12]
#> 10    10            [1 × 12]
#> # … with 22 more rows
```

<sup>Created on 2021-08-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

and `group_keys()` uses the group data that is arranged. 

I believe `group_nest()` does the right thing here, or at least is consistent with `dplyr`. Maybe this is a `tidyr::nest
()` issue ?

**Comment by orgadish** [comment]
As a user of `group_nest(x)` only, it feels weird that it would sort, when `with_groups(x, nest)` does not. However, considering that `group_keys()` and `group_split(x)` has arranged data, it makes sense `group_nest` would too.

Perhaps all that's needed is to add a comment in the documentation about it returning the groups sorted.

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately because unlikely to affect many people, we don't have the development resources to fix at this time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.
