### ISSUE TITLE
Using starts_with() on a grouped dataframe adds the grouping column name to the output 

### ISSUE THREAD

**Issue by dwaynepaschall** [tidyverse/dplyr#5987]
When attempting to get a list of column names from a spark data frame using 'starts_with()' inside a select function, this adds the name of the group_by column to the list, even when it is not part of the selecting expression. I would expect only the column names matching the 'starts_with()' expression to be returned. (Apologies for the second post. I was able to show that it happens for both spark df and local df).

Package versions:
sparklyr: 1.5.2
dplyr: 1.0.7

Minimal reproducible example:

```r
library(sparklyr)
library(dplyr)


sc <- spark_connect(master = "yarn-cluster", config = config) 

employeeID <- c('123','456','789', '123')
Test_Score1 <- c(90, 23400, 26800, 223)
testdate <- as.Date(c('2010-11-1','2008-3-25','2007-3-14', '2011-12-2'))
Test_Score2 <-  c(190, 3400, 6800, 512)

employData <- data.frame(employeeID, testdate, Test_Score1, Test_Score2)
employData <- employData %>% group_by(employeeID)

employData_spk <- sdf_copy_to(sc, employData)
employData_spk <- employData %>% group_by(employeeID)

trend_cols_spk <- employData_spk %>% select(starts_with("Test_")) %>% colnames()
# Adding missing grouping variables: `employeeID`

trend_cols <- employData %>% select(starts_with("Test_")) %>% colnames()
# Adding missing grouping variables: `employeeID`


#> trend_cols
#[1] "employeeID"  "Test_Score1" "Test_Score2"

#> trend_cols_spk
#[1] "employeeID"  "Test_Score1" "Test_Score2"
```

**Comment by dwaynepaschall** [comment]
This issue is somewhat related to https://github.com/tidyverse/dplyr/issues/5473 in that ungrouping the data frame produces a correct/expected output. However, it really seems like "give me a column name" and "how are the rows organized" should be irrelevant to each other.

**Comment by eutwt** [comment]
I'm not part of the dplyr team but I can offer some context that may be helpful:

This is standard `select()` behavior, even without `starts_with()`. 

``` r
library(dplyr, warn.conflicts = FALSE)

data.frame(a = 1, b = 2) %>% 
  group_by(a) %>% 
  select(b)
#> Adding missing grouping variables: `a`
#> # A tibble: 1 × 2
#> # Groups:   a [1]
#>       a     b
#>   <dbl> <dbl>
#> 1     1     2
```

<sup>Created on 2021-08-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


It appears to be intentional, since the second line of the `select.data.frame` definition is

```r 
loc <- ensure_group_vars(loc, .data, notify = TRUE)
```

**Comment by DavisVaughan** [comment]
@eutwt is correct, this is intentional. It is also mentioned in `?select`:

> Groups are maintained; you can't select off grouping variables.

You will have to ungroup to completely ignore those grouping variables

**Comment by dwaynepaschall** [comment]
So in order to use starts_with() I have to use it inside a select() function. But if I use select() to work with columns, I have to first think about how the rows are organized. Seems a bit counterintuitive. But I do find that ungrouping does produce the expected output.

**Comment by eutwt** [comment]
`group_by()` and the order of rows are actually separate issues. `group_by()` does not reorder rows, and if you do reorder rows you can use `select` in the way you want.

``` r
library(dplyr, warn.conflicts = FALSE)

data.frame(a = c(2, 1, 3), b = 4) %>%
  group_by(a)
#> # A tibble: 3 × 2
#> # Groups:   a [3]
#>       a     b
#>   <dbl> <dbl>
#> 1     2     4
#> 2     1     4
#> 3     3     4

data.frame(a = c(2, 1, 3), b = 4) %>%
  arrange(a) %>%
  select(b)
#>   b
#> 1 4
#> 2 4
#> 3 4
```

<sup>Created on 2021-08-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dwaynepaschall** [comment]
The explicit order of rows isn't important in this context. More so, having to consider and account for whether the dataframe you're working with has a grouping col or not. Since a variable with column names does't require Spark per se to hold the size of the var, defaulting to a base R solution seems quicker/easier/safer.

trend_cols_idx <- grep("Test_", colnames(employData))
trend_cols3a <- colnames(employData)[trend_cols_idx]

**Comment by eutwt** [comment]
I think the expectation is that in a chain of dplyr verbs, computations are done by group until the data frame is ungrouped. If you drop the group var this isn't possible, at least not without adding some notion of hidden columns. I'm sure there is by now a whole lot of code out there which depends on this behavior, so I'll speculate the base case scenario is a `.drop` argument being added which would still require you to consider the grouping.

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(a = c(2, 1, 2, 3), b = a*2) %>%
  group_by(a) %>% 
  select(b) %>% 
  mutate(d = mean(b)) %>% 
  pull(d)
#> Adding missing grouping variables: `a`
#> [1] 4 2 4 6


tibble(a = c(2, 1, 2, 3), b = a*2) %>%
  group_by(a) %>% 
  .[, 'b'] %>% 
  mutate(d = mean(b)) %>% 
  pull(d)
#> [1] 4 4 4 4
```

<sup>Created on 2021-08-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If it helps any, it's not too difficult to make your own function, at least for R data frames. No clue how/if this works with sparklyr.

``` r
library(dplyr, warn.conflicts = FALSE)

select2 <- function(.data, ...){
  loc <- tidyselect::eval_select(expr(c(...)), .data)
  if (!all(group_vars(.data) %in% names(loc))) {
    select(ungroup(.data), ...)
  }
  else
    select(.data, ...)
}

tibble(a = c(2, 1, 2, 3), baseball = a*2) %>%
  group_by(a) %>%
  select2(starts_with('b'))
#> # A tibble: 4 × 1
#>   baseball
#>      <dbl>
#> 1        4
#> 2        2
#> 3        4
#> 4        6
```

<sup>Created on 2021-08-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dwaynepaschall** [comment]
"I think the expectation is that in a chain of dplyr verbs, computations are done by group until the data frame is ungrouped." -- agree completely. However, starts_with() isn't really a verb in that it is a helper function that assist in identifying a list of colnames, without performing an action on those columns.
