### ISSUE TITLE
support ad-hoc group var creation in `with_groups`

### ISSUE THREAD

**Issue by eutwt** [tidyverse/dplyr#5988]
Already `with_groups` simplifies many  operations done by group

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  group_by(cyl) %>% 
  slice_head() %>% 
  ungroup()
#> # A tibble: 3 × 11
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  22.8     4   108    93  3.85  2.32  18.6     1     1     4     1
#> 2  21       6   160   110  3.9   2.62  16.5     0     1     4     4
#> 3  18.7     8   360   175  3.15  3.44  17.0     0     0     3     2

mtcars %>% 
  with_groups(cyl, slice_head)
#>    mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> 1 22.8   4  108  93 3.85 2.32 18.61  1  1    4    1
#> 2 21.0   6  160 110 3.90 2.62 16.46  0  1    4    4
#> 3 18.7   8  360 175 3.15 3.44 17.02  0  0    3    2
```

<sup>Created on 2021-08-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It would be nice if you could  also use it to replace `group_by` in situations like the one below.

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  group_by(g = mpg %/% 10) %>% 
  slice_head() %>% 
  ungroup()
#> # A tibble: 3 × 12
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb     g
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  18.7     8 360     175  3.15  3.44  17.0     0     0     3     2     1
#> 2  21       6 160     110  3.9   2.62  16.5     0     1     4     4     2
#> 3  32.4     4  78.7    66  4.08  2.2   19.5     1     1     4     1     3

mtcars %>% 
  with_groups(c(g = mpg %/% 10), slice_head)
#> Error: object 'mpg' not found
```

<sup>Created on 2021-08-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This would make `.groups` in `with_groups` similar to `by` in data.table

``` r
library(data.table)
library(magrittr)

as.data.table(mtcars) %>%
  .[, head(.SD, 1), .(g = mpg %/% 10)]
#>    g cyl  disp  hp drat   wt  qsec vs am gear carb
#> 1: 2   6 160.0 110 3.90 2.62 16.46  0  1    4    4
#> 2: 1   8 360.0 175 3.15 3.44 17.02  0  0    3    2
#> 3: 3   4  78.7  66 4.08 2.20 19.47  1  1    4    1
```

<sup>Created on 2021-08-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Example implementation below, although I get the feeling supporting this must not be so simple or it would've been supported originally.

``` r
library(dplyr, warn.conflicts = FALSE)
library(rlang, warn.conflicts = FALSE)

with_groups2 <- function(.data, .groups, .f, ...) {
  .groups <- enquo(.groups)
  if (quo_is_call(.groups, "c")) {
    out <- group_by(.data, !!!call_args(.groups))
  } else {
    out <- group_by(.data, !!.groups)
  }

  .f <- as_function(.f)
  out <- .f(out, ...)
  dplyr:::dplyr_reconstruct(out, .data)
}

# `c` call
mtcars %>%
  with_groups2(c(g = mpg %/% 10, cyl), slice_head)
#>    mpg cyl  disp  hp drat   wt  qsec vs am gear carb g
#> 1 18.1   6 225.0 105 2.76 3.46 20.22  1  0    3    1 1
#> 2 18.7   8 360.0 175 3.15 3.44 17.02  0  0    3    2 1
#> 3 22.8   4 108.0  93 3.85 2.32 18.61  1  1    4    1 2
#> 4 21.0   6 160.0 110 3.90 2.62 16.46  0  1    4    4 2
#> 5 32.4   4  78.7  66 4.08 2.20 19.47  1  1    4    1 3

# varname symbols
mtcars %>%
  with_groups2(cyl, slice_head)
#>    mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> 1 22.8   4  108  93 3.85 2.32 18.61  1  1    4    1
#> 2 21.0   6  160 110 3.90 2.62 16.46  0  1    4    4
#> 3 18.7   8  360 175 3.15 3.44 17.02  0  0    3    2

# expressions with varnames
mtcars %>%
  with_groups2(mpg %/% 10, slice_head)
#>    mpg cyl  disp  hp drat   wt  qsec vs am gear carb mpg%/%10
#> 1 18.7   8 360.0 175 3.15 3.44 17.02  0  0    3    2        1
#> 2 21.0   6 160.0 110 3.90 2.62 16.46  0  1    4    4        2
#> 3 32.4   4  78.7  66 4.08 2.20 19.47  1  1    4    1        3

# `list` call. Needs a warning?
mtcars %>%
  with_groups2(list(mpg %/% 10), slice_head)
#>   mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> 1  21   6  160 110  3.9 2.62 16.46  0  1    4    4
#>                                                                                   list(mpg%/%10)
#> 1 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 2, 1, 1, 1, 1, 2, 2, 3, 1, 1, 1, 2
```

<sup>Created on 2021-08-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by romainfrancois** [comment]
I'm not sure this adds much, when you can perhaps more clearly first do a `mutate()`.

**Comment by eutwt** [comment]
That's understandable. If it's code I'm going to come back to later I might want to write it more clearly with mutate. The time this comes up is when I'm using dplyr to explore data interactively. I often do a slice_sample or summarise based on ad-hoc groups such as `time_last_event < today() - months(1)`, and about a dozen other groupings that pop into my mind, none of which I intend to explicitly add to my data unless I'm done exploring and have found some groups I think may be informative.

At this stage I think of what I'm doing in terms like "what's the average age of gym visitors across (quartiles of) total exercise time?". Conceptually I'm just looking at a feature under some grouping, and adding a new variable or changing my data isn't a distinct step mentally.  If I use mutate I need to think of a variable name for my new group before I can see the results. Of course I could just put `g = `, but writing out `mutate(g = ...) %>%` is a slight mental overhead for boilerplate.  The idea was to slightly decrease the friction of going from thought -> code.

I guess dplyr is often intentionally at the other end of the concision spectrum from data.table though, which can obviously have benefits. Having to think of a variable name can be a good thing :).
