### ISSUE TITLE
Compilation error with GCC 10.3.1

### ISSUE THREAD

**Issue by smaudet** [tidyverse/dplyr#5994]
---

When installing this package or the packages from tidyverse, it appears there are a number of segmentation faults with GCC 10.3.1.

This bug may be upstream in GCC, there seems to be a related issue here:

https://github.com/tidyverse/dplyr/issues/5589

There is mention of a gcc patch, however the version which fedora 32 contains (10.3.1-1) does not appear to address this bug. There is no mention of which gcc version which should be used to compile dplyr.

```r
# install.package("dplyr")
```

The seg fault appears somewhat intermittent... (it now compiles fine) just posting this in case others come across. May be a local system mis-configuration, possibly.

**Comment by romainfrancois** [comment]
I'm not sure what action we can take based on this report. Can you share more details ?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Comment by smaudet** [comment]
@romainfrancois well for starters you could mention supported gcc versions. There are tens if not hundreds of versions.

@hadley I don't think a reprex is applicable here - your closing of bugs seems rather invalid, if not short sighted.

I don't think this should be closed until someone can confirm this compiler works for them, or confirm some downstream issue, or issue a supported compiler version.
