### ISSUE TITLE
colnames(.data) does not err (but fail) while rownames(.data) does

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#5996]
Using `colnames()` in a dplyr call does not work if .data is used to refer to the data.
Perhaps this makes sense since a pronoun is not a noun, but the issue is that it does not show any error message:

``` r
dplyr::mutate(iris, col_list = list(colnames(iris)))[1, 6]
#> [[1]]
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"
dplyr::mutate(iris, col_list = list(colnames(.data)))[1, 6]
#> [[1]]
#> NULL
```

This can create issues that may go overlooked, e.g.:

``` r
dplyr::mutate(iris, col_found = ifelse("Sepal.Length" %in% colnames(iris), TRUE, FALSE))[1:5, ]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species col_found
#> 1          5.1         3.5          1.4         0.2  setosa      TRUE
#> 2          4.9         3.0          1.4         0.2  setosa      TRUE
#> 3          4.7         3.2          1.3         0.2  setosa      TRUE
#> 4          4.6         3.1          1.5         0.2  setosa      TRUE
#> 5          5.0         3.6          1.4         0.2  setosa      TRUE
dplyr::mutate(iris, col_found = ifelse("Sepal.Length" %in% colnames(.data), TRUE, FALSE))[1:5, ]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species col_found
#> 1          5.1         3.5          1.4         0.2  setosa     FALSE
#> 2          4.9         3.0          1.4         0.2  setosa     FALSE
#> 3          4.7         3.2          1.3         0.2  setosa     FALSE
#> 4          4.6         3.1          1.5         0.2  setosa     FALSE
#> 5          5.0         3.6          1.4         0.2  setosa     FALSE
```

Strangely, `rownames()` behave better since it does complain:

``` r
dplyr::mutate(iris, row_list = list(rownames(.data)))[1, 6]
#> Error: Problem with `mutate()` column `row_list`.
#> ℹ `row_list = list(rownames(.data))`.
#> x Can't take the `length()` of the `.data` pronoun
```

I did this on current CRAN version at the time of the posting:
```r
packageVersion("dplyr")
#> [1] '1.0.7'
```

<sup>Created on 2021-08-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by romainfrancois** [comment]
Perhaps `rlang` could have a `dimnames.rlang_data_pronoun` or `dplyr` could extend the `rlang_data_pronoun` class and implement a `dimnames()` method ? cc @lionel-

**Comment by lionel-** [comment]
Good idea, I've opened https://github.com/r-lib/rlang/issues/1265 to track this.

**Comment by lionel-** [comment]
I've made the dimnames method consistent with `length()` and `names()` which, unlike `[`, silently behaves as if `.data` was an empty data structure. I think failing would probably be better. Changing this now would probably not be worth the trouble. Also failing from length, names, etc might cause errors in unexpected places.
