### ISSUE TITLE
Ordering problem in arrange

### ISSUE THREAD

**Issue by dax44** [tidyverse/dplyr#5997]
I want to arrange results of summarise function in numeric order, but I can't.
Example

```r
library(tidyverse)

gr <- rep(c("q1", "q2", "q10", "q11"), 5)
y <- rnorm(20)

dt <- bind_cols(y = y, gr = gr) 
```

Now i arrange with `.by_group = F` (as default option)

```r
dt %>% 
  group_by(gr) %>% 
  summarise(m = mean(y)) %>% 
  arrange(str_sort(gr, numeric = T))
```

and also with `.by_group = T`

```r
dt %>% 
  group_by(gr) %>% 
  summarise(m = mean(y)) %>% 
  arrange(str_sort(gr, numeric = T), .by_group = T)
```

but in both methods I've got this

```
# A tibble: 4 x 2
  gr         m
  <chr>  <dbl>
1 q1    -0.273
2 q11   -0.206
3 q2    -0.457
4 q10    0.362
```

so arranging is wrong for me. Moreover the following code give me right order

```r
dt %>% 
  group_by(gr) %>% 
  summarise(m = mean(y)) %>% 
  pull(gr) %>% 
  str_sort(., numeric = T)
```

`[1] "q1"  "q2"  "q10" "q11"`

Please help me

**Comment by DavisVaughan** [comment]
You can't use any of stringr's extra features like `numeric = TRUE` directly in `arrange()`.

I'd advise stripping the non-numeric characters off the column you want to arrange by, and then converting it to integer and arranging by that.

``` r
library(tidyverse)

gr <- rep(c("q1", "q2", "q10", "q11"), 5)
y <- rnorm(20)

dt <- tibble(y = y, gr = gr) 

dt <- mutate(dt, gr = as.integer(sub("q", "", gr)))

head(dt)
#> # A tibble: 6 × 2
#>        y    gr
#>    <dbl> <int>
#> 1  0.232     1
#> 2  1.77      2
#> 3  0.906    10
#> 4  1.14     11
#> 5 -0.477     1
#> 6 -0.147     2

dt %>% 
  group_by(gr) %>% 
  summarise(m = mean(y)) %>% 
  arrange(gr)
#> # A tibble: 4 × 2
#>      gr      m
#>   <int>  <dbl>
#> 1     1  0.386
#> 2     2 -0.210
#> 3    10  0.649
#> 4    11 -0.248
```

<sup>Created on 2021-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by dax44** [comment]
Thank you for your advise... but I think that lack of such application is small drawback of arrange.
It's not the problem to order the data.frame with assignment even without of changing anything in group variable, e.a.

```r
library(tidyverse)

gr <- rep(c("q1", "q2", "q10", "q11"), 5)
y <- rnorm(20)

dt <- bind_cols(y = y, gr = gr)

results <- dt %>% 
  group_by(gr) %>% 
  summarise(m = mean(y)) %>% 
  arrange(str_sort(gr, numeric = T))

results[str_order(results$gr, numeric = T),]
```
But I wanted to do it in a simpler way.

**Comment by eutwt** [comment]
@dax44 The dplyr equivalent of `results[idx,]` is `results %>% slice(idx)`, so another way to accomplish this is:

``` r
gr <- rep(c("q1", "q2", "q10", "q11"), 5)
y <- rnorm(20)
library(dplyr, warn.conflicts = FALSE)
dt <- bind_cols(y = y, gr = gr) 

dt %>% 
  group_by(gr) %>% 
  summarise(m = mean(y)) %>% 
  slice(stringr::str_order(gr, numeric = TRUE))
#> # A tibble: 4 × 2
#>   gr         m
#>   <chr>  <dbl>
#> 1 q1     0.166
#> 2 q2     0.115
#> 3 q10   -0.180
#> 4 q11   -0.263
```

<sup>Created on 2021-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

A third option is to use `readr::parse_number` to convert the column to numeric before using `arrange`

``` r
gr <- rep(c("q1", "q2", "q10", "q11"), 5)
y <- rnorm(20)
library(dplyr, warn.conflicts = FALSE)
dt <- bind_cols(y = y, gr = gr) 

dt %>% 
  group_by(gr) %>% 
  summarise(m = mean(y)) %>% 
  arrange(readr::parse_number(gr))
#> # A tibble: 4 × 2
#>   gr         m
#>   <chr>  <dbl>
#> 1 q1     0.396
#> 2 q2     0.752
#> 3 q10    0.279
#> 4 q11   -0.742
```

<sup>Created on 2021-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dax44** [comment]
Thanks @eutwt . This what I looking for.

**Comment by romainfrancois** [comment]
I second the suggestion from @eutwt, and will close this issue now. 

I ca just add some extra information. The use of `.by_group = T` is not relevant here, as the `arrange()` call happens on an ungrouped data frame, i.e. after the `summarise()` call. 

``` r
library(tidyverse)

gr <- rep(c("q1", "q2", "q10", "q11"), 5)
y <- rnorm(20)

dt <- bind_cols(y = y, gr = gr) 

dt %>% 
  group_by(gr) %>% 
  summarise(m = mean(y))
#> # A tibble: 4 x 2
#>   gr         m
#>   <chr>  <dbl>
#> 1 q1     0.788
#> 2 q10   -0.229
#> 3 q11    0.252
#> 4 q2     0.438
```

<sup>Created on 2021-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Then, the follow up call `%>% arrange(str_sort(gr, numeric = T))` is essentially identical to: 

```r
  %>% 
      mutate(temp = str_sort(gr, numeric = T)) %>%
      arrange(temp) %>%
      select(-temp)
```

So not doing what you may have assumed.
