### ISSUE TITLE
lag only for vectors?

### ISSUE THREAD

**Issue by tappek** [tidyverse/dplyr#5999]
Is `dplyr::lag` only meant for vectors? This is what the documentation tells us:
_"Find the "previous" (lag()) or "next" (lead()) values in a vector."_

It seems to work as expected on factors as well (and a factor is not a vector):

```
dplyr::lag(factor(1:10))
# [1] <NA> 1    2    3    4    5    6    7    8    9   
# Levels: 1 2 3 4 5 6 7 8 9 10
is.vector(factor(1:10))
# [1] FALSE
```

If it is meant for factors as well, the documenation could be adapted and this error message, too:
```
tsx <- ts(1:10, frequency = 4, start = c(1959, 2))
dplyr::lag(tsx)
# Error: `x` must be a vector, not a ts object, do you want `stats::lag()`?
#   Run `rlang::last_error()` to see where the error occurred.
```

**Comment by romainfrancois** [comment]
Closing this here, as this will be taken care of in the `funs` package, e.g. https://github.com/tidyverse/funs/pull/70
