### ISSUE TITLE
Unenhanced warnings are emitted from `mutate()` when run in a `reprex()`

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#6005]
When run with `reprex::reprex()`:

``` r
library(dplyr)

foo <- function() {
  warning("foo")
  NA
}

df <- tibble(x = 1)

df <- mutate(df, x = foo())
#> Warning in foo(): foo
```

vs when run interactively:

```r
df <- mutate(df, x = foo())
#> Warning message:
#> Problem with `mutate()` column `x`.
#> ℹ `x = foo()`.
#> ℹ foo 
```

I think this is related to the changes from https://github.com/tidyverse/dplyr/pull/5686, in particular it is about the `maybe_restart()` bit here that occurs when the warning is muffled

https://github.com/tidyverse/dplyr/blob/87d1cecd7285f935ee3a202af0f74b9c1a640f7d/R/mutate.R#L427-L446

I guess in the stack of `reprex()`, someone is muffling the warnings as it captures them to be able to print them out later on?

Since it was slow to throw the enhanced warnings, maybe this is the best we can do, but it wasn't mentioned in #5686 as a potential issue so I figured I'd bring it up in case @lionel- has any thoughts here

**Comment by lionel-** [comment]
hmmm, it might be possible to create a structured warning where the `conditionMessage()` method communicates with the calling handle.,If the instrumenting handler is alive when the method is called, we'd call it back to return a full warning. I'm happy to work on this if you like (or assist if you want to implement).

**Comment by DavisVaughan** [comment]
If you have the time I'd appreciate if you could take the lead on this because I only understood about half of that 😬

**Comment by hadley** [comment]
@lionel- can you take a look at this when you start integrating the new rlang error stuff into dplyr?
