### ISSUE TITLE
colwise-select documentation should explicitly mention using where()

### ISSUE THREAD

**Issue by rundel** [tidyverse/dplyr#6010]
The current version of the documentation for colwise-select shows these functions as being superseded and includes the following text:

>rename_if(), rename_at(), and rename_all() have been superseded by rename_with(). The matching select statements have been superseded by the combination of a select() + rename_with().
>
>These functions were superseded because mutate_if() and friends were superseded by across(). select_if() and rename_if() already use tidy selection so they can't be replaced by across() and instead we need a new function.

This does not give a clear indication on what function should be used instead - it seems like it would be helpful to explicitly mention using `where()` within `select()` and `rename_with()` as the specific replacement for these superseded functions.

The included examples show the use of `where()` but this was non-obvious to me when I was first looking through the documentaion

**Comment by jmuhlenkamp** [comment]
PR for this: https://github.com/tidyverse/dplyr/pull/6165

Added the last sentence below.

```
rename_if(), rename_at(), and rename_all() have been superseded by rename_with(). 
The matching select statements have been superseded by the combination of a select() + rename_with(). 
Any predicate functions passed as arguments to select() or rename_with() must be wrapped in where().
```
