### ISSUE TITLE
Support dplyr verbs in `group_map` functions

### ISSUE THREAD

**Issue by tentacles-from-outer-space** [tidyverse/dplyr#6014]
The `group_map` functions (`group_map()`, `group_modify()` and `group_walk()`) does not support "dplyr verbs" (`n()`, `cur_group_id()` and others).

Argument `.y` behaves like `cur_group()`.

Is it intentional or just not supported in current state of development (experimental)? If second: can it be supported?

**Comment by hadley** [comment]
I think these are functions that we're leaning away from in general, i.e. it currently seems unlikely that we'll remove the experimental badge, so we're not planning on investing in them in the near term.
