### ISSUE TITLE
Combined mutate + pull operation?

### ISSUE THREAD

**Issue by insperatum** [tidyverse/dplyr#6026]
Whenever I use `pull` it's almost always after a `mutate` operation, and looking through others' code online suggests that this is the most common use case. For example:

```r
df %>% ... %>% mutate(older_than_60 = age>60) %>% pull(older_than_60)
```

This feels a little clunky and redundant to me, so sometimes I'll instead just use `base::with`, which looks cleaner:

```r
df %>% ... %>% with(age>60)
```

However, this obviously precludes me from using all my favorite dplyr goodies like `row_number`, `c_across`, etc. Would it be out of scope to include a dplyr verb that's essentially like pull, but which has mutate semantics rather than select semantics? Or is there another better, dplyr-sanctioned way of doing this?

Thanks for your amazing work on an amazing library ❤️
~ Luke

**Comment by romainfrancois** [comment]
one thing you can do is call a bare `pull()` which gives the last column
so you don’t need to name the variable

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(age = runif(10, min = 18, max = 102))
df %>% 
  mutate(age > 60) %>% 
  pull()
#>  [1]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE
```

then perhaps if this is something you happen to do often, you
can make it a function

``` r
haul <- function(.data, expr) {
  mutate(.data, {{ expr }}) %>% pull()
}

df %>% 
  haul(age > 60)
#>  [1]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE
```

<sup>Created on 2021-09-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
