### ISSUE TITLE
(Reopening) Compilation error with GCC 10.3.1

### ISSUE THREAD

**Issue by smaudet** [tidyverse/dplyr#6041]
Duplicated off of closed bug, which was erroneously said to not contain a "reprex": https://github.com/tidyverse/dplyr/issues/5994

When installing this package or the packages from tidyverse, it appears there are a number of segmentation faults with GCC 10.3.1.

This bug may be upstream in GCC, there seems to be a related issue here:

#5589

There is mention of a gcc patch, however the version which fedora 32 contains (10.3.1-1) does not appear to address this bug. There is no mention of which gcc version which should be used to compile dplyr.

---

**This is the REPREX**

```r
# install.package("dplyr")
```

The seg fault appears somewhat intermittent... (it now compiles fine) just posting this in case others come across. May be a local system mis-configuration, possibly.

Please either:
* Confirm fix this GCC version
* State what GCC version is required

**Comment by romainfrancois** [comment]
We currently don't have the bandwidth to test that particular case. Perhaps you can adapt the check action in a pull request: https://github.com/tidyverse/dplyr/blob/master/.github/workflows/R-CMD-check.yaml so that we actually get to see the problem.

**Comment by smaudet** [comment]
@romainfrancois I'm not sure why you want to close this so bad - isn't the point of bugs to keep track of and fix them?

I understand bandwidth is limited today, maybe you get more help tomorrow. You seem very knee jerk about this, almost like you can't take there being issues like this...

**Comment by lionel-** [comment]
@smaudet Please be aware that ad hominem hot takes do not have a place here.

We use the list of _open_ issues for bugs for which we currently have bandwidth to work on. The list of _closed_ issues is still available for tracking and discussion, and for notifying maintainers of ongoing activity.

**Comment by smaudet** [comment]
"We use the list of _open_ issues for bugs for which we currently have bandwidth to work on."

Well then your bug tracking system is broken - you can't maintain the actual list of known issues, just stuff you want to work on.

And, its not ad hominem if it is true - you just said you don't want to work issues you don't want to work on... (and will go so far as to close them). If that's true, I'm not really inclined to report bugs here any more...enjoy your broken software.
