### ISSUE TITLE
integer64 and “ifelse”

### ISSUE THREAD

**Issue by domq** [tidyverse/dplyr#6043]
---

Brief description of the problem

```r
t <- tibble::tribble(~a, bit64::as.integer64(1))
dplyr::mutate(t, b = ifelse(TRUE, a, a))
```

Expected: column `b` should be of type `integer64`

Actual: column `b` is of type `dbl`

**Comment by DavisVaughan** [comment]
The base R version of `ifelse()` strips the class, so this isn't a dplyr issue.

But you can use `dplyr::if_else()`, which does the right thing here:

``` r
library(bit64)
library(dplyr)

x <- as.integer64(c(1, 2))
y <- as.integer64(c(3, 4))

ifelse(c(TRUE, FALSE), x, y)
#> [1] 4.940656e-324 1.976263e-323

if_else(c(TRUE, FALSE), x, y)
#> integer64
#> [1] 1 4
```

<sup>Created on 2021-10-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
