### ISSUE TITLE
Make count/tally.data.frame methods default?

### ISSUE THREAD

**Issue by nealrichardson** [tidyverse/dplyr#6048]
It's great that count and tally are now generics and you can define methods for them, but I was wondering if the current `count.data.frame` and `tally.data.frame` methods could be renamed to `count.default` and `tally.default`? As far as I can tell, they only meaningfully call other dplyr functions that are themselves generics (summarize, group_by, group_vars), so if you've defined methods for those verbs, then count/tally would just work (but you could still define special methods for them if there were a reason to). 

Context: in https://github.com/apache/arrow/pull/11306 we essentially copied in `count.data.frame` and `tally.data.frame` and had to reach in for some unexported helper functions, and it seems like that should be discouraged.

**Comment by hadley** [comment]
Yeah, that seems reasonable.

**Comment by hadley** [comment]
I think I've changed my mind here — it's been surprisingly hard to reason about what precisely `count()` and `tally()` should return, and the current reconstruction technique is fundamentally tied to data frame subclasses. So I think it's better to leave this as is, and accept that `count()` and `tally()` methods will include some duplication. 

Something about the way we've designed these functions isn't quite right, but I don't know what and I don't know how to avoid it in the future 😞.
