### ISSUE TITLE
Feature request: Allow `lag/lead` to use length-X `n`

### ISSUE THREAD

**Issue by pnacht** [tidyverse/dplyr#6049]
`lag` and `lead` currently mandate that the lag value `n` be a length-1 integer value. Is there a specific reason for this?

I was able to write the following function which allows for length-X vectors in `n`:

``` r
myLag <- function(x, n = 1, default = NA) {
    i <- pmax(seq_along(x) - n, 0)
    x <- c(default, x)
    x[i + 1]
}

myLag(10:15)
#> [1] NA 10 11 12 13 14
myLag(10:15, 0:5)
#> [1] 10 10 10 10 10 10
myLag(10:15, 5:0)
#> [1] NA NA NA 11 13 15
myLag(10:15, 1:2)
#> [1] NA NA 11 11 13 13
myLag(10:15, 2:1)
#> [1] NA 10 10 12 12 14
```

<sup>Created on 2021-10-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Obviously, it lacks some of the checks in `dplyr::lag`, but those would be straightforward to include. It also doesn't include the `order_by` argument and implementation, but at a glance that also seems to be a simple drop-in.

With this implementation, if `x`'s length is not a multiple of `n`'s, a warning is thrown and the output is usually not what was expected, but that could be handled by the standard dplyr error of `"n must be of length {length(x)} or 1, not {length(n)}"` (though that'd make some of the examples above not work, but I'm fine with that).

But most importantly, is there a reason why `lag` currently requires `n` to be length-1?

**Comment by hadley** [comment]
@romin-ebrahimi I think the most useful place to start would be a minimal patch to the existing `lead()` and `lag()` functions.  I think the basic idea is something like this:

```R
lag <- function(x, n = 1L, default = NA, order_by = NULL, ...) {
  if (!is.null(order_by)) {
    return(with_order(order_by, lag, x, n = n, default = default))
  }

  if (inherits(x, "ts")) {
    msg <- "`x` must be a vector, not a ts object, do you want `stats::lag()`?"
    abort(msg)
  }

  if (!is.numeric(n) || any(n < 0)) {
    msg <- glue("`n` must be a vector of positive integers.")
    abort(msg)
  }

  if (vec_size(default) != 1L) {
    msg <- glue("`default` must be size 1, not size {vec_size(default)}")
    abort(msg)
  }

  inputs <- fix_call(vec_cast_common(default = default, x = x))

  xlen <- vec_size(x)
  idx <- seq_len(xlen) - n
  out <- vec_init(x, vec_size(x))

  out <- vec_slice(inputs$x, ifelse(idx <= 0, NA, idx))
  out[idx <= 0] <- default
  out
}
```

**Comment by romin-ebrahimi** [comment]
@hadley I agree. It makes sense to make a simple modification to the code to get this feature request into production first. Is there a standard process for requesting contributor access to create a new feature branch?

**Comment by pnacht** [comment]
@romin-ebrahimi use the standard Github flow: fork the repository, make the necessary changes to your copy of the repo, and then make a pull request.

**Comment by romin-ebrahimi** [comment]
Thank you for the direction. I’ll do that later today.

**Comment by pnacht** [comment]
@romin-ebrahimi You can write a description of the pull request (PR) when you submit it. Make sure to start it with ```Closes #6049``` (this issue). When the PR is eventually accepted, it'll automatically close this issue.

**Comment by romin-ebrahimi** [comment]
The package [collapse](https://cran.r-project.org/web/packages/collapse/collapse.pdf) on CRAN seems to achieve this while utilizing cpp on the backend and is completely compatible with dplyr.

**Comment by DavisVaughan** [comment]
FWIW the original intention of this issue and the PR in #6235 do very different things.

The original intention of this PR is to apply a different lag to each _element_ of `x`

The PR in #6235 maps over N lag values, applying each one to `x` and returning a cbind-ed result. I definitely don't think we are going to do this, because that changes the guarantees around the output type of `lag/lead` too much. So I'm going to close that PR.

---

Regarding the original intention of this PR, I don't see how applying a different lag to each element of `x` would ever be useful? I think I'd need to see a motivating example before considering this.
