### ISSUE TITLE
Shouldn't setequal ignore duplicates? 

### ISSUE THREAD

**Issue by juangomezduaso** [tidyverse/dplyr#6057]
I thought that being in the group of set operations, _setequal()_ would deem things like, say,  _mtcars_ and _bind_rows(mtcars, mtcars)_ as equal, but it doesn´t. 
i suppose this is the intended behavior, but in that case: Souldn´t this be explained somewhere in the documentation? My apologies if it already is, as I was unable to find it. 
Taking into account that Rbase behavior in vectors ignores duplicates (and so  _bind_rows(mtcars,mtcars)[[1]]_ and  _mtcars[[1]]_ are equal) I think this clarification would be useful.

**Comment by DavisVaughan** [comment]
Minimal reprex showing the difference with base R

``` r
setequal(1, c(1, 1))
#> [1] TRUE

dplyr::setequal(data.frame(x = 1), data.frame(x = c(1, 1)))
#> [1] FALSE
```

Seems reasonable that we should be consistent and drop duplicates before checking
