### ISSUE TITLE
Avoid `type_sum()` reexport

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#6058]
Users should import it from pillar (or tibble if absolutely necessary), or better implement `vec_ptype_abbr()` .

dplyr also reexports many more functions that are now deprecated.

This is a breaking change.

**Comment by hadley** [comment]
See discussion in #6281

**Comment by DavisVaughan** [comment]
To summarize, in https://github.com/tidyverse/dplyr/pull/6284 I removed the `tbl_sum()` re-export, but `type_sum()` is imported into many other packages through dplyr and will be hard to remove https://github.com/tidyverse/dplyr/pull/6281#issuecomment-1137739984

**Comment by krlmlr** [comment]
Yeah, let's keep the reexport. I wish there was a way to simplify this. We *could* notify maintainers now, and plan for a breaking patch release (1.1.1 or 1.1.2) in a month or so from now, with just that change. But that seems so much work for so limited gain. I gave up on similar issues for pillar/tibble.
