### ISSUE TITLE
add option to specify filler for missing joins

### ISSUE THREAD

**Issue by Raoul-Kima** [tidyverse/dplyr#6066]
This is essentially a repeat of #1004, as that one was closed. I want to add further motivation and a solution to the issue brought up there.

First the motivation:
Suppose we have a dataset containing NA values that we want to join to another dataset. These NA values might have a different meaning than missing data. Here's a real world example:
```
speciesProperties=
    tibble(
        speciesId=1:3
        ,scientificName=c("Recurvirostra avosetta","Tadorna tadorna","Larus ridibundus")
    )
countResults=
    tibble(
        speciesId=1:2
        ,numberOfBirds=c(34,NA)
    )
```
Suppose this is data from a bird census. Data for species 2 was lost. Species 3 was not encountered during the census. This is how bird census data is formatted in the real world, as there are thousands of bird species on this planet and not having to note species that don't occur saves a lot of work.

In this case I'd like to join the tables with this syntax:
```
speciesProperties %>% 
    left_join(
        countResults
        ,missing=c(numberOfBirds=0) # this function parameter does not exist, i suggest adding it.
    )
```
And the expected result would be:
```
# A tibble: 3 x 3
  speciesId scientificName         numberOfBirds
      <int> <chr>                  <chr>        
1         1 Recurvirostra avosetta 34            
2         2 Tadorna tadorna        NA           
3         3 Larus ridibundus       0            
```
Note how species 2 is treated differently from species 3.
The current version of joins doesn't allow for this differentiation, resulting in a loss of data:
```
# A tibble: 3 x 3
  speciesId scientificName         numberOfBirds
      <int> <chr>                  <chr>        
1         1 Recurvirostra avosetta 34            
2         2 Tadorna tadorna        NA           
3         3 Larus ridibundus       NA           
```
The "simplest" workaround that I found with the current version of joins is the following one. It should be noted that in this special case I could have simplified the code by temporarily recoding NA as -1, as bird counts can never be negative. I decided to show the more complicated general solution using an auxilliary variable, however, as this feature request is supposed to be of general use.
```
speciesProperties %>% 
    left_join(
        countResults %>% 
            mutate(nBirdsMissing=is.na(numberOfBirds))
    ) %>% 
    mutate(
        numberOfBirds=
            ifelse(
                !nBirdsMissing|is.na(nBirdsMissing)
                ,ifelse(
                    is.na(numberOfBirds),0,numberOfBirds
                )
                ,NA
            )
    ) %>% 
    select(-nBirdsMissing)
```
Maybe there is a still simpler workaround, but I couldn't find one. Even if there is a simpler workaround however, the fact that it (apparently) is hard to come up with one suggests that the feature request has merit. This issue has come up many times for me during practical data analysis.

In the original #1004 it was brought up that different variable types (e.g. numeric, character, date, factor, ...) would require different filler values, so one would need to specify a value for each possible variable type. I suggest instead defining it on a per column basis, as each column can only have one variable type (which may be "list"). I've shown how this could look like in the example above (2nd codeblock), using a named vector where the name of the vector elements corresponds to the column names.

**Comment by hadley** [comment]
Given that this is a rather specialised problem and there's an workaround, I think we're better off keeping the join functions focussed on their existing use cases. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
