### ISSUE TITLE
Replace `slice_head()` with `slice_head_n()` and `slice_head_prop()`

### ISSUE THREAD

**Issue by jameslairdsmith** [tidyverse/dplyr#6069]
This might just be me of course, but I keep typing the following when using `slice_head()`:

``` r
library(dplyr, warn.conflicts = F)

mtcars %>% 
  slice_head(10)
#> Error: `...` is not empty.
#> 
#> We detected these problematic arguments:
#> * `..1`
#> 
#> These dots only exist to allow future extensions and should be empty.
#> Did you misspecify an argument?
```

<sup>Created on 2021-11-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Partly I suppose because I'm expecting it to behave in the same way as `head()`.

When looking at the documentation, it looks like the idea is to force the user to choose between `n` and `prop`. One downside is that, when looking at the function definition, a user might think that both are required. 
``` r
slice_head(.data, ..., n, prop)
```
The other downside is that it might make the function harder to reason about. What happens if both `n` and `prop` are provided? At the moment it seems that `prop` gets silently ignored:

``` r
library(dplyr, warn.conflicts = F)

mtcars %>% 
  head(n = 1, prop = 0.99)
#>           mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> Mazda RX4  21   6  160 110  3.9 2.62 16.46  0  1    4    4
```

<sup>Created on 2021-11-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

This seems similar to the [situation with `forecats::fct_lump()`](https://design.tidyverse.org/args-independence.html#cs-fct-lump). In that case, the solution would be to have new functions as follows:

``` r
slice_head_n(.data, n, ...)
slice_head_prop(.data, prop, ...)
slice_tail_n(.data, n, ...)
slice_tail_prop(.data, prop, ...)
```
These would make it clear what the intent of the function is. The arguments would all be required and so easy to reason about and there would be less chance of accidentally passing arguments to the dots. 

One downside of changing the arguments is it might complicate translations in dplyr's extensions. I'm not sure what the implications of that would be.

**Comment by romainfrancois** [comment]
Perhaps we can delegate to `get_slice_size()` the handling of `...` so that it would perhaps specifically handle the case of none of `n` and `prop` are given *and* there is a single unnamed thing in `...`. 

We could either promote that thing to `n` or fail with a better hint.

**Comment by jameslairdsmith** [comment]
> I suppose you meant `slice_head()` in the second example, which does take care of the case where both `n` and `prop` are supplied.

Sorry! Yes, I did mean `slice_head()`. I must have copy-pasted wrong. It's `head()` which doesn't give an error message when using the dots.

**Comment by romainfrancois** [comment]
We ended up going for a special case in #6074: 

``` r
library(dplyr, warn.conflicts = F)

mtcars %>% 
  slice_head(10)
#> Error: `n` must be explicitly named.
#> ℹ Did you mean `slice_head(n = 10)`?
```

<sup>Created on 2021-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I don't think we want to add more variants at this points, but they could easily be incubated in scripts/alternative package: 

```r
slice_head_n <- function(.data, n) { slice_head(.data, n = n) }
```
