### ISSUE TITLE
Unexpected behavior of `{{ var }}` if variable name is declared in multiple namespaces

### ISSUE THREAD

**Issue by luerhard** [tidyverse/dplyr#6096]
The `{{ var }}` (curly-curly operator) behaves strangely when the variable name is used multiple times in different namespaces.

1. a global variable, which is passed to the function
2. a variable in function scope
3. a column in the data.frame
4. the variable is not referenced beforehand in the function

---

The following output shows that it depends on how you name the variable that is iterated over in the uppermost namespace.
If everythings works as expected, the output would always be `1` for 2015 and `100` vor 2016. But if I use the variablename `year` in the for-loop AND do not reference the function variable `year` beforehand, the curly-operator seems to compare the column `year` to itself, which is always `TRUE` -> Thus, using all rows in the dataset to calculate the mean of `50.5` instead of `1` or `100`

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

d <- list(year=c(2015,2015,2016,2016), val=c(1,1,100,100))
df <- as.data.frame(d)

years = c(2015, 2016)

calc_mean_curly <- function(df, year) {
  subdf <- df %>% filter(year == {{ year }})
  mean(subdf$val)
}

calc_mean_exclamation <- function(df, year) {
  subdf <- df %>% filter(year == !!year)
  mean(subdf$val)
}

calc_mean_curly_ref_first <- function(df, year) {
  year
  subdf <- df %>% filter(year == {{ year }})
  mean(subdf$val)
}

# strange namespace conflict?
for (year in years) {
  cat("YEAR: ", year, "\n")
  print(paste("curly =", calc_mean_curly(df, year)))
  print(paste("exclamation =", calc_mean_exclamation(df, year)))
  print(paste("curly, ref first =", calc_mean_curly_ref_first(df, year)))
}
#> YEAR:  2015 
#> [1] "curly = 50.5"
#> [1] "exclamation = 1"
#> [1] "curly, ref first = 1"
#> YEAR:  2016 
#> [1] "curly = 50.5"
#> [1] "exclamation = 100"
#> [1] "curly, ref first = 100"

# works fine
for (y in years) {
  cat("YEAR: ", y, "\n")
  print(paste("curly =", calc_mean_curly(df, y)))
  print(paste("exclamation =", calc_mean_exclamation(df, y)))
  print(paste("curly, ref first =", calc_mean_curly_ref_first(df, y)))
}
#> YEAR:  2015 
#> [1] "curly = 1"
#> [1] "exclamation = 1"
#> [1] "curly, ref first = 1"
#> YEAR:  2016 
#> [1] "curly = 100"
#> [1] "exclamation = 100"
#> [1] "curly, ref first = 100"
```

<sup>Created on 2021-11-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Versions:
dplyr: 1.0.7
R: 4.0.4

**Comment by eutwt** [comment]
I found this example a little confusing so here's (what I believe to be) an equivalent  but simplified example. 

``` r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(a = 'tibble column')
a <- 'global variable'

curly <- function(df, x){
  transmute(df, new = {{ x }})
}

exclamation <- function(df, x){
  transmute(df, new = !!x)
}

curly_ref_first <- function(df, x){
  x
  transmute(df, new = {{ x }})
}

curly(df, a)
#> # A tibble: 1 × 1
#>   new          
#>   <chr>        
#> 1 tibble column
exclamation(df, a)
#> # A tibble: 1 × 1
#>   new            
#>   <chr>          
#> 1 global variable
curly_ref_first(df, a)
#> # A tibble: 1 × 1
#>   new            
#>   <chr>          
#> 1 global variable
```

<sup>Created on 2021-11-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by romainfrancois** [comment]
It looks like the expected behavior. cc @lionel-

**Comment by luerhard** [comment]
But how can it be the excepted behavior if the result changes based on whether (`curly_ref_first`) or not (`curly`) a variable has been mentioned in the function beforehand? That is really weird. Have i just understood the curly braces completely wrong? (which might well be the case)

**Comment by romainfrancois** [comment]
@lionel- will know more, but from my understanding `curly_ref_first()` is off-label, when you tunnel things with `{{` I believe they should only be used once, if you want more flexibility you can use `enquo()` and `!!`

**Comment by lionel-** [comment]
Due to how the language R is implemented, it's impossible to defuse a function argument after it has been used. We might make it an error to defuse a forced argument in rlang 1.1 (end of 2022).

**Comment by luerhard** [comment]
Ok, thanks for the information! I will close this issue then and just use the exclamation mark notation.
