### ISSUE TITLE
bind_rows: allow coercion to type x when column is all NA's

### ISSUE THREAD

**Issue by torbjorn** [tidyverse/dplyr#6097]
I am currently collecting data across well formatted xlsx files.

For a given numerical column some of these files only missing values, where as other files have numeric data in these.

The files with only missing values have this column set to character (because read_xlsx cannot know better), while for other files they correctly get the numeric or double type.

This gives me a problem when I try to bind_rows, as it stops with the error message that it can't combine character and double.

Could it be considered safe to coerce type when one side (either the exising data or the new data to be combined with existing data), is all NA's? Since it is very reasonable that that column originally was another type that was turned to NA with the input function used to read it?

In my particular case (biotech, reading data files from lab), I am dealing with 60 or so files, with 130 or so columns each.
I iteratively have to solve my problem one column at a time. For each column that triggers the above error, I have to add it to a list of columns that needs to be cast to numeric before-hand (even if they are all NA's), and then I retry bind_rows.

I am contemplating writing a function that will read all the files into a list of tibbles, check each column found in any one frame, check if it exists only as character, and if so all NA's, or at most as one other class in the set. A quite laborous and complex thing to do for something that could be available in a much simpler implementation as an option or even as default behaviour in bidn_rows perhaps?

**Comment by DavisVaughan** [comment]
@jennybc do you know if readxl is purposefully doing this behavior:

> The files with only missing values have this column set to character (because read_xlsx cannot know better), while for other files they correctly get the numeric or double type.

I think in readr the "all missing" columns are read in as logical NAs for this exact reason, i.e. https://github.com/tidyverse/readr/issues/662

**Comment by eutwt** [comment]
Looks like readxl has a test that the result is logical here:

https://github.com/tidyverse/readxl/blob/895ccb494846249a4e771c8087a53e90b5a65283/tests/testthat/test-missing-values.R#L101 

I tested just now and it did read an "all missing" column as logical, but my test xlsx was created on a mac with Numbers, so maybe that changes the output vs using MS Excel in a way that's important here.

**Comment by jennybc** [comment]
readxl reads a blank column as logical, so there has to be more to that aspect of the backstory.
<img width="405" alt="Screen Shot 2021-11-29 at 8 55 06 AM" src="https://user-images.githubusercontent.com/599454/143909944-a2779cc3-1b2c-42bb-9ebc-b72368189a1f.png">


``` r
readxl::read_excel("~/tmp/test.xlsx")
#> # A tibble: 2 × 3
#>       x y     z    
#>   <dbl> <lgl> <chr>
#> 1     1 NA    a    
#> 2     2 NA    b
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by romainfrancois** [comment]
In any case, the behavior (to not upcast vectors full of missing values (but not logical) ) is inherited from `vctrs`, and intentional: 

``` r
library(tibble)
library(vctrs)
#> 
#> Attaching package: 'vctrs'
#> The following object is masked from 'package:tibble':
#> 
#>     data_frame

df1 <- tibble(x = NA_character_)
df2 <- tibble(x = 3)
vec_rbind(df1, df2)
#> Error: Can't combine `..1$x` <character> and `..2$x` <double>.
vec_c(NA_character_, 3)
#> Error: Can't combine `..1` <character> and `..2` <double>.
```

<sup>Created on 2021-11-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by torbjorn** [comment]
I get that `vec_rbind` does this, probably with good reason. Or I don't know.

But doesn't this just mean that this issue should be solved a level higher up?

As it is now this is effectively blocking me from combining tibbles from multiple xlsx files, without going through those files in excruciating detail (checking each and every column from each and every file, changing to the proper `NA_subtype_` for all columns that are all NA's). And at this point bind_rows is essentially worthless as I'm doing all the things I needed *it* to do manually myself instead.

The user hardly ever has to deal with NA's having different types. This rarely is an issue in everyday life. From the user's perspective, he or she just sees the rbind fail because NA cannot be combined with other data, and this makes little sense from his or her naive viewpoint.

As it is now:

* read_xlsx inspects content and decides what data type works for each column
* bind_rows aligns and combines the tibbles to be bound, and makes it so.

Between them they fill all the functions necessary to solve this problem. They infer data types from data and combine tibbles to rbind them.

It is not the right way of things to have the user of this functionality, go in and fix things that is the combined responsibility of these two lower level actors.

Should I retype this issue in vctrs instead? A simple `upcast_all_na = TRUE` option to vec_rbind or something similar seems like a useful thing to have.

**Comment by romainfrancois** [comment]
I'm not sure `vctrs` can deal with this, cc @lionel- @DavisVaughan. One thing you can do is code around `bind_rows()` so that you make NA only columns be *logical* NA only, i.e. 

``` r
library(dplyr, warn.conflicts = FALSE)

only_na <- function(x) all(is.na(x))

na_disguise <- function(.data) {
  mutate(.data, across(where(only_na), ~ NA))
}

bind_rows2 <- function(..., .id = NULL) {
  dots <- rlang::list2(...)
  dots <- purrr::map(dots, na_disguise)
  bind_rows(!!!dots, .id = .id)
}

bind_rows2(
  tibble(x = NA_character_),
  tibble(x = 3)
)
#> # A tibble: 2 × 1
#>       x
#>   <dbl>
#> 1    NA
#> 2     3
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by lionel-** [comment]
> Should I retype this issue in vctrs instead?

It is a deliberate design decision to only coerce logical `NA` vectors. I think a better solution is to find out why a vector of character `NA` is created in the first place. Jenny mentioned this shouldn't be the case with blank columns so maybe there's an issue on your side somewhere? If you find that there is an issue on our side, could you please post a readxl reprex that shows how character `NA` s are created from blank columns?

**Comment by torbjorn** [comment]
In my particular case I have some data.frames with columns that are all logical NA's, and other data frames where the same columns have character content that is not NA.

**Comment by jennybc** [comment]
Row-binding when some data frames have column `z` as all logical `NA`s and others have `z` as character does already work, by design.

``` r
library(tidyverse)

x <- tibble(z = NA)
y <- tibble(z = "blah")
bind_rows(x, y)
#> # A tibble: 2 × 1
#>   z    
#>   <chr>
#> 1 <NA> 
#> 2 blah
```

<sup>Created on 2021-12-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
