### ISSUE TITLE
`bind_rows()` strips out columns' "custom" attributes

### ISSUE THREAD

**Issue by netique** [tidyverse/dplyr#6099]
When I have two tibbles containing columns with "custom" attributes, they are stripped out during `bind_rows()`. Note that conventional attributes such as levels or class are retained as expected. I suspect that the issue lies in `dplyr_reconstruct()` phase, because the template is OK, but the function does not care about _column_ attributes at all:

``` r
library(tidyverse)

b <- a <- tibble(a = factor(letters[1:3]))

attr(b$a, "my_attr") <- attr(a$a, "my_attr") <- "don't loose this"

# those are OK
a %>% map(attributes)
#> $a
#> $a$levels
#> [1] "a" "b" "c"
#> 
#> $a$class
#> [1] "factor"
#> 
#> $a$my_attr
#> [1] "don't loose this"

# where is my attribute?
bind_rows(a, b) %>% map(attributes)
#> $a
#> $a$levels
#> [1] "a" "b" "c"
#> 
#> $a$class
#> [1] "factor"
```

<sup>Created on 2021-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by romainfrancois** [comment]
I believe this is what is meant to happen in `vctrs`, here is a shorter reprex without dplyr specific code:

``` r
library(vctrs)

f <- g <- factor(letters[1:3])
attr(f, "my_attr") <- attr(g, "my_attr") <- "don't loose this"
out <- vec_c(f, g)
str(out)
#>  Factor w/ 3 levels "a","b","c": 1 2 3 1 2 3
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Presumably, this needs `f` and `g` (or the `a` columns) to have a class and `vctrs` support for that class.

**Comment by romainfrancois** [comment]
I believe [vec_restore](https://vctrs.r-lib.org/reference/vec_proxy.html) is what you are looking for. I'll close this here though. 

cc @DavisVaughan @lionel-

**Comment by DavisVaughan** [comment]
I would advise you to read over https://vctrs.r-lib.org/articles/s3-vector.html and maybe open a vctrs issue if you have any very specific questions or issues
