### ISSUE TITLE
group_by() row order different when testing

### ISSUE THREAD

**Issue by grahamjwhite** [tidyverse/dplyr#6101]
I'm having an issue where some tests are failing unexpectedly because the row order of a tibble during tests is different to when code is run interactively, where the code involves a `group_by() %>% summarise()`. Steps to create the problem:
* create a new package
* put the function `func()` as below into an R file
```r
func <- function(){
  tib <- tibble::tibble(name = c("b", "b", "A", "C", "A", "C"),
                        value1 = 1:6,
                        value2 = 3:8)

  tib %>%
    dplyr::group_by(name) %>%
    dplyr::summarise(sum1 = sum(value1),
                     sum2 = sum(value2))
}
```
* put the test as below into corresponding test file
```r
test_that("func output", {
  funcOutput <- func()
  expect_equal(tibble::tibble(name = c("A", "b", "C"),
                              sum1 = c(8, 3, 10),
                              sum2 = c(12, 7, 14)),
                funcOutput)
})
```
* run `devtools::test()`

The issue appears to be that the sorting of the groups is putting lower-case group items below upper-case ones during tests, but otherwise sorting them alphabetically. In the reprex below, the groups are "A", "b" and "C" and the output of `func()` gives the rows in that order, but when you run `func()` inside the test, the tibble is returned in the order "A", "C", "b" and the test fails. 

``` r
devtools::load_all()
#> i Loading test
#> Warning: package 'testthat' was built under R version 4.0.5

packageVersion("dplyr")
#> [1] '1.0.7'
packageVersion("testthat")
#> [1] '3.1.0'
packageVersion("devtools")
#> [1] '2.4.2'

# output of func
func()
#> # A tibble: 3 x 3
#>   name   sum1  sum2
#>   <chr> <int> <int>
#> 1 A         8    12
#> 2 b         3     7
#> 3 C        10    14

# but test fails...
devtools::test()
#> i Loading test
#> i Testing test
#> v | F W S  OK | Context
#> / |         0 | hello                                                           - | 1       0 | hello                                                           x | 1       0 | hello [0.4s]
#> --------------------------------------------------------------------------------
#> Failure (test-hello.R:5:3): func output
#> tibble::tibble(...) (`actual`) not equal to `funcOutput` (`expected`).
#> 
#> actual vs expected
#>                 name sum1 sum2
#>   actual[1, ]      A    8   12
#> - actual[2, ]      b    3    7
#> + expected[2, ]    C   10   14
#> - actual[3, ]      C   10   14
#> + expected[3, ]    b    3    7
#> 
#> `actual$name`:   "A" "b" "C"
#> `expected$name`: "A" "C" "b"
#> 
#>   `actual$sum1`: 8  3 10
#> `expected$sum1`: 8 10  3
#> 
#>   `actual$sum2`: 12  7 14
#> `expected$sum2`: 12 14  7
#> --------------------------------------------------------------------------------
#> 
#> == Results =====================================================================
#> Duration: 0.4 s
#> 
#> [ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
May be related to #6018

**Comment by DavisVaughan** [comment]
I'm pretty sure this is just because when you run testthat it sets the locale to C for consistency across all platforms, but when you run the code interactively it uses your system locale, which is potentially something like `"en_US"`.

Both `arrange()` and `group_by() %>% summarise()` are sensitive to the system locale, so that is why you are seeing those differences.

Both #6018 and #5942 are intended to help with these sort of issues

**Comment by grahamjwhite** [comment]
Thanks both for your time, this explains it (output below showing the effect of locale on `func()`). Seems there was some discussion about this, I just wasn't aware locale was the issue (see for example r-lib/testthat#1181). I will consider this issue closed, since I can solve it with withr. 

``` r
withr::with_collate("C", func())
#> # A tibble: 3 x 3
#>   name   sum1  sum2
#>   <chr> <int> <int>
#> 1 A         8    12
#> 2 C        10    14
#> 3 b         3     7
withr::with_collate("English_US", func())
#> # A tibble: 3 x 3
#>   name   sum1  sum2
#>   <chr> <int> <int>
#> 1 A         8    12
#> 2 b         3     7
#> 3 C        10    14
```

<sup>Created on 2021-12-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
