### ISSUE TITLE
"Ancestor must be an environment" error

### ISSUE THREAD

**Issue by AlbertRapp** [tidyverse/dplyr#6118]
I have already asked a question on Stackoverflow about this (see [here](https://stackoverflow.com/questions/70243637/what-triggers-ancestor-must-be-an-environment-error)) but so far no one was able to help me. I am looking for reasons that could cause an error like this

```
✖ Problem with `filter()` input `..1`.
ℹ Input `..1` is `between(n, lBd, uBd)`.
✖ `ancestor` must be an environment"
```

I have tried looking at the source code but I could not find where this kind of message is coming from or what it means. Do you have any suggestions? As described on my [original SO post](https://stackoverflow.com/questions/70243637/what-triggers-ancestor-must-be-an-environment-error), it is kind of hard to find a reprex. I run a somewhat large script on multiple threads but the only calculation where my script fails is the following:

``` 
lBd <- floor(TMax^delta) # lower bound
uBd <-  ceiling(m * TMax^delta) # upper bound
    
# process is a tibble with columns `n` and `variance`
process %>% 
  dplyr::filter(between(n, lBd, uBd)) %>% 
  lm(data = ., log(variance) ~ log(n))
``` 

Nothing to fancy is really going on here and the weird thing is sometimes the script runs through on the threads and sometimes I get the above error message (I could not find a common denominator in either case). I don't know what is going on but understanding what can trigger such an error might help me trace back what goes wrong. Are there any "usual suspects" for this error?

**Comment by hadley** [comment]
Unfortunately there's not much we can do without a reprex. The types of errors you are seeing suggest some sort of memory corruption, which might occur upstream of the dplyr code reporting the problem.
