### ISSUE TITLE
Use base pipe in examples and vignettes

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#6129]
I don't know how we're going to do this and keep supporting R 3.5 and later, but it would be good to come up with a plan.

**Comment by Fredo-XVII** [comment]
Hello!

Just throwing out an idea.  R 3.5 is based on magrittr's  pipe, `%>%`,  but that is just a function.  Couldn't you name it `|>` instead? 

By doing so, you could then use a condition where if the R version is < 4.0, you use the `|>` that points to the magrittr pipe code, else, use the new base R pipe `|>`.  Then you can use `|>` in all the code.  

I believe that you have done something similar with versioning in some packages to use an older version based on the R version...just can't remember which package that was.  I believe you used an ENV variable to select the previous version.  

This just came to me so I thought I should write it down.

If I knew how to do it, I would work on it myself, but don't know how versioning packages works.

Thanks!

**Comment by hadley** [comment]
@Fredo-XVII unfortunately that won't work because `|>` isn't a valid function name in < 4.0.

**Comment by hadley** [comment]
Waiting for https://github.com/r-lib/roxygen2/issues/1295

**Comment by hadley** [comment]
Closing here; once we've figured out in roxygen we'll roll out across the tidyverse.
