### ISSUE TITLE
Preserve `variable.labels` attribute in column manipulation

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#6136]
From https://github.com/rstudio/rstudio/issues/9771

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(a=1, b=2, c=3)
attr(df, "variable.labels") <- c(a = "a", b = "b", c = "c")
attr(select(df, -b), "variable.labels")
#>   a   b   c 
#> "a" "b" "c"
```

<sup>Created on 2021-12-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by romainfrancois** [comment]
The ide uses the attribute to add a description in `View()`. `View(df)` gives: 

<img width="306" alt="image" src="https://user-images.githubusercontent.com/2625526/146766038-43c0c2ab-0ee5-41b4-8a47-92f1b731067c.png">

`View(select(df, -b))` gives: 

<img width="226" alt="image" src="https://user-images.githubusercontent.com/2625526/146766095-7bddda63-8e86-4852-9769-f2109f268833.png">

that is dealt with in this PR: https://github.com/rstudio/rstudio/pull/10082

However, a name based approach does not work for renaming, i.e. `select(a = b)`: 

<img width="191" alt="image" src="https://user-images.githubusercontent.com/2625526/146766242-9df10dbc-c6ad-41b2-b397-da800673eead.png">

**Comment by jgutman** [comment]
This is now addressed in rstudio/rstudio#10335, but the issue above with renaming columns still stands

**Comment by hadley** [comment]
We could consider transforming `variable.labels` (if it exists and is the correct length) in all column focussed verbs.

**Comment by hadley** [comment]
Hmmmmm, this feels like quite a lot of work as there are many cases to consider:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(a = 1, b = 2, c = 3)
attr(df, "variable.labels") <- c(a = "a", b = "b", c = "c")

attr(select(df, -b), "variable.labels")
#>   a   b   c 
#> "a" "b" "c"
attr(select(df, B = b), "variable.labels")
#>   a   b   c 
#> "a" "b" "c"
attr(mutate(df, c = paste(a, b)), "variable.labels")
#>   a   b   c 
#> "a" "b" "c"
attr(mutate(df, c = paste(a, b), .drop = "used"), "variable.labels")
#>   a   b   c 
#> "a" "b" "c"
attr(relocate(df, b), "variable.labels")
#>   a   b   c 
#> "a" "b" "c"
attr(rename(df, B = b), "variable.labels")
#>   a   b   c 
#> "a" "b" "c"
```

<sup>Created on 2022-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It also feels a bit out of scope for dplyr itself, since it doesn't otherwise know about `"variable.labels"` or handle any attribute specially. But I'm not sure where else this would go.

**Comment by hadley** [comment]
@DavisVaughan points out that base R doesn't do anything to preserve them, so you'll lose them pretty quickly in any case. So I think that pushes me over the line to say this is out of scope for dplyr.
