### ISSUE TITLE
Summarise gives Internal error in `df_slice()`: Columns must match the data frame size.

### ISSUE THREAD

**Issue by IanWorthington** [tidyverse/dplyr#6138]
I've been asked over at [rstudio ](https://community.rstudio.com/t/summarise-gives-internal-error-in-df-slice-columns-must-match-the-data-frame-size/124778) to raise this possible bug report here.

---
The code below gives the error message

Error: Problem with `summarise()` column `xxx`.
i `xxx = nrow(filter(cur_data(), abc2 > 0))`.
x Internal error in `df_slice()`: Columns must match the data frame size.

```r

library(tidyverse)
library(glue)

lookAhead = 2
colnm = sym(glue("abc{lookAhead}"))

set.seed(123)
df <- data.frame(abc1 = rnorm(5), abc2 = rnorm(5))


df %>% 
  summarise(n  = n(), 
            xxx = nrow(filter(cur_data(), {{colnm}}>0))
  )
```

Reversing the two summarise parameters fixes the problem.

**Comment by romainfrancois** [comment]
This to be an issue with what `cur_data()` gives: 

``` r
library(tidyverse)
library(glue)

lookAhead = 2
colnm = sym(glue("abc{lookAhead}"))

set.seed(123)
df <- data.frame(abc1 = rnorm(5), abc2 = rnorm(5))

df %>% 
  summarise(n  = n(), 
            xxx = str(cur_data())
  )
#> tibble [5 × 3] (S3: tbl_df/tbl/data.frame)
#>  $ abc1: num [1:5] -0.5605 -0.2302 1.5587 0.0705 0.1293
#>  $ abc2: num [1:5] 1.715 0.461 -1.265 -0.687 -0.446
#>  $ n   : int 5
#>   n
#> 1 5
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

`n` is size 1, should it be size `n()` ? Should it even be in `cur_data()` ? 

Should `vec_slice()` give more detail about what column is wrong ?

``` r
library(vctrs)
set.seed(123)

df <- list(abc1 = 1:5, n = 5)
class(df) <- "data.frame"
attr(df, "row.names") <- c(NA, -5L)
str(df)
#> 'data.frame':    5 obs. of  2 variables:
#>  $ abc1: int  1 2 3 4 5
#>  $ n   : num 5

vctrs::vec_slice(df, c(TRUE, TRUE, FALSE, FALSE, FALSE))
#> Error:
#> ! Internal error in `df_slice()`: Columns must match the data frame size.
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

However, there is no need to use `nrow()` + `filter()` here: 

``` r
library(tidyverse)
library(glue)

lookAhead = 2
colnm = sym(glue("abc{lookAhead}"))

set.seed(123)
df <- data.frame(abc1 = rnorm(5), abc2 = rnorm(5))

df %>% 
  summarise(n  = n(), 
            xxx = sum({{colnm}}>0)
  )
#>   n xxx
#> 1 5   2
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Also, `{{` is meant to be used with function arguments, this should use `!!` instead: 

``` r
df %>% 
  summarise(n  = n(), 
            xxx = sum(!!colnm>0)
  )
#>   n xxx
#> 1 5   2
```

@lionel- is there a way to make `{{` error when not used for function arguments ?

**Comment by lionel-** [comment]
> @lionel- is there a way to make {{ error when not used for function arguments ?

Unfortunately we can't do that because regular objects are indistinguishable from arguments resolving to constants in compiled code, see https://rlang.r-lib.org/reference/topic-embrace-non-args.html

**Comment by IanWorthington** [comment]
> > @lionel- is there a way to make {{ error when not used for function arguments ?
> 
> Unfortunately we can't do that because regular objects are indistinguishable from arguments resolving to constants in compiled code, see https://rlang.r-lib.org/reference/topic-embrace-non-args.html

@lionel - 

If the two are indistinguishable, does it actually matter if !! or {{...}} are used?

**Comment by lionel-** [comment]
yes because not all arguments are constant-folded by the compiler, only constants like `"foo"` or `1` are. In particular symbolic arguments (symbols and calls) are wrapped in promises and can be defused by `enquo()`. So the difference between `!!` and `{{` (which is a shortcut for `!!enquo()` is meaningful (and crucial) most of the times.
