### ISSUE TITLE
Take ownership of the `mutate()` step in `group_by()`

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#6139]
To simplify the error message:

```r
mtcars %>%
  group_by(cyl = 1 + "") %>%
  mutate(new = 1 + "")
#> Error in `group_by()` at dplyr/R/mutate.R:156:2:
#> ! Problem adding computed columns.
#> Caused by error in `mutate()`:
#> ! Problem while computing `cyl = 1 + ""`.
#> Caused by error in `1 + ""`:
#> ! non-numeric argument to binary operator
```

**Comment by hadley** [comment]
Is there some simple way to do this?

**Comment by lionel-** [comment]
To keep the dplyr API user-oriented, we didn't add `call` arguments to the generics or data frame methods, instead we used a sentinel approach. It works by setting `dplyr_local_error_call()` before calling other dplyr verbs, then they should borrow the call automatically.

This is still experimental but is used in some places, e.g. in the `slice()` derivatives like `slice_head()`.

**Comment by hadley** [comment]
Hmmm, adding `dplyr_local_error_call()` at the obvious place in `count.data.frame()` doesn't work, and `add_computed_columns()` already has what looks like an existing attempt to solve this problem, so I think probably someone else will need to take a look at this.

**Comment by lionel-** [comment]
Sounds good I'll take a look after the workshop.
