### ISSUE TITLE
Summarise feature: paste_distinct

### ISSUE THREAD

**Issue by roni-fultheim** [tidyverse/dplyr#6140]
If possible, could a `summarise()` helper be created for **pasting** all unique values per summed group?
Similar to the existing `n_distinct()` which helps sum the number of unique values per category.

Many thanks

```r
# existing - count of unique values
x <- c(1:5)
length(unique(x))
#> [1] 5
n_distinct(x)
#> [1] 5

# current solution
paste0(unique(x), collapse = ";")
#> [1] "1;2;3;4;5"
# wanted - pasting unique values
paste_distinct(x, sep = ";") #
#> [1] "1;2;3;4;5"


```

**Comment by DavisVaughan** [comment]
I think your current solution is pretty good. You could even wrap that up in a function called `paste_distinct()` if you wanted.

We typically don't add small ad hoc wrappers to dplyr though, so I don't think this belongs here. But thank you for the suggestion!
