### ISSUE TITLE
`slice` fails if the index is a variable that is also a column name

### ISSUE THREAD

**Issue by michaellevy** [tidyverse/dplyr#6143]
`slice`ing with the index provided by a variable which is also a column name fails to slice.

``` r
library(tidyverse)
x <- 3
tibble(x = 1:5) %>% 
    slice(x)
#> # A tibble: 5 × 1
#>       x
#>   <int>
#> 1     1
#> 2     2
#> 3     3
#> 4     4
#> 5     5
```

<sup>Created on 2021-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by eutwt** [comment]
You can use the [injection operator](https://rlang.r-lib.org/reference/injection-operator.html) i.e. "bang bang"

``` r
library(dplyr, warn.conflicts = FALSE)
x <- 3
tibble(x = 1:5) %>% 
    slice(!!x)
#> # A tibble: 1 × 1
#>       x
#>   <int>
#> 1     3
```

<sup>Created on 2021-12-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by romainfrancois** [comment]
This is the desired behavior. Thanks @eutwt for the workarounds.
