### ISSUE TITLE
include window_order() here

### ISSUE THREAD

**Issue by cboettig** [tidyverse/dplyr#6146]
I'd like to second @krlmlr 's suggestion from #5903 to include `window_order()` here in addition to `dbplyr`.  

Currently, this creates an edge case where dplyr can run on a remote connection (`tbl_sql`) but not natively in R. I realize this was intentionally created to address #2874 (regarding the use of `arrange()` on remote sources), but it feels like the converse case, support for `window_order()` in native dplyr, would also be logical.  

For example, this fails 
```r
library(tidyverse)
diamonds %>% dbplyr::window_order(cut) %>% group_by(cut) %>% summarise(m=mean(price))
```

Note too that the error message is somewhat cryptic:

```
Error in UseMethod("op_vars") : 
  no applicable method for 'op_vars' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"
```

i.e. it is not obvious that `op_vars` is being triggered by `dbplyr::window_order()` and not some other part of the pipeline.  At very least a more helpful error message (`window_order() is not defined for an object of class "c('tbl_df', 'tbl', 'data.frame'), did you mean to use arrange() instead?`) would help.  

Ideally though it seems we should be able to use `window_order` on R data.frames, as discussed in #5903.

**Comment by hadley** [comment]
I'm pretty sure this should to stay as a dbplyr only feature; I think it's fine for backends to have some features that dplyr does not.

**Comment by cboettig** [comment]
yeah that makes sense.  Would it be possible for the error message to indicate that `op_vars()` refers to the call to `window_order()`?  

```
  no applicable method for 'window_order' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"
```

would seem more intuitive but yeah probably not a priority (yay for interactive debugger)

**Comment by hadley** [comment]
Would you mind filing that in dbplyr?
