### ISSUE TITLE
Grouped data summarize() with zero-length value silently drops group

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#6147]
When running summarize with a calculated summary value (`value_at_mask` in the example) drop the group rather than giving the expected error that the result must be length >= 1.  The reason for the issue below is that `value[mask]` for group 2 is zero-length.

The expected result from the call below would give an error indicating that `value_at_mask` must be length 1 or greater.

``` r
library(tidyverse)

d <-
  tibble(
    ID=1:2,
    mask=c(TRUE, FALSE),
    value=1:2
  )
d %>%
  group_by(ID) %>%
  summarize(
    value_min=min(value),
    value_at_mask=value[mask]
  )
#> `summarise()` has grouped output by 'ID'. You can override using the `.groups` argument.
#> # A tibble: 1 x 3
#> # Groups:   ID [1]
#>      ID value_min value_at_mask
#>   <int>     <int>         <int>
#> 1     1         1             1
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by romainfrancois** [comment]
size 0 is valid, and then `value_min` is correctly "recycled" zero times. This is consistent with tidy recycling rules. 

One could write a specialized `summarise()` variant that would forbid size 0 results, e.g. 

``` r
library(tidyverse)
library(rlang)
#> 
#> Attaching package: 'rlang'
#> The following objects are masked from 'package:purrr':
#> 
#>     %@%, as_function, flatten, flatten_chr, flatten_dbl, flatten_int,
#>     flatten_lgl, flatten_raw, invoke, list_along, modify, prepend,
#>     splice
library(vctrs)
#> 
#> Attaching package: 'vctrs'
#> The following object is masked from 'package:dplyr':
#> 
#>     data_frame
#> The following object is masked from 'package:tibble':
#> 
#>     data_frame

d <- tibble(
    ID=1:2,
    mask=c(TRUE, FALSE),
    value=1:2
  )

summarise2 <- function(.data, ..., .groups = NULL) {
  dots <- map(enquos(...), function(quo) {
    new_quosure(
      call2("check_size", quo_get_expr(quo)),
      env(quo_get_env(quo), check_size = function(x) {
        if (vec_size(x) == 0L) {
          abort("Result can't be size 0")
        }
        x
      })
    )
  })
  summarise(.data, !!!dots, .groups = .groups)
}
d %>%
  group_by(ID) %>%
  summarise2(
    value_min=min(value),
    value_at_mask=value[mask]
  )
#> Error in `summarise()`:
#> ! Problem while computing `value_at_mask = check_size(value[mask])`.
#> ℹ The error occurred in group 2: ID = 2.
#> Caused by error in `check_size()`:
#> ! Result can't be size 0
```

<sup>Created on 2022-01-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by romainfrancois** [comment]
@lionel- I was wondering if `summarise2()` could be made simpler to write with this imaginary `{{{` syntax: 

```r
summarise3 <- function(.data, ..., .groups = NULL) {
  check_size = function(x) {
    if (vec_size(x) == 0L) {
      abort("Result can't be size 0")
    }
    x
  }
  summarise(.data, {{{ check_size(...) }}}, .groups = .groups)
}
```

**Comment by billdenney** [comment]
@romainfrancois , thanks for the quick reply.

Thanks for the description of what is happening.  I now understand that it is consistent, and that a change would likely be unnecessarily breaking backwards compatibility.

For my use cases, a mixture of length 0 and nonzero would always be an error since I would use filter to remove groups that I don't want in the output explicitly rather than summarize to remove them more implicitly.

I do think that at least a warning when some values are zero would be useful.  That is because, at least for me, any zeros-length values are actually errors.

If others don't agree, no worries and thanks for the pointers of how I can do it on my own.

**Comment by lionel-** [comment]
@romainfrancois When we discussed a `{{{` syntax for templating dots in the group meeting we concluded that it wouldn't be worth complicating the tidy eval syntax now that we have `across()`.

**Comment by lionel-** [comment]
> I do think that at least a warning when some values are zero would be useful. That is because, at least for me, any zeros-length values are actually errors.

We generally take the position that a behaviour should either be an error or a silent success, not a warning.

The goal of recycling size-0 vectors is to reduce the number of edge cases to handle specially. Making it a warning would defeat that purpose.
