### ISSUE TITLE
Feature request: abritrary mutating/processing entire tibble in pipe

### ISSUE THREAD

**Issue by esamatic** [tidyverse/dplyr#6152]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Quite often there is a need to call some function (which does something else than column/rowwise operations) for the entire tibble based on the value of a predicate. 

In my opinion it would be nice to this in the pipe - so I'm asking would it be possible to add this kind of functionality to dplyr (or some other tidyverse package)?

Here is the basic idea - kind of operation to mutate/process the entire tibble (you can most probably generalize this idea further):

```r
call_fun_for_tibble_if <- function(x, predicate, fun, ...) { if (predicate) fun(x, ...) else x }
```

In this manner this stupid example
```r
test_me <- function(x, verbose = T) {
  out <- tibble(a = LETTERS)
  if (verbose) print(out)
  out
}
```
would become
```r
test_me <- function(x, verbose = T) {
  tibble(a = LETTERS) %>%
    call_fun_for_tibble_if (verbose, print)
}
```

**Comment by DavisVaughan** [comment]
This idea has come up a few times before 
https://twitter.com/thomas_neitmann/status/1309431998805573632?s=20

In general I think this would be a nice idea for a separate package, but I don't think we should add this to dplyr itself because I think the use case is a little too narrow

**Comment by esamatic** [comment]
For me it quite often "breaks" a nice pipe - just like Thomas N says in his tweet. 

But I understand, my use of dplyr/tidyverse may be quite different from the majority of other users,

**Comment by romainfrancois** [comment]
Maybe this is a use case for the `%T>%` operator: 

```r
test_me <- function(verbose = T) {
  tibble(a = LETTERS) %T>% 
    { if (verbose) print(.) } %>% 
    head()
}
```

`tibble(a = LETTERS)` is piped in to both `{ if (verbose) print(.) }` and `head()`
