### ISSUE TITLE
Case_when and ifelse calculations not lazy

### ISSUE THREAD

**Issue by IgnatiusPang** [tidyverse/dplyr#6158]
---

If the evaluations are not lazy (e.g delays the evaluation of an expression until its value is needed), then the NaN warning for sqrt(-1) should only be produced once. However, since the calculations are done for all case, the sqrt(-1) NaN warning is produced twice. In best practice, the calculations should not be done if the left hand side logical test is not satisfied. 

How I wish lazy evaluations of the type described in [Wikipedia](https://en.wikipedia.org/wiki/Lazy_evaluation) be implemented for case_when. This limits the type of things I can do with writing programs (e.g. less flexible). For examples, it forces me to use base R if  else conditional statements rather than using case_when.... I think this problem applies for the ifelse function as well. 

The code below produces two NaN warnings... 
```r
library(dplyr)

even_function <- function(y){sqrt(y) }
odd_function <- function(y){sqrt(y) + 1}

data.frame(x=1:10, y =-1:8) %>% 
  mutate( type = case_when( x %% 2 == 0 ~ even_function(y) ,
             TRUE ~ odd_function(y) ))

```
Warning: Problem with `mutate()` column `type`.
ℹ `type = case_when(x%%2 == 0 ~ even_function(y), TRUE ~ odd_function(y))`.
ℹ NaNs produced
Warning: Problem with `mutate()` column `type`.
ℹ `type = case_when(x%%2 == 0 ~ even_function(y), TRUE ~ odd_function(y))`.
ℹ NaNs produced

The behaviour is reproducible for ifelse as well. 
```{r}
test_data %>% 
  mutate( type = ifelse(x %% 2 == 0, even_function(y),  odd_function(y)    ))

```
Warning: Problem with `mutate()` column `type`.
ℹ `type = ifelse(x%%2 == 0, even_function(y), odd_function(y))`.
ℹ NaNs produced
Warning: Problem with `mutate()` column `type`.
ℹ `type = ifelse(x%%2 == 0, even_function(y), odd_function(y))`.
ℹ NaNs produced

**Comment by hadley** [comment]
This is a fundamental limitation of the current implementation that we don't yet know how to resolve.

**Comment by IgnatiusPang** [comment]
Thank you Hadley.
