### ISSUE TITLE
Feature request to distinct() function 

### ISSUE THREAD

**Issue by pehkawn** [tidyverse/dplyr#6160]
This is more a feature request in the `distinct()` function than an issue. However, I find this function somewhat lacking, and introducing some additional features would simplify certain operations:

If for example you want to find duplicate entries in specific columns, but at the same time keep all columns (`.keep_all = TRUE`), the `distinct()` will only keep the first row. This isn't always desirable (I dare say it is quite often not). It could for some reason be that you want to keep another row, or you want the row merged by some formula. Supposedly, there are ways of adding data-masking functionality. However, this isn't necessarily very intuitive, and therefore adding some base operations (e.g. column means or column medians, column sums) would greatly simplify how to deal with duplicated entries in the data.

Example:
Currently, `distinct()` can only preserve only the first row:
```r
a <- data.frame(
    "x" = rep(1:3, each = 2),
    "y" = rep(1:3, each = 2),
    "z" = 1:6
)

# Original dataframe
a
A data.frame: 6 × 3
x	y	z
<int>	<int>	<int>
1	1	1
1	1	2
2	2	3
2	2	4
3	3	5
3	3	6

# Dataframe with duplicates removed
distinct(a, x, .keep_all = TRUE)
A data.frame: 3 × 3
x	y	z
<int>	<int>	<int>
1	1	1
2	2	3
3	3	5
```

Example of suggested functionality:
```R
# Duplicates removed by adding column means:
distinct(a, x, .keep_all = "colMeans")
A data.frame: 3 × 3
x	y	z
<int>	<int>	<int>
1	1	1.5
2	2	3.5
3	3	5.5

# Duplicates removed by adding column sums:
distinct(a, x, .keep_all = "colSums")
A data.frame: 3 × 3
x	y	z
<int>	<int>	<int>
1	2	3
2	4	7
3	6	11
```

**Comment by DavisVaughan** [comment]
That can be done pretty simply with group by + summarize.

``` r
library(dplyr, warn.conflicts = FALSE)

a <- tibble(
  "x" = rep(1:3, each = 2),
  "y" = rep(1:3, each = 2),
  "z" = 1:6
)
a
#> # A tibble: 6 × 3
#>       x     y     z
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     1     1     2
#> 3     2     2     3
#> 4     2     2     4
#> 5     3     3     5
#> 6     3     3     6

a %>%
  group_by(x) %>%
  summarise(across(everything(), mean))
#> # A tibble: 3 × 3
#>       x     y     z
#>   <int> <dbl> <dbl>
#> 1     1     1   1.5
#> 2     2     2   3.5
#> 3     3     3   5.5

a %>%
  group_by(x) %>%
  summarise(across(everything(), sum))
#> # A tibble: 3 × 3
#>       x     y     z
#>   <int> <int> <int>
#> 1     1     2     3
#> 2     2     4     7
#> 3     3     6    11
```

<sup>Created on 2022-01-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by pehkawn** [comment]
Thank you for your reply.
I was aware I can use `group_by` in combination with `summarise(across(...))`, which is why I consider my post more of a feature request than an issue. Using `group_by(x) %>% summarise(across(everything(), mean))` isn't without issues though: it is slow and strips all variables and values of any labels. I suspect that this procedure will recalculate the variables in *all* rows, not only the ones with duplicated values in the ID column(s), consequently, coercing all values to numeric in the process. (At least it was considerably faster to run on a subset of duplicates.) It is possible to subset the duplicates, merge them by the desired procedure, and join together with the original data set. However, this creates a lot of additional steps. You have to subset and merge duplicates, remove all duplicates from the original data set, and then join back together.

`distinct()` is nice because it is an easy way to remove any duplicates in a pipe chain after a join. However, in the case that somehow not all variables match, dropping all row but would in many cases be an arbitrary decision, and most likely is it not an ideal way of dealing with the duplicates. Hence my request for this as an additional feature of `duplicate()`. It would be nice if a function could recognise which rows in a specified column(s) have duplicate values, then perform then merge by a specified function/procedure without performing calculation on all rows or dropping variable and value labels.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
