### ISSUE TITLE
Select and relocate work inconsistenly on an empty dataframe

### ISSUE THREAD

**Issue by jttoivon** [tidyverse/dplyr#6167]
I expect that trying to `relocate` a non-existing column with `any_of` would return the original dataframe. Even if the dataframe is empty. The function `select` seems to work more consistently with `any_of`.

My dplyr version is 1.0.7.

``` r
library(tidyverse)
tibble(a=1:2) %>% relocate(any_of("b"))
#> # A tibble: 2 × 1
#>       a
#>   <int>
#> 1     1
#> 2     2
tibble() %>% relocate(any_of("b"))
#> Error: Can't subset columns that don't exist.
#> x Location 1 doesn't exist.
#> ℹ There are only 0 columns.
tibble() %>% select(any_of("b"))
#> # A tibble: 0 × 0
```

<sup>Created on 2022-01-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
This does seem like a bug. Some related issues with `.before` and `.after`:

``` r
library(tidyverse)

tibble(x = 1) %>% relocate(x, .before = any_of("a"))
#> Warning in min(unname(tidyselect::eval_select(.before, .data))): no non-missing
#> arguments to min; returning Inf
#> Error in seq.int(from, to): 'to' must be a finite number
tibble(x = 1) %>% relocate(x, .after = any_of("a"))
#> Warning in max(unname(tidyselect::eval_select(.after, .data))): no non-missing
#> arguments to max; returning -Inf
#> Error in seq.int(from, to): 'from' must be a finite number
```

<sup>Created on 2022-01-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think we need to slightly tweak the logic of `relocate()` to better handle the case of empty selections. `.before = <empty-selection>` should probably be the same as `.before = NULL`, same with `.after`. This means if want to relocate columns before/after "nothing" then they end up at the front of the data frame, which is consistent with what `relocate(data, cols)` does.
