### ISSUE TITLE
rowwise, mutate, and sum multiple columns gives inexplicably wrong result sometimes

### ISSUE THREAD

**Issue by jcutlerbiostats** [tidyverse/dplyr#6168]
---

If I sum multiple columns rowwise, the result is bizarrely wrong sometimes. See example below

```r
df <- tibble(
  x = c(1,2,0,1),
  y = c(0,1,3,2),
  z = c(0,0,3,0)
)

df %>% 
  rowwise() %>% 
  mutate(
    row_total = sum(x:z)
  )
```

The column 'row_total' is correct for rows 1 through 3. Shockingly, though, row 4 of row_total should say 3, but it says 1. This clearly makes no sense, right?

rowSums() gives the output I expect. Row 4 now says 3, as it should. 

```r
df %>% 
  rowSums() %>% 
  as_tibble()
```

**Comment by perlatex** [comment]
```r
library(dplyr)
df <- tibble(
  x = c(1,2,0,1),
  y = c(0,1,3,2),
  z = c(0,0,3,0)
)

df %>% 
  rowwise() %>% 
  mutate(
    row_total = sum(c_across(x:z))
  )
```

**Comment by eutwt** [comment]
In that code, `x:z` is not within a function that accepts tidy-select, so it behaves like base R and results in output the same as `seq(x, z)`.

``` r
x <- 1
y <- 2
z <- 0

x:z
#> [1] 1 0
sum(x:z)
#> [1] 1
```

<sup>Created on 2022-01-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

You can check that this is happening by using `print`

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  x = c(1,2,0,1),
  y = c(0,1,3,2),
  z = c(0,0,3,0)
)

df %>% 
  rowwise() %>% 
  mutate(
    row_total = sum(print(x:z))
  )
#> [1] 1 0
#> [1] 2 1 0
#> [1] 0 1 2 3
#> [1] 1 0
#> # A tibble: 4 × 4
#> # Rowwise: 
#>       x     y     z row_total
#>   <dbl> <dbl> <dbl>     <int>
#> 1     1     0     0         1
#> 2     2     1     0         3
#> 3     0     3     3         6
#> 4     1     2     0         1
```

<sup>Created on 2022-01-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jcutlerbiostats** [comment]
Thank you! That resolves the issue perfectly. I feel like I don't know dplyr nearly as well as I thought I did! Time for me to do a little more homework before posting an issue.
