### ISSUE TITLE
Suggested addition to "Programming with dplyr" vignette: `as.character(substitute())` to refer to quoted column name in a function

### ISSUE THREAD

**Issue by tedmoorman** [tidyverse/dplyr#6174]
I experienced some difficulty trying to refer to a quoted column name within a function. [Please see this stackoverflow post.](https://stackoverflow.com/questions/70963235/refer-to-quoted-column-name-in-a-function-in-r). 

Sebastian Krantz proposed a good solution with `as.character(substitute())`. Including something about this in the "Programming with dplyr" vignette could help those who encounter a similar problem.

Thank you for considering and for all your work on an excellent package!

**Comment by DavisVaughan** [comment]
The examples and solutions there are strictly about the collapse package, which the author mentioned only uses base R NSE, so I don't think that would be applicable in a dplyr vignette

**Comment by tedmoorman** [comment]
Yes, you're correct, as I now recognize. The reference I need is here: http://adv-r.had.co.nz/Computing-on-the-language.html.
