### ISSUE TITLE
Feature requested: multiple assignments in case_when statements 

### ISSUE THREAD

**Issue by chumbleycode** [tidyverse/dplyr#6180]
In SQL one can assign multiple variables - say var1 and var2 - when a given case is verified, with a construction like

case when condition then var1 = x, var2 = y

Pretty please can dplyr::case_when (or anything else in the tidyverse) support this useful feature one day?

The relates to my question and answers on stackexchange here https://stackoverflow.com/questions/71023157/can-i-make-multiple-assignments-within-a-given-case-when-true-clause/

**Comment by DavisVaughan** [comment]
This would be resolved by https://github.com/tidyverse/dplyr/pull/6145, so I'm going to close. We definitely have this on our radar
