### ISSUE TITLE
Confusing error in `count`

### ISSUE THREAD

**Issue by Moohan** [tidyverse/dplyr#6182]
When you mis-specify the name of the variable in `count`, the error thrown is by actually by `group_by`. This is confusing, especially for new R users who may not realise that `count` is a shorthand for `group_by` `summarise(n = n()` ...

Current error:
```r
> library(tidyverse)
> tibble(group = c(1,1,2,2,3,3),
+        value = c(1,1,1,1,1,1)) %>% 
+   count(groups)
Error in `group_by()`:
! Must group by variables found in `.data`.
x Column `groups` is not found.
Run `rlang::last_error()` to see where the error occurred.
```

Ideal error:

```r
> library(tidyverse)
> tibble(group = c(1,1,2,2,3,3),
+        value = c(1,1,1,1,1,1)) %>% 
+   count(groups)
Error in `count()`:
! Must group by variables found in `.data`.
x Column `groups` is not found.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by hadley** [comment]
Reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = 1)
df |> count(y)
#> Error in `group_by()`:
#> ! Must group by variables found in `.data`.
#> x Column `y` is not found.
```

<sup>Created on 2022-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I'm not sure it's going to be worth fixing this, but we should at least take a look.

**Comment by hadley** [comment]
I've taken a look and I don't see any obvious way to make it better, that doesn't either add a bunch of overhead, or hit one of the weird `count()` edge cases.
