### ISSUE TITLE
between function bug for datetime/date mix

### ISSUE THREAD

**Issue by abdellah19jan** [tidyverse/dplyr#6183]
`between(ymd_hms("2022-02-15 00:00:00"), ymd("2022-02-01"), ymd("2022-02-28"))`
Returns FALSE
`between(as_date(ymd_hms("2022-02-15 00:00:00")), ymd("2022-02-01"), ymd("2022-02-28"))`
Returns TRUE

**Comment by hadley** [comment]
Reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

jan1 <- as.Date("2022-01-01")
jan2 <- as.Date("2022-01-02")
jan3 <- as.Date("2022-01-03")

between(jan2, jan1, jan3)
#> [1] TRUE
between(as.POSIXct(jan2), jan1, jan3)
#> [1] FALSE
```

<sup>Created on 2022-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
