### ISSUE TITLE
`slice_sample()` errors if `n` bigger than number of rows

### ISSUE THREAD

**Issue by swannyy14** [tidyverse/dplyr#6185]
In the man page for `slice` functions, the description for the argument `n` states:

> If n is greater than the number of rows in the group (or prop > 1), the result will be silently truncated to the group size. If the proportion of a group size does not yield an integer number of rows, the absolute value of prop*nrow(.data) is rounded down.

The output of `slice_sample` used to be the same `data.frame` (with different ordering) if `n` is higher than the number of rows, but it is now returning an error.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tmp <- data.frame(x = c(rep('a',6), rep('b',4)), y = 1:10)
print(tmp)
#>    x  y
#> 1  a  1
#> 2  a  2
#> 3  a  3
#> 4  a  4
#> 5  a  5
#> 6  a  6
#> 7  b  7
#> 8  b  8
#> 9  b  9
#> 10 b 10

tmp %>% slice_sample(n = 15)
#> Error in `slice_sample()`:
#> ! Problem while computing indices.
#> Caused by error in `sample.int()`:
#> ! cannot take a sample larger than the population when 'replace = FALSE'

tmp %>% group_by(x) %>% slice_sample(n = 15)
#> Error in `slice_sample()`:
#> ! Problem while computing indices.
#> ℹ The error occurred in group 1: x = "a".
#> Caused by error in `sample.int()`:
#> ! cannot take a sample larger than the population when 'replace = FALSE'
```

<sup>Created on 2022-02-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by romanzenka** [comment]
I had to write my own wrapper around `slice_sample`. I use it to show 5 example values to user (or less), and this update broke the functionality. I had to add extra logic to handle sampling of fewer samples than present, and also handling sampling 0 samples from data set of 0 rows...

**Comment by swannyy14** [comment]
I have the same problem. I have a package that randomly samples `n` rows from each grouping of a `data.frame`, and right now the package is failing to build do to this change. I used this function due to its handling of `n` being greater than the number of rows from each group in the `data.frame`. I hope they fix this soon.

**Comment by fegue** [comment]
This seems to be introduced on purpose because there is a test specifically for this error. The documentation however was not updated.
So my question would be: should we wait for this regression to be fixed or is it time to re-write the code?

**Comment by swannyy14** [comment]
That's interesting. I also see the test change... In that case, it seems like the change in behavior is on purpose and I'm strongly considering re-writing my own code. I hope that the description for the argument is updated so that there is no ambiguity.

**Comment by huftis** [comment]
`slice_sample() now also results in an error when `n = Inf`:

```r
> slice_sample(iris, n = Inf)
Error in `slice_sample()`:
! Problem while computing indices.
Caused by error in `sample.int()`:
! vector size cannot be infinite
Run `rlang::last_error()` to see where the error occurred.
```

This used to work, and would permute the rows, which was very useful. But we can use `prop = 1` instead.

BTW, values of `prop` > 1 now also results in an error message (this is not consistent with the documentation).

**Comment by willschulz** [comment]
Definitely need to retain the option to sample "n, or however many rows exist, whichever is smaller".  Potentially good to change it from silently doing this behavior without warning the user, but a lot of us have code that depends on the function not throwing an error in this situation

**Comment by hadley** [comment]
Regression introduced in #6172 — the PR doesn't explicitly mention this change so I suspect it's an omission, not a deliberate change.

**Comment by dtatarak** [comment]
Has this been addressed? I did not have this issue until recently, but now it is happening for me as well.

**Comment by dtatarak** [comment]
The issue is: I don't want to sample with replacement in the samples where
size > n.

If I take a random sample of 100 from samples of:

94
125
200
80

I want to get back:

94
100
100
80

With no replacement in the larger samples. This used to be how
slice_sample() behaved, but it seems to have changed for some reason.

Best,
David Tatarakis

**Comment by hadley** [comment]
@dtatarak that sometimes sampling with replacement and sometimes sampling without replacement seems ill-founded to me.

**Comment by eutwt** [comment]
I think it would make sense for all the `slice()` functions to return a data frame (or group) of the same size when you supply an argument indicating a size larger than the number of rows. `slice_sample()` is the odd one out here.

``` r
library(dplyr, warn.conflicts = FALSE)
#> Warning: package 'dplyr' was built under R version 4.1.2
df <- data.frame(a = 1)

df %>% 
  slice(1:2)
#>   a
#> 1 1

df %>% 
  slice_head(n = 2)
#>   a
#> 1 1

df %>% 
  slice_tail(n = 2)
#>   a
#> 1 1

df %>% 
  slice_min(n = 2, order_by = a)
#>   a
#> 1 1

df %>% 
  slice_max(n = 2, order_by = a)
#>   a
#> 1 1

df %>% 
  slice_sample(n = 2)
#> Error in `slice_sample()`:
#> ! Problem while computing indices.
#> Caused by error in `sample.int()`:
#> ! cannot take a sample larger than the population when 'replace = FALSE'
```

<sup>Created on 2022-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dtatarak** [comment]
I agree. Definitely not something I do generally, but I have a specific
use-case for it in my work. It's useful to have a function that says "Give
me a random sample that's this size without replacement. If there aren't
enough, just give me all of them." I can certainly do that manually, but
slice_sample() was a very convenient way of doing that within a larger
dplyr statement.

Best,
David Tatarakis

**Comment by lawalter** [comment]
Similar to @dtatarak, I also had (and still have) a use case for sampling more rows than exist in a table. I wrote a function for reducing partial duplicates down to one record, and if the records were "tied" I used `slice_sample(n = 1)` to pick one from each group randomly. If there were no duplicates, the function still operated fine. But `slice_sample()` changes broke the function and I now must use an if else wrapper to only slice if `nrow() > 0`.

**Comment by leejs-abv** [comment]
The way `n`  is documented in `slice` functions right now, this behavior in `slice_sample` looks like a bug.

> If n is greater than the number of rows in the group (or prop > 1), the result will be silently truncated to the group size.

Maybe clarifying this behavior for `slice_sample` could minimize the confusion? 
Personally, I would like `slice_sample` to return the way [dtatarak](https://github.com/dtatarak) has described - to return the original data frame with different ordering. It would also be consistent with other `slice` functions as [eutwt](https://github.com/eutwt) has described.

**Comment by hadley** [comment]
@eutwt ah that makes sense. Do you want to have a go at a PR?

**Comment by DavisVaughan** [comment]
No, but it is fixed in the development version.

**Comment by erydit** [comment]
This bug is almost a year old. When the fix would reach CRAN ? Is there any release schedule or something?

**Comment by DavisVaughan** [comment]
@erydit https://www.tidyverse.org/blog/2022/11/dplyr-1-1-0-is-coming-soon/

**Comment by eutwt** [comment]
@erydit FWIW if you need this right away and can't install the dev package, this is pretty easy to "patch" by redefining `dplyr:::sample_int`. This is of course a bad idea in general, but may be useful as a temporary fix for development while waiting for the new release.

I should probably mention I don't work at Rstudio and this hacky patch is not recommended by them I'd guess :) 

```
sample_int <- function(n, size, replace = FALSE, wt = NULL, call = caller_env()) {
  if (!replace && n < size) {
   size <- n
  }

  if (size == 0L) {
    integer(0)
  } else {
    sample.int(n, size, prob = wt, replace = replace)
  }
}

assignInNamespace('sample_int', sample_int, 'dplyr')
```
