### ISSUE TITLE
mutate() truncates output to the same number of observations as variables with "model.selection" object

### ISSUE THREAD

**Issue by pigcooker** [tidyverse/dplyr#6187]
No problems using mutate() on "model.selection" objects in version 1.0.7, but in 1.0.8, regardless of what is being done inside the mutate function, the output observations are truncated to equal the number of variables. For example, when using mutate() to add a cumsum() column to a "model.selection" object with 256 observations and 14 variables, the resulting output is only 15 observations long (with now 15 variables). Same result for several attempts with different number of variables, the output observations are truncated to the length of the number of variables. Reprex here:

``` r
library(tidyverse)
library(MuMIn)

dat <- data.frame(R1 = sample(c(0,1), 50, replace = T),
                  V1 = c(1:50),  V2 = c(51:100),
                  V3 = rep(1:2, 25), V4 = rep(1:5, 10))

dat.global.mod <- glm(R1 ~ ., data=dat, family=binomial(link=logit), na.action = "na.fail")
dat_dredge <- dredge(dat.global.mod)
#> Fixed term is "(Intercept)"

# dimensions of model.selection object
dim(dat_dredge)
#> [1] 16 10
dat_dredge <- dat_dredge %>% mutate(cumulative_weight=cumsum(weight))

# dimensions of model.selection object after mutating and adding one variable (cumulative_weight)
# now observations are truncated to equal the number of variables
dim(dat_dredge)
#> [1] 11 11
```

<sup>Created on 2022-02-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If I force the object to a data frame, it works just fine, but then I can't do any further modeling work with it.

Again, this worked fine with 1.0.7, but does this truncation behavior with 1.0.8. I don't believe this is an issue with MuMIN because that package hasn't been updated in nearly two years.

**Comment by pigcooker** [comment]
Well... I just reinstalled 1.0.7 and it still doesn't work. Something in another dependency that was updated at the same time, maybe?

**Comment by pigcooker** [comment]
Just for reference, here is the output using version 1.0.7:

``` r
library(tidyverse)
library(MuMIn)

dat <- data.frame(R1 = sample(c(0,1), 50, replace = T),
                  V1 = c(1:50),
                  V2 = c(51:100),
                  V3 = rep(1:2, 25),
                  V4 = rep(1:5, 10))

dat.global.mod <- glm(R1 ~ ., data=dat, family=binomial(link=logit), na.action = "na.fail")
dat_dredge <- dredge(dat.global.mod)
#> Fixed term is "(Intercept)"

# dimensions of model.selection object
dim(dat_dredge)
#> [1] 16 10
dat_dredge <- dat_dredge %>% mutate(cumulative_weight=cumsum(weight))

# dimensions of model.selection object after mutating and adding one variable (cumulative_weight)
# now observations are truncated to equal the number of variables
dim(dat_dredge)
#> [1] 16 11
```

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
The problem is that MuMin defines a `[.model_selection` method where `df[i]` selects rows rather than columns.

dplyr requires that if a custom `[` method is implemented, it much select columns when a single `i` is provided (just like how data.frame works already!)

``` r
library(tidyverse)
#> Warning: package 'dplyr' was built under R version 4.1.2
library(MuMIn)

dat <- data.frame(R1 = sample(c(0,1), 50, replace = T),
                  V1 = c(1:50),
                  V2 = c(51:100),
                  V3 = rep(1:2, 25),
                  V4 = rep(1:5, 10))

dat.global.mod <- glm(R1 ~ ., data=dat, family=binomial(link=logit), na.action = "na.fail")
dat_dredge <- dredge(dat.global.mod)
#> Fixed term is "(Intercept)"

dim(dat_dredge)
#> [1] 16 10

# this selects rows
# i.e. see MuMIn:::`[.model.selection`
dim(dat_dredge[1])
#> [1]  1 10
dim(dat_dredge[1:2])
#> [1]  2 10

# we expect it to select columns, like
dim(as.data.frame(dat_dredge)[1])
#> [1] 16  1
dim(as.data.frame(dat_dredge)[1:2])
#> [1] 16  2
```

Because MuMIn breaks this assumption, I do not think there is much we can do for that package.

**Comment by DavisVaughan** [comment]
FWIW it was through sheer luck that it previously worked at all. If you try to use `select()` with 1.0.7 then you will see that that also used to fail (and still does) since the `[` method doesn't meet our assumptions

``` r
library(tidyverse)
library(MuMIn)

dat <- data.frame(R1 = sample(c(0,1), 50, replace = T),
                  V1 = c(1:50),
                  V2 = c(51:100),
                  V3 = rep(1:2, 25),
                  V4 = rep(1:5, 10))

dat.global.mod <- glm(R1 ~ ., data=dat, family=binomial(link=logit), na.action = "na.fail")
dat_dredge <- dredge(dat.global.mod)
#> Fixed term is "(Intercept)"
dat_dredge
#> Global model call: glm(formula = R1 ~ ., family = binomial(link = logit), data = dat, 
#>     na.action = "na.fail")
#> ---
#> Model selection table 
#>     (Intrc)       V1       V2      V3      V4 df  logLik AICc delta weight
#> 1  -0.08004                                    1 -34.617 71.3  0.00  0.191
#> 9   0.52630                           -0.2026  2 -34.114 72.5  1.16  0.107
#> 2   0.36440 -0.01748                           2 -34.226 72.7  1.39  0.095
#> 3   1.23800          -0.01748                  2 -34.226 72.7  1.39  0.095
#> 4   0.36440 -0.01748                           2 -34.226 72.7  1.39  0.095
#> 5   0.40120                   -0.3212          2 -34.457 73.2  1.85  0.076
#> 10  0.89270 -0.01598                  -0.1893  3 -33.795 74.1  2.79  0.047
#> 11  1.69200          -0.01598         -0.1893  3 -33.795 74.1  2.79  0.047
#> 12  0.89270 -0.01598                  -0.1893  3 -33.795 74.1  2.79  0.047
#> 13  1.02200                   -0.3278 -0.2040  3 -33.950 74.4  3.10  0.041
#> 6   0.82060 -0.01722          -0.3089          3 -34.080 74.7  3.36  0.036
#> 7   1.68100          -0.01722 -0.3089          3 -34.080 74.7  3.36  0.036
#> 8   0.82060 -0.01722          -0.3089          3 -34.080 74.7  3.36  0.036
#> 14  1.36600 -0.01571          -0.3168 -0.1911  4 -33.644 76.2  4.86  0.017
#> 15  2.15200          -0.01571 -0.3168 -0.1911  4 -33.644 76.2  4.86  0.017
#> 16  1.36600 -0.01571          -0.3168 -0.1911  4 -33.644 76.2  4.86  0.017
#> Models ranked by AICc(x)

dat_dredge %>% 
  select(V1)
#> Error in `dplyr_col_select()`:
#> ! Can't reconstruct data frame.
#> x The `[` method for class <model.selection/data.frame> must return a data frame with 1 column.
#> ℹ It returned a <model.selection/data.frame> of 10 columns.
```

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by pigcooker** [comment]
Interesting note about how MuMIn defines the object - I never noticed that. I suppose I'm curious then, is that dplyr requirement new to version 1.0.8 since it works correctly in 1.0.7?

**Comment by DavisVaughan** [comment]
I think we commented at exactly the same time but regarding:

> is that dplyr requirement new to version 1.0.8 since it works correctly in 1.0.7?

see https://github.com/tidyverse/dplyr/issues/6187#issuecomment-1040633706. No it isn't a new requirement, it was just pure luck that this particular call to `mutate()` looked like it was working correctly. Many other dplyr verbs would have failed in 1.0.7 too

**Comment by pigcooker** [comment]
Got it. Very helpful, thank you. I've found another (slightly sloppier) way to do what I want to do, but it'll hopefully not be subject to pure luck and actually be reproducible for future runs.

Thanks!
