### ISSUE TITLE
bang-bang operator does not work with constants having length >1 in grouped dataframes

### ISSUE THREAD

**Issue by rich-payne** [tidyverse/dplyr#6188]
When using a `mutate()` statement on a grouped dataframe, using the `!!` operator for a constant of an appropriate length greater than 1 throws an error in version 1.0.8, but, not using the `!!` operator works.  This is a break from previous versions.

I first noticed the break moving from version 1.0.7 to 1.0.8, and, it appears it is still happening in the 1.0.8.9000.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '1.0.2'

y <- c(1, 2)

# works with y and !!y
data.frame(x = c("a", "a", "b", "b")) %>%
  group_by(x) %>%
  mutate(numbers = y)
#> # A tibble: 4 × 2
#> # Groups:   x [2]
#>   x     numbers
#>   <chr>   <dbl>
#> 1 a           1
#> 2 a           2
#> 3 b           1
#> 4 b           2

data.frame(x = c("a", "a", "b", "b")) %>%
  group_by(x) %>%
  mutate(numbers = !!y)
#> # A tibble: 4 × 2
#> # Groups:   x [2]
#>   x     numbers
#>   <chr>   <dbl>
#> 1 a           1
#> 2 a           2
#> 3 b           1
#> 4 b           2

detach("package:dplyr", unload = TRUE)
library(dplyr, lib.loc = "../../Rlib_trashme")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '1.0.8.9000'
packageDescription("dplyr")$RemoteSha
#> [1] "dd9a3b8be98c6e12bc15d7057e29a571ceab9215"

# works with y
data.frame(x = c("a", "a", "b", "b")) %>%
  group_by(x) %>%
  mutate(numbers = y)
#> # A tibble: 4 × 2
#> # Groups:   x [2]
#>   x     numbers
#>   <chr>   <dbl>
#> 1 a           1
#> 2 a           2
#> 3 b           1
#> 4 b           2

# does not work with !!y
data.frame(x = c("a", "a", "b", "b")) %>%
  group_by(x) %>%
  mutate(numbers = !!y)
#> Error in `mutate()`:
#> ! Problem while computing `numbers = <dbl>`.
#> Inlined constant `numbers` must be size 4 or 1, not 2.
```

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = c("a", "a", "b", "b")) 
y <- c(1, 2)

df %>%
  group_by(x) %>%
  mutate(numbers = y)
#> # A tibble: 4 × 2
#> # Groups:   x [2]
#>   x     numbers
#>   <chr>   <dbl>
#> 1 a           1
#> 2 a           2
#> 3 b           1
#> 4 b           2

df %>%
  group_by(x) %>%
  mutate(numbers = !!y)
#> Error in `mutate()`:
#> ! Problem while computing `numbers = <dbl>`.
#> Inlined constant `numbers` must be size 4 or 1, not 2.
```

<sup>Created on 2022-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It seems like the value is being inserted ignoring grouping?

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = c("a", "a", "b", "b")) 
y <- 1:4
df %>%
  group_by(x) %>%
  mutate(numbers = !!y)
#> # A tibble: 4 × 2
#> # Groups:   x [2]
#>   x     numbers
#>   <chr>   <int>
#> 1 a           1
#> 2 a           2
#> 3 b           3
#> 4 b           4
```

<sup>Created on 2022-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
Introduced here https://github.com/tidyverse/dplyr/pull/6056 so maybe @lionel- remembers why this was added (there is even a test that is similar to this example that we are "expecting" to error)

**Comment by lionel-** [comment]
Previously, injecting constants in grouped data frame would only work in the very specific case of identical lengths in all groups.

Now, we can use injection to to bypass the evaluation phase, which is useful for metaprogramming, especially when injecting a whole data frame with `!!!`. See the _transmute() as a data-mask to selection bridge_ section in https://rlang.r-lib.org/reference/topic-data-mask-programming.html#transmute-as-a-data-mask-to-selection-bridge

**Comment by lionel-** [comment]
@rich-payne To force grouped evaluation you can use `.env$myvar`.

**Comment by hadley** [comment]
@lionel- oh yeah, that makes sense.

**Comment by rich-payne** [comment]
Thanks @lionel-, the `.env$y` certainly does the trick (I was aware of `.data`, but not `.env`).  I had been using the `!!` as a surrogate for `.env`.

Is `!!` or `.env` generally preferred over the other?
