### ISSUE TITLE
Source table names are not preserved using "join"

### ISSUE THREAD

**Issue by JonAnCla** [tidyverse/dplyr#619]
I've tried to generalise the problem as pseudo code below...

Say I have three tables in my database: Type, and SubType, and Object

Type:
    id = primary key
    name = string

SubType:
    id = primary key
    name = string

Object:
    id = primary key
    type_id = foreign key to Type
    subtype_id = foreign key to SubType
    value = int

I'd like to left join Object to SubType and Type to get a flat table with the fields:
type.name
subtype.name
value

If I try to do this using dplyr, then I end up with a table that looks something like:
x.name
y.name
value

Now imagine I want to do many more joins with other tables, and you'll see that there's no way of telling from the results which variables come from which tables, and in fact the x andy prefixes are re-used no matter how many joins I make, so dplyr ends up crashing if I try to join onto a third table with a name attribute, because x.name and/or y.name have already been used as attribute names.

Hope that makes sense!

**Comment by gwerbin** [comment]
Shouldn't this be fairly straightforward for `tbl_sql`s? The table name is always going to be in `tbl_sql$from`.
