### ISSUE TITLE
`filter` behavior change with respect to empty arguments

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidyverse/dplyr#6191]
A coworker and I were observing different behavior when using `filter` with an empty argument.  My version (1.0.2) produced an error, but 1.0.7 (and 1.0.8) succeed.

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.0.5
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

mtcars %>% filter(,mpg< 1)
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 rows> (or 0-length row.names)
```

I didn't see anything in the change notes indicating this behavior change, and it seems related to #5925 .

**Comment by DavisVaughan** [comment]
It looks like it was introduced around 1.0.6 with https://github.com/tidyverse/dplyr/pull/5857

CC @lionel- it looks like this was unintentional (previously `filter_rows()` used `enquos(...)`, but here it switched to `dplyr_quosures()` which uses `enquos(..., .ignore_empty = "all")`), but do you have any thoughts on the behavior here? It might be good to be consistent across all of dplyr here, and it probably makes sense to ignore empty dots (i.e. the new behavior is right and more consistent)

**Comment by lionel-** [comment]
I agree consistency would be good, but I don't really have a sense of which behaviour is better for dplyr.

**Comment by hadley** [comment]
I think this is correct; we generally ignore empty arguments.
