### ISSUE TITLE
allow arrange() to accept NULL argument

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/dplyr#6193]
When programming with `dplyr`, it can be handy to pass `NULL` as a value.

For instance when using `group_by()`, I can pass `NULL` when I want to use my custom function but I don't want to group on any variable.

However, while `group_by()` allow this syntax, `arrange()` throws an unexpected error:

``` r
dplyr::group_by(iris, NULL)[1,]
#> # A tibble: 1 x 5
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#> 1          5.1         3.5          1.4         0.2 setosa
dplyr::arrange(iris, NULL)[1,]
#> Error in mapply(.f, .x, .y, MoreArgs = list(...), SIMPLIFY = FALSE): zero-length inputs cannot be mixed with those of non-zero length
```

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This might be related to https://github.com/tidyverse/dplyr/issues/6093.

**Comment by hadley** [comment]
Looks like this has been fixed:

``` r
df <- dplyr::arrange(mtcars, NULL)
```

<sup>Created on 2022-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But there's a new bug if you mix `NULL` with other variables:

``` r
df <- dplyr::arrange(mtcars, NULL, am)
#> Error: `direction` should have length 1 or length equal to the number of columns of `x` when `x` is a data frame.
```

<sup>Created on 2022-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
A correct solution should handle both of these cases:

``` r
df <- dplyr::arrange(mtcars, NULL, am)
#> Error: `direction` should have length 1 or length equal to the number of columns of `x` when `x` is a data frame.

x <- NULL
df <- dplyr::arrange(mtcars, x, am)
#> Error: `direction` should have length 1 or length equal to the number of columns of `x` when `x` is a data frame.
```
