### ISSUE TITLE
summarize does not work but summarise does

### ISSUE THREAD

**Issue by pseudorational** [tidyverse/dplyr#6195]
For one of my students summarize (with a z) throws up an error but not summarise (with an s). I cannot reproduce the error on my installation of R. We have the same versions of R and dplyr. He is an American student with a computer set to American English. 

Strangely enough, when he went on to create a reprex, summarize (with a z) worked!

I have never seen this error before. 

```r
mtcars %>% summarize(mean(mpg))

Warning in mean.default(mpg) :
  argument is not numeric or logical: returning NA
Error in FUN(X, ...) : argument "FUN" is missing, with no default


mtcars %>% summarise(mean(mpg))

  mean(mpg)
1  20.09062
```

**Comment by DavisVaughan** [comment]
I have a feeling they had something else in their environment that conflicted with `summarize()`, but not with `summarise()`. The fact that everything works fine in a reprex is highly suggestive of this. I am fairly certain nothing is actually wrong in dplyr, so I'm going to close, but feel free to add an additional comment if you have more evidence of an issue
