### ISSUE TITLE
performance issue with recode on character column

### ISSUE THREAD

**Issue by ericemc3** [tidyverse/dplyr#6196]
mutate + recode on a character column is much slower (40x) than the same operation on a factor column,
even compared to as.character(recode(factor(...),....)) 

```r
library(microbenchmark)
library(tidyverse)

l50 <- c(letters[1:25], LETTERS[1:25])
n <- 1000000

at <- tibble(
  id  = seq(1, n),
  str = rep(l50, n/50)
)

recode_list <- as.list(setNames(str_c("xxx", l50), l50))

microbenchmark(
  recode_char     = at %>% mutate(str = recode(str, !!!recode_list)),
  recode_fct      = at %>% mutate(str = recode(factor(str), !!!recode_list)),
  recode_fct_char = at %>% mutate(str = as.character(recode(factor(str), !!!recode_list))),
  times = 10
)
```
![image](https://user-images.githubusercontent.com/17407796/155575938-2eaee285-c425-404d-9eea-710096a9a70f.png)

**Comment by hadley** [comment]
This isn't surprising because we only need to recode the levels of a factor, not ever element like for a character vector.

**Comment by ericemc3** [comment]
i disagree, my point here is that my 'recode_char' is way too slow.

'recode_fct' is not just about recoding the levels of a factor, it is converting strings to factors first, then recoding them.

'recode_fct_char' produces exactly the same result that 'recode_char', but is 30 x faster : it is my workaround to cope with what i think is a performance issue with recode.
