### ISSUE TITLE
n_distinct is not calculating distinct counts accurately for integer64 datatype 

### ISSUE THREAD

**Issue by Shirrang** [tidyverse/dplyr#6197]
Hi, below is the reproducible example where it shows n_distinct is not calculating the counts accurately . Please take a look . Thanks 

 library(bit64)
 library(dplyr)
 x = as.integer64(-20:20 * 10^9)
 #x
 n_distinct(x)
#[1] 2
 length(unique(x))
#[1] 41

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by DavisVaughan** [comment]
This was fixed in the dev version of vctrs by https://github.com/r-lib/vctrs/pull/1378, which should be sent to CRAN in a few weeks or less
