### ISSUE TITLE
slice_sample does not allow for slicing unique elements

### ISSUE THREAD

**Issue by deschen1** [tidyverse/dplyr#6198]
Not entirely sure if I just don't find it, but `slice_sample` does not support sampling from the unique values of a column (like the `sample` function would do).

Let's assume I have the following data and would want to randomly filter the data on 2 of the 5 unique x values.

```
df <- data.frame(x = rep(1:5, 3))

# works
library(tidyverse)
df %>%
  filter(x %in% sample(unique(x), size = 2, replace = FALSE))

# does not work
df %>%
  slice_sample(???)
```

**Comment by eutwt** [comment]
Similar to the slice-by-group idea discussed in https://github.com/tidyverse/dplyr/issues/5965

Using functions in @romainfrancois' comment

``` r
group_slice_fn <- function(fn) {
  function(.data, ...) {
    group_keys(.data) %>% 
      fn(...) %>% 
      right_join(.data, .)
    
  }
}
group_slice_sample <- group_slice_fn(slice_sample)

library(dplyr, warn.conflicts = FALSE)

df <- data.frame(x = rep(1:5, 3))

df %>% 
  group_by(x) %>% 
  group_slice_sample(n = 2) %>% 
  ungroup()
#> Joining, by = "x"
#> # A tibble: 6 × 1
#>       x
#>   <int>
#> 1     1
#> 2     5
#> 3     1
#> 4     5
#> 5     1
#> 6     5
```

<sup>Created on 2022-02-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by deschen1** [comment]
Thanks for providing this workaround. Just to prevent confusion, does this mean the provided custom function is the closest I could get to implement this in my code or does it mean that there might (or might not) be such a built-in function in dplyr at some point?

**Comment by eutwt** [comment]
Sorry, should've been more clear. I'm not a dplyr developer so I don't know the answer. I just wanted to link to the past issue so that if there is a desire for something like this at some point, related discussions and comments are all together in one place.

**Comment by hadley** [comment]
`slice_sample()` works with rows, so I'm not sure what sampling by unique values of individual variables could mean here. I'd suggest continuing to use a grouped filter.
