### ISSUE TITLE
Error message for `select()` when column doesn't exist

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#6200]
See below for a reprex for selecting a column that doesn't exist:

``` r
library(dplyr)

df <- tibble(x = 1:2, y = 3:4)
df
#> # A tibble: 2 × 2
#>       x     y
#>   <int> <int>
#> 1     1     3
#> 2     2     4
df %>% select(z)
#> Error in `stop_subscript()`:
#> ! Can't subset columns that don't exist.
#> x Column `z` doesn't exist.
```

<sup>Created on 2022-02-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think the error should say `Can't select columns that don't exist` since `subset` is not the verb used in the code, and it actually means `filter()` in base R.

**Comment by hadley** [comment]
It now says

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = 1:2, y = 3:4)
df %>% select(z)
#> Error in `select()`:
#> ! Can't subset columns that don't exist.
#> ✖ Column `z` doesn't exist.
```

<sup>Created on 2022-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Which I think is about as good as we can get, without customising the underlying vctrs error which would be a lot of work, for relatively little gain, IMO.

**Comment by DavisVaughan** [comment]
This might not be that hard actually. tidyselect is already renaming it to `subset` and `columns` for us:

``` r
tidyselect:::with_subscript_errors
#> function (expr, type = "select", call = caller_env()) 
#> {
#>     tryCatch(expr, vctrs_error_subscript = function(cnd) {
#>         cnd$subscript_action <- subscript_action(type)
#>         cnd$subscript_elt <- "column"
#>         cnd_signal(cnd)
#>     })
#> }
#> <bytecode: 0x7f7dbd5df4f0>
#> <environment: namespace:tidyselect>
```

``` r
tidyselect:::subscript_action
#> function (type) 
#> {
#>     switch(validate_type(type), select = "subset", rename = "rename", 
#>         pull = "extract")
#> }
#> <bytecode: 0x7f7ddc4e69e0>
#> <environment: namespace:tidyselect>
```

So maybe tidyselect should say `select = "select"` here rather than `select = "subset"`? @lionel- what do you think?

**Comment by lionel-** [comment]
That sounds good. We'll need a change in both vctrs and tidyselect, I've opened issues.

**Comment by hadley** [comment]
FWIW I stand by my original comment that this is more trouble than its worth. Having to change three packages in concert to modify a single word in an error message that is already pretty good doesn't feel like a great payoff to me.

**Comment by DavisVaughan** [comment]
Fine by me
