### ISSUE TITLE
Helper for numeric sorting?

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#6208]
Something like `stringi::stri_rank(measure_cd, list(numeric = TRUE))` ? Might be possible now that we have a weak dependency on stringi for the locale stuff.

Like `desc()` is a wrapper for `xtfrm()`.

**Comment by DavisVaughan** [comment]
At one point we considered allowing `arrange(.locale = list(numeric = TRUE, locale = "en_US"))`, i.e. a list of named collator options https://github.com/tidyverse/tidyups/issues/11#issuecomment-889150085

But I think we decided against it for now to keep the scope narrow

**Comment by hadley** [comment]
Yeah, I was thinking more like:

```R
num <- function(x) {
  check_installed("stringi")
  stringi::stri_rank(measure_cd, list(numeric = TRUE))
}
```

Needs a better name though.

**Comment by hadley** [comment]
On balance, I think pointing people towards `stringr::str_rank()` is probably a better solution.
