### ISSUE TITLE
`relocate.data.frame()` shouldn't rely on `vec_unique()` retaining names

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#6209]
Currently, `relocate()` relies on the fact that `vec_unique()` keeps names
https://github.com/tidyverse/dplyr/blob/8abb54b60e40ef7c619156a12b14872cb2eb7989/R/relocate.R#L83-L85

We think we should actually drop names from the result of `vec_unique()`, since the returned names are reliant on the fact that only the _first_ encountered duplicate value is returned (this is also consistent with `unique()`). See https://github.com/r-lib/vctrs/issues/1442 and https://github.com/r-lib/vctrs/pull/1532 where we tried to implement this, but found that dplyr relies on this behavior currently.

---

One easy way to fix this is to use `vec_unique_loc()` to get the locations, and then `vec_slice()`, which will retain names.

That should work in the immediate term but it may be worth looking at the code to also see why we currently get names off the unique values, and if there is something else we should be doing instead, since that _feels_ unreliable.

**Comment by eutwt** [comment]
The `lhs` and `rhs` in `c(lhs, to_move, rhs)` are already unique, and neither contain any elements in `to_move`.  So, the only effect of `vec_unique` is to make `to_move` unique. The only time `to_move` is not unique is when the user supplies the same column twice with different names (if they supply the same column twice with no name or the same name, `eval_select` would give a unique output). 

So, the only thing `vec_unique` does here is silently prevent users from creating copies of columns with `relocate`. Maybe there should be a check for this up front with an error that copying columns using `relocate` is not supported?

```r
df <- tibble(a = 1, b = 2)

#### current behavior
df %>% 
  relocate(new = b, new2 = b)
# # A tibble: 1 × 2
#     new     a
#   <dbl> <dbl>
# 1     2     1

#### no `vec_unique()` i.e. `pos` defined as `pos <- c(lhs, to_move, rhs)`
df %>% 
  relocate(new = b, new2 = b)
# # A tibble: 1 × 3
#     new  new2     a
#   <dbl> <dbl> <dbl>
# 1     2     2     1

```
