### ISSUE TITLE
Select, rename, mutate, etc. for lists?

### ISSUE THREAD

**Issue by anthonynorth** [tidyverse/dplyr#6212]
Are there any plans for supporting lists in dplyr manipulation functions? If so, are you accepting PRs?
I would like to delete [this code](https://github.com/anthonynorth/rdeck/blob/master/R/utils-dplyr.R) and instead use dplyr.

Edit: updated link

**Comment by hadley** [comment]
This is out of scope for dplyr, sorry, as it focusses exclusively on data frames.
