### ISSUE TITLE
varying samples sizes in slice_sample across groups

### ISSUE THREAD

**Issue by mfakaehler** [tidyverse/dplyr#6213]
---
I would like to humbly suggest the following feature, totally aware that you cannot design functions to everyones needs:

sample_n used to support size-arguments that differ across groups. slice_sample does not. In usecases for at least three organisations I found this feature quite useful, as taking stratified samples with varying sample-sizes was often required. This keeps me from adapting to the new slice_sample. Would you kindly consider adding this feature to slice_sample?
Thank you very much!

```r
library(dplyr)
library(palmerpenguins)

# currently not supported:
penguins %>% 
  mutate(n_samples = case_when(
    year == 2007 ~ 3L,
    year == 2008 ~ 2L,
    year == 2009 ~ 4L,
    TRUE ~ 0L
  )) %>% 
  group_by(year) %>%
   slice_sample(n = n_samples) # formerly sample_n(size = n_samples)
```
Error in `check_constant()`:
! `n` must be a constant in `slice_sample()`

**Comment by hadley** [comment]
I think unfortunately it would be very difficult to support this in the new `slice_sample()` functions because it was one of the features that made `sample_n` so hard to implement correctly.
