### ISSUE TITLE
is it better to warn when change the factor levels in group_df?

### ISSUE THREAD

**Issue by Yunuuuu** [tidyverse/dplyr#6216]
Sometimes we may think `group_df` is like a unified but separate ~~data.frame~~ (like a `list-data.frame`), where we mistake to change factor levels in the different group of this data. 

There're some questions in `stackoverflow`:
-https://stackoverflow.com/questions/57696639/reorder-factor-levels-within-group
-https://stackoverflow.com/questions/53698444/reorder-factor-not-working-on-grouped-data

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
df <- tibble::tibble(
    afct = factor(rep(c("f1", "f2"), times = 2), levels = c("f1", "f2")),
    group = rep(c("a", "b"), each = 2),
    weight = c(1, 2, 2, 1)
)

# we mistate to do this:
df %>%
    dplyr::group_by(group) %>%
    dplyr::mutate(
        bfct = forcats::fct_reorder(afct, weight)
    ) %>%
    dplyr::pull(bfct)
#> [1] f1 f2 f1 f2
#> Levels: f1 f2

# what we need is like this: 
df %>%
    dplyr::group_by(group) %>%
    dplyr::group_split() %>%
    lapply(function(x) {
        x %>%
            dplyr::mutate(
                bfct = forcats::fct_reorder(afct, weight)
            ) %>%
            dplyr::pull(bfct)
    })
#> [[1]]
#> [1] f1 f2
#> Levels: f1 f2
#> 
#> [[2]]
#> [1] f1 f2
#> Levels: f2 f1
```

<sup>Created on 2022-03-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I think we have considered warning here in the past, but ultimately decided that it would create more problems than it solved.
