### ISSUE TITLE
Behaviour for duplicates in left/right Joins

### ISSUE THREAD

**Issue by l-gorman** [tidyverse/dplyr#6220]
# Description 

When conducting a left join or a right join, if there are multiple matches, then extra rows are added to the dataset (see example below). While I completely appreciate that it is sensible for new rows to be created, having spoken to colleagues that use this feature, many are not aware that the joins behave in this way, and this 

# Reproducible Example

```r
library(dplyr)
library(tibble)
library(magrittr)

left_df <- tibble::as_tibble(
    list(
        name = c("john", "lisa", "mark", "connor", NA),
        income = c(1000, 2000, 100000, 50, NA)
    )
)

right_df <- tibble::as_tibble(
    list(
        name = c("john", "lisa", "mark", "mark", NA),
        outgoings = c(300, 600, 20000, 10, NA)
    )
)

left_df %>% dplyr::left_join(right_df, by=c("name"="name"))
```

This gives the following output:
```
# A tibble: 6 x 3
  name   income outgoings
  <chr>   <dbl>     <dbl>
1 john     1000       300
2 lisa     2000       600
3 mark   100000     20000
4 mark   100000        10
5 connor     50        NA
6 NA         NA        NA
```
# Suggested Solution

I was going to try and add a simple warning/message to make it clear how these joins are behaving, something along the lines of:

``` r
warning("Multiple matches between left and right dataframe, new rows being created in left df.")
```
I just wanted to check whether this is something that would be useful to others before I start working on it. I hope that makes sense! Thanks for all of the work on this package, it has been so useful for me, I'd love an opportunity to help in any way I can! 😄

**Comment by DavisVaughan** [comment]
If you read through https://github.com/tidyverse/dplyr/pull/5910, particularly the `multiple` argument, I think you'll see that we are planning to cover this in the next big release of dplyr!

**Comment by l-gorman** [comment]
Ah great, I just looked through it! Thanks 🙂 Sorry for the pointless issue!
