### ISSUE TITLE
Using .after or .before within across

### ISSUE THREAD

**Issue by deschen1** [tidyverse/dplyr#6223]
With `across`, we can perform computations on several columns at the same time. However, the `.after` argument in `mutate` is outside of `across`, which means I can't handle the location of newly created columns individually. I can only put them in bulk either before or after a certain position.

Ideally, the `.after` or `.before` argument would run on each new column within across.

```
df <- data.frame(x = 1, y = 2, z = 3)

df |>
  dplyr::mutate(dplyr::across(tidyselect::everything(), ~ . + 1, .names = "{.col}_new"))
```

This puts all new columns at the end of `df`. However, what would make sense in many case is to put the new columns behind the original ones, i.e. expected output would be:

```
# A tibble: 1 x 6
      x x_new     y y_new     z z_new
  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1     1     2     2     3     3     4
```

**Comment by DavisVaughan** [comment]
I appreciate the idea, but I think that using .before/.after to interleave multiple columns at once like that is a bit out of scope for what it is trying to do
