### ISSUE TITLE
group_by needs across for all_of

### ISSUE THREAD

**Issue by olivroy** [tidyverse/dplyr#6226]
This syntax used to work. (Maybe this issue does not belong here, since this might be caused by tidyselect or vctrs)

 I know you can use `across()` to solve the problem.

I feel like this is not that clear in the `group_by()` documentation

``` r
library(dplyr, warn.conflicts = FALSE)
mtcars |> group_by(all_of(c("vs", "am")))
#> Error in `group_by()`:
#> ! Problem adding computed columns.
#> Caused by error in `mutate()`:
#> ! Problem while computing `..1 = all_of(c("vs", "am"))`.
#> x `..1` must be size 32 or 1, not 2.

# This works

mtcars |> group_by(across(all_of(c("vs", "am"))))
```

<sup>Created on 2022-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by anthonynorth** [comment]
`tidyselect::all_of()` takes a single arg, so you'll need to do something like this:

``` r
library(dplyr, warn.conflicts = FALSE)
mtcars |> group_by(across(all_of(c("vs", "am"))))
#> # A tibble: 32 x 11
#> # Groups:   vs, am [4]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # ... with 22 more rows
```

<sup>Created on 2022-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by olivroy** [comment]
You are right, I updated my reprex. 

Thanks!

**Comment by hadley** [comment]
I don't think this was ever supposed to work, so if it previously worked it was by accident.

**Comment by joeramirez** [comment]
I came across this in my code recently and wonder if it would be a good idea to throw an error when using all_of with group_by without across.  I'm 99% sure my code used to work fine that way (even if by accident) and I only recently realized that my code was incorrectly calculating some data without throwing any error.  Here's an example of it happening using dplyr 1.1.0.  Both dfgp and dfgp2 run without error and produce a technically viable output but dfgp is not the intended result (dfgp is correct though):

```
library(dplyr)
df <- data.frame(
  category = rep(letters[1:5], each = 5),
  color = rep(c("RED", "GRN", "BLU", "YLO", "ORG"), 5),
  value = rep(1:5, 5),
  stringsAsFactors = F
)

myCol <- "color"

dfgp <- df %>%
  group_by(all_of(myCol)) %>%
  mutate(csum = cumsum(value))

dfgp2 <- df %>%
  group_by(across(all_of(myCol))) %>%
  mutate(csum = cumsum(value))
```
