### ISSUE TITLE
Joins by date fail when one is `Date` and one is `IDate`

### ISSUE THREAD

**Issue by rmcd1024** [tidyverse/dplyr#6230]
A `left_join` fails when joining by `Date` = `IDate`. I believe this merge should work. Failing that, the error message needs to be improved. Several things:

1. Both `Date` and `IDate` variables are of class `Date`. I presume the problem occurs because `IDate` is mode integer while `Date` is numeric but not integer.
2. This join works fine with the base `merge` function
3. The `dplyr` error message is incomprehensible since it doesn't describe the reason the join fails.

```r
x1df = data.table::fread("date, data1\n2022-04-01, 5")
x2df = tibble::tribble(~ date, ~ data2,
                      as.Date('2022-04-01'), 6)
test1 = merge(x1df, x2df, by='date')  ## works
test1 
#>          date data1 data2
#> 1: 2022-04-01     5     6
test2 = dplyr::left_join(x1df, x2df, by='date')  ## fails
#> Error in `dplyr::left_join()`:
#> ! Can't join on `x$date` x `y$date` because of incompatible types.
#> ℹ `x$date` is of type <date>>.
#> ℹ `y$date` is of type <date>>.
xfun::session_info()
#> R version 4.1.3 (2022-03-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.2 LTS
#> 
#> Locale:
#>   LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>   LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>   LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>   LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>   LC_ADDRESS=C               LC_TELEPHONE=C            
#>   LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> Package version:
#>   assertthat_0.2.1  base64enc_0.1.3   bslib_0.3.1       callr_3.7.0      
#>   cli_3.2.0         clipr_0.8.0       compiler_4.1.3    crayon_1.5.1     
#>   data.table_1.14.2 DBI_1.1.2         digest_0.6.29     dplyr_1.0.8      
#>   ellipsis_0.3.2    evaluate_0.15     fansi_1.0.3       fastmap_1.1.0    
#>   fs_1.5.2          generics_0.1.2    glue_1.6.2        graphics_4.1.3   
#>   grDevices_4.1.3   highr_0.9         htmltools_0.5.2   jquerylib_0.1.4  
#>   jsonlite_1.8.0    knitr_1.38        lifecycle_1.0.1   magrittr_2.0.3   
#>   methods_4.1.3     pillar_1.7.0      pkgconfig_2.0.3   processx_3.5.3   
#>   ps_1.6.0          purrr_0.3.4       R6_2.5.1          rappdirs_0.3.3   
#>   reprex_2.0.1      rlang_1.0.2       rmarkdown_2.13    rstudioapi_0.13  
#>   sass_0.4.1        stats_4.1.3       stringi_1.7.6     stringr_1.4.0    
#>   tibble_3.1.6      tidyselect_1.1.2  tinytex_0.38      tools_4.1.3      
#>   utf8_1.2.2        utils_4.1.3       vctrs_0.4.0       withr_2.5.0      
#>   xfun_0.30         yaml_2.3.5
```
Finally, given the growing integration between `tidyverse` and `data.table`, I think this will become an increasingly common issue.

**Comment by rmcd1024** [comment]
This seems to be a long-standing issue. From 2015:  https://stackoverflow.com/questions/32082175/cant-use-dplyr-joins-on-two-date-columns

**Comment by hadley** [comment]
@DavisVaughan can you take a look at this?

Maybe the root cause is that data.table reads dates into integer vectors?

**Comment by hadley** [comment]
And we'd need to relax our handling of dates in vctrs.

**Comment by DavisVaughan** [comment]
vctrs can combine integer and double dates together without issues nowadays, so the linked SO question is not actually related to this

``` r
vctrs::vec_c(.Date(1), .Date(1L))
#> [1] "1970-01-02" "1970-01-02"
```

The root of the problem is that we don't define `vec_ptype2.Date.IDate`, so you can't combine those (the fact that they both say `is of type <date>` is just an unfortunate circumstance, they really are different types).

I doubt data.table will define those, so we could define ptype2/cast methods and assert that `<Date> + <IDate> = <Date>`? We'd go towards `<Date>` for the same reasons that `<double> + <integer> = <double>`.

This also came up here https://github.com/r-lib/vctrs/issues/1549

**Comment by hadley** [comment]
Ok, lets track this in vctrs.
