### ISSUE TITLE
Re-exporting desc() breaks in arrange

### ISSUE THREAD

**Issue by jonthegeek** [tidyverse/dplyr#6231]
I have a package that re-exports functions from various places so I can easily use them in some internal packages without having to deal with the separate imports. I can easily work around this issue by not doing that, but the bug surprised me and was invisible without direct testing, so I wanted to report it in case you want to deal with it.

Basically, if I reexport `desc()`, and I call it by namespacing, it doesn't do anything in `arrange()`.

```r
# Install my example package that reexports desc.
# devtools::install_github("jonthegeek/mydesc")
df <- data.frame(x = c("first", "second"))
dplyr::arrange(df, dplyr::desc(x))$x[[1]]
#> [1] "second"
dplyr::arrange(df, mydesc::desc(x))$x[[1]]
#> [1] "first"
```

It appears to be an issue with row 98 of arrange.R, but I'm not sure how/if it should be fixed.

**Comment by jonthegeek** [comment]
FWIW it looks like this behavior changed when #5929 was implemented.

**Comment by moodymudskipper** [comment]
You don't need to reexport it nor prefix it, the symbol is not fetched from the calling env : 

``` r
df <- data.frame(x = c("first", "second"))
desc <- stop
dplyr::arrange(head(df), desc(x))
#>        x
#> 1 second
#> 2  first
```

<sup>Created on 2022-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

{tidyselect} functions work the same, among those `where()` is not even exported.

**Comment by jonthegeek** [comment]
@moodymudskipper Yeah, this is super easy to work around, it was just invisible and surprising. I've already dealt with it in my own code, but I almost didn't notice it, which could have resulted in some very confusing results.
