### ISSUE TITLE
case_when gives difficult to interpret error when mixing outputs

### ISSUE THREAD

**Issue by billdenney** [tidyverse/dplyr#6234]
I accidentally gave a logical/character output type for case_when.  I know that is not allowed, but the error that I got back was about a names attribute rather than telling me that I cannot mix types.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
case_when(
  FALSE~NA,
  TRUE~"A"
)
#> Error in names(message) <- `*vtmp*`: 'names' attribute [1] must be the same length as the vector [0]
```

<sup>Created on 2022-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eutwt** [comment]
Tracked in #6206
