### ISSUE TITLE
`rowwise()` with a mutate() call with warnings is very slow

### ISSUE THREAD

**Issue by charliejhadley** [tidyverse/dplyr#6236]
As identified by @debruine here https://github.com/tidyverse/dplyr/issues/6236#issuecomment-1103972470 this issue is actually caused when mutate() is used after rowwise() and generates warnings.

This code takes ~11 seconds to run in a clean R session

```r
library(dplyr)
library(tictoc)
tic()
foo <- tibble(
  id = 1:800
) %>% 
  rowwise() %>% 
  mutate(group_b_mean = mean(NULL))
toc()
# 11.584 sec elapsed
```

Please note that weirdly the same code takes <1second when run with the {reprex} addin.

Many thanks to debruine for figuring this out.

**Comment by eutwt** [comment]
Looks like it got slower after [this pr](https://github.com/tidyverse/dplyr/pull/6119). Example above goes from 1.6s to 15s for me and profvis shows all the time is spent in `cli_format()`

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(id = 1:100) 

f <- function() {
  warning()
  1
}

bench::system_time(
  df %>% 
    rowwise() %>% 
    mutate(x = f())
)
#> process    real 
#>     3s    3.6s 
```

(Note that you can't run this with the reprex package because something about the way rmarkdown handles warnings makes the problem go away)

@lionel- could you take a look to see if there's any obvious way to speed up the warning wrapping in `mutate_cols()`?

**Comment by lionel-** [comment]
One possible way to go about this would be to collect warnings until all computations are done, and then emit the first few warnings and suggest to use something like `dplyr_last_warnings()` to get them all.

**Comment by hadley** [comment]
@lionel- I like that idea.

**Comment by sjkiss** [comment]
Sorry: has this been added to 1.0.10 yet? I'm not clear. How do I get this fix into my version of dplyr?

**Comment by hadley** [comment]
@sjkiss it's in the dev version

**Comment by vak** [comment]
dplyr 1.1.2 is still slow on it

**Comment by hadley** [comment]
@vak please file a new issue with reprex.
