### ISSUE TITLE
summarize(across(...), across(...)) and mutate(across(...), across(...))

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#6254]
A `summarize()` call can contain more than one call to `across()`, which makes it more powerful than the `_at` and `_if` variants. I still wonder if we need to consider new columns when selecting columns with `across()`. 

## Example

Consider the following (contrived) example:

``` r
library(dplyr)

data <- tibble(my_summary = 0, xa = 1, xb = TRUE)

data %>%
  summarize(
    across(starts_with("x"), sum, .names = "{.col}_summary"),
    across(ends_with("_summary"), mean, .names = "{.col}_summary")
  )
#> # A tibble: 1 × 5
#>   xa_summary xb_summary my_summary_summary xa_summary_summary xb_summary_summary
#>        <dbl>      <int>              <dbl>              <dbl>              <dbl>
#> 1          1          1                  0                  1                  1
```

<sup>Created on 2022-05-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The second `across()` call captures the summary columns created in the first `across()` call. I can't think of a practical use case.

## Proposal

Should we limit the columns selectable with `across()` to the original columns in `summarize()`, and perhaps also in `mutate()` (though the case is not as clear there)? In the above example, the `_summary_summary` columns would no longer be created.

## Motivation

Separation of `mutate()` into `build_mutate_spec()` and `mutate_spec()` (same for `summarize()`), so that backends need to implement only `mutate_spec()` and let dplyr do the rest.

**Comment by eutwt** [comment]
I would not like this as a user. If you exclude new columns you’d have two options for what to do with modified columns having the same name as original data

1. Use the original column.
This breaks existing code like below. Unless you plan to keep track of whether across is accessing previously modified columns (breaking the motivation?), users will get an unexpected result without any warning.
```r
df %>% 
  summarise(
    across(everything(), sum),
    across(everything(), sqrt)
  )
```

2. Use the newly modified column
In this case the answer to "what is in scope for across" is more complex than just "everything" or "the original data", which I think would significant.y complicate users mental model relative to the current implementation.

**Comment by romainfrancois** [comment]
This is by design so that `across()` conceptually disappears. It is essentially the same issue as: 

```r
summarise(x = mean(x), y = x + 1)
```

One workaround is to bind both results in a `tibble()` call: 

``` r
library(dplyr)
data <- tibble(my_summary = 0, xa = 1, xb = TRUE)

data %>%
  summarize(
    tibble(
      across(starts_with("x"), sum, .names = "{.col}_summary"),
      across(ends_with("_summary"), mean, .names = "{.col}_summary")  
    )
  )
#> # A tibble: 1 × 3
#>   xa_summary xb_summary my_summary_summary
#>        <dbl>      <int>              <dbl>
#> 1          1          1                  0
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
I faced the same problem: #5433

> I can't think of a practical use case.

I still believe `across()` can behave better (without the `tibble()` workaround), but there definitely are some use case where `across()` needs to refer to the columns defined in `summarise()`, not in the original data. So, I don't think it's possible to change the default behavior of `across()`.

``` r
library(dplyr, warn.conflicts = FALSE)

data <- tibble(x = 1:4, y1 = 10:13, y2 = 22:25)

data %>%
  summarize(
    x_total = sum(x),
    across(starts_with("y"), ~ .x / x_total)
  )
#> # A tibble: 4 × 3
#>   x_total    y1    y2
#>     <int> <dbl> <dbl>
#> 1      10   1     2.2
#> 2      10   1.1   2.3
#> 3      10   1.2   2.4
#> 4      10   1.3   2.5
```

<sup>Created on 2022-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I'd prefer not to make any more changes to `across()` semantics unless we have a really really really compelling reason. It's highly folks now rely on the existing behaviour (even by accident) and changing is likely to be painful.
