### ISSUE TITLE
`filter` is many times slower than base R

### ISSUE THREAD

**Issue by jl5000** [tidyverse/dplyr#6256]
I'm finding that `filter` is extremely slow when compared with base R. I'm using the CRAN version of `dplyr` (1.0.9) and R 4.2.0. I would have expected it to be a bit slower, but not by this much.

```r
microbenchmark::microbenchmark(
  base = {iris[iris$Species=="setosa",]},
  dplyr = {dplyr::filter(iris, Species == "setosa")},
times = 100)

Unit: microseconds
  expr      min        lq       mean    median         uq       max neval
  base  131.423  143.0345   206.7922  208.7005   224.1915   581.396   100
 dplyr 7873.443 8315.1935 10415.7697 8544.3645 10784.3290 50407.269   100
```

**Comment by romainfrancois** [comment]
`filter()` does have to do more work. The difference become less dramatic when dealing with larger files, e.g.

``` r
filter <- dplyr::filter
bench::mark(
  base = iris[iris$Species=="setosa",],
  dplyr = filter(iris, Species == "setosa")
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 base        24.44µs  27.22µs    35330.   85.08KB     53.1
#> 2 dplyr        1.29ms   1.34ms      736.    1.73MB     45.9

iris <- iris[rep(1:150, each = 1e5), ]
bench::mark(
  base = iris[iris$Species=="setosa",],
  dplyr = filter(iris, Species == "setosa")
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 base          409ms    458ms      2.18     789MB     3.27
#> 2 dplyr         640ms    640ms      1.56     560MB     1.56
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We might at some point however recognize expressions of the form `<column> == <value>` and treat differently. 

Although most of the time is being spent in `vctrs::vec_slice()`: 

```r
profvis::profvis(filter(iris, Species == "setosa"))
```

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/2625526/166466906-10a77c66-e6d7-4952-b3f3-c6d5fa26561d.png">

Might be interesting to see if `vec_slice()` can be further optimized ?

```r
profvis::profvis(iris[iris$Species=="setosa",])
```

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/2625526/166467353-c80ef83a-b5a4-459b-8221-f5cb2ec395f1.png">

**Comment by DavisVaughan** [comment]
@romainfrancois I wonder if that profvis isn't quite right for some reason because I see this

``` r
library(vctrs)

condition <- iris$Species == "setosa"

bench::mark(
  base = iris[condition,],
  vctrs = vec_slice(iris, condition)
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 base        41.46µs   51.2µs    18925.   18.73KB     21.7
#> 2 vctrs        8.69µs   11.3µs    85623.    7.88KB     17.1
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
