### ISSUE TITLE
filter / group_by problem when using it before the collect()

### ISSUE THREAD

**Issue by GildasLepennetier** [tidyverse/dplyr#6266]
Dear community,
I encounter a problem when filtering data on the SQL-server side before a collect() function.

I am not sure how to create a reproducible example since I would need to create some SQL database.

Still, I will leave that problem I have here:

This command start a connection to a SQL database via the "con" handle, like follow (dbx package)

```r
 con <- dbx::dbxConnect(adapter = "mysql", host = config$host, user = config$user, password = config$password, port = config$port, dbname = config$dbname)
```

We select two columns, collect the data, then group_by the id. 
The filter using n() should isolate cases in which the id_1 has several values of the id_2, and does the job.

```r
tbl(con, "my_sql_table") %>% select(id_1, id_2) %>%
  collect() %>%
  group_by(id_1) %>% filter(n() > 1)
```

BUT, if the collect() is placed at the end of the code, it is not working any more. 

```r
tbl(con, "my_sql_table") %>% select(id_1, id_2) %>%
  group_by(id_1) %>% filter(n() > 1) %>%
  collect()
```

Can someone reproduce this error? Did I miss something in the manual?

**Comment by hadley** [comment]
This sounds like a dbplyr problem — and it includes some advice for creating reprexes: https://dbplyr.tidyverse.org/articles/reprex.html
