### ISSUE TITLE
Unify `group_by()` and `left_join()`?

### ISSUE THREAD

**Issue by psychelzh** [tidyverse/dplyr#6267]
In an edge case when `by` does not exist, `group_by()` works for `NULL` but not `left_join()`, and `character()` works for `left_join()` but not `group_by()`. Life will be easy if the behavior of these two is consistent. For now I will refer to `merge()` from base and stick with `NULL`.

``` r
a <- tibble::tibble(x = 1)
b <- tibble::tibble(y = 2)
a |> dplyr::group_by(NULL) # This works
#> # A tibble: 1 × 1
#>       x
#>   <dbl>
#> 1     1
a |> dplyr::group_by(character()) # This does not
#> Error in `dplyr::group_by()`:
#> ! Problem adding computed columns.
#> Caused by error in `mutate()`:
#> ! Problem while computing `..1 = character()`.
#> ✖ `..1` must be size 1, not 0.
a |> dplyr::left_join(b, by = NULL) # This does not
#> Error in `dplyr::left_join()`:
#> ! `by` must be supplied when `x` and `y` have no common variables.
#> ℹ use by = character()` to perform a cross-join.
a |> dplyr::left_join(b, by = character()) # This works again
#> # A tibble: 1 × 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
a |> merge(b, by = NULL) # This works
#>   x y
#> 1 1 2
```

<sup>Created on 2022-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I don't think these need to be consistent — `by` takes a character vector of variable names; `group_by` takes a mutate specification. If we make them consistent with one another, we'd make them less internally consistent.
