### ISSUE TITLE
Request: Export a unified wrapper of all `*_join` verbs

### ISSUE THREAD

**Issue by hsbadr** [tidyverse/dplyr#6272]
Would it make sense to export a general verb (e.g., `join()` or `join_type()` to avoid conflicts if desired) with a `type` argument, similar to `plyr::join()`? I think this would make it more readable and easier to track the related development such as #5910. It could be a generic that directly utilizes the internal `join_mutate()` and `join_filter()` helper functions while keeping the current `*_join` verbs for backward compatibility. This is similar to `readr::read_delim()` and may be applicable to other verbs. Thank you!

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think think it's something we'll consider right now: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
