### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by Falnesio** [tidyverse/dplyr#6285]
**Site is down**

https://dplyr.tidyverse.org/

Tested at multiple locations on multiple machines, same result.

![image](https://user-images.githubusercontent.com/36005374/170704617-1bbbe43a-f92b-4fbd-b4e5-bbf1d4bb28b9.png)

**Comment by romainfrancois** [comment]
Seems to be back up now: https://twitter.com/rstudio/status/1530267364113018880?s=20&t=oFmq8c4hyn3yYYGTrt-3qg

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/2625526/170974527-a7ee6d7c-7dcd-4b66-8ed7-92dbf56ae120.png">
