### ISSUE TITLE
If `.keep = "unused"`, default `.after` to first used variable

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#6299]
Often you use `.keep = "unused"` to "replace" a variable with a new name and value, and you want it in the same place. So I find myself using this pattern pretty commonly:

``` r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(x = 1, y = 2, z = 3)
df |> 
  mutate(
    y_new = y * 10,
    .keep = "unused",
    .after = y
  )
#> # A tibble: 1 × 3
#>       x y_new     z
#>   <dbl> <dbl> <dbl>
#> 1     1    20     3
```

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Can we make it a little simpler by automatically setting `.after` here?

**Comment by DavisVaughan** [comment]
Feels a little magical to me, I think it would be hard to define the right behavior for cases like these

``` r
library(dplyr)

df <- tibble(a = 1, b = 2, c = 3, d = 4, e = 5)

# Combine to replace 2 columns.
# How do you know where to put `b_d`?
mutate(df, b_d = b + d, .keep = "unused")
#> # A tibble: 1 × 4
#>       a     c     e   b_d
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     1     3     5     6

# Create multiple columns.
# How do you specify where to put `b2` and `d2`?
mutate(df, b2 = b + 2, d2 = d + 2, .keep = "unused")
#> # A tibble: 1 × 5
#>       a     c     e    b2    d2
#>   <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1     1     3     5     4     6
```

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Yeah, ok.
