### ISSUE TITLE
Revisit injection properties of `!!` with grouped data frames

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#6305]
A few of us find this behavior very odd, given how it works with `.env$` and when not injected

```r
library(dplyr)

xx <- 1:32
mtcars <- mtcars[1:3]

# This seems weird
mtcars %>%
  group_by(cyl) %>%
  mutate(x = !!xx)
#> # A tibble: 32 × 4
#> # Groups:   cyl [3]
#>      mpg   cyl  disp     x
#>    <dbl> <dbl> <dbl> <int>
#>  1  21       6  160      1
#>  2  21       6  160      2
#>  3  22.8     4  108      3
#>  4  21.4     6  258      4
#>  5  18.7     8  360      5
#>  6  18.1     6  225      6
#>  7  14.3     8  360      7
#>  8  24.4     4  147.     8
#>  9  22.8     4  141.     9
#> 10  19.2     6  168.    10
#> # … with 22 more rows

# Because these fail
mtcars %>%
  group_by(cyl) %>%
  mutate(x = xx)
#> Error in `mutate()`:
#> ! Problem while computing `x = xx`.
#> ✖ `x` must be size 11 or 1, not 32.
#> ℹ The error occurred in group 1: cyl = 4.

mtcars %>%
  group_by(cyl) %>%
  mutate(x = .env$xx)
#> Error in `mutate()`:
#> ! Problem while computing `x = .env$xx`.
#> ✖ `x` must be size 11 or 1, not 32.
#> ℹ The error occurred in group 1: cyl = 4.
```

I know this was talked about here https://github.com/tidyverse/dplyr/issues/6188#issuecomment-1102311640, but I feel like a constant value should always be recycled to the group size. Bypassing that and using the size of the whole data frame for an injected constant feels extremely strange.

I know recycling to the group size isn't particularly useful (the groups would have to be the same size if you are injecting a vector), but I feel like it is the more internally consistent thing to do and it should make the internal code easier to understand. Our argument is that if you want to inject something that is the same size as the data, then you should ungroup first.

**Comment by krlmlr** [comment]
Ideally, `!!` and `.env$` would behave identically for all practical purposes. Is this the only exception?

**Comment by lionel-** [comment]
> Ideally, !! and .env$ would behave identically for all practical purposes. Is this the only exception?

I don't think this is correct. The semantics of evaluation are different. `!!` and `!!!` inject values before any evaluation occurs whereas `.env$` produces a value at evaluation time.

There is no purpose to recycling within the group size. However there is an important use case to injecting full-sized constants in meta-programming. This is documented in https://rlang.r-lib.org/reference/topic-data-mask-programming.html#transmute-as-a-data-mask-to-selection-bridge
