### ISSUE TITLE
Should pass error calls instead of using `fix_call()`

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#6309]
vctrs and tidyselect have been updated to support error calls. We should generally use this instead of `fix_call()`. This should improve backtraces as the trace suffix from the bottom call up to `call = <frame>` will be hidden by default.

Also tidyselect now creates chained errors, and the `fix_call()` in `select()` doesn't interact well with these. The parent error is missing:

```r
f <- function() g()
g <- function() h()
h <- function() abort("foo")
dplyr::select(mtcars, f())
#> ! Problem while evaluating `f()`.
```

**Comment by hadley** [comment]
Looks like we still need `error_call`/`call` arguments for `vec_rbind()`, and `vec_cbind()`.
