### ISSUE TITLE
group_by NULL

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#6321]
If we use a NULL in a `group_by` it works, i.e. it ignores it, but if we name the NULL then it gives an error.

```
mtcars %>% group_by(vs, NULL) %>% tally # works.  NULL ignored.
mtcars %>% group_by(vs, am = NULL) %>% tally  # issues error message
```

It would be useful if the second above acted the same as the first so we could do this which works if `by_am` is TRUE but currently gives an error if `by_am` is FALSE.  It will work if `by_am` is FALSE if we don't name the argument but in that case it will give a name of `"if (by_am) am"` so we need to name it.

```
# gives error
by_am <- FALSE
mtcars %>% group_by(vs, am = if (by_am) am) %>% tally
```

There are some workarounds in this SO post https://stackoverflow.com/questions/72896135/how-can-i-use-dplyr-group-by-within-a-function-conditional-on-a-flag but a direct solution as above would be nice.

Also the `group_by` help page should make clear how it behaves with a NULL argument.

**Comment by batpigandme** [comment]
Making this a bit easier to read by adding a reprex (as well as a couple of examples without the `tally()`, so the results of the grouping operations can be seen:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
mtcars %>% group_by(vs, NULL) %>% tally
#> # A tibble: 2 × 2
#>      vs     n
#>   <dbl> <int>
#> 1     0    18
#> 2     1    14
mtcars %>% group_by(vs, am = NULL) %>% tally
#> Error in `group_by()`:
#> ! Must group by variables found in `.data`.
#> ✖ Column `am` is not found.

mtcars %>% group_by(vs, am)
#> # A tibble: 32 × 11
#> # Groups:   vs, am [4]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows

# these two are the same
mtcars %>% group_by(vs)
#> # A tibble: 32 × 11
#> # Groups:   vs [2]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows
mtcars %>% group_by(vs, NULL)
#> # A tibble: 32 × 11
#> # Groups:   vs [2]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows

mtcars %>% group_by(vs, am = NULL)
#> Error in `group_by()`:
#> ! Must group by variables found in `.data`.
#> ✖ Column `am` is not found.

by_am <- FALSE
mtcars %>% group_by(vs, am = if (by_am) am) %>% tally
#> Error in `group_by()`:
#> ! Must group by variables found in `.data`.
#> ✖ Column `am` is not found.
```

<sup>Created on 2022-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

> Also the `group_by` help page should make clear how it behaves with a NULL argument.

It seems to me that it, in effect, ignores the `NULL` argument, and that with `am = NULL` it interprets this as asking for a variable that isn't in the data frame (this is just my cursory understanding, though, not to be taken as definitive by any measure).

**Comment by DavisVaughan** [comment]
The current behavior seems right to me. The `...` of `group_by()` have `mutate()-like semantics (for better or worse). And `mutate(mtcars, NULL)` does nothing, but `mutate(mtcars, am = NULL)` removes the `am` column. So essentially you are removing the column that you are then trying to group by, and that error message portrays that decently well.

I don't think diverging from `mutate()` in the `group_by(am = NULL)` case is a good idea here

**Comment by eutwt** [comment]
To be more specific about how it "works like mutate", if you provide a named argument to `group_by`, the expressions get passed to the same `mutate_cols` function used by `mutate` ([here](https://github.com/tidyverse/dplyr/blob/6d22c0f0e1b0d945f2fff28cecb71d9cd548098b/R/group-by.r#L215)). So, the arguments are treated exactly the same (plus an additional post-mutate step) and the column gets dropped for that reason.

If you wanted this behaviour, you'd have to special-case `name = NULL` to not get passed to `mutate_cols` like other named arguments to `group_by` would be. (Otherwise, even if this worked without error you'd still drop a column which, as you say, is not what `group_by` is used for)

**Comment by ggrothendieck** [comment]
Based on the examples in my last post, named arguments in `group_by` act like `mutate` if their right hand side is not NULL but do not act like `mutate` if the right hand side is NULL.  In `mutate` the name is dropped and in `group_by` it generates an error.

Thus we can restate the issue as it should drop the column if the right hand side from the `groiup_by` if it is NULL just as `mutate` does.

If the argument being made is that it complicates the implementation to be consistent then that is too bad but the fact is it is inconsistent in how it works from the user's viewpoint.

**Comment by eutwt** [comment]
Currently it doesn't act like mutate in that it behaves analogously to mutate for its own use-case, it acts like mutate in that there's an actual mutate step prior to the group-by (which causes a column drop, leading to this error). Whether that's good is another question, I just wanted to make spell out more clearly the relation of group by to mutate as it is currently.

**Comment by ggrothendieck** [comment]
Yes, I understand how it works but I wouldn't say that because it works that way it is necessarily consistent. The point of the issue is to fix the inconsistency.

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately I don't think it's worth fixing because it's arguable which behaviour is more consistent and it seems unlikely to affect very many people. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.
