### ISSUE TITLE
`arrange()` sorts `rownames` inconsistently for `data.frame`  

### ISSUE THREAD

**Issue by shivam7898** [tidyverse/dplyr#6322]
```r
library(dplyr) 

c_chr <- b_num <- a_def <- data.frame(x = letters[1:3], y = letters[4:6])

row.names(b_num) <- 11:13         #integer Rownames different from default
row.names(c_chr) <- LETTERS[1:3]  #character Rownames

# arrange() 
a_def_arr <- arrange(a_def, desc(x))
b_num_arr <- arrange(b_num, desc(x))
c_chr_arr <- arrange(c_chr, desc(x))

# order() ALWAYS reorders the rownames
a_def_ord <- a_def[order(a_def$x, decreasing = TRUE), ]
b_num_ord <- b_num[order(b_num$x, decreasing = TRUE), ]
c_chr_ord <- c_chr[order(c_chr$x, decreasing = TRUE), ]

# arrange() reinitialises them from 1 if rownames are numbers
row.names(a_def_ord) # [1] "3" "2" "1"
row.names(a_def_arr) # [1] "1" "2" "3"

# arrange() reinitialises them from 1 even if these are not the default numbers
row.names(b_num_ord) # [1] "13" "12" "11"
row.names(b_num_arr) # [1] "1" "2" "3"

# arrange() reorders the rownames if these are character
row.names(c_chr_ord) # [1] "C" "B" "A"
row.names(c_chr_arr) # [1] "C" "B" "A"
```

### Comments

Based on the results, I think the logic is if `rownames` are `character` sort them, otherwise they must be `integer` so renumber the rows starting from 1. However, I believe this may lead to unpredictable behavior. `identical()` comparison fails in 2 cases but passes in 1 of them. 

I did try to look at the code. `dplyr:::arrange.data.frame()`  leads to `dplyr:::arrange_rows()`  which in turn calls `vctrs::new_data_frame()` and this calls `.External(ffi_new_data_frame, x, n, class, ...)`. However, I don't know how to explore the C code for `ffi_new_data_frame`  [at this link](https://github.com/cran/vctrs/blob/5007db2b12329210eb007313ed942991801eb5c9/src/type-data-frame.c#L41), so I am stuck there :(

Anyway, my suggestion is `arrange()` should behave like `order()` for `rownames` but obviously there might be other considerations that I don't know about.

### sessionInfo()

```r
sessionInfo()

# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19044)
# 
# Matrix products: default
# 
# locale:
# [1] LC_COLLATE=English_India.utf8  LC_CTYPE=English_India.utf8   
# [3] LC_MONETARY=English_India.utf8 LC_NUMERIC=C                  
# [5] LC_TIME=English_India.utf8    
# 
# attached base packages:
# [1] stats     graphics  grDevices datasets  utils     methods   base     
# 
# other attached packages:
# [1] dplyr_1.0.9
# 
# loaded via a namespace (and not attached):
#  [1] fansi_1.0.3      assertthat_0.2.1 utf8_1.2.2       crayon_1.5.1    
#  [5] R6_2.5.1         DBI_1.1.3        lifecycle_1.0.1  magrittr_2.0.3  
#  [9] pillar_1.7.0     rlang_1.0.3      cli_3.3.0        vctrs_0.4.1     
# [13] generics_0.1.3   ellipsis_0.3.2   glue_1.6.2       purrr_0.3.4     
# [17] compiler_4.2.1   pkgconfig_2.0.3  tidyselect_1.1.2 tibble_3.1.7
```

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE) 

rn_def <- data.frame(x = 3:1)
rn_num <- data.frame(x = 3:1, row.names = 11:13)
rn_chr <- data.frame(x = 3:1, row.names = c("a", "b", "c"))

rownames(arrange(rn_def, x))
#> [1] "1" "2" "3"
rownames(arrange(rn_num, x))
#> [1] "1" "2" "3"
rownames(arrange(rn_chr, x))
#> [1] "c" "b" "a"
```

<sup>Created on 2022-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

There's two principles at play here:

* If the row names are numeric, dplyr/vctrs ignores them.
* If the row names are character, dpyr/vctrs preserves them.

In general, we don't bother to preserve automatic/numeric row names because we don't think they're very useful. 

``` r
rn_def <- data.frame(x = 3:1)
rownames(rn_def[c(1, 1), , drop = FALSE])
#> [1] "1"   "1.1"
```

<sup>Created on 2022-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
