### ISSUE TITLE
`!is.numeric` doesn't work in `across`

### ISSUE THREAD

**Issue by roaldarbol** [tidyverse/dplyr#6323]
I am trying to summarise all columns that are not numeric, e.g. both characters and dates. However, using `summarise(across(where(!is.numeric), some_function))` doesn't work.
I'm at a loss - there may be something I've missed or maybe it's a bug?

Here's a reprex:

---

Let's first generate some data; both characters, dates and integers:

```r
abc <- tibble(
  a = c("a", "a", "b"),
  b = as_date(c("2022-06-27", "2022-06-28", "2022-06-27")),
  c = c(1,2,2)
  )
```

Then let's first inspect the modes of the data:
`mode(abc$a)` > `"character"`
`mode(abc$b)` > `"numeric"`
`mode(abc$c)` > `"numeric"`

So on first glance, the dates are numeric - however:
`is.numeric(abc$b)` > `FALSE`

And if we try to summarise using `is.numeric`, the dates are (as expected) not processed:

```r
abc %>% 
  summarise(across(where(is.numeric), n_distinct))
```
```r
# A tibble: 1 × 1
      c
  <int>
1     2
```

...and of course neither with `is.character`:
```r
abc %>% 
  summarise(across(where(is.character), n_distinct))
```
```r
# A tibble: 1 × 1
      a
  <int>
1     2
```

So the logical thing is to just negate and use `!is.numeric`, but that throws an error:
```r
abc %>% 
  summarise(across(where(!is.numeric), n_distinct))
```
```r
Error in `summarise()`:
! Problem while computing `..1 = across(where(!is.numeric), n_distinct)`.
Caused by error in `across()`:
! invalid argument type
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by DavisVaughan** [comment]
You need to use `where(~ !is.numeric(.x))`. `where()` takes a function or purrr-like formula, but you have to use the purrr-like formula if you have something that is more complicated than just supplying a function name.

``` r
library(dplyr)

abc <- tibble(
  a = c("a", "a", "b"),
  b = as.Date(c("2022-06-27", "2022-06-28", "2022-06-27")),
  c = c(1,2,2)
)
abc
#> # A tibble: 3 × 3
#>   a     b              c
#>   <chr> <date>     <dbl>
#> 1 a     2022-06-27     1
#> 2 a     2022-06-28     2
#> 3 b     2022-06-27     2

# This...
abc %>% 
  summarise(across(where(is.numeric), n_distinct))
#> # A tibble: 1 × 1
#>       c
#>   <int>
#> 1     2

# ...is equivalent to this. But when you just have an unmodified function
# you don't need the `~` form.
abc %>% 
  summarise(across(where(~is.numeric(.x)), n_distinct))
#> # A tibble: 1 × 1
#>       c
#>   <int>
#> 1     2

# With the `!`, you are modifying `is.numeric()`, so you have to use the `~` form
abc %>% 
  summarise(across(where(~!is.numeric(.x)), n_distinct))
#> # A tibble: 1 × 2
#>       a     b
#>   <int> <int>
#> 1     2     2
```

<sup>Created on 2022-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
