### ISSUE TITLE
Base R functions misinterpreted as methods in documentation

### ISSUE THREAD

**Issue by FelicienLL** [tidyverse/dplyr#6326]
Hello, 
In the documentation of generic functions, there is an automatic detection of the methods available for other classes defined in the loaded packages. This is great but :
- the `select()` documentation mentions `list` as a class for which a `select` method exists, and points to `utils::select.list()`.
- the `slice()` documentation mentions `index` as a class for which a `slice` method exists, and points to `base::slice.index()`.

Don't you think they should be removed, by making an exception in the `methods_rd()` function for instance? 

Thanks in advance

Félicien

**Comment by hadley** [comment]
Hmmmm, they will be dispatched to by `UseMethod()`, but I agree that we'd be best off omitting from the docs. I think the easiest way to do so is just to remove the base packages from the results of `methods_generic()`.
