### ISSUE TITLE
Feature request: complete cases by columns

### ISSUE THREAD

**Issue by sgbstats** [tidyverse/dplyr#6332]
I often need complete case data but only on a subset of a few columns (I don't care where the other NAs are) and find myself always using 
```r
library(tidyverse)
df<-data.frame("X1"=c(1,2,NA,4),
              "X2"=c(5,NA,7,8),
              "X3"=c("a",NA,"c",NA))

df %>% filter(!is.na(X1), !is.na(X2))
#>   X1 X2   X3
#> 1  1  5    a
#> 2  4  8 <NA>
```

and having something along the lines of 

```r
df %>% col_complete_cases(X1, X2)
#>   X1 X2   X3
#> 1  1  5    a
#> 2  4  8 <NA>
```
 where you can specify which columns need to be complete would be super useful.

**Comment by eutwt** [comment]
Below are some ways to do this in current dplyr. I'm not a dplyr developer, so this isn't a comment on whether to add the feature.

``` r
library(dplyr, warn.conflicts = FALSE)

df<-data.frame("X1"=c(1,2,NA,4),
              "X2"=c(5,NA,7,8),
              "X3"=c("a",NA,"c",NA))

df %>% 
  filter(complete.cases(X1, X2))
#>   X1 X2   X3
#> 1  1  5    a
#> 2  4  8 <NA>

df %>% 
  filter(!if_any(c(X1, X2), is.na))
#>   X1 X2   X3
#> 1  1  5    a
#> 2  4  8 <NA>
```

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sgbstats** [comment]
Thanks, given that complete.cases is from _{stats}_ this would be a fairly low priority issue, so I'll close it off.
