### ISSUE TITLE
group_by function no longer working

### ISSUE THREAD

**Issue by kpitt100** [tidyverse/dplyr#6370]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

Within code that was working last week, now an error message comes up in R studio:

Error in `vec_as_location()`:
! `...` must be empty.
✖ Problematic argument:
• call = call

Traced to within group_by function:

Backtrace:
     ▆
  1. ├─base::source("~/.active-rstudio-document")
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. ├─r %>% group_by(x) %>% summarize(y = sum(y)) at ~/.active-rstudio-document:7:0
  6. ├─dplyr::summarize(., y = sum(y))
  7. ├─dplyr::group_by(., x)
  8. └─dplyr:::group_by.data.frame(., x)
  9.   └─dplyr::grouped_df(groups$data, groups$group_names, .drop)
 10.     └─dplyr:::compute_groups(data, vars, drop = drop)
 11.       ├─as_tibble(data)[vars]
 12.       └─tibble:::`[.tbl_df`(as_tibble(data), vars)
 13.         └─tibble:::vectbl_as_col_location(...)
 14.           ├─tibble:::subclass_col_index_errors(...)
 15.           │ └─base::withCallingHandlers(...)
 16.           └─**vctrs::vec_as_location(**j, n, names, call = call)
 17.             └─ellipsis::check_dots_empty()
 18.               └─rlang:::action_dots(...)
 19.                 ├─base (local) try_dots(...)
 20.                 └─rlang (local) action(...)

I am new to R so not certain if I have made an error, however I've not changed anything since the code worked.

R studio version: 2022.07.1 build 554
dplyr version 1.0.7

```r
# insert reprex here:
```
This is a simple code I created which has the same error message:

#create dataframe
x <- c(1,1,2,3,4,5,6,6,7)
y <- c(1:9)
r = data.frame(x,y)

#summarise 
r_sum = r %>% group_by(x) %>% 
  summarize(y = sum(y))

**Comment by DavisVaughan** [comment]
I'm not sure what is happening on your end but it works for me. Maybe try to update dplyr with `install.packages("dplyr")` and then restart R and try again.

``` r
library(dplyr)

#create dataframe
x <- c(1,1,2,3,4,5,6,6,7)
y <- c(1:9)
r = data.frame(x,y)

#summarise
r %>% 
  group_by(x) %>%
  summarize(y = sum(y))
#> # A tibble: 7 × 2
#>       x     y
#>   <dbl> <int>
#> 1     1     3
#> 2     2     3
#> 3     3     4
#> 4     4     5
#> 5     5     6
#> 6     6    15
#> 7     7     9
```

<sup>Created on 2022-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
