### ISSUE TITLE
Make `count()` more flexible?

### ISSUE THREAD

**Issue by modche** [tidyverse/dplyr#6373]
Wouldnt it be easy to implement a new functionality for `count` in `dplyr`?

At the moment:
`count(..., sort = TRUE)`

new:
`count(..., sort = 1)` and `count(..., sort = -1)`

`1` and `-1` can also be `asc` and `desc` or `a` and `d` and `TRUE` or `FALSE` can stay also.

It's just, that various ways of sorting are interesting during data analysis (and, yes, we can do this with an `arrange()` afterwards). This might be a small, but solid improvement and the parameter `sort=` is already there.

Thanks for your time.
Michael

**Comment by DavisVaughan** [comment]
`count()` and `tally()` are already very complex, and we are unlikely to make any additional changes that add to that complexity. I think calling `arrange()` with explicit `desc()` wrappers is a much nicer solution to this problem.
