### ISSUE TITLE
filter and select behave differently when passed strings with curly-curly

### ISSUE THREAD

**Issue by dhicks** [tidyverse/dplyr#6374]
Context: I'm writing a lesson for a data science course that includes an introduction to curly-curly notation for writing functions that encapsulate dplyr pipes.  

`filter()` and `select()` behave differently when a string (quoted column name) is passed instead of a bare.  Wrapping the variable reference in `if_all()` or `if_any()` works as expected, but seems more cumbersome than intended.  

Reprex: 
``` r
## Passing a string to select using curly-curly works same as passing a bare
foo = function(df, var) {
    dplyr::select(df, {{ var }})
}
identical(foo(mtcars, disp), 
          foo(mtcars, 'disp'))
#> [1] TRUE

## But passing a string to filter using curly-curly is interpreted as a string
## NB In the actual example, the filter condition is !is.na{{ var }}
bar = function(df, var) {
    dplyr::filter(df, {{ var }} > 300)
}
bar(mtcars, disp) |> nrow()
#> [1] 11
bar(mtcars, 'disp') |> nrow()
#> [1] 32

## Wrapping the condition in `if_all()` or `if_any()` works as expected, but seems unnecessarily complicated
bat = function(df, var) {
    dplyr::filter(df, dplyr::if_all({{ var }}, ~ . > 300))
}
bat(mtcars, disp) |> nrow()
#> [1] 11
bat(mtcars, 'disp') |> nrow()
#> [1] 11
```

<sup>Created on 2022-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
I'd encourage you to take a step back and look at what happens with these functions on their own before adding in curly curly.

Doing `select(mtcars, disp)` is essentially equivalent to `select(mtcars, "disp")`, even though we recommend the first form more. This is part of how tidyselect works, and there is no ambiguity here.

Doing `filter(mtcars, disp > 100)` is _very_ different from `filter(mtcars, "disp" > 100)`. `"disp" > 100` can be evaluated on its own, outside of the `filter()`, and just returns `TRUE`. So it keeps all 32 rows of mtcars.

``` r
library(dplyr)
mtcars <- as_tibble(mtcars)

select(mtcars, disp) # == select(mtcars, "disp")
#> # A tibble: 32 × 1
#>     disp
#>    <dbl>
#>  1  160 
#>  2  160 
#>  3  108 
#>  4  258 
#>  5  360 
#>  6  225 
#>  7  360 
#>  8  147.
#>  9  141.
#> 10  168.
#> # … with 22 more rows
#> # ℹ Use `print(n = ...)` to see more rows

# Very different from `disp > 100`, this is what gets evaluated
"disp" > 100
#> [1] TRUE

filter(mtcars, "disp" > 100) # == filter(mtcars, TRUE)
#> # A tibble: 32 × 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows
#> # ℹ Use `print(n = ...)` to see more rows
```

<sup>Created on 2022-07-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dhicks** [comment]
Sorry, I'm not sure how this step back is helpful.  The context is programming with functions that use tidy evaluation; we need to use curly-curly (or the equivalent).  At a minimum, it's going to be confusing to students first encountering tidy evaluation that sometimes a string "just works" for passing a column name and sometimes it doesn't.
