### ISSUE TITLE
`count` gives incorrect results when using an out-of-data-frame weight

### ISSUE THREAD

**Issue by deschen1** [tidyverse/dplyr#6391]
When doing a weighted frequency analysis with `count` and using an external vector for the weights, the results are incorrect. It seems that the external vector is not "matched" rowwise (although I think that is what most people would expect).

```
set.seed(1)
df <- data.frame(x      = rep(letters[1:2], 2),
                 weight = runif(4, min = 0, max = 3))

  x   weight
1 a 2.061069
2 b 1.152311
3 a 2.309524
4 b 1.493098

df |> 
  count(x)

# (a) correct results
  x n
1 a 2
2 b 2

df |> 
  count(x, wt = weight)

# (b) correct results
  x        n
1 a 4.370593
2 b 2.645409

ext_weight <- df$weight

df |> 
  count(x, wt = !!ext_weight)

# (c) incorrect results. Instead, should be identical to (b)
  x        n
1 a 7.016002
2 b 7.016002
```

**Comment by hadley** [comment]
I think it's easier to see what's happening here if you write out what `count()` is doing:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  x = rep(letters[1:2], 2),
  w = c(1:4)
)
w <- df$w

df |> 
  group_by(x) |> 
  summarise(wt = sum(w))
#> # A tibble: 2 × 2
#>   x        wt
#>   <chr> <int>
#> 1 a         4
#> 2 b         6

df |> 
  group_by(x) |> 
  summarise(wt = sum(!!w))
#> # A tibble: 2 × 2
#>   x        wt
#>   <chr> <int>
#> 1 a        10
#> 2 b        10
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I certainly don't think this is a desired outcome, but this case seems relatively rare, and it's going to be hard to fix it specifically, since this behaviour arises as a natural combination of things that make sense in other contexts.

**Comment by deschen1** [comment]
hmm, sad to see this closed. Couldn't it be an option to have some condition check that if the weight vector is external, the `sum(!!w)` part will be changed to, IDK, something like `sum(!!w[x = x of current group]`. Or rather what I'm doing as a workaround currently: if the weight is an external vector, append it to the data first. I hope/think this wouldn't have any side effects, because after the count or group_by/summarize the original data is "gone" anyway.

So the under-the-hood part would be:

```
df |> 
  bind_cols(w_make_sure_it_has_unique_name = w) |>
  group_by(x) |> 
  summarise(wt = sum(w_make_sure_it_has_unique_name))
```

Because I think that doing a normal weighted frequency analysis is a basic step for 95% of social science researchers (and probably many others).

Admittedly, the problem only arises when the weighting vector is not part of the data, but if the above workaround could be considered "safe", it would help making the count command operate more consistently.

**Comment by DavisVaughan** [comment]
I think using a weighting vector that isn't part of the data is already a bit of an anti-pattern that we don't encourage

**Comment by deschen1** [comment]
Fair enough and I agree with it. However, maybe the documentation could be phrased a bit more clearly here? E.g. with some warning or so that if the weigting var is an external one, the results will potentially be wrong?

**Comment by hadley** [comment]
From dplyr's perspective, there's no difference between what you're doing and this:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  x = rep(letters[1:2], 2),
  w = c(1:4)
)

df |> 
  group_by(x) |> 
  summarise(wt = sum(1:4))
#> # A tibble: 2 × 2
#>   x        wt
#>   <chr> <int>
#> 1 a        10
#> 2 b        10
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

That's certainly unlikely to be your goal, but it is valid R code. This complexity is one of the reasons we have been steering folks away from `!!`.

**Comment by deschen1** [comment]
Wouldn't it then be an option to either discourage the usage of an external vector in the documentation or throw an error (however, the latter's probably an unwanted breaking change)?

**Comment by hadley** [comment]
We don't document using an external vector the in first place, so I don't think it would help.
