### ISSUE TITLE
tally is wrong when wt = var and var is NULL 

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#6396]
``` r
library(dplyr, warn.conflicts = F)
tally(band_members, wt = NULL)
#> # A tibble: 1 × 1
#>       n
#>   <int>
#> 1     3
a <- NULL
tally(band_members, wt = a)
#> # A tibble: 1 × 1
#>       n
#>   <int>
#> 1     0
```

Replacing `quo_is_null()` by `eval_tidy()` in `dplyr:::tally_n()` would solve it.
It seems indeed that `rlang::quo_is_null()` returns `TRUE` only if a naked `NULL` is provided. 

Tangentially it makes sense that this function doesn't evaluate the expression but maybe the doc could make it clearer ?

``` r
rlang::quo_is_null(rlang::quo(NULL))
#> TRUE
> rlang::quo_is_null(rlang::quo(a))
#> FALSE
```

**Comment by hadley** [comment]
I agree that this is suboptimal, but I don't think there's anything we can easily do about it. We have many regrets about the design of `count`/`tally`.

**Comment by moodymudskipper** [comment]
Thanks, on a closer look I see it's not that immediate to solve.
For lurkers : storing `wt` as `NULL` in a variable is probably rare but the issue appears in practice when forwarding the `wt` argument from a wrapper function, in that case forwarding `{{wt}}` rather than `wt` will work.
