### ISSUE TITLE
Dplyr 1.0.9 cannot be installed

### ISSUE THREAD

**Issue by bgupsych** [tidyverse/dplyr#6398]
I updated some packages and now i cannot use the tidyverse no more. I had to manually download "cli" and now i cant use Dplyr.
Detailed topic:
https://community.rstudio.com/t/tidyverse-cannot-be-called-because-of-cli-permission-denied/144562/6

when i try to load or install tidyverse:
```
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘dplyr’ 1.0.8 is already loaded, but >= 1.0.9 is required
```
When i try to install dplyr:
`Error in install.packages : cannot open file 'C:/Users/97253/Documents/R/win-library/4.1/file36544dca5593/vctrs/help/figures/cast.png': Permission denied`

**Comment by hadley** [comment]
1. Close all open R/RStudio
2. Re-open R
3. Re-run `install.packages("dplyr")`
