### ISSUE TITLE
rename example documentation does not work.

### ISSUE THREAD

**Issue by mccroweyclinton-EPA** [tidyverse/dplyr#6411]
I am running R version 4.1.1 with dplyr version 1.0.9 installed. The example code included in the rename function does not seem to work.

---

Brief description of the problem

```r
iris <- as_tibble(iris) # so it prints a little nicer
rename(iris, petal_length = Petal.Length)
Error in rename(iris, petal_length = Petal.Length) : 
  object 'Petal.Length' not found
```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by tomyputw** [comment]
> iris <- as_tibble(iris) # so it prints a little nicer
> rename(iris, petal_length = Petal.Length)
Error: object 'Petal.Length' not found
R version 4.3.0 with dplyr version 1.1.4
I dont know why

**Comment by tomyputw** [comment]
> Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.
> conflicted::conflict_scout()
36 conflicts
• `rename()`: S4Vectors and dplyr

I find it and that is ......
