### ISSUE TITLE
`safely()` and `%||%` equivalent for use inside `mutate()`

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/dplyr#6431]
I commonly work with datasets from different sources that use different names for the same variables, and I need to consolidate these into a common name.

Currently, I use a workflow with `tibble::has_name()`:

```r
library(tidyverse)
if (!has_name(mtcars, "MPG")) mutate(mtcars, MPG = MPG)
```

This is can be tedious with many variables and different schemes.

It would be really convenient if I could instead call variable names inside of `mutate()` and have a way for them to return `NULL` instead of error if the variables are missing. Something like:

```r
mutate(mtcars, MPG = safely(MPG) %||% mpg)
```

Could something like that be implemented?

**Comment by DavisVaughan** [comment]
I think that feels a bit out of scope for dplyr itself. You could try-catch the expression though.

``` r
library(dplyr)
library(rlang)

safely <- function(expr) {
  tryCatch(expr, error = function(cnd) NULL)
}

mutate(mtcars, MPG = safely(MPG) %||% mpg) %>%
  head()
#>                    mpg cyl disp  hp drat    wt  qsec vs am gear carb  MPG
#> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4 21.0
#> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4 21.0
#> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1 22.8
#> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1 21.4
#> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2 18.7
#> Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1 18.1
```

<sup>Created on 2022-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eutwt** [comment]
Another option is `purrr::possibly`

```
mutate(mtcars, MPG = purrr::possibly(~ MPG, mpg)())
```
