### ISSUE TITLE
`group_by_prepare` with default `error_call` argument results in error

### ISSUE THREAD

**Issue by eutwt** [tidyverse/dplyr#6442]
The default values for arguments `caller_env` and `error_call` in `group_by_prepare` don't seem to work

`group_by_prepare` with default `error_call`
``` r
df <- data.frame(x = 1)
dplyr::group_by_prepare(df)
#> Error in is_missing(call): promise already under evaluation: recursive default argument reference or earlier problems?
```
<sup>Created on 2022-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

with `error_call` supplied but not `caller_env`, adding a column
``` r
df <- data.frame(x = 1)
dplyr::group_by_prepare(df, y = 3, error_call = call('fun'))
#> Error in initialize(...): promise already under evaluation: recursive default argument reference or earlier problems?
```
<sup>Created on 2022-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The reason I noticed this is that `group_by_prepare(data.frame(x = 1))` works with CRAN dplyr but not dev dplyr, which causes `group_by` to fail in dtplyr if dev dplyr is installed.

It seems to be because `caller_env` is self-referencing in the function signature. I guess the users of this function would be package developers who can probably figure out what's going on and just supply the arguments, but it was a little confusing. Maybe these arguments could have no default to make the error more understandable (`argument "caller_env" is missing` rather than `promise already under evaluation`), or `caller_env` renamed to `.caller_env`.

https://github.com/tidyverse/dplyr/blob/48431a541c16ad7f88bf2e2918013ae1dc82f480/R/group-by.r#L193-L199

``` r
fun <- function(caller_env = caller_env(2)) {
  print(caller_env)
}
fun()
#> Error in print(caller_env): promise already under evaluation: recursive default argument reference or earlier problems?
```
<sup>Created on 2022-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Ended up accidentally fixing this in #6444.
