### ISSUE TITLE
General support for .data and .env

### ISSUE THREAD

**Issue by latot** [tidyverse/dplyr#6449]
Hi, actually one of the most flexible and easy to read and understand code is with ```.data``` and ```.env```, and there is some functions here we can't use them in one way or other, I think would be great have their support.

Fails
```
dplyr::rename(df, .data$pair_idd = pair_id)
dplyr::rename(df, .data$pair_idd = .data$pair_id)
dplyr::mutate(df, .data$pair_id = .data$pair_id*2)
dplyr::transmute(df, .data$pair_id = .data$pair_id*2)
```

Thx!

**Comment by hadley** [comment]
You can't use `.data` on the right-hand side of `=`. That's a limitation of the R parser, and not something we could change even if we wanted to.

**Comment by latot** [comment]
mm, you means in the left hand?

**Comment by hadley** [comment]
Yes, sorry.

**Comment by latot** [comment]
mm, in that case, maybe instead of have ```.data``` and ```.env``` would be better other format, that can be used universally in dplyr? maybe a new function of something.
