### ISSUE TITLE
Link to documentation of methods

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#6452]
DBI has this nice feature of listing the installed methods and linking their help page (see the attached image). It would be great for other backends (e.g. dbplyr and dtplyr) if dplyr could do the same. This would help (at least a little) in issues such as https://github.com/tidyverse/dbplyr/issues/996.

![image](https://user-images.githubusercontent.com/18258854/189288355-87a6e384-1689-40c8-a909-d539bb84307a.png)

**Comment by hadley** [comment]
It already does. Is there a generic we're missing?

<img width="733" alt="Screen Shot 2022-09-09 at 07 42 23" src="https://user-images.githubusercontent.com/4196/189352395-aa46a40b-837b-4f38-afde-06b5b3609a9f.png">

**Comment by hadley** [comment]
Oh `copy_to()`, I guess.

**Comment by mgirlich** [comment]
I found a couple that are missing:

* `copy_to()`
* `db_*()`, e.g. `db_explain()`
* `sql_*()` e.g. `sql_join()`
* `rows_*()`

**Comment by hadley** [comment]
I'll leave `db_*` and `sql_` as is since they're not user facing
