### ISSUE TITLE
Feature request: `dplyr::distinct`: add argument to keep last duplicate

### ISSUE THREAD

**Issue by rempsyc** [tidyverse/dplyr#6460]
In survey-based research, we often have scenarios where some participants started a survey, then stopped for some reason (e.g., technical problem), and restarted shortly after. The *full* and correct answer is therefore the last one, not the first one. E.g.,

``` r
library(dplyr)
df <- data.frame(
  id = c(1, 1, 2),
  item1 = c(NA, 1, 1),
  item2 = c(NA, 1, 1),
  item3 = c(NA, 1, 1)
)
df
#>   id item1 item2 item3
#> 1  1    NA    NA    NA
#> 2  1     1     1     1
#> 3  2     1     1     1
```

If using `dplyr::distinct()`, which conceptually seems to be the perfect tool to deal with such duplicates, we end up removing the wrong duplicate:

``` r
df %>% 
  distinct(id, .keep_all = TRUE)
#>   id item1 item2 item3
#> 1  1    NA    NA    NA
#> 2  2     1     1     1
```

The ideal solution would be to either add a logical argument, e.g., `.keep_first`, `.keep_last`, with TRUE or FALSE, but those might be confusing because of `.keep_al`. So an alternative could be `.keep`, taking a character string either “first”, or “last”, with current default.

``` r
df %>% 
  distinct(id, .keep = "last")
```

    #>   id item1 item2 item3
    #> 2  1     1     1     1
    #> 3  2     1     1     1

Of course, there are other workarounds, such as using base R,

``` r
df[!rev(duplicated(rev(df$id))),]
#>   id item1 item2 item3
#> 2  1     1     1     1
#> 3  2     1     1     1
```

Or:

``` r
df %>%
  group_by(id) %>%
  filter(row_number() == n()) %>% 
  ungroup()
#> # A tibble: 2 × 4
#> # Groups:   id [2]
#>      id item1 item2 item3
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     1     1     1     1
#> 2     2     1     1     1
```

But it just feels bad to have to use a workaround to `distinct` if the function exists already.

<sup>Created on 2022-09-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I think the simplest approach is just to arrange in the desired order first:

```R
df |>
  arrange(desc(row_number()) |>
  distinct(id)
```

I don't currently believe that this comes up frequently enough to be worth adding an extra argument.

**Comment by rempsyc** [comment]
Yes, although, if you care about the rows being in the original order, you have to rearrange them again after, so that's 3 lines instead of one. Also, survey-based research is most of psychology, even though not everyone uses the current strategy for dealing with duplicates.

**Comment by hadley** [comment]
Once #6214 happens, you'd also be able to write `df |> slice_last(n = 1, by = id)`.

**Comment by rempsyc** [comment]
In the meanwhile, I wrote a function to take care of this more thoughtfully: it will pick the duplicate with the fewer number of missing values, and in case of ties, pick the first one.

``` r
library(rempsyc)
df1 <- data.frame(
  id = c(1, 2, 3, 1, 3),
  item1 = c(NA, 1, 1, 2, 3),
  item2 = c(NA, 1, 1, 2, 3),
  item3 = c(NA, 1, 1, 2, 3)
)
df1
#>   id item1 item2 item3
#> 1  1    NA    NA    NA
#> 2  2     1     1     1
#> 3  3     1     1     1
#> 4  1     2     2     2
#> 5  3     3     3     3

extract_duplicates(df1, id = "id")
#>   Row id item1 item2 item3 count_na
#> 1   1  1    NA    NA    NA        3
#> 2   4  1     2     2     2        0
#> 3   3  3     1     1     1        0
#> 4   5  3     3     3     3        0
best_duplicate(df1, id = "id")
#> (2 duplicates removed)
#>   id item1 item2 item3
#> 1  1     2     2     2
#> 2  2     1     1     1
#> 3  3     1     1     1
```

<sup>Created on 2022-10-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
