### ISSUE TITLE
better error when forgetting to quote string in filter

### ISSUE THREAD

**Issue by drmowinckels** [tidyverse/dplyr#6470]
I dont know if this is an error that is even possible to improve, but I've just encountered a large collection of learners that all did the same filtering error, and the error message was very unhelpful. While I understand that it might not be feasible to improve, I thought I'd show the example. 

In the care of learning to filter, remembering when to quote something or not is something hard to learn novices (it takes a little time to grasp the concept of something being a string and something being an object).

So instead of filtering on a character column asking for a value in quotations, they dont quote, and the error is... not awesome.

---

```r
library(dplyr)

mtcars |> 
  mutate(test = "something") |> 
  filter(test == something)
```
```
Error in `filter()`:
! Problem while computing `..1 =
  test == something`.
Caused by error in `mask$eval_all_filter()`:
! object 'something' not found
Run `rlang::last_error()` to see where the error occurred.
```

What would be awesome

```
Error in `filter()`:
! Problem while computing `..1 =
  test == something`.
! Did you mean `filter(test == "something")`
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by hadley** [comment]
Unfortunately I don't think we can do much better here because we'd need some kind of high quality heuristic to detect the absence of quotes, and I think it's going to be very hard to come up with something that has a very high predictive value. IWe have to be very careful with these sorts of hints because it's very easy to send people in the wrong direction.

**Comment by drmowinckels** [comment]
I kind of expected this answer, but wanted to give it a shoutout anyway. Thanks.
