### ISSUE TITLE
Suggestion: filter raises warning on `filter(x, id == id)`

### ISSUE THREAD

**Issue by zeehio** [tidyverse/dplyr#6485]
A [twit](https://twitter.com/_ColinFay/status/1574751654590976002) by Colin Fay describes a common [papercut issue](https://en.wikipedia.org/wiki/Paper_cut_bug) when using `dplyr::filter()`. 

A user writes the following code (notice the `id == id` inside the `filter()`):

```r
x <- function(data, id){
  data |> dplyr::filter(id == id)
}
```
where the user actually meant:

```r
x <- function(data, id){
  data |> dplyr::filter(id == .env$id)
}
```

And the behaviour they get is:

```r
x <- function(data, id){
  data |> dplyr::filter(!is.na(id))
}
```

I can't think of scenarios where `id == id` is useful:

- If the user meant `.data$id == .data$id`, I would suggest `!is.na(.data$id)` instead, as a more explicit expression.
- If the user meant `.data$id == .env$id`, the user is introducing a bug and should get a warning.

In either case a warning offering the two alternatives should probably be helpful, in my opinion.

**Comment by hadley** [comment]
I think unfortunately this is out of the scope of problems we can warn about. My main concern is that it's a slippery slope — should we also warn about `df |> filter(TRUE)`, or `df |> filter(if(something) TRUE else FALSE)` or ...
