### ISSUE TITLE
Should filter run with nrow(.data) == 0?

### ISSUE THREAD

**Issue by kendonB** [tidyverse/dplyr#6486]
I have a piece of code that gave a surprising warning because it tried to run `max` on an empty vector that came from a data frame with `nrow(.data) == 0`.

I would have expected `filter` to instantly return `.data` in this case without running the condition and therefore not giving the warning.

The output of `filter` is still what I expect - `.data` with no changes.

``` r
library(tidyverse)
tibble() %>% filter({warning("Test"); TRUE})
#> Warning in mask$eval_all_filter(dots, env_filter): Test
#> # A tibble: 0 × 0
```

<sup>Created on 2022-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
We generally treat 0 row data frames consistently with all other data frames. We  believe that this leads to fewer surprises over all.

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = integer(), y = integer())
df %>% mutate(z = x + y)
#> # A tibble: 0 × 3
#> # … with 3 variables: x <int>, y <int>, z <int>
```

<sup>Created on 2022-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kendonB** [comment]
@hadley do you have any examples of potential surprises caused by `filter` running with `nrow(.data) ==0`? I don't think that making this change would introduce an inconsistency implied by your example as `filter` is fundamentally about removing rows (and data.frames can't have negative rows) and `mutate` is fundamentally about adding/editing columns (which rightly should have no limits).
