### ISSUE TITLE
Issue with non equi joins, repeated column names, and `keep = FALSE`

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#6499]
With non equi joins we allow the same column to be used in multiple expressions, because you need to do this to specify bounds correctly. Seems that doesn't play well with `keep = FALSE`.

This, of course, also affects `between()` because it generates expressions exactly like these

``` r
library(dplyr)

df1 <- tibble(x = 1)
df2 <- tibble(lower = 0, upper = 2)

# Fine (default)
left_join(df1, df2, join_by(x >= lower, x <= upper), keep = TRUE)
#> # A tibble: 1 × 3
#>       x lower upper
#>   <dbl> <dbl> <dbl>
#> 1     1     0     2

# Hmm
left_join(df1, df2, join_by(x >= lower, x <= upper), keep = FALSE)
#> Error in `left_join()`:
#> ! Join columns must be unique.
#> ✖ Problem with `x`.

#> Backtrace:
#>     ▆
#>  1. ├─dplyr::left_join(df1, df2, join_by(x >= lower, x <= upper), keep = FALSE)
#>  2. └─dplyr:::left_join.data.frame(df1, df2, join_by(x >= lower, x <= upper), keep = FALSE)
#>  3.   └─dplyr:::join_mutate(...)
#>  4.     └─dplyr:::join_cols(...)
#>  5.       └─dplyr:::check_join_vars(by$x, x_names, by$condition, keep, error_call = error_call)
#>  6.         └─rlang::abort(bullets, call = error_call)
```

**Comment by hadley** [comment]
I think we could just make `keep = FALSE` an error here.

**Comment by DavisVaughan** [comment]
Might be kind of tricky to detect this specific case.

Would you force it to be an error for all non-equi joins, assuming that if you do a non-equi join you want to keep all of the key columns? That might make sense, in the following examples you probably do want to keep both sets of keys:

```r
# issue is here
join_by(x >= lower, x <= upper)

# no issue here currently
join_by(x_lower >= lower, x_upper <= upper)

# no issue here currently, but `suffix` kicks in
join_by(lower >= lower, upper <= upper)

# no issue here currently
join_by(x <= y)
```

**Comment by hadley** [comment]
Yeah just require both keys for non equi joins. I think it’s a weird enough special case we don’t need to support it.

**Comment by DavisVaughan** [comment]
I looked at this a bit more and realized that it is actually working exactly as I wanted it to at the time.

I wanted to allow `keep = FALSE` when it "made sense", and in theory it made sense to allow it when the key columns were unique, like in 

```r
# i.e. within()
join_by(x_lower >= lower, x_upper <= upper)
```

Or in

```r
join_by(x <= y)
```

But it is likely that you want both sets of keys in these cases anyways (which is why the default gives both sets of keys), which makes using `keep = FALSE` here quite rare.

---

Additionally, even though it might be reasonable to _sometimes_ use `keep = FALSE` in those two rare cases, there are two big reasons to disallow `keep = FALSE` with non-equi joins altogether:

- It won't ever work with `between(x, lower, upper)` because that would treat `x` as a duplicate key, causing the original error.

- More interesting is something I discovered in https://github.com/tidyverse/dplyr/pull/6502. If you use a right/full join with `keep = FALSE` and `overlaps()`, then you can get nonsensical results because of how the keys are merged.

``` r
library(dplyr)

df1 <- tibble(xl = c(1, 3), xu = c(4, 7))
df2 <- tibble(yl = c(2, 5, 8), yu = c(6, 8, 9))

df1
#> # A tibble: 2 × 2
#>      xl    xu
#>   <dbl> <dbl>
#> 1     1     4
#> 2     3     7

df2
#> # A tibble: 3 × 2
#>      yl    yu
#>   <dbl> <dbl>
#> 1     2     6
#> 2     5     8
#> 3     8     9

# Translates to `xl <= yu, xu >= yl`:
# - `yu` is merged into `xl`
# - `yl` is merged into `xu`
# This makes no sense and means the resulting columns don't
# keep the `xl <= xu` invariant and would never be desired
# (look at row 4).
full_join(df1, df2, join_by(overlaps(xl, xu, yl, yu)), keep = FALSE)
#> # A tibble: 4 × 2
#>      xl    xu
#>   <dbl> <dbl>
#> 1     1     4
#> 2     3     7
#> 3     3     7
#> 4     9     8
```

So I'll look into disallowing `keep = FALSE` with non-equi joins, it will likely simplify some of the code.
