### ISSUE TITLE
dplyr compatibility with 3.6.0?

### ISSUE THREAD

**Issue by algsat** [tidyverse/dplyr#6505]
Hello,

When I run dplyr::sumarise() in R 3.6.0 I get an error with glue.  This does not happen when I run in R 4.2.1.  I am using dplyr version 1.0.10 and glue version 1.6.2.  Here is an example:

```r
library(dplyr)
dplyr::summarise(mtcars,mean = mean(disp), n = n())
```
`Error in glue(str, .envir = .envir, .transformer = transformer, .cli = TRUE) : object 'glue_' not found`

I thought dplyr was compatible with versions >3.4, am I missing something?  Thanks!

**Comment by DavisVaughan** [comment]
dplyr is compatible with R 3.6.0, you likely have an outdated package of some kind.

I would try running these one at a time in a fresh R session, restarting R between each call. They are the likely candidates that you might have out of date. Then try your reprex again.

```r
install.packages("rlang")
install.packages("glue")
install.packages("vctrs")
install.packages("dplyr")
```

**Comment by algsat** [comment]
Thanks Davis, your solution worked.  I really appreciate your time, and thanks for an epic package!
