### ISSUE TITLE
Test of inequality not typo-safe

### ISSUE THREAD

**Issue by AlbertRapp** [tidyverse/dplyr#6506]
Today, one of my students wanted to check if two columns are not equal. Instead of using `!=` he wanted to use `!(x == y)` but forgot an `=`. Unfortunately, the output gave no warning that something is wrong. 

Sure, using `!=` would prevent this but then again my student is an absolute beginner and simply forgot about `!=`. Could happen to other beginners too. Is it possible to prevent these kind of mishaps? Or create a warning?

```r
data.frame(x = c(1L, 2L), y = c(3L, 2L)) |> 
  dplyr::mutate(
    test_equality = (x = y), # typo here but detectable that output is not correct Boolean
  )
# x y   test_equality
# 1 3   3
# 2 2   2


data.frame(x = c(1L, 2L), y = c(3L, 2L)) |> 
  dplyr::mutate(
    test_inequality = !(x = y), # typo here but Boolean output
  )
# x y   test_inequality
# 1 3   FALSE
# 2 2   FALSE
```

**Comment by hadley** [comment]
Unfortunately catching every possible typo is out of scope for dplyr.
