### ISSUE TITLE
Unexpected slice_max behaviour. Turns mandatory arguments into optional arguments when run within a function

### ISSUE THREAD

**Issue by selkamand** [tidyverse/dplyr#6515]
Thanks for all your work on this package!!

# Problem
I found some extremely unexpected behavior of `slice_max` (at least for me!)

I was writing a function which took a mandatory argument 'topn', which I passed to `slice_max` within this function.

To my surprise, calling the function without setting `topn` threw no error. Reprex below

# Desired Behaviour
I'd have expected R to throw the error: ` Error in print(topn): argument "topn" is missing, with no default`

# Reprex: Unexpected Behaviour 
``` r
library(dplyr, warn.conflicts = FALSE)

# Define function that passes argument along to slice_max
foo <- function(topn){
  
  slice_max(mtcars, order_by = mpg, n = topn)
    
}

# Running function without arguments throws no error
foo()
#>                 mpg cyl disp hp drat    wt qsec vs am gear carb
#> Toyota Corolla 33.9   4 71.1 65 4.22 1.835 19.9  1  1    4    1
```

<sup>Created on 2022-10-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

# Reprex: Example of expected behaviour
``` r
# Define function that passes argument along to slice_max
foo2 <- function(topn){
  print(topn)
  slice_max(mtcars, order_by = mpg, n = topn)
  
}

# Throws appropriate error since variable is 'used' in `print`
foo2()
#> Error in print(topn): argument "topn" is missing, with no default
```

<sup>Created on 2022-10-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

# Why is this happening
As per 'normal' R behaviour, arguments which aren't used in the function are not 'required' - and thus no error is thrown

``` r
foo3 <- function(very_important_arg) {
  # very_important_arg never used, so is not required
  print('No error thrown :)')
}

foo3()
#> [1] "No error thrown :)"
```

<sup>Created on 2022-10-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The unexpected behavior here is that I assumed passing `topn` to `slice_max`, meant it would be considered as being 'used'. 

So my guess is its something to do with the argument evaluation works in the absense?

# Potential fixes

Bit of a shot in the dark, I don't know the dplyr source well at all so at the risk of showing my ignorance:

Would a `check_number` or `check_required` call to this argument lead to the expected behaviour?

**Comment by hadley** [comment]
Looks like this is fixed in the dev version:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(x = 1:0)
foo <- function(topn) {
  df %>% slice_max(x, n = topn)
}
foo()
#> Error in `slice_max()`:
#> ! `n` must be a constant.
#> Caused by error in `force()`:
#> ! argument "topn" is missing, with no default

```

<sup>Created on 2022-10-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
