### ISSUE TITLE
[FR] allow grouping from inside `mutate()`

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/dplyr#6521]
Hi,

With `dplyr` 1.0+, `across()` let us use a more compact syntax that I believe improved the quality of our code.

In the same wave of thought, it would be very nice to have a grouping syntax from inside `mutate()`.

For instance, I sometimes have to do something like this:

```r
x = mtcars %>% 
  group_by(cyl) %>% 
  mutate(mean_mpg_by_cyl = mean(mpg)) %>% 
  group_by(carb) %>% 
  mutate(mean_mpg_by_carb = mean(mpg)) %>% 
  group_by(vs) %>% 
  mutate(mean_mpg_by_vs = mean(mpg)) %>% 
  ungroup()

x %>% 
  filter(mean_mpg_by_carb>17 & mean_mpg_by_vs>20 & mean_mpg_by_cyl>19)
```

It would be so much more elegant to write (and DRY-proof) if there was some way to write it like this:

```r
x = mtcars %>% 
  mutate(
    mean_mpg_by_cyl = across(mpg, mean, .group_by=cyl),
    mean_mpg_by_carb = across(mpg, mean, .group_by=carb),
    mean_mpg_by_vs = across(mpg, mean, .group_by=vs),
  )
```

Do you think this would be feasible and in the scope of `dplyr`?

I know there will be some limitations, like what should be done with existing grouping, what should be done inside summarise (where different grouping makes little sense), and probably more, but I thought it was still worth the shot asking 😁

**Comment by hadley** [comment]
We're going to do #6214 which will get you much of the way there.

**Comment by moodymudskipper** [comment]
`.by` in `across()`, overriding `.by` in `mutate()`, would be great though!

**Comment by DavisVaughan** [comment]
That is definitely going to be out of scope for `.by`, I don't think a single call to `mutate()` should be able to have more than 1 set of grouping keys.

**Comment by moodymudskipper** [comment]
@DanChaltiel here's an option, the grouping of `across_by()` is applied on top of the initial grouping by default.

The groups (tidy selections) are provided through the dots, it was either this or a `.by = quos(...)` arg that I thought didn't look good but you might change it to your taste. This means where you would have used the dots for `.fns` you'll need `~ fun(arg, ...)`.

``` r
library(dplyr, w = F)

across_by <- function(.cols, .fns, ..., .names = NULL, .unpack = FALSE, .add = TRUE) {
  data <- across(everything())
  .by <- enquos(...)
  env <- parent.frame()
  purrr::map_dfc(.by, ~ {
    .by_cols <- expr(!!.x) %>% 
      tidyselect::eval_select(data, env) %>% 
      names() %>% 
      paste(collapse = "_")
    data %>% 
      # apply (additional) groups
      group_by(across(!!.x), .add = .add) %>% 
      # apply transformation to subset
      transmute(across({{ .cols }}, .fns, .names = .names, .unpack = .unpack)) %>%
      ungroup() 
  }
  )
}

# for display
mtcars2 <- mtcars %>% 
  as_tibble() %>% 
  select(cyl, carb, vs, mpg) 

mtcars2 %>% 
  mutate(across_by(mpg, mean, cyl, carb, vs, .names = "mean_{.col}_by_{.by_cols}"))
#> # A tibble: 32 × 7
#>      cyl  carb    vs   mpg mean_mpg_by_cyl mean_mpg_by_carb mean_mpg_by_vs
#>    <dbl> <dbl> <dbl> <dbl>           <dbl>            <dbl>          <dbl>
#>  1     6     4     0  21              19.7             15.8           16.6
#>  2     6     4     0  21              19.7             15.8           16.6
#>  3     4     1     1  22.8            26.7             25.3           24.6
#>  4     6     1     1  21.4            19.7             25.3           24.6
#>  5     8     2     0  18.7            15.1             22.4           16.6
#>  6     6     1     1  18.1            19.7             25.3           24.6
#>  7     8     4     0  14.3            15.1             15.8           16.6
#>  8     4     2     1  24.4            26.7             22.4           24.6
#>  9     4     2     1  22.8            26.7             22.4           24.6
#> 10     6     4     1  19.2            19.7             15.8           24.6
#> # … with 22 more rows
```

<sup>Created on 2022-11-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
