### ISSUE TITLE
cbind with a grouped_df and stringsAsFactors=FALSE results in an erroneous column being added

### ISSUE THREAD

**Issue by daattali** [tidyverse/dplyr#6529]
> Originally discovered in https://github.com/glin/reactable/issues/283 but @glin traced it down to a potential bug in {dplyr}. If this doesn't feel like a bug, feel free to close

`cbind(..., stringsAsFactors = FALSE)` when provided a grouped_df() doesn't work correctly - it adds a `stringsAsFactors` column.

```r
cbind(x = "a", data.frame(y = 2), stringsAsFactors = FALSE)
#   x y
# 1 a 2

cbind(x = "a", dplyr::grouped_df(data.frame(y = 2), "y"), stringsAsFactors = FALSE)
# # A tibble: 1 x 3
#   x         y stringsAsFactors
#   <chr> <dbl> <lgl>           
# 1 a         2 FALSE     
```

This feels like a bug because in the documentation for `cbind` it says that the parameter `stringsAsFactors` is supported, which suggests it shouldn't be treated as a column:

> For the "data.frame" method of cbind these can be further arguments to data.frame such as stringsAsFactors.

**Comment by hadley** [comment]
Given that this is fixed upstream, and `cbind()` is such an odd function, I think it's best to just leave it as is.

(If we did make a change, I think it would be more consistent to add all named arguments to `data.frame()`, but that just doesn't seem worth it.)
