### ISSUE TITLE
`rename_with()` doesn't handle factors well

### ISSUE THREAD

**Issue by jmbarbone** [tidyverse/dplyr#6561]
`rename_with.data.frame()` has _unexpected_ results when `.fn` returns a `factor` -- or at least unexpected for me.  Documentation does _suggest_ that `.fn` should return a `character` vector, but I wouldn't expect factors to be coerced to integers first.

The coercion occurs within `[<-`, which could be replaced with `vec_slice()`?

https://github.com/tidyverse/dplyr/blob/434caa2db5c1f48b9f0becc9295e547c1072260b/R/rename.R#L69

``` r
df <- data.frame(
  a = 1,
  b = 2,
  c = 3
)

foo <- function(x) {
  factor(toupper(x))
}

dplyr::rename_with(df, foo)
#>   1 2 3
#> 1 1 2 3


# name reassignment within rename_with.data.frame()
x <- c("a", "b", "c")
x[1:3] <- foo(x)
x
#> [1] "1" "2" "3"


# vctrs seems fine
x <- c("a", "b", "c")
vctrs::vec_slice(x, 2:3) <- foo(x[2:3])
x
#> [1] "a" "B" "C"
```

<sup>Created on 2022-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
We should probably just error if you return anything other than a string.
