### ISSUE TITLE
`group_map` overrides default arguments to `.f` with group names when called with `...`

### ISSUE THREAD

**Issue by tfehring** [tidyverse/dplyr#6562]
Situation: `group_map.data.frame` is called from a function taking `...` arguments. `group_map` passes those `...` arguments to `.f`, i.e., the function being mapped. `.f` also accepts one or more named arguments with defaults, in addition to the data.frame and `...`.

I'd expect one of two possible behaviors here:

1. Grouping variables are not passed to `.f` via `...`; the `...` arguments to `.f` are the same as those passed to the outer function, or
2. Grouping variables are passed to `.f` via `...`; the `...` arguments to `.f` are the union of the grouping variables and the `...` arguments passed to the outer function (possibly with a warning or error if named arguments passed to the outer function conflict with reserved names for the grouping variables)

Either way, I'd expect default arguments to `.f` to be retained, unless they're overridden explicitly in the calls to `group_map` or the outer function. Instead, they're overridden by the grouping variable.

```r
library(dplyr)

data <- tibble(group = c(1, 1, 2, 2))

inner_function <- function(df, foo = 3:4, bar = 7:8, ...) {
    tibble(foo = foo, bar = bar, ...)
}

inner_function(data, foo = 5:6, baz = 9:10)

# # A tibble: 2 × 3
#     foo   bar   baz
#   <int> <int> <int>
# 1     5     7     9
# 2     6     8    10

outer_function <- function(df, ...) {
    data |>
        group_by(group) |>
        group_map(inner_function, ...)
}

outer_function(data, foo = 5:6, baz = 9:10)

# [[1]]
# # A tibble: 2 × 3
#     foo bar$group   baz
#   <int>     <dbl> <int>
# 1     5         1     9
# 2     6         1    10

# [[2]]
# # A tibble: 2 × 3
#     foo bar$group   baz
#   <int>     <dbl> <int>
# 1     5         2     9
# 2     6         2    10
```

Note that `bar`, a default argument to `inner_function`, is overridden by the `group` variable and isn't present in the output.

With a single grouping variable, `group_map` overrides the first argument to the inner function that isn't specified in the call to the outer function. So this modification results in the expected output:

```r
inner_function <- function(df, foo = 3:4, an_unused_argument = NULL, bar = 7:8, ...) {
    tibble(foo = foo, bar = bar, ...)
}

outer_function(data, foo = 5:6, baz = 9:10)

# [[1]]
# # A tibble: 2 × 3
#     foo   bar   baz
#   <int> <int> <int>
# 1     5     7     9
# 2     6     8    10

# [[2]]
# # A tibble: 2 × 3
#     foo   bar   baz
#   <int> <int> <int>
# 1     5     7     9
# 2     6     8    10
```

For completeness, note that `group_modify` exhibits similar behavior, since it wraps `group_map`.

**Comment by hadley** [comment]
I don't think there's much we can do here as I'm pretty sure you're just experiencing the details of how `...` works. Fortunately you can clear up much of the problem by using an anonymous function which makes it more precise exactly where the `...` is going:


``` r
library(dplyr, warn.conflicts = FALSE)

inner_function <- function(df, foo = 3:4, bar = 7:8, ...) {
  tibble(foo = foo, bar = bar, ...)
}

outer_function <- function(df, ...) {
  data |>
    group_by(group) |>
    group_map(\(df, key) inner_function(df, ...))
}

data <- tibble(group = c(1, 1, 2, 2))
outer_function(data, foo = 5:6, baz = 9:10)
#> [[1]]
#> # A tibble: 2 × 3
#>     foo   bar   baz
#>   <int> <int> <int>
#> 1     5     7     9
#> 2     6     8    10
#> 
#> [[2]]
#> # A tibble: 2 × 3
#>     foo   bar   baz
#>   <int> <int> <int>
#> 1     5     7     9
#> 2     6     8    10
```

<sup>Created on 2022-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
