### ISSUE TITLE
 Drop all the columns below specific threshold ?  

### ISSUE THREAD

**Issue by Hesham999666** [tidyverse/dplyr#6564]
So I am dealing with big data with hundreds or thousands of columns some of them I am not interested they contain a lot of zero and I want to tide up my data to get fewer columns. 

Is there function  in **dplyr** to drop all the columns below specific threshold / number for example 0.01 ?

**Comment by hadley** [comment]
Yes, you can use `select()` + `where()` for this sort of task:

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars |> 
  as_tibble() |> 
  select(where(\(col) all(col > 5)))
#> # A tibble: 32 × 4
#>      mpg  disp    hp  qsec
#>    <dbl> <dbl> <dbl> <dbl>
#>  1  21    160    110  16.5
#>  2  21    160    110  17.0
#>  3  22.8  108     93  18.6
#>  4  21.4  258    110  19.4
#>  5  18.7  360    175  17.0
#>  6  18.1  225    105  20.2
#>  7  14.3  360    245  15.8
#>  8  24.4  147.    62  20  
#>  9  22.8  141.    95  22.9
#> 10  19.2  168.   123  18.3
#> # … with 22 more rows
```

<sup>Created on 2022-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
