### ISSUE TITLE
Feedback for alternate names for `reframe()`

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#6565]
In https://github.com/tidyverse/dplyr/pull/6557 we implemented `reframe()`, which allows us to deprecate the `summarise()` feature that allowed it to return per-group results of size 0 or >1, as requested by https://github.com/tidyverse/dplyr/issues/6382

In https://github.com/tidyverse/dplyr/issues/6382, we had a large amount of discussion about the name of this new function. That issue also documents a number of assumptions about how this function should be used. We were never able to come up with a name that we were 100% happy with, but `reframe()` seemed like the least worst option.

It has some nice connections to `tibble::enframe()` and `tibble::deframe()` https://github.com/tidyverse/dplyr/issues/6382#issuecomment-1323866603

Until dplyr 1.1.0 is released, this issue will stay open to gather feedback about this name.

- Feel free to leave comments with additional suggestions
- Leave a 👍 reaction on this comment if you like this name
- Leave a 👎 reaction if you strongly disagree with this name

**Comment by wurli** [comment]
Thinking about it more, I actually quite like `reframe()` as a name when I think about it in terms of its everyday meaning:

> _reframe_: frame or express (words or a concept or plan) differently.
"I reframed my question"

This has a nice correspondence with the literary meaning of `summarise()`

> _summarise_: give a brief statement of the main points of (something).
"these results can be summarized in the following table"

`reframe()` is different, `summarise()` is less.

**Comment by jl5000** [comment]
My suggestion is collapse().

**Comment by mcsnowface** [comment]
How about `condense()`?

**Comment by DavisVaughan** [comment]
For those offering names that imply a _direction_, like `collapse()` or `condense()`, note that this new verb doesn't have any restrictions on the number of rows returned per group. In particular, it is perfectly acceptable and common to return _more_ rows than you started with, so we don't want a name that implies some kind of shrinking. The ivs examples here are good cases of this https://github.com/tidyverse/dplyr/issues/6382#issuecomment-1328256952

**Comment by cgoo4** [comment]
Maybe `morph` as extracted from metamorphosis:

>  The action or process of changing in form, shape or substance.

I do like `reframe` but wonder if another 'frame might be confusing given `enframe` and `deframe`.

**Comment by DavisVaughan** [comment]
@cgoo4 we previously used `morph()` but it never felt quite right and was already taken by `tidygraph::morph()` which heavily uses dplyr.

We actually partially picked `reframe()` _because_ of its connection to `enframe()` and `deframe()`, see https://github.com/tidyverse/dplyr/issues/6382#issuecomment-1323866603

**Comment by mcsnowface** [comment]
@DavisVaughan That makes sense. Some other verbs that come to mind are `pack()` or `bundle()`. It still suggest some sort of grouping and packaging up but not in a way of reducing the overall size, like a warehouse that can grow as more stuff is being bundled up in it.

**Comment by mcsnowface** [comment]
Two other verbs I haven't seen yet is to `spawn()` as in to "bring forth", or to "generate", or to `modulate()` as in passing from one state to another.

**Comment by bwiernik** [comment]
Personally, the alternatives suggested so far in this thread feel far too opaque. None of them clearly suggest what the function--I would have a hard time understanding what is happening when reading that in new code.

**Comment by eutwt** [comment]
I like `create()` better than the others, for the reasons originally given
https://github.com/tidyverse/dplyr/issues/6382#issuecomment-1328258712
https://github.com/tidyverse/dplyr/issues/6382#issuecomment-1329072022

I also get the same feeling as @bwiernik that the names so far don't really convey much info about what this function does.
Actually I think we probably *can't* come up with a verb that describes what it does, because it could do several things (summarise, select, transmute, explode). What we can settle for is to at least choose a name which conveys the fact that there are many possibilities, and it seems several people in the previous thread do get that feeling from `create()`.

**Comment by msberends** [comment]
`summarise2()` is it then! 😂😂

**Comment by cgoo4** [comment]
_reimagine_: consider something in a new and creative way, e.g. as grouped quartiles?

**Comment by cathblatter** [comment]
`form()` as middle ground between `create()` (too open) and `reframe()` (too technical/restricted)?

**Comment by mcsnowface** [comment]
I also think `create()` goes in the right direction but sounds a bit boring compared to the other dplyr verbs. How about `evolve()` instead? First you `mutate()` then you `evolve()`?

**Comment by allenbaron** [comment]
I don't favor `reframe()` because it sounds like it's just a data reshaping operation but this can actually change the data. I think `evolve()` is a great idea. It matches nicely with `mutate()`, at least when considering these words in the domain of biology where evolution can be a single mutation or involve more complex changes that make similar things look very different (e.g. mammalian ancestor -> whales & mice).

**Comment by mcsnowface** [comment]
Plus `evolve()` doesn't imply a direction  - it represents an adaptive process by the analyst to a given context.

**Comment by markfairbanks** [comment]
Maybe `adapt()`? Or `alter()`?

**Comment by sda030** [comment]
> How about `adapt()`?

Seems a bit too vague to me. Think I prefer `evolve()`, a more complex mutate. Also, I'm concerned about the confusion arising in teaching/explaining the function. "For solving this problem we can adapt ... ehm ... we can _use_ `adapt()`."

**Comment by arnaudgallou** [comment]
I personally like both `reframe` and `evolve` but here're a few more suggestions:
- `alchemize`, might not be the most pleasing word to the ear but it looks fun, has the same length and ending as `summarize`. Plus it conveys the idea of transforming an object with something else without exactly knowing the attributes (size, dimension, etc.) of the output in advance, like a per-group results of any length.
- `transmute` to keep a similar root with mutate.
- Possibly `recombine`.

**Comment by devillemereuil** [comment]
I like `reframe` more than `evolve` which I would fear to be too cryptic for newcomers.

But since the function can greatly impact the structure of a data.frame and change it into something completely new (especially if the called functions return data.frames), why not something along `overhaul` or `rebuild` ? It would make it crystal clear that it is difficult to have strong expectations about the structure of the returned tbl based on the input tbl.

**Comment by arnaudgallou** [comment]
`recast` might cause confusion among people using the `vctrs` package which has a `vec_cast` function that performs type conversion.

More suggestions to complete my previous ones:
- `forge`
- `mold`

**Comment by davidchall** [comment]
> - `alchemize`, might not be the most pleasing word to the ear but it looks fun, has the same length and ending as `summarize`. Plus it conveys the idea of transforming an object with something else without exactly knowing the attributes (size, dimension, etc.) of the output in advance, like a per-group results of any length.

I recoiled from `alchemize` when I first heard it, but the more I think about it the more I like it.

**Comment by DavisVaughan** [comment]
Thanks everyone for your feedback! We have decided to keep `reframe()` as the final name for this operation. We really appreciate your responses. Below I'll list some rationale for not choosing some of these names:

- `morph()`, this is already used in tidygraph
- `forge()` and `mold()` are already used by the tidymodels package hardhat
- `pack()` is already used by tidyr
- `evolve()` was a nice suggestion, but we feel it is too close to the idea of taking a data frame and _slightly_ tweaking/mutating it to create a new one, and that really isn't the case. This generally creates a completely new data frame that doesn't look similar to the original one. It is more similar to `summarise()` and `do()` than to `mutate()`.
- `alchemize()` sounds a bit too cryptic and is probably fairly hard to teach.

---

We like `reframe()` because:

- No one has seemed _horribly_ confused by it
- A few of us really like it quite a bit
- The connection to `tibble::enframe()` and `tibble::deframe()` outlined here https://github.com/tidyverse/dplyr/issues/6382#issuecomment-1323866603 is really nice, and is something we will add to the documentation.
