### ISSUE TITLE
Argument `multiple=` no longer exists in mutating joins of dplyr v.1.0.10

### ISSUE THREAD

**Issue by mc-unimi** [tidyverse/dplyr#6568]
I had scripts no longer working for apparently inexplicable reasons when at last I've found that the last dplyr v.1.0.10 has silently suppressed the `multiple=` argument in mutating joins (inner/left/right/full etc.), used to deal with duplicated rows.

The online help does not mention it and I've found no notice about that change. 
Are there reasons for this silent suppression? Is it to consider permanent in future releases?

**Comment by hadley** [comment]
That argument is only available in the dev version.
