### ISSUE TITLE
issue using regex quantiriers in str_glue when used in str_extract

### ISSUE THREAD

**Issue by jic007** [tidyverse/dplyr#6586]
an issue combining quantifiers in str_glue()

str_extract(

str_glue("({variable}\\s*)(\\w)*\\s*\\d{1,3}", .na = "")

)

can't seem to make the quantifiers {1,3} work in this context

thank you

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by jic007** [comment]
Thank you Hadly for this. Below is an example


library(tidyverse)

df <- tibble::tribble(
                                                           ~text, ~expected_output,    ~key,
               "contract ref John 00/2020 is a reference number",        "00/2020",  "John",
       "some references look like contract ref  Hadly 9393/2022",      "9393/2022", "Hadly",
    "others can be contract ref Ahmad 2-2019 which is confusing",         "2-2019", "Ahmad"
    )


df %>% 
    mutate(extract = str_glue("(?<=contract ref){key}(\\d{1,4}[/-]\\d{4}"))

**Comment by hadley** [comment]
When I attempt to run that, I get the error "\d" is an unrecognised escape; that is the first problem that you will need to fix. You might finding reading something like https://r4ds.hadley.nz/regexps.html to be a good place to start.

**Comment by jic007** [comment]
Hi sorry about that

now got the code working; only quantifiers are the issue
library(tidyverse)

df <- tibble::tribble(
    ~text, ~expected_output,    ~key,
    "contract ref John 00/2020 is a reference number",        "00/2020",  "John",
    "some references look like contract ref Hadly 9393/2022",      "9393/2022", "Hadly",
    "others can be contract ref Ahmad 2-2019 which is confusing",         "2-2019", "Ahmad"
)


# code works with regex
df %>% 
    mutate(testing_extract = text %>% str_extract("(?<= contract ref\\s)(Hadly|Ahmad)\\s\\d*[-/]\\d*"))

# code works with regex and variable name
df %>% 
    mutate(extract = str_extract(text, str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d*")))

# code breaks when quantifers are added
df %>% 
    mutate(extract = str_extract(text, str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d{2,4}")))

**Comment by jic007** [comment]
Hi Hadly, 
thank you for the advice about reprex()
I got the code working with a workaround by using paste0 in conjunction with the str_glue(), please refer to the last code chunk, any ideas how to encapsulate all quantifiers  in str_glue()?

library(reprex)
#> Warning: package 'reprex' was built under R version 4.2.2
library(tidyverse)
#> Warning: package 'tidyverse' was built under R version 4.2.2
#> Warning: package 'ggplot2' was built under R version 4.2.2
#> Warning: package 'tibble' was built under R version 4.2.2
#> Warning: package 'tidyr' was built under R version 4.2.2
#> Warning: package 'readr' was built under R version 4.2.2
#> Warning: package 'purrr' was built under R version 4.2.2
#> Warning: package 'dplyr' was built under R version 4.2.2
#> Warning: package 'stringr' was built under R version 4.2.2
#> Warning: package 'forcats' was built under R version 4.2.2


df <- tibble::tribble(
  ~text, ~expected_output,    ~key,
  "this contract ref Smith 001/2020 is a reference number",        "00/2020",  "Smith",
  "some references look like contract ref Hadly 9393/2022",      "9393/2022", "Hadly",
  "others can be contract ref Ahmad 2-2019 which is confusing",         "2-2019", "Ahmad"
)


# code works with regex
df %>% 
  mutate(testing_extract = text %>% str_extract("(?<= contract ref\\s)(Hadly|Ahmad)\\s\\d*[-/]\\d*"))
#> # A tibble: 3 × 4
#>   text                                                     expec…¹ key   testi…²
#>   <chr>                                                    <chr>   <chr> <chr>  
#> 1 this contract ref Smith 001/2020 is a reference number   00/2020 Smith <NA>   
#> 2 some references look like contract ref Hadly 9393/2022   9393/2… Hadly Hadly …
#> 3 others can be contract ref Ahmad 2-2019 which is confus… 2-2019  Ahmad Ahmad …
#> # … with abbreviated variable names ¹​expected_output, ²​testing_extract

# code works with regex and variable name
df %>% 
  mutate(extract = str_extract(text, str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d*")))
#> # A tibble: 3 × 4
#>   text                                                     expec…¹ key   extract
#>   <chr>                                                    <chr>   <chr> <chr>  
#> 1 this contract ref Smith 001/2020 is a reference number   00/2020 Smith Smith …
#> 2 some references look like contract ref Hadly 9393/2022   9393/2… Hadly Hadly …
#> 3 others can be contract ref Ahmad 2-2019 which is confus… 2-2019  Ahmad Ahmad …
#> # … with abbreviated variable name ¹​expected_output

# code breaks when quantifers are added
df %>% 
  mutate(extract = str_extract(text, str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d{2,4}")))
#> Error in `mutate()`:
#> ! Problem while computing `extract = str_extract(text, str_glue("(?<=
#>   contract ref\\s)({key})\\s\\d*[-/]\\d{2,4}"))`.
#> Caused by error in `parse()`:
#> ! <text>:1:2: unexpected ','
#> 1: 2,
#>      ^

#> Backtrace:
#>      ▆
#>   1. ├─df %>% ...
#>   2. ├─dplyr::mutate(., extract = str_extract(text, str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d{2,4}")))
#>   3. ├─dplyr:::mutate.data.frame(., extract = str_extract(text, str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d{2,4}")))
#>   4. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
#>   5. │   ├─base::withCallingHandlers(...)
#>   6. │   └─mask$eval_all_mutate(quo)
#>   7. ├─stringr::str_extract(text, str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d{2,4}"))
#>   8. │ └─stringr:::type(pattern)
#>   9. ├─stringr::str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d{2,4}")
#>  10. │ └─glue::glue(..., .sep = .sep, .envir = .envir)
#>  11. │   └─glue::glue_data(...)
#>  12. ├─glue (local) `<fn>`("2,4")
#>  13. │ ├─.transformer(expr, env) %||% .null
#>  14. │ └─glue (local) .transformer(expr, env)
#>  15. │   ├─base::eval(parse(text = text, keep.source = FALSE), envir)
#>  16. │   └─base::parse(text = text, keep.source = FALSE)
#>  17. └─base::.handleSimpleError(...)
#>  18.   └─dplyr (local) h(simpleError(msg, call))
#>  19.     └─rlang::abort(...)


# now using paste0 in addition to the argument got it working
df %>% 
  mutate(extract = str_extract(text, paste0(str_glue("(?<= contract ref\\s)({key})\\s\\d*[-/]\\d"),"{1,4}")))
#> # A tibble: 3 × 4
#>   text                                                     expec…¹ key   extract
#>   <chr>                                                    <chr>   <chr> <chr>  
#> 1 this contract ref Smith 001/2020 is a reference number   00/2020 Smith Smith …
#> 2 some references look like contract ref Hadly 9393/2022   9393/2… Hadly Hadly …
#> 3 others can be contract ref Ahmad 2-2019 which is confus… 2-2019  Ahmad Ahmad …
#> # … with abbreviated variable name ¹​expected_output
