### ISSUE TITLE
.by column is always named .by and appears at the end

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#6588]
The result of using `.by` is that the grouping column is always called `.by`.  A meaningful name would be preferred.  Also it always comes at the end, i.e. last column in the output, but I think most people would expect it to come at the beginning. Also why di this return 7 rows?
```
library(dplyr)
packageVersion("dplyr")
## [1] ‘1.0.10’

# https://www.tidyverse.org/blog/2022/11/dplyr-1-1-0-is-coming-soon/
expenses <- tibble(
  id = c(1, 2, 1, 3, 1, 2, 3),
  region = c("A", "A", "A", "B", "B", "A", "A"),
  cost = c(25, 20, 19, 12, 9, 6, 6)
)

expenses |>
   summarise(cost = mean(cost), .by = region)
## # A tibble: 7 × 2
##    cost .by    <------------------------------------------------------------
##   <dbl> <chr>
## 1  13.9 A    
## 2  13.9 A    
## 3  13.9 A    
## 4  13.9 B    
## 5  13.9 B    
## 6  13.9 A    
## 7  13.9 A    
```

**Comment by hadley** [comment]
Did you restart R?

**Comment by ggrothendieck** [comment]
That isn't part of the instructions at the link but I just tried it and got the same result.  Maybe that blog post could be fixed.

**Comment by hadley** [comment]
I'm pretty sure pak reminds you to restart R if the package is already loaded; it's just that the instruction doesn't come at quite the right time.

**Comment by ggrothendieck** [comment]
The restarting isn't the problem since I restarted R and got the same output.
