### ISSUE TITLE
bind_cols() accepts combining lenghts 0 and 1

### ISSUE THREAD

**Issue by LukasWallrich** [tidyverse/dplyr#6589]
Based on the help, the example, and the suggested equivalence with do.call(), I would have expected the following to fail. Instead, it silently returns an unexpected length 0 result. If this is expected, could it be clarified?

``` r
library(dplyr)
library(tibble)

# Would expect this to fail ...
bind_cols(tibble(), tibble(1))
#> # A tibble: 0 × 1
#> # … with 1 variable: 1 <dbl>

# ... in line with this
cbind(tibble(), tibble(1))
#> Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 0, 1
```

<sup>Created on 2022-12-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
This is the tidyverse recycling rules: https://vctrs.r-lib.org/articles/type-size.html#common-sizes-recycling-rules
