### ISSUE TITLE
Slow n_distinct performance dplyr 1.0.10 with base R 4.2.1 or R 4.2.2

### ISSUE THREAD

**Issue by omarwh** [tidyverse/dplyr#6593]
---

n_distinct using parameter na.rm = TRUE has slow performance on data set of  of 526K, function takes 10-15 minutes to return a value.
If parameter na.rm = FALSE  is used a result is return in less than 1 minute.
```r
#  data is 526K rows
data %>% 
group_by(col1) %>%
summarise(count=n_distinct(col2,na.rm=TRUE))
```

**Comment by hadley** [comment]
This is likely to be fixed in the dev version. I can't tell for sure because you didn't provide a reprex.

**Comment by omarwh** [comment]
Thanks for the response. See reprex below with start and end times:

```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
df_test <- data.frame (col1  = 1:300000,
                       col2 =  1:300000
)
Sys.time()
#> [1] "2022-12-12 12:18:37 -05"
df_test %>%
  group_by(col1) %>%
  summarise(count = n_distinct(col2,na.rm = TRUE)) 
#> # A tibble: 300,000 × 2
#>     col1 count
#>    <int> <int>
#>  1     1     1
#>  2     2     1
#>  3     3     1
#>  4     4     1
#>  5     5     1
#>  6     6     1
#>  7     7     1
#>  8     8     1
#>  9     9     1
#> 10    10     1
#> # … with 299,990 more rows
Sys.time()
#> [1] "2022-12-12 13:54:49 -05"
```

**Comment by omarwh** [comment]
OK so this issue is seems to be with occuring when using dplyr with vctrs 0.5.1 (latest version) . 
dplyr  group_by  runs in normal expect time on vctrs version 0.4.1.
So this issue occured in dplyr  when I upgraded from vctrs 0.4.1 to 0.5.1
