### ISSUE TITLE
Feedback on `join_by()` helpers

### ISSUE THREAD

**Issue by davidchall** [tidyverse/dplyr#6595]
Following up on the [call for feedback on dplyr 1.1.0](https://www.tidyverse.org/blog/2022/11/dplyr-1-1-0-is-coming-soon/)...

The new `join_by()` function supports helpers `between()`, `within()`, and `overlaps()` for working with numeric ranges. I have two pieces of feedback on the `within()` helper:

* This function name is provided by base R, so roxygen is creating links from the [dplyr docs](https://dplyr.tidyverse.org/dev/reference/join_by.html) to the [base R function](https://rdrr.io/r/base/with.html). This might cause some confusion for end users. I think these links can be prevented though.
* The name "within" has a lot of meanings in different scenarios, but the implementation is very specific to numeric ranges. I'm a bit worried we might be boxing ourselves into a corner if we want to provide more `join_by()` helpers in future. For example, "within" is often used to check membership (e.g., [`ipaddress::is_within()`](https://davidchall.github.io/ipaddress/reference/address_in_network.html)). I'm unfamiliar with your plans for `join_by()`, but I'm wondering if this should be renamed as `range_within()`?

Looking forward to the new release - congrats! 🎉

**Comment by DavisVaughan** [comment]
@davidchall we've decided to keep `within()` because it is still just the most natural and short name for this operation

We are going to attempt to improve the links as much as we can though (#6661)
