### ISSUE TITLE
does .by support slice_max function?

### ISSUE THREAD

**Issue by CNUlichao** [tidyverse/dplyr#6611]
.by is a very good feature, but I find that it doesn't work on slice_max function.

My code is as follows.

```r
expenses <- tibble(
      id = c(1, 2, 1, 3, 1, 2, 3),
      region = c("A", "A", "A", "B", "B", "A", "A"),
      cost = c(25, 20, 19, 12, 9, 6, 6)
)

expenses %>%
      group_by(region) %>%
      slice_max(cost, n = 2)

expenses %>%
     slice_max(cost, n = 2, .by = region)
```

The error message:

Error in `slice_max()`:
! `...` must be empty.
✖ Problematic argument:
• .by = region
Run `rlang::last_error()` to see where the error occurred.

**Comment by DavisVaughan** [comment]
It does but the argument name is `by`, consistent with all of the other arguments to `slice_max()` that don't have a `.`. We only add the `.` when we have to (i.e. when the function accepts possibly named `...` where there might be risk of collision)
