### ISSUE TITLE
Document `cur_data()` and `cur_data_all()`

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#6616]
They're superseded, but don't seem to appears in the docs.

**Comment by DavisVaughan** [comment]
<img width="956" alt="Screen Shot 2022-12-16 at 3 12 28 PM" src="https://user-images.githubusercontent.com/19150088/208181485-120e1f12-600d-4ee0-8863-b4d6abc94b44.png">

?

**Comment by hadley** [comment]
Oh hmmmm, I think I got caught out by a pkgload / topic caching bug.
