### ISSUE TITLE
Column label attribute for new variable in `mutate()` incorrectly inherited

### ISSUE THREAD

**Issue by ddsjoberg** [tidyverse/dplyr#6626]
When a new column is create using `mutate()`, the new variable incorrectly is inheriting the column label attribute from one of the source variables.

In the example below, I've assigned column label attributes to the first two columns of the `mtcars` dataset. When I create a third variable that is the sum of the first two, `mutate()` assigns a column label to the new variable incorrectly. Example below.

Thank you!

``` r
packageVersion("dplyr")
#> [1] '1.0.10'
packageVersion("vctrs")
#> [1] '0.5.1'

mtcars2 <- mtcars[,1:2] 
attr(mtcars2$mpg, "label") <- "Miles per Gallon"
attr(mtcars2$cyl, "label") <- "Number of Cylinders"

mtcars2 |> 
  dplyr::mutate(
    new_var_with_wrong_label = mpg + cyl
  ) |> 
  purrr::map(~attr(.x, "label"))
#> $mpg
#> [1] "Miles per Gallon"
#> 
#> $cyl
#> [1] "Number of Cylinders"
#> 
#> $new_var_with_wrong_label
#> [1] "Miles per Gallon"
```

<sup>Created on 2022-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
This isn't anything to do with dplyr:

``` r
mtcars2 <- mtcars[,1:2] 
attr(mtcars2$mpg, "label") <- "Miles per Gallon"
attr(mtcars2$cyl, "label") <- "Number of Cylinders"

attributes(mtcars2$mpg + mtcars2$cyl)
#> $label
#> [1] "Miles per Gallon"
```

<sup>Created on 2022-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Apologies for the incorrect posting here, and thank you for education.
