### ISSUE TITLE
na_if can't convert character to date, and throws error 

### ISSUE THREAD

**Issue by hideaki** [tidyverse/dplyr#6628]
I'm getting this error from na_if, if I specify a Date value as a character, which I did not get with dplyr 1.0.10.

```r
tibble::tibble(d=as.Date("2022-01-01")) %>% mutate(d=na_if(d, "2022-01-01"))
# Error in `mutate()`:
# ℹ In argument: `d = na_if(d, "2022-01-01")`.
# Caused by error in `na_if()`:
# ! Can't convert `y` <character> to match type of `x` <date>.
```

**Comment by hadley** [comment]
This is deliberate as previously the date was converted to a string, which meant code like `na_if(d, "2022-30-30"))` would silently not work.
