### ISSUE TITLE
case_when gives low-level error for mismatched types 'numeric', 'dvec'.

### ISSUE THREAD

**Issue by bergsmat** [tidyverse/dplyr#6632]
Thanks for a great package!

I am using case_when() with mismatched types, e.g. 'numeric' for one condition and 'dvec' (vctrs object from package 'yamlet') for a second condition.  I expect an informative error indicating mismatched types.  Instead, I see an error about 'names' attribute.  It looks to me like case_when() calls replace_with( name = NULL, ...); then replace_with() calls check_class(header = name), which calls glue(), giving a length-zero non-null message that is passed to rlang::abort().  Apologies in advance if I'm missing something obvious.  (Perhaps normally one expects check_type() to have aborted already, but both 1 and as_dvec(1) have typeof() 'double'.)

```r
library(yamlet)
#> 
#> Attaching package: 'yamlet'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
case_when(c(TRUE, FALSE) == TRUE ~ 1, TRUE  ~ as_dvec(1))
#> Error in names(message) <- `*vtmp*`: 'names' attribute [1] must be the same length as the vector [0]
Created on 2023-01-04 with reprex v2.0.2
```

**Comment by hadley** [comment]
This is fixed in the dev version:

``` r
library(yamlet, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)

case_when(c(TRUE, FALSE) == TRUE ~ 1, TRUE  ~ as_dvec(1))
#> [1] 1 1
```

<sup>Created on 2023-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
