### ISSUE TITLE
Joining columns with list content returns NULL instead of NA

### ISSUE THREAD

**Issue by TimBMK** [tidyverse/dplyr#6635]
I noticed that, when joining data that has list content, unmatched rows in left_join() produce NULL values rather than the NA values common for all other datatypes. 

This potentially creates downstream issues, as replacing the NULLs with NAs for consistent behaviour is relatively expensive (go-to functions like na_if() usually struggle with this type of nested list column).

There may be a work-around in the join family I'm not seeing, but this does seem like unintended and incosistent behaviour.

Reprex:
```r
test_1 <- tibble(id = c("1611030457298161665", "1611079838563184641"))

test_2 <- tibble(id = "1611030457298161665", content = list(c("this", "is", "a", "list")))

test_3 <- tibble(id = "1611030457298161665", content = "not a list")

left_join(test_1, test_2, by = "id)

left_join(test_1, test_3, by = "id)
```
Results:
```
  id                  content  
  <chr>               <list>   
1 1611030457298161665 <chr [4]>
2 1611079838563184641 <NULL> 

  id                  content   
  <chr>               <chr>     
1 1611030457298161665 not a list
2 1611079838563184641 NA 
```

**Comment by hadley** [comment]
This is deliberate: `NULL`s are the equivalent of `NA`s for lists, and at least in the dev version of dplyr, all functions know about this:

``` r
library(dplyr, warn.conflicts = FALSE)

x <- list(1, 2, NULL)

str(na_if(x, list(2)))
#> List of 3
#>  $ : num 1
#>  $ : NULL
#>  $ : NULL
str(coalesce(x, list(0)))
#> List of 3
#>  $ : num 1
#>  $ : num 2
#>  $ : num 0
```

<sup>Created on 2023-01-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by TimBMK** [comment]
Thanks for the explanation, that makes sense. Also, thanks for the pointer towards the coalesce() function I was not aware of.

For anyone looking for an easy solution to convert all NULLs to NAs in a dataset with lists after na_if() no longer works (due to the type checking):

```r
data %>% mutate(across(.cols = where(is.list), ~ coalesce(., list(NA)))) 
```

This can be helpful for e.g. filtering, as is.null() does not recognize a list with NULL as its first element (the result of the joins) as TRUE, whereas is.na() does for its NA equivalent. Therefore, replacing NULLs with NAs can be helpful for typical operations such as filter(!is.na(var))
