### ISSUE TITLE
Support a 0-length array result in summarize, when working on an empty DataFrame

### ISSUE THREAD

**Issue by machow** [tidyverse/dplyr#6637]
Currently, afaict dplyr handles summarizing an empty dataframe as follows:

* for each argument:
* apply the given calculation, using the empty dataframe
* use the result type to produce a new 0-length column, but ~~discard its value~~ (edit: grouped summarize discards the value, ungrouped summarize keeps it)
* if the result is length 0 or > 1, print a deprecation warning

This results in a sort of funky situation where operations like `+` raise a warning, because `integer() + 1` results in a 0-length array. I wonder if a 0-length result when summarizing an empty data.frame should not be deprecated? It seems like there is already some special behavior around empty frames, and some operations returning 0-length results is likely in this case :/.

``` r
library(tidyverse)

df <- tibble(a = integer())

integer() + 1
#> numeric(0)

df %>% summarize(b = sum(a))
#> # A tibble: 1 × 1
#>       b
#>   <int>
#> 1     0

df %>% summarize(b = a + 1)
#> Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
#> dplyr 1.1.0.
#> ℹ Please use `reframe()` instead.
#> ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
#>   always returns an ungrouped data frame and adjust accordingly.
#> # A tibble: 0 × 1
#> # … with 1 variable: b <dbl>
```

<sup>Created on 2023-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

related to https://github.com/machow/siuba/issues/467

**edit:** wait -- I just noticed ungrouped summarize keeps the value, but grouped summarize discards it...

``` r
library(tidyverse)

df <- tibble(a = integer())

df %>% group_by(a) %>% summarize(b = sum(a))
#> # A tibble: 0 × 2
#> # … with 2 variables: a <int>, b <int>
```

<sup>Created on 2023-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I think those results are consistent:

* An ungrouped summarise always returns 1 row
* A grouped summarise always return 1 row per group

`+` isn't a summarise operations so I'm not surprised we get some weirdness here.

**Comment by machow** [comment]
That's fair--I'm still trying to wrap my head around this, but something feels a bit inconsistent. For example, mutate on an empty frame allows either 0 or 1 row...

``` r
library(tidyverse)

df <- tibble(a = integer())

df %>% mutate(b = integer())
#> # A tibble: 0 × 2
#> # … with 2 variables: a <int>, b <int>

df %>% mutate(b = 1)
#> # A tibble: 0 × 2
#> # … with 2 variables: a <int>, b <dbl>
```

<sup>Created on 2023-01-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

As long as aggregation functions always return a single value, when they're given empty data, then it seems like the current behavior shouldn't be a problem for summarize?

**Comment by hadley** [comment]
Yeah, because `mutate()` obeys the recycling rules, which allows a length-1 vector to be expanded or shrunk to any size.

**Comment by machow** [comment]
Okay, thanks, this is all super helpful. Knowing that aggregate functions should always return some 1-length value, even when given empty data was the missing piece!

**Comment by DavisVaughan** [comment]
> and that recycling can also reduce a 1-length value to 0-length

@machow these recycling rules are actually the same as the broadcasting rules used by numpy, if you want a Python connection https://numpy.org/doc/stable/user/basics.broadcasting.html#general-broadcasting-rules
