### ISSUE TITLE
Mark `nest_by()` and `group_*()` as questioning rather than experimental

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#6639]
- Since we will probably have `nest(.by =)` in tidyr
- And the `group_*()` family doesn't fit super well in conjunction with the new dplyr `.by` ideas

**Comment by manhnguyen48** [comment]
Hi, `dplyr::nest_by` returns a rowwise data frame while `tidyr::nest(.by=)` doesn't. Those are useful to organise tibbles within tibble and not having to use `purrr::map` on every `mutate `calls. If `nest_by` is being phased out perhaps `tidyr::nest()` could gain a `.rowwise=TRUE` argument for backward compatibility?

**Comment by hadley** [comment]
@manhnguyen48 we are considering a different way to achieve a `rowwise()` since `mutate()` is really the only function that `rowwise()` affects, suggesting that creating a custom class isn't the right approach here.
