### ISSUE TITLE
sleuth package- `select_()` was deprecated in dplyr 0.7.0.

### ISSUE THREAD

**Issue by AlexGaithuma** [tidyverse/dplyr#6641]
ℹ Please use `select()` instead.
ℹ The deprecated feature was likely used in the dplyr package.
  Please report the issue at <https://github.com/tidyverse/dplyr/issues>.

**Comment by DavisVaughan** [comment]
This message should have told you to go open an issue on the {sleuth} package site. The fact that it told you to open an issue on dplyr was our fault, which I've fixed here https://github.com/tidyverse/dplyr/pull/6643.

I think you should open an issue on the sleuth issues page and tell them to switch from `select_()` to `select()` https://github.com/search?q=repo%3Apachterlab%2Fsleuth%20select_&type=code
