### ISSUE TITLE
by vs .by in slice_*

### ISSUE THREAD

**Issue by jonthegeek** [tidyverse/dplyr#6647]
Is it intentional that `slice_head()`, `slice_tail()`, `slice_min()`. and `slice_max()` use `by` instead of `.by`? As of #6558 you HAVE to use `by` for those variants (rather than `.by`), but I can't figure out why they're different. Using `.by` throws an error:

``` r
# remotes::install_github("tidyverse/dplyr")
library(dplyr, warn.conflicts = FALSE)

# Works
mtcars |> 
  slice_max(mpg, n = 1, by = "vs")
#>                 mpg cyl  disp hp drat    wt qsec vs am gear carb
#> Porsche 914-2  26.0   4 120.3 91 4.43 2.140 16.7  0  1    5    2
#> Toyota Corolla 33.9   4  71.1 65 4.22 1.835 19.9  1  1    4    1

# Fails
mtcars |> 
  slice_max(mpg, n = 1, .by = "vs")
#> Error in `slice_max()`:
#> ! `...` must be empty.
#> ✖ Problematic argument:
#> • .by = "vs"

#> Backtrace:
#>     ▆
#>  1. ├─dplyr::slice_max(mtcars, mpg, n = 1, .by = "vs")
#>  2. └─dplyr:::slice_max.data.frame(mtcars, mpg, n = 1, .by = "vs")
#>  3.   └─rlang::check_dots_empty0(...)
#>  4.     └─rlang::check_dots_empty(call = call)
#>  5.       └─rlang:::action_dots(...)
#>  6.         ├─base (local) try_dots(...)
#>  7.         └─rlang (local) action(...)
```

<sup>Created on 2023-01-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Originally reported by a confused user on the [R4DS Slack](https://rfordatascience.slack.com/archives/C01SHS2Q9HV/p1674159212080249).

**Comment by DavisVaughan** [comment]
The signature of `slice_max()` is:

```r
slice_max(
  .data,
  order_by,
  ...,
  n,
  prop,
  by = NULL,
  with_ties = TRUE,
  na_rm = FALSE
)
```

In general we only add `.` to an argument name if we _have to_. We add `.` to a name in the cases where the function takes `...` and those dots can be named, like `df %>% mutate(foo = bar + 1, .keep = "unused")`. If we didn't add a `.` in front of `.keep`, then it has a high probability to collide with user input if they try to provide a column named `keep`.

In the case of `slice_max()`, the dots must be empty. They are only there to force optional arguments to be specified by name. So all of the arguments there _don't_ have a `.` in their name. The fact that `.data` does is a historical accident and is unfortunately hard to change today.

I think making the argument `.by` in `slice_max()` when `n` and `prop` and `with_ties` all _don't_ have a `.` would be fairly inconsistent and look pretty weird

**Comment by jonthegeek** [comment]
It's also inconsistent that it's ".by" everywhere else, though (and almost everywhere in the docs). If both were accepted it wouldn't be a big deal, but I expect we'll need a set reply about this on r4ds; I think a lot of people will make this mistake and not understand why their code isn't working.

**Comment by hadley** [comment]
@DavisVaughan but maybe it's worth a custom error message here? I think Jon is right that a lot of people (e.g. me) will trip over this.

**Comment by DavisVaughan** [comment]
I'm working on expanding out the docs for sure. I'll also look into adding better error messages

**Comment by DavisVaughan** [comment]
It is tough to add a good error message for `mutate(by = )` because that is a valid column name. Same problem for `summarise()` and `reframe()`.

We can definitely add good errors for `filter()` and the `slice()` family though, since those shouldn’t have named dots at all.

Maybe that would take care of most of the issues since `.by` is what most people will try and reach for, and `mutate/summarise/reframe()` all consistently use `.by`, so really `slice(.by = )` vs `slice_max(by = )`  is what people will trip over?

**Comment by hadley** [comment]
Yeah, I think it's only really needed for `slice()` since it uses `by` instead of `.by`.
