### ISSUE TITLE
The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.

### ISSUE THREAD

**Issue by dxtxs1** [tidyverse/dplyr#6664]
The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
 The deprecated feature was likely used in the dplyr package.
---

Having a group by issue with combining data.
---

--- Code:

names(laborfile)<-gsub(" ", "", tolower(names(laborfile)))
library(tidyr)
laborwide<-spread(laborfile %>%
                    group_by(.dots=c("site", "deptidtype", "deptname", "date", "trc")) %>%
                    summarize(hours=sum(quantity)), trc, hours) %>%
  mutate(DBL=if_else(is.na(DBL), 0, DBL)) %>%
  mutate(OVT=if_else(is.na(OVT), 0, OVT)) %>%
  mutate(REG=if_else(is.na(REG), 0, REG)) %>%
  mutate(TRN=if_else(is.na(TRN), 0, TRN)) %>%
  mutate(TOTALHOURS=DBL+OVT+REG+TRN)
```

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
