### ISSUE TITLE
Advice in compatibility.html vignette is wrong

### ISSUE THREAD

**Issue by gavinsimpson** [tidyverse/dplyr#6668]
The Compatibility vignette suggests that using `pkg::foo()` is an option instead of using `importFrom` in situations where there are namespace differences between the current and development versions of dplyr that a package author is trying to support.

The vignette claims this will raise a NOTE, but that this is largely harmless. Doing as advised in the vignette will actually raise a WARNING, however, not a NOTE, and this will fail checks on CI systems like GitHub Actions (causing an error) and will be a much harder sell on CRAN (and certainly slow down submissions as manual intervention will almost certainly be required for a WARNING).

For example, when trying to handle the deprecation in `summarise()` of results of more than one row per group and reimplementation of this in `reframe()`, using 

```r
...
#' @importFrom dplyr summarise
...
if (utils::packageVersion("dplyr") > "1.0.10") {
  dplyr::reframe(...)
} else {
  summarise(...)
}
...
```

Causes warnings:

```
* checking dependencies in R code ... WARNING
Missing or unexported object: 'dplyr::reframe'
```

~~I would suggest removing this suggestion, or at the very least correct it and include a big warning to unsuspecting users that WARNINGs will cause difficulties for CRAN.~~

**Comment by hadley** [comment]
I think we can just update the suggestion, rather than removing it. Something must have changed in the time since we wrote it.

**Comment by gavinsimpson** [comment]
Do you think the suggestion is still helpful though? To what end? (I suppose this could be an option for someone not planning to submit a package to CRAN.) Have you had success arguing with CRAN allowing a package through that emitted such a warning?

**Comment by hadley** [comment]
We can update the suggestion to something that doesn't trigger the warning, e.g.

```R
if (utils::packageVersion("dplyr") > "1.0.10") {
  getFromNamespace("reframe", "dplyr")(...)
} else {
  summarise(...)
}
```

**Comment by gavinsimpson** [comment]
I see what you mean; that looks immediately useful too. Thanks 🙏

**Comment by DavisVaughan** [comment]
i.e. that is our tidyr solution which is on CRAN https://github.com/tidyverse/tidyr/blob/0764e65fad777b71aa2a81ffd5447d04a61f8d5e/R/complete.R#L117
