### ISSUE TITLE
`rename_with` with empty column selection fails w/ dplyr 1.1.0.

### ISSUE THREAD

**Issue by lschneiderbauer** [tidyverse/dplyr#6688]
Hi,

due to the size check in the new dplyr version, dplyr 1.1.0, renames with empty column selections don't work anymore (since it expects a vector of functions of size 0).
This is of course not a big problem when used interactively, since one can simply omit the whole statement.
But when used programmatically in a data pipeline it forces the programmer to always treat this case separately (if for instance the .cols argument is defined by external dynamical parameters).

I would expect this function to simply do nothing if no columns are selected, and not throw an error.

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(col = c(1,3)) %>%
  rename_with(
    .cols = contains("test"),
    .fn = ~ paste0("blah.", .)
  )
#> Error in `rename_with()`:
#> ! `.fn` must return a vector of length 0, not 1.

#> Backtrace:
#>     ▆
#>  1. ├─tibble(col = c(1, 3)) %>% ...
#>  2. ├─dplyr::rename_with(...)
#>  3. └─dplyr:::rename_with.data.frame(., .cols = contains("test"), .fn = ~paste0("blah.", .))
#>  4.   └─cli::cli_abort("{.arg .fn} must return a vector of length {length(sel)}, not {length(new)}.")
#>  5.     └─rlang::abort(...)
```

<sup>Created on 2023-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lschneiderbauer** [comment]
Okay, I think, I get it now.
The problem is that `~ paste0("blah.", .)` returns a vector of length 1 even if the argument is a vector of length zero.

In this case, the behavior seems actually fine and consistent to me.
I just need to find a proper substitute for `~ paste0("blah.", .)`.

Sorry for the noise.

**Comment by hadley** [comment]
Technically that's a bug with `paste0()`:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(col = c(1, 3))

df |>
  rename_with(
    .cols = contains("test"),
    .fn = ~ paste0("blah.", ., recycle0 = TRUE)
  )
#> # A tibble: 2 × 1
#>     col
#>   <dbl>
#> 1     1
#> 2     3
df |>
  rename_with(
    .cols = contains("test"),
    .fn = ~ stringr::str_c("blah.", .)
  )
#> # A tibble: 2 × 1
#>     col
#>   <dbl>
#> 1     1
#> 2     3
```

<sup>Created on 2023-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So I'm not sure how we should handle this in dplyr.

**Comment by mrainers** [comment]
It's the same with `stringr::str_c`. The dplyr update change broke my script :-( Now I have to do extra checks if the variable selection returns an empty string to handle this error.
