### ISSUE TITLE
Unable to append data to empty data.frame with union_all (dplyr=1.1.0)

### ISSUE THREAD

**Issue by mhaynam** [tidyverse/dplyr#6692]
With the new update to 1.1.0, I'm unable to append a data.frame (with data) to an empty data frame using union_all(). I do this often in for loops, by creating an empty data frame before the for loop and appending the data created in the for loop to that empty data frame.

Error that comes up now with 1.1.0 when running the below example:
Error in `union_all()`:
! `x` and `y` are not compatible.
✖ Different number of columns: 0 vs 2.

```r
library(dplyr)

n <- 5
vc1 <- c(1, 2, 3, 4, 5)
vc2 <- c(5, 4, 3, 2, 1)
df <- data.frame()

for(i in 1:n){
    val1 <- vc1[i]
    val2 <- vc1[i]
    add_data <- data.frame(col1 = val1, col2 = val2)
    df <- union_all(df, add_data)
}

print(df)
```

**Comment by hadley** [comment]
That's because you should be using `bind_rows()` here:

``` r
library(dplyr, warn.conflicts = FALSE)

n <- 5
vc1 <- c(1, 2, 3, 4, 5)
vc2 <- c(5, 4, 3, 2, 1)
df <- data.frame()

for (i in 1:n) {
  val1 <- vc1[i]
  val2 <- vc1[i]
  add_data <- data.frame(col1 = val1, col2 = val2)
  df <- bind_rows(df, add_data)
}

print(df)
#>   col1 col2
#> 1    1    1
#> 2    2    2
#> 3    3    3
#> 4    4    4
#> 5    5    5
```

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

And in general, you code will be much faster if you don't progressively grow the output, but instead call `bind_rows()` once:

``` r
library(dplyr, warn.conflicts = FALSE)

n <- 5
vc1 <- c(1, 2, 3, 4, 5)
vc2 <- c(5, 4, 3, 2, 1)

out <- vector("list", n)
for (i in 1:n) {
  val1 <- vc1[i]
  val2 <- vc1[i]
  out[[i]] <- data.frame(col1 = val1, col2 = val2)
}

bind_rows(!!!out)
#>   col1 col2
#> 1    1    1
#> 2    2    2
#> 3    3    3
#> 4    4    4
#> 5    5    5
```

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mhaynam** [comment]
Perfect, I will use that moving forward. Thanks Hadley!
