### ISSUE TITLE
Using `closest` in a package context

### ISSUE THREAD

**Issue by Moohan** [tidyverse/dplyr#6697]
I would usually refer to `dplyr` functions in my package with `dplyr::fun()` however, `closest` doesn't seem to be exported...

```r
dplyr::closest()
Error: 'closest' is not an exported object from 'namespace:dplyr'
```

Oddly it seems to work as just `closest` in my package but this is causing lint issues and build notes.

Can this be fixed? Or what is the advised way to use this function (and it's friends) in a package context.

**Comment by DavisVaughan** [comment]
If you add `utils::globalVariables("closest")` in your package somewhere do the build notes go away?

**Comment by Moohan** [comment]
> If you add `utils::globalVariables("closest")` in your package somewhere do the build notes go away? Like this https://github.com/tidyverse/dbplyr/blob/7edf5d607fd6b0b897721ea96d1c9ca9401f0f9b/R/backend-redshift.R#L144
> 
> `closest()` isn't a "real" function in the sense of something like `dplyr::first()`, it just gets parsed and reinterpreted by `join_by()`

Yep, this works for me 👍
