### ISSUE TITLE
Fix license on GitHub

### ISSUE THREAD

**Issue by vanillajonathan** [tidyverse/dplyr#6720]
GitHub says something about the license being unknown...

![image](https://user-images.githubusercontent.com/10222521/218305815-4d518f23-3cef-471a-aa80-e000e4293893.png)

**Comment by DavisVaughan** [comment]
The unknown bit is pointing to this license file https://github.com/tidyverse/dplyr/blob/main/LICENSE

But that is used by CRAN so we need it, and we don't really control how github displays the license, so I don't think there is anything we can do here

**Comment by vanillajonathan** [comment]
I don't know how CRAN works but I guess it wouldn't be possible to just delete the existing `LICENSE` and `LICENSE.MD` files and create a new `LICENSE` file which only contains the MIT License in its original form and nothing else?
