### ISSUE TITLE
Suggest not to use `by` argument in `filter` function

### ISSUE THREAD

**Issue by hope-data-science** [tidyverse/dplyr#6721]
I designed my own package [tidyfst](https://github.com/hope-data-science/tidyfst) and excited to see the new updates in dplyr. I use `by` in many functions, but not in `filter_dt`. I realize that there is a `by` argument in the current version of dplyr, I try to get one for my function, but suddenly realize why I did not use it before. When you filter, you never care if it is filter by group or not, it will yield the same results. Any strong reasons for the existence of it in `filter`? Thanks.

**Comment by DavisVaughan** [comment]
It isn't particularly common, but some people compute the filter expressions by group, like this

``` r
library(dplyr)

mtcars %>% 
  filter(disp == max(disp), .by = cyl)
#>                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> Hornet 4 Drive     21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
#> Merc 240D          24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
#> Cadillac Fleetwood 10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
```

That can be done with `slice_max()` too, but in general you can use an arbitrarily complicated expression there and have it computed by group (i.e. `slice_max()` can be considered as syntax sugar for a `filter()` call)
