### ISSUE TITLE
recode() is superseded by case_match() but case_match() isn't exported from dplyr 1.0.10

### ISSUE THREAD

**Issue by twest820** [tidyverse/dplyr#6749]
The [documentation for `recode()`](https://dplyr.tidyverse.org/reference/recode.html) states it's superseded by `case_match()`. However, `case_match()` is not available in dplyr 1.0.10.
```R
dplyr::case_match()
Error: 'case_match' is not an exported object from 'namespace:dplyr'
```

While the related `case_when()` is exported from dplyr, it fails to hello world in R 4.2.2.
```R
factorVec = factor(c("A", "B"))
case_when(factorVec == "A" ~ 1,
          factorVec == "B" ~ 2,
          .default = NA_real_)
Error in `case_when()`:
! Case 3 (`factorVec == "A" ~ 1`) must be a two-sided formula, not a double vector.
```
`recode()` handles the above without difficulty.
```R
recode(factorVec, 
       "A" = 1,
       "B" = 2,
       .default = NA_real_)
```

It seems like one of the two possibilities below should happen.

1) `case_match()` and `case_when()` are backed out and `recode()` revered from superseded status.
2) `case_match()`, `case_when()` are implemented so that `recode()` can be deprecated without forcing dplyr users into `if_else(if_else(if_else(...)))` stacks.

Assuming the latter, it seems unit test coverage for `case_match()` and `case_when()` needs to be expanded and I would suggest it cover more complex formulas and type conversions than the simple repexes here. `recode()` allows multiple terms, `exp()`, `log()`, and so on. It's desirable to retain that flexibility.

There may be additional issues in this area as it appears #6328 also added `vec_case_match()` but that's not exported from dplyr and isn't in the documentation.

**Comment by DavisVaughan** [comment]
The CRAN version of dplyr is 1.1.0, you just need to update

**Comment by twest820** [comment]
Thanks! I'd checked for updates but for some reason RStudio wasn't seeing them and had to be restarted to pick up 1.1.0 and related changes. Sorry I missed that the version had bumped when looking at the dplyr documentation.

Switched a couple `recode()` to `case_when()` and they pass sanity testing. 😎
