### ISSUE TITLE
Isn't the `join_by()` DSL a new type of tidy evaluation ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#6751]
It is not data masking, it's not tidy selection, but it's evaluated and it's tidy ? Should it be included as a 3rd type of tidy evaluation the ["Programming with dplyr" vignette](https://dplyr.tidyverse.org/articles/programming.html) ?

I love the "\<tidy-select>" and "\<data-masking>" hyperlinks in the doc, having these argument types named and knowing that tidy evaluation means one of those is very helpful to browse the doc and to teach.

`join_by()` 's `...` arg does not have this honour, maybe because it's the only function that uses this DSL, still I think it might be named for consistency and avoiding confusing re different kinds of NSE used in the tidyverse.

This [SO question](https://stackoverflow.com/questions/75531148/why-to-quote-in-dplyr-and-why-not-to-quote-in-dplyr), and more specifically Paul's answer,  made me request this.

**Comment by DavisVaughan** [comment]
It is different from those, and as you say it is the only function that uses this special join DSL.

At this point I don't think we have enough experience with the common patterns of programming against `join_by()` to write a good vignette section about it with meaningful how-tos.

We do allow for simple uses of `{{ }}` in `join_by()` like this

``` r
library(dplyr)

join_on <- function(x, y) {
  join_by({{x}} == {{y}})
}

join_on(a, b)
#> Join By:
#> - a == b
```

But I don't think that will be all that common. I imagine that most of the time the end user is going to be the one creating the `join_by()` object and passing it on to some other function, so there won't be any programming involved there and the `?join_by` page describes the full interactive API you can use.

As we gather more examples we can certainly revisit and expand on the `join_by()` docs and possibly the programming vignettes
