### ISSUE TITLE
Using `mutate(across())` on vector with named elements uses names rather than element values, WAD?

### ISSUE THREAD

**Issue by ammar-gla** [tidyverse/dplyr#6754]
I have a vector where each value corresponds to a column name, which I pass onto `mutate(across())` hoping to transform the existing columns. When the vector elements do not have names, this work correctly, but when I assign names to the elements, the output contains new columns with the intended transformation using the vector names instead. 

Is this working as designed? I could not find any documentation explaining this behaviour, but I am also relatively new to R in general.

I found this issue when trying to pass a named vector to `unite()` which seemed to have problems with the named elements. Not sure whether these issues are connected.

```r
library(dplyr)

# Create vector with named elements
named_vector <- iris[1:2] %>% colnames() %>% setNames(c("length","width"))
not_named_vector <- iris[1:2] %>% colnames()

# Intent: change columns to character
bug_output <- iris %>% mutate(across(all_of(named_vector),as.character)) 
correct_output <- iris %>% mutate(across(all_of(not_named_vector),as.character))

str(bug_output) # Outcome: new character columns are created using element names
str(correct_output) # Correct outcome
```

**Comment by DavisVaughan** [comment]
It is intentional, it is part of how tidyselection works, like with `select()`:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(a = 1, b = 2, c = 3)

cols <- c("a", "c")
names(cols) <- toupper(cols)

select(df, all_of(cols))
#> # A tibble: 1 × 2
#>       A     C
#>   <dbl> <dbl>
#> 1     1     3
```

I've added an example of this to the `across()` docs https://github.com/tidyverse/dplyr/pull/6757

We are also going to add examples to the docs of `all_of()` https://github.com/r-lib/tidyselect/issues/333

**Comment by ammar-gla** [comment]
That is good to know, thank you. 

To avoid this behaviour, do I need to drop the element names from the vector column beforehand, or is there a way to ignore the names when using `all_of()`?

**Comment by DavisVaughan** [comment]
You need to drop the names
