### ISSUE TITLE
Can't run output that has dplyr warnings through latex

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#6755]
This isn't really a dplyr problem -- it is a latex problem because latex was developed before unicode existed; nevertheless, from a practical point of view it makes it hard to run an arbitrary dplyr script that may have warnings through latex using `knitr::spin` since dplyr warnings include a unicode character \u2139 that makes latex fail. See
https://github.com/yihui/knitr/issues/2231

**Comment by DavisVaughan** [comment]
I've added some notes of my own experience but i think it is a knitr bug so im going to close here and we will track this over there

**Comment by cderv** [comment]
@DavisVaughan I think this is related to **cli** url - This was also reported in https://github.com/yihui/knitr/issues/2234 and I looked into there to found that the deprecation warning from **lifecycle** was now using url which in message and it seems there is some ANSI characters  still present. Probably related to https://github.com/r-lib/cli/issues/581 

So I don't think it is a **knitr** issue. I'll comment on **knitr** side about this.
