### ISSUE TITLE
group-summary-arrange changed behavior

### ISSUE THREAD

**Issue by bmschmidt** [tidyverse/dplyr#676]
A note that the new grouped sorting feature produces an unfortunate results for what I'd think is a pretty basic data exploration task: you can no longer use a `summarize %>% arrange` process to get an ordered list of the top results for an interaction. For example: 

``` r
library(nycflights13)
library(dplyr)

flights %>% group_by(carrier,origin) %>% summarize(count=n()) %>% arrange(-count)
```

...no longer gives as a first element the top carrier-origin combination as the first row--instead you get the most common origin for the alphabetically first carrier. I do these operations a lot in dplyr.

Of course one can just add `ungroup` every time you want to do see summary stats sorted, but this isn't what I'd 'expect,' for whatever that's worth. (My expectations are probably mostly based on the results of a SQL `GROUP BY ... ORDER BY` query, which does the old operation, not the new one--maybe I'm just old-fashioned.)

The only fixes I can see would be either having `arrange` arguments take precedence over groups for sorting, or to have `summarize` default to returning ungrouped data rather than just dropping the last-added group. (The 0.2 docs said `summarize` returned ungrouped which was another reason for my expectation, but I guess they were incorrect.) It's up to you to say whether the costs to either of those are greater than adding a lot of `ungroup`s.

Thanks.

```
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.3.0.9000 nycflights13_0.1

loaded via a namespace (and not attached):
[1] assertthat_0.1 DBI_0.3.1      lazyeval_0.1.9 magrittr_1.0.1 parallel_3.1.1 Rcpp_0.11.3    tools_3.1.1   
```

**Comment by pseemakurthi** [comment]
I faced a similar issue with filter %>% group_by %>% summarize %>% mutate %>% select;
issue got resolved after adding ungroup (filter %>% group_by %>% summarize %>% mutate %>% ungroup %>% select) not sure if its the expect behavior.
