### ISSUE TITLE
Different order between sort and arrange for capitals vs lowercase letters

### ISSUE THREAD

**Issue by dkutner** [tidyverse/dplyr#6764]
I'm hitting an issue where `sort` and `arrange` give different results when processing capitals vs lowercase letters.

```r
sort(c("a", "A"))
#> [1] "a" "A"
dplyr::arrange(dplyr::tibble(x = c("a", "A")), x)
#> # A tibble: 2 x 1
#>   x    
#>   <chr>
#> 1 A    
#> 2 a
```

**Comment by DavisVaughan** [comment]
As of dplyr 1.1.0, `arrange()` uses the C locale when sorting character vectors. This is one of the differences vs something like the English locale.

To request an English locale, use the new `.locale` argument

``` r
dplyr::arrange(dplyr::tibble(x = c("a", "A")), x, .locale = "en")
#> # A tibble: 2 × 1
#>   x    
#>   <chr>
#> 1 a    
#> 2 A
```

<sup>Created on 2023-02-27 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

We've outlined this change in many places:
- The NEWS https://dplyr.tidyverse.org/news/index.html#breaking-changes-1-1-0
- A 1.1.0 post https://www.tidyverse.org/blog/2023/02/dplyr-1-1-0-pick-reframe-arrange/#arrange
- A 1.1.0 coming soon post https://www.tidyverse.org/blog/2022/11/dplyr-1-1-0-is-coming-soon/#arrange-improvements-with-character-vectors
- An in depth technical tidyup describing motivations https://github.com/tidyverse/tidyups/blob/main/003-dplyr-radix-ordering.md
