### ISSUE TITLE
Article title on pkgdown website lacks special characters

### ISSUE THREAD

**Issue by fkohrt** [tidyverse/dplyr#6769]
The vignette containing a comparison between {dplyr} and base R has the title “dplyr <-> base R”. The corresponding {pkgdown} article strips out its special characters, however:

![pkgdown article](https://user-images.githubusercontent.com/12914806/221947634-e0c6aeb4-71c5-43be-b6ee-27191ce35e2c.png)

Source: [`dplyr.tidyverse.org`](https://dplyr.tidyverse.org/articles/base.html)

Compare this to the vignette:

![Vignette](https://user-images.githubusercontent.com/12914806/221947583-7c5eed84-c66d-4532-949f-af1b13c94f92.png)

Source: [`vignette(topic = "base", package = "dplyr")`](https://cran.r-project.org/package=dplyr/vignettes/base.html)

A similar vignette from the {purrr} package has special characters stripped from its title as well, see [`purrr.tidyverse.org`](https://purrr.tidyverse.org/articles/base.html).

**Comment by DavisVaughan** [comment]
Tracking in https://github.com/r-lib/pkgdown/issues/2286
