### ISSUE TITLE
case_when is very slow in version 1.1.0

### ISSUE THREAD

**Issue by rszulkin** [tidyverse/dplyr#6788]
Hi,

I don't know if this has been reported already but I experience the same thing as in this stackoverflow post. The case_when funciton has become extremly slow in this new version

https://stackoverflow.com/questions/75304966/dplyr-v1-1-0-runtime-much-slower-for-case-when-with-grouping-variable

Kind regards,
Robert

**Comment by bevthewitch** [comment]
Hi Robert, yes I'm experiencing a significant slow-down and have been testing different versions of dplyr. Previously my code ran in seconds, now it takes 10 minutes!

**Comment by rszulkin** [comment]
> Hi Robert, yes I'm experiencing a significant slow-down and have been testing different versions of dplyr. Previously my code ran in seconds, now it takes 10 minutes!

OK! It's the same on my computer. Seems to be a common problem then.

**Comment by joranE** [comment]
Previously discussed at length (and I believe addressed in the dev version) [here](https://github.com/tidyverse/dplyr/issues/6674).

**Comment by rszulkin** [comment]
> Previously discussed at length (and I believe addressed in the dev version) [here](https://github.com/tidyverse/dplyr/issues/6674).

Thank you!

**Comment by bevthewitch** [comment]
I wasn't sure if it was the case_when or my lags that were the problem, but it is a significant slowdown over 60500 records. At least  it has been recognised and I'm not the only one experiencing this.

**Comment by DavisVaughan** [comment]
We've basically fixed this in the dev version, which should go to CRAN in a week or so, with additional plans to make it faster in the future
