### ISSUE TITLE
Cannot drop columns that are used in group_by except for the last grouping variable

### ISSUE THREAD

**Issue by daattali** [tidyverse/dplyr#6791]
It seems that if `group_by()` is used, then any of the variables except for the last one cannot be removed with `select()`.

```r
# this works, returns only "disp"
mtcars %>% group_by(cyl) %>% summarise(disp = mean(disp)) %>% select(-cyl)

# this works, returns "gear" and "disp"
mtcars %>% group_by(gear, cyl) %>% summarise(disp = mean(disp)) %>% select(-cyl) 

# this doesn't work as intended; returns "cyl" as well
mtcars %>% group_by(cyl, gear) %>% summarise(disp = mean(disp)) %>% select(-cyl)
```

After some testing, it looks like only the last variable used in the grouping can be dropped. `mtcars %>% group_by(cyl, gear, am, vs) %>% summarise(disp = mean(disp)) %>% select(disp)` only drops `vs`.

I could not find any information in the documentation about this behaviour. 

Using `ungroup()` does allow us to remove the columns. I see a very old issue about this https://github.com/tidyverse/dplyr/issues/1030 but I don't see any reason given to why this is happening. It essentially ignores what the user wants to do, so I agree with the OP that perhaps a warning can be warranted, but I think that outright rejecting what the user wants to do is much too strict.

**Comment by DavisVaughan** [comment]
I think the `summarise()` call is throwing you off here because of its default behavior where it strips off the outermost layer of grouping?

So:
- In the 1st example, the result of `summarise()` is ungrouped so you can remove any columns.
- In the 2nd example, the result is grouped by `gear` so you can't remove `gear` but you can remove anything else
- In the 3rd example, the result is grouped by `cyl` so you can't remove `cyl` but you can remove anything else

**Comment by daattali** [comment]
Thanskd for explaining the behaviour I see. However, the main issue still stands, I do think this undocumented unexpected behaviour is too opinionated. Is there a strong reason that we aren't allowing the user to do what they want to do?

**Comment by DavisVaughan** [comment]
It is not undocumented, in `?select` there is

> Groups are maintained; you can't select off grouping variables.

Plus you get a message about it in `select()`

``` r
library(dplyr, warn.conflicts = TRUE)

mtcars %>% 
  group_by(cyl) %>%
  select(-cyl)
#> Adding missing grouping variables: `cyl`
#> # A tibble: 32 × 11
#> # Groups:   cyl [3]
#>      cyl   mpg  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1     6  21    160    110  3.9   2.62  16.5     0     1     4     4
#>  2     6  21    160    110  3.9   2.88  17.0     0     1     4     4
#>  3     4  22.8  108     93  3.85  2.32  18.6     1     1     4     1
#>  4     6  21.4  258    110  3.08  3.22  19.4     1     0     3     1
#>  5     8  18.7  360    175  3.15  3.44  17.0     0     0     3     2
#>  6     6  18.1  225    105  2.76  3.46  20.2     1     0     3     1
#>  7     8  14.3  360    245  3.21  3.57  15.8     0     0     3     4
#>  8     4  24.4  147.    62  3.69  3.19  20       1     0     4     2
#>  9     4  22.8  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10     6  19.2  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows
```

<sup>Created on 2023-03-16 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by daattali** [comment]
Ah you're right, I was looking in the `group_by` documentation (which was a dumb place to look, now I realize!)

I still am unclear about why this choice is forced on the user? This feels overprotective, if someone wants to delete a column, why is that disallowed?

**Comment by DavisVaughan** [comment]
It is more of a choice that `df %>% group_by(bar) %>% select(foo)` should also keep `bar` with a message about it doing so. We typically call this a "sticky" column that always sticks around through `select()` calls. sf and tsibble also have these.

Notably we expect that the lower level call to `gdf["foo"]` _would_ drop off `bar`, and the result would be ungrouped.

It is just a nature of tidy-selection that `select(foo)` ends up looking exactly the same in the end as `select(-bar)` (assuming those are the only 2 columns in the data frame) after processing the selection expression. 

We don't have any plans to make changes to the way this works at this time
