### ISSUE TITLE
Trying to setup local dev environment in Docker fails

### ISSUE THREAD

**Issue by szabgab** [tidyverse/dplyr#6794]
We tried to setup a local development environment and run the test of dplyr but so far could not figure out how.
First launched a Docker container and then we followed what seems to be instructions on the README file:

```
git clone git@github.com:tidyverse/dplyr.git
cd dplyr
docker run -it --rm --workdir /opt -v$(pwd):/opt r-base:4.2.3 bash
Rscript -e 'install.packages("pak")'
```
This worked

```
Rscript -e 'pak::pak("tidyverse/dplyr")'
```

This gave the following error:

```
Error: 
! error in pak subprocess
Caused by error in `loadNamespace(x)`:
! there is no package called ‘pkgdepends’
---
Backtrace:
1. pak::pak("tidyverse/dplyr")
2. pak::pkg_install(pkg, ...)
3. pak:::remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...), …
4. err$throw(res$error)
---
Subprocess backtrace:
1. base::withCallingHandlers(cli_message = function(msg) { …
2. get("pkg_install_make_plan", asNamespace("pak"))(...)
3. base::loadNamespace(x)
4. base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
5. base::withOneRestart(expr, restarts[[1L]])
6. base::doWithOneRestart(return(expr), restart)
7. base::stop(cond)
8. global (function (e) …
Execution halted
```

**Comment by gaborcsardi** [comment]
Hi, this is the best way to install pak, it works on x86_64 and arm64 Linux: 

```r
install.packages("pak", repos = sprintf(
  "https://r-lib.github.io/p/pak/stable/%s/%s/%s",
  .Platform$pkgType,
  R.Version()$os,
  R.Version()$arch
))
```

From https://pak.r-lib.org/reference/install.html

**Comment by gaborcsardi** [comment]
If you really want to install pak from source, then you'll need a C compiler and the `libcurl4-openssl-dev` and `libssl-dev` Ubuntu packages:
```
apt-get install libcurl4-openssl-dev libssl-dev
```
Then 
```
Rscript -e 'install.packages("pak")'
```
should produce a functional pak package.

**Comment by szabgab** [comment]
Our goal was to setup a dev environment and be able to run the tests starting from a public docker images. (preferably an official image of either Ubuntu or R-base. I'll check your suggestions.
