### ISSUE TITLE
`na_matches = "never"` doesn't work if matching columns contain only NAs

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#6804]
``` r
dplyr::inner_join(data.frame(a=NA), data.frame(a=NA), by = "a", na_matches = "never")
#> Error in `dplyr::inner_join()`:
#> ! Can't convert `out[merge]$a` <logical> to match type of `a` <vctrs_unspecified>.
```

<sup>Created on 2023-03-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by zajichek** [comment]
Any conversation on making `na_matches = "never"` the default argument? I wouldn't have expected that `NA` values would be joined by default, but maybe that's just me. Anyway, just wondering.
