### ISSUE TITLE
`bind_cols()` doesn't like length-zero list-cols

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/dplyr#6814]
`bind_cols()` (and associated users of it, like `purrr::map_dfc()`) issues a (somewhat cryptic) warning when working with length-zero list-cols and then neglects to include those cols in the output:
```r
> list(foo = integer(0), bar = character(0), baz = list()) |> dplyr::bind_cols()
# A tibble: 0 × 2
# … with 2 variables: foo <int>, bar <chr>
# ℹ Use `colnames()` to see all variable names
# Warning message:
# Outer names are only allowed for unnamed scalar atomic inputs
```
I'm surprised that `baz` isn't included as a column in the output, especially since the equivalent empty list-col is fine with other tbl construction-methods:
```r
> tibble::tibble(baz = list())
# A tibble: 0 × 1
# … with 1 variable: baz <list>
# ℹ Use `colnames()` to see all variable names
```
This is with {dplyr} v1.1.1.

<details>
<summary>Session info:</summary>
<pre>
 R version 4.2.2 (2022-10-31)
 Platform: x86_64-apple-darwin20.6.0 (64-bit)
 Running under: macOS Big Sur 11.3

 Matrix products: default
 BLAS:   /usr/local/Cellar/openblas/0.3.21/lib/libopenblasp-r0.3.21.dylib
 LAPACK: /usr/local/Cellar/r/4.2.2/lib/R/lib/libRlapack.dylib

 locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

 attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   base

 other attached packages:
 [1] forcats_0.5.2   stringr_1.5.0   dplyr_1.1.1     purrr_1.0.1     readr_2.1.3     tidyr_1.3.0     tibble_3.2.1    ggplot2_3.4.0   tidyverse_1.3.2

 loaded via a namespace (and not attached):
  [1] pillar_1.8.1        compiler_4.2.2      cellranger_1.1.0    dbplyr_2.2.1        tools_4.2.2         timechange_0.1.1    googledrive_2.0.0   jsonlite_1.8.3      lubridate_1.9.0
 [10] lifecycle_1.0.3     gargle_1.2.1        gtable_0.3.1        pkgconfig_2.0.3     rlang_1.1.0         reprex_2.0.2        DBI_1.1.3           cli_3.4.1           haven_2.5.1
 [19] xml2_1.3.3          withr_2.5.0         httr_1.4.4          generics_0.1.3      vctrs_0.6.1         fs_1.5.2            hms_1.1.2           googlesheets4_1.0.1 grid_4.2.2
 [28] tidyselect_1.2.0    glue_1.6.2          R6_2.5.1            fansi_1.0.3         readxl_1.4.1        tzdb_0.3.0          modelr_0.1.10       magrittr_2.0.3      backports_1.4.1
 [37] scales_1.2.1        ellipsis_0.3.2      rvest_1.0.3         assertthat_0.2.1    colorspace_2.0-3    utf8_1.2.2          stringi_1.7.8       munsell_0.5.0       broom_1.0.1
 [46] crayon_1.5.2
</pre>
</details>

**Comment by haozhou1988** [comment]
bind_cols() drops the empty list() because it is designed to work with one-dimensional atomic vectors, such as integer, double, character, and logical vectors. The main purpose of bind_cols() is to bind atomic vectors together column-wise, creating a data frame or Tibble. 
When we provide an empty list() as one of the inputs to bind_cols(), it doesn't fit the expected input structure, so it is dropped with a warning message. The warning message indicates that outer names are only allowed for unnamed scalar atomic inputs, which means that non-atomic inputs like a list() are not considered valid inputs for this function.
-- From ChatGpt 4

**Comment by DavisVaughan** [comment]
Due to weird legacy squashing behavior with `bind_cols()`, there isn't much we can do to change this. You can use `vctrs::vec_cbind()` if you want "more correct" behavior here

```r
x <- list(foo = integer(0), bar = character(0), baz = list())

dplyr::bind_cols(!!!x)
#> # A tibble: 0 × 2
#> # ℹ 2 variables: foo <int>, bar <chr>

vctrs::vec_cbind(!!!x) |> tibble::as_tibble()
#> # A tibble: 0 × 3
#> # ℹ 3 variables: foo <int>, bar <chr>, baz <list>
```

**Comment by mmuurr** [comment]
I get that there's a legacy issue making this a bit complicated, but the current behavior is at odds with much of the rest of the {tidyverse}. Moreoever, the current documentation for `bind_cols()` is:
> `...`: Data frames to combine. Each argument can either be a data frame, a list that could be a data frame, or a list of data frames. Inputs are recycled to the same length, then matched by position.

The example given definitely meets that criteria.

Moreover, the behavior is quite inconsistent with listcols. If the listcol is _already_ in a tibble, e.g., `bind_cols()` is quite happy to deal with them, regardless of length, **but the same is not true if in a plain data frame**. This seems (to me) ripe for very sneaky bugs to be introduced that are data-dependent (i.e. the worst kind!) ... e.g. now the developer needs to be worried about a package on which they have no control returning a tibble or a data frame, despite `bind_cols()` claim to handle both more-or-less identically (along with lists, which also isn't true). Observe:

```r
library(tibble); packageVersion("tibble")
#> [1] '3.2.1'
library(dplyr); packageVersion("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> [1] '1.1.1'

## produces tibble(x <lst>, y<int>) as expected
bind_cols(
  tibble(x = list()),
  tibble(y = integer(0))
) |> str()
#> tibble [0 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ x: list()
#>  $ y: int(0)

## produces tibble(x <lst>, y<int>) as expected
bind_cols(
  tibble(x = list(NULL, NULL, NULL)),
  tibble(y = 1:3)
) |> str()
#> tibble [3 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ x:List of 3
#>   ..$ : NULL
#>   ..$ : NULL
#>   ..$ : NULL
#>  $ y: int [1:3] 1 2 3

## produces tibble(y<int>) NOT as expected
bind_cols(
  list(x = list()),
  list(y = integer(0))
) |> str()
#> tibble [0 × 1] (S3: tbl_df/tbl/data.frame)
#>  $ y: int(0)

## produces tibble(y<int>) NOT as expected
bind_cols(
  list(x = list(NULL, NULL, NULL)),
  list(y = 1:3)
) |> str()
#> tibble [3 × 1] (S3: tbl_df/tbl/data.frame)
#>  $ y: int [1:3] 1 2 3

## what if we pre-cast the listcol to a tibble?
## produces tibble(x<lst>, y<int>) as expected
bind_cols(
  list(x = list()) |> as_tibble(),
  list(y = integer(0))
) |> str()
#> tibble [0 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ x: list()
#>  $ y: int(0)

## what if we'd used data.frame instead?
## produces data.frame(y<int>) NOT as expected (VERY much so, this time)
bind_cols(
  list(x = list()) |> as.data.frame(),
  list(y = integer(0))
) |> str()
#> 'data.frame':    0 obs. of  1 variable:
#>  $ y: int
```

<sup>Created on 2023-04-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

That type of inconsistency **really** feels like a bug to me. If it doesn't meet the criteria for a bug, then at least the documentation should be updated to include all of these edge cases.

**Comment by mmuurr** [comment]
Now that I've also found more oddities, I'd be fine changing the title of this Issue _or_ creating a (new) more general Issue.
