### ISSUE TITLE
`filter()` when iterator and function's argument have the same name

### ISSUE THREAD

**Issue by JackCaster** [tidyverse/dplyr#6816]
I'd like to filter a dataframe within a function based on a condition passed as an argument. If the argument is created as an iterator in a for-loop, and this has the same name of the dataframe variable to filter on, `{{` does not work as intended unless I first use the argument somehow. 

Consider 
```r
library(tidyverse)

f <- function(Species) {
    iris %>%
        filter(Species == {{ Species }}) %>%
        distinct(Species) %>%
        print()
}
```

This will work

```r
f(Species = "setosa")

#   Species
# 1  setosa
```

but this will not
```r
for (Species in c("setosa")) {
    f(Species = Species)
}

#      Species
# 1     setosa
# 2 versicolor
# 3  virginica
```

If I use the variable passed as argument (a `print` is just enough), then it works
```r
f2 <- function(Species) {
    print(Species) # <--- I added this

    iris %>%
        filter(Species == {{ Species }}) %>%
        distinct(Species) %>%
        print()
}

for (Species in c("setosa")) {
    f2(Species = Species)
}

# [1] "setosa"
#   Species
# 1  setosa
```

I realize that this is somehow a niche use case. Is this behavior as expected? Would you be able to help?

**Comment by DavisVaughan** [comment]
If you expect that the `Species` argument is always an actual value (not an expression), then you should use the `.env` pronoun:

``` r
library(dplyr, warn.conflicts = FALSE)

f <- function(Species) {
  iris %>%
    filter(Species == .env$Species) %>%
    distinct(Species) %>%
    print()
}

f(Species = "setosa")
#>   Species
#> 1  setosa

for (Species in c("setosa", "versicolor")) {
  f(Species = Species)
}
#>   Species
#> 1  setosa
#>      Species
#> 1 versicolor
```

<sup>Created on 2023-04-06 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>
