### ISSUE TITLE
While nest_by is "thinking", there is no red stop sign 

### ISSUE THREAD

**Issue by Yann-C-INN** [tidyverse/dplyr#6829]
Hi. I'm working on a large data set and thus when I nest data (using `nest_by()` directly) it takes time, but it does not make the red stop sign appear. It just leaves the screen as is and allows me to write things in the console,

So yesterday when I typed 5+5 and received no output, I thought the function is broken. 
The function does work eventually (it's 10, if you wondered), and operates as expected, but this seemingly minor issue caused me to restart R a few times due to lack of patience. I'm sure its not on propose that the "Stop" sign didnt turn on... 

//  R version 4.2.3 (2023-03-15 ucrt) // RStudio ‘2023.3.0.386’

**Comment by DavisVaughan** [comment]
I imagine this is an RStudio issue, not a dplyr issue. It works fine for me with this:

```r
library(dplyr)

df <- tibble::tibble(
  g = sample(100, 1e8, replace = TRUE),
  x = sample(g)
)

nest_by(df, g)
```

https://user-images.githubusercontent.com/19150088/233386571-5fe5836b-391c-45a2-bbe0-d563e008ce47.mov
