### ISSUE TITLE
`na_if()` throws an error on unknown levels of a factor

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/dplyr#6831]
Hi,

Since` dplyr 1.1.0`, `na_if()` is stricter about type stability.

While this might be a very good thing in most cases, it can get quite awkward when dealing with factors.

For instance, consider this example:

``` r
library(dplyr)
x=factor(letters)
na_if(x, "a")
#>  [1] <NA> b    c    d    e    f    g    h    i    j    k    l    m    n    o   
#> [16] p    q    r    s    t    u    v    w    x    y    z   
#> Levels: a b c d e f g h i j k l m n o p q r s t u v w x y z
na_if(x, "aa")
#> Error in `na_if()`:
#> ! Can't convert from `y` <character> to `x` <factor<754f0>> due to loss of generality.
```

<sup>Created on 2023-04-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The breaking change is significant in a project where I have to deal with multiple factors with different levels but sharing a common NA level. 

`forcats::fct_na_level_to_value()` seems to work in place though. If this is the correct way to deal with factors, maybe it could be worth documenting?

**Comment by DavisVaughan** [comment]
> I have to deal with multiple factors with different levels but sharing a common NA level.

I think this use case still works though?

``` r
library(dplyr)

x <- factor(c("NA!", "a", "b"))
y <- factor(c("c", "d", "NA!"))

na_if(x, "NA!")
#> [1] <NA> a    b   
#> Levels: a b NA!
na_if(y, "NA!")
#> [1] c    d    <NA>
#> Levels: c d NA!
```

I do think a forcats utility is probably best, but I don't think we need to document specifics of factors in a general function like `na_if()`

**Comment by DanChaltiel** [comment]
> this use case still works though

This code will fail if any vector has no missing value, which can obviously happen from time to time.

I understand your point of view though.
