### ISSUE TITLE
`summarise()` warns about < 1 row when there are 0 groups

### ISSUE THREAD

**Issue by cjyetman** [tidyverse/dplyr#6834]
`summarise()` now warns if more (or less) than 1 row per `summarise()` group is returned, however when the number of groups are 0 (e.g. in the case of a data frame with 0 rows), I would expect that 0 groups * 1 row = 0 so this warning would not be shown, i.e. this warning should only occur if the returned number of rows is different than the number of groups.

This is a convoluted, but minimal reprex...
``` r
library(dplyr)

packageVersion("dplyr")
#> [1] '1.1.2.9000'

starwars %>% 
  filter(grepl("^D", species)) %>% 
  group_by(species) %>% 
  summarise(sex = unique(sex), .groups = "keep")
#> # A tibble: 2 × 2
#> # Groups:   species [2]
#>   species sex  
#>   <chr>   <chr>
#> 1 Droid   none 
#> 2 Dug     male

starwars %>% 
  filter(grepl("^D", species)) %>% 
  filter(height > 200) %>% 
  group_by(species) %>% 
  summarise(sex = unique(sex), .groups = "keep")
#> Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
#> dplyr 1.1.0.
#> ℹ Please use `reframe()` instead.
#> ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
#>   always returns an ungrouped data frame and adjust accordingly.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.
#> # A tibble: 0 × 2
#> # Groups:   species [0]
#> # ℹ 2 variables: species <chr>, sex <chr>
```

**Comment by DavisVaughan** [comment]
Thanks, I do not think this is a bug.

The functions used within `summarise()` _must_ return exactly 1 value, no matter what their input is. Even if the input is empty, it must return 1 value. Like `sum()`, `mean()`, `prod()`, etc:

``` r
sum(integer())
#> [1] 0
mean(integer())
#> [1] NaN
prod(integer())
#> [1] 1
```

`unique()` does not do this, and is not something that should be used in `summarise()`, but it is a good candidate for `reframe()`. I know this is a contrived example but I imagine the same problem holds true for your real example.

Ultimately we are trying to get back to dplyr 0.8.5 behavior where returning anything other than a size 1 result in `summarise()` is an error. `sum()` would be fine, `unique()` would not. Like this:

``` r
# pak::pak("tidyverse/dplyr@v0.8.5")

library(dplyr, warn.conflicts = FALSE)

empty <- starwars %>% 
  filter(grepl("^D", species)) %>% 
  filter(height > 200)

# Not ok 
empty %>% 
  summarise(birth_year = unique(birth_year))
#> Error: Column `birth_year` must be length 1 (a summary value), not 0

# Allowed but I think this is a bug in 0.8.5
empty %>% 
  group_by(species) %>% 
  summarise(birth_year = unique(birth_year))
#> # A tibble: 0 × 2
#> # ℹ 2 variables: species <chr>, birth_year <dbl>


# Both of these are ok because `sum()` has the correct properties of a "summary" function
empty %>% 
  summarise(birth_year = sum(birth_year))
#> # A tibble: 1 × 1
#>   birth_year
#>        <dbl>
#> 1          0

empty %>% 
  group_by(species) %>% 
  summarise(birth_year = sum(birth_year))
#> # A tibble: 0 × 2
#> # ℹ 2 variables: species <chr>, birth_year <dbl>
```

<sup>Created on 2023-04-25 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>
