### ISSUE TITLE
Is it possible to NOT deprecate by = character() in _join - or how to rework the below code when it happens?

### ISSUE THREAD

**Issue by Generalized** [tidyverse/dplyr#6837]
The problem: I calculate hierarchical percentages, where a denominator for the current group is nominator for the parent group. The "top" level row is labelled 100% and is simply divided by itself*.

/ *because the exact value of N and Ntot is required to pass later into a procedure calculating the confidence interval for the %, so no - it cannot be just fixed at 1. /

Later I'm going to show you how the title of this issue relates to my problem. Not let's generate some data.
```
data <- structure(list(SOC = c("SOC1", "SOC1", "SOC1", "SOC1", "SOC2", 
"SOC2", "SOC2", "SOC3", "SOC3", "SOC1", "SOC1", "SOC1", "SOC2", 
"SOC5", "SOC5", "SOC10", "SOC11", "SOC11", "SOC1", "SOC1", "SOC1", 
"SOC1", "SOC2", "SOC2"), PT = c("PT1-1", "PT1-1", "PT1-2", "PT1-3", 
"PT2-1", "PT2-1", "PT2-2", "PT3-3", "PT3-4", "PT1-1", "PT1-1", 
"PT1-2", NA, "PT5-10", "PT5-2", "PT10-2", "PT11-1", "PT11-2", 
"PT1-1", "PT1-1", "PT1-2", "PT1-3", "PT2-1", "PT2-2"), ARM = c("SoC", 
"SoC", "SoC", "SoC", "SoC", "SoC", "SoC", "SoC", "SoC", "Arm1", 
"Arm1", "Arm1", "Arm1", "Arm1", "Arm1", "Arm1", "Arm1", "Arm1", 
"SoC", "SoC", "SoC", "SoC", "SoC", "SoC"), SIDE = c("LEFT", "LEFT", 
"LEFT", "RIGHT", "RIGHT", "RIGHT", "RIGHT", "RIGHT", "LEFT", 
"RIGHT", "RIGHT", "LEFT", "LEFT", "LEFT", "LEFT", "LEFT", "RIGHT", 
"RIGHT", "LEFT", "LEFT", "RIGHT", "LEFT", "RIGHT", "RIGHT")), row.names = c(NA, 
24L), class = "data.frame")
```
which gives (head):
```
> head(o)
   SOC    PT ARM  SIDE
1 SOC1 PT1-1 SoC  LEFT
2 SOC1 PT1-1 SoC  LEFT
3 SOC1 PT1-2 SoC  LEFT
4 SOC1 PT1-3 SoC RIGHT
5 SOC2 PT2-1 SoC RIGHT
6 SOC2 PT2-1 SoC RIGHT
.... and so on
```

Let's run some exemplary code, that calculates the denominators I use later in my code. It's sufficient here to share only this part of the code:

```{r}
# First, the grouping columns
> grp_cols <- c("ARM", "SOC")

# Now - the sequences of grouping columns, defining levels of the denominators.

> sequences_of_cols <- sapply(seq(from = length(grp_cols), to=1), function(s) grp_cols[seq(s)])
> sequences_of_cols <- c(sequences_of_cols, list(character(0))) # will make the "top" total

> sequences_of_cols
[[1]]
[1] "ARM" "SOC"

[[2]]
[1] "ARM"

[[3]]
character(0)  # this is for the top row. Using it facilitates my code a lot later with left_join()
 
# Now the code calculating the denominators per each level of grouping
> lapply(sequences_of_cols, 
        function(s) 
            data %>% 
            group_by(across(all_of(s))) %>%
            summarize(.groups = "drop") %>% 
            left_join( data %>%
                       group_by(across(all_of(head(s, -1)))) %>%
                           summarize(n_tot = n()),
                       by = head(s, -1))) 
[[1]]
# A tibble: 8 × 3
  ARM   SOC   n_tot
  <chr> <chr> <int>
1 Arm1  SOC1      9
2 Arm1  SOC10     9
3 Arm1  SOC11     9
4 Arm1  SOC2      9
5 Arm1  SOC5      9
6 SoC   SOC1     15
7 SoC   SOC2     15
8 SoC   SOC3     15

[[2]]
# A tibble: 2 × 2
  ARM   n_tot
  <chr> <int>
1 Arm1     24
2 SoC      24

[[3]]
# A tibble: 1 × 1
  n_tot
  <int>
1    24
```

I need exactly this format of the list.
See? The left_join() handles both non-empty vector of "parent" columns (minus the last one), and when it's empty - it just gives me the n_tot without the column names (that's why I couldn't join by anything).

And I would be very happy about this code, if it didn't tell me that: 

> "Using `by = character()` to perform a cross join was deprecated in dplyr 1.1.0."

which means this is unsafe and I cannot rely on it.
Theoretically I should conditionally use either left_join() or cross_join(), but this overcomplicates the above code :(

```{r}
> lapply(sequences_of_cols, 
+        function(s) 
+            data %>% 
+            group_by(across(all_of(s))) %>%
+            summarize(.groups = "drop") %>% 
+            {
+                x <- .
+                tmp <- data %>%  group_by(across(all_of(head(s, -1)))) %>% summarize(n_tot = n())
+                
+                if(length(head(s, -1)) > 0)  
+                    left_join(x, tmp, by = head(s, -1)) %>% return()
+                 else 
+                    tmp  %>% return()  # or cross_join(), if there were some other columns in the "x" I want to preserve
+            })
[[1]]
# A tibble: 8 × 3
  ARM   SOC   n_tot
  <chr> <chr> <int>
1 Arm1  SOC1      9
2 Arm1  SOC10     9
3 Arm1  SOC11     9
4 Arm1  SOC2      9
5 Arm1  SOC5      9
6 SoC   SOC1     15
7 SoC   SOC2     15
8 SoC   SOC3     15

[[2]]
# A tibble: 2 × 2
  ARM   n_tot
  <chr> <int>
1 Arm1     24
2 SoC      24

[[3]]
# A tibble: 1 × 1
  n_tot
  <int>
1    24
```
But those "inline {}" look a bit weird to me, moreover they don't seem to work with the new |> operator.

If only I could use the left_join() without the warning of deprecation, it would be great. Couldn't you leave this functionality for backward compatibility, especially that you provide now the explicit cross_join(), so people can use it easily without specifying by=character())?

Or maybe there is another way to achieve the same without this {} or creating helper functions like "my_join()" combining the two? The format of the list needs to be as shown, including the "top" row.

**Comment by DavisVaughan** [comment]
I think `left_join()` is probably the wrong tool for the job here. A mixture of select/distinct/count seems like it would work better

``` r
lapply(sequences_of_cols, function(cols) {
  out <- select(data, all_of(cols))
  count_cols <- head(cols, -1)
  out <- add_count(out, pick(all_of(count_cols)))
  out <- distinct(out, pick(all_of(cols)), .keep_all = TRUE)
  out
})
#> [[1]]
#>    ARM   SOC  n
#> 1  SoC  SOC1 15
#> 2  SoC  SOC2 15
#> 3  SoC  SOC3 15
#> 4 Arm1  SOC1  9
#> 5 Arm1  SOC2  9
#> 6 Arm1  SOC5  9
#> 7 Arm1 SOC10  9
#> 8 Arm1 SOC11  9
#> 
#> [[2]]
#>    ARM  n
#> 1  SoC 24
#> 2 Arm1 24
#> 
#> [[3]]
#>    n
#> 1 24
```

The main issue we have with allowing `by = character()` to be a (sort of) cross join is that when _most_ people program around `by` (sort of like what you are doing) it is actually very surprising when going from 1 column in common -> 0 columns in common results in a cross join, giving you an explosive Cartesian product in the number of resulting rows. Most of the time when people program with `left_join()` and expose `by` to their user in some way, they don't ever expect a cross join to be possible. It is much better (and more like SQL) to be explicit by calling `cross_join()` directly when you really need it.

_Technically_ the `left_join(by = character())` isn't even a true cross join. The only one that actually gave the correct results in all edge cases was `inner_join(by = character())`.

We do not have any plans to change this back at this time
