### ISSUE TITLE
Unhelpful error message when using `dplyr::between()` in `join_by()`

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#6838]
I accidentally used `dplyr::between()` instead of `between()` in `join_by()`. Not sure whether you want to accept it with a namespace or not but the error message isn't very helpful.

``` r
dplyr::join_by(dplyr::between(y, a, b))
#> Error in `as_string()`:
#> ! Can't convert a call to a string.
#> Backtrace:
#>     ▆
#>  1. └─dplyr::join_by(dplyr::between(y, a, b))
#>  2.   └─dplyr:::parse_join_by_expr(exprs[[i]], i, error_call = error_call)
#>  3.     └─rlang::as_string(expr[[1]])
#>  4.       └─rlang:::abort_coercion(x, "a string")
#>  5.         └─rlang::abort(msg, call = call)
```

<sup>Created on 2023-05-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Yeah, probably.

**Comment by balthasars** [comment]
> I accidentally used `dplyr::between()` instead of `between()` in `join_by()`. Not sure whether you want to accept it with a namespace or not but the error message isn't very helpful.
> 
> ```r
> dplyr::join_by(dplyr::between(y, a, b))
> #> Error in `as_string()`:
> #> ! Can't convert a call to a string.
> #> Backtrace:
> #>     ▆
> #>  1. └─dplyr::join_by(dplyr::between(y, a, b))
> #>  2.   └─dplyr:::parse_join_by_expr(exprs[[i]], i, error_call = error_call)
> #>  3.     └─rlang::as_string(expr[[1]])
> #>  4.       └─rlang:::abort_coercion(x, "a string")
> #>  5.         └─rlang::abort(msg, call = call)
> ```
> 
> Created on 2023-05-02 with [reprex v2.0.2](https://reprex.tidyverse.org)

Would be super neat if dplyr would support that so the new `join_by()` feature can also be used in situations where calling `dplyr::between()` is the only safe option. Thanks for the great work on dplyr!

**Comment by DavisVaughan** [comment]
What do you mean by safe?

**Comment by balthasars** [comment]
> What do you mean by safe?

Safe as in not loading the entire dplyr namespace using `library()` in legacy code projects that have the potential of namespace conflicts.

I suppose a potential workaround would be to use `library(dplyr, include.only = c("between"))`, which sort of invalidates my argument.

**Comment by DavisVaughan** [comment]
`join_by()` interprets its input in a very special way, so if you don't load dplyr I'm fairly certain you can still call `between()` without namespacing it

**Comment by balthasars** [comment]
> `join_by()` interprets its input in a very special way, so if you don't load dplyr you can still call `between()` without namespacing it, i.e.
> 
> ```r
> dplyr::join_by(between(x, y, z))
> #> Join By:
> #> - between(x, y, z)
> ```
> 
> Created on 2023-09-18 with [reprex v2.0.2](https://reprex.tidyverse.org)

😮 I didn't even consider that, very cool! Thank you for providing this illuminating example!
