### ISSUE TITLE
Feature request .remove specific column in mutate argument

### ISSUE THREAD

**Issue by TarJae** [tidyverse/dplyr#6841]
I would like to ask for a new feature in `mutate` function: 

---
In `mutate` we have the wonderful `.keep` argument with ("all", "used", "unused" and "none"). I am wondering if it is possible to implement a `.remove` argument with specific coulmn names similar to the `.by` argument. 

```r
# here I have to add a extra line select(-id), the .keep argument does not help
iris %>% 
  head() %>% 
  mutate(id = row_number()) %>% 
  mutate(x = if_else(Species == "setosa", paste(id, Sepal.Length, Sepal.Width), 
                     paste(id, Petal.Length, Petal.Width))) %>% 
  select(-id)

# is it possible to have
iris %>% 
  head() %>% 
  mutate(id = row_number()) %>% 
  mutate(x = if_else(Species == "setosa", paste(id, Sepal.Length, Sepal.Width), 
                     paste(id, Petal.Length, Petal.Width)), .remove= id) 
```

**Comment by TarJae** [comment]
Ah, Now I remember. Thank you very much. setting column to `NULL` is a good solution!

**Comment by DavisVaughan** [comment]
Yea I think either setting it to `NULL` or calling `select()` afterwards (which is my preferred solution) is your best bet here
