### ISSUE TITLE
`.by` creates different row order as `group_by()`

### ISSUE THREAD

**Issue by mayer79** [tidyverse/dplyr#6843]
The new `.by` does not seem to sort the results of **`summarize()`** or **`reframe()`** by factor levels. This causes an inconsistency to `group_by()`:

```r
lev <- c("A", "B", "C")

X <- data.frame(x = 1:3, g = factor(rev(lev), levels = lev))

X %>% group_by(g) %>% summarize(mean(x))  # A B C
X %>% summarize(mean(x), .by = g)         # C B A
```

Introducing a `.sort` argument as suggested in https://github.com/tidyverse/dplyr/issues/6663 would be great!

**Comment by DavisVaughan** [comment]
FWIW this is documented here https://dplyr.tidyverse.org/reference/dplyr_by.html#result-ordering

**Comment by mayer79** [comment]
I see. So if I want the results of `reframe()` to be sorted by levels, I'd simply use `group_by()`... :-)
