### ISSUE TITLE
Summary table of 1 row in group_by

### ISSUE THREAD

**Issue by ipovilonis** [tidyverse/dplyr#6863]
Hello. I am trying to create a table with summary statistics grouped by categories with group_by() and summarise() in dplyr. The grouping is not happening, and instead of obtaining a table with 4 rows (4 categories), I'm getting 1 row as if there was no grouping. I have the latest version of R and dplyr.
---

This is the code:

```r
library(dplyr)

# Create a data frame from the data: datahvcar

# Group the data by method

datahvcar_grouped <- datahvcar %>% group_by(method)

# Summarize the data by calculating the mean, min, max, and SD of each variable:

resume_table <- datahvcar_grouped %>% summarise(
  Mean = mean(caroten),
  Min = min(caroten),
  Max = max(caroten),
  SD = sd(caroten)
)

# Print the resume table

print(resume_table)

```
This is the expected output:
```r
# A tibble: 4 × 5
# Groups:   method [4]
   method Mean min max sd
#  <fct> <dbl> <dbl> <dbl> <dbl>
1 potter_A 46.8 26.8 76.2 17.1
2   rod     17.5 13.0 20.0  3.4
3 potter_B 37.2 14.0 54.4 14.7
4   rod2     15.5 12.0 19.9  4.2
```
This is the output I am getting:
```r
"Description:df [1 × 4]
Mean
<dbl>
Min
<dbl>
Max
<dbl>
SD
<chr>
37.71563	12.99789	76.22059	20.16017	1 row"
```

**Comment by DavisVaughan** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

In particular I don't know what `datahvcar` is.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks
