### ISSUE TITLE
dplyr full_join & "DLL requires the use of native symbols"

### ISSUE THREAD

**Issue by obruck** [tidyverse/dplyr#6865]
I use `R 4.3.0.` in a Linux Ubuntu system with very limited internet access. I cannot install anything there myself from the internet except from R packages from certain CRAN mirrors (Muenster and Umeå) and Bioconductor.

This is the `sessionInfo()`
![Screenshot 2023-06-07 at 11 30 50](https://github.com/tidyverse/dplyr/assets/25300573/62143872-a2be-4050-8db5-7a36bc3f21ab)

After updating R from 4.2. to 4.3. The dplyr command full_join command raises the error `DLL requires the use of native symbols`. This has also been observed for the `as_tibble` command https://github.com/tidyverse/dplyr/issues/6793. I am 100% certain that the error is not in the data (I have tested different data and dataframes, tibbles and datatable) and the exact same data and command worked in R 4.2. Adding a reprex would not make any sense so I leave it out.

I found that the error disappears if instead of
`full_join(df1, df2)`
I use
`full_join(df1, df2, keep=TRUE)`
But I do not want to keep duplicate columns so that is not a solution for me.

I have also tested both dplyr 1.1.0 and 1.0.9 so likely not fully related to dplyr but perhaps to a library or Ubuntu + R 4.3. dependency problem. Could you help me to point the reason for this?

**Comment by DavisVaughan** [comment]
It sort of sounds like you somehow have a package that needs to be reinstalled. Did you carry over your R package library when you upgraded from 4.2 to 4.3? If you did, you should purge your entire package library and reinstall it. Packages are incompatible across minor versions of R

**Comment by obruck** [comment]
Thanks @DavisVaughan, that's a very good idea. I actually tried that but indeed some packages remains built in 4.2. and not 4.3. I'll try that and tell you if that worked.

**Comment by obruck** [comment]
This fixed the issue, thanks again!
