### ISSUE TITLE
if_else produce unnecessary warning in mutate

### ISSUE THREAD

**Issue by mghaderizefreh** [tidyverse/dplyr#6877]
the function `if_else` combined with `mutate` will produce warnings which are not appropriate.

Consider `foo` to be

```r
foo <- tibble(fac = rep(c('linear','exp'), each = 2), value = c(-2,-1,1,2))
```

Now, I want to log-transform the exponential part.

```r
bar <- foo %>% mutate(if_else("exp" == fac, log(value), value)
```

This produces the desired output but will give a warning

```r
Warning message:
There was 1 warning in `mutate()`.
In argument: `if_else(fac == "exp", log(value), value)`.
Caused by warning in `log()`:
! NaNs produced 
```

even though there is no NaN in `bar`.

**Comment by joranE** [comment]
`mutate()` isn't necessary to produce the warnings, they appear if you just run `if_else()` and are expected. `if_else()` can't know up front what the TRUE/FALSE values in the expression will be, so it calculated both `log(value)` and `value` in their entirety up front, and then constructs the output from the results. 

I could have sworn this behavior was explicitly mentioned in the documentation (and for `ifelse`) but unless my tired eyes are just glossing over it, I can't find it.

**Comment by banbh** [comment]
`if_else` appears to be stricter than `ifelse`. For example, `ifelse(c(TRUE,TRUE), 1, stop())` succeeds, but `if_else(c(TRUE,TRUE), 1, stop())` generates an error.

**Comment by psychelzh** [comment]
This is by design, and see the documentation:

> Compared to the base R equivalent, [ifelse()](https://rdrr.io/r/base/ifelse.html), this function allows you to handle missing values in the condition with missing and always takes true, false, and missing into account when determining what the output type should be.

For more information, see also #3637.

**Comment by DavisVaughan** [comment]
As others have said, the fact that `if_else()` and `case_when()` fully evaluate all conditions is by design and due to type stability. I think it is mostly clear from the description of:

> always takes true, false, and missing into account when determining what the output type should be.
