### ISSUE TITLE
`if_else` being strict about object length

### ISSUE THREAD

**Issue by briatte** [tidyverse/dplyr#6879]
I am trying to understand whether this is expected behaviour from `if_else`:

```r
x <- character(0)
if_else(!length(x), NA_character_, x)
#> Error in `if_else()`:
#> ! `false` must have size 1, not size 0.
#> Run `rlang::last_trace()` to see where the error occurred.
```

(I presume that 'size' means 'length' in this context, but I'm definitely no expert in the terminology that should be used here -- apologies if I'm misunderstanding the error message.)

Part of the reason why this is happening seems to be that, [quoting](https://github.com/tidyverse/dplyr/issues/6728) @DavisVaughan, "the true and false arguments are always evaluated, regardless of whether their values are seen in the result." However, the example above is about length/size rather than type.

The same code works with base R:

```r
ifelse(!length(x), NA_character_, x)
#> NA

na_if_empty <- function(x) if(length(x)) x else NA_character_
na_if_empty(x)
#> NA
```

Is there any way to perform something like the above with `if_else`, or is the function deliberately strict on object length, and I should therefore use base R instead when I need to replace an 0-length string with `NA`?

**Comment by DavisVaughan** [comment]
The docs for `if_else()` state this for `true` and `false`:

> Both `true` and `false` will be [recycled](https://vctrs.r-lib.org/reference/vector_recycling_rules.html) to the size of `condition`.

And what you have is essentially:

```r
if_else(TRUE, true = NA_character_, false = character()) 
```

Where we can't recycle `false`, something with 0 size, to a size of 1.

This is expected behavior.

I think all you really need is

```r
if (length(x) == 0L) {
  x <- NA_character_
}
```

i.e. you aren't really using the vectorized nature of `if_else()` here, so it is better to just use an if.

**Comment by briatte** [comment]
Thank you very much. I better understand the behavior now.
