### ISSUE TITLE
`recode()` is very slow due to `signal_stage()`

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#6881]
Most of the time is spend in `signal_stage()`. This makes `recode()` so slow that it can't really be used in some situations anymore.

``` r
char_vec <- sample(c("a", "b", "c"), 10, replace = TRUE)
bench::mark(
  recode = dplyr::recode(char_vec, a = "Apple", b = "Banana")
)
#> # A tibble: 1 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 recode        1.9ms   2.62ms      335.    3.54MB     10.7
```

<sup>Created on 2023-07-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I also opened an issue in lifecycle: https://github.com/r-lib/lifecycle/issues/167

**Comment by DavisVaughan** [comment]
We will track in https://github.com/r-lib/lifecycle/issues/167
