### ISSUE TITLE
Getting dplyr error with OmnipathR install

### ISSUE THREAD

**Issue by rstorch01** [tidyverse/dplyr#6893]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
remotes::install_github("saezlab/liana")

* installing *source* package ‘OmnipathR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘join_by’ is not exported by 'namespace:dplyr'
Execution halted

```r
# insert reprex here
```

**Comment by DavisVaughan** [comment]
It looks like you need to install the latest version of dplyr with `install.packages("dplyr")` first. You should restart R, run that, and then restart R again just to be safe
