### ISSUE TITLE
Usage of `overlaps()`, `closest()`, `between()`, and `within()` in join_by() triggers NOTE

### ISSUE THREAD

**Issue by koenniem** [tidyverse/dplyr#6894]
I'm using the new helpers `overlaps()`, `closest()`, `between()`, and `within()` in the `join_by()` function in my CRAN package. However, when I run R CMD CHECK, it generates the following NOTE:

```
no visible global function definition for 'closest'
```

Normally I would evade such a note by either importing the function into my package, prefixing the namespace, or using the `.data$` pronoun. None of these are possible, as `dplyr::overlaps()` doesn't exist (see also #6838) , and the `.data$` pronoun clearly shouldn't be used and also doesn't work.

One possible workaround is defining the helpers in `globalVariables`,but as Hadley noted this is a ["hideous hack"](https://stackoverflow.com/a/12429344), and I'd prefer to avoid it if possible. 

How can these helpers be used in `join_by()` without triggering a NOTE during CRAN checks?

**Comment by DavisVaughan** [comment]
The `globalVariables()` helper is fine to use here. We mention this here https://dplyr.tidyverse.org/articles/in-packages.html#join-helpers
