### ISSUE TITLE
row_number(df) has an unexpected behavior for zero col data frames

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#6899]
The results is actually non stable

```
# zero col
row_number(data.frame(row.names = 1:10))
#> [1] 582098136         1 582098024         1 585748024         1 537055392         1 251706160         1

# one col
row_number(data.frame(10:1))
#> [1] 10  9  8  7  6  5  4  3  2  1
```

My expectation would have been `1:10` (we have nothing to order so all rows are assumed equal and disambiguated by using the first), but I would understand an error, or `rep(NA, 10)` as well.

btw the argument-less use is not documented, it was reported in #5820 but no action was taken AFAICT

**Comment by DavisVaughan** [comment]
Tracking in https://github.com/r-lib/vctrs/issues/1863
