### ISSUE TITLE
Add natural sort option to `arrange()`

### ISSUE THREAD

**Issue by bounlu** [tidyverse/dplyr#6917]
Currently there is no option for `arrange()` to mimic the natural/human sorting of columns containing alphanumerical characters. In Bash, this can be achieved by `sort -V`. Please add this feature to `arrange()`.

```
df %>% arrange(Sample)

Sample
S10a
S10b
S11a
S11b
S12a
S12b
S13a
S13b
S14a
S14b
S15a
S15b
S16
S17
S18
S19
S1a
S1b
S2a
S2b
S3a
S3b
S4a
S4b
S5a
S5b
S6a
S6b
S7a
S7b
S8
S9
```

In Bash, we can sort the same column with `sort -V`:

```
$ sort -V Sample
S1a
S1b
S2a
S2b
S3a
S3b
S4a
S4b
S5a
S5b
S6a
S6b
S7a
S7b
S8
S9
S10a
S10b
S11a
S11b
S12a
S12b
S13a
S13b
S14a
S14b
S15a
S15b
S16
S17
S18
S19
```

**Comment by DavisVaughan** [comment]
You can always rank the string column with `stri_rank()` and the corresponding locale options that use natural sorting

``` r
library(dplyr)
library(stringi)

locale <- list(locale = "en_US", numeric = TRUE)

df <- tibble(x = c("S1a", "S10a", "S1b", "S8", "S11"))

dplyr::arrange(df, stri_rank(x, opts_collator = locale))
#> # A tibble: 5 × 1
#>   x    
#>   <chr>
#> 1 S1a  
#> 2 S1b  
#> 3 S8   
#> 4 S10a 
#> 5 S11
```

<sup>Created on 2023-08-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bounlu** [comment]
Reopen as not implemented.
