### ISSUE TITLE
The .keep= "unused" parameter of the mutate does not work correctly when the ifelse function (from the base) is called

### ISSUE THREAD

**Issue by apalacio9502** [tidyverse/dplyr#6922]
Hello,

I have detected that if the ifelse function (of the base) is used within a mutate and the .keep parameter is equal to "unused", in certain situations the columns called by the ifelse do not disappear.

For example, if the true value does not apply to any row, it generates that the column that is called in the true value does not disappear. This behavior does not happen when using the if_else function, however I think this is a bit confusing for the end user.

I understand that the if_else function evaluates the entire expression which causes .keep = "unused" to work correctly.

```
# Example ifelse --------------------------------

data <- data.frame(
  ROW = c(1,2,3,4),
  VALUE_1 = c("A","A","A","A"),
  VALUE_2 = c("B","B","B","A")
)

data %>%
  mutate(
    EXPRESION = ifelse(
      test = ROW > 4,
      yes = VALUE_1,
      no = VALUE_2
    ), .keep = "unused"
  ) 

Result:
  VALUE_1 EXPRESION
1       A         B
2       A         B
3       A         B
4       A         A

# Example if_else ------------------------------

data <- data.frame(
  ROW = c(1,2,3,4),
  VALUE_1 = c("A","A","A","A"),
  VALUE_2 = c("B","B","B","A")
)

data %>%
  mutate(
    EXPRESION = if_else(
      condition = ROW > 4,
      true = VALUE_1,
      false = VALUE_2
    ), .keep = "unused"
  ) 

Result:
  EXPRESION
1         B
2         B
3         B
4         A

```

Regards,

**Comment by DavisVaughan** [comment]
Unfortunately there isn't anything we can do about this since `ifelse()` is somewhat lazy and doesn't evaluate the `yes` condition when only `FALSE` values are seen in the condition. This means the `VALUE_1` binding is never triggered and it doesn't look "used" to us. I realize this is slightly confusing but I think the tradeoff of leaving this as is vs trying to find a way around it just isn't worth it
