### ISSUE TITLE
arrange Function Suggestion

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/dplyr#6926]
Let say I have dataframe 
df <- data.frame(a = c(1, 2, 3, 3), b = c(2, 2.5, 3, 1), z = letters[1:4])
and i would like to arrange ascending
df %>% arrange(a, b)
if i would like to arrange descending
df %>% arrange(desc(a), desc(b))

if it possible to have an argument .decreasing = TRUE/FALSE so
df %>% arrange(desc(a), desc(b)) will be 
df %>% arrange(a, b, .decreasing = TRUE)

i am suggesting this cos i might have more than two columns to arrange descending.

**Comment by philibe** [comment]
Hello

```
arrange(df, across(c(a,b), desc))
#>  a   b z
#>  1 3 3.0 c
#>  2 3 1.0 d
#>  3 2 2.5 b
#>  4 1 2.0 a

df %>% arrange( across(c(a,b), desc))
#>  a   b z
#>  1 3 3.0 c
#>  2 3 1.0 d
#>  3 2 2.5 b
#>  4 1 2.0 a
```

https://stackoverflow.com/questions/38052325/arrange-multiple-columns-with-descending-order/67506887#67506887

**Comment by DavisVaughan** [comment]
The `across()` usage there is nice, we are not considering any further extensions to make this more compact at this time, thanks!
