### ISSUE TITLE
incorrect column name when mutate uses indexing -- but only when mutating a tibble, not a data.frame.

### ISSUE THREAD

**Issue by gcpoole** [tidyverse/dplyr#6928]
When I use indexing (square bracket) in a `mutate` command, the resulting column name and column contents are incorrect, but only when I `mutate` a `tibble`.  Behavior is as expected when I `mutate` a `data.frame`.

```r
library(tibble)
library(dplyr)

# expected behavior using data.frame.
> cars %>% mutate(slow = speed < .[3,1]) %>% head()
  speed dist  slow
1     4    2  TRUE
2     4   10  TRUE
3     7    4 FALSE
4     7   22 FALSE
5     8   16 FALSE
6     9   10 FALSE

# unexpected name and incorrect values when using a tibble
> cars %>% as_tibble() %>% mutate(slow = speed < .[3,1]) %>% head()
# A tibble: 6 × 3
  speed  dist slow[,"speed"]
  <dbl> <dbl> <lgl>         
1     4     2 TRUE          
2     4    10 TRUE          
3     7     4 TRUE          
4     7    22 TRUE          
5     8    16 TRUE          
6     9    10 TRUE 
```
Again, note that a problem occurs in **both** the name of the new column and in the contents thereof.

**Comment by DavisVaughan** [comment]
This is separate from dplyr, tibble indexing with `[` is different from data.frame indexing in that it will never return a vector, it always returns another data frame.

``` r
library(tibble)

cars[3,1]
#> [1] 7

as_tibble(cars)[3,1]
#> # A tibble: 1 × 1
#>   speed
#>   <dbl>
#> 1     7
```

<sup>Created on 2023-09-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
