### ISSUE TITLE
! and - behave differently in `select()

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#6959]
In R4DS we say

> You can also use `-` instead of `!` (and you’re likely to see that in the wild); we recommend `!` because it reads as “not”, and combines well with `&` and `|`.

However, they behave differently in `select()`:

``` r
library(dplyr)

mtcars |> as_tibble() |> select(mpg:disp, !cyl)
#> # A tibble: 32 × 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # ℹ 22 more rows
mtcars |> as_tibble() |> select(mpg:disp, -cyl)
#> # A tibble: 32 × 2
#>      mpg  disp
#>    <dbl> <dbl>
#>  1  21    160 
#>  2  21    160 
#>  3  22.8  108 
#>  4  21.4  258 
#>  5  18.7  360 
#>  6  18.1  225 
#>  7  14.3  360 
#>  8  24.4  147.
#>  9  22.8  141.
#> 10  19.2  168.
#> # ℹ 22 more rows
```

<sup>Created on 2023-11-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Originally reported at https://github.com/hadley/r4ds/issues/1528 by @coltongearhart.

**Comment by DavisVaughan** [comment]
CC @lionel-, I don't think there is a bug in tidyselect, I just don't think `-` and `!` are actually interchangeable like this. But I'll let Lionel weigh in on how best to handle this

**Comment by hadley** [comment]
`select(mpg:disp, !cyl)` does make sense as `select(mpg:disp | !cyl)` which is the usual select semantics. So I think this behaviour is correct.

**Comment by DavisVaughan** [comment]
Does this imply R4DS needs a tweak? Since it seems to imply `!` and `-` are fully interchangeable?

**Comment by lionel-** [comment]
Another way they differ is in operator precedence, so `!foo:bar` and `-foo:bar` behave differently. I'll add a note to R4DS saying that these operators have the same purposes but with subtle differences and that's another reason to prefer using `!`.
