### ISSUE TITLE
Different and inconsistent `.by / by` behaviours in different functions of dplyr

### ISSUE THREAD

**Issue by Yann-C-INN** [tidyverse/dplyr#6964]
Hi. Maybe these things can be considered in a new dplyr realse:
The .by argument added to reframe/mutate and alike is awesome. however, it seems like there are still some inconsistencies across the various functions.

```
library(tidyverse)
mtcars |> slice_max(mpg, .by=cyl) # Error. Doesn't work with the dot
mtcars |> slice_max(mpg,by=cyl) # Returns a grouped (though ungrouped) data frame (with row names)
mtcars |> reframe(mpg = max(mpg),.by=cyl) # Returns a summarized data frame (without row names)
mtcars |> reframe(mpg = max(mpg),by=cyl) # returns a completley different result, where the cyl variable has changed to by with the same values and no grouping was done (nrow is the same as original data).

```

I am quite sure that the last example of reframe and `by` without the dot is not what most users would expect, and the inconsistency might be confusing for new users. 

Thank you,
Yann

**Comment by DavisVaughan** [comment]
The difference of `.by` vs `by` is documented here https://dplyr.tidyverse.org/reference/dplyr_by.html#supported-verbs

Luckily most of the time autocomplete can help you figure out which one is supported without having to remember / look that up.

We've tried to error in cases where it is unambiguous (like slice_max), but in the case of `reframe()` it is perfectly reasonably to construct a new column named `by`, and it is very likely that many people have called `mutate()`, `summarise()`, or `reframe()` to do exactly this, so we can't turn that into an error. Unfortunately this is just a silent typo that we can't easily tell the user about.
