### ISSUE TITLE
Native pipe does not work with rowwise

### ISSUE THREAD

**Issue by Yann-C-INN** [tidyverse/dplyr#6965]
Using the `dplyr::rowwise` i noticed something strange. 
The native R pipe (|>) Doesn't work, where's the `magrittr::%>%` works just fine.

The following code works:

`mtcars |> rowwise() %>% mutate(sum = sum(.))`

But this one doesnt:

`mtcars |> rowwise() |>  mutate(sum = sum(.)) `

**Comment by bhattmaulik** [comment]
I guess the problem is not the pipe, but the dot inside sum(.). The base R pipe needs a different syntax to work.

**Comment by Yann-C-INN** [comment]
> I guess the problem is not the pipe, but the dot inside sum(.). The base R pipe needs a different syntax to work.

It doesnt make sensethat these pipes will not work the same... I find this a bugrather than a feature

**Comment by philibe** [comment]
> It doesnt make sensethat these pipes will not work the same... I find this a bugrather than a feature.

They are similar but intrinsically a little differents.

Read that please:

- https://www.tidyverse.org/blog/2023/04/base-vs-magrittr-pipe/
- https://towardsdatascience.com/understanding-the-native-r-pipe-98dea6d8b61b

**Comment by philibe** [comment]
Here is workaround for result identical to your example `mtcars |> rowwise() %>% mutate(sum = sum(.))`

- `mtcars |>  {\(.)  mutate(., sum= sum(.))  }()`  from https://stackoverflow.com/questions/75961573/use-base-r-pipe-in-conditional-dplyr-chain/75961590#75961590

**Comment by Yann-C-INN** [comment]
> Here is workaround for result identical to your example `mtcars |> rowwise() %>% mutate(sum = sum(.))`
> 
> * `mtcars |>  {\(.)  mutate(., sum= sum(.))  }()`  from https://stackoverflow.com/questions/75961573/use-base-r-pipe-in-conditional-dplyr-chain/75961590#75961590

the workaround is to use the more robust pipe if you ask me ;) thanks though. I am not convinced that this is something worth keeping in the future (the differences) but sure. I'll adjust my defaults

**Comment by DavisVaughan** [comment]
The base R pipe is deliberately different from the magrittr pipe. The differences are outlined in https://www.tidyverse.org/blog/2023/04/base-vs-magrittr-pipe/#-vs as @philibe mentioned, and there is nothing dplyr can do to support this differently
