### ISSUE TITLE
the functions filter and full_join do not work properly with numbers with 4 decimals or more.

### ISSUE THREAD

**Issue by PStaus** [tidyverse/dplyr#6971]
The functions filter and full_join do not work properly with numbers with 4 decimals or more.
---
Thank you for the very nice package. I use it every day. 
I found out that some functions have problems when it comes to numbers with 4 decimals.
The filter function and also the Join function do not seem to work properly when applied to numbers with this precision.
If converted to character the functions work again.
This is an unexpected behaviour and produces unexpected results, which can be quite dangerous.
```r

# Repex 1 for filter:

library(dplyr)
longseq <- data.frame(time = seq(0,10, 0.0001))
longseq[70002,]
longseq %>% filter (time == 7.0001)
longseq %>% filter (time == "7.0001")
class(longseq$time)
typeof(longseq$time)

# Repex 2 for join:

shortseq <- data.frame(old_time =  c(0, 3:7, 7.0001, 8:10))
joinedframe <- full_join(shortseq, longseq,
          by = c("old_time" = "time"),
          na_matches = "never",
          keep = TRUE) %>%
  arrange(time)

joinedframe %>% filter(time == 7.0001)
joinedframe[70002,]
tail(joinedframe,10)

shortseq_as_char <- short_seq %>%
  mutate(old_time = as.character(old_time))
longseq_as_char <- longseq %>% 
  mutate(time = as.character(time))
joinedframe_as_char <- full_join(shortseq_as_char, longseq_as_char,
                         by = c("old_time" = "time"),
                         na_matches = "never",
                         keep = TRUE) %>%
  mutate(time = as.numeric(time)) %>%
  arrange(time)

joinedframe_as_char %>% filter(time == 7.0001)
joinedframe_as_char[70002,]
tail(joinedframe_as_char, 10)
```

**Comment by DavisVaughan** [comment]
This is a typical problem with floating point numbers. Manually typing in `7.0001` and generating the supposedly equivalent value with `seq()` results in two different numbers under the hood:

``` r
options(digits = 22)

seq(0,10, 0.0001)[70002]
#> [1] 7.00010000000000065512

7.0001
#> [1] 7.000099999999999766942
```

They are close, but not quite the same. There is a nice python article about this:
https://docs.python.org/3/tutorial/floatingpoint.html

In general, filtering or joining on fractional numbers like this is going to be problematic. For filtering, one solution is to use `near()`:

``` r
library(dplyr)
longseq <- data.frame(time = seq(0,10, 0.0001))
longseq[70002,]
#> [1] 7.0001
longseq %>% filter(near(time, 7.0001))
#>     time
#> 1 7.0001
```

For joins, you should try to avoid using floating point numbers if you can, or at least round them to the nearest second first if they are times. If you really need fractional seconds, you could look into nanotime or clock, which have "true" subsecond types that aren't backed by floating point types, so they would work better for that.

Other than that, there isn't much dplyr can do here

**Comment by PStaus** [comment]
Thank you Davis Vaughan!
this helped me a lot. And thank you for the very fast reply and pointing to the other two packages. I will have a look on using different classes for joining data frames.
