### ISSUE TITLE
relocate: naming index-identified column triggers warning unless index wrapped in all_of() et al.

### ISSUE THREAD

**Issue by david-romano** [tidyverse/dplyr#6975]
Running:
```r
library(tidyverse)
tibble(a = 0) |> 
  relocate(b = 1)
```
works, but raises:
> Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()`  instead.

so that running:
```r
library(tidyverse)
tibble(a = 0) |> 
  relocate(b = all_of(1))
```
does not.

**Question**:  It seems strange to have to use `all_of()` et al. with a vector of length 1.  Is there a conceptually cleaner way to rename and relocate a column identified by its index?

**Comment by DavisVaughan** [comment]
Works for me without warnings, you may have an outdated version of a package

```r
library(dplyr)

tibble(a = 0) |> 
  relocate(b = 1)
#> # A tibble: 1 × 1
#>       b
#>   <dbl>
#> 1     0
```

Here is my set of packages, you could look into updating dplyr or tidyselect?

```
 package     * version    date (UTC) lib source
 cli           3.6.1.9000 2023-11-16 [1] Github (r-lib/cli@ef77a16)
 dplyr       * 1.1.3      2023-09-03 [1] CRAN (R 4.3.0)
 fansi         1.0.5      2023-10-08 [1] CRAN (R 4.3.1)
 generics      0.1.3      2022-07-05 [1] CRAN (R 4.3.0)
 glue          1.6.2.9000 2023-10-31 [1] Github (tidyverse/glue@42d29d4)
 lifecycle     1.0.4      2023-11-07 [1] CRAN (R 4.3.1)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.3.0)
 pillar        1.9.0      2023-03-22 [1] CRAN (R 4.3.0)
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.3.0)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.3.0)
 rlang         1.1.2.9000 2023-11-16 [1] Github (r-lib/rlang@81c7dcd)
 rstudioapi    0.15.0     2023-07-07 [1] CRAN (R 4.3.0)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.3.0)
 tibble        3.2.1      2023-03-20 [1] CRAN (R 4.3.0)
 tidyselect    1.2.0      2022-10-10 [1] CRAN (R 4.3.0)
 utf8          1.2.4      2023-10-22 [1] CRAN (R 4.3.1)
 vctrs         0.6.5.9000 2023-12-05 [1] Github (r-lib/vctrs@8bf5ba5)
 withr         2.5.2      2023-10-30 [1] CRAN (R 4.3.1)
```

**Comment by david-romano** [comment]
Sorry, I mistook when the warning was triggered:  I have that same dplyr and tidyselect versions as you, and the code I posted doesn't trigger it.   What does is when it's used within a function:
``` r
library(dplyr)

test <- function(n = 1){
  tibble(a = 0) |> 
  relocate(b = n)
}

test()
#> Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
#> ℹ Please use `all_of()` or `any_of()` instead.
#>   # Was:
#>   data %>% select(n)
#> 
#>   # Now:
#>   data %>% select(all_of(n))
#> 
#> See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.
#> # A tibble: 1 × 1
#>       b
#>   <dbl>
#> 1     0
```

<sup>Created on 2023-12-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
Ok yes in that case the warning you are seeing is expected. It is ambiguous whether you want a column `n` from the data frame, or the vector `n` from your environment. To unambiguously use `n` from the env, use `all_of(n)`

**Comment by david-romano** [comment]
It would think that if the external vector consists of integers, there should be no issue since integers would be nonsyntactic column names.  Couldn't numeric vectors be excluded from the warning?

**Comment by DavisVaughan** [comment]
Regardless of the underlying value, it is still ambiguous, it could mean one of two things:
- `n`, a column in the data frame
- `n`, an object in your environment

If we wrote tidyselect over again, we would have made the code you've currently written an error, because we'd look for `n` in the data frame, fail to find it, and then immediately error about that. And the only way to include "external" objects would be to use `all_of()` or `any_of()`

**Comment by david-romano** [comment]
Thanks for the clarification.
