### ISSUE TITLE
Feature Request: profiling options for a chain of pipes

### ISSUE THREAD

**Issue by wbvguo** [tidyverse/dplyr#6983]
Dear `dplyr` developer,

Thanks for maintaining this tool. 

The pipe `%>%` is convenient for data processing, I was wondering if `dplyr` can provide profiling option to evaluate the time and memory needed to finish a step. This might be useful when evaluating and optimizing the data processing pipelines

e.g. from
```r
mtcars %>% group_by(cyl) %>% summarize(mean= mean(mpg))
```

to something like 
```r
mtcars %tm>% group_by(cyl) %TM>% summarize(mean= mean(mpg))
```

where `t`, `m`, `T`, `M` are 4 options, which stand for
- t, m:  time/memory needed to finish the next following step
- T,M: time/memory needed to finish the whole pipeline

Thanks,
Wenbin

**Comment by DavisVaughan** [comment]
This sounds like something that would be nice for a separate package, but isn't something we plan to provide in dplyr itself.
