### ISSUE TITLE
Unexpected behavior in summarize()

### ISSUE THREAD

**Issue by RoyalTS** [tidyverse/dplyr#6994]
In the below, column `a` contains two `NA`s, yet `sum(is.na(a))` in the summarize yields `1`:

```r
tibble::tibble(
  a = c(NA, NA),
  b = c(1, 2)
) |>
  dplyr::summarize(
    across(everything(), ~ mean(., na.rm = TRUE)),
    a_is_missing = sum(is.na(a))
  )
#> # A tibble: 1 × 3
#>       a     b a_is_missing
#>   <dbl> <dbl>        <int>
#> 1   NaN   1.5            1
```

I get the correct result if I reverse the order of the items in the `summarize` – if I count missings first, then take means.

Is what's going on here that `sum(is.na(a))` takes `a` to be the column named `a` that's created by the `across()` instead of the column in the original `tibble`?

**Comment by etiennebacher** [comment]
> Is what's going on here that sum(is.na(a)) takes a to be the column named a that's created by the across() instead of the column in the original tibble?

Yes, from the [docs of `summarize()`](https://dplyr.tidyverse.org/reference/summarise.html#backend-variations):

> The data frame backend supports creating a variable and using it in the same summary. This means that previously created summary variables can be further transformed or combined within the summary, as in [mutate()](https://dplyr.tidyverse.org/reference/mutate.html). However, it also means that summary variables with the same names as previous variables overwrite them, making those variables unavailable to later summary variables.

Here's a slightly simpler example:

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = 1:2) |> 
  mutate(
    x = 3:4,
    x_mean = mean(x) # this computes the mean of 3 and 4, not of 1 and 2
  )
#> # A tibble: 2 × 2
#>       x x_mean
#>   <int>  <dbl>
#> 1     3    3.5
#> 2     4    3.5
```

**Comment by RoyalTS** [comment]
I don't suppose it would make sense to emit a warning whenever this happens? I thought the behavior was _extremely_ unintuitive and it took me quite a long while to figure out what was happening.

**Comment by etiennebacher** [comment]
I'm not a `tidyverse` developer so I can't answer that for sure, but I think it's extremely unlikely they change the behavior to throw a warning. There must be an enormous amount of existing code that relies on this behavior and this change would trigger warnings everywhere.

Note that a simple solution in your case is to automatically rename columns modified in `across()` by using the `.names` argument:
``` r
library(dplyr, warn.conflicts = FALSE)

tibble(
  a = c(NA, NA),
  b = c(1, 2)
) |>
  summarize(
    across(everything(), ~ mean(., na.rm = TRUE), .names = "{.col}_mean"),
    a_is_missing = sum(is.na(a))
  )
#> # A tibble: 1 × 3
#>   a_mean b_mean a_is_missing
#>    <dbl>  <dbl>        <int>
#> 1    NaN    1.5            2
```

**Comment by DavisVaughan** [comment]
Unfortunately this is a decision we are stuck with, as @etiennebacher said there is a lot of code out there that depends on this, and some people really do like this behavior. I agree it can be very surprising, but this is one of those things where there isn't much we can do about it without annoying some non zero subset of the community
