### ISSUE TITLE
Add param to left_join to set value when does not exists match

### ISSUE THREAD

**Issue by latot** [tidyverse/dplyr#6996]
Hi, I think this feature could be very useful, when we perform a left join, if the value does not exists, be able to set the default value to something instead of always being NA.

This also simplifies some cases where the data already has NA and we can't easily know which values was not found to replace them.

**Comment by DavisVaughan** [comment]
I think the most generic way to solve this is with a merge indicator https://github.com/tidyverse/dplyr/issues/6435, where you'd tack on the merge indicator column and then use that to update any missing values to whatever value you actually want it to be

**Comment by latot** [comment]
well, yeah, we can do that, there is workaround solutions, but I think is too much code, and does this more complex from what it can be...

This feature could simplify all that with just one param.
