### ISSUE TITLE
R: group_by() column1 and perform rle() on column2

### ISSUE THREAD

**Issue by davidss101** [tidyverse/dplyr#6997]
Hello Everyone, 

I was wondering if people could help with this problem.  I am trying to use group_by() and rle() in R to group according to column1 and count the consecutive number of times there is either a one or a zero within each group from column2.  I would like to return both the "values" and "lengths" data from using rle().  

This is what my data frame (df1) looks like: 

<img width="166" alt="Screenshot 2024-02-29 at 4 20 49 PM" src="https://github.com/tidyverse/dplyr/assets/119550460/523eed6e-721c-48c1-87ba-d9539eb80e2b">

I used this code to generate what I thought might work based on some suggestions I found on the web.

df2 <- df1 %>% group_by(column1) %>% reframe(data.frame(unclass(rle(df1$column2))))

This is the output I get for df2:

<img width="210" alt="Screenshot 2024-02-29 at 4 24 43 PM" src="https://github.com/tidyverse/dplyr/assets/119550460/93d6ed01-e28b-4500-a904-3fdaa1f5c1d7">

It seems that my code is not grouping the data effectively according to column1.  Any suggestions would be appreciated.  Thanks.

**Comment by davidss101** [comment]
I'm sorry I forgot to mention that this is what I am looking for:

<img width="204" alt="Screenshot 2024-02-29 at 4 36 10 PM" src="https://github.com/tidyverse/dplyr/assets/119550460/cf3976d1-2c23-4bce-a0a0-8f2098c42bd1">

**Comment by davidss101** [comment]
Hi Everyone,

Since I was ultimately interested in only the values in column1 which were "1", I used this code that I adapted from another website.  Unfortunately, I forget now what that site was.

df2 <- df1 %>% group_by(column1) %>% mutate(sequence = data.table::rleid(column2 == 1),) %>% filter(column2 == 1) %>% group_by(column1, sequence) %>% summarise(length = n())

Thanks.

**Comment by williamlai2** [comment]
Hi, the issues here a specific to the package code.

You might get more help on your problem at: https://community.rstudio.com/

**Comment by psychelzh** [comment]
Or a better place to go is https://stackoverflow.com/.
