### ISSUE TITLE
Ascendant order explicit function for arrange

### ISSUE THREAD

**Issue by latot** [tidyverse/dplyr#6998]
Hi all, actually the function arrange by default order in ascendant way, if we want it in reverse we can use ```dplyr::desc```, I think would be great also have the ascendant function in a explicit way.

If we think only in ppl who uses R, this would not be needed, because with the time all ppl will know the default behavior, here where there is the main arguments to why create this function:

- If the default behavior changes by any reason, be able to declare it explicitly will helps to don't change the behavior of the current code (this is more likely low probability case)
- Other functions who also can use order of columns, could use this one to know the order
- Ppl does not only uses dplyr and R, some other libraries can sort in descendant, other languages too, try to remember and know each case causes to be a lot harder the readability of code, declare this explicitly helps to know in the moment the intention of the code, personally this is what affects me, because I use more languages.

Thx!

**Comment by DavisVaughan** [comment]
I appreciate the idea in terms of making code easier to read, but I doubt that many people would use it in practice. I do think a lot of people are used to ascending order by default, so I don't think the "hidden" default is _that_ hard to understand.

If you would like to make your own code more explicit, you can always add `asc <- function(x) x` which does nothing but would allow you to say `arrange(mtcars, asc(mpg))`, but as of this time we don't plan to add this.

Thanks!

**Comment by latot** [comment]
Would be acceptable a PR with that idea?
