### ISSUE TITLE
Allow tidyselect operators inside `distinct()`

### ISSUE THREAD

**Issue by AltfunsMA** [tidyverse/dplyr#7003]
I find that `distinct()` has use as a selecting function, showing the minimum number of combinations of a few columns within a dataframe. The tidyselect operators would be very convenient in this task. 

`tidytable` has incorporated this functionality; I was wondering whether there are plans to adapt it into the `dplyr` version. I couldn't find an issue directly related to this topic.

I note that `pick()` works, but its use with `distinct` is not documented in either `distinct()` or `pick()` itself.

```r
library(dplyr)

# This doesn't work
iris %>% 
  distinct(contains("Petal"))

# This does
iris %>% 
  tidytable::distinct(contains('Petal'))

# This also works but it's not documented

iris %>% 
  distinct(pick(contains("Petal")))

```

**Comment by psychelzh** [comment]
Actually, based on the documentation, this is the expected behavior. `distinct()` supports data-masking not tidy-select:

> \<data-masking\> Optional variables to use when determining uniqueness. If there are multiple rows for a given combination of inputs, only the first row will be preserved. If omitted, will use all variables in the data frame.

You can refer to [this article](https://dplyr.tidyverse.org/articles/programming.html) for more information. Basically, if you want to use tidy-select in functions supporting data-masking, `pick()` will be bridge of these two.

**Comment by AltfunsMA** [comment]
Thanks @psychelzh. I'm just asking for `distinct` to support tidyselect as it does in tidytable because it's convenient. 

To make the case clearer, columns that capture a particular aspect of observations (e.g. geography) may have a prefix (e.g. "loc_"). In your EDA, you may naturally want to see what possible combinations of those variables exist in your data with `distinct(df, contains("loc_"))`. `Pick` feels like a repetitive/illogical intermediate step, since distinct's main mechanism is already picking/selecting columns to get unique rows based on them.

Neither of those articles you link or `?pick()` give `distinct` as an example, probably because it's not what the Devs were thinking of facilitating when creating `pick()`. `distinct()` apparently uses `mutate` and inherits its behaviour, so it might be hard to change but it doesn't seem unreasonable to suggest it should.

**Comment by psychelzh** [comment]
I think maybe dplyr authors think of `distinct()` a function more like `mutate()`, so they classify it into the data-masking group. I am sorry those articles do not help, but if you really grasp the ideas behind data-masking and tidy-select and know the differences between them, you will find if you need to use tidy-select in which only data-masking is supported, `pick()` or `across()` is the bridge.

Return to add tidy-select support for `distinct()`, I think I should agree with you a little, for I was really kind of surprised when finding out it is a data-masking one. But, I think the team will continue treat it as data-masking, and tell us to use the bridge.

BTW, the bridge is a common pattern in `dplyr`, for example, you would use `mutate(across(<tidy-select>, <fun>))` when you want to use tidy-select in `mutate()`.

**Comment by DavisVaughan** [comment]
> I'm just asking for distinct to support tidyselect as it does in tidytable because it's convenient.

We unfortunately cannot. This has come up many times over the years. As @psychelzh says, `distinct()` and `group_by()` are data-masking functions like `mutate()`, even though one could argue (and I do feel this way nowadays) that they should really be pure tidyselection functions (it would certainly simplify the internals!).

_Mixing_ data-masking and tidy-select support would be quite difficult and error prone, so we have to choose one or the other, and that choice was made years ago 😄 

---

`pick()` is indeed the bridge solution. The documentation does link them in an indirect way: 

`pick()` docs:

> pick() provides a way to easily select a subset of columns from your data using [select()](https://dplyr.tidyverse.org/reference/select.html) semantics while inside a ["data-masking"](https://rlang.r-lib.org/reference/args_data_masking.html) function like [mutate()](https://dplyr.tidyverse.org/reference/mutate.html) or [summarise()](https://dplyr.tidyverse.org/reference/summarise.html)

Dots of `distinct()`:

> ... <[data-masking](https://rlang.r-lib.org/reference/args_data_masking.html)> Optional variables to use when determining uniqueness.

So the link is in the mentioning of data-masking
