### ISSUE TITLE
bind_rows unexpectedly renames columns

### ISSUE THREAD

**Issue by lboller-pwbm** [tidyverse/dplyr#7013]
If column names have "default" column names from dplyr, bind_rows will sometimes change the number of the column name unexpectedly. Reprex below. I would expect that this line would not rename the columns but return the tibble unchanged.

``` r
dplyr::bind_rows(list(tibble::tibble(...2 = 1, ...3 = 2)))
#> New names:
#> • `...2` -> `...1`
#> • `...3` -> `...2`
#> # A tibble: 1 × 2
#>    ...1  ...2
#>   <dbl> <dbl>
#> 1     1     2
```

<sup>Created on 2024-04-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
In `vctrs::vec_as_names()` we mention

> Pre-existing suffixes of the form ...j are always stripped, prior to making names unique, i.e. reconstructing the suffixes. If this interacts poorly with your names, you should take control of name repair.

I don't think we need to re-mention this here, as it is sufficiently niche.

The main idea is that behavior with these `...j` names is not something you should really rely on. Those names are there to make you as the user aware that something weird is happening, and it encourages you to try and handle the names explicitly using some better mechanism.
