### ISSUE TITLE
Error in across

### ISSUE THREAD

**Issue by Unaimend** [tidyverse/dplyr#7041]
```r
data(iris)
iris %>%
  group_by(Species) %>%
  summarise(across(starts_with("Sepal"), ~ mean(.x, na.rm = TRUE)))
```
Results in following error
`Error in `across()`:
! Must only be used inside data-masking verbs like `mutate()`, `filter()`, and `group_by()`.
Run `rlang::last_trace()` to see where the error occurred.
(ins)> `

The code was copied from the documentation 
https://dplyr.tidyverse.org/reference/across.html#:~:text=across()%20makes%20it%20easy,colwise%22)%20for%20more%20details.

**Comment by Unaimend** [comment]
This is  definitely an issue with my current environment not with dplyr

**Comment by efisso** [comment]
I also have the same problem... I was able to run my code before but I guess with the latest update I get this error when I used group_by() and then summarise(across())... any suggestions?

**Comment by philibe** [comment]
No, no.

When you have issues with masked functions, you have to prefix by the name of the package (or change the order of the loadind)

- `library(AAA)` with function `select`
- `library(BBB)` with function `select`
- => Therefore `select` will call `select` of `BBB` except if you write `AAA::select()`

For example if you load a package containing the `select` function after the loading of `dplyr`, the `select` won't be that of `dplyr`.
