### ISSUE TITLE
group_split(): add a '.groups_to_names=T' type argument

### ISSUE THREAD

**Issue by barnabasharris** [tidyverse/dplyr#7042]
When splitting by categorical (or indeed integer) groups it might be useful to transfer the grouped values to the names of the resulting list object, to assist with functions later in the pipeline.

**Comment by DavisVaughan** [comment]
Yea names on the list are not the right place for this information as it only works decently for single variable cases, and even then it isn't perfect.

I think the results of `tidyr::nest(.by = )` are much more appropriate for this

**Comment by DanChaltiel** [comment]
I ended up on this 2-year-old issue, so it might be relevant to post.
Here is how you can have almost the `base::split()` behaviour with tidyverse syntax in 2026:
```r
iris |>
  tidyr::nest(data=-Species) |>
  tibble::deframe()
```
This creates a named list, the only difference being that the tibbles inside don't have the `Species` column.

It is a bit surprising that the tidyverse team is forbidding names in some parts, considering it even an anti-pattern, but not in others, and TBH it is a bit frustrating that it is done with no consideration for the community's arguments and needs.
