### ISSUE TITLE
Error in the function 'across()'

### ISSUE THREAD

**Issue by Mzhuk7** [tidyverse/dplyr#7051]
Brief description of the problem:
In some of the old courses, I pass using this function from h:
  h_st <- mutate_each (h,"scale") 
Rstudio says that this function is obsolete.
it suggests to use across. I've checked several sites and created the following function.  
h_st <- mutate(across(c("Fertility","Agriculture", "Examination","Education", "Catholic","Infant.Mortality"),scale))

But Rstudio says the following:
"Error in `across()`:
! Must only be used inside data-masking verbs like `mutate()`, `filter()`, and `group_by()`"
and I cannot understand the error here, because across is in "()".

Can someone please help to solve this problem?

**Comment by philibe** [comment]
IMHO you have forgotten the dataset, `h` in your case:
- `mutate(h, across(c("Fertility","Agriculture", "Examination","Education", "Catholic","Infant.Mortality"),scale))`
- `h%>%  mutate(across(c("Fertility","Agriculture", "Examination","Education", "Catholic","Infant.Mortality"),scale))`


PS: I'm a simple user (ie not from the tidyverse team).

**Comment by philibe** [comment]
```R
  Examination=1:5,
  Education=1:5,
  Catholic=1:5,
  Infant.Mortality=1:5,
  other1=1:5,
  other2=1:5,
)

mutate(h,across(c("Fertility","Agriculture", "Examination","Education", "Catholic","Infant.Mortality"),scale))
```
