### ISSUE TITLE
`if_else` `missing` argument does not work when using `%in%` to evaluate.

### ISSUE THREAD

**Issue by Raesu** [tidyverse/dplyr#7054]
This function could refer to the `missing` argument to fill in missing values. It works except for when `%in%` is used in the condition to check.

---
```r
x <- c(NA, 1,2,3)

# Expected behavior, NA passes through
if_else(x == 2, TRUE, FALSE)

# NA is converted to FALSE
if_else(x %in% c(2), TRUE, FALSE)

# NA is converted to FALSE, `missing` argument has no impact
if_else(x %in% c(2), TRUE, FALSE, missing=NA)
```

**Comment by DavisVaughan** [comment]
The conversion of the `NA` to `FALSE` happens with `%in%`, and is unrelated to dplyr code

``` r
x <- c(NA, 1,2,3)

x %in% 2
#> [1] FALSE FALSE  TRUE FALSE
```

So there is nothing for dplyr to do here. Converting `NA` to `FALSE` is just a known side effect of how `%in%` and `match()` work.

**Comment by DavisVaughan** [comment]
If you really want `NA`s to pass through, you can use `vctrs::vec_in()` with `na_equal = TRUE`

``` r
vctrs::vec_in(c(NA, 1, 2, 3), 2, na_equal = FALSE)
#> [1]    NA FALSE  TRUE FALSE
```

But for the most part that is considered "advanced usage"

**Comment by Raesu** [comment]
Helpful, I did not know that. Thanks.
