### ISSUE TITLE
Add a Ranking Function to Compute Tail Means

### ISSUE THREAD

**Issue by walkerjameschris** [tidyverse/dplyr#7055]
I work on a data science research team that is interested in computing tail means. That is, the average of all values in a vector above some percentile. This is simple enough with base R or the `tidyverse`:

```r
x <- runif(1000)
weighted.mean(x, x > quantile(x, 0.95))
```

However, I was recently asked to perform this calculation for every value in the vector. We could expand this idea by iterating over all the elements in the vector. However, this is quite slow and not particularly efficient:

```r
x <- runif(1000)

purrr::map_dbl(x, function(i) {
  under <- x[x < i]
  weighted.mean(under, dplyr::cume_dist(under) >= 0.95)
}) 
```

So I developed an algorithm in C++ which does this rather efficiently and wondered if it would be of use for the `dplyr` family of ranking functions! You can see the R and C++ components here (of course leveraging Rcpp to compile). This munches through a vector of 1M elements or more in around a second or better on my x86 machine.

```r
cume_tail_mean <- function(x, tail = 0.95) {

  tibble::tibble(x) |>
    dplyr::mutate(
      id = dplyr::row_number()
    ) |>
    dplyr::arrange(x) |>
    dplyr::mutate(
      pcts = dplyr::cume_dist(x),
      x = cume_tail_mean_internal(x, pcts, tail)
    ) |>
    dplyr::arrange(id) |>
    dplyr::pull(x)
}
```

```cpp
NumericVector cume_tail_mean_internal(
  NumericVector x,
  NumericVector pcts,
  double tail
) {

  int n = x.length();
  double tail_min;
  double tail_max;
  double tail_sum;
  double n_tail = 1;
  int tail_bottom = 0;

  NumericVector tail_means(n);

  tail_sum = x[0];
  tail_means[0] = x[0];
    
  for (int i = 1; i < n; i++) {

    tail_max = pcts[i];
    tail_min = tail_max * tail;

    tail_sum += x[i];
    n_tail += 1;
  
    while (pcts[tail_bottom] < tail_min) {
      tail_sum -= x[tail_bottom];
      n_tail -= 1;
      tail_bottom += 1;
    }
  
    tail_means[i] = tail_sum / n_tail;
  }
    
  return tail_means;
}
```

I am new to contributing to FOSS so if this does not fit the spirit (or performance standards) of `dplyr` let me know! Primarily I made something cool and wanted to share. Thanks!

**Comment by DavisVaughan** [comment]
I think this is a neat function but maybe a little too niche for dplyr. You could consider putting it in your own package though! It seems cool!
