### ISSUE TITLE
Potential bug with `if_any()`- returns TRUE if no columns are selected

### ISSUE THREAD

**Issue by ks8997** [tidyverse/dplyr#7074]
The `if_any()` function returns TRUE if we pass an empty vector of columns. I think this behavior is unexpected and may introduce subtle bugs if your tidyselect function does not match any columns. I think it should possibly return an error.

```r
iris %>%
    mutate(z = if_any(c(), ~ . > 4000)) # returns all TRUE

iris %>%
    mutate(z = if_any(starts_with("XYZ"), ~ . > 4000)) # returns all TRUE
```

**Comment by DavisVaughan** [comment]
This was actually just fixed by https://github.com/tidyverse/dplyr/pull/7072

The correct behavior is actually to return all `FALSE` here, consistent with the base function `any()` when no inputs are provided. I don't think we want to error, we just want consistent and explainable behavior

**Comment by ks8997** [comment]
Thanks for explaining. But, I don't think this behavior is fixed. I updated to the latest version and using `if_any` in `mutate` with zero cols returns TRUE, although I think it works correctly inside `filter`. You can try the examples I posted above.
