### ISSUE TITLE
Problem with select() and filter() 

### ISSUE THREAD

**Issue by paschatz** [tidyverse/dplyr#7093]
Hey,

Sometimes I face problems with dplyr functions. Today I consistently get different errors when I use filter:
e.g:

```
test <- metadata %>%
+   filter(plot == "C1", year_n == 2020)
Error: object 'year_n' not found
```

year_n exists on my data and If I run the code with dplyr::filter() then runs smoothly. 
The same applies when I use the select()

```
species_sub <- species %>%
+   select(which(colSums(species) > 10))
Error: unable to find an inherited method for function ‘select’ for signature ‘x = "tbl_df"’
```
Again, once I use dplyr::select() the problem is resolved! 

I am using M1, R4.4.1, Rstudio 2024.09.0+375, tidyverse 2.0.0 (with dplyr 1.1.4).

I restarted Rstudio, deactivated all the packages and loaded only dplyr and the problem persisted. 

Thank you in advance, 
Paschalis

**Comment by DavisVaughan** [comment]
Are you sure you loaded dplyr? It looks like (possibly) `stats::filter()` and `MASS::select()` are running instead. 

Either:
- Something else is masking `filter` and `select`
- You don't actually have dplyr loaded

**Comment by paschatz** [comment]
I am using tidyverse but i tried only loading dplyr and the problem persisted. 

Apparently it was a dependancy issue with `automap`.
