### ISSUE TITLE
`rename` keeps the old column name

### ISSUE THREAD

**Issue by adupaix** [tidyverse/dplyr#7095]
The old column of a data frame is somehow "kept" after using the `rename` function. It happens only when the new name starts with the old name.

```r
df <- data.frame(a = 1:10)
df %>% dplyr::rename('a_a' = 'a') -> df
df$a_a
#  [1]  1  2  3  4  5  6  7  8  9 10
'a' %in% names(df)
# [1] FALSE
df$a
# [1]  1  2  3  4  5  6  7  8  9 10
```

**Comment by sda030** [comment]
This is not a bug, when you are using df$a, R uses partial matching to grab a_a.
``` r
tmp <- data.frame(a_a = 1:10)
tmp$a
#>  [1]  1  2  3  4  5  6  7  8  9 10
```

<sup>Created on 2024-10-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
