### ISSUE TITLE
everything is too long

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/dplyr#7097]
Could we have a synonym for `everything` that is shorter.   Maybe `tout` (everything in French)?

**Comment by DavisVaughan** [comment]
We don't currently feel that there is much to gain from adding a shorter equivalent, but thank you for the idea!

**Comment by ggrothendieck** [comment]
Shorter code can be easier to read and understand because there is less text to read, commands are more likely to not run off the end of the screen and commands can more likely fit on one line rather than several lines and if they take 2 lines instead of one then the entire piece of code may run off onto the next page so you can't get a birds eye view of it as easily.
