### ISSUE TITLE
Feature request: A function to check if a set of variables form a unique ID in a dataframe

### ISSUE THREAD

**Issue by bholtemeyer** [tidyverse/dplyr#7098]
I'd like to have a function to check if a set of variables form a unique ID in a dataframe, like this: https://search.r-project.org/CRAN/refmans/eeptools/html/isid.html

I think this would make code more readable as pipes would not need to be involved.

function would return TRUE or FALSE. TRUE indicates the variables uniquely identify the rows. FALSE indicates they do not.

**Comment by ggrothendieck** [comment]
If the reason to want this is is so that one can check prior to using `mutate(..., .by = ...)` to get the effect of `rowwise` then perhaps it would be better to support something like `.by = .ROWID` .

A one-liner that calculates `isid` would be:

```
isid <- function(data, ...) ! anyDuplicated(data[c(...)])

isid(anscombe) # TRUE
isid(anscombe, "x1", "x2") # TRUE
isid(anscombe, c("x1", "x2")) # TRUE
isid(anscombe, "x4") # FALSE
```
