### ISSUE TITLE
(em@directo!!) Assista a Usyk vs Fury 2 Transmissão ao vivo online gratis 21/12/2024

### ISSUE THREAD

**Issue by abhijeetsaha17** [tidyverse/dplyr#7340]
Os gigantes dos pesos pesados ​​Oleksandr Usyk e Tyson Fury se enfrentam pela segunda vez em 2024 no que promete ser outra batalha intrigante e explosiva, e com transmissão ao vivo no DAZN Pay-Per-View.

[DIRECTO >»> Usyk X Fury 2 AO VIVO](https://watchespnorg.blogspot.com/2024/09/boxing-2024.html)

[DIRECTO >»> Usyk X Fury 2 AO VIVO](https://watchespnorg.blogspot.com/2024/09/boxing-2024.html)

[DIRECTO >»> Usyk X Fury 2 AO VIVO](https://watchespnorg.blogspot.com/2024/09/boxing-2024.html)

Neste sábado (21 de dezembro) em Riad, Usyk defenderá seus cinturões WBO, WBC e WBA contra seu arquirrival Fury, depois que o ucraniano se tornou o primeiro campeão indiscutível dos pesos pesados ​​na era dos quatro cinturões após a vitória na primeira luta em maio.

No entanto, desde a vitória por decisão dividida, Usyk teve que deixar o título da IBF para o britânico Daniel Dubois, o que significa que se Fury vingar a derrota de maio, a primeira de sua carreira, ele ganhará os três cinturões, em vez de ser coroado campeão indiscutível.

Os dois têm grande respeito um pelo outro enquanto lutam novamente, sabendo que o vencedor pode ficar ao lado dos maiores boxeadores pesos pesados ​​de todos os tempos.

Fury foi o primeiro a subir na balança e nem tirou a jaqueta, muito menos as joias de ouro.

O homem de Morecambe pesa em 20º 1 libra ou 281 libras.

Fury pesava 18 libras quando os dois se conheceram em maio.

Há duas lutas de peso pesado, com o promissor Moses Itauma enfrentando o experiente Demsey McKean, enquanto Johnny Fisher e Dave Allen se encontram em uma batalha totalmente britânica.

O ex-campeão dos médios leves da WBA Israil Madrimov enfrenta Serhii Bohachuk, e o campeão europeu dos super galos Dennis McCann defenderá seu título contra Peter McGrail.

Isaac Lowe abrirá o card em uma luta de peso pena contra o escocês Lee McGregor, que venceu suas duas últimas lutas por nocaute.

Oleksandr Usyk vs. Tyson Fury; Pelos títulos WBA, WBC e WBO de Usyk
Serhii Bohachuk vs. Ishmael Davis; Peso médio-leve
Moses Itauma vs. Demsey McKean; Peso pesado
Johnny Fisher vs. Dave Allen; Peso pesado
Peter McGrail v Rhys Edwards; Peso superpluma
Isaac Lowe vs. Lee McGregor; Peso pena
Daniel Lapin vs Dylan Colin; Peso meio-pesado
Andrii Novytskyi vs Edgar Ramirez; Peso pesado
Usyk x Fury 2: O que aconteceu na primeira luta
A primeira luta em duas décadas coroaria o campeão mundial indiscutível dos pesos pesados ​​deixou todo mundo na expectativa e não decepcionou.

Oleksandr Usyk e Tyson Fury mostraram toda a qualidade como talentos geracionais, entregando uma batalha intrigante e envolvente, que fluía e refluía, com ambos se revezando no comando do combate, e a luta indo até o fim.

O "Gypsy King" foi derrubado por Usyk no nono round. Enquanto Fury tentava se recuperar nos rounds seguintes, este momento foi crucial na disputa, com o ucraniano conquistando a vitória por pontos, com uma decisão dividida.

Luta de MMA tem Oleksandr Usyk vs. Tyson Fury 2 atualiza rodada por rodada ao vivo para uma das lutas de boxe mais esperadas do ano na Kingdom Arena em Riyadh, Arábia Saudita, na tarde de sábado.

O evento principal está previsto para começar por volta das 18h ET no DAZN. Confira nosso Usyk vs. Página de resultados do Fury 2 para descobrir o que aconteceu na eliminatória.

Oleksandr Usyk (22-0) é o medalhista de ouro olímpico de 2012 no boxe. Ele se profissionalizou em 2013 e tem sido dominante desde então, tornando-se o primeiro (e até agora o único) campeão indiscutível dos pesos-cruzados na era dos quatro cinturões. Mais recentemente, Usyk derrotou Tyson Fury por decisão dividida para se tornar o campeão indiscutível dos pesos pesados ​​em maio passado, mas desocupou o campeonato dos pesos pesados ​​​​da IBF em junho.

**Comment by abhijeetsaha17** [comment]
No entanto, desde a vitória por decisão dividida, Usyk teve que deixar o título da IBF para o britânico Daniel Dubois, o que significa que se Fury vingar a derrota de maio, a primeira de sua carreira, ele ganhará os três cinturões, em vez de ser coroado campeão indiscutível.

**Comment by gbloodcaitl** [comment]
hjy

### **👉⏩🎥🅻🅸🆅🅴🔴▶️ ✅🟢 [**STREAM PLAY NOW** ▶️](https://www.onflix.online/boxing)**
.
### **👉⏩🎥🆆🅰🆃🅲🅷🔴▶️ ✅🟢 [**PLAY NOW ONLINE**](https://www.onflix.online/boxing)**
.

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://www.onflix.online/boxing)
.
.

[![werx](https://github.com/user-attachments/assets/1b1dd544-6865-4e28-8e2f-2f2b3a5cb216)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)

ngft
