### ISSUE TITLE
(PPV/STREAMS)**Tyson Fury vs Oleksandr Usyk 2 LIVE PPV Fight On 21 Dec 2024

### ISSUE THREAD

**Issue by jenuferLopez** [tidyverse/dplyr#7341]
The Oleksandr Usyk vs. Tyson Fury full fight video showcases the instant classic between Oleksander Usyk and Tyson Fury this past May.

On May 18, 2024, Usyk and Fury went the full 12 rounds in their first meeting and needed the judges to determine the winner that night at Freedom Arena in Riyadh, Saudi Arabia.

The judges scored the fight 115–112, 114–113, 113–114 to Usyk and allowed him to become the latest undisputed heavyweight champion. It was also the first career loss to Fury.

Uysk (22-0) has since vacated the IBF heavyweight title before their upcoming rematch so the WBA, WBC and WBO heavyweight titles will be on the line Saturday afternoon again. The IBF organization wanted Usyk to face Daniel Dubois. This clash also takes place at Freedom Arena in Riyadh, Saudi Arabia.

Usyk vs. Fury 2 airs on DAZN pay-per-view, and the price is $39.99 in the United States. The following eight fights will be on the undercard Saturday:

Moses Itauma vs. Demsey McKean; Heavyweight- 10 rounds

Johnny Fisher vs. Dave Allen; Heavyweight - 10 rounds

Peter McGrail v Rhys Edwards; Super featherweight - 10 rounds

Isaac Lowe vs. Lee McGregor; Featherweight - 10 rounds

Daniel Lapin vs Dylan Colin; Light-heavyweight - 10 rounds

Andrii Novytskyi vs Edgar Ramirez; Heavyweight - 10 rounds

Mohammad Alakel vs. Joshua Ocampo, junior lightweights - 6 rounds

 Watch ex-UFC heavyweight Robelis Despaigne deliver historic 4-second knockout at Karate Combat 51
Usyk vs. Fury 2 weigh-in results: Tyson Fury has massive weight edge over Oleksandr Usyk
Oleksandr Usyk vs. Tyson Fury 2: Live round-by-round updates
Missed Fists: Bout cancelled after fighter rushes opponent during introductions
Conor McGregor scoffs at Ilia Topuria’s plans to move up in weight: ‘He has the balls of a kitten’
Usyk vs. Fury 2 Results: Live updates of the undercard and main event

**Comment by gbloodcaitl** [comment]
hjy

### **👉⏩🎥🅻🅸🆅🅴🔴▶️ ✅🟢 [**STREAM PLAY NOW** ▶️](https://www.onflix.online/boxing)**
.
### **👉⏩🎥🆆🅰🆃🅲🅷🔴▶️ ✅🟢 [**PLAY NOW ONLINE**](https://www.onflix.online/boxing)**
.

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://www.onflix.online/boxing)
.
.

[![werx](https://github.com/user-attachments/assets/1b1dd544-6865-4e28-8e2f-2f2b3a5cb216)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)

ngft
