### ISSUE TITLE
left_join silently kills RStudio when value in by= not present in either data frame

### ISSUE THREAD

**Issue by andrewcstewart** [tidyverse/dplyr#738]

**Comment by bartbisschops** [comment]
I had the same problem after updating to the latest version of dplyr.

Use of  any join function would either give the error:

Error in withCallingHandlers(tryCatch(evalq((function (..., call. = TRUE, : object '.rcpp_warning_recorder' not found

or completely crash rstudio

after running install.packages('Rcpp') dplyr couldnt find the Rcpp package anymore. install.packages('dplyr') then fixed the problem
