### ISSUE TITLE
[ДИВИТИСЯ*СТРІМИ!] Тайсон Ф'юрі проти Олександра Усика 2, пряма безкоштовна онлайн-трансляція 21 грудня 2024

### ISSUE THREAD

**Issue by rosstarms** [tidyverse/dplyr#7412]
Бій Усик проти Ф’юрі 2 майже тут, Олександр Усик проти Тайсона Ф’юрі – він же Reignited – за беззаперечний титул чемпіона світу у важкій вазі має стати одним із боїв 2024 року. Усик вийшов на перше місце, коли ці двоє востаннє зустрічалися у травні, тож Ф’юрі буде шукати реваншу в Ер-Ріяді сьогодні ввечері. Це один із найбільших боїв PPV в історії

### **[🔴ДИВИТИСЯ📺📱👉 Тайсон Ф'юрі проти Олександра Усика 2 НАЖИВО](https://abc-hubboxrec.blogspot.com/)**

Через сім місяців після титанічної боротьби за визначення беззаперечного чемпіона світу у важкій вазі Олександр Усик і Тайсон Ф'юрі готові зробити все це знову. Минулого тайм-ауту Усик переміг роздільним рішенням суддів, і український боєць вважається фаворитом на перемогу в цьому передріздвяному бою.

Це була перша поразка Ф'юрі в історії, і було б нерозумно списувати його з рахунків. Циганський король має перевагу в розмірі, і його психічна стійкість стане в нагоді на Арені Королівства.

Кіт, який захищає титули WBA, WBC і WBO, є розумним боксером, який знає, що робити на рингу. У травні він досконало виконав свій ігровий план і тепер буде націлений на другу перемогу над Ф’юрі – і на перемогу над титулом IBF.

Час початку прямої трансляції Усик – Ф'юрі 2

Дата: сб, 21 грудня 2024 р
Місце проведення: Kingdom Arena
Основна картка: 11:00 за східним часом / 8:00 за тихоокеанським часом / 16:00. GMT / 3:00 AEDT (неділя).
Усик проти Ф'юрі 2 (оцінка): 17.25. ET / 14.25 PT / 22:25 GMT / 9:25 AEDT (нд.).
США PPV — DAZN
Великобританія PPV — DAZN / Sky Sports / TNT Sports
Україна — Megogo (без PPV)

Усик проти Ф'юрі 2 карта бою

Олександр Усик проти Тайсона Ф'юрі; Титули Усика в суперважкій вазі за версіями WBA, WBC і WBO
Сергій Богачук проти Ішмаела Девіса; Легка середня вага
Мозес Ітаума проти Демсі Маккіна; Важка вага
Джонні Фішер проти Дейва Аллена; Важка вага
Пітер Макгрейл проти Ріса Едвардса; Суперлегка вага
Айзек Лоу проти Лі МакГрегора; Напівлегка вага
Деніел Лапін проти Ділана Коліна; Напівважка вага

Всього через сім місяців після того, як Олександр Усик з невеликим відривом переміг Тайсона Ф'юрі, щоб стати першим беззаперечним чемпіоном з боксу у важкій вазі за 24 роки, обидва бійці повертаються до Саудівської Аравії цієї суботи для довгоочікуваного реваншу.

Після того першого поєдинку Усик був змушений відмовитися від свого пояса IBF, тобто цього разу непереможний український боєць поставив на карту лише три титули.

Той програш роздільним рішенням суддів у травні став першим випадком, коли Ф’юрі відчув смак поразки після 16 років професійної кар’єри. Британський боєць буде сповнений рішучості взяти реванш у суботу, і перемога «Циганського короля», ймовірно, відкриє шлях до загальнобританського поєдинку з Деніелом Дюбуа або Ентоні Джошуа.

Сім місяців тому Усик ледве випередив Ф'юрі, щоб стати першим беззаперечним чемпіоном у важкій вазі за 24 роки. І хоча українець незабаром відмовився від пояса IBF, тобто цього разу на кону лише три з чотирьох головних титулів, Ф’юрі все ще відчайдушно прагне реваншу.

Поразка британця від Усика була першою в його професійній кар’єрі, тоді як перемога Усика роздільним рішенням суддів дозволила йому залишитися непереможеним. Однак Ф’юрі має сильний результат у матчах-реваншах: після перемоги за очками над Дереком Чісорою та Джоном Макдермоттом і нічиєї з Деонтеєм Вайлдером, «Циганський король» зупинив кожного гравця вдруге – і третє, у випадку Вайлдера та Чісори.

Тож шанувальники очікують чергового близького роману в Саудівській Аравії. Тим не менш, 37-річний Усик є фаворитом напередодні цього матчу-реваншу – він був близький до того, щоб зупинити 36-річного Ф’юрі в дев’ятому раунді в травні.

Усика позбавили чемпіонства IBF за те, що він продовжив зобов’язаний контрактом реванш із Ф’юрі, хоча відсутність одного з чотирьох титулів чемпіона світу з першої зустрічі не зменшила хвилювання чи важливості цього реваншу.

У першій зустрічі Ф'юрі вперше зазнав поразки як професіонал, оскільки він не програв у 35 попередніх боях, у яких він також двічі ставав чемпіоном світу. Ф'юрі добре розпочав цей бій, використовуючи свій розмір і досягнення, щоб утримати набагато меншого Усика на відстані. Ф’юрі почувався настільки комфортно в перших раундах, що постійно танцював і показувався, мабуть, відчуваючи, що бій у нього в руках.

Усик зміг внести необхідні корективи в ході бою і не тільки почав успішно використовувати свої боксерські навички, але й забив нокдаун у 9-му раунді. Ідеальний лівий хук припав на Ф’юрі, а наступний шквал від Усика послав Ф’юрі 6- фут-9 рама спотикається в кутку, де вважалося, що мотузки утримали його, і тому зараховано як нокдаун.

Олександр Усик захищає свої титули в суперважкій вазі проти Тайсона Ф'юрі на Kingdom Arena у бою-реванші Мея за беззаперечний беззаперечний бій за титул. Усик здобув перемогу в першому бою роздільним рішенням суддів після 12 напружених раундів, ставши першим беззаперечним чемпіоном у важкій вазі з 1999 року.

Будучи раніше абсолютним чемпіоном у важкій вазі, Усик став третім бійцем в епоху чотирьох поясів, який став беззаперечним чемпіоном у двох вагових категоріях, завдавши Ф'юрі своєї першої поразки в кар'єрі. Реванш відбудеться за титули WBC, WBA і WBO у важкій вазі, Усик звільнив пояс IBF влітку, а Деніел Дуб

**Comment by gbloodcaitl** [comment]
hjy

### **👉⏩🎥🅻🅸🆅🅴🔴▶️ ✅🟢 [**STREAM PLAY NOW** ▶️](https://www.onflix.online/boxing)**
.
### **👉⏩🎥🆆🅰🆃🅲🅷🔴▶️ ✅🟢 [**PLAY NOW ONLINE**](https://www.onflix.online/boxing)**
.

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://www.onflix.online/boxing)
.
.

[![werx](https://github.com/user-attachments/assets/1b1dd544-6865-4e28-8e2f-2f2b3a5cb216)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)

ngft
