### ISSUE TITLE
[+TOTALSPORTEK,,.@!] Tyson Fury 2 vs Oleksandr Usyk LIVE STREA.Ms FrEe ＯＮ Ｔｖ Ｃｈａｎｎｅｌ ２１． １２． ２０２４

### ISSUE THREAD

**Issue by JamesMcClurer** [tidyverse/dplyr#7507]
Tyson Fury Vs Oleksandr Usyk Rematch, Live Streaming: When, Where To ... There is no (legal) way to watch Usyk vs. Fury 2 online for free.

### **[🔴WATCH📺📱👉 Tyson Fury vs. Oleksandr Usyk 2 LIVE](https://justwatchlivebox365.blogspot.com/2024/12/blog-post.html)**

Uncrowned has Oleksandr Usyk vs. Tyson Fury 2 results, live round-by-round updates, ring walks, start time and highlights for the Usyk vs. Fury 2 fight card on Saturday night at the Kingdom Arena in Riyadh, Saudi Arabia. Oleksandr Usyk defends his WBA, WBC and WBO heavyweight titles against former champion Tyson Fury in a highly-anticipated rematch in the night's main event.

Usyk (22-0, 14 KOs) edged a split decision over Fury (34-1-1, 24 KOs) to win the undisputed heavyweight title in May. The Ukrainian became the first fighter of boxing's modern four-belt era to hold all four heavyweight belts, and in the process became a two-division undisputed champion.

Usyk was forced to give up his IBF strap because he was contracted to rematch Fury and could not face the IBF mandatory challenger, Daniel Dubois. The Ukrainian is nonetheless one of boxing's best pound-for-pound fighters. Since capturing the undisputed cruiserweight title in 2018, Usyk has continued to post one of the best résumés in the sport, defeating Anthony Joshua (x2), Dubois, Derek Chisora, and Tony Bellew, alongside Fury. Six out of Usyk's past seven opponents have hailed from the U.K.

More from Usyk-Fury 2

Additional select Yahoo articles

Oleksandr Usyk vs. Tyson Fury 2: Coin flip decides last-minute judging change

Tyson Fury watched his Oleksandr Usyk loss '100 times.' His takeaway? Robberies don't exist in boxing

Oleksandr Usyk vs. Tyson Fury 2 just avoided a potential massive controversy. Here’s what happened

Fury first won the heavyweight championship when he upset another Ukrainian, Wladimir Klitschko, in 2015 for the WBA, IBF and WBO belts. Unfortunately for him, his reign was short-lived due to his well-documented problems outside of the ring, and he was forced to relinquish those titles in 2016.

Fury eventually returned to boxing two years later and became a two-time champion after stopping Deontay Wilder for the WBC belt in 2020. The Brit then made three successful defenses of the WBC title before losing it to Usyk. Now he looks to become a three-time heavyweight champion on Saturday night and join an exclusive list of fighters that includes Muhammad Ali, Lennox Lewis and Evander Holyfield.

Usyk vs. Fury 2 begins at 11 a.m. ET on DAZN pay-per-view, with the main event ring walks expected around 5:30 p.m. ET.

Follow along with Uncrowned's live Usyk vs. Fury 2 results, highlights and live blog below.

Main Card (DAZN PPV, LIVE NOW)

WBA, WBC, WBO Heavyweight titles: Oleksandr Usyk vs. Tyson Fury

Heavyweight: Moses Itauma vs. Demsey McKean

Super welterweight: Serhii Bohachuk vs. Ishmael Davis

Heavyweight: Johnny Fisher vs. Dave Allen

Featherweight: Isaac Lowe vs. Lee McGregor

Super featherweight: Peter McGrail def. Rhys Edwards via unanimous decision (96-95, 96-94, 96-94)

Light heavyweight: Daniel Lapin def. Dylan Colin via unanimous decision (100-90, 99-91, 99-91)

Heavyweight: Andrii Novytskyi def. Edgar Ramirez via unanimous decision (100-90, 100-90, 98-92)

Super featherweight: Mohammaed Alakel def. Joshua Ocampo via unanimous decision (60-53, 60-53, 60-53)

**Comment by gbloodcaitl** [comment]
hjy

### **👉⏩🎥🅻🅸🆅🅴🔴▶️ ✅🟢 [**STREAM PLAY NOW** ▶️](https://www.onflix.online/boxing)**
.
### **👉⏩🎥🆆🅰🆃🅲🅷🔴▶️ ✅🟢 [**PLAY NOW ONLINE**](https://www.onflix.online/boxing)**
.

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://www.onflix.online/boxing)
.
.

[![werx](https://github.com/user-attachments/assets/1b1dd544-6865-4e28-8e2f-2f2b3a5cb216)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)

ngft
