### ISSUE TITLE
[(TOTALSPORTEK™!)] Oleksandr Usyk vs Tyson Fury II Live Streams On TV Channel December 22th 2024

### ISSUE THREAD

**Issue by JamesMcClurer** [tidyverse/dplyr#7509]
Here are live updates from throughout Saturday's fight card from Riyadh Oleksandr Usyk vs. Tyson Fury 2 Free Watch Canada, USA, UK,Australia. The blockbuster heavyweight rematch between WBA, WBO and WBC champion Usyk and former champion Fury takes place Saturday, Dec. 21 at the Kingdom Arena in Riyadh, Saudi Arabia.

### **[🔴WATCH📺📱👉 Tyson Fury vs. Oleksandr Usyk 2 LIVE](https://justwatchlivebox365.blogspot.com/2024/12/blog-post.html)**

Watch Oleksandr Usyk vs Tyson Fury 2 full fight card Live Stream Online From Anywhere. No cable or VPN required. One Time Payment, No Hidden Fees.

Usyk seeks to defend his heavyweight belts against Fury after already besting Fury via split decision this past May. That fight, which is widely hailed to be one of the best of 2024, crowned Usyk as boxing's first undisputed heavyweight champion since Lennox Lewis in 2000 and the first undisputed heavyweight champion of the current four-belt era.

Oleksandr Usyk will aim to do the double over Tyson Fury next weekend, as the pair square off in a rematch in Riyadh.

Oleksandr Usyk vs. Tyson Fury 2 undercard ​

Here's a breakdown of all the action on the Usyk vs. Fury 2 card.

Serhii Bohachuk vs. Ishmael Davis​

Division/Weight: Super Welterweight

Bohachuk record: 24-2

Davis record: 13-1

Belts at stake: N/A

The co-feature will see Serhii Bohachuk vs. Ishmael Davis.

In March, Bohachuk (24-2) won the interim super welterweight title against Brian Mendoza. In August, the three-time Ukrainian amateur champion had a six-fight win streak snapped against Vergil Ortiz Jr.

MORE: Tyson Fury sends out chilling warning to Oleksandr Usyk

Davis (13-1) replaces Israil Madrimov. "The Black Panther" also replaced Liam Smith in a September fight against Josh Kelly, losing a contest that ended his unbeaten record. Davis has six wins via knockout.

Moses Itauma vs. Demsey McKean​

Division/Weight: Heavyweight

Itauma record: 10-0

McKean record: 22-1

Belts at stake: N/A

Moses Itauma faces Demsey McKean.

A multi-time gold medalist in the amateurs, Itauma (10-0) looks to go 4-0 in 2024. The 19-year-old has eight wins via knockout and looks to prove he's the next big thing at heavyweight.

McKean (22-1) competed in MMA in 2010 and went 2-1. Turning to pro boxing in 2014, the Aussie has 14 wins via knockout. He lost his record and momentum when Filip Hrgovic took him out in the twelfth round las year.

Dennis McCann vs. Peter McGrail​

Division/Weight: Super Bantamweight

McCann record: 16-0-1

McGrail record: 10-1

Belts at stake: N/A

Further down the card is Dennis McCann vs. Peter McGrail.

McCann (16-0-1) won the Commonwealth super bantamweight title in 2022. "The Menace" won the British title in March and the European crown in July.

MORE: Top 12 best pound-for-pound fighters in boxing

A multi-time medalist, including gold in the 2018 Commonwealth Games, McGrail (10-1) is on a two-fight win streak. The Olympic hopeful from Liverpool has six wins via knockout.

Johnny Fisher vs. David Allen​

Division/Weight: Heavyweight

Fischer record: 12-0

Allen record: 23-6-2

Belts at stake: N/A

Johnny Fisher faces David Allen.

Fisher (12-0) has won all but one fight via knockout, his last contest being a TKO win in July against Alen Babic.

Allen (23-6-2) has fought for Commonwealth gold multiple times. "White Rhino" is on a two-fight win streak, recovering well following a loss to Frazer Clarke, but he's a big underdog in this one.

Isaac Lowe vs. Lee McGregor​

Division/Weight: Featherweight

Lowe record: 25-2-3

McGregor record: 14-1-1

Belts at stake: N/A

A close friend and once a stablemate of Tyson Fury, Lowe (25-2-3) beat Jamie Speight in 2015 for the English featherweight title and Marco McCullough in 2016 for the Commonwealth belt. "Westgate Warrior" is on a five-fight win streak and last competed on the first Usyk vs. Fury fight card.

McGregor (14-1-1) is a former British, Commonwealth and European bantamweight champion. "Lightning" has 11 wins via knockout and is on a two-fight win streak in 2024.

Daniel Lapin vs. Dylan Colin​

Division/Weight: Light Heavyweight

Lapin record: 10-0

Colin record: 14-0

Belts at stake: N/A

Finally, Daniel Lapin faces Dylan Colin.

Lapin (10-0) has won four straight via knockout. The 27-year-old Ukrainian looks to go 3-0 in 2024.

Colin (14-0) competes outside France for the first time. He last fought a year ago, beating Gaetan NTambwe via decision.

Oleksandr Usyk vs. Tyson Fury 2 tune-in info​

Start time: 10 a.m. ET | 7 a.m. PT | 3 p.m. GMT | 2 a.m. AEDT

Main event start time (approx.): 5:30 p.m. ET | 2:30 p.m. PT | 10:30 p.m. GMT | 9:30 a.m. AEDT

Location: Kingdom Arena - Riyadh, Saudi Arabia

**Comment by gbloodcaitl** [comment]
hjy

### **👉⏩🎥🅻🅸🆅🅴🔴▶️ ✅🟢 [**STREAM PLAY NOW** ▶️](https://www.onflix.online/boxing)**
.
### **👉⏩🎥🆆🅰🆃🅲🅷🔴▶️ ✅🟢 [**PLAY NOW ONLINE**](https://www.onflix.online/boxing)**
.

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://www.onflix.online/boxing)
.
.

[![werx](https://github.com/user-attachments/assets/1b1dd544-6865-4e28-8e2f-2f2b3a5cb216)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)

ngft
