### ISSUE TITLE
𝐋𝐈𝐕𝐄𝐒𝐓𝐑𝐄𝐀𝐌*! 𝐖𝐀𝐓𝐂𝐇 𝘖𝘭𝘦𝘬𝘴𝘢𝘯𝘥𝘳 𝘜𝘴𝘺𝘬 𝘷𝘴 𝘛𝘺𝘴𝘰𝘯 𝘍𝘶𝘳𝘺 2 𝘓𝘪𝘝𝘦 𝐒𝐭𝐫𝐞𝐚𝐦𝐬 𝘍𝘳𝘌𝘦 𝘉𝘳𝘖𝘢𝘋𝘤𝘈𝘴𝘛 𝘰𝘕 𝘛𝘝 𝘎𝘶𝘪𝘥𝘦 & 𝐒𝐭𝐫𝐞𝐚𝐦𝐢𝐧𝐠 21 𝘋𝘦𝘤𝘦𝘮𝘣𝘦𝘳 2024

### ISSUE THREAD

**Issue by jgonza-2002** [tidyverse/dplyr#7514]
Researchers are expecting millions of people to seek out free live streams of the heavyweight boxing fight between Oleksandr Usyk and Tyson Fury on Saturday, putting them at risk to fraud and other cyber security

[🔴WATCH📺📱👉 Tyson Fury vs. Oleksandr Usyk 2 LIVE](https://fury-vs-usyk-2-tv.blogspot.com/)

[🔴WATCH📺📱👉 Tyson Fury vs. Oleksandr Usyk 2 LIVE](https://fury-vs-usyk-2-tv.blogspot.com/)

[🔴WATCH📺📱👉 Tyson Fury vs. Oleksandr Usyk 2 LIVE](https://fury-vs-usyk-2-tv.blogspot.com/)

The first Fury vs Usyk bout sold over 1.5 million pay-per-views, however the £25 ($40) PPV fee saw many more turn to illegal live streams to watch the fight for free.

Links to free streams also spread across popular social media sites like Facebook and X, while users of certain Reddit forums also shared the best ways to reach illegal streaming sites.

The rematch between Fury and Usyk is expected to attract a similar level of piracy, with DAZN, TNT Sports Box Office and Sky Sports Box Office charging the same £25 PPV fee.

Oleksandr Usyk (left) and Tyson Fury (right) at the weigh-in (Nick Potts/PA)
open image in gallery
Oleksandr Usyk (left) and Tyson Fury (right) at the weigh-in (Nick Potts/PA) (PA Wire)
Experts have warned of the risks involved for people seeking free streams for the Usyk vs Fury fight, both legally and in terms of cyber security.

“Choosing to bypass official channels to watch the highly anticipated Fury vs. Usyk fight this Saturday isn’t just risky –it’s illegal and can expose you to serious dangers,” Kieron Sharp, chief executive of FACT, told The Independent.

“Illegal streaming puts consumers at risk of malware, financial theft, and the compromise of personal data, such as emails, photos, and browsing history. During events of high viewership, fraudsters are targeting unsuspecting viewers.”

The BeStreamWise anti-piracy campaign issued an alert in the build up to the Fury vs Usyk 2 fight, claiming that one in three viewers in the UK who stream illegally have been victims of fraud, scams and identity theft.

Free live streams of Tyson Fury’s heavyweight title defence will spread across the internet in the build up to the fight
open image in gallery
Free live streams of Tyson Fury’s heavyweight title defence will spread across the internet in the build up to the fight (Screengrab)
A separate report from pub loyalty app MiXR claimed that 63 per cent of boxing fans have missed a knockout punch due to buffering and lagging issues that are prevalent with illegal streams.

Research carried out by the app found that the majority of people searching for illegal streams of popular fights did so due to the high PPV costs.

“Not only can illegal streaming ruin the experience of watching live boxing, but it also directly impacts pubs across the country,” a spokesperson for MiXR told The Independent.

“If this trend were repeated for Saturday’s rematch, with people opting to illegally stream instead of watching in pubs and bars, MiXR estimates that the UK pub industry could lose £16 million in revenue.”

fds
fd
fd
fd

fg
gf
gf

**Comment by gbloodcaitl** [comment]
dfe
