### ISSUE TITLE
[TOTALSPORTEK] Tyson Fury 2 vs Oleksandr Usyk LIVE STREA.Ms Ｆｒｅｅ ＯＮ Ｔｖ Ｃｈａｎｎｅｌ ２１． １２． ２０２４

### ISSUE THREAD

**Issue by ITechCarlo** [tidyverse/dplyr#7517]
When the main event begins around 6 p.m. ET, check out our Usyk vs. Fury 2 live round-by-round updates for our live blog of the main event.

**[➤►🌍📺📱👉LINK 🔴✅👉CLICK HERE TO WATCH LIVE NOW](https://tvaccess.live/usyk-vs-fury-2-live/?v=GIT)**

**[➤►🌍📺📱👉LINK 🔴✅👉CLICK HERE TO WATCH LIVE NOW](https://tvaccess.live/usyk-vs-fury-2-live/?v=GIT)**

[![](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiYkNfNDMEr-A58FVUGSJsXMpQkmUT2DPjUGgCXdTwqqRsQU38gtPSs9a_IopMbMADoo5VEO8ALsuHnJ33i6kXZASL_wge1Frjuh7aUaJe-ZkkfdCB1IacjZgWGSEefsmBVq3oOADwkPOft6Ai7JDuDXTge1wuwgPatffhJ6OpnpMv_SULOgIjGmwRThw/w473-h266/boxing%20main.gif)](https://tvaccess.live/usyk-vs-fury-2-live/?v=GIT)

In May, Oleksandr Usyk completed his mission, defeating Tyson Fury by split decision to become the first undisputed heavyweight champion of the modern four-belt era. On Saturday in Saudi Arabia, Usyk will look for a repeat performance when he rematches Fury, this time with three world titles on the line.

Usyk was stripped of the IBF championship for moving ahead with his contractually obligated rematch with Fury, though the lack of one of the four world titles from the first meeting has done nothing to diminish the excitement or importance of this rematch.

The first meeting was the first time Fury had suffered defeat as a professional, having gone undefeated across 35 previous bouts that also saw him twice reign as world champion. Fury started that fight well, using his size and reach to keep the much smaller Usyk at range. Fury was so comfortable in the early rounds that he repeatedly danced and showboated, seemingly feeling he had the fight in hand.

Usyk was able to make the necessary adjustments as the fight wore on and not only started to successfully use his boxing skills, but also scored a knockdown in Round 9. A perfect left hook landed on Fury and the following flurry from Usyk sent Fury's 6-foot-9 frame stumbling into the corner where it was ruled the ropes had held him up and thus counted as a knockdown.

That knockdown was the difference between a split decision win for Usyk and a split draw, with one judge scoring the fight 114-113 Fury and two turning in Usyk scores of 115-112 and 114-113. Without the knockdown making for a 10-8 Usyk ninth round, that third card would have been 114-114.

"I've got nothing to say apart from there's going to be a whole lot of hurt and pain in this fight, you watch," Fury said. "The talking's been done. The first fight, I talked, I joked, all my career. This time I'm serious, I'm going to do some damage here on Saturday night. Watch me go to work."

Usyk's win ran his career record to 22-0. More impressive than his spotless record, Usyk has managed to go undisputed at two different weight classes.

"Now we just have the performance. Talks, cameras, lights, kind of show. Everything is going to be taking place Saturday night on the 21st," Usyk said at the final press conference. "Don't be afraid. I will not leave you alone. See you on Saturday."

Usyk ran through the cruiserweight division before winning the World Boxing Super Series in 2018 to unify all four world titles at 200 pounds. In October 2019, Usyk made the move to heavyweight with a win over Chazz Witherspoon. Two fights later, he'd defeated Anthony Joshua to capture the IBF, WBO and WBA heavyweight titles.

"Regarding the main event, I've got a lot of history with Oleksandr Usyk, but I am backing Tyson Fury. Of course, he's the Brit. People ask me all the time, "who's going to win this fight?" and I've said this: Oleksandr Usyk is an incredible fighter and it will take something extraordinary to beat him on Saturday night. But, and I know we've had our differences, Tyson Fury is capable of extraordinary things," Matchroom Boxing CEO Eddie Hearn said. 

"His victory against Wladimir Klitschko in Germany, I watched that on a laptop in a hotel in America, I thought he had absolutely no chance. He won every single round. When he fought Deontay Wilder in America, I thought he had absolutely no chance. He was robbed in the first fight, he smashed him to pieces in the second fight. Two generational great heavyweights, two credits to the sport. May God bless you both on Saturday night, but most of all, I can't believe I'm saying it, may Tyson Fury be victorious on Saturday night for Britain and get the championship back."

Now the two meet again with legacy on the line. Can Fury make the necessary adjustments to maintain his early momentum from the first fight or will Usyk again conquer the giant and prove his place atop the heavyweight division?

The undercard was set to feature a solid matchup between Serhii Bohachuk and Israil Madrimov at junior middleweight. Unfortunately, Madrimov was forced to withdraw from the bout after suffering from bronchitis during training camp. His next appearance is expected to be on the Feb. 22 card featuring Artur Beterbev vs. Dmitry Bivol 2 in the main event where he will face another top contender in Vergil Ortiz. Instead, Bohachuk will take on Ismael Davis. 

Elsewhere on the card, more heavyweights give support to the main event. Rising teenage phenom Moses Itauma is back in action when he takes on veteran Demsey McKean. The 19-year-old has thrilled in his early career, scoring eight knockouts in 10 professional fights. His last was most impressive when he stopped veteran Mariusz Wach in the second round in July. He gets a durable veteran in McKean, who is coming off the first defeat of his pro career when he was stopped by Filip Hrgovic in August.

Let's take a closer look at the rest of the undercard before getting to a prediction and expert pick on the main event.

Usyk vs. Fury 2 fight card, odds
Oleksandr Usyk (c) -140 vs. Tyson Fury +110, unified heavyweight titles
Serhii Bohachuk -950 vs. Ismael Davis +600, junior middleweight
Moses Itauma -1400 vs. Demsey McKean +750, heavyweights
Johnny Fisher -1400 vs. Dave Allen +700, heavyweights
Peter McGrail -450 vs. Rhys Edwards +320, junior featherweights
Lee McGregor -190 vs. Isaac Lowe +150, featherweights
Where to watch Usyk vs. Fury 2
Date: Dec. 21
Location: Kingdom Arena -- Riyadh, Saudi Arabia
Start time: 10 a.m. ET  (main event ring walks around 5 p.m. ET)
How to watch: DAZN PPV (Price: $39.99)
Prediction
The image of Fury reeling along the ropes as Usyk was on the verge of scoring a stoppage is hard to shake from one's mind. Usyk was so good over the second half of the fight that it erased what was a tremendous early showing from Fury. What Fury needs to manage is to build that momentum without letting Usyk ever get comfortable. The biggest question heading into Saturday is whether Fury has developed a gameplan that can throw Usyk off, since Usyk figured out Fury midway through the first fight and never looked back.
Oleksandr Usyk and Tyson Fury step into the ring together again on 21 December in Saudi Arabia.

The rival heavyweights collided six months ago in Riyadh, with Usyk narrowly beating Fury via split decision.

It was a historic night with Usyk becoming the modern era's first four-belt heavyweight champion and they will do it all again in an early Christmas present for sports fans.

Live text and radio commentary will start at 20:00 GMT on fight night on the BBC Sport website and app.

Can Fury avenge his only loss or will Usyk's incredible, unblemished career continue?

Everything you need to know about the WBA, WBO and WBC heavyweight world title fight is below.

When is Usyk v Fury 2 and what are the UK times?
Ringwalk timings in Saudi have been a bit hit and miss in the past 12 months. Some fights have begun well after midnight while others have started closer to 22:00.

Organisers in Riyadh this time are aiming for the earlier end of that spectrum.

The first fight is set to start at 16:00 GMT.

Usyk and Fury's ringwalks are targeted for 22:15, meaning the fight will probably start around 22:30.

How to follow Usyk v Fury 2 on the BBC?
Fury's rematch with Usyk will be broadcast live on BBC Radio 5 Live from 21:00 GMT on Saturday, 21 December on the BBC Sport website and app.

BBC Sport will bring you daily coverage from Riyadh in fight week and Steve Bunce will deliver daily episodes of his 5 Live Boxing with Steve Bunce podcast.

You can follow live text commentary of the undercard and all the build-up from 20:00.

[![](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiYkNfNDMEr-A58FVUGSJsXMpQkmUT2DPjUGgCXdTwqqRsQU38gtPSs9a_IopMbMADoo5VEO8ALsuHnJ33i6kXZASL_wge1Frjuh7aUaJe-ZkkfdCB1IacjZgWGSEefsmBVq3oOADwkPOft6Ai7JDuDXTge1wuwgPatffhJ6OpnpMv_SULOgIjGmwRThw/w473-h266/boxing%20main.gif)](https://tvaccess.live/usyk-vs-fury-2-live/?v=GIT)

Who is on the Usyk v Fury 2 undercard and what is the running order?
Oleksandr Usyk v Tyson Fury 2 - WBC, WBO & WBA heavyweight titles

Serhii Bohachuk v Ishmael Davis - light-middleweight

Moses Itauma v Demsey McKean - heavyweight

Johnny Fisher v Dave Allen - heavyweight

Isaac Lowe v Lee McGregor - featherweight

Peter McGrail v Rhys Edwards - featherweight

Daniel Lapin v Dylan Colin - light-heavyweight

Andrii Novytskyi v Edgar Ramirez - heavyweight

Who are the judges for Usyk v Fury 2?
USA's Patrick Morley, Panama's Ignacio Robles and Puerto Rico's Gerardo Martinez will be the three judges at ringside.

**Comment by gbloodcaitl** [comment]
hjy

### **👉⏩🎥🅻🅸🆅🅴🔴▶️ ✅🟢 [**STREAM PLAY NOW** ▶️](https://www.onflix.online/boxing)**
.
### **👉⏩🎥🆆🅰🆃🅲🅷🔴▶️ ✅🟢 [**PLAY NOW ONLINE**](https://www.onflix.online/boxing)**
.

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://www.onflix.online/boxing)
.
.

[![werx](https://github.com/user-attachments/assets/1b1dd544-6865-4e28-8e2f-2f2b3a5cb216)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)

ngft
