### ISSUE TITLE
!!+@>[OffiCial@!!#@]*  Southlake Carroll vs Vandegrift LIVE STreams ON TV Channel 22 December

### ISSUE THREAD

**Issue by braybnix** [tidyverse/dplyr#7559]
Both Vandegrift and Southlake Carroll certainly earned their way to AT&T Stadium after thrilling semifinals last week.
The Vipers turned some heads with a 34-31 win over 2023 finalist Summer Creek. Miles Teodecki connected with Jack Rudberg for a 57-yard touchdown with eight minutes left to grab the lead, and the Vandegrift defense did the rest from there.

**[▶✔CLICK HERE TO WATCH LIVE NOW!](https://cutt.ly/xeZhAZ5y)**

Southlake Carroll needed all 48 minutes and then some. The Dragons got an extra shot at the game-winning field goal after a roughing the kicker penalty. That’s all Gavin Strange needed as he booted through the 36-yard field goal to knock off Longview 20-17.

Now, after such emotional victories, these teams need one more all-out push this Saturday at 3:00. Here’s what to watch for in the 6A Division II State Title Game.

Southlake Carroll Dragons (15-0)

Head Coach: Riley Dodge (7th season; 93-8 record)

Distance from AT&T Stadium: 21 miles

2024 Playoff Results

Bi-District: W 69-7 vs. Mansfield Legacy

Area: W 49-42 vs. Frenship

Regional Semifinals: W 42-37 vs. Hebron

Regional Final: W 56-45 vs. Guyer

State Semifinals: W 20-17 vs. Longview

Key Players and Storylines

The last time Southlake Carroll was at state, the Quinn Ewers-led Dragons came up short against Cade Klubnik’s Westlake Chaparrals.

But while Ewers and Klubnik do battle again on Saturday, Riley Dodge will be looking for his first state title as Southlake Carroll’s head coach and the Dragons’ first title in 13 years.

Expect Southlake to come out slinging it. Quarterback Angelo Renda had 3,550 passing yards and 36 touchdowns this year. There’s no question who his number one target will be either. That would be TCU commit Brock Boyd (98 catches for 1,690 yards), who is averaging over 100 yards per game with 18 touchdowns on the season.

And if Boyd isn’t there, the Dragons have had sophomores Blake Gunter (726 yards and eight touchdowns) and Brody Knowles (464 receiving yards) prove to be reliable targets as well.

The Dragons did lose running backs USC commit Riley Wormley and Baylor commit Davis Penn to season-ending injuries. However, Christian Glenn has proved he’s more than capable of carrying the load after a 132-yard performance against Longview last week.

Defensively, the Dragons lean on junior linebackers Robbie Ladd and Marcus Brouse, who are among their leading tacklers this season.

Jack VanDorselaer is a four-star commit to Tennessee at tight end, but at 6’5″ and 240 pounds, he can also get after it at defensive end. Vandegrift will have to be weary of him at all times.

Vandegrift Vipers (14-1)

Head Coach: Drew Sanders (15th season; 145-46)

Distance to AT&T Stadium: 202 miles

2024 Playoff Results

Bi-District: W 56-14 vs. Austin High

Area: W 51-0 vs. Sotomayor

Regional Semifinals: W 49-35 vs. Cibolo Steele

Regional Final: W 47-14 vs. Harlan

State Semifinals: W 34-31 vs. Summer Creek

Key Players and Storylines

Vandegrift is back in the state title game for the second time in three years. Back in 2022, DeSoto proved to be too much for the Vipers.

Now, they’re ready for another shot. They certainly showed they have the elite pedigree after their 34-31 win against Summer Creek last week.

And just like the Dragons, they’re going to let their junior quarterback have at it. Miles Teodecki has flourished in the starting role this year with 3,016 passing yards and 46 touchdowns.

If Vandegrift needs a big play, he’ll likely find either Brock Chilton (904 receiving yards and 12 touchdowns) or George Farley (838 receiving yards and 13 touchdowns). Both are averaging over 19 yards a catch, and Farley has good size too at 6’2″.

Senior running back Brendan Fournier will be key to giving the Vipers a balanced attack. He’s up to over 1,100 yards this season, and he had two touchdowns last week.

On the other side of the ball, Arizona State commit Daeshon Morgan can enforce his will in the trenches. He has 82 tackles and 14 tackles for loss this year. And while Morgan comes flying off the edge, the Vipers will rely on nose guard Ian Witt (92 tackles and 14 TFLs) to stuff anything that comes up the middle.

Adam Scott has been a playmaker at linebacker for the Vipers this year, while safety Hollister Stephens is playing his best football at the right time. He has had 35 tackles the past two weeks alone.

Final Thoughts

If you like a good aerial attack, this is the game for you.

With so much passing, turnovers could be something to watch. Both quarterbacks will need to take care of the football on Saturday and be aware of the pass rush threat the opposition presents.

From there, it’s all about getting it in the hands of their playmakers and seeing who can come up with the big plays in the big moments as both head coaches look to bring home their first state titles.

**Comment by gbloodcaitl** [comment]
hjy

### **👉⏩🎥🅻🅸🆅🅴🔴▶️ ✅🟢 [**STREAM PLAY NOW** ▶️](https://www.onflix.online/boxing)**
.
### **👉⏩🎥🆆🅰🆃🅲🅷🔴▶️ ✅🟢 [**PLAY NOW ONLINE**](https://www.onflix.online/boxing)**
.

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://www.onflix.online/boxing)
.
.

[![werx](https://github.com/user-attachments/assets/1b1dd544-6865-4e28-8e2f-2f2b3a5cb216)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://www.onflix.online/boxing)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://www.onflix.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://www.onflix.online/boxing)

ngft
