### ISSUE TITLE
Support for xts/zoo

### ISSUE THREAD

**Issue by kristang** [tidyverse/dplyr#767]
Hi,

Is there any planned support for `xts/zoo` in dplyr, or is `data.table` the preferred method for handling time-series data, as mentioned in http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html?

**Comment by randomgambit** [comment]
Hello everybody

Congrats on this superb package. Quick follow up here. Any support for xts/zoo forthcoming?

Thanks!

**Comment by madhancr** [comment]
yes, please support xts/zoo

**Comment by hadley** [comment]
Please define what supporting xts/zoo would mean.
