### ISSUE TITLE
MonetDB backend

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#8]
- DBI compliant package: http://cran.r-project.org/web/packages/MonetDB.R
- SQL reference (such as it is): http://www.monetdb.org/print/book/export/html/10
- Supports sampling: http://www.monetdb.org/print/book/export/html/5 (search for SAMPLE)

Basic setup:

```
brew install monetdb
monetdbd create monetdb
monetdbd start monetdb
monetdb create mydb
monetdb release mydb
mclient -u monetdb -d mydb
# password is monetdb
```

**Comment by edgararuiz** [comment]
Hi @hannesmuehleisen , I tried out MonetDB today and the companion R package.  From what I read in this link posted in your documentation: https://en.wikipedia.org/wiki/SQL, it looks like all MonetDB.R needs to support `dbplyr` are pointers to the appropriate MySQL translations.  For example, simply adding a pointer to `sql_translate_env()` allowed `tally()` to work:

```
library(MonetDB.R)
library(DBI)
library(dplyr)
library(dbplyr)

con <- dbConnect(MonetDB.R(), host="localhost", dbname="demo", user="monetdb", password="monetdb")

sql_translate_env.MonetDBConnection <- dbplyr:::sql_translate_env.MySQLConnection

tbl(con, "mtcars") %>%
  tally()

tbl(con, "mtcars") %>%
  group_by(am) %>%
  tally()
```
From what I read in your documentation, I think you'll need to also point the SQL Transactions related functions 

@hadley / @hannesmuehleisen - These updates could be done in either package, I'll be glad to sent over a PR if you guys think this should be done inside `dbplyr`
