### ISSUE TITLE
rename() and error - attempt to use zero-length variable name

### ISSUE THREAD

**Issue by tyokota** [tidyverse/dplyr#817]
I think this issue is solved when using select(); however, it requires that I cbind() the mutated string data (date character string converted to numeric using as.Date() in this case). Can rename() function like select() so that I do not have to cbind() later?

**Comment by bramtayl** [comment]
I got this same error in a very different context. It seems dplyr doesn't like variables with empty names.

data = data_frame(a = 2, b = 3)
names(data) = c("", "b")
data$c = data$b
#works
data %>% mutate(c = b)
#Error in mutate_impl(.data, dots) : attempt to use zero-length variable name

**Comment by sfirke** [comment]
I just ran into the same issue as @bramtayl, calling mutate on a data.frame with an empty-named variable.  I negative-selected that variable and that allowed the mutate call to run.
